### ISSUE TITLE
Add image and table fields to resource page and custom page templates in Wagtail 

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#1146]
Having identified the transition pages owned by FEC Information Division and chosen the ones to prioritize (Issue #1133 - https://github.com/18F/fec-cms/issues/1133), we have been looking at the templates in Wagtail to see which will fit the needs of the two sections we are prioritizing.

The resource page template will be most useful for our  educational outreach page needs with a small modification: The conference and webinar pages use graphics and will need an "image" field, so we would like to ask that this be added.

The reporting pages make heavy use of tables. We anticipate using the custom page template to create these pages, and would like to ask that the "custom table" field be added to that template.

**Comment by johnnyporkchops** [comment]
I would suggest the generic table and custom table blocks be added since the custom table block only works well with financial data

**Comment by AmyKort** [comment]
putting in next quarter ideas

**Comment by dorothyyeager** [comment]
Closing this issue in favor of #1916 .
