### ISSUE TITLE
Identify missing content from Candidate Guide to fill in gaps in the "Help for Candidates" section

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#1214]
There are certain portions of the Candidate Guide that have not been posted in the Candidates section at https://www.fec.gov/help-candidates-and-committees/. Candidates, consultants and FEC staff using this section have a harder time researching the missing information.

For example, there is a note on https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/contribution-limits-candidates/ that a candidate may spend unlimited personal funds. That is the basic rule of thumb; however, doing this actually can involve some complicated legal issues for a candidate that are fully explained in the Candidate Guide on pages 15 and 28-29. A separate page on the candidate as a source of receipts would help candidates, consultants and FEC staff who need to research and answer questions on this topic.

After we complete this issue, the next step will be implementation tickets for whatever needs to be added.

Steps to take:

- [x] Identify gaps in coverage in the candidate section
- [x] Determine which language in Guide to use and determine whether we will need create new page or add to existing pages as needed.

**Comment by llienfec** [comment]
Noticed gaps again when adding reporting examples to existing content pages.  We don't have a content section where we can add basics like how to report contributions from PACs or Parties.  

@dorothyyeager found Campaign Guide language that can help us out a little if we need to stick to 100% guide language.  The Guide doesn't address this directly.  Another idea would be waiting to figure out if/how we add original language or which other sources are okay to take language from.

From the awesome @dorothyyeager:
One idea might be to just add those simple sentences and link the pages from those sections. This gives you the spot for PAC and party reporting examples on the "who can give" page.

So you could say:
PACs and party committees
PACs and party committees may make contributions. See (link for PAC) and (link for party).

Then insert this language from page 89 of Guide, followed by examples:

These receipts must be itemized regardless of amount:
•     Contributions from party committees and organizations (including those that do not
qualify as political committees under the Act (Line
11(b));
•     Contributions from other political committees and organizations (including all committees
that are political committees under the Act) (Line 11(c).

**Comment by dorothyyeager** [comment]
@llienfec and I identified some places for her reporting examples but that now that we are tackling this issue, wanted to note that it's still worth working through the reporting examples posted and seeing if there are needs for new pages of content from the Candidate Guide to go with them, or if content needs to be added to existing pages.

Also on this issue, I've reached out to Information Division specialists to see if they've identified any gaps in coverage in the candidate sections while taking 800 line questions and answering emails.

**Comment by AmyKort** [comment]
Thanks!

**Comment by dorothyyeager** [comment]
From the work done to check consistency of candidate registration pages with the Guide, we will need to think about flushing the candidate and candidate committee registration pages, so am adding those two to the spreadsheet of places we've identified as having gaps. See #1982

**Comment by dorothyyeager** [comment]
With the gaps to fill identified, and language from the Guide to use located, this issue can be closed. The implementation issue for creating some new pages and filling out old ones is at #1995 .
