### ISSUE TITLE
Find an approach for archives of info across the site

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#1216]
Users have expressed a need to access not only current information (which the new FEC site does well) but historical content as well.  Currently, we haven’t thought through how we may want users to access this information or designed wagtail templates/best practices for displaying this type of info.  (This is the broader issue described in #1197 and ready for next PI)

### Completion criteria
- [ ] do some content and design thinking about old (“archived”) information
- [ ] design how to show or link to archive information on a page, what the archived landing pages should look like
- [ ] identify types of information that need archives, including all types of contribution limits, reporting deadlines
- [ ] create the archived pages according to the designs above

### Use case example
Coordinated party expenditures is an example of limits that change needing to have public access to limits and information from prior years. (#1197)

**Comment by johnnyporkchops** [comment]
We have the current contribution limits snippet in Wagtail, but I am not sure where it is being used yet. We could create additional snippets for past cont limits if it helps this process

**Comment by dorothyyeager** [comment]
Just a note to add that this was done for the coordinated party expenditure limits already. See #1749

**Comment by AmyKort** [comment]
Thanks, @dorothyyeager !

**Comment by dorothyyeager** [comment]
I had a friend in the biz recently ask me for this information for the individual contribution limits, so I made a spreadsheet while I researched it, in case it is useful for when we get to this task.

https://docs.google.com/spreadsheets/d/13swYNdFZYYune7A17hKMdt6AyzFyP_bMfuZjA9VVlFI/edit?usp=sharing

**Comment by dorothyyeager** [comment]
This should definitely remain open as in 2019 we will have to publish the inflation-adjusted limits again. The approach used for coordinated party expenditures might work - https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/coordinated-party-expenditures/coordinated-party-expenditure-limits/. It also might be good to have one dedicated page for contribution limits. Right now we have a page for each type of committee with its Guide-specific language and we have to remember to update each of those pages.
