### ISSUE TITLE
Make the related media module work for reporting examples

### ISSUE THREAD

**Issue by jameshupp** [fecgov/fec-cms#1218]
In order to give users a firm understanding of how to use FECFile for reporting, we need to present the related media that accompanies FECFile instructions in a way that makes the association between them clear.

Reporting examples often contain related instructions in PDF or video format, specifically for how to use FECFile. We have been using the related media module to surface these because it lets us use a neat layout: thumbnail, filetype, description, link; all laid out horizontally next to other related media.

The horizontal rule, combined with the very simple introduction in the preceding section, breaks up the visual continuity in a way that makes it feel like it's two separate things we're introducing. Something about the disparity between how strong that line is and how little text there is before it. However, these things are incredibly closely related, to a degree that you almost wouldn't want one without the other. Here's how that looks on an in-progress example that @llienfec has been working on:
<img width="612" alt="related-images-line" src="https://user-images.githubusercontent.com/6314097/29732219-a3bd747a-89b5-11e7-8703-a818bfc83cb8.png">

This is one of the lessons we have taken from #1170 and it seems like we should figure it out alongside #1177.

**Comment by jenniferthibault** [comment]
**Noting for future github archeology:** 
This issue has not been addressed and is still causing the same problems described above. This was closed in a batch of issues that have been iceboxed for an extended period of time.
