### ISSUE TITLE
Implement changes to feedback and recruiting tools

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-cms#1222]
To create another pathway for people to give feedback and improve the site, update the recruiting tool and feedback drawer based on strategy set in https://github.com/18F/fec-cms/issues/1190

- [x] Restyle feedback button [ 🎨 [designs](https://user-images.githubusercontent.com/11636908/29523712-e18046aa-865b-11e7-8d40-f2e41db7afe4.png)]
- [x] Restyle feedback drawer [ 🎨 [designs](https://user-images.githubusercontent.com/11636908/29523746-fa71015e-865b-11e7-9386-87f9f4d332ac.png)]
- [ ] Create and style landing page for recruiter [ 🎨 [designs](https://user-images.githubusercontent.com/12799132/29373943-c01f1cb6-827d-11e7-98a7-daa6a6e96735.jpg)]
- [ ] @laurenancona to allow recruiter tool to add form fields to recruiter page. @patphongs will work with her to fix up styles if needed.
- [x] @jameshupp to finalize content: 🔏  [Google Doc](https://docs.google.com/a/gsa.gov/document/d/1MErQxTmd49Xppbd5zaCq3c_d2CslDgy4Va93IhB1hWQ/edit?usp=sharing)

**Comment by patphongs** [comment]
@laurenancona has been making progress on the recruiter form. This is needed to embed the form to our website. 

In addition, changes to the feedback template will be done in the CMS + Webapp merge, need to take that into account for implementation.

Once these are figured out, we can start to implement the design changes

**Comment by patphongs** [comment]
CMS + Webapp merge is now complete, so I am starting to work on updating the feedback drawer this sprint.

**Comment by patphongs** [comment]
Connected to this WIP PR: https://github.com/18F/fec-cms/pull/1341

**Comment by patphongs** [comment]
Just spoke to @laurenancona today and we have a plan going forward to embed the form fields within the user testing signup landing page. She will be working on the submit code from those embedded fields.

**Comment by patphongs** [comment]
Drawer design implementation code is complete, just waiting for OPP to help with the implementation for the form fields on the user testing sign-up landing page.

**Comment by jenniferthibault** [comment]
**Noting for future github archeology:** 
This issue has not been addressed and is still causing the same problems described above. This was closed in a batch of issues that have been iceboxed for an extended period of time.
