### ISSUE TITLE
Can't click "search individual contributions" in site-wide search if hovering over text

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#1254]
@nickykrause commented on [Tue May 16 2017](https://github.com/18F/fec-testing/issues/61)

While testing [this script](https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Test-Script_2017-05-12.md), when one user entered a person's name into the site-wide search and then tried to select `search individual contributions from: [name]` in the typeahead, nothing happened. It seemed like the button was not responding.

I am able to replicate this issue on my machine by searching for a name -- nothing happens when I try to click `search individual contributions...`:
<img width="292" alt="screen shot 2017-05-16 at 10 20 44 am" src="https://cloud.githubusercontent.com/assets/1450173/26113983/b87a8b7a-3a21-11e7-8213-f1c8f18d5c86.png">

Specifically, it seems that if my mouse is over the text, then it doesn't work. If I move the mouse so that it is still within the button but NOT over the text, then the button is clickable.

---

@nickykrause commented on [Mon May 22 2017](https://github.com/18F/fec-testing/issues/61#issuecomment-303132402)

FYI: This came up again in testing last Friday

---

@jenniferthibault commented on [Thu Jul 13 2017](https://github.com/18F/fec-testing/issues/61#issuecomment-315111456)

This gets me all the time. :shakes-fist:

---

@nickykrause commented on [Thu Jul 20 2017](https://github.com/18F/fec-testing/issues/61#issuecomment-316733640)

This doesn't seem to be an issue anymore. @noahmanger -- was this actively fixed at some point, as a part of some recent release?

**Comment by AmyKort** [comment]
Is this something we still need to address?

**Comment by jenniferthibault** [comment]
I think so. There still seems like there are barriers to usability here.

When you want to select something from the "search individual contributor" field in the typeahead, and it's in the first position, it seems like only the top 1/3 of the field is an active button/link, which makes it really frustratingly hard to click that option. Screencapture:

![wohsjhyhnw](https://user-images.githubusercontent.com/11636908/32562587-07528a1e-c47d-11e7-8dbe-8e3a01006572.gif)

**Comment by AmyKort** [comment]
I think this is something we can try to address in the normal course of business during this PI.

**Comment by jenniferthibault** [comment]
**Noting for future github archeology:**
This issue has not been addressed and was closed as part of a batch of issues that have been iceboxed for an extended period of time. The problems described above still exist as of the point this issue was closed.

**Comment by AmyKort** [comment]
Thanks, @jenniferthibault . I'm going to put this into our backlog.

**Comment by PaulClark2** [comment]
This problem still exists (6/11/2019)

**Comment by rfultz** [comment]
The main site menu was in a layer higher than the search results so the mouse events across that range went to the menu bar instead of the the drop-down. Those should be fixed by PR #3250
