### ISSUE TITLE
Users forget whether AO Number format is 2012-01 or 2012-1

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#1292]
@nickykrause commented on [Fri Apr 07 2017](https://github.com/18F/fec-testing/issues/44)

While testing [this script](https://github.com/18F/fec-testing/blob/master/Testing-Scripts/Test-Script-3-31-17-AOs.md), two users commented that it would be nice to have a subtle reminder in place of whether the system requires that AOs with single digits (e.g., `AO 2012-01` vs `AO 2012-11`) should be input with a zero or not (e.g., `AO 2012-01` or `AO 2012-1`). The user suggested that some kind of subtle indicator or reminder would be helpful.

Screenshots for reference:

![image](https://cloud.githubusercontent.com/assets/1450173/24818140/e34c41d6-1ba4-11e7-9756-615b13727609.png)

![image](https://cloud.githubusercontent.com/assets/1450173/24818162/f2d5e760-1ba4-11e7-8eb9-738a7599dfb5.png)

---

@patphongs commented on [Mon Oct 02 2017](https://github.com/18F/fec-testing/issues/44#issuecomment-333617285)

There is an existing design pattern to add an example directly below the input box. Let's implement this so that we can test if users think it is useful.

![screen shot 2017-10-02 at 2 08 41 pm](https://user-images.githubusercontent.com/12799132/31092079-3d31ad50-a77b-11e7-850c-2be4695d44ff.png)

**Comment by jenniferthibault** [comment]
@patphongs the example text is exactly what I'd use here from the existing patterns 👍 ⚡️

**Comment by AmyKort** [comment]
@cptechiegal

**Comment by jenniferthibault** [comment]
**Noting for future github archeology:**
This issue has not been addressed and and was closed as part of a batch of issues that have been iceboxed for an extended period of time. The problems described above still exist as of the point this issue was closed.

@patphongs @JonellaCulmer since this came from research, is it something we'd want to move into the testing repo?

**Comment by JonellaCulmer** [comment]
@jenniferthibault That sounds good to me! Requires a small amount of design work too, but can be tracked for later in fec-testing.
cc: @patphongs

**Comment by AmyKort** [comment]
@JonellaCulmer  This seems relatively straightforward and would meet an important user need as we work to improve the AO search. Do you think we could look into implementing an MVP this PI?
