### ISSUE TITLE
Design template for Explanation and Justification (E&J) index

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-cms#1333]
@jenniferthibault commented on [Thu Oct 13 2016](https://github.com/18F/fec-style/issues/541)

Used frequently, provides historical context for regulations.

http://fec.gov/law/cfr/ej_toc.shtml

http://fec.gov/law/cfr/ej_toc_1970.shtml

---

@porta-antiporta commented on [Thu Oct 13 2016](https://github.com/18F/fec-style/issues/541#issuecomment-253563468)

@jenniferthibault @adrianwebb @nickykrause  Just a comment for consideration.  E&Js track the changes and rationale behind changes to 11 C.F.R of regulations.  

Would it make sense to look at whether E&Js should belong on the eregs viewer.

Couple things lead me to ponder this:
1. In eregs, there are related asssets that are referenced in the right hand nav: https://atf-eregs.18f.gov/478-11/2016-12100#478-11. In this particular example, rulings could be viewd as akin to AOs.  
2. eregs supports diff'ing regulations as they change over the years.  https://atf-eregs.18f.gov/diff/478-74/2016-13878/2016-12100?from_version=2016-12100

So _could_ E&Js be shown as context of related assets and diffs of 11 C.F.R over time.  Does it meet the usage pattern of the user and also, is the juice worth the squeeze?

Offhand this would seem like a lot of effort, but did want us to look wholistically when we migrate E&Js, Rulemakings; we consider whether it should be treated as part of regulations as opposed to the separate entities they are on the current fec.gov site.

---

@jenniferthibault commented on [Thu Oct 13 2016](https://github.com/18F/fec-style/issues/541#issuecomment-253625375)

@porta-antiporta that was my first instinct too! But @noahmanger and Amy Kort seemed to think that it wasn't possible, based on what they had been told earlier about eregs' capabilities?

If it IS possible, I think that's the preference, though I know it would take some design thinking to figure out how best to do it.

---

@porta-antiporta commented on [Thu Oct 13 2016](https://github.com/18F/fec-style/issues/541#issuecomment-253635026)

That _may_ be related to something I mentioned when we tried supporting _diff_ functionality on our eregs instance.  @anthonygarvan had found that the federal register was missing a lot of the XML we would like to render those diffs.

However, eregs can also parse text (not used often, so may need some dusting off).  So this is where the effort starts to grow.  We never went in and actually tried to size that effort though; it was more "hairs on the back of my neck are tingling" estimation.

**Comment by dorothyyeager** [comment]
Hey @jenniferthibault got a notification on this issue and wanted to let you know - I update those pages on the FEC transition and classic site (when they need updating) and developed the original paper index ages and ages ago. So it's definitely something I can help you with if you have historical or indexing or what does the FEC and its users do with these notices type questions.

**Comment by jenniferthibault** [comment]
Great! Thanks @dorothyyeager. The notification was likely from me moving this issue into this repo from `fec-style` but it's likely going to be in the icebox until prioritized. Excellent to have subject matter experts identified for when it's ready though, thank you!

**Comment by jenniferthibault** [comment]
Noting for future github archeology:
This issue has not been addressed and and was closed as part of a batch of issues that have been iceboxed for an extended period of time. The state described above still exist as of the point this issue was closed.

**Comment by AmyKort** [comment]
I'm going to put this into ideas for next quarter. Thanks, @jenniferthibault
