### ISSUE TITLE
Implement embedded search module onto "Enforcement" and "Audit reports" page

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-cms#1360]
Designs in #1311 | Research in https://github.com/18F/openfec-web-app/issues/2317

______

Build/modify front-end matching page design on [Enforcing federal campaign finance law](https://www.fec.gov/legal-resources/enforcement/) and [Audit reports](https://www.fec.gov/legal-resources/enforcement/audit-reports/) pages.

**Final design**
![screen shot 2017-10-24 at 7 08 49 pm](https://user-images.githubusercontent.com/11636908/31977502-3985548a-b90b-11e7-8872-162f9d055a18.png)

See https://github.com/18F/fec-cms/issues/1311#issuecomment-338838486 for placement of this module in page mockups

**Completion criteria** 
- [x] Use custom HTML blocks to restyle links as buttons for each enforcement program on the "Enforcement" page. This will be an MVP improvement to help draw the eye toward more available information and searchable systems. 
- [ ] Create audit search template block
  - Note: I've found two different approaches to this. The embedded [AO search uses a jinja template](https://github.com/18F/fec-cms/blob/develop/fec/legal/templates/legal-advisory-opinions-landing.jinja) and the embedded [MUR search uses an html template block](https://github.com/18F/fec-cms/blob/develop/fec/home/templates/blocks/mur_search.html). I'm not proficient enough to know why there are two different ways we do it, so would appreciate @xtine taking a look to clarify.
  - Interaction: Like our standard filters, the search should kick off once someone hits enter in the search field (after selecting an option from the typeahead, or entering their own search) OR after a preliminary category is chosen from the dropdown.
- [ ] Add audit search template block to Enforcement page
  - The module should show up on the wagtail editor, like the MUR search does:
  - <img width="774" alt="screen shot 2017-10-24 at 10 21 59 pm" src="https://user-images.githubusercontent.com/11636908/31977446-ee592748-b90a-11e7-8ed3-f3a02651a33b.png">
- [ ] Add audit search template block to Audit reports page
  - The module should show up on the wagtail editor

**Dependencies**
Launching this change is dependent on the audit search being moved to the new site and available/ready to use. 
- https://github.com/18F/fec-cms/issues/1304
- https://github.com/18F/openFEC-web-app/issues/2312

**Comment by jenniferthibault** [comment]
@xtine & @johnnyporkchops I think this is ready to get started, but would appreciate it if you took a look at the approach in the completion criteria. I took my best guess.

**Comment by jenniferthibault** [comment]
@PaulClark2 @AmyKort this got lost in sprint 4.2—it will need to be moved up to be in sync with when the audit search table is completed

**Comment by jenniferthibault** [comment]
**Noting for future github archeology:**
This issue has not been addressed and and was closed as part of a batch of issues that have been iceboxed for an extended period of time. 

When audit search is ready to be launched on the site, this feature needs to be implemented, as it brings in consistency in how legal resources are accessed. 
cc @AmyKort — maybe this one should stay open in the icebox, since there's still ongoing work on implementing the audit search?

**Comment by AmyKort** [comment]
I'll put this in next quarter issues. Thanks, @jenniferthibault !

**Comment by johnnyporkchops** [comment]
@JonellaCulmer , for the left search box in the mockup, it says `Candidate or committee name or id`. That mockup is based on the [data landing](https://www.fec.gov/data/) embedded search, that returns a list of search results for anything entered. 

For the embedded audit search, I don't think there is a way to search both `candidate name or id` AND `committee name or id` from the same search input. 

Some suggestions might be to:
1) have two search boxes for the left side
2) have a radio button that allows to to choose whether you are searching` candidate name or id` OR `committee name or id`
3) Pick one of the two that is more likely to be useful to users.

Or something else.

**Comment by llienfec** [comment]
I added the embedded audit search to the Enforcement page and the Audit reports page per the design in https://github.com/fecgov/fec-cms/issues/1311#issuecomment-338838486.
