### ISSUE TITLE
Confusing spacing in the results for candidate/committee searches

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#1378]
User called and was searching between two different committees with the same name.  Was confused by the spacing in the results list because it looks like details belong to the committee below the details: 

![image](https://user-images.githubusercontent.com/22914750/31965772-65406914-b8d6-11e7-946e-79b3eda0d821.png)

**Comment by jenniferthibault** [comment]
Thanks @llienfec that is super visually confusing and does not look like I expected (or remembered). Hoping it's a straightforward fix to set or adjust the margins around type styles that appear in this order.

**Comment by jenniferthibault** [comment]
**Noting for future github archeology:** 
This issue has not been addressed and and was closed as part of a batch of issues that have been iceboxed for an extended period of time. The problems described above still exist as of the point this issue was closed.

**Comment by JonellaCulmer** [comment]
@llienfec This looks like it's no longer a problem according to what we can see on the candidate and committee profiles search results page. It does have a different appearance, so I can't say with complete certainty that we're talking about the same page. Can you take a look at this again and confirm that this is fixed or not?
Screenshot from 8/21/18:
https://www.fec.gov/data/search/?search=obama
![screen shot 2018-08-21 at 2 48 14 pm](https://user-images.githubusercontent.com/31663028/44422530-67f76280-a551-11e8-9d2a-1c645f231a6a.png)

**Comment by llienfec** [comment]
Yep, looks like the results spacing was fixed when the page template changed.  It's a lot clearer which information belongs with which committee.  Here's the same search from my issue above.  Looks like this can be closed out.

![image](https://user-images.githubusercontent.com/22914750/44423501-3b911580-a554-11e8-8565-0df4e2505087.png)

**Comment by JonellaCulmer** [comment]
Excellent, thanks @llienfec. 

Closing, as this problem has been resolved.
