### ISSUE TITLE
Design content model for data descriptions and metadata

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-cms#1402]
In the designs for the new Advanced data section which integrates the downloadable data formerly found in the data catalog and FPT files, all descriptive content was pulled from the classic site. This means it was written by data experts. In order to make it more approachable to a broader range of users, we'd like to rewrite this content (which will be the next-step issue). To do so, we should start with defining a content model (that's this issue).

The content we're looking at specifically includes: 
- The descriptions found in accordion panels 
  - [Template](https://user-images.githubusercontent.com/11636908/32083129-76ac33ae-ba8e-11e7-8472-ee8ac95e398e.png)
  - 📝 [Google Doc of accordion content](https://docs.google.com/a/gsa.gov/document/d/1UldBI9T_Bhz8j-CPoCr7LViBOEYLZNtbZnH8BgMd7mk/edit?usp=sharing)
- Full content on the metadata pages
  - [Template](https://user-images.githubusercontent.com/11636908/32083169-c4bda992-ba8e-11e7-8d91-87754bc80102.png)
  - Data catalog page issue: https://github.com/18F/fec-cms/issues/1401
  - Bulk data catalog issue: https://github.com/18F/fec-cms/issues/1399
  - 📝 [Google Doc of metadata content](https://docs.google.com/a/gsa.gov/document/d/15ELHgzOIdS-x3oD3pByuhhzhSTgf6xo_boNECsvo_zI/edit?usp=sharing)

Please duplicate each content document before editing—it's being used to implement the first round of copy for the new Adv data pages

**Completion criteria:**
- [x] Use the existing copy as a research artifact to create a content model outline
- [ ] Review & get feedback on draft outline with [team members?]
- [ ] Use outline to generate content model, including proposed word counts for each type of content.

**Comment by jenniferthibault** [comment]
Made placeholder issues in #1403 and #1404 for where to go for starting to rewrite the content after the content model is ready.

**Comment by jameshupp** [comment]
After long clarifying conversation with Jen about the bigger story this fits into, I'm pulling apart the content of this to look for points of commonality and goals. Should have a first pass at the issues done before Thanksgiving. Afterward @PaulClark2 I'm going to steal what little bit of time you can make available to clearly align around goals vs structure of the content to see what makes sense for the data the metadata/content applies to, and what makes sense for the FEC as content to manage.

**Comment by jameshupp** [comment]
Draft outline here:
🔒 https://docs.google.com/document/d/1Du5aYLjZtIR7PLjV4GVVhl7dnaMiALxdXxjSVwMymlw/edit#

**Comment by jenniferthibault** [comment]
Catching myself up on in progress/ready issues around the data catalog epic, what's the status here @jameshupp ?

**Comment by AmyKort** [comment]
What's the status of this?
