### ISSUE TITLE
Research use cases for historical statistics and redesign experience

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-cms#1408]
**What we're after:**
 Understand how external people use historical statistics published by the press office,  use what we learned in research to make quick win improvements while redesigning the experience on the new fec.gov.

**Why this matters:** 
The historical statistics haven't yet been moved from transition to new fec.gov. They can be found on transition here: https://transition.fec.gov/press/campaign_finance_statistics.shtml

**Background**
As part of https://github.com/18F/openFEC-web-app/issues/2318 we mapped data resources from the old site to the new site so that all of the FEC's data is available to download and no longer hosted on Waltham.

As part of that, Christian from the Press office helped us understand that the historical statistics that summarize the data should probably we within reach of the data searches & downloads. (Note: this was a first direction, but could change based on user research) We built a blueprint for where this could fit into the Advanced Data page in [this InVision prototype](https://gsa.invisionapp.com/share/K5DYFESA8#/258343811_Advanced-Data_Historical).

**Completion criteria**

- [ ]  identify individuals for user interviews
- [ ] develop interview script or test tasks
- [ ] summarize findings
- [ ] prioritize design improvements from research
- [ ] use prioritized changes and new fec.gov site templates to redesign experience

**Comment by JonellaCulmer** [comment]
Issue moved to [fecgov/fec-testing #111](https://github.com/fecgov/fec-testing/issues/111) via [**ZenHub**](https://www.zenhub.com/)
