### ISSUE TITLE
Implement "Historical statistics" tab on data landing page

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-cms#1411]
**What we're after**
In order to complete the new designs that integrate the data catalog & bulk data to the new site, we need to make a new home for the link to "Historical statistics." Previously lived on the "[Bulk data and other sources](https://www.fec.gov/data/advanced/?tab=other)" tab. It no longer fits in the new organizational pattern set in https://github.com/18F/openFEC-web-app/issues/2318, because this tab will only be used for downloads of former FTP files.

We have a longer-term investigation planned into understanding how people use this information, which will help us move the content from transition to the new site in https://github.com/18F/fec-cms/issues/1408

This issue is for a  short-term solution that will help keep the information available.

## Designs 

🖌  [Invision Prototype](https://gsa.invisionapp.com/share/K5DYFESA8#/258343811_Advanced-Data_Historical)

![screen shot 2017-10-27 at 3 55 44 pm](https://user-images.githubusercontent.com/11636908/32122727-5d2869f6-bb2f-11e7-80f9-caaa252ab9b3.png)

**Completion criteria**
- [ ] Using the existing templates and styles, add new tab in advanced data section called `Historical statistics`
  - [ ] Add section to left-hand menu, between "Filings and reports" and "External sources"
- [ ] Add page copy: `Data tables that summarize campaign financial activity by filer type, election cycle and reporting period.`
- [ ] Add button linking to transition, text `Find statistics`, link to https://transition.fec.gov/press/campaign_finance_statistics.shtml
- [ ] Check mobile styling

**Comment by JonellaCulmer** [comment]
This work appears to be done, so closing. 

Historical statistics page: https://www.fec.gov/data/advanced/?tab=historical
