### ISSUE TITLE
"Explore all advisory opinions" button doesn't show AOs that were withdrawn

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1419]
The "Explore all advisory opinion" button ( https://www.fec.gov/data/legal/advisory-opinions/ ) defaults to final opinions and, as a result, doesn't show a little over 100 opinions that were resolved without a final opinion. One suggestion made by users is to change the language to "Explore all final opinions" or otherwise alert users to the fact that the results are filtered to final opinions.

**Comment by lbeaufort** [comment]
Moving this issue to https://github.com/fecgov/fec-testing for further research

**Comment by lbeaufort** [comment]
Issue moved to [fecgov/fec-testing #118](https://github.com/fecgov/fec-testing/issues/118) via [**ZenHub**](https://www.zenhub.com/)
