### ISSUE TITLE
Implement Committee Profile Page Changes to Add Authorized Candidate Information

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1476]
### What we're after:
Currently there isn't an easy way for users to navigate from a candidate committee page to the authorized candidate's page and multiple users have expressed how time-consuming and frustrating it is to search for a candidate and their committee. In order to address this concern, we need to add candidate information to committee pages and a pathway to candidate profile pages. For committee pages, this involves adding a card with key candidate information in the `About this committee` section, as well as adding a button below the left-nav. 

History: https://github.com/18F/fec-cms/issues/1414

### Designs:
**Updated `About this committee` section on committee profile page**
Below is a design showing what the updated page will look like after incorporating the new candidate card in the `About this committee` section. The card includes different information depending on the seat, which will be broken down below. 

This design also shows the button that would be used on the left-nav.

![screen shot 2017-11-06 at 11 30 03 am](https://user-images.githubusercontent.com/31663028/32568139-66c8ac0e-c48b-11e7-9d07-d54c68053a46.png)

**House and Presidential card examples**
In addition to the Senate example shown above, below are examples of what the cards should look like for House and Presidential candidates. Each card should include the following: 
_Senate candidates_
- candidate name with link to candidate profile page 
- office sought (ex. Candidate for Senate) |
- State |
- political party (ex. American party) 

_House candidates_
- candidate name with link to candidate profile page 
- office sought (ex. Candidate for House) |
- State - District (ex. GA-06) |
- political party (ex. Republican party)

_Presidential candidates_
- candidate(s) name with link to candidate profile page (Stein, Jill or Clinton, Hillary Rodham / Timothy Michael Kaine)
- office sought (ex. Candidate for President) |
- political party (ex. Democratic party)

![screen shot 2017-11-03 at 1 08 07 pm](https://user-images.githubusercontent.com/31663028/32568077-3b15d302-c48b-11e7-9296-87695afbeeb5.png)

**Authorizing candidate left-nav button**
This button will include the candidate name and the label "Authorizing candidate". This button should be linked as a whole to the candidate's profile page, versus hyperlinking specific text. It mirrors the button currently used on candidate profile pages. This gives users a pathway to investigate a candidate committee, then view the candidate and then explore other candidates in the same election. 
![screen shot 2017-11-06 at 11 30 42 am](https://user-images.githubusercontent.com/31663028/32568167-7a4a6a7e-c48b-11e7-9ae5-ad95eaa5fa16.png)

**Updated `About this candidate` section on the candidate profile page**
This final design shows the change in placement between the `Committees` section and the `Other documents filed` section where the `Committees` section will be placed just below the `Candidate information` section. 
![screen shot 2017-11-03 at 1 07 21 pm](https://user-images.githubusercontent.com/31663028/32568204-8b0c8194-c48b-11e7-84c2-4009d1353592.png)

### Completion criteria:
- [ ] ~Content team drafts and provides content for the top of the page~
- [x] Add [callout](https://fec-pattern-library.app.cloud.gov/components/detail/callout.html) card with candidate information to the `About this committee` page for all authorized candidate committee pages. The candidate name text should link to the applicable candidate profile pages. 
- [x] Add the [button (call-to-action basic)](https://fec-pattern-library.app.cloud.gov/components/detail/basic.html) to the left-nav to direct users back to the applicable candidate committee profile pages
- [x] Remove "Political party" line from `About this committee` section. This information, which is relevant to the candidate, will now be found in the card.
- [x] On candidate profile pages, in the `About this candidate` section, switch the `Committees` section with the `Other documents filed` section. So the order will be 1. Candidate information, 2. Committees, 3. Other documents filed

History: https://github.com/18F/fec-cms/issues/1414

**Comment by llienfec** [comment]
@rhoughfec and I had a few working sessions to come up with intro language for the top of the candidate and the committee profile pages.  We suggest __deleting the language sections__ from the tops of these two pages.  The design is really well laid out and clear, so that there's no information to add that isn't immediately addressed on the page by the design.

I ran this by @JonellaCulmer this afternoon and she was good with taking the language sections out.  If we hear about users having difficulty understanding what's on the page, we can always address this when we understand the issues they're having.

It's always a great sign when you can remove language from a page because the design is so clear.  Really great job team!  @JonellaCulmer @jenniferthibault @patphongs @rhoughfec

**Comment by patphongs** [comment]
Just found out that if I move something from the closed pipeline to any other pipeline, it automatically gets reopened.
