### ISSUE TITLE
Creating MUR filter for date opened and date closed

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-cms#1533]
@AmyKort commented on [Thu Sep 28 2017](https://github.com/18F/openFEC-web-app/issues/2314)

Users searching our MUR holdings still have difficulty searching MURs opened or closed during specific time periods. We need to add a filter option to allow users to set date opened and date closed filters for MURs.

Jen may already have much of this work completed. 

- [ ] create the filter

---

@jenniferthibault commented on [Tue Oct 03 2017](https://github.com/18F/openFEC-web-app/issues/2314#issuecomment-333975035)

 :female_detective: GitHub archeology is one of my favorite things because I get to rediscover the awesome work and thinking our teammates have already done!

Nicky documented the most up-to-date filter designs and concepts for MURs, ADRs, and Admin fines  in https://github.com/18F/openFEC-web-app/issues/1797#issuecomment-275701188 This will be a good issue to keep handy.

Pulling out the MUR filters specifically, and zooming in on the time period concepts, the question in orange was a content design question about the field label:

<img width="392" alt="screen shot 2017-10-03 at 4 49 25 pm" src="https://user-images.githubusercontent.com/11636908/31148557-0b8aedf8-a85b-11e7-8095-f9dd344abc45.png">

@xtine can you help assess if the components on the API/back end are in place for the case data & violation date concepts to work?

---

@jenniferthibault commented on [Tue Oct 10 2017](https://github.com/18F/openFEC-web-app/issues/2314#issuecomment-335472827)

Rebumping to @xtine for taking a look at the front end needs 👋 

---

@lbeaufort commented on [Tue Oct 17 2017](https://github.com/18F/openFEC-web-app/issues/2314#issuecomment-337333160)

@jenniferthibault if it's not too much work, there were two recent requests to add MUR number to the search, like the AO search: 

https://github.com/18F/FEC/issues/4583
https://github.com/18F/FEC/issues/4460

---

@AmyKort commented on [Tue Oct 17 2017](https://github.com/18F/openFEC-web-app/issues/2314#issuecomment-337342574)

I think we've had that functionality for a while, but it was difficult to find https://www.fec.gov/data/legal/search/enforcement/?search=&search_type=murs

Am I misunderstanding @jenniferthibault ? (because that has been the theme of my day) Are you suggesting we integrate the filters differently?

---

@lbeaufort commented on [Tue Oct 17 2017](https://github.com/18F/openFEC-web-app/issues/2314#issuecomment-337368182)

@AmyKort @jenniferthibault Sorry I was unclear - I think the request was to make it easier to find, or on the search landing page, similar to the AO search (below). I met a new EA today who mentioned she had recently submitted feedback, and when I was looking through the feedback I discovered two requests for MUR number search that I thought could have come from our internal users.
![image](https://user-images.githubusercontent.com/31420082/31688904-d2158752-b35b-11e7-894b-e960e3e36797.png)

---

@AmyKort commented on [Tue Oct 17 2017](https://github.com/18F/openFEC-web-app/issues/2314#issuecomment-337368997)

Super! Thanks @lbeaufort ! 

---

@jenniferthibault commented on [Tue Oct 17 2017](https://github.com/18F/openFEC-web-app/issues/2314#issuecomment-337449844)

@lbeaufort what you're looking for has already been added via https://github.com/18F/fec-cms/pull/1276 and you can take a look [on staging](https://fec-stage-proxy.app.cloud.gov/legal-resources/enforcement/). It will go out with the release. 🎉 

This issue is about adding the date opened/closed filters to the actual full filter list available in the advanced MUR search sidebar, at this link: https://www.fec.gov/data/legal/search/enforcement/?search_type=murs

And will be seen here:
<img width="1418" alt="screen shot 2017-10-17 at 11 23 11 pm" src="https://user-images.githubusercontent.com/11636908/31699675-31530a06-b392-11e7-8ff6-1f482f2ddce4.png">

This is a piece of an issue where we had all the research and designs for the full filter list finished a long time ago, (check them out in https://github.com/18F/openFEC-web-app/issues/1797#issuecomment-275701188!) but haven't had the engineering support available to implement them, so we're adding them piece by piece.

Does that clear things up am I misunderstanding and adding more confusion?

---

@jenniferthibault commented on [Tue Oct 17 2017](https://github.com/18F/openFEC-web-app/issues/2314#issuecomment-337451490)

PS: @lbeaufort this is also a good reminder using my own bad example: no matter how "urgent" the fix or how inexperienced the dev (me, in this case!) including a proper pull request description and linking the PR to existing issues filed is a core part of working in the open and documenting what/how/why we're making these changes. Thanks you for training the trainers 😄 

---

@lbeaufort commented on [Wed Oct 18 2017](https://github.com/18F/openFEC-web-app/issues/2314#issuecomment-337575429)

@jenniferthibault That is awesome, thanks!

---

@AmyKort commented on [Wed Oct 25 2017](https://github.com/18F/openFEC-web-app/issues/2314#issuecomment-339332344)

cc @johnnyporkchops  

---

@jenniferthibault commented on [Mon Oct 30 2017](https://github.com/18F/openFEC-web-app/issues/2314#issuecomment-340515058)

Thanks to @lbeaufort 's awesome demo today, it looks like 
 her pull request https://github.com/18F/openFEC/pull/2712 adds the work that makes this information available to use on the front end via a change to the endpoint. (I think, but may be misrepresenting.)

So if it's available, this is a front end implementation issue to add the feature to the MUR search filters!

**Comment by lbeaufort** [comment]
@xtine - I think the date filter on the AO search may be helpful here: https://www.fec.gov/data/legal/search/advisory-opinions/?type=advisory_opinions&ao_category=F

API MUR date fields are: 

`mur_min_open_date`
`mur_max_open_date`
`mur_min_close_date`
`mur_max_close_date`


![image](https://user-images.githubusercontent.com/31420082/34362725-00d7759a-ea44-11e7-9b0e-0f5cf881d5b5.png)

**Comment by lbeaufort** [comment]
Here, maybe? https://github.com/18F/fec-cms/blob/develop/fec/fec/static/js/legal/Filters.js

**Comment by lbeaufort** [comment]
Note: MURs aren't using react - just a form submit.

**Comment by lbeaufort** [comment]
@PaulClark2 I think this work is still important.

**Comment by lbeaufort** [comment]
We're addressing this in PI 9

**Comment by JonellaCulmer** [comment]
I've updated the filter panel to show what it would/should look like with the time periods built in. 

<img width="285" alt="Screen Shot 2019-06-13 at 4 17 20 PM" src="https://user-images.githubusercontent.com/31663028/59464564-c8b09e00-8df6-11e9-8d63-126235197ec1.png">

**Comment by lbeaufort** [comment]
Thanks @JonellaCulmer! 

Not all MURs are violations... we could take a cue from the classic site labels or the api. The api has a “case election cycles”, but I’m not sure if that always has data. For MURs we aren’t required to choose a year - we can take a look at the data. 

https://api.open.fec.gov/developers/#/legal/get_legal_search_

**Comment by JonellaCulmer** [comment]
Closing in favor of this new issue: https://github.com/fecgov/fec-cms/issues/2969
