### ISSUE TITLE
Missing Candidate Data for 2009-2010

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1541]
@JonellaCulmer commented on [Wed Oct 25 2017](https://github.com/18F/openFEC-web-app/issues/2339)

Received user feedback via email that outlined 21 candidates with missing data from 2010. 

>  I was unable to locate campaign finance records for several candidates from the 2010 elections in either the CandidateSummaryAction file from the classic FEC site or the new FEC site through the individual candidate lookup. 

can_id | can_name | can_office | can_off_state | can_off_district
-- | -- | -- | -- | --
H0CA09075 | HASIMOTO,   GERALD | H | CA | 9
H8CA12148 | MOLONEY,   MICHAEL J. | H | CA | 12
H0CA13101 | BAKER,   FOREST | H | CA | 13
H0CA14075 | CHAPMAN,   DAVE | H | CA | 14
H0CA16104 | SAHAGUN,   DANIEL | H | CA | 16
H0CA32325 | SCHMERLING,   EDWARD | H | CA | 32
H0CA33174 | ANDION,   JAMES L | H | CA | 33
H6CA34211 | MILLER,   WAYNE | H | CA | 34
H0CA38116 | VAUGHN,   ROBERT WILLIAM | H | CA | 38
H0HI01157 | DJOU,   CHARLES K | H | HI | 1
H0HI02106 | WILLOUGHBY,   JOHN WILLIAM | H | HI | 2
H0IL01111 | WARDINGLEY,   RAYMOND G | H | IL | 1
H0IL09072 | ISRAEL,   VASQUEZ | H | IL | 4
H0IL07126 | WEIMAN,   MARK M | H | IL | 7
H0NJ10158 | ALONSO,   MICHAEL J | H | NJ | 10
H0NY04099 | BECKER,   FRANCIS X JR | H | NY | 4
H0NY10054 | MUNIZ,   DIANA | H | NY | 10
H8NY11055 | CARR,   HUGH C. | H | NY | 11
H0NY16119 | DELLA   VALLE, FRANK | H | NY | 16
H0NC12108 | DORITY,   GREG | H | NC | 12
H8OH11133 | PEKAREK,   THOMAS | H | OH | 11

---

@PaulClark2 commented on [Mon Nov 20 2017](https://github.com/18F/openFEC-web-app/issues/2339#issuecomment-345801606)

@jwchumley @hcaofec can one of you take a look at this?

---

@hcaofec commented on [Wed Nov 29 2017](https://github.com/18F/openFEC-web-app/issues/2339#issuecomment-347886652)

@JonellaCulmer  is there a link to the page that is not shown correctly?

**Comment by AmyKort** [comment]
Is this still an issue?

**Comment by PaulClark2** [comment]
I'm not sure that it is. 

**F2 filed**|**F2 no committee**|**No F2 (ballot list)**
----|----|----|
H0CA16104|H0IL09072|H0CA09075
H0CA32325||H0CA13101
H0CA38116||H0CA14075
H0HI01157||H0CA33174
H0HI02106||H0IL01111
H0IL07126||H0NC12108
H0NY04099||H0NJ10158
|||H0NY10054
|||H0NY16119
|||H6CA34211
|||H8CA12148
|||H8NY11055
|||H8OH11133
