### ISSUE TITLE
Build canonical landing page for an audit report

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1543]
@jenniferthibault commented on [Mon Sep 18 2017](https://github.com/18F/openFEC-web-app/issues/2312)

Follow up to https://github.com/18F/openFEC-web-app/issues/2261
___
 
So that:
- audit reports have stable, unique, shareable URLs
- users can view quick information about the audit without needing to find the report listing in the search result stream
- users have a consistent experience when searching through and opening types of legal resources (AOs, MURs, audit reports)

Use existing canonical case page templates (like AOs and MURs) to design and build a landing page template for audit reports.

**Criteria for completion**
- [x] Design landing page template outlining interactions 
- [x] Update based on @JonellaCulmer 's usability testing
- [ ] Build front end matching page design: (when the user clicks on the audit to view it) Referencing AO/MUR canonical landing page because it’s the same template format
- [ ] Testing is scheduled for the search and landing pages

@xtine 

---

@jenniferthibault commented on [Mon Oct 30 2017](https://github.com/18F/openFEC-web-app/issues/2312#issuecomment-330350027)

This follows patterns set by AO landing pages ([example](https://www.fec.gov/data/legal/advisory-opinions/2016-23/)) and MUR landing pages ([example 1](https://www.fec.gov/data/legal/matter-under-review/7248/)) ([example 2](https://www.fec.gov/data/legal/matter-under-review/7025/))

Since we have an existing template for this interaction already used for similar legal resources, first design concepts were quick:

![screen shot 2017-10-30 at 11 03 53 am](https://user-images.githubusercontent.com/11636908/32178017-0b72c040-bd62-11e7-8f66-c7ff97670b07.png)

This concept will let us bring in the two-column summary info pattern that's in the design files but not the pattern library — it was originally conceived when we were working on the template for these canonical landing pages, and will be put to use further when we make improvements to the MUR landing pages, and when we transition the ADR and Admin fine landing pages. _Not for action now, but for reference of where/how else this pattern will exist:_
![screen shot 2017-09-18 at 4 42 40 pm](https://user-images.githubusercontent.com/11636908/30563586-4f6a7e0c-9c90-11e7-89e3-3668019c73aa.png)
![screen shot 2017-09-18 at 4 42 46 pm](https://user-images.githubusercontent.com/11636908/30563585-4f696274-9c90-11e7-912f-344fd26bd872.png)
![screen shot 2017-09-18 at 4 42 54 pm](https://user-images.githubusercontent.com/11636908/30563584-4f687ea4-9c90-11e7-8491-8a4395c43ff8.png)

---

@jenniferthibault commented on [Tue Nov 28 2017](https://github.com/18F/openFEC-web-app/issues/2312#issuecomment-347647427)

@johnnyporkchops in sprint planning today, we talked about how the Adv data page work and Audit page work were competing priorities for front end time. We decided that the Adv data work should be completed first, and so moved this task back to the next sprint. Please focus on Adv data issues this sprint instead of this task.

**Comment by llienfec** [comment]
Hi all - I received further feedback and questions from Erica in Audit based on the design mock-up of the Audit Report page posted by @jenniferthibault on Oct 30, 2017 above ^^.

1.  Documents at the bottom of the page should appear in the order they are listed in the ARSS and not in date order.  For example, the LRA is always after the IAR or DFAR, even though it happens before since it supports the IAR/DFAR.

2.  Where does the "final audit report date" come from? One of the dates in the ARSS table is the public release date and not the final audit report date, so we need to make sure the label describes the date shown.

3.  Request to capitalize "issues" in "Findings and issues."  This one we do not need to act on because it's title case when the website standard is sentence case.

cc: @JonellaCulmer

**Comment by JonellaCulmer** [comment]
@llienfec Thanks for this additional feedback. I'm looking into each of them, particularly 1 &2, so we'll hopefully have questions for the audit team when we meet with them for a demo on Thursday.
