### ISSUE TITLE
Display problem for some paper reports

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1549]
@jwchumley commented on [Fri Sep 15 2017](https://github.com/18F/openFEC-web-app/issues/2311)

There are some paper reports (24 and 48 hour notices) that are keyed in by FEC staff using the online efiling interface. The process creates an electronic image but the paper is also scanned and stored in a separate folder within the docquery system. I've asked Salient to look at the logic and confirm it for me but I think it is simply "always look in the paper folder for a pdf first. If you find it display it. If not then display the regular image"

Here is an example:
Original paper image:  http://docquery.fec.gov/pdf/PAPER/201706059055303214.pdf#navpanes=0

Generated electronic image: http://docquery.fec.gov/pdf/214/201706059055303214/201706059055303214.pdf

- [ ] is it possible to keep track of this in a table?

More to come but this is an important issue in production.

@LindsayYoung 

---

@jwchumley commented on [Mon Sep 18 2017](https://github.com/18F/openFEC-web-app/issues/2311#issuecomment-330203946)

I confirmed the logic.

if the image number exists here: http://docquery.fec.gov/pdf/PAPER/
then display it.
else display it as per usual.

**Comment by jwchumley** [comment]
The logic for the viewer works like this. It is a front code. If you go here:



C90006149
