### ISSUE TITLE
Research how to include all 2 year periods on spending/raising breakdown pages

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1550]
@jwchumley commented on [Wed Oct 25 2017](https://github.com/18F/openFEC-web-app/issues/2340)

The time period pull downs on the [spending breakdown](https://www.fec.gov/data/spending/) and [raising breakdown](https://www.fec.gov/data/raising/) pages are missing some 2-year periods. They should displayall 2-year periods back to 2007-2008 (as far back as the data supports this kind of breakdown for all the listed committee types). 

- [x] make the pulldowns for all candidate and committee options 2-year periods. Include all 2 year periods even for presidential and Senate candidates.
- [x] add 2017-2018 and make it the default
- [x] figure out why 2013-2014 is missing
- [x] Check logic to make sure future cycles are added as the default automatically

## Screenshots 
(thanks @jenniferthibault!):

![screen shot 2018-04-04 at 9 18 48 am](https://user-images.githubusercontent.com/11636908/38309940-4372d01e-37e9-11e8-8b34-ebcdd7353947.png)

![screen shot 2018-04-04 at 9 19 40 am](https://user-images.githubusercontent.com/11636908/38309978-5e3d8e48-37e9-11e8-8bab-2db82f0c2a8e.png)

**Comment by PaulClark2** [comment]
What's the status of this issue?

**Comment by jwchumley** [comment]
I think it was pretty much any committee but I thought it was already done.  Too bad I didn't include a URL. I'm not even sure which page it was but I can't find a page with the problem now. Can you? @johnnyporkchops was this done?

**Comment by lbeaufort** [comment]
@jenniferthibault thank you! It looks like it's still an issue. @jwchumley should I mark this as 5.4?

**Comment by lbeaufort** [comment]
Sorry, it looks like 2017-2018 is the default, so I updated the issue. Now it's just missing:
2013-2014 
2009-2010
2007-2008
Should it still be marked "high priority"?

**Comment by jwchumley** [comment]
Yes. 5.4 please. Thanks Jen and Laura.

**Comment by lbeaufort** [comment]
Research portion complete - see PR https://github.com/fecgov/fec-cms/pull/1958
