### ISSUE TITLE
Committee filing pages displaying more than one "Current" Form 1 (Statement of Organization)

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1554]
@lbeaufort commented on [Thu Aug 31 2017](https://github.com/18F/openFEC-web-app/issues/2285)

So that committees and the public can see the most recent version of the Form 1 (Statement of Organization), we need to update the logic to handle when a committee files multiple Form 1's as new and only show the newest as "Current Version" and the others as "Past Version."

@patphongs discovered this issue.

Example: (https://www.fec.gov/data/committee/C00639013/?tab=filings)

![8-31-2017 3-35-01 pm](https://user-images.githubusercontent.com/31420082/29941933-2965589e-8e62-11e7-9e47-56b989cdba16.jpg)

Background: Using FECFile and other 3rd party vendors, committees can amend their Statement of Organization (Form 1) by filing it as new. Then, an overnight process updates it to show as amended. As a result, there is no amendment number associated with the file that was submitted as new and now displays as amended.

Potential fix: Add to /filings/ "amendment chain" logic to handle multiple F1Ns for the same committee.  If the amendment chain logic fails (>1 current version for the same filing type - for statements of org. ) then use the most recently filed one as the current version and mark the others as past version.

- [ ] modify F1 function logic for amendments -- create special case for committees that file multiple  Form 1 news
- [ ] check F2 logic for same flaw

**Comment by lbeaufort** [comment]
Issue moved to [fecgov/openFEC #3096](https://github.com/fecgov/openFEC/issues/3096) via [**ZenHub**](https://www.zenhub.com/)
