### ISSUE TITLE
Overview of committee and candidate search enhancements

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1555]
@PaulClark2 commented on [Tue Jul 25 2017](https://github.com/18F/openFEC-web-app/issues/2220)

- [ ] enable downloads for https://www.fec.gov/data/candidates/house/
- [ ] enable downloads for https://www.fec.gov/data/candidates/senate/
- [ ] enable downloads for https://www.fec.gov/data/candidates/president/
https://github.com/18F/openFEC/issues/1946

- [ ] create committee pages to replace committee summary, leadership PACs and lobbyist/registrant PACs datasets 
- [ ] create downloads for committee pages
https://github.com/18F/openFEC-web-app/issues/2222

- [ ] create  page for unverified filers
https://github.com/18F/openFEC-web-app/issues/2252

- [ ] create downloads for unverified filers
- [ ] create  page or enhance filters for candidate disbursements

------------------------------------------------------------------------------
**Enable downloads**

_Candidate summary_

So that we can replace the candidate summary dataset, http://classic.fec.gov/data/CandidateSummary.do?format=html, we need to enable downloads for these pages:
https://www.fec.gov/data/candidates/house/
https://www.fec.gov/data/candidates/senate/
https://www.fec.gov/data/candidates/president/

**New pages**

_Committee summary_ 

So that we can replace the committee summary dataset, http://classic.fec.gov/data/CommitteeSummary.do?format=html, we need to consider how best present this information, and how best to help users find this information.

Provide download functionality.

Option:
Consider creating committee type pages similar to the candidate specific pages we have for House, Senate and President. 

This might replace the following datasets: committee summary, leadership PACs and lobbyist/registrant PACs

http://classic.fec.gov/data/CommitteeSummary.do?format=html
http://classic.fec.gov/data/Leadership.do?format=html
http://classic.fec.gov/data/Lobbyist.do?format=html

_Unverified Filers_

So that we can replace the unverified filers dataset, http://classic.fec.gov/data/UnverifiedCommittees.do?format=html, we need to determine the optimal UX for meeting the regulatory requirement while not polluting true data

Provide download functionality.

_Candidate disbursements_

So that we can replace the candidate disbursements interface, http://classic.fec.gov/data/CandidateDisbursement.do?format=html, we need consider designing a page to allow user to access downloadable file.

Options:
Design page to allow users to find and download pre-generated files
Enhance spending page to allow users to filter for candidate disbursements. We may need to provide for downloads larger than 100,000 records. 

Provide download functionality.

**Comment by jenniferthibault** [comment]
For future reference, to tie together the history here, check out this issue: https://github.com/18F/openFEC-web-app/issues/2222

(Especially helpful for designers!)
