### ISSUE TITLE
Add new pages to sitewide search indexing

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1559]
@noahmanger commented on [Fri Mar 03 2017](https://github.com/18F/openFEC-web-app/issues/1872)

While testing the site-wide search offered through the DigitalGov search, I'm seeing that search engines don't seem to be indexing our canonical pages consistently. Doing domain-limited searches in Google or DigitalGov (Bing) don't consistently return results for candidates, committees, AOs or MURS. 

I can't tell what the rhyme or reason is to why some pages seem indexed and others aren't. At first I thought it was because of pages that relied on Javascript, but there seem to be plenty of places where server-side pages somehow aren't getting crawled either.

**Comment by lbeaufort** [comment]
@patphongs
