### ISSUE TITLE
MUR search missing documents for MUR #7126

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#1606]
Hey @vrajmohan , @pkfec 

From a lawyer in OGC:

I noticed that the public file for one of my matters, MUR 7126, is incomplete on the new website, but complete on the old website.  Please see the screenshots below.  Namely, it is missing the General Counsel’s Briefs, Conciliation Agreements, and Factual and Legal Analysis (the dispositive documents in the matter).

https://www.fec.gov/data/legal/matter-under-review/7126/

![old](https://user-images.githubusercontent.com/12615919/33494998-e1022d9c-d692-11e7-8b3d-f3758c3ff709.jpg)

**Comment by vrajmohan** [comment]
Tagging @lbeaufort

**Comment by AmyKort** [comment]
cc @lbeaufort as an FYI

**Comment by lbeaufort** [comment]
I confirmed this is no longer an issue @AmyKort 
https://docs.google.com/spreadsheets/d/15jiNekVyzjNpTAk-le8034hZlewh63pPCEOWbdXOh70/edit#gid=0
