### ISSUE TITLE
Do load testing

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1611]
@noahmanger commented on [Mon Mar 13 2017](https://github.com/18F/openFEC-web-app/issues/1886)

We want to do load testing on our various apps so we're sure that they can handle the increased load that we expect from being the main fec.gov. We should do this for all of the apps:

- API
- Web app
- CMS
- eRegs (though probably much less necessary here)

---

@AmyKort commented on [Thu Nov 30 2017](https://github.com/18F/openFEC-web-app/issues/1886#issuecomment-348274936)

@vrajmohan  Is this issue still relevant?

**Comment by vrajmohan** [comment]
We have load testing for the API only. We need one for the CMS. eRegs is probably not needed.
