### ISSUE TITLE
Revisit special election candidate logic

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1612]
@noahmanger commented on [Mon Apr 17 2017](https://github.com/18F/openFEC-web-app/issues/1953)

In order to ensure that all special election edge cases show up, we should revisit the logic used for displaying candidate pages which https://github.com/18F/openFEC-web-app/pull/1945 patched just to make sure we're not forgetting anything.

---

@AmyKort commented on [Thu Nov 30 2017](https://github.com/18F/openFEC-web-app/issues/1953#issuecomment-348255318)

@lbeaufort  Is this issue still relevant?

**Comment by lbeaufort** [comment]
@AmyKort I poked around some of the AL senate candidates and found this 404 error: https://www.fec.gov/data/candidate/S8AL00308/?cycle=2017&election_full=true

Steps to reproduce: Click on candidate page https://www.fec.gov/data/candidate/S0AL00156/ and choose "2017." Not sure if this is addressed by @patphongs's [redirect fix](https://github.com/18F/fec-cms/pull/1528), but 2017 and 2018 probably shouldn't both be in the dropdown.
