### ISSUE TITLE
Visual styling/display bugs on committee reports data tables

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-cms#1622]
So that users experience a consistent and predictable layout when navigating between data tables, fix the spacing and alignment issues in the following page layouts to match other data table templates:

### [Presidential committee reports data table page](https://www.fec.gov/data/reports/presidential/?is_amended=false&data_type=processed) 

- [ ] Remove/reduce unnecessary space under page title. Title should align with export button.
<img width="1271" alt="screen shot 2017-12-06 at 11 19 26 am" src="https://user-images.githubusercontent.com/11636908/33672140-7e829542-da77-11e7-8a12-572b35eff30c.png">

### [House and Senate committee reports data table page](https://www.fec.gov/data/reports/house-senate/?is_amended=false&data_type=processed)

- [ ] Remove/reduce unnecessary space under page title. Title should align with export button.
<img width="1270" alt="screen shot 2017-12-06 at 11 19 40 am" src="https://user-images.githubusercontent.com/11636908/33672147-8328424a-da77-11e7-9035-26a76f24853b.png">

### [PAC and party committee reports data table page](https://www.fec.gov/data/reports/pac-party/?is_amended=false&two_year_transaction_period=2018&data_type=processed&min_receipt_date=01%2F01%2F2017&max_receipt_date=12%2F31%2F2018)

- [ ] Remove/reduce unnecessary space under page title. Title should align with export button.
- [ ] Filter panel should be the same width as on other pages. This one's a bigger problem because the filter is currently too narrow to use easily
<img width="1267" alt="screen shot 2017-12-06 at 11 19 51 am" src="https://user-images.githubusercontent.com/11636908/33672158-88041fc8-da77-11e7-998c-a437d9d224ce.png">

### Correct, expected layout template:

<img width="1267" alt="screen shot 2017-12-06 at 11 20 04 am" src="https://user-images.githubusercontent.com/11636908/33672175-977cff92-da77-11e7-8b82-1ca2af69afa9.png">

**Comment by llienfec** [comment]
@JonellaCulmer These appear to be fixed.  Here are the screenshots of the 3 pages.  Didn't clip the export button, but the text lines up.  Can you :eyes: and confirm before I close the issue?  Sizing differences below are b/c of the varied widths of my screencaps - not the site.

![image](https://user-images.githubusercontent.com/22914750/45056309-846ec100-b060-11e8-8d13-70f480ccad93.png)

![image](https://user-images.githubusercontent.com/22914750/45056310-8769b180-b060-11e8-8757-f0c3d05d7344.png)

![image](https://user-images.githubusercontent.com/22914750/45056316-8a64a200-b060-11e8-9f28-af1f2a97cf5c.png)

**Comment by JonellaCulmer** [comment]
@llienfec For the most part, yes I agree with you. But the page breakpoint that moves the export to another line appears to happen too soon. I'd like for this to be tweaked.
