### ISSUE TITLE
Implement new social media image

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1635]
**What we're after:**
We've updated our social media image and are introducing new ones, if they can be supported on the front end. A previous implementation of our social images were based on the page template and should maintain this if possible. Existing images for the most part will stay the same, with one exception. The "new FEC.gov" has been updated. And we are introducing 4 new images for other page templates. 

**New images here:** https://drive.google.com/drive/folders/18Mn6eIjhtK5-wxwPHCoQUpR1MecZUprI

### Related issues
https://github.com/fecgov/fec-cms/issues/2972 Decide on / design new social media image

### Completion criteria

_List action items that need to be done to complete this task. List in checklist formatting._
- [ ] Add images to applicable page templates
- [ ] Replace "the new FEC.gov" image with the updated version
- [ ] Tell FB and Twitter to refresh their URLs, per URL (after the new images are on Prod)

### Images
**Record page template**
Pages included: Advisory opinion

![Tweet_AO](https://user-images.githubusercontent.com/31663028/63110497-9be54800-bf59-11e9-862e-5edfd4c45cb8.png)

**Digest page template**
Pages included: Weekly digest

![Tweet_WD (1)](https://user-images.githubusercontent.com/31663028/63359297-7df15c00-c33a-11e9-9ab5-951c5e0df08e.png)

**Meeting page template**
Pages included: Open meeting, Public hearing, Executive session

![Tweet_OS](https://user-images.githubusercontent.com/31663028/63110537-aef81800-bf59-11e9-93f4-b328fd02be78.png)

**Press release page template**
Pages included: Press release

![Tweet_PR](https://user-images.githubusercontent.com/31663028/63110547-b3bccc00-bf59-11e9-9b6b-fd3ead8a82ae.png)

**Updated generic image**
Pages included: All other page templates not covered

![New Twitter Graphic 01](https://user-images.githubusercontent.com/31663028/63110564-b9b2ad00-bf59-11e9-993e-18e76a47ee28.jpg)

### Future work
- [ ] Explore whether new language is needed for these pages/page templates
- [ ] Make sure this is added to our pattern library

**Comment by AmyKort** [comment]
Great discussion here https://github.com/18F/fec-style/issues/670

cc @JonellaCulmer

**Comment by AmyKort** [comment]
@JonellaCulmer  What would you estimate the work for this ticket to be?

**Comment by rfultz** [comment]
Could we make these images larger, too? SproutSocial keeps an [ongoing list of current sizes](https://sproutsocial.com/insights/social-media-image-sizes-guide/), but right now Facebook likes 1200x630 and Twitter likes at least 280x150 (keep the ratio and stay under 5MB).

The image for the homepage is awfully simple and still includes "the new" above "fec.gov". The [image for the data pages](https://www.fec.gov/static/img/social/data.png) is much more interesting.

Once the image(s) is(are) created, it's simple to update it across the site.

**Comment by rfultz** [comment]
@JonellaCulmer, the site's images are currently determined by their sections. Those choices are  help-candidates-and-committees, legal-resources, about, and campaign-finance-data (or just data), and then everything else. Do these line up neatly along those lines? If so, a simple replacement would get the job done.

@patphongs if they don't align neatly, we'll need to engineer another system rather than the content_section. I'd _like_ to but it'll be a bigger lift.

**Comment by PaulClark2** [comment]
My understanding was that the images would be associated with page templates, not website sections. Any page template that doesn't have an image associated with it would get the generic FEC logo image. See above https://github.com/fecgov/fec-cms/issues/1635#issue-280620163:

**Comment by rfultz** [comment]
Alright, @PaulClark2, I'll work on the logic to make that happen.

**Comment by JonellaCulmer** [comment]
This original PR description suggests it was supposed to be by page template. https://github.com/fecgov/fec-cms/pull/1053
