### ISSUE TITLE
Senate Candidate Profile page displaying invalid image 

### ISSUE THREAD

**Issue by cptechiegal** [fecgov/fec-cms#1645]
The system displays a Flag image in the area for error messages (e.g. 404 not found).
The issue is repeatable when 2004 Election is selected.
It seems to occur when switching between the Spending and Financial pages of the Candidate Profile for Senators. 

Example: Senate Candidate, Doug Jones
https://www.fec.gov/data/candidate/S0AL00156/?tab=spending&cycle=2004&election_full=False

![Senate Candidate page- Financial Summary image issue.jpeg](https://images.zenhubusercontent.com/597914ce61b4ca3b0a75d5ec/c3522b62-05e8-497c-8810-6cecb0e33a95)

**Comment by lbeaufort** [comment]
This issue has been addressed.
