### ISSUE TITLE
Change the Elections pulldown component to include the Time Period subcomponent on the Raising and Spending pages.

### ISSUE THREAD

**Issue by cptechiegal** [fecgov/fec-cms#1647]
For the Candidate Profile pages related to Spending and Raising, the Elections pulldown component may need to include the Time Period subcomponent per Design Team.
Design Team advised that the Election pulldown menu on Spending/Raising pages is missing the sub period information:
![Candidate Raising - Issue 1647.jpeg](https://images.zenhubusercontent.com/597914ce61b4ca3b0a75d5ec/7d3d4494-2dbc-4c45-a066-7aa2504653f0)

The information should display the same Time periods sub filtering as is seen on the Financial Summary page:
![Candidate Financial Summary- Issue 1647.jpeg](https://images.zenhubusercontent.com/597914ce61b4ca3b0a75d5ec/c64e9647-fb0b-4b95-a42d-6692ccb9b675)

(Issue 1444 Changed the label text for the heading on the Elections pulldown menu from ‘Election Cycle’ to ‘Election’)

Raising and Spending pages
https://www.fec.gov/data/candidate/H8WI01024/?tab=raising
https://www.fec.gov/data/candidate/P80001571/?tab=raising
https://www.fec.gov/data/candidate/S2MA00170/?tab=raising
https://www.fec.gov/data/candidate/S2MA00170/?tab=spending

**Comment by cptechiegal** [comment]
House Candidate-Financial Summary page- shows sub period info correctly
<div class="content__section">
 <div class="cycle-select js-cycle-select">
    <label for="cycle-1" class="label cycle-select__label">Election</label>
    <select id="cycle-1" class=" js-cycle" name="cycle" data-cycle-location="query" data-duration="2">... </select>
  </div>
<div class="subcycle-select"><span class="cycle-select__label">Time period:</span>
<span class="t-block">2017–2018</span>
</div>
</div>

House Candidate - About this Candidate page - shows sub period correctly
<div class="content__section">
  <div class="cycle-select js-cycle-select">
    <label for="cycle-2" class="label cycle-select__label">Election</label>
    <select id="cycle-2" class=" js-cycle" name="cycle" data-cycle-location="query" data-duration="2">...</select>
  </div>
<div class="subcycle-select"><span class="cycle-select__label">Time period:</span>
<span class="t-block">2017–2018</span>
</div>
</div>

House Candidate-Raising page - needs sub period
<div class="content__section">
    <label for="cycle-5-cycle" class="label cycle-select__label">Election</label>
    <select id="cycle-5-cycle" class="js-cycle" name="cycle" data-cycle-location="query" data-election-full="False">...  </select>
  </div>

Technical: Add the js-subcycle-select component to the Raising and Spending pages
This may impact several macros  (jinja templates) as follows:
candidate_cycle_select
committee_cycle_select
election_cycle_select
Need tech discussion as to whether to change these macros to include the Time Period subcomponent or just refactor by reusing the cycle_select macro and eliminate the other macros.
Needs more research since it was designed into 3 separate macros for some reason originally.

Ref: fec-cms/fec/data/templates/macros/cycle-select.jinja

**Comment by PaulClark2** [comment]
I don't think we need to make this change.

**Comment by cptechiegal** [comment]
The Raising page has the election year: 2018 but should probably display as 2 year periods instead
(note: currently this Election pulldown is using cycles data)
