### ISSUE TITLE
Data landing page election selection incorrectly navigates to search results page instead of election page

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-cms#1655]
**Current behavior**
When you enter a specific race into the election search on the data landing page, and hit `Go`, you are taken to the elections search results page, where you need to then make an additional click into the election you were trying to get to. This is an unnecessary additional page in the sequence, and is not functioning as intended by the design. 

On https://www.fec.gov/data/
When I enter `Alabama` + `Senate` then click `Go`, I am brought to https://www.fec.gov/data/elections/?cycle=2018&state=AL

![iclpe6uw3g](https://user-images.githubusercontent.com/11636908/34053146-9a8a133c-e193-11e7-9965-15cd2a256ff9.gif)

**Expected behavior**
When you enter a specific race into the election search on the campaign finance data landing page, and hit `Go` you should be taken to the specific election page for the most recent year. (I believe this was previously working as intended, and regressed)

On https://www.fec.gov/data/
When I enter `Alabama` + `Senate` then click `Go`, I should be brought to https://www.fec.gov/data/elections/senate/AL/2018/

**Comment by PaulClark2** [comment]
This is no longer an interaction we support. `Senate` has been removed from the drop down. 

![image.png](https://images.zenhubusercontent.com/59563d2061b4ca3b0a72d03d/fcdf4347-3b6c-443f-af42-cf41a0404cab)
