### ISSUE TITLE
Individual contributions by size datatable should link only to P and A committees

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-cms#1656]
Amount links on "Individual contributions to candidates" section of election profile pages are incorrect

- [ ] Amount links on "Individual contributions to candidates" section of election profile pages should only go to the candidate's PCC and authorized committees (P's and A's) not include joint fundraising committees

## Background:
On the election summary pages, when you navigate from the "Contributor amount" section on the individual contributions table to the transactions behind them in the filterable data table, you will see a list of contributors to the candidate's committees.

**From:** https://www.fec.gov/data/elections/president/2012/?tab=contributions
<img width="953" alt="screen shot 2017-12-18 at 12 51 05 pm" src="https://user-images.githubusercontent.com/11636908/34120852-09e69102-e3f5-11e7-8504-e608dbbe2cc0.png">

**To:** https://www.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2012&committee_id=C00496497&committee_id=C00522540&min_date=01%2F01%2F2011&max_date=12%2F31%2F2012&min_amount=0.00&max_amount=200.00
<img width="1279" alt="screen shot 2017-12-18 at 12 51 27 pm" src="https://user-images.githubusercontent.com/11636908/34120856-0b844e00-e3f5-11e7-9d77-f9b79e25b493.png">

## Current behavior

In some instances, individual contribution data tables aren't loading any data when you  go from an election page summary table to the transactions in the full data table.

This _seems_ to happen when it's showing transactions from more than five committees.

**From:** https://www.fec.gov/data/elections/president/2012/?tab=contributions
<img width="953" alt="screen shot 2017-12-18 at 12 51 05 pm" src="https://user-images.githubusercontent.com/11636908/34120852-09e69102-e3f5-11e7-8504-e608dbbe2cc0.png">

**To:** Candidates showing more than five committees, including [Obama](https://www.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2012&committee_id=C00431445&committee_id=C00434357&committee_id=C00443317&committee_id=C00446195&committee_id=C00446435&committee_id=C00450809&committee_id=C00451393&committee_id=C00455949&committee_id=C00462176&committee_id=C00494740&committee_id=C00496992&committee_id=C00507830&committee_id=C00519694&committee_id=C00528364&committee_id=C00529842&min_date=01%2F01%2F2011&max_date=12%2F31%2F2012&min_amount=0.00&max_amount=200.00), [Romney](https://www.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2012&committee_id=C00431171&committee_id=C00493726&committee_id=C00502708&committee_id=C00505107&committee_id=C00518282&committee_id=C00518852&committee_id=C00523050&committee_id=C00528513&committee_id=C00529859&committee_id=C00532671&min_date=01%2F01%2F2011&max_date=12%2F31%2F2012&min_amount=0.00&max_amount=200.00), [Ron Paul](https://www.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2012&committee_id=C00436006&committee_id=C00437160&committee_id=C00441907&committee_id=C00448597&committee_id=C00495820&committee_id=C00507194&committee_id=C00510818&committee_id=C00511212&committee_id=C00522508&min_date=01%2F01%2F2011&max_date=12%2F31%2F2012&min_amount=0.00&max_amount=200.00). 
<img width="1278" alt="screen shot 2017-12-18 at 12 51 49 pm" src="https://user-images.githubusercontent.com/11636908/34121011-9a000ec6-e3f5-11e7-8353-840b6d5e67b0.png">

I was able to reproduce this across candidates in other offices and other elections that had more than 5 committees, however I think it's worth noting that the number 5 might be a misleading diagnosis—it could have to do with an underlying common symptom or deficiency. 

**Additionally, when you remove committees from the filter list, results display as soon as you narrow it to view 5 or fewer committees**

<img width="1275" alt="screen shot 2017-12-18 at 12 53 05 pm" src="https://user-images.githubusercontent.com/11636908/34121103-e8013960-e3f5-11e7-8a7a-d0236885e977.png">

Another strange clue is that when you uncheck committees in the filter panel, you receive a server error warning. Yet when you X out of committees in the tag list, no error message is surfaced

<img width="1278" alt="screen shot 2017-12-18 at 12 52 01 pm" src="https://user-images.githubusercontent.com/11636908/34121137-061e5978-e3f6-11e7-90fd-0553412f6e76.png">

_____

I've outlined several anomalies, but this issue probably requires grooming or research to determine the underlying cause before the fix is identified.

**Comment by JonellaCulmer** [comment]
https://github.com/fecgov/openFEC/issues/3209

**Comment by lbeaufort** [comment]
Closing in favor of https://github.com/fecgov/openFEC/issues/3209 - this is an API issue. I'll confirm these examples work with the API fix.

**Comment by lbeaufort** [comment]
After doing more research, I realized that the links on these pages are incorrect. They should only to to the candidate's PCC and authorized committees - not joint fundraising committees.
