### ISSUE TITLE
Create new SCSS for auditsearch sub-category indentation.

### ISSUE THREAD

**Issue by fec-jli** [fecgov/fec-cms#1657]
<img width="328" alt="sub-category-indent" src="https://user-images.githubusercontent.com/24395751/34121374-d0ec6640-e3f6-11e7-946e-19dbfd2c35c3.png">
<img width="208" alt="sub-category-indent-sample" src="https://user-images.githubusercontent.com/24395751/34121380-d75a837c-e3f6-11e7-96f1-2a3f0040a459.png">

**Comment by xtine** [comment]
Acceptance criteria should include adding a pattern library component.

**Comment by johnnyporkchops** [comment]
The work on this is complete, but it needs to be added to pattern library per @xtines comment above, here is the main PR for audit search Feature/new audit search page #1883 where this SCSS implementation can be seen
