### ISSUE TITLE
Committee + committee ID field incomplete for Trump/Pence's individual contributions transactions

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-cms#1658]
When navigating to the transactions for individual contributions to a candidate in an election via their committees, the committee name and ID fields automatically populate the transaction data table.

In the case of the Trump/Pence links from the 2016 presidential election page:
https://www.fec.gov/data/elections/president/2016/?tab=contributions
<img width="954" alt="screen shot 2017-12-18 at 1 26 22 pm" src="https://user-images.githubusercontent.com/11636908/34121626-bd0cb0c0-e3f7-11e7-8c0c-116962a3835c.png">

When you click any of those total numbers, you are brought to the transactions data table. On each and every instance, the committee Name/ID field is incomplete for one tag, and displays an ID number not associated with a committee name. 
`C00615674` is missing the Committee name

https://www.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2016&is_individual=true&committee_id=C00580100&committee_id=C00615674&committee_id=C00621672&min_date=01%2F01%2F2015&max_date=12%2F31%2F2016&contributor_state=NY
<img width="1278" alt="screen shot 2017-12-18 at 1 32 52 pm" src="https://user-images.githubusercontent.com/11636908/34121724-fe9dceb6-e3f7-11e7-8e82-b11d7d21975e.png">

_____

I'm describing a symptom, but am unsure of the underlying cause.

**Comment by jwchumley** [comment]
I think this  is an issue with the unverified filers list. C00615674 is on that list so it should not appear. When you click on one of the amounts in the grid it should be excluding committees in the unverified list from the query.

**Comment by PaulClark2** [comment]
Closing. We don't have a datatable that displays `Unverified filers`. We might want to to rethink the way we do this on the filings and reports page. Perhaps add a filter option for `Unverified filers`
