### ISSUE TITLE
Research Common Data Usage Issues: Navigation 1/3

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1659]
**What we're after:** FEC.gov has been experiencing problems regarding its data, including navigation to particular data sets. These problems negatively impact user confidence in our data and inevitably with the FEC's overall customer experience. While performance issues are known and have been logged, one issue in particular has also outlined other needs that prompt additional research, including navigation to data.

This issue seeks to better understand how people are using the site and the problems they’re facing when trying to find specific campaign finance data. 

**Research tasks:**
- [x]  Speak with internal FEC staff about problems expressed by users
- [x]  Review user feedback issues for common problems
- [ ]  Conduct data user interviews to identify pain points
- [ ]  Identify and organize themes
- [ ]  Discuss/mock-up solutions

This is the first of a series of research tasks from https://github.com/18F/fec-cms/issues/1505

**Comment by JonellaCulmer** [comment]
Closing, no longer relevant.
