### ISSUE TITLE
Container Outline Appearance Not Functioning Properly

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1671]
On the "Individual contributions" tab on election pages, the top container outline floats off to the left. This is can be seen on several other election pages. 

Example: https://www.fec.gov/data/elections/senate/DE/2018/?tab=contributions

<img width="1247" alt="screen shot 2017-12-21 at 3 23 16 pm" src="https://user-images.githubusercontent.com/31663028/34274281-db912b28-e665-11e7-91c1-1088e5a46f2c.png">

**Comment by jenniferthibault** [comment]
@xtine do you think this is related to the Chrome default changes we've seen and had to fix elsewhere? (Scrolling, etc)

**Comment by xtine** [comment]
Yeah this doesn't seem to be an issue when I load it on Safari.

**Comment by PaulClark2** [comment]
I cannot replicate this, so closing.
