### ISSUE TITLE
[ATO] Research updating "fullcalendar" package version

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#1672]
Gemnasium is flagging `moment` even though we updated to ver 2.19 most likely because `fullcalendar` is still using ver 2.17

Gemnasium alert: https://gemnasium.com/github.com/18F/fec-cms/alerts#alert-6732337
From @xtine: it may be flagging from `package-lock.json` because that shows the dependencies of dependencies
https://github.com/18F/fec-cms/blob/master/package-lock.json

it looks like `fullcalendar-3.3.1` uses `moment-2.17.1`

- [ ] Make sure the version of `fullcalendar` we update to is using a safe version of `moment`. Does the ^2 mean highest 2.X version?
https://github.com/fullcalendar/fullcalendar/blob/master/package.json
- [ ] Test fullcalendar locally - either update package.json with new fullcalendar, delete node modules folder, then npm install to get fresh dependencies, or just npm install fullcalendar

![image](https://user-images.githubusercontent.com/31420082/34278377-664dfc5c-e678-11e7-8a75-420115ca1681.png)

**Comment by ccostino** [comment]
For help with the package version syntax in `package.json` and `package-lock.json`, there is a [semantic versioning guide](https://docs.npmjs.com/getting-started/semantic-versioning) in NPM's documentation.

**Comment by pkfec** [comment]
Are we suggesting to upgrade moment alone under fullcalendar? Or upgrade the fullcalendar to the latest version, which is V3.8.2?

**package.json** has :

- `fullcalendar V3.3.1`
- `moment V2.19.3`

Where as **package-lock.json** has :

- `fullcalendar V3.3.1`
- `moment V2.17.1`

To be consistent with package.json, i am attempting to update the `moment V2.19.3` in package.lock.json

**Comment by lbeaufort** [comment]
@pkfec I'm sorry my completion criteria was unclear. We're looking into updating the `fullcalendar` package to a version that uses a non-compromised version of `moment`. To do this we update the `fullcalendar` version in `package.json`, delete "node modules" folder, then `npm install` to get fresh dependencies, or just `npm install fullcalendar`.

cc: @fec-jli @ccostino @patphongs

**Comment by pkfec** [comment]
Now this so clear. fullcalendar v3.4.* is the most stable version with the latest moment v2.19.3. I have tested  this in my local (calendar app, tested pages wherever there is date field)

I am running into JS errors when i tried to upgrade fullcalendar  ^3.5.1 and up. Still investigating.

**Comment by pkfec** [comment]
The JS error is happening at this line : 
https://github.com/18F/fec-cms/blob/develop/fec/fec/static/js/modules/calendar.js#L32

Spoke with @johnnyporkchops briefly and it appears that fullcalendar V3.3.1 was customized in order to get our Calendar app  working. I will check with him more on this.

cc : @patphongs and @johnnyporkchops

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by fec-jli** [comment]
it is done, can close. thanks
