### ISSUE TITLE
Research Including House Special Elections on Election Search Pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1685]
**What we're after:** Currently, within a given state, upcoming Presidential, Senate, Special Senate, and House elections are included on election search pages. However, Special House elections have been excluded. In order to help provide a complete picture of all election activity we need to include Special House elections so that ALL upcoming elections are available to data users.

Example: https://www.fec.gov/data/elections/?cycle=2018&state=AZ

In particular, the Arizona - 08 Special is not included on the list of upcoming elections and the Special General is slated for April 24, 2018. 
![screen shot 2018-01-02 at 12 00 40 pm](https://user-images.githubusercontent.com/31663028/34492207-987caf12-efb4-11e7-90e1-0a11f17af719.png)

- [ ] confirm House special election data in fecapp.trc_election table
- [ ] check election types from fecapp.trc_election table

**Comment by AmyKort** [comment]
Closed as stale
