### ISSUE TITLE
Large bulk data files fail to download in browser

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#1712]
It has been reported and confirmed that downloading large bulk data files exceeding 1 GB will fail. Example: https://www.fec.gov/files/bulk-downloads/2016/indiv16.zip

We need to investigate the cause so that normal users can download large bulk data files.

**Comment by patphongs** [comment]
@LindsayYoung Could we modify the proxy to extend the timeout for our site? Currently it's set to 30 seconds. Code is here: https://github.com/18F/fec-proxy/blob/68725568350282a4b3996850ec0977a000c3360c/nginx.conf#L23

**Comment by AmyKort** [comment]
Merged, so closing
