### ISSUE TITLE
Normal homepage banner anouncement

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#1715]
Since we have received feedback that the homepage banner has been difficult to find or notice, we need to research other possible ways to enhance the find-ability aspect of the banner. Routine Homepage banner announcements are meant to serve as a notice to the public of normal FEC activities such as meetings/events, rulemaking comments, etc.

Here is the [original design concept](https://github.com/18F/openFEC-web-app/issues/2159) for the design banner, which was implemented in a homepage 2 redesign.

<img width="1439" alt="screen shot 2018-01-23 at 12 20 58 pm" src="https://user-images.githubusercontent.com/12799132/35290321-e6d994c0-0037-11e8-8799-b9b8901459e6.png">

**Comment by dorothyyeager** [comment]
Just wanted to flag two new issues we've thought of in the Slack content channel and put in. 
#1738 #1737

**Comment by AmyKort** [comment]
Closed as stale
