### ISSUE TITLE
Improve message for off-election cycles in Puerto Rico

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#1722]
Puerto Rico doesn't have an election in 2018 - PR elects their resident commissioner every four years. Implement a more elegant answer for PR - it's the only place that doesn't have any election for some 2-year cycles.

**Completion Criteria**
- [ ] Build logic for PR since we know their elections are every four years.  
- [ ] Create content: the message for mid-term elections: @AmyKort suggests, `Elections for Resident Commissioner in Puerto Rico are held every four years, coinciding with the U.S. Presidential election.`

![image](https://user-images.githubusercontent.com/31420082/35519021-18a52b6a-04e1-11e8-8c09-431d1b92913f.png)

cc: @PaulClark2

**Comment by PaulClark2** [comment]
@AmyKort suggests, `Elections for Resident Commissioner in Puerto Rico are held every four years, coinciding with the U.S. Presidential election.`

**Comment by dorothyyeager** [comment]
Took off the content label since Amy provided some wording above that would work well. I'll reprint here:

> Elections for Resident Commissioner in Puerto Rico are held every four years, coinciding with the U.S. presidential election.

**Comment by lbeaufort** [comment]
I believe we already implement conditional messages for PA about redistributing, so this should be a pretty small lift.
