### ISSUE TITLE
Change FEC Address--WAGTAIL

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1723]
The FEC will be moving to a new office space location this spring. When that happens, we'll need to change our mailing and meeting address on the website. The work of identifying changes that must be made is complete at https://github.com/18F/fec-cms/issues/1667

**Comment by dorothyyeager** [comment]
Just adding a handy link to our handy list of what needs to be updated!

https://docs.google.com/spreadsheets/d/1xCH8wriV3Vh0eCN-1wIVhtjlltEK-BqDFJOI9nX0gvI/edit?usp=sharing

**Comment by dorothyyeager** [comment]
For the PDF files bearing the old address, those will be updated as we update them for other things.
I'll begin working on the Wagtail pages so that we're ready to go on day 1 of the new address.

**Comment by dorothyyeager** [comment]
All Wagtail and transition pages with the address have been updated. PDF copies of FEC forms and instructions and certain popular publications have also been updated to show the new FEC address. With this work done, we are ready to close this issue.
