### ISSUE TITLE
Update the Button Colors from Federal-Blue to Crimson

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1726]
**What we're after:**
In an effort to maintain pattern and styling consistency throughout the website, we need to correct the colors used on the Forms page on fec.gov. 

The cards used  at the bottom of this page need to be updated from federal blue to crimson (#631010) https://www.fec.gov/help-candidates-and-committees/forms/

<img width="753" alt="screen shot 2018-01-30 at 1 39 58 pm" src="https://user-images.githubusercontent.com/31663028/35584468-1c66ff5c-05c3-11e8-8e06-be4e5e9a3159.png">

**Comment by jenniferthibault** [comment]
@JonellaCulmer and I just talked through a little background that might be helpful for other folks too.

The logic here is that card color in the related topic section is determined by what section of the site they link to, to match the IA color coding. If it’s a link to something in the Help for Candidates and committee section, the card should be `$secondary` (crimson). If it’s linking to a data or legal page, the card should be `$primary` (federal blue).

**Comment by dorothyyeager** [comment]
While we are talking buttons, just a note that it's on the content team's Wagtail wish list that they be an option for the custom page template.
