### ISSUE TITLE
Header on Transition Links to Help with Reporting and Compliance, Not FEC.gov

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1730]
Clicking the FEC seal in the header on transition should link back to the FEC.gov homepage, but instead it is linking to the Help for Reporting and Compliance page. Also, the page says Help for Reporting and Compliance but the URL is transition.fec.gov

<img width="792" alt="screen shot 2018-01-31 at 3 14 37 pm" src="https://user-images.githubusercontent.com/31663028/35645348-8111460c-0699-11e8-9460-a73f38a9d189.png">

**Comment by patphongs** [comment]
This has been fixed. Also bonus, I updated the menus with the new design on transition also: https://transition.fec.gov/
