### ISSUE TITLE
Hover-jump on card-image containers with alternating backgrounds

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#1734]
We seemed to have overlooked fixing for the jump on the alternating background cards, like we did on primary and secondary cards. See the cards at the bottom of:
https://www.fec.gov/help-candidates-and-committees/making-disbursements/operating-expenditures-candidate/
This can be fixed by adding:
` border: 2px solid transparent;`
To the `.card--alternating-bg`  class on line 212 of _cards.scss

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by patphongs** [comment]
Yes, this was fixed in #1789 and will be in the next release
