### ISSUE TITLE
Filter panel breakpoints error: too narrow to view/use on desktop

### ISSUE THREAD

**Issue by jenniferthibault** [fecgov/fec-cms#1739]
When opening the following data tables on a normal-sized browser window, the filter panel renders at inconsistent or incorrect sizes, making it too narrow to use.
- [Presidential committee reports](https://www.fec.gov/data/reports/presidential/?is_amended=false&data_type=processed)
  - ![screen shot 2018-02-02 at 12 13 26 pm](https://user-images.githubusercontent.com/11636908/35745803-854db7d0-0812-11e8-9613-9aa07da01382.png)

- [House and Senate committee reports](https://www.fec.gov/data/reports/house-senate/?is_amended=false&data_type=processed)
  - ![screen shot 2018-02-02 at 12 11 16 pm](https://user-images.githubusercontent.com/11636908/35745694-3441cb38-0812-11e8-92e1-56b85be1caa7.png)

- [PAC and party committee reports](https://www.fec.gov/data/reports/pac-party/?is_amended=false&two_year_transaction_period=2018&data_type=processed&min_receipt_date=01%2F01%2F2017&max_receipt_date=02%2F02%2F2018)
On this one, the right-hand edge of the screen also cuts off, making me wonder if a container is incorrectly placed.
  - ![screen shot 2018-02-02 at 12 11 50 pm](https://user-images.githubusercontent.com/11636908/35745714-48eee19c-0812-11e8-9654-6459503346ca.png)

**Steps to recreate the issue**
I am using Chrome 64.0
- Start on https://www.fec.gov/data/advanced/?tab=filings
- Open each data page link

**Completion criteria**
- [ ] Identify cause of error
- [ ] Identify steps needed to repair
- [ ] Repair correct sizing

**Comment by PaulClark2** [comment]
Cannot replicate this issue using Chrome 75.0.3770.80, so closing
