### ISSUE TITLE
Research: Profile pages don't show summary data for inaugural committees

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#1745]
Not sure whether this should go in cms or open-fec. Committee profile for inaugural committees won't show financial summary data.  Try C00629584. The filings are available in the filings search. These committees file on form 13. Similar to IE only filers, with 2 line summary, total money in and total money refunded.  Non qualified, non party committee.

https://www.fec.gov/data/committee/C00629584/?cycle=2016#cash-summary

**Comment by patphongs** [comment]
@apburnes Just checking on the status of this, will you be able to complete this research by the end of this sprint?

**Comment by apburnes** [comment]
This appears to be an api bug with not finding and returning results for reports or financials for committees with **designation** `Unauthorized` and **type** `Party - Nonqualified`

Will create an issue in openFEC and add issue to check fec-cms UI after api fix.
