### ISSUE TITLE
Deploy Wagtail pages on public funding rules

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1750]
What we're after:
A wagtail page that combines the current brochures on Public Funding and the $3 Tax Checkoff. This will help move both brochures and the public funding quick answers off transition (See #1729 and #1204) and help with our one home for related content principle. 

Work to draft initial content is detailed in https://github.com/fecgov/fec-cms/issues/1748

To implement the content change, we'll
- [x] Ensure Press, OGC and Audit divisions are comfortable with the new page's design and content
- [x] Create and publish the new page in the Citizens' Section
- [x] Create a collection and upload related documents into the CMS - collection was created
- [x] Create any needed redirects and take the old content completely off the transition site.

**Comment by dorothyyeager** [comment]
In starting to set this up, there are documents to link that are on transition (and in one case, on classic). Rather than link to them there, it seems desirable to create a collection for these and upload into the CMS, so I've edited the completion criteria accordingly.

**Comment by dorothyyeager** [comment]
A note to self and @AmyKort to see how #1406 fits in with this one (I'm guessing that page should be linked on this page).

**Comment by dorothyyeager** [comment]
We have made a slight change to the text and have circulated the content and the draft page to OGC, Press and Audit.

**Comment by dorothyyeager** [comment]
Updated the title and added a step to the completion criteria since we have been working with OGC, Press and Audit who provide and update much of the related material.

**Comment by dorothyyeager** [comment]
Had a really good meeting with Press, @llienfec and @patphongs. We are going to find a new home for placing data-oriented documents and files relating to public funding (perhaps somewhere with the bulk downloads). Christian is going to review Press' page for reporters on this issue to see if we can add anything to this page from it (but they are leaning towards using this new page for the main content for press and public). We discussed the many files that are linked on this page, and overall will be keeping most of those links and adding some others (while deleting a few).

We'll send around the draft page one more time to each division next week for a final check and then will be able to move on to creating the new page and making new homes for related content.

**Comment by dorothyyeager** [comment]
We've heard back from Press so we'll go ahead and create the new page in feature so that interested parties can have one more lookover.

**Comment by dorothyyeager** [comment]
We've gotten thumbs up from Press, Audit and OGC, so work on the new page in prod- has begun.

**Comment by dorothyyeager** [comment]
I've updated links on the transition site in Quick Answers, brochures and the library to point to the new page.

We will need to remove the following pages after creating the redirect:
https://transition.fec.gov/pages/brochures/pubfund.shtml
https://classic.fec.gov/pages/brochures/pubfund.shtml
https://transition.fec.gov/pages/brochures/checkoff.shtml
https://classic.fec.gov/pages/brochures/checkoff.shtml
https://transition.fec.gov/ans/answers_public_funding.shtml
https://classic.fec.gov/ans/answers_public_funding.shtml

For now, closing this issue since the links most people would use have been updated and we will be tackling redirects in a future sprint.
