### ISSUE TITLE
Refine metadata pages

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1756]
Refine metadata content after Press and Public Records review. 

We're migrating our data catalog metadata to Wagtail. Design and content work are complete (great discussion at https://github.com/18F/fec-cms/issues/1401 )

We're migrating the bulk data metadata into Wagtail. Designs are complete and content for these pages has been created and reviewed. ( great discussion at https://github.com/18F/fec-cms/issues/1399 )

**Data catalog**
- [x] Bundled contributions: https://www.fec.gov/campaign-finance-data/lobbyist-bundled-contributions-file-description/
- [x] Committee summary: https://www.fec.gov/campaign-finance-data/committee-summary-file-description/
- [x] Leadership PACs and sponsors: https://www.fec.gov/campaign-finance-data/leadership-pacs-and-sponsors-description/
- [x] Lobbyist/registrant: https://www.fec.gov/campaign-finance-data/lobbyistregistrant-committees-file-description/
- [x] Unverified filers: https://www.fec.gov/campaign-finance-data/unverified-filers-file-description/
- [x] Candidate summary: https://www.fec.gov/campaign-finance-data/candidate-summary-file-description/
- [x] Communication costs: https://www.fec.gov/campaign-finance-data/communication-costs-file-description/
- [x] Independent expenditures: https://www.fec.gov/campaign-finance-data/independent-expenditures-file-description/
- [x] Electioneering communications: https://www.fec.gov/campaign-finance-data/electioneering-communications-file-description/
- [x] New statements of candidacy: https://www.fec.gov/campaign-finance-data/new-statements-candidacy-file-description/
- [x] New committee registrations: https://www.fec.gov/campaign-finance-data/new-committee-registrations-file-description/
~~- [ ] Committee report summary: https://www.fec.gov/campaign-finance-data/committee-report-summary-file-metadata/~~

**FTP files**
- [x] CM (committee master): https://www.fec.gov/campaign-finance-data/committee-master-file-description/
- [x] CCL (candidate-committee linkage): https://www.fec.gov/campaign-finance-data/candidate-committee-linkage-file-description/
- [x] CN (candidate master): https://www.fec.gov/campaign-finance-data/candidate-master-file-description/
- [x] OPPEXP (operating expenditures): https://www.fec.gov/campaign-finance-data/operating-expenditures-file-description/
- [x] OTH (committee-to-committee): https://www.fec.gov/campaign-finance-data/any-transaction-one-committee-another-file-description/
- [x] INDIV (individual contribuitons): https://www.fec.gov/campaign-finance-data/contributions-individuals-file-description/
- [x] PAS2 (committee-to-candidate): https://www.fec.gov/campaign-finance-data/contributions-committees-candidates-file-description/
- [x] webALL: https://www.fec.gov/campaign-finance-data/all-candidates-file-description/
- [x] webL: https://www.fec.gov/campaign-finance-data/current-campaigns-house-and-senate-file-description/
- [x] webK: https://www.fec.gov/campaign-finance-data/pac-and-party-summary-file-description/

**Reference pages**
- [x] Report type codes: https://www.fec.gov/campaign-finance-data/report-type-code-descriptions/
- [x] Committee type codes: https://www.fec.gov/campaign-finance-data/committee-type-code-descriptions/
- [x] Disbursement category codes: https://www.fec.gov/campaign-finance-data/disbursement-category-code-descriptions/
- [x] Transaction codes: https://www.fec.gov/campaign-finance-data/transaction-type-code-descriptions/
- [x] Party codes: https://www.fec.gov/campaign-finance-data/party-code-descriptions/

**Administrative fines** (already published)
- [x] Admin fines: https://www.fec.gov/legal-resources/enforcement/administrative-fines/administrative-fines-file-metadata/

**Comment by PaulClark2** [comment]
Incorporated comments from Press and Public Records
