### ISSUE TITLE
Show RQ-5 w/Form 2

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#1759]
What we're after:

In order to have clarity when looking at a candidate's forms, RQ-5  needs to be displayed with Form 2 (statements of candidacy).

This is to complete the work started in https://github.com/18F/fec-cms/issues/1252

**Comment by llienfec** [comment]
@jwchumley I think we should change the title/criteria above.  MS-Hs do show up on the Candidate pages on the website.  It looks like RQ-5s are the letter type that are not showing up on those pages.  These are letters that are sent when there's a question about what a candidate filed on his/her Statement of Candidacy (Form 2).  

If we put these documents under "Other documents filed," then we should change the section's title to "Other documents."  The changed language would match what's currently on the committee pages.

:lock: https://docs.google.com/spreadsheets/d/1YaHth4MyG-OiECQFvwDQcNqkIrYKsVsXsEaxTlzQW50/edit?usp=sharing :lock:
