### ISSUE TITLE
Press and Public Record review for metadata pages

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1775]
We're migrating our data catalog metadata to Wagtail. Design and content work are complete (great discussion at #1401 )

Once the review is complete at #1401 is closed, we'll need to give Press and Public records a chance to look at:

 Administrative fines file description
 Lobbyist bundled contributions file description
 Committee summary file description
 Communication costs file description
 Electioneering communications file description
 Independent expenditures file description
 Leadership PACs and sponsors description
 Lobbyist/registrant committees file description
 New committee registrations file description
 New statements of candidacy file description
 Unverified filers file description

We're migrating the bulk data metadata into Wagtail. Designs are complete and content for these pages has been created and reviewed. ( great discussion at #1399 )

We've completed the first round of review for these pages:

All candidates file metadata
Candidate master file metadata
Candidate-committee linkages file metadata
Current campaigns for House and Senate file metadata
Committee master file metadata
PAC and party summary file metadata
Contributions by individuals file metadata
Contributions from committees to candidates file metadata
Any transaction from one committee to another file metadata
Operating expenditures file metadata

Great discussion at https://github.com/18F/fec-cms/issues/1399

Our next step will be to ask Press and Public Records to review.

Completion criteria:
- [x]  Provide pages to reviewers in a form that will allow them to read and comment
- [x]  Incorporate feedback

**Comment by AmyKort** [comment]
cc @johnnyporkchops @dorothyyeager

**Comment by PaulClark2** [comment]
Press and Public Records will complete their review 3/20.

**Comment by PaulClark2** [comment]
Received comments from Press and Public Records.
