### ISSUE TITLE
Audit search styling and tags 

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#1777]
- [x] ImplementSCSS styles and any changes to html templates to make sub categories list indented under category as seen in below design mockup. 
- [x] Apply highlighting for chosen sub-category AND identify current current category/sub-category chosen in head of table, above filters(this is a proposed solution for MVP) --This is so that users know it is not a "filter" option but rather which category/sub-category combination is being currently searched.

Category/Sub-Category mockup (not live code screnshot):
![image](https://user-images.githubusercontent.com/5572856/36054250-5451f6c6-0dc3-11e8-8cf5-6157fac24441.png)

Related issues/PRs:
https://github.com/18F/fec-cms/issues/1304
https://github.com/18F/fec-cms/issues/1724

**Comment by JonellaCulmer** [comment]
This is done. So closing.
