### ISSUE TITLE
Candidate's principal and authorized committee styling bug

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#1780]
It appears that the candidate's principal committee is displayed as a card design and the candidate's authorized committee is a link in a bulleted list. Need to clarify what the design is supposed to be, whether or not there needs to be two cards here, one for the principal and one for the authorized. 

<img width="745" alt="screen shot 2018-02-12 at 11 15 30 am" src="https://user-images.githubusercontent.com/12799132/36106877-7ed23d3c-0fe6-11e8-989d-3b473adac821.png">

**Comment by jenniferthibault** [comment]
This is a great learning opportunity for finding an approach to trouble-shooting unexpected  interface bugs. @JonellaCulmer and I can pick this up in a sprint that has capacity

**Comment by AmyKort** [comment]
Closing in favor of https://github.com/fecgov/fec-cms/issues/1906
