### ISSUE TITLE
Synthesize and share testing results for new election summary display

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1797]
We're testing the designs for our new election summary display with users at the FEC's February conference. Our next step is to synthesize those results in order to better understand and share what we learned.

Completion criteria:
- [x] write up synthesis of testing results
- [x] read out of results in March 2 design sync
- [x] share results with team at March 19 demo

**Comment by JonellaCulmer** [comment]
Research on election summary pages is synthesized here:
**Mural.ly board:** https://app.mural.ly/t/gsa6/m/gsa6/1519665643310/94fe998bbc279c39c078d5c60abc59caa309a0c0
**Presentation:** https://docs.google.com/presentation/d/1At2jlxqJBQc9DXooIRRmk_KiLgOwG41A2J5a21DjJqQ/edit#slide=id.g2549073cbc_1_205
