### ISSUE TITLE
Calendar filters not working on homepage

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1803]
The "all filing deadlines," "all outreach" and "all legal events" filters on the homepage take users to all calendar events, rather than filtering for the specific type of event.

![image](https://user-images.githubusercontent.com/13237823/36430556-69a5eb3c-1623-11e8-8c04-82596d1f5541.png)

**Comment by patphongs** [comment]
This fix has been merged in the PR #1843. Closing...
