### ISSUE TITLE
All reporting deadlines filter on calendar not returning results

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1804]
The "all reporting deadlines" filter on the calendar should show all reporting deadlines, including mid-year, year end, etc. It's not returning any results.

Need to make sure that all of the available categories are showing with the all reporting deadline filter.

![image](https://user-images.githubusercontent.com/13237823/36430659-baffb706-1623-11e8-8082-407749ffcea9.png)
- [ ] Meet with pubrec about category 21 - why is it different this year?

**Comment by patphongs** [comment]
Reporting deadlines is call the API for `calendar_category_id=21`. That endpoint does not seem to return all reporting dates for 2018 https://api.open.fec.gov/v1/calendar-dates/?api_key=DEMO_KEY&calendar_category_id=21

We need to figure out how that endpoint is working and why 2018 reporting dates are different from all the other years.

**Comment by lbeaufort** [comment]
@patphongs it looks like for 2018 at least, category `21` is a very small subset of reporting deadlines. To search all of them, I think we need to include four categories: 

 category               | calendar_category_id   
--- | ---
 Monthly                | 26                     |
 Pre and Post-Elections | 27                     |
 Quarterly              | 25                     |
 Reporting Deadlines    | 21                     |
-----------------------------------------------

https://api.open.fec.gov/v1/calendar-dates/?page=1&max_start_date=12%2F31%2F18&api_key=DEMO_KEY&sort=-start_date&min_start_date=1%2F1%2F18&per_page=20&calendar_category_id=21&calendar_category_id=25&calendar_category_id=26&calendar_category_id=27

**Comment by johnnyporkchops** [comment]
- In previous years, It looks like Category `21`  is supposed to show Monthly, Quarterly, Mid-Year and Year-End, but NOT pre- and post-election deadlines. 
- May 2018 shows an item that belongs in ` All elections` ("Primary Election held in Indiana") when filtering on `Reporting deadlines`. But this is missing from filter for `All elections`

So clearly data has been entered incorrectly and/or not at all for `Reporting deadlines` in 2018.
Reiterating the task from above:
- [ ] Meet with pubrec about category 21 - why is it different this year ? (and why data is incorrect)

**Comment by AmyKort** [comment]
@llienfec  What would you think about our temporarily removing the "reporting deadlines" filter, just until we get the calendar data sorted out. My understanding is that the mid-year report is not a calendar event this year, so the only report we are not specifically filtering for is the year-end. As currently constructed, I'm not sure it would be clear to users that the "reporting deadlines" filter doesn't include pre- and post election reports, so it might be causing confusion anyway.

**Comment by llienfec** [comment]
@AmyKort  To me, it seems risky to show confusing or incomplete reporting deadline information.  It seems safer to take down the filter, fix the logic, and put something up that makes a lot of sense to users and internal stakeholders.  I don't have a lot of background with what's going on in this issue, but I think it makes sense to take it down and work on it.

**Comment by AmyKort** [comment]
Closing in favor of https://github.com/fecgov/fec-cms/issues/1981
