### ISSUE TITLE
green check-icons not showing up for "Current version" reports

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#1815]
@johnnyporkchops commented on [Wed Feb 21 2018](https://github.com/18F/fec-pattern-library/issues/53)

The green check icon that is conditionally added to some Reports datatables for" Current version" reports is not showing up. [example page](https://www.fec.gov/data/reports/house-senate/?is_amended=false&data_type=processed).  **See screenshot below of local fix.**

`<i class="icon-circle--check-outline--inline--left"></i>Current version... `

I noticed when adding this to an election page (as a test) in the inspector it does show up, getting its style from the compiled `elections.css` .
This was fixed locally by adding `@import 'common';` to  [datatables.scss](https://github.com/18F/fec-cms/blob/develop/fec/fec/static/scss/datatables.scss)

Comparing [static/scss/elections.scss](https://github.com/18F/fec-cms/blob/develop/fec/fec/static/scss/elections.scss) with [/static/scss/datatables.scss](https://github.com/18F/fec-cms/blob/develop/fec/fec/static/scss/datatables.scss) shows that datatables.scss is missing `@import 'common';` I assume this is the fix, but not being as familiar with the CSS as @jenniferthibault, I would like her or @patphongs to take a look too.

**Fixed locally:**
![missing_check_icon1](https://user-images.githubusercontent.com/5572856/36519993-8f62a2ae-175c-11e8-954d-222a87834d6a.jpg)

**Comment by jenniferthibault** [comment]
Thanks for flagging this! I wish I knew, but off the top of my head, I'm not familiar with what we have to import into the stylesheets. Maybe Pat knows :fingers-crossed:

**Comment by johnnyporkchops** [comment]
`@import 'common';` imports common.scss which has`@import 'global-common';`, so it could be that`@import 'global';` can be removed, but I have not researched how that concatenated yet.

**Comment by patphongs** [comment]
PR merged, closing
