### ISSUE TITLE
Upgrade Docker Buildpack for Circle Builds

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#1824]
We recently noticed this message in the build of fec-cms: **WARNING** A newer version of python is available in this buildpack. Please adjust your app to use version 3.5.5 instead of version 3.5.4 as soon as possible. Old versions of python are only provided to assist in migrating to newer versions.

In the circleci config, we need to update the config to use 

`- image: circleci/python:3.5.5-jessie-node`

We are using docker images from here: https://github.com/CircleCI-Public/circleci-dockerfiles/tree/master/python/images 

Also we can update runtime.txt to `3.5.x` to be consistent with our docker builds. The carrot will make sure that we are to the latest python version within 3.5

**Comment by AmyKort** [comment]
resolved
