### ISSUE TITLE
Site search doesn't show up in mobile/collapsed menus

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#1827]
It looks like site search doesn't show up for users that see the collapsed (burger) menu.  

I started to do some initial research about whether this was an intentional decision or if we intended to provide site search to mobile/collapsed menu users and it was broken/lost along the way.  The great @jenniferthibault helped a ton and found this issue: Design site search in header https://github.com/18F/fec-cms/issues/935#issuecomment-293567899 that discusses we did intend to provide site search in the collapsed menus and shows designs for these.

No PR is linked in the issue and I conducted a cursory search for PRs from about the same time frame. I haven't found anything yet.

We have a good argument to take a look at this sometime given that 1) UX research in AZ (and past research) shows that users rely on the site search and 2) we've striven to provide responsive design/parity for desktop and mobile users.  

We need to decide:
- Is site search something we want to provide when people see the collapsed menu?  
- Is it worth continuing to research this to see what happened?  What's the timing/priority if yes?  

### Previous designs:
Again, thanks @jenniferthibault :tada: 
![screen shot 2018-03-02 at 3 50 07 pm](https://user-images.githubusercontent.com/22914750/36922976-bb3b26a8-1e37-11e8-9827-d423f884a263.png)

**Comment by jenniferthibault** [comment]
To Lauren's first question, 
> Is site search something we want to provide when people see the collapsed menu?

Gor GitHub forensics, tying in an older issues Lauren & I found while looking into this. There was early research indicating some users were expecting search on mobile:

#342  - [User stated expectation preference for search-first navigation on mobile](https://github.com/fecgov/fec-cms/issues/342)

**Comment by llienfec** [comment]
Updated link for the original issues: https://github.com/fecgov/fec-cms/issues/935#issuecomment-293567899

**Comment by llienfec** [comment]
Also - see issue about adding landing page links to the mobile menu:
#2036

**Comment by AmyKort** [comment]
closing in favor of https://github.com/fecgov/fec-cms/issues/2083
