### ISSUE TITLE
Migrate IG page to Wagtail--Design phase

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1828]
The Office of Inspector General provides a variety of resources on it's legacy webpage: https://transition.fec.gov/fecig/fecig.shtml As a first step toward migrating this content to the CMS, we'll need to determine the best way to make the various resources easy to find and sort. We're planning to provide the IG reports in a feed, similar to https://www.fec.gov/about/reports-about-fec/foia-reports/ , but we'll need to decide how to present other information, such as contact information and links about he law. This page https://www.fec.gov/freedom-information-act/ might provide a starting point for our thinking.
- [x] review existing IG report page feed design to see how the problem was initially designed
- [x] meet with IG about what is possible
- [x] update based on OIG team feedback
- [ ] update bad names for some OIG reports, here: https://github.com/fecgov/fec-cms/issues/2215

@AmyKort is the person to ask for history on these changes and on this work

**Comment by JonellaCulmer** [comment]
We've shared the first drafts of the IG pages in wagtail with OIG. So far so good. Waiting on edits from their team to see if there are any final edits before implementation. 

@AmyKort We can probably close this issue and open and open a final implementation ticket to include work such as updating the page based on OIG edits and moving off feature to production.

**Comment by JonellaCulmer** [comment]
After chatting with @AmyKort we're going to leave this issue open and move to `Blocked` while we wait for edits from OIG.

**Comment by JonellaCulmer** [comment]
Additional work related to the IG pages is in this issue: https://github.com/fecgov/fec-cms/issues/2215

**Comment by JonellaCulmer** [comment]
Closing this ticket, in favor of this final work that needs to be completed: https://github.com/fecgov/fec-cms/issues/2215
