### ISSUE TITLE
Design Call to Action for Contact Your Analyst

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1829]
Usability testing suggests that users have a hard time finding and using the Find Your Analyst lookup. https://www.fec.gov/help-candidates-and-committees/question-rad/ We'll use what we've learned from users to design a more intuitive path to this resource.

### Completion criteria
- [x] Review UX research findings regarding if and how users find the RAD form, especially [#98](https://github.com/fecgov/fec-testing/issues/98) in testing repo
- [x] Look at designs in the pattern library to see we already have to see if anything can be used/repurposed
- [ ] ID places where call to action makes the most sense (where to place it) (design + content)
- [ ] Make mock ups
- [ ] Discuss preliminary mock ups in design sync
- [ ] Make rest of tickets needed to finish the work (implement)

**Comment by llienfec** [comment]
A big thanks to @JonellaCulmer for pairing on the completion criteria above

**Comment by JonellaCulmer** [comment]
We have a meeting scheduled this Wednesday to consider the menu redesign as the first step to improving traffic to the Contact your analyst form. 

![mega-menu_live_h4cc](https://user-images.githubusercontent.com/31663028/38197631-44468a82-3657-11e8-8f09-a8bf7c2d4dd0.png)

**Comment by JonellaCulmer** [comment]
Through a pairing with the content and design teams, we've opted to move forward with the link on the menu (mock-up in above comment), as a good first step to improving traffic to the Contact your analyst feature. 

Updated mock-up can be found in #1862.
