### ISSUE TITLE
Implement new SERS supplemental page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#1832]
What we're after:
The SERS supplemental information page at https://classic.fec.gov/pages/sers_nic_note.htm provides information and an index of the FEC's different rulemaking projects. It is helpful for locating the REG number to use when searching SERS for rulemaking documents.

As part of #1728, it has been identified as a page that is not on transition. After we work with OGC Policy to update the content in #1831 , this issue is to implement a new page in Wagtail (as a child page of the regulations page) in order to ensure this information is on fec.gov's current site.

Completion criteria:
- [x] Set up new page with content drafted in #1831 and additional edits requested by OGC Policy
- [x] Add links to new page on SERS and any other appropriate place - Done for Wagtail; Requested for SERS
- [x] Create a redirect for the old page.

**Comment by dorothyyeager** [comment]
Having seen a draft of the page, OGC might have some additional edits. Updating the completion criteria to reflect that.

**Comment by dorothyyeager** [comment]
On hold while OGC is reviewing some cuts to the "'recently updated rulemakings" portion of the page.

**Comment by dorothyyeager** [comment]
OGC has approved the final content to go on to the page, so now on to making the page ready to go live!

**Comment by dorothyyeager** [comment]
The new page is live at https://www.fec.gov/legal-resources/regulations/sers-supplemental-information/. I've sent a note to Jennie Boyt to request that our contractors who update the links on http://sers.fec.gov/fosers/ change out the link that now points to the supplemental page on classic.

**Comment by dorothyyeager** [comment]
The link at https://www.fec.gov/legal-resources/regulations/#search-rulemakings to the supplemental page has been updated to point to the new page.

**Comment by AmyKort** [comment]
closed to soon!

**Comment by dorothyyeager** [comment]
We will need to request that Salient do the change out of the bad and outdated links on the SERS search page. A ticket for this has been put in at #1929 so will close out this issue as the work on it that the FEC staff could do is complete.
