### ISSUE TITLE
Design and plan Ethnio interaction/pop-up method

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#1833]
Design and plan Ethnio interaction/pop-up method

- [x] Look in Ethnio to see what types of popup interactions exist
- [x] design and plan what interaction will look like on the site.

**Comment by JonellaCulmer** [comment]
Ethnio's web intercepts give us a lot of control over the design, appearance, and placement of the feedback pop-up. There are a wide variety of pop-ups and each can be customized in different ways. We are not bound to one pop-up type and can change it as often as we see fit. 

Using our colors and styles as a guide, below is a mock-up of what we can do with ethn.io web intercept. We are somewhat limited to the colors, as their color palette is not extensive enough to accommodate our exact color scheme, but we can get close. 

<img width="1419" alt="screen shot 2018-05-08 at 1 27 36 pm" src="https://user-images.githubusercontent.com/31663028/39772580-9b11248e-52c3-11e8-9efc-55969393e3cd.png">

This is a screenshot of the multi-page web intercept theme. This theme is locked to the bottom, but can be implemented on a left-offset, which is what is shown in the mock-up above. 

Thoughts?
cc: @patphongs

**Comment by patphongs** [comment]
@JonellaCulmer this looks pretty good. My question though is how this would perform on mobile? Will the ethnio pop up block the view of the aqua feedback drawer button? Also when someone clicks on the feedback button and the drawer pops up, would the ethnio pop up overlay on top of the drawer or below (will have to check which one has the higher z-index which is CSS speak for which one will come to the forefront). This is a great start though, maybe we can play around with it in feature to get a better answer to these questions

**Comment by JonellaCulmer** [comment]
@patphongs Great questions. I can only see a very general preview of how it would appear, but ethn.io's web intercepts are supported for mobile. Would love to pair with you to play with in on feature to see what we can do to accommodate both the feedback drawer and the pop-up. 

It is important to note that users will only see each pop-up/intercept once because of cookies unless we turn those off. So that would help against repeat interference unless we change intercepts.

**Comment by JonellaCulmer** [comment]
We also have the option to create a link to take users to an ethn.io page to answer questions or sign up for user testing in the future. We already have a mock-up for how that might work. If we go that route, we can avoid the pop-up altogether. This would of course take people to another website to complete sign-up. We can talk through that as well when we pair through and discuss the mobile implications. 

<img width="380" alt="screen shot 2018-05-09 at 8 15 44 am" src="https://user-images.githubusercontent.com/31663028/39814155-391814a6-5361-11e8-8b08-03bcba9e3833.png">

**Comment by JonellaCulmer** [comment]
While testing ethnio on transition, we came across a weird error. 

Here's notes from @patphongs in slack about it: 
> We’re getting a weird error when trying to test ethnio on our transition site: `The SSL certificate used to load resources from https://ethn.io will be distrusted in M70. Once distrusted, users will be prevented from loading these resources. See https://g.co/chrome/symantecpkicerts for more information.`
> It’s complaining about our certs. We get this error on classic as well though https://classic.fec.gov/. And the ethnio screener still works
We attempted to put it on this page: https://transition.fec.gov/law/policy.shtml. You’ll see a pop up in the lower left about participating in feedback session. Clicking the `Next` button just opens a new about:blank window. Not really sure why this is happening.
> But just tested the original ethnio screener on transition and that seemed to work. Probably just have to play around with the settings…

I've put in a request with ethnio to see if they have any guidance regarding this error.

Until we can resolve this error, I'd like to move this issue out of the production track. If we cannot get a pop-up to work on our site, we may need to explore alternative means. 

If we'd like to resolve this quickly, my recommendation would be to implement the larger feedback form, incorporating a link to take you to ethnio and sign-up for testing. 

Thoughts @patphongs?

**Comment by JonellaCulmer** [comment]
I heard back from Ethnio about the error. 
> We are upgrading the cert will in advance of Chrome 70, probably within 24hrs.

**Comment by AmyKort** [comment]
What's the status of this issue?

**Comment by JonellaCulmer** [comment]
We have opted to implement a link into a modified feedback drawer for this interaction. 

**Mock-up:** 
<img width="380" alt="screen shot 2018-05-09 at 8 15 44 am" src="https://user-images.githubusercontent.com/31663028/39814155-391814a6-5361-11e8-8b08-03bcba9e3833.png">

**This work is being completed here: https://github.com/fecgov/fec-cms/issues/1876**
