### ISSUE TITLE
Transfer fec-cms repo to FEC

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1836]
We need to transfer the fec-cms repo from 18F to fec.gov.
- [x] delete fec's current fec-cms fork
- [x] set up circle - bring over env vars
- [x] set up gemnasium alerts
- [x] update fec-pattern-library package dependency after the fec-cms repo is moved https://github.com/fecgov/fec-pattern-library/issues/83
- [x] Lindsay makes a copy for 18F's records
- [x] dev's are informed of how to change the remote origin to `fecgov` org:
```git remote set-url origin git@github.com:fecgov/fec-cms.git```

More information at https://github.com/fecgov/fec-transition/issues/155

**Comment by lbeaufort** [comment]
Great job @patphongs!
