### ISSUE TITLE
USAJobs API not returning 'WhoMayApply'

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#1839]
**Response from vendor_help@usajobs.gov regarding the first posting that did not return WhoMayApply:**
_This job is being posted with GOVT_WhoMayApply set to 15511.
We have looked into this and have confirmed it is a bug that we will fix in a future release of USAJOBS._
_Also a note on WhoMayApply. In the coming months we will be updating the documentation on developer.usajobs.gov to include information on the new HiringPath field that will be replacing the WhoMayApply field in future._

I will continue to followup on this and update issue with any developments. We might want to  consider removing this field from the /careers page:
https://www.fec.gov/about/careers/

(Also inquiring into wether the six digit code mentioned in the response may be an interim way the determine the WhoMayApply value)

**Comment by rhoughfec** [comment]
Thanks for flagging this @johnnyporkchops I had noticed this the other day. Looping in @AmyKort so we can determine if we need to take action or just wait for the bug fix from USAJOBS.

**Comment by AmyKort** [comment]
I would suggest removing the field from the page.

**Comment by johnnyporkchops** [comment]
I will map hiring path abbreviation(s) listed for each job to the corresponding description available at https://data.usajobs.gov/api/codelist/hiringpaths and render to a field titled `Open to` on the /Carreers page

**Comment by AmyKort** [comment]
Merged,so closing.
