### ISSUE TITLE
VA District 10 candidates misidentified as VA District 1 candidates

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1845]
It looks like we have two House district race pages labeled VA 1. This one, which is correct https://www.fec.gov/data/elections/house/VA/01/2018/ and this one, which actually shows District 10 candidates https://www.fec.gov/data/elections/house/VA/10/2018/ . 

District 10 candidates are mistakenly identified as District 1 candidates in the "About this Candidate" page. For example, Barbara Comstock shows incorrectly as a District 1 candidate here (https://www.fec.gov/data/candidate/H4VA10089/?tab=about-candidate) when she is the incumbent in District 10. 

![image](https://user-images.githubusercontent.com/13237823/37169669-878b10cc-22d6-11e8-8747-ee032c26115c.png)

However the same page also correctly identifies her as a candidate in District 1

![image](https://user-images.githubusercontent.com/13237823/37169707-a6aaa788-22d6-11e8-9aca-7d04b7ec9198.png)

**Comment by lbeaufort** [comment]
Addressed by https://github.com/fecgov/fec-cms/pull/1850
