### ISSUE TITLE
Hardcoded changes for FEC address

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1848]
When we change the FEC address on the contact page https://github.com/18f/fec-cms/issues/1723, we should also make a few changes to the office descriptions.

- [x] Information Division description should read "Including help with campaign finance law, educational materials or registration and reporting forms"
- [x]  Press Office description should read "Including press queries and inquiries about Commission meetings"
- [x] Change mailing address to "1050 First Street, NE"

We also need to:

- [x] Change the address on the bottom banner to 1050 First Street, NE (three versions of the banner)

This will need a hotfix on Monday the 19th.

**Comment by dorothyyeager** [comment]
Just wanted to leave the spreadsheet of places needing the address change here too, in case there are other hard-coded pages that need it.

https://docs.google.com/spreadsheets/d/1xCH8wriV3Vh0eCN-1wIVhtjlltEK-BqDFJOI9nX0gvI/edit#gid=0

**Comment by patphongs** [comment]
Transition site address changes have been completed. 

Along with updating the transition footer, I did a replacement for 4 different variations of our old address below. To help save time with manual updates in the transition content pages.

```999 E Street, N.W.
999 E Street, Northwest
999 E Street, NW
999 E Street NW```

This does NOT account for any Room numbers that need to be updated. And it’s possible some other pattern variations were missed, but my hope is that it covered the majority.

This resulted in 139 HTM, HTML, and SHTML files being updated.

I cross checked with the 31 identified files in the attached spreadsheet to this ticket and it seems to have replaced all of those too.

**Comment by lbeaufort** [comment]
Deployed, thanks @johnnyporkchops
