### ISSUE TITLE
Need to inventory Press Office pages

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#1849]
**What we're after:**
In tackling other issues (see #1472, #1305, #1310, #1728, and #1729 for example), and answering emails to the webmanager, it's become apparent that there are a lot of Press Office pages that may be out of date or duplicate each other, and these pages are spread out over the classic, transition and current fec.gov sites. 

In order to identify the scope of the problem, we need to first complete the inventory of press office pages. Inventory of the classic and transition sites that are press office-based was begun in #1472 but not finished due to the sheer number of pages. 

Completion criteria: 
- [x] Finish the inventory of the classic and transition sites for the Press Office
- [x] Review the current pages for the Press Office for currency and duplication (or their ability to replace something on the classic or transition site)

**Comment by llienfec** [comment]
This inventory was done alongside the larger site inventory.  Closing issue.
