### ISSUE TITLE
mega__cards shifting content in mega menu for campaign finance

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#1853]
This can be fixed by changing line 83 of components/_mega-menu.scss from 1px to 2px

```  .mega__card {
 border: 1px solid $inverse;
 margin-bottom: u(1.5rem);
```

![mega-jump](https://user-images.githubusercontent.com/5572856/37229049-c3d393da-23b0-11e8-91bf-dff33d876e6a.gif)

**Comment by JonellaCulmer** [comment]
This work is no longer relevant. Closing.
