### ISSUE TITLE
Feedback tool redesign

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#1854]
Working off an existing ticket #1222 to redesign the feedback tool and implement it. Part of the design comp is below, we discussed and would like to remove the "sign-up" top portion of the design for now as we are going to implement ethnio in the near future.

@JonellaCulmer When you have time, can you please modify the below designs to reflect what we talked about.

![Feedback-tool-image](https://user-images.githubusercontent.com/12799132/31621371-8ae28dd4-b267-11e7-8ddc-6c79e1a9248d.png)

**Comment by JonellaCulmer** [comment]
This will be updated to retain the new visual appearance of the feedback drawer, but will remove the language, "Test new features...new website features," and the sign-up button. 

The drawer will essentially retain the functionality that is currently live on the site (as of 3/20/18) with visual adjustments.

**Comment by JonellaCulmer** [comment]
Below is an updated mock-up of the feedback tool. It retains the new visual update and remove the "Test new features..." section at the top. 

**Design:**
![feedback_drawer](https://user-images.githubusercontent.com/31663028/37729973-cfeaea66-2d14-11e8-9313-bb217d0ca41b.png)

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issue: https://github.com/fecgov/fec-cms/issues/1876
