### ISSUE TITLE
Content review and data review of new Advance Data Pages

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#1863]
Users need to see all registered candidates when they search in Advanced Data pages, and not just those that have reported financial activity. Users also need to clearly understand the information they're looking at. 

In the current design, it appears to be implied that the Presidential candidates, Senate candidates, and House of Representatives candidates is a subset of All candidates, but this is not the case. cc @JonellaCulmer 

<img width="730" alt="screen shot 2018-03-14 at 1 52 52 pm" src="https://user-images.githubusercontent.com/12799132/37436880-9cd3cac0-27c0-11e8-93a9-62057545bffa.png">

This is that candidate's committee page with no financial data: https://www.fec.gov/data/candidate/H8ME02193/?tab=summary

Language should be consistent with solution we've designed for election pages.

# What's the problem?

The "All candidates" link implies that you are able to see all candidates, but it's actually hiding candidates who have not raised any money: https://www.fec.gov/data/candidates/?has_raised_funds=true. For this to be true, we may consider removing `has_raised_funds` parameter so that we are truly showing all candidates regardless of whether or not they have raised funds.

We may have partially addressed this problem from a design standpoint with the new Advance Data page designs, but we should review those designs to make sure we've succeeded.

Completion criteria:
Consistent with implementation of https://github.com/fecgov/fec-cms/issues/1874:

- [ ] review new advanced data pages to make sure users will clearly understand the results that will be returned from a search
- [ ] make sure "no data" message for committees that have no reported financial data is consistent with message for such committees in the election page interface

**Comment by JonellaCulmer** [comment]
The problem concerning the visual presentation of the candidate information (i.e. Presidential, House, and Senate candidates nested beneath All candidates), may be addressed with the updated Advanced data: Candidate page. These pages are in the final stages of development and will be implemented shortly.

<img width="1002" alt="screen shot 2018-03-26 at 3 43 55 pm" src="https://user-images.githubusercontent.com/31663028/37929138-1f6be6c0-310d-11e8-815f-04fc14cace6a.png">

**Comment by patphongs** [comment]
The confusion with the visual representation of all candidates and their different offices will be resolved in the new design of advanced data. The totals work is part of this ticket. Closing this ticket in favor of https://github.com/fecgov/fec-cms/issues/1874
