### ISSUE TITLE
Add to indiv contribution help screen for employer search prior to 2003

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#1867]
Prior to 2003 employer and occupation were concatenated in the employer column so searching on occupation returns nothing. 

- [ ] write help text for individual contributor search that explains to use only the employer search for both employer and occupation prior to 2003.

**Comment by jwchumley** [comment]
1. To find by occupation in all years before 2003 search in the employer field. 

2. Prior to 2003 employer and occupation were stored together in the employer column. Searching for occupation in periods before 2003 should be done in the employer field.

@AmyKort @dorothyyeager @JonellaCulmer  This is help text for the occupation search box wherever it is used. (individual contributor and all Receipts. What do you think of these two options?

**Comment by AmyKort** [comment]
Use the employer field to search by occupation in reports filed before 2003.

???

@dorothyyeager @JonellaCulmer  @llienfec

**Comment by JonellaCulmer** [comment]
Hmm...I think either Jeff's option 1, or Amy's option would be good. 

Also, considering what some front-end solutions might look like to help alleviate further issues. Such as graying out the occupation field if someone has specified a search for any time prior to 2003. But perhaps that should be a separate issue.
