### ISSUE TITLE
Implement updated feedback tool

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1876]
We've updated the design of the feedback tool and this issue will complete its implementation on the website. This feedback tool incorporates ethnio signup for future usability testing sessions. 

For `Sign up` button, use this link to ethnio: https://ethn.io/12085
For `Post` button: Submit issue to github. Will function the same as present feedback drawer
For `Review all reported feedback` link: https://github.com/FECgov/FEC/issues
For `Contact the FEC about a specific question` link: https://www.fec.gov/contact-us

### Design: 
![feedback drawer_final_6 1](https://user-images.githubusercontent.com/31663028/40990027-8f6025e4-68bd-11e8-9b92-ab12c3f979e8.png)

### History: https://github.com/fecgov/fec-cms/issues/1854

**Completion criteria:**
- [ ] Add fix to help users close box: sticky close button
- [ ] Incorporate links as outlined above

**Comment by patphongs** [comment]
@JonellaCulmer Should we make the contact link in the drawer to our contact page instead? That will give users the full listing of our specific contacts

**Comment by JonellaCulmer** [comment]
@patphongs That's a great idea. While I like the immediacy of an email box opening up for a quick note to someone at the FEC, we don't know the particular issues that someone might be facing. And emailing someone at the webmanager inbox may slow that response down, if for example they're interested in getting compliance type information. 

I'll modify the link in the original comment.

**Comment by johnnyporkchops** [comment]
The new contact page will make the new link for contact be `/contact` instead of `/contact-us/` whih we can of course redirect in Wagtail redirects, but do we want to make this `/contact` here since these PRs will essentially go in together?
