### ISSUE TITLE
Bug: Incorrectly constructed links to committee profile pages

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#1877]
**What we are after**: 
We want to provide users with the correct committee profile link when a candidate profile page lists more than one authorized committee.

**Current state**: 
Also there seems to a bug in the construction of the committee profile page URL if a candidate has more than one committee listed on his/her candidate profile page. See for example: https://www.fec.gov/data/candidate/H6NV01232/ and https://www.fec.gov/data/candidate/H2NJ05014/. 

The second listed committee is missing a `/` after committee ID and before the question mark.

**Completion criteria**:

**Comment by PaulClark2** [comment]
I tested this in dev. The committee links behave as expected. 

https://fec-dev-proxy.app.cloud.gov/data/candidate/H2NJ05014/
https://fec-dev-proxy.app.cloud.gov/data/candidate/H6NV01232/

**Comment by fec-jli** [comment]
The bug fixed, so close this issue.
