### ISSUE TITLE
Identify way to filter individual contributor search by exact name (way to overcome fuzzy logic if you want to)

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1886]
When searching for Jonathan Baum a user attempted to filter by only that name. Unfortunately, all manner of individual contributors with a name containing Baum came up in the search. Names such as Bauman, Jonathan also appeared, and there doesn't seem to be a way to filter further. 

This could possibly be solved by exporting the data and filtering in Excel (or comparable program), but it's not unfathomable that a user would want to export only the most relevant data applicable to their search and not have to continue filtering further independently. If there's a way to relieve this pain point, it should be explored.  

**Possible fixes to explore:** 
- Sort results by name
- More specific name search in quotations: should look for exact name match in quotations, instead of similar name contained within quotations

**Example:** 
<img width="1364" alt="screen shot 2018-03-26 at 9 32 16 am" src="https://user-images.githubusercontent.com/31663028/37909382-b991d398-30d8-11e8-83a5-4ac9793e20c2.png">

**Comment by lbeaufort** [comment]
I confirmed that the `/schedules/schedule_a/` endpoint uses the full-text filter on `contributor_name`: https://github.com/fecgov/openFEC/blob/develop/webservices/resources/sched_a.py#L52
