### ISSUE TITLE
Investigate logic for earmarked contributions

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1887]
When conducting the same search for https://github.com/fecgov/fec-cms/issues/1886, DCCC also appeared in the individual contributor search as the contributor.

Contributions from the same individual are appearing differently. One is showing up as from the original contributor and another is showing up as coming from the recipient committee (DCCC). Both contributions were earmarked contributions from the original contributor through ActBlue to the DCCC.

We need to take another look at the logic used for earmarked contributions to ensure that information is presented accurately. 

Example:
<img width="1273" alt="screen shot 2018-03-26 at 10 32 19 am" src="https://user-images.githubusercontent.com/31663028/37912746-29925976-30e1-11e8-992c-9bc135e39e29.png">

<img width="1276" alt="screen shot 2018-03-26 at 10 31 46 am" src="https://user-images.githubusercontent.com/31663028/37912761-303a5b5c-30e1-11e8-830a-65bbc99299bd.png">

**Comment by jwchumley** [comment]
It looks like the set of transactions that have the issue are
1. Under $200 
2. Coded and have the "earmarked for" committee id in the contributor ID column.

Earmarks that are under $200 and are not coded and have no contributor ID don't have the problem.
Earmarks that are over $200 don't have the problem.

This particular situation should not exist as the under $200 contribution are not supposed to be coded but they sometimes are.

I suspect we have display rules for transactions under $200 and rules for earmarked transactions and they are conflicting.

**Comment by jwchumley** [comment]
OK, so it looks like the data is correct coming out of the API so it must be some front end logic that is displying different api elements in the columns based on some criteria. If someone on the front end team could have a look and point me to the code that places data in columns.

All four of the transactions on this page should have Jonathan Baum as the contributor.
https://www.fec.gov/data/receipts/?two_year_transaction_period=2018&data_type=processed&contributor_name=baum%2C+jonathan&min_date=01%2F01%2F2017&max_date=04%2F13%2F2018&image_number=201802019091410013&image_number=201803219096903756

Here is the data as it comes out of the API:
{"candidate_suffix":null,"conduit_committee_city":null,"amendment_indicator":"A","schedule_type":"SA","donor_committee_name":null,"contributor_last_name":"BAUM","candidate_prefix":null,"conduit_committee_zip":null,"contributor_street_1":"39 HOLLENBECK AVENUE","candidate_office":null,"contributor_aggregate_ytd":68.0,"report_year":2018,"candidate_office_state":null,"memo_code":null,"candidate_id":null,"two_year_transaction_period":2018,"memoed_subtotal":false,"candidate_office_full":null,"committee":{"street_1":"P.O. BOX 441146","street_2":null,"treasurer_name":"HILL, ERIN","designation":"U","city":"SOMERVILLE","state_full":"Massachusetts","party":null,"organization_type_full":null,"committee_type_full":"PAC with Non-Contribution Account - Qualified","name":"ACTBLUE","committee_id":"C00401224","state":"MA","cycles":[2008,2016,2006,2012,2004,2018,2014,2010],"zip":"02144","designation_full":"Unauthorized","cycle":2018,"organization_type":null,"candidate_ids":[],"committee_type":"W","party_full":null},"contributor_first_name":"JONATHAN","contribution_receipt_amount":19.0,"fec_election_type_desc":null,"contributor_name":"BAUM, JONATHAN","contributor_middle_name":null,"line_number":"11AI","receipt_type_full":"EARMARK","receipt_type_desc":null,"candidate_office_state_full":null,"fec_election_year":null,"election_type_full":null,"line_number_label":null,"back_reference_transaction_id":null,"increased_limit":null,"is_individual":true,"conduit_committee_state":null,"pdf_url":"http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201803219096903756","contributor_state":"MA","unused_contbr_id":null,"contributor_zip":"01230","candidate_last_name":null,"filing_form":"F3X","link_id":4032120181519125971,"sub_id":"4032620181520058693","image_number":"201803219096903756","committee_name":null,"candidate_name":null,"schedule_type_full":"ITEMIZED RECEIPTS","contributor_city":"GREAT BARRINGTON","contributor_employer":"SELF","candidate_office_district":null,"conduit_committee_street2":null,"original_sub_id":null,"memo_text":"EARMARKED FOR DCCC (C00000935)","transaction_id":"SA11AI_103186630","candidate_first_name":null,"timestamp":"2018-03-27T01:49:24.027713+00:00","cycle":2018,"contributor":null,"national_committee_nonfederal_account":null,"file_number":1215697,"conduit_committee_id":null,"conduit_committee_street1":null,"amendment_indicator_desc":"ADD","election_type":null,"contributor_occupation":"LAWYER","conduit_committee_name":null,"contributor_prefix":null,"report_type":"M3","entity_type_desc":"INDIVIDUAL","contributor_suffix":null,"contribution_receipt_date":"2018-02-14T00:00:00","contributor_id":null,"load_date":"2018-03-27T09:00:00.155695+00:00","back_reference_schedule_name":null,"committee_id":"C00401224","memo_code_full":null,"receipt_type":null,"candidate_middle_name":null,"entity_type":"IND","contributor_street_2":null},
{"candidate_suffix":null,"conduit_committee_city":null,"amendment_indicator":"A","schedule_type":"SA","donor_committee_name":null,"contributor_last_name":"BAUM","candidate_prefix":null,"conduit_committee_zip":null,"contributor_street_1":"39 HOLLENBECK AVENUE","candidate_office":null,"contributor_aggregate_ytd":68.0,"report_year":2018,"candidate_office_state":null,"memo_code":null,"candidate_id":null,"two_year_transaction_period":2018,"memoed_subtotal":false,"candidate_office_full":null,"committee":{"street_1":"P.O. BOX 441146","street_2":null,"treasurer_name":"HILL, ERIN","designation":"U","city":"SOMERVILLE","state_full":"Massachusetts","party":null,"organization_type_full":null,"committee_type_full":"PAC with Non-Contribution Account - Qualified","name":"ACTBLUE","committee_id":"C00401224","state":"MA","cycles":[2008,2016,2006,2012,2004,2018,2014,2010],"zip":"02144","designation_full":"Unauthorized","cycle":2018,"organization_type":null,"candidate_ids":[],"committee_type":"W","party_full":null},"contributor_first_name":"JONATHAN","contribution_receipt_amount":15.0,"fec_election_type_desc":null,"contributor_name":"BAUM, JONATHAN","contributor_middle_name":null,"line_number":"11AI","receipt_type_full":"EARMARK","receipt_type_desc":null,"candidate_office_state_full":null,"fec_election_year":null,"election_type_full":null,"line_number_label":null,"back_reference_transaction_id":null,"increased_limit":null,"is_individual":true,"conduit_committee_state":null,"pdf_url":"http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201803219096903756","contributor_state":"MA","unused_contbr_id":null,"contributor_zip":"01230","candidate_last_name":null,"filing_form":"F3X","link_id":4032120181519125971,"sub_id":"4032620181520058691","image_number":"201803219096903756","committee_name":null,"candidate_name":null,"schedule_type_full":"ITEMIZED RECEIPTS","contributor_city":"GREAT BARRINGTON","contributor_employer":"SELF","candidate_office_district":null,"conduit_committee_street2":null,"original_sub_id":null,"memo_text":"EARMARKED FOR DCCC (C00000935)","transaction_id":"SA11AI_102332045","candidate_first_name":null,"timestamp":"2018-03-27T01:52:43.453849+00:00","cycle":2018,"contributor":null,"national_committee_nonfederal_account":null,"file_number":1215697,"conduit_committee_id":null,"conduit_committee_street1":null,"amendment_indicator_desc":"ADD","election_type":null,"contributor_occupation":"LAWYER","conduit_committee_name":null,"contributor_prefix":null,"report_type":"M3","entity_type_desc":"INDIVIDUAL","contributor_suffix":null,"contribution_receipt_date":"2018-02-03T00:00:00","contributor_id":null,"load_date":"2018-03-27T09:00:00.155695+00:00","back_reference_schedule_name":null,"committee_id":"C00401224","memo_code_full":null,"receipt_type":null,"candidate_middle_name":null,"entity_type":"IND","contributor_street_2":null},
{"candidate_suffix":null,"conduit_committee_city":null,"amendment_indicator":"A","schedule_type":"SA","donor_committee_name":null,"contributor_last_name":"BAUM","candidate_prefix":null,"conduit_committee_zip":null,"contributor_street_1":"39 HOLLENBECK AVENUE","candidate_office":null,"contributor_aggregate_ytd":351.0,"report_year":2017,"candidate_office_state":null,"memo_code":null,"candidate_id":null,"two_year_transaction_period":2018,"memoed_subtotal":false,"candidate_office_full":null,"committee":{"street_1":"P.O. BOX 441146","street_2":null,"treasurer_name":"HILL, ERIN","designation":"U","city":"SOMERVILLE","state_full":"Massachusetts","party":null,"organization_type_full":null,"committee_type_full":"PAC with Non-Contribution Account - Qualified","name":"ACTBLUE","committee_id":"C00401224","state":"MA","cycles":[2008,2016,2006,2012,2004,2018,2014,2010],"zip":"02144","designation_full":"Unauthorized","cycle":2018,"organization_type":null,"candidate_ids":[],"committee_type":"W","party_full":null},"contributor_first_name":"JONATHAN","contribution_receipt_amount":19.0,"fec_election_type_desc":"PRIMARY","contributor_name":"BAUM, JONATHAN","contributor_middle_name":null,"line_number":"11AI","receipt_type_full":"EARMARK","receipt_type_desc":"EARMARKED INTERMEDIARY TREASURY OUT","candidate_office_state_full":null,"fec_election_year":null,"election_type_full":null,"line_number_label":null,"back_reference_transaction_id":null,"increased_limit":null,"is_individual":true,"conduit_committee_state":null,"pdf_url":"http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201802019091410013","contributor_state":"MA","unused_contbr_id":"C00000935","contributor_zip":"01230","candidate_last_name":null,"filing_form":"F3X","link_id":4020120181503582749,"sub_id":"4021620181512217098","image_number":"201802019091410013","committee_name":null,"candidate_name":null,"schedule_type_full":"ITEMIZED RECEIPTS","contributor_city":"GREAT BARRINGTON","contributor_employer":"SELF","candidate_office_district":null,"conduit_committee_street2":null,"original_sub_id":null,"memo_text":"EARMARKED FOR DCCC (C00000935)","transaction_id":"SA11AI_98581760","candidate_first_name":null,"timestamp":"2018-02-17T15:49:16.978176+00:00","cycle":2018,"contributor":{"street_1":"430 SOUTH CAPITOL STREET, SE","street_2":"2ND FLOOR","treasurer_name":"SENA, DANIEL","designation":"U","city":"WASHINGTON","state_full":"District Of Columbia","party":"DEM","organization_type_full":null,"committee_type_full":"Party - Qualified","name":"DCCC","committee_id":"C00000935","state":"DC","cycles":[1986,2002,2006,1978,1996,2014,2000,1990,2012,1984,1992,2004,2010,1994,2018,1976,1980,2008,1982,1988,1998,2016],"zip":"200034024","designation_full":"Unauthorized","cycle":2018,"organization_type":null,"candidate_ids":[],"committee_type":"Y","party_full":"DEMOCRATIC PARTY"},"national_committee_nonfederal_account":null,"file_number":1205995,"conduit_committee_id":null,"conduit_committee_street1":null,"amendment_indicator_desc":"ADD","election_type":"P","contributor_occupation":"LAWYER","conduit_committee_name":null,"contributor_prefix":null,"report_type":"YE","entity_type_desc":"INDIVIDUAL","contributor_suffix":null,"contribution_receipt_date":"2017-12-14T00:00:00","contributor_id":"C00000935","load_date":"2018-02-18T09:13:19.064598+00:00","back_reference_schedule_name":null,"committee_id":"C00401224","memo_code_full":null,"receipt_type":"24T","candidate_middle_name":null,"entity_type":"IND","contributor_street_2":null},
{"candidate_suffix":null,"conduit_committee_city":null,"amendment_indicator":"A","schedule_type":"SA","donor_committee_name":null,"contributor_last_name":"BAUM","candidate_prefix":null,"conduit_committee_zip":null,"contributor_street_1":"39 HOLLENBECK AVENUE","candidate_office":null,"contributor_aggregate_ytd":351.0,"report_year":2017,"candidate_office_state":null,"memo_code":null,"candidate_id":null,"two_year_transaction_period":2018,"memoed_subtotal":false,"candidate_office_full":null,"committee":{"street_1":"P.O. BOX 441146","street_2":null,"treasurer_name":"HILL, ERIN","designation":"U","city":"SOMERVILLE","state_full":"Massachusetts","party":null,"organization_type_full":null,"committee_type_full":"PAC with Non-Contribution Account - Qualified","name":"ACTBLUE","committee_id":"C00401224","state":"MA","cycles":[2008,2016,2006,2012,2004,2018,2014,2010],"zip":"02144","designation_full":"Unauthorized","cycle":2018,"organization_type":null,"candidate_ids":[],"committee_type":"W","party_full":null},"contributor_first_name":"JONATHAN","contribution_receipt_amount":15.0,"fec_election_type_desc":"PRIMARY","contributor_name":"BAUM, JONATHAN","contributor_middle_name":null,"line_number":"11AI","receipt_type_full":"EARMARK","receipt_type_desc":"EARMARKED INTERMEDIARY TREASURY OUT","candidate_office_state_full":null,"fec_election_year":null,"election_type_full":null,"line_number_label":null,"back_reference_transaction_id":null,"increased_limit":null,"is_individual":true,"conduit_committee_state":null,"pdf_url":"http:\/\/docquery.fec.gov\/cgi-bin\/fecimg\/?201802019091410013","contributor_state":"MA","unused_contbr_id":"C00000935","contributor_zip":"01230","candidate_last_name":null,"filing_form":"F3X","link_id":4020120181503582749,"sub_id":"4021620181512217097","image_number":"201802019091410013","committee_name":null,"candidate_name":null,"schedule_type_full":"ITEMIZED RECEIPTS","contributor_city":"GREAT BARRINGTON","contributor_employer":"SELF","candidate_office_district":null,"conduit_committee_street2":null,"original_sub_id":null,"memo_text":"EARMARKED FOR DCCC (C00000935)","transaction_id":"SA11AI_97349388","candidate_first_name":null,"timestamp":"2018-02-17T16:13:38.935392+00:00","cycle":2018,"contributor":{"street_1":"430 SOUTH CAPITOL STREET, SE","street_2":"2ND FLOOR","treasurer_name":"SENA, DANIEL","designation":"U","city":"WASHINGTON","state_full":"District Of Columbia","party":"DEM","organization_type_full":null,"committee_type_full":"Party - Qualified","name":"DCCC","committee_id":"C00000935","state":"DC","cycles":[1986,2002,2006,1978,1996,2014,2000,1990,2012,1984,1992,2004,2010,1994,2018,1976,1980,2008,1982,1988,1998,2016],"zip":"200034024","designation_full":"Unauthorized","cycle":2018,"organization_type":null,"candidate_ids":[],"committee_type":"Y","party_full":"DEMOCRATIC PARTY"},"national_committee_nonfederal_account":null,"file_number":1205995,"conduit_committee_id":null,"conduit_committee_street1":null,"amendment_indicator_desc":"ADD","election_type":"P","contributor_occupation":"LAWYER","conduit_committee_name":null,"contributor_prefix":null,"report_type":"YE","entity_type_desc":"INDIVIDUAL","contributor_suffix":null,"contribution_receipt_date":"2017-12-03T00:00:00","contributor_id":"C00000935","load_date":"2018-02-18T09:13:19.064598+00:00","back_reference_schedule_name":null,"committee_id":"C00401224","memo_code_full":null,"receipt_type":"24T","candidate_middle_name":null,"entity_type":"IND","contributor_street_2":null},

**Comment by fec-jli** [comment]
@jwchumley  it looks like api problem?
try this api link: [https://api.open.fec.gov/v1/schedules/schedule_a/?min_date=20170101&max_date=20180413&contributor_name=baum%2C%20jonathan&per_page=20&sort=contribution_receipt_date&two_year_transaction_period=2018&api_key=DEMO_KEY&image_number=201802019091410013&image_number=201803219096903756](https://api.open.fec.gov/v1/schedules/schedule_a/?min_date=20170101&max_date=20180413&contributor_name=baum%2C%20jonathan&per_page=20&sort=contribution_receipt_date&two_year_transaction_period=2018&api_key=DEMO_KEY&image_number=201802019091410013&image_number=201803219096903756)

you will see:
1)when report_year =2017, there is a **contributor** sub nested section which `name=DCCC`.
2)when report_year=2018, there is no **contributor** sub nested section, =null. so display `contributor_name` value which = "BAUM, JONATHAN"

report_year=2017:
<img width="344" alt="screen shot 2018-04-13 at 11 00 30 am" src="https://user-images.githubusercontent.com/24395751/38742579-fa344760-3f0a-11e8-9ec5-62f2de9cd9a0.png">


report_year=2018:
<img width="361" alt="screen shot 2018-04-13 at 11 01 09 am" src="https://user-images.githubusercontent.com/24395751/38742618-16da6890-3f0b-11e8-9e95-70ce9177152a.png">

**Comment by jwchumley** [comment]
Research complete. See https://github.com/fecgov/fec-cms/issues/1924   for implementation issue.
