### ISSUE TITLE
Committee addresses missing "Suite" on committee profile "About this committee" pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1888]
There are a few committees that seem to be missing the Suite from their addresses when listed on the 'About this committee' pages on committee profile pages. 

Suites appear on the committee's Form 1 filing but it doesn't seem to make it to the 'About this committee' page. In order for someone to get the complete address, they need to view Form 1 to make sure they are seeing an accurate address. Moreover, they need to already _know_ to look at Form 1 to get the complete address. They cannot rely on what's listed in the 'About this committee' section alone. 

(check to see if data is pulling address line 2)

### Some examples: 
**Samsung Electronics America Inc Political Action Committee**
About this committee page: https://www.fec.gov/data/committee/C00590315/?tab=about-committee
Form 1: http://docquery.fec.gov/cgi-bin/forms/C00590315/1215949/

**Denali Leadership PAC**
About this committee: https://www.fec.gov/data/committee/C00438291/?tab=about-committee
Form 1: http://docquery.fec.gov/cgi-bin/forms/C00438291/1196606/

**Motor City PAC**
About this committee: https://www.fec.gov/data/committee/C00507574/?tab=about-committee
Form 1: http://docquery.fec.gov/cgi-bin/forms/C00507574/1162211/

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by JonellaCulmer** [comment]
Yes, the fix has been merged. Closing.
