### ISSUE TITLE
Refactor design of Contact page

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1895]
The design and language of the contact page is potentially confusing to users. For example, the descriptions of services are not necessarily clear, the layout is complicated, the contact information is generally based on an agency-centric understanding of the services we provide rather than a user-centric understanding, and the offices are not listed in an intuitive order. Some of these concerns have arisen from users. Great information at https://github.com/fecgov/fec-testing/issues/89

We'll take a look at the page to see if we can get any quick wins, such as re-ordering the page based on
- [x] Determine strategy for prioritizing what's most sought 
- [x] Determine most frequently sought information

Reconsidering the way information is divided among offices by:
- [x] grouping contact information by services rather than by division?

Reconsidering the layout by
- [x] simplifying the design?

Reconsidering language by
- [x] making descriptions shorter
- [x] considering descriptions from a user-perspective rather than an agency perspective.

**Comment by JonellaCulmer** [comment]
Below is the latest mock-up for the updated Contact page after a thorough review by the content team.

**Design:**
![updated_contactpage](https://user-images.githubusercontent.com/31663028/39130227-8e217584-46da-11e8-8e8f-8f0ac77bdd97.png)

**Next steps:**
- [ ] Share with stakeholders cc: @AmyKort 
- [ ] Move to implementation issue

**Comment by AmyKort** [comment]
We're we going to make "specific requests" "help with"? Or did we decide to stay with specific requests?

**Comment by dorothyyeager** [comment]
Looked back through our convo and I think we landed on "Assistance with"

**Comment by llienfec** [comment]
I think I put up "help with" as less formal.

**Comment by dorothyyeager** [comment]
@llienfec is right, we did end up with "Help with"

**Comment by JonellaCulmer** [comment]
Oversight! I'll make that change tomorrow and update the issue with a new mock-up/screenshot.

**Comment by JonellaCulmer** [comment]
Please see the updated mockup in my previous comment with **Next steps**. 👆👆

**Comment by AmyKort** [comment]
Implementation at https://github.com/fecgov/fec-cms/issues/1943
