### ISSUE TITLE
Develop plan and documentation for redirect strategies and procedures

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1896]
To better empower the content team, they'll learn how to make their own redirects where possible.
- [x] develop strategies for redirects
- [x] document and share startegies
- [x] learn how to do it

**Comment by dorothyyeager** [comment]
In early May, the content team was trained in doing redirects and in the next weeks, we are going to focus on implementing them for the items that were previously housed in classic and transition, but that now have new homes in fec.gov.
