### ISSUE TITLE
Resesarch task: Update the election search map with the new Pennsylvania districts

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#1897]
@jwchumley .

https://www.fec.gov/data/elections/?cycle=2018&state=PA&sort=district

I believe this was an open source district map tool so it may already have been updated and be available for download. Or they may get their data points from Census like our old map. 

Completion Criteria:
- [x] Verify whether updated map downloads are available or if we have to wait for Census (Census data is not available yet, but we shoulfdbe able to use shapefiles until then)
- [x] If updated map data is not available, can we update the map ourselves? (attempting this now, we should be able to do it)

**Comment by jwchumley** [comment]
The issue is all about the districts as they appear on the map. They are now wrong due to the new PA redistricting and people looking up races on the map are confused. If they know their new district number they can use that to find who is running but the map will be wrong . 

The the first step would be to look at the code and see what mapping tool was used and then to see if the new PA districts are available for it. The Census hasn't published them yet as far as I know and that probably means they haven't but whoever maintains the map tool may have done it. So here are the three possibilities:
1. The new district maps are downloadable. We download them and update our map. Done.
2. The new district maps are not yet available. We wait.
3. The new district maps are not yet available but we can update the map code ourselves. (I don't know if this is possible and if it is it may be a heavy lift)

**Comment by PaulClark2** [comment]
The PA Supreme Court included shapefiles in their order mandating new congressional districts. See Remedial Plan Shape Files, http://www.pacourts.us/news-and-statistics/cases-of-public-interest/league-of-women-voters-et-al-v-the-commonwealth-of-pennsylvania-et-al-159-mm-2017. 

We might be able to use these files to update the map on classic. We should ask one of our developers to determine the source of our district maps on the new site. 
- [ ] determine if that source has updated Pennsylvania congressional districts
- [ ] develop and put in a PR that would update Pennsylvania congressional districts on that project. Then use the updated information in our project.

**Comment by johnnyporkchops** [comment]
The process we use for the new site does use Census data to generate the district map as well. I paired with @apburnes on this and we think we have a way forward to update for Pennsylvania's new districts until Census updates their data. Still need to do a little more research to setup local environments and edit the existing script to  generate the data for Pennsylvania.

**Comment by johnnyporkchops** [comment]
See updated map at:
https://fec-feature-cms.app.cloud.gov/data/elections/?cycle=2018&state=PA&sort=district

**Comment by PaulClark2** [comment]
@johnnyporkchops I'm not sure the first check box in my comment above is still relevant. We might just need to strike through it.        

The new district map looks good to me. @jwchumley do you agree?

**Comment by patphongs** [comment]
This has been updated. PR https://github.com/fecgov/fec-cms/pull/1931
