### ISSUE TITLE
Independent expenditure search: difficulty finding Form 5 filers

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#1900]
**What we’re after**:
We need to ensure that all IE filers are available from our search tools.

**Current state**:
Some Form 5 filers to do appear if a user searches by name but do appear if searching by filer ID. 

See for example, America Inc. C90014788

![image](https://user-images.githubusercontent.com/11817734/38271537-b7dfbdda-3754-11e8-877f-11da6a7a64e6.png)

**Completion criteria**:

**Comment by lbeaufort** [comment]
Hi @PaulClark2 my first impression is that because the results are sorted by receipts (and contributions are not often reported by C9 filers), C9 results will be more likely to be at the bottom.

https://github.com/fecgov/openFEC/blob/develop/webservices/resources/search.py#L48

**Comment by PaulClark2** [comment]
Thanks for looking at this. I'm not sure how to move forward on this. So, folks will have problems finding F5, F7 and F9 filers because these filers generally don't include receipts information. I'm not sure how to move forward on this. We need to think of a way for users to find these types of filers.

**Comment by lbeaufort** [comment]
One idea that comes to mind is weighting and displaying exact matches higher in the results. If there's a simple implementation it doesn't come to mind, but it could be done. We would want to be mindful of the broad scope of that function.

**Comment by lbeaufort** [comment]
In sprint planning we decided to sort results by receipts + disbursements

**Comment by lbeaufort** [comment]
Issue moved to [fecgov/openFEC #3057](https://github.com/fecgov/openFEC/issues/3057) via [**ZenHub**](https://www.zenhub.com/)
