### ISSUE TITLE
Update Regulations page with 2018 CFR

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1904]
We need to update the CFR page to link to the new CFR pdf, and other related links (such as taking down the separate pdfs that link to the changes that were expected to be included in that publication). See https://www.fec.gov/legal-resources/regulations/

![image](https://user-images.githubusercontent.com/13237823/38370673-a8e22740-38b8-11e8-9ebe-97f1db21266a.png)

**Comment by rhoughfec** [comment]
For next year when we have to do this again, noting how I found the live/updated links in GPO.

The following changes have been made:

PDF - changed link from 2017 to 2018
XML - changed link from 2017 to 2018
Text - changed link from 2017 to 2018

No change needed to eCFR link.

Found links through GPO then search of all CFR and then narrowed to 11 which had all formats easily accessible that way.
