### ISSUE TITLE
Implement new menu designs

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1905]
**What we're after:** After extensive research and design, we're updating our menu to improve user navigation to the CFD, H4CC, and Legal landing pages. We've also added links to helpful information and tools in order to improve accessibility to those tools. Including the contact your analyst form, the electronic filing page, and the global legal search. Finally, we've made the visual design of all four menus more consistent. 

Many of the links already in use will stay the same but, nonetheless, are broken down below. 

### Campaign finance data menu
![mega-menu_data](https://user-images.githubusercontent.com/31663028/39051337-5507e6c2-4476-11e8-9a51-217ae4dd3f12.png)
Links:
- Explore all data: https://www.fec.gov/data/
- Raising: https://www.fec.gov/data/advanced/?tab=raising
- Spending: https://www.fec.gov/data/advanced/?tab=spending
- Loans and debts: https://www.fec.gov/data/advanced/?tab=loans-debts
- Filings and reports: https://www.fec.gov/data/advanced/?tab=filings
- Candidates: https://www.fec.gov/data/advanced/?tab=candidates
- Committees: https://www.fec.gov/data/advanced/?tab=committees
- Bulk data: https://www.fec.gov/data/advanced/?tab=bulk-data
- Find elections. Search by state or ZIP code: https://www.fec.gov/data/elections/
- Looks up contributions from specific individuals: https://www.fec.gov/data/receipts/individual-contributions/

### Help for candidates and committees menu
![updated-menu-h4cc](https://user-images.githubusercontent.com/31663028/38376347-600279b8-38c6-11e8-8c27-63f4076ce856.png)
Links:
- Explore all compliance resources: https://www.fec.gov/help-candidates-and-committees/
- Guides: https://www.fec.gov/help-candidates-and-committees/guides/
- Forms: https://www.fec.gov/help-candidates-and-committees/forms/
- Dates and deadlines: https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/
- Trainings: https://transition.fec.gov/info/outreach.shtml
- Learn about electronic filing: https://www.fec.gov/help-candidates-and-committees/filing-reports/electronic-filing/
- Find and contact your committee's analyst: https://www.fec.gov/help-candidates-and-committees/question-rad/

### Legal resources menu
![updated-menu-legal](https://user-images.githubusercontent.com/31663028/38379620-3f64a100-38cf-11e8-89b6-b60ff698a386.png)
Links: 
- Explore all legal resources: https://www.fec.gov/legal-resources/
- Advisory opinions: https://www.fec.gov/data/legal/advisory-opinions/
- Enforcement: https://www.fec.gov/legal-resources/enforcement/
- Statutes: https://www.fec.gov/data/legal/statutes/
- Legislation: https://www.fec.gov/legal-resources/legislation/
- Regulations: https://www.fec.gov/legal-resources/regulations/
- Court cases: https://www.fec.gov/legal-resources/court-cases/
- Policy and other guidance: https://transition.fec.gov/law/policy.shtml
- Search across all legal resources: https://www.fec.gov/legal-resources/

### About menu
![updated-menu-about](https://user-images.githubusercontent.com/31663028/38379641-4b1f21f0-38cf-11e8-9318-032cf6c92883.png)
Links:
- Learn more about the FEC: https://www.fec.gov/about/
- News and announcements: https://www.fec.gov/updates/
- Commission meetings: https://www.fec.gov/meetings/
- Mission and history: https://www.fec.gov/about/mission-and-history/
- Leadership and structure: https://www.fec.gov/about/leadership-and-structure/
- Reports about the FEC: https://www.fec.gov/about/reports-about-fec/
- Careers: https://www.fec.gov/about/careers/
- Working with the FEC: https://www.fec.gov/about/#working-with-the-fec
- Contact: https://www.fec.gov/contact-us/

**Comment by patphongs** [comment]
We will not be doing final UX testing on the new menu designs. We have done previous testing on other menu design versions, based on that testing, these new designs were created. We will see how it functions in the wild and track analytics to get a better understanding as to how these changes have effected our site. cc @JonellaCulmer @llienfec

**Comment by johnnyporkchops** [comment]
Are the mockups above the final versions to be implemented in this issue/PR?

Can someone clarify what this means `Many of the links already in use will stay the same but, nonetheless, are broken down below.` ?

**Comment by JonellaCulmer** [comment]
Yes, those are the mockups to use for this issue/PR. And that sentence just means that I've listed out all the links you'll need to use for each of the buttons/links/etc.

**Comment by jenniferthibault** [comment]
It it's helpful context to have @johnnyporkchops , historically when building the menus with Noah and Christine, we always decided that they were ok to build entirely custom style or html for, since they're their own component. 

@JonellaCulmer have you all discussed how these work and look on mobile 📱 💭 ? For implementation issues it's helpful to have those designs represented as well so that there are no surprises.

**Comment by johnnyporkchops** [comment]
@jonella and I did sync on some responsive display concerns she had during the mockup phase and I tested the implementations here  in various sizes a bit. Everything looks good on first pass, except for a few font color adjustments. Of course, we should do a more comprehensive responsive test before deploying.

**Comment by AmyKort** [comment]
@johnnyporkchops  (and @JonellaCulmer and @llienfec ): Should the menu link to Bulk data: https://www.fec.gov/data/advanced/?tab=bulk-data be labeled "Advanced Data" rather than "Bulk Data"? When I get to the page, that's what it is called.

**Comment by AmyKort** [comment]
Wait! Never mind @johnnyporkchops . I get what we're doing now. It was just a little jarring when I was testing the Advance Data fixes today and thought I'd gotten lost.

**Comment by johnnyporkchops** [comment]
@JonellaCulmer , Is the text adjacent to icons on the right of some of the menues supposed to be smaller than the listed links.? For example, the text in these links: Learn about electronic filing,
Find and contact your committee's analyst

**Comment by patphongs** [comment]
PR has been merged. Closing
