### ISSUE TITLE
Simple grammar edits on Campaign Finance Data's filings page

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#1907]
A couple grammar edits on the CFD filings and reports page:

- In the breadcrumbs for [PAC and party committee reports](https://www.fec.gov/data/reports/pac-party/?is_amended=false&two_year_transaction_period=2018&data_type=processed&min_receipt_date=01%2F01%2F2017&max_receipt_date=04%2F09%2F2018), change "Pac And Party Committee Reports" to "PAC and party committee reports"

![image](https://user-images.githubusercontent.com/22914750/38502495-921ffcf8-3bdd-11e8-86c8-b22efb1baa19.png)

- In the committee type filter on the [PACs and parties filings page](https://www.fec.gov/data/reports/pac-party/?is_amended=false&two_year_transaction_period=2018&data_type=processed&min_receipt_date=01%2F01%2F2017&max_receipt_date=04%2F09%2F2018), add a closing parenthesis for Super PACs so that it reads "Super PAC (independent expenditure only)"  At first I thought it was truncated b/c of length, but I think that other labels in the list are longer.

![image](https://user-images.githubusercontent.com/22914750/38502686-0b93a0b2-3bde-11e8-8ce9-c2bb86551118.png)

![image](https://user-images.githubusercontent.com/22914750/38502675-057320a4-3bde-11e8-8c91-0e5428017f86.png)

**Comment by llienfec** [comment]
We could also tackle the change from `Independent expenditor (person or group)` to `Independent expenditure filer (not a committee)` with these changes.

**Comment by JonellaCulmer** [comment]
Talked to @fec-jli about making the independent expeditor change and the following files need to be updated in order for it to be changed consistently across the site. 
- [ ] update committee-types.jinja
- [ ] update audit-committee-types.jinja
- [ ] update staging.ref_cmte_tp

**Comment by AmyKort** [comment]
cc @vrajmohan

**Comment by lbeaufort** [comment]
PR is merged: https://github.com/fecgov/fec-cms/pull/1987
