### ISSUE TITLE
Research - Filters missing on "filings and reports" CFD page

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#1908]
- [x] On the [PAC and party committee reports page](https://www.fec.gov/data/reports/pac-party/?is_amended=false&two_year_transaction_period=2018&data_type=processed&min_receipt_date=01%2F01%2F2017&max_receipt_date=04%2F09%2F2018), the "report type" filter is missing options for monthly reports.

![image](https://user-images.githubusercontent.com/22914750/38504586-0e8fe23a-3be3-11e8-857f-2898f8f22e16.png)

**Comment by llienfec** [comment]
In addition, here are a couple of other potential issues with the filters in the [Filings and reports](https://www.fec.gov/data/filings/?data_type=processed) section.
- Presidential reports section's report type filter is missing bundling
- House and senate reports section's report type filter is missing bundling
- None of the committee pages allow users to filter by filings that aren't reports (like Form 1s)

**Comment by lbeaufort** [comment]
@llienfec - as a recap of our discussion, 

- _House, Senate, & Presidential reports section's report type filter is missing bundling_ the reports endpoint doesn't return F3L at this time - removing the filter for the Reports data table
- _None of the committee pages allow users to filter by filings that aren't reports_ Users expect the reports data table to show non-financial filings. We should think about how to display filings & reports in a more user-friendly way.

**Comment by lbeaufort** [comment]
Addresed by PR fecgov/fec-cms #1951
