### ISSUE TITLE
Add PCCs to elections endpoint

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#1910]
An old PR that was closed concerning adding principal campaign committees (PCCs) to the elections endpoint: #2901 should be given a closer look. We want to be able to show PCCs within the new About section of the election pages. See example below:

![candidate_info](https://user-images.githubusercontent.com/12799132/38515400-19dd4e56-3c02-11e8-939b-a3e21d90543f.png)

**Comment by lbeaufort** [comment]
PR is merged: fecgov/openFEC#2901
