### ISSUE TITLE
Research: Fix special election dates on the election search page

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#1912]
The wrong election dates are displayed on the elections search page for special elections. It would be nice to re-use this logic in order to display general elections and special general elections on the elections landing page. It is buggy on display of special elections, need to try and fix that logic foundation first before we build on top of it.

Example of something buggy. Below link still shows Arizona 8 as a having a 2018 special election even though you are viewing 2012 data.

https://www.fec.gov/data/elections/?cycle=2012&state=AZ&sort=district

**Completion criteria:**
- Take a look at @llienfec research findings below
- Make an implementation ticket for what comes out of testing results

**Comment by llienfec** [comment]
I researched how special elections are showing up on the elections search page:

## Results
@patphongs `Look into the unchecked boxes below.`  Looks like NY 25th district and PA 15th district should show a special election.  Also how should this work when there's a special election and a regularly-scheduled election on the same day (for example 11/6/18)?

## Testing
### Logic
This is how I understand the logic for what general election should show up: The election on the CFD pages should be the next upcoming general election for the seat, whether special general or general election.  

### Special election tests
**One:** Looking for any districts where the upcoming election is a special election to see what the CFD page shows.  Based on my understanding of the logic, CFD should show Special General (SG).
- [ ] MI 13 - SG on 11/6/18.  CFD shows SG.
- [ ] MS Senate - SG on 11/6/18.  CFD shows SG.
- [ ] NY 25 - SG on 11/6/18.  CFD shows regular general, but prior notices are coming soon, so it may not be in the database yet.
- [ ] PA 7 - SG on 11/6/18.  CFD shows SG.
- [ ] PA 15 - SG on 11/6/18.  CFD shows regular genera.  Prior notice has been issued.

**Two:** Looking for districts that were recently specials, but the special general has passed.  We'd expect that CFD would show the upcoming regularly scheduled general election.
- [ ] TX 27 - CFD shows regular general
- [ ] OH 12 - CFD shows regular general
- [ ] AZ 8 - CFD shows regular general

**Comment by llienfec** [comment]
Next steps are to see why NY 25 and PA 15 aren't showing the special general as the next upcoming election. Since this is where my research ends, I'm going to take my name off as an assignee on the ticket.  I'm happy to come back and test or help look into this if you need me @patphongs.

**Comment by patphongs** [comment]
@llienfec I think I'll need to review the testing results with you again. I'm seeing `General Election` results for all of these and nothing with Special general elections noted on the front end interface. Not sure if I'm missing something, could you please ping me about this when you get the chance? Thanks!

**Comment by llienfec** [comment]
Hey @pat - I think that both of those districts should say "special general."  I pinged you w/ availability today.  Thanks!

**Comment by patphongs** [comment]
New business rules to untangle display of G vs SG elections.
- If the General (G) and Special General(SG) elections are on on the same day, we want to show both at the same time. 
- Display should be `General/Special general election` within the same result item

Otherwise, just show the next upcoming election:
- General election should show the next upcoming general election
- Special General should show the next upcoming special general election

**Comment by patphongs** [comment]
New issue was created based on comments above. Closing this issue in favor of https://github.com/fecgov/fec-cms/issues/2419
