### ISSUE TITLE
Formatting bug in Updates search

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#1914]
I was doing a search of updates to find anything on text message AOs (there's an old Record article), and in page 3 of the results, I ended up with half the entries being in italics. 

Specifically, I searched the term "text" on https://www.fec.gov/updates/ 

Here's a screencap of what page 3 of the results looked like:
![record search.PNG](https://images.zenhubusercontent.com/59833ec0f8b79f8376e1d2ce/ec963354-bf38-42ae-b6fd-40fa59c0daf5)

It went back to normal on page 4.

Tagging @lbeaufort since she advised me to put this in as a possible bug.

**Comment by lbeaufort** [comment]
Thanks so much for entering this, @dorothyyeager! What browser were you using? I don't see this behavior on Chrome on Mac.

**Comment by dorothyyeager** [comment]
Chrome for Windows. It's the only time it's happened in search for me and that term brings up a lot of results, so maybe error on my end.

**Comment by lbeaufort** [comment]
It definitely happens for me too!

**Comment by dorothyyeager** [comment]
Thank you for looking into it @lbeaufort

**Comment by apburnes** [comment]
@dorothyyeager this is an error in the data via the `formatted_title` attribute.  Update the `formatted_title` field of _District Court Issues Judgment in James v. FEC_ by adding the missing closing `>` and it will no longer make the posts italic. 

<img width="760" alt="screen shot 2018-07-09 at 12 44 47 pm" src="https://user-images.githubusercontent.com/693815/42461303-87ad0d2a-8376-11e8-9604-c50570e51b36.png">

**Comment by dorothyyeager** [comment]
But we want the posts (the ones about court cases anyway) to be in italics... will make sure I close the tag in that one post.

**Comment by dorothyyeager** [comment]
Oh wait, I didn't understand - but now I do, the bad closing tag caused the search error?

**Comment by dorothyyeager** [comment]
That post has been fixed. It was in a scraped press release. I don't know if there are other errors in other scraped press releases, but if we find them, we'll fix them. Thanks @apburnes

**Comment by AmyKort** [comment]
Awesome! Thanks! Should we close this issue?

**Comment by apburnes** [comment]
Closing this issue. Discovered it was a input data error and has been updated.
