### ISSUE TITLE
Tweaks desired for resource page template in Wagtail.

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#1916]
What we're after:
This issue is to consolidate some older issues regarding elements that need to be tweaked or added into the resource page template in Wagtail into one issue for when there is time to work on improving this template, which has proved to be a very useful and versatile one for H4CC pages. Making these changes will make the template even better and more powerful for content owners.

Older issues:
#1146 - Add an image block and table options to the template
#1841 - Add an image block option to the template
#[5544](https://github.com/fecgov/FEC/issues/5544) - Fix the font size for bullet points if used in the intro part of the template

Basically, what is desired is for the resource page to have all the options. We are able to function without these options, but we have had to put [irregularly sized font into intro-text with bullet points](https://www.fec.gov/introduction-campaign-finance/understanding-ways-support-federal-candidates/presidential-elections/public-funding-presidential-elections/), forego including useful images (see #1841), and have had to [manually code the tables we've included](https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/coordinated-party-expenditures/coordinated-party-expenditure-limits/) (a lot of work) using the HTML block on the pages using the template.

I will close the issues listed above in favor of this one.

**Comment by JonellaCulmer** [comment]
Ignore this issue as part of bulk issue closeout. @PaulClark2

**Comment by patphongs** [comment]
PR with these tweaks have been merged: PR #2346
