### ISSUE TITLE
Improve "no data found" message to a bullet for looking at raw data

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#1922]
@fec-issues-bot commented on [Mon Apr 16 2018](https://github.com/fecgov/FEC/issues/5553)

## What were you trying to do and how can we improve it?
 Find latest filing for a California House candidate, apparently filed after the evening deadline for the overnight refresh. We need to add instructions on how to find raw filings.

Here's the message I got:

We don't have any financial data for KRISTIN GASPAR FOR CONGRESS in 2017–2018.
This can be because:
•	There hasn't been a filing deadline yet or
•	A filing deadline has passed, but the FEC hasn’t finished processing the financial data
To find the most recent activity for this candidate or committee, try changing the election cycle.

I think it would be helpful to suggest after the second bullet that people try looking at raw filings (and provide a step-by-step on how to find them), because the report shows up there. 

 

## Tell us about yourself
 FEC Press Office 

## Details
* URL: https://www.fec.gov/data/committee/C00666842/?cycle=2018 
* User Agent: Amazon CloudFront

**Comment by AmyKort** [comment]
@llienfec -- is this something you'd tackle in connection with #1892 ?

**Comment by llienfec** [comment]
Sure thing.  I assigned the issue to me.  =)

**Comment by llienfec** [comment]
I did some research into best practices for "no data" messages.  In general, a big lesson from the research is to either:

- Provide suggestions to make the search successful.
- Provide an alternative to getting at the same/similar information that may work better.

So this suggestion from Press is right in line with best practice research.  I'm going to close this issue and combine it into the work on #1892.
