### ISSUE TITLE
Display problem with earmarked contributions

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#1924]
Individual contributions normally display the contributor name in the contributor name column. That makes sense right? But when the contributor is a committee and the contributor_id is populated, the API code looks up the committee id and plugs in the official committee name in the contributor name column.  The reason for this is that filers may use any number of abbreviations or spellings or approximations of the name of the committee that gave them money and we want it standardized as much as possible.

There is a problem though with earmarked transactions. Unlike a contribution from a committee, an earmarked transaction gets coded (15E, 24T, 24I) and the committee id of the third party is plugged into the contributor ID column (which makes no sense but it has to go somewhere and that is where it goes.) So because of the aforementioned logic, the API code does a lookup for the third party by ID and plugs in that committee name as the contributor name. This makes no sense so there was code written to work around it but only for 15E. We need to add exception clauses for 24T and 24I as well

Here is an example:
https://www.fec.gov/data/receipts/?two_year_transaction_period=2018&data_type=processed&contributor_name=OELSNER%2C+GEOFFREY

All six of the listed transactions should be from Geoffrey Oelsner.  The one that looks like it is from the DNC and the one that looks like it is from the DCCC are both coded 24T and have CONTRIBUTOR IDs that match DNC and DCCC. 

The file that handles the display in the cms is `receipts.hbs` but we’d want to update the `EARMARKED_CODE`constant. We want to make sure we’re displaying 15E,  24T and 24I properly.

**Comment by johnnyporkchops** [comment]
From comment above:
` the committee id of the third party is plugged into the contributor ID column (which makes no sense but it has to go somewhere and that is where it goes.)  `
When this is complete, do we expect to see the correct contributor (Geoffrey Oelsner in the example) for all entries in the `contributor column` or just see the correct contributor in the details panel?
