### ISSUE TITLE
Search regulations button always link to prod.

### ISSUE THREAD

**Issue by fec-jli** [fecgov/fec-cms#1925]
1)"Search regulations" button in Regulations page from dev or stage always go to prod.
https://fec-dev-proxy.app.cloud.gov/legal-resources/regulations/

![Screen Shot 2018-04-16 at 4.22.40 PM.png](https://images.zenhubusercontent.com/595e524361b4ca3b0a736e43/252addf1-93e5-4be3-89db-389246ff404d)

**Comment by patphongs** [comment]
@fec-jli I was able to easily fix this in the Stage wagtail and Prod wagtail. Should be fixed now.
