### ISSUE TITLE
Fix Audit page broken links

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#1926]
The transition bucket cannot have a space in the path or it will error. We need to do a search and replace in the Audit database to correct the following directory path. There are multiple links that have this folder in it.

**Bad directory path:**
https://transition.fec.gov/audits/2008/McCain-Palin_2008_Inc_McCain-Palin_Compliance%20Fund_Inc

**Good directory path:**
https://transition.fec.gov/audits/2008/McCain-Palin_2008_Inc_McCain-Palin_Compliance_Fund_Inc

**Comment by fec-jli** [comment]
This is fixed. Thanks

**Comment by patphongs** [comment]
Thanks! Closing
