### ISSUE TITLE
Add data tutorial to Advanced Data pages

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1927]
We need to include this tutorial on the Advanced Data pages. https://classic.fec.gov/finance/disclosure/DataFiles.pdf

This document could probably be more user-friendly, and that's something we should look into. But, as an MVP, let's port the information from classic to the new website. As a second step, we can look into improving the tutorial.

@JonellaCulmer                        @PaulClark2                        

Completion criteria:
- [ ] Port information from classic page into a Wagtail page

**Comment by PaulClark2** [comment]
Can we put those images in a Wagtail page? Maybe that's the MVP? We create a Wagtail page with that information. Later we work on improving the content.

**Comment by AmyKort** [comment]
Great idea!

**Comment by dorothyyeager** [comment]
The draft page is ready for review by @PaulClark2 when he gets back.

**Comment by AmyKort** [comment]
Would @jwchumley or @ChristianHilland be able to review the new page?

**Comment by PaulClark2** [comment]
I'm slow. Since Judy requested and Jason created the original page, I sent it to them for review.

**Comment by dorothyyeager** [comment]
I've updated the page with Jason's edits. It's ready to publish if there are no other edits from Judy.

**Comment by AmyKort** [comment]
Looks great! Let's go ahead with this!

**Comment by dorothyyeager** [comment]
The page is now live at https://www.fec.gov/campaign-finance-data/working-downloadable-fec-data-files-using-ms-access/ and we can close this issue.
