### ISSUE TITLE
Bad links: campaign finance data menu and data pages

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#1928]
**What we’re after**:
Update links so that users are directed to the correct page.

**Current state**:
The CFD menu has a couple bad links. The `Bulk data and other sources` link takes you to `External sources`.  The `External sources` link takes you to `Raising`.

![image](https://user-images.githubusercontent.com/11817734/38991566-2a5f1b2c-43ac-11e8-97c9-169fb40203d7.png)

The `bulk data` link on the schedule data pages takes you to `External sources`.
![image 1](https://user-images.githubusercontent.com/11817734/38991588-3ab64680-43ac-11e8-93c4-5a044f5edcdb.png)

**Completion criteria**:
- [x] links take uses to correct page
   - [x] fix Bulk data and other sources link
   - [x] fix External sources link

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by lbeaufort** [comment]
PR is merged - closing the issue, thanks @AmyKort!
