### ISSUE TITLE
Research YouTube streaming and design possibilities

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#1932]
- How can we replace the current live video link?
- How do we replace this within wagtail?
- How does digitalgov utilize YouTube live? Or other agencies?

**Comment by AmyKort** [comment]
@dorothyyeager  Do you think we can close this in favor of https://github.com/fecgov/fec-cms/issues/2084 ?

**Comment by dorothyyeager** [comment]
Sorry @AmyKort - We have figured out we can do this with some modifications to the meeting page template. Jim Jones has done a ton of research into this and we know we need the html block to make the embed code from YouTube work. So I think this can be closed, but in favor of #2166 where the work on the meeting page template is being done.
