### ISSUE TITLE
PAC and Party Reporting Examples: Round 3 publishing

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#1934]
To help PACs and party committees understand how to report campaign finance transactions, we will draft and post reporting examples that will go with the nonconnected, SSF, and party sections within Help for Candidates and Committees.

#1866 covers round 3 language; #1933 covers images, edits, and approvals. This issue covers the work to post examples.

### Completion criteria
- [x] Enter compiled edits into Wagtail
- [x] RAD manager review and approval
- [x] Publish examples
- [x] Create links on Reporting Examples list page
- [x] Add Reporting Example cards to content pages

cc: @rhoughfec

**Comment by llienfec** [comment]
Got comments back from RAD, and after 1 image adjustment, we'll be good to go.  I updated the scope of this ticket.  We're going to hold off publishing until we finish the corresponding IE examples for committees (these examples only cover Form 5 filers).   I'll put in a new issue for this next week when I'm back in the office.

**Comment by llienfec** [comment]
Made the image adjustment, published the "converting to a multicandidate committee" example, and created links in the reporting list and in the page that addresses converting.  Will work on publishing the IE examples as addressed above ^^.

**Comment by dorothyyeager** [comment]
We've added the new examples for independent expenditures to both the Filing PAC reports and Filing SSF reports pages, so the circle is complete and we can reclose this issue.
