### ISSUE TITLE
Implement new "no data" message

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1939]
Building on our work at https://github.com/fecgov/fec-cms/issues/1892 , we need to implement the new language for our no data messages. The new language is below:

We don’t have [data type] information for [time period].

This can be because:

We’re still processing the data. Try looking for raw versions of committee filings. Raw files are only available for electronic filers.
No one filed this type of activity during the time period.
The filing deadline hasn’t passed yet.
Think this result is a mistake or have questions? Send us more information in the feedback box or contact us.

**Comment by JonellaCulmer** [comment]
@apburnes I think the intention of this ticket was to display the default reasons. How I would love to display a single reason for missing data, but I don't think we're in a place to do that just yet.

**Comment by apburnes** [comment]
@JonellaCulmer these are the lists of current `reasons` [https://github.com/fecgov/fec-cms/blob/develop/fec/fec/static/js/modules/helpers.js#L365-L372](https://github.com/fecgov/fec-cms/blob/develop/fec/fec/static/js/modules/helpers.js#L365-L372) that the message could display. It's set up to display the default ones if none of the predefined are met. Is the list of current `reasons` valid today?

**Comment by JonellaCulmer** [comment]
Work has been merged, so closing.
