### ISSUE TITLE
Update documented process for updating State district maps

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#1942]
This is a followup to
 **Issue:** https://github.com/fecgov/fec-cms/issues/1897 (Resesarch task: Update the election search map with the new Pennsylvania districts)
**PR:** https://github.com/fecgov/fec-cms/pull/1931 (Update Penn districts #1931)

 PR 1931 provides a temporary fix to add the new Pennsylvania 2018 redistricting to https://www.fec.gov/data/elections/?cycle=2018&state=PA&sort=district because the Census data that we normally use to generate the districts.json file was not yet available. 

In doing so, we found that the documented procedure in [notes.md](https://github.com/fecgov/fec-cms/blob/develop/fec/fec/static/js/data/notes.md) is not complete. This ticket is to update those instructions, and if the census data is available yet, test the procedure with the new data.

Completion:
-[ ] update notes MD

**Comment by AmyKort** [comment]
@johnnyporkchops  Is this something we need to do now? Or is it something that can wait?

**Comment by johnnyporkchops** [comment]
@AmyKort, this can wait. 
Background:
We are waiting until Census updates the geo data for 2017, which they have not as of today. So when this file exists, we can move forward:
https://www2.census.gov/geo/tiger/TIGER2017/CD/tl_2016_us_cd115.zip
I have been checking periodically and will continue to do so.

**Comment by jwchumley** [comment]
I'm taking the milestone off of this since we have no way to know when the Census data will be available.
