### ISSUE TITLE
Implement new contact page design

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1943]
**What we're after:** We've reorganized and streamlined our contact page language and design to help users better find the FEC services they are looking for. Our next step is to implement the new design. Great background at: https://github.com/fecgov/fec-cms/issues/1895

**Designs:**
![contact_updated_ig](https://user-images.githubusercontent.com/31663028/39281163-4ac5fc30-48d1-11e8-913d-9bd578999304.png)

**Completion criteria:** 
- [x] Create wagtail template, or discover applicable, mobile-friendly template to function similarly to the hard-coded version (column 1 (left), then column 2(right)) (also talk to Jonella about line spacing)
- [x] Front-end and content pair to build contact page in Wagtail
- [x] Publish new wagtail contact page live
- [x] Delete hard-coded contact page
- [x] Modify link to contact page to say `www.fec.gov/contact` and remove `-us`
- [x] Add a wagtail redirect for for `/contact-us/` to go to `/contact/`

**Comment by JonellaCulmer** [comment]
Once upon a time, we planned on removing the `-us` from the `www.fec.gov/contact-us` link in an effort to move away from first-person POV. Emileigh started a PR some time ago that is now out of date, but I think we can incorporate the intent of the PR in this implementation issue as well. 

Old PR: https://github.com/fecgov/fec-cms/pull/784

**Comment by dorothyyeager** [comment]
Took a look at the templates in the pattern library to see if there was one that functioned similarly to the current page. The closest seemed to be the "custom page" which does permit two columns, but would require us to swap what's in the design. It looks like the best option will be to build a new Wagtail template.

**Comment by johnnyporkchops** [comment]
@JonellaCulmer , do you have the text for the above mockup by any chance?

**Comment by JonellaCulmer** [comment]
@johnnyporkchops I can compile the text in a google doc for you. 
The image in the mock-up is what is currently implemented.

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Here's the page content: https://docs.google.com/document/d/1dv-n3Wbqr3pnvu23vEdFN_xIfertUG6iWZS5aFwm0fQ/edit#

cc: @dorothyyeager

**Comment by dorothyyeager** [comment]
@johnnyporkchops Happy to review the PR for content if needed.

**Comment by JonellaCulmer** [comment]
This work has been merged into the next release, so closing this issue.

**Comment by dorothyyeager** [comment]
@JonellaCulmer and I built out the draft page in prod this AM and have sent to PMs to review, with a cc to @johnnyporkchops so he knows we're about to publish it.

**Comment by dorothyyeager** [comment]
All contact page-related tasks are complete and the old contact address is now redirecting to https://www.fec.gov/contact/ so we can close this issue.
