### ISSUE TITLE
Make raising/spending page cycles data-driven

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#1947]
This arises from https://github.com/fecgov/fec-cms/issues/1550

The [raising/spending pages](https://www.fec.gov/data/raising) cycle dropdown is hard-coded.  We should make sure the raising/spending pages automatically add future cycles - possibly we could leverage the `macros/cycle-select.jinja`

**Comment by apburnes** [comment]
We could add `utils.get_cycles` to each of the views and then use `macros/cycle-select` in the template.

**Comment by AmyKort** [comment]
Merged, so closing.
