### ISSUE TITLE
Test TimeTrade for user testing appointment booking

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1948]
We currently use a GSA google calendar to book appointments for user testing. In order to use the calendar someone from 18F (Jen, our savior) needs to open up time slots. With her departure looming we need to explore alternatives. 

Enter TimeTrade. We've had a preliminary discussion with them about the system's capabilities but now we need to test for ourselves. To do that we can sign up for a trial account and see if the system can address our needs. 

Our needs include: 
- Blocking out specific timeframes
- Send confirmation emails
- Customize the calendar and confirmation email content/appearance (appearance not a dealbreaker)

This list is not all-encompassing. 

Completion criteria:
- [ ] Create trial account (14 days)
- [ ] Document pros and cons
- [ ] Make final determination

**Comment by AmyKort** [comment]
cc @wluoFEC

**Comment by wluoFEC** [comment]
I think it is a good idea. Let me know what I need to do to make this happened.

**Comment by patphongs** [comment]
We found out that Ethnio has a built in scheduling tool that we can utilize to schedule user testing. We no longer need timetrade :)
