### ISSUE TITLE
Presidential 2017 - 2020 data on adv data table not displaying properly

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1950]
Relevant issue: #1949 

**What we're after:** The Presidential candidates advanced data table is not displaying data for the two-year periods within the 4-year presidential cycle. When viewing 2017-2020 data, we get a full list of candidates currently raising and spending money for the 2020 election. However, upon filtering to view 2017-2018 data, the tables are empty. We need to display data by both 2017-2020 and by two-year periods.

Completion:
- [ ] Identify desired interaction for buttons

<img width="1197" alt="screen shot 2018-04-25 at 11 53 53 am" src="https://user-images.githubusercontent.com/31663028/39257467-98e5666e-487f-11e8-8349-0b9f7f544ed8.png">
<img width="1113" alt="screen shot 2018-04-25 at 11 55 06 am" src="https://user-images.githubusercontent.com/31663028/39257475-9cfbc55e-487f-11e8-9712-792df4c81758.png">

**Comment by AmyKort** [comment]
Is this something that will be dependent on https://github.com/fecgov/fec-cms/issues/2007 ?

**Comment by lbeaufort** [comment]
Issue moved to [fecgov/openFEC #3214](https://github.com/fecgov/openFEC/issues/3214) via [**ZenHub**](https://www.zenhub.com/)
