### ISSUE TITLE
Wagtail wish list: Add the citations block to the Record page template

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#1952]
Many Record articles contain multiple citations. For readability and also just to follow the style we like in H4CC pages, we put the citations at the bottom. ([Example in this article](https://www.fec.gov/updates/earmarked-contributions/).) It would be great for site consistency to have the citations block as an option in the Record page template.

Completion criteria:
[ ] Modify Record page template in Wagtail to include the citations block option

(For other Wagtail wish list items, see #1738 #1737 and especially #1916 )

**Comment by johnnyporkchops** [comment]
@dorothyyeager , Is this the same as a citations block option that exists on another template?

**Comment by dorothyyeager** [comment]
@johnnyporkchops Yes. We'd like to have the Record use the same citations block that the custom page template has now (and I think a couple of other templates have it, but I'm definitely thinking of the one on the custom page template).

**Comment by dorothyyeager** [comment]
While this would be great for site consistency, we do have a working workaround. So I'll keep it on my Wagtail wishlist and will revisit if there's ever a Record page template issue, but closing this issue for now as it's low priority and more of a nice to have than a need.
