### ISSUE TITLE
[Med risk] Bleach DOS vulnerability

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#1953]
[Med Risk] Snyk alert: https://snyk.io/vuln/npm:bleach:20151024

Vulnerable module: bleach
Introduced through: bleach@0.3.0
Fix: It appears that we no longer use bleach inside of the fec-cms. We can just remove this package and any variables that reference it.

- [ ] Draft google doc for issue - get consensus from developers
- [ ] reach out to Bleach library owner (submit issue in their repo)

**Comment by patphongs** [comment]
On further inspection, we actually use this within our typeahead. Will have to revisit this.

**Comment by AmyKort** [comment]
@patphongs  What's the status of this issue?

**Comment by patphongs** [comment]
Sorry this fell off my radar and I haven't had a chance to look at this yet. Will try to get to it this sprint, but may shift.
