### ISSUE TITLE
[Med Risk] Django information exposure #2

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#1955]
**[Med Risk] Snyk alert:** https://snyk.io/vuln/SNYK-PYTHON-DJANGO-40778
**Vulnerable module:** django
**Introduced through:** django-jinja@2.3.1, django@1.10.8 and others

Fix: Upgrade django to versions 1.8.19, 1.11.11, 2.0.3 or higher.

**Comment by patphongs** [comment]
I am actively working on upgrading to django version 1.11.11. That should resolve this security issue.

**Comment by AmyKort** [comment]
Assigning myself just so there is someone on the ticket. This will resolve with the Wagtail upgrade.

**Comment by jwchumley** [comment]
@JayRibeiro  We will probably go over the 60 day limit. We are actively working to upgrade Django. What are the ramifications?

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by patphongs** [comment]
We need to upgrade Wagtail, that will upgrade Django in the process and resolve this issue. We are working to make sure everything is in place to upgrade wagtail though. This will most likely take a few more sprints

**Comment by JonellaCulmer** [comment]
@patphongs @apburnes Is this, and #1954, still blocked?

**Comment by patphongs** [comment]
@JonellaCulmer Thanks for flagging, this is no longer blocked as the upgrade has been merged and set to be deployed in on 8/14. I'll put this in the ready column until we actually deploy the Penny Robinson 6.5 release. Then this can be closed.

**Comment by JonellaCulmer** [comment]
This issue will be resolved with the wagtail upgrade deploy. Closing.
