### ISSUE TITLE
[Low risk] boto3 information exposure

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#1956]
**[Low risk] SNYK Alert:** https://snyk.io/vuln/SNYK-PYTHON-BOTO3-40617

**Vulnerable module:** boto3
**Introduced through:** boto3@1.4.4

**Fix:** Upgrade boto3 to version 1.4.5 or higher.

**Comment by patphongs** [comment]
Will upgrade to latest version boto3==1.7.9 to patch this security issue this sprint.

**Comment by vrajmohan** [comment]
It looks like the boto3 version required is 1.5.31 (see boto/boto3#1017 (comment))
