### ISSUE TITLE
Implement new election profile pages for House and Senate 

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1970]
**What we’re after:** In order to implement the improvements to the election profile pages, (example: [Arizona - 01](https://www.fec.gov/data/elections/house/AZ/01/2018/), [Arizona Senate](https://www.fec.gov/data/elections/senate/AZ/2018/)) we have  a few things that need to change, including the rearrangement of how data is presented and adding in valuable election-related information. 

These election profile pages are broken out into two pages: Election data and reporting deadlines, and About this election. The work for each of these pages is broken down below. 

## Designs:
![about this election_implement](https://user-images.githubusercontent.com/31663028/39584625-dc33f100-4ec0-11e8-8a42-9d58744c3de3.jpg)
![election data_implement](https://user-images.githubusercontent.com/31663028/39594054-944f62e8-4ed9-11e8-9273-e23175e30db6.png)

## Overall page work:
- [x] Modify breadcrumbs to reflect election and seat (ex. `Arizona - House 01 | 2018` or `Arizona | Senate | 2018`)

## Election data and reporting deadlines page work:
- [x] Move all data tables onto this single page. Includes data currently available on the following pages:
  - Candidate financial totals
  - Individual contributions
  - Spending by others to support/oppose
- [x] Include glossary links on titles for Independent expenditures and Electioneering communications data tables.  
- [x] Change page/tab name to `/tab=election-data` 
- [x] Remove language at the top of the page that says: “This table only shows candidates who have registered and filed a financial report. Looking for all candidates who registered?”
- [x] Incorporate reporting deadline information below each of the following data tables, including icon-calendar and language detailed below: 
- Candidates in this election
  - Congressional committee reports:
Quarterly filing and pre-/post-election reports
  - `Convention and Primary deadlines` button
  - `General deadlines` button
  - Use this spreadsheet for deadline button links: https://docs.google.com/spreadsheets/d/1hxzh-_ALYS_w7lC_4NC1kmT0k950fYVyHhsn2Y8mJo4/edit#gid=0 
  - Create alternative state for elections 2008 and before. Use informational message with text: “Reporting deadlines are only available for elections 2010 and later.”

![screen shot 2018-05-03 at 10 59 47 am](https://user-images.githubusercontent.com/31663028/39584736-24b766e6-4ec1-11e8-910a-78b492c3907e.png)
- Independent expenditures
  - Independent expenditure reports:
24- and 48-hour report periods
  - `Independent expenditure deadlines` button
  - Use this spreadsheet for deadline links: https://docs.google.com/spreadsheets/d/1hxzh-_ALYS_w7lC_4NC1kmT0k950fYVyHhsn2Y8mJo4/edit#gid=2077802716 
  - Create alternative state for elections 2008 and before. Use informational message with text: “Reporting deadlines are only available for elections 2010 and later.” (Screenshot above^)
- Electioneering communications
  - Electioneering communications:
30- and 60-day report periods
  - `Electioneering communication deadlines` button
  - Use this spreadsheet for deadline links: https://docs.google.com/spreadsheets/d/1hxzh-_ALYS_w7lC_4NC1kmT0k950fYVyHhsn2Y8mJo4/edit#gid=1313952208 
  - Create alternative state for elections 2008 and before. Use informational message with text: “Reporting deadlines are only available for elections 2010 and later.” (Screenshot above^)
- [x] Include cards at the top for three sections:
  - `Dates and deadlines` card (https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/)
  - `All (state name) state elections` card  - inactive state coloring ([Pattern library](https://fec-pattern-library.app.cloud.gov/components/detail/basic.html))
  - `All House elections` card - inactive state coloring ([Pattern library](https://fec-pattern-library.app.cloud.gov/components/detail/basic.html))
- [x] Update explanatory language, listed at the bottom of the Candidate financial totals table to say: “This table only shows candidates who have registered and filed a financial report. Information in this table may not include the most recently submitted filings.”
- [x] Add export function to the following tables: 
  - Candidate financial totals
  - Individual contributions
  - Independent expenditures
  - Communication costs
  - Electioneering communications
  - The null state for tables without data to export, Export button should use inactive state coloring. ([Pattern library](https://fec-pattern-library.app.cloud.gov/components/detail/basic.html))

**Active** 
![screen shot 2018-05-03 at 11 01 40 am](https://user-images.githubusercontent.com/31663028/39584841-67307684-4ec1-11e8-85e7-ea351a966285.png)

**Inactive**
![screen shot 2018-05-03 at 11 07 16 am](https://user-images.githubusercontent.com/31663028/39585196-33862792-4ec2-11e8-8e63-b159749e936e.png)

- [x] Side navigation should incorporate each of the data tables listed the page to include:
- Election data and reporting deadlines
  - Candidate financial totals
  - Individual contributions
  - Independent expenditures
  - Communication costs
  - Electioneering communications
- About this election (will break this sections work down below)
  - Candidate information
  - State election offices
- Below this the “Find another election” accordion will remain as is.

## About this election page work: 

- [x] Create new page called About this election
- [x] Change page/tab name to `/tab=about-election` 
- [x] Below title include previous elections information
  - Last general election: Month Day, Year
  - General election: Month Day, Year
- [x] Remove `Current officeholder`
- [x] Side navigation should incorporate each of the data tables listed the page to include:
- Election data and reporting deadlines
  - Candidate financial totals
  - Individual contributions
  - Independent expenditures
  - Communication costs
  - Electioneering communications
- About this election
  - Candidate information
  - State election offices
- Below this the “Find another election” accordion will remain as is.
- [x] Include cards at the top for three sections:
  - `Dates and deadlines` card (https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/)
  - `All (state name) state elections` card  - inactive state coloring
  - `All House elections` card - inactive state coloring
- [ ] Create `Candidate information` table that uses this work, currently in progress: https://github.com/fecgov/openFEC/pull/2901 
- Table should include:
  - Candidate name: `Name`
  - Candidate’s political affiliation: `Party`
  - Candidate’s committee: `Principal campaign committee`
- Table will also delineate which candidate is the incumbent. This should behave like the incumbent feature on the Election data and reporting deadlines page.
- [x] Create `State election offices` section that uses this work: https://github.com/fecgov/openFEC/pull/3011 
  - Include explainer text regarding this section that says: “State laws and procedures govern elections for state and local offices, as well as how candidates come to appear on election ballots. Contact the appropriate state election office for more information.” 
  - Section should include two contact numbers per state. On mobile, these will stack with the left column (first contact), then right column (second contact) and so on.

**Comment by patphongs** [comment]
@apburnes I've got a [work in progress PR](https://github.com/fecgov/fec-cms/pull/1984) from when we were user testing the election profile pages. Still needs some clean up but you can use the same PR to get a feeling of where this currently is. @lbeaufort was able to get the principal campaign committee into the elections endpoint, and that was merged last week https://github.com/fecgov/openFEC/pull/2901. This can be used to build out the table in the about tab. Also for reference this was deployed to our feature environment for user testing purposes: https://fec-feature-cms.app.cloud.gov/data/elections/house/AZ/01/2016/

@JonellaCulmer knows more about the specifics of what has been implemented, so feel free to reach out to her.

**Comment by patphongs** [comment]
This is currently with our public facing offices for user testing and verification
