### ISSUE TITLE
Identify PI 6 Design/UX Goals

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1974]
**What we're after:** Similar to what was done for PI5, we need to identify some design and UX goals for the upcoming PI. 

**Completion criteria:**
- [x] Identify some desired and necessary projects 
- [x] Go over these projects during UX sync
- [x] Share with PMs

**Comment by dorothyyeager** [comment]
Hi @JonellaCulmer for when you get to this next sprint... was asked by Info Div people if the redesign of the prior notice pages/compliance pages is still on the board for PI 6, so hoping that will make your team's list! Work for the next cycle on these will begin in September so summer would be the time for redesign.

**Comment by JonellaCulmer** [comment]
Desired goals for upcoming PI6: https://docs.google.com/document/d/1QUejCLqhJ4HBhwtEELuxo_jKlIEMj2tuiqsXjETVD1c/edit#heading=h.qwc7wsd3kl3b
