### ISSUE TITLE
Synthesize research underlying nation-wide election summary designs

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#1978]
**What we're after:** Heading into PI planning, we'd like to have some preliminary mock-ups on hand of the nationwide election summary pages that we plan to build during the next PI.

**Completion criteria:**
- [x] Take stock what mock-ups/designs already exist
- [x] Dream as big as I possibly can

**Comment by AmyKort** [comment]
This is awesome! Thanks @JonellaCulmer !
