### ISSUE TITLE
Rename "All Reports" filter on calendar

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1981]
The All Reports filter is not returning results on the calendar. This is partly due to the way the date is coded. However, in investigating this problem, we determined that the filter itself is misleading, since even when it functions properly it does not return "All Reports." We'll start work in a separate ticket to re-think the way this filter works. In the mean time, we will temporarily remove the nonfunctional 
filter from the calendar. 

![image](https://user-images.githubusercontent.com/13237823/39767498-edcd990a-52b4-11e8-93fa-15336eeaefdd.png)

**Comment by lbeaufort** [comment]
After a discussion with @AmyKort we're going to change the category 21 label to “Mid-year and year-end”

**Comment by lbeaufort** [comment]
@AmyKort FYI, there are some reporting deadlines that are in the "Year-end and mid-year" category that shouldn't be there. 

Category 21:		
|event_name	|description|	start_date|
|---|---|---|
|Year-End Report Due	|Year-End Report for ALL filers due today.|	1/31/2017|
|<b>Quarterly Report Due </b>	|April Quarterly Report due today.	|4/15/2017|
|<b>Monthly Report Due</b>	|June Monthly Report due today.	|6/20/2017|
|Mid-Year Report Due	|Mid-Year Report due today.	|7/31/2017|
|<b>Monthly Report Due</b>	|September Monthly Report is due.	|9/20/2017|
|<b>Quarterly Report Due</b>	|October Quarterly Report is due.	|10/15/2017|
|<b>Monthly Report Due</b>	|October Monthly Report is due.	|10/20/2017|
|Year-End Reports Due	|Year-End Report for ALL filers is due.	|1/31/2018|
|Year-End Report Due	|Year-End Report due for ALL filers	|1/31/2019      |

**Comment by AmyKort** [comment]
Is that something we can fix on the back end?

**Comment by lbeaufort** [comment]
For posterity, we circled back with the Information Division and they were able to change the category for the mis-categorized items.
