### ISSUE TITLE
Check H4CC pages for consistency 

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1982]
The H4CC section is designed to provide users with plain language guidance for FECA compliance. Now that we have all 4 campaign guides available in this format, it's time to go back over our earlier efforts to ensure consistency of language.

- [x] review all reporting pages for consistency and accuracy, starting with the candidate section in this sprint. (We will tackle other pages and committees in future sprints.)
- [x] review all candidate registration pages for consistency and accuracy

**Comment by dorothyyeager** [comment]
Had a good pairing with @rhoughfec this morning. For this sprint, we will focus on candidate registration and reporting pages, and ensure consistency and accuracy with the Candidate Guide, while making sure that we don't have the same information in two places. 

For other H4CC pages, ensuring our H4CC content is accurate and consistent but not duplicated will need to span over multiple sprints, so we envision this "refresh/refactoring" of the H4CC pages as something we will do as content team work in PI6 and that we will break into manageable chunks of work, similar to the way the reporting example issues are being tackled. @AmyKort

**Comment by dorothyyeager** [comment]
Have reviewed the candidate registration pages and identified some gaps in content on the H4CC page. (The reporting pages look great.) I've added the pages with gaps to the spreadsheet in issue #1214, which deals with identifying gaps in candidate content, so that the content team can together decide how to address this.

**Comment by dorothyyeager** [comment]
Have reviewed the candidate reporting examples and found no major inconsistencies. They look good! Have forwarded a few small suggestions to the content team for review, but with the overall review for consistency completed, we can close this issue.
