### ISSUE TITLE
New menu designs are showing up on transition

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#1990]
User reported that they were able to see new menu designs when clicking on transition.

### How user got there:
User went to H4CC > Trainings, then back to H4CC and saw the menu.  After further testing, it looks like the new menu designs are showing up on the transition website.  We weren't sure if they should be showing up yet.

### Potential issues:
- Text for menu options is really small
- Buttons on the right are running into each other and aren't aligned with the menu text

![image](https://user-images.githubusercontent.com/22914750/40007302-64225938-576a-11e8-99ec-06a058f97229.png)

**Comment by AmyKort** [comment]
We launched the new menus on transition a little earlier than on the regular site. I'm not able to replicate the problem with the spacing in Chrome or IE.
