### ISSUE TITLE
Can't click the right box on the org chart

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#1992]
The clickable areas on the org chart don't line up with the boxes, which makes it difficult to click on the right person. For example, clicking the box for the Associate General Counsel for Policy brings up the Associate General Counsel for Litigation. Clicking the Associate General Counsel for Litigation doesn't get the user anywhere.

https://transition.fec.gov/about/offices/offices.shtml

**Comment by johnnyporkchops** [comment]
@akort---
Wei, Kim, Wenchun, and Jay do not currently have links associated with their names. Should there be links for these?
Should I use the same one for these that we use for Alec? (/about/offices/CIO/CIO.shtml), or should these remain unlinked?
![hotspots](https://user-images.githubusercontent.com/5572856/41127387-bf809f8a-6a78-11e8-901b-9262c7842975.jpg)

**Comment by johnnyporkchops** [comment]
This has been fixed: 
https://transition.fec.gov/about/offices/offices.shtml
