### ISSUE TITLE
User Provided Credentials from CF not working for careers page

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#1993]
The Careers page is not showing  the one open job we have.
- If I hardcode the credentials locally (being sure not to push anywhere) as a test, it works fine.
- I logged into CF and doublechecked that the credentials are set there and that there is no typos.
-These are the credentials, not working from /fec/settings/base.py
-Maybe they are in the wrong place.
```
USAJOBS_WHOMAYAPPLY = env.get_credential('USAJOBS_WHOMAYAPPLY')
USAJOBS_AGENCY_CODE = env.get_credential('USAJOBS_AGENCY_CODE')
USAJOBS_API_KEY = env.get_credential('USAJOBS_API_KEY')
```

**Comment by dorothyyeager** [comment]
Not sure if this info is helpful or not, but the current open job is an internal-only posting, so maybe that's a factor in whatever is happening.

**Comment by ccostino** [comment]
Oh good call to check, @dorothyyeager!  Debugging the issue with testing the API call directly was showing it coming back in the response though according to @johnnyporkchops, and the position is publicly visible on USAJOBS as well (but with the internal position marker on it).

**Comment by johnnyporkchops** [comment]
There was a mistake in the agency code for FEC, where `zeros` were input as `O`s. This should be fixed. There are no open jobs to test but on feature it no longer shows other agency jobs, which I am confident means its fixed.
