### ISSUE TITLE
Wagtail 2.0 testing for hard coded page templates

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#1994]
In the previous Wagtail 2.0 testing issue at https://github.com/fecgov/fec-cms/issues/1973, some page templates could not be tested because they were hard-coded and unable to be tested by the tester (me).
This issue is to move testing of those pages into the next sprint and have those with access to the hard-coded pages do the testing.

Remaining page templates to be tested include:

- Document feed page
- Document page
- Legal resources landing page
- Reports landing page
- Services landing page
- Advanced data pages

**Background for this issue:**

- Initial testing of page templates and notes: https://github.com/fecgov/fec-cms/issues/1973
- Write-up of dealbreakers and issues in Rich Text Editor found during initial testing of all templates: https://docs.google.com/document/d/1fgxx9oTEXunm7scqyqJRDF5bG-z45eXO1VkOLwSa8Zw/edit?usp=sharing

**Completion criteria:**
- [ ] Test each hard-coded page template thoroughly. 
- [ ] Sort issues found into "dealbreakers" that need to be resolved before Wagtail 2.0 is put into use vs. those issues that are annoying but that have workarounds and wouldn't prevent use of Wagtail 2.0.

**Comment by johnnyporkchops** [comment]
- [ ] Pair with @dorothyyeager, to understand her current process for creating pages using:
   Document feed page
   Document page
   Reports landing page

**Comment by johnnyporkchops** [comment]
Some pages have the majority of the content hardcoded, but still also have a wagtail template associated with them. The work fine in Wagtail 2.0 just as they would in <2. These are one-off templates designed specifically for the one page, so these templates would never be used to make a new child page. For reference, examples of these pages are:

Services landing pageDocument feed page
Document page
Reports landing page
Legal Resources Landing Page
