### ISSUE TITLE
Implementation: Fill in gaps identified in candidate H4CC content

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#1995]
In #1214 we identified gaps in the candidate content in the H4CC section of the FEC's website and language from the Campaign Guide for Candidates that could be used to fill those gaps.

This issue is to implement the changes recommended to fill the gaps.

Background document with gaps/language/recommendations is at https://docs.google.com/spreadsheets/d/18RLyzvSWAkLICkGWPHQdGOaVP-QZZwTl4e272UpMD-g/edit#gid=0.

Completion criteria:
- [x] Decide on final approach with the content team 
- [x] Update the pages identified as lacking in information with language from the Guide
- [ ] Create the new pages needed with language from the Guide

**Comment by dorothyyeager** [comment]
See issue #2002 regarding paper filings

**Comment by dorothyyeager** [comment]
This work is going to take more than one sprint, so I've adjusted milestone. It depends on some review time by the rest of the content team. New pages in development and will be sent to content team for review this week on:

- Independent expenditures (from candidate perspective)
- Joint fundraising (from candidate perspective)
- Personal funds of candidate

Also revisions to some registration pages have been sent around to team as well.

**Comment by dorothyyeager** [comment]
Google doc sent to content team for review of the three new pages: https://docs.google.com/document/d/1cDFmzguUTYlm8YKj7y7Zqwr3fE8n45y1KxOLgRpXBhk/edit?usp=sharing

**Comment by dorothyyeager** [comment]
To clarify above, ideas for "revisions to some registration pages" were sent to team. I am working on a doc with the proposed wording from the Guide to send around. So yes, this issue will definitely continue into sprint 6.2.

**Comment by dorothyyeager** [comment]
Google doc sent to content team to review changes to three current pages in candidate registration section: https://docs.google.com/document/d/12mDTK410PMAGW4JvTkRruBNAe98IwO2Hwj4W3K0pZLE/edit?usp=sharing

Affected pages:
- Appointing a treasurer
- Registering a candidate for the House or Senate
- House and Senate candidate committee registration

**Comment by AmyKort** [comment]
Do you need help getting a reviewer for this?

**Comment by dorothyyeager** [comment]
@AmyKort George has reviewed and left comments but just need to know if rest of content team is OK with proposed revisions and new content. (Docs were emailed a few days ago and linked above.) There were a couple of minor questions that it would be good to hear from team on.  @rhoughfec @llienfec 

Once team is onboard, I can start making and updating the pages so that part will be 6.2 work for me.

**Comment by llienfec** [comment]
@dorothyyeager Thanks for the reminder.  I'm hoping to get to this either this afternoon or tomorrow afternoon.

**Comment by llienfec** [comment]
Hey @dorothyyeager: Thanks so much for all of your detailed work on this.  I put some comments in the document.  It may be easier to talk through it together, so take a look and let me know.  You are awesome!!!!

**Comment by dorothyyeager** [comment]
@llienfec and I had a really productive conversation about the proposed new pages. 

With the content team review of the wording done, I'm going to work on updating the registration pages mentioned, and will start setting up the new pages since we know where they'll go in Wagtail.

However, there's an outstanding issue to think through: While the new pages will fill gaps, there are some other outstanding issues with the content architecture that we need to figure out first before they can go live. So we've made a new issue for that work at #2101 .

**Comment by dorothyyeager** [comment]
We've updated the following pages:

- Appointing a treasurer
- Registering a candidate for the House or Senate
- House and Senate candidate committee registration

**Comment by dorothyyeager** [comment]
The content for the new pages on personal funds and independent expenditures is ready. We just need to decide, in #2101, where they're going to go. We are also going to need to update a page on personal loans by a candidate to remove duplicative content and point to the new page.

@llienfec had a good idea regarding the joint fundraising pages, so have moved implementation of that to its own issue at #2111

**Comment by dorothyyeager** [comment]
We will make separate implementation issues for the personal funds and IE pages (we know what they will say) after we decide, in #2101 , where they'll go. The new joint fundraising pages will be tackled in #2111 

With the content work for this task complete, will close and move on to implementation and organization issues mentioned above.
