### ISSUE TITLE
Elections improvements in prep for election season

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#1999]
## WIP to be done
- Improve elections endpoint, major refactor
- Finish election profile page work that was in PI 5.

## Big picture of what we're after
1. Figure out a better way to get users to this election information
2. Enhance our current elections information

### Possible improvements
- Improve ability to get to sections of our elections information, given that this is an election year.
- Document what election features we currently have on our site.
- What are the capabilities on the classic site that we do not currently have for the new website. This would require new feature development, but good to have the list at hand.
- Get list of pain points to elections information
          - Dive into previous UX research done for elections
          - Get more insights from internal stakeholders
- See how we can make the raising and spending charts better.

**Comment by AmyKort** [comment]
We've decided to tackle this issue from a different direction.
