### ISSUE TITLE
Edits to `Where to file by paper` 

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#2002]
The portion that refers to IEs referencing Senate candidates being filed with the Secretary of the Senate is not correct. https://www.fec.gov/help-candidates-and-committees/filing-reports/paper-filing/

Can we please change that particular portion to read: "Senate candidates and committees file with the Secretary of the Senate. All persons and political committees, including committees that support Senate candidates, must file their 24- and 48-hour reports of independent expenditures with the Commission." The revised language comes directly from a recent Record article.

https://github.com/fecgov/FEC/issues/6051

**Comment by dorothyyeager** [comment]
The requested fix has been made so we can close this issue. Both the Guides and the regulations are clear about how IE reports referencing Senate candidates must be filed with the Commission; and the wording in Paul's ticket has been put onto the page as Record articles are reviewed by OGC and RAD.
