### ISSUE TITLE
Swagger user testing

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2003]
API has a bunch of endpoints.  We're dividing and conquering to get this Swagger testing done!

### Testing plan
- [ ] ID endpoints to test
- [ ] Wenchun will divide and give team members to test, high-level test script. (2 story point to assign)
- [ ] Wenchun and @patphongs will run through an example test
- [ ] pull down locally and test (1 story point per person).  Connect to dev to test.

### Things to test
- Open endpoint and get a response back.  
- Make sure it executes.  
- Does bad info return a 500? 
- Required fields are still required.  
- Compare to existing site.

**Comment by patphongs** [comment]
Related to: https://github.com/fecgov/openFEC/issues/3094

**Comment by wjiangFEC** [comment]
@apburnes Rohan and I did a quick test, it looks good to us except the text box seems not populating the items correctly.  The items are there in the text box but did not display correctly.

**Comment by apburnes** [comment]
@wjiangFEC can you elaborate on which routes and/or data types should be looked at to test the text box functionality?

**Comment by patphongs** [comment]
Issue moved to [fecgov/openFEC #3170](https://github.com/fecgov/openFEC/issues/3170) via [**ZenHub**](https://www.zenhub.com/)
