### ISSUE TITLE
Add automated JS test for elections

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2005]
Backfill test for Javascript we have developed - this is for the Election Pages.
1 pt for Andrew

-[ ] write test for elections

**Comment by apburnes** [comment]
Refactoring `elections.js` page to be a minimal series of modules and then testing the modules that build the page.

**Comment by apburnes** [comment]
New PR #2126

**Comment by apburnes** [comment]
This issue is closed by #2126
