### ISSUE TITLE
Research and break out all the issues causing 2020  data not to show

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2007]
We need to turn on the 2020 data.  Have had reports that turning it on locally still does not return data. It looks like we may have complementary (or conflicting) work on this issue, so let's tackle this with https://github.com/fecgov/fec-cms/issues/1949 in mind.

**Comment by patphongs** [comment]
We need to research all the different places to turn on 2020 data for. @JonellaCulmer Can you please flesh out this for us and split them up into workable issues?

**Comment by JonellaCulmer** [comment]
This work is split up in the following issues: 
**#1949** Presidential candidate raising breakdown not consistent with advanced data table (WIP)
**#1950** Presidential 2017-2020 on advanced data table not displaying properly (WIP)
**#2085** 2019-2020 and 2021-2022 options on election dropdown, but no data (removing options for now, pushing fix for later sprint)
**#2087** Enable 2019-2020 on election search dropdown (pushed for later sprint)
