### ISSUE TITLE
Port Litigation PDF

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#2009]
Port Litigation PDFs from transition buckets to fec.gov buckets.

**Comment by patphongs** [comment]
@dorothyyeager The litigation documents have been ported over to the wagtail CMS bucket. Please let the litigation team know to upload files to wagtail from now on. And link to them using this URL string: `https://www.fec.gov/resources/cms-content/documents/[pdf_name].pdf`. 

We don't really need to update the other URLs, we can catch that in our scraping or I can do a mass search and replace for those old URLs and update those to re-upload to transition. We can make that call later on.
