### ISSUE TITLE
Research to see if we can use candidate/totals endpoint instead  of elections endpoint

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#2010]
Activate export function on these features on the election profile pages:

- [ ] elections
- [ ] ind contribs
- [ ] sch a by size

Might require backend work.

example
https://www.fec.gov/data/elections/house/AL/01/2018/#candidate-financial-totals

**Comment by AmyKort** [comment]
@JonellaCulmer  Can you provide the links?

**Comment by JonellaCulmer** [comment]
@fec-jli
The data sets that require export functions are all found on House and Senate election profile pages, currently on the feature site.

These pages are all results from the elections search, here: https://www.fec.gov/data/elections/

Here are some example pages: 
https://fec-feature-cms.app.cloud.gov/data/elections/senate/AL/2018/
https://fec-feature-cms.app.cloud.gov/data/elections/house/AL/01/2018/

**Comment by fec-jli** [comment]
Thanks @JonellaCulmer  
Can you tell me the branch name or PR# for those changes on feature space?
I need checkout to my local and find where to enable export link.
Thanks

**Comment by JonellaCulmer** [comment]
No problem,@fec-jli It's here: https://github.com/fecgov/fec-cms/pull/1984

**Comment by fec-jli** [comment]
This Issue involves changes on both fec-cms and openFEC.
### setup env locally
1) checkout fec-cms branch:  feature/enable_export_link_candidate_info
export FEC_WEB_API_KEY_PUBLIC=xxxxxxx
export FEC_WEB_API_KEY=xxxxxxx
export FEC_CMS_ENVIRONMENT=LOCAL
export FEC_API_URL=http://localhost:5000
export DATABASE_URL=postgresql://:@/cfdm_cms_test

2)setup openFEC local (env api variables)
export SQLA_CONN=xxxxxxx
export access_key_id=
export secret_access_key=
export bucket=
export region=

3)start redis-server
4)Setup Celery Worker and start
export SQLA_CONN=xxxxxxx
export access_key_id=
export secret_access_key=
export bucket=
export region=

5)example url: http://127.0.0.1:8000/data/elections/senate/AL/2018/
Click "Export" on Candidate financial totals section, download the file.

**Comment by fec-jli** [comment]
### Datatable  sections info:
**1)Candidate financial totals**
**2)Candidate Information**
**tag:** _financial_
**path:** _elections_

**endpoint:** _elections.ElectionView_

**model:** 
totals.CommitteeTotalsPresidential
	ofec_totals_presidential_mv
totals.CommitteeTotalsHouseSenate
	ofec_totals_house_senate_mv

elections.ElectionResult
	ofec_election_result_mv

**Comment by fec-jli** [comment]
In order to make download function work, we have to refactor ### elections.ElectionView endpoint.

The ElectionView is a very complex endpoint which includes two multi-level MVs: **ofec_totals_house_senate_mv and ofec_totals_presidential_mv**
and many SQLAlchemy ORM functions. it looks like a big job. so we need prioritized.
Thanks @Vraj to review this issue.

**Comment by fec-jli** [comment]
I will close this ticket. 
open two new tickets, one for refactoring elections endpoint on openFEC side.
another is enable "export" link on cms side.

**Comment by PaulClark2** [comment]
@fec-jli I re-opened this issue. Where's the issue doesn't include a discussion about refactoring an endpoint. Is that discussion going to in the new ticket? Is refactoring the best option?

**Comment by fec-jli** [comment]
@do we need create a new issue for cms repo? or keep this Issue? just change title to:
**Enable export link for candidate financial totals on election summary page.** ? Thanks

**Comment by PaulClark2** [comment]
I've created a new issue for the front-end work.
