### ISSUE TITLE
Fix Migrations and Switch to PyTest from Django

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2011]
Right now we're using Django tests and we want to change to PyTest.  We need help moving it over and writing tests.  

### Potential problems
Tests aren't running in the order we need them to.  Potentially need to figure out why the order matters.  Work for @annalee and @patphongs 

### Additional info:
**Blocker:**  This is part of the Wagtail showstopper issue.

**Future work:** Train the devs on writing these tests training each other.

**Comment by AmyKort** [comment]
@annalee  Can you help us split up this ticket?

**Comment by annalee** [comment]
This ticket has been split into #2040 and #2041.
