### ISSUE TITLE
Meet with AF and ADRO re: pay.gov

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2017]
Meet with AF and ADRO on request to add pay.gov information to the website.

**Comment by AmyKort** [comment]
Had a great meeting with AF. We're not going to add additional pay.gov links to the Enforcement section. However, we'll create orphan wagtail pages our ADRO and enforcement offices an use to help respondents who need that access. I'm closing this ticket, and will open a new one when we get more information on implementation of the orphan pages.
