### ISSUE TITLE
Find existing nat'l research 

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2019]
What we want:
We want to gather all existing research on National election pages (Jonella has sketch file. Lauren was in design session.)  
Why we want it:
So we can move forward with putting together the national election presentation

**Comment by llienfec** [comment]
All of the stakeholder/user research, synthesis, and design studio drafts from March - July 2017 are saved in the Elections-Map folder in the shared drive.  The issue was (at least partially) covered here: https://github.com/18F/openFEC-web-app/issues/2164#issuecomment-314893130

From what I remember about the design studio, we thought a lot about what users were looking for on a page and what the research said users wanted to do with comparison info. Through the drawing process and conversations about ideas, we generally came to the conclusion that we needed to build strong pathways from district to state to national comparisons (and back) because 1) users were looking for comparisons at lots of levels, and 2) once a user answer a question like "what's happening in this district?" the answer often leads the user to another question that changes the scale of the comparison, like "is the same thing happening at the state level?"

**Comment by JonellaCulmer** [comment]
Additional research on elections related data can be found summarized in this issue: https://github.com/fecgov/fec-cms/issues/1978 

Beyond the existing research, additional research on how users are navigating to our elections data must be conducted. A separate issue will be created and linked here.

**Comment by llienfec** [comment]
We've collected all of the prior research and @JonellaCulmer has a great plan for filling in what's missing and where we need research as next steps.  Closing issue.

**Comment by JonellaCulmer** [comment]
Additional research on navigation to nation-wide election data from https://github.com/fecgov/fec-cms/issues/2033

### Findings

- All of our users tested visit FEC.gov frequently and are interested in what committees are reporting they raised and spent. 
- When asked where they would go for big picture data, all three immediately wanted to look under the advanced data section to find what they were looking for. 
- While all three users are expressed interest in different datasets, they all wanted to be able to drill down the data to find specific information. 
- All three users were successful in finding the individual contributor information, albeit from different directions. 
- Users continue to try to search for elections using the global search, such as "ca house 44" or "us house 27"

### Recommendations
- Explore incorporating high-level summary visualization on advanced data pages
- Explore enhancing global search to find elections
