### ISSUE TITLE
Fix rich text editor (RTE) issues in Wagtail 2.0

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2024]
**What we're after:**

Initial testing of Wagtail 2.0 has revealed some issues with the rich text editor and other minor features. There are workarounds for these, so fixing them shouldn’t hold up use of Wagtail 2.0. They seemed to be common to all of the templates that use the editor.

- Glossary button only works if the term is exactly like it is in the glossary. (That is not usually the case; for example, a word like contribution might be pluralized, or a phrase like “coordinated communication” might be put as “communication that is coordinated.”) While editing can serve as a work around, we would need html editor ability to code glossary to keep it from looking funny.
- When copied from block to block, the glossary term remained bolded, but was no longer coded as a glossary term.
- When adding external links, the link text box does not populate with the text that is selected.
- In some of the templates, you could not indent the bulleted or numbered lists by pressing tab.
- The embed button works but doesn't use the embed source code that youtube provides. Instead you put in the URL. A ton of white space appears below the video when viewed. (As a workaround, we can use the embed code with an html block.)
- The horizontal line button did not yield a horizontal line on the page when rendered in preview (although you could see the line in Wagtail). It also had a lot of extra space above it.
- Some templates don’t permit an internal link to be used when one is available.
- Sometimes line break did not copy/paste between blocks.
- Inserting an image into the text did not work.

**Other issues**

- Pages that use “contribution limits snippet” - Rename that tool as “snippet” as we are hoping to use other snippets too.
- A feature link that was previously sent to OGC and worked no longer worked after the reset.

**Background:**

Initial testing of Wagtail 2.0 page templates and notes: #1973
Write-up of dealbreakers and issues in Rich Text Editor found during initial testing of all templates: https://docs.google.com/document/d/1fgxx9oTEXunm7scqyqJRDF5bG-z45eXO1VkOLwSa8Zw/edit?usp=sharing
Related Django and Wagtail updating issues: #1538 and #1968
Wagtail 2.0 and hard coded pages #1994
HTML editor issue #1971
Python tests failing #1972
The content team's Wagtail wish list: https://docs.google.com/document/d/1HM1-SaxAL-pVhzwQY8ZP-1uA8bVlbAxwFhqW4f-3lAo/edit

Completion criteria:

[ ]

**Comment by llienfec** [comment]
One thing that @dorothyyeager and I really need is ability to use anchor links - whether in the editor OR in HTML.  It looks like Wagtail is currently enabling this functionality and the work is tracked here:
https://github.com/wagtail/wagtail/issues/1049

Not sure if something in their discussion is helpful or if you need us to reach out to their team about a time frame.  Happy to do it.

**Comment by AmyKort** [comment]
What's the status of this issue?

**Comment by apburnes** [comment]
Most of the issues are resolved in https://github.com/fecgov/fec-cms/pull/1968. The HTML editor issue #1971 is the only not addressed and should be reprioritized.

**Comment by AmyKort** [comment]
Thanks!

**Comment by apburnes** [comment]
Closed issues are resolved by #1968
