### ISSUE TITLE
Incorrect contributor name showing up on receipts

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2028]
A user contacted me with a data issue where the incorrect name is showing up in C00624692's receipts list.
https://www.fec.gov/data/receipts/?two_year_transaction_period=2016&data_type=processed&committee_id=C00624692&min_date=01%2F01%2F2015&max_date=12%2F31%2F2016

During the 2016 cycle, the committee reported an in-kind contribution for Gary Johnson for Congress, using the vendor Biz Talk Radio Network.  On the committee's receipts list, Gary Johnson for Congress shows up as the contributor when Biz Talk Radio Network should actually show up as the contributor.  This happens 3 times.

![image](https://user-images.githubusercontent.com/22914750/40681391-fb73cd7e-6356-11e8-9b27-b015db48e0de.png)

**Weird wrinkle:** If you export this data set, the correct contributor shows up.

**Comment by jwchumley** [comment]
After consulting with RAD I've deleted the 15Z code from these two transactions. They are misreported and were miscoded. After tonight they should appear with the correct (incorrect because they are reported wrong) names.

**Comment by jwchumley** [comment]
These are corrected. There was another with the same issue.  To sum up:
1. Coded as 15Z but should not have been coded (this didn't cause the name issue)
2. Contrtibutor ID was Gary Johnson for Congress ID and it should have been null (this caused the name issue)

There is logic built in to handle transactions that actually SHOULD have a contributor ID  like IEs where the place you spend the money is less important than who you were supporting or opposing and that logic is tripped up when there is a contributor ID where there shouldn't be one.
