### ISSUE TITLE
Create better paths to eFliling help

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2030]
To help users find help with trouble shooting eFiling issues, let's create a link at https://www.fec.gov/help-candidates-and-committees/filing-reports/ under "trouble shooting" with language like "Help with FECFile" that sends users to the general FECFile page that has all of the help manuals, troubleshooting links, and youtube videos.

https://www.fec.gov/help-candidates-and-committees/filing-reports/fecfile-software/

**Comment by llienfec** [comment]
Added "Help with FECFile" link under the Troubleshooting pages for:
- [x] Filing candidate reports
- [x] Filing PAC reports
- [x] Filing party reports
- [x] Filing SSF reports

Closing issue since work is finished.
