### ISSUE TITLE
Random 404 errors on "Explore all compliance resources" link in drop down Help for Candidates and Committees (IE only)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2034]
Kathy Carothers in Information reported this error and when I checked I found it happening too. When you click on the drop down menu for Help for candidates and committees, and then click "Explore all committee resources" - sometimes when this is done in Internet Explorer, it returns a 404 page not found error. It doesn't happen everytime and the link always works in Chrome or Firefox, so it seems limited to IE. 

I did notice a strange URL when I hoved the mouse over the link in IE and right-clicked it to copy - https://www.fec.gov/help-candidates-and-committees/help-candidates-and-committees/help-candidates-and-committees/help-candidates-and-committees/help-candidates-and-committees/ . When I do the same in Chrome or Firefox, I get the correct URL of https://www.fec.gov/help-candidates-and-committees/.

Completion criteria:
- [x] Investigate the 404 error in IE and what might be generating that strange URL
- [x] Make any fixes needed

**Comment by johnnyporkchops** [comment]
This because this link needs to be relative to the top level, not to the page it is on--needs a leading slash
So 
 ` help-candidates-and-committees/ `
Needs to be changed to 
` \help-candidates-and-committees/ `

**Comment by dorothyyeager** [comment]
Thanks @johnnyporkchops !
