### ISSUE TITLE
Add main landing pages to mobile menu

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2036]
So that mobile & tablet users (along with users working in condensed browser windows) can access the great landing pages, add:
- [ ] Explore all data link to the collapsed CFD menu
- [ ] Explore all compliance resources to the collapsed H4CC menu
- [ ] Explore all legal resources to the collapsed Legal menu

### Current campaign finance data collapsed menu
Note it doesn't have the "explore all data" link.
![image](https://user-images.githubusercontent.com/22914750/40843612-922beb14-657f-11e8-9b85-6088c448f425.png)

### Current full campaign finance data menu
![image](https://user-images.githubusercontent.com/22914750/40843660-ba541b48-657f-11e8-8201-cb8ba1aef0e3.png)

**Comment by AmyKort** [comment]
closing in favor of https://github.com/fecgov/fec-cms/issues/2083
