### ISSUE TITLE
Derive changes from research for Nation-wide Data visualizations

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#2046]
**What we're after:** Following the design studio in 6.2, we need to derive changes from research for nationwide data visualizations. This synthesis should primarily support work that can be accomplished during this PI (short-term) but while also considering long-term solutions to keep in mind as we iterate in the future. 

We will derive these changes from the following research: 
- [ ] Design studio with stakeholders
- [ ] Previous elections research
- [ ] Nationwide election navigation research

**Comment by JonellaCulmer** [comment]
This work is not currently relevant to our PI goals. Closing for now.
