### ISSUE TITLE
Implement - Committee Profile pages - RFAI placement

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#2048]
RFAIs for 24/48 hour Form 5 notices are not showing up in the filings for the committee profile pages. Because the API is serving them up I think there is a front end filter condition that is excluding them.

Here is an example:  https://api.open.fec.gov/v1/committee/C90017450/filings/?form_type=FRQ&sort=-receipt_date&report_year=2018&api_key=DEMO_KEY&page=1&per_page=20

There are 2 RFAIs coming out of the API endpoint but only one of them is showing up on the web page. The one Request_type=7 is correctly showing up with the regular reports but the one Request_type=2 is not showing up at all and should show up with the 24/48 hour notices on this page: https://www.fec.gov/data/committee/C90017450/?tab=filings

![image](https://user-images.githubusercontent.com/12615919/42344888-abdf3dde-806b-11e8-99bc-379c603505fc.png)

- [x] Work with RAD to find examples 
- [x] Identify cause (API issue, CMS issue or data issue)
- [x] If data issue, correct data
- [x] Fix 24/48 hour report table to display RFAIs of request_type=2

**Comment by patphongs** [comment]
@jwchumley @JonellaCulmer I'm going to need some more clarification and help grooming this ticket:

> 1. RFAIs for 24/48 Hour F5s are not showing up on the website.

Jeff could not find any examples. He has emailed RAD for any examples they have on these not showing up.

> 2. RFAIs if at all possible should fall below a filing not above it, despite the filters. This is the case for RQ-1s and RQ-2s.

24/48 hour reports are currently separated into a different table. I'm not sure what they mean by having it show above the filings. The regular filings show up under the "Regularly filed reports" table. Whereas the 24/48 hour reports show up in a separate table, are there additional filings that are supposed to be in that table?

Regularly filed reports table are bringing in the following form types:
`form_type: ['F3', 'F3X', 'F3P', 'F3L', 'F4', 'F5', 'F7', 'F13', 'RFAI'], 
report_type: ['-24', '-48']`. EXCLUDES 24/48 hour F5 reports from this table.

24/48 hour reports table are bringing in the following form types:
`form_type: ['F5', 'F24', 'F6', 'F9', 'F10', 'F11']`. INCLUDES 24/48 hour F5 reports.

> 3. If the RFAIs could be indented or use different text it would set them apart. We should draw users to the fact that correspondence sent by the Commission is not a filing.

These are 2 requirements that are unclear. 

1. RFAIs currently have the `RFAI:` within the text of the link to distinguish it already. 
2. Looks like we need design/content to look at this and see how we can accomplish this.: "We should draw users to the fact that correspondence sent by the Commission is not a filing."

**Comment by JonellaCulmer** [comment]
@jwchumley Reassigning to you, as we are at a point of being blocked an unable to replicate some of the issues.

**Comment by jwchumley** [comment]
@patphongs  See the completely edited description at the top. I'm pretty sure it is that the front end call is leaving out request_tp=2 and they should be listed in the 24/48 hr notice section.
