### ISSUE TITLE
Research: Identify major gaps in fec-cms JS tests

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#2052]
Research: Identify major gaps in fec-cms JS tests

**Completion criteria:**
- [x] Research existing JS tests to see what they do
- [x] Hold a meeting to establish a clear path and best practices for JS tests going forward
- [x] Create a list of JS tests that still need to be built or modified

**Comment by apburnes** [comment]
Strategy write up #2113

**Comment by jwchumley** [comment]
@apburnes  SHould we close this one in favor of  the frontend js testing strategy ticket?

**Comment by apburnes** [comment]
@jwchumley Sounds good. 👍We can Incorporate #2113 as a rough outline for a new ticket.
