### ISSUE TITLE
Add historical stats to data menu

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#2054]
To improve usability, Add historical stats to data menu and label it "Historical statistics" - it should go to https://www.fec.gov/data/advanced/?tab=historical

![image.png](https://images.zenhubusercontent.com/59563d2061b4ca3b0a72d03d/1d71ce52-58dd-41d7-996e-18ca9b306f41)

**Comment by lbeaufort** [comment]
Addressed by https://github.com/fecgov/fec-cms/pull/2180
