### ISSUE TITLE
Research/design: Add filings tab to candidate profile page

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#2055]
To make it more consistent across committee and candidate profiles, move the candidate form 2s from the "about" tab to a new "Filings" tab.

- [ ] remove form 2's and disavowal notices from About tab
- [ ] Create filings tab and include form 2s and disavowal notices

Make sure image number is included in the display

**Comment by JonellaCulmer** [comment]
In conjunction with moving the filings to a separate Filings tab, I recommend we leave the latest Form 2 filing listed under `About this candidate` as well. Our users currently know to look in this section for a candidate's Form 2. But at the same time it seems unnecessary to list **all** previous versions of the form. For some candidates, that can be upwards of a dozen different versions and thereby pushing other content down. Specifically, a candidate's authorized committees. 

On the filings tab, the format should match that of the committee's pages and order the tables Form 2 "Statements of candidacy", then "Other documents" which will include disavowal notices, as originally listed in the initial comment.

Table columns should be organized in the following order:
- Document
- Version
- Date filed
- Image number _(new)_
- Pages

@jwchumley The work/recommendation related to keeping the latest form 2 on the About this candidate page, may coincide with work that needs to be completed here: https://github.com/fecgov/openFEC/issues/3096 Which is curerntly on the roster of potential taskd for 6.4.

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issue: https://github.com/fecgov/fec-cms/issues/2154
