### ISSUE TITLE
Identify gaps in python tests in fec-cms

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#2058]
Identify gaps in python tests in fec-cms

Sticky says John and Andrew and also something that looks like it might say Priya

**Comment by PaulClark2** [comment]
@annalee what's the status of this issue?

**Comment by jwchumley** [comment]
New issue should be created about which python tests need to be created. Look into API caller python file to check what calls are being made and create tests. Then close this issue.

**Comment by annalee** [comment]
Sorry--I've been on leave. There are two working tests in the CMS, so yes, at this point it's about creating a test-backfilling strategy. API calls are a good place to start.
