### ISSUE TITLE
Add reference to GovDelivery variable in settings

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#2064]
Gov delivery token has been updated to user provides service (UPS) on cloud foundry.
It needs to be referenced in settings.py and, for consistency, changed in the template:
https://github.com/fecgov/fec-cms/blob/develop/fec/home/templates/home/latest_updates.html

**latest_updates.html:** Change `GOV_DELIVERY_TOKEN` to `GOVDELIVERY_TOKEN`
`{{ settings.GOVDELIVERY_TOKEN }}`

**settings.py, add:**
`GOVDELIVERY_TOKEN = env.get_credential('GOVDELIVERY_TOKEN')`

**Comment by JonellaCulmer** [comment]
This work has been merged, so closing.
