### ISSUE TITLE
Raising and spending breakdown back button issue

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2066]
When on the raising or spending breakdown charts with anything other than presidential selected. If you click on a candidate and navigate away from the spending and raising breakdown page and then press the back button, the office displayed in the dropdown does not match the actual data that is displayed on the chart.

https://www.fec.gov/data/raising-bythenumbers/
https://www.fec.gov/data/spending-bythenumbers/

![breakdown-bug](https://user-images.githubusercontent.com/12799132/41065071-756eff68-69ab-11e8-97de-2594eed84f66.gif)

**Comment by AmyKort** [comment]
In re-implemented chart, back button doesn't function in this way. Closing.

**Comment by JonellaCulmer** [comment]
@AmyKort I'm looking at the by the numbers pages and this issue and I'm still observing this issue. So reopening.
