### ISSUE TITLE
Update outdated building images on homepage and contact page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2067]
**What we're after:** Following our move to the new HQ location at 1050 1st Street, we need to update our imagery, replacing the old photos from our location at 999 E Street. 

- [X] review existing photos
- [ ] take new photos if necessary, make recommendations
- [x] photo review with PMs, internal stakeholders
- [ ] add to implementation issue

**Comment by JonellaCulmer** [comment]
Here are some options for both the homepage and contact page. 

**Homepage:** My recommendation would be for the first image, with ceiling
![hearingroom_ceiling](https://user-images.githubusercontent.com/31663028/41121359-24953c04-6a66-11e8-9948-2cfc329d769e.jpg)

![hearingroom_noceiling](https://user-images.githubusercontent.com/31663028/41121360-24a47836-6a66-11e8-862d-7ac275887b17.jpg)

**Contact page:** 
![background_seal](https://user-images.githubusercontent.com/31663028/41121390-3ca81776-6a66-11e8-9afb-b8fdb43f0aed.jpg)

![building_1050](https://user-images.githubusercontent.com/31663028/41121391-3cb5026a-6a66-11e8-8495-a660e3e4c628.jpg)

**Comment by JonellaCulmer** [comment]
@AmyKort I've thought about that and we can explore other non-FEC type images. For example, we used the Washington Monument on our beta homepage. Any interest in a more "DC" type photo?

We can also explore more specific imagery, such as a indistinguishable candidate or possibly an event similar to what's being used on the homepage for the citizen's guide. Happy to continue to explore other options and look forward to additional guidance from @wluoFEC @jwchumley @PaulClark2 as well.

**Comment by wluoFEC** [comment]
My recommendation is to use the first image without changing the concept/design for the homepage for now.  @JonellaCulmer @AmyKort

**Comment by JonellaCulmer** [comment]
Moved to an implementation issue, so closing. 

Implementation issue: https://github.com/fecgov/fec-cms/issues/2078
