### ISSUE TITLE
Disable/hide/remove top raising candidates in 2017–2018

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#2068]
**What we want**:
Remove "top raising candidates in 2017-2018" list.
https://www.fec.gov/data/
![image](https://user-images.githubusercontent.com/11817734/41170036-d0a81fae-6b18-11e8-9752-a455e5e28d69.png)

**Why we want it**:
This list is incorrect. We will remove it until we are able to correct the underlying data issues. 

**Completion criteria**:
- [ ] remove list

**Comment by AmyKort** [comment]
Merged, so closing.
