### ISSUE TITLE
Disable/hide/remove possible uses of this data

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#2069]
**What we want**:
Remove "possible uses of this data: list.
https://www.fec.gov/data/
![image](https://user-images.githubusercontent.com/11817734/41170724-9440a3ee-6b1b-11e8-86c4-ae971dea9513.png)

**Why we want it**:
The list was added primarily to provide balance on the page with the "Look up candidate and committee profiles" box.  We will be removing the "top raising candidates" list. This should maintain visual balance. 

**Completion criteria**:
 - [ ] remove list

**Comment by AmyKort** [comment]
Merged, so closing
