### ISSUE TITLE
Disable/hide/remove trending elections list

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#2070]
**What we want**:
Remove "trending elections" list. 
https://www.fec.gov/data/
![image](https://user-images.githubusercontent.com/11817734/41170818-02157296-6b1c-11e8-8646-3401d43398c2.png)

**Why we want it**:
Trending elections is not defined and the Commission is not going to define the term. 

**Completion criteria**:
- [ ] remove list

**Comment by AmyKort** [comment]
Merged, so closing
