### ISSUE TITLE
Disable/hide/remove raising line chart

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#2071]
**What we want**:
Disable/hide/remove raising line chart. 
https://www.fec.gov/data/
![image](https://user-images.githubusercontent.com/11817734/41170971-c24dfc0e-6b1c-11e8-91f7-7f9859e6b396.png)

**Why we want it**:
The line chart displays incorrect data. 

**Completion criteria**:
- [ ] remove raising line chart

**Comment by AmyKort** [comment]
Merged, so closing
