### ISSUE TITLE
Disable/hide/remove spending line chart

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#2072]
**What we want**:
Disable/hide/remove spending line chart.
https://www.fec.gov/data/
![image](https://user-images.githubusercontent.com/11817734/41171092-47de5058-6b1d-11e8-8050-c788b445f505.png)

**Why we want it**:
The line chart displays incorrect data.

**Completion criteria**:
- [ ] remove spending line chart

**Comment by AmyKort** [comment]
Merged, so closing
