### ISSUE TITLE
Disable/hide/remove raising breakdown

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#2073]
**What we want**:
Disable/hide/remove raising breakdown.
https://www.fec.gov/data/raising/
![image](https://user-images.githubusercontent.com/11817734/41171189-a85cbe88-6b1d-11e8-993f-7f3b5a3d8376.png)

**Why we want it**:
The raising breakdown displays incorrect data.

**Completion criteria**:
- [ ] remove raising breakdown

**Comment by AmyKort** [comment]
Merged, so closing
