### ISSUE TITLE
Disable/hide/remove spending breakdown

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#2074]
**What we want**:
Disable/hide/remove Spending breakdown.
https://www.fec.gov/data/spending/
![image](https://user-images.githubusercontent.com/11817734/41171280-fde43ec6-6b1d-11e8-8e13-4053cd6a7155.png)

**Why we want it**:
The spending breakdown displays incorrect data. 

**Completion criteria**:
- [ ] remove spending breakdown

**Comment by AmyKort** [comment]
Merged, so closing
