### ISSUE TITLE
Idea to make reporting examples easier to find and share

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2080]
@fec-issues-bot commented on [Fri May 25 2018](https://github.com/fecgov/FEC/issues/6077)

## What were you trying to do and how can we improve it?
 I received a call from a candidate committee that wanted to see reporting examples, but could not get to them on the website.  There does not seem to be an easy way to find them, and no specific link for reporting examples I could provide to the committee.  Currently, the user would have to go to "Filing Reports" (https://www.fec.gov/help-candidates-and-committees/filing-reports/) and scrolling way down on that page.  This is not easily accessible. 

## General feedback?
 It would help to make the reporting examples have a separate link and make them more prominent by putting a link in the top portion of the "Filing Reports" page, so it's visible on the screen when the user first accesses it. 

## Tell us about yourself
 I am a RAD manager who responds to questions from committees by phone. 

## Details
* URL: https://www.fec.gov/ 
* User Agent: Amazon CloudFront

---

@AmyKort commented on [Fri May 25 2018](https://github.com/fecgov/FEC/issues/6077#issuecomment-392088551)

The reporting examples are a great resource--we're really proud of them. Thank you for the thoughtful feedback about how to make them easier to find!

cc @llienfec

**Comment by llienfec** [comment]
User needs an easier, faster way to get committees to reporting examples.  We discovered that although we can't make anchor links in Wagtail (YET), we can make links to the section headers on pages that are made with the resource link.  

Since all teams are busy on other features, we'll try this MVP solution and see if it works for users.

### To do:
- [ ] Get resource page anchor link (/#title-of-section-header)
- [ ] Find a shorter link that makes sense for reporting example pages (will need to specify committee type)
- [ ] Make a redirect in Wagtail

**Comment by llienfec** [comment]
I worked with the Authorized Branch Chief to come up with a link name that they can use with committees to easily direct them to reporting examples.  

The simplified link:
www.fec.gov/candidate-reporting-examples 

is now redirected to the bottom of `Filing candidate reports`:
https://www.fec.gov/help-candidates-and-committees/filing-reports/#reporting-examples

Also made parallel shortcuts in wagtail for PAC and SSF reporting examples:
www.fec.gov/PAC-reporting-examples
www.fec.gov/SSF-reporting-examples

Will make the shortcut for parties when we start writing those examples.

**Comment by llienfec** [comment]
@dorothyyeager I'm going to email you a request to help publicize the link as a Tip for Treasurers.  Maybe language something like this?

> Reporting examples for candidates are linked throughout Help for Candidates and Committees, but you can find a complete list of all available examples at www.fec.gov/candidate-reporting-examples.

**Comment by llienfec** [comment]
Revised language requested.  Sent to Info, so I'm going to close out this ticket since it's no longer website team work.  Thanks all!

> Reporting examples for candidate committees are now available on the FEC website.  You can find a complete list of all available examples, including how to report various categories of receipts and disbursements, at www.fec.gov/candidate-reporting-examples.  The links to candidate reporting examples also appear in “Filing candidate reports” under Help for Candidates and Committees.   

(Filing candidate reports will link to that section)
