### ISSUE TITLE
Add missing features to mobile menu

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2083]
So that mobile & tablet users (along with users working in condensed browser windows) can access the great landing pages, add:

- [x] Site Search  
- [x] Explore all data link to the collapsed CFD menu
- [x]  Explore all compliance resources to the collapsed H4CC menu
- [x]  Explore all legal resources to the collapsed Legal menu

Background is at https://github.com/fecgov/fec-cms/issues/1827 and https://github.com/fecgov/fec-cms/issues/2036

**Comment by JonellaCulmer** [comment]
Below are the mock-ups for the updated menus that incorporate search and add in links to each of the landing pages. 

### Menu at the first break, tablet size
![mobile menu - 1st break](https://user-images.githubusercontent.com/31663028/41370905-dab7ad00-6f16-11e8-944a-aa6a7166a5a8.png)

### Menu at the second break, phone size, collapsed accordion 
![mobile menu - 2nd break collapsed](https://user-images.githubusercontent.com/31663028/41370906-dac70c64-6f16-11e8-87bc-5ceb9297ab0a.png)

### Menu at the second break, phone size, expanded accordion
![mobile menu - 2nd break expanded](https://user-images.githubusercontent.com/31663028/41370907-dadaa616-6f16-11e8-903a-50986f5bbfbd.png)

**Comment by johnnyporkchops** [comment]
@JonellaCulmer, What are you r thoughts on removing the larger flag icon for the "Explore all" links in the mobile menu?  Its complicated to realign the spacing at that size to balance that with the other items. Also this goes along with the idea of minimal use of extraneous visual elements in mobile size. 
![pr_scrnsht](https://user-images.githubusercontent.com/5572856/41474750-d51cb8d4-708a-11e8-8e2e-41de4f1bb8c9.gif)
