### ISSUE TITLE
Determine approach to embedding open meeting livestreams

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2084]
@jjonesfec has been testing using a YouTube livestream for open meetings of the Commission. It's time to consider how to best use these. 

See https://github.com/fecgov/FEC/issues/5460 for background.

**Completion criteria:**
- [x] Fix html block issue noted in comment below.
- [ ] Decide if we want to embed the livestreams once the Wagtail issue is solved.

**Comment by dorothyyeager** [comment]
We've just discovered a new problem with the meeting page template, both in the current version of Wagtail and in Wagtail 2.0. Will add this to the content team's document referenced in #1994 and in #2006 .

At the bottom of the template is a place where we should be able to insert a "html block" which we could use to copy/paste the embed code from YouTube. The html block portion of the template is not configured properly and we're unable to do that.

It looks like this when you are on the Wagtail editor:
<img width="714" alt="meetingpagehtmlblock1" src="https://user-images.githubusercontent.com/24437369/41364511-f5b38bf4-6f04-11e8-9b67-e7fc6249c115.PNG">
 When you click "html block" you get a white space that you can't copy/paste into:
<img width="646" alt="meetingpagehtmlblock2" src="https://user-images.githubusercontent.com/24437369/41364542-03eb5274-6f05-11e8-9701-207e5b940cc4.PNG">

It should work like it does on the Record page template - you select "html" as a block and get this space you can copy/paste into:
<img width="734" alt="htmlblockworkinginrecordpagetemplate" src="https://user-images.githubusercontent.com/24437369/41364582-1961f5b8-6f05-11e8-977d-42f1140a4133.PNG">

**Comment by johnnyporkchops** [comment]
@dorothyyeager , This html block is not for adding content to the page. It is for importing the scraped content from old meetings. It would be nice to hide it on the template so content editors do not click on it, it has been left accessible for older meetings on the outside chance that we want to edit it or correct how the scraped content renders.
If we want to add an html block, for embedding youtube, we can edit the template model to do that. You could test it now using the text-area RTE, html option.

**Comment by dorothyyeager** [comment]
Updating the issue after speaking with @johnnyporkchops . Will put in a separate issue for what's needed for the meeting page template to make embeds work. This will return to being an issue to think about when/how to begin using them.

**Comment by johnnyporkchops** [comment]
Or since @dorothyyeager does not have a local instance, could test this in dev, or feature for 2.0

**Comment by dorothyyeager** [comment]
Tested adding the html embed code to the html content block on an old meeting in both dev and feature. It worked in dev but not in feature (possibly a Wagtail 2.0 thing?). @johnnyporkchops

**Comment by dorothyyeager** [comment]
Closing this issue in favor of #2166, where the work will be done to enable the meeting page template to do this.
