### ISSUE TITLE
Research: Identify which candidates are affected by incorrect candidate financial totals

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2088]
**What we're after:** This issue was brought to our attention during a stakeholder review that stated: 

> Incumbent totals for receipts and disbursements do not match once you click their name. Same results seem for a number of pages

Figures on candidate profile pages and the data that's on classic match. It is only the data that is displaying on the candidate financial tables that are appearing incorrectly. At face value it does appear that only incumbents are affected.

To leave no stone unturned, and verify whether it is in fact just incumbents who are affected, we need to check as many candidates as possible and check who is not displaying financials accurately on the candidate financial totals table. 

**Example:**
_Incumbents_
**FEC.gov/Classic.fec.gov**
California - Senate - FEINSTEIN, DIANNE
Total receipts: **$9,953,612.00/$9,631,512**
Total disbursements: **$5,342,658.00/$5,022,073**
Total cash on hand: **$7,035,307.00/$7,033,794**

**FEC.gov/Classic.fec.gov**
Alabama - House 1 - BYRNE, BRADLEY ROBERTS
Total receipts: **$853,285.97/$813,286**
Total disbursements: **$529,489.16/$490,482**
Total cash on hand: **$770,222.37/$769,122**

**Comment by jwchumley** [comment]
Any candidate that had joint fundraisers was probably affected as the joint fundraising committees were being included in the aggregates thus inflating the amounts.  I adjusted the SQL locally to remove the joint fundraisers and to remove the unverified candidates and tested it against all 2018 house and senate candidates. It should correct Presidentials too but I haven't yet tested them.

Here are details: https://github.com/fecgov/openFEC/issues/3221
