### ISSUE TITLE
bad link in bulk data documentation

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2091]
@jschachter commented on [Tue Jun 12 2018](https://github.com/fecgov/FEC/issues/6155)

at https://www.fec.gov/campaign-finance-data/contributions-committees-candidates-file-description/

the brown breadcrumb link for "campaign finance data" links to a 404. it should link to /data/

**Comment by patphongs** [comment]
@dorothyyeager and I spoke about this and Dorothy can make a wagtail redirect for this. We'll want to see if we ever want to make `/campaign-finance-data/` redirect permanent too.

**Comment by dorothyyeager** [comment]
The redirect has been made successfully, and that breadcrumb link will now redirect /campaign-finance-data/ (which was a parent page for some data description pages in Wagtail) to https://www.fec.gov/data/.
