### ISSUE TITLE
Wagtail: Update custom page template to add internal and external buttons

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2098]
There are times we would like to include a call to action button on pages that use the Custom Page template, but that button is not an option. 

I've added this to the "Wagtail wish list" at https://docs.google.com/document/d/1HM1-SaxAL-pVhzwQY8ZP-1uA8bVlbAxwFhqW4f-3lAo/edit?usp=sharing but wanted to put in a separate issue as I'm hearing this might not be a hard thing to do and would help us with some pages currently in development.

This issue is not a "dealbreaker" (see #2006) but it is something that will be quite useful, especially as we start to work on moving various filing deadline and compliance pages out of transition.

**Comment by apburnes** [comment]
Fixed in PR #1968

**Comment by dorothyyeager** [comment]
Thanks @apburnes for all your work on this!
