### ISSUE TITLE
Finish up content work on candidate pages

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2101]
### Problem
Need to fix candidate committee pages, especially receipts, to be more complete.

### Background
In candidate section of H4CC, we worked on identifying gaps in content moved over from campaign guides (#1995).  To address these gaps, @dorothyyeager created content, whether they go on separate pages or as sections in existing ones.  However, in the current content architecture - we can't find places to put the information in ways that make sense.  

We keep running into this issue, and the problems are documented in our work at #1214.  We especially need to make sure that all types of contributions (including joint fundraising, PAC, party, earmarks, loans, candidate contributions) are covered in these pages. 

### The work

- Is info in the right place under "[types of contributions](https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/contribution-types/)" and "[who can and can't contribute](https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/who-can-and-cannot-contribute/)"?  We think it's not.  We need to mock up moving sections around.
- We need to add an IE page to this section.  Makes sense in the receipts section for "other sources of support."  Should we move [coordinated communications](https://www.fec.gov/help-candidates-and-committees/making-disbursements/coordinated-communications/) here too?

### To do
- [x] Mock up moving sections around
- [x] Solicit comments from content team

### Future work
- Make edits and decisions based on comments
- Update pages as needed

### References
#1214 
#1995

**Comment by dorothyyeager** [comment]
Noting this feedback received on https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/who-can-and-cannot-contribute/.  See https://github.com/fecgov/FEC/issues/6498

There is indeed a little bit of technical detail that wasn't included but that would have answered one of his questions. It's in the glossary and actually should probably be on the page.

**Comment by dorothyyeager** [comment]
@llienfec and I had a fantastic sync-up about this and have re-scoped the topic (see edits above) to focus our work for this sprint on coming up with a way to use the current page architecture but reorganize the content within the pages, fill in gaps (e.g., no references to PACs being able to contribute) and use the resource page template for the longer pages as a way to assist people with finding information. We're planning to circulate a document to the rest of the content team this morning for their comments, and then we can go from there to the future work.

**Comment by dorothyyeager** [comment]
Document link: https://docs.google.com/document/d/1zq1AvNYRBFzxYoWQIpnfJZBs2mDtluhMS9aFpnuWgJQ/edit?usp=sharing

**Comment by llienfec** [comment]
Closing issue: new section structure and pages have been out to content team for over a week.  We're going to finish collecting the comments and edit the pages.  That work is tracked at #2173.
