### ISSUE TITLE
Typo=missing parenthesis on https://fec-dev-proxy.app.cloud.gov/data/reports/pac-party/

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#2104]
What are we after: Add the missing paren at the end of Super PAC (independent expenditure only) in the list of filter options.

Why we're after it: resolves embarrassing typo.

Completion criteria:

- [ ] Add closing paren, Line 231 /data/constants.py 

![comma](https://user-images.githubusercontent.com/5572856/41606406-99bfbe06-73b1-11e8-946b-4f973122d321.png)

**Comment by lbeaufort** [comment]
PR has been merged
