### ISSUE TITLE
Bug: Glossary link does not work on e-regs page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2105]
Problem:
The link at the top of the page to open the glossary on the e-regs pages (https://www.fec.gov/regulations) has gone dead.

Completion criteria:
- [ ]  Fix the link to the glossary at the top of the e-regs pages.

**Comment by patphongs** [comment]
closing in favor of https://github.com/fecgov/fec-eregs/issues/409
