### ISSUE TITLE
Drop down menu got smaller on filings tab.

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2112]
@fec-issues-bot commented on [Tue Jun 19 2018](https://github.com/fecgov/FEC/issues/6408)

## What were you trying to do and how can we improve it?
 Drop down menu for filing options shrunk- was "normal" on 6/18.  Smaller (more difficult to use) on 6/19 

## Tell us about yourself
 RAD analyst 

## Details
* URL: https://www.fec.gov/data/committee/C00280743/?tab=filings 
* User Agent: Amazon CloudFront

---

@jwchumley commented on [Wed Jun 20 2018](https://github.com/fecgov/FEC/issues/6408#issuecomment-398715507)

Thanks for your feed back. We'll look into this.

---

@patphongs commented on [Wed Jun 20 2018](https://github.com/fecgov/FEC/issues/6408#issuecomment-398731381)

There’s an incorrect padding being added to the `.column--doc-download .dropdown__value` for that drop down. It’s only .75rem, which makes the box smaller. We need to update the styles.

<img width="117" alt="screen shot 2018-06-20 at 8 25 37 am" src="https://user-images.githubusercontent.com/12799132/41658321-013bda1c-7464-11e8-84f7-5f1c33b9287a.png">

---

@patphongs commented on [Wed Jun 20 2018](https://github.com/fecgov/FEC/issues/6408#issuecomment-398731503)

Moving this to fec-cms

**Comment by johnnyporkchops** [comment]
These dropdowns also seem to be incorrect in other places as well, like here where they are offset above the bottom of the button:
<img width="847" alt="screen shot 2018-06-25 at 11 37 48 am" src="https://user-images.githubusercontent.com/5572856/41860335-6f6da32e-786c-11e8-84e6-40ae19224d23.png">
