### ISSUE TITLE
Add sale or use ("salt list") guidance to new site

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2115]
User emailed the great @dorothyyeager about companies using FEC reports to find names for mail/spam.  He needed the salt list guidance.  We need to move this info from campaign guide into web pages and possibly retire 1992 PDF guidance.  This is a part of the larger work of converting campaign guide to wagtail pages & getting off transition site.

Content topic:  sale or use/salt lists/list of pseudonyms

### To do:
- [x] Figure out where this will live  (Comment from @dorothyyeager: We've decided to do this as a Record article, which has proven to be a good way to handle moving content from old stand-alone brochures. It will be assigned to an Info Div specialist for drafting.)
- [x] Draft content from guide/PDF 
- [ ] Create script and video for the article (Comment from Dorothy:  we are moving this to #2241)
- [ ] Circulate for review by RAD, OGC, Public Records and content team  (Comment from Dorothy:  we are moving this to #2241)

Implementation of the content will be handled in a future sprint in #2225

### Future work:
- [ ] Look for other brochures and guidance that 1) are covered in the campaign guide and 2) may be out of date.  They may be in transition folder or when users google, these show up.

**Comment by dorothyyeager** [comment]
We are apparently linking this outdated brochure from open api access page at https://api.open.fec.gov/developers/, so we will want to get this updated soon.

**Comment by dorothyyeager** [comment]
Groomed the issue above slightly to note that we're going to use a Record article as our home for the new page. The article has been assigned to an Information Division specialist and will be circulated to the appropriate divisions as well as content team for review.

**Comment by dorothyyeager** [comment]
We have made a decision in Information that we need to spend a little quality time on the video scripting and production to get a good quality product. So for this ticket, I'm going to groom the completion criteria and move the video and the circulation of everything to a future ticket.

**Comment by dorothyyeager** [comment]
Closing this issue since the Record article has been drafted. Work will now turn to the videos in #2241.
