### ISSUE TITLE
"Filter added" popup message for ALL filters

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#2118]
The last change to audit search PR# https://github.com/fecgov/fec-cms/pull/2029 did not make it in for some reason. Perhaps due to the way we manually restored the branch.

Just before merge, @JonellaCulmer  caught:  The green "filter added" message and accompanying checkbox for each dropdown filter was only working for some filters.
https://github.com/fecgov/fec-cms/pull/2029#pullrequestreview-125203578

See example screenshot of this broken for the first PAC filter on production:
![jun-20-2018 01-02-57](https://user-images.githubusercontent.com/5572856/41638366-078b9e94-7427-11e8-88cd-c4c957975471.gif)

**Comment by JonellaCulmer** [comment]
@johnnyporkchops fixed this, so closing.
