### ISSUE TITLE
Test new election profile pages

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2120]
We need to check the election profile pages for each type of office:

- [ ] House
- [ ] Senate
- [ ] Presidential

**Comment by patphongs** [comment]
The state election offices don't necessarily pertain to the Presidential office type. Currently it is displaying nothing in that section except for the intro text. @JonellaCulmer thoughts on what we should do?

https://fec-dev-proxy.app.cloud.gov/data/elections/president/2016/?tab=about-election#state-election-offices

**Comment by JonellaCulmer** [comment]
The content team has approved the following language to update the state election offices section on the Presidential election pages: 
> Ballot access procedures for presidential candidates vary by state. Contact each state election office for information.”

**Comment by JonellaCulmer** [comment]
@patphongs @apburnes Identified the following three issues on the election profile pages: 

Needs to be fixed:
- IE aggragate total links fix has appeared to have not made it over to dev. It's working on my local, but not on dev. Is it possible I'm missing something?
Presidential page: https://fec-dev-proxy.app.cloud.gov/data/elections/president/2016/
Senate page: https://fec-dev-proxy.app.cloud.gov/data/elections/senate/CA/2018/
House page: https://fec-dev-proxy.app.cloud.gov/data/elections/house/KY/01/2018/

Not a huge deal, but if there's bandwidth would like it fixed:
- Inactive cards are appearing as a different size than the “Dates and deadlines” card. 
Presidential page: https://fec-dev-proxy.app.cloud.gov/data/elections/president/2016/
Senate page: https://fec-dev-proxy.app.cloud.gov/data/elections/senate/ID/2016/
House page: https://fec-dev-proxy.app.cloud.gov/data/elections/house/KY/01/2018/

This may be something that we can deal with later:
- 2016 Presidential PCC table did not pick up Marco Rubio’s committee even though he has one and in the API candidate_pcc_name is listed as null. There is no termination report for this committee and it doesn’t appear that the committee has been rejiggered to be used as a senate committee. Rubio currently has a separate, active, Senate committee. https://fec-dev-proxy.app.cloud.gov/data/elections/president/2016/?tab=a

**Comment by JonellaCulmer** [comment]
Separate issues have been opened for reported problems listed above:

1. Different environment setups: https://github.com/fecgov/fec-cms/issues/2147
2. Cards: https://github.com/fecgov/fec-cms/issues/2148
3. Candidate PCC: https://github.com/fecgov/openFEC/issues/3244

Closing this issue, in favor of those separate issues.
