### ISSUE TITLE
Add Filter Options to Independent Expenditure page

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#2127]
https://www.fec.gov/data/independent-expenditures/?data_type=processed&is_notice=true

The current filter options on the IE search page do not include some options that are necessary for users to find the set they are looking for.

Filters to add:
candidate state
candidate district
candidate office sought
candidate party affiliation

- [x] confirm the endpoint supports these options
- [x] design team determines filter locations and groupings https://github.com/fecgov/fec-cms/issues/2354
- [ ] add filters

**Comment by JonellaCulmer** [comment]
Updated candidate filter arrangement below: 
<img width="256" alt="screen shot 2018-09-14 at 3 27 14 pm" src="https://user-images.githubusercontent.com/31663028/45571034-eda9bd80-b832-11e8-8328-b7db39a0984f.png">
