### ISSUE TITLE
Add committee type filter to disbursement search

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#2128]
https://www.fec.gov/data/disbursements/?data_type=processed&two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=06%2F25%2F2018

Currently we are unable to limit disbursement searches by committee type (example, I want all disbursements made by leadership PACs from Minnesota)

- [x] confirm committee type is an endpoint option
- [x] design location of filter option
- [x] determine the language for the committee filter (ex. "Spender committee type"?)
- [x] add filter to screen

**Comment by johnnyporkchops** [comment]
There is a WIP branch for this issue:
feature/add_spender_committee_type_filter

**Comment by JonellaCulmer** [comment]
Below is a mock-up of what the filters can look like. It also includes a change for the currently named "Spender details" filter section, to be updated to now say "Recipient details".

![screen shot 2018-10-18 at 1 55 54 pm](https://user-images.githubusercontent.com/31663028/47174097-bcaf2380-d2dd-11e8-87e8-4798057070e4.png)

**Comment by dorothyyeager** [comment]
This has been merged, so closing the issue.
