### ISSUE TITLE
Committee type filter missing from  all receipts search and individual contributor search

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#2129]
As a reporter, I need to be able to find individuals who contribute to different types of committees so that I can better understand campaign finance trends.

All receipts:
https://www.fec.gov/data/receipts/?data_type=processed&two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=06%2F25%2F2018

Individual contributors:
https://www.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2018&min_date=01%2F01%2F2017&max_date=06%2F25%2F2018

We are currently unable to limit receipts searches by committee type (example, I want all Line 11(a)(i) transactions reported by Super PACs)

- [x] confirm committee type is an endpoint option
- [x] design team determines location of filter
- [x] design team determine appropriate wording for committee type filter
- [x] add `recipient committee type` filter to screen

**Comment by JonellaCulmer** [comment]
@lbeaufort It appears that both `All receipts` and `Individual contributions` tables both support the addition of committee filters, as both have committee_type and committee_type_full as fields within the schedules/schedules_a endpoint.

**Comment by JonellaCulmer** [comment]
@lbeaufort The Committee type filters for both the `All receipts` and `Individual contributions` tables should resemble the display currently implemented on the `Committees` table, here: https://www.fec.gov/data/committees/

The Committees type filters are tucked within an accordion. And the filters themselves are a combination of checkboxes and dropdowns, depending on the category. 

Screenshot below:
<img width="301" alt="screen shot 2018-06-28 at 10 31 42 am" src="https://user-images.githubusercontent.com/31663028/42040822-879b3390-7abe-11e8-8f9f-a0c9f0a39c05.png">

**Comment by lbeaufort** [comment]
@JonellaCulmer here, just calling it "Committee type" would be confusing because we'd want to know whether we're looking for the recipient committee type or the contributor committee type. How does this look? Also @jwchumley confirming that we want to look for recipient committee type, not contributor committee type.

![image](https://user-images.githubusercontent.com/31420082/42044005-d8a6d904-7ac5-11e8-89ca-336ffda89a07.png)

![image](https://user-images.githubusercontent.com/31420082/42044022-e2d22dac-7ac5-11e8-9b9c-935b021dcf05.png)

**Comment by lbeaufort** [comment]
@JonellaCulmer do you see `committee_type` as a filter here? https://api.open.fec.gov/developers/#/receipts/get_schedules_schedule_a_

**Comment by JonellaCulmer** [comment]
I confused the fields with the search filters. We need to make a change in the schedules/schedules_a endpoint to add a committee_type search filter. 

API work issue: https://github.com/fecgov/openFEC/issues/3248 (blocker)
WIP PR for front-end work here: https://github.com/fecgov/fec-cms/pull/2150
