### ISSUE TITLE
Research task: Add "Other filers" help section

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#2131]
**What we're after:**
As a non-registered filer, I want to be able to learn more about reporting contributions and expenditures so that I can stay in compliance. 

This issue will track research to identify how other filers currently get to reporting/compliance information and make recommendations to improve access to this information. 

**Areas to consider/explore:**
- [x] Information architecture
- [x] Possible content improvements
- [x] Website analytics

---------------------------------
From RAD:
Add “Other Filers” Section to Website – This should be for Forms 5, 7, 9, and 13 filers.  Perhaps, and this might be stretching things, we could re-label the “Help for candidates and committees” to “Help for candidates and other filers.”  I am guessing this was a hot topic eons ago, but with the rise in F5 and F9 filings it seems like we should be paying more attention to them on the website.  Also, the current sub-categories under that section don’t even reference other filers.

**Comment by llienfec** [comment]
## Scoping research (#2131)

### Defining request
Adding “other filers” section to site.
- Appears to be request for H4CC, possibly language + reporting examples
- Filer types requested:
o	IE filer NOT a committee (Form 5)
o	Corps & unions (Form 7)
o	Electioneering communications (Form 9)
o	Inaugural committees (Form 13)

### Research to do:
- **Timing** – Do we work on all or some of these?  When is best timing?  These are not similar committee types, will need to separate out the work.
- **Content architecture**
o	Can we make these sections parallel to existing content?
o	Where do we put it?
- **Creating content**
o	What do we need to have “complete” sections?  How do we get there?
o	MVP – what is language we have currently existing?  Is it somewhere else on the site already?  What can we steal and borrow?
o	Do we need new or can we use existing reporting examples?
- **Team review** – will need to be in-depth
- **OGC Review** - depending on amount of new language
- Create implementation tickets

**Comment by llienfec** [comment]
Closing b/c this is scoped.  Moving forward with creating this section by working on IEs at #2177
