### ISSUE TITLE
Redirect links for E&Js from transition to SERS or CMS

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2134]
In #2079 links on the E&J pages were updated to point to the SERS database, and a [spreadsheet](https://docs.google.com/spreadsheets/d/1OUELbPCrwJsciY19SkvbxZB14S3MwuayI6Fstob5fiU/edit?usp=sharing) was developed in anticipation of redirects. In addition, we are uploading replacement files to the CMS for some of the transition links that aren't very legible.

Many Record articles, tips, Infoweb pages, press releases and other web pages link to these rulemaking documents, so we need to write redirects to point them to SERS or the CMS as appropriate, once the next phase of the work of updating the links has been done in #2202  

**To do:**
- [ ] Write redirects for the E&J links
- [ ] After redirects are in place, make a list of the E&Js that can have their transition files deleted from the transition site.

**Comment by llienfec** [comment]
Project plan changed so we're closing this for now.  See other E&J tickets: https://github.com/fecgov/fec-cms/issues/2392

Closing issue.  Thanks @dorothyyeager
