### ISSUE TITLE
Research task: Make filter options for raw pages the same (or as close as possible) to processed data filters

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#2135]
A reporter needs to access transactions on or just after a filing deadline and must use the raw data source to do this. Her filter needs are no different than any other time and so she needs the same filters she always needs.

There are far more filter options on processed data pages than on raw. Most people that access the raw data have the same filter needs as those that access the processed data so we should upgrade the raw filters to support the same search options. 

- [ ] Assess the raw search pages to determine which filters need to be added
- [ ] Assess the efiling endpoints to make sure they support the search filters we want to add
- [ ] Create follow-up tickets for API work and front-end work

**Comment by PaulClark2** [comment]
Can we time box this?

**Comment by llienfec** [comment]
@lbeaufort and I conducted a time boxed inventory of:
1. Processed vs raw filters
1. Fields available in the API for all receipts/all disbursements

:lock: https://docs.google.com/document/d/16DWIquTYpbdtCCDrXYLXXRrHQXS51sX_8cLY75spLA0/edit?usp=sharing :lock: 

Before this work moves forward, we need PM help to come up with a strategy for what we are trying to achieve.  We can't get parity between filters with current API.  Need to figure out what is enough, what is an MVP for this work, and how to prioritize it.

cc: @jwchumley @PaulClark2 @AmyKort

**Comment by AmyKort** [comment]
Implementation continues at https://github.com/fecgov/fec-cms/issues/2204
