### ISSUE TITLE
Take down redirected pages off transition site

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2137]
Having redirected old and outdated brochures, pages, etc. in #1728, #1729, and #2025 , now we take down these pages off of transition (after the release is deployed 6/26/18).

**To do:**
- [x] Remove all transition pages on the list below (after the release is deployed 6/26 and we verify redirects worked).
- [ ] Potential future work: train Dorothy in how to do this.

**Files to remove**
- [x] Campaign Guides (those housed on transition; they've been uploaded to CMS)
https://transition.fec.gov/pdf/candgui.pdf
https://transition.fec.gov/pdf/partygui.pdf
https://transition.fec.gov/pdf/nongui.pdf
https://transition.fec.gov/pdf/colagui.pdf

- [x] Toolkits (no longer used) - https://transition.fec.gov/info/toolkit.shtml

- [x]  Audio forms (no longer used)
https://transition.fec.gov/pdf/forms/fecfrm1ssf.pdf
https://transition.fec.gov/pdf/forms/fecfrm1nc.pdf
https://transition.fec.gov/pdf/forms/fecfrm1party.pdf

- [x] Timely tips archive pages (all tips are on fec.gov)
https://transition.fec.gov/info/TimelyTipsArchive.shtml
https://transition.fec.gov/info/tips/timelytipsarchive2015.shtml
https://transition.fec.gov/info/tips/timelytipsarchive2014.shtml
https://transition.fec.gov/info/tips/timelytipsarchive2013.shtml
https://transition.fec.gov/info/tips/timelytipsarchive2012.shtml
https://transition.fec.gov/info/TimelyTipsArchive2006.shtml

- [x]  Old FECfile manuals (latest ones have been uploaded to CMS)
https://transition.fec.gov/support/GettingStartedManual_A.pdf
https://transition.fec.gov/support/GettingStartedManual_U.pdf
https://transition.fec.gov/support/GettingStartedManualIEForm5_6.23.16-1.pdf

- [x]  Various outdated and/or retired brochures and informational pages (updated material is now on fec.gov)
https://transition.fec.gov/ans/answers_public_funding.shtml
https://transition.fec.gov/law/nonfederalfundraisingfaq2.shtml
https://transition.fec.gov/law/lobbybundlingfaq.shtml
https://transition.fec.gov/pages/brochures/ao.shtml
https://transition.fec.gov/pages/brochures/ao_brochure.pdf
https://transition.fec.gov/pages/brochures/bestpractices.shtml
https://transition.fec.gov/pages/brochures/treas.shtml
https://transition.fec.gov/pages/brochures/committee_treasurers_brochure.pdf
https://transition.fec.gov/pages/brochures/delegate.shtml
https://transition.fec.gov/pages/brochures/ec-brochure.pdf
https://transition.fec.gov/pages/brochures/fec_feca_brochure.pdf
https://transition.fec.gov/pages/brochures/foreign.shtml
https://transition.fec.gov/pages/brochures/internetcomm.shtml
https://transition.fec.gov/pages/brochures/jointfundraising.shtml
https://transition.fec.gov/pages/brochures/locparty.shtml
https://transition.fec.gov/pages/brochures/ssfvnonconnected.shtml
https://transition.fec.gov/pages/brochures/TestingtheWaters.shtml
https://transition.fec.gov/pages/brochures/indexp.shtml
https://transition.fec.gov/pages/brochures/pubfund.shtml
https://transition.fec.gov/pages/brochures/checkoff.shtml
https://transition.fec.gov/pages/brochures/complain.shtml
https://transition.fec.gov/pages/brochures/complaint_brochure.pdf

**Comment by PaulClark2** [comment]
@dorothyyeager I couldn't find the files listed below on the transition server to delete. I'm not sure it matters. The redirects take you to the new site.

- [ ] https://transition.fec.gov/info/tips/timelytipsarchive2012.shtml
- [ ] https://transition.fec.gov/info/tips/timelytipsarchive2013.shtml
- [ ] https://transition.fec.gov/info/tips/timelytipsarchive2014.shtml
- [ ] https://transition.fec.gov/info/tips/timelytipsarchive2015.shtml

**Comment by dorothyyeager** [comment]
Thanks @PaulClark2 . How funny. I don't see them in there either and I checked the info/ subdirectory. Like you said, redirects are in place and hopefully people aren't really using the older tips much. All of the tips are on the new site.

**Comment by PaulClark2** [comment]
Thanks. I'm going to close this.
