### ISSUE TITLE
Change the local number on the contact page to 202-694-1100

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2138]
The automated menu tied to 202-694-1000 is not working properly - disconnecting callers when they choose options 3 & 6, among other issues.  

Once the contact page is deployed on 6/26, please replace the local number on the contact page - https://www.fec.gov/contact-us/ - with 202-694-1100

**Comment by dorothyyeager** [comment]
One quick note - the new page is going to be at /contact/ instead of  /contact-us/ .  I've updated the new page to make that phone number change and it will be included when the page goes live.

**Comment by dorothyyeager** [comment]
https://www.fec.gov/contact/ is now live and the number is updated so we can close this issue.
