### ISSUE TITLE
Restructuring Calendar Entries

### ISSUE THREAD

**Issue by DavidfromInfo** [fecgov/fec-cms#2144]
Is it possible to change the calendar entries to include the Event name from the database entries (also in the API code)? See attached images for visual support

Thanks!

![proposed change calendar entry](https://user-images.githubusercontent.com/40633757/41976816-ebc7f692-79eb-11e8-8770-ac10abda9bbd.jpg)
![proposed change quick entry](https://user-images.githubusercontent.com/40633757/41976817-ebd4e492-79eb-11e8-9da8-02a32c9ca1b3.jpg)

**Comment by lbeaufort** [comment]
I confirmed no API changes are needed. It's not called title there - I'll confirm. I think it's "summary."
