### ISSUE TITLE
Test 2020/2022 candidate data tables

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2151]
Test 2020/2022 candidate data tables:

Presidential - test 2-year 2018 totals and 6-year 2020 totals:
https://fec-dev-proxy.app.cloud.gov/data/candidates/president/?election_year=2020&cycle=2020&election_full=true

Senate - test 2020 and 2022 election years, 2-year totals and 6-year totals:
https://fec-dev-proxy.app.cloud.gov/data/candidates/senate/?election_year=2020&cycle=2020&election_full=true

**Comment by jwchumley** [comment]
I have questions about three presidential candidates:
1. C00639021 | P00005900 | Davenport, Keith | $22844.16 | $5651.04 - I think he should be on the list but he isn't

2. C00671610 | P00006981 | Farber | 2572 | 2552 His amounts are doubled but I found a dup row in the linkage table for him and deleted it. Will that solve this?

3.  C00553206 | P00004861 | Bickelmeyer | 454 | 434 - corrected API shows $2022 in receipts but I only see $454

**Comment by lbeaufort** [comment]
thanks so much for taking a look! The duplicate link shouldn't double totals, so I will take a look at fixing that too.

**Comment by jwchumley** [comment]
Either removing the dup fixed on #2 or you fixed it. I'm looking at it this morning in a bit more depth and with coffee. I've found a few more and am making a spreadsheet

**Comment by jwchumley** [comment]
OK. After digging deeper you will be glad to know that all your presidentials are correct. I was being confused by committees who are linked to a committee with committee type=U where that committee has $$ and their PCC does not. In your endpoint those dollars should not show up and they don't. Yay. Now I'll look at Senate filers and try not to post anything here until I'm sure. ;)

**Comment by jwchumley** [comment]
OK. I've been through all of the 2020 Senate and Presidential candidates and all the candidates and their receipt and disbursement numbers match.
