### ISSUE TITLE
Enable export button for candidate financial totals

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#2153]
What we are after: 
We need to enable the export button for candidate financial totals on the election profile pages. 

Why we are after is: 
Users want to able to download candidate financial totals. 

Completion criteria: 
- [ ] enable export button

![image](https://user-images.githubusercontent.com/11817734/42104511-d13aceac-7b9a-11e8-95e3-e470322ea117.png)

Related issues and PRs:
Original issue: https://github.com/fecgov/fec-cms/issues/2010
This PR enables the back-end functionality required to enable the export button: https://github.com/fecgov/openFEC/pull/3253

**Comment by JonellaCulmer** [comment]
@fec-jli @PaulClark2 Does this work also include enabling the export function for the individual contributions table as well?

**Comment by PaulClark2** [comment]
@JonellaCulmer no. There is additional back-end work that needs to happen before we can enable the export functionality of the individual contributions data tables.

**Comment by PaulClark2** [comment]
follow-on work: https://github.com/fecgov/openFEC/issues/3254

**Comment by fec-jli** [comment]
This has been merged.  It is ok to close.
