### ISSUE TITLE
Create Filings tab and add image number to filings on candidate profile pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2154]
**What we're after:** To add more clarity and consistency across our profile pages, we need to create a Filings tab and move the bulk of candidate filings to that section. 

While we plan to create that tab, we also need to keep the candidate's current version of their Statement of candidacy on the `About this candidate` tab. That way, users familiar with this placement will not be without it, or we introduce a pain point for them. Additional work is outlined below in the completion criteria, include the addition of filing image number to the tables. 

**Completion criteria:**
- [x] Create "Filings" tab, list last after "Spending by others to support or oppose"
- [x] Add logic to "About this candidate" tab to list only the candidate's current version of their Form 2 Statement of candidacy
- [x] Create a 'Statements of candidacy' table on "Filings" tab, include all versions including current version
- [x] Move `Other documents` table from "About this candidate" tab to "Filings" tab. This table should follow the `Statements of candidacy` table
- [x] Include document "Image number" in `Statements of candidacy` table. Order of columns should be: Document > Version > Date filed > **Image number** > Pages
- [x] Update side nav and subnav items to correspond with new sections. Under Filings, Statements or candidacy and Other documents should be listed. Under About this candidate, Candidate information and Committees should be listed, and Other documents removed. 

**Designs:**

## Update about this candidate page
<img width="751" alt="screen shot 2018-07-16 at 8 27 30 am" src="https://user-images.githubusercontent.com/31663028/42758657-33af814c-88d2-11e8-84bf-0b7da38c606c.png">

## New filings page
Information such as documents and image number columns are truncated to fit the mockup, but in production no overlap of graphics and text, or truncation of numbers should occur.
![screen shot 2018-07-10 at 11 04 18 am](https://user-images.githubusercontent.com/31663028/42520042-54ff3566-8433-11e8-82d4-86327d077c89.png)

**Comment by lbeaufort** [comment]
@JonellaCulmer could you provide some visuals of what you expect this to look like?

**Comment by johnnyporkchops** [comment]
@JonellaCulmer , In your first mockup above, it shows a `Disbursements tab` for Tammy Baldwin for Senate, but on her page on prod it does not show a Disbursements tab and I do not see this as tab being included in the logic for the candidate-single template. Am I missing something, or is this just because its a old mockup or something?
https://www.fec.gov/data/candidate/S2WI00219/

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Good catch, I'll update that mock-up in the description above.
