### ISSUE TITLE
Display multi-part archived MURs 

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2157]
**What we're after:** There are instances where archived MUR documents are split into multiple files, but those are in the minority. However, in order to address these circumstances, we need to determine what that front-end interaction would look like to accommodate both scenarios or identify the best interaction for each. 

These are the instances of MURs with multiple files: 
1252_A
1503_A
1704_A
253_A
2583_A
2667_A
2804_A
2892_A
3485_A

Example with a single file: 1251
archived MURs on classic: https://classic.fec.gov/MUR/

**Completion criteria:**
- [ ] Research use of table: identify high value information to include for archived MURs
- [ ] Mock-up design solution for archived MURs with multiple documents/files
- [ ] Move to implementation issue

**Comment by JonellaCulmer** [comment]
@lbeaufort I see this was moved to 6.4, but this was originally intended to be a design issue. I'd like more time to review the issue and determine if the table is the best way forward. Do you have any problem with my moving it back out of 6.4 for future design work?

**Comment by lbeaufort** [comment]
Because this is a bug fix and it's ready, let's create a new issue to improve the design and move forward with the bug fix this sprint.

**Comment by JonellaCulmer** [comment]
I suppose that since the work is now already complete than we should move forward. I'll just recreate this issue and make it clear that it's for design work. In the future, I don't believe we should bypass design work to solely make a bug fix. We don't have the best track record of going back to an issue. When work slips they are often design improvements.

**Comment by lbeaufort** [comment]
Thanks @JonellaCulmer - In this case because this has been brokedn without a workaround for so long, I didn't want to push the implementation to 6.6, which wouldn't get deployed until almost September.

There are screenshots here if you think there are dealbreakers, but my front-end abilities are limited :) - https://github.com/fecgov/fec-cms/pull/2185
