### ISSUE TITLE
Remove legal citations from AO's until we can fix the data

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2159]
Due to missing OCR text, 23 AO's are missing citations. So we don't show wrong data on the website, we should remove legal citations from AO's until we can fix the data.

cc: @AmyKort @jwchumley I'm going to work on this hotfix so it's ready to go if we can't fix the AO data quickly.

Example: https://www.fec.gov/data/legal/advisory-opinions/2018-01/

| ao_no   |
|---------|
| 1975-01 |
| 1985-09 |
| 2003-05 |
| 2014-18 |
| 2015-03 |
| 2015-04 |
| 2017-01 |
| 2017-03 |
| 2017-05 |
| 2017-06 |
| 2017-07 |
| 2017-08 |
| 2017-09 |
| 2017-10 |
| 2017-12 |
| 2017-13 |
| 2018-01 |
| 2018-02 |
| 2018-03 |
| 2018-04 |
| 2018-05 |
| 2018-06 |
| 2018-07 |
+---------+

**Comment by AmyKort** [comment]
Can we close this?

**Comment by lbeaufort** [comment]
Yes, thanks @AmyKort!
