### ISSUE TITLE
Improve meeting page template in Wagtail

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2166]
We've begun streaming open meetings and hearings using YouTube.  In doing this, we've discovered things that need improvement in the meeting page template. This issue replaces #2108, 2095 and 2099.

Background: https://github.com/fecgov/fec-cms/pull/1323, https://github.com/fecgov/fec-cms/issues/2095, https://github.com/fecgov/fec-cms/issues/2099, 

Completion criteria:
- [x] Update template to allow for meetings that last more than one day, so that only one page needs to be created per hearing/meeting
- [x] Add the "hearing" option to the template (which right now only offers a choice between labeling as an open meeting or an executive session). Hearings are open but differ from regular open meetings.
- [x] Add optional block for optional intro text.
- [x] Add the ability to copy/paste the YouTube embed code via html editor or html block into the meeting page template.
- [x]  Make embedded video mobile-responsive.
- [x] Add fields for video links to specific agenda items or testimony within the meeting page. (For routine open meetings, these links will be per agenda item but for hearings they will be per panel.)

Make additional changes requested by Commission Secretary regarding hearing titles and page titles:
- [x] Change the page name from Hearings to Public Hearings (https://www.fec.gov/meetings/?tab=hearings)
- [x] Move all Audit Hearings, Administrative Review Hearings, and Oral Hearings to their chronological order placement on the Open Meeting page, as they appeared on the classic website
- [x] Make pages for missing hearings and update other hearings as requested by Secretary. (Content work)

**Comment by dorothyyeager** [comment]
@johnnyporkchops received an email from the Commission Secretary requesting some changes to the way that public hearings are titled, the display of some of the older hearings and moving some of the older hearings from transition to the CMS. I've added that to the completion criteria.

**Comment by dorothyyeager** [comment]
I've started a google doc to capture the information that is content-related from emailing back and forth with the Commission Secretary. There are some missing hearings for which we'll need to generate a page. Other hearing pages did not scrape the information and need to have the content from classic brought over. @AmyKort 

https://docs.google.com/document/d/15mf9hiRXxkvW-dKQ1kmv2kO9UQCWxbS2vktEStI_dkk/edit?usp=sharing

**Comment by dorothyyeager** [comment]
Specific changes to the meeting pages requested by the Commission Secretary have been done. 

Next step for my part of this is to compare the classic hearings to those on our current site and update any missing information.

**Comment by johnnyporkchops** [comment]
@dorothyyeager , @@jamesjones:
For the into text for hearings, how should we handle that. Right now it is grouped with open meetings. Here is the current text as it appears in the template:
```
{% if self.meeting_type == 'O' %}
      <p>The Commission considers new regulations, advisory opinions and other public matters at open meetings, which are typically held at FEC headquarters on Thursdays at 10:00am.</p>
      <p>Members of the public can attend any open meeting or hearing in person. Open meetings are also streamed live online. To attend in person, please bring a photo ID and be prepared to go through a security check. After security, attendees are escorted to the Commission's hearing room.</p>
    {% elif self.meeting_type == 'E' %}
      <p>The Commission meets regularly in executive sessions to discuss pending enforcement actions, litigation and other matters that, by law, must be kept confidential.</p>
    {% endif %}

```

**Comment by dorothyyeager** [comment]
Good question @johnnyporkchops. My instinct is that we would want something that we could customize for each hearing, but we might also want a standardized blurb for hearings. I'm going to run it by the content team and see if people agree, and what we should say.

**Comment by dorothyyeager** [comment]
We've made the changes for specific hearings already posted as requested by the Commission Secretary. The other part of her request was to make pages for hearings that are on SERS, but were not ported over from classic. While it's not hard work, there are quite a few of these. Here's a checklist of those for my tracking purposes:

- [ ] 3/7/2012 hearing on IEs and ECs by corporations and labor organizations
- [ ] 3/2-3/2010 hearing on coordinated communications
- [ ] 12/16/2009 hearing on FEA definition
- [ ] 7/29/2009 and 8/25/2009 hearings on website improvement
- [ ] 1/14/2009 hearing on agency procedures
- [ ] 9/17/2008 hearing on lobbyist bundling
- [ ] 10/17-18/2007 hearing on ECs
- [ ] 7/11/2007 hearing on hybrid communications
- [ ] 1/25-26/2006 hearing on coordinated communications
- [ ] 8/4/2005 hearing on FEA
- [ ] 6/28-29/2005 hearing on Internet communications
- [ ] 10/1/2003 multicandidate committees and biennial limits
- [ ] 10/1/2003 Candidate travel
- [ ] 6/11/2003 Enforcement procedures
- [ ] 6/6/2003 Presidential public funding and national convention funding

**Comment by jamesjones** [comment]
All,

James Jones no longer works for Erdos Miller and this email address now
forwards to me.

Thanks in Advance,
Kenneth Miller
Erdos Miller
Cell: 713-562-4315

Want to set up a meeting? http://calendly.com/ken-em

Want to leave feedback? https://www.surveymonkey.com/r/ErdosMiller

Check Out our Results:

http://info.erdosmiller.com/case-studies

http://bit.ly/2u3d0YF

**Comment by dorothyyeager** [comment]
@johnnyporkchops @jjonesfec (apologies to the person above!) - on the question above about text for hearings - https://github.com/fecgov/fec-cms/issues/2166#issuecomment-405125805, the feedback I am getting is that we really want flexibility to be able to modify that introductory text for each hearing, as they are each their own individual thing and not standardized like the other two types of meetings we have.

**Comment by dorothyyeager** [comment]
As far as the missing hearings (not really missing because they are on SERS), for purposes of closing out this ticket which was primarily focused on modifying the page template, we are going to move that content work into its own ticket for the next sprint, and think through our strategy as the hearing information is on SERS already.

**Comment by jjonesfec** [comment]
Just a heads-up that this is my account! Not sure who the other fellow was. :(

**Comment by AmyKort** [comment]
Thanks @dorothyyeager !! You're the best!
