### ISSUE TITLE
Upload PDF of the statute into CMS

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2169]
I just discovered that we have not uploaded the PDF of the paperback version of Federal Campaign Finance Laws linked on https://www.fec.gov/data/legal/statutes/ into the CMS. We should do that so that this particular PDF can come off transition.

**TO DO**
- [x] Upload the PDF to the CMS
- [x] Update the link on https://www.fec.gov/data/legal/statutes/
- [x] Update the links to GPO's postings to point to the latest version they have (2015)
- [x] Write redirect for the transition to new CMS PDF link.

(This is one you can definitely assign me to.)

**Comment by dorothyyeager** [comment]
The PDF of the federal campaign finance laws compilation is now in the CMS and available at https://www.fec.gov/resources/cms-content/documents/feca.pdf. Next up: updating links and writing the redirect.

**Comment by dorothyyeager** [comment]
GPO has posted the 2015 editions of Titles 52 and 26 so have added updating those links to the completion criteria.
Title 52: https://www.gpo.gov/fdsys/pkg/USCODE-2015-title52/pdf/USCODE-2015-title52.pdf
Title 26: https://www.gpo.gov/fdsys/pkg/USCODE-2015-title26/pdf/USCODE-2015-title26-subtitleH.pdf

**Comment by dorothyyeager** [comment]
Pull requests for the hard-coded statute page links and the redirect from transition have been approved and merged. Links I could update on the transition site have been updated. Work on this is complete and ready for the release (although the redirect will need to be manually done at night.)

**Comment by PaulClark2** [comment]
PR is merged, so closing.
