### ISSUE TITLE
Add RFAIs of request_type 4 to 24/48 hour reports table #2170

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2174]
See https://github.com/fecgov/fec-cms/pull/2170/files

Per @jwchumley RQ-4's need to show as well

**Comment by llienfec** [comment]
You can test fixes by looking at these filers.  I verified they each have at least one RQ-4.
- C90010661
- C90011115
- C90011305

**Comment by lbeaufort** [comment]
Thanks @llienfec! This was super helpful.
