### ISSUE TITLE
Counting issue on committee filings tab

### ISSUE THREAD

**Issue by jwchumley** [fecgov/fec-cms#2175]
The committee filings tab has an issue where even with small numbers of filings the count can be wrong.  Here is an example:

https://www.fec.gov/data/committee/C00140715/?tab=about-committee

There are three reports in the regularly filed reports section and the count directly below says 1 to 4 of 4. The rest of the sections that have reports correctly count them as 1.

**Comment by JonellaCulmer** [comment]
This is resolved. Unable to replicate this issue now. Closing.
