### ISSUE TITLE
Get comments & approvals for IE pages

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2177]
Users requested "other filers" section.  One part of this section is for independent expenditures.  We drafted the IE pages in #2136.  

### To do:
- [x] Get comments from content team
- [x] Compile edits
- [x] Send over to OGC
- [x] Get comments and approval from OGC
- [x] Compile OGC edits

After this is done, we'll open an implementation ticket to:
- Add "other filers" section 
- Post new IE pages

**Comment by llienfec** [comment]
Sent documents to content team for review.  Plan is to get content comments back, get the drafts in shape by the end of the week, and send to OGC for review ASAP.

**Comment by dorothyyeager** [comment]
Draft pages have been sent to OGC for review.

**Comment by dorothyyeager** [comment]
Moving to sprint 6.5. OGC is working on this but we don't anticipate them returning comments before the end of the sprint.

**Comment by dorothyyeager** [comment]
OGC has returned their comments. They had some suggested language changes. They also want to ensure we link to glossary terms throughout, as well as to pages that fully explain IEs. (The new page for candidates on understanding IEs might be useful for that.)

Next step is to compile their edits into a google doc we can use for the page creation in a future sprint.

**Comment by dorothyyeager** [comment]
We've compiled the edits, so will close this issue and file an implementation ticket(s).
