### ISSUE TITLE
Research: develop strategy for past hearing pages and implement as needed

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2186]
What we're after: Users want separate pages for rulemaking hearings, including hearings held over the past 20 years and captured separately on the old website.

In #2166 we've made the changes for specific hearings already posted as requested by the Commission Secretary. The other part of her request was to make pages for older hearings that are on SERS, but were not ported over from [classic](https://classic.fec.gov/info/hearings.shtml) and thus don't appear in the hearings list on fec.gov. Apparently, internal stakeholders are looking for past hearing information on the hearings list of fec.gov and aren't looking on SERS. 

While it's not hard work, there are [quite a few of these hearings only on SERS now](https://github.com/fecgov/fec-cms/issues/2166#issuecomment-405237419). So we need to make a strategy for how we will approach the hearings, including archiving them once done, with an eye towards keeping our principle of one place for information.

**To do**
- [x] Meet with Commission Secretary and agree on content strategies for hearings going forward and archival of old hearings
- [x] Determine if there is a need to make pages for older hearings. Here is [the list](https://github.com/fecgov/fec-cms/issues/2166#issuecomment-405237419) of those not on the hearings page but in SERS. (Meetings that are policy-related but not regulations related are on transition and so will need to have a page made for them if we want to get them off transition.)
- [x] Make pages for the [older hearings not on SERS](https://github.com/fecgov/fec-cms/issues/2186#issuecomment-406006506) (see link).

**Comment by dorothyyeager** [comment]
Hearings that are not on SERS because they aren't regulations-related. These will need a page made. The rest of the hearings in the list are on SERS.

- [ ] January 2009 hearing on agency procedures https://transition.fec.gov/law/policy/enforcement/publichearing011409.shtml
- [ ] July and August 2009 hearings on website improvements https://transition.fec.gov/pages/hearings/internethearing.shtml

**Comment by dorothyyeager** [comment]
We had a great meeting this morning with the Commission Secretary. @AmyKort will follow through with our strategy for determining if there is a need to make additional hearing pages.

**Comment by AmyKort** [comment]
Rather than bring over all of the hearing pages from the classic site, let's add language to the hearings page to alert users to the fact that additional hearing documents are in SERS. We can develop a strategy for hosting pages in the hearing section as well (maybe keep them up for a set period of time?). That way, we can better maintain our content principle of keeping content in one place and also avoid a situation where we provide an overwhelming amount of information to users on the hearings pages.

**Comment by dorothyyeager** [comment]
Updated the ticket's completion criteria to add in the making of the pages for the hearings not on SERS. Will make a new ticket to address the changes in language and strategy for the hearings page.

**Comment by dorothyyeager** [comment]
New page up for the January 14-15 2009 hearing: https://www.fec.gov/updates/january-14-15-2009-public-hearing-agency-procedures/
