### ISSUE TITLE
Feedback tool not functioning/submitting feedback to FEC repo

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2196]
**What we're after:** The feedback tool is not currently functioning. Going through emails it looks like the last fec-issues-bot issue that was submitted via the feedback tool was on July 4, 2018. That was after the last update to the feedback tool on Jun 19, 2018. 

This issue will investigate the bug/error to determine the cause and propose a solution to fix and allow users to submit timely feedback to the FEC repository.

**Comment by lbeaufort** [comment]
I did a little investigating - when I tested this locally I got a response that issue #7141 had been created, but it didn't appear in the list. I entered an issue by hand and there's a gap in the numbers:

![Screen Shot 2018-07-18 at 10.15.44 PM.png](https://images.zenhubusercontent.com/59a579f28f62dc7798c47359/76260c59-a132-4c86-8a78-eeed16d99cfe)

**Comment by lbeaufort** [comment]
It appears that it's been since February since an  issue has come from `fec-issues-bot`. I'm thinking it has to do with the `FEC_GITHUB_TOKEN`  - I'd like to try rotating that credential and see if it addresses the issue. I'm not sure how it's set, though - @patphongs do you know how that credential gets set?

**Comment by patphongs** [comment]
fec-issues-bot has been fixed and is now submitting issues again. This is a new issue to implement a form human validation tool so that we are not spammed even if there is a scan: https://github.com/fecgov/fec-cms/issues/2205
