### ISSUE TITLE
Design: Reimplement raising/spending line charts back into production

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2199]
**What we're after:** Following taking down and making critical updates to our raising and spending line charts, we need to reimplement them back into production. 

**Some considerations:**
As part of the data fix here (https://github.com/fecgov/openFEC/issues/3240), there were some slight name changes to parameters that must be considered as part of this reimplementation. 

Also, recent usability testing suggested that users were not going to the bottom of the campaign finance data landing page and subsequently are not seeing the raising and spending charts. As part of this ticket, we should consider placing the raising and spending charts on the applicable advanced data pages where we know our users frequent.  

**Completion criteria:**
- [x] Review and address parameters with name changes
- [x] Mock-up alternative solution for displaying raising and spending line charts on advanced data pages
- [x] Discuss solution in design sync

**Comment by JonellaCulmer** [comment]
During design sync 8/10, we discussed the reimplementation of the cumulative raising/spending line charts. Part of that reimplementation, we discussed moving the line charts to the advanced data pages. 

From our user testing, we identified that very few of our users would think to look at the bottom of our data landing page for these high-level charts. Most were inclined to look on the advanced data pages for high-level birds-eye-view data. The mock-ups below address that change and incorporate the reaction box, to get an idea of user sentiment regarding the charts. 

Additionally, we may want to consider re-implementing the charts on the data landing page, along with the reaction box. If we're able to track which reaction charts receive feedback, we may be able to learn even more about how our users are using/seeing the charts on the different pages. 

**Designs:**
<img width="755" alt="screen shot 2018-08-13 at 11 38 55 am" src="https://user-images.githubusercontent.com/31663028/44042841-58d43a7a-9eef-11e8-99a3-9d09fdb193c3.png">
<img width="585" alt="screen shot 2018-08-13 at 11 39 33 am" src="https://user-images.githubusercontent.com/31663028/44042856-5f2eb864-9eef-11e8-868c-f20193f72661.png">

**Next steps:**
- [ ] Confirm shift of line charts to advanced data pages and possibly back on the data landing page @AmyKort @PaulClark2 @jwchumley @patphongs 
- [ ] Identify whether the reaction chart is something trackable(?)/comparable on different pages
- [ ] Make any necessary updates
- [ ] Move to an implementation issue
- [ ] Create a testing issue for followup.

**Comment by JonellaCulmer** [comment]
We had a productive conversation about the addition of the raising and spending line charts on their respective advanced data pages. Additionally, we intend to reimplement the charts back onto the data landing page. The charts, coupled with a reaction box, will allow us to get feedback on which table placement works better for our users. 

Based on that design sync comments, I have updated the mockups. There are also some unanswered questions that will be added to a followup content issue, specifically for the "Raising breakdown" and "Advanced data" language.

**Updatd designs:**
<img width="719" alt="screen shot 2018-08-17 at 3 49 25 pm" src="https://user-images.githubusercontent.com/31663028/44290098-28750180-a245-11e8-8139-113d72fd7ea8.png">
<img width="458" alt="screen shot 2018-08-17 at 3 49 59 pm" src="https://user-images.githubusercontent.com/31663028/44290138-52c6bf00-a245-11e8-87a2-61a13f8300b1.png">

**Comment by JonellaCulmer** [comment]
@apburnes As part of your ongoing PR, are you able to take a look at the first item on the checklist in the original comment? Below: 
> **Some considerations:**
As part of the data fix here (fecgov/openFEC#3240), there were some slight name changes to parameters that must be considered as part of this reimplementation.

**Comment by apburnes** [comment]
Will take a look.

**Comment by apburnes** [comment]
The endpoint was updated and the chart is using the updated API endpoint.  Nothing to do.

**Comment by patphongs** [comment]
Design is finished and another issue for the line charts  is outstanding coupled with a PR https://github.com/fecgov/fec-cms/pull/2276 to reimplement. Closing this.
