### ISSUE TITLE
Reimplement raising/spending breakdown charts back into production

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2200]
**What we're after:** Following the takedown and critical updates made to improve our raising/spending breakdown bar charts, and as part of the reimplementation work for the raising/spending line charts here (#2199), we need to now reimplement them back into production.

The URL can stay the same but we need to acknowledge that it will now be moved from where it previously lived. 

**Completion criteria:**
- [X] Meet to discuss the re-implementation of this bar chart
- [x] Talk to content about a logical URL and page name now that we've removed the word, "Breakdown" from the button on line charts
- [x] Reimplement the breakdown charts for the raising and spending information in both places where the line charts now exist: data landing page, advanced data: raising, advanced data: spending
- [ ] Change some terms and labels based on talks with content.

**Comment by llienfec** [comment]
Suggestions are with Content Team.  We should have an answer for you soon.

**Comment by llienfec** [comment]
Big thanks to the Content Team for going through so many name suggestions!  It was a struggle to find something descriptive, correct and plain language.  Our winner is: "Raising: by the numbers" as the page title/URL with a similar change for spending.

cc: @JonellaCulmer

**Comment by AmyKort** [comment]
Thanks @llienfec for doing all of the heavy lifting on this!

**Comment by patphongs** [comment]
Thanks @llienfec! As you're reviewing the change @JonellaCulmer we've also got some file names that need to change, they are currently called 

- breakdowns.jinja
- breakdowns.js 
- raising-breakdown.jinja
- spending-breakdown.jinja

**Comment by JonellaCulmer** [comment]
@llienfec Great! Just to clarify, the URL would be: `/data/raising-by-the-numbers` and `/data/spending-by-the-numbers`.

@patphongs How about the following? 
- bythenumbers.jinja
- bythenumbers.js 
- raising-bythenumbers.jinja
- spending-bythenumbers.jinja

**Comment by patphongs** [comment]
Changes have been made to file names and paths to use the `bythenumbers` syntax.
