### ISSUE TITLE
Update links to E&Js on transition site

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2202]
**User story**
As a user of FEC legal resources, I need to have the cleanest copy of an explanation and justification possible and locate the particular page of an E&J that pertains to the regulation I'm researching. 

**Background**
To help us get things off of transition and provide the cleanest copy available, we need to change the links to the older E&Js on transition (but not on SERS) to point to their links on GPO. In some cases, E&Js may not be on SERS or GPO, and will need to be uploaded to the CMS and linked from that. Finally, in an earlier ticket at #2079 , we updated more recent E&Js to point to SERS, but OGC would like to add anchor links to point to the specific page of an E&J. So we need to modify those pages. All of this work will be done by Information Division staff using Contribute.

**To do**
- [x] Research use of Wagtail instead of Contribute -(@llienfec  and I/timebox: 2 hours)
- [x] Meet with info about research findings and to get a game plan together

**Issue closing criteria**
Once research is done and we meet with Info Div, most of the work will be on their end as legal research.  We'll close this ticket and will create an implementation ticket when they are ready to move the tables into HTML.

**Work for Info Div**
- Update [spreadsheet ](https://docs.google.com/spreadsheets/d/1OUELbPCrwJsciY19SkvbxZB14S3MwuayI6Fstob5fiU/edit?usp=sharing) of links to modify (for use in future redirecting ticket).
- Update the links pointing to SERS (and their spreadsheet) to add the page anchor link
- Update the links pointing to transition to point the same document linked on GPO, using anchor links to get to a specific page.

Redirects will be done via #2134  in a future sprint after this work is complete.

**Issue closing criteria**
Once research is done and we meet with Info Div, most of the work will be on their end as legal research.  We'll close this ticket and will create an implementation ticket when they are ready to move the tables into HTML.

**Comment by llienfec** [comment]
After research spike, thought we were at an impasse and planned to drop this issue.  Now, we may have a way forward and I'll sync with @dorothyyeager tomorrow to fill her in.

- Want to use the resource templates
- Need Wagtail 2.0 b/c you can have links within an HTML table that you create yourself
- Figured out a way to copy the E&J tables into Word (more comfortable for non-technical users), change the hyperlinks to be in column 2, delete column 3, convert the table to HTML and add to Wagtail, while preserving table style

**Comment by dorothyyeager** [comment]
We're meeting with Info Division staff on Wednesday to talk about this issue and demonstrate the E&J - > HTML conversion. Zainab Smith in Information has begun the legal research needed for this task.

**Comment by llienfec** [comment]
Prepping for meeting with info

**Comment by dorothyyeager** [comment]
We had a really great meeting today with @llienfec who demo-ed how we'll do the E&J table to html table conversion.  Zainab will continue with legal research needed for task and prepping the word docs that will be used. There are a lot of E&Js, so doing the legal research and prepping the word documents will come first and will take time.

Having had our meeting, we can close this issue for now and open a future implementation ticket if needed when we are ready to input the new tables into Wagtail.
