### ISSUE TITLE
Form human validation tool for feedback tool

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2205]
**What we're after:** 
We need to be able to validate user feedback submissions through our feedback drawer so that we do not get spammed in our FEC github repository, especially when vulnerability testing is done. 

**Completion criteria:**
- [x] Use invisible recaptcha so that the user is only prompted to do a captcha challenge if there is suspicious activity
- [ ] Test for 508 compliance

![screen shot 2018-07-20 at 1 56 05 pm](https://user-images.githubusercontent.com/12799132/43017654-df6f4c38-8c24-11e8-9866-b2cd51c8ad63.png)

![screen shot 2018-08-27 at 12 40 03 pm](https://user-images.githubusercontent.com/12799132/44672430-65d05080-a9f6-11e8-9614-001a791aaeca.png)

**Comment by patphongs** [comment]
@JonellaCulmer This is what the recaptcha badge will look like on our website. First screenshot is when it first displays, second one is when you hover over it. Since this tool is part of the validation for the feedback drawer this badge gets displayed on every page of our site. In addition, google's terms of service says: `Don’t remove, obscure, or alter any legal notices displayed in or along with our Services.` See using our services [here](https://policies.google.com/terms?hl=en#toc-services). So I think we are required to have this badge showing.

![screen shot 2018-09-06 at 3 46 16 pm](https://user-images.githubusercontent.com/12799132/45181316-1a832280-b1ec-11e8-91b1-a140d79734d9.png)
![screen shot 2018-09-06 at 3 46 02 pm](https://user-images.githubusercontent.com/12799132/45181320-1ce57c80-b1ec-11e8-9468-f0be808fe1f8.png)

**Comment by JonellaCulmer** [comment]
RE: `Don’t remove, obscure, or alter any legal notices displayed in or along with our Services.`

@patphongs I saw the above note and don't want to alter any of the notices along with the reCAPTCHA, but I'm curious how much control we have over where this is placed. Can you tell me what happens to it when it's on mobile? It is possible to embed in the feedback drawer since that's what it pertains to, or in the footer? 

I just want to avoid it getting in the way of content on the page.

**Comment by patphongs** [comment]
We don't have much ability to change placement of the badge. The options are only placing it on the left, right, or inline. Because the drawer is a global form, I don't think we can position the badge inside of it, I don't think we would be able to hide it within there. Good news is that on mobile, the badge doesn't appear until you click on the drawer.

<img width="391" alt="screen shot 2018-09-14 at 2 21 23 pm" src="https://user-images.githubusercontent.com/12799132/45568300-432d9c80-b82a-11e8-8a6a-5b2401d3db7f.png">

**Comment by patphongs** [comment]
After chatting with @JonellaCulmer, we agreed that the placement of the badge has a small enough footprint that it would not obscure our content.

**Comment by patphongs** [comment]
Moving this to blocked for now as we are waiting for legal language for this new Recaptcha tool

**Comment by patphongs** [comment]
Got a response for accessibility language from Admin Law. Need to discuss on where to implement this. @AmyKort

**Comment by JonellaCulmer** [comment]
To address the need for incorporating accessibility language into the feedback box with the new recaptcha feature, we've built a new [Use of reCAPTCHA](https://www.fec.gov/use-recaptcha/) page. We need to now link this to the bottom of the feedback box. cc: @patphongs @AmyKort 

**Mock-up:** 
<img width="538" alt="screen shot 2018-09-28 at 11 33 30 am" src="https://user-images.githubusercontent.com/31663028/46218373-666c4780-c312-11e8-9783-491a6e01627e.png">

**Comment by patphongs** [comment]
Thanks @JonellaCulmer. Link has been added to the PR and is ready for review
