### ISSUE TITLE
unable to load house senate committee reports page

### ISSUE THREAD

**Issue by hcaofec** [fecgov/fec-cms#2206]
As of 07/20/2018, starting from 1:30pm, the house senate committee reports page is not loading.  All other reports pages are fine. 

same error appears on staging site too. Dev website has no such error.

endpoint `financial/reports/{committee_type}/` was checked and works fine too

Here is the link:
https://www.fec.gov/data/reports/house-senate/?data_type=processed

The console shows this error message:
<img width="1376" alt="screen shot 2018-07-20 at 4 08 45 pm" src="https://user-images.githubusercontent.com/24396726/43022995-43ef2ae0-8c37-11e8-8b3a-8589da46750f.png">

**Comment by AmyKort** [comment]
This appears to be resolved.
