### ISSUE TITLE
Refactor EC language for other filers section

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2210]
**User story** As a person or entity who makes electioneering communications, I need to know the complete rules and reporting obligations.

**Background** 
Users requested "other filers" section. One part of this section will be for electioneering communications. We're making some small tweaks to current language in #2209 and this will be more comprehensive.

**To do**
- [x] Figure out how to refactor the language used in current page
- [x] Draft language for review by content team
- [x] Compile edits from content team
- [x] Send language to OGC
- [x] Send reporting example to RAD for review
- [x] Send images to Jim for creation

**Comment by dorothyyeager** [comment]
A draft of the page has been sent around to the content team and is at https://docs.google.com/document/d/1hjpPbjOb0OaKER2c3LhEy4vlPtTskD2j_D7w8H3BxcQ/edit?usp=sharing

**Comment by llienfec** [comment]
I finished drafting the EC reporting example.  @dorothyyeager reviewed it and it's with RAD for subject matter review.

**Comment by dorothyyeager** [comment]
The content team has reviewed the rules page and came up with a good draft that combines info from the corporate page, the candidate guide and the recent IE page draft (for disclaimer language). It's at https://docs.google.com/document/d/1hjpPbjOb0OaKER2c3LhEy4vlPtTskD2j_D7w8H3BxcQ/edit?usp=sharing and has been sent to OGC, so we can close this issue and open an implementation ticket once comments are back from OGC (and RAD on the reporting example).

**Comment by llienfec** [comment]
Images for reporting examples have been sent to Jim.

**Comment by dorothyyeager** [comment]
We've sent everything off for review. Closing this ticket and we'll track the approvals and compile the edits in #2233
