### ISSUE TITLE
Font sizes in Wagtail templates

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2214]
Received feedback from users that the font size for intro text varies from page to page.  After researching, it looks like intro text on the Collections template is a little bit smaller than the intro text on the Resource template.

Example:
Collection template page:  [Taking in receipts](https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/)
Resource template page: [Types of contributions](https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/types-contributions/)

**Comment by dorothyyeager** [comment]
We've noticed on several of the resource pages that using bullets in the intro text causes a smaller font size to be used.
Examples : https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/types-contributions/ and https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/coordinated-party-expenditures/coordinated-party-expenditure-limits/

**Comment by dorothyyeager** [comment]
Closing. This was fixed at some point.
