### ISSUE TITLE
Drop null from filings tables

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2218]
**What we're after:** For filings datatables, we include both `Version unknown` and `null` if we don't know the version or the fec_file_id. In these cases where both are unknown we should only provide one result. "Version unknown" seems sufficient to cover both missing pieces of information, but null is a term we try to avoid. 

<img width="884" alt="screen shot 2018-07-26 at 9 39 24 am" src="https://user-images.githubusercontent.com/31663028/43265805-d513b9c6-90b7-11e8-8f9d-d80166b3f2df.png">

**Completion criteria:**
- [x] Confirm "Version unknown" is good with content team
- [x] Identify field that populates "current version, and add logic that displays "Version unknown" in cases when neither that field nor fec_file_id are available
- Make the same change on the following tables: 
  - [x] https://www.fec.gov/data/filings/
  - [x] https://www.fec.gov/data/reports/presidential/
  - [x] https://www.fec.gov/data/reports/house-senate/
  - [x] https://www.fec.gov/data/reports/pac-party/

**Comment by pkfec** [comment]
Reached out to content team for their recommendation on`Version` text changes.
