### ISSUE TITLE
Re-enable python tests AFTER Wagtail 2.0 deployed to prod

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2221]
Since python tests needed to be disabled on initial deploy of Wagtail 2.0, we need to re-enable them again AFTER Wagtail 2.0 has been deployed to production.

**Completion criteria:**
- Create a hotfix to re-enable python tests by:
- [x] Modify the 0001_initial.py migration file to add this dependency ```dependencies = [('wagtailcore', '0040_page_draft_title')]```
- [x] Add `./manage.py test` back into the run test section of the circle config.yml file.

**Comment by JonellaCulmer** [comment]
@patphongs Is this complete?

**Comment by patphongs** [comment]
Yes it is, thanks for pinging @JonellaCulmer. Closing...
