### ISSUE TITLE
Add "other filers" option to hard coded page

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2222]
Content team needs front end help publishing the new "other filers" section under [H4CC > Guides](https://www.fec.gov/help-candidates-and-committees/guides/) b/c the page is hardcoded.

![image](https://user-images.githubusercontent.com/22914750/43286220-5e804daa-90ef-11e8-8033-fb04b7c78d5b.png)

As a second step, we need design help for the [H4CC landing page.](https://www.fec.gov/help-candidates-and-committees/)  Do we want "other filers" to be included with the "Guides" cards?  Eventually we want to add a presidential section, bringing the number of sections up to 6. 

![image](https://user-images.githubusercontent.com/22914750/43286308-9701f9f8-90ef-11e8-8026-e9e255098204.png)

cc: @dorothyyeager 

**Completion criteria:**
- [x] Mock-up design solutions to modify the H4CC landing page cards. @JonellaCulmer
- [x] Content team provides language for the Other filers section @dorothyyeager / @llienfec 
- [ ] Update the guides.html

**Comment by dorothyyeager** [comment]
Created an issue at #2248 for the collection page that gets created and serves as the home for child pages. The front end will need that page to link to when they do this work. So the two issues go hand-in-hand.

**Comment by dorothyyeager** [comment]
Wording for the Guides page is in a google doc as requested by @patphongs at https://docs.google.com/document/d/1_76eBAtftxN4pNEq6RE1JtpAZYlJLSb1O2K1zY3p0Xw/edit?usp=sharing

**Comment by JonellaCulmer** [comment]
Below is a mock-up of a first iteration of the new cards arrangement. We'd be changing the cards from a 4-grid to a 3-grid. Would love your initial thoughts on this @johnnyporkchops. 

I've gone ahead and shown what it would look like with all 6 of the cards we intend to implement, including the card for Presidential candidates. That is placeholder language I used there, but that is the order in which I'd like to display the cards. Unless the content team has strong feelings about the order. What we have there may warrant a language change for the first card, "Candidates and their authorized committees". But we can cross that bridge when we come to it. 
cc: @llienfec @dorothyyeager @AmyKort 

<img width="730" alt="screen shot 2018-10-31 at 4 01 50 pm" src="https://user-images.githubusercontent.com/31663028/47815417-b03bb980-dd26-11e8-9c6b-5e91fef1a472.png">

**Comment by dorothyyeager** [comment]
Thanks @JonellaCulmer. I am thinking one solution might be to replace "authorized committees" with "campaigns." I know that's not "official" terminology but it's shorter and it's what we mean. Then you would have "House and Senate campaigns" and "Presidential campaigns." Thought for the future when we have the presidential section.

For now, what would it look like with 5 out of 6 cards filled out?

**Comment by JonellaCulmer** [comment]
Great question, @dorothyyeager. 

This is what it will look like with five cards: 
<img width="728" alt="screen shot 2018-11-01 at 9 03 42 am" src="https://user-images.githubusercontent.com/31663028/47853452-2b4bb100-ddb5-11e8-9722-bd04a9851b41.png">

**Comment by dorothyyeager** [comment]
Looks good to me! Thanks @JonellaCulmer

**Comment by dorothyyeager** [comment]
A note on where we are with prepping the Other Filers pages - close! https://github.com/fecgov/fec-cms/issues/2248#issuecomment-437148872

**Comment by dorothyyeager** [comment]
Great news! The Other Filers pages are unofficially live and we can say that they are live enough for work to begin on this ticket! So I'm removing the block.
