### ISSUE TITLE
Get comments and approvals for new EC pages for other filers

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2233]
Users have requested an "other filers" section, including information for Form 9 filers making electioneering communications. The page and reporting examples for this section were sent to OGC and RAD for review in #2210 .

**To do**
- [x] Get comments and approval from OGC on rules page
- [x] RAD review and approval of reporting examples
- [x] Compile edits

After this is done, we'll open an implementation ticket to:

- Add "other filers" section
- Post new EC pages

**Comment by llienfec** [comment]
Got RAD comments on reporting example draft back today!

**Comment by llienfec** [comment]
Just got EC images back!  Will work on putting the reporting example together.

**Comment by dorothyyeager** [comment]
The EC rules page edits are compiled at https://docs.google.com/document/d/1bWJoI7-gr-KlT4ZTnsysnTMv-EVrqRR9ulRf09PSc28/edit?usp=sharing.

**Comment by dorothyyeager** [comment]
With the edits compiled, we're ready to close this issue.

Implementation of the new pages will be handled in #2222 (Front end work) and #2248 (Content team work)
