### ISSUE TITLE
[MED] Arbitrary Code Execution (Due 09/10/18)

### ISSUE THREAD

**Issue by rjayasekera** [fecgov/fec-cms#2236]
Check logs sprint 6.5 (Penny Robinson) week 2 #3301 found this issue
https://app.snyk.io/org/fecgov/project/ff0dca01-794e-4c1c-bf1f-0c0f8932fadd

Vulnerable module: PyYAML
Introduced through: bandit@1.4.0

**Comment by lbeaufort** [comment]
Addressed by fecgov/fec-cms#2238
