### ISSUE TITLE
Add authorized committees parameter to /elections

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2244]
Issue #1656 requires the ability to link only principal and authorized committees in the by-size total links in the individual contributions to candidates table. We already have a `candidate_pcc_id` and now just need a `candidate_acc_ids` to grab authorized committees within the /elections endpoint to complete the ticket.

Example API call for elections: https://fec-dev-api.app.cloud.gov/v1/elections/?cycle=2012&office=house&state=AL&stateFull=Alabama&district=1&per_page=0&sort_hide_null=true

Update: this came up again with McCaskill (cc: Paul)
https://fec-dev-api.app.cloud.gov/v1/elections/?cycle=2018&office=senate&state=MO&per_page=0&sort_hide_null=true

**Comment by lbeaufort** [comment]
Issue moved to [fecgov/openFEC #3442](https://github.com/fecgov/openFEC/issues/3442) via [**ZenHub**](https://www.zenhub.com/)
