### ISSUE TITLE
Create "Other filers" collection page and related IE & EC pages for H4CC

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2248]
**User story** Other filers (Forms 5, 7, 9 and eventually 13) need to have a home in Help for candidates and committees too.

**Background - work completed** 
#2131 Content architecture for the section was researched and strategy developed. One important thing we realized is that the IE information needed to be consolidated and consistent. 
#2136 and #2177 Content for the IE pages (Rules for IEs, Form 5 and Form 3X) was developed and approved
#2209, #2210 and #2233 - Content for the EC pages (rules and reporting plus the corporate version up now) was developed and approved.

**Related issue**
#2222 This is the front-end issue for adding the collection page we'll develop here into the hard-coded pages.

**To do:**
- [x] Get IE pages and examples re-reviewed by OGC and RAD to incorporate recent guidance.
- [x] Create the new collection page for other filers. We'll use this to add new pages made for this as child pages. 
- [x] Find approved language or draft new language for the intro text spots on the new collection page.
- [x] Besides the new page, this page will need to include a link to the existing page for Form 7 in the corporate section (https://www.fec.gov/help-candidates-and-committees/making-disbursements-ssf-or-connected-organization/corporation-labor-organization-communications-restricted-class/)
- [x] Create the IE rules page
- [x] Create the  EC rules page
- [x] Create the IE reporting examples and add their cards to the IE rules page.
- [x] Create the EC reporting examples and add their cards to the EC rules page.
- [x] Content team one final lookover and testing
- [x] Publish the pages

**Comment by dorothyyeager** [comment]
The draft collection page (needs a lot of work!) has been started and the new rules page for ECs has been drafted using the language already approved by OGC.

**Comment by dorothyyeager** [comment]
Revised draft text for the collection page has been sent around to the content team for review.

**Comment by llienfec** [comment]
**Reviewed:** Collection page.  Thanks @dorothyyeager for coordinating this!  
**EC Section:** EC reporting example draft to `other filers`
**IE Section:** Meeting with RAD SME this afternoon to go through CREW guidance before requesting image changes from Jim Jones and adjusting reporting example language for F5 IE filers.  Will hopefully have another update this afternoon.

**Comment by llienfec** [comment]
We're getting a little more information on the reporting guidance released by the Commission.  After that, I plan to:
- [ ] Request updated images from Jim
- [ ] Draft language in accordance with the new guidance
- [ ] Make pages and compile the images
- [ ] Send to SMEs for double checking and approval

**Comment by llienfec** [comment]
Got everything re-created - remade pages that were 404ing and updated guidance for CREW case.  Sent to RAD for review.

**Comment by dorothyyeager** [comment]
The landing page introducing the section has been sent to OGC for review.

**Comment by llienfec** [comment]
✅ EC example is approved.

For IE examples: we're moving the dates of the examples so that they happen post-CREW decision and fall in line with guidance.  Another round of image change requests was sent to Jim.

**Comment by dorothyyeager** [comment]
OGC has returned a comment on the intro text for the collection page. We may need to add a glossary entry or a sentence to what we drafted. (The sentence is probably easier.) In any case, it's not a huge edit or blocker.

**Comment by llienfec** [comment]
Updated images to make dates fall after CREW decision per RAD request. Published the IE reporting examples.

**Comment by dorothyyeager** [comment]
We're letting OGC look over the reporting example that was affected by CREW. Once they've OKed it, we'll be ready to go.

**Comment by dorothyyeager** [comment]
OGC has approved the reporting example affected by CREW with one minor wording change. However, one of the forthcoming new pages is a page on reporting independent expenditures that will serve as one home for everyone (PACs, SSFs and other filers) who makes them. That new page will link to a new page with info specific to Form 5 filers and also will link to a new page for PACs and SSFs on reporting IEs on Form 3X. The new PAC page will also have new reporting examples that are being developed in #2492 . Once those are finalized, we will be able to link those new pages up and finalize the pages for the other filers section. We're close!

**Comment by dorothyyeager** [comment]
We've finalized the pages and they are undergoing one last look by the content team.

**Comment by dorothyyeager** [comment]
A few tiny tweaks were made and the content team has finished its final lookover. These pages are good to go. The front end work to make the section visible within the H4CC and Guides pages has begun in #2222 and the content team will make some related new material for SSFs and  PACs available in #2641. Our work on this issue is complete, so closing. Thank you to everyone, especially @llienfec !!!
