### ISSUE TITLE
Make final updates and publish OIG pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2255]
**What we're after:** Following the work done here and here, we need to make any final updates from the OIG team and publish the updated pages. 

Part of publishing the new pages, includes changing the footer link for the Inspector general page. 

**Completion criteria:**
- [x] Make any last updates from final OIG review
- [x] Publish pages in production

**Comment by AmyKort** [comment]
@JonellaCulmer  can we close this and pick up the rest of the work at https://github.com/fecgov/fec-cms/issues/2360 ?

**Comment by JonellaCulmer** [comment]
Yes, thank you, @AmyKort. I couldn't find 2360! I'll close now. 

Closing in favor of #2360.
