### ISSUE TITLE
Add linting and formatting to frontend JS

### ISSUE THREAD

**Issue by apburnes** [fecgov/fec-cms#2259]
To help maintain and standardized frontend JS development, code linting and formatting should be added to the testing/build process.

[eslint](https://eslint.org/) and [prettier](https://prettier.io/) are two popular projects used to lint and format respectively. Adding their functionality to the NPM scripts with a git pre-commit hook would be most advantageous. NPM specific Git hooks could be setup with something like [ghooks](https://www.npmjs.com/package/ghooks)

**Comment by johnnyporkchops** [comment]
@apburnes, this is a much needed! We have not had this type of style-checking since we stopped using hound
