### ISSUE TITLE
Update boolean search box and add tooltip

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2283]
History: https://github.com/fecgov/fec-cms/issues/2051

**What we're after:** Usability testing revealed that users had trouble understanding they could use boolean symbols in the main search for AOs, MURs and Statutes. Therefore, we have made several changes to the "Find documents with..." pop-up box to help improve their use. 

These changes include:
- [x] Modify/add text to explain what each section of the pop-up accomplishes
  - Section 1 text: Use these search boxes to refine your search:
  - Section 2 text: Use these symbols in the main search box:
- [x] Add an "or" dividing line to make it clear the user has options
- [x] Update the symbols table, removing some of the dividing lines in the mini-table to make it flush with the page a bit more
- [x] Add a tooltip to the "Keyword" search on the main search pages for AOs, MURs and Statutes
  - Tooltip text: Refine a keyword search by using AND, OR, “ ”, -,  to expand or limit results.
- [x] Test on internet explorer, ask content staff since they have a different IE build than devs

### Designs
![screen shot 2018-08-14 at 2 30 10 pm](https://user-images.githubusercontent.com/31663028/44110850-d8c4ccd8-9fce-11e8-968a-909b7b70d854.png)

![screen shot 2018-08-14 at 2 31 52 pm](https://user-images.githubusercontent.com/31663028/44110853-dd3702fe-9fce-11e8-8672-5373a04821f7.png)

**Comment by johnnyporkchops** [comment]
@JonellaCulmer , Can you clarify this:
Update the symbols table, removing some of the dividing lines in the mini-table to make it flush with the page a bit more

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Sure! Basically, remove the top and bottom border lines. In this implementation, I think they draw the eye too much.
