### ISSUE TITLE
Design an improved null state for empty calendar

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2285]
History: https://github.com/fecgov/fec-testing/issues/56

**What we're after:** Users have experienced confusion when looking at the calendar and there are no events listed. This can occur based on the filters or criteria they have applied during their search. We need to develop a null state to address this confusion and make it clear to users why they are not seeing any events listed. 

**Completion criteria:**
- [x] Review previous research findings for the calendar
- [x] Mock-up options for improving the null state for an empty calendar
- [x] Demo the options in design sync
- [x] Move to an implementation issue

**Comment by JonellaCulmer** [comment]
Per our discussion in design sync on 8/17, we discussed the use of a no results message. We decided to move forward on a version that also provides reasons why there may be no results. Below is the mock-up, but before we can move to an implementation issue, the content team plans to do a content review and identify the best reasons to include on the no results message. 

**Design:**
This design includes a combination of placeholder text, as well as some language we currently use or have drafted. None of it is final. 
<img width="763" alt="screen shot 2018-08-20 at 8 45 08 am" src="https://user-images.githubusercontent.com/31663028/44342064-d7892700-a457-11e8-9c21-3acc57fe2cab.png">

**Next steps:**
- [ ] Content identifies key reasons to include in the message and provides approved language for the whole message
- [ ] Update mock-up with approved language
- [ ] Move to an implementation issue
- [ ] Move to a testing issue

cc: @llienfec @dorothyyeager @rhoughfec @AmyKort

**Comment by llienfec** [comment]
Here's the drafted updated language.  I'm going to run this by @rhoughfec when she's back later this week.

### No results for this month

To find the information you're looking for, try:
- Changing the month to look for future dates.
- Adjusting the filters.  For example, check "Pre- and post-election" under filing deadlines in addition to "Quarterly reports" or "Monthly reports."

This this is a mistake or have questions?
Send us more information in the feedback box or contact us.

**Comment by llienfec** [comment]
We're good to go with the language above.  Thanks!

**Comment by JonellaCulmer** [comment]
Closing this issue in favor of implementation ticket: https://github.com/fecgov/fec-cms/issues/2315
