### ISSUE TITLE
Design updated election search page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2286]
History: https://github.com/fecgov/fec-testing/issues/113
Relevant feedback issue: https://github.com/fecgov/FEC/issues/7642

**What we're after:** It's been observed that users have had difficulty finding search results on the election search page. Often the results populate below the fold and users cannot tell that the search has worked.

The problem seems to be that there is no visual cue that the page has changed in any way. From their perspective, between selecting a state or year, there's no visual change. Other than the map updating. But it seems even that is unclear to our users that their search has, in fact, yielded results.

**Completion criteria:**
- [x] Review research on the election search
- [x] Mock-up options to improve the usability of election search
- [x] Demo options in design sync
- [x] [Content review](https://github.com/fecgov/fec-cms/issues/2286#issuecomment-416695758) of language changes to search results section (@llienfec @AmyKort @dorothyyeager) 
- [ ] Move to an implementation issue
- [ ] Update testing issue with mock-ups and testing criteria

**Comment by JonellaCulmer** [comment]
Below is a mock-up for improving the election search page. However, there are some unanswered questions. 

- [ ] @patphongs The search button is available to users, but the way the search is built, is not required to complete the search. You mentioned checking to see whether that was something we needed. 
- [ ] @llienfec @dorothyyeager We have modified the language that explains which results are shown on the page.  Original text below. Because we have changed the way this page functions and all districts are shown, the language ("If no candidates have filed...") is no longer accurate. Also, we show elections for Senate and President. While users can toggle to the district and see all applicable elections including Senate and President as part of their search, it's not readily understood that that is the case. Can you suggest some language to resolve this? Or do we even need to include any additional information here at all?
> This page shows financial data by district. If no candidates have filed (or if candidates have filed by not yet reported financial data), the district may not show up here.

**Design:**
<img width="1113" alt="screen shot 2018-08-28 at 2 38 05 pm" src="https://user-images.githubusercontent.com/31663028/44743261-034b8300-aad0-11e8-909c-84873aa02aa6.png">

**Comment by JonellaCulmer** [comment]
Updated mock-up to include the search button. Even though we don't necessarily NEED the search button, I'm not finding any significant justification, based on UI guidance, for removing it. 

<img width="967" alt="screen shot 2018-09-06 at 2 00 25 pm" src="https://user-images.githubusercontent.com/31663028/45176262-6f6b6c80-b1dd-11e8-9231-bce0771999ae.png">

**Comment by llienfec** [comment]
Thanks for having us weigh in @JonellaCulmer!  

**Preference 1:** No text.  Would that move the search results up enough to go above the fold? 

**Preference 2:** `This page shows financial data by office sought, state and district.`

**Comment by JonellaCulmer** [comment]
@llienfec Thanks so much! Let's go with preference 1 and when we test later we can incorporate whether or not folks understand what their results entail without prompting. 

I think the removal of the results text and the reorganization of the search fields will both help to move the results above the fold.

**Comment by JonellaCulmer** [comment]
Updated mock-up for election search page: 
![screen shot 2018-09-11 at 2 42 55 pm](https://user-images.githubusercontent.com/31663028/45380592-10d53280-b5d1-11e8-8d00-ec29579aee07.png)

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issue #2353
