### ISSUE TITLE
Research pages needing edits if the Senate e-filing bill passes

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2287]
The Senate e-filing bill pending in Congress would change the point of entry for Senate candidate filings. Users will need to find the new address (if the bill becomes law and the point of entry changes). They'll also need updated filing information.  Because this will take effect immediately upon passage, we need to be able to quickly change the address and update reporting guidance across the website.

**To do**
- [x] Info - Make a spreadsheet of the pages that will need changes (This has been assigned to an Info Division specialist and they've been given a copy of the address change spreadsheet to work from).
- [x] RAD - review pages too
- [x] Compare notes 

**Be sure to check for:**
- Senate address
- References to senate filing

**Comment by llienfec** [comment]
Hey @dorothyyeager - I was tasked with this from the RAD perspective.  Hope to get this research done in a few days and we can compare notes.  Updating the scope above.  Excited that we're getting ahead of this!

**Comment by llienfec** [comment]
Sent spreadsheet to @dorothyyeager with additional instances/mentions to add to our shared list.

**Comment by dorothyyeager** [comment]
Our spreadsheet is at https://docs.google.com/spreadsheets/d/1gT7xDHnacpslC_Gob1JpySy2Mg-SHOaundhaJuPmf3M/edit?usp=sharing

**Comment by dorothyyeager** [comment]
@llienfec and I met to compare notes and make sure we felt like we got everything. Having done the research for this task, compiled in our spreadsheet above, we're ready to close this issue. Should the pending legislation concerning Senate point of entry become law, we'll open an implementation issue ASAP.
