### ISSUE TITLE
Add FEC to code.gov

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2288]
Once PR https://github.com/fecgov/fec-cms/pull/2260 is merged: 

- [x]  create an issue in code-gov to scrape our site (provide [FEC seal image](https://www.fec.gov/static/img/seal.svg) in issue)

- [ ]  put in a PR to code-gov?

**Comment by lbeaufort** [comment]
Issue created in code-gov: https://github.com/fecgov/fec-cms/pull/2260

**Comment by lbeaufort** [comment]
FEC is live on code.gov: https://code.gov/#!/browse-projects?agencies=FEC

**Comment by JonellaCulmer** [comment]
@lbeaufort Any way we can get our name updated to remove the s from Elections?

**Comment by lbeaufort** [comment]
I already put in a PR so it just has to go live.
