### ISSUE TITLE
404 Errors when clicking through to individual candidate/committee pages

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#2294]
Some candidates and committees that show up in the initial datatable results for `data/candidates` and `data/committees` get 404 errors when you click through to view their individual pages:
Examples:
Candidates:
MENEFEE, JON MARK MR : https://www.fec.gov/data/candidate/H0TX09168/ 

MARTIN, JOSEPH S: https://www.fec.gov/data/candidate/P40003832/

~Committees~ Fixed by PR #2296 
SIERRA CLUB: https://www.fec.gov/data/committee/C90011875/

**Comment by JonellaCulmer** [comment]
Closing, since the PR/hotfix has been merged.

**Comment by lbeaufort** [comment]
@jonellaculmer this issue isn't complete - only the committees are fixed

**Comment by lbeaufort** [comment]
We had to back  fecgov/fec-cms#2316 because we discovered issues with past candidates (https://github.com/fecgov/fec-cms/issues/2343) too close to the release.

**Comment by lbeaufort** [comment]
Closing in favor of https://github.com/fecgov/fec-cms/issues/2349

cc: @patphongs
