### ISSUE TITLE
Update "committee profile page" template used for EC filers

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2301]
We're currently using the main "committee profile page" information for electioneering communications filers; however, a lot of information doesn't apply to ECs.  These changes affect filers with ID numbers that start with C3.  Most of the suggestions below are because:
- These are `filers` instead of `committees`
- They don't file F1s or have "regularly filed reports"

If these changes are possible, we also need to review the C9 independent expenditure filers "committee profile pages."  Those filers will need similar (but less extensive) updates.

Example committee: https://www.fec.gov/data/committee/C30001366/
Relevant committees: File on Form 9
Type: Electioneering communication committees 
Committee ID: C3XXXXXXX

**Completion criteria:**
- [x] Investigate in the API whether we need to introduce new logic to distinguish between EC filers and other committees. (There are committee type C and we already do dynamically generate financial summary pages based on committee type. Check out get_committee view.)
- [x] Update the conditionals with the `committees-single.jinja` file to render what is described below
- [x] Implement changes in language and appearance suggested below

### Menu:
- [x] Change "About this committee" to "About this filer"
- [x] Under Spending, add s to "electioneering communication"

### About this committee:
![image](https://user-images.githubusercontent.com/22914750/44487321-03590800-a624-11e8-96aa-c2908fd74ac5.png)

### Spending
- [x] Within the description for the EC section and the disbursements section, indicate it's a disbursement by inserting the words "Any disbursement for a..." 
- [x] Electioneering communications - switch the columns for all ECs information on committee profile pages
![image](https://user-images.githubusercontent.com/22914750/44487541-88dcb800-a624-11e8-97fd-7dd1ef81edd8.png)

- [x] Conditionally add candidate disbursement column in the table for only EC committee type pages. Column name should be "Candidate".
![image](https://user-images.githubusercontent.com/22914750/44487549-8d08d580-a624-11e8-87a2-9f25fb2c67b6.png)

### Filings
- [x] Conditionally remove "regularly filed reports" and "Statements of organization" only for EC committee type pages.
- [x] Change "24- and 48-hour reports" to "24-hour reports"
![image](https://user-images.githubusercontent.com/22914750/44487631-c04b6480-a624-11e8-94bc-4fe4638aee2c.png)

**Comment by patphongs** [comment]
@llienfec We made a few technical changes to the completion criteria you laid out above, can you please double check?

**Comment by llienfec** [comment]
@patphongs Looks good.  I added in a criteria above to adjust the menu options under filing.  Thanks so much for working on this!

**Comment by pkfec** [comment]
I am conditionally hiding the links for EC committee type like mentioned in the ticket above. However, its not clear  if we have to hide the `Raising` link and also hide or not show the `Other documents` under the `Filings` link. 

@llienfec Can you please tell me how to proceed further? 
cc @jwchumley

**Comment by llienfec** [comment]
Hi @pkfec  - I think we should hide the `raising` link.  Keep the `other documents` link under `filing`.  ECs may file something like a Form 99.  I don't know why they would, but I think they're allowed to.  So while it wouldn't be used often, it's safer to keep it visible.

Great questions!  Let me know if this is unclear.

**Comment by pkfec** [comment]
@llienfec Thank you! I will work on this.

**Comment by pkfec** [comment]
The endpoint that returns the disbursements data for C3 filers is : **v1/schedules/schedule_b/**

The disbursement candidate info for C3 filers is not available in the DB.  After looking at that C3 filers data, it appears that disbursement candidate information is never submitted on Form9. 
I can still add the  `Candidate` column to the `Disbursements` datatable,  however there is NO DATA  to display under this column. In this case should we still display the `Candidate` column?

**Other C3 filers without Disbursement candidate information:**
"C00009282"
"C30000012"
"C30000020"
"C30000038"
"C30000046"
"C30000053"
"C30000061"
"C30000079"
"C30000087"
"C30000095"
"C30000103"
"C30000111"
"C30000129"

**Screenshot of  Disbursements datatable  for `C30002885` after adding the `Candidate` column:**

![screen shot 2018-11-27 at 9 16 08 pm](https://user-images.githubusercontent.com/11650355/49124263-ba02ff00-f289-11e8-8be3-bbccf8152c64.png)

**API call:**
https://api.open.fec.gov/v1/schedules/schedule_b/?sort_null_only=false&committee_id=C30002885&api_key=DEMO_KEY&two_year_transaction_period=2018&sort_hide_null=false&per_page=20&sort=-disbursement_date

**JSON Screenshots without candidate information:**
![screen shot 2018-11-27 at 8 31 42 pm](https://user-images.githubusercontent.com/11650355/49123608-406a1180-f287-11e8-9735-5cfc6c95bc6d.png)

![screen shot 2018-11-27 at 8 31 10 pm](https://user-images.githubusercontent.com/11650355/49123552-fc770c80-f286-11e8-875a-5d39ca917dac.png)

cc: @fecjjeng @jwchumley @PaulClark2

**Comment by pkfec** [comment]
Disbursement Candidate information for EC filers is not available in SB endpoint.  @PaulClark2 suggested that EC filers committee, disbursements candidate information can be obtained from  `/electioneering/` endpoint. However on the API, these two columns `payee_name` and `payee_st` are not mapped in the EC model which are required columns and are displayed in the `disbursement` section. I will open a new API ticket to map these two DB columns and update the EC model file.

`SB `api call:
https://api.open.fec.gov/v1/schedules/schedule_b/?sort_null_only=false&committee_id=C30002885&api_key=DEMO_KEY&two_year_transaction_period=2018&sort_hide_null=false&per_page=20&sort=-disbursement_date

`/electioneering/ `api call:
https://api.open.fec.gov/v1/electioneering/?sort_hide_null=false&committee_id=C30002885&page=1&per_page=20&api_key=DEMO_KEY&sort_nulls_last=false
