### ISSUE TITLE
Wagtail returning random server error when task is attempted

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2303]
I was trying to change out the tips for treasurers .xml file and got this error. Logging for @patphongs who asked me to log these errors in a github ticket when they occur. Also noticing in Wagtail when I hover over the document link - I see "forbidden" and also an incorrect (old) date for when the document was last uploaded. (It says August 28, 2017, but we uploaded the newest update to it on Monday the 20th.)

![image.png](https://images.zenhubusercontent.com/59833ec0f8b79f8376e1d2ce/d235980d-df1c-45f2-a6c7-98d88680f6a7)

**Comment by patphongs** [comment]
It appears that if someone is trying to replace a file, it will instead delete the file from the S3 bucket. Investigating why that happens...

**Comment by patphongs** [comment]
Created a temporary patch until Wagtail can fix this: https://github.com/fecgov/fec-cms/pull/2331

After the PR is implemented, if content owners wish to retain the same URL and filename for their images/documents they will need to:

1. Choose the file they want to replace, **the file must be of the same name.**
2. Click Save. Now the document/image will have random numbers appended to the name
3. Go back into the same document/image resource again and choose the file to replace, **the file must be of the same name.** 
4. Click Save. This will rename the file back to what its original.
