### ISSUE TITLE
Add "example image" to Resource & Custom templates in Wagtail

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2304]
In Wagtail, we need to add the `example image` block to:
- [x] Resource tempate
- [x] Custom template

Right now, it's available in the Reporting Example template.  It's a really useful widget  b/c of the large image size and the ability to add a caption. We need the `example image` block to be more widely available to continue building the Outreach page.

![image](https://user-images.githubusercontent.com/22914750/44550458-5b5e4000-a6f2-11e8-8703-0b6fab994870.png)

cc: @dorothyyeager @JonellaCulmer

**Comment by dorothyyeager** [comment]
@johnnyporkchops has done the work and it's in https://github.com/fecgov/fec-cms/pull/2346

**Comment by dorothyyeager** [comment]
Clarifying - the work has been done for the research page in #2346 . Will need to add to custom page template still.

**Comment by patphongs** [comment]
#2346 has implemented this, closing
