### ISSUE TITLE
Test React 16 upgrade due on 9/6/2018

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2307]
React 16 is now on the feature environment (https://fec-feature-cms.app.cloud.gov/). Please make sure that it is *tested thoroughly by Thursday 9/6/2018*, this will give us time to address any critical issues. Deploy to production will be on 9/11/2018. Any problems from the upgrade, please note within this ticket.

- [x] AO Search datatable page: https://fec-feature-cms.app.cloud.gov/data/legal/search/advisory-opinions/. Make sure all filter components work
  - [x] AO Number
  - [x] Requestor Name
  - [x] Requestor type
  - [x] Keywords
  - [x] More keyword options (Advanced search)
  - [x] Show only pending requests checkbox
  - [x] Final Opinion checkbox
  - [x] votes checkbox
  - [x] draft docs checkbox
  - [x] AO Request, Supplemental Material, and Extensions of Time checkbox
  - [x] Withdrawl Request checkbox
  - [x] Comments and Ex parte Communications checkbox
  - [x] Commissioner Statements checkbox
  - [x] Show cases citing any of them, Show cases citing all of them radio buttons
  - [x] Regulatory citation
  - [x] Statutory citation
  - [x] Issued Date
  - [x] Request Date
  - [x] Entity name
- [x] Make sure that the AO canonical page displays correctly and works https://fec-feature-cms.app.cloud.gov/data/legal/advisory-opinions/2018-10/

**Comment by dorothyyeager** [comment]
We've got a few Information Division staffers who will test this for us. Am sending them this checklist now.

**Comment by prstoetzer** [comment]
The first thing I note is that the search interface does not load at all in Internet Explorer.

**Comment by prstoetzer** [comment]
Completed the checklist. The only problem I noted, other than the Internet Explorer compatibility problem, is filtering by a statutory citation.  When attempting to filter by a statutory citation, the search process never completes (or takes longer than 2 minutes to do so, I did not wait beyond 2 minutes).

**Comment by dorothyyeager** [comment]
From Chris: _I was able to complete the checklist with only one issue: the statutory citation filter doesn’t return any results for citations I know are referenced in a number of advisory opinions (30143 for example)._

**Comment by dorothyyeager** [comment]
From Don  (who tested using Chrome):
_1.	The “Statutory citation” search does not populate any results. It stays on the loading screen.
2.	The “Entity name” search does not show all possible results. 
Internet Explorer did not work._

**Comment by patphongs** [comment]
Confirmed that statutory citations filter does not work. This is also a problem in production, which seems to be an API bug, unrelated to React. A bug ticket has been made for this here: https://app.zenhub.com/workspace/o/fecgov/openfec/issues/3271.

**Comment by patphongs** [comment]
@prstoetzer @dorothyyeager and Chris, thanks for helping to test the AOs. I wanted to follow-up about the AO filters not working in IE. I just tried it on my windows machine and it is working. Are there any errors that you get in IE? Does it just hang?

**Comment by prstoetzer** [comment]
This is all I see.

![ie screen](https://user-images.githubusercontent.com/31514408/44922915-b7d5e680-ad14-11e8-8f58-fbf469ac268c.png)

**Comment by dorothyyeager** [comment]
Don sent me a similar screencap to that above - IE is not loading the page for them.

**Comment by dorothyyeager** [comment]
Chris was able to test the pages on Opera and Safari. He only noted the same issue with the Statutory Citations in both browsers, but no other problems.

**Comment by dorothyyeager** [comment]
I tested too. Here's my notes:

On https://fec-feature-cms.app.cloud.gov/data/legal/search/advisory-opinions/, the search filters work, but maybe not as effectively as they could. Some examples:

- Searching "Al Franken" as requester gave me too many results, and some that were frankly not right. (I did get his AO though).

- I put "114.2(f)" as my keyword and got way too many wacky results. Not sure why. Putting 114.2 into the "citations" search yielded the right AOs, but I couldn't narrow the reg to 114.2(f).

- Searching requester type "corporation" yielded LLCs too. Other types of requester types also seemed to yield too much - "Individual" gave me more than "individuals" for example.

Like everyone, I got the blinking flag with no returns when searching with statutory citation filter, and I got the screencap above showing nothing when I used IE.

No comments from me on https://fec-feature-cms.app.cloud.gov/data/legal/advisory-opinions/2018-10/. That seemed to be fine.

**Comment by llienfec** [comment]
@patphongs - Confirming that search results do not show up for the AO search when using IE 11. Also confirmed that the AO filter is currently working on IE 11 in production.

Let me know if you'd like me to show you or if you need me to look at anything else.

**Comment by patphongs** [comment]
@apburnes Is going to try a polyfill to fix this issue, will update this ticket again when that has been implemented so that content can test these pages again in IE.

https://reactjs.org/docs/javascript-environment-requirements.html

**Comment by apburnes** [comment]
See #2330

**Comment by patphongs** [comment]
Fix for statutory citations should be in the upcoming release, it's pending review now: https://github.com/fecgov/openFEC/pull/3363

**Comment by llienfec** [comment]
Re-tested the AO search showing results in IE browser -- looked good.

**Comment by dorothyyeager** [comment]
Chris tested on IE and here are his notes:
_One small issue I just noticed is that the requestor name field is finicky. When I search for “DSCC,” I get nothing, but when I search “Franken,” it returns “Franken/DSCC.” Other requestor name return without a hitch.

Otherwise, I had no issue other than the statutory citation search_

**Comment by patphongs** [comment]
Testing has been completed. IE 11 issue is fixed with Polyfill and the statutory citations filter is now working in the staging environment, that fix will be deployed on 9/11. 

Any outstanding issues that seemed to be unrelated to the react upgrade have been logged within this issue for further analysis: https://github.com/fecgov/fec-cms/issues/2335
