### ISSUE TITLE
Candidate raising/spending tab "compare" button taking users to the wrong election profile pages

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2321]
If a user is on a candidate raising/spending page on an off-election year and clicks "Compare to opposing candidates" they will be taken to an election profile page where the candidate isn't running. We need to pass the `election_year` for the button rather than the `two_year_period`.

Example: 
Go to https://www.fec.gov/data/candidate/S2MA00170/?tab=raising&cycle=2014&election_full=false

Click the "Compare to opposing candidates" button  
<img width="253" alt="screen shot 2018-08-29 at 4 53 46 pm" src="https://user-images.githubusercontent.com/31420082/44814957-29deec00-abac-11e8-82ad-d85dcaa8b63b.png">

![screen shot 2018-09-18 at 10 57 47 am](https://user-images.githubusercontent.com/12799132/45696483-b89eb300-bb31-11e8-9799-b444aec1d048.png)

You're taken to the 2014 election profile page, where the candidate did not run: https://www.fec.gov/data/elections/senate/MA/2014/

**Comment by patphongs** [comment]
Check special candidates, past and current presidential candidates.

Example special candidate: 
- Jon Ossoff had a special in 2017
- Doug Jones
- Luther Strange

**Comment by patphongs** [comment]
Looks like more work needs to be done for specials on this issue: https://github.com/fecgov/fec-cms/pull/2340#issuecomment-420850485. Moving this to 7.2.

**Comment by AmyKort** [comment]
Should we move this ticket to 7.3?
