### ISSUE TITLE
Research: Identify any past efforts of connecting a candidate and leadership committee

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2329]
**User story:** As a concerned citizen, I want to see how candidates are connected to leadership PACs, so that I can better understand how money is being raised and spent in races relevant to me.

**What we're after:** We have received multiple requests from users to make it easier for them to identify the candidates affiliated with leadership PACs. Both to improve navigation to those candidates or committees, as well as to better understand the way those committees are raising and spending money. 

There are, however, legal implications to completing this work, including a leadership PACs non-affiliation to a candidate's other authorized committees and considering that to date, we have not made this kind of connection between a candidate and their leadership PAC.

**Completion criteria:**
- [x] Inquire with Press/Public Records about the past efforts of connecting a candidate to a committee. Need to determine what boundaries may/must exist between a candidate's leadership PAC and the authorized committees. 
- [x] Identify next steps

**Comment by dorothyyeager** [comment]
This H4CC page may help too... https://www.fec.gov/help-candidates-and-committees/registering-pac/types-nonconnected-pacs/ (Go to the leadership PAC heading.)

**Comment by patphongs** [comment]
@JonellaCulmer Please circle up with @AmyKort about this. She knows more.

**Comment by JonellaCulmer** [comment]
After speaking with the Press office, we have come away with some new information: 
- **Sponsors are not consistently provided on Form 1.** This makes it difficult to connect all leadership PACs to the appropriate candidate. So any solution we propose is in jeopardy of not being made available for all leadership PACs unless we're able to confirm the sponsor for all active and terminated leadership PACs.
- **The money is entirely separate.** The way our pages are currently structured should not necessarily preclude the possibility of adding raising/spending data on a candidate or officeholders leadership PAC. But any solution would need to make it crystal clear that the money raised and spent on connection with that connected candidate's election is NOT related to the money raised and spent for their leadership PAC, which is often used to support other candidates. 

**Next steps:**
Based on these takeaways, it seems as though this is not an impossible task, just a difficult one. And I would recommend next steps include a brainstorming session to identify the commonalities between committees with known sponsors and unknown sponsors to see if there is a path forward to addressing this user need. 
cc: @AmyKort

**Comment by JonellaCulmer** [comment]
Closing this issue in favor of meeting to discuss next steps in https://github.com/fecgov/fec-cms/issues/2369
