### ISSUE TITLE
Training on deploying proxy, blocking IPs in NGINX

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#2332]
As part of the corrective actions for recent website [slow-performance issue.](https://docs.google.com/document/d/18uXN2WBY6eWZuuXCG6YE8KE90IGcF_KHskqbC3kL2BI/edit#)  We need to make sire that multiple people should know how to block IPs in the NGINX conf and deploy to proxy. 
Who else knows? 
We should have a training. Also need to show how to block IPs in Nginx.

**Comment by patphongs** [comment]
I will discuss this during engineering sync tomorrow (thurs)

**Comment by patphongs** [comment]
This training has been completed in engineering sync, closing this issue
