### ISSUE TITLE
Test line chart data due 9/20

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2334]
The line charts for Raising and spending will be re-implemented into 3 places on the site (see list below). Testing for this should be completed by **9/20** and this feature will be released to prod on **9/25**:

- Data landing - https://fec-dev-proxy.app.cloud.gov/data/
- Raising data page - https://fec-dev-proxy.app.cloud.gov/data/advanced/?tab=raising
- Spending data page - https://fec-dev-proxy.app.cloud.gov/data/advanced/?tab=spending

Things to test:
- [ ] Ensure that the data is accurate across all years in the chart. The data in the chart goes all the way from 01/01/2007 - 08/31/2018
- [x] Check functionality and make sure the cursor lines up with the dotted line in the chart. Some bug fixes went into making that more smooth.

**Comment by llienfec** [comment]
The functionality of the line and data points looks great.  The cursor moves much more predictably and if you put your cursor on a month, the totals include data for that month.  Looks really good!

Checking the data is a little more complicated and needs a team-swarming approach:
- @PaulClark2 is going to help me get the data from another source other than the API so that we can check that the numbers are accurate.
- I'm going to split up the testing into smaller portions.
- We're going to seek 5-10 volunteers to help check the data points across the chart's 3 locations.

**Comment by llienfec** [comment]
API fixes explained here: https://github.com/fecgov/openFEC/pull/3251 and https://github.com/fecgov/openFEC/issues/3240

**Comment by patphongs** [comment]
Let's create some feature flags for the charts. That way if there's a problem we can easily flip the flag to remove the charts until things are fixed.

**Comment by patphongs** [comment]
Created feature flags for the charts, we can flip them on/off now without needing a hotfix

**Comment by llienfec** [comment]
@PaulClark2 sent the data to test so I'll be splitting it up among team members.

I'm having trouble easily moving between election cycles - I think I may be missing something obvious (apologies if so!).  The interaction to move between election cycles take a really long time. You have to press the arrows for each data point on the graph to get to the previous cycle.   I think that in the past, the arrows moved users between cycles.  If there's any way that we can change the arrow action to move between cycles instead of months, that would be really helpful.

![image](https://user-images.githubusercontent.com/22914750/45758177-04656100-bbf3-11e8-9d37-10dbc583973a.png)

**Comment by patphongs** [comment]
@llienfec This has actually always been the interaction of the arrows. That's certainly something to take a look at as an enhancement to the chart @JonellaCulmer? cc @PaulClark2

**Comment by JonellaCulmer** [comment]
@patphongs That's correct. @llienfec The timeframe has always been from the start of the cycle through that month. The toggle is used as a way for those with accessibility concerns to arrow through if they are unable to use their mouse to move between time periods. 

However, the inability to move more quickly between cycles is something to consider when we take a closer look at the helpfulness of this chart and see what kind of feedback we can from the reaction box and user testing. The primary purpose of this reimplementation was just to be put back into production what we currently have built - with some slight modifications.

Some questions I'd like answered include: 
- Is previous cycle raising/spending as valuable at this high-level view, or are folks interested in doing quick comparisons for time? 
- How else might folks like this information displayed?

In addition to:
- Are users better able to find the charts on the advanced data pages than they were on the data landing page?

**Comment by llienfec** [comment]
Make sense, thanks for taking a look.

**Comment by llienfec** [comment]
### Line chart testing instructions
**Assignments:**
- [ ] [2007-2008 Raising - Priya](https://docs.google.com/spreadsheets/d/1kFvwnycWRoUkqfVHYMC3hu1rxASxnTesjIbFSyRrNeY/edit?usp=sharing)
- [ ] [2007-2008 Spending - Rohan](https://docs.google.com/spreadsheets/d/1rUMIZ8gl-fWNEPFtsTGxZUmXaw1l01FhcgitRcpEjQs/edit?usp=sharing)
- [ ] [2009-2010 Raising - Helen](https://drive.google.com/open?id=1GgRABZ-VXxjkNpyPgteZ5Wl4xeVnUzPsrNDzcobChI4)	
- [ ] [2009-2010 Spending - Charlie](https://drive.google.com/open?id=1Sx8LP22osSYlqNQ2JZFhu-pjXHTkJMW1MmQkLHJfJMM)
- [ ] [2011-2012 Raising - Laura](https://drive.google.com/open?id=13VZc04etj7ovH_m-SMlAoIw57wbba0CynNGaOzJiafc)
- [ ] [2011-2012 Spending - Jean](https://drive.google.com/open?id=1iIvqzdLHnf-XF18nwynPgScBGrKOj80S3IXQi5vjJQE)
- [ ] [2013-2014 Raising - Lauren](https://drive.google.com/open?id=1YPiL6p1Uy7ynJs4H6nEHmiasFitMoyyOgcMP68LRtZk)
- [ ] [2013-2014 Spending - Lauren](https://drive.google.com/open?id=1Wh_Dw80aIjb1cLvXRNLdQfeHknJUL-ZpAHPLteymKB0)
- [ ] [2015-2016 Raising - Pat](https://drive.google.com/open?id=1fsefqhl5J3ItvEaz2jvhU00t9lI20AcpqCOOm_bYvEI)
- [ ] [2015-2016 Spending - John](https://drive.google.com/open?id=1XHb_jUZy8uapNhCIJ1u-rvkPjTYx52AFoq30ya-2aJg)
- [ ] [2017-2018 Raising - Jonella](https://drive.google.com/open?id=1gaurI3XIbk_7kQlU9o3OkVZi8re1gPVpi-Yq7rudzn4)
- [ ] [2017-2018 Spending - Dorothy](https://drive.google.com/open?id=1qDstU-3CUaGqkHuTO3jAQH-hq5tiWLn0H37fAKChzGw)

#### Goal:
We’re checking that the data is right on the line charts.  We’re hoping to finish this by **Monday (9/24) close of business.**  Let me know if you can't or have problems.  

#### Directions:
Compare the data in the link with your name (it’s a google sheet) to the data in these line charts:
People testing RAISING:
1.	https://fec-dev-proxy.app.cloud.gov/data/  (first chart on page)
2.	https://fec-dev-proxy.app.cloud.gov/data/advanced/?tab=raising

People testing SPENDING:
1.	https://fec-dev-proxy.app.cloud.gov/data/ (second chart on page)
2.	https://fec-dev-proxy.app.cloud.gov/data/advanced/?tab=spending

#### Findings:
- If there’s a problem, highlight the cell in yellow in your spreadsheet.  Also, Slack the #data channel and tag me so I know there’s a problem.
- If the data matches 100%, check the box.  Feel free to Slack me w/ questions!

**Comment by patphongs** [comment]
The line chart will be hidden under the `FEC_FEATURE_LINECHARTS` flag after deploy tomorrow (9/25) until we can determine and fix the mismatch of data.

**Comment by dorothyyeager** [comment]
@jwchumley please add your findings about the data discrepancies - Thanks!

**Comment by patphongs** [comment]
The testing has been completed and the line chart data issue was moved to this ticket: https://github.com/fecgov/fec-cms/issues/2449. Closing this issue.
