### ISSUE TITLE
Wagtail 2.2.1 issues

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2337]
These are issues that came out of testing for Wagtail 2.2.1 (https://github.com/fecgov/fec-cms/issues/2305). Could use some refinement in the future:

**Collection page template:**
- [ ] Gray dividing line, does not appear. This is the same problem from our 2.0 upgrade.
- [ ] Right-aligned picture seems to appear out of order, or not where it was intentionally placed.

**Resource template**
 - [ ] Buttons and legal citations section are the wrong color (should be red if a H4CC page). I was able to toggle the breadcrumb color.
- [ ] Still have the small font in indented lists in the intro section. [Known issue,](https://github.com/fecgov/fec-cms/issues/1916) not a dealbreaker.
- [ ] An image placed as a separate section worked, but the anchor link on the left side menu did not work. This is a feature we might want to incorporate in future outreach pages, so definitely would want to fix this.

**Reports landing page template**
- [ ] We can't create additional reports landing pages, however, you are able to modify the existing one and publish it. 

**All templates**
- [ ] Horizontal rule does not appear when published on page

**Comment by dorothyyeager** [comment]
Just a note on the image as section - @johnnyporkchops looked into fixing that and found it created other problems. There is a workaround now that he's added the image block to the RTE editor, so this is not something we must have fixed anymore. Thanks!

**Comment by AmyKort** [comment]
Can we close this?

**Comment by dorothyyeager** [comment]
My vote would be yes - @johnnyporkchops fixed the breadcrumb thing on the resource template and the other items mentioned are just improvements and not dealbreakers. I'd defer to @patphongs though...
