### ISSUE TITLE
Test candidate filings tab by 9/20/2018

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2339]
A filings tab has been implemented on all candidate pages in order to display their Statement of candidacy and other documents. We need to test to make sure everything looks good before release. This feature will be **released on 9/25/2018**. All testing must be completed by **9/20/2018** in order to catch any major dealbreakers before release.

For reference, original issue is https://github.com/fecgov/fec-cms/issues/2154 and the PR that was merged is https://github.com/fecgov/fec-cms/pull/2310

Filings tab can be tested on develop. Here's an example URL of a candidate profile page: https://fec-dev-proxy.app.cloud.gov/data/candidate/S6AZ00019/?tab=filings

**Completion criteria:**
- [x] Ensure filings tab and sub items of the filings tab exists on candidate profile page left hand nav
- [x] For current candidates, ensure that the "About this candidate" tab lists only the candidate's current version of their Form 2 Statement of candidacy. Example: https://fec-dev-proxy.app.cloud.gov/data/candidate/S2MA00170/?tab=about-candidate
- [x] Check the filings tab to make sure that within the Statement of Candidacy (SOC) table all versions of the Form 2 is present including the current version
- [x] Check the SOC table to make sure that only F2s and RQ-5s display here.
- [x] Check that the `Other documents` table within the filings tab has all the necessary docs and are accurate. There should be no RFAIs listed in this table. 
- [x] Check that the SOC table has columns in this order: Document > Version > Date filed > **Image number** > Pages

**Comment by johnnyporkchops** [comment]
This candidate 404s John S. McCaine for President:
https://fec-dev-proxy.app.cloud.gov/data/candidate/P80002801/
Works in prod:
https://www.fec.gov/data/candidate/P80002801/
The other examples of 404 errors that @lbeaufort fixed in PR #2320 are working ,so hopefully this is just an outlier.
Example of previous candidate that got 404 (now working)
https://fec-dev-proxy.app.cloud.gov/data/candidate/P40003832/

**Comment by patphongs** [comment]
It seems to 404 on past candidates who no longer have financial activity because it is trying to call to the 2018 cycle, but that candidate does not have data in 2018, so it 404s. 

Below is an example of another candidate that 404s, George Bush:

https://fec-dev-proxy.app.cloud.gov/data/candidate/P00000455

API Call:

ERR INFO:data.api_caller: load_single_type: https://fec-dev-api.app.cloud.gov/v1/candidate/P00000455/history/2018/?per_page=1&election_full=False

**Comment by lbeaufort** [comment]
@patphongs @johnnyporkchops thanks for finding this. It looks like it's an issue on stage, so most likely a "feature" of the candidate refactoring/404 bug fix work. We should fix this before the release tomorrow. I can't find a testing issue for testing the candidate 404's - it may have been missed.

**Comment by llienfec** [comment]
Tested a handful of committees.  Only saw one strange case where a Form 2 that is a letter should come up as the most recent F2 under "About this candidate," but doesn't.  The weird part is that it's first in the statement of candidacy list under "Filings."

> H2CA42023 – most recent F2 on file is a letter from 11/28/2006.  It shows up in the doc feed but not on the first page.

Tested candidates are below. I plan to look at a couple more senates and some presidentials tomorrow.  Also need to find some examples where people have received RQ-5s to make sure those are showing up correctly.  MS-Hs (disavowal notices) are showing up correctly in the other documents section.

H0LA03018 – good
H4TX02082 – good
H4LA03069 - good
H8TX16109 – good
S2MN00019 – good
S4KS00010 – good
S8VT00059 – good

**Comment by llienfec** [comment]
`Potential issue` I'm looking at the candidate filing tab and it looks like it's not responsive like the committee filing tab for the same candidate.  I used S2TX00106 and C00369033:

### Candidate filing tab 
At half width on my Surface - can't see the entire table and can't scroll:
![image](https://user-images.githubusercontent.com/22914750/45571930-e0420280-b835-11e8-8431-1a1620b61d62.png)

### Committee filing tab - responsive
![image](https://user-images.githubusercontent.com/22914750/45571955-f51e9600-b835-11e8-8aa8-26358631dc47.png)

**Comment by llienfec** [comment]
@patphongs I'm finished with testing.  The only real problem is the data chart's responsiveness mentioned above.  The testing items from the ticket above all passed.  This round of testing is finished.  We can either close this ticket and make a new one for the responsiveness issue, or we can add it on here.  Whichever works best for you.  Thanks!

**Comment by patphongs** [comment]
Closing out this testing ticket as it has been completed. Opened 2 new follow-up issues to take care of the responsive and recent F2 issue: 

https://github.com/fecgov/fec-cms/issues/2381
https://github.com/fecgov/fec-cms/issues/2382

**Comment by patphongs** [comment]
There were no dealbreakers in the testing and we can proceed with deployment of the Candidate filings tab
