### ISSUE TITLE
404 on past candidates

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2343]
**What's happening:** 
Past candidates who ran for a particular office with no financial activity in the current year 2018 are getting 404 errors. Below are all examples of these types of candidates:

**Examples:**

- Barack Obama Senate candidate: https://fec-dev-proxy.app.cloud.gov/data/candidate/S4IL00180
- John S. Mccain Presidential candidate: https://fec-dev-proxy.app.cloud.gov/data/candidate/P80002801/
- George Bush Presidential candidate
- Martin Frost House candidate: https://fec-dev-proxy.app.cloud.gov/data/candidate/H6TX24057/

**Possible related PR:**
Refactor candidate view, fix 404's for future candidates
https://github.com/fecgov/fec-cms/pull/2320

**Comment by lbeaufort** [comment]
@patphongs I confirmed these candidate pages now load properly in the staging environment as well.
