### ISSUE TITLE
Test candidate profile pages

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2344]
After the refactor of the candidate profile pages to fix 404's for future cycle candidates without committees, we need to test to make sure candidate profile pages are all functioning. Please test in our staging environment: https://fec-stage-proxy.app.cloud.gov/data/candidates

1 known issue with 404 on past candidates with no financial activity in 2018 has already been logged: https://github.com/fecgov/fec-cms/issues/2343

**Completion criteria:**
- [x] Test future and past House candidates
- [x] Test future and past Senate candidates
- [x] Test future and past Presidential candidates
- [x] Ensure that future cycles show up for candidates who are running in future election cycles

**Comment by llienfec** [comment]
@patphongs I think this is a problem with terminated committees. After we got off our call, I tested 3 more and all had 404s.  I'll test other committees, but for now, that's where I'd focus my time.

Here's a link to my API pull of terminated committees.  Each has a candidate ID number so you can test in staging:
https://api.open.fec.gov/v1/committees/?sort=name&api_key=DEMO_KEY&page=1&committee_type=H&per_page=20&filing_frequency=T

**Comment by patphongs** [comment]
2017-2018 data is displayed for Obama's presidential candidate profile even though the election year is 2012: https://fec-stage-proxy.app.cloud.gov/data/candidate/P80003338/

**Comment by llienfec** [comment]
@patphongs Do you still need more information or is this enough research?

**Comment by llienfec** [comment]
Testing is related to #2343

**Comment by patphongs** [comment]
Thanks for researching @llienfec, we will use some of these testing results and ideas when we create a new testing after the code is fixed up more
