### ISSUE TITLE
Compile list and catch up on content redirects for www 

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2350]
**What we're after** 
Need to make sure that users are able to get to the most recent version of a file, without any 404 errors.

The content team has done a lot of redirects from transition, but in a conversation with @patphongs, I realized that we hadn't been doing them from www. This ticket is to catch up on those. 

As a team, we've decided it's best to tackle these catch-up redirects first, and then going forward, we'll do the redirects for www and for transition simultaneously. Once we've caught up on these, we'll go forward with the other forthcoming redirect issues (#2402, #2225, #2360 )

**To do**
 - [x] Go through past redirects done by content team and identify which ones  also need redirects from www.  
- [ ]  Put in the www redirects we need to catch up on.
- [ ] Add these files to the forthcoming issues above as needed to plan for taking these files off transition after the redirect is in place.

(Edited to add: As I check these past redirects to make the [list of catch-up redirects for this issue](https://docs.google.com/spreadsheets/d/1E8wnT98QYqWE3x3UK28mlgrxyDd3cghYFOuD2aKmxSQ/edit?usp=sharing)- I'll update the background list to note what is done and what needs doing.)

**Background** 
Past redirects of H4CC content were captured in these github issues:
https://github.com/fecgov/fec-proxy/issues/93 - www redirects are in place; no more action needed.
https://github.com/fecgov/fec-proxy/issues/88 - www redirect is not in place, but related issue #2188 - it appears they've been deemed unnecessary.
https://github.com/fecgov/fec-proxy/pull/85 - www redirect is not in place for two old tips.shtml pages. Have added them to our list.
https://github.com/fecgov/fec-proxy/pull/84 www redirect is not in place for three of the files (all pages maintained by info in info/ or law/ directories) but was in place for all of the other files. Have added the three files to our list.
(See https://github.com/fecgov/fec-cms/issues/2025 for pull 84 and pull 85)
https://github.com/fecgov/fec-proxy/pull/83 - www redirect is in place. No action necessary.
https://github.com/fecgov/fec-proxy/issues/81 - www redirect is in place for three files but not for the old toolkit page. Have added that to list.
https://github.com/fecgov/fec-proxy/issues/71 - covered by several issues above. No action necessary.
https://github.com/fecgov/fec-proxy/issues/68 - www redirect is in place. No action necessary.
https://github.com/fecgov/fec-proxy/pull/65 (for recent developments redirect) - www redirect is in place. No action necessary.
https://github.com/fecgov/fec-proxy/pull/63 -covered by several issues above. No action necessary.
https://github.com/fecgov/fec-proxy/issues/62 (https://github.com/fecgov/fec-cms/issues/1215)  -covered by several issues above. No action necessary.
https://github.com/fecgov/fec-proxy/pull/58  - www redirect is in place. No action necessary.
https://github.com/fecgov/fec-proxy/pull/55   - www redirects are in place. No action necessary.
https://github.com/fecgov/fec-proxy/pull/50  - www redirects are in place. No action necessary.

**Comment by patphongs** [comment]
@dorothyyeager You can create www.fec.gov redirects using Wagtail. Below is an example of a redirect I just put in for the guides page:

![screen shot 2018-10-30 at 2 35 01 pm](https://user-images.githubusercontent.com/12799132/47741629-1bb35780-dc51-11e8-98fc-5d8760bb2acd.png)

**Comment by dorothyyeager** [comment]
Have gone through all the PRs listed above and figured out that most of the items do have www redirects in place. There were 7 files that don't. Next step is to write those redirects.

**Comment by dorothyyeager** [comment]
Ah I just found a few more while looking at our redirect round 2 list. I'll add them to my list above before I start writing them.
