### ISSUE TITLE
Implement updated election search page design

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2353]
History: https://github.com/fecgov/fec-cms/issues/2286

**What we're after:** It's been observed that users have had difficulty finding search results on the election search page. Often the results populate below the fold and users cannot tell that the search has worked.

To address this issue, we have redesigned the election search page, to make more room for the results to populate on the page. Allowing users to better see and validate when a search has completed.

**Design:**
![screen shot 2018-09-11 at 2 42 55 pm](https://user-images.githubusercontent.com/31663028/45383753-1a16cd00-b5da-11e8-9fa8-8da9d1b2dbf2.png)

**Completion criteria:**
- [x] Modify the display of search filters into gray row. This is similar to the way filters are display on the [Latest Updates](https://www.fec.gov/updates/) page.
- [x] Remove the default Results language "This page shows...show up here."
- [x] Modify the search button for ZIP code. Buttons should become one, search box and button combined. Similar to the way it's displayed on datatable search filters. 
- [x] Change page title from "Search" to "Find elections"
- [ ] Show upcoming presidential election profile page by default. For example, we want to show 2020 for for this current time period.
- [ ] Add to release notes

**Comment by patphongs** [comment]
> * Show upcoming presidential election profile page by default. For example, we want to show 2020 for for this current time period.

@JonellaCulmer For this completion criterion, do you want the 2020 election year to be selected on the election search page by default? Or do you want to leave it at the current year 2018 by default? And when you mean show presidential by default, does that mean whatever year is selected, no matter if it's a presidential election year, show the presidential profile page link?

**Comment by johnnyporkchops** [comment]
Correction: The last comment is incorrect, clicking either of the search boxes does not change the presidential results. The current page has  no way to search only presidential elections either by page interaction or URL/query

**Comment by johnnyporkchops** [comment]
I take back the last comment, @pat was referring to the new version of this, not the existing. So yes, the search-submit buttons will perform a search for upcoming pres elections
