### ISSUE TITLE
Design: Add candidate search filters to IE data table

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2354]
**What we're after:** Users, specifically reporters, have expressed difficulty using the [independent expenditure search](https://www.fec.gov/data/independent-expenditures/?data_type=processed&is_notice=true). They are unable to complete a typical search they would do to locate funds spent in relation to a specific candidate. Instead of using the new search, they revert to the classic site to find what they need. 

To better provide them with easy access to IEs, and not force them to seek data elsewhere, we should consider integrating new high-value search filters on the IE search. 

**Filters to add:**
candidate state
candidate district
candidate office sought
candidate party affiliation

Filter implementation happening here: https://github.com/fecgov/fec-cms/issues/2127

**Completion criteria:**
- [x] Mock-up filters panel for IEs table to include the aforementioned filters
- [x] Check-in with @lbeaufort on the technical bits
- [ ] Update #2127 with designs
- [ ] Create testing ticket

**Comment by lbeaufort** [comment]
@JonellaCulmer the "candidates" data table has the filters in this order, so I'm going off that for now:

https://www.fec.gov/data/candidates/?has_raised_funds=true

<img width="295" alt="screen shot 2018-09-13 at 8 47 05 am" src="https://user-images.githubusercontent.com/31420082/45489244-c919ec80-b731-11e8-9f0a-518a3fa6cfdc.png">

**Comment by JonellaCulmer** [comment]
Please see the updated candidate filters for the IE search.

<img width="256" alt="screen shot 2018-09-14 at 3 27 14 pm" src="https://user-images.githubusercontent.com/31663028/45571010-d8cd2a00-b832-11e8-9f59-dad1c7af5504.png">

**Comment by JonellaCulmer** [comment]
Closing in favor of #2127
