### ISSUE TITLE
Modify Inspector General link in footer

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2360]
**What we're after:** We have moved the information regarding the Inspector general, including reports, from transition to wagtail. Now that the page has changed, we need to update the link in the footer to reflect the new page. 

This page has yet to be published, but will soon be. Once that happens we can proceed with this edit. We should also consider a redirect from the legacy page to the new version, then remove the legacy page from transition. 

**Completion criteria:**
- [x] First, create redirect from legacy page, to the new page. PR: https://github.com/fecgov/fec-proxy/pull/95
- [x] Add the OIG page to content team's list of redirects (@dorothyyeager)
- [x] Update footer link for Inspector General to new wagtail page on fec-cms (Will update with link once published). PR: https://github.com/fecgov/fec-cms/pull/2483

Future work for future sprint:
- [ ] Remove legacy IG page from transition
- [ ] Create followup issue to add the footer back into e-regs with updated IG link
- [ ] Update footer links on transition. This is more work intensive, however, the redirect is a good temporary solution until we can update all these footer links

**Comment by dorothyyeager** [comment]
Still pending so moving to next sprint (7.3).

**Comment by patphongs** [comment]
Redirect PR and CMS footer change PR have been submitted. Those are all pending review and merge.

**Comment by JonellaCulmer** [comment]
Closing this issue in favor of followup issue: https://github.com/fecgov/fec-cms/issues/2497
