### ISSUE TITLE
Show Committee ID on Committees CFD page

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2361]
@llienfec commented on [Tue Sep 04 2018](https://github.com/fecgov/openFEC/issues/3354)

User was trying to tell the difference between committees with similar names.  Can we make `Committee ID` visible on the search results screen for the `Committees` search in Campaign Finance Data?

Example: https://www.fec.gov/data/committees/?treasurer_name=SYLVAN+MACKANESS

![image](https://user-images.githubusercontent.com/22914750/45038034-64bea500-b02e-11e8-8bde-8e9eb21e4b64.png)

- [x] Confirm with @JonellaCulmer that this is an ok change to make
- [x] Add the column
- [x] Test mobile view and breakpoints to make sure page renders properly

---

@lbeaufort commented on [Thu Sep 13 2018](https://github.com/fecgov/openFEC/issues/3354#issuecomment-421116893)

@llienfec I agree this would be a great change! I confirmed it's [available in the API](https://api.open.fec.gov/v1/committees/?api_key=5yyI90SU3Xb73TVlv4wrEhQxYcCwMWCywQiGdYbJ&sort_hide_null=true&treasurer_name=SYLVAN+MACKANESS&sort=-first_file_date&per_page=30&page=1) so I'm moving this to the fec-cms repo.

**Comment by lbeaufort** [comment]
@pkfec that is awesome! Here are the chrome developer docs that go over testing these views. Breakpoints mean as you resize the window, do the elements rearrange so you can still see them. Please let me know if you’d rather do a call! https://developers.google.com/web/tools/chrome-devtools/device-mode/

**Comment by JonellaCulmer** [comment]
@pkfec I think this looks good. I don't normally advocate for changes based on a single request from any one person, but think this is high-level enough information to include. 

The one thing I would change is to remove the ability to sort by the committee ID column. I can't see how that would be helpful. I could be wrong, but at this stage, I think we can remove.

**Comment by pkfec** [comment]
@JonellaCulmer Every other column on Committees datapage is sortable except this new column Committee ID. To be consistent, we can make this new column sortable too? 

FYI :sort is disabled on Committee ID column.

**Comment by JonellaCulmer** [comment]
@pkfec Thanks for that extra information. But I don't think it's necessary at this point.
