### ISSUE TITLE
Add FEC API to data.gov

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2362]
Similar to when we [added our `code.json` file](https://github.com/fecgov/fec-cms/pull/2260) for code.gov, we should add a `data.json` file so FEC's data can appear on data.gov. 

@vrajmohan took a first pass at the json file:
```
{
    "title": "FEC API",
    "description": "A description",
    "keyword": ["campaign", "finance"],
    "publisher": {},
    "contactPoint": "",
    "identifier": [],
    "accessLevel": "public",
    "bureauCode": "ss",
    "programCode": "sddsasa",
    "distribution": [
        {
            "accessURL": "https://api.open.fec.gov",
            "description": "A fully queryable REST API with JSON output",
            "describedBy": "https://api.open.fec.gov/swagger/",
            "describedByType": "application/swagger+json",
            "format": "API",
            "title": "OpenFEC REST API"
        }
    ]
}
```

- [x] Figure out some of the remaining fields (bureauCode, programCode, etc) here - https://project-open-data.cio.gov/v1.1/schema/ 
- [x] Add data.json to fec-cms (like this PR https://github.com/fecgov/fec-cms/pull/2260)
- [x] Let data.gov know to harvest our data.json file (emailed 11/21 with a 12/5 "harvest" date)

**Comment by lbeaufort** [comment]
PR has been merged, data.gov folks have been notified.

**Comment by PaulClark2** [comment]
Thanks!
