### ISSUE TITLE
Fix server error for 2 reporting examples in Wagtail

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2363]
Getting a server error when trying to edit the following Wagtail pages:

How to report as a joint fundraising representative
- https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/joint-fundraising-representative/
- ID: 9869

How to report 48-Hour notices
- https://www.fec.gov/help-candidates-and-committees/filing-reports/reporting-48-hour-notices/
- ID: 9387

These are the highest priority to fix.  We have other reporting examples with this problem (but not all reporting examples have this problem).  I'll go through and make a more comprehensive list later.

**Comment by patphongs** [comment]
These pages have been restored in production. You can now edit them again.
