### ISSUE TITLE
Remove display of count estimate for all data tables

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2366]
@AmyKort commented on [Fri Sep 14 2018](https://github.com/fecgov/openFEC/issues/3381)

What we're after: Remove display of count estimate for all data tables in the campaign finance data section.

Why we're after it: Users searching and downloading data need to have confidence that the have found all of the results responsive to their search. Right now, our estimated count is approximately double the actual number of results (great information here: https://github.com/fecgov/openFEC/issues/3104 ) We need to remove the estimate as a first step, while we correct the problem with the estimates.

**Completion Criteria**
- [x] Identify all the data tables where the counts appear
- [x] Remove the counts
- [x] Make sure styling still looks ok
- [x] Test the data tables to make sure they work properly (pagination, export)
- [ ] Create a ticket to re-implement the counts once the API issue is addressed

This is connected to these API issues:
https://github.com/fecgov/openFEC/issues/3104
https://github.com/fecgov/openFEC/pull/3264#issuecomment-406752980

**Comment by patphongs** [comment]
Hotfix has been deployed, closing
