### ISSUE TITLE
Check committee type - Party Nonqualified - financial summaries

### ISSUE THREAD

**Issue by apburnes** [fecgov/fec-cms#2368]
Verify committee reports/financial summaries display correctly for type `Party Nonqualified` once the API is fixed referenced in issue https://github.com/fecgov/openFEC/issues/3382

Testable committee - https://www.fec.gov/data/committee/C00629584/?cycle=2016#cash-summary

**Comment by lbeaufort** [comment]
This was fixed and tested a while back: https://www.fec.gov/data/committee/C00629584/?cycle=2018&tab=summary
