### ISSUE TITLE
Error when publishing certain pages made with collection_page template

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#2372]
Some collecton_pages are getting an error when trying to publish or preview in Wagtail. In production, it gets a 404, locally it gets this error:

Similar issue #2389
```
raise EntityException('Expected {0}, got {1}'.format(expected_entity, command.data))
draftjs_exporter.entity_state.EntityException: Expected 2, got 1

```
This is different than the other errors we have with draftail Rich Text Editor (RTE) that will not allow the page to be edited. This allows the page to open in the editor, but does not allow publishing/preview. However it still may have to do with invalid html in the RTE.

This example and several other collection_pages in the H4CC section of Wagtail get this error:
https://fec-dev-proxy.app.cloud.gov/admin/pages/8132/edit/

Preview error screenshot:
<img width="527" alt="screen shot 2018-10-25 at 2 20 59 pm" src="https://user-images.githubusercontent.com/31663028/47521523-453f3e00-d861-11e8-8f86-063cd591c660.png">

Publish error screenshot:
<img width="682" alt="screen shot 2018-10-25 at 2 20 08 pm" src="https://user-images.githubusercontent.com/31663028/47521495-28a30600-d861-11e8-89df-b125a5b69acb.png">

This page has an issue with the reporting example page block. Rather than trying to figure out where it's breaking within the draftJS exporter, we can actually fix this faster by:

- [ ] Go into the Wagtail page that won't publish 
- [ ] Open the live page in a new tab so that you can reference it
- [ ] Delete the reporting example blocks
- [ ] Repopulate the content again, use the opened live page for reference
- [ ] Re-link all the reporting example links with internal wagtail links

**Comment by johnnyporkchops** [comment]
This issue **does not** effect creating new pages using the collection_page template.

**Comment by patphongs** [comment]
@dorothyyeager and I spoke about this today and she knows how to fix this in Wagtail using the above defined method. cc @llienfec
