### ISSUE TITLE
Update organization chart and staff page for the Deputy Staff Director, management and administration

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2377]
We need to update the FEC office listings for the new Acting Deputy Staff Director, Management and Administration, as well as the organization chart.

**To do**
- [x] Update https://transition.fec.gov/about/offices/DSDMA/DSDMA.shtml with Kate Higginbothom's photo and bio (Dorothy)
- [x] Update image used (https://transition.fec.gov/about/offices/fec_org_chart.jpg) for organization chart at https://transition.fec.gov/about/offices/offices.shtml to replace Ed Holder with Kate Higginbothom (2nd column, first box under Staff Director's box) (Front-end work)

**Comment by dorothyyeager** [comment]
I've done the content team part and the office's transition page has been updated. Will need @johnnyporkchops or @patphongs to edit the image that's used for the organization chart and edit any related hard-coding for that.

**Comment by dorothyyeager** [comment]
Taking myself off this issue as I've completed my tasks and don't have the ability to edit the org chart photo and related coding. I'm available to answer any questions about what's needed in terms of the edits though.

**Comment by patphongs** [comment]
Graphic has been updated and will be automatically deployed at 1:30pm today
