### ISSUE TITLE
Test IE filters (goes live 9/25)

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2379]
Test https://github.com/fecgov/fec-cms/issues/2127

Filters to test: 
- [x] "Office sought": candidate_state
- [x] "Political party" : candidate_party
- [x] "State or territory": candidate_office_state
- [x] "District": candidate_office_district
- [x]  "Support/Oppose"

https://www.fec.gov/data/independent-expenditures/?data_type=processed&is_notice=true

**Comment by llienfec** [comment]
## Testing results:
IE filters look like they're working well for the small data set I tested.  Good job!

## Data used to test:
:lock: https://docs.google.com/spreadsheets/d/1XPeayyFuqHZDtH11ci9xGV7OludZaPQlYVmWM1IEv5Q/edit?usp=sharing :lock:

## How the filters were tested:
Matched spreadsheet vs website,
-  Checked all (52 results)
- "Office sought": candidate_state - P (1), H (30), and S (21).  Combo H & P (31)
- "Political party" : candidate_party - Dem (9), Rep (41) - there are 2 blanks
- "State or territory": candidate_office_state - tested TX (4), CA (2), AL (0)
`finding: IEs for pres cmttes have US in the state, can't filter to find.  Not a big deal, can use office sought instead`
-  "District": candidate_office_district - 01 (2), 00 (20), 6+9 (6)
- "Support/Oppose" - S (41), O (11)
- Combos tested:  PA 04 (2), Oppose Reps (6), Senate Dems (5)

**Comment by llienfec** [comment]
With testing finished and filters deployed, I'm closing the issue.
