### ISSUE TITLE
Filings tab bug

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2382]
Strange case where a Form 2 that is a letter should come up as the most recent F2 under "About this candidate," but doesn't.  The weird part is that it's first in the statement of candidacy list under "Filings."

> H2CA42023 – most recent F2 on file is a letter from 11/28/2006.  It shows up in the doc feed but not on the first page.

- [x] Find cause 
- [ ] Fix cause

**Comment by AmyKort** [comment]
@johnnyporkchops  Are you working on this ticket? I can assign it to you if are.

**Comment by johnnyporkchops** [comment]
The document in question (on the filings tab SOC table)  shows up in the 2006 dropdown on `About this Candidate tab`. 
The `SOC table on filings tab` is sorted on receipt date while the latest SOC that shows up on `about this candidate tab` is based on `election year` parameter associated with the document.
In this case, the candidate has one SOC for 2008 with an `election_year` of 2008 and another with an `election_year` of 2006.(see link below)

Is one or the other is wrong? ( cc: @llienfec )

**Date anomaly on API**: https://fec-dev-api.app.cloud.gov/v1/filings/api_key=None&sort_hide_null=true&data_type=processed&candidate_id=H2CA42023&cycle=2006&form_type=F2&sort=-receipt_date&per_page=30&page=1

Based on the [letter(PDF)](http://docquery.fec.gov/pdf/706/26039294706/26039294706.pdf), it seems like that by mistakenly filing an SOC for 2008, this candidate now has 2008 among his `election_years` even though he was never actually a candidate in 2008. Or that the SOC was never withdrawn as requested.
<img width="887" alt="screen shot 2018-10-10 at 11 53 29 pm" src="https://user-images.githubusercontent.com/5572856/46779931-0b5e2b80-cce8-11e8-9280-baba8f93d276.png">

**Comment by llienfec** [comment]
Hi @johnnyporkchops Thanks for flagging this for me.  This should be the most recent filing.  We wouldn't take down the 2008 F2 that was filed in error.  Technically, this is a document that deals with the 2008 F2, negating it. It seems like this should be the most recent Form 2.

**Comment by llienfec** [comment]
This a complicated edge case.  We think that the letter above, classified as a 2006 doc should be a 2008 doc and show up as the most recently filed F2 for the candidate on the candidate profile page.  However, since this is rare, we're going to close this ticket and pick it up 1) when we have more time later or 2) when we have other cases with similar circumstances.  For now we're not tackling because of resource constraints.
