### ISSUE TITLE
Implement the front-end data table and canonical pages for ADRs

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2385]
**What we're after:** Using the [designs](https://github.com/fecgov/fec-cms/issues/2338) created and [data moved to the API](https://github.com/fecgov/openFEC/issues/3359) in 7.2, we want to begin to implement the front-end interface and canonical pages for the ADR pages.  

We're basing this first iteration on the MUR pages currently implemented in production. See example linked above.

**Completion criteria:**
- [ ] Make the ADR data table page.
- [ ] Make the ADR canonical page.
- [ ] Send to ADR for review.
- [ ] Add feature flag for ADR data table and canonical page.

**Comment by patphongs** [comment]
Made smaller issues with separate ADR datatable and canonical page implementation tickets: 

https://github.com/fecgov/fec-cms/issues/2436
https://github.com/fecgov/fec-cms/issues/2437
