### ISSUE TITLE
Inventory Wagtail pages that can't be updated

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2389]
Some (not all) reporting example pages are no longer editable after the Wagtail upgrade.  Need to fix the pages so that we can edit them.

### To do:
- [x] Check all existing reporting example pages to see if there are server errors. (Check: Wagtail > edit)
- Candidate
- SSF
- Nonconnected
- [x] Look for reasons the pages are different from the reporting example pages that worked
- [x] Create an implementation ticket to make the pages editable

### Info to include:
- page URL
- unique page

### Current error message: ![image](https://user-images.githubusercontent.com/22914750/45707944-2d7fe600-bb4e-11e8-901f-71e78cea5228.png)

Possibly related issue: https://github.com/fecgov/fec-cms/issues/2372

**Comment by llienfec** [comment]
Over 40 Reporting Example template pages are affected by server error problems when trying to edit the page.  
:lock: https://docs.google.com/spreadsheets/d/125G8IWi22DvHqWiwRMgO2W8ivf1t-L_mq3hm4jZfvco/edit?usp=sharing :lock:

In addition, it looks like `related media` at the end of the page is required and it shouldn't be:
![image](https://user-images.githubusercontent.com/22914750/45712767-27443680-bb5b-11e8-97b7-3ac46de1f4f0.png)

Next steps: meeting with @johnnyporkchops on Friday to go over one way to restore the pages.  After I try it out, I'll figure out what the implementation ticket should be (either Content can do it or we'll need Front-End help).

**Comment by johnnyporkchops** [comment]
Per conversation with @llienfec , the issue above regarding making `related_media` optional will be addressed short-term in issue #2398

**Comment by llienfec** [comment]
Talked to @johnnyporkchops about how to get these pages fixed.  We have about 40 with issues.  We're going to try removing the required flag for `related_media` first.  Hopefully this will reduce the number of pages that aren't showing up.

John also showed me how to revert to a prior version of a Wagtail page. However, that solution doesn't work for the reporting example pages because all of the prior versions have the server error.

It looks like we may have to copy and paste all of the pages.  We're planning to do this over a longer period of time because of the number of pages.

**Comment by AmyKort** [comment]
Do we want to close this ticket and open a new one that addresses a long-term roll out of this work?

**Comment by llienfec** [comment]
@AmyKort  I'm planning to write the 4 implementation tickets after the sync with Dorothy today.  I talked to @johnnyporkchops and we're spreading the work out over 4 sprints.  I'll close this issue after I write the others.  Thanks!

**Comment by llienfec** [comment]
@johnnyporkchops - There are 4 implementation tickets to make these pages editable over time ^^.   I really appreciate your offer to update any of the ones that become urgent as well.

Closing the issue.
