### ISSUE TITLE
Craft language for data tables with missing descriptions

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2396]
**User story:** 
As a data user, I want to know more about what each data set contains, so that I can go to the right place more efficiently.

**What we're after:** For consistency and so users can better understand the data they'll find in individual datatables, we need to craft language for the following data tables.

- [All filings](https://www.fec.gov/data/advanced/?tab=filings)
- [Presidential committee reports](https://www.fec.gov/data/advanced/?tab=filings)
- [House and Senate committee reports](https://www.fec.gov/data/advanced/?tab=filings)
- [PAC and party committee reports](https://www.fec.gov/data/advanced/?tab=filings)
- [Loans](https://www.fec.gov/data/advanced/?tab=loans-debts)
- [Party coordinated expenditures](https://www.fec.gov/data/advanced/?tab=spending)

**Completion criteria:**
- [x] Survey existing data descriptions
- [x] Draft similar language for the list of above reports where needed
- [x] Content team and @PaulClark2 review.
- [x] Draft implementation ticket.

**Comment by llienfec** [comment]
**Draft:**
- [ ] All filings
- [ ] Presidential committee reports
- [ ] House and Senate committee reports
- [ ] PAC and party committee reports
- [ ] Loans
- [ ] Party coordinated expenditures

**Additional:**
- [ ] Add receipts description under Receipts title
- [ ] Adjust "all receipts" description

All descriptions are drafted and have been sent to Content + Paul for review.
:lock: https://docs.google.com/document/d/1N_Lsl4cwFEgxiKnFWxe52k5uvf9840sez8_0zjAeCfI/edit?usp=sharing :lock:

**Comment by llienfec** [comment]
Implementation ticket for front end is at #2426.  Closing out the research and drafting.  Happy to answer any questions from the front end team!
