### ISSUE TITLE
Make related media optional in reporting_example template

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#2398]
After meeting with @llienfec , it was decided that making the `related_media field ` optional in `reporting_example template` would be a helpful short-term fix that would allow her to continue work on some pages until issue #2389 can be fully addressed.

So I will make a PR to the upcoming 09/25 release branch for this.

This is the [comment](https://github.com/fecgov/fec-cms/issues/2389#issuecomment-422533145) on issue **2389** for this fix

**Comment by patphongs** [comment]
Fixed in this PR: https://github.com/fecgov/fec-cms/pull/2399
