### ISSUE TITLE
Missing links to transaction level data pre-2006: Candidate and committee profile pages

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2401]
@PaulClark2 commented on [Wed Sep 19 2018](https://github.com/fecgov/openFEC/issues/3391)

This example is of a Senate candidate and committee. 

**What we are after**: Provide users access to transaction level data. 
**Why we are after it**: As part of our disclosure mission, we should provide access to campaign finance data to the public.
**Current state**: We have coded data from the committee but the line item links on the financial summary are not active. Users cannot click through to explore the schedule data.

**Examples**: 
https://www.fec.gov/data/candidate/S6MT00162/?cycle=2006&election_full=true
https://www.fec.gov/data/candidate/S6MT00162/?cycle=2006&election_full=true

**Screen shots**: 
![image](https://user-images.githubusercontent.com/11817734/45774583-5621e180-bc1b-11e8-8687-f8515ff62aed.png)

![image](https://user-images.githubusercontent.com/11817734/45774608-6934b180-bc1b-11e8-946e-555081982617.png)

**Completion criteria**:
- [x] Investigate why line item links are not active
- [ ] Make line item links active

---

@lbeaufort commented on [Wed Sep 19 2018](https://github.com/fecgov/openFEC/issues/3391#issuecomment-422933837)

@PaulClark2 it looks like this has been hard-coded to only link after 2006 since the beginning of the repo - https://github.com/fecgov/fec-cms/commit/fbd7e7f37254b0766a6803a6d5867eb3d81a3b12#diff-4817fd82110ba07bc1ccf075000feccdR27

Looks like that was one of the original requirements: https://github.com/18F/openFEC-web-app/issues/2125

<img width="514" alt="screen shot 2018-09-19 at 3 46 34 pm" src="https://user-images.githubusercontent.com/31420082/45777248-460e0000-bc23-11e8-9d82-a665bdc2baa6.png">

---

@PaulClark2 commented on [Wed Sep 19 2018](https://github.com/fecgov/openFEC/issues/3391#issuecomment-422937854)

@lbeaufort thanks for looking into this. 

Looks like this isn’t a bug but works as designed. @AmyKort @jwchumley it seems to me if we have the coded data we should let folks click through to it. We will need to explain to folks that the scope of the data is less than that of more recent filings.

I’ll change the label from `bug` to needs `prioritization`.

**Comment by rjayasekera** [comment]
During random testing found out some of links which as dollar values but after clicking on them no details will appear.  Try the following link as an example:

http://127.0.0.1:8000/data/committee/C00370007/?tab=summary&cycle=2002

![image](https://user-images.githubusercontent.com/20324717/49181396-4282ad80-f325-11e8-95b5-add18703e47a.png)

After clicking on "temized individual contributions" no detail data shows up cc @lbeaufort 

![image](https://user-images.githubusercontent.com/20324717/49181483-765dd300-f325-11e8-865d-04c465c423b3.png)
