### ISSUE TITLE
Quick answers - map content to new site for 3 sections

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2402]
We're looking at what to do with "quick answers" section on old site & transition.  Before redirecting these three sections, we need to make sure that all of the information in the sections are on the new site somewhere. 

 **Quick answers sections to map to new site:**
- General
- Disclosure
- Compliance

**To do:**
- [x] make a doc mapping old content to the new content
- [x] come up with one or two suggested strategies for redirects
- [x] figure out who we need to talk to about redirecting the content
- [x] work with those offices
- [x] additional item: create a path from "understanding ways to support federal candidates" to "introduction to campaign finance" page
- [x] make an implementation ticket

**Comment by llienfec** [comment]
I set up the chart and got started mapping content today.  Looking to pick back up tomorrow.

:lock: https://docs.google.com/spreadsheets/d/1FzteENgtmXJUcPgVZDwdtG6a-xuouVXTjl_jSrY863Q/edit?usp=sharing :lock:

**Comment by llienfec** [comment]
Finished the [quick answers](https://transition.fec.gov/ans/answers.shtml) inventory.  If you'd like different links, feel free to update!

@dorothyyeager I have a couple of questions about what we should do next.  I'm not 100% sure what the redirect strategy should be.

Structure of quick answers section:
- Main page has `topic links` and `quick answer anchor links`
- There's a child page for each `topic` has `quick answer anchor links` and `quick answer content`

Are we able to redirect anchor links?  Or can we only redirect the main link?

**Comment by dorothyyeager** [comment]
I think we need to check with @patphongs on the redirecting anchor links question.

I looked at the code for our current redirects and we have one written (seems to be done properly) for https://transition.fec.gov/ans/answers_compliance.shtml#embezzlement1 but it doesn't seem to work. (It's supposed to redirect to https://www.fec.gov/help-candidates-and-committees/keeping-records/misappropriated-funds/.)

**Comment by llienfec** [comment]
**Redirect plan:**

- General - https://www.fec.gov/introduction-campaign-finance/understanding-ways-support-federal-candidates/
- Disclosure - https://www.fec.gov/introduction-campaign-finance/understanding-ways-support-federal-candidates/
- Compliance - https://www.fec.gov/legal-resources/enforcement/

**Additional work:**
- [ ] create a path from "understanding ways to support federal candidates" to "introduction to campaign finance" page

**Comment by llienfec** [comment]
Planning and research work is finished.  Redirect implementation issue is at #2425. Closing issue.
