### ISSUE TITLE
Remove closed meeting announcements from homepage

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2416]
What are we after: Change homepage calendar feed to show only open meetings.

Why are we after it: Users can watch or attend open meetings, but executive sessions are closed to the public. Users tell us that they'd rather have more notice of open meetings, but because executive sessions are scheduled for earlier in the day, the generally appear for a longer period on the calendar. To fix this, we're going to make only open meeting appear on the front page. 

![image](https://user-images.githubusercontent.com/13237823/46813518-d8965080-cd44-11e8-91ef-da73282d81db.png)

*completion criteria*
 - [x] remove executive session meetings (but not hearings or open meetings) from front page feed
- [x] change "next commission meeting" to "next open commission meeting" or something similar (consult with content team)
- [ ] Consider solutions for hearings

MORE DISCUSSION BELOW

@fec-issues-bot commented on [Fri Sep 14 2018](https://github.com/fecgov/FEC/issues/7735)

## What were you trying to do and how can we improve it?
 Just flagging again that, for most of the month, the "Next commission meeting:" feature on the landing page is of use only to FEC staff. Our public and non-public meetings usually come in pairs every two weeks with the non-public meetings on Tuesday and the public meetings on Thursday. This creates a problem when the only factor taken into account for the landing page entry is calendar and not context. I know that there are more pressing issues but my goal is to give the web team some perspective on this.

The average number of days that a non-public meeting will be advertised on the landing page is 12.  By contrast, the average number of days a public meeting is advertised is only 1. This disparity gets even larger during periods when meetings are less frequent. For example, the next staff-only meeting, September 25, will have been advertised on the landing page for 19 straight days. Compare this to the next public meeting, September 27, which will be advertised on the landing page– again– for just one day.

I'd encourage the web team to consider modifying this field on the landing page such that, except in rare occasions, it grabs only public meetings. 

## Tell us about yourself
 Jim Jones, Info Div 

## Details
* URL: https://www.fec.gov/ 
* User Agent: Amazon CloudFront

---

@AmyKort commented on [Fri Sep 14 2018](https://github.com/fecgov/FEC/issues/7735#issuecomment-421377037)

@JonellaCulmer @llienfec @rhoughfec  @dorothyyeager  This is an important point we're hearing from a number of sources. Let's get together and talk about solutions. Thanks!

---

@rhoughfec commented on [Fri Sep 14 2018](https://github.com/fecgov/FEC/issues/7735#issuecomment-421378909)

I agree. What about if the "next commission meeting" was to be "next public commission meeting" and only show open meetings? It always faults to Exec (maybe alpha order?)

---

@AmyKort commented on [Fri Sep 14 2018](https://github.com/fecgov/FEC/issues/7735#issuecomment-421379498)

I agree. I think we make it "next public meeting" so that only public meetings make the home page, even if all meetings are on the full calendar.

---

@JonellaCulmer commented on [Fri Sep 14 2018](https://github.com/fecgov/FEC/issues/7735#issuecomment-421405482)

I defer to your judgment, but should it say "next open meeting" since that's what they're called, or does "public" clarify it better?

@johnnyporkchops Are we able to filter what's presented there under meetings by just open meetings?

---

@llienfec commented on [Fri Sep 14 2018](https://github.com/fecgov/FEC/issues/7735#issuecomment-421406970)

That's a good point, @JonellaCulmer.  I think maybe we do "next public meeting" as the title and then beside the date, have "open meeting" as the link?  

![image](https://user-images.githubusercontent.com/22914750/45561797-97c71c80-b816-11e8-991c-3e9fdb088dbd.png)

Also, this is where public hearings would show up as well, right?  (so everything from the "Commission meetings" page except executive sessions)

---

@Iosunlock commented on [Sat Sep 29 2018](https://github.com/fecgov/FEC/issues/7735#issuecomment-425613836)

I agree

---

@dorothyyeager commented on [Mon Oct 01 2018](https://github.com/fecgov/FEC/issues/7735#issuecomment-425892273)

I had missed this posting but it's a good suggestion; moving to the CMS repo for action and closing here.

**Comment by dorothyyeager** [comment]
Moved this suggestion from @jjonesfec to this repo. As noted above, it's a good suggestion and this will get us moving on it.

**Comment by Iosunlock** [comment]
issue

**Comment by Iosunlock** [comment]
Unlocked
