### ISSUE TITLE
Prep and conduct user testing for charts and processed/raw toggle filter

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2422]
**What we're after:** To gauge the usefulness and usability of some of our features and filters, we need to conduct user testing. Specifically we plan to test the line and bar charts which have recently been updated to reflect the best data available as well as moving them to a new location. We also need to test the usability of our processed/raw toggle filter after receiving feedback users are not able to get to the most recently filed reports - which is available through the use of the toggle filter. 

We need to test for the following things: 
### Line/bar charts:
**Pages involved in test:** 
- Data landing page
- Advanced data raising page
- Advanced data spending page

**Questions to answer:**
- Are users able to quickly and easily locate the line charts?
- Are users able to determine what information the line charts are trying to provide?
- Is this data useful?
- Do users primarily use the toggle filter or cursor to move through the timeline?
- Are the bar charts useful?
- What are our users expectation when looking at data at this level?

### Processed vs. Raw toggle filter
**Pages involved in test:**
- Election profile pages
- Data tables using raw/processed toggle
- Committee profile pages

**Questions to answer:**
- Where are users looking for recently filed reports?
- Do users have trouble noticing the raw/processed toggle?
- What does the terminology "processed" and "raw" mean to users, if anything?
- Is it a user's expectation that upon clicking 'Sources reports' link on election profile page that they - see ALL filings, including new, or just the newest filings?

**Completion criteria:**
- [x] Finalize script
- [x] Contact users for testing
- [x] Provide press with tweet for additional testers
- [x] Prep: Update relevant testing documents
- [x] Put out a call for volunteer notetakers
- [x] Conduct testing
- [x] Synthesize testing
- [x] Build summary presentation
- [x] Demo in design sync or sprint demo

**Comment by JonellaCulmer** [comment]
**Testing script:** https://docs.google.com/document/d/1RvP2PeYAekBCNMcZ6BFH9-bV1gVgCN1FJ8xdpmZekww/edit#heading=h.bx322sb1kyth

**Research synthesis:** https://docs.google.com/document/d/11KfHmFe_VXLj4yjdiuFkAZr2yVUWqdMEJZ0kHgPPBT4/edit#

**Research synthesis overview presentation:** https://docs.google.com/presentation/d/1DOv2vCRDKziWbwVqLXaStfYKd8mZ5eRv5Ej-Udm6XVY/edit#slide=id.g2549073cbc_1_205

**Comment by AmyKort** [comment]
Is this ready to close?
