### ISSUE TITLE
Create Quick Answers redirects

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2425]
So that users can find the most up-to-date information, we're redirecting [quick answers](https://transition.fec.gov/ans/answers.shtml) to the new site.

Redirects:
- General - https://www.fec.gov/introduction-campaign-finance/understanding-ways-support-federal-candidates/
- Disclosure - https://www.fec.gov/introduction-campaign-finance/understanding-ways-support-federal-candidates/
- Compliance - https://www.fec.gov/legal-resources/enforcement/
- Filing - already redirected
- Candidate - already redirected
- PAC - https://www.fec.gov/help-candidates-and-committees/
- Party - https://www.fec.gov/help-candidates-and-committees/
- Public funding - already redirected

Ideally, party would to go the party guide page.  I think I remember that we can't link to a tabbed page, so I suggested the H4CC landing page since all the guides are right at the top.

- [x] Determine whether we can link to tabbed pages

**Comment by llienfec** [comment]
Updated the `redirect round 2` spreadsheet to show that these are ready to go.

**Comment by dorothyyeager** [comment]
As part of this issue, we'll redirect a few Info Div. pages that were developed as answers for the quick answers pages, and catch up on a few other needed redirects, as follows:

- [ ] Election Day Links https://transition.fec.gov/info/election_day_links.shtml will redirect to https://www.fec.gov/introduction-campaign-finance/election-day-information/
- [ ] Sale or use brochure https://transition.fec.gov/pages/brochures/saleuse.shtml will redirect to https://www.fec.gov/updates/sale-or-use-contributor-information/
- [ ] Citizens Guide brochure  https://transition.fec.gov/law/litigation/citizens_guide_brochure.pdf will redirect to https://www.fec.gov/introduction-campaign-finance/understanding-ways-support-federal-candidates/
- [ ] Debt retirement 2009 https://transition.fec.gov/info/articles/debtretirement09.pdf will redirect to https://www.fec.gov/help-candidates-and-committees/handling-loans-debts-and-advances/
- [ ] Winding down 2009 https://transition.fec.gov/info/articles/windingdown09.pdf will redirect to https://www.fec.gov/help-candidates-and-committees/winding-down-candidate-campaign/
- [ ] Lobbyist bundling FAQ https://transition.fec.gov/info/guidance/hlogabundling.shtml will redirect to https://www.fec.gov/updates/lobbyist-bundling-disclosure-2018/. (Note that we will need to tackle this one again in the future as we need to move to archiving lobbyist bundling thresholds.)

**Comment by dorothyyeager** [comment]
The redirect for quick answers disclosure will point to https://www.fec.gov/introduction-campaign-finance/how-to-research-public-records/ now that the how to research page is live. It is closer to the content on the original page.

**Comment by dorothyyeager** [comment]
PR for transition redirects: https://github.com/fecgov/fec-proxy/pull/97
PR for www redirects: https://github.com/fecgov/fec-proxy/pull/98

**Comment by dorothyyeager** [comment]
www redirects were done in Wagtail with an edit to remove conflicting transition redirects in fecgov/fec-proxy#101.

With the redirects for transition now merged, we're able to close this issue.
