### ISSUE TITLE
Implement data table descriptions

### ISSUE THREAD

**Issue by llienfec** [fecgov/fec-cms#2426]
So that users have more info about our data tables, we need to implement descriptions for that are missing from page titles and links to tables.

- [x] Receipts - add under title:
Receipts are anything of value, like money, services or property.
- [x] All receipts - change to:
Search candidate and committee receipt data by contributor, amount and date.
- [x] All filings - add:
Search for reports, statements, and filings submitted by committees and filers.  Search by committee name, candidate, receipt date, form type and more.
- [x] Presidential committee reports -  add:
Search financial disclosure reports filed by presidential committees on Form 3P. Search by committee name, candidate, amount of financial activity and report name.
- [x] House and Senate committee reports - add:
Search financial disclosure reports filed by House and Senate committees on the Form 3. Search by committee name, candidate, amount of financial activity and report name.
- [x] PAC and party committee reports - add:
Search financial disclosure reports filed by political action committees (PACs) and party committees on Form 3X. Search by committee name, amount of financial activity and report name.
- [x] Loans - add:
Search loans owed by or to committees. Search by committee, loaner’s name, date the loan was incurred, original loan amount and payments made.
- [x] Party coordinated expenditures - add:
Search party coordinated expenditures [glossary link] by specific national or state party committee, candidate and payee.
- [x] Electioneering communications - change to:
Search electioneering communications [link to glossary] by the spender, candidate mentioned, date, or amount spent.

**Comment by johnnyporkchops** [comment]
@llienfec for the first checklist item above, the title is Raising, not Receipts. Is that what you meant?

- [ ] Receipts- add under title:
Receipts are anything of value, like money, services or property.

**Comment by JonellaCulmer** [comment]
@llienfec @dorothyyeager Are we adding "party coordinated expenditures" to the glossary?

**Comment by JonellaCulmer** [comment]
@llienfec @dorothyyeager Nevermind, it's in the glossary as "coordinated party expenditure".

**Comment by dorothyyeager** [comment]
@JonellaCulme @johnnyporkchops Just confirming that the term is indeed "coordinated party expenditure" in the glossary.
