### ISSUE TITLE
Check logs Sprint 7.4 week 2 (10/24)

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2431]
Log review needs to be completed for Sprint 7.3 (week 2) per the Security Event Review Checklist (https://github.com/fecgov/FEC/wiki/Security-Event-Review-Checklist)

**Comment by lbeaufort** [comment]
## Found security issues
FEC-CMS 2 vulnerability issues:
https://github.com/fecgov/fec-cms/issues/2456
https://github.com/fecgov/fec-cms/issues/2457

FEC-EREGS 1 vulnerability issue:
https://github.com/fecgov/fec-cms/issues/2456 (Same vulnerability as what was noted in fec-cms)

OPENFEC 1 vulnerability issue:
https://github.com/fecgov/fec-cms/issues/2456 (Same vulnerability as what was noted in fec-cms)

## Account change
- 1 offboarded user removed from Wagtail
