### ISSUE TITLE
Implement ADR datatable page

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2436]
**What we're after:** Using the design created below and [data moved to the API](https://github.com/fecgov/openFEC/issues/3359) in 7.2, we want to begin to implement the front-end interface and canonical pages for the ADR pages.  

We're basing this first iteration on the MUR pages currently implemented in production. See example linked above.

Updated mockup following conversations during design sync and dev pairing. 
![screen shot 2018-09-18 at 9 08 24 am](https://user-images.githubusercontent.com/31663028/45689913-2f807f80-bb23-11e8-8158-e2ad846d5c20.png)

**Completion criteria:**
- [ ] Make the ADR data table page.
- [ ] Send to ADR for review.
- [x] Add feature flag for ADR data table page.

**Comment by patphongs** [comment]
@JonellaCulmer For the "Election cycle" column, we can't determine the general and primary election cycle attributes that you've included in your mock up. Is it needed? If so, we'll need an API change. https://fec-dev-api.app.cloud.gov/v1/legal/search?hits_returned=20&type=adrs&api_key=DEMO_KEY

**Comment by patphongs** [comment]
@JonellaCulmer Do we have this file icon <img width="29" alt="screen shot 2018-10-11 at 8 13 56 pm" src="https://user-images.githubusercontent.com/12799132/46840693-42891700-cd92-11e8-81ff-13854781a32c.png"> anywhere?

**Comment by lbeaufort** [comment]
@patphongs that’s correct. We’re moving to the more generic ‘case_’... filters.

**Comment by JonellaCulmer** [comment]
@patphongs Here are some answers to your questions. Happy to discuss further during design sync

> 1. For the "Election cycle" column, we can't determine the general and primary election cycle attributes that you've included in your mock up. Is it needed? If so, we'll need an API change. https://fec-dev-api.app.cloud.gov/v1/legal/search?hits_returned=20&type=adrs&api_key=DEMO_KEY

- In some cases the -General or -Primary is included. It won't be in every case, only for those where it has been provided. 

> 2. Looks like complaints can have multiple files, not sure how the complaints are used in this context.

- It doesn't necessarily need to be a complaint file that's used. The keyword match should yield a document that includes those terms. And I think we should limit it to one document. 

> 3. Do we have this file icon anywhere?

- Yes, should be called .i-folder

**Comment by patphongs** [comment]
- `election_cycles` currently does not pull in `election_cycle_type`, so this would require an API change to append election_cycle_type to election_cycles.

**Comment by patphongs** [comment]
As discussed in design sync, I will make the ADRs within this URL path: `/legal-resources/enforcement/adrs-search`. This is consistent with what we have for the audit search and will apply the same URL structure for other enforcement related paths in the future, see https://github.com/fecgov/fec-cms/issues/2441

**Comment by patphongs** [comment]
As discussed with @JonellaCulmer, it is too challenging to put in the filter tag functionality at this point and would likely slow down development if this needed to be implemented in the first iteration. Currently the ADR search is all using input boxes, so it would be easy enough for the user to clear the input box or type something else to do another search.

**Comment by patphongs** [comment]
Outstanding items from design sync:
- [ ] Move datatable counts to below the Alternative dispute resolution heading
- [ ] Add ADR classic info message
- [ ] Add grey dividing lines between table cells
