### ISSUE TITLE
Implement ADR canonical page

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2437]
**What we're after:** Using the design created below and [data moved to the API](https://github.com/fecgov/openFEC/issues/3359) in 7.2, we want to begin to implement the front-end 
 canonical pages for ADR pages. 

We're basing this first iteration on the MUR pages currently implemented in production. See example linked above.

Updated mockup following conversations during design sync and dev pairing. 
![screen shot 2018-09-18 at 10 58 30 am](https://user-images.githubusercontent.com/31663028/45696609-f4d21380-bb31-11e8-9c3a-0d160394b4b6.png)

**Completion criteria:**
- [ ] Make the ADR cannonical page.
- [ ] Send to ADR for review.
    - [ ] Ask about penalties that show as $0 vs penalty that shows as just blank
    - [ ] Ask about whether or not blank in the disposition penalty and citation columns are ok
    - [ ] Ask about whether or not blank is ok for Subject, Complainant, and Election Cycle within the summary section
- [ ] Add feature flag for ADR cannonical page.

**Comment by JonellaCulmer** [comment]
Per your comments, @patphongs, I made some adjustments to the mock-up. Please see below. Happy to discuss further in design sync. 

<img width="453" alt="screen shot 2018-10-19 at 10 41 03 am" src="https://user-images.githubusercontent.com/31663028/47225249-a364b080-d38b-11e8-8c31-005301e3196a.png">

**Comment by patphongs** [comment]
Per our design sync conversation, noting some of the updates here:

- [ ] Subject and Complainant and Election Cycles fields can be empty. For content review purposes, will leave one field as "none" and the other blank
- [ ] Disposition table: Data for penalty and citation columns are not always present. Decided to leave this blank until we hear back from SMEs
- [ ] Added "Disposition" from commission votes to summary section
- [ ] Remove Legal citations section as this was decided that we did not need it since it's noted already under Disposition
