### ISSUE TITLE
Implement AF datatable page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2438]
**What we're after:** Using the design created below and [data moved to the API](https://github.com/fecgov/openFEC/issues/3359) in 7.2, we want to begin to implement the front-end interface and canonical pages for the AF pages.  

We're basing this first iteration on the MUR pages currently implemented in production. See example linked above.

Updated mockup following conversations during design sync and dev pairing. 
![screen shot 2018-09-18 at 9 09 18 am](https://user-images.githubusercontent.com/31663028/45689914-2f807f80-bb23-11e8-890f-67b404918e1a.png)

**Completion criteria:**
- [ ] Make the AF data table page.
- [ ] Send to AF for review.
- [ ] Add feature flag for AF data table page.

**Comment by patphongs** [comment]
Noting this change that was discussed and implemented:

- Updated the respondents filter to committee name. Made it only search committee name fields.
