### ISSUE TITLE
Implement AF canonical page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2439]
**What we're after:** Using the design created below and [data moved to the API](https://github.com/fecgov/openFEC/issues/3359) in 7.2, we want to begin to implement the front-end canonical pages for AF pages. 

We're basing this first iteration on the MUR pages currently implemented in production. 

Updated mockup following conversations during design sync and dev pairing. 
![screen shot 2018-09-18 at 10 58 48 am](https://user-images.githubusercontent.com/31663028/45696627-fbf92180-bb31-11e8-96c3-c70692616447.png)

**Completion criteria:**
- [ ] Make the AF canonical page.
- [ ] Send to AF for review.
- [ ] Add feature flag for AF canonical page.

**Comment by patphongs** [comment]
Noting this change that was discussed and implemented:

- Removed petition decision columns in table. 
- Add disposition field to summary section
- Left nav should have only Summary and Documents sections
- Ignore "Open case document" button and date
- AF canonical page mappings were mapped according to this [spreadsheet](https://docs.google.com/spreadsheets/d/1i8GeWHEeTzt3jdN3RZg3wKA_dSq2J-6CR5JGtq6G2nQ/edit#gid=568533660) :lock:
