### ISSUE TITLE
Change labels for F13, F4 filer financial summary

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2446]
**Form 13**
Form 13 financial summary should have two total lines:
Total Donations Accepted
Total Donations Refunded
(similar to IE-only Form 5 filers)

Paper instructions: https://www.fec.gov/resources/cms-content/documents/fecfrm13.pdf
Test with API branch `feature/fix-missing-f4-and-f13-committees` (see https://github.com/fecgov/openFEC/pull/3432)
Example link: http://127.0.0.1:8000/data/committee/C00629584/?tab=summary

**Form 4**
Form 4 financial summary should have these totals:
Total Receipts
Federal Funds  
Contributions to Defray Convention Expenses
Transfers From Affiliated Committees    
Loans and Loan Repayments Received
Refunds Rebates, Returns of Deposits Relating to Convention Expenditures
Other Refunds, Rebates, Returns of Deposits
Other Income

Total Disbursements 
Convention Expenses
Transfers To Affiliated Committees
Loans and Loan Repayments Made
Other Disbursements

Paper instructions: https://www.fec.gov/resources/cms-content/documents/fecfrm4.pdf
Test with API branch `feature/fix-missing-f4-and-f13-committees` (see https://github.com/fecgov/openFEC/pull/3432)
Test with: http://127.0.0.1:8000/data/committee/C00611335/?tab=summary

- [x] Add test coverage for existing committee page function (see https://github.com/fecgov/fec-cms/pull/2302 and https://github.com/fecgov/fec-cms/pull/2312)
- [X] Add dynamic templates for F13 (Convention) and 
- [ ] And F4 (Inaugural) committees (based on `org_type` and most recent filing here. Some org_type H committees file F3X so we want to leave those summaries alone and only change labels for F4 filers. https://github.com/fecgov/openFEC/issues/3441). See https://github.com/fecgov/fec-cms/blob/develop/fec/data/views.py#L352-L354
N - National Party Committee
S- State Party Committee
I - Inaugural Committee
K - Convention Committee
H - Host Committee
- [ ] Double-check calculations -  Looks like C00333088 is an example of F4 and F3X by the same committee. How do the summaries work? (https://fec-dev-api.app.cloud.gov/v1/committee/C00333088/filings)

**Comment by pkfec** [comment]
/committee/{committee_id}/reports/ has `report_form` column  which has the form type which we are looking for. See if we can use that column and switch the templates to display the labels and the amounts.

**Comment by lbeaufort** [comment]
@pkfec that's helpful, thanks! In order to filter the most reliably, we need information on the committee level, in /committee/{id}/history endpoint ([example](https://fec-dev-api.app.cloud.gov/v1/committee/C90018045/history)) and @jwchumley wants to take this approach: https://github.com/fecgov/openFEC/issues/3441

**Comment by lbeaufort** [comment]
To be resolved: How to label F3X filers vs. F4 filers. Do they ever file both?
One idea is to look at `financials['reports']['report_form'] and if it's F4, show labels differently?

F3X host committee: C00571133

**Comment by lbeaufort** [comment]
Host committees now blocked by https://github.com/fecgov/openFEC/issues/3457 (Missing summary fields for F4 filers). Plan is to move forward with the F13 changes, as they're ready to go. 

Need to increment this migration, then it can be merged: https://github.com/fecgov/openFEC/pull/3432

Front-end work for F13 filers: https://github.com/fecgov/fec-cms/pull/2465

**Comment by lbeaufort** [comment]
Still needs part 2: https://github.com/fecgov/fec-cms/pull/2472
