### ISSUE TITLE
Conduct usability testing on ZZ codes

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2452]
**What we're after:** To gauge the usefulness and usability of some of our features and filters, we need to conduct user testing. In addition to testing new features, this test includes a continuation of testing from the previous sprint - specifically the processed/raw toggle. We need additional testing on this to verify our conclusions.

We need to test for the following things: 

### ZZ codes
**Pages involved in test:**
- All receipts and individual contributions data tables

**Questions to answer:**
- Are users able to conduct a search for places not technically listed as states, such as bases?
- Can users conduct a search for contributors living in foreign countries?

**Completion criteria:**
- [x] Finalize script
- [x] Contact users for testing
- [x] Provide press with tweet for additional testers
- [x] Prep: Update relevant testing documents
- [ ] Put out a call for volunteer notetakers
- [ ] Conduct testing
- [ ] Synthesize testing
- [ ] Build summary presentation
- [ ] Demo in design sync or sprint demo

**Comment by JonellaCulmer** [comment]
We have been unable to get a decent number of testers this sprint to complete this testing. Recommend moving this work to the backlog for future work when we're not as near to reporting deadlines, elections, and possibly holidays.

**Comment by AmyKort** [comment]
@JonellaCulmer Can we pare this down at all based on your great work at https://github.com/fecgov/fec-testing/issues/119 ?

**Comment by JonellaCulmer** [comment]
@AmyKort Yes, I believe so. I got four testers to look at the homepage banner in addition to the other test previously completed on the banner. Still need to text more on the other three items.

**Comment by JonellaCulmer** [comment]
Attempting to test the Processed vs. Raw stuff as part of this work here: https://github.com/fecgov/fec-testing/issues/120

**Comment by JonellaCulmer** [comment]
Issue moved to [fecgov/fec-testing #123](https://github.com/fecgov/fec-testing/issues/123) via [**ZenHub**](https://www.zenhub.com/)
