### ISSUE TITLE
404 for House Candidates with only election year 2020 and cycle 2018

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2463]
**User story:** As a new candidate running in a future election (currently 2020/2022), I need to be able to see my candidate profile page even during 2018. 

When looking at house candidate pages with only an election_year defined as 2020 and only a cycle defined as 2018, we get a 404 error. It currently appears that only House candidate are impacted. 

Examples of these types of candidates that were found include:

https://www.fec.gov/data/candidate/H0FL18173
https://www.fec.gov/data/candidate/H0TX24134
https://www.fec.gov/data/candidate/H0FL01112
https://www.fec.gov/data/candidate/H0FL22050
https://www.fec.gov/data/candidate/H0GA06150
https://www.fec.gov/data/candidate/H0FL04124

These Senate and Presidential candidates also have the 2020 candidate election year and 2018 fec_election_yr but they don't have the problem that the House candidates do:

S0CO00419
S0CO00427
S0NC00277
S0SC00230
S0SC00255
S0KY00271

P00007393
P00006338
P00004911
P00007633
P00006809
P00005660

**Completion criteria:**
- [x] @jwchumley is going to check for other affected candidates
- [ ] Write a test for it, figure out why it's failing and mimic that behavior with a test
- [x] Check House, Senate and Presidential just in case
- [ ] Note: This area has the potential to break other things. Tread lightly.

**Comment by JonellaCulmer** [comment]
This ticket (https://github.com/fecgov/fec-cms/issues/2349) lays good groundwork for solving this issue.

**Comment by lbeaufort** [comment]
Local testing links
404 candidates
http://localhost:8000/data/candidate/H0FL18173
http://localhost:8000/data/candidate/H0TX24134
http://localhost:8000/data/candidate/H0FL01112
http://localhost:8000/data/candidate/H0FL22050
http://localhost:8000/data/candidate/H0GA06150
http://localhost:8000/data/candidate/H0FL04124

https://docs.google.com/spreadsheets/d/1xmDu2Ypr2tJnUjWZJcMIf_SOD7BOipCR4fGD3FmZLJ0/edit#gid=0
