### ISSUE TITLE
ADR feature testing

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2467]
Before deploying the new ADRs feature in the next release, we would like to test with the team (by the website team 11/1/2018) and subject matter experts. There's currently a feature flag in place for ADRs, so if this needs to slip due to external review we have some room.

**Completion criteria:**
- [x] Share prototype with ADRO for their review
- [ ] Meet with ADR team to review their feedback
- [ ] Compile and prioritize suggested fixes or additions from ADR subject matter experts

The feature space URL for ADRs is here: https://fec-feature-cms.app.cloud.gov/data/legal/search/adrs/

**Comment by AmyKort** [comment]
ADRO is reviewing the ADR search and will have comments for us next week.

**Comment by AmyKort** [comment]
We've got comments back from ADRO. Next step is to compile and prioritize these. @JonellaCulmer can we get together next week and walk through the feedback?

**Comment by JonellaCulmer** [comment]
Moving this to blocked while we wait to hear back from ADRO on some additional comments. 

cc: @AmyKort

**Comment by pkfec** [comment]
We have one round of feedback, but we had questions about their comments--some of them were pretty global to the legal resources section.we're looking for a follow-up meeting. In the meantime, they've just hired a new staff person, who will be our new contact person on this issue. They asked for more time to onboard that person before we met. 

Based on the above comments, I am removing the milestone from this issue.

**Comment by AmyKort** [comment]
I'm going to close this ticket--it's stale. Let's look at where we are with the ADR and Admin fines work and come up with a plan for PI9.
