### ISSUE TITLE
Reaction boxes on data landing and advanced data pages are being spammed

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2470]
**What we're after:** We're seeing a large number of FEC-issues-bot spam feedback being submitted to the FEC repo through the reaction boxes. The reaction boxes are in three places: data landing page, as well as the raising and spending advanced data pages. 

These reaction boxes are important to understanding how users are reacting to the line charts on those three pages, so it is my preference that we keep them there - but receiving so much spam is proving both annoying and time consuming to delete. 

**Completion criteria:**
- [x] @patphongs can share the recaptcha stats on this, if necessary
- [x] Look through the kibana logs to see how the submit is happening. Need to parse the logs. 
- [x] Identify root cause
- [x] Make appropriate changes
- [x] Confirm changes are present in all instances of the reaction box on data landing page, raising advanced data page, spending advanced data page

**Comment by patphongs** [comment]
Fix for this has been deployed and should alleviate our issues
