### ISSUE TITLE
Update links to efiling  and paper filed formats and documentation

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#2473]
**What we are after**: We need to update two links in the download bulk data section of the advanced data page.

**Why we are after it**: Users need to be able to find electronic and paper filing specifications, header  row files and metadata to help them understand and process .fec files. 

**Business completion criteria**:
- [ ] fix File formats, header file and metadata link in Electronically filed reports (.fec files) accordion
    - [ ] correct link is https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/bulk-downloads/electronic/eFilingFormats.zip

- [ ] fix File formats, header file and metadata link in Paper filed reports (.fec files) accordion
    - [ ] correct link is 
https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/bulk-downloads/paper/PaperFormats.zip

![image](https://user-images.githubusercontent.com/11817734/47514190-c55ba880-d84d-11e8-92bb-8f6b12da71a7.png)

**Technical completion criteria**:
- [ ] Update links in `partials/advanced/bulk-data.jinja`

**Comment by EarlGlynn** [comment]
Why are the files eFilingFormats.zip and PaperFormats.zip on AWS instead of GitHub?  Why not keep all revisions of these files on GitHub to improve transparency about changes?

**Comment by PaulClark2** [comment]
We have no plans to move these files to GitHub. The format files are on FEC.gov, https://www.fec.gov/data/browse-data/?tab=bulk-data. 

![image](https://user-images.githubusercontent.com/11817734/94264586-ee3abb80-ff04-11ea-9d59-8a40271dcf51.png)
