### ISSUE TITLE
Create JS test for dropdown.js disappearing dropdown change

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#2479]
Changes made to [dropdowns.js](https://github.com/fecgov/fec-cms/blob/develop/fec/fec/static/js/modules/dropdowns.js) in this PR #2471 removed tests to check for the dropdown to remove when user chooses last possible selection. 

- [ ] For this issue, create tests to make sure the dropdown does NOT remove when user chooses last possible selection.

**Comment by johnnyporkchops** [comment]
Although writing a test for the absence of a behavior might  not make as much sense as writing a test for the existence of a behavior. Nothing was added in the PR, just removed the call to a function: `removePanel`. It seems like for this test to make sense, it would test that the `removePanel` function is only called on init, and never again.
cc: @lbeaufort

**Comment by lbeaufort** [comment]
@johnnyporkchops given that fact, I think it's ok to close this issue. Thoughts?

**Comment by lbeaufort** [comment]
Closing this issue unless it comes up again
