### ISSUE TITLE
potential bug: undefined name 'paginator' in fec-cms/fec/home/views.py(line 314, 324, 334)

### ISSUE THREAD

**Issue by qqss88** [fecgov/fec-cms#2493]
it is potential bug when empty page exception encountered.

for testing:

This is a rare bug, it only happens when the empty paginator exception happens. There is no initial unit test for this. I think we just need to do a quick code check using flake8 or prospector(static code analysis tool) to make sure the original 'non-defined variable' error is gone.

I also did some clean up(removed some non-used imports) and code reformatting. make sure all functions related to fec/home/views.py are still working properly by checking fec.gov/about

Also, the related code has lot of redundant  and can definitely be refactored. we can open a new ticket on this for refactoring and new unit tests.
an example:

meetings_paginator = Paginator(open_meetings, 20)
    meetings_page = page if active == "open-meetings" else 1
    try:
        open_meetings = meetings_paginator.page(meetings_page)
    except PageNotAnInteger:
        open_meetings = meetings_paginator.page(1)
    except EmptyPage:
        open_meetings = meetings_paginator.page(meetings_paginator.num_pages)

    hearings_paginator = Paginator(hearings, 20)
    hearings_page = page if active == "hearings" else 1
    try:
        hearings = hearings_paginator.page(hearings_page)
    except PageNotAnInteger:
        hearings = hearings_paginator.page(1)
    except EmptyPage:
        hearings = hearings_paginator.page(hearings_paginator.num_pages)

    executive_paginator = Paginator(executive_sessions, 20)
    executive_page = page if active == "executive-sessions" else 1
    try:
        executive_sessions = executive_paginator.page(executive_page)
    except PageNotAnInteger:
        executive_sessions = executive_paginator.page(1)
    except EmptyPage:
        executive_sessions = executive_paginator.page(executive_paginator.num_pages)

**Comment by JonellaCulmer** [comment]
@qqss88 Can you please update this issue with more information? We don't have enough information to move forward.

**Comment by qqss88** [comment]
1. undefined 'paginator' fixed.
2. add a quick doc string
3. code reformatted and isorted.

**Comment by qqss88** [comment]
rebased and conflicts resolved. also removed some unused imports:
Line: 1
    pylint: unused-import / Unused import urllib
  Line: 6
    pylint: unused-import / Unused import requests
  Line: 9
    pylint: unused-import / Unused reverse imported from django.core.urlresolvers
  Line: 12
    pylint: unused-import / Unused redirect imported from django.shortcuts
