### ISSUE TITLE
Support/Oppose sort on IE table not functioning

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2494]
The sort filter for Support/Oppose column on IE datatable is not currently functioning. 

Need to identify the cause and fix as necessary. 

![Support-Oppose sort.gif](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/1683958d-7dfe-41f9-a727-2f0768f1256b)

**Comment by pkfec** [comment]
To make the support/oppose column sortable, requires an API change on SE endpoint. There is no ticket to track the API changes. @lbeaufort Can you please create API ticket for this?

**Comment by pkfec** [comment]
@lbeaufort i have created a new API ticket to enable the sort on ScheE endpoint by  support_oppose_indicator column. https://github.com/fecgov/openFEC/issues/3518

 The work on API is done.  I will submit a PR and have you or someone in our team review it.

**Comment by pkfec** [comment]
@JonellaCulmer The API PR to enable support/oppose indicator on Independent Expenditures is merged to `develop` branch. fecgov/openFEC#3518

Can you test the sort by support/oppose on IE datatables in `dev` environment?

**Comment by JonellaCulmer** [comment]
@pkfec The sort is working now on dev! But I noticed that regardless of which you're sorting by, there are "unknown"s that appear. Do we know how these are populating on the list?

**Comment by pkfec** [comment]
Sort on suppose/oppose indicator column is not working because this column values are inconsistent. The column value in the backend is not always S or O. @fecjjeng identified that there are other values like 0(ZERO), UNI, SUP and Nulls. 

Reached out to @jwchumley and waiting to hear from him on how to manipulate the data when the support/oppose indicator values either one of these : 0( ZERO), UNI, SUP and Nulls

**Comment by pkfec** [comment]
after taking to @jwchumley @PaulClark2 , we all agreed to replace the non S/O values with NULL.
@fecjjeng is working on updating the s_o_ind column on SE MV here:https://github.com/fecgov/openFEC/issues/3532

**Comment by pkfec** [comment]
@JonellaCulmer did you get a chance to test this bug in `Dev` environment?

**Comment by JonellaCulmer** [comment]
@pkfec So that I understand, I should no longer see Unknown, but null? I'm only seeing Support or Oppose.

**Comment by pkfec** [comment]
@JonellaCulmer Nulls on the backend are mapped to Unknowns on the CMS.  The Unknowns are always sorted last and they always appear at the end of the results.

**Comment by JonellaCulmer** [comment]
@pkfec I understand! Thanks so much! Looks great to me!

**Comment by JonellaCulmer** [comment]
The PR work related to this work has been merged and the fix has been reviewed. So closing this issue.
