### ISSUE TITLE
Wrap up final OIG page changes

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2497]
**What we're after:** Following up on the work related to the OIG pages, we need to make a few last changes to complete the work. 

**Completion criteria:**

- [ ] Remove legacy IG page from transition
- [ ] Add the footer back into e-regs (footer is completely missing in eregs) with updated IG link
- [ ] Update footer links on transition. This is more work intensive, however, the redirect is a good temporary solution until we can update all these footer links

**Related issues/PRs:**
https://github.com/fecgov/fec-cms/issues/2360 Modify Inspector General link in footer
https://github.com/fecgov/fec-proxy/pull/95 Add redirects for IG page and documents
https://github.com/fecgov/fec-cms/pull/2483 update IG link in footer

**Comment by patphongs** [comment]
OIG pages have been implemented in Wagtail, closing this issue
