### ISSUE TITLE
Broken candidate filing tab on null amendment_chain

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2504]
Candidate filings tab is not able to display filings if there is a null in the amendment_chain. We need to accommodate for nulls in the amendment chain. 

Example: https://www.fec.gov/data/candidate/P80001571/?tab=filings

**JS error:**
<img width="451" alt="screen shot 2018-11-13 at 12 20 37 pm" src="https://user-images.githubusercontent.com/12799132/48430993-99419200-e73e-11e8-966a-238970febe5d.png">

**Comment by lbeaufort** [comment]
PR has been deployed: https://github.com/fecgov/fec-cms/pull/2505
