### ISSUE TITLE
Remove PI 7 redirected pages off of transition and classic sites

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2512]
**User story** 
Users always want the latest version of FEC help for candidates and committees materials.

**What we're after** 
During PI7, we redirected many old, outdated pages and files, and now, with the redirects in place and working, it's time to take those materials off the transition and classic sites.

**To do**
Remove these files from the transition site and shut down their classic pages too:
- [x] /ans/answers_general.shtml
- [x] /ans/answers_disclosure.shtml
- [x] /ans/answers_compliance.shtml
- [x] /ans/answers_filing.shtml
- [x] /ans/answers_candidate.shtml
- [x] /ans/answers_pac.shtml
- [x] /ans/answers_party.shtml
- [x] /ans/answers_public_funding.shtml

- [x] /elecfil/electron.shtml
- [x] /elecfil/ef_overview.shtml
- [x] /elecfil/FECFileIntroPage.shtml
- [x] /elecfil/online.shtml
- [x] /elecfil/software.shtml
- [x] /elecfil/vendors.shtml

- [x] /info/articles/debtretirement09.pdf
- [x] /info/articles/windingdown09.pdf

- [x] /info/outreach.shtml
- [x] /info/elearning.shtml
- [x] /info/checkoff.htm
- [x] /info/election_day_links.shtml
- [x] /info/legrec.htm
- [x] /info/LegislativeRecommendations2002.htm
- [x] /info/LegislativeRecommendations1993.htm

- [x]  /info/guidance/recountreporting.shtml

- [x] /info/hearings.shtml

- [x] law/legrec2014.pdf
- [x] law/legrec2013.pdf
- [x] law/legrec2012.pdf
- [x] law/legrec2011.pdf
- [x] law/legrec2009.pdf
- [x] law/legislative_recommendations_2007.shtml
- [x] /law/legislative_recommendations_2005.shtml

- [x] /law/litigation/citizens_guide_brochure.pdf

- [x] /law/policy/enforcement/publichearing011409.shtml

- [x] /legrec1992.pdf

- [x] /pages/legislative_recommendations_2004.htm

- [x] /pages/brochures/public_funding_brochure.pdf
- [x] /pages/brochures/public_funding_brochure2012.pdf
- [x] /pages/brochures/saleuse.shtml

- [x] /pages/hearings/internethearing.shtml

- [x] /pdf/ar06.pdf
- [x] /pdf/ar05.pdf
- [x] /pdf/ar04.pdf
- [x] /pdf/ar03.pdf
- [x] /pdf/ar02.pdf
- [x] /pdf/ar01.pdf
- [x] /pdf/ar00.pdf
- [x] /pdf/ar99.pdf
- [x] /pdf/ar98.pdf
- [x] /pdf/ar97.pdf
- [x] /pdf/ar96.pdf
- [x] /pdf/ar95.pdf
- [x] /pdf/ar94.pdf
- [x] /pdf/ar93.pdf
- [x] /pdf/ar92.pdf
- [x] /pdf/ar91.pdf
- [x] /pdf/ar90.pdf
- [x] /pdf/ar89.pdf
- [x] /pdf/ar88.pdf
- [x] /pdf/ar87.pdf
- [x] /pdf/ar86.pdf
- [x] /pdf/ar85.pdf
- [x] /pdf/ar84.pdf
- [x] /pdf/ar83.pdf
- [x] /pdf/ar82.pdf
- [x] /pdf/ar81.pdf
- [x] /pdf/ar80.pdf
- [x] /pdf/ar79.pdf
- [x] /pdf/ar78.pdf
- [x] /pdf/ar77.pdf
- [x] /pdf/ar76.pdf
- [x] /pdf/ar75.pdf
- [x] /pdf/eleccoll.pdf
- [x] /pdf/legrec2016.pdf
- [x] /pdf/legrec2015.pdf
- [x] /pdf/legrec2003.pdf
- [x] /pdf/legrec1996.pdf
- [x] /pdf/legrec1995.pdf
- [x] /pdf/legrec1994.pdf
- [x] /pdf/legrec1991.pdf
- [x] /pdf/legrec1990.pdf
- [x] /pdf/legrec1989.pdf
- [x] /pdf/legrec1988.pdf
- [x] /pdf/legrec1987.pdf
- [x] /pdf/legrec1986.pdf
- [x] /pdf/legrec1985.pdf
- [x] /pdf/legrec1984.pdf
- [x] /pdf/legrec1983.pdf
- [x] /pdf/legrec1982.pdf
- [x] /pdf/legrec1981.pdf
- [x] /pdf/legrec1980.pdf
- [x] /pdf/legrec1979.pdf
- [x] /pdf/legrec1978.pdf
- [x] /pdf/legrec1977.pdf
- [x] /pdf/legrec1976.pdf

- [x] /pdf/forms/fecfrm1ssf.pdf
- [x] /pdf/forms/fecfrm1nc.pdf
- [x] /pdf/forms/fecfrm1party.pdf

- [x] /support/index.shtml

**Comment by johnnyporkchops** [comment]
These have been removed and backed up locally. Lets come up with a central location to put backed up files just in case we need them later. Maybe just a backup folder on the same filesystem will suffice.
