### ISSUE TITLE
Wrong section name in bulk data documentation

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2522]
@jschachter commented on [Tue Jun 12 2018](https://github.com/fecgov/FEC/issues/6156)

https://www.fec.gov/data/advanced/?tab=bulk-data

the "Contributions to candidates" section should be "Contributions by committees"

---

@jwchumley commented on [Fri Nov 16 2018](https://github.com/fecgov/FEC/issues/6156#issuecomment-439493938)

Correct. It should be changed to "Contributions by committees":
![image](https://user-images.githubusercontent.com/12615919/48641596-49fe9a00-e9a8-11e8-8958-c02412db1955.png)

Note the title says "contributions to candidates: but the description below the data links correctly describes contributions to committees.

**Comment by lbeaufort** [comment]
@AmyKort @jwchumley should the description say "Contributions by committees **to candidates**"? This doesn't look to include contributions by committees to parties, for example.

**Comment by jwchumley** [comment]
let me have a look at the downloaded data to make sure.


Jeff Chumley

Electronic Filing, Web and Disclosure Branch Manager

Federal Election Commission



________________________________

**Comment by jwchumley** [comment]
This is more complicated. THe section includes contributions from committees to candidate committees and independent expenditures made on behalf of or opposed to a candidate. "Contributions to candidate committees" is no more accurate than the current "contributions to candidates". 

I can't think of a good short phrase. "Contributions to Candidate committees and independent Expenditures"

"Direct and indirect candidate support"

Probably should wait and  let Paul chime in on this one. @AmyKort ?

Maybe Committee contributi
Probably should wait for Paul to weight in on this.

**Comment by lbeaufort** [comment]
@PaulClark2 @jwchumley what about "Contributions from committees to candidates and independent expenditures"

**Comment by PaulClark2** [comment]
I'll try to look at this tonight. I'm fine with the long name @lbeaufort suggests. On classic we used this title, "Contributions to Candidates (and other expenditures) from Committees."

It looks like the transaction type list is incorrect. It's too long. The list included on the description page seems to be for OTH (Any transaction from one committee to another). This files is PAS2. The transaction type list should be: 24A, 24C, 24E, 24F, 24H, 24K, 24N, 24P, 24R and 24Z.  I'll confirm this and I can make the change to the transaction type list.

**Comment by lbeaufort** [comment]
@PaulClark2 @jwchumley the title "Contributions from committees to candidates & independent expenditures" looked much better than "Contributions from committees to candidates and independent expenditures." 

If you agree, I tagged you as reviewers on the PR if you don't mind taking a look. It's a text change if you'd like to merge!
