### ISSUE TITLE
Bad link on webforms help page

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2524]
@fec-issue-bot commented on [Tue Jan 23 2018](https://github.com/fecgov/FEC/issues/5082)

## What were you trying to do and how can we improve it?
 When on the Form 5 webform pages and clicking on the “Help” button (https://webforms.fec.gov/wfja/help/form5help_nonregs.html and https://webforms.fec.gov/wfja/help/form5help_regs.html), the link for “electronic filing password” doesn’t work (https://www.fec.gov/elecfil/passwords.shtml).  

We need to send that link to https://webforms.fec.gov/psa/getstarted.htm instead.

---

@jwchumley commented on [Wed Jan 24 2018](https://github.com/fecgov/FEC/issues/5082#issuecomment-360146709)

Thank you for the feedback. We will correct this as soon as possible. In the mean time you can find the information here:
https://transition.fec.gov/elecfil/passwords.shtml

---

@jwchumley commented on [Fri Nov 16 2018](https://github.com/fecgov/FEC/issues/5082#issuecomment-439491685)

Here is the correct url for the password link to go to:
https://webforms.fec.gov/psa/getstarted.htm

**Comment by lbeaufort** [comment]
Steps to reproduce:

- Go to webforms: https://webforms.fec.gov/
- Click on either Form 5 link (you may need to click "agree")
- Click on "Help" button
- Click on "electronic filing password" link

**Comment by lbeaufort** [comment]
@AmyKort these pages aren't part of the fec-cms app - I believe they're maintained by Salient.

**Comment by patphongs** [comment]
Add redirect from https://www.fec.gov/elecfil/passwords.shtml to https://webforms.fec.gov/psa/getstarted.htm

**Comment by dorothyyeager** [comment]
Also noting the Form 5 failed redirect is also in play here.

**Comment by kathycarothers** [comment]
I have put in the requested redirect. It is now closed.

**Comment by dorothyyeager** [comment]
Closing issue for @kathycarothers (she needs to be add to FEC group).
