### ISSUE TITLE
webmanager link on saos.fec.gov points to a 404 on fec.gov

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2525]
@alex commented on [Tue Oct 23 2018](https://github.com/fecgov/FEC/issues/8174)

URL: http://saos.fec.gov/saos/searchao

In the footer "webmanager" points to: http://www.fec.gov/about/offices/CIO/webmanager/webmanager.shtml which is now a 404, it's supposed to have contact info for making suggestions to improve the FEC Advisory Opinion page. (I need this link so that I can complain that `saos.fec.gov` isn't available over HTTPS, which means advisory opinions can't be accessed securely.)

**Comment by AmyKort** [comment]
@jwchumley Could you reach out to Salient and ask them to fix this for us? Thanks!

**Comment by jwchumley** [comment]
I've passed it along to Salient and asked them to point to https://www.fec.gov/contact/.

Also I asked him about HTTPS but as I recall, we haven't upgraded these because they are being phased out.

**Comment by patphongs** [comment]
Please add redirect in http://www.fec.gov/about/offices/CIO/webmanager/webmanager.shtml to https://www.fec.gov/contact/

**Comment by dorothyyeager** [comment]
I've made the redirect. It solves the initial problem in that the user who clicks the old webmanager page will end up on the right place. 

I don't know if we still want to reach out to Salient to fix the original bad link.  Also, a note on the original comment. HTTPS links to AOs are available via the https://www.fec.gov/data/legal/search/advisory-opinions/ search. It's only the SAOS versions that come up using our legacy search that aren't HTTPS.

**Comment by patphongs** [comment]
@jwchumley Can you please take a look at Dorothy's comment above?

**Comment by jwchumley** [comment]
All of the legacy searchable apps are converted to HTTPS and Srini says he is working with Pat to correct links.

**Comment by alex** [comment]
Thanks all!
