### ISSUE TITLE
Bug: Candidate comparison map interaction on mobile

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2526]
@fec-issue-bot commented on [Wed Nov 04 2015](https://github.com/fecgov/FEC/issues/128)

## What were you doing?

Scroll down to map on iphone6
## What happened?

Map runs off screen. Fl and New England are cut off. Can&#39;t scroll side to side
## Details
- URL: https://beta.fec.gov/data/committee/C00575795/?cycle=2016&amp;tab=receipts
- User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 9_1 like Mac OS X) AppleWebKit/601.1.46 (KHTML, like Gecko) Version/9.0 Mobile/13B143 Safari/601.1

---

@jwchumley commented on [Thu Nov 05 2015](https://github.com/fecgov/FEC/issues/128#issuecomment-154112877)

This was mine by the way. Just so you know.

---

@jenniferthibault commented on [Wed Apr 19 2017](https://github.com/fecgov/FEC/issues/128#issuecomment-295565160)

This issue is still ongoing in the new format. cc @xtine 
https://beta.fec.gov/data/committee/C00575795/?cycle=2016&amp%3Btab=receipts&tab=receipts
<img width="365" alt="screen shot 2017-04-19 at 11 24 15 pm" src="https://cloud.githubusercontent.com/assets/11636908/25212280/635dc8b6-2557-11e7-8081-2b88ebc6f82d.png">

**Comment by JonellaCulmer** [comment]
Related to: https://github.com/fecgov/fec-cms/issues/2667
