### ISSUE TITLE
Users ending up on "District None" Senate election profile page that doesn't show data

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2530]
Users going to URL: https://www.fec.gov/data/elections/senate/IN/2018/?tab=spending-by-others 
 end up on "District None" version of the page that doesn't show data. 

For example, the URL goes to https://www.fec.gov/data/elections/senate/IN/None/2018/#independent-expenditures , which doesn't present results. 

Results show at https://www.fec.gov/data/elections/senate/IN/2018/#independent-expenditures. I am not sure how the "None" gets inserted into the search. Ideas?

**Comment by lbeaufort** [comment]
I believe this may be a symptom of this PR: https://github.com/fecgov/fec-cms/pull/2500

- [ ] Add automated tests 
- [ ] Refine district logic

**Comment by lbeaufort** [comment]
This is actually looking like an issue with the redirect of `?tab=spending-by-others`. I will investigate.
