### ISSUE TITLE
Implement advanced data page URL change and redirect(s)

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2538]
**What we're after:** As part of our effort not to unintentionally exclude any of our users from exploring our data, we modified the section name from "Advanced data" to "Browse data" (see https://github.com/fecgov/fec-cms/issues/2306#issuecomment-442087983). We now need to change the URL and add redirects from the old pages.

**Completion criteria:**
- [ ] Change URL from: `/data/advanced` to: `/data/browse-data`
- [ ] Put in redirect and make sure it will work with a "?" in the redirect (example: https://www.fec.gov/data/advanced/?tab=raising) - check what was done for election profile pages (see #2188 and fec-cms #2235 )

**Comment by AmyKort** [comment]
Is this ready to close?

**Comment by lbeaufort** [comment]
@AmyKort this work isn't done - I think it still adds value but it's up to you!

**Comment by lbeaufort** [comment]
Oh, haha it looks done to me, nevermind!
