### ISSUE TITLE
Election profile page: Draft individual Contributions No Results Message

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2554]
When there are no results for the individual contributions section of the election profile page, there is no message indicating no results. This should be added so that there is no confusion.

Example link to bug: http://fec-stage-proxy.app.cloud.gov/data/elections/house/CO/01/2022/

![screen shot 2018-11-29 at 4 01 02 pm](https://user-images.githubusercontent.com/12799132/49251696-049e8b80-f3f0-11e8-8507-3a1f74a3dc1d.png)

- [x] Identify these various error states.
- [x] Draft message
- [x] This table shows candidate checkboxes; we need to add messages/error states for other 
situations (no data at all, etc.) 
- [x] Draft implementation ticket

**Comment by AmyKort** [comment]
Looks like the error message should read (with the applicable date range):

We don't have individual contributions to candidates for 2019–2020.
This can be because:
•	We’re still processing the data. Try looking for raw versions of committee filings. Raw files are only available for electronic filers.
•	No one filed this type of activity during the time period.
•	The filing deadline hasn’t passed yet.
Think this result is a mistake or have questions?
Send us more information in the feedback box or contact us.

@dorothyyeager @lbeaufort

**Comment by patphongs** [comment]
I hope to get to this later today

**Comment by patphongs** [comment]
This is more complicated than I expected. Because the individual contributions table works based on "selected" candidate checkboxes, I have to figure out a way to show the no data message based on whether there are any candidates at all. Will work on this more next sprint, since it's more complicated

**Comment by JonellaCulmer** [comment]
Need to identify what the different error states are for this feature. Knowing this will guide our development and content needs.

**Comment by bmathesonFEC** [comment]
To summarize the conversation on this ticket, there are two potential ‘no result’ situations here:

1. When there are no candidates registered in the selected race.
          ex: https://www.fec.gov/data/elections/president/2019/
2. There are candidates but there aren’t any individual contributions disclosed by those candidates (@AmyKort’s language above is a starting point for that message)
          ex: https://www.fec.gov/data/elections/president/2018/

Would it simplify the issue for @patphongs if we have one error message that addresses both situations? Or, do you want it to display one of two available messages specific to the 'no result' situation?

(note, I modified the URLs to get those examples, they aren't otherwise find-able clicking through on the site.)

**Comment by bmathesonFEC** [comment]
Looks like some of the messages on this page are not accurate. We may need someone to look over the api logic for these requests to confirm data is displaying as intended.

The election profile page is made up of subsection tables (Candidate Financial Totals, Individual contributions to candidates, Independent expenditures, etc.). Each subsection has two messages:

1. No Results: The message that appears when there are no results in the subsection table.
2. Static message: appears at the bottom of each subsection.

Here are my proposals for each of those subsection messages:
### Candidate Financial Totals

**Static message:**
**Current:** 

> This table only shows candidates who have registered and filed a financial report. Information in this table may not include the most recently submitted filings.

_Problem_, candidates that have registered are included in the list prior to filing a financial repor

**Proposed:** 

> This table only shows candidates who have registered and designated a registered principal campaign committee. Information in this table may not include the most recently submitted filings.

t.
_Example_, C00665117, P00006742, Frank, David: registered candidate with registered committee, no financial totals is on the list.
_Example_ P00009415, Cats, Seymore: registered candidate, no registered committee, not on the list.

### Individual contributions to candidates
**“No Results” message:** 
**Static message:**

**Comment by bmathesonFEC** [comment]
One of the existing messages on this pages is inaccurate. @patphongs, we may need someone to look over the api logic for these requests to confirm data is displaying as intended. A change to the logic here affects the way we will display messages to users. If we decide no change is needed, here's proposed new and edited language for our messages. (A quicker approach is to assume we're satisfied with the display of the data and conform our messages accordingly).

### Background:
The election profile page is made up of subsection tables (Candidate Financial Totals, Individual contributions to candidates, Independent expenditures, etc.). Each subsection has two messages:

No Results: The message that appears when there are no results in the subsection table.
Static message: appears at the bottom of each subsection. Visible when results are and are not present.

Here are my proposals for each of those subsection messages:

## Candidate financial totals
**Static message:**
Current:
> This table only shows candidates who have registered and filed a financial report. Information in this table may not include the most recently submitted filings.

_Problem_, candidates that have registered are included in the list prior to filing a financial report.
_Example_, C00665117, P00006742, Frank, David: registered candidate with registered committee, no financial totals **is on the list**.
_Example_, P00009415, Cats, Seymore: registered candidate, no registered committee, **not on the list**.

Proposed:
> This table only shows candidates who have registered and designated a registered principal campaign committee. Information in this table may not include the most recently submitted filings.

**"No Results" message:**
no change

## Individual contributions to candidates
**“No Results” message:**
**No Candidates -- No Contributions**
> We don't have individual contributions to candidates for 20**–20**.
> This can be because:
> - No candidates have registered for this election. 
> - Registered candidates for this election have not yet filed a financial report.
> Think this result is a mistake or have questions?
> Send us more information in the feedback box or contact us.

**Yes Candidates -- No Contributions**

> We don't have individual contributions to candidates for 20**–20**.
> This can be because:
> - We’re still processing the data. Try looking for raw versions of committee filings. Raw files are only available for electronic filers.
> - No one filed this type of activity during the time period.
> - The filing deadline hasn’t passed yet.
> Think this result is a mistake or have questions?
> Send us more information in the feedback box or contact us.

**Static message:**
Current: None.

Proposed:
> This table only shows candidates who have registered and filed a financial report. Information in this table may not include the most recently submitted filings.

**Comment by patphongs** [comment]
Thanks @bmathesonFEC! May I suggest splitting up the tickets for the candidate financial totals table and the individual contributions error states? Or do you feel like they are one in the same?

**Comment by bmathesonFEC** [comment]
I'll draft two implementation tickets for this. One of these changes is more straight forward than the other.

**Comment by bmathesonFEC** [comment]
Sounds like the nature of the work is different so I'm making them separate tickets:

1. Update no results message on election profile page candidate individual contributions to candidates. #3199 
2. Update static messages on election profile page. #3200
3. Election Profile Page - Inconsistent Sets of Candidates #3201
