### ISSUE TITLE
Add election search and bar charts to homepage

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2562]
**What we're after:** Following on the design work done [here](https://github.com/fecgov/fec-cms/issues/2674), we need to now implement the design on the front-end. Specifically, we need to add the election search to the FEC.gov homepage. As part of this work, we are also making tweaks to the language in the Getting started section of the page. 

**Completion criteria:**
- [x] Incorporate the election search map into the gray box on the homepage
- [x] Change header above election search that says "Compare candidates in elections"
- [x] Include copy in Compare candidate section: "Learn about candidates running in a particular state or district for past or upcoming elections."
- [x] Create new section between election search map and bar charts for these links (next item), use icon and text format, as seen in website menus. Separate with white lines. 
- [x] Include links to citizen guide sections
  - 1: Understand ways to support federal candidates https://www.fec.gov/introduction-campaign-finance/understanding-ways-support-federal-candidates/. Use direction sign icon.
  - 2: Learn more about using the FEC's campaign finance data https://www.fec.gov/introduction-campaign-finance/how-to-research-public-records/. Use financial document icon.
  - 3: Find election and voting information https://www.fec.gov/introduction-campaign-finance/election-and-voting-information/. Use election icon.
- [x] Change "Getting started" header to "Who's raising and spending the most"
- [x] Include copy: "Learn how much individual candidates have raised and spent for presidential, Senate and House elections."
- [x] Include modified version of the raising and spending bar charts in toggle format so that users can switch between the two. 
- [x] Add interactions to search the bar chart data including toggle, and two-single select dropdowns for the candidate selection and election year selection. 
- [x] Show top three raisers/spenders in bar chart

### Homepage design

<img width="898" alt="screen shot 2019-02-22 at 4 28 41 pm" src="https://user-images.githubusercontent.com/31663028/53272719-0d85bd00-36c0-11e9-864d-0b138d173bbc.png">

**Comment by johnnyporkchops** [comment]
Changed the estimate for this from 2 to 3 after looking deeper in to what is it going to entail to embed content from /data app in to /home app in addition to responsively redesigning both visualizations (map and bar chart) for new layout and location.

**Comment by johnnyporkchops** [comment]
@JonellaCulmer - The embedded election map does not have a "election" dropdown in the  mockup, is that correct? Just checking because the title mentions "state or district for past or upcoming elections..."

**Comment by JonellaCulmer** [comment]
@johnnyporkchops That's correct. The default will take you to the current/upcoming election year.

**Comment by AmyKort** [comment]
@johnnyporkchops I have one more edit to this design--sorry it is coming so late. 

In the line of 3 icons in the middle of the design, could the last one read: "Find election *results* and voting information." 

Thanks!

**Comment by AmyKort** [comment]
change goes here:
![image](https://user-images.githubusercontent.com/13237823/54132862-5b523300-43eb-11e9-92c0-33d1cd4ba9b0.png)

cc @JonellaCulmer

**Comment by JonellaCulmer** [comment]
This is merged, so closing.
