### ISSUE TITLE
Develop map based on mockups

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2563]
**What we're after:** As part of our ongoing visualization work, we need to begin to develop the map work that was previous started [here](https://github.com/fecgov/fec-cms/issues/2542), with the creation of maps feature branch. 

This work includes creating a nationwide raising map to show money raised by state.

A possible dummy data source is the `schedules/schedule_a/by_state/by_candidate/` endpoint. You could use one or two candidates as an example until we get the totals endpoint straightened out. https://api.open.fec.gov/v1/schedules/schedule_a/by_state/by_candidate/?api_key=DEMO_KEY&candidate_id=P00006213&candidate_id=P80001571&cycle=2018&per_page=99

**Completion criteria:**
- [ ] Put a feature flag on the raising map
- [ ] Develop functioning choropleth maps based on existing technology, such as those used on election profile pages (https://www.fec.gov/data/elections/senate/AZ/2018/ > Individual contributions to candidates > Contributions by state toggle > Map toggle) for the Raising: by the numbers page

### Raising by House/Senate/Presidential by state
<img width="817" alt="screen shot 2018-11-28 at 8 38 57 am" src="https://user-images.githubusercontent.com/31663028/49156201-c7040a80-f2ea-11e8-9ce0-2076d5d4470d.png">

**Comment by patphongs** [comment]
This is no longer needed, design direction has changed
