### ISSUE TITLE
Final Review of 2019 Prior Notice Pages 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#2572]
User story: As a committee I need to know when my reports are due for 2019. 

Background: This summer we developed the reporting pages for 2019. Those pages will be published the first week in January of 2019. Before they are published they need a final look over. 

To do: 
- [x] Review the Quarterly, Semi-annual and monthly prior notices
- [x] Review the Supplements to each notice 
- [x] Review CC, EC, FEA and IE pages

**Comment by kathycarothers** [comment]
Need to follow-up with David Garr on the following pages:
Filing Freq
Quarterly filers page
Monthly filers page
Semi-annual filers page 
IE page
CC page
EC page
FEA page 
Presidential pages

**Comment by kathycarothers** [comment]
Publishing orphan pages to ensure all links are working and all pages are connected. Then will move into final review of pages.

**Comment by kathycarothers** [comment]
Info Div. in process of final review of pages

**Comment by dorothyyeager** [comment]
@kathycarothers has completed her review and my understanding is that Info. Division management is doing one final review of the pages. We can close this issue once that's completed.

**Comment by dorothyyeager** [comment]
Prior notices have been reviewed by the website team and Info Div. management, so we are able to close this issue. The pages will be posted (to be linked off Dates and deadlines) in early 2019.
