### ISSUE TITLE
[Med] Snyk: Cross-site Scripting (XSS) due 2/4/19

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2573]
Vulnerable module: lxml
Introduced through: lxml@3.7.0
Detailed paths
Introduced through: project@0.0.0 › lxml@3.7.0

Remediation
Upgrade lxml to version 4.2.5 or higher.

https://app.snyk.io/org/fecgov/project/ff0dca01-794e-4c1c-bf1f-0c0f8932fadd/

**Comment by lbeaufort** [comment]
@patphongs great point. Look what I found! https://github.com/fecgov/fec-cms/issues/1628

Do you anticipate needing to do more scraping? There's probably scraping-related code we should remove as well.

**Comment by patphongs** [comment]
> Do you anticipate needing to do more scraping? There's probably scraping-related code we should remove as well.

Thanks @lbeaufort for finding that old ticket. We discussed that since this code is not needed right now, we can delete the scraping script and remove the `lxml` dependency.

**Comment by lbeaufort** [comment]
@pat I might have misunderstood the scraping - is scraping the only way we can add things to the site-wide search? (per instructions here: https://github.com/fecgov/fec-cms/blob/develop/fec/search/management/instructions.md)

**Comment by qqss88** [comment]
I can spend some time on this and add some details.

**Comment by qqss88** [comment]
Just add some quick points here
1. digitalgov search tool seems not working now. It probably replaced by search.gov
2. if lxml package is an issue for scraping,  and we still need those scrape code, there are other html parser we can use. Refer this page for more details:
https://www.crummy.com/software/BeautifulSoup/bs4/doc/

**Comment by patphongs** [comment]
@lbeaufort Oh that's right, I forgot about scraping for the search. It might be best to just upgrade for now then. We haven't scraped content for the search in a little while I think, so we'll need this utility when we do scrape again.

**Comment by lbeaufort** [comment]
@patphongs thanks! For now, we decided to leave the code in place and just update the package to satisfy the security warning. We can investigate the scraping code further when we reopen.

**Comment by lbeaufort** [comment]
@fec-jli deployed the hotfix today, so closing this issue. Thanks @fec-jli!
