### ISSUE TITLE
Update the FEC organization chart for recent personnel changes

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2589]
We need to update the FEC organization chart for a few changes:

To do:
- [x] Edit the title to say "Deputy Staff Director, Management and Administration" (no other changes needed, as the position is no longer "Acting")
- [x] Remove "J. Cameron Thurber" from the box for Deputy Inspector General and replace with "Vacant"
- [x] Not in screencap but in the box for Chief Information Security Officer, replace Licerio G. Ribeiro Jr with Justin Park and add "Acting" to the title.

![image](https://user-images.githubusercontent.com/24437369/50016824-4acf1f80-ff98-11e8-9123-4d5d962900d6.png)

**Comment by johnnyporkchops** [comment]
@dyeager  
This has been updated:
http://transition-stage.fec.gov/about/offices/offices.shtml

**Comment by johnnyporkchops** [comment]
Oops. Good catch. Updated
http://transition-stage.fec.gov/about/offices/offices.shtml

**Comment by dorothyyeager** [comment]
Perfect, thanks! Looks great. I'll go ahead and close the ticket since work is completed.
