### ISSUE TITLE
Make small state chiclets

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#2605]
**What we are after:** So that users can find and click on smaller states like Rhode Island or Maryland because the map will not currently be zoomable. We want to add chiclets (buttons) like in the example below:
See classic site for example: https://transition.fec.gov/info/ElectionDate/

**Comment by patphongs** [comment]
This is a duplicate issue and we decided to go a different direction. This ticket is no longer needed.
