### ISSUE TITLE
Add existing election search to Homepage

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#2607]
**What we are after:** Add the election search to homepage that currently exists at https://www.fec.gov/data/elections/?state=&cycle=2020&election_full=true
Mockup is part of this issue:
https://github.com/fecgov/fec-cms/issues/2566
Completion criteria:

- [ ] Determine what what the final decided-upon location for this is on homepage
- [ ] Reconfigure search box to fit in this design and work responsively
- [ ] Consider using CSS grids and/or Flexbox to make this respond better to various screen sizes (this may also include reconfiguring SCSS and layout for the full page layout if the search area on data/elections (#2619)
- [ ] Need to decide if there is indeed full browser support for this and wether a polyfill for IE is necessary and wether we want to use a polyfill or wait until  IE to gets on board with support.
See issue: Reconfigure election search box using CSS grid and or Flexbox #2619

**Comment by JonellaCulmer** [comment]
Closing this issue in favor of: https://github.com/fecgov/fec-cms/issues/2562
