### ISSUE TITLE
Add toggle for House, Senate, and Presidential

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2610]
We need to add the dropdown to select the 3 different office types: House, Senate, and Presidential

**completion criteria:**
- [x] Add screenshot of mock-up
- [ ] Verify data filters correctly when toggling. This may be using dummy data at first until API changes are made.

**Comment by JonellaCulmer** [comment]
Here's a screenshot of the raising map. The area of interest for this ticket is highlighted in pink. 
![screen shot 2019-01-29 at 1 13 39 pm](https://user-images.githubusercontent.com/31663028/51931971-273b2980-23cc-11e9-96ad-a087abc9c934.png)

**Comment by patphongs** [comment]
No longer needed, changed design direction
