### ISSUE TITLE
Insert All state totals

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2611]
All state totals need to appear at the bottom of the table for Where contributions come from. We can code it in with filler text at first until the API is able to create that total for us to pull in.

**Completion criteria:**
- [ ] Create secondary ticket to pull in real data from API.

**Comment by lbeaufort** [comment]
Closing in favor of https://github.com/fecgov/openfec/issues/3559

**Comment by lbeaufort** [comment]
Oops, I thought this was API work, sorry - reopening!

**Comment by JonellaCulmer** [comment]
Below is a screenshot of the raising map. The area of interest is highlighted in pink. 

![screen shot 2019-01-29 at 1 44 20 pm](https://user-images.githubusercontent.com/31663028/51932104-708b7900-23cc-11e9-9092-eb826d9f57f9.png)

**Comment by patphongs** [comment]
This is no longer needed, design direction has changed
