### ISSUE TITLE
Mockup changes to raising and spending by the numbers time periods

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2616]
**What we're after:** With the introduction of the new raising map, we are changing the way the By the numbers pages function. We're making it so that each table is individual and distinct and with therefore require its only time period filter - as opposed to the time period at the top of the page dictating all the data shown.

**Completion criteria:**
- [x] Mock up the new time period filter for both the raising and spending pages so they function the same way. 
- [x] Introduce way to traverse between raising and spending: by the numbers pages
- [x] Design where totals will be on raising/spending breakdown feature
- [x] Confirm methodology language is accurate

### Currently on .gov:
**Raising**
<img width="848" alt="screen shot 2018-12-21 at 4 33 22 pm" src="https://user-images.githubusercontent.com/31663028/50364504-3b267c80-053e-11e9-8774-a6d579e98c7b.png">

**Spending**
<img width="796" alt="screen shot 2018-12-21 at 4 33 38 pm" src="https://user-images.githubusercontent.com/31663028/50364507-41b4f400-053e-11e9-9520-a6da1c5e11d9.png">

**Comment by JonellaCulmer** [comment]
First pass at updating the Who's raising the most chart to change the time filter:
<img width="624" alt="screen shot 2018-12-21 at 4 56 40 pm" src="https://user-images.githubusercontent.com/31663028/50365195-6bbbe580-0541-11e9-92c2-0708be7adef7.png">

**Comment by JonellaCulmer** [comment]
Below are updated versions of the bar charts on each of the 'by the numbers' pages: raising and spending. These updates include an aggragate total for all money raised by a committee type, add a button to move between the raising and spending by the numbers pages, and change the time filter from a two-year period to election. 

The content team needs to review the language used in three places: the new button below the left-hand navigation, the description text for the total data figure, and the text to introduce the elections dropdown "Running in". For the "running in" language, it makes sense when we're talking about candidates, but doesn't make sense in the case of PACs or Parties, which are data sets that are also available on this bar chart. The "running in" language needs to accommodate all of them. cc: @AmyKort @dorothyyeager @kathycarothers 

### Raising design
<img width="814" alt="screen shot 2019-02-11 at 6 12 37 pm" src="https://user-images.githubusercontent.com/31663028/52600285-19a08d80-2e29-11e9-8e5e-72f647d5faff.png">

### Spending design
<img width="873" alt="screen shot 2019-02-11 at 6 11 10 pm" src="https://user-images.githubusercontent.com/31663028/52600304-26bd7c80-2e29-11e9-9ef7-5b949783843f.png">

Happy to have a chat with content team if there are any questions.

**Comment by AmyKort** [comment]
I like these a lot, @JonellaCulmer . The totals bar is very effective at pulling out the big number and also making it clear where we got that figure. I might tweak the language to say: The total raised by *all* presidential candidates between January 01, 2017 *and* December 31, 2018.

For the "running in" box--I think that language is great. I'd like to revisit the idea of not including PAC and Party spending/raising on these particular charts. I think it is confusing to put candidate and other spending on the same chart. Also, now that we are adding totals, I think we risk confusing users by providing different totals here than what we show for PACs and parties on the "cost of the election" chart that accounts for transfers, etc.. cc @PaulClark2 and @jwchumley

**Comment by PaulClark2** [comment]
@AmyKort @JonellaCulmer we mix committee types in our "cost of election" chart. We do need to think about how to make it clear that the totals on the "by the numbers" chart will be different than the numbers on the "cost of election" chart. Of course, we can add information about the "by the numbers" methodology to the methodology pop-up. 

I'd be interested in others opinions about mixing committee types. Is there anything in the navigation path to the "by the numbers" charts that would lead a user to expect they are only going to see candidate data? If we restrict the chart above to candidate data, where are we going to visualize PAC and party data? 

![image.png](https://images.zenhubusercontent.com/59563d2061b4ca3b0a72d03d/43617d7d-5d1f-43bf-86f1-48263cb03800)

**Comment by PaulClark2** [comment]
Amy's right ......

**Comment by JonellaCulmer** [comment]
Final mockups for the raising and spending by the number bar charts are below. 

While updates have been made to the charts based on the completion criteria (changing two-year period, adding aggragate total, and button to switch between raising and spending pages), modifications have also been made to remove PACs and Parties now that we are moving to cycle-specific time periods, depending on the seat. 

Because previous testing has not been on the time periods, we don't have enough information to show that users will or won't be confused. We hope to conduct additional testing to ensure that users are not confused by the removal and will explore new ways to present this data. This also gives us an opportunity to enhance the data for PACs specifically, since including ActBlue numbers tends to skew the results. (ActBlue will always be the top raising PAC).

### Raising design
<img width="957" alt="screen shot 2019-02-12 at 3 22 54 pm" src="https://user-images.githubusercontent.com/31663028/52665661-1addc300-2eda-11e9-8d20-4877fa0e8ae2.png">

### Spending design
<img width="943" alt="screen shot 2019-02-12 at 3 22 26 pm" src="https://user-images.githubusercontent.com/31663028/52665676-216c3a80-2eda-11e9-9f81-40adc8a4c44a.png">

**Comment by JonellaCulmer** [comment]
@PaulClark2 Do you have the bandwidth to review the methodology? I know we now need to drop the last line at least.
<img width="795" alt="screen shot 2019-02-12 at 3 28 35 pm" src="https://user-images.githubusercontent.com/31663028/52666047-2087d880-2edb-11e9-9475-484fd19fa193.png">

**Comment by PaulClark2** [comment]
@JonellaCulmer  here's my first pass.  We'll need to ask @dorothyyeager @AmyKort and @bmathesonFEC  to make to better. Note for content reviewers: we are including financial data from a candidate's PCC and  other authorized committees, committee designations "P" and "A." We do _not_ include JFs.  

This chart includes data up to and including the most recent report filed by each campaign. It displays an overall total for the selected office and it displays totals for individual candidate campaigns.

The overall total is the sum of the total receipts of the campaign committees of the selected office. 

Candidates are displayed in descending order of total receipts. Total receipts are the sum of all contributions and other receipts received by the candidate’s authorized committees: two-year cycles for House candidates, four-year cycles for presidential candidates and six-year cycles for Senate candidates. 

The form and line used to calculate candidate campaign total receipt sums are: 

- Presidential campaigns: Form 3P, Line 22, Column A
- Senate and House campaigns: Form 3, Line 16, Column A

**Comment by AmyKort** [comment]
This looks good to me. I have a small suggested edit below, but I would defer to @PaulClark2 and @bmathesonFEC about the best way to communicate this information.

"This chart includes data up to and including the most recent report filed by each campaign. It displays an overall total for the selected office and *also* displays totals for individual *candidate's* campaigns."

**Comment by PaulClark2** [comment]
@AmyKort I like your edit.

**Comment by dorothyyeager** [comment]
I do too.

For this line: "The overall total is the sum of the total receipts of the campaign committees of the selected office." - should it be "candidate" instead of "office"? (Unless we mean the big billion dollar overall total, in which case, I'm still finding "office " a little confusing. Maybe "race"?

**Comment by JonellaCulmer** [comment]
@dorothyyeager Office or seat. Race would work for Presidential elections, but not for House and Senate when there are multiple races.

**Comment by PaulClark2** [comment]
@dorothyyeager @JonellaCulmer I don't have a preference. My reason for using the word "office" was simply because the drop-down options are "Presidential candidates," "House candidates" and "Senate candidates." I will defer to the content folks about word choice there.

**Comment by dorothyyeager** [comment]
How about "The overall total is the sum of the total receipts of the campaign committees of all candidates for the selected office."

**Comment by PaulClark2** [comment]
@dorothyyeager I like it. It's clearer than my version.

**Comment by bmathesonFEC** [comment]
Should we include something here about processed vs. raw data? Am I right that these figures won't be updated until the filing is processed?

**Comment by PaulClark2** [comment]
I'm not sure. The sums are generated from Pass 1 data. So the delay is typically 24 hours or less.  What do other folks think?

**Comment by bmathesonFEC** [comment]
My suggesting is based on the assumption that press/info gets calls when candidates don't think their numbers are up-to-date. If that's not a problem then we don't need to add anything.

**Comment by PaulClark2** [comment]
@bmathesonFEC I checked with Christian about adding a note about processed data. He doesn't think it's necessary because the sums are calculated from summary level data (pass 1) that is updated nightly. 

This version incorporates edits by @AmyKort and @dorothyyeager. 

This chart includes data up to and including the most recent report filed by each campaign. It displays an overall total for the selected office and also displays totals for individual candidate's campaigns.

The overall total is the sum of the total receipts of the campaign committees of all candidates for the selected office.

Candidates are displayed in descending order of total receipts. Total receipts are the sum of all contributions and other receipts received by the candidate’s authorized committees: two-year cycles for House candidates, four-year cycles for presidential candidates and six-year cycles for Senate candidates.

The form and line used to calculate candidate campaign total receipt sums are:

* Presidential campaigns: Form 3P, Line 22, Column A
* Senate and House campaigns: Form 3, Line 16, Column A

**Comment by JonellaCulmer** [comment]
@PaulClark2 Great! So we've got the raising methodology down. Assuming there are only a few places that need to be changed for the spending chart. I **bolded** some areas. 

This chart includes data up to and including the most recent report filed by each campaign. It displays an overall total for the selected office and also displays totals for individual candidate's campaigns.

The overall total is the sum of the **total receipts** of the campaign committees of all candidates for the selected office.

Candidates are displayed in descending order of **total receipts.** **Total receipts are the sum of all contributions and other receipts received** by the candidate’s authorized committees: two-year cycles for House candidates, four-year cycles for presidential candidates and six-year cycles for Senate candidates.

The form and line used to calculate candidate campaign **total receipt sums** are:

* **Presidential campaigns: Form 3P, Line 22, Column A**
* **Senate and House campaigns: Form 3, Line 16, Column A**

**Comment by PaulClark2** [comment]
@JonellaCulmer here's my first pass. We'll need to ask @dorothyyeager @AmyKort and @bmathesonFEC to make to better.

This chart includes data up to and including the most recent report filed by each campaign. It displays an overall total for the selected office and also displays totals for individual candidate's campaigns.

The overall total is the sum of the total disbursements of the campaign committees of all candidates for the selected office.

Candidates are displayed in descending order of total disbursements, Total disbursements are the sub of all expenditures and other disbursements made by the candidate’s authorized committees: two-year cycles for House candidates, four-year cycles for presidential candidates and six-year cycles for Senate candidates.

The form and line used to calculate candidate campaign total disbursement sums are:

* Presidential campaigns: Form 3P, Line 30, Column A
* Senate and House campaigns: Form 3, Line 22, Column A

**Comment by dorothyyeager** [comment]
I don't have any edits to that -seems clear to me!

**Comment by AmyKort** [comment]
I agree with @dorothyyeager

**Comment by bmathesonFEC** [comment]
Yep, looks good.

**Comment by JonellaCulmer** [comment]
This issue is complete. Closing in favor of implementation issue: https://github.com/fecgov/fec-cms/issues/2678
