### ISSUE TITLE
Update scatterplot based on user testing and data/design studio

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2621]
**What we're after:** After discussing the usefulness of the proposed spending map, the team determined it was not the best way to display relevant data. So we have decided to move on to the scatterplot map which was designed following the visualization review completed during PI 7. 

The team was fortunate enough to be able to test the scatterplot at COGEL and were able to come away with some takeaways to improve it. 

This ticket is to incorporate that feedback from user testing as well as what was discussed during the data/design studio at PI 8 planning. 

**Completion criteria:**
- [x] @bmathesonFEC to provide valuable/key expenditures for PACs
- [x] Review scatterplot feedback, including incorporating multiple committees to review
- [x] Eliminate committee type from search, make it so that we can compare two specific PACs
- [x] Add additional completion criteria based on user testing feedback
- [ ] Identify/write-up clear methodology
- [x] Make figures clickable to disbursements
- [ ] Move to the implementation issue

### Current design:
<img width="849" alt="screen shot 2018-12-17 at 10 20 58 am" src="https://user-images.githubusercontent.com/31663028/50364405-d834e580-053d-11e9-91e2-f3b90f3c53e2.png">

**Comment by JonellaCulmer** [comment]
User feedback found here: https://drive.google.com/drive/folders/1qGTRJRzBcQ8gqTZAOM6IycK7TQmdYmzQ

Summary presentation found here: https://docs.google.com/presentation/d/1acCvMwkQRuGbgLwxyXuTZrFrRGwdV58wz-633zvLs1U/edit?usp=drive_web&ouid=105783572789865461959

**Comment by JonellaCulmer** [comment]
Below are three different states of the PAC spending chart. They show the possibilities for what the chart might look like at different stages of interaction. 

### Starting state
This beginning state is very empty. This is before the user has made any choices to the chart. We may want to consider a default state and include one or two committees for possible comparison. Perhaps the top two spending nonconnected committees, or a random set of two. I welcome other ideas.
<img width="818" alt="screen shot 2019-02-25 at 3 06 34 pm" src="https://user-images.githubusercontent.com/31663028/53365486-613a1580-390f-11e9-80e9-128d0966287d.png">

### User adding committees for comparison
This state shows the user actively making selections of PACs to compare. It also shows what it could look like if the user were only seeking out the spending data for a single committee, as there is only one column on the right-hand side. 

Because we are limiting the chart to show nonconnected committees, we need to provide an "error" message that notifies users of the potential problem. I considered limiting the dropdown list to include only those nonconnected committees, but if a user continues to type out a complete committee ID or name and sees nothing, we need to provide them with a way to rectify the problem. This requires some help from the content team to help flesh out what this message should say, but it should be very short and concise. 
<img width="790" alt="screen shot 2019-02-25 at 3 12 44 pm" src="https://user-images.githubusercontent.com/31663028/53365675-d4438c00-390f-11e9-96d8-7bc8a0c16632.png">

### Complete state
This state shows a successful comparison between two committees. It also displays what the dots will do when both committees have the same percentage for a particular disbursement type, as well as two rows of data on the right-hand side. 
<img width="804" alt="screen shot 2019-02-25 at 3 07 01 pm" src="https://user-images.githubusercontent.com/31663028/53365836-300e1500-3910-11e9-8535-661222b8673b.png">

cc: @patphongs @PaulClark2 @AmyKort @bmathesonFEC @rfultz @johnnyporkchops

**Comment by patphongs** [comment]
@JonellaCulmer These are good mock ups, I like how you explained each state of your designs. I've annotated a few observations using invision for easier references: https://projects.invisionapp.com/boards/D73T93A5S4T/

**Comment by JonellaCulmer** [comment]
@patphongs Thanks for all the feedback! I've answered your questions in Invision.

**Comment by AmyKort** [comment]
This looks really good to me @JonellaCulmer! I don't think I have anything to add to the great feedback from @patphongs . I agree that we might want to provide more prompts to help users identify nonconnected PACs, to lessen frustration. Also, even though we link to the glossary definition of nonconnected committee, we might want to see if there's a way to help users find https://www.fec.gov/help-candidates-and-committees/guides/?tab=political-action-committees for more information. The glossary defines a nonconnected committee by identifying what it is not--which is helpful, but maybe not helpful enough.

**Comment by dorothyyeager** [comment]
Thought on @AmyKort's thought - linking to the pages at https://www.fec.gov/help-candidates-and-committees/registering-pac/types-nonconnected-pacs/ (Types of nonconnected PACs) and/or https://www.fec.gov/help-candidates-and-committees/registering-pac/understanding-nonconnected-pacs/ (Understanding nonconnected PACs) will help readers understand nonconnected PACs. We don't have a great term for them.

**Comment by JonellaCulmer** [comment]
@dorothyyeager That works for me. For now, I'm thinking any linking can go in the methodology until we get enough feedback. We can test for confusion. I'm thinking there will be some, but perhaps more so with the actual search limitation. 
cc: @AmyKort

**Comment by JonellaCulmer** [comment]
@patphongs We may need to hold off on drafting the methodology until we have a clearer picture of what back-end work is required. What do you think?

**Comment by JonellaCulmer** [comment]
@bmathesonFEC Can you help me to understand which expenditure types are going to be included in the "All other spending" category that will group "all" other expenditures. 
Is it the following, highlighted lines, or am I missing anything?
<img width="974" alt="screen shot 2019-02-27 at 3 16 41 pm" src="https://user-images.githubusercontent.com/31663028/53520062-be1a0500-3aa2-11e9-97d3-058b70e8fc73.png">

**Comment by lbeaufort** [comment]
@JonellaCulmer yes, it's possible. 

Including transfers in "all other spending" would probably be confusing - we see some really [big](https://www.fec.gov/data/disbursements/?two_year_transaction_period=2018&data_type=processed&min_date=01%2F01%2F2017&max_date=12%2F31%2F2018&line_number=F3-18) transfers.

**Comment by bmathesonFEC** [comment]
@JonellaCulmer These are great. I really like that you took the time to mock each state and include warning messages. 

**Small thing:** can we make the PAC's total expenditure number at the top clickable to direct the user to the committee's Financial Summary > Total Spent: https://www.fec.gov/data/committee/C00011262/?tab=summary#total-spent

**Re: default state.** I agree that it shouldn't be blank, but I'm not sure what's the best approach otherwise. Have you received any feedback from anyone else on this yet?

**Re: All Other** Spending: based on my conversations with our PAC reviewers in RAD, I would lump these lines into All Other for non-Connected PACs: 22, 25, 26, 27, 28, and 29 (include  @lbeaufort 's concern regarding transfers is valid, but I think we're OK lumping Transfers in with All Other for Non-Connected Organizations. I don't see them making transfers.  Laura's concern about transfers is particularly important if we're going to make a one size fits all request for lumping expenditure categories together. The All Other Spending categories of expenditures would have to change depending on the committee type, especially if we expand this to Party, Candidate, JF.

**Comment by JonellaCulmer** [comment]
@bmathesonFEC Thanks, Brad, for taking a look. That's a great idea to link to the committee's profile page. 

I haven't received any other feedback regarding the default state. Right now, I'm stumped. We can chat when you're next free or we can talk tomorrow in design sync. 

And thank you for clarifying the expenditure lines!

**Comment by JonellaCulmer** [comment]
@AmyKort @dorothyyeager @bmathesonFEC Want to double check that the language used is good to go. Especially based on @patphongs's comment in the Invision mockup regarding the header. Do we need to make it more clear at the outset that we're talking about a specific type of PAC? So should the header read: Compare nonconnected PAC spending (with a glossary link). 

<img width="830" alt="screen shot 2019-02-28 at 11 33 00 am" src="https://user-images.githubusercontent.com/31663028/53582130-e52d1100-3b4c-11e9-89a4-cf7ae4e498fd.png">

**Comment by dorothyyeager** [comment]
For the header:
- Instead of a glossary link - it needs to link to one of those two H4CC pages in my last comment.
- I would say "Compare nonconnected political action committee spending"

About transfers - nonconnected PACs that do shared fundraising between federal and nonfederal accounts must allocate. Unless they're paying it 100% federal, there would be reportable transfers. This comment assumes they are following those rules. I'm not sure there's a lot of those transfers happening, but that's the legal requirement that would trigger them having to make a transfer. For our purposes with this chart, I think it's fine to put them in "all other" since the transfers are caused by FEC allocation accounting rules and you're just moving money between committee accounts. The federal account will report spending for allocated fundraising on Schedule H4 for Line 21a.

For the little sign in red, suggest changing the first sentence to "You entered a committee ID that is not assigned to a nonconnected PAC" - that could link to one of the pages I mentioned above or to the glossary.

**Comment by dorothyyeager** [comment]
Just read @Laura's comment above and clicked her link. Those large transfers are being made by leadership PACs acting as joint fundraising committees and basically thus would be transfers of money raised, so I agree with her, including that would be confusing. 

Basically, transfers are really just moving the money around, not spending it on something tangible. Yes, they left the account, but the money ended up in an affiliated entity's account.

**Comment by dorothyyeager** [comment]
One last thought: perhaps change "and" to "with" since I think "compare X with y" reads better?

**Comment by JonellaCulmer** [comment]
@dorothyyeager I don't know about linking to something other than the glossary when clicking on the book icon. I also wouldn't include any other icon mid-text in a header. And we don't hyperlink headers. My suggestion for that link would be to place that link in the methodology or add new text to the bottom of the chart similar to the candidate comparison's table on the election profile pages. Example below: 
<img width="959" alt="screen shot 2019-02-28 at 1 26 57 pm" src="https://user-images.githubusercontent.com/31663028/53589139-94251900-3b5c-11e9-9ba0-9f67ea820809.png">

**Comment by AmyKort** [comment]
The text underneath the chart seems like a good option.

**Comment by dorothyyeager** [comment]
I like the idea of the text at the bottom of the chart. Maybe a sentence saying: 
_Learn more about the different types of nonconnected PACs_ (Link to https://www.fec.gov/help-candidates-and-committees/registering-pac/types-nonconnected-pacs/ (Types of nonconnected PACs) _and how they vary from other types of political committees_ (Link to https://www.fec.gov/help-candidates-and-committees/registering-pac/understanding-nonconnected-pacs/).

**Comment by AmyKort** [comment]
I like your sentence.

**Comment by JonellaCulmer** [comment]
Thanks @dorothyyeager. If I might make a suggestion about the sentence. I'd like to address the table in that sentence too. How about something like this:

This table only shows spending for nonconnected PACs. Learn more about nonconnected PACs and how they vary from other political committees. 

![screen shot 2019-02-28 at 3 09 42 pm](https://user-images.githubusercontent.com/31663028/53595315-ed944480-3b6a-11e9-818d-453ec512d102.png)

**Comment by dorothyyeager** [comment]
Makes sense to me! @JonellaCulmer

**Comment by JonellaCulmer** [comment]
At design sync today, we decided we were going to include a default state of the top two spending nonconnected PACs. This may require additional backend work in order to display these top two spenders. When a user moves to edit the committees both of the default committees are removed.

**Comment by JonellaCulmer** [comment]
@dorothyyeager @AmyKort @kathycarothers @bmathesonFEC 
Just remembered we still need definitions for the rollover tooltips next to each of the expenditure types. These need to be very short and concise and convey what kinds of expenditures are included for each type. More specific detail that goes into each of these lines (form #, line #, definition) can be found in the methodology. 

What I have below is really rough, but what I'm hoping we can aim for. Short and sweet and gets to our legal definitions without getting us into trouble.

**Tooltips:**
Operating expenditures: Rent, overhead, travel, advertising, equipment, etc.
Contributions to candidates/committees: anything of value given, or payment of services not charged to the committee...?
Independent expenditures: Independent communications such as advertising,....?
All other spending: transfers, loans made, loan repayments, contribution refunds, FEA, etc.

**Comment by kathycarothers** [comment]
I think we might pull from the definitions from the glossary and conferences, since that language has  been used already. Are you looking to give just examples or to incorporate examples into the definition? Sorry I just need some clarification. 

For example:

Operating expenditures: A committee's day-to-day expenditures for items such as rent, overhead, 
administration, personnel, equipment, travel, etc. 

Contribution:  Generally, anything of value given to influence an election, which includes gifts, in-kind contributions (goods or services), loans and extensions of credit. 

Independent expenditures: I don't think we can make to short and sweet. I would say to pull from the conference outline. 

Expenditure for communication that "expressly advocates" the election or defeat of a clearly identified candidate and that is not made in cooperation with , or at the request or suggestion of, the candidate or his/her campaign or its agents, or a political party or its agents. Examples include billboards and newspaper and radio/tv ads. 

All other spending: I need to think about.

**Comment by dorothyyeager** [comment]
Agree with @kathycarothers - IEs are very specifically defined in the statute. The regs pull from that, the conference outlines just quote it directly and OGC approved what's in our glossary.

For operating expenditures, you need to add "and fundraising" and then you match the glossary and the regs.

For contribution: how about this:

A gift, subscription, loan, advance or deposit of money or anything of value given to influence a federal election, including goods or services provided at less than the usual/normal charge.

For other spending: I like the idea of just listing the categories on the Form 3X, but maybe add, "see Form 3X instructions for specific descriptions of these categories."

What do you think @AmyKort?

**Comment by JonellaCulmer** [comment]
Trying to cut the fat wherever possible, please see the suggestions below:

- Operating expenditures: Day-to-day expenditures such as rent, overhead,
administration, personnel, equipment, travel, etc.

- Contribution: Generally, anything of value given, which includes gifts, subscriptions, in-kind contributions (goods or services), loans and extensions of credit.

- Independent expenditures: Communication that "expressly advocates" the election or defeat of a clearly identified candidate, is not made in cooperation with, or at the request or suggestion of, the candidate or his/her campaign or its agents, or a political party or its agents, such as billboards and newspaper and radio/tv ads.

- All other spending: Total for all transfers, loans made, loan repayments, contribution refunds, FEA, etc.

cc: @AmyKort @dorothyyeager @kathycarothers

**Comment by AmyKort** [comment]
I think we need to stay as close as we can to the legal definitions, especially with regards to contribution and Independent expenditure. 

 @dorothyyeager and @kathycarothers

**Comment by JonellaCulmer** [comment]
@AmyKort What do you think about creating a glossary term for "All other spending"? I think we're really pushing the limits on what would make a tooltip helpful by including full definitions in there.

**Comment by PaulClark2** [comment]
@JonellaCulmer @AmyKort would we use "all other spending" anywhere else? Can we define it in the methodology and not in the tool tip. Maybe the tool tip just says see methodology. I know that's not the friendliest thing but I'm not sure "all other spending" belongs in the glossary unless we are going to use that combination of F3X disbursement lines in other places.

**Comment by AmyKort** [comment]
I agree with @PaulClark2 . Also, (checking with @dorothyyeager ) I think we've kept our glossary to FECA terms as much as possible.

**Comment by JonellaCulmer** [comment]
Can we just include examples in the tooltip and link to glossary for full definition?

**Comment by AmyKort** [comment]
I like it!

**Comment by dorothyyeager** [comment]
I'm not sure that will work @JonellaCulmer - some of the lines/categories (like FEA) have a long thing in the glossary and some have nothing in the glossary. Plus they are all something different. 

I like @PaulClark2's idea of see methodology. That way we can elaborate there on each line and what it is.

**Comment by PaulClark2** [comment]
Another concern is this "all other spending" would only apply to PACs. Do we create "all other spending for parties and another one for candidate committees?

**Comment by JonellaCulmer** [comment]
I mean link to the glossary for the first three. All other spending would just list the lines/expenditures. That can link to/point to methodology.

**Comment by dorothyyeager** [comment]
Ah! That makes sense @JonellaCulmer for PACs. For the methodology, a good source for what to say about them might be the Form 3X instructions.

I think Paul is right that the "all other spending" group changes for parties and for candidates.

**Comment by JonellaCulmer** [comment]
Updated suggestion: @dorothyyeager @AmyKort @PaulClark2 @kathycarothers 

- Operating expenditures: Rent, overhead,
administration, personnel, equipment, travel, etc. See full definition. (link to glossary)

- Contribution: Anything of value given, including gifts, subscriptions, in-kind contributions (goods or services), loans and extensions of credit. See full definition. (link to glossary)

- Independent expenditures: Communication such as billboards and newspaper and radio/tv ads. See full definition. (link to glossary)

- All other spending: Total for all transfers, coodinated party expenditures, loans made, loan repayments, contribution refunds, FEA, and other disbursements. See methodology. (link)

**Comment by kathycarothers** [comment]
By George I think we've got it. I may be showing my age with this line:)

**Comment by dorothyyeager** [comment]
I like the approach @JonellaCulmer but the IE definition needs a pinch more. What really makes an IE is the combo of ad with express advocacy that is not coordinated. So how about "An express advocacy communication (such as an ad) that is not coordinated with a candidate or party. See full definition."

**Comment by AmyKort** [comment]
I agree with @dorothyyeager . Also, I think the definition of contribution has the same problem.

"A gift, subscription, loan, advance or deposit of money or anything of value *given to influence a federal election; or the payment by any person of compensation for the personal services of another person if those services are rendered without charge to a political committee for any purpose.* 11 CFR 100.52(a) and 100.54."

**Comment by JonellaCulmer** [comment]
@dorothyyeager Thanks for that edit! Do you mind taking a look at the contributions definition too and seeing where we can trim there? The length of the IE definition is about as long as I think we should go for a tooltip.

**Comment by dorothyyeager** [comment]
How does this work? @JonellaCulmer @AmyKort To me, the "to influence a federal election" is more important legally than the examples of anything of value, and the part Amy put in italics is an "or" so the concept must be included in tool tip.

"Contribution: Anything of value given to influence a federal election, or payment of compensation for personal services rendered without charge. See full definition and examples. (link to glossary)"

**Comment by JonellaCulmer** [comment]
How about: "Anything of value given to influence a federal election, or payment for services rendered without charge. See full definition. (link to glossary)

@dorothyyeager @AmyKort

**Comment by dorothyyeager** [comment]
I think you need "of compensation" after payment (or the sentence doesn't make sense and doesn't match the law).

**Comment by JonellaCulmer** [comment]
The PAC spending chart mockup has been updated following a conversation on the use of our tooltips and the information contained within. We're opting to include the full legal definitions found on form 3X as the definitions and explainer text for the different lines. 

We plan to test the usability of the chart, including the effectiveness and usability of the line definitions being shown in the methodology and whether or not users know to look there. This will also help us gauge the usefulness of the methodology feature for other data visualizations currently employed.

<img width="934" alt="screen shot 2019-03-05 at 1 10 57 pm" src="https://user-images.githubusercontent.com/31663028/53827231-9d412c00-3f48-11e9-8ed4-b3640054865f.png">

**Comment by JonellaCulmer** [comment]
Closing this issue in favor of usability testing ticket, here: https://github.com/fecgov/fec-cms/issues/2710
