### ISSUE TITLE
Update site to reflect new Admin Fine penalties for 2019

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2627]
**User story** As a filer (or a stakeholder or a consultant), I need to know that there are automatic penalties for late/non-filed reports, and that the law for those penalties has been extended.

**Background** 
 Revised rules published on December 27, 2018 update the penalties for certain FECA violations. We need to update admin fine pages accordingly.

**To do:**
- [x] Update the regulations page (https://www.fec.gov/legal-resources/regulations/) and the main admin fine page (https://www.fec.gov/legal-resources/enforcement/administrative-fines/) to add the new rules
- [x] Update the admin fines page at (https://www.fec.gov/legal-resources/enforcement/administrative-fines/calculating-administrative-fines)/ to reflect updated penalties published at 83 FR 66596 (12/27/2018) (- @patphongs for hard coded changes)
- [x]  Publish new calculator for 2019 (in transition at https://transition.fec.gov/af/afcalc_20190101.shtml) and update the previous calculator page to show the ending period (in transition at https://transition.fec.gov/af/afcalc_20171228.shtml)

**Comment by dorothyyeager** [comment]
As I'm working through the content edits sent by Admin Fine office, I'm updating the completion criteria to reflect the steps we need to take for this task. Look forward to this getting off transition one day!

**Comment by patphongs** [comment]
Thanks @dorothyyeager! The new calculator pages have been published to transition production. Everything looks like it's done, so I'm closing this issue.
