### ISSUE TITLE
Prevent users from clicking past the end of the line chart

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2632]
As of 1/29/19, users can click past the end of the line chart and get to a blank chart with incorrect dates and numbers (see screenshots). This can be seen when clicking forward and backward buttons in the timeline. We should prevent users from clicking past the end of the line chart.

# Before
<img width="985" alt="screen shot 2019-01-29 at 10 39 45 am" src="https://user-images.githubusercontent.com/31420082/51919853-47f68580-23b2-11e9-9eb3-b30a2a372d2f.png">

# After clicking right
<img width="985" alt="screen shot 2019-01-29 at 10 39 57 am" src="https://user-images.githubusercontent.com/31420082/51919896-5b095580-23b2-11e9-99b1-71daa1605a66.png">

**Comment by johnnyporkchops** [comment]
As of 01/31/19, the map does what we would expect and returns data for Jan 19. 
Per discussion on standup:
Waiting to hear from @PaulClark2 and @AmyKort as to wether we want to either:
A) limit map to 2018 until we are sure there is sufficient data available
B) Leave it as it, but make sure to change the hardcoded `DEFAULT_TIME_PERIOD = 2018`  to 2019
https://github.com/fecgov/fec-cms/blob/125e190f3485427190a13f48dbf7429afc3c10fd/fec/data/constants.py#L8

**Comment by patphongs** [comment]
Discussed during stand-up, we will leave 2018 as the default time period for now until more data comes in during future filings. Moving this to new issues for now until PI 9 to revisit.
