### ISSUE TITLE
Update DEFAULT_TIME_PERIOD to 2020 

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#2640]
In order for data to  reflect current time period, we need to update this hardcoded constant.
https://github.com/fecgov/fec-cms/blob/125e190f3485427190a13f48dbf7429afc3c10fd/fec/data/constants.py#L8

Double check that the line charts are also updated with this change:  #2632, https://github.com/fecgov/fec-cms/issues/2838

**Comment by lbeaufort** [comment]
Looks like there are two places     
```
DEFAULT_TIME_PERIOD 
START_YEAR
END_YEAR
```

Are getting set. Should we at least set this as an `env var`?

**Comment by patphongs** [comment]
Here's the PR that may have originated the `DEFAULT_TIME_PERIOD`. May be good to take a look at for context: https://github.com/fecgov/openFEC-web-app/pull/1822

**Comment by lbeaufort** [comment]
Thanks @patphongs! Can we consider just adding 2 to `DEFAULT_TIME_PERIOD` for `END_YEAR`?
