### ISSUE TITLE
Rethink rollover to new cycle data "Mind the gap"

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2648]
Rethink rollover to new cycle data (cc: @PaulClark2)

- Inventory where we've hard-coded or calculated default timeframes in both: transaction data, line charts (these have data for candidate committees and pac/party committees), candidate pages, committee pages
- Consider padding the `delayed_start` timeframe on candidate committee page rollover
- Think about the types of reporting schedules that come into play 

Outcome:
- [ ] Make a strategy for handling two-year period rollover better
- [ ] Create implementation tickets based on this strategy

**Comment by AmyKort** [comment]
@PaulClark2 What do you want to do with this?

**Comment by PaulClark2** [comment]
@lbeaufort can we close this for now in favor of changing the default year/cycle to 2020? We can revisit this later. 

For example this, https://github.com/fecgov/fec-cms/issues/2838, and perhaps others.

**Comment by lbeaufort** [comment]
It makes sense to me to keep the goal of a larger strategy in mind while working on the specific tasks. I’ll go ahead and close this issue
