### ISSUE TITLE
Update AF links on /legal-resources/enforcement/ AND /legal-resources/enforcement/administrative-fines/

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#2650]
Upon deploying release with new Admin Fines pages, update AF links (in Wagtail ) to the AF case-search page on:
https://www.fec.gov/legal-resources/enforcement/ 
https://www.fec.gov/legal-resources/enforcement/administrative-fines/
![admin-_fines_link1](https://user-images.githubusercontent.com/5572856/52140254-4631f980-2620-11e9-8b13-3ea4bb15b4f5.jpg)
![admin-_fines_link](https://user-images.githubusercontent.com/5572856/52140255-4631f980-2620-11e9-943d-67946663b60c.jpg)

**Comment by johnnyporkchops** [comment]
This is blocked, awaiting stakeholder review.

**Comment by dorothyyeager** [comment]
Taking myself off this issue for now so I don't get confused. I can be reassigned when we're ready to work on it.

**Comment by JonellaCulmer** [comment]
This is done. So closing.
