### ISSUE TITLE
Research: Gather approved resources for use in possible future presidential section of H4CC

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2651]
**User story** During a presidential election cycle, candidates and the interested public need to know the federal campaign finance rules that apply to presidential candidates.

**Background**
We've long wanted a section for presidential candidates, similar to the one for House and Senate candidates, but also capturing the unique topics and quirks that apply to only presidential candidates (for example, a four year election cycle, application of limits to the primary season, use of Form 3P, and public funding for those who qualify and opt to live under spending limits).

**Known resources**

- The introduction to the [Campaign Guide for Congressional Candidates](https://www.fec.gov/resources/cms-content/documents/candgui.pdf#page=5) (containing Commission-approved language) notes that much of it also pertains to presidential candidates that do not take public funding. (We'd need to identify which pages in H4CC contain that approved language already.)
- The page on presidential elections in our citizens section ([https://www.fec.gov/introduction-campaign-finance/understanding-ways-support-federal-candidates/presidential-elections/](url).) 
- Linked from that page above, the public funding information at https://www.fec.gov/introduction-campaign-finance/understanding-ways-support-federal-candidates/presidential-elections/public-funding-presidential-elections/.

**Completion criteria**
- [ ] Identify and make a list of the other resources we might have for approved language we could use for this section.

**Comment by bmathesonFEC** [comment]
Added to google drive:
- Public funding brochure
- classic.fec.gov press FAQ for public funded committees
- Form 3P instructions
- Legal guidance for Presidentials (AOs, MURs, etc.) -- last updated in 2016

More docs to be added. @dorothyyeager suggested that we inventory the candidate guide pages to find content that is relevant for presidential committees.

**Comment by bmathesonFEC** [comment]
Added: 

- RAD FAQ (plenty of F3 - F3P crossover here)
- Resources from current fec.gov (Introduction to campaign finance)
