### ISSUE TITLE
Upgrade Node.js

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#2653]
We should start looking at upgrading our version of Node.

We're currently running Node.js version 8.9.1, which has just moved into maintenance mode.

The current version is 11.9.0 and 12.0.0 is just a few months away ([release schedule](https://github.com/nodejs/Release)).

Follow-up tasks:
- [ ] Update installation scripts
- [ ] Update onboarding documentation

**Comment by xhanchoLee** [comment]
Question... I'm trying to find where Node Js lives/resides on my mac.   I figured out that my Python3.7 resides in my mac in  "/Volumes/Library/Frameworks...."  until i get to the "bin, lib and other folders" with files that allow python to run on my environment.... Does Node Js have a similar file structure with files.ext somewhere in my mac? Please shed some light on the topic if you can. thanks.

**Comment by rfultz** [comment]
Thanks for checking out our repo @xhanchoLee!

You're not alone in wondering that—I know I did!

I'm not sure what your system configuration is like but there are lots of search results for [questions like this](https://github.com/nodejs/help/issues/915). Good luck!

> Question... I'm trying to find where Node Js lives/resides on my mac. I figured out that my Python3.7 resides in my mac in "/Volumes/Library/Frameworks...." until i get to the "bin, lib and other folders" with files that allow python to run on my environment.... Does Node Js have a similar file structure with files.ext somewhere in my mac? Please shed some light on the topic if you can. thanks.

**Comment by xhanchoLee** [comment]
Thanks for the guidance :)

**Comment by rfultz** [comment]
Related to this: [#2681](https://github.com/fecgov/fec-cms/issues/2681)

**Comment by rfultz** [comment]
This branch is now on the feature space
