### ISSUE TITLE
[Low] Snyk: Prototype Pollution

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/fec-cms#2659]
https://app.snyk.io/org/fecgov/project/2a97cddb-4b62-4d54-b18f-3b85d55a5e10
**Vulnerable module:** lodash
Introduced through: babel-preset-latest@6.24.1, babelify@7.3.0 and others

**Detailed paths and remediation**
Introduced through: fec-cms@1.0.0 › babel-preset-latest@6.24.1 › babel-preset-es2015@6.24.1 › babel-plugin-transform-es2015-modules-umd@6.24.1 › babel-plugin-transform-es2015-modules-amd@6.24.1 › babel-plugin-transform-es2015-modules-commonjs@6.26.2 › babel-template@6.26.0 › babel-traverse@6.26.0 › babel-types@6.26.0 › lodash@4.17.10
Remediation: Your dependencies are out of date, otherwise you would be using a newer lodash than lodash@4.17.10. Try reinstalling your dependencies. If the problem persists, one of your dependencies may be bundling outdated modules.
Introduced through: fec-cms@1.0.0 › babel-preset-latest@6.24.1 › babel-preset-es2015@6.24.1 › babel-plugin-transform-es2015-classes@6.24.1 › babel-helper-define-map@6.26.0 › babel-helper-function-name@6.24.1 › babel-template@6.26.0 › babel-traverse@6.26.0 › babel-types@6.26.0 › lodash@4.17.10
Remediation: Your dependencies are out of date, otherwise you would be using a newer lodash than lodash@4.17.10. Try reinstalling your dependencies. If the problem persists, one of your dependencies may be bundling outdated modules.
Introduced through: fec-cms@1.0.0 › babel-preset-latest@6.24.1 › babel-preset-es2017@6.24.1 › babel-plugin-transform-async-to-generator@6.24.1 › babel-helper-remap-async-to-generator@6.24.1 › babel-helper-function-name@6.24.1 › babel-template@6.26.0 › babel-traverse@6.26.0 › babel-types@6.26.0 › lodash@4.17.10
Remediation: Your dependencies are out of date, otherwise you would be using a newer lodash than lodash@4.17.10. Try reinstalling your dependencies. If the problem persists, one of your dependencies may be bundling outdated modules.

**Comment by patphongs** [comment]
Dependencies have been reinstalled, this no longer shows up as a vulnerability
