### ISSUE TITLE
Inventory of Wagtail pages that need annual updates

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2670]
**User story**
As a user, I need to know the latest limits and get the latest versions of things.

**Background**
@kathycarothers and I just updated the site for 2019-2020 index and limit adjustments. Our snippet for contribution limits was handy. There are a number of pages though, that had random references to various limits, and/or links to videos that are updated annually or every two years. We realized we really need to make a list of these places for ease in future updates.

Completion criteria:
- [x] Make list of videos and where they are linked on Wagtail
- [x] Update our document of snippets to note random pages with text needing updating.
- [x] Make a list of H4CC pages linking Record articles for when those articles need updating

**Comment by kathycarothers** [comment]
Below is the link to the master document for pages that reference the contribution limits. This document includes pages with articles, text, snippets and videos.

https://docs.google.com/document/d/1A_qyq7sSYpafxaVKDzqYknBxqjE2CFSl7BBIX7qXaW0/edit

**Comment by dorothyyeager** [comment]
We've got a spreadsheet set up for the video and article inventory at https://docs.google.com/spreadsheets/d/164phGPvSHgvneNJUIV2WogMYl7MnDX5n0d2dIFNn9y8/edit?usp=sharing

**Comment by dorothyyeager** [comment]
Closing this issue as we've completed the inventory. See the spreadsheet linked in comment right above for the complete inventory.
