### ISSUE TITLE
Update Election Data and other pages that are linking to the wrong pages for 2019-2020 deadlines

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2671]
**What we're after**
I'm using the "compare candidates" pages, and noticed the links to the various dates and deadlines pages. The top box is correct. However, when clicking the buttons for specific items after each section, they are pointing to transition pages for 2020. Starting with this year, we are no longer putting these pages in transition, and instead are using Wagtail pages, so those links need to be changed as they return a 404.

For an example, see https://www.fec.gov/data/elections/president/2020/. However, every single page that comes out of this for 2020 most likely needs modification (or the template that generates these pages).

![image](https://user-images.githubusercontent.com/24437369/52441372-69f8b200-2aee-11e9-8263-7e5389f08bfb.png)
This button needs to point to https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/ 

![image](https://user-images.githubusercontent.com/24437369/52441453-9b717d80-2aee-11e9-9a87-7c3f23025ef2.png)

This button needs to point to https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/2019-reporting-dates/24-and-48-hour-reports-independent-expenditures-2019-20/ (or alternatively, you could just point to dates and deadlines and not have to edit the link each year).

![image](https://user-images.githubusercontent.com/24437369/52441504-c6f46800-2aee-11e9-9289-fd55f927fd92.png)
This button needs to point to https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/2019-reporting-dates/electioneering-communications-periods-2019/  (or alternatively, you could just point to dates and deadlines and not have to edit the link each year).

Likewise, there are many pages reference the compliance map; however, the map was not updated for 2019 and older links to it just return a dead map. The Dates and deadlines page has the same information, and contains archived information for past years.

**To do:**
- [ ] Replace the hard-coded links at the bottom of the election data pages to link to the Dates and Deadlines page at https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/ - front end work
- [x] Links to the Compliance Map (https://transition.fec.gov/info/ElectionDate/index.shtml) and its subdirectories and files within (/info/ElectionDate/) from past years should be redirected to  https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/ (Front end or content team work) - This work has been moved to #2699

**Comment by dorothyyeager** [comment]
Spoke with @rfultz and we'll pair on the compliance map redirect as part of the content team's redirect work in 8.3 #2699 so I'll add that part to that ticket and check that tickbox above.

**Comment by patphongs** [comment]
merged in PR, closing
