### ISSUE TITLE
Update 404 page/message

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#2675]
Our 404 page still mentions 18F, that we're redesigning our site, and suggests users search classic.fec.gov. Should it?

https://www.fec.gov/404test/

> ## Page not found
> Sorry, we couldn't find the page you're looking for.
> 
> FEC.gov is in the middle of a redesign. We've worked hard to keep our URLs up to date, but please let us know if you think something is missing or broken. We're available by [email](mailto:webmanager@fec.gov) or [GitHub](https://github.com/18f/fec).
> 
> [Return home](https://www.fec.gov/)
> 
> Or try searching an archive of the [old FEC.gov design](http://classic.fec.gov/).

**To do**
- [ ] Draft new message wording

**Future work**
- [x]  Implementation ticket for front-end updating of the page.

**Comment by AmyKort** [comment]
Thanks for catching that @rfultz . Let's let the content team take a crack at re-wording this message. And the GitHub link should be https://github.com/fecgov/FEC .

**Comment by dorothyyeager** [comment]
I've drafted an update that I'm going to run past folks in Design Sync today. After the wording's approved, will close this ticket and put in one for the front end work.

**Comment by dorothyyeager** [comment]
Here's what we've wordsmithed: 

> Page not found
> Sorry, we couldn't find the page you're looking for.
> 
> We work hard to keep our URLs up to date, but please let us know if you think something is missing or broken. Use the feedback box on the bottom of any page or contact the FEC (link the contact page)

cc: @AmyKort @bmathesonFEC @patphongs - let me know if we're good to go or if more edits are needed. We will work making this page an editable Wagtail page into the upcoming front-end work ticket.

**Comment by dorothyyeager** [comment]
Everyone is good to go (Thanks!). Closing and we're ready to move on to front-end work in #2693
