### ISSUE TITLE
Transition pages to take down (8.4)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2676]
**What we're after**
Now that some redirects are in place after the last few sprints, it's time to take down the old transition and classic pages.

**To do**
Remove the following pages from the transition site: (These were redirected in previous sprints)
- [x] /elecfil/electron.shtml
- [x] /elecfil/ef_overview.shtml
- [x] /elecfil/FECFileIntroPage.shtml
- [x] /elecfil/software.shtml
- [x] /info/election_day_links.shtml
- [x] /info/guidance/recountreporting.shtml
- [x] /law/litigation/citizens_guide_brochure.pdf
- [x] /law/policy/enforcement/publichearing011409.shtml
- [x] /pages/brochures/electioneering.shtml
- [x] /pages/brochures/ec-brochure.pdf
- [x] /pages/hearings/internethearing.shtml
- [ ] /pages/brochures/indexp.shtml 
- [x] /pages/brochures/ie_brochure.pdf
- [x] /pages/brochures/public_funding_brochure.pdf
- [x] /pages/brochures/public_funding_brochure2012.pdf
- [x] /pages/brochures/saleuse.shtml (Note - bottom of data pages still link to transition site version. Redirect is working but that link should be updated.)
- [x] /pdf/eleccoll.pdf
- [x] /support/index.shtml

**Comment by johnnyporkchops** [comment]
@dorothyyeager , These pages have been deleted from transition.  The only file we could not find was/ `pages/brochures/indexp.shtml`. There was a an image file /pages/brochures/indexp.gif--Was that the one you wanted removed by any channce?

**Comment by dorothyyeager** [comment]
@johnnyporkchops Thanks! That's good if it can't be found. It was very very outdated! It may have been in an earlier removal ticket and I may not have realized it. 

The related image file can be removed too (or if you want to close the ticket out, I can just add it to the list for the next sprint).

**Comment by johnnyporkchops** [comment]
`/pages/brochures/indexp.gif` has been  removed
