### ISSUE TITLE
Update raising/spending by the numbers pages

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2678]
**What we're after:**
We are updating the raising/spending by the numbers pages to use election years instead of two-year periods. This will update the office breakdown page aggregates to display by election years as well. This is already a part of the /candidates/totals endpoint.

**Completion criteria:**
- [x] Change bar chart header to "Top raising candidates" and "Top spending candidates"
- [x] Remove two-year period search filter. Create election year single-select dropdown filter to the right of the "How much has been raised by" dropdown filter, with the text "Running in:"
- [x] Change the API calls to query `election_full=true` , `cycle` and `election_year`, and `active_candidates=true`, (example call: https://api.open.fec.gov/v1/candidates/totals/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&election_year=2020&cycle=2020&election_full=true&active_candidates=true&sort=-receipts&per_page=30&page=1&office=P)
- [x] Change left nav text for bar charts from "Who's raising the most" to "Top raising candidates"
- [ ] Create new section above bar charts that show the aggregate total for all candidates (by office) raising and spending. 
- [x] Create button linking to the opposite page, (Raising page button links to Spending page and vice versa), and place below the left nav
- [x] Remove PACs and Parties from among the options in the dropdown for "How much has been raised by" and "How much has been spent by"
- [x] Update methodology language for both charts. Language below:

**Raising methodology:**
This chart includes data up to and including the most recent report filed by each campaign. It displays an overall total for the selected office and also displays totals for individual candidate's campaigns.

The overall total is the sum of the total receipts of the campaign committees of all candidates for the selected office.

Candidates are displayed in descending order of total receipts. Total receipts are the sum of all contributions and other receipts received by the candidate’s authorized committees: two-year cycles for House candidates, four-year cycles for presidential candidates and six-year cycles for Senate candidates.

The form and line used to calculate candidate campaign total receipt sums are:

* Presidential campaigns: Form 3P, Line 22, Column A
* Senate and House campaigns: Form 3, Line 16, Column A

**Spending methodology:**
This chart includes data up to and including the most recent report filed by each campaign. It displays an overall total for the selected office and also displays totals for individual candidate's campaigns.

The overall total is the sum of the total disbursements of the campaign committees of all candidates for the selected office.

Candidates are displayed in descending order of total disbursements, Total disbursements are the sum of all expenditures and other disbursements made by the candidate’s authorized committees: two-year cycles for House candidates, four-year cycles for presidential candidates and six-year cycles for Senate candidates.

The form and line used to calculate candidate campaign total disbursement sums are:

* Presidential campaigns: Form 3P, Line 30, Column A
* Senate and House campaigns: Form 3, Line 22, Column A

### Raising: by the numbers 
<img width="728" alt="screen shot 2019-03-05 at 2 27 08 pm" src="https://user-images.githubusercontent.com/31663028/53831453-ded6d480-3f52-11e9-8b0b-86f0790c3863.png">

### Spending: by the numbers
<img width="730" alt="screen shot 2019-03-05 at 2 27 32 pm" src="https://user-images.githubusercontent.com/31663028/53831468-e5654c00-3f52-11e9-9046-a11e25714ca2.png">

#2616 - Design issue

**Comment by JonellaCulmer** [comment]
This has been pushed up to feature for [testing](https://github.com/fecgov/fec-cms/issues/2710): 
https://fec-feature-cms.app.cloud.gov/data/raising-bythenumbers/
https://fec-feature-cms.app.cloud.gov/data/spending-bythenumbers/

**Comment by rfultz** [comment]
@patphongs, I've locked the agg totals behind a feature flag and spun that work off into #2744.
