### ISSUE TITLE
Org chart footnote has weird characters

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2679]
@llienfec commented on [Mon Feb 11 2019](https://github.com/fecgov/FEC/issues/8798)

On the [org chart](https://transition.fec.gov/about/offices/offices.shtml), footnote 1 has weird characters.  I tested in both IE and Chrome and see the same issue:

![image](https://user-images.githubusercontent.com/22914750/52575059-8d23aa00-2deb-11e9-9ae5-501f75db58cb.png)

- [ ] Make changes to org chart, see @AmyKort [comment below](https://github.com/fecgov/fec-cms/issues/2679#issuecomment-471560510).

**Comment by dorothyyeager** [comment]
Just a note that there are some changes since last time chart was updated - need to put in the new Chief Information Security Officer and also the new CFO who's starting on the 19th.

**Comment by AmyKort** [comment]
Great point @dorothyyeager . Let's see if we can catch all of these changes at once--I think the weird characters problem can wait a week.

**Comment by AmyKort** [comment]
@rhoughfec will ping us when we're ready to makes these changes.

**Comment by JonellaCulmer** [comment]
This ticket will proceed without all the changes needed on this page. We're going to work on the weird characters in this issue only.

**Comment by AmyKort** [comment]
For the org chart (https://transition.fec.gov/about/offices/offices.shtml)
CISO: Wenchun Jiang 
CFO: John Quinlan
Enforcement ASG: Charles Kitcher  (Acting)
Database Management: Rohan Jayasekera (Acting)

@johnnyporkchops @patphongs

**Comment by johnnyporkchops** [comment]
For future reference, org chart source files are on ntsrv1/DSDD/Web Admin/Applications and Updater Files/FEC Offices/
See notes on process to save with hi res

**Comment by dorothyyeager** [comment]
Weird characters somehow replaced em dashes. We've put the em dashes back in. @johnnyporkchops is going to update the org chart image with some employee changes and updates.

**Comment by JonellaCulmer** [comment]
The org chart has been updated with the correct names and the weird characters are gone, so closing.
