### ISSUE TITLE
PAC and party reporting examples Round 5 - Prep for Drafts (Language & Images)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2689]
To help PACs and party committees understand how to report campaign finance transactions, we will draft and post reporting examples that will go with the nonconnected, SSF, and party sections within Help for Candidates and Committees.

Prior work issues: #1751, #1752, #1753, #1754, #1864, #1865, #1866, #1933, #1934, #1935

**Completion criteria (8.4):**

- [x] Identify no more than 10 examples to include in this sprint.
- [x] Identify PAC reporting examples (and their F3X images) that can be reused for party examples.

Future work (8.5 - 8.6):

- [ ] Draft example (language only) using existing campaign guides.
- [ ] Draft image caption language when possible.
- [ ] Find links for FECFile videos, FECFile getting started manuals, and other resources to be included with the example.
- [ ] Compile text for images
- [ ]  Create images & review
- [ ] Team image edits and revisions
- [ ] RAD SME edits and revisions

**Comment by bmathesonFEC** [comment]
I would like to add a completion criteria to identify PAC reporting examples that can be brought into the Party report examples without edit.  Can we do that without creating new pages? Or does that create URL issues? (@dorothyyeager)

**Comment by dorothyyeager** [comment]
@bmatheson I think it's a good idea, but he reporting examples that are used do have URLs depending on which section they are in. So I do have an idea.

Reporting example URLs do have the section URL.
https://www.fec.gov/help-candidates-and-committees/**filing-ssf-reports/**operating-expenditures/
https://www.fec.gov/help-candidates-and-committees**/filing-pac-reports/**operating-expenditures/

Party ones would end up with https://www.fec.gov/help-candidates-and-committees/filing-political-party-reports/name of slug

**But** the images used in the examples don't. They are housed in Wagtail as separate .jpg files and not tied to any bucket. 

![image](https://user-images.githubusercontent.com/24437369/54384055-c741cf00-4669-11e9-88c0-e5800bf21a68.png)

They get inserted into the reporting example template and you'd make a "reporting example page" where you'd choose the "featured image" from that collection in Wagtail.

![image](https://user-images.githubusercontent.com/24437369/54384168-fce6b800-4669-11e9-869c-678c2297b164.png)

So my advice would be to add completion criteria to identify the Form 3X images already uploaded to Wagtail that could be re-used in a party example (which cuts out the image creation/approval part of the steps above).

**Comment by bmathesonFEC** [comment]
Thanks @dorothyyeager . That's too bad about the URLS, I figured that would be the barrier for full reuse. Glad you had idea for how to use some of the exisiting material. I'll make that part of the conversation with the Party folks down here.

**Comment by bmathesonFEC** [comment]
Added completion criteria " Identify PAC reporting examples (and their F3X images) that can be reused for party examples."

**Comment by dorothyyeager** [comment]
Just had one more thought - you'd need to be careful with it but there is a way to copy pages in Wagtail that might be helpful. That way you could copy over the content you want to reuse to get your new slug.

**Comment by bmathesonFEC** [comment]
Coordinated with RAD's party specialists to review PAC examples for applicability to Party Committees. They are also brainstorming 5-8 reporting examples that are key to an initial roll out of the Party Committee Reporting Example page.

**Comment by bmathesonFEC** [comment]
Party specialists identified all of the changes required to adapt existing PAC reporting examples. Checking back with them regarding new reporting examples required to kick off a party reporting example section.

**Comment by bmathesonFEC** [comment]
RAD Party specialists identified the following reporting examples that would need be included to publish a Party Reporting Example section:

Allocation
- Allocated Federal and Nonfederal Administrative Expenses (...) (Schedule H1)
- Allocation Ratios (Schedule H2)
- Transfers from Nonfederal Accounts for Allocated Federal/Nonfederal Activity (Schedule H3)
- Disbursements for Allocated Federal/Nonfederal Activity (Schedule H4)

Coordination
- Itemized Coordinated Party Expenditures Made by Political Parties (Schedule F)

Added to #2786.
