### ISSUE TITLE
[HIGH] Snyk - Arbitrary Code Execution (Due by 20190330)

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-cms#2690]
**Vulnerable module:**  static-eval

**Detailed paths:**
   Introduced through: fec-cms@1.0.0 › topojson@1.6.19 › d3-geo-projection@0.2.16 › brfs@1.6.1 › static- 
   module@2.2.5 › static-eval@2.0.0

**Remediation:**
Upgrade static-eval to version 2.0.1 or higher.

**Comment by patphongs** [comment]
This got taken care of during a recent node upgrade PR: https://github.com/fecgov/fec-cms/pull/2733/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R62
