### ISSUE TITLE
[Med] Snyk - Uncontrolled Memory Consumption

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-cms#2691]
**Vulnerable module:** django

- Introduced through: django-jinja@2.4.1, cg-django-uaa@1.3.0 and others

**Detailed paths:**

- Introduced through: project@0.0.0 › django-jinja@2.4.1 › django@1.11.15
- Introduced through: project@0.0.0 › cg-django-uaa@1.3.0 › django@1.11.15
- Introduced through: project@0.0.0 › django@1.11.15

**Remediation:**
Upgrade django to version 1.11.19, 2.0.11, 2.1.6 or higher.

**Comment by jason-upchurch** [comment]
Current `django` is `django@1.11.20`. Vulnerability no longer appears.
