### ISSUE TITLE
Raising/Spending Bar charts break on candidates with "party":null

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#2694]
### Raising/Spending Bar charts "party":null issue:
Candidates with `"party": null` in their data break rendering from their number to the end of that page.

**Examples:**
- Raising Chart not showing items 11 through 20, for President- 2018. 
- Spending Chart not showing all items for 21 through 30 for President-2018
All ten candidates for each page show up in the data returned form the API, but not all are being rendered to the page:
**Spending Chart, President, 2018, page-3:**
https://api.open.fec.gov/v1/candidates/totals/?api_key=5yyI90SU3Xb73TVlv4wrEhQxYcCwMWCywQiGdYbJ&sort=-disbursements&per_page=10&sort_hide_null=true&cycle=2018&office=P&page=3

### FIX:  **Change line 170 of top-entities.js to this:**  
`party_code: (result.party===null) ? ' ' :'[' + result.party.charAt('0').toUpperCase() + ']' ,`

### Screenshots or error:

![screen shot 2019-02-24 at 2 47 40 am](https://user-images.githubusercontent.com/5572856/53296536-d6f29400-37de-11e9-8fae-1e8f4a8e0c87.png)

<hr>

![screen shot 2019-02-24 at 3 02 11 am](https://user-images.githubusercontent.com/5572856/53296758-f4c0f880-37e0-11e9-9ea5-2ec5ecff0de8.png)

**Comment by patphongs** [comment]
This ticket has been completed, hotfix was deployed: https://github.com/fecgov/fec-cms/pull/2703
