### ISSUE TITLE
Identify portions of H4CC candidate guide that would work for presidential guidance too

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2698]
**User story**
During a presidential election cycle, candidates and the interested public need to know the federal campaign finance rules that apply to presidential candidates.

**Background**
We've long wanted a section for presidential candidates, similar to the one for House and Senate candidates, but also capturing the unique topics and quirks that apply to only presidential candidates (for example, a four year election cycle, application of limits to the primary season, use of Form 3P, and public funding for those who qualify and opt to live under spending limits).

In #2651 we gathered the materials we have specific to presidential elections. This task is to identify pages or portions of the House/Senate candidate section which would also work for presidential candidates. This will help us make decisions about how we are presenting information to Title 26 (publicly funded) committees vs. Title 52 ones. It will also help us in our planning meeting #2697  This is work that could be done by staff in the Information Division with review by content team.

**To do**
- [x] Identify pages (or sections of pages) in https://www.fec.gov/help-candidates-and-committees/guides/?tab=candidates-and-their-authorized-committees that would be equally applicable to presidential candidates.

**Comment by dorothyyeager** [comment]
Info Division has assigned @prstoetzer to work with @bmathesonFEC on this.

**Comment by prstoetzer** [comment]
I have completed reviewing the content under the candidate section for applicability to Presidential candidates and committees. The results of my review are in \\ntsrv1\InfoProj\Presidential H4CC Guide

**Comment by bmathesonFEC** [comment]
Thanks @prstoetzer. The work you did helped us decided to roll up Presidential guidance into our current pages. We appreciate all of your organization and note taking.
