### ISSUE TITLE
Transition pages and files to take down (8.5)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2712]
**User story:** Our overall goal this PI for content is to reduce files on transition. Users don't need old outreach files or transition copies of PDFs that are on fec.gov's CMS.

**To do:**
- [x] Take down these image directories and files as the images in them are no longer needed.
/info/images/
/info/conference_materials/images/

- [x] Take down the files that were [redirected in 8.3](https://github.com/fecgov/fec-cms/issues/2699).

Info Division coordinated party limits pages:
/info/charts_cpe_2017.shtml
/info/charts_cpe_2016.shtml
/info/charts_cpe_2015.shtml
/info/charts_441ad_2014.shtml
/info/charts_441ad_2013.shtml
/info/charts_441ad_2012.shtml
/info/charts_441ad_2011.shtml
/info/charts_441ad_2010.shtml
/info/charts_441ad.shtml

Info Division FR notices:
/law/cfr/ej_compilation/2016/notice2016-01.pdf
/law/cfr/ej_compilation/2015/notice2015-01.pdf
/law/cfr/ej_compilation/2014/notice2014-03.pdf
/law/cfr/ej_compilation/2013/notice2013-03.pdf
/law/cfr/ej_compilation/2012/notice2012-02.pdf
/law/cfr/ej_compilation/2011/notice_2011-01.pdf
/law/cfr/ej_compilation/2010/notice_2010-02.pdf
/law/cfr/ej_compilation/2009/notice_2009-04.pdf
/law/cfr/ej_compilation/2008/notice_2008-04.pdf
/law/cfr/ej_compilation/2007/notice_2007-2.pdf
/law/cfr/ej_compilation/2006/notice_2006-03.pdf
/law/cfr/ej_compilation/2005/2005-7.pdf

Forms:
/pdf/forms/fecfrm1i.pdf
/pdf/forms/fecfrm1sf.pdf
/pdf/forms/fecfrm1m.pdf
/pdf/forms/fecfrm1mi.pdf
/pdf/forms/fecfrm2.pdf
/pdf/forms/fecfrm2i.pdf
/pdf/forms/fecfrm2sf.pdf
/pdf/forms/fecfrm3.pdf
/pdf/forms/fecfrm3i.pdf
/pdf/forms/fecfrm3post.pdf
/pdf/forms/fecfrm3posti.pdf
/pdf/forms/fecfrm3x.pdf
/pdf/forms/fecfrm3xi.pdf
/pdf/forms/fecfrm3p.pdf
/pdf/forms/fecfrm3pi.pdf
/pdf/forms/fecfrm3ppost.pdf
/pdf/forms/fecfrm3pposti.pdf
/pdf/forms/fecfrm3l.pdf
/pdf/forms/fecfrm3li.pdf
/pdf/forms/fecfrm4.pdf
/pdf/forms/fecfrm4i.pdf
/pdf/forms/fecfrm5.pdf
/pdf/forms/fecfrm5i.pdf
/pdf/forms/fecfrm6.pdf
/pdf/forms/fecfrm6i.pdf
/pdf/forms/fecform7.pdf
/pdf/forms/fecform7sf.pdf
/pdf/forms/fecfrm8.pdf
/pdf/forms/fecfrm8i.pdf
/pdf/forms/fecfrm9.pdf
/pdf/forms/fecfrm9i.pdf
/pdf/forms/fecfrm9sf.pdf
/pdf/forms/fecfrm13.pdf
/pdf/forms/fecfrm13i.pdf
/pdf/forms/ie_only_letter.pdf
/pdf/forms/noncontribution_letter.pdf

**Comment by rfultz** [comment]
@dorothyyeager, @patphongs and I just went through these. All gone!

**Comment by patphongs** [comment]
Thanks @rfultz ! Closing out this ticket as the work is now done 🎉
