### ISSUE TITLE
E&Js: Make the html tables used for the chronological index and publish the index once ready

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2723]
User story
As an internal stakeholder or outside legal consultant, I need to see the explanation and justification for Commission regulations to do proper legal analysis of them.

Background:
In previous issues, we worked on the citation index. The other main index for the E&Js is the chronological listing of them. (Currently these pages are linked at https://transition.fec.gov/law/cfr/ej_toc.shtml.) This process will work much like the citation index.

Work plan
We need to create the tables in word (done in #2568), update the links (done in #2617), turn into HTML blocks and then populate pages set up in Wagtail (done in #2722). This task is to convert the word tables into HTML blocks. ~~This is work that could be done by specialists in the Information Division with review by the content team.~~ Updated: We'll use coding from the pattern library for the tables, which is a little trickier so a content team member (me) will do it.

Completion criteria:
- [x] Convert the word tables into html blocks and insert into the draft pages made in #2722 
- [x] Link up the final pages on the index's introductory page
- [x] Content team review before publish
- [x] Publish the new pages
- [x] Once published, update the transition site to point to the new site and add to the redirect list.

**Comment by dorothyyeager** [comment]
The coding is done and the pages are ready to be reviewed and then published. Will send to the content team to get a second pair of eyes on all of it before publishing.

**Comment by dorothyyeager** [comment]
And we've got our second pair of eyes in @prstoetzer - thank you! He's reviewing them now.

**Comment by prstoetzer** [comment]
I have completed my review:

1.	The 1975 table style code was different from the other years and it was adding an extra line between the 1975 and 1976 sections and creating some formatting issues. I changed the code and everything looks good.
2.	The 1976 code had several extra <p> tags creating format inconsistencies. That has been corrected.
3.	The filename for the June 8, 1979 filename was incorrect. This has been corrected.
4.	1998 E&Js were in both the 1995 and 1998 sections and 1995 E&Js were not present. This has been corrected.
5.	The July 31, 1984 E&Js are out of order. 1984-13 is listed before 1984-11. I have not changed this in case these E&Js were deliberately presented in that order.

**Comment by dorothyyeager** [comment]
Thanks @prstoetzer - I really appreciate the thorough review and you fixing things you spotted! For #5: E&Js are sorted by date of publication, but if there's a tie, the tiebreaker is sorting by effective date. I'll see if that's what's up with those two 1984 E&Js. Again, many thanks!

**Comment by dorothyyeager** [comment]
Confirming that it is indeed the case with the two July 31, 1984 E&Js that they are in order of effective date.

**Comment by dorothyyeager** [comment]
The E&J chronological index has gone live! (On to the last task)

https://www.fec.gov/legal-resources/regulations/explanations-and-justifications/chronological-index-e-j-s/

**Comment by dorothyyeager** [comment]
I've updated the links in the transition site, put a few www redirects into Wagtail and slotted the transition and other redirects for 8.5 in our log for them. Work on this issue is completed, so closing.
