### ISSUE TITLE
Increase timeout on checking for downloads

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2731]
When exporting a data set, the CMS calls `/download/` every half second to check if the file is done. We should investigate increasing the timeout to reduce the load (and API calls for rate limiting) on the servers.

**Comment by lbeaufort** [comment]
@patphongs these are needed, but we should extend the timeout so they endpoint doesn't git hit so hard.

**Comment by lbeaufort** [comment]
Update - looks like it checks every 5 seconds. I'm investigating checking every 10 seconds.

**Comment by lbeaufort** [comment]
Update: after speaking with Paul and thinking about it, every 5 seconds is reasonable and any further performance improvements should be made on the API side.
