### ISSUE TITLE
H4CC: Create a new page in candidate receipts covering contributions received from affiliated committees

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2738]
Stakeholders noticed that the candidate receipts pages in H4CC do not address contributions received from affiliated committees.

**To do**
- [x] Take material (using approved language) from pages 18-19 of the Campaign Guide for Congressional Committees and turn into a Wagtail page.
- [x] Content team review of new page before publishing
- [ ] Once published, add the new page to the Taking in receipts index and link as "read next" where appropriate in the candidate section.

**Comment by kathycarothers** [comment]
The new page has been drafted and is ready for the content team to review before publishing.

**Comment by kathycarothers** [comment]
Dorothy from the content team has reviewed the page, and now the page has been sent for George to review.

**Comment by kathycarothers** [comment]
Published . Just needs to be linked in candidate receipts.

**Comment by kathycarothers** [comment]
The page has now been published to https://fec-prod-proxy.app.cloud.gov/help-candidates-and-committees/candidate-taking-receipts/ and the link for the page is https://fec-prod-proxy.app.cloud.gov/help-candidates-and-committees/candidate-taking-receipts/affiliation-and-contribution-limits/
