### ISSUE TITLE
Non-Filer filter for press releases not returning results

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2745]
The Non-filer filter for press releases is broken again. https://www.fec.gov/updates/?update_type=press-release&category=non-filer-publications

![image](https://user-images.githubusercontent.com/13237823/54452340-54009180-472b-11e9-9082-a778c0c2feeb.png)

**Comment by lbeaufort** [comment]
@rfultz I thought I fixed this with this commit: https://github.com/fecgov/fec-cms/pull/2528/commits/986ee49add3dfd9507f0d7b4d854419298de7945
