### ISSUE TITLE
Update Org Chart 

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2765]
We need to update the org chart to take "Acting" out of the Deputy CIO Operational Support title. 

![image](https://user-images.githubusercontent.com/13237823/54944520-0eea1580-4f0a-11e9-9dee-e7355021578f.png)

**Comment by johnnyporkchops** [comment]
Done:
https://transition.fec.gov/about/offices/offices.shtml
Make sure to clear cache, 
Also,  to verify, see:
https://transition.fec.gov/about/offices/fec_org_chart.jpg
