### ISSUE TITLE
Find new home for classic map explainers

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2770]
We need to find homes on the new website for these two explainers for the maps on classic. They should be accessible from the classic site, but need to live on the new site (either on transition or in wagtail).

H/S map 'What's included here" https://classic.fec.gov/press/HSMapHelp.shtml

Pres map: "What's included here"/"Candidates"/"Size of contributions" https://classic.fec.gov/press/mapHelp.shtml

- [x] Create wagtail pages (one for H/S map and one for the Pres. map) to provide explainer language that explain maps on the classic site

**Comment by dorothyyeager** [comment]
Similar explainers have been ported over into custom page templates within Wagtail. There's a section called Data that they can be child pages of. 

![image](https://user-images.githubusercontent.com/24437369/55171615-12221300-514f-11e9-84c8-eb800fdd118d.png)

**Comment by dorothyyeager** [comment]
Similar pages have been created in Wagtail. No need to create one in transition. A good place for the map explainers to live in Wagtail would be as child pages of the "Campaign finance data" section:
![image](https://user-images.githubusercontent.com/24437369/55171799-6200da00-514f-11e9-8465-f9bd385b83ee.png)

**Comment by kathycarothers** [comment]
HS Map language is being reviewed by Paul, Amy, George and Dorothy.

**Comment by kathycarothers** [comment]
Incorporating edits to H/S map help and starting to draft prez map help.

**Comment by kathycarothers** [comment]
Checking to see if language for the prez map needs to be updated.

**Comment by kathycarothers** [comment]
@dorothyyeager @AmyKort @bmathesonFEC I have created the two maps in Wagtail. They are ready for the content team to review. The pages are under "Campaign finance data" and are labeled House and Senate map help, and Presidential map help.

**Comment by kathycarothers** [comment]
Pages are in final review with the content team before publishing.

**Comment by dorothyyeager** [comment]
@kathycarothers is out today, but content team and PMs reviewed and it looks great, so @PaulClark2 had me go ahead and publish.

House/Senate map help: https://www.fec.gov/campaign-finance-data/house-and-senate-map-help/
Presidential map help: https://www.fec.gov/campaign-finance-data/presidential-map-help/

Put in a www redirect for the old pages to the new pages. Paul will have the links added where needed to the maps. 

Work is done, so we're ready to close.

**Comment by kathycarothers** [comment]
@dorothyyeager Thank you!
