### ISSUE TITLE
Add a page to SSF H4CC content on types of bank accounts and adjust a related page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2774]
**User Story** While looking for a handy link explaining rules for having federal and nonfederal accounts set up during an SSF webinar, I found we only had handy links for nonconnected PACs and party committees. I gave them the nonconnected link, but we should make an SSF version since there's irrelevant content on nonconnected page. I later found the page I was looking for in the SSF disbursement section - but the part I needed (about the ability to set up the accounts) should've been in the registering the SSF section as its own page.

**To do**
- [ ] Draft content for a page in registration bucket that is similar to https://www.fec.gov/help-candidates-and-committees/registering-pac/bank-accounts-nonconnected-pacs/ but for SSFs. 

Sources of approved language to use: There is SSF guide content on https://www.fec.gov/help-candidates-and-committees/making-disbursements-ssf-or-connected-organization/supporting-nonfederal-candidates-ssf/ that we might want to consider moving into this new page (where it relates to setting up the two accounts), and letting the two pages cross reference each other.  Alternatively, section 1 on page 177 of the SSF Guide provides the language needed for this page.

- [x] Content team and Info Division review of draft content. 
- [x] OGC review if any new language is drafted (try to find approved language). - No new language 
- [x] Once content approved, create Wagtail page
- [x] Second pair of eyes reviews Wagtail page
- [x] Publish Wagtail page and add to H4CC collection page menu

**Comment by kathycarothers** [comment]
Working on drafting a word document for the new sub section page.

**Comment by dorothyyeager** [comment]
So @kathycarothers and I realized that a paragraph on "Federal Election Purpose" notices that applies to SSFs was not put in the corporate guide (not sure why, it's a rule for them too) but should be added to the SSF page on fundraising notices and linked off this new page. (There is approved language in the nonconnected guide at https://www.fec.gov/help-candidates-and-committees/making-disbursements-pac/notices-required-nonconnected-solicitations/.) @AmyKort - Does it makes sense to work this part of things into this ticket?

**Comment by dorothyyeager** [comment]
Checked with @AmyKort and Information Division management on our question above. They would prefer to omit the "Federal Election Purpose" paragraph from the SSF section since it was omitted from the Corporate/Labor guide. So no need to act on our comment. @kathycarothers

**Comment by kathycarothers** [comment]
@dorothyyeager sounds good. I will get the word doc ready to circulate for the content team to take a look at it. Thanks!

**Comment by kathycarothers** [comment]
I have sent the draft to the content for review and input. Deadline for all comments is COB 5/3.

**Comment by kathycarothers** [comment]
Drafting page in Wagtail

**Comment by kathycarothers** [comment]
Working on publishing the page. Just have one hiccup with the bullet points.
