### ISSUE TITLE
Add new FEC notify subscription accordion to Filings and reports advanced data page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2777]
**What we're after:** To help users find and subscribe to candidates and/or committees through the new FEC notify, we want to add an accordion with some helpful language and a button and link to the registration and log in pages. 

This will need to be created as a **hotfix** so that we're able to push this out when the efiling team is ready to release FEC notify. 

**The efiling team currently has FEC Notify slated for release Friday April 12, 2019**

**Completion criteria:**
- [x] Add accordion to the Filings and reports page: https://www.fec.gov/data/browse-data/?tab=filings
- [x] Accordion header: "Get notified when a candidate or committee submits a new filing"
- [x] Accordion body: "Subscribe to individual candidates and committees to be notified immediately by email of new filing submissions, as well as Requests for Additional Information the FEC sends to filers."
- [x] Include "Subscribe" button and link to: https://fecnotify.fec.gov/fecnotify/register/
- [x] Below button, include text: "Already subscribed? Log in" and link to: https://fecnotify.fec.gov/fecnotify/login/

**Design:**
![Screen Shot 2019-03-27 at 2.11.56 PM.png](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/c71a9c6c-0157-42a1-8e35-8fa6d2b7c1ac)

**Comment by pkfec** [comment]
@patphongs deployed the hotfix to production today, April 12th. 
Closing this issue.
