### ISSUE TITLE
Finalize reporting examples for Form 5, Form 9 and Form 3X filers for the new multistate communication rules (PUBLISH)

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#2785]
**User story**
I'm a Form 3X (or Form 5 or Form 9) filer or consultant to one, and am making disbursements for independent expenditures (or electioneering communications) that relate to presidential primary elections and are publicly distributed in multiple states but that don't refer to any particular state's primary election. How and when do I report this activity?

**Background**
On December 27, 2018, the FEC published new rules for reporting multistate independent expenditures and electioneering communications that relate to presidential primary elections and are publicly distributed in multiple states but don't refer to any particular state's primary election. The new rules take effect on March 31, 2019 (although that date may shift at the conclusion of congressional review.) Our task will be to update the reporting examples for Form 5, Form 9 and IEs on Form 3X to incorporate these new rules.

Continuation of ticket: #2666 

**8.6 Completion Criteria**
- [x]  Adapt F5 example for F3X and F9 filers
- [x]  Send draft images to @jjonesfec
- [x]  Team image edits and revisions
- [x]  Create wagtail page
- [ ]  Publish pages

**Comment by bmathesonFEC** [comment]
Adapted F5 reporting example for F9. F3X draft not yet complete, need to consult PAC specialists to decide how this fits in with other complicated independent expenditure reporting requirements on the F3X.

Image request for F5 and F9 send to Jim Jones.

**Comment by pkfec** [comment]
@bmathesonFEC  Do you have any update on this issue? Have you heard from Jim Jones yet?

**Comment by bmathesonFEC** [comment]
Regained cloud.gov access. Working on these now. Updates to come.

**Comment by bmathesonFEC** [comment]
Resumed work on these reporting examples. Updated images for:
- Form 5 multistate IE example
- Form 9 multistate EC example

To-do:
- Input Form 3X reporting example
- Request edit for Form 5 image.

**Comment by bmathesonFEC** [comment]
Created Form 3X reporting example and requested images for the page.

**Comment by bmathesonFEC** [comment]
Updated images, received feedback from Content Team and RAD-Party. Will make updates today.

**Comment by bmathesonFEC** [comment]
Received PAC/Party images for multi-state reporting examples. Will update today and distribute to Content Team / RAD for review.

**Comment by bmathesonFEC** [comment]
Distributed pages to the Content Team and RAD Managers for review.

**Comment by bmathesonFEC** [comment]
Distributed final drafts to RAD and Content team.

**Comment by bmathesonFEC** [comment]
Incorporated all feedback. Added links to the "Filing ____ Reports" pages for:
- Non-connected
- SSF
- Other filers (IE, EC)

Also, added the link to Party but it will not be published until all of the reporting examples are published.

Next step: add reporting example cards on other content pages.

**Comment by jjonesfec** [comment]
Modified reporting examples completed and transmitted for publishing.

**Comment by bmathesonFEC** [comment]
After receiving approval for these drafts, they have been published, links are available on the guide page. Next work is in #2994.
