### ISSUE TITLE
PAC and party reporting examples Round 5 - Drafting  (Language & Images)

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#2786]
To help PACs and party committees understand how to report campaign finance transactions, we will draft and post reporting examples that will go with the nonconnected, SSF, and party sections within Help for Candidates and Committees.

Prior work issues: #1751, #1752, #1753, #1754, #1864, #1865, #1866, #1933, #1934, #1935

Continuation of #2689 (prep for drafts)

**Completion Criteria (8.5):**
Party examples adapted from PAC examples:
- [x]  Create Party drafts from PAC examples with minor language changes
- [x] Find links for FECFile videos, FECFile getting started manuals, and other resources to be included with the example.
- [x]  Compile text for images

For newly created Party examples:
- [x]  Draft example (language only) using existing campaign guides.
- [x]  Draft image caption language when possible.
- [x] Find links for FECFile videos, FECFile getting started manuals, and other resources to be included with the example.
- [x]  Compile text for images

**Future work (8.6):**
- [ ]  Change committee names for new images
- [ ]   Send draft images to @jjonesfec
- [ ]  Create images & review
- [ ]  Team image edits and revisions
- [ ]  RAD SME edits and revisions

**Comment by bmathesonFEC** [comment]
New sections and pages to be drafted by Party specialists in RAD. (full list of new and adaptable examples in google drive).

**Allocation**
Allocated Federal and Nonfederal Administrative Expenses (...) (Schedule H1)
Allocation Ratios (Schedule H2)
Transfers from Nonfederal Accounts for Allocated Federal/Nonfederal Activity (Schedule H3)
Disbursements for Allocated Federal/Nonfederal Activity (Schedule H4)

**Coordination**
Itemized Coordinated Party Expenditures Made by Political Parties (Schedule F)

**Comment by bmathesonFEC** [comment]
Question raised by Party specialist, can we just add reporting guidance to these pages that cover schedules H1, H3, and H4, instead of creating new reporting example pages?

https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/administrative-expenses-party-committees/

Don't know the answer yet, but wanted to log this here to review.

**Comment by bmathesonFEC** [comment]
While working on drafts for reporting examples, Dan in PNP asked the question above.  @dorothyyeager, it looks like there's some party committee reporting advice on allocation (H1, H3, H4) mixed in with regular content. In your experience creating the original pages, do you think it make sense to pull reporting content off that page, create a reporting example, and add reporting example link cards in place of the original content? Looking at other guides, it looks like we keep the reporting advice non-existent or bare bones and link with a reporting example card. 

Let me know what you think. (no hurry!)

**Comment by dorothyyeager** [comment]
Hi @bmathesonFEC on your comments above: Yes, the idea was to keep reporting examples on their own cards, to make the pages less long. When we didn't have reporting examples, we would insert language from the printed Campaign Guides as placeholders so that the reader had something to use.

For the allocation examples, they do get kind of convoluted, at least in our webinars and conferences. The "example scenario" might be a good way to work with parts of them. Take a look at the joint fundraising page at https://www.fec.gov/help-candidates-and-committees/making-disbursements/joint-fundraising-candidates-political-committees/. @llienfec came up with the organization for that page and a mix of reporting examples and example scenarios that really made it all make sense online and improved on the printed guide's organization of them. It might make a good model for allocation examples.

Also if a page is super long, we may want to think about converting it into a resource template page, so that it will have the left side bar and people can use those links to navigate. Something to consider.

**Comment by dorothyyeager** [comment]
If you want to see how we organized the joint fundraising page work (it took several sprints because our first stab at it made us realize the page needed reorganization), look at #1995 #2101 and #2111 .

**Comment by bmathesonFEC** [comment]
Received drafts from RAD party specialists. On my desk for review now.

**Comment by bmathesonFEC** [comment]
Still reviewing RAD party drafts. If we move forward with this approach for reporting examples, we will remove reporting advice from this page and add a reporting example card: https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/raising-funds-federal-and-nonfederal-party-committee-accounts/

**Comment by bmathesonFEC** [comment]
Another reporting example card here: https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/administrative-expenses-party-committees/

**Comment by bmathesonFEC** [comment]
Draft for two reporting examples are with RAD management for review. 

Party Administrative Expense Allocation: https://drive.google.com/open?id=1jZu1VDCdY9s_hw-5inMvewsT_YQkJowaX63eXhgrUno

Party Fundraising Allocation: https://drive.google.com/open?id=1w5FlEoDWkCD3XhALoyUtwl5mdOm6fFvR4bkvFjGODuE

Party coordinated expenses is still in the drafting stage.

Meeting with @dorothyyeager Friday to get a crash course on replicating existing wagtail pages so I can begin work on PAC -> Party adaptation.

**Comment by bmathesonFEC** [comment]
Still working on edits from PAC to Party for adapted pages, but will be done today. Created the following draft reporting examples in wagtail. Ready for image creation and final push for publication in the next sprint:

Registering:
- registering a party
- mulsticandidate status

Receipts
- Earmarked contributions

Disbursements
- Operating expenditures
- Credit card disbursements
- Contributions to federal candidates
- Redesignating contributions given
- In-kind contributions to  candidates
- Earmarked contributions
- Refunded contributions
- Voided contributions
- Donations to nonfederal candidates

Independent Expenditures
- 48-hour reports
- 24-hour reports
- Estimating independent expenditures
- Disseminating and paying for IEs in the same reporting period
- Paying for an IE first and disseminating in a later reporting period
- Disseminating an IE first and paying in a later reporting period
- Repaying independent expenditure debt

Debts
- Debts owed by the committee
- Repaying operating expenditure debt
- Repaying independent expenditure debt

Allocation
- Allocated Administrative expenses
- Allocated fundraising expenses

Coordination
- Coordinated expenditures

**Comment by bmathesonFEC** [comment]
Work continues in #2824 (publishing)
