### ISSUE TITLE
Discuss removing 2-year restriction data/design planning session

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2788]
**What we're after:** We intend to lift the 2-year restriction from schedule A and we've had initial conversations about what that entails for the All receipts and Individual contributions data tables. Now we need to expand that discussion to include other impacted areas on our website that rely on schedule A data and are broken out by election or two-year period. 

**Completion criteria:**
- [x] Update this ticket with initial documentation that tracks the impacted areas on the site. 
- [x] Document everywhere the front-end uses schedule A data (also consider documenting schedule B data)
- [x] Plan a meeting to have this discussion: include devs, PMs, and design
- [x] Identify key takeaways and clear action items, open follow-up tickets

**Comment by patphongs** [comment]
Preliminary [document](https://docs.google.com/document/d/1U-Y3P4-Q5TXTKse-qAjNzGKRERd6PLEljksnKkz37wg/edit#) 🔒 outlining possible schedule_a and schedule_b updates to remove the 2 year restriction.

**Comment by patphongs** [comment]
Meeting has been schedule for 4/9 at 2pm

**Comment by pkfec** [comment]
Follow up tickets are created. Hence closing this ticket.
