### ISSUE TITLE
Update aggregate amount links on election profile page

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2790]
Currently the `IE`, `CC`, and `EC` datatables on the election profile pages aggregate amount column is linking to just a 2 year expanse of time. They should be linking to the full election year expanse of time There’s no 2 year restrictions on these separate datatables.

https://www.fec.gov/data/elections/president/2016/#individual-contributions
https://www.fec.gov/data/elections/president/2016/#independent-expenditures
https://www.fec.gov/data/elections/president/2016/#communication-costs
https://www.fec.gov/data/elections/president/2016/#electioneering-communication

<img width="679" alt="Screen Shot 2019-04-02 at 1 29 24 PM" src="https://user-images.githubusercontent.com/12799132/55423300-a1faff00-554b-11e9-84bb-2c47954644a6.png">
<img width="675" alt="Screen Shot 2019-04-02 at 1 29 13 PM" src="https://user-images.githubusercontent.com/12799132/55423301-a1faff00-554b-11e9-8534-a9aba05a0621.png">
<img width="703" alt="Screen Shot 2019-04-02 at 1 28 17 PM" src="https://user-images.githubusercontent.com/12799132/55423302-a1faff00-554b-11e9-9add-c6e24f37e598.png">

**Comment by lbeaufort** [comment]
This may need API work, need to verify.

**Comment by lbeaufort** [comment]
@johnnyporkchops here's what I have so far: https://github.com/fecgov/fec-cms/pull/3052/files. It might be easier to talk through in person.
