### ISSUE TITLE
Re-organization of classic website

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2794]
**What we're after:**
We need to start retiring static content from our classic website as it is no longer needed. This will not effect any of our dynamic data or legal applications on classic.

## Completion criteria ##
- [ ] implement changes in [spreadsheet](https://docs.google.com/spreadsheets/d/1AylWmebD8ZJT128wuWXSXSVA11iWIttXHNR33y5Likg/edit#gid=0)

**Comment by patphongs** [comment]
Classic campaign finance portal link changes: https://docs.google.com/spreadsheets/d/1AylWmebD8ZJT128wuWXSXSVA11iWIttXHNR33y5Likg/edit#gid=0 🔒

**Comment by patphongs** [comment]
@PaulClark2 The Presidential Elections page still has 2016 in the title, should that be changed to "2020 Presidential Elections"? https://classic.fec.gov/portal/presidential.shtml

**Comment by PaulClark2** [comment]
@patphongs yes, please change it to 2020.

**Comment by patphongs** [comment]
@PaulClark2 Other question is concerning what to do with the classic legal searches. How should we incorporate them to our new data homepage?

![Screen Shot 2019-09-09 at 12 55 02 PM](https://user-images.githubusercontent.com/12799132/64550571-2de63380-d301-11e9-989f-1dc21e05cc68.png)

**Comment by AmyKort** [comment]
Will the links to EQS work from https://www.fec.gov/legal-resources/enforcement/ and the AO search link from https://www.fec.gov/data/legal/advisory-opinions/ and the SERs link from https://www.fec.gov/legal-resources/regulations/ continue to work the same way?

**Comment by AmyKort** [comment]
If the links to legacy legal research tools continue to work the same way on the new website, then I'm not sure that we need them on the old site as well. The one tool we would orphan would be the Archived MUR search, which we could add as a link from fec.gov.

**Comment by AmyKort** [comment]
It seems strange to me to have legal research tools on our data section homepage. What do you all think?

**Comment by AmyKort** [comment]
We are archiving the legacy Audit search in any case, so I don't think we need to make an extra effort for that system.

**Comment by JonellaCulmer** [comment]
Is it possible to introduce a new homepage for what's left? Similar to what's on the FECnet site. 
One link for legal stuff, one link for data stuff, another for what else is left?

**Comment by patphongs** [comment]
@AmyKort I forgot that our new website links to those classic legal systems anyways, so I agree, we don't necessarily need to re-introduce it on the classic site. @JonellaCulmer I think we only want to show the data things on the classic site. Since all the other pages we're trying to retire anyways. So we may just be able to not reference it at all anymore on the classic site? I'm open to be persuaded otherwise though

**Comment by AmyKort** [comment]
My preference would be to have fec.gov be the only place users would access our legal research tools--the new ones and the legacy systems. And then we'd only have campaign finance data left on classic. Thanks, everybody, for all of your work on this!

**Comment by PaulClark2** [comment]
I agree with Amy. If website users can access those systems from links on fec.gov, I don't think we need to keep links on classic.

**Comment by patphongs** [comment]
Thanks @AmyKort @PaulClark2 @JonellaCulmer for your input. I have not linked any legal apps in the re-organization of the classic pages.

This task is now complete:
- [x] Implemented changes in spreadsheet
- [x] Removed footer from classic site
- [x] Removed all links in the top navigation
- [x] Added redirect for old classic data portal `/pindex.shtml` to redirect to `/index.shtml`
- [x] Renamed `pindex.shtml` to `index.shtml` to make it our new classic homepage
