### ISSUE TITLE
Updates to Paper Filing Page

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#2796]
RAD requests to edit language to the first paragraph of the paper filing page:

Page: https://www.fec.gov/help-candidates-and-committees/filing-reports/paper-filing/

Add : “All reports that are filed on paper with the FEC should be filed on the most recent version of the report or form and the writing should be legible.  In addition, two-sided documents and the use of staples are discouraged.” 

- [x] Get language approved by OGC.
- [ ] Edit page.

**Comment by dorothyyeager** [comment]
I found some approved language in the corporate/labor guide and combined with the suggested edit. I've sent to RAD and Information to look over, and when they're happy, we'll send it on to OGC to get approved.

**Comment by dorothyyeager** [comment]
RAD and Information are happy, and the draft has been sent to OGC for approval.

**Comment by bmathesonFEC** [comment]
Thanks @dorothyyeager !!

**Comment by dorothyyeager** [comment]
OGC has approved the language. Working on the update now.

**Comment by dorothyyeager** [comment]
We've added the following paragraph to the page at https://www.fec.gov/help-candidates-and-committees/filing-reports/paper-filing/:

> **Requirements for paper filings**
> FEC forms filed on paper should be typed; printing in ink is also acceptable (but not recommended) as long as the forms are legible. Because filings will be imaged and photocopied several times before being placed on the public record, it is required that committees submit the original report (not a copy) with an original signature. Committees submitting illegible documents will be required to re-file. All reports that are filed on paper with the FEC should be filed on the most recent version of the report or form. In addition, two-sided documents and the use of staples are discouraged.

Closing the issue because work is complete.
