### ISSUE TITLE
Two-year period not filtering correct on House data table

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2797]
**What we're after:** On the [House candidates data table](https://www.fec.gov/data/candidates/house/), we've observed a bug where the two-year period does not filter correctly when a second search criteria is chosen and presents the incorrect data. 

Example: Filtering by second criteria, then changing the two-year period. The URL does not change and the data in the table is wrong. 

**Steps to replicate:**
1. Change state to Michigan
2. Change district to 03
3. Change two-year period to 2019-2020
4. You should be seeing a list with one candidate (Smith, Douglas Mark Mr. Jr.), who is not currently running in 2020. 

**Completion criteria:**
- [ ] Take a look to see how the two-year period interaction filters the table. The URL does not retain the cycle filter criteria
- [ ] Make sure that the AJAX call is correct and passes the same filter criteria through the URL.

**Comment by lbeaufort** [comment]
This is addressed by https://github.com/fecgov/fec-cms/pull/2917, sorry I missed it before!
