### ISSUE TITLE
Build new office/party aggregate totals box

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2802]
**History**
Design work: https://github.com/fecgov/fec-cms/issues/2620
Back-end work: https://github.com/fecgov/openFEC/issues/3549

**What we're after:** Building on design work previously completed, we now want to build out the totals aggregates box to also include a bar chart showing party raising and spending. 

**Completion criteria:**
- [ ] Build out aggregates box based on mock-up

### Raising: by the numbers aggregates box
https://www.fec.gov/data/raising-bythenumbers/
<img width="999" alt="Screen Shot 2019-04-05 at 1 42 39 PM" src="https://user-images.githubusercontent.com/31663028/55646468-475ede80-57a9-11e9-8fad-5a2eaa82ab3f.png">

### Spending: by the numbers aggregates box
https://www.fec.gov/data/spending-bythenumbers/
<img width="1000" alt="Screen Shot 2019-04-05 at 1 42 02 PM" src="https://user-images.githubusercontent.com/31663028/55646483-4d54bf80-57a9-11e9-8da2-df5f65c57336.png">

**Comment by rfultz** [comment]
Going decently well. Working on getting vars into JS from Python through Jinja

**Comment by rfultz** [comment]
Updates (comp on the left, in-browser on the right)

Default with the light theme:
![image](https://user-images.githubusercontent.com/26720877/56690063-931aee80-66aa-11e9-9392-1bcd1b695e36.png)

And a class-name swap to the dark theme:
![image](https://user-images.githubusercontent.com/26720877/56690110-afb72680-66aa-11e9-9de0-ce4ab099c594.png)

**Comment by patphongs** [comment]
For immediate deployment to our website, we'll need:
- [ ] Make a new .gov PR that will have the dark theme with office and election year dropdowns
- [ ] For the <aside> remove the updated date and FEC logo
- [ ] Default election years to current DEFAULT_ELECTION_YEAR var. Add this var to the window constants. Should be 2020.

**Comment by AmyKort** [comment]
Quick question: Can we build in a step for content review before we deploy these? There are a few inconsistencies in how we capitalize office names and how we identify party affiliation that I'd want to look at, both within these mock ups and to make sure we're consistent across the site. @JonellaCulmer and @rfultz

**Comment by AmyKort** [comment]
and @patphongs
