### ISSUE TITLE
Discuss and get OGC approval for shareable widgets and mock up solutions

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2803]
**What we're after:** As part of our "share and save our visualizations" feature epic, and building on the aggregate office/party totals [here](https://github.com/fecgov/fec-cms/issues/2620), we need to mock-up some design solutions for an embeddable data feature for persons/groups outside of the organization. 

While some preliminary mock-ups have been done (see below comment), we need to have a discussion about some of the possibilities for our embeds. What are the capabilities, limitations, and what are the best practices, if any, etc.

**Completion criteria:**
- [x] Schedule a discussion to go over what our goals are for the embeddable charts/features, possibilities and limitations
- [x] What are some possible design solutions that help us to achieve those goals, while considering limitations 
- [x] Discuss any legal implications that may arise from sharing our data beyond our website
- [x] Move to front-end ticket

**Comment by JonellaCulmer** [comment]
Some preliminary mock-ups below:

![design-draft-totals-embed](https://user-images.githubusercontent.com/31663028/55676762-3a291900-58a9-11e9-89c2-c7fe2813db58.jpg)

**Comment by JonellaCulmer** [comment]
Had a quick discussion about some of the stuff we want to consider as we move forward, including: 
- We need a strategy that can guide our embed work. What are our goals, what data are we interested in sharing
- We should keep it high-level and not candidate or committee level data
- Need to talk to OGC about legal issues that must be addressed
- Possible design changes to consider
- What other data widgets do we want to think about for the future

Notes are here: https://docs.google.com/document/d/1aVUJ5HGRXnRdNZqpST1j3rmMttyLR2iYTV7hBHKjozM/edit#

Next steps:
- [ ] Update designs based on conversation
- [ ] Discuss with @AmyKort, before engaging OGC. What do we need to provide for a complete review, how can we start an ongoing/collaborative relationship with them on this project and engage with them throughout the development/idea process

**Comment by JonellaCulmer** [comment]
Updated designs:
![Screen Shot 2019-04-22 at 11 32 29 AM](https://user-images.githubusercontent.com/31663028/56508465-599f8300-64f2-11e9-82b0-a3838fb248b8.png)

**Comment by JonellaCulmer** [comment]
This is blocked while we wait to have a discussion with Amy and OGC.

**Comment by pkfec** [comment]
@JonellaCulmer Did you have a discussion with @AmyKort and OGC? Do you have any update on this issue?

**Comment by AmyKort** [comment]
I think this is something we'll want to look at tackling in PI9.

**Comment by JonellaCulmer** [comment]
Working on a document that describes what a widget is and attempts to address possible concerns.

**Comment by JonellaCulmer** [comment]
Compiled summary and concerns in the below doc: https://docs.google.com/document/d/1oNq0iRLmPATcnHX8g9PiT5VvWKp0d4Ci4VOi--JehKg/edit

**Comment by AmyKort** [comment]
We've completed the review process for our proposal, and we're ready to move to implementation with our widgets!

**Comment by JonellaCulmer** [comment]
Please see updated widget designs below. 
![widget_styles](https://user-images.githubusercontent.com/31663028/59695899-fdd33c80-91b8-11e9-9f88-e80fb12d07b7.jpg)
Thoughts? @AmyKort @rfultz @johnnyporkchops

**Comment by rfultz** [comment]
@JonellaCulmer, I like it!

We'll need to figure out what the email/Facebook/Twitter functionality are.
- For any of them, we'll need a destination URL for users to hit. The Raising and Spending By the Numbers pages come to mind. Or the upcoming widgets page. Or maybe a new page exclusively for the aggregate totals widget?
- **Facebook** will only let us share a URL, but we can make sure that URL has a decent poster and description. Those shares are cached so we'd use a catch-all image and description (as opposed to race- or election-specific)
  - We could share something like `fec.gov/widget/aggregate-totals` and set up that page with an appropriate catchall image for the widget.
  - Last I checked, Facebook would treat query vars as separate URLs so we could share something like `fec.gov/widgets?widget=aggregate-totals` and serve an appropriate poster and description for aggregate totals but take the user to the page of all (one so far) of the widgets
- **Twitter** would let us share an image but it's more solid to treat images like the Facebook setup.
  - Twitter will let us pre-compose a tweet!
  - We could pre-compose a tweet based on the data in the chart, though users could take our "Combined, 2020 candidates have raised $100,000. Explore the data at fec.gov/whatever" message and change it to _anything_. But they could write whatever they want around our link, anyway.
- **Email** is all over the place.
  - We can pre-fill a message with a subject _and_ body. Attaching images with a link are tough and we couldn't demand that any attached images would be displayed at all (I personally do _not_ display images inside emails). We could pre-fill the message with any text we want—current data/totals, links, legal statements, etc. Again, if users want to edit any of it, they can.
  - As much freedom as email gives us, email links don't always work when people use webmail services like Gmail though they work fine with email clients e.g., Outlook, Mail.
- **SMS** We could precompose a text, if their device supports it.
- **WhatsApp** offers `https://wa.me/?text=`

**Comment by JonellaCulmer** [comment]
@rfultz I think the simpler we can keep this for now, the better. We can always update and add more features later after we get more of an idea on user needs. So perhaps sticking to the features that share links, would be good for now.

**Comment by JonellaCulmer** [comment]
Updated to remove email icon as an option. 

![widget_styles_updated](https://user-images.githubusercontent.com/31663028/59773268-579c3b00-927b-11e9-9c50-247cd835d4c8.jpg)

**Comment by AmyKort** [comment]
Thanks @JonellaCulmer!

**Comment by JonellaCulmer** [comment]
Closing in favor of #2980 and #2981.
