### ISSUE TITLE
Research implementation of time period filter interaction changes on all receipts, indiv. contrib. and disbursement data tables

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2812]
**_This ticket will be updated with mock-ups once work in the [design ticket](https://github.com/fecgov/fec-cms/issues/2811) is complete._**

**User story:** As a data user, I need to be able to increase my time period selection filter larger than a single 2 year time period for receipts and individual contributions data so that I can view and filter data for that expanded time span.

**What we're after:** Based on the [design work](https://github.com/fecgov/fec-cms/issues/2811) completed, we need to now implement this new interaction on the front-end. 

**Completion criteria: (timeboxing research to 1 week due by 4/19/2019)**
- [x] Try different methods on changing time period interaction. 
- [x] Decide what works best and can be fully implemented
- [x] ~Make a separate ticket with full implementation guidelines and business logic~ The business logic is in a comment referenced below.
- [x] Hold separate data design studio to discuss implementation details that come from this work

**Comment by patphongs** [comment]
So far I have created the ability to specify multiple two_year_time_periods within schedule_a and schedule_b data. However, performance when opening up the time period restriction is slow. We need to figure out what to do. I have set a meeting for tomorrow (4/22) to decide with the PMs on a path forward.

**Comment by patphongs** [comment]
After yesterday's meeting, we have devised new business logic. However, we should still check performance and feasibility for this new logic. https://github.com/fecgov/fec-cms/issues/2857

**Comment by AmyKort** [comment]
Is this ready to wrap up?

**Comment by patphongs** [comment]
Business logic is referenced in the design ticket here: https://github.com/fecgov/fec-cms/issues/2811#issuecomment-488786938

**Comment by patphongs** [comment]
Closing this issue in favor of #2811
