### ISSUE TITLE
Fix click-through from candidate profile pages to receipts and disbursements datatables

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2815]
**User story:** As a data user, I am interested in digging into totals figures to better understand where money is raised and spent.

Following on our work to remove the 2-year restriction from schedules A/B, we need to now address some "broken" links on our candidate profile pages. If a user were to look across multiple cycles to see all data raised and spent in cycles leading up to an election then linked figures in the summary page take you to the relevant data table but you don't see the data that contributes to that total. You are only taken to a view with a two-year total instead of a four or six year total.

For example, for Senate "all years" totals we should pass three 2-year periods. For 2020 "all years" senate, the data table should show `two_year_transaction_period`s 2020, 2018, 2016.

**Completion criteria:**
-  [ ] Clicking on financial summary breakdown links for house/senate/president takes the user to the correct set of two-year periods. This should take the user to the correct set of transactions for both the "all years" and a given 2-year period.

**Example:** 
Looking at Susan Collins candidate profile page (https://www.fec.gov/data/candidate/S6ME00159/), view "All years: 2015-2020" and clicking on itemized individual contributions in the summary view, you are taken to the all receipts datatable (https://www.fec.gov/data/receipts/?two_year_transaction_period=2020&cycle=2020&data_type=processed&committee_id=C00314575&min_date=01%2F01%2F2019&max_date=12%2F31%2F2020&line_number=F3-11AI)  and can see data for only 2019-2020, not 2015-2020.

![Screen Shot 2019-04-10 at 10 34 14 AM](https://user-images.githubusercontent.com/31663028/55887926-75169f80-5b7c-11e9-8e72-a764aaf2073b.png)
<img width="650" alt="Screen Shot 2019-04-10 at 10 29 18 AM" src="https://user-images.githubusercontent.com/31663028/55888027-a7c09800-5b7c-11e9-879e-7f692478157f.png">
<img width="641" alt="Screen Shot 2019-04-10 at 10 29 34 AM" src="https://user-images.githubusercontent.com/31663028/55888040-abecb580-5b7c-11e9-85e5-4e9cc5b9d4e5.png">

**Comment by johnnyporkchops** [comment]
@JonellaCulmer , Do we want to pass parameters for each of  two year periods in all-years(showing filter tags for each two-year period on the datatable), or do we want to pass a date range when all years is chosen (showing a filter tag with a date range like `01/01/15-12/31/2020` , with with election_full flag applied as well.) ?

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Yes, I believe we should click-through to filter tags with each of the two-year periods that apply and not a range. Thanks for asking.
