### ISSUE TITLE
Feedback Form Reliability

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#2819]
#### Summary
Our site feedback has dropped recently, and internal users have reported being unable to submit feedback through the form.

The issue has been proven to affect Chrome, Firefox, Firefox Developer Edition, Safari, and Safari Technology Preview.

As this is a rush project, we could time-limit the initial investigation, implement an immediate option, and continue working on a more stable, long-term solution.

#### To reproduce
On basically any page on the site, open the Feedback panel from the lower right corner of the page. If the recaptcha appears at the bottom it's fine. If it doesn't appear (shift-reload to try again), the form submission will not work.

When the recaptcha hasn't loaded, submitting the form works like a redirect with the form values sent through the url string.

#### Some quick-fix options
- remove the Feedback box until we solve it.
- change the content of the feedback box until we solve it (e.g., “Thanks for taking the time, please email… see Github…”)

#### Possible option (with zero investigation)
We could set up a timer to continually check whether the recaptcha is loaded (while the Feedback panel is open) and only activate the submit button when it is—check every couple seconds whether recaptcha is loaded and, if so, stop checking and activate the submit button.

#### Immediate acceptance criteria
- Users are able to submit feedback when needed, whether through email, Github, or some other means.

#### Final acceptance criteria
- [ ] The feedback form is back,
- [ ] recaptcha works reliably on all major modern browsers, and
- [ ] users are able to submit feedback using the form without leaving their current page.
- [ ] Add feature flag for feedback box

#### Bonus
- Address console warnings (especially Firefox) when the recaptcha _does_ appear.

##### Related PRs
Original PR for recaptcha implementation: [#2367](https://github.com/fecgov/fec-cms/pull/2367)

**Comment by JonellaCulmer** [comment]
Work is merged, so closing.
