### ISSUE TITLE
PAC and party reporting round 5 - Publishing Examples

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#2824]
To help PACs and party committees understand how to report campaign finance transactions, we will draft and post reporting examples that will go with the nonconnected, SSF, and party sections within Help for Candidates and Committees.

Prior work issues: #1751, #1752, #1753, #1754, #1864, #1865, #1866, #1933, #1934, #1935

Continuation of #2689 (prep for draft), #2786 (drafting language)

Drafts language and images are created,  once approved by RAD management they will be ready for their own wagtail pages.

**Completion Criteria:**
- [x]  Create wagtail page for each new reporting example
- [x]  Create images & review
- [x]  Send draft images to @jjonesfec
- [x]  Content team reviews draft language
- [x]  RAD final review
- [x]  Team image edits and revisions

Additional work required required for publication:
- create a Reporting Example section on the [Filing political party reports page](https://www.fec.gov/help-candidates-and-committees/filing-political-party-reports/)
- remove party reporting advice that is currently integrated in other pages, replace with Reporting Example "cards".

**Comment by bmathesonFEC** [comment]
Image edits and original image drafts sent to Jim Jones.

**Comment by jjonesfec** [comment]
Completed initial drafting of modified image set (36 images). Should complete final web optimization by Thursday.

**Comment by jjonesfec** [comment]
Delivered first set of images optimized for web, started work creating remaining images.

**Comment by jjonesfec** [comment]
Completed initial new Party Reporting Examples (11 images). Should complete final web optimization on Monday.

**Comment by jjonesfec** [comment]
Delivered first drafts of all remaining PAC and party reporting images, optimized for web. Two text images still pending clarification from @bmathesonFEC. Awaiting review and final punch list.

**Comment by bmathesonFEC** [comment]
Regained cloud.gov access. Working on these now. Updates to come.

**Comment by bmathesonFEC** [comment]
Resumed updates to Party Reporting Examples. Updated images for:
- Multicandidate Status
- Earmarks
- Operating Expenditures
- Contributions to Federal Candidates
- Redesignating contributions given
- In-kind contributions
- Refunded contributions
- Voided contributions
- Donations to nonfederal candidates
- Allocated Administrative Expenses
- Allocated Fundraising Expenses
- Coordinated Expenditures

Issues that came up while uploading images that need to be resolved:
- Allocated admin expenses: needs FECFile instructions
- Allocated fundraising expenses: needs FECFile instructions
- Coordinated expenditures: ask if this needs FECFile intructions
- Operating expenditures: must update link to credit card reporting example once the Party Credit Card reporting example is published.
- Credit cards example: get an error in Wagtail. Problem must have occurred when I copied the PAC page.  (ask @dorothyyeager)
- Contributions to federal candidates: requires an edit to an image.

Image updates to-do:
- 48-Hour
- 24-Hour
- Estimating IEs
- Disseminating and paying for IEs in same period
- Paying for an IE first and disseminating later
- Disseminating first paying later
- Repaying IE debt
- Debts owed by committee
- Repaying operating expenditure debt

Blockers:
- RAD work

**Comment by dorothyyeager** [comment]
Hi @bmathesonFEC - I took a look at the credit card page and I think you are right - there are most likely some HTML errors in the page you copied from, and copying them over into a new page makes the new page lock up. They happen when people copy in stuff from a word document but forget to do it as plain text. The weird thing is I looked at both SSF and PAC credit card examples in Wagtail and they seemed error-free, so if it was one of those you copied from, I'm not sure why you're getting that server error.

My best advice for the credit card page would be to delete it (sorry!) and start over, but copy in plain text and insert the images fresh. @johnnyporkchops has helped our team before when HTML errors have caused a page to not be available. Usually the fix basically involved deleting everything and starting over. :(

**Comment by bmathesonFEC** [comment]
Thanks for looking. I'll delete and recreate for now. It's not too much work, just some copy/paste.

**Comment by bmathesonFEC** [comment]
Continued work.  Updated images for:
- Credit Cards (@dorothyyeager I fixed this issue by copying the SSF example instead of the NC example. NC PAC example DID NOT want to be copied).
- 48-Hour
- 24-Hour
- Estimating independent expenditures
- Disseminating and paying for IEs in the same reporting period
- Paying for an IE first and disseminating in a later reporting period
- Disseminating an IE first and paying in a later reporting period
- Repaying independent expenditure debt
- Debts owed by the committee

Issues that came up while uploading images that need to be resolved:
- 48 Hour: update aggregation reporting example card once party examples are published
- 24 Hour: update aggregation reporting example card once party examples are published
- Disseminating and Paying for IEs in the same period: Update links to 48 and 24 reporting examples
- Disseminating an IE first and paying in a later period: Update link to debt reporting examples.

**Comment by dorothyyeager** [comment]
For @bmathesonFEC -- I'll add that nonconnected example to a list we keep for clean up week. At some point, one of us will need to go in there and cut/re-paste as plain text each element of that page so that we can edit it in the future if we need to.

**Comment by bmathesonFEC** [comment]
Thanks Dorothy.

Operating expenditures:  must add links to allocable admin and fundraising examples.
Credit Cards:  must add links to allocable admin and fundraising examples.

**Comment by bmathesonFEC** [comment]
Updated images, received feedback from Content Team and RAD-Party. Will make updates today.

**Comment by bmathesonFEC** [comment]
Feedback received, reviewing and incorporating changes today/tomorrow.

**Comment by bmathesonFEC** [comment]
Incorporated most changes. Still have to incorporate some language Dorthy suggested to clarify that examples do not apply to FEA. Also, several required edits to images... those request have been sent to Jim.

**Comment by jjonesfec** [comment]
Revised images uploaded to Goggle Drive.

**Comment by bmathesonFEC** [comment]
Distributed final drafts to RAD and Content team.

**Comment by bmathesonFEC** [comment]
Making adjustments based on Dorothy's feedback.

**Comment by bmathesonFEC** [comment]
Remaining issues before this ticket can be closed:

- **IE's paid before dissemination**: must come to a conclusion about reporting these expenditures on 21b or 30b or fitting this into the next round of example featuring FEA.

- **Redesignation**: two questions, 1. do we need the "as originally reported memo" in our reporting examples for parties, non-connecteds, and SSFs. 2. do we need to remove the negative "redesignation from" memo entry because it's not in the regs.

- **Inadequate purpose of disbursement link**: does the information on that page apply to IE reporting? Or is it just operating expenditure reporting?

**Comment by bmathesonFEC** [comment]
From Jim:
Modified reporting examples completed and transmitted for publishing.

Brad: Updated Earmark example with new images!

**Comment by bmathesonFEC** [comment]
Image drafts for redesignation are with Jim. Tentative date for publish is now Wednesday. (Thanks, @jjonesfec)

**Comment by jjonesfec** [comment]
Revised images completed.

**Comment by bmathesonFEC** [comment]
Images updated, comments edited reflect the updated image.

I added the question of referencing the adequate/inadequate purpose lists in IE reporting examples to the Future Reporting Example work ticket (#2974). It shouldn't prevent publication of these examples.

Thank you to @dorothyyeager, @kathycarothers, @jjonesfec, @AmyKort for your patience with me on this marathon ticket.
