### ISSUE TITLE
(For when after 8.5 release is live) Remove the workaround html block from various custom pages 

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2826]
**What we're after** Color-coding that's consistent.

**Background** In #2762 and PR #2818, @johnnyporkchops fixed the code for custom and resource pages so that they  have a set breadcrumb color and style based on parent-page type.

All page-types published with a parent of legal-resources , campaign-finance-data , and introduction-campaign-finance will have blue breadcrumb style.
All other page-types published NOT in the three sections above are red --(unless it is a
ResourcePage that is specified as blue.)
Resource pages still have the checkbox in the "promote tab" to specify red or blue, but this will not have any effect if the pages are in any of the three sections mentioned above.

Before this was fixed, he'd given the content team an html code block to insert to temporarily fix the wrong breadcrumb color for certain pages. This task is to take out the block now that the problem has a permanent fix.

**To do**
- [x] Go into each of these pages and delete the first html block that sets the color:
/legal-resources/regulations/explanations-and-justifications/chronological-index-e-j-s/
/legal-resources/regulations/information-for-public-hearing-june-27-28-2018/
/legal-resources/regulations/pending-rulemaking-matters-comment/
/legal-resources/regulations/sers-supplemental-information/
/campaign-finance-data/candidate-summary-file-description/
/campaign-finance-data/committee-summary-file-description/
/campaign-finance-data/committee-master-file-description/
/campaign-finance-data/communication-costs-file-description/
/campaign-finance-data/contributions-committees-candidates-file-description/
/campaign-finance-data/house-and-senate-map-help/
/campaign-finance-data/independent-expenditures-file-description/
/campaign-finance-data/party-code-descriptions/
/campaign-finance-data/presidential-campaign-finance-summaries/
/campaign-finance-data/presidential-map-help/

**Comment by kathycarothers** [comment]
I will start on this once the release is out on 4/24

**Comment by kathycarothers** [comment]
The block code has been removed of the requested pages.
