### ISSUE TITLE
[High Priority] Turn on bar charts feature flag on homepage

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2828]
**What we're after:** Based on the results of [this ticket](https://github.com/fecgov/fec-cms/issues/2630) to verify that high-profile candidate data is present and correct on the website, we need to move forward with removing the feature flag on the bar charts on the homepage so users can see/use the bar charts.

**Completion criteria:**
- [x] Check with PM's on the date when this should be deployed to PROD (tentative dates April 16th or April17th). 
- [x] Turn on feature flag (`FEC_FEATURE_HOME_BARCHARTS`) for homepage bar charts
- [ ] Redeploy master branch on circle

**Comment by patphongs** [comment]
@lbeaufort Please approve showing the bar charts on the homepage after data verification.

**Comment by pkfec** [comment]
a hotfix is deployed and feature flag is set on homepage. closing this issue
