### ISSUE TITLE
Coverage dates outside expected election "period"

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2836]
**What we're after:** We still seem to see money raised and spent for candidate's no longer raising or spending money toward a specific election. 

Below are some examples: 
Ted Cruz - https://www.fec.gov/data/candidate/P60006111/
Barack Obama - https://www.fec.gov/data/candidate/P80003338/
Bernie Sanders - https://www.fec.gov/data/candidate/P60007168/?cycle=2016&election_full=true

<img width="1018" alt="Screen Shot 2019-04-16 at 8 42 28 AM" src="https://user-images.githubusercontent.com/31663028/56211367-bea43600-6025-11e9-9e82-0eba5e8ccfa7.png">

**Comment by lbeaufort** [comment]
This issue was addressed by https://github.com/fecgov/fec-cms/pull/3075
