### ISSUE TITLE
8.7 Redirect work and future planning

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2837]
**What we are after**
Making sure that the website users are getting the latest and most up to date content, while moving towards getting content moved from transition to fec.gov

Redirect spreadsheet for PI8: 
https://docs.google.com/spreadsheets/d/1AHZ4rnZGHL3E9yboZ1_j6_4lbM9ZkKfloK9ZMpsZki8/edit

**To do:**
- [x] Redirect these old discontinued audio form URLS to https://www.fec.gov/resources/cms-content/documents/fecfrm1.pdf
/pdf/forms/fecfrm1ssf.pdf
/pdf/forms/fecfrm1nc.pdf
/pdf/forms/fecfrm1party.pdf

- [x] Put in redirects for a few brochures and old handouts
/info/articles/ - Will redirect to H4CC
/pages/brochures/TestingTheWaters.shtml
/pages/brochures/citizens.shtml
/pages/brochures/citizens_guide_brochure.pdf
/pages/brochures/citngui1.shtml
/pages/brochures/contriblimits.shtml

- [x] Figure out what's going on with our redirect for /pages/brochures/internetcomm.pdf (it's returning 404 error) even though we have something in Wagtail for it and make the correction.
- [x] Test the corrected form redirects after they are merged. (The old pages are already removed from transition; we are just fixing our redirect in this ticket.)
- [x] Test the remaining redirects after merge
- [x] Talk to Information Division stakeholders about redirecting some older publications that are not yet retired but for which there is existing content on fec.gov.
- [x] Make plans / put in ticket(s) / make our spreadsheet for PI 9 transition page redirect and removal work.

**Comment by dorothyyeager** [comment]
We've gotten feedback from the Information Division and have some good plans for most of the materials we asked about. Some others will require a little more thought and care.

A spreadsheet has been set up for 9.1 redirects at https://docs.google.com/spreadsheets/d/1Jn5nC3fFku10RTCP5OAW6RiffjNBE4VwBubITQpCNK8/edit?usp=sharing

**Comment by dorothyyeager** [comment]
A spreadsheet for PI9 redirect work has been set up at https://docs.google.com/spreadsheets/d/1Jn5nC3fFku10RTCP5OAW6RiffjNBE4VwBubITQpCNK8/edit?usp=sharing. 

We've updated it with the brochures we can go ahead and redirect in 9.1, as well as notes on a few others which will require Wagtail page creation. Going to put in tickets for the 9.1 redirects and the Wagtail pages to be made.

**Comment by dorothyyeager** [comment]
We've heard back from the Information Division and are able to proceed with some redirects in 9.1 (#2890 ). We are going to need to make a Wagtail page for partnership information #2891  and create and post other content (a Record article or a PDF of a print brochure), so we've noted those items in the [spreadsheet created for PI 9 redirects](https://docs.google.com/spreadsheets/d/1Jn5nC3fFku10RTCP5OAW6RiffjNBE4VwBubITQpCNK8/edit?usp=sharing)

**Comment by kathycarothers** [comment]
We've heard back from the Information Division and are able to proceed with some redirects in 9.1 (#2891). We are going to need to make a Wagtail page for partnership information #2892 and create and post other content (a Record article or a PDF of a print brochure), so we've noted those items in the spreadsheet created for PI 9 redirects [https://docs.google.com/spreadsheets/d/1Jn5nC3fFku10RTCP5OAW6RiffjNBE4VwBubITQpCNK8/edit?usp=sharing]

**Comment by kathycarothers** [comment]
We've heard back from the Information Division and are able to proceed with some redirects in 9.1 (#2891). We are going to need to make a Wagtail page for partnership information #2892 and create and post other content (a Record article or a PDF of a print brochure), so we've noted those items in the spreadsheet created for PI 9 redirects [https://docs.google.com/spreadsheets/d/1Jn5nC3fFku10RTCP5OAW6RiffjNBE4VwBubITQpCNK8/edit?usp=sharing]

**Comment by kathycarothers** [comment]
dd

**Comment by dorothyyeager** [comment]
We've tested the redirects and all are working except the one that keeps mysteriously 404'ing. We'll add that to our ticket for 9.1 (#2890). We've put in a ticket for taking down these redirected pages at #2893.
