### ISSUE TITLE
Need to change raising and spending line charts to default to current two-year period, not 2017-2018

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2838]
**What we're after:** Now that we have a good amount of data coming in for the current two-year period, we should default to 2019-2020 on the raising and spending line charts. 

Raising: https://www.fec.gov/data/browse-data/?tab=raising
Spending: https://www.fec.gov/data/browse-data/?tab=spending

### Before
![Screen Shot 2019-04-16 at 9.54.32 AM.png](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/57333176-89e1-49fc-af02-8f5c0edb7ada)

### After
![Screen Shot 2019-04-16 at 9.54.47 AM.png](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/8bcb0367-71fa-4ac3-b8f4-67237ce3f0ec)

**Comment by lbeaufort** [comment]
I think this will be addressed by https://github.com/fecgov/fec-cms/issues/2640 but I'm not 100% sure.

**Comment by AmyKort** [comment]
Moving to 9.1 just so we keep tracking progress.

**Comment by patphongs** [comment]
Closing in favor of: https://github.com/fecgov/fec-cms/issues/2640
