### ISSUE TITLE
Raising/Spending: by the numbers: Not showing correct election years for Prez. candidates on iPhone

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2851]
**What we're after:** Just like everywhere else, we need to only see Presidential election years on the raising/spending by the numbers pages. Unfortunately, we're seeing additional election years on iPhone, such as 2014, 2018, and 2022 as options. And it's returning bad data. 

**Completion criteria:**
TBD

![Image from iOS copy.png](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/c1c8b5d8-295e-4053-b318-cf5f11338796)
![Image from iOS.png](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/f87191ca-fd1b-49d5-ad67-1604cd37eb46)

**Comment by patphongs** [comment]
A solution has been merged into the release
