### ISSUE TITLE
Draft updates to the glossary to add certain terms related to presidential elections

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2856]
**What we're after** Including guidance for presidential campaigns in the candidate portion of H4CC.

**To do**
- [x] After drafting tasks for presidential pages are done, we'll have a list here of related words or terms that need to be put into the glossary.
- [x] Draft glossary definitions for these terms:
_communication costs_ (request by front end for data-related page)
_date of ineligibility_
_expenditure report period_
_GELAC fund_
_host committee_
_inactive candidate_
_inaugural committee_
_matching funds_
_matching payment period_
_minor party_
_municipal fund_
_nonmulticandidate committee_ (request by website user)
_Net outstanding campaign obligations (NOCO)_
_new party_
_Presidential Election Campaign Fund_
_Qualified campaign expense_
_Written instrument_
_family_
_collecting agent_ (user suggestion)
_reason to believe_ (user suggestion)

- [x] Get OGC approval for any definitions that don't have approved language.

### Future work
- When OGC returns comments, move to #3221  to update glossary for both cms and eregs, aiming from 10.6 (will need PRs).

**Comment by johnnyporkchops** [comment]
Reminder: `terms.json` needs to be updated in both CMS and EREGS repos.

**Comment by dorothyyeager** [comment]
Thanks @johnnyporkchops This task is for the end of the PI, but hoping I can touch base with you when we're ready to do that. The last time we added words to it (a year ago or so), we only updated in the CMS repo.

**Comment by dorothyyeager** [comment]
@kathycarothers and I split up the list for drafting and we're working on that now. We also found a list of suggested additions over the past year (there were only two), so I've edited the completion criteria to add those terms to the list as well.

**Comment by dorothyyeager** [comment]
@kathycarothers and I are balancing out our assignments. She'll finish up drafting today and get to content team.

**Comment by kathycarothers** [comment]
I have sent the terms to the content team for review with a deadline for Monday morning.

**Comment by dorothyyeager** [comment]
Based on a few comments (mine, sorry) - we're going to keep working on this into 10.5. Need to talk to George about a few items.

**Comment by kathycarothers** [comment]
Content team has approved and Dorothy plans to send to OGC later today.

**Comment by dorothyyeager** [comment]
And they've been sent! I think we're ready to close this ticket and pick up the work in #3221 when OGC returns their comments. Their suggested deadline is November 29.
