### ISSUE TITLE
Find home for data tutorial 

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#2861]
**What we are after**: Provide help with  how to download and use .fec  file.

**Why we are after it**: Users would like to understand how to download and use .fec (and .csv) files of campaign finance report.

**Completion criteria**:
- [x] Find a temporary home of the content
- [x] Review content
- [x] Create Wagtail page
- [x] Publish page

**Comment by dorothyyeager** [comment]
Have talked with Press and Public Records offices and both are OK with this new page living in the introduction-campaign-finance section. It will be linked off a new section of https://www.fec.gov/introduction-campaign-finance/how-to-research-public-records/.

**Comment by dorothyyeager** [comment]
Current content is at https://classic.fec.gov/press/data_tutorials.shtml

**Comment by dorothyyeager** [comment]
Took a look at the classic page content and updated text for our content guide rules (no directional language, sentence case, etc.). @PaulClark2 will this work? If so, I'll go ahead and create the page (I'll turn on the button that will show the contact page link). In meantime, will upload related files to CMS.

Text for new page:

**Locating, downloading and exporting raw data files (.FEC Files)**

This tutorial provides written instructions on how to download and use .FEC files, the agency's raw data files containing campaign finance data.

_Internal button text with link to PDF_: Download written instructions

.FEC file templates: These are in .xlsx format. Do not use these templates for 30-Day Post-Election reports.
- House candidate committee (Form 3) raw data template
- Senate candidate committee (Form 3) raw data template 
- Presidential candidate committee (Form 3P) raw data template
- Party and PAC (Form 3X) raw data template

For 30-Day Post-Election reports only, please use these specific templates (in .xlsx format):
- House candidate committee (Form 3) raw data template
- Senate candidate committee (Form 3) raw data template
- Presidential candidate committee (Form 3P) raw data template

**Comment by PaulClark2** [comment]
@dorothyyeager That works!

**Comment by dorothyyeager** [comment]
The page is live now at https://www.fec.gov/introduction-campaign-finance/data-tutorials/. From the home page, people can get to it quickly by scrolling to just below the candidate map, clicking "Learn more about using the FEC's campaign finance data" and then selecting "data tutorials" from the left hand side.

Work is done for this stop gap page, so closing this particular issue. See #2858 for the next steps.
