### ISSUE TITLE
Candidate links on raw filings datatable 404

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2865]
Candidate links on the raw filings page will 404. The links seem to be incorrect, as the candidate links are directing to the `/committee/[candidate_id]` path when it should be going to the `/candidate/[candidate_id]` path.

https://www.fec.gov/data/filings/?data_type=efiling

<img width="1250" alt="Screen Shot 2019-04-26 at 10 06 34 AM" src="https://user-images.githubusercontent.com/12799132/56813503-0e93b180-680b-11e9-8a91-b03bc7d84d49.png">

**Comment by johnnyporkchops** [comment]
Based on second bullet point here: https://github.com/fecgov/fec-cms/pull/2975#issue-289361454,
Should we also change this disclaimer text to say `filer's` instead of `committee's` ?
![filers](https://user-images.githubusercontent.com/5572856/59862630-20985900-9351-11e9-82c4-0c91542033d3.png)

**Comment by johnnyporkchops** [comment]
**Many of the newly filed Committees 404 on All Filings > Raw as well:** 

![comm-404](https://user-images.githubusercontent.com/5572856/60136302-cabd1a00-9771-11e9-803b-9f72c43616a1.png)

**Comment by johnnyporkchops** [comment]
Should we reconsider not-linking candidates and possibly committees for `All Filings > Raw` data:
1)  We know that some (and often several) of the links on this table will 404. So we are asking the user to take a chance with a link. It may work it may not.
2)  The broken links mostly have to do with recent filings, which show first. This means that the initial view presented to the user upon visiting this page will always have broken links.
3)  This is `Raw` filings. All we can guarantee here is that a form has been submitted by whom. It seems totally reasonable to only link the Form and not the comm/cand.
4)  Maybe less important, clicking through from a result-row for a `Raw filing`  might take one to a comm/cand profile page that does not reflect changes that the filing they are viewing would apply, once processed.

**Comment by lbeaufort** [comment]
@johnnyporkchops these are great points. I defer to @JonellaCulmer on what the most user-friendly behavior is. 
One option from a technical standpoint is to redirect to the filed form where there is no candidate/committee info. 

I wouldn't want these questions to block fixing the links we can serve up though - I think it makes the most sense to send F2's to the candidate profile pages and deal with the 404s in a follow-up issue.

**Comment by johnnyporkchops** [comment]
@lbeaufort, Redirecting when comm id starts wit H,S,P  (or just F2) will allow us to  fix some of the Raw filings candidate links, but there will still always be broken links among those as well. Which I think leads back to the my original concern of inconsistent experience.

**Comment by johnnyporkchops** [comment]
@lbeaufort. I was not sure what you meant by this:
"One option from a technical standpoint is to redirect to the filed form where there is no candidate/committee info."
