### ISSUE TITLE
Show most recent filings on candidate profile filings tab

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#2866]
**What we are after**:  As an interested citizen , I want to see most recently filed candidate statements so that I can learn more about a particular election or race. 

**Why are we after it**: We would like to make it easier for users to find most recently filed candidate statements. We would like the the candidate profile page's file tab to have similar behavior as the committee profile page's  filing tab. 

**Completion criteria**: 
- [x] Display most recently filed candidate statements on Candidate Profile page filing tab
- [x] Make it easier to find candidate statemetns
- [ ] Make Candidate Profile page's filing tab behave like Committee Profile page's filing tab

**Examples**:
Candidate Profile
![image](https://user-images.githubusercontent.com/11817734/56813498-0b002a80-680b-11e9-982c-8aa372eab298.png)

Committee Profile
![image](https://user-images.githubusercontent.com/11817734/56813567-3a169c00-680b-11e9-8f12-885340f6d451.png)

**General technical**
- front-end work
- back-end work
- Also see, https://github.com/fecgov/fec-cms/issues/2865

**Technical steps**
TBD

**Comment by patphongs** [comment]
After preliminary investigation, it appears that we are only providing raw filings information on committee profile pages:

https://github.com/fecgov/fec-cms/blob/9135f92e6b3d6158b5186d10c1fb8651353963a0/fec/data/views.py#L421
