### ISSUE TITLE
Premature "trouble processing" error on datatables

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2867]
Related work: https://github.com/fecgov/fec-cms/pull/2853

**What we're after:** While testing the front-end implementation of the 2-year restriction lift, I came across a significant number of errors, particularly when changing the selected filters. 

We need to investigate this possible front-end bug a little more to understand why, when a query is still running is a "trouble processing" error displaying in the datatables. It appears that the code (looks like: `DataTable.prototype.fetch`  in `tables.js`) that triggers the error is "jumping to conclusions" even when it's not necessary for it to display. We see this most often when a user removes a filter criteria during an ongoing or search in-progress.

Preliminary documentation of some of these instances is in the [testing notes doc](https://docs.google.com/document/d/1pebeE1oEvnqJS3dUKZ5vIYzlJzFpj-vsQtomqdyQ5yM/edit#).

**Completion criteria:**
- [ ] Investigate and make a recommendation for a fix
- [ ] Fix

**Comment by patphongs** [comment]
New error states have been drafted within this ticket: https://github.com/fecgov/fec-cms/issues/2811#issuecomment-488786938. Closing in favor of that implementation ticket.
