### ISSUE TITLE
Calendar not showing properly in Internet Explorer

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2870]
**What we're after** A working calendar. Some users, including FEC staff, must use IE as their default browser, so we need the calendar to work in IE.

**Background** 
From an OGC staff member; I also experienced the same result when I tested it so that's my screenshot.

> Good morning,
I’ve been meaning to let you know about an issue I’ve encountered lately when accessing the FEC site using IE: the Calendar link (upper right, next to the glossary and search box) doesn’t work.  When I click I get this:
 
![image](https://user-images.githubusercontent.com/24437369/56902790-00db6780-6a69-11e9-9a01-537f69759dbe.png)

> In Firefox I have no problem getting the calendar page and all the filters.

From Dorothy: I noticed that the updates feed on the home page does not show the next event for each category in IE. This is also drawn from the calendar and possibly related.

![image](https://user-images.githubusercontent.com/24437369/59055664-5c68f400-8864-11e9-8835-26b611f4902b.png)

**To do:**
- [ ] Find the problem with IE showing the calendar and populating the updates feed on home page..
- [ ] Fix the problem so IE shows the calendar and populates the updates feed on home page.

**Comment by rfultz** [comment]
May be solved by https://github.com/fecgov/fec-cms/pull/2957
![image](https://user-images.githubusercontent.com/26720877/60125664-47dc9500-975a-11e9-9f46-8b110484a38a.png)

**Comment by dorothyyeager** [comment]
I reviewed #2957 PR. While it had some other things to resolve regarding other connected issues, it did correct the issues noted in this ticket.
