### ISSUE TITLE
Lift 2 year restriction on disbursements (schedule_b) datatable

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2871]
**User story:** 
As a data user, I need to be able to increase my time period selection filter larger than a single 2 year time period for disbursements data so that I can view and filter data for that expanded time span.

https://www.fec.gov/data/disbursements/

**Completion criteria:**
- [x] @JonellaCulmer please attach your design mock-ups for disbursement filters
- [x] Update TRANSACTION TIME PERIOD label to what is reflected in the mock ups (report year filter)
- [x] Add report year to the datatable data
- [x] Change transaction time period to be multi select
- [x] Open beginning and ending transaction dates to wider date ranges
- [x] Deploy PR to feature space to test disbursement datatable data
- [x] Update feature space to point to stage environment to test using API umbrella caching

**Comment by JonellaCulmer** [comment]
@patphongs Here are the notes from our disbursement discussion yesterday:

Disbursement data table
- All years on default
- Need all report time period chiclet
- All years chiclet goes away if user selects any specific report time period(s). Chiclet is automatically replaced by that/those time period(s).
- All years chiclet would return automatically after user deselects all time periods 
- Add tooltip for “Report time period” that says: “The two-year period in which the transaction was made.”
- Disbursement date range
- Report time period


### Disbursement datatable filter panel
<img width="248" alt="Screen Shot 2019-05-02 at 10 09 02 AM" src="https://user-images.githubusercontent.com/31663028/57081249-58284480-6cc2-11e9-8ae6-cf92912b3eb7.png">

**Comment by AmyKort** [comment]
Do we want to move this to 9.1 for now?

**Comment by patphongs** [comment]
Thanks @AmyKort for flagging this. I have moved this to 9.1 since I'll need another sprint to get things finalized.

**Comment by patphongs** [comment]
@lbeaufort @JonellaCulmer and have a plan to help take care of null disbursement dates appearing at the top of the sort. This requires turning on the `sort_nulls_last` option. We agreed that these null values should not hold up or be a blocker for getting this work merged in. The issue has been logged here: https://github.com/fecgov/openFEC/issues/3775
