### ISSUE TITLE
Draft new H4CC pages on debts and recordkeeping for publicly funded campaigns

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2879]
**What we are after:**
Presidential campaigns need guidance too. In past issues, we've identified resources for it and made a list of new pages we need to create. This ticket is to create new pages that will go in the H4CC candidate debts and recordkeeping buckets. (Note: the debt page is limited to Part 116 considerations for publicly funded candidates; there will be audit/repayment pages in the upcoming buckets we'll create for presidential public funding.)

**Past work:** #2651 (resources gathered), #2769 (new pages listed), #2807 (work plan for new pages)

**To do**
- [x] Find approved language (will need to go through Guides and other sources) 
- [x] Draft content in a Word doc for new debts page; note source of content
- [x] Circulate to Information Division and content team for review and comment.

**Future work**
-NEXT Ticket: Circulate to stakeholders in #2922  along with the other new pages listed in that issue
-When comments are back, create and publish the pages, and add links to collection page for candidates.

**Comment by dorothyyeager** [comment]
Beginning legal research needed for the debt page. One note: this is for the page that will just note special concerns under Part 116 of FEC rules for publicly funded campaigns. Things that relate to the audits and repayment process will end up on their own pages in the forthcoming buckets for public funding.

**Comment by dorothyyeager** [comment]
Looks like the debt page will actually be pretty short! But I did notice one thing - we have no page for any kind of candidate that talks about assuming debts of an affiliated committee. This might be worth adding (especially as its something that publicly financed candidates can't do) and there is approved language in the guide to work with. Thoughts @AmyKort @bmathesonFEC @kathycarothers ??

**Comment by AmyKort** [comment]
I defer to the program office folks on this one. Thanks!

**Comment by kathycarothers** [comment]
Let's add it since we have the language.

**Comment by dorothyyeager** [comment]
I'll put in a ticket on it separate from the presidential work. It won't take long to finish since it's approved language.

**Comment by kathycarothers** [comment]
Sounds good.

**Comment by dorothyyeager** [comment]
Due to vacations and other work, we're going to split off drafting the recordkeeping page into its own ticket.

**Comment by dorothyyeager** [comment]
I've completed the first draft of the new debts for the publicly funded presidential candidates page. It's been sent around to the content team for review. Edits will be implemented and the revised completed draft will be circulated to stakeholders in #2922
