### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#2885]
**Thank you for your interest in helping improve the FEC CMS.**

Below, you'll find questions to help us visualize your request.

### Summary

_Briefly describe what you'd like to see changed._

### Proposed Behavior / Feature

_What were you expecting to happen?_

### Current Situation

_What actually happened?_

### Use Case

_Who would benefit from this requested feature?_

### Misc

_If you'd like to include anything else that may be of interest, do that here._

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Can this be closed?
