### ISSUE TITLE
9.1 Redirect Work

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2890]
What we are after
Making sure that the website users are getting the latest and most up to date content, while moving towards getting content moved from transition to fec.gov

Redirect spreadsheet for PI9: 
https://docs.google.com/spreadsheets/d/1Jn5nC3fFku10RTCP5OAW6RiffjNBE4VwBubITQpCNK8/edit?usp=sharing

Redirect work to do in 9.1:
- [x] Put in redirects in proxy and wagtail for the following pages
- /info/publications.shtml redirect to https://www.fec.gov/help-candidates-and-committees/guides
- /pages/brochures/brochures.shtml redirect to https://www.fec.gov/help-candidates-and-committees/guides
- /pages/brochures/contrib.shtml redirect to https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts
- /pages/brochures/contributions_brochure.pdf redirect to https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts
- /pages/brochures/contributions_brochure_spanish.pdf redirect to https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts
- /pages/brochures/volact.shtml redirect to https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/volunteer-activity/
- /pages/brochures/volunteer_activity_brochure.pdf redirect to https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/volunteer-activity/
- /pages/brochures/volunteer_activity_brochure_spanish.pdf redirect to https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/volunteer-activity/
- /pages/brochures/internetcomm**.pdf** redirect to https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts (We redirected the shtml page but not the PDF one. We do have a Wagtail redirect for this but will need the transition one.)
- [x] Test redirects after they are merged
- [x] If working, make ticket for front-end to delete the files from transition

**Comment by kathycarothers** [comment]
Have sent this for review to @dorothyyeager and @patphongs

**Comment by kathycarothers** [comment]
Wagtail has been updated too. Just waiting for them to be merged now. Google Redirect 9.1 document has been updated to reflect these changes.

**Comment by kathycarothers** [comment]
Will be merged tonight 5/28 and review will be tomorrow

**Comment by kathycarothers** [comment]
Redirecting are working. @dorothyyeager is making the ticket for them to be taking down. We can close this ticket.

**Comment by dorothyyeager** [comment]
We've put in a ticket for the front end to remove the redirected pages. We will also need to put in a ticket for the content team to update pages that were linking the contributions and volunteer activity brochures, to remove those links (since they now will just circle back to the page they came from).

Closing this issue as work is complete.
