### ISSUE TITLE
Draft content for new page in Candidate H4CC for partnership contributions

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2891]
**User story:** Partnerships give to campaigns too, so campaigns and partnerships need to know those rules.

**What we're after** A new home for the information currently in the partnerships brochure at https://transition.fec.gov/pages/brochures/partner.shtml within the candidate section. This information is needed by all types of campaigns but only exists in limited form on https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/who-can-and-cant-contribute/#who-can-contribute. It can also serve as a home for a reporting example.

**NOTE:** The Information Division will assign a specialist to do the initial drafting.

**To do**
- [x] Draft content for new page (using approved language but made applicable to all types of federal candidates so it fits in with our new content forthcoming for presidential campaigns)
- [x] Content team review

Future work:
- [ ] Circulate to OGC with the other new H4CC pages being drafted in 9.1 through 9.3.
- [ ] Create the new page (child page of /help-candidates-and-committees/candidate-taking-receipts/)
- [ ] Second pair of eyes
- [ ] Publish the new page
- [ ] Remove duplicative content from https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/who-can-and-cant-contribute/#who-can-contribute and insert button linking to new page
- [ ] Add the link to new page to the collection page at https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/
- [ ] Add the new page to our [spreadsheet created for PI 9 redirects](https://docs.google.com/spreadsheets/d/1Jn5nC3fFku10RTCP5OAW6RiffjNBE4VwBubITQpCNK8/edit?usp=sharing)

**Comment by dorothyyeager** [comment]
Taking me off this ticket and assigning @kathycarothers as she's the one assigned to do the drafting.

**Comment by kathycarothers** [comment]
Working on a Word draft

**Comment by kathycarothers** [comment]
Word draft almost ready for content team. Hoping today 5/28.

**Comment by kathycarothers** [comment]
I have sent this doc over to the content team for review.

**Comment by kathycarothers** [comment]
Sending out draft for one last look from content team before getting it ready for OGC.

**Comment by kathycarothers** [comment]
Closing this issue. Drafting is complete and we'll circulate this draft to OGC, Press, Audit and Info in 9.4 as part of #2922
