### ISSUE TITLE
Take pages off transition that were redirected in 8.7

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2893]
**What we're after:** 
Getting outdated content off the site and directing users to current content

**To do:**
- [x] Remove the following pages redirected in 8.7 (See #2837) from transition:

/info/articles/ and all files in it
/pages/brochures/citizens.shtml
/pages/brochures/citizens_guide_brochure.pdf
/pages/brochures/citngui1.shtml
/pages/brochures/contriblimits.shtml
~/pdf/forms/fecfrm1nc.pdf~
~/pdf/forms/fecfrm1party.pdf~
~/pdf/forms/fecfrm1ssf.pdf~

**Comment by dorothyyeager** [comment]
Taking the three PDF forms off the list as they were removed in a previous sprint. Thank you @rfultz for taking this on this sprint...

**Comment by rfultz** [comment]
@dorothyyeager, these have been removed—ready for your sign-off

**Comment by dorothyyeager** [comment]
Looks good! Redirects are working well. Good to get some of these old pages taken off. Thank you @rfultz and closing issue since work is complete.
