### ISSUE TITLE
Add separate two-year-period dropdown for raising/spending election profile pages

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2903]
### Summary

**What we're after:**
_As a data user, I need to under the time period context of raising and spending data figures so that I can more accurately understand the totals._

For a short-term solution, while the backend team is working on allowing for full election totals, we should add a separate two-year-period dropdown for the raising/spending section of the election profile pages.

<img width="302" alt="Screen Shot 2019-05-16 at 12 33 32 PM" src="https://user-images.githubusercontent.com/12799132/57871240-e3cbc600-77d6-11e9-854e-121c49e9fa10.png">

### Completion criteria

- [ ] Add two year period dropdown
- [ ] Trigger raising/spending datatables based on two-year-period dropdown

**Comment by johnnyporkchops** [comment]
@patphongs, can you list a few example pages for the `raising/spending election profile pages` you refer to in this issue?

**Comment by patphongs** [comment]
@johnnyporkchops It appears that all the other datatables are functioning based on full election totals, except for the individual contributions. So that table would need to have it's own two-year period drop down box so that users know they can select two year increments.

https://www.fec.gov/data/elections/president/2020/#individual-contributions

**Comment by lbeaufort** [comment]
@patphongs it looks like individual contributions are also calculating full election totals. I will plan to QA the data on the API side, but it doesn't look like we need to make a front-end change. I'm going to incorporate my testing in the ticket for https://github.com/fecgov/openFEC/issues/3777.

I apologize for missing this functionality!

**Comment by dorothyyeager** [comment]
Ticket no longer needed after further research so closing.
