### ISSUE TITLE
Research: Where contributions come from initial UI on raising by the numbers page

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2904]
### Summary

As a starter, we need to copy the candidate individual contributions map on the election profile pages onto the raising-by-the-numbers page. Make it clear that this is based on 2 year cycle data.

<img width="525" alt="Screen Shot 2019-05-16 at 12 39 23 PM" src="https://user-images.githubusercontent.com/12799132/57871604-a87dc700-77d7-11e9-9839-85d1f0eb42d9.png">

### Completion criteria

- [ ] Take a look at the code for the maps on the election profile page individual contributions map
- [ ] Find a way to import that map onto the raising-by-the-numbers where contributions come from section

**Comment by JonellaCulmer** [comment]
Closing this in lieu of https://github.com/fecgov/fec-cms/issues/2929
