### ISSUE TITLE
Mockup "where contributions come from" for raising: by the numbers page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2906]
### Summary

**What we're after:**
In an effort to increase the use of data visualizations on our website and improve navigation to our contribution charts on election profile pages, we would like to use these same maps on the raising: by the numbers page and allow our users to see contributions going to candidates. 

It still needs to be determined what our MVP state will look like and whether that includes single candidate views, or a candidate comparison. Some questions that we still need to answer:
 - We need a default state. What does that look like?
 - Are we allowing for the comparison of two candidates?
 - Are we including all candidates? By office? By party?

### Completion criteria
- [x] Schedule a discussion to decide what MVP state should be
- [x] Mockup what that map/chart/visualization will look like and potential options
- [ ] ~Consider changing gradient scale. Is this necessary for an MVP?~
- [x] Discuss preliminary mocks up with the team including PMs
- [x] Discuss front-end and back-end requirements with devs
- [x] Update mock-ups based on discussion with PMs and devs
- [ ] Move to an implementation issue

### Future work

_Create implementation issue._

**Comment by JonellaCulmer** [comment]
Below is a first draft of the where contributions come from chart. I've made some assumptions about what we want to show and think this is a good starting point for a conversation and to make sure we're all on the same page about the MVP we hope to achieve this PI. 

cc: @AmyKort @PaulClark2 @patphongs @lbeaufort @dorothyyeager 

<img width="904" alt="Screen Shot 2019-05-24 at 12 59 13 PM" src="https://user-images.githubusercontent.com/31663028/58344502-ddb39600-7e23-11e9-90f9-f972a2ef6e9e.png">

**Comment by AmyKort** [comment]
This looks great @JonellaCulmer . For our first iteration, are we looking at just providing presidential information? Or would users be able to choose House or Senate candidates via the same chart, like on the Who's raising/spending the most chart?

**Comment by patphongs** [comment]
This is a good start @JonellaCulmer. Leaving some comments here and adding on to what @AmyKort noticed too.
- Are we allowing them to choose from our full list of candidates?
- Is the intention to only allow results for active candidates in a chosen election year? Given that we're keying off `running in` for election year, it appears they need to be active?
- These filters are dependent on each other. They may need to choose a candidate first in order for us to populate the election year drop down. In addition, some candidates only ran in specific years. But are we keying off all the office election years rather than the candidate's election years? If we're showing all office election years, they may get more no results if the user doesn't know which election year the candidate ran in.
- Can you mock up error and no data states?

**Comment by JonellaCulmer** [comment]
Based on our conversation from today @patphongs has documented all of the APIs where data needs to come from for this chart to work properly. 
<img width="1656" alt="Screen Shot 2019-05-28 at 3 38 21 PM" src="https://user-images.githubusercontent.com/31663028/58509421-833c7180-8164-11e9-9cd1-0edddd74ba64.png">

Additionally, some design action items have come out from the discussion:
- [ ] Incorporate a way for the user to confirm that they are looking at the candidate they are interested in, in the event that a user has started to look at a candidate, but did not finish typing in the name or hit submit/enter.
- [ ] Design for error state: Candidate does not exist
- [ ] Design for error state: No data for that candidate

**Comment by JonellaCulmer** [comment]
Below are some updated mock-ups that incorporate the above completion criteria: 
- Incorporate way for user to confirm they are looking at a specific candidate
- Error state for when candidate does not exist
- Error state for when there is no data for that candidate. 

While I still need a content review on the language used for the errors, this is how it could look with them in place. 

### Normal/success state
![Screen Shot 2019-05-30 at 12 11 42 PM](https://user-images.githubusercontent.com/31663028/58647045-b56ce100-82d4-11e9-987b-adf28c7ab69a.png)

### Normal search state
![Screen Shot 2019-05-30 at 12 11 51 PM](https://user-images.githubusercontent.com/31663028/58647060-ba319500-82d4-11e9-8dbd-94853416b384.png)

### Error state for no data
![Screen Shot 2019-05-30 at 12 12 00 PM](https://user-images.githubusercontent.com/31663028/58647079-c3bafd00-82d4-11e9-9dca-33d7a71ffebf.png)

### Error state for missing candidate
![Screen Shot 2019-05-30 at 12 12 11 PM](https://user-images.githubusercontent.com/31663028/58647089-c87fb100-82d4-11e9-987b-58be3467ad59.png)

cc: @AmyKort @jwchumley @PaulClark2 @lbeaufort @dorothyyeager @patphongs

**Comment by dorothyyeager** [comment]
For the "error state with no data" message, just a small tweak to suggest...
"There is no YYYY financial data for this candidate. Try searching a different **election** year." (Or election cycle, whatever matches data better.)

For the "Error state for missing candidate" - The message is fine, but there's a typo - should be "candidate ID"

**Comment by AmyKort** [comment]
Looks great! Do we need to lower-case "President" in "Candidate for President"--in the success state?

**Comment by patphongs** [comment]
@JonellaCulmer Thanks for the new mock ups. I have a question about the error state for missing candidate. Aren't we going to force a candidate pick from the dropdown? So there would never be an instance where they can just type a random name or committee ID to pick. Otherwise, I'm not sure how we would present them with multiple candidate options. See implementation on this IE page under `Candidates mentioned` expando, CANDIDATE NAME OR ID field. This one also forces to pick a valid candidate. https://www.fec.gov/data/independent-expenditures/?data_type=processed&is_notice=true

**Comment by JonellaCulmer** [comment]
@patphongs Happy to talk through that today, but I'd argue that the interaction isn't great because it doesn't tell the user what happened or why their search didn't go through. Certainly could be the MVP implementation though and test from there to see how users interpret that interaction.

**Comment by patphongs** [comment]
> Happy to talk through that today, but I'd argue that the interaction isn't great because it doesn't tell the user what happened or why their search didn't go through. Certainly could be the MVP implementation though and test from there to see how users interpret that interaction.

Thanks @JonellaCulmer! Just backfilling our convo here. So we'll have the candidate error pop up whenever someone submits something that is not a valid candidate name or candidate ID in the list.

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation ticket: https://github.com/fecgov/fec-cms/issues/2929
