### ISSUE TITLE
Update Org Chart (05/28/19 go live date)

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#2912]
### Summary

**What we're after:**
We need to update the Org Chart to list "Tony Baptiste" as the "Acting Inspector General." This appointment takes effect *May 28*, so that's the day we want the change to the org chart to take effect. More information is available here https://www.fec.gov/updates/fec-names-tony-baptiste-acting-inspector-general/

### Related issues

None

### Completion criteria

- [x] Change "Vacant" "Inspector General" to "Tony Baptiste" "Acting Inspector General"
- [x] Make sure to keep the footnote

### Future work

The link from the Inspector General box on the org chart takes users to the OIG pages. We can update this page as a separate stream of work.

**Comment by patphongs** [comment]
These changes have been made and deployed today: https://transition.fec.gov/about/offices/offices.shtml
