### ISSUE TITLE
Remove SSFs and Leadership PACs from receipts/individual contribution datatables

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2913]
@dorothyyeager commented on [Thu May 23 2019](https://github.com/fecgov/openFEC/issues/3787)

**User story** I was trying to search all contributions made to corporate SSFs in 2019-2020 and set filter accordingly. The results appeared to yield a list of contributions made to all types of committees. The first results in this screenshot, for example, show contributions to a candidate and to a labor organization SSF.

![image](https://user-images.githubusercontent.com/24437369/58269577-dfaf2380-7d55-11e9-9512-a6d549db7d45.png)

**To do**
- [ ] Remove SSFs and Leadership PACs from receipts/individual contribution datatables

---

@lbeaufort commented on [Thu May 23 2019](https://github.com/fecgov/openFEC/issues/3787#issuecomment-495299030)

Thanks for entering this issue, @dorothyyeager! After speaking with @PaulClark2, we need organization type and designation in addition to committee type to filter by SSF's and Leadership PACs. We'd need to add these to Schedule A in order to filter by them, which is a big lift. 

For now,  think we should remove those options from the receipts/individual contributions datatables, since they don't work.

---

@lbeaufort commented on [Thu May 23 2019](https://github.com/fecgov/openFEC/issues/3787#issuecomment-495299363)

I'll go ahead and copy this to the CMS to remove the filters as a short-term workaround.

**Comment by dorothyyeager** [comment]
Thanks @lbeaufort !!

**Comment by lbeaufort** [comment]
Follow-up API issue to add the filters to Schedule A: https://github.com/fecgov/openFEC/issues/3787

**Comment by lbeaufort** [comment]
From the PACs dropdown, remove:
<img width="382" alt="Screen Shot 2019-06-04 at 10 44 42 AM" src="https://user-images.githubusercontent.com/31420082/58888716-d4dd8280-86b5-11e9-946b-c8547d4b320e.png">
<img width="374" alt="Screen Shot 2019-06-04 at 10 44 27 AM" src="https://user-images.githubusercontent.com/31420082/58888726-d7d87300-86b5-11e9-8dac-fb409a02a56a.png">
