### ISSUE TITLE
Front End- Take 9.1 redirected pages off transition

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2920]
### Summary

**What we're after:**
Various transition pages were taken down in 9.1 and it's time to take them off transition site.

### Related issues

- #2890

### Completion criteria

- [ ] Remove the following from transition:
/info/publications.shtml 
/pages/brochures/brochures.shtml 
/pages/brochures/contrib.shtml 
/pages/brochures/contributions_brochure.pdf
/pages/brochures/contributions_brochure_spanish.pdf
/pages/brochures/volact.shtml
/pages/brochures/volunteer_activity_brochure.pdf
/pages/brochures/volunteer_activity_brochure_spanish.pdf
/pages/brochures/internetcom.pdf

**Comment by rfultz** [comment]
@dorothyyeager @kathycarothers, I didn't find /pages/brochures/internetcom.pdf. ?

**Comment by kathycarothers** [comment]
I think the link might be wrong. I think it is this

/pages/brochures/internetcomm.pdf

**Comment by rfultz** [comment]
Kathy says we're good so I'm closing
