### ISSUE TITLE
Research informing users of 7:30pm data cutoff 

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/fec-cms#2924]
**Thank you for your interest in helping improve the FEC CMS.**

Below, you'll find questions to help us visualize your request.

### Summary
Filings received after 7:30 pm won't appear on the website--in visualizations or data tables--the next business day. To make sure users understand what data they are looking at, we need to inform users about this limitation. This limitation applies across the site, and is most likely to confuse users the day after a filing deadline.

We need to develop a way to inform users about this potential data limitation.

### Proposed Behavior / Feature

- [x] Identify a quick-win method of informing users of our data limitation
- [x] Develop language for explanation
- [ ]  Make followup ticket for front-end implementation
- [x]  Make followup ticket for larger fix. 
https://github.com/fecgov/openFEC/issues/3800

**Comment by lbeaufort** [comment]
@AmyKort and @PaulClark2 are happy to help with this research task

**Comment by kathycarothers** [comment]
I have a meeting set-up with Amy and Paul for Thursday 6/20.

**Comment by kathycarothers** [comment]
Draft language:

Newly filed summary data may not appear for up to 48 hours.

Sent to the content team for review with a deadline of 1 pm tomorrow. 

@AmyKort, @PaulClark2

**Comment by kathycarothers** [comment]
Closing out this ticket and work will continue in ticket #2986
