### ISSUE TITLE
Add filter for active candidate to "All Candidates" and "House/Senate Candidates" datatables

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2927]
**User story:** As a data user, I want to be able to compare candidate lists and quickly identify active and inactive candidates, so that I can make sure that I'm up to date on who's running.

**Possible solution:** Add a checkbox to filter for active candidates to the  "All candidates" datatables and "Senate/House Candidates" datatables (per @PaulClark2, presidential candidates that drop out aren't marked as inactive so it wouldn't add value to add the filter to the presidential candidate datatables.)

By introducing some filtering here we have the added benefit of keeping up-to-date and accurate candidate listings across datatables, specifically House, Senate and all candidates. 

**Completion criteria**
- [x] Design the filter location/label
- [x] Content/dev review - can the data accomodate the design?
- [ ] Make the change (WIP PR: https://github.com/fecgov/fec-cms/pull/2926)

WIP PR screenshot ideas: 
![Screen Shot 2019-05-30 at 4 35 59 PM](https://user-images.githubusercontent.com/31420082/58663077-a2b8d300-82f9-11e9-94c2-873c8f35ded1.png)
![Screen Shot 2019-05-30 at 4 35 21 PM](https://user-images.githubusercontent.com/31420082/58663081-a4829680-82f9-11e9-9430-c8fdd6170d97.png)

**Comment by JonellaCulmer** [comment]
Below are some preliminary mock-ups of how the filter panels can look with the addition of the candidate status filter. Content needs to review the language of the filters, all the same in each place (House, Senate and All candidates datatables). cc: @AmyKort @dorothyyeager @kathycarothers @bmathesonFEC 

Essentially this filter includes two options, to view all candidates currently active or view candidates no longer seeking office. Selecting active candidates would return one list, selecting no longer seeking would return a second, and selecting neither would return a third, combined list. cc: @lbeaufort 

![Screen Shot 2019-06-06 at 8 42 59 AM](https://user-images.githubusercontent.com/31663028/59033903-e2bb1100-8837-11e9-84c1-152585bfb67e.png)

**Comment by kathycarothers** [comment]
@JonellaCulmer quick question. Why is the "Time period" option just for Senate candidates?

**Comment by dorothyyeager** [comment]
The labeling is clear. I have the same question as Kathy. Also wondering if the time periods should be in order of most recent at the top.

Also wondering if the "date first filed Statement of Candidacy" and the option to filter out the $0 fundraisers should be available in the House and Senate filters too.

**Comment by lbeaufort** [comment]
@kathycarothers @dorothyyeager the "Time period" option is available on the Senate and Presidential datatables. The 3rd screenshot is of the "All candidates" datatable, which doesn't have a time period option - I'm guessing because it doesn't apply to house candidates.

**Comment by lbeaufort** [comment]
@JonellaCulmer is the expected behavior the same for all unchecked and all checked? IE, if no checkboxes are selected, all candidates active/inactive are returned, and if both are checked, all candidates active/inactive are returned?

**Comment by lbeaufort** [comment]
@AmyKort regarding your concern about the legal definition and accuracy of "Active", we could phrase it as candidates that have withdrawn from seeking office, rather than actively seeking office

**Comment by bmathesonFEC** [comment]
I would want to know more about how the Candidate Status label is assigned and how frequently it is updated. Election losers are the easiest for us to identify (but even that is tough sometimes), candidates that drop out are harder to identify, so I'm curious to know how that data field is informed.

Another landmine is presidential candidates' "suspended campaigns." How does the Candidate Status flag approach those?

Regardless, I see no problem with using "Actively Seeking Office."  For the other label I found some precedence for using "former" to distinguish from "current" or "present" candidates/office holders. It's even used in the regs once ([113.1](https://www.fec.gov/regulations/113-1/2019-annual-113#113-1)) and used in @dorothyyeager 's [Record article](https://www.fec.gov/updates/petition-rulemaking-use-campaign-funds-former-candidates-officeholders-2018/) about the petition for rulemaking for "dormant" committees. 

**Former Candidates** is the best I have for now, but I'm curious to learn more about Candidate Status in the database.

**Comment by kathycarothers** [comment]
@lbeaufort Thanks for the explanation for the "Time period" options. I get it now.

**Comment by PaulClark2** [comment]
I'm jumping in late. I have concerns about the 'candidate status` check boxes. The only grouping we can really make is: 1) candidate has filed F2 for this election and 2) candidate has not filed F2 for this election.

**Comment by lbeaufort** [comment]
@PaulClark2 don't we flag when candidates file a F2 and then withdraw from office as inactive in the `cand_inactive` table?

**Comment by JonellaCulmer** [comment]
@kathycarothers @dorothyyeager The time period toggle there is only for Senate candidates because their data crosses over multiple two-year periods. House candidates only cover a single two-year period. You would see the same for Presidential candidates with a time period toggle too, but we're not modifying that datatable this time, so I didn't include it in my screenshots. 

We can talk about the other filters in a separate issue, but we should keep this specific to the active candidate filter work at this time. 

@lbeaufort This doesn't seem like an either/or, true/false issue to me. Unlike the filter for "raised more than $0, users have the potential for three different results. But you have a point about the user going into the exported data and verifying which candidates are which. I think there's still an argument to be able to show that on the front-end and provide users with the ability to see each subgroup.

**Comment by JonellaCulmer** [comment]
As an alternative, we can use radio buttons, which might be a better way to show this data given the three choices. 

<img width="348" alt="Screen Shot 2019-06-06 at 1 27 40 PM" src="https://user-images.githubusercontent.com/31663028/59053212-e0b87880-885e-11e9-8c34-33206a235c57.png">

**Comment by lbeaufort** [comment]
To summarize the data part of @JonellaCulmer and my discussion with @PaulClark2, the `is_active_candidate=true` filter in the API only removes known house/senate incumbents that drop out of the race. 

If a candidate loses the primary or a challenger drops out, they're not coded as inactive.

Therefore, the filter doesn't really show "active candidates" as most people think of them (folks currently seeking office), but removes known incumbents that drop out.

**Comment by JonellaCulmer** [comment]
Updated mockups. Any more thoughts on copy, @AmyKort @dorothyyeager @kathycarothers @bmathesonFEC ?

<img width="666" alt="Screen Shot 2019-06-07 at 10 23 17 AM" src="https://user-images.githubusercontent.com/31663028/59111118-66dfc800-890e-11e9-8a6b-42177329cb98.png">

cc: @PaulClark2 @lbeaufort

**Comment by AmyKort** [comment]
I'm still not comfortable with the "actively seeking office" language. First, I'm not sure it represents what's in the data. And second, I'm worried that users might think that's there to identify folks who are raising money, rather than folks who have dropped out. Do you have any other ideas @PaulClark2 ?

**Comment by lbeaufort** [comment]
@AmyKort @PaulClark2 @JonellaCulmer   
I'm sure content can make it better, but what we're really is 
- "Remove incumbents that have dropped out"
- "Show incumbents that have dropped out"
- "All candidates"

**Comment by dorothyyeager** [comment]
Just a stab at it... thanks @lbeaufort - that helped clarify all of this for me! How about 

- Candidates (excluding incumbents not seeking re-election)
- Candidates  (including incumbents not seeking re-election)
- All candidates

**Comment by dorothyyeager** [comment]
(I realize that's long for a label though.)

**Comment by lbeaufort** [comment]
@dorothyyeager I think it's:

- Candidates (excluding incumbents not seeking re-election)
- Candidates (only incumbents not seeking re-election)
- All candidates

**Comment by PaulClark2** [comment]
@AmyKort @JonellaCulmer I agree with Amy. `Actively seeking office` does not represent that data even for those that are not included in our `inactive candidates` table. We don't know the motivation of anyone that files a Form 2 or forms a campaign. We are asking users to pick one of three buckets: 1) candidates excluding incumbents that have announced they aren't running and the FEC has added to the `inactive candidates` table, 2) incumbents that have announced they aren't running and the FEC has added to the `inactive candidates` table, or 3) all candidates.

**Comment by PaulClark2** [comment]
I think @dorothyyeager and @lbeaufort are on the right track or may have it now.

**Comment by JonellaCulmer** [comment]
Do I have it right?

- All candidates
- Exclude former encumbents
- Show only former encumbents

**Comment by PaulClark2** [comment]
I won't call them `former` incumbents. Incumbency is a little odd because the incumbent is the incumbent until he or she leaves office. For example, an incumbent that has announced she is retiring at the end of her current term (but had filed a Form 2 for the next election) is the incumbent until January after the November general election. If a user is looking at the data at anytime through January following the general election, the incumbent is the current incumbent.

**Comment by PaulClark2** [comment]
These https://github.com/fecgov/fec-cms/issues/2927#issuecomment-499942466 are really more accurate.

**Comment by JonellaCulmer** [comment]
For the all candidates datatable, this will include candidates going back a long ways, yes, who may have "withdrawn"? Do we need to account for them as well? Or are they less relevant to this discussion?

- All candidates
- Exclude previous(?) withdrawn(?) incumbents (default)
- Show only ... incumbents

**Comment by lbeaufort** [comment]
@JonellaCulmer I'm not sure "previous" makes sense here - we have to pass an election year. So, if I'm looking for all candidates in 2020, excluding incumbents that withdrew from the race will hide candidates that were at some point an incumbent for a 2020 seat and withdrew.

So "previous" combined with an election year doesn't really make sense to me.

**Comment by JonellaCulmer** [comment]
Per our discussion, we are going to default to "Exclude incumbents not seeking re-election" as a single option.  Will update the ticket with new mockups.

**Comment by JonellaCulmer** [comment]
@lbeaufort Please see the below updated mock-up for the three datatables. Let me know if you have any questions or thoughts. 

<img width="710" alt="Screen Shot 2019-06-12 at 11 42 48 AM" src="https://user-images.githubusercontent.com/31663028/59365883-5745f200-8d07-11e9-8877-ee2d95d52433.png">
