### ISSUE TITLE
Build Where Contributions Come From Tool

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2929]
**What we're after:**
This ticket involves the front-end development of the Where individual contributions come from. Below is a series of mock-ups of the different states our users will encounter while using this chart. Hopefully we can build the chart and add to the feature space in order to conduct usability testing. 

Endpoints needed: https://drive.google.com/file/d/1t-wmP_LNNvC1yBeQm6HAq3176NYtEcFD/view

### Related issues

_List any relevant related issue(s)_
- https://github.com/fecgov/fec-cms/issues/2906 Mockup "where contributions come from" for raising: by the numbers page
- https://github.com/fecgov/fec-cms/issues/2904 Research: Where contributions come from initial UI on raising by the numbers page
- https://github.com/fecgov/openfec/issues/3777 Change /schedules/schedule_a/by_state/by_candidate/ to have election_full=true capability

### Completion criteria

_List action items that need to be done to complete this task. List in checklist formatting._
- [x] Take a look at the code for the maps on the election profile page individual contributions map
- [x] Find a way to import that map onto the raising-by-the-numbers where contributions come from section
- [x] Build chart based on mock-ups, please note dividing header borders for greater distinction between the sections, update left nav, and if possible, the reintroduction of the reaction boxes 
- [ ] Create pop-up on WCCF with methodology. See https://github.com/fecgov/fec-cms/issues/2929#issuecomment-527451710

#### Normal/success state
<img width="748" alt="Screen Shot 2019-05-31 at 1 22 12 PM" src="https://user-images.githubusercontent.com/31663028/58723276-a9058880-83a7-11e9-935f-913335db3040.png">

#### Normal search state
<img width="754" alt="Screen Shot 2019-05-31 at 1 22 21 PM" src="https://user-images.githubusercontent.com/31663028/58723286-b02c9680-83a7-11e9-87ab-c299c5045753.png">

#### Error state for no data
<img width="749" alt="Screen Shot 2019-05-31 at 1 22 30 PM" src="https://user-images.githubusercontent.com/31663028/58723296-b6227780-83a7-11e9-8419-bbff6db4cc4d.png">

#### Error state for missing candidate
<img width="753" alt="Screen Shot 2019-05-31 at 1 22 38 PM" src="https://user-images.githubusercontent.com/31663028/58723310-bae72b80-83a7-11e9-9799-dd91c5722410.png">

#### Entire Raising: by the numbers page
<img width="457" alt="Screen Shot 2019-05-31 at 1 25 45 PM" src="https://user-images.githubusercontent.com/31663028/58723334-cc303800-83a7-11e9-98aa-f9407cd1b4e3.png">

**Comment by jason-upchurch** [comment]
@rfultz I submitted PR for review to support the "All states" portion of the chart: https://github.com/fecgov/openFEC/pull/3835

**Comment by rfultz** [comment]
(down to getting the datatable to display and refresh its data)

**Comment by rfultz** [comment]
Spent way too much time fighting with datatables; gave up and built my own table; roadblock removed

**Comment by rfultz** [comment]
Implementing error handling, states, messages, and styles

**Comment by rfultz** [comment]
Quick progress update: It works! (Still need to style, break the legend into five…)

![image](https://user-images.githubusercontent.com/26720877/63168650-baebe480-c002-11e9-9883-e3b372f7f892.png)

**Comment by JonellaCulmer** [comment]
The Methodology needed for this work can be found here: https://github.com/fecgov/fec-cms/issues/3123#issuecomment-526207919
