### ISSUE TITLE
Wagtail wish list: Add internal and external link buttons to Record and Example page templates

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2935]
### Summary

Often the content team needs to place links on reporting examples and in Record articles. It would be nice to have the internal and external button features available on those two page templates. 

### Use Case

Doing this would make the links stand out more.

### Completion Criteria

Add the internal button and external buttons to these templates in Wagtail: 
- [ ] Record page
- [x] New example page from (#3149)

Here's a screenshot from a different Wagtail template (Resource page) that has these options:
![image](https://user-images.githubusercontent.com/24437369/64344321-39adbf00-cfbc-11e9-9110-36a62b331583.png)

When opened in Wagtail, here's what they look like:
![image](https://user-images.githubusercontent.com/24437369/64344579-b93b8e00-cfbc-11e9-928f-0f9546aa6703.png)

![image](https://user-images.githubusercontent.com/24437369/64344628-d8d2b680-cfbc-11e9-89da-e425045f848a.png)

Here's what they look like when rendered (both buttons look the same):
![image](https://user-images.githubusercontent.com/24437369/64344419-64981300-cfbc-11e9-880c-f915aac5f3d7.png)

**Comment by rfultz** [comment]
@dorothyyeager for those of us less familiar, could you include screenshot of what you'd like?

**Comment by dorothyyeager** [comment]
@johnnyporkchops is including this work in his ticket on the example template #3149 . Leaving ticket open for Record page update.
