### ISSUE TITLE
Tooltip text on receipts/disbursement 2-year period is incorrect

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2936]
The tooltip text on receipts/disbursement 2-year period is incorrect. 

**Currently** says "The two-year period in which the transaction was **made**."
![Screen Shot 2019-06-03 at 5 35 45 PM](https://user-images.githubusercontent.com/31420082/58836548-170bb300-8627-11e9-97f9-b31c0a1eea28.png)

**Should** say: "The two-year period in which the transaction was **reported**." 

From API docs: All receipt data is divided in two-year periods, called `two_year_transaction_period`, which is derived from the `report_year` submitted of the corresponding form.

**Completion criteria:**
- [x] Check with content to team on the change
- [x] Make the change

**Comment by patphongs** [comment]
done
