### ISSUE TITLE
Some special election candidates linked from election profile 404

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#2937]
### Summary

_Some special election candidates linking from election profile pages 404._

### How to Reproduce

1. Go to this link: https://www.fec.gov/data/elections/house/GA/06/2018/
2. See Candidate financial totals datatable
3. Click on candidate links in the table. Some of the candidates linked will 404, such as OSSOFF, T. JONATHAN and MOODY, DAN._

**Comment by lbeaufort** [comment]
We should check NC 09 and NC 03 special election candidates
