### ISSUE TITLE
SSF label is cut off in dropdown

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#2943]
### Summary

http://localhost:8000/data/receipts/?data_type=processed&two_year_transaction_period=2020&min_date=01%2F01%2F2019&max_date=12%2F31%2F2020
Left column, Receipt Committee Type, PACS
When there's a section title, the scroll bar-type piece overlaps the text of the section title.

### Expected Behavior
I'd like the text not to underlap the interface.

### Browser, device
Mac Chrome 74

### Screenshots
![image](https://user-images.githubusercontent.com/26720877/58969468-c2cb1500-8785-11e9-8243-6033669cdb2c.png)

## Completion Criteria
- [ ] Update styles
- [ ] Test in all browsers (ESPECIALLY IE)

**Comment by rfultz** [comment]
@JonellaCulmer, any style guidance? D'you think it would be enough to bring in the left side of the section text ("Separate segregated funds")? The left edge would be lined up with the left edges of the other items. Or should I indent all of the other items, too?

Also, the background color of the section titles is a pixel or two too wide on the left and one too wide on the right. I'd like to fix those, too. Thoughts?

![image](https://user-images.githubusercontent.com/26720877/66426512-fb9f2300-e9df-11e9-8f32-08e8b4c3a43d.png)

**Comment by JonellaCulmer** [comment]
@rfultz I would indent everything so that we maintain the SSFs as a section "header/divider". 

If you could fix the extra pixels on the right, that would be great!
