### ISSUE TITLE
Ensure webform is one word throughout website

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2946]
### Summary

**What we're after:**
Style consistency. In drafting a Record article, we discovered that while most of the website and publications says "webform" as one word (which is preferred by stakeholders), the forms page says "web form." We need to fix this and any other page using the two-word version.

### Completion criteria

- [x] Edit https://www.fec.gov/help-candidates-and-committees/forms to make "web form" into "webform"
- [x] Do search on website to see if the term appears on any other pages.
- [x] Make the switch on any other pages as needed.
- [x]  Edit the content guide to make sure we've got this in the spelling guidance.

**Comment by kathycarothers** [comment]
The term appeared on 10 different web pages. All pages have been updated. The content guide has been updated to reflect term as one word.
