### ISSUE TITLE
Fix missing column headers

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#2951]
Example: https://fec-stage-proxy.app.cloud.gov/data/receipts/?data_type=processed&two_year_transaction_period=2020&min_date=01%2F01%2F2019&max_date=12%2F31%2F2020

<img width="1057" alt="Screen Shot 2019-06-06 at 4 00 26 PM" src="https://user-images.githubusercontent.com/31420082/59062663-6397fe00-8874-11e9-95e5-565edfb19e77.png">

I think the commit that caused the issue was 2131629df9519833513a8723042f6dac96a56768

**Comment by patphongs** [comment]
This has been fixed and merged in
