### ISSUE TITLE
Column headers missing 

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#2959]
### How to Reproduce

Navigate to any election profile page 

https://www.fec.gov/data/elections/senate/KY/2020/

### Browser

iPad Safari (iOS 12.3.1)

### Screenshots###

![120F006A-07DF-4F1B-ADFF-193622744577](https://user-images.githubusercontent.com/11817734/59314809-f8d82f80-8c84-11e9-9fa5-5d6e0077214a.jpeg)

**Completion criteria:**
- [ ] Fix election profile page
- [ ] Double-check all existing datables in `prod` to make sure they all have headers

**Comment by patphongs** [comment]
@lbeaufort Can you please be our second pair of eyes and inventory all the datatables with this bug? That way we can ensure that all of the datatables in the fix PR #2960 all have headers correctly.

**Comment by patphongs** [comment]
This has been fixed. Closing
