### ISSUE TITLE
Add MUR filter to datatable

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2969]
**What we're after:** Following the design work [here](https://github.com/fecgov/openFEC-web-app/issues/1797#issuecomment-275701188) and the discussion [here ](https://github.com/fecgov/fec-cms/issues/1533#event-2410922983), we need to add time period filters to the MUR search. 

The API work is done: https://github.com/fecgov/fec-cms/issues/1533#issuecomment-354000748

**Completion criteria:** 
- [x] Content review of the language used. Does "Violation time period" make sense? I don't want to say time period since everywhere else we use Time period for a 2-yr period. But maybe there's something better to describe the year or years during which a violation occurred."
- [ ] ~Confirm/determine whether it's a single year or two-year period that we need to search by~
- [x] Update design if necessary
- [x] Add filters to MUR filter panel

### Mockups
<img width="285" alt="Screen Shot 2019-06-13 at 4 17 20 PM" src="https://user-images.githubusercontent.com/31663028/59464564-c8b09e00-8df6-11e9-8d63-126235197ec1.png">

**Comment by dorothyyeager** [comment]
Initial thoughts from content perspective:

- Not all cases turn out to be violations. Sometimes the respondent wasn't actually violating the law and the Commission finds No Reason to Believe. So we definitely do not want to say "violation."

- Cases can span multiple election cycles and years. For example, recently closed MUR 7586 concerned an SSF that violated collecting agent rules for five years. The case didn't even begin until two years after the vioI could see a similar case happening for a party committee that violated allocation rules, or any committee with an embezzled funds issue that goes undetected for a long time.

So I think for re-wording "Violation Time Period" (which I think does need re-wording), I'd suggest "**Case Time Frame (Year(s))**." @AmyKort thoughts?

As far as how you would search for it, I'll take my cues from [MUR 7586](https://www.fec.gov/data/legal/matter-under-review/7586/) again. That case began for the FEC in 2018 when the trade association involved filed a _sua sponte_ complaint to report itself for violations. According to the First General Counsel's Report, the violations began in 2012 and were discovered in 2016 by the trade association. From perspective of someone who searches for these kinds of cases, I'd be looking for "if/when" the case is closed. But if I know that it could be anywhere between 2012 and 2018, I'd want the option to put all of those years in. 

So there's a question - do we want the MUR search to return the years covered by the case or the years that FEC documents are available? In the case of the MUR above, the years covered are 2012 through 2019. FEC documents are dated 2018 and 2019.

I hope this is helpful @jculmer! Let me know if you need anything more content-team-wise.

**Comment by AmyKort** [comment]
What if our first iteration is just this:
![image](https://user-images.githubusercontent.com/13237823/59865422-f21d7c80-9356-11e9-8422-6dd41033756c.png)

**Comment by AmyKort** [comment]
I think that was the request--being able to look up a MUR based on the time frame you think the MUR was opened or closed--just a way to narrow your search. We could see how much that helps users, and we might be able to build on that knowledge to make a smarter filter later. Thoughts @JonellaCulmer and @dorothyyeager ?

**Comment by dorothyyeager** [comment]
@AmyKort I'm good with that, and in that case, all we really need are the two boxes in your comment above (Case close date and case open date).

**Comment by JonellaCulmer** [comment]
Sounds good. Updated mockup below. @AmyKort @dorothyyeager 

![Updated_MUR _filterpanel](https://user-images.githubusercontent.com/31663028/59943046-4e53cf80-942f-11e9-9004-3c9aca607958.jpg)

**Comment by JonellaCulmer** [comment]
@lbeaufort Do you think you have any reason to believe that the previous API work that was done on this can't support the latest mock-up - showing Case open date and Case close date?

**Comment by lbeaufort** [comment]
No reason to believe, thanks for checking. 

**Open date example**
https://api.open.fec.gov/v1/legal/search/?api_key=DEMO_KEY&case_min_open_date=1%2F1%2F18&case_max_open_date=6%2F1%2F18&type=murs

**Close date example**
https://api.open.fec.gov/v1/legal/search/?api_key=DEMO_KEY&case_min_close_date=1%2F1%2F19&type=murs

**Comment by JonellaCulmer** [comment]
@patphongs Please see the updated mockup below based on our discussion to add a bit more clarity and consistency with our other date filter.

![MUR filter panel_finalish](https://user-images.githubusercontent.com/31663028/60541074-bda6aa80-9cde-11e9-8fb3-a130fd0a9e76.jpg)

**Comment by patphongs** [comment]
I've got the logic for the MUR date filter working. The Accordions are giving me trouble though, need to try to resolve the styling in the templates.
