### ISSUE TITLE
Draft Party Reporting Examples for FEA and Registration

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#2974]
### **Summary**
In our first round of publications of party reporting examples we published a set of party reporting examples that were derived from existing PAC examples and added examples for allocated and coordinated expenses. 

In our second round we are going to add examples for FEA and registration, details below.

### Related issues
- Publishing Party Examples: #2824 

### Topics for next round of reporting examples:
- New reporting example for Party Registration
- New reporting example for FEA (all four types, either one consolidate example or four separate examples). Be sure to include clarification of IEs as they relate to FEA (this references our email conversations about 21b vs. 30b in the first round of reporting examples)

**other notes for the first round of drafts**
- Update the earmark example to be as thorough as this outreach Record article: https://www.fec.gov/updates/earmarked-contributions/
- Confer with Info to ensure our redesignation advice in the reporting example is consistent with reporting advice that is provided at conferences (this will affect PAC and SSF examples as well)
- Add links to the coordinated party expenditures page once FEA examples are made.
- Look into adding the adequate/inadequate purpose lists to the IE examples (this affects all IE examples -- PAC and SSF). The adequate/inadequate purpose lists may be useful but the page is designed more for operating expenditures rather than IEs.

### Completion Criteria
- [x] Distribute drafting assignments in RAD
- [x] Draft publication ticket.

**Comment by dorothyyeager** [comment]
Updating on behalf of @bmathesonFEC who is on leave. The drafting has been assigned to various RAD analysts under Brad's supervision. It will continue into 10.5.

**Comment by bmathesonFEC** [comment]
Received several FEA drafts from assigned RAD managers, will review and move on to an implementation ticket. Will be asking @jjonesfec for images next week!
