### ISSUE TITLE
Design new widgets page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2981]
**What we're after:**
Now that we have the [go-ahead from OGC](https://github.com/fecgov/fec-cms/issues/2803#issuecomment-502123285) and updated mock-ups on what the widgets will look like, we need to decide where we want this to live, what information we link to from the widgets, and how we might want to advertise their existence.

### Related issues

- https://github.com/fecgov/fec-cms/issues/2803
- https://github.com/fecgov/fec-cms/issues/2980

### What to think about

- [ ] What kind of page and where do we want the widgets to live? 
- [ ] Do our page templates currently support copy and pasting of embed text? (Need assistance from front-end on this bit.)

**Completion criteria:**
- [x] Mock up page
- [x] Document needs for implementation on wagtail side
- [ ] Create followup implementation ticket to build new wagtail template, or modify an existing template
- [ ] Make a ticket to communicate with external facing offices about advertising the widgets (Press? Info? RAD?)
- [ ] Make a content ticket to draft communications discussed with external offices

**Comment by JonellaCulmer** [comment]
We had a good conversation on Friday about what our needs were for the widgets work. Document link is below: https://docs.google.com/document/d/1mE4Kmub8z8NmJTCYJCDn6i0WEgslxWiYtgA87oqh4AY/edit#heading=h.c8zsx1vlknvm

Next steps are to mock-up what this page might look like. This may contribute to the list of needs in the attached, and as such will be updated as the design process progresses.

**Comment by JonellaCulmer** [comment]
Below is a mock-up of what the widgets page can look like using the custom table template and HTML to embed our widgets onto the page. This mock-up also utilizes a toggle to move between the blue and white versions. I understand that piece may be difficult, so in the end, we may just have to list out each version. 

Some questions still left to answer: 
- [ ] Any criticisms with the url: www.fec.gov/widgets? @AmyKort 
- [ ] What will the content say? Need help from @rfultz @pat and a content team review
- [ ] Where will we link to this page from? Will this sit as an orphaned page unless linked? @AmyKort 

Other than announcements and releases we may use, as well as linking from the embeds themselves, one place we can link from on .gov would be the cards on the data landing page, replacing the external links card, which I don't believe holds as much value. Thoughts? 

### Data landing cards
<img width="1104" alt="Screen Shot 2019-07-18 at 12 45 43 PM" src="https://user-images.githubusercontent.com/31663028/61476140-5cc3d700-a95a-11e9-8c62-e76eb1eeb178.png">

### Page mock-up
![Widgets page_1](https://user-images.githubusercontent.com/31663028/61476194-76fdb500-a95a-11e9-936c-7485bff0dc68.jpg)

**Comment by patphongs** [comment]
Thanks @JonellaCulmer for this mock up, I have a few suggestions:

1. It may be nice to have the embed code within a `<textarea>` in order to add a "copy" button so that the text will automatically be selected rather than having the user select it with their cursor. This will also distinguish the code snippet further.

2. Do you have a font in mind for the code snippet? We'll may need to import a new font set for it

3. It would be nice to have the user be able to see each of the color schemes instead of the toggle. Is there a way for us to give them a bit of a preview or thumbnail on the page? 

4. Should we apply some kind of left nav element on the page since this seems like it may grow be a long page?

**Comment by patphongs** [comment]
Also additional comment about linking the widgets. Would it be worth it to add it in the footer? Since we have other code/development related notes in the far right column

<img width="984" alt="Screen Shot 2019-07-18 at 1 55 03 PM" src="https://user-images.githubusercontent.com/12799132/61482487-bdf2a700-a968-11e9-9bff-1e68017619c8.png">

**Comment by JonellaCulmer** [comment]
@patphongs Sure. 

> It may be nice to have the embed code within a <textarea> in order to add a "copy" button so that the text will automatically be selected rather than having the user select it with their cursor. This will also distinguish the code snippet further.

Is this functionality we can build into a page template? I was going the path of least resistance at this point, but I would absolutely support having this functionality. 

> Do you have a font in mind for the code snippet? We'll may need to import a new font set for it

Yes, Courier.

> It would be nice to have the user be able to see each of the color schemes instead of the toggle. Is there a way for us to give them a bit of a preview or thumbnail on the page?

The toggle was also a way to switch between the different embed codes which would include the coloring. Showing them all takes up a lot of space. Especially if we think about adding other widget types in the future. Perhaps we can talk about this more and you can explain your thinking here.

> Should we apply some kind of left nav element on the page since this seems like it may grow be a long page?

We can. We just need to figure out short ways to explain each widget type. Perhaps by size? Otherwise this is just a matter of changing the page type from Custom to Resource, or Collection, if it can allow for HTML in the section text.

@AmyKort What are your thoughts on adding to the footer? I don't have a real preference either way, but know that we should really only keep it to the necessary content as it seems pretty heavy with links now. Whether the widgets count, I can't judge.

**Comment by AmyKort** [comment]
I'm not sure what's best. I think it would be okay to have the widget info in that column of the footer--it's a logical addition to the list and I don't think it's too much on the footer--especially looking at some other government websites. Does it seem like folks would notice it there? I know anecdotally that folks often don't find our Twitter and YouTube links at the very bottom of the page, and I don't know that folks are looking to our footer for information like this.

**Comment by JonellaCulmer** [comment]
@AmyKort I'm not sure they're looking there either. This is something we can test for in the future. But I'm fine with parking it there if you don't think it's too much. 

Next steps: 
- [ ] Update mock-up to Resource or Collection page, draft short language for each widget type
- [ ] Create text area with copy button to select embed text
- [ ] Show both color mock-ups next to one another. 
- [ ] Mock-up link in footer

**Comment by AmyKort** [comment]
Sounds like a plan. Let's go with that. Thanks!

**Comment by JonellaCulmer** [comment]
Please see the below updates to the widgets page and the footer. cc: @AmyKort @patphongs 
![Resource template - widgets_take2](https://user-images.githubusercontent.com/31663028/61795186-d5aaaf00-adf0-11e9-8eba-da9c4b2d4b06.jpg)
<img width="1014" alt="Screen Shot 2019-07-24 at 8 55 15 AM" src="https://user-images.githubusercontent.com/31663028/61795191-d8a59f80-adf0-11e9-91e9-4b1f66f18969.png">

**Comment by rfultz** [comment]
Not a big deal, but there will not be different embed codes for the different widths. What will be different, though, are 1) the color and whether we're displaying 2) all (federal) elections, 3) only one federal election, 3) all election years, 4) only one election year, or whatever combo of those.

**Comment by JonellaCulmer** [comment]
Thanks @rfultz So really, I can eliminate, say, the medium widgets, since they are essentially the same. Correct?

**Comment by JonellaCulmer** [comment]
After discussion with @rfultz I've removed the "medium" sized widgets. @rfultz If you could tell me the min pixel width, I would appreciate. 

Next steps
- [ ] Update mock-up with corrected min pix width
- [ ] Open follow-up ticket for language (@rfultz and @patphongs) and implementation

Updated design: 
![Resource template - widgets_take3](https://user-images.githubusercontent.com/31663028/61874986-a743d700-aeb7-11e9-9a63-54450998acaa.jpg)

**Comment by JonellaCulmer** [comment]
Updated mock-up with corrected min px width.

![Resource template - widgets_take4](https://user-images.githubusercontent.com/31663028/61953289-07a04a80-af84-11e9-848f-d3b087c4f576.jpg)

**Comment by JonellaCulmer** [comment]
Closing in favor of followup work: https://github.com/fecgov/fec-cms/issues/2909, https://github.com/fecgov/fec-cms/issues/2727, https://github.com/fecgov/fec-cms/issues/2980, and https://github.com/fecgov/fec-cms/issues/2793
