### ISSUE TITLE
Error message appearing incorrectly

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2983]
**What we're after:**
Receive an error message when I should not. Only if there are not required filters applied, and searching more than one two-year period, am I supposed to receive a message that says `You're trying to search across multiple time periods. Filter by recipient name or ID, contributor details, or image number for results.` 

Unfortunately, I'm getting an error when I remove one filter even though another required filter is applied.

**To replicate:**
1. Go to receipts datatable on feature (https://fec-feature-cms.app.cloud.gov/data/receipts/)
2. Under Recipient name or ID, choose "Donald J. Trump for President"
3. Under ZIP code, input 22205
4. Under Report time period, select 2017-2018 in addition to the pre-selected 2019-2020
5. Remove Trump committee. 
6. You should receive an error message below the committee name. You are not supposed to get this error.

**Completion criteria:**
- [ ] Correct error message usage to only appear if there are no required fields applied while searching more than one two-year period.

**Comment by lbeaufort** [comment]
Thank you @JonellaCulmer! Addressed by https://github.com/fecgov/openFEC/pull/3829 which has been merged to the release
