### ISSUE TITLE
Point feature to stage

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2984]
**What we're after:** Because stage is a closer representation for how production works, we should always point feature to `stage` db instead of `dev` db. 

**Completion criteria:**
- [ ] Change default(?) to have feature point to `stage`

**Comment by pkfec** [comment]
update the api url in cms`manifest_feature.yml`file to point to stage api.  PR https://github.com/fecgov/fec-cms/pull/2998 is up for review
