### ISSUE TITLE
Remove Clear all filters from receipts and individual contributions

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#2988]
**What we're after:** Based on the bug reported [here](https://github.com/fecgov/fec-cms/issues/2987), we're going to implement a short-term solution that removes the "Clear all filters" functionality until we can devote more time to fixing the issue. 

**Completion criteria:**
- [ ] Remove `Clear all filters` button from the receipts and individual contributions datatables

**Comment by lbeaufort** [comment]
We've decided to prioritize this bug https://github.com/fecgov/fec-cms/issues/2987 and hold up the release if needed.

**Comment by pkfec** [comment]
PR #3002 is merged into the release branch. Hence closing this issue.
