### ISSUE TITLE
Multistate IE Reporting Cards - 

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#2994]
### Summary

Multistate independent expenditure examples are published. Now links to the pages need to be incorporated into the existing guidance on independent expenditures.

### Related issues
Continuation of
- #2666: Drafting
- #2785: Publishing

### Completion criteria

- [ ] identify all pages where multistate IE reporting example cards are needed.
- [ ] publish pages with added reporting example cards.

**Comment by bmathesonFEC** [comment]
Added multistate content and reporting cards on these pages: 
F3X: https://www.fec.gov/help-candidates-and-committees/making-independent-expenditures/reporting-independent-expenditures-form-3x/
F5: https://www.fec.gov/help-candidates-and-committees/making-independent-expenditures/reporting-independent-expenditures-form-5/
F9: https://www.fec.gov/help-candidates-and-committees/other-filers/electioneering-communications/

**Comment by dorothyyeager** [comment]
Work is completed, so closing this issue.
