### ISSUE TITLE
Draft content for new page on presidential primary public funding: spending limits

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2996]
**What we are after**
Presidential campaigns need guidance too. In past issues, we've identified resources for it and made a list of new pages we need to create. This ticket is to draft content for new pages that cover presidential primary public funding. The new pages will be part of a new bucket in the candidate part of H4CC that will cover primary public funding.

Past work: #2651 (resources gathered), #2769 (new pages listed), #2807 (work plan for new pages)

**To do**

  Find approved language for new pages on:
--Eligibility to receive matching funds - drafting in issue #2881 
--Entitlement to receive matching funds - drafting in issue #2881
**--Use of public funds and spending limits- drafting in this issue**- make into several other pages. This one will just focus on the actual spending limits. Other pages will address use of funds, media/Secret Service, and winding down.
--Audits and repayment - drafting in issue ~#2997~ #3066  

- [x]   Draft content in a Word doc for each page; note source of content
- [x]  Determine if additional new pages may be needed
- [x]   Circulate to Information Division and content team for review and comment.
- [x] Add material on attribution of spending limit to primary to draft.
- [x] Re-circulate to Info and content team for review and comment.

**Future work**
NEXT Ticket: Circulate to OGC, Audit, Press, RAD, and Info with other primary bucket pages in #3046 
When comments are back, create and publish the bucket collection page
Create new pages as child pages of the new bucket, and add links to collection page
Front end adds new bucket to H4CC hard-coded pages.

**Comment by kathycarothers** [comment]
I have developed the spending limit section and Dorothy has reviewed it. I am now going to start the use of funds section.

**Comment by kathycarothers** [comment]
Use of public funds is now going to be it's own page. There is a good amount of information tied to this subject for it to be it's own page. The draft being worked on in the shared folder.

**Comment by kathycarothers** [comment]
Sent the draft page on spending limits to the content team for review.

**Comment by kathycarothers** [comment]
We have a created a new ticket to address "Use of public funds" for the next sprint.

**Comment by dorothyyeager** [comment]
Have discovered that some material drafted for the use of the funds page really fits better on this page, so re-opening this ticket to add that material to the draft.

**Comment by dorothyyeager** [comment]
I've moved the content about attribution of expenditures to the primary limit into this draft. Will recirculate to the content team when I send the other draft on use of funds in #3077.

**Comment by dorothyyeager** [comment]
Have send the use of funds draft [#3077] and this draft to the content team for review.

**Comment by dorothyyeager** [comment]
Have heard back from the content team and will incorporate their edits into the draft we send to stakeholders when we circulate the public funding drafts in #3046. Closing this ticket since drafting is complete.
