### ISSUE TITLE
Draft content for new page on public funding on audit/repayment process

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#2997]
**What we are after**
Presidential campaigns need guidance too. In past issues, we've identified resources for it and made a list of new pages we need to create. This ticket is to draft content for new pages that cover presidential primary public funding. The new pages will be part of a new bucket in the candidate part of H4CC that will cover public funding.

Past work: #2651 (resources gathered), #2769 (new pages listed), #2807 (work plan for new pages)

**To do**

  Find approved language for new pages on:
--Eligibility to receive matching funds - drafting in issue #2881 
--Entitlement to receive matching funds - drafting in issue #2881
--Use of public funds and spending limits - drafting in issue #2996
**--Audits and repayment - drafting in this issue**

- [x]   Draft content in a Word doc for each page; note source of content
- [ ]  Determine if additional new pages may be needed
- [ ]   Circulate to Information Division and content team for review and comment.

**Future work**
NEXT Ticket: Circulate to OGC, Audit, Press, RAD, and Info with other public funding bucket pages in #3046 
When comments are back, create and publish the bucket collection page
Create new pages as child pages of the new bucket, and add links to collection page
Front end adds new bucket to H4CC hard-coded pages.

**Comment by bmathesonFEC** [comment]
Draft sent to content team. No additional pages are needed; however, I think we can cover all publicly funded committees with one page if we genericize some language, add a few sentences, and add more citations.

**Comment by bmathesonFEC** [comment]
Content team + info agreed that the primary + general Audit/Repayment pages can be all in one. New ticket edited (#3066) created to make adjustments to the draft to ensure all content, regs, links apply for both types of publicly funded committees.
