### ISSUE TITLE
Add Line 25 to disbursement details filter

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3001]
@PaulClark2 commented on [Wed Jun 19 2019](https://github.com/fecgov/openFEC/issues/3826)

### Summary

Users are not able to filter for party coordinated expenditures using the disbursement details filter group (Made by PACs or party committees) on https://www.fec.gov/data/disbursements/

### Expected Behavior

Users should be able to filter by Line 25 (Made by PACs or party committees)

### How to Reproduce
- navigate to https://www.fec.gov/data/disbursements/
- expand disbursement details filter group
- expand drop down of Made by PACs or party committees

### Screenshots

_Screenshots would help us correctly identify the issue._
![image](https://user-images.githubusercontent.com/11817734/59782712-94bcf900-928c-11e9-9498-848084788827.png)

**Comment by patphongs** [comment]
This issue has been closed, since Line 25 is part of coordinated expenditures. This work will be part of future design ticket: https://github.com/fecgov/fec-cms/issues/3019
