### ISSUE TITLE
Re-organize party contributions made page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3005]
### Summary

**What we are after:**
Party committees need info on how to make contributions. Recently @bmathesonFEC and I reviewed our page in H4CC on this to resolve a question about it, and realized that our page for it is overly long and should be broken into several pages or re-vamped using the resource page template.

Page in question is at https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/contributions-made-by-party-committees/

### Completion criteria

- [x] Review content on page and compare the approach taken to the approaches used in the pages that were set up for PACs and SSFs.
- [x] Decide whether to split up content into new, shorter, topic-specific pages, or move content into the resource page template.
- [x] If we find inconsistencies in the PAC pages, put in a ticket regarding that.
- [x] Making new page(s)
- [x] Putting in redirect from old page to new pages

### Future work
- Add any reporting cards needed.

**Comment by kathycarothers** [comment]
In comparing the PAC pages and looking at the party contribution page a re-vamped page using the resource page template is the better option.

**Comment by kathycarothers** [comment]
Created resource page to begin the revamp of the party contribution page.

**Comment by kathycarothers** [comment]
Revamping the page.

**Comment by kathycarothers** [comment]
Submitted to content team for review.

**Comment by dorothyyeager** [comment]
Looks good @kathycarothers !! My only suggestion would be to rephrase "Limits on contributions to candidates" as "Limits on contributions" since you took out the annoying text references to limits and inserted the snippet (a very good change)!

**Comment by kathycarothers** [comment]
@dorothyyeager Thank you for the suggestion. I have made the change.
