### ISSUE TITLE
[RAW IEs] Implement changes to flyout and filter panel for Raw IEs

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3011]
**What we're after:** As part of our work to allow users to filter and view transactions that are the latest version, we need to implement several changes to the front end filter and flyout panels on the IE datatable. 

As part of this work, we need to make changes to both the IE datatable Raw AND Processed panels. The work in this ticket contains changes to the Raw filter panel. [Processed IE work happening here.](https://github.com/fecgov/fec-cms/issues/3370)

**Completion criteria:**
Filter panel
- [ ] ~Modify the Regularly Scheduled Report Form to gray out when the 24- and 48-hour reports toggle is active~ This has been moved to a new issue for filter & tags interaction work: https://github.com/fecgov/fec-cms/issues/3448
- [x] Update the Raw filter panel according to the mockup below, including several new filters being added
- [x] Link below version filter is a pop-up similar to other methodology pop-ups
- [x] Update methodology text according to this issue for methodology: https://github.com/fecgov/fec-cms/issues/3360
- [x] Current version filter should be checked by default on page load

Flyout panel
- [x] Change "Open original image" to "Open image" 
- [x] Update the flyout panel according to the mockup below to include version type

#### Flyout panel
<img width="863" alt="Screen Shot 2019-11-18 at 8 45 40 AM" src="https://user-images.githubusercontent.com/31663028/69057424-d7236700-09df-11ea-998a-a5647e487b23.png">

#### Raw filter panel
<img width="141" alt="Screen Shot 2019-11-18 at 8 19 12 AM" src="https://user-images.githubusercontent.com/31663028/69055598-28c9f280-09dc-11ea-9d64-0df79e38aa42.png">

### Methodology pop-up
TBD

**Comment by patphongs** [comment]
> * Modify the Regularly Scheduled Report Form to gray out when the 24- and 48-hour reports toggle is active

@JonellaCulmer For this completion criteria, what happens if filters are checked under the Regularly Scheduled Report Form filters? If this is grayed out, the filters are still applied...

**Comment by patphongs** [comment]
I can't get the Version information to be on the same line as the open image button since that is a global button placed on another template. The best I could do was put another panel row for the version information. Would that be ok @JonellaCulmer ?

<img width="677" alt="Screen Shot 2020-01-02 at 8 09 39 PM" src="https://user-images.githubusercontent.com/12799132/71702156-d716d500-2d9b-11ea-81a7-3d5743c915e7.png">

**Comment by patphongs** [comment]
@JonellaCulmer This is the other option we talked about where the version is part of the "Expenditure information" section rather than standing alone up at the top.

![Screen Shot 2020-01-06 at 3 34 56 PM](https://user-images.githubusercontent.com/12799132/71847126-2447bf00-309a-11ea-8036-126932e7a91f.png)

**Comment by patphongs** [comment]
@JonellaCulmer For now, I will also remove the "Report type" and "Regularly scheduled report forms" filters from raw IE filing filters until these two tickets are completed: https://github.com/fecgov/openFEC/issues/4140, https://github.com/fecgov/fec-cms/issues/3448

**Comment by patphongs** [comment]
@JonellaCulmer I've been having issues with getting the accordions working on both the Processed and Raw data tabs together. To get that working, I'll probably need to figure out how to overhaul the accordion scripts to work on separate tabs. 

As you can see in the processed data filters tab, there are "Candidate mentioned" and "Transaction information" accordions. I tried to implement the same for the Raw data filters tab, but they started to conflict and break the processed data accordions. Would you be ok with the first implementation not having accordions for the for the Raw data filters tab? See screenshot below of what that looks like.

## Processed data filters tab
![Screen Shot 2020-01-08 at 3 44 04 PM](https://user-images.githubusercontent.com/12799132/72014715-70c40380-322e-11ea-8528-c6d8fadafad4.png)

## Raw data filters tab
![raw-ie-data-filter](https://user-images.githubusercontent.com/12799132/72014871-b84a8f80-322e-11ea-8234-669aee9e90d3.jpg)

**Comment by patphongs** [comment]
This work has been completed and merged in
