### ISSUE TITLE
Remove Line 24 Disbursements datatable and update title and description

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3019]
### Summary

**What we're after:**
_Line 24 is applicable to both schedule_e and form 57. The disbursements datable only accounts for schedule_b data, and therefore will show no results for that particular line number._

_The all disbursements datatable only encompasses schedule_b data. We need a way to more accurately title and describe the disbursements datatable, since it doesn't include every disbursement transaction._

### Completion criteria

- [x] Content and design should decide how to re-title and describe the disbursements datatable and document in this ticket. 
![Screen Shot 2019-07-03 at 1 09 30 PM](https://user-images.githubusercontent.com/12799132/60611262-e63cac00-9d93-11e9-8050-7b6715377d83.png)
- [x] Implement decision for re-titling and descriptions for disubrsement datatable on this page: https://www.fec.gov/data/browse-data/?tab=spending
- [x] Remove Line 24 from Disbursement datatable: https://www.fec.gov/data/disbursements/
![Screen Shot 2019-07-03 at 1 00 56 PM](https://user-images.githubusercontent.com/12799132/60610790-a923ea00-9d92-11e9-97c1-228265018006.png)
~Product managers should create a new ticket to redesign the spending section of the website to possibly show all disbursements data within one datatable.~ This might be a post-election task.

**Comment by JonellaCulmer** [comment]
@AmyKort Had a good convo with @dorothyyeager and @patphongs about the language. Below are two options for your review to update the disbursements datatable name and description. Essentially we're excluding everything that isn't in schedule b. Let us know what you think. Happy to have a followup discussion to go over this some more.

### Option 1
<img width="759" alt="Screen Shot 2019-07-11 at 3 03 47 PM" src="https://user-images.githubusercontent.com/31663028/61078434-993d8300-a3ee-11e9-8886-1f0ac859e210.png">


### Option 2
Would like to this page: https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/#outside-spending
<img width="702" alt="Screen Shot 2019-07-11 at 3 15 37 PM" src="https://user-images.githubusercontent.com/31663028/61078514-c4c06d80-a3ee-11e9-8a09-1444fc06df6a.png">

**Comment by JonellaCulmer** [comment]
@dorothyyeager @patphongs Just talked to @AmyKort who approved option 2 language and linking to outside spending language.
