### ISSUE TITLE
[High] Snyk: Prototype Pollution - lodash.mergewith (due 8/2/19)

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3022]
Prototype Pollution
Vulnerable module: lodash.mergewith
Introduced through: sanitize-html@1.18.4
Detailed paths
Introduced through: fec-cms@1.0.0 › sanitize-html@1.18.4 › lodash.mergewith@4.6.1
Remediation: Upgrade lodash.mergewith to version 4.6.2 or higher.

Vulnerable Functions
```
index.baseMerge
index.baseMergeDeep
```
 
https://app.snyk.io/vuln/SNYK-JS-LODASHMERGEWITH-174136

**Comment by patphongs** [comment]
Vulnerability has been remediated, see this comment for details: https://github.com/fecgov/fec-cms/pull/3043#issuecomment-515994163
