### ISSUE TITLE
Follow-up tasks for moving to `FEC_WEB_API_KEY_PUBLIC` key

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3029]
## Summary ##
Follow-up tasks from https://github.com/fecgov/fec-cms/pull/3026 and https://github.com/fecgov/fec-accounts/issues/176

## Completion criteria ##
- [x] Remove `FEC_WEB_API_KEY` env vars after deployments. This is the ticket for stage: https://github.com/fecgov/fec-cms/issues/3044
- [x] make sure `stage` and `prod` are using different keys 
- [x] Research possible limits per IP for `FEC_WEB_API_KEY_PUBLIC` using Kibana logs, 
- [x] add the limits via API umbrella

**Comment by pkfec** [comment]
Paired with @fec-jli and removed unused `FEC_WEB_API_KEY` from `stage` and `prod` spaces.
on circle, I rebuild the latest release onto stage env to bound the api app with the latest env config changes.

**Comment by pkfec** [comment]
noticed that `stage` and `prod` use the same `FEC_WEB_API_KEY_PUBLIC` unlimited key/value pairs. on the api umbrella, @patphongs created a new `unlimited` key/value just for `stage` environment. I will bound this new key/value to the api app on stage and test to make sure everything works fine.

**Comment by pkfec** [comment]
switched the` stage` `FEC_WEB_API_KEY_PUBLIC` with the new value starting with qis*******. redeployed the `api` and `cms` apps via circle. Tested few ajax calls (endpoints) on `cms` and  to make sure the calls return results.

**Comment by pkfec** [comment]
1. The unlimited key `FEC_WEB_API_KEY_PUBLIC` is under ` alison.rowland@gsa.gov` user email id. We should consider creating/moving this unlimited public key under our email id i.e.`webappalerts@fec.gov`.  

2. The unlimited `FEC_WEB_API_KEY_PUBLIC` starting with `oXyFx` is being used extensively across the environments. we should consider creating  different keys for different environments.

cf space | cms-api calls | downloads
------------ | ------------- | ----------------
dev | yes | yes
feature | yes | stage downloads key
prod |yes|  prod downalods key

**Comment by pkfec** [comment]
Today i created 3 new FEC_WEB_API_KEY_PUBLIC keys on api umbrella for `dev`, `feature` and `prod` spaces.
I have switched the existing key with the new key value in `dev` and `feature` spaces. Rebuild/Redeploy the cms and api apps, and tested few server side calls to make sure the API is returning results with the new key.

**Comment by pkfec** [comment]
I switched the FEC_WEB_API_KEY_PUBLIC key in  `prod` space.  Tested the production website to make sure CMS is functioning properly with the new key.

Send a draft mail to @PaulClark2 regarding public key that's on ****@gsa.gov user, on what necessary actions we have to take to retire this unused key

**Comment by pkfec** [comment]
sent an email to api umbrella admins to either delete or deactivate the unused FEC api key assosiciated with *****@gsa.gov email id. waiting for their response.

**Comment by pkfec** [comment]
- On api umbrella, i disabled the unused keys associated with *****.gsa.gov email id. 
- Created new public and private api keys for each environment. 
- All the public api keys in `dev`, `feature`,`stage` and `prod` environments are rate limited per ip.
