### ISSUE TITLE
Front-End takedown of transition pages redirected in 9.4

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3032]
### Summary

**What we are after:**
Making sure we have the latest version of things up, and also getting rid of transition eventually.

### Related issues

- #3000 
- #3035 

### Completion criteria

- [ ] Remove the following pages from transition.fec.gov:
- /law/policy/guidance/Appendices_2008_Guideline.pdf
- /law/policy/guidance/2008_guideline_approved_aug092007.pdf
- /pages/brochures/candregis.shtml
- /pages/brochures/notices.shtml
- /support/GettingStarted_FECFileManual_ie_filers_61517.pdf
- /support/GettingStarted_FECFileManual_candidates_61517.pdf

- [ ] Check for these files and remove if they are still there:

- /rad/candidates/documents/FECFileGettingStartedManual.pdf 
- /support/GettingStartedManualUpdate-A_61517.pdf
- /support/Getting_Started_Manual_ie_filers_61517.pdf

**Comment by johnnyporkchops** [comment]
This content has been removed
