### ISSUE TITLE
Redirect work for 9.5

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3035]
### Summary

**What we are after:**
We need to redirect the old candidate registration brochure now that we've updated the pages on candidate registration to include presidential guidance. This will insure that all federal candidates are pointed to the most up-to-date page and get another file off of transition.

### Completion criteria

- [x] Write redirect in proxy for /pages/brochures/candregis.shtml to now point to https://www.fec.gov/help-candidates-and-committees/registering-candidate/
- [x] Put redirect in Wagtail for this as well.
- [x] [Update our spreadsheet](https://docs.google.com/spreadsheets/d/1Jn5nC3fFku10RTCP5OAW6RiffjNBE4VwBubITQpCNK8/edit?usp=sharing)
- [x] Draft ticket for front end to take down /pages/brochures/candregis.shtml

### Future work

If any other pages need redirecting in the next sprint, we will add them to this ticket.

**Comment by kathycarothers** [comment]
@dorothyyeager I have created the redirect in proxy for the candidate brochure and it is ready for review. @patphongs

**Comment by kathycarothers** [comment]
@dorothyyeager redirect has been updated in Wagtail.
