### ISSUE TITLE
Add pagination back to datatables pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3041]
**What we're after:** In an effort to help orient our users when viewing multiple pages of data, we should update our pagination to include the number of results being viewed and total results. Presently, a user must rely on whether they notice the data in the table has changed with no confirmation. If a user clicks multiple times they may lose track of where they are in the list.

### Before
![Screen Shot 2019-07-11 at 10.28.23 AM.png](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/08bd9351-77fe-466e-8000-a85a80b6ae2e)

### After
<img width="890" alt="Screen Shot 2019-10-29 at 11 14 27 AM" src="https://user-images.githubusercontent.com/31663028/67796459-4f2fea00-fa3d-11e9-9b15-721b2126a8d7.png">

**Completion criteria:**
- [x] Research how page count estimates were tweaked in the past. When is it an estimate and when is it exact? **Answer:** counts are estimates when the estimate is over 500K. ([code](https://github.com/fecgov/openFEC/blob/d1ff96fd09a4eb018c60a4e7fe85e2749967bf98/webservices/common/counts.py#L16))
- [ ] Re-implement page counts on page

**Comment by johnnyporkchops** [comment]
FYI- The Pattern Library patter library has the alternate design patterns for showing estimated page counts and numbered buttons.
https://fec-pattern-library.app.cloud.gov/components/detail/feed-pagination.html

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Thanks, John! I've updated the ticket.

**Comment by JonellaCulmer** [comment]
@johnnyporkchops I spoke too soon. This doesn't include controls on how to change the number of items seen on a page. I'll mock something up today or tomorrow.

**Comment by JonellaCulmer** [comment]
@johnnyporkchops What do you think about below?
I think I prefer the first one. Users already know to look for the pagination buttons there on the right. 

<img width="812" alt="Screen Shot 2019-07-15 at 11 18 32 AM" src="https://user-images.githubusercontent.com/31663028/61227469-5d5a3480-a6f2-11e9-948e-d93b3b6cf7fd.png">

**Comment by JonellaCulmer** [comment]
I've updated the mock-up in the original comment based on previous discussions.

**Comment by lbeaufort** [comment]
@JonellaCulmer, something that came up in discussion - can you show what the pagination would look like for a large results set - such as all 2020 schedule A data? It has 1,078,296 pages: https://api.open.fec.gov/v1/schedules/schedule_a/?api_key=DEMO_KEY&two_year_transaction_period=2020

**Comment by JonellaCulmer** [comment]
@lbeaufort A previous version of the pagination accounted for all pages. Listing pages 1, 2, 3...through to 1,000,000, etc. But that would add some visual clutter and confusion. And I'm not at all convinced that a user would page that far through the results without introducing new filters or sorting the date another way. I'm comfortable only listing some of the upcoming pages, not all of them.

**Comment by JonellaCulmer** [comment]
@rfultz Here's some mock-ups to account for the other states. Happy to chat further if you think it necessary.

The first shows that a page will move to the middle, if possible. The last shows what it looks like to be on the last page. With the page all the way to the right and the right pagination button disabled.

<img width="939" alt="Screen Shot 2019-11-01 at 10 59 03 AM" src="https://user-images.githubusercontent.com/31663028/68033867-f8255180-fc96-11e9-9f6f-b8e51f7e2cc2.png">

**Comment by rfultz** [comment]
The datatables logic wants to include the ellipses. Here's how it looks with only five stops between the < and >. Not super helpful.
![image](https://user-images.githubusercontent.com/26720877/68807522-eef09900-0635-11ea-972b-10a82e0c7875.png)
