### ISSUE TITLE
Remove old API key in stage when release is cut

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3044]
### Summary

**What we're after:**
_The private API key name has changed. We need to remove the old `FEC_WEB_API_KEY` from stage when release is cut now that we're using `FEC_WEB_API_KEY_PRIVATE`._

### Completion criteria

- [x] Update stage environment var for private key as noted above
- [ ] Make sure `stage` and `prod` aren't using the same keys, set up new ones if needed
- [ ] Delete the old private key variable `FEC_WEB_API_KEY`
- [ ] Test to make sure the parts of the site that access the API do not break (Such as calendar, data sections, candidate and committee profile pages, etc.)

**Comment by lbeaufort** [comment]
@patphongs here is the follow up task #3029 the keys are already in place

**Comment by patphongs** [comment]
Closing, this is a duplicate
