### ISSUE TITLE
Migrate FOIA zip files to Wagtail

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3059]
### Summary

**What we're after:**
_In an effort to move uploaded documents to Wagtail, we would like to move the FOIA quarterly zip files from being uploaded to transition to Wagtail._

Transition path is: `transition.fec.gov/foia/quarterly/[filename.zip]`
New path on www would be: `www.fec.gov/resources/cms-content/documents/[filename.zip]`

### Completion criteria

- [x] Discuss with Admin Law team about moving the zip file directory path. They will probably need to communicate to their agency counterparts that the path has changed from old transition path to new Wagtail CMS path.
- [x] Developer with zip up the files to send to content team to upload to Wagtail - @patphongs 
- [x] Create new collection name `FOIA (documents)`
- [x] Upload all existing quarterly FOIA zip files on transition to that collection in Wagtail
- [x] Spreadsheet created to link old file paths to their new file path and sent to Candace in Admin Law
- [x] Set up transition redirects to point to from old transition path to new path and add/set up testing ticket for 14.2

**Comment by dorothyyeager** [comment]
Have scheduled a meeting for 2/26 to talk with Admin law

**Comment by dorothyyeager** [comment]
@patphongs Candace advises they only need to keep 7 years worth of files online (so I would say let's keep 2013 files and on). Older ones aren't needed for the DOJ site they give the links to (although we may want to save them for other reasons).

**Comment by dorothyyeager** [comment]
@patphongs I just realized that we'll want to ask Admin Law about including the quarterly zip files on this page: https://www.fec.gov/about/reports-about-fec/foia-reports/

**Comment by patphongs** [comment]
> @patphongs I just realized that we'll want to ask Admin Law about including the quarterly zip files on this page: https://www.fec.gov/about/reports-about-fec/foia-reports/. Or is it enough to just upload them into Wagtail and give Admin Law the live link, like we do now with the transition files.

@dorothyyeager Let's loop them into the changes that will be occurring. That way if they have any issues with our migration path and the new link, we'll know before implementation.

**Comment by dorothyyeager** [comment]
Had a really good meeting with Candace from Admin Law today, @johnnyporkchops and content team. There is an issue with their annual report .csv file that John will log and assign to himself.

For this ticket, we are ready to migrate the old quarterly .zip files, so  @patphongs please go ahead and send the big .zip folder of the .zip files to me and Candace. Candace wants to archive all of them in her files, but for the website, we'll just upload 2012 on. They do not need to be in the FOIA report feed page. She just needs a link to each one that we'll create by uploading to Wagtail. I plan to keep the same filenames so we can put in a broader redirect. She'd also like a spreadsheet to send to DOJ to cross-reference the old links and new names, so I'll add it to completion criteria and make that as well.

**Comment by dorothyyeager** [comment]
Testing ticket opened in #4433 for 14.2 and PR submitted for review. This will be ready to close after the PR is approved and merged.
