### ISSUE TITLE
Null values for reports tables

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3060]
### Summary

_When there is a null value for the `amendment_chain` JSON key, we need to do a catch on the front end for what should be returned. Otherwise there is a `.length` error and the table does not return at all._

Related issue: https://github.com/fecgov/fec-cms/issues/3057

### Screenshots

<img width="1675" alt="Screen Shot 2019-07-18 at 12 34 34 PM" src="https://user-images.githubusercontent.com/12799132/61475271-6ba98a00-a958-11e9-9484-55918f3aed0c.png">

## Completion Criteria ##
- [ ] Handle Null error

**Comment by jason-upchurch** [comment]
currently unable to reproduce bug. However, a question arose as to whether behavior when `amendment_chain` is null is correct. Example: https://www.fec.gov/data/reports/house-senate/?data_type=processed&committee_id=C00048587. Checking to see if the "Read report" should be `|.fec`. If this is correct behavior may need to wait for reproducible bug.

**Comment by jason-upchurch** [comment]
Thank you @hcaofec and @fec-jli for your help identifying where we want to make sure `amendment_chain` is not null! Updated and creating PR.
