### ISSUE TITLE
Draft new page on GELAC Fund

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3065]
### Summary

**What we're after:**
This ticket is to draft content for a new page in our forthcoming bucket for public funding of presidential elections. This new page will cover the GELAC fund and contributions to it.

### Completion criteria

- [x]  Do legal research (Regs, E&Js, AOs) on the GELAC fund
- [x]   Identify approved language to use for page
- [x]   Draft content for page, noting all sources of language
- [x]   Circulate to content team
- [x]   Make any edits content team suggests

### Future work

- NEXT Ticket: Circulate to stakeholders in #3046.
- When stakeholder comments are back, create and publish the bucket collection page.
- Create new pages as child pages of the new bucket, and add links to collection page.
- Front end adds new bucket to H4CC hard-coded pages.

**Comment by dorothyyeager** [comment]
We're going to shift this drafting ticket to the next sprint.

**Comment by bmathesonFEC** [comment]
Have completed draft ready to circulate. Wrapping up #3090 now. Will circulate together this morning.

**Comment by bmathesonFEC** [comment]
Distributed to content team for comment.

**Comment by bmathesonFEC** [comment]
Received edits from content team, made edits.
