### ISSUE TITLE
[Tenable] CMS missing/inadequate headers (due 8/31/19)

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3069]
### 1. Missing 'Cache-Control' Header 
The HTTP 'Cache-Control' header is used to specify directives for caching mechanisms. The server did not return a 'Cache-Control' header which means page containing sensitive information (password, credit card, personal data, social security number, etc) could be stored on client side disk and then be exposed to unauthorised persons. This URL is flagged as a specific example: fec-dev-cms.app.cloud.gov 
Remediation path: Configure your web server to include a 'Cache-Control' header with appropriate directives. If page contains sensitive information 'Cache-Control' value should be 'no-cache, no-store' and 'Pragma' header value should be 'no-cache'. 
References: 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Pragma; https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Cache-Control; https://www.owasp.org/index.php/Testing_for_Browser_cache_weakness_(OTG-AUTHN-006)
### 2. Missing Content Security Policy 
Content Security Policy (CSP) is a web security standard that helps to mitigate attacks like cross-site scripting (XSS), clickjacking or mixed content issues. CSP provides mechanisms to websites to restrict content that browsers will be allowed to load. No CSP header has been detected on this host. This URL is flagged as an specific example: fec-dev-cms.app.cloud.gov 
Remediation path: Configure Content Security Policy on your website by adding 'Content-Security-Policy' HTTP header or meta tag http-equiv='Content-Security-Policy'. 
References: 
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy; https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP; https://csp-evaluator.withgoogle.com/; https://developers.google.com/web/fundamentals/security/csp/; https://content-security-policy.com/

**To do**
- [ ] Front end investigates use of Engine X or the CMS application itself to investigate headers. (Also, are there core settings?)

**Comment by patphongs** [comment]
For item # 1, we need to find a way for Django to set the cache-control header. Looking into possibly using python-memcache to be able to cache for us when someone hits the application directly: https://docs.djangoproject.com/en/2.2/topics/cache/

For item # 2, we need to decide what we can safely set our Content-Security-Policy to, without breaking things. Here's an example where this meta tag would be added directly to our template headers: `<meta http-equiv="Content-Security-Policy" content="default-src https:">`. Setting it to https would negatively effect local development though, as our local does not serve up https and would break links to styles, JS, etc.

**Comment by patphongs** [comment]
I have a PR in for the content security policy vulnerability, we'll need to do a lot of testing as this could break things: https://github.com/fecgov/fec-cms/pull/3099
