### ISSUE TITLE
Fix feedback box on stage.fec.gov and dev.fec.gov

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3074]
**What we are after**
Before we can grab browser info for issues we get via feedback box, we need to get the feedback box working on stage.fec.gov and dev.fec.gov.

From https://github.com/fecgov/fec-cms/issues/2985#issuecomment-511836006:

> We need the feedback box working on stage.fec.gov and dev.fec.gov, currently it is not working. Those domains utilize the CDN service. After this is fixed we can try implementing one of the solutions above from @johnnyporkchops
> 
> Error when submitting to stage.fec.gov feedback box
https://camo.githubusercontent.com/a59a4d1d49e404a3f33e470905747efef53ef396/68747470733a2f2f696d616765732e7a656e68756275736572636f6e74656e742e636f6d2f3539613537396632386636326463373739386334373335392f65333437353534652d396364372d346539342d386362382d366336613638356335353764

**Comment by JonellaCulmer** [comment]
Working in stage: https://github.com/fecgov/FEC/issues/10106

Working in dev: https://github.com/fecgov/FEC/issues/10107
