### ISSUE TITLE
Add connected organization to SSF profile pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3078]
**What we're after:**
Following on the [design work](https://github.com/fecgov/fec-cms/issues/3024), we need to now add connected organizations to those select committee types. Specifically, this new information will be added as the last item on the About this committee tab. 

### Related issues
- https://github.com/fecgov/fec-cms/issues/3024

### Completion criteria
- [ ] Add "Connected organization" to profile pages for committees with connected organizations. This means where org_type is: 
C corporation
L labor organization
M membership organization
T trade association
V cooperative
W corporation without capital stock

SSF examples:

org_tp | min | max
-- | -- | --
W | [C00012153](https://www.fec.gov/data/committee/C00012153/?tab=about-committee) | [C00690149](https://www.fec.gov/data/committee/C00690149/?tab=about-committee)
C | [C00000042](https://www.fec.gov/data/committee/C00000042/?tab=about-committee) | [C00709956](https://www.fec.gov/data/committee/C00709956/?tab=about-committee)
L | [C00000000](https://www.fec.gov/data/committee/C00000000/?tab=about-committee) | [C00702043](https://www.fec.gov/data/committee/C00702043/?tab=about-committee)
V | [C00000422](https://www.fec.gov/data/committee/C00000422/?tab=about-committee) | [C00681338](https://www.fec.gov/data/committee/C00681338/?tab=about-committee)
M | [C00000117](https://www.fec.gov/data/committee/C00000117/?tab=about-committee) | [C99002727](https://www.fec.gov/data/committee/C99002727/?tab=about-committee)
T | [C00000026](https://www.fec.gov/data/committee/C00000026/?tab=about-committee) | [C00702092](https://www.fec.gov/data/committee/C00702092/?tab=about-committee)

- [ ] For committees without name, leave blank. 

### Design
<img width="979" alt="Screen Shot 2019-07-26 at 9 42 29 AM" src="https://user-images.githubusercontent.com/31663028/61968836-03d1ef80-afa7-11e9-8479-dc8f45c4c629.png">

**Comment by patphongs** [comment]
@PaulClark2 We will only be adding the connected organization to the about committee page for now. Other ticket to implement org type is #3079

**Comment by patphongs** [comment]
@PaulClark2 I found 2 committees where the organization_type doesn't line up to what was defined in the table above. Can you please verify if this is an error?

- C00012153 - organization_type is null - https://api-stage.open.fec.gov/v1/committee/C00012153/history?per_page=1&api_key=DEMO_KEY
- C00000422 - organization_type is M - https://api-stage.open.fec.gov/v1/committee/C00000422/history?per_page=1&api_key=DEMO_KEY
