### ISSUE TITLE
Add page watch template tags for govdelivery into Wagtail templates

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3081]
### Summary

**What we are after:**
We needed to suspend govdelivery pagewatches due to excessive emails triggered from a security implementation for csrftoken. We now need to add govdelivery template tags so that pagewatch only monitors only part of a web page

### Related issues

- #1697 
- #3061 

### Completion criteria
**Dorothy:**
- [x] Go into GovDelivery and set each topic's Watched Tagged Content to "yes"
- [x] Copy the page watch content block code for each topic into the spreadsheet (in shared google drive in folder called "govdelivery")

![image](https://user-images.githubusercontent.com/24437369/62073698-40078900-b20f-11e9-8e01-c7ca9d1da8c6.png)

- [x] Note if page being watched is hard coded or in CMS.
- [x] Note the specific content on the page that we are trying to watch and anything else that might be helpful.

**Once Dorothy's done; turn over to John to:**
- [ ]  Insert the pagewatch tags as needed into each hard-coded page template. This page contains the tags info: https://support.granicus.com/s/article/Automating-Updates-on-Webpage-or-File-Content-by-Email.
- [ ] For CMS pages, research how to do this, especially for pages like Dates and Deadlines that have numerous codes to insert. Do we insert using HTML blocks? (Answer: yes for custom page; John will look into template modifications for Resource and Document Feed pages).
- [x] See what if anything we can do about watching YouTube page content. 
- [ ] Test that the tags are working

**Comment by johnnyporkchops** [comment]
@dorothyyeager , regarding the CMS templates. We could add a dropdown inside certain templates that would allow you to choose to tag a certain section with a specific  pagewatch tag. Or just a pagewatch field in which you manually input the topic ID and it would wrap that section in a pagewatch tag when rendered. If most of pages we want to watch are built on only a few different template-type (ie- `ResourcePage, CoolectionPage etc.`) and the pertinent content is typically put into a certain field types (ie `sections, body , etc`) maybe this would not be that complicated.

**Comment by dorothyyeager** [comment]
That sounds good @johnnyporkchops - I'll update the spreadsheet to note which template a CMS page is using.

**Comment by dorothyyeager** [comment]
I've got all of the topics updated except for the YouTube ones. Will send the spreadsheet to @johnnyporkchops and re-assign the issue to him for the front-end work.

John: There are a couple of files that are transition files, so if it's helpful for me to add the tags on those, I can do that via Contribute.

**Comment by dorothyyeager** [comment]
I've put the spreadsheet in our shared google drive in the "govdelivery" folder.

**Comment by dorothyyeager** [comment]
John and I are going to start tagging. I'll do the custom page CMS and transition page tags. He'll do the hard-coded ones. He may look into modifying templates like the Resource Page template and the Document Feed page template to add a drop down way to select the applicable code.

[Spreadsheet is here](https://docs.google.com/spreadsheets/d/1C7qpmrW_leY1FCL7lEzlwMt_2w9MA97G/edit#gid=925587780).

**Comment by AmyKort** [comment]
Thank you both SO much!

**Comment by dorothyyeager** [comment]
The custom page (there was only one) and the four transition page tags have been added. This weekend will be a good test to see if it worked.

**Comment by dorothyyeager** [comment]
We found that the transition page watch tags are working. The custom page watch tag is not. Since that one and all the rest we need to add involve Wagtail, we need to make sure we're setting this up right with our CMS. @johnnyporkchops and I have reached out to our Gov Delivery contact to set up a call and ask our questions.

**Comment by dorothyyeager** [comment]
We're going to set up a call with the govdelivery contact during this sprint and ask our questions. We also will talk with InfoDiv about the need for page watch at all. Moving to blocked until we get our questions answered, which will help us decide what to do with the rest of the work.

**Comment by dorothyyeager** [comment]
We just had our call and will email support with our more technical questions. We learned that due to changes on YouTube's end, it doesn't really work for YouTube anymore, so have ticked that box.

**Comment by lbeaufort** [comment]
@dorothyyeager are we still waiting for answers from InfoDiv on this?

**Comment by dorothyyeager** [comment]
@lbeaufort Not Info Div. We're blocked waiting on Gov Delivery to answer our support tickets. @johnnyporkchops have you heard back from them? We may need to make a decision about how long we want to wait on Gov Delivery.

**Comment by patphongs** [comment]
@johnnyporkchops @dorothyyeager Can we escalate this ticket in GovDelivery so that we get an answer sooner? Maybe bring it up the chain at the FEC?

**Comment by dorothyyeager** [comment]
We got some preliminary answers from GovDelivery and they are having me test out page watch on the one custom page where we inserted tags. I'm not sure they really answered @johnnyporkchops larger questions though. We'll keep talking with them.

**Comment by dorothyyeager** [comment]
We've not been able to get an answer from GovDelivery that indicates that page watch notification tags are going to be useful for us. They don't seem to play well with the CMS.

Luckily, it's very easy to still generate bulletins without page watch. After talking with @AmyKort, we're going to schedule an internal meeting with the Info Division manager and hopefully we'll be able to disable page watch, as it isn't able to do for us what it is intended to do. Closing this ticket and will open a new one if any work results from that meeting.
