### ISSUE TITLE
Implement "closed cases only" message on MUR search page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3083]
### Summary

**What we are after:**
We need to let users of the MUR search know that it doesn't include open and ongoing cases, but only closed ones.

### Related issues

_List any relevant related issue(s)_
- #2969 
- #3049 

### Completion criteria

- [ ] Change label on MUR Search page https://www.fec.gov/data/legal/search/enforcement/?case_no= to read "Closed Matters Under Review" instead of "Matters under review."
- [ ] Add "closed" to the first sentence in the info message at the top that explains what's in our search, so that it reads:

> The MUR search feature includes all closed cases dating back to . . .

- [ ] Include content team member in the PR review for proofreading.

**Comment by patphongs** [comment]
@dorothyyeager Would like to pair on how these changes are made
