### ISSUE TITLE
Transition Analytics Away From 18F's Account

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#3087]
### Summary

**What we're after:**
We want to transition our site analytics away from 18F's account back to the account currently in use with Classic. We'll keep the dap script in place, too.

### Related issues

If it hasn't happened by the time we get to this ticket. we'll need to claim ownership of the Classic account. @patphongs is currently working on that bit. [Google Analytics Account Help](https://support.google.com/analytics/troubleshooter/7264014?hl=en#ts=7271146)

### Completion criteria

All instances of `UA-48605964-22` across the site will be replaced with the account number on Classic.

### Future work

Verify the analytics data is coming in correctly.
Check whether events are going to our account and/or to DAP.

**Comment by patphongs** [comment]
@rfultz, good news! I believe I have been able to regain account access and have given you access as well. You should be receiving an email notification.

**Comment by rfultz** [comment]
Checking the latest analytics code from Google, when doing this switch, we may want to transition to Tag Manager at the same time. https://developers.google.com/analytics/devguides/collection/gtagjs/migration
Related Tag Manager ticket: #2840

**Comment by dorothyyeager** [comment]
PR merged, so closing.
