### ISSUE TITLE
Draft content for new page on presidential   public funding: Winding down costs

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3090]
What we are after
Presidential campaigns need guidance too. In past issues, we've identified resources for it and made a list of new pages we need to create. This ticket is to draft content for a new page that will cover the winding down rules for both publicly funded presidential primary candidates who are no longer eligible for matching funds and publicly funded general election candidates after the election is held. The new page will be part of a new bucket in the candidate part of H4CC that will cover public funding, in a catch-all section for pages that affect both primary and general.

Past work: #2651 (resources gathered), #2769 (new pages listed), #2807 (work plan for new pages); #3077 (Use of primary matching funds page, which will intro and link to this one)

To do:

- [x]   Do legal research (Regs, E&Js, AOs) on these rules (@kathycarothers has done some on the primary which is saved in our research folder)
- [x]   Identify approved language to use for page
- [x]   Draft content for page, noting all sources of language
- [x]   Circulate to content team
- [x]   Make any edits content team suggests

Future work
NEXT Ticket: Circulate to stakeholders in #3046.
When stakeholder comments are back, create and publish the bucket collection page.
Create new pages as child pages of the new bucket, and add links to collection page.
Front end adds new bucket to H4CC hard-coded pages.

**Comment by bmathesonFEC** [comment]
Wrapping up this morning.

**Comment by bmathesonFEC** [comment]
Distributed to content team for comment.

**Comment by bmathesonFEC** [comment]
Received edits from content team, made edits.
