### ISSUE TITLE
Draft new page on presidential general election spending limits

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3097]
### Summary
**What we are after:**
This ticket is to draft content for a new page in our forthcoming bucket for public funding of presidential elections. This new page will cover complying with general election spending limits.

### Related issues:
Primary version of this page: #2996 

### Completion criteria
 - [x] Do legal research (Regs, E&Js, AOs) on complying with general election spending limits
 - [x] Identify approved language to use for page
 - [ ] Draft content for page, noting all sources of language
 - [ ] Circulate to content team
 - [ ] Make any edits content team suggests

### Future work
NEXT Ticket: Circulate to stakeholders in #3046
When stakeholder comments are back, create and publish the bucket collection page
Create new pages as child pages of the new bucket, and add links to collection page
Front end adds new bucket to H4CC hard-coded pages.

**Comment by kathycarothers** [comment]
In looking at the pages drafted for #3063 and #3064 they thoroughly cover spending limits for the general election. I don't think we need to draft this page. What do you think @dorothyyeager @AmyKort @bmathesonFEC ?

**Comment by dorothyyeager** [comment]
I think you may be right @kathycarothers - there's not much to the spending limits  (amount of grant plus $50,000 from personal funds) other than they exist and have to be complied with, which is explained in both the eligibility draft and the use of funds draft pages' content. We'll want to make sure those two pages cross-reference each other on this topic, and also will want to work spending limit into the SEO for those pages. But I vote we can skip drafting this particular page.

**Comment by kathycarothers** [comment]
All are in agreement that a page is not need, so I will close out this ticket.
