### ISSUE TITLE
[Tenable] Cookie Without Secure Flag Detected (due 8/31/19)

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#3102]
### Cookie Without Secure Flag Detected

This ticket is split from [#3070](https://github.com/fecgov/fec-cms/issues/3070) to better track its progress.

From Tenable:
> When the `secure` flag is set on a cookie, the browser will prevent it from being sent over a clear text channel (HTTP) and only allow it to be sent when an encrypted channel is used (HTTPS). The scanner discovered that a cookie was set by the server without the secure flag being set. Although the initial setting of this cookie was via an HTTPS connection, any HTTP link to the same server will result in the cookie being sent in clear text. Note that if the cookie does not contain sensitive information, the risk of this vulnerability is mitigated.
> 
> Remediation path: If the cookie contains sensitive information, then the server should ensure that the cookie has the `secure` flag set.
> 
> References: https://www.owasp.org/index.php/SecureFlag

The cookie is question is _gat_GSA_ENOR0.

Got an email reply from Freddie / DAP on 8 August that the cookie doesn't contain PII and that they don't really have plans to change anything. Being that it's not a cookie we can control, we can't really change anything about it. Freddie's email:
> The cookie you mention does not contain sensitive information. The information stored in that cookie is only used for Google Analytics and according to GA360 terms of service does not contain any personally identifiable information.

**Comment by PaulClark2** [comment]
DAP has determined resolving this issue is not an effective use of their resources because the cookie does not "carry" PII. Our continued use of DAP and the clear text cookie is an acceptably minimal risk, so closing.
