### ISSUE TITLE
[MED] Increase cipher strength - system dashboard JIRA (Due 10/12)

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3108]
### Summary

The remote host supports the use of SSL ciphers that offer medium strength encryption. Nessus regards medium strength as any encryption that uses key lengths at least 64 bits and less than 112 bits, or else that uses the 3DES encryption suite.

Note that it is considerably easier to circumvent medium strength encryption if the attacker is on the same physical network.

### Remediation

Reconfigure the affected application if possible to avoid use of medium strength ciphers.

**Comment by PaulClark2** [comment]
This is not website work, so closing. This is for the ITSS group.
