### ISSUE TITLE
Improve message for beginning of advanced search for statutes

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3111]
### Summary

**What we are after:**
Right now, when a user goes to the advanced search for statutes, they see a "no results" message which is confusing if one hasn't begun to search anything. We need to create a message similar to those used on other legal resource advanced search pages.

![image](https://user-images.githubusercontent.com/24437369/63045930-62e89d00-be9f-11e9-9bed-675bc685ab1a.png)

### Related issues

_List any relevant related issue(s)_

### Completion criteria

- [x] Draft message for users who access this page: https://www.fec.gov/data/legal/search/statutes/?search=
that explains what they can search for and how/if they can filter results (like the AO search) 

- [x] Run draft by the content team
- [x] Add approved draft to implementation ticket at #3112 

### Future work

- Implementation ticket at #3112 to update the API links and implement the message drafted in this ticket.

**Comment by JonellaCulmer** [comment]
@dorothyyeager I can't recall, has statutes always defaulted to an error message on first load?

**Comment by dorothyyeager** [comment]
@JonellaCulmer I'm not sure either. This turned up while testing the CSP Headers in feature. When I compared to the live site, I found this was our default state for the pre-search page, and it just seemed strange and confusing to get "no results" when you haven't yet searched.

**Comment by dorothyyeager** [comment]
Here's what I've drafted for a message for when users access this page without first searching something:

> The statutes search feature includes the Federal Election Campaign Act (52 U.S.C. §§ 30101 to 30146), the Presidential Election Campaign Fund Act (26 U.S.C. §§ 9001 to 9013) and the Presidential Primary Matching Payment Account Act (26 U.S.C. §§ 9031 to 9042). You can search statutes using keywords and/or statutory citations (full or partial).

(Note that the message in the screencap should also be retained for the situation when the user searches for something and there are no results.)

**Comment by bmathesonFEC** [comment]
Language looks good to me. Semi-unrelated, I noticed that in the Regs page we provide an example search below the search box. Should we add one for the statutes search?

![image](https://user-images.githubusercontent.com/33758291/64172916-0a644a00-ce24-11e9-9995-4124bbfe67af.png)

**Comment by dorothyyeager** [comment]
Thanks @bmathesonFEC - We've got it on the Statutes home page... 
![image](https://user-images.githubusercontent.com/24437369/64174560-8b711080-ce27-11e9-9e60-55f4498b8286.png)

But I agree, it would be nice to have on the advanced search page too. I'll add it into that implementation ticket.

**Comment by dorothyyeager** [comment]
I've updated the ticket at #3112 with the new message and example. We're ready to close this ticket.
