### ISSUE TITLE
Update advanced search opening message

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3112]
### Summary

**What we're after:**
We've been linking to GPO's old API address on the statutes page. We also are displaying a "no results" message. Both things need to be fixed to make it easier for users to use the search.

### Related issues

- #3111 
- https://github.com/fecgov/openFEC/issues/4028 (Default load)
- https://github.com/fecgov/openFEC/issues/3942 (Default load)
- https://github.com/fecgov/openFEC/issues/3942 (fix links)

### Completion criteria

- [x] Implement the message drafted in #3111 for those accessing the page before searching 
anything.:

> The statutes search feature includes the Federal Election Campaign Act (52 U.S.C. §§ 30101 to 30146), the Presidential Election Campaign Fund Act (26 U.S.C. §§ 9001 to 9013) and the Presidential Primary Matching Payment Account Act (26 U.S.C. §§ 9031 to 9042). You can search statutes using keywords and/or statutory citations (full or partial).

Note: We need to retain the current message too, for when an individual has actually searched for something and came up empty.

- [ ] Add same example on the advanced search keyword box as the one seen on the statutes page (https://www.fec.gov/data/legal/search/statutes/?search=spending):
![image](https://user-images.githubusercontent.com/24437369/64174707-d3903300-ce27-11e9-88d4-fbe6151bad01.png)

- [x] Second pair of eyes from content team to ensure links work and message is good to go.

- [x] create `openFEC` issue to fix default search behavior for statutes to make it consistent with other legal resource pages to load everything by default

### Future work
- Consider our design. The other advanced searches in legal resources bring up all the rules or all the AOs. Can we do similar for the statutes?

**Comment by dorothyyeager** [comment]
See https://www.fec.gov/data/legal/search/advisory-opinions/?type=advisory_opinions&ao_category=F for an example.

**Comment by rfultz** [comment]
@dorothyyeager, is this what we're after?

![image](https://user-images.githubusercontent.com/26720877/69279889-48674380-0bb3-11ea-9e2e-b8eeaa3a1c5b.png)

**Comment by dorothyyeager** [comment]
That's exactly it. Looks great @rfultz - thank you!
