### ISSUE TITLE
Implement new message for 500 Server Errors

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3113]
### Summary

**What we are after:**
We're improving the message for users when there is a 500 server error in the API, by referring them to our API Status page.

### Related issues

- #3109 

### Completion criteria

- [ ] Update 500 server error message to read:

> > ! Server error
> 
> Sorry, this page failed to load. Check the FEC’s API status page _(link to https://www.fec.gov/status)_ to see if we are experiencing a temporary outage. If not, please try again, and thanks for your patience.
> 
> If you’d like to contact our team, please use the feedback box on the bottom of any page or contact the FEC (_link to https://www.fec.gov/contact/_). 
- [ ] Add a reviewer from content team to review/proofread the related PR

**Comment by rjayasekera** [comment]
@lbeaufort I contacted Pingdom regarding secure public status page and below is the reply.

> We don't support officially secure status pages for custom domains.
 Rowena Moratin (Pingdom)

> Sep 23, 18:28 CEST

> I still don't have any idea when would this be available. I'll tag this up as a feature request to highlight the importance of this to our product management team. We do also have a public forum available here where feature requests can be submitted for product management to read!

--

But as a work around we can use following links:

http://status.open.fec.gov/ (this works)
https://status.open.fec.gov/ (add security exception on your browser)
Or we can call it pingdom status pages directly without the `Custom Domain`
**https://secure-stats.pingdom.com/x0blqgj29ogg** (`Secure Connection` but no `Custom Domain`)

**Comment by patphongs** [comment]
As a temporary work-around, we've applied a friendly redirect for the API status: https://www.fec.gov/status
