### ISSUE TITLE
CMS database performance

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#3116]
### Summary
Benchmark and load test CMS database.

**What we're after:**
We need to understand what level of stress the CMS database can take and still be performant. 

### Completion criteria

_List action items that need to be done to complete this task. List in checklist formatting._
- [ ] Benchmark CMS database performance
- [ ] Load test CMS database performance
- [ ] Make recommendations about CMS database performance

**Comment by lbeaufort** [comment]
This issue is addressed by #3907
