### ISSUE TITLE
Bring the EEO page into Wagtail

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3117]
### Summary

**What we are after:**
As part of our effort to shut down transition and update the office pages, we need to move the EEO pages at https://transition.fec.gov/about/offices/EEO/EEO.shtml and at https://transition.fec.gov/eeo/eeo.shtml into a new page combining both of the old pages' information.

### Related issues

- #3103 
- See FECNet page for EEO too, as well as IG page.

### Completion criteria

- [x] Draft content for new page in Word document for review by EEO office and content team
- [x] Draft Wagtail page (Resource template) with the content reviewed
- [x] Upload documents into Wagtail 
- [x] Second pair of eyes from EEO and content team
- [x] Make any requested changes and publish
- [x] Update the link on https://www.fec.gov/about/careers/ to point to new page
- [x] Add the old pages to the [redirect spreadsheet](https://docs.google.com/spreadsheets/d/1Jn5nC3fFku10RTCP5OAW6RiffjNBE4VwBubITQpCNK8/edit?usp=sharing) (proxy and www)
- [x] Update the organization chart.

### Future work

- [ ] Put in the redirect

**Comment by kathycarothers** [comment]
@dorothyyeager where do we plan to make this a child page off of?

**Comment by dorothyyeager** [comment]
The "About the FEC" page. It'll replace the link to the transition page on https://www.fec.gov/about/careers/, so should just be a child page of the main "About" page.

**Comment by kathycarothers** [comment]
@dorothyyeager thanks!

**Comment by kathycarothers** [comment]
I have drafted the page and have sent it over to the content team and EEO for review.

**Comment by kathycarothers** [comment]
Talked with Kevin and he is going to review the draft and get back to me by next week.

**Comment by dorothyyeager** [comment]
Posting on behalf of @kathycarothers who is traveling. Before she left, she met with Kevin Salley (FEC EEO Officer) who gave his final approval to publish. The page is now live at https://www.fec.gov/about/equal-employment-opportunity/. The old pages have been added to the redirect spreadsheet and the link in the organization chart is updated as well. We're ready to close this ticket. Great work, Kathy!
