### ISSUE TITLE
Update the Updates information box to add a link to new Record archive page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3122]
### Summary

**What we're after:**
We're getting the Record archive off of transition and need to make a link to the new page available.

### Related issues

- #2839 

### Completion criteria
- [x] ask @dorothyyeager for link for new sentence
- [ ] Add a sentence to the second paragraph of the About Latest Updates box to read, "Access Record articles from 1975 through 2004 on the Record archive page." This sentence should be inserted as the second sentence of the second paragraph.
- Record archive link: https://www.fec.gov/updates/record-archive-1975-2004/

![image](https://user-images.githubusercontent.com/24437369/63455801-7a81d180-c41b-11e9-9466-58c3850f1634.png)

- [ ] Make the new sentence link to the Record archive page.
- [ ] Have @dorothyyeager review PR.

**Comment by jason-upchurch** [comment]
@kathycarothers do you happen to know where the link @dorothyyeager mentioned above is located?

**Comment by JonellaCulmer** [comment]
Updated the original comment with the appropriate link.

**Comment by kathycarothers** [comment]
@jason-upchurch @JonellaCulmer Thank you!

**Comment by dorothyyeager** [comment]
Thanks everyone! @kathycarothers @JonellaCulmer @jason-upchurch

**Comment by patphongs** [comment]
@JonellaCulmer Would like to pair on this ticket
