### ISSUE TITLE
[Due 9/3/19] Update Wagtail pages to reflect commissioner departure

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#3128]
Commissioner Petersen is leaving the Commission, effective August 31. We'll need to make changes to our website to reflect this change in leadership. These changes need to be implemented the morning of September 3.

In the CMS, we'll need to update

- [x] https://www.fec.gov/about/leadership-and-structure/ to move the Commissioner's page to all Commissioners, change the image to the blank icon and vacant seat pattern, and re-order the images so that the three vacant seats appear at the bottom of the list.
- [x] https://www.fec.gov/press/resources-journalists/commissioners/ to remove the Commissioner
- [x] Update the slug for his Commissioner Petersen's page to be correctly spelled: `about/leadership-and-structure/matthew-s-petersen/`
- [x] Create redirect in Wagtail from old slug `about/leadership-and-structure/mathew-s-petersen/` to new slug `about/leadership-and-structure/matthew-s-petersen/`

**Comment by dorothyyeager** [comment]
On the press page I removed the Commissioner and also updated the sentence about the Chair.

To modify the Leadership and Structure page, I needed to add the expiration date of Commissioner Petersen's term which was 8/31/2019. That created the blank spot and moved him off the current Commissioner's list. The page now looks like this. 
![image](https://user-images.githubusercontent.com/24437369/64173166-aaba6e80-ce24-11e9-8094-4cdd84566df8.png)

Moving the blank seat to the bottom won't happen until Commissioner Hunter is named Vice Chair, I suspect.

**Comment by dorothyyeager** [comment]
We'll need to update the "current Commissioners" in a grid configuration to make the three active Commissioners go to the top. Since that is hard-coded work, I've opened up a ticket at #3137

**Comment by dorothyyeager** [comment]
@patphongs hotfix for the grid in #3137 resolved the issue and the page at https://www.fec.gov/about/leadership-and-structure/ now looks like this: 
![image](https://user-images.githubusercontent.com/24437369/64203615-dc055f80-ce61-11e9-87ad-823dab1529a7.png)

Closing the ticket; Wagtail work is done.
