### ISSUE TITLE
[Due 9/3/19] Update Homepage to reflect commissioner departure

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#3129]
Commissioner Petersen is leaving the Commission, effective August 31. We'll need to make changes to our website to reflect this change in leadership. These changes need to be implemented the morning of September 3.  We'll need to deploy the change to the homepage as hotfix.

We need to update the list of Commissioners at the bottom of the homepage to show the Commissioner's departure by:

- [ ] Remove Commissioner Petersen's picture and link
- [ ] Add another Vacant Seat icon/text to the bottom of the list.
- [ ] Prepare and deploy hotfix

**Comment by JonellaCulmer** [comment]
Work merged, so closing.
