### ISSUE TITLE
No consistent data on Candidate Financial Summary page click back from RAISING/SPENDING page

### ISSUE THREAD

**Issue by fec-jli** [fecgov/fec-cms#3135]
_Briefly describe what happened._

go to any candidate profile page.
ex: https://dev.fec.gov/data/candidate/H8GA06195/
click **RAISING/SPENDING** menu.
chose **TWO-YEAR PERIOD** = 2019-2020
click back: **FINANCIAL SUMMERY** menu

will see total display 2019 data, not 2018 data. and user couldn't get 2017-2018 data on this page anymore. 
<img width="1001" alt="not_consistent_data" src="https://user-images.githubusercontent.com/24395751/64039083-d3dab680-cb27-11e9-9395-88271ce09a24.png">

## Completion criteria ##
- [x] determine if behavior is acceptable
- [x] if not, develop additional completion criteria (groom)

**Comment by patphongs** [comment]
This may be the same issue as the overlay bug. @jason-upchurch will attach that ticket to this one.

**Comment by jason-upchurch** [comment]
> This may be the same issue as the overlay bug. @jason-upchurch will attach that ticket to this one.

Sorry @patphongs I looked for "spin" or "overlay" in the search criteria to find the other issue, but nothing was returned that is open.
