### ISSUE TITLE
Disable cycle button for candidate without activity on candidate financial summary

### ISSUE THREAD

**Issue by fec-jli** [fecgov/fec-cms#3136]
_Briefly describe what you'd like to see changed._

go to candidate profile page:
ex: https://dev.fec.gov/data/candidate/P00003392/?cycle=2008&election_full=true
This candidate doesn't have any activity in 2005-2006. 
We can disable the 2005-2006 button (grey out)

Note: Think about to use the new column **fec_cycles_in_election** in
public.ofec_candidate_totals_detail_mv
<img width="1007" alt="grey_out" src="https://user-images.githubusercontent.com/24395751/64039738-5ca62200-cb29-11e9-839e-683ac0d4606b.png">

**Comment by lbeaufort** [comment]
It looks like this issue has been addressed by one of our recent candidate profile page changes![Screen Shot 2019-10-21 at 11.59.26 AM.png](https://images.zenhubusercontent.com/59a579f28f62dc7798c47359/4fdcd286-3436-4dc8-b38c-959b942c478e)
