### ISSUE TITLE
Research removing 'unsafe-inline' and 'unsafe-eval' from Content Security Policy [DUE 11/3/2019]

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3138]
See #3124. We should Make changes to remove 'unsafe-inline' and 'unsafe-eval' from Content Security Policy. This issue affects global constants throughout the `fec-cms` codebase.

## Completion criteria ##
- [ ] identify source of vulnerable javascript code (e.g., check glossary, look for inline `<script>` tag--search across codebase for any instances of tag, `href=<js execution>`
- [ ] develop plan for using these tags in a secure way
- [ ] create any necessary issues to implement plan

**Comment by patphongs** [comment]
@jason-upchurch and @lbeaufort would like to pair on learning in this ticket. Thanks!

**Comment by patphongs** [comment]
@johnnyporkchops @lbeaufort @jason-upchurch We intend to incorporate google tag manager (GTM) into all of our environments. GTM, however, requires `unsafe-inline` to function as it injects JS into the page via the gtm.js script. Here's more information from google: https://developers.google.com/tag-manager/web/csp

**Comment by johnnyporkchops** [comment]
Issue moved to [fecgov/fec-accounts #212](https://github.com/fecgov/fec-accounts/issues/212) via [**ZenHub**](https://www.zenhub.com/)
