### ISSUE TITLE
Fix API links in Statutes

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#3145]
**What we're after:**
Following up on the work to [update that message](https://github.com/fecgov/fec-cms/issues/3112) on the Statutes search, we now need to update the links to make sure that when a user clicks on the link to a specific statute that it actually goes to the appropriate page. 

### Related issues
- [ ]  https://github.com/fecgov/fec-cms/issues/3112

### Completion criteria

- [ ] Update the links to the API so they point to the govinfo API, not http://api.fdsys.gov/ for each provision (which GPO has moved on from using). 
For Title 26: See https://www.govinfo.gov/app/details/USCODE-2017-title26/USCODE-2017-title26-subtitleH for details
For Title 52: See https://www.govinfo.gov/app/details/USCODE-2017-title52/USCODE-2017-title52-subtitleIII for details.

### Future work

Open up followup tickets to consider how to improve the Statutes search.

**Comment by lbeaufort** [comment]
This is an API issue, so moving to the openFEC repo. Check out the `index_statutes` function in the API.

Example query: https://fec-dev-api.app.cloud.gov/v1/legal/search?hits_returned=20&type=statutes&from_hit=0&q=contribution

**Comment by lbeaufort** [comment]
Issue moved to [fecgov/openFEC #3942](https://github.com/fecgov/openFEC/issues/3942) via [**ZenHub**](https://www.zenhub.com/)
