### ISSUE TITLE
Draft disclaimer examples 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#3148]
### 

**What we're after:**
To present the regulated community with disclaimer examples for the real world.

### Completion criteria

List action items that need to be done to complete this task. 
- [x] Draft examples
- [x] Draft images 
- [x] Review by Info Div managers
- [x] Incorporate manager feedback into examples
- [x] Circulate to content team 
- [x] Circulate to OGC 
- [x] OGC approval

### Future work

- [ ] John creates example template in Wagtail [#3149 in 10.2]
- [ ] Example template with embedded video capability
- [ ] Draft future ticket for posting examples: 
- [ ] Incorporate OGC comments and edits
- [ ] Publish images

**Comment by djgarr** [comment]
Created candidate disclaimer examples

**Comment by djgarr** [comment]
Circulated examples to Info Div. managers.

**Comment by djgarr** [comment]
Received feedback from Info Div managers. Incorporating feedback into updated examples to circulate to OGC

**Comment by djgarr** [comment]
Circulated examples to the content team on 9/12

**Comment by djgarr** [comment]
Created a ticket for the publication step for the examples (#3179)

**Comment by jjonesfec** [comment]
Added Stand By Your Ad language to existing disclaimer, awaiting final review.

**Comment by jjonesfec** [comment]
Edited above to add "TV AD" to sentence.

**Comment by djgarr** [comment]
circulated to OGC on 9/26

**Comment by djgarr** [comment]
Closing ticket. Part 2 continues at #3179
