### ISSUE TITLE
Create Example Page template in Wagtail

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3149]
### Summary

To assist with our upcoming work in making disclaimer examples and keep Wagtail tidy and easy for content managers, we'd like to make a new template similar to the reporting example template, but called "Example page"

### Proposed Behavior / Feature

We'd like the template to work like this one (https://fec-prod-proxy.app.cloud.gov/admin/pages/add/home/reportingexamplepage), but be called "Example page." We'd like to have a few other features added, such as embeddable video and internal/external buttons.

Here's a screenshot of the reporting example template:

![image](https://user-images.githubusercontent.com/24437369/65260926-31ce3e80-dad5-11e9-85be-ccd65118792c.png)

For this template, we'd like to add the following options to what's already in the reporting example template:
- image into the body portion (similar to what's available in custom/resource page templates)
- video embed into the body portion  (similar to what's available in custom/resource page templates)
- internal button into the body portion (See #2935 for background on this button)
- external button into the body portion  (See #2935 for background on this button)
- "Example" added as an option into "pre-title" drop down

### Use Case

Users who will love the examples we are making of proper disclaimers. (Currently being drafted in #3148 )

## Completion criteria ##
- [ ] Add the requested features listed above into the requested new template (based off the reporting example template)
- [ ] Testing by content team to ensure it has what we need for the disclaimer examples in #3148

**Comment by patphongs** [comment]
@dorothyyeager Can you please highlight the elements you want to be present or added to this new "Example page" template?

**Comment by dorothyyeager** [comment]
I've updated the ticket with a screenshot and list of the elements we're looking for in this new template.

**Comment by johnnyporkchops** [comment]
@dorothyyeager. Would it make sense to add the additional features to the ReportingExamples template and that could then be used for the disclaimer examples as well?

**Comment by dorothyyeager** [comment]
I think so, yes.
Sent from my iPhone

On Oct 27, 2019, at 11:41 PM, John Carroll <notifications@github.com<mailto:notifications@github.com>> wrote:


@dorothyyeager<https://github.com/dorothyyeager>. Would it make sense to add the additional features to the ReportingExamples template and that could then be used for the disclaimer examples as well?

**Comment by dorothyyeager** [comment]
Clarifying - If we can make the choice of "Example" available along with "Example Scenario" and "Reporting Example" that would be great. We must have the ability to embed videos too. Thanks @johnnyporkchops

**Comment by johnnyporkchops** [comment]
@dorothyyeager Currently, I believe your team uses either html block or Rich text block to embed videos, correct?
There is already a Rich Text block in the template, should I add HTML too?

**Comment by johnnyporkchops** [comment]
@dorothyyeager , If you get a chance, take a look at feature space where you can test  ReportingExample page template with new features.
https://fec-feature-cms.app.cloud.gov/admin
