### ISSUE TITLE
Automate Wagtail database backup

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3150]
@PaulClark2 commented on [Tue Jun 11 2019](https://github.com/fecgov/fec-accounts/issues/180)

## Completion criteria ##
- [ ] Create CRON job to automatically backup the Wagtail database.
- [ ] Save backup in an S3 bucket

---

@lbeaufort commented on [Wed Jul 10 2019](https://github.com/fecgov/fec-accounts/issues/180#issuecomment-510170849)

@ChingKuan is working on this issue

**Comment by lbeaufort** [comment]
Possibly investigate updating `dev` and `stage` dbs?

**Comment by patphongs** [comment]
@PaulClark2 Instructions on how to back-up and restore wagtail databases: https://github.com/fecgov/fec-cms/wiki/Backup-or-Restore-Wagtail-PostgreSQL-database-in-dev,-staging,-or-production

**Comment by rjayasekera** [comment]
Currently we are backing up Production cms and eregs database daily to DC4 data center for DR purposes.  We are keeping them for a one week.  

- fec_cms_gov_cloud_prod_20190909.sql
- fec_eregs_gov_cloud_prod_20190909.sql

We can restore these two database from the backups in an event of a disaster. We have also tested the backup/restore process.

cc @PaulClark2 @patphongs @lbeaufort

**Comment by patphongs** [comment]
Need to discuss access to the backup data

**Comment by patphongs** [comment]
We'll make a new ticket to discuss where the Wagtail DB back up will be so that more staff has access to it. @patphongs update with ticket number.
