### ISSUE TITLE
Comprehensive front-end testing after two changes

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3152]
After https://github.com/fecgov/fec-cms/pull/3126 and https://github.com/fecgov/fec-cms/pull/3154 are merged, we should do some time-boxed testing of the front-end site.

**Comment by patphongs** [comment]
2 issues have been created to test google tag manager and eslint prior to deploy. Google tag manager is under a feature flag, so it can be turned on and off:

https://github.com/fecgov/fec-cms/issues/3189
https://github.com/fecgov/fec-cms/issues/3186

**Comment by patphongs** [comment]
closing in favor of tickets noted above
