### ISSUE TITLE
Candidate page 404ing

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3163]
@fec-issues-bot commented on [Thu Sep 12 2019](https://github.com/fecgov/FEC/issues/9153)

## What were you trying to do and how can we improve it?
 I was trying to review the contributions to Elizabeth Warren for 2018 Senate seat. 

## General feedback?
 After generating the list of senate candidates for 2018, I selected Elizabeth Warren's name and then received the Page Not Found message. 

## Tell us about yourself
 I am a private citizen interested in campaign contributions. 

## Details
* URL: https://www.fec.gov/data/candidate/S2MA00170/ 
* User Agent: Amazon CloudFront

**Comment by pkfec** [comment]
API hotfix has been deployed. here is the PR # https://github.com/fecgov/openFEC/pull/3958 The data now appear in production. Closing this issue
