### ISSUE TITLE
State Filing Waiver Program: Remove from Transition

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#3169]
### Summary
A candidate committee is seeking advice from the FEC regarding the requirement to send copies of their FEC filings to the respective state election offices, except for those states exempt under the State Filing Waiver Program. There is a transition page, and many dead links out there with no redirect.

Part of a bigger effort to remove content from Transition.

**Dead link:** http://www.fec.gov/pages/statefiling.shtml
**Transition page:** https://transition.fec.gov/pages/statefiling.shtml

Regulation: [108.1](https://www.fec.gov/regulations/108-1/2019-annual-108#108-1)

### Completion criteria
- [x] Add redirects for transition page and dead link.

### Completion criteria (option 2)
- [x] Create new page
- [x] Circulate for Content Team review
- [x] Add redirects for transition page and dead link
- [x] Publish page

**Comment by kathycarothers** [comment]
The page will remain a link off the Public Records page. I will begin drafting the Wagtail page.

**Comment by bmathesonFEC** [comment]
There's a link on the Public Records page!? I had no idea.

**Comment by kathycarothers** [comment]
Page has been drafted. I will be sending an email out to the content team to review the page shortly.

**Comment by kathycarothers** [comment]
The page has been published and will be added to the master redirect sheet.
