### ISSUE TITLE
Inventory RAD FAQs

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3175]
### Summary

**What we are after:**
Getting the RAD FAQs off of transition and making sure the information is on fec.gov

### Completion criteria

- [x] Look at RAD FAQs at https://transition.fec.gov/rad/index.shtml to see what's already covered elsewhere on fec.gov 
- [x] Identify any gaps and create drafting tickets if needed

### Future work
For 10.3, put in ticket to 
- add any needed redirects for old RAD FAQs pages to redirect spreadsheet
- Identify the links for RAD to use in RFAIs.

**Comment by bmathesonFEC** [comment]
Working with RAD analysts to inventory the content on FAQ to prepare for drafting in 10.3

**Comment by bmathesonFEC** [comment]
Delegated PAC and Party sections to RAD analysts.

**Comment by bmathesonFEC** [comment]
Received all of the feebdack from RAD reviewers. Docs saved on the network. Next ticket: #3249 for drafting new content.
