### ISSUE TITLE
Update the "no results" message for the Updates search with new Record archive link

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3176]
### Summary

**What we're after:**
We've updated the Record Archive page in fec.gov and now we need to swap out the link in the no results message for Record searches.

![image](https://user-images.githubusercontent.com/24437369/65150042-46390b00-d9f1-11e9-8d6a-640122bde92a.png)

### Related issues

- #3122 

### Completion criteria

- [ ] Change the link in the no results message above to point to https://www.fec.gov/updates/record-archive-1975-2004/ instead of the transition page.

### Future work
Record archive page will be part of our next redirect ticket.

**Comment by patphongs** [comment]
merged PR so closing
