### ISSUE TITLE
Redirects for 10.2

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3178]
### Summary

**What we're after:**
We've gotten a few pages off of transition and into Wagtail lately, and it's time to redirect the old page to the new version.

### Completion criteria (see [spreadsheet](https://docs.google.com/spreadsheets/d/1Jn5nC3fFku10RTCP5OAW6RiffjNBE4VwBubITQpCNK8/edit?usp=sharing) for specifics)

- [x] Redirect old Record archive pages to new page (proxy and Wagtail)
- [x] Redirect old Combined Federal State Disclosure Directory files to new page (proxy and www)
- [x] Redirect a few stray pages of the 90s as indicated on spreadsheet
- [x] After the redirects are deployed, test them and update spreadsheet
- [x] Put in ticket for front end to take down the pages from transition.

**Comment by kathycarothers** [comment]
The redirects has been plugged, reviewed and are ready deployment and to be merged.
