### ISSUE TITLE
Disclaimer Example Publication

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#3179]
**Work on during the second week of 10.5 after the November 12 release.**

### Summary

**What we're after:**
To present the regulated community with disclaimer examples for the real world.

### Related issues
- #3148 (Drafting ticket)
- John creates example template in Wagtail [#3149 in 10.2]

### Completion criteria

- [x] Create image blocks using example template with embedded video capability
- [x] Incorporate OGC comments and edits
- [x] Ensure images are sized properly for wagtail
- [x] Add images to wagtail
- [x] Draft captions for examples using approved language
- [x] Check accessibility of the video example @JonellaCulmer 
- [x] Review disclaimer caption language and verify content guide compliance
- [x] OGC review of caption language. Update (if needed) based on input  
- [x] Add fundraising invite example to fundraising page as well
- [x] Publish examples
- [x] Insert examples in "Advertising and disclaimer" page

**Comment by dorothyyeager** [comment]
OGC would like to ensure we add some language to the disclaimer page itself regarding the full name requirement. They also suggested making the name of the campaign less simplistic to better illustrate that it's a full name.

For the full name requirement, we could crib from the language approved for page on making independent expenditures:

> “A disclaimer notice must contain the full name of the individual, group, political committee, corporation, or labor organization that paid for the communication, along with any abbreviated name it uses to identify itself.”

They also would like us to reference IRS requirements but not craft them into our examples. Here's approved language from the Candidate Guide:

> IRS Notice Requirements
> Section 6113 of the Internal Revenue Code requires political committees whose gross annual receipts normally exceed $100,000 to include a special notice on their solicitations to inform solicitees that contributions are not tax deductible.

We could insert that language as the side text for the solicitation image.

**Comment by djgarr** [comment]
Updated completion criteria with next steps following call

**Comment by dorothyyeager** [comment]
We've sent the disclaimer captions to OGC for review.

**Comment by djgarr** [comment]
OGC reviewed examples. Just had one minor edit. Change has been updated in wagtail

**Comment by johnnyporkchops** [comment]
@djgarr - You can change the width of the video frame to 80% to match the surrounding paragraphs by changing the CSS width attribute of the `.vidframe` class from 100% to 80%.

**Comment by JonellaCulmer** [comment]
@djgarr Just want to document what we talked about. 

As @johnnyporkchops mentioned above we were going to modify the size of the video to 80%. At 100% it's a bit imposing and at 85% it's in better alignment with the content. 

We also talked about making the first sentence that describes how to use the video a separate paragraph from the rest of the text, to help distinguish it and make it clear that it's a playable video. 

Everything else looks good. Thanks!

**Comment by johnnyporkchops** [comment]
Once we establish a final (or MVP) for this, we should move the CSS into our SCSS instead of have it in the html block. This would require a PR, so we could do a followup issue. It could probably go in `components/_responsive-object.scss`

**Comment by djgarr** [comment]
I published the examples just now. The examples are now live and attached to https://fec-prod-proxy.app.cloud.gov/help-candidates-and-committees/making-disbursements/advertising/ and https://fec-prod-proxy.app.cloud.gov/help-candidates-and-committees/making-disbursements/fundraising-notices-campaigns/
