### ISSUE TITLE
New homepage banner image

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3183]
**What we're after:**
We need to consider and identify a new banner image for the homepage. Consult with visual designer in Information division.

**Related issues:**
https://github.com/fecgov/fec-cms/issues/2078

**Completion criteria:**
- [x] Compile recommendations and present to necessary stakeholders
- [x] Finalize image and open followup implementation issue

### Future work

Implementation issue later in the PI.

**Comment by JonellaCulmer** [comment]
@AmyKort @PaulClark2 Let me know your thoughts for the below suggested banner image.

Below is a recommendation for the homepage image. As shown below it's at about 50% completion. It requires additional tweaking of the icons and accompanying text.  The icons and text shown were included in the original design/stock file and we plan to use our own iconography for our site. But as it shown below would essentially be the way it would appear on our live site. 

@jjones describes the photo this way:

> It has two components: the regulatory icon matrix and the stanchion flag background. The two are blended in a way to create balance with each other and with the surrounding landing page elements. The interconnected icons are vector and can be modified in any number of ways to satisfy our needs.

![image001](https://user-images.githubusercontent.com/31663028/69181688-8db94180-0add-11ea-9916-5396ab31ab47.jpg)

**Comment by AmyKort** [comment]
I think this is a great idea. Thanks!!

**Comment by PaulClark2** [comment]
I agree!  Thanks for all your work on this.

**Comment by jjonesfec** [comment]
Here's the revised image, shown in context.

Since your initial feedback on the concept was positive, I further developed the image by incorporating the FEC's web icons into the matrix while adding some depth and lowering their opacity to allow them to better integrate into the image.

Each design element is customizable and can be easily modified should any further changes be needed.
![Blue Blend Final D2](https://user-images.githubusercontent.com/10223901/70074746-56f92600-15c9-11ea-919e-ef107f95a024.jpg)

**Comment by patphongs** [comment]
@JonellaCulmer These designs look great. Can you also provide mock ups on how this would look on mobile layouts?

**Comment by jjonesfec** [comment]
Sure. For reference, here's how the current image looks on my iPhone:

![Unknown](https://user-images.githubusercontent.com/10223901/70078321-7e072600-15d0-11ea-8f7c-64521c3433a8.png)

**Comment by jjonesfec** [comment]
Here's are iPad and iPhone mock-ups
![iPhoneD1](https://user-images.githubusercontent.com/10223901/70080096-f15e6700-15d3-11ea-887c-fb7a374bafbb.jpg)
 in context and assuming that the image resizes vertically while staying centered.
![iPad D1](https://user-images.githubusercontent.com/10223901/70080070-e60b3b80-15d3-11ea-8902-9c88978a05a6.jpg)

**Comment by AmyKort** [comment]
I like it. Are we ready for me to show it to some people beyond the team?

**Comment by JonellaCulmer** [comment]
Blocked while waiting for feedback from other offices.

**Comment by JonellaCulmer** [comment]
Updated banner image
<img width="947" alt="Screen Shot 2020-02-28 at 9 49 08 AM" src="https://user-images.githubusercontent.com/31663028/75558344-b1aaee00-5a0f-11ea-9450-0eea706bfad6.png">

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issue here: https://github.com/fecgov/fec-cms/issues/3585
