### ISSUE TITLE
Tag Manager testing

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#3186]
Placeholder for Tag Manager testing. Should probably include a tutorial of what Tag Manager is and does.

Testing Tag Manager's implementation will be checking each environment's source for home, other html template, Jinja templates, and legal templates to make sure the right option and accounts are being included in the page source. Without the tag manager feature flag, the pages should include Google Analytics and GSA/DAP. With the flag on, those elements should be replaced with the GTM elements, and using the proper container IDs (Production vs everything else).

It would be nice to confirm that GA and DAP tracking are being included for Production so we don't lose data when switching to GTM.

However, one of the biggest benefits of GTM is that those approved to edit the containers and publish them can do so without the extended build, review, test, review, two-week queue, document, release schedule—we can update the code, submit it for review (with documentation), and it appears on the site with the next page load. Then we test / verify, and update again if we need to.

As far as things to test:
- Confirm that a data page and a legal page are showing Google Analytics / GSA DAP (may need to set DEBUG = false)
- Confirm that Home and a Wagtail page are showing GA / GSA DAP (will need to set DEBUG = false)
- Set the feature flag to true
- Confirm that Home, a Wagtail page, a data page, and a legal page are showing two Tag Manager elements—a `<script>` at the end of the `<head>`, and a `<noscript>` at the top of the `<body>`
- Check the container IDs for the GTM tags—Production should have its own and the others (dev, stage, feature, local) should have a different one
- To check whether GA and DAP are loaded check the Inspector's network traffic
- In the console, enter `ga` to check whether the GA object exists
- DAP should load into Production but not the other(s)
- The GA property ID should be different for Production than the others'

**Comment by JonellaCulmer** [comment]
Closing in favor of #3906
