### ISSUE TITLE
Decide on final acceptance criteria for Where contributions come from

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3195]
### Summary
We need to decide on the final acceptance criteria prior to go live of the Where contributions come from feature

**Completion criteria:**
- [x] Decide on criteria needed before go live of this feature. See this [document](https://docs.google.com/document/d/19hJEhPYfSl__6Z9ukhk6WvBHVJZbqKns6r5rtMLHjEw/edit) 🔒 
- [x] Assign to @rfultz the final acceptance criteria prior to go live

**Comment by JonellaCulmer** [comment]
Closing in favor on new feature work ticket: https://github.com/fecgov/fec-cms/issues/3203
