### ISSUE TITLE
Fix logic for browse individual contributions button on WCCF feature

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3204]
**What we're after:**
This is one of the four tasks that needs to be completed as part of the final work required before launching the WCCF feature to production. All other tasks will be completed [here](https://github.com/fecgov/fec-cms/issues/3203). 

**Complete list of work needed:** https://docs.google.com/document/d/19hJEhPYfSl__6Z9ukhk6WvBHVJZbqKns6r5rtMLHjEw/edit#

### Related issues

- [ ] https://github.com/fecgov/fec-cms/issues/3203 

### Completion criteria

- [ ] Browse individual contributions button should link to filtered list of relevant transactions by candidate’s committees and by applicable cycles 
https://fec-stage-proxy.app.cloud.gov/data/receipts/individual-contributions/?committee_id=C00580100&two_year_transaction_period=2018&two_year_transaction_period=2020

**Comment by lbeaufort** [comment]
It looks like the API call for authorized committees isn't being made. I'm having trouble updating the JavaScript in https://github.com/fecgov/fec-cms/blob/524e236a0dd298db813db5f7919258647d695f7b/fec/fec/static/js/widgets/contributions-by-state-box.js to make the call.

API calls needed for the map: https://www.draw.io/#G1t-wmP_LNNvC1yBeQm6HAq3176NYtEcFD

Example API call needed for authorized committees: https://api.open.fec.gov/v1/candidate/P80001571/committees/?per_page=100&API_KEY=DEMO_KEY&designation=P&designation=A&cycle=2020
