### ISSUE TITLE
Redirects: RAD FAQs and other pages

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#3209]
### What we are after:
Set up redirects.

Non RAD pages:
### Completion criteria (see [spreadsheet](https://docs.google.com/spreadsheets/d/1Jn5nC3fFku10RTCP5OAW6RiffjNBE4VwBubITQpCNK8/edit?usp=sharing) for specifics)
- [x] Identify pages that need to be redirected (enter on spreadsheet) and where to redirect to (proxy and do we need a www or Wagtail redirect too)
- [x] After redirect is entered, @patphongs will deploy and merge.
- [x]  After the redirects are deployed, test them and update spreadsheet
- [x] Put in ticket for front end to take down the pages from transition.

**Comment by dorothyyeager** [comment]
We've got a few other redirects ready to be done, so best to just do them all at once :) I added them to the spreadsheet and also edited the issue title to reflect this (cc: @bmathesonFEC)

**Comment by kathycarothers** [comment]
I have entered the redirects for the non RAD pages for this ticket. They have been sent to @patphongs and @dorothyyeager for review.

**Comment by kathycarothers** [comment]
All work has been completed.
