### ISSUE TITLE
Transition pages take down ( Redirects 10.2) 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#3212]
### Summary

**What we're after:**
_Now that some redirects are in place after this last sprint, it's time to take down the old transition pages._

### Related issues

- #3178 

### Completion criteria
_Remove the following pages from the transition site: (These were redirected in 10.2)_

- [x] /info/apptwo.htm
- [x] /info/appone.htm
- [x] /pdf/record/1996/index96_1.htm
- [x] /pdf/record/1996/index96.htm
- [x] /pages/fecrecord/fecrecord.shtml
- [x] /pages/record.shtml
- [x] /pubrec/cfsdd/cfsdd.shtml
- [x] /pubrec/cfsdd/cfsded_000.pdf
- [x] /pages/statefiling.shtml

**Comment by johnnyporkchops** [comment]
These pages were deleted:
delete: 's3://cg-9b32b324-4671-48ca-b13b-a37b742f7443/info/appone.htm'
delete: 's3://cg-9b32b324-4671-48ca-b13b-a37b742f7443/info/apptwo.htm'
delete: 's3://cg-9b32b324-4671-48ca-b13b-a37b742f7443/pages/fecrecord/fecrecord.shtml'
delete: 's3://cg-9b32b324-4671-48ca-b13b-a37b742f7443/pages/record.shtml'
delete: 's3://cg-9b32b324-4671-48ca-b13b-a37b742f7443/pages/statefiling.shtml'
delete: 's3://cg-9b32b324-4671-48ca-b13b-a37b742f7443/pdf/record/1996/index96.htm'
delete: 's3://cg-9b32b324-4671-48ca-b13b-a37b742f7443/pdf/record/1996/index96_1.htm'
delete: 's3://cg-9b32b324-4671-48ca-b13b-a37b742f7443/pubrec/cfsdd/cfsdd.shtml'
delete: 's3://cg-9b32b324-4671-48ca-b13b-a37b742f7443/pubrec/cfsdd/cfsded_000.pdf'
