### ISSUE TITLE
Admin Termination and Debt Settlement Page: Implementation Ticket

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#3213]
### Summary
Currently there is no designated place on FEC.gov for documents relating to Administrate Termination and Debt Settlement Plans that are required to be hosted on the site.  This ticket is a placeholder for implementing decisions made in #2482.

**Location on fec.gov:**
The new AT/DSP page will be listed on [Policy Statements, Interpretive Rules, and Other Guidance](https://transition.fec.gov/law/policy.shtml) under [Other Guidance](https://transition.fec.gov/law/policy.shtml#guidance).

**Page format:**
The page will be a resource page with document lists for each referral. 

### Previous Work
Create Admin Term/DSP page #2482

### Completion criteria
- [x] Add note to sprint 10.6 ticket (#3220) about reassessing the home of this information at that time. 
- [x] Content team, upload PDFs of documents supplied by OGC.
- [x] Create a Wagtail page to house AT and DSP charts.
- [x] Get RAD/OGC approvals on page
- [ ] Publish and add link to this page on transition: https://transition.fec.gov/law/policy.shtml

### Future work

Confirm workflow with RAD/OGC to ensure future documents are updated to FEC.gov timely.

**Comment by bmathesonFEC** [comment]
After working on the draft for this page in stage, I have additional questions:
- the naming convention for the PDFs
- the top description for the page? RAD/OGC provided section descriptions for AT and DSP, but we might need a page heading under the title.

**Comment by bmathesonFEC** [comment]
I ran into a few issues while attempting to create the document table as planned. The wagtail _document list_ didn't quite work because each AT or DSP referral has two documents (or more) for each heading but the _document list_ only has one. I ended up stealing some HTML from other parts of the site to try and make something that looks nice:

```
<div class="post">
<p class="t-sans post__doc">
```

![image](https://user-images.githubusercontent.com/33758291/66682186-6bace380-ec42-11e9-8c62-00631c584364.png)

**Comment by bmathesonFEC** [comment]
I got some feedback from RAD on the format of the page I've setup in stage, as a result I'm ready to start putting this page together in production.

@dorothyyeager Are you ok if I move forward with our -- briefly discussed -- idea to create a draft wagtail page called "Legal: Policy and Other Guidance" under legal resources? Set up for #3220 that we have tagged as a 10.6 issue. If so, I'll put this AT and DSP page within that page and publish it before the actual Policy and Other Guidance page goes live.

**Comment by dorothyyeager** [comment]
@bmathesonFEC I'm good with that. It gives both the AT/DSP and the policy page their new homes (and the AT/DSP page will still work even if the policy page is not yet live). We may want to put in a temporary redirect for  the breadcrumb it will create.

**Comment by bmathesonFEC** [comment]
Approved by RAD. Incorporated feedback from the content team. Waiting for OGC.

**Comment by bmathesonFEC** [comment]
Page is approved by OGC. The only comment was about the location of the AT/DSP page on the site, I added their feedback to #3220 to reflect their feedback. 

Final push:
- update transition with the link to the new page: (@dorothyyeager, can you help make this change? Link: https://www.fec.gov/legal-resources/policy/administrative-terminations-and-debt-settlement-plans/

![image](https://user-images.githubusercontent.com/33758291/67504448-5e86f000-f657-11e9-97d0-e5afe42329d4.png)

- I added a redirect for the Policy and Other Guidance breadcrumb [spreadsheet](https://docs.google.com/spreadsheets/d/1Jn5nC3fFku10RTCP5OAW6RiffjNBE4VwBubITQpCNK8/edit#gid=1351118154) . Also updated #3220 completion criteria to remove the redirect.

Once the transition Policy and Other Guidance page is updated this issue can be closed.

**Comment by bmathesonFEC** [comment]
AT/DSPs now linked to from Policy and Other Guidance:  ttps://transition.fec.gov/law/policy.shtml#policy

Home of this page will be reevaluated as part of #3220.
