### ISSUE TITLE
Turn on "Where Contributions Come From" map after 10/28 release deploy

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3218]
## Summary
We nearing publication of WCCF. All code ready, must change one variable to make the feature live.

## Completion Criteria
- [x] (Robert) Key needs to accurately match the colors shown in the map for each candidate. For states with money. Don’t include anything new for states without. 
- [x] (Robert) Browse individual contributions button should link to filtered list of relevant transactions by candidate’s committees and by applicable cycles 
     - [x] Issue: https://github.com/fecgov/fec-cms/issues/3204
     - [x] API endpoints needed: https://www.draw.io/#G1t-wmP_LNNvC1yBeQm6HAq3176NYtEcFD
     - [x] Example link: https://fec-stage-proxy.app.cloud.gov/data/receipts/individual-contributions/?committee_id=C00580100&two_year_transaction_period=2018&two_year_transaction_period=2020
     - [ ] Calculate two_year_transaction_periods based on office. Confirm PR house uses 4 years (2 2-year periods) [@jason-upchurch 10/22/2019: this will be dealt with in #3290 ]
- [x] (Helen) Data for paper senate filers need to be fixed. Need to fix so that the data is accurate. 68 candidate corrections for this need to be made. This is upstream Oracle data. #3986

- [x] Check this feature on stage after release cut on 10/22. https://fec-stage-proxy.app.cloud.gov/data/raising-bythenumbers/#contributions-by-state
- [x] Turn on the feature after the release is ~cut~ deployed on 10/28.

If time allows: 
- [x] Link each state dollar figure to go to filtered list of individual contributions by candidate, by applicable cycles and by state.

**Comment by jason-upchurch** [comment]
Thank you @rfultz for:
For WCCF, `FEC_FEATURE_CONTRIBUTIONS_BY_STATE=true`
cc @patphongs @lbeaufort

**Comment by jason-upchurch** [comment]
Blocked by #3290

**Comment by jason-upchurch** [comment]
environment variable in prod, stage, and dev as of 10/28 release.
