### ISSUE TITLE
Make Audit process pages into Wagtail pages

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3219]
### Summary

**What we are after:**
We are moving pages off of transition and found a few regarding the audit process that need moving;
https://transition.fec.gov/audits/audit_reports_pres.shtml - We are going to hold off on drafting this page in Wagtail for now. 
https://transition.fec.gov/audits/understand_pres_audits.shtml

### Completion criteria

- [x] Identify home in Wagtail for the new pages
- [x] Create the new page drafts
- [x] Second pair of eyes
- [x] Add the old pages to our redirect spreadsheet
- [x] Contacted Public Records to alert them of the change, to update the link on https://transition.fec.gov/audits/audit_reports_pres.shtml 

### Future work

Redirecting the old pages as part of routine work.
Linking the new pages in our forthcoming page on presidential public funding audits/repayments

**Comment by kathycarothers** [comment]
This page has been sent to the content team for review.

**Comment by kathycarothers** [comment]
The page has been drafted, reviewed and published.
