### ISSUE TITLE
Prepare for migrating the policy page to Wagtail

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3220]
### Summary

**What we are after:**
We would like to bring the policy page at https://transition.fec.gov/law/policy.shtml into Wagtail as part of our effort to get off transition.

### Previous work:
In 10.4 we published an AT and DSP wagtail page to host documents required to be made public by a policy on this page (#2482, #3213). Although we ultimately linked to the AT/DSP page from the policy page, there was disagreement about what's a natural home for those documents. That discussion should be resumed when we are migrating the Policy page from transition to wagtail.

### Completion criteria

- [x] Confirm with OGC Policy that they want to retain the organizational structure of page (MVP = keeping the current structure and bringing over as is)
- [x] Determine if there are any items that can come off the page (check with OGC Policy)
- [x] Upload any PDFs currently stored on transition to the CMS. Ensure they are updated for accessibility.

### Future work
- Create the page as child page of legal resources, with a resource page template (#3470) 
- Part of future redirect work
- Moving the request for legal consideration page to Wagtail

**Comment by bmathesonFEC** [comment]
Regarding the new home for the AT/DSP page, OGC made a suggestion that may inform our decision for how to reorganize content in the policy page.

OGC's suggestion: give ATs and DSPs their own tab(s) under the Legal Resources (Explore all legal resources) section?  Reasoning: the information contained in the referrals, OGC recommendation memos, and Commission certifications is valuable research information and a legal resource for committees trying to decide how to proceed and the public in trying to understand how the Commission functions.

**Comment by dorothyyeager** [comment]
Did an inventory of the current Policy page. There's going to be a lot of decisions to make and PDFs to upload even for an MVP. I'm meeting with OGC tomorrow to ask some initial questions of them.

**Comment by dorothyyeager** [comment]
OGC is fine with an MVP of moving the page over as is. They are letting exactly one thing come off (the website initiative, since it's not guidance or a compliance thing, and that information is also linked on the 2009 hearing page for it).

They are going to think about what they'd like to improve for future iterations, but for now we'll retain current structure, although we may de-emphasize proposals that never went anywhere.

The PDFs are another story - there are gazillions of them, and they all are records we need to keep online (comments on policy statements, etc.). In some cases, there were separate pages set up for comments (because there were so many comments). I think we will want to bring those pages over too; want to talk with @AmyKort about this and if needed, will put in a ticket.

**Comment by dorothyyeager** [comment]
With the upcoming work on the new Guidance page, we're going to hold off on uploading new PDFs until we determine the best place for them. Closing this ticket.
