### ISSUE TITLE
Update front end to indicate raw data is limited to 4 months

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3223]
### Summary

**What we're after:**
After we finish deleting data for efiling up to only 4 months of data (based on file date), we need to update the front end to reflect this change.

**Completion criteria:**
- [ ] Implement change based on design
- [ ] @JonellaCulmer will update this ticket with the design

API issue: https://github.com/fecgov/openFEC/issues/4045

**Comment by JonellaCulmer** [comment]
We are no longer doing any front-end implementation. So closing.
