### ISSUE TITLE
WCCF: Make individual contribution committee api call consistent

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3232]
### Summary

The API call that is used in the Where contributions come from map should be consistent with the one we are using on the candidate profile page. We need to change the call to include `/history/` like this:
/candidate/[committee_id]/committees/history/[cycle]?per_page=100&API_KEY=[key]&designation=P&designation=A&election_full=true

### Completion criteria

- [ ] Check the committees link on the Where contributions come from "Browse individual contributions" button link and the individual state dollar figure links now use the updated API call

**Comment by rfultz** [comment]
Should I add `/[election_year]/` to the query, too, or keep it as a parameter (`cycle`)?

**Comment by patphongs** [comment]
@rfultz You should be able to keep it as `cycle` since we are passing `election_full=true`, that should take care of getting the full election years worth of committees

**Comment by patphongs** [comment]
Sorry @rfultz, I mis-interpreted this endpoint. You'll need to put cycle as part of the endpoint path and not as a query param. It doesn't seem to take cycle in that way
