### ISSUE TITLE
"statutes" and "regulations" uncapitalized in searches

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3235]
Summary

https://www.fec.gov/data/legal/search/statutes/?search_type=statutes

![Screen Shot 2019-10-07 at 9 53 27 AM](https://user-images.githubusercontent.com/31420082/66318187-d5e32280-e8e8-11e9-806c-2518b06306ef.png)

**Comment by lbeaufort** [comment]
During testing, I realized that `regulations` is also uncapitalized in the regulations search.

**Comment by rfultz** [comment]
@lbeaufort is this 'ready'? Is there a PR for it?
