### ISSUE TITLE
Implement reaction box for WCCF feature

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3237]
**What we're after:** To support the release and track usability needs, we should implement the reaction box below the WCCF to solicit for feedback. 

This feedback will be tracked and recorded by @JonellaCulmer 

**Completion criteria:**
- [ ] See previous implementation and confirm that questions/form boxes used apply to this feature. Last used on line chart on data landing page and raising and spending browse data pages. Confirm questions with @JonellaCulmer 
- [ ] Implement reaction box that solicits for and sends feedback to the FEC github repo. 
- [ ] Open up follow-up ticket to take down reaction box approximately 2 months from the time of the launch.

### Reaction box screenshot
<img width="663" alt="Screen Shot 2019-10-07 at 11 09 36 AM" src="https://user-images.githubusercontent.com/31663028/66324177-fc0dc000-e8f2-11e9-853f-589471791374.png">

**Comment by johnnyporkchops** [comment]
@jonella. Do you remember if there where issues with the recaptcha placement on the form for the reaction box when this was previously implemented on the line charts on browse-data? It is defaulting to a little off in terms of placement

**Comment by JonellaCulmer** [comment]
@johnnyporkchops No, I don't recall there being issues with the placement. I do recall some issues though with the questions and I'm struggling to find a PR that Andrew put in as he was the last person to get them implemented.

**Comment by lbeaufort** [comment]
@JonellaCulmer @johnnyporkchops here are some relevant PRs:

Add reaction box: https://github.com/fecgov/fec-cms/pull/2276
Remove reaction box: https://github.com/fecgov/fec-cms/pull/2510

**Comment by patphongs** [comment]
For the reaction box recaptcha badge replacement, I recall that we decided to place it on the left side of the screen. Because the reaction box has a comment area that appears after a user selects a reaction, we couldn't really place the badge next to the submit button as we would want the user to know that recaptcha is there prior to use of the tool.
