### ISSUE TITLE
Details are missing on the flyout panel for filing datatable page

### ISSUE THREAD

**Issue by hcaofec** [fecgov/fec-cms#3238]
**Thank you for your interest in helping improve the FEC CMS.**

Below, you'll find questions to help us more quickly identify, prioritize, and then address the issue.

### Summary

_On filing datatable page, the details the popup are missing when clicking on the expand button_

### Expected Behavior (C00665554)

<img width="1053" alt="Screen Shot 2019-10-07 at 11 49 57 AM" src="https://user-images.githubusercontent.com/24396726/66327370-bb18aa00-e8f8-11e9-81fc-d1200cf4746a.png">

### Actual Behavior  ( C00102517 )

<img width="1071" alt="Screen Shot 2019-10-07 at 11 50 27 AM" src="https://user-images.githubusercontent.com/24396726/66327447-d84d7880-e8f8-11e9-8f78-2807a557af54.png">

### Frequency

- [ ] This is the first time it's happened
- [x] This is an ongoing, predictable issue
- [ ] It seems to be random
- [ ] Other: …

### How to Reproduce

https://www.fec.gov/data/filings/?data_type=processed&committee_id=C00102517&committee_id=C00665554&form_type=F1&form_type=F3&form_type=F3P&form_type=F3X&form_type=F3L&form_type=F4&form_type=F5&form_type=F7&form_type=F13

### Browser

_Which version of which browser are you using? Does this issue occur with other browsers or with other browser sizes?_

- [ x ] Chrome, version: …
- [ ] Firefox, version: …
- [ ] Safari, version: …
- [ ] Edge, version: …
- [ ] Internet Explorer, version: …
- [ ] Other: …

### Device

_Tell us what you can about your device and its operating system._

- [x ] Laptop/desktop
- [ ] Tablet
- [ ] Phone

Manufacturer: …
Model: …
Operating system: …
Screen orientation: …

### Screenshots

see above

### Misc

_If you'd like to include anything else that may be of interest, do that here._

**Comment by hcaofec** [comment]
For filing with negative file number or 'not applicable' version, the expand arrow is not even shown.

<img width="1098" alt="Screen Shot 2019-10-16 at 9 52 52 AM" src="https://user-images.githubusercontent.com/24396726/66925948-2d754280-effb-11e9-9f29-2ff0bd4f9068.png">

**Comment by PaulClark2** [comment]
No details panel	|	Has details panel
---	|	---
F1	|	F3
F1M	|	F3P
F2	|	F3X
F3L	|	F5
F4	|	F99
F24	|	
F6	|	
F7	|	
F8	|	
F9	|	
F10	|	
F11	|	
F12	|	
F13	|	
F99	|	
RFAI / FRQ	|

**Comment by PaulClark2** [comment]
Here are the first few. I'll try to get through these quickly. That'll help us see if there are overall changes we'd like make to the details panel. 

**Form 1 **
Statement of organization
Current version
Filer
FEC file number
Receipt date
Filing method
Read report

**Form 1M**
Statement of organization
Current version
Filer
FEC file number
Receipt date
Filing method
Read report

**Form 2**
Statement of candidacy
Current version
Filer
Election year
State
Office
District
FEC file number
Receipt date
Filing method
Read report

**Form 3L **
Report type and year
Version
Filer
FEC file number
Report coverage
Receipt date
Filing method
Read report

Total reportable bundled contributions

**Comment by patphongs** [comment]
After discussion with @lbeaufort and @PaulClark2, we've decided to make a separate call for all non-financial forms. Currently financial forms that are using the `/committee/[committee_id]/reports/` are F3, F3P, F3X, and F5. For all other forms, we want to default to calling this endpoint when the filings panel button is clicked `/committee/[committee_id]/filings/`. The default template will display:


```Filer
FEC file number
Report coverage
Receipt date
Filing method
Read report
```

**Comment by PaulClark2** [comment]
:lock: https://docs.google.com/spreadsheets/d/1ikNqr7fKkCuDElMEV8a3ZxFpNerXEW4XBWHaEzEXEhE/edit#gid=1030423814 :lock:

**Comment by JonellaCulmer** [comment]
The example in the original comment doesn't appear to be broken "anymore". https://www.fec.gov/data/filings/?data_type=processed&committee_id=C00102517&form_type=F3X&form_type=F3
<img width="1669" alt="Screen Shot 2019-10-29 at 2 06 31 PM" src="https://user-images.githubusercontent.com/31663028/67809173-77c3de00-fa55-11e9-8ced-3bffa7af3db0.png">

**Comment by PaulClark2** [comment]
@JonellaCulmer @hcaofec @rfultz I checked filings of nine committees and did not find another filing with its details panel with missing information. 

@hcaofec when you noticed the issue with C00665554's detail panel did you notice the same issue on any other filing's detail panel? 

C00466359 Renacci for Senate 2018 year-end
C00606939 Rosen for Nevada 2018 pre-general
C00540500 Cory Booker for Senate 2018 Q2

C00414078 Sali for Congress 2019 Q3
C00331769 Barbara Lee for Congress 2019 Q1
C00660431 Mindi for Congress 2019 Q2

C00693234 Warren for president 2019 Q3
C00580100 Donald J. Trump for president 2019 Q2
C00697896 Dario for America 2019 M10

**Comment by PaulClark2** [comment]
@rfultz @JonellaCulmer I moved all the `add new panels` information to a new ticket, https://github.com/fecgov/fec-cms/issues/3309
