### ISSUE TITLE
Candidate name lookup not working for Schedule E raw data

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3247]
We should use candidate name lookup for Schedule E raw data not working as expected. 

https://www.fec.gov/data/independent-expenditures/?data_type=efiling&candidate_name=warr&is_notice=true

**Example:**
<img width="794" alt="Screen Shot 2019-11-01 at 1 53 34 PM" src="https://user-images.githubusercontent.com/31663028/68045195-56f6c500-fcaf-11e9-9e8d-9ef453d1c295.png">

**Completion criteria:**
- [ ] Correct the candidate mentioned filter to search and return appropriate results by candidate's name
- [ ] Open follow-up ticket to review the business logic for how we want users to use this filter, or create an additional filter to also search by candidate ID. Will our data support this change?

**Comment by JonellaCulmer** [comment]
In addition to the autosuggest work, it doesn't seem return results I would expect to see. 

<img width="794" alt="Screen Shot 2019-11-01 at 1 53 34 PM" src="https://user-images.githubusercontent.com/31663028/68045195-56f6c500-fcaf-11e9-9e8d-9ef453d1c295.png">

**Comment by lbeaufort** [comment]
@JonellaCulmer great catch, it doesn't look like the filter is working.

**Comment by lbeaufort** [comment]
The API search field is `candidate_search` which searches name and ID.  https://api.open.fec.gov/v1/schedules/schedule_e/efile/?sort_nulls_last=false&sort_hide_null=false&sort=-expenditure_date&candidate_search=trump&api_key=DEMO_KEY&page=1&per_page=20&sort_null_only=false. 

We could modify the typeahead to pass name as well as ID.
