### ISSUE TITLE
forbidden link for Read report link for committee

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-cms#3258]
### Summary
For https://www.fec.gov/data/reports/house-senate/?data_type=processed&committee_id=C00498683 the Read report link `.fec` takes user to 403 Forbidden.

### Expected Behavior
Either follow a valid link or not be presented with the option to click.

### Actual Behavior
403 forbidden

**Comment by patphongs** [comment]
We believe this error is fixed after applying https to the .fec links
