### ISSUE TITLE
Investigate why 2002 Commission meeting minutes are 404'ing & fix it

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3266]
### Summary

**What we're after:**
The Commission Secretary needs us to find out why Commission meeting minutes from 2002 are 404'ing, and fix it.

Example: October 31, 2002: https://www.fec.gov/agenda/agendas2002/approve02-77.pdf.

Looks like all of the minutes were put in the agenda/agendas2002/ subdirectory back then. The classic.fec.gov link works in the building, but the redirect may not be working.

### Completion criteria

- [x] Identify the reason the meeting minutes are 404'ing
- [x] Put in or adjust redirects as needed

**Comment by dorothyyeager** [comment]
These redirects will be deployed by @patphongs tonight.

**Comment by patphongs** [comment]
These redirects have been deployed and should resolve this issue. Closing as the deploy is complete. Thanks @dorothyyeager !
