### ISSUE TITLE
New Bug: Obama and others not showing in sitewide search candidate results

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3267]
### Summary

Obama doesn't come up in the list of candidates in the sitewide search, only committtees

### Expected Behavior

We should see this list because the API returns results: https://api.open.fec.gov/v1/names/candidates/?q=obama&api_key=DEMO_KEY

I can see the AJAX call but the results aren't displayed after you type the "ma" in Obama
<img width="408" alt="Screen Shot 2019-10-11 at 8 59 56 AM" src="https://user-images.githubusercontent.com/31420082/66653226-8876f600-ec05-11e9-8830-dd3a6568ef84.png">

### Actual Behavior

No candidate results

<img width="408" alt="Screen Shot 2019-10-11 at 8 57 09 AM" src="https://user-images.githubusercontent.com/31420082/66653044-21f1d800-ec05-11e9-8e60-0003f3f6b0fd.png">

### Frequency

- [ ] This is the first time it's happened
- [X] This is an ongoing, predictable issue
- [ ] It seems to be random
- [ ] Other: …

### How to Reproduce

_List any steps you took for this issue to happen. Be sure to include the URL and what you clicked or entered._
URL: https://www.fec.gov/…

1. Type in "Obama" in the sitewide search
2. No candidate results

### Browser

_Which version of which browser are you using? Does this issue occur with other browsers or with other browser sizes?_

- [X] Chrome, version: …
- [ ] Firefox, version: …
- [ ] Safari, version: …
- [ ] Edge, version: …
- [ ] Internet Explorer, version: …
- [ ] Other: …

### Device

_Tell us what you can about your device and its operating system._

- [X] Laptop/desktop
- [ ] Tablet
- [ ] Phone

### Completion Criteria
- [ ] visible search suggestions match the API results

**Comment by rfultz** [comment]
Either a direct or related issue: WCCF's typeahead finds Obama and Dole when I enter the first three letters (i.e. "oba", "dol") but displays nothing when I enter the fourth. WCCF is limited to candidates. Seems to work fine on Production but nowhere else. We use typeahead for the various filters, too.
