### ISSUE TITLE
No validation/error message when searching more than ten committees

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3272]
**User story:**
As a data user, when searching more than 10 committees, I need to be able to understand why I'm not seeing data. 

Follow-up issue for https://github.com/fecgov/openFEC/issues/3996

There is no validation/error message when searching more than 10 committees - the datatables just don't return results: https://www.fec.gov/data/receipts/?data_type=processed&committee_id=C00031781&committee_id=C00107391&committee_id=C00139998&committee_id=C00171538&committee_id=C00187435&committee_id=C00188888&committee_id=C00250191&committee_id=C00329706&committee_id=C00364091&committee_id=C00401224&committee_id=C00412304&committee_id=C00547679

When a user chooses more than 10 committees on **all**  transaction datatables, we should have validation that indicates they should choose less than 10 committees. 

**List of transaction tables:**
- Receipts
- Individual contributions
- Disbursements
- Independent expenditures

**Completion criteria:**
- [x] Discuss with content, what kind of message is appropriate, write message
- [x] Mock-up design solution with language in mind
- [x] Open follow-up implementation ticket

**Comment by JonellaCulmer** [comment]
@patphongs In looking at this ticket, I'm wondering if you think it's possible to include a "cap" on the number of committees a user can select?

We could disable the button and/or include a message that explains the interaction.

**Comment by patphongs** [comment]
@JonellaCulmer I do think it's possible to include a cap on the number of committees a user can select. We could add some kind of message indicating that they can only insert 10 or less committees after they attempt to put in more than 10.

**Comment by JonellaCulmer** [comment]
@lbeaufort @patphongs Are we sure that the only fields we need to be concerned with are Recipient name or ID, contributor name/contributor name or ID, and ZIP codes?

What about **city**, **occupation**, **employer**, **image number**, **spender name or ID**, **candidate mentioned/candidate name or ID** OR **payee**?

**Comment by JonellaCulmer** [comment]
@dorothyyeager @kathycarothers I based the error message language on what is currently used on the receipts and individual contributions datatables to say that users need to select additional criteria before a search of more than one two-year period can go through. 
> You're trying to search across multiple time periods. Filter by recipient name or ID, contributor details, or image number for results.

Below are my mockups. Let me know what you think.

![More than 10 committees](https://user-images.githubusercontent.com/31663028/69014519-2bcfcf00-0959-11ea-84c2-496a0ccf47f8.jpg)

cc: @patphongs

**Comment by dorothyyeager** [comment]
I like it.

**Comment by JonellaCulmer** [comment]
Based on the conversation with @dorothyyeager @lbeaufort and @patphongs I've updated the mock-ups to only include those filters with the existing 10 committee limitations. 

![More than 10 committees Copy](https://user-images.githubusercontent.com/31663028/69091744-e7a40380-0a18-11ea-9c72-4a92d73a6846.jpg)

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation ticket: https://github.com/fecgov/fec-cms/issues/3367
