### ISSUE TITLE
Zebra stripe on reporting date tables needs work

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3274]
### Summary

**What we're after:**
Needs to alternate by state or row or by some logical way.

**Technical observation:**
We have each row with a state class. Should we key the zebra striping based on those classes?

![image](https://user-images.githubusercontent.com/40633757/67038692-e61bae80-f0ed-11e9-9fda-ff8fcb94612c.png)

### Related issues
- #3017 
Different issue, same file: #3263

### Completion criteria
- [x] Fix zebra stripes on pre-election reporting based STATE.

**Comment by johnnyporkchops** [comment]
The addition of TBD rows in production caused an unforeseen issue with the alternate zebra-striping. Based on new request, we will stripe by state(not alternating)

**Comment by jason-upchurch** [comment]
PR approved and merged
