### ISSUE TITLE
Make all report and statement images available

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#3276]
### Summary

Some images of reports and statements are not available. 

Related work:
https://github.com/fecgov/fec-cms/issues/3337 
https://github.com/fecgov/openFEC/issues/4757

### Expected Behavior

If you have an image of a report or statement, users should be able to view it on the website. 

### Actual Behavior

Image link is not available.

### Example
Document: RFAI: YEAR-END 1996	
Image number: 97031982435
https://www.fec.gov/data/committee/C00213512/?tab=filings&cycle=1996

FEC.gov committee filings page
![image](https://user-images.githubusercontent.com/11817734/67029432-435a3480-f0db-11e9-925a-e4d13b4231f2.png)

classic
![image](https://user-images.githubusercontent.com/11817734/67029538-80262b80-f0db-11e9-893f-19d3f2538861.png)

docquery
https://docquery.fec.gov/pdf/435/97031982435/97031982435.pdf

### Completion criteria
- [ ] make all images available

**Comment by lbeaufort** [comment]
@patphongs your work on https://github.com/fecgov/fec-cms/issues/3238 might address this issue as well.

**Comment by hcaofec** [comment]
Database function function report_pdf_url_or_null has been modified. The image link is available now on website.  No work needed on cms.
