### ISSUE TITLE
Create sitemap.xml for wagtail pages

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3280]
### Summary

**What we're after:**
_As a user, I want to be able to search the website easily using key words in order to find what I need._

Adding a comprehensive sitemap.xml to our website would help search.gov leverage it to index our content. Currently we are manually running a scraping and index tool using management commands. If we have a sitemap, we may be able to automated this for us.
[FEC wiki for scraping/indexing instructions](https://github.com/fecgov/fec-cms/blob/develop/fec/search/management/instructions.md#adding-cms-pages-to-the-index)

When working on this ticket, we need to consider: https://github.com/fecgov/fec-cms/issues/3598

### Useful docs

- Search.gov sitemap info: https://search.gov/manual/sitemaps.html
- Wagtail sitemap: https://docs.wagtail.io/en/v2.6.2/reference/contrib/sitemaps.html
- Look at i14y, search.gov's content indexing API to see how sitemaps may be integrated: https://search.gov/developer/i14y.html and https://search.gov/developer/indexing-api.html

Search.gov docs actually recommend switching to sitemaps:
_"Important Note: April, 2018. i14y does not visit your content to do full-text scraping of your content. For new implementations, the Search.gov team recommends you index your content with us not using the i14y API, but rather by publishing a comprehensive xml sitemap, which we can use to index your content. [Read more](**https://search.gov/blog/six-months-in.html**)._"

**Exiting sitemaps in production:** Since we have now used xml sitemaps as a solution in production for policy PDF project, we should take a look at this process ad part of our research. https://github.com/fecgov/fec-cms/pull/3607. It would also be helpful to solicit feedback from the content team and devs that worked on this (see PR)

### Decisions to make:
- Are there places on the site that users have trouble finding?
- What pages would we like users to find more easily?
- How does this differ from or how would this work with the guidance sitemap?

**Completion criteria:**
- [ ] Build a sitemap for all wagtail pages

**Comment by lbeaufort** [comment]
A user at the San Diego FEC conference requested this feature

**Comment by patphongs** [comment]
Things to research:
- [ ] We should talk to callers and staff about the content that users are having trouble finding. 
- [ ] Look through feedback issues of things users are having trouble finding. 
- [ ] Cross check analytics to make sure that results are ranked accordingly (especially the top ranked pages).

**Comment by patphongs** [comment]
Moving this issue to 11.5. That will allow time for content and UX team to research the new ticket that will be created above ^^

**Comment by jason-upchurch** [comment]
related issue https://github.com/fecgov/fec-cms/issues/3599 used a sitemap. One requirement for this issue (#3280) is that the solution should not cause additional search results to be returned on the guidance search from #3599. It may not be an issue, but while working with search.gov the possibility was raised of one search polluting another when a common domain was used.

**Comment by patphongs** [comment]
Our global search and guidance search both us search.gov. We need to ensure that we don't have conflicts in the sitemaps if we automate them. Especially since the guidance search is specific to particular documents.

**Comment by johnnyporkchops** [comment]
Sitemaps have been developed and are in the process of QA and final setup tasks for launch.
See https://github.com/fecgov/fec-cms/issues/5770
