### ISSUE TITLE
Update front-end to not use deprecated endpoints

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3285]
**Aim to complete before PI 10 innovation sprint**

**Completion criteria:**
- [x] Confirm these deprecated endpoints are still in use
- [x] Switch the front end to use the alternate endpoints

Deprecated API endpoint | Available now: Replacement API endpoint | Example
-- | -- | --
/committee/<committee_ID>/schedules/schedule_a/by_employer/ | /schedules/schedule_a/by_employer/ | /schedules/schedule_a/by_employer/?committee_id=<committee_ID>
/committee/<committee_ID>/schedules/schedule_a/by_occupation/ | /schedules/schedule_a/by_occupation/ | /schedules/schedule_a/by_occupation/?committee_id=<committee_ID>
/committee/<committee_ID>/schedules/schedule_a/by_size/ | /schedules/schedule_a/by_size/ | /schedules/schedule_a/by_size/?committee_id=<committee_ID>
/committee/<committee_ID>/schedules/schedule_a/by_state/ | /schedules/schedule_a/by_state/ | /schedules/schedule_a/by_state/?committee_id=<committee_ID>
~/committee/<committee_ID>/schedules/schedule_a/by_zip/~ | ~/schedules/schedule_a/by_zip/~ | ~/schedules/schedule_a/by_zip/?committee_id=<committee_ID>~
~/committee/<committee_ID>/schedules/schedule_b/by_purpose/~|~/schedules/schedule_b/by_purpose/~ | ~/schedules/schedule_b/by_purpose/?committee_id=<committee_ID>~
/committee/<committee_ID>/schedules/schedule_b/by_recipient/ | /schedules/schedule_b/by_recipient/ | /schedules/schedule_b/by_recipient/?committee_id=<committee_ID>
/committee/<committee_ID>/schedules/schedule_b/by_recipient_id/ | /schedules/schedule_b/by_recipient_id/ | /schedules/schedule_b/by_recipient_id/?committee_id=<committee_ID>
/committee/<committee_ID>/schedules/schedule_e/by_candidate/ | /schedules/schedule_e/by_candidate/ | /schedules/schedule_e/by_candidate/?committee_id=<committee_ID>

Ref Issue: https://github.com/fecgov/openFEC/issues/3995

https://github.com/fecgov/openFEC/issues/4023

https://github.com/fecgov/openFEC/issues/4024

**Comment by pkfec** [comment]
`/committee/<committee_ID>/schedules/schedule_a/by_zip/` couldn't find any reference for this endpoint in cms.
