### ISSUE TITLE
Need to ensure "agents" are added to pages on IEs and CCs

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3291]
### Summary

**What we are after:**
In returning comments on our citizen's page, OGC strongly recommended that we include "agents in every discussion of coordinated and independent expenditures in every single webpage, brochure, and campaign guide that discusses coordinated communications and independent expenditures." We've retired the brochures, but we'll need to doublecheck the web pages to ensure we've included this (and add it if we haven't). 

### Related issues

- #3173 

### Completion criteria

- [x] Find pages that cover independent expenditures and coordinated communications
- [x] In the case of coordinated communications, see if we have too many pages. Can we consolidate into one central page as we did for IEs? (If so, let's put in a ticket to do that in PI11)
- [x] Ensure that we have a discussion of "agent" on those pages and that it links to the glossary.
- [x] Draft language if needed for any page. In some cases, linking to the glossary may be most appropriate.
- [x] Review of any draft updates by content team (and OGC if needed)

**Comment by kathycarothers** [comment]
I am taking the definition from the glossary and regulations to update the appropriate pages. Here is the wording I plan to insert: 
, …”a candidate’s authorized committee, or their agents (link to glossary), or a political party committee or its agents (link to glossary),”...
@AmyKort @dorothyyeager

**Comment by kathycarothers** [comment]
Talked with Dorothy and Brad regarding the reporting pages for IEs. I will add a link to those pages.

**Comment by kathycarothers** [comment]
All pages have been updated. The only changes were adding glossary terms, linking to the Making Independent Expenditure page, and adding the regulation language where needed. No major changes were added to these pages:
URL
https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/2019-reporting-dates/coordinated-communications-dates/
https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/coordinated-communications/
https://www.fec.gov/help-candidates-and-committees/making-disbursements-ssf-or-connected-organization/coordinated-communications-ssf/
https://www.fec.gov/press/resources-journalists/coordinated-communications/
https://www.fec.gov/help-candidates-and-committees/taking-receipts-political-party/communications-coordinated-party-committee/
https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/coordinated-party-expenditures/

https://www.fec.gov/help-candidates-and-committees/making-independent-expenditures/multistate-independent-expenditures/
https://www.fec.gov/help-candidates-and-committees/filing-political-party-reports/multistate-independent-expenditures/
https://www.fec.gov/help-candidates-and-committees/filing-pac-reports/multistate-independent-expenditures/
https://www.fec.gov/help-candidates-and-committees/filing-political-party-reports/estimating-independent-expenditures/
https://www.fec.gov/help-candidates-and-committees/filing-pac-reports/estimating-independent-expenditures/
https://www.fec.gov/help-candidates-and-committees/making-independent-expenditures/estimating-independent-expenditures/
https://www.fec.gov/help-candidates-and-committees/filing-pac-reports/aggregating-independent-expenditures/
https://www.fec.gov/help-candidates-and-committees/making-independent-expenditures/
https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/understanding-independent-expenditures/
https://www.fec.gov/help-candidates-and-committees/making-independent-expenditures/reporting-independent-expenditures-form-5/
https://www.fec.gov/help-candidates-and-committees/making-independent-expenditures/reporting-independent-expenditures-form-3x/
https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/2019-reporting-dates/24-and-48-hour-reports-independent-expenditures-2019-20/
https://www.fec.gov/help-candidates-and-committees/making-independent-expenditures/quarterly-reports-independent-expenditure-filers/
https://www.fec.gov/help-candidates-and-committees/making-independent-expenditures/48-hour-reports-independent-expenditure-filers/
https://www.fec.gov/help-candidates-and-committees/making-independent-expenditures/24-hour-reports-independent-expenditure-filers/
https://www.fec.gov/help-candidates-and-committees/filing-political-party-reports/repaying-independent-expenditure-debt/
https://www.fec.gov/help-candidates-and-committees/filing-political-party-reports/party-committee-independent-expenditures/
https://www.fec.gov/help-candidates-and-committees/filing-political-party-reports/disseminating-paying-ies-same-reporting-period/
https://www.fec.gov/help-candidates-and-committees/filing-political-party-reports/paying-ie-first-and-disseminating-later-reporting-period/
https://www.fec.gov/help-candidates-and-committees/other-filers/
https://www.fec.gov/help-candidates-and-committees/filing-political-party-reports/disseminating-ie-first-and-paying-later-reporting-period/
