### ISSUE TITLE
EEO Office request: Convert Limited English Proficiency Plan page to Wagtail

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3301]
### Summary

**What we are after:**
The EEO office was thrilled with the work we did on their page. They have one more page they need to convert. For this one, they'd like it to be on a separate new page (as it is now at https://transition.fec.gov/eeo/LimitedEnglishProficiencyPlan.shtml) and then linked on the EEO page under Resources.

### Related issues

- #3117 

### Completion criteria

- [x]  Create Wagtail page (custom page format) with text from https://transition.fec.gov/eeo/LimitedEnglishProficiencyPlan.shtml
- [x] Second pair of eyes from content team and EEO office
- [x]  Publish the page once approved
- [x] Add link to new page on https://www.fec.gov/about/equal-employment-opportunity/ under Resources
- [x] Add old page to redirect spreadsheet

### Future work

Redirect of old page

**Comment by kathycarothers** [comment]
I have started to draft the page.

**Comment by kathycarothers** [comment]
I have sent the page out for review to the content team.
