### ISSUE TITLE
Coverage dates of individual contributions on WCCF

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#3304]
### Summary

The coverage dates above the list of states reflects the most recent filing. It should reflect the latest  processed transactions. 

### Expected Behavior

Display date range of transaction included.

### Actual Behavior

Display date range of filings received

### Frequency
- This is an ongoing, predictable issue

### How to Reproduce

Look at any candidate that has un-cleared transactions from a new report. 

### Screenshots
Viewed 10/28/19 
WCCF (The coverage dates are wrong. The transactions include are only through 6/30/19. His Q3 filing hasn't cleared yet.)
![image](https://user-images.githubusercontent.com/11817734/67699253-3dd5d780-f982-11e9-8398-4e46a88b65a3.png)

Candidate profile (The coverage dates are correct.)
https://www.fec.gov/data/candidate/P80001571/?tab=raising
![image](https://user-images.githubusercontent.com/11817734/67699343-6067f080-f982-11e9-8e64-7d3ed63b9e90.png)

**Comment by lbeaufort** [comment]
We want to use the `transaction_coverage_date` field, not the `coverage_end_date`

Example call: https://api.open.fec.gov/v1/candidate/P80001571/totals/?cycle=2020&election_full=True&API_KEY=DEMO_KEY

Front end code: https://github.com/fecgov/fec-cms/blob/85fe64f5b1a3152f3a8b5e5a022164d74216ec9f/fec/fec/static/js/widgets/contributions-by-state-box.js#L454-L456
