### ISSUE TITLE
Update home page and Leadership page to reflect Vice Chair's title

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3308]
### Summary

**What we are after:**
The Commission Secretary has instructed us to update the website to reflect that Commissioner Hunter is now Vice Chair Hunter. I've done so for her page; we need to update the hard coded pages

### Related issues

_List any relevant related issue(s)_
- #2585 

### Completion criteria

- [ ] Update Commissioner Hunter on home page to note she is now Vice Chair
- [x] Update code for Commissioner section on https://www.fec.gov/about/leadership-and-structure/ to note Commissioner Hunter is now Vice Chair

**Comment by dorothyyeager** [comment]
I forgot that we made the change in the beginning of the year. The page at Leadership and Structure is now up to date. We still will need the home page changed.

**Comment by JonellaCulmer** [comment]
Work has been merged, so closing.
