### ISSUE TITLE
Financial summary missing for committee

### ISSUE THREAD

**Issue by fec-jli** [fecgov/fec-cms#3311]
This is following up api issue (already merged in dev): [https://github.com/fecgov/openfec/issues/4016](https://github.com/fecgov/openfec/issues/4016)

- [x] committees file wrong form
- [x] committees file **terminate** , still need show financial summery data.

**Comment by JonellaCulmer** [comment]
Testing ticket to address some of the proposed changes: https://github.com/fecgov/fec-testing/issues/126
