### ISSUE TITLE
Allow users to see all mobile menu items

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3313]
**What we're after:**
Users should be able to view the entire mobile menu. When viewing the About or Legal resources menus, you're unable to see all menu options in a given accordion. 

This has been observed on both Chrome and Safari on iPhone X. 

![Screenshot 2019-10-31 at 4 17 59 PM](https://user-images.githubusercontent.com/31663028/67983451-176ea100-fbfb-11e9-8417-756cc9b5e5eb.jpeg)

### Completion criteria

- [ ] Ensure users can view all mobile menu items

**Comment by johnnyporkchops** [comment]
I am able to scroll to see all items on  my old FEC Iphone. We should check to see If this is specific to an Android phone? Or the new FEC-issued Iphones?

**Comment by JonellaCulmer** [comment]
@johnnyporkchops I'm unable to see them all on my personal iPhone.
