### ISSUE TITLE
Publish "about this data" pages

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3314]
### Summary

**What we are after:**
This ticket is to create and publish several new pages explaining various API end points

### Completion criteria
- [x] Content team review of draft text
- [x] Publish new "About data" landing page
- [x] Publish page on methodology
- [x] Publish page on "About data receipts"

**Comment by dorothyyeager** [comment]
With the help of Don in the Information Division, the methodology page was published.

@PaulClark2 I think you ok'ed the publishing of the landing page, correct? Let me know and I'll hit publish.

The "About the receipts" page is more complicated. I'm working on that now.

**Comment by PaulClark2** [comment]
Thank you @dorothyyeager and Don. Please publish the landing page.

**Comment by dorothyyeager** [comment]
I've published the landing page and methodology. Got some design ideas with @JonellaCulmer for the tricky receipts page - we're going to use a table approach and pair again on it later today.

**Comment by JonellaCulmer** [comment]
@dorothyyeager Here's the mockup we talked about this afternoon. Let me know if you need anything else. 

![Screen Shot 2019-11-05 at 3 43 09 PM](https://user-images.githubusercontent.com/31663028/68244521-fdf69c00-ffe2-11e9-846e-9655a0792288.png)

**Comment by dorothyyeager** [comment]
Thank you @JonellaCulmer !! This was awesome and worked perfectly. The last of the pages is coming together and I should have a draft ready for review soon.

**Comment by dorothyyeager** [comment]
The last of three pages is ready for review by @PaulClark2 (link is in Slack).

**Comment by dorothyyeager** [comment]
Paul's approved the last page, and the pages have been published:
Landing page: https://www.fec.gov/campaign-finance-data/about-campaign-finance-data/
Methodology page: https://www.fec.gov/campaign-finance-data/about-campaign-finance-data/methodology/
About receipts data page: https://www.fec.gov/campaign-finance-data/about-campaign-finance-data/about-receipts-data/

Closing as work is complete.
