### ISSUE TITLE
Draft content for 4 month raw data limitation 

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3319]
**What we're after:**
With the removal of most of our raw filings, limiting them to the last 4 months, we need to make sure that it's clear to users what IS available to them. 

### Related issues

- Update API documentation to indicate raw data(/efile/ endpoints) is limited to 4 months https://github.com/fecgov/openFEC/issues/4045

### Completion criteria

- [ ] Compile a list of all locations where the new language is necessary across the API
- [ ] Draft content
- [ ] Update implementation tickets

**Comment by JonellaCulmer** [comment]
Quick and dirty suggestions: 
- Raw data is limited to 4 months.
- It is what it is.

**Comment by JonellaCulmer** [comment]
Closing this ticket in favor of https://github.com/fecgov/openFEC/issues/4045

**Comment by jason-upchurch** [comment]
floating this suggestion around:

>These endpoints are perfect for watching filings roll in when you want to know the latest information. Efiling endpoints only contain the most recent ~two years~ [insert: four months] worth of data and don't contain the processed and coded data that you can find on the other endpoints. Those endpoints are better for in-depth analysis.
