### ISSUE TITLE
Design solution for active vs terminated committee status

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3325]
**What we're after:** Following the [usability testing](https://github.com/fecgov/fec-testing/issues/125) conducted at the San Diego conference, we need to consider how we can better support our users by making it clearer when a committee is still active or terminated. At the conference, we learned that our users are doing a lot of guesswork to determine a committee's active status. 

Conference takeaways: https://github.com/fecgov/fec-testing/issues/125#issuecomment-550328985

**Related tickets:**
Design interaction for terminated committees https://github.com/fecgov/fec-cms/issues/1944

**Completion criteria:**
- [x] Review research and ideate potential solutions
- [x] Mock up solutions and determine best direction
- [x] Open followup front-end implementation ticket

**Comment by JonellaCulmer** [comment]
There are a few different things we can do to make it clear whether a committee is active or terminated. 
- Include the status at the top of the committee profile page (A)
- Include the status in the about this committee tab (B)
- Include the status in the committee dropdowns in the global search and on the data landing page (C)

I'm leaning towards options A and C, including the status at the top of the committee profile page and, possibly after some time, including an indicator in the global search and committee/candidates search on the data landing. 

Additionally there's a decision to make on the appearance of the indicator. For the global search we have limited options because of space limitations. I don't want to anything any more intrusive than what I've already mocked up. 

There is the question of the appearance for the indicator on the committee profile pages, however. While I appreciate the addition of color to the page, I'm leaning towards the dot and italicized text. That way if we also implement the change in the committee search boxes, it's easy to match them up and can reinforce their meaning in the search. Also, I'd rather not make something that's pretty simply to draw attention to the status indicator, when I'm not entirely sure it needs to be the first thing someone sees when arriving at the page. 

Secondarily, need to determine whether a pop-up of some kind is necessary in the global search to explain what the dot means. 

### Mockup A/B

<img width="752" alt="Screen Shot 2020-03-11 at 9 42 43 AM" src="https://user-images.githubusercontent.com/31663028/76427132-50293e80-6382-11ea-8fc2-07be7f4aa8bf.png">
<img width="970" alt="Screen Shot 2020-03-11 at 8 35 44 AM" src="https://user-images.githubusercontent.com/31663028/76427129-4f90a800-6382-11ea-98a6-d64cbdafd389.png">

### Mockup C

<img width="308" alt="Screen Shot 2020-03-11 at 9 36 43 AM" src="https://user-images.githubusercontent.com/31663028/76427223-6afbb300-6382-11ea-9696-e4f1f474c88e.png">


cc: @jjonesFEC @AmyKort @patphongs 

Choices to make:
1. Where do we place the indicator: At the top of the committee page and/or the about the committee tab and possible in the search.
2. What style indicator for top of page: green box, or dot and italicized text. For terminated committees, gray or red.

My recommendations:
- Place in search and at top of committee profile page
- Dot and italicized text and gray for terminated committees

**Comment by JonellaCulmer** [comment]
Alternative for option A:
Including the status at the front of the list of items. It reads more like a sentence, like Active PAC or Terminative Senate Candidate committee, etc. 

<img width="1100" alt="Screen Shot 2020-03-15 at 11 43 22 PM" src="https://user-images.githubusercontent.com/31663028/76721608-f4aad800-6716-11ea-8470-91b720cdc98c.png">
<img width="1098" alt="Screen Shot 2020-03-15 at 11 43 36 PM" src="https://user-images.githubusercontent.com/31663028/76721610-f4aad800-6716-11ea-8e65-ab59266b9400.png">

**Comment by patphongs** [comment]
@JonellaCulmer I like the indicator being at the front of the list items and on the committee search. Gray and green dot indicators with no background looks clean and simple and doesn’t distract too much from the rest of the page.

**Comment by jjonesfec** [comment]
I like the placement in A/B. It's part of the meta for each committee and is properly placed with the rest. I also like the subtle use of color in A/B and C. It's clear and noticeable without calling too much attention to itself. The color itself is part of the message. Perfect.

Am I correct that only one of these would be visible in A/B? IOW, would it make sense to show both options so that the user understands the difference? If I just see "Active Committee", I assume that the alternative is "Inactive Committee", not "Terminated Committee". I think that there would be value in showing both options but only highlighting one. Without this, how would users know what all of the options are? Unless we tell them otherwise, a user could easily think that there's a category called "Inactive Committee" or any number of alternatives. Listing both options would establish a standard while also informing users of the full range of status options available. There looks to be plenty of space to do so.

**Comment by JonellaCulmer** [comment]
@patphongs Thanks for the feedback. That is where I was leaning as well, specifically the last mockup I did. Would you say we could pick and choose the committee search dropdowns on which we want to place the indicator? 

I ask because after we get an idea of the indicator/label's usefulness from our users, we may want to also add it to the Committee datatable. And possibly wherever a committee name is displayed, but that seems way off at this point.

**Comment by JonellaCulmer** [comment]
> Am I correct that only one of these would be visible in A/B? IOW, would it make sense to show both options so that the user understands the difference? If I just see "Active Committee", I assume that the alternative is "Inactive Committee", not "Terminated Committee". I think that there would be value in showing both options but only highlighting one. Without this, how would users know what all of the options are? Unless we tell them otherwise, a user could easily think that there's a category called "Inactive Committee" or any number of alternatives. Listing both options would establish a standard while also informing users of the full range of status options available. There looks to be plenty of space to do so.

@jjonesfec Would love to talk to you about your perspective on this and see what possible solutions there are if you have time.

**Comment by jjonesfec** [comment]
Great discussion. All of your solutions are good options, my preference being flush left under the committee name. It's the first meta you see which is perfect for a binary like active/terminated. We might consider adding a definition for Active as there isn't one right now.

**Comment by JonellaCulmer** [comment]
Thanks @jjonesfec! I think that's what I'll move forward with. 

@dorothyyeager Referencing @jjonesfec's comment above, I see that we don't currently have a glossary term for "Active," or one specifically for "Terminated" (but there is one for Terminating committee). Do you see the value in adding a glossary term for either?

When we tested with users at the San Diego conference there didn't appear to be any confusion with what active or terminated meant, but that doesn't mean that there might not be confusion with those less familiar with campaign finance. This could also be a future iteration.

**Comment by dorothyyeager** [comment]
@JonellaCulmer The glossary is a mix of legal definitions and ones used for data descriptions. "terminating committee" and "ongoing committee" are legal things, but they mean specific things. For example, a committee that is not looking to terminate but that has had no financial activity for awhile would be an "ongoing" committee in the regulations, but maybe an "inactive" committee if I'm following your conversation.

A definition of "active" and "inactive" might be useful if those are terms we are using on data pages, but we'd want to mix in something like "when used on FEC data pages" to get it by OGC.

**Comment by JonellaCulmer** [comment]
@dorothyyeager Should there be more states that Active and Terminated? Do we need a third for Inactive?

Are there any others? 

cc: @AmyKort @PaulClark2

**Comment by dorothyyeager** [comment]
@JonellaCulmer Not really a data person so that seems like a better question for @PaulClark2 or @bmathesonFEC. From the legal standpoint, you're either ongoing or terminating. From the data standpoint, I could see a state for a committee that isn't terminating but isn't doing much either.

**Comment by JonellaCulmer** [comment]
@PaulClark2 @bmathesonFEC @dorothyyeager I'm partial to handling this from the legal standpoint that Dorothy mentioned in the previous comment - either ongoing or terminating. Any objections? Or any objections with the terminology I have mocked up - Active or Terminated?

cc: @AmyKort

**Comment by PaulClark2** [comment]
@JonellaCulmer @dorothyyeager we should stick to the legal/regulatory definitions. We really only identify committees as active or terminated.

**Comment by dorothyyeager** [comment]
Hmm, in that case, it would be "ongoing" or "terminated."

**Comment by dorothyyeager** [comment]
I kind of like "Active" better than ongoing though. We'd probably need to figure out how to define that for the glossary if you went with it.

**Comment by PaulClark2** [comment]
I agree with Dorothy. I'm not a fan of "ongoing."

**Comment by PaulClark2** [comment]
Below are committee filing frequencies and their appropriate"active" or "terminated" label. 

Label	|	cmte_filing_freq	|	filing frequency description
----	|	----	|	----
Active	|	Q	|	Quarterly flier
Active	|	M	|	Monthly filer
Terminated	|	T	|	Terminated
Terminated	|	A	|	Administratively terminated
 
cc: @lbeaufort

**Comment by lbeaufort** [comment]
Mockups A/B are for the committee profile page, and mockup C is for the sitewide committee search. 

**Committee profile page** 
- Committee profile page uses endpoint `committee/ID/history` for committee data
- Example: https://fec-dev-api.app.cloud.gov/v1/committee/C00693234/history?per_page=1&api_key=DEMO_KEY
- Has filing frequency, no API change needed

**Sitewide committee search** 
- Sitewide committee search uses `/names/committees/` endpoint. 
- Example: https://api.open.fec.gov/v1/names/committees/?q=Warren&api_key=DEMO_KEY
- **Needs API change**
- Consideration - this will most likely slow down search results. How much will this slow down the search results? Needs testing to be sure

cc: @PaulClark2 @JonellaCulmer

**Comment by JonellaCulmer** [comment]
@lbeaufort Thank you for looking through this. Would love to know how much the speed is impacted. 

@PaulClark2 Thoughts on opening a testing ticket for the sitewide search component and a separate ticket for the implementation of the committee profile page work?

**Comment by PaulClark2** [comment]
@JonellaCulmer your plan for two streams of work makes sense to me.

**Comment by JonellaCulmer** [comment]
@PaulClark2 @lbeaufort Are there any committee types that don't have an active/terminated status? For example, we use committee profile pages for filers. Do we want to exclude them?

**Comment by PaulClark2** [comment]
@JonellaCulmer thanks for thinking of that. Non-political committee filing entities (Form 5, 7 and 9 filers) use the same filing frequency codes as political committees. We can use the same active/terminated logic for all filers.

**Comment by JonellaCulmer** [comment]
Closing in favor of two new tickets:
1. Test the impact to results rate of return for global search if status indicator is added #3643 
2. Implement committee status on committee profile pages #3642
