### ISSUE TITLE
Research newsletter to share .gov updates

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3333]
**What we're after:**
We're hearing from our users that they are unfamiliar with new features we have implemented. Up to now the only way to know if a new feature has been deployed would be to add it to our release notes. This is great for developers who regularly use github (where those notes are posted), but not so great for the bulk of our users - those who are not as technically inclined. 

We need to consider a newsletter or something of the like that we can use to share our new features with users. Other FEC divisions use govdelivery. Is this something we want to pursue as well. How much control do we have over the layout, appearance, contact lists, etc to make sure that what we want is what is made?

### Completion criteria
- [ ] Discuss our goals for this product
- [ ] Research and schedule a discussion with govdelivery
- [ ] Research other newsletter platforms, are they useful for government use
- [ ] Make recommendation and pursue a purchase agreement, if necessary

**Comment by dorothyyeager** [comment]
It is very simple to use GovDelivery. Greg Scott is the contact for that. But Info sends them out for a lot of the pages already. Isaac uses some sort of customization for the trainings pages when he sends out gov delivery on them, I'll forward one to you.

**Comment by JonellaCulmer** [comment]
There are a multitude of ways to provide updates to .gov whenever they happen, whether that's on a regular basis or as it happens. I think whatever method we moves towards in the future will need to support irregular updates, as we do not consistently release new "features" or front-end changes that our users will be aware of. 

It probably couldn't hurt to do a survey to identify the best way to get to these specific users, who appreciate regular updates. Certainly those who are interested in a front-end .gov data related changes.

**Comment by JonellaCulmer** [comment]
Closing in favor of https://github.com/fecgov/fec-cms/issues/3765
