### ISSUE TITLE
Candidates with committees and no financial data have blank financial summary pages

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3336]
After this PR https://github.com/fecgov/fec-cms/pull/3322 was merged, we discovered that candidates that have a committee with no data are showing up with blank financial summary pages. Example http://127.0.0.1:8000/data/candidate/P00012799/?tab=summary? We  are expecting a “no data” message, not blank summary pages.

<img width="943" alt="Screen Shot 2019-11-07 at 10 41 26 AM" src="https://user-images.githubusercontent.com/31420082/68404207-2e0d7e80-014c-11ea-8971-40b35431a293.png">

**Comment by JonellaCulmer** [comment]
Work has been merged (https://github.com/fecgov/openFEC/pull/4084), so closing.
