### ISSUE TITLE
Can't close the downloads box if there's an error message

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3339]
**What we're after:** Usually there's a little X marks the spot to close the downloads box once a user is done with their download and wants to move on. It's just been observed that if there's an error message like in the screenshot below that there is no way to close the box. The user is forced to refresh the page. 

**Completion criteria:**
- [ ] Allow users to close the downloads box regardless of the content within it

**Before:** 
![Screen Shot 2019-11-07 at 4 03 22 PM](https://user-images.githubusercontent.com/31663028/68427801-d9342d00-0178-11ea-9cb1-748eccee1f63.png)

**After:**
<img width="626" alt="Screen Shot 2019-11-21 at 1 27 56 PM" src="https://user-images.githubusercontent.com/31663028/69365666-ccc4cf80-0c62-11ea-8cec-4524490f5dce.png">

**Comment by rfultz** [comment]
@JonellaCulmer, how would one go about triggering the error message?

**Comment by JonellaCulmer** [comment]
@rfultz The error message suggests that downloading over the limit would cause the error. 

@lbeaufort Do you know what that limit is?

**Comment by patphongs** [comment]
@rfultz This message occurs when there is a 429 error (over rate limit) from the API. We can test this by hooking up your local environment to the stage API. Then updating the downloads API key to something super low, so that the message will be triggered when developing.
