### ISSUE TITLE
Draft disclaimer examples to use on party fundraising by candidates page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3342]
### Summary

**What we are after:**
Now that we have a spiffy new Example template, we can use it to create examples for disclaimers that must be used on party fundraising featuring federal candidates. They could go on https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/fundraising-party-committees-federal-candidates/. Content for this could come from https://www.fec.gov/updates/fundraising-federal-candidates-and-officeholders-other-candidates-and-committees-2017/.

### Related issues

- #3149 (Example page)
- #3179 (Disclaimer examples)

### Completion criteria

- [x] Draft examples
- [x] Draft images 
- [x] Review by Info Div managers
- [x] Incorporate manager feedback into examples
- [x] Review by Content team 
- [x] Second Review by Info Div managers of additional examples and website language
- [x] Second Incorporate manager feedback into examples
- [x] Second Review by Content team 
- [x] Incorporate Content team feedback
- [x] Circulate to OGC 
- [x] OGC approval

### Future work

- [x] Draft future ticket for posting examples
- [x] Once OGC approves, create ticket to publish these.
- [ ] Publish images

**Comment by djgarr** [comment]
Following standup, it was decided to move this up to the current sprint to show it as in progress. the plan is still to have this completed by the end of PI 11

**Comment by dorothyyeager** [comment]
@djgarr is out today but he has circulated the second round to the content team. We'll give him feedback this week. Moving to 11.5.

**Comment by djgarr** [comment]
Finalized disclaimers and incorporated all edits between info div managers and content team

**Comment by dorothyyeager** [comment]
The examples have been sent to OGC for approval!  For @djgarr we can either close this ticket and pick up publishing work in #3492 after OGC approves, or we can leave it as blocked for external review until OGC approves and then close. They've been asked to return comments in next few weeks. cc: @JonellaCulmer @pkfec @bmathesonFEC for your sprint facilitation purposes.

**Comment by djgarr** [comment]
OGC reviewed the disclaimers and came back with one minor change. will close the ticket and pick it up with the publication of the images at #3492
