### ISSUE TITLE
Update fec.gov pages that reference presidential public funding once new bucket is published

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3352]
### Summary

**What we are after:**
Once we publish the presidential public funding bucket pages, we should update the other pages on the site that reference public funding to link to it. ~We will also want to link any new glossary terms that we can link.~ (We'll do that in a separate ticket)

### Related issues

- #3221 (glossary update coming soon)
- #3205 (publication of public funding bucket pages coming soon)

### Completion criteria

- [x] Identify and update pages that might need links updated. We can start a list here.

https://www.fec.gov/introduction-campaign-finance/understanding-ways-support-federal-candidates/presidential-elections/
https://www.fec.gov/introduction-campaign-finance/understanding-ways-support-federal-candidates/presidential-elections/public-funding-presidential-elections/
https://www.fec.gov/help-candidates-and-committees/registering-candidate/
https://www.fec.gov/legal-resources/enforcement/audit-reports/
https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/
https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/using-personal-funds-candidate/
https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/delegate-activity/
https://www.fec.gov/help-candidates-and-committees/making-disbursements/
https://www.fec.gov/help-candidates-and-committees/keeping-records/
https://www.fec.gov/help-candidates-and-committees/filing-reports/
https://www.fec.gov/help-candidates-and-committees/winding-down-candidate-campaign/
https://www.fec.gov/help-candidates-and-committees/filing-reports/inaugural-committee-reports/
https://www.fec.gov/help-candidates-and-committees/winding-down-candidate-campaign/
https://www.fec.gov/help-candidates-and-committees/handling-loans-debts-and-advances/
https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/contributions-made-party-committees/
https://www.fec.gov/help-candidates-and-committees/other-filers/

All pages in the new buckets:
https://www.fec.gov/help-candidates-and-committees/understanding-public-funding-presidential-elections/
https://www.fec.gov/help-candidates-and-committees/presidential-transition-and-inauguration/

**Comment by kathycarothers** [comment]
I am going through the Candidate Guide pages and adding the two bucket links were relevant. In addition, I have added the pages that have been updated in the Completion Criteria of this ticket.

**Comment by kathycarothers** [comment]
All relevant pages have been linked and a second pair of eyes (Thank you @dorothyyeager Dorothy).
