### ISSUE TITLE
Transition pages to take down 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#3358]
**What we are after** is to remove the outdated pages from transition now that the redirects are in place. These were redirected in #3209 . 

**To do**:

- [x] Remove the following pages:

https://transition.fec.gov/pages/brochures/partnership_brochure.shtml
https://transition.fec.gov/pages/brochures/partnership.shtml
https://transition.fec.gov/about/offices/offices.shtml
https://transition.fec.gov/about/offices/EEO/EEO.shtml
https://transition.fec.gov/eeo/eeo.shtml
https://transition.fec.gov/eeo/LimitedEnglishProficiencyPlan.shtml
https://www.fec.gov/pages/brochures/delegate_brochure.pdf
https://transition.fec.gov/pages/brochures/partnership_brochure.pdf

**Comment by patphongs** [comment]
https://transition.fec.gov/pages/brochures/partnership_brochure.shtml - previously removed
https://transition.fec.gov/pages/brochures/partnership.shtml - previously removed
https://transition.fec.gov/about/offices/offices.shtml - removed
https://transition.fec.gov/about/offices/EEO/EEO.shtml - removed entire /offices/eeo/ folder
https://transition.fec.gov/eeo/eeo.shtml - removed
https://transition.fec.gov/eeo/LimitedEnglishProficiencyPlan.shtml - removed
https://www.fec.gov/pages/brochures/delegate_brochure.pdf - removed
https://transition.fec.gov/pages/brochures/partnership_brochure.pdf - removed
