### ISSUE TITLE
Update the feedback box language

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3359]
**What we're after:** We receive a number of questions of varying degrees of complexity in the feedback box. To make sure that the appropriate feedback is making its way to the website team and that other more complicated compliance or regulatory questions are being properly routed, we need to improve the feedback box language.

**Completion criteria:** 
- [x] Meet to discuss language improvements to the feedback box
- [x] Provide recommendations to PMs and Info for review
- [x] Open a front-end implemention ticket

**Comment by rfultz** [comment]
@dorothyyeager @kathycarothers do you know if there's been any movement on this?

**Comment by dorothyyeager** [comment]
@rfultz I don't think @JonellaCulmer has had a chance to get to it yet.

**Comment by JonellaCulmer** [comment]
First attempt at improving the language slightly. Just to include more references to the website wherever possible. @dorothyyeager @kathycarothers Let me know what you think.

The sentence, "Or post public `website` feedback anonymously `about the website`, would be an either the first edit or second edit change, not both. I couldn't decide which I liked better. 

![Screen Shot 2020-03-03 at 3 40 04 PM](https://user-images.githubusercontent.com/31663028/75817606-6b35f600-5d65-11ea-88d3-8fa4512d0327.png)

**Comment by kathycarothers** [comment]
@JonellaCulmer and @dorothyyeager I think adding the word website in more places helps to get the point across. It explains clearly this is feedback for the website. I agree with the updated language.

**Comment by dorothyyeager** [comment]
I like where you're going with this. My vote for the edit to the one sentence would be to say "Post public feedback about the FEC website anonymously." I also think you can take out the "Or" since it's really an and/or and that puts the action word at start of sentence.

Another idea: Change the question to say "What were you trying to do **on the website** and how can we improve it.

**Comment by JonellaCulmer** [comment]
Thanks @dorothyyeager and @kathycarothers. Here's the updated mockup. 

![Screen Shot 2020-03-04 at 8 54 17 AM](https://user-images.githubusercontent.com/31663028/75886127-c44d6a80-5df5-11ea-91c4-d114016e81d3.png)

**Comment by kathycarothers** [comment]
The only small correction is to hyphen Sign-Up. Dorothy and I did some research into the GPO style guide and it will need to have a hyphen. Sorry I didn't pick-up on this earlier. Aside from that, it looks good. @JonellaCulmer @dorothyyeager

**Comment by dorothyyeager** [comment]
One more catch - should we change "using the form below" to "using this form" in order to avoid the directional word? Other than that and "sign-up"it is good to go.

Thanks! @JonellaCulmer

**Comment by JonellaCulmer** [comment]
Updated based on above and slack comments. 
@AmyKort If this looks good to you, I'll move forward with an implementation issue. 

![Screen Shot 2020-03-04 at 3 27 17 PM](https://user-images.githubusercontent.com/31663028/75920149-ced72680-5e2c-11ea-8359-792ad2c8cbc0.png)

cc: @dorothyyeager @kathycarothers

**Comment by AmyKort** [comment]
Looks great! Thanks @JonellaCulmer !

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issue https://github.com/fecgov/fec-cms/issues/3592
