### ISSUE TITLE
CSS Styles for TV ad examples

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#3373]
### Summary

**What we're after:**
We need to move CSS in the advertising reporting examples to SCSS files, instead of having it in the html block. It could probably go in `components/_responsive-object.scss` 

Draft page:
https://fec-prod-proxy.app.cloud.gov/admin/pages/10616/edit/preview/

### Related issues
https://github.com/fecgov/fec-cms/issues/3179

**Action Items**
- [x] Remove CSS from any html blocks using the TV ad example iframe background image.
- [x] Add or edit classnames where  necessary html block in Wagtail and in `components/_responsive-object.scss`  for semantic clarity

**Comment by djgarr** [comment]
@johnnyporkchops do you need anything from Content Team for this ticket?
