### ISSUE TITLE
Pages getting  500,  server-error  when trying to edit in Wagtail

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#3383]
### Summary

The following pages in `/press` return a 500, server error  when trying  to open for editing in Wagtail:

- https://fec-prod-proxy.app.cloud.gov/admin/pages/120/edit/  (Locating, downloading and exporting raw data files)
- https://fec-prod-proxy.app.cloud.gov/admin/pages/104/edit/ (Advisory opinions)
- https://fec-prod-proxy.app.cloud.gov/admin/pages/101/edit/ (Litigation involving the FEC)
~- https://fec-prod-proxy.app.cloud.gov/admin/pages/113/edit/  (Presidential Public Funding)~ Page no longer used and unpublished.
- https://fec-prod-proxy.app.cloud.gov/admin/pages/9576/edit/ (H4CC - filing amendments) 

Also, more pages than not in `About/Reports about FEC/Modernizing the E-filing experience and infrastructure` return a 500, server error  when trying  to open for editing in Wagtail:

### Completion criteria

- [x] Restore editing capability to these pages using techniques here: 
https://github.com/fecgov/fec-cms/wiki/Fixing-invalid-HTML-Wagtail-pages-that-error

**Comment by dorothyyeager** [comment]
The Press Office is no longer updating the one page about public funding - it's been retired and redirected to our main page on it. So you might not have to fix that one.

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Do we still need to address this work? If not, please close.

**Comment by dorothyyeager** [comment]
Do we want to put it into a milestone? (Yes, definitely necessary, and the page @kathycarothers found on filing amendments should be added to list above.) @JonellaCulmer

**Comment by kathycarothers** [comment]
I have added the page to the ticket.

**Comment by pkfec** [comment]
For some wagtail pages, even after removing the unwanted tags `<span>` from the body of the text and save the page, i ended up with an validation error .
ERROR:
>>> page.save()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/vcap/deps/0/python/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/home/vcap/deps/0/python/lib/python3.6/site-packages/wagtail/core/models.py", line 443, in save
    self.full_clean()
  File "/home/vcap/deps/0/python/lib/python3.6/site-packages/wagtail/core/models.py", line 433, in full_clean
    super().full_clean(*args, **kwargs)
  File "/home/vcap/deps/0/python/lib/python3.6/site-packages/django/db/models/base.py", line 1250, in full_clean
    raise ValidationError(errors)
django.core.exceptions.ValidationError: {'menu_title': ['This field cannot be blank.']}

**Comment by pkfec** [comment]
The new model requires that the  menu_title should be set on the page if doesn't exist already before saving the page.

Paired with @johnnyporkchops  and fixed above 4 wagtail pages in `dev` environment first. Tested and make sure the links are editable in wagtail.  

Copied the changes from `dev` interactive shell to the `prod` space. Wagtail pages are now editable in Dev and Prod spaces.

**Comment by patphongs** [comment]
@pkfec @johnnyporkchops Nice work on pairing with this ticket! Thanks for fixing these pages!
