### ISSUE TITLE
Blank "Individual contributions" datatable shows up for Inaugural Committees

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3390]
### Summary

As a data user, the blank `Individual contributions` datatable for Inaugural committee `Raising` tab makes me think there were no donations, which is confusing because the summary shows `$85,530,042.00` in total receipts.

### Expected Behavior

We shouldn't show a datatable for data that doesn't exist for inaugural committees. Donations filed on schedule 13-A of the Form 13 won't show up in the individual contributions datatable, which makes it look like there's no data. In the short term, we should hide that databtable for Inaugural committees. (`organization_type == 'I'`)

### Actual Behavior

<img width="1078" alt="Screen Shot 2019-11-26 at 9 16 48 AM" src="https://user-images.githubusercontent.com/31420082/69641965-0fa1f100-102f-11ea-9b26-b04feb5040d6.png">

### How to Reproduce

URL: https://www.fec.gov/data/committee/C00409011/?tab=raising&cycle=2006
1. $85 million shows in the summary
2. Blank "Individual contributions" datatable

### Completion criteria
- [x] Remove `individual contributions` datatable for Inaugural committees.
- [x] Enter a ticket to explore improvement alternatives for Inaugural committees.

**Comment by patphongs** [comment]
New [alternatives for Inaugural committees ticket](https://github.com/fecgov/fec-cms/issues/4949) has been created
