### ISSUE TITLE
Update global search during PI10 innovation

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3391]
### Summary

**What we are after:**
As a user, I want to find the content pages relevant to me.

### Related issues

_List any relevant related issue(s)_
- #3283 (plan to update global search manually once per sprint until we get automated updates going)
- #3278  (past global search task)

### Completion criteria
- [x] Make manual update to global search
- [x] Put in ticket for the next sprint update

### Future work
We'll be doing this once per sprint.

**Comment by JonellaCulmer** [comment]
@patphongs To hold a training session on how to do this, so that she's not the only point of failure.

**Comment by patphongs** [comment]
Training was conducted on 12/17. A new ticket for January search indexing has also been created #3418. This ticket is now complete, closing...
