### ISSUE TITLE
Fix issues when posting reports about the FEC

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3392]
### Summary

**What we are after:**
_As a user, I want to be able to find the reports posted by the FEC about the FEC._

**Background**
We've identified a couple of issues with reports posted about the FEC that are using the "resource page template" and we need to fix them. Right now the only pages using this are https://www.fec.gov/about/reports-about-fec/agency-operations/e-filing-study-2016/ and its child pages.

1)  Need to fix the template (front-end work): To select the category of report when using a resource page, you have to do so on the promote tab, choosing from a drop down menu. However, something is preventing the category that was selected from showing up, and is causing the page to appear in the wrong category. See the listing for "Modernizing the e-filing experience..." on https://www.fec.gov/about/reports-about-fec/agency-operations/?category=gift+report. This listing should not be included in this category, as "study" was the category assigned to it. See screenshot:

![image](https://user-images.githubusercontent.com/24437369/69662104-bc8d6580-1051-11ea-9ba1-65ceaac67a9d.png)

2. The child pages of the e-filing page most likely were completely copied/pasted from Word and can't be opened for editing. They are returning 500 server errors and will need to be restored for editing using this: https://github.com/fecgov/fec-cms/wiki/Fixing-invalid-HTML-Wagtail-pages-that-error

3. The page for the e-filing page needs some editing to make the text plain text rather than text that was copied/pasted from Word.  It also needs SEO (see screenshot above; the fields for that are blank.) This is something content team could do.

### Completion criteria

**Front end**
- [x] Find and fix the issue with the resource page template that is causing the report to show up in the wrong category (see #1 above) 
- [x] Fixing the editability of the e-filing child pages - there's a ticket for this in #3383 

**Content**
- [x] Go into https://www.fec.gov/about/reports-about-fec/agency-operations/e-filing-study-2016/ and copy the text in arial, cut, and then re-paste as plain text.
- [x] Fill out the title and search description fields.

**Comment by dorothyyeager** [comment]
Related ticket for the fixing needed for the e-filing pages at #3459 so I've added dependency.

**Comment by pkfec** [comment]
@dorothyyeager Resource pages under `FEC/Modernizing the E-filing experience and infrastructure` all are editable. These pages were fixed here https://github.com/fecgov/fec-cms/issues/3459.

**Comment by dorothyyeager** [comment]
Thanks @pkfec - the front end issue is fixed and the e-filing study is showing up as a "study." Taking Priya off and assigning myself to finish out the issue.

**Comment by dorothyyeager** [comment]
The rich text editor issues with these pages have been fixed and the pages render like they are supposed to now. Thanks again @pkfec , turned out to be a very easy fix for me. Now https://www.fec.gov/about/reports-about-fec/agency-operations/e-filing-study-2016/ and all of its child pages are looking sharp and the report can be found in the "Study" category. Closing the ticket as the work is complete.
