### ISSUE TITLE
Update links to presidential matching funds submission pages on classic page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3393]
### Summary

**What we are after:**
We moved matching fund submission pages into transition as part of our work to get ready for 2020. Now we have a classic page that is still an active page that needs some links updated to point to our new pages.

### Related issues

- #3251 

### Completion criteria

- [ ] Update the highlighted links on https://classic.fec.gov/finance/disclosure/other_disclosure.shtml to point to the new transition pages (see image below):
https://transition.fec.gov/finance/disclosure/2016MatchingFundSubmissions.shtml, https://transition.fec.gov/finance/2012matching/2012matching.shtml, https://transition.fec.gov/finance/2008matching/2008matching.shtml, https://transition.fec.gov/finance/disclosure/2004MatchingFundSubmissions.shtml

![image](https://user-images.githubusercontent.com/24437369/69669035-0af53100-105f-11ea-9fa6-76fe2571119b.png)

**Comment by patphongs** [comment]
Updates have been made as requested @dorothyyeager
