### ISSUE TITLE
Figure out why some older Record index links are not working (Content clean up work)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3397]
### Summary

**What we are after:**
_As a user, I want to be able to research older articles the Commission has posted._

### Completion criteria

- [x] Figure out what’s going on with forbidden errors on the Record index PDFs for 1996-1999 and 1980-1982 Record indexes (or if those indexes exist in PDF format)
- [x] Upload the missing indexes
- [x] Add any new links to https://www.fec.gov/updates/record-archive-1975-2004/.

**Comment by dorothyyeager** [comment]
For @patphongs when you get a moment: Is it possible to see if these documents exist in our CMS (and if yes, do what's needed to remove the "access denied" message so that the links work)?
https://www.fec.gov/resources/record/1997/index1997.pdf
https://www.fec.gov/resources/record/1998/index1998.pdf
https://www.fec.gov/resources/record/1999/index1999.pdf
https://www.fec.gov/resources/record/1982/index1982.pdf
https://www.fec.gov/resources/record/1981/index1981.pdf
https://www.fec.gov/resources/record/1980/index1980.pdf

**Comment by dorothyyeager** [comment]
Was not able to locate any copies of the indexes in Info's files. Hoping Pat can find them on the CMS; if not, will check with law library.

**Comment by patphongs** [comment]
@dorothyyeager Looks like the PDF files above don't exist. We just have index HTML files, but they're more like embedded frames. We don't currently let frames load on our site. Here's an example of a frame page that won't load: https://www.fec.gov/resources/record/1998/index98.htm

The components of that page can be seen here though:

https://www.fec.gov/resources/record/1998/index98_1.htm
https://www.fec.gov/resources/record/1998/index98_2.htm
https://www.fec.gov/resources/record/1998/index98_3.htm

Does this help? Do you think we'll want to create index PDF files for these archived records?

**Comment by dorothyyeager** [comment]
Thanks @patphongs very helpful! We're linking some of the htm files now and was hoping to replace them with a PDF. So far I've struck out at the law library and in Info files. Going to try one more place to see if we have old paper copies we could scan into a PDF, but just knowing that we don't have these PDFs in our s3 bucket is helpful.

**Comment by patphongs** [comment]
@dorothyyeager To clarify, we do have old record article PDFs. We just don't have the index PDF files. So here's an example of what the 1998 directory of PDF files look like:

<img width="98" alt="Screen Shot 2019-12-04 at 10 31 11 AM" src="https://user-images.githubusercontent.com/12799132/70155975-2e346780-1681-11ea-9a86-0cbe323521d8.png">

**Comment by dorothyyeager** [comment]
Thanks @patphongs - we're good with the old Record issues - just looking for a few missing annual indexes. It may be that they didn't get done in the first place.

**Comment by dorothyyeager** [comment]
Checking with Public Records to see if they have the indexes for the years in question. They may or may not and will get back to me next week, so moving to blocked until I hear back from them.

**Comment by dorothyyeager** [comment]
Fantastic news. We have found the paper copies of the missing indexes. Now we'll find someone to scan them into PDFs (it might be a little labor intensive) that we can upload.

**Comment by dorothyyeager** [comment]
Question for @patphongs - once I get these made into PDFs, should I give them to you to put in the s3 bucket with the rest of the Record archive, or should I just upload to the CMS?

**Comment by dorothyyeager** [comment]
@patphongs said to just put the files into the CMS. So I've uploaded them and added their new URLs to the Record archive page.

We'll need to redirect three .htm indexes for 1997, 1998, and 1999 in our next redirect ticket. I've added them to our spreadsheet for that work.

Closing as work is complete on this ticket.
