### ISSUE TITLE
Candidate disbursement and winding down pages need better interaction (Content clean up task)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3398]
### Summary

**What we are after:**
_As a campaign, I need to know what I can use campaign funds for, including winding down expenses._

### Background
We're finding that users aren't always making the links from the disbursement part of H4CC to the winding down part of H4CC. We need to look at how those pages interact with each other.

### Completion criteria

- [ ] Go through candidate disbursements and candidate winding down buckets, and see where those pages might need to link each other (either via Read next or internal button links).

**Comment by kathycarothers** [comment]
I have linked the following pages together:

- Noncampaign expenses linked with Winding down a campaign
- Personal use linked with Winding down a campaign
- Making contributions to other candidates linked with Winding down a campaign 
- Winding down the campaign linked with Making contributions to other candidates and Noncampaign expenses
