### ISSUE TITLE
Change the purposes of disbursement page to a resource template

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3400]
### Summary

**What we're after:**
_As a user, I need to be able to tab between the adequate and inadequate purposes of disbursements._

### Completion criteria

- [x] Move content from https://www.fec.gov/help-candidates-and-committees/purposes-disbursement/ into a resource page template
- [x] Publish the new page
- [x] Put in a redirect via Wagtail and unpublish the old page

**Comment by kathycarothers** [comment]
Drafting the page.

**Comment by kathycarothers** [comment]
Sent to the content team for review.

**Comment by kathycarothers** [comment]
thanks @bmathesonFEC and @dorothyyeager  for reviewing this page. The redirect is working. This ticket is now closed.
