### ISSUE TITLE
Full-width page updates

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#3406]
### Summary

Adding a "Legal citations" section to the end of the full-width page, similar to the custom page template. And removing "All notes" from the end of the charts.

### Completion criteria

_List action items that need to be done to complete this task. List in checklist formatting._
- [x] Add "Legal citation" section to full-width page templates
- [x] Remove "All notes" from chart pages 

![image](https://user-images.githubusercontent.com/40633757/70567654-5d0c7b00-1b64-11ea-9038-82efccf8344d.png)

![Screen Shot 2019-12-20 at 1 21 34 PM](https://user-images.githubusercontent.com/12799132/71281362-af4f5800-232b-11ea-8f98-98028e02ae94.png)

### Future work
- Update the dates and deadlines pages to move legal cites into the new section - #3450

**Comment by jason-upchurch** [comment]
@johnnyporkchops when you have a chance can you update as needed? Thank you!
