### ISSUE TITLE
Make a plan to shut down classic.fec.gov

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3410]
We should make a plan to shut down classic.fec.gov

- C-Name change and  DNS change that can take up to two days but can happen as soon as Friday afternoon 01/16/20

- Classic.fec.gov will redirect to www.fec.gov externally 

- classic.fec.gov will be accessible only  on FEC network

- Paul will send additional communication with links to WWW versions of Classic data applications based on this document:

https://docs.google.com/document/d/1tHNfYuK_Ktd1TypuU1r0DtyeFtNqvktmVEgseBDzw8M/edit

Create followup ticket for reevaluating response to classic shutdown #3471

**Comment by davidnir** [comment]
Is classic.fec.gov now permanently down?

**Comment by lbeaufort** [comment]
@davidnir yes, the FEC has permanently shut down its legacy website, classic.fec.gov.

For more information, please see https://www.fec.gov/campaign-finance-data/classicfecgov-permanently-discontinued/
