### ISSUE TITLE
Fix paths to open government page

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3412]
### Summary

So that the public can access our open government page, we should make it easier to find. 

1) we should redirect www.fec.gov/about/open to www.fec.gov/open OR make a application route in Django to send www.fec.gov/open to the www.fec.gov/about/open page
2) We should update the "open government" link in the page footer to link to our www.fec.gov/open page. 

### Related issues

https://github.com/fecgov/fec-cms/issues/3345

### Completion criteria

- [x] we should redirect www.fec.gov/about/open to www.fec.gov/open OR make a application route in Django to send www.fec.gov/open to the www.fec.gov/about/open page
- [x] We should update the "open government" link in the page footer to link to our www.fec.gov/open page.

**Comment by dorothyyeager** [comment]
Older pages that need to redirect to the current open page:

https://transition.fec.gov/open/index.shtml
https://classic.fec.gov/open/

**Comment by dorothyyeager** [comment]
PRs to fix this have been merged, so closing.
