### ISSUE TITLE
Bug: Extra } is appearing on various H4CC pages when printed out

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3417]
Timeboxed issue: If bigger than a bracket fix, document and move the ticket to PI 14.

### Summary

_When printing out a page from dates and deadlines, an extra } appears at the bottom of the page. Looking further, it's on many H4CC pages using various templates, including custom, resource and full-page width_

### Expected Behavior

No extra character.

### Actual Behavior

The extra character appears

### Frequency

- [ ] This is the first time it's happened
- [X] This is an ongoing, predictable issue
- [ ] It seems to be random
- [ ] Other: …

### How to Reproduce

1. Go to a H4CC page. For example, [Types of contributions](https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/types-contributions/) and hit print.
2. When page comes up in print preview, look for bracket at end of page. Here's a screenshot:
<img width="713" alt="bracket" src="https://user-images.githubusercontent.com/24437369/71023999-ed513f80-20d1-11ea-8068-e921fbf94e01.PNG">

### Browser

_Which version of which browser are you using? Does this issue occur with other browsers or with other browser sizes?_

- [X] Chrome, version: Version 79.0.3945.79 (Official Build) (64-bit)
- [X] Firefox, version: 71.0 (64-bit)
- [ ] Safari, version: …
- [ ] Edge, version: …
- [X] Internet Explorer, version: 11
- [ ] Other: …

### Device

_Tell us what you can about your device and its operating system._

- [X] Laptop/desktop, 
- [ ] Tablet
- [ ] Phone

Manufacturer: … Dell
Model: …
Operating system: … Windows 7 Enterprise
Screen orientation: …

### Misc

@patphongs took a look and thinks it's an unclosed } in several of the templates.

**Comment by patphongs** [comment]
I took a look at this and there does not appear to be an extra bracket in print preview anymore. I believe this issue has resolved itself!
