### ISSUE TITLE
Publish 2020 election reporting pages (Due: January 2, 2020)

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#3419]
### Summary

Publish reporting pages

### Related issues

- #3295 

### Completion criteria

- [x] Publish Quarterly pages for congressional candidates
- [x] Publish Quarterly pages for presidential candidates
- [x] Publish Monthly pages
- [x] Publish state pages
- [x] Publish pre-election primary/caucus reporting page
- [x] Publish CC pages
- [x] Publish EC pages
- [x] Publish FEA pages
- [x] Publish IE pages
- [x] Second pair of eyes from Information Division management
- [ ] Publish the updated Dates and deadlines page and the 2019 archive page on January 2.

**Comment by dorothyyeager** [comment]
Updating for @djgarr who is on leave. The 2020 pages have been published in a soft launch, with the exception of Dates and deadlines. Information Division management is doublechecking them now, and the updated Dates and deadline page with the 2020 links will be published on January 2.

**Comment by djgarr** [comment]
pages are published
