### ISSUE TITLE
Update current admin fine calculator in Contribute if new fines updated

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3421]
### Summary

**What we are after:**
_As a user, I need the latest administrative fine calculator with updated fines. If that happens before the new calculator is built (normally it happens via rules published in January), the old calculator is what I have to use, so it needs the latest fines_

### Related issues

_List any relevant related issue(s)_
- #https://github.com/fecgov/fec-testing/issues/127

### Completion criteria

- [ ] Make new calculator on transition for 2020
- [ ] Review by AF office
- [ ] Link new calculator on this page as well as review content: https://www.fec.gov/legal-resources/enforcement/administrative-fines/calculating-administrative-fines/#calculating-a-fine

### Future work

_Other future work that may be needed following this issue's completion._

**Comment by patphongs** [comment]
We have not heard about changes to this yet. Moving to blocked until commission is able to make a decision.

**Comment by dorothyyeager** [comment]
Closed because the new calculator is up and we are redirecting the old ones in #3783 .
