### ISSUE TITLE
Admin fine calculator preliminary mockups and review with stakeholder

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3431]
Preliminary design and mock ups need to be created and reviewed with stakeholder. We will only be using approved (existing) language.

**Completion criteria:**
- [x] Create design mock-ups for the admin fine calculator based on user testing
- [x] Discuss mock-up with stakeholder for any needed changes

**Comment by JonellaCulmer** [comment]
**Preliminary decision tree:** Each green box is a screen.

![AdminFineDecisionTree](https://user-images.githubusercontent.com/31663028/72027733-18046300-324e-11ea-8bae-278e5c756c45.jpg)

**Comment by JonellaCulmer** [comment]
Invision prototype: https://invis.io/4GVJIFJE8BS

**Comment by JonellaCulmer** [comment]
First round of reviews have come back from ADR. It's not looking likely that we'll keep the second stream of questions, for "not sure" where users can get extra help to determine if their report is election sensitive or not. I would like to include some additional information to improve that portion and the suggestion is being discussed within the ADR team. The prototype (link in previous comment) is being updated as conversations progress, so it will always be the latest version.

**Comment by JonellaCulmer** [comment]
Blocked while waiting to hear back from ADR.

**Comment by JonellaCulmer** [comment]
I've received some final feedback from Compliance and have made some very minor tweaks. We are good to move forward with development. 

https://invis.io/4GVJIFJE8BS

**Comment by JonellaCulmer** [comment]
Link to files: https://drive.google.com/drive/folders/0B1PRnuw_hqg1SnJjYW80eTgxNTA
