### ISSUE TITLE
H4 data-design studio with RAD, Press, and Website team

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3432]
### Summary

**What we're after:**
_We need to hold a data design studio with RAD and Press to determine MVPs for the new schedule H endpoints._

**Note:** The H4 endpoint prototype was created (PR openFEC#4123, issue openFEC#4112), we need to determine if we have everything we need in this particular endpoint or if there are other fields needed.

**Completion criteria:**
- [ ] Determine which fields to display in the front end datatable
- [ ] Determine which fields are required for schedule_h export 
- [ ] Determine filter options

**Comment by JonellaCulmer** [comment]
The data-design studio is scheduled for today at 1pm. We have participants from RAD, Press, and IT which should make for a great discussion. 

Presentation:
https://docs.google.com/presentation/d/1_GQuLpsx-4kUuvv921ooD0JWpaIolk1342ASfklnkKM/edit#slide=id.g2549073cbc_1_205

**Comment by JonellaCulmer** [comment]
RAD is going to spend some time looking at the H4 endpoint and come back to IT with a list of fields that they know to ve relevant to the endpoint and let us know if there are some that they can remove. 

This work is blocked until then, as well as in favor of other IT projects that need to take precedence.

**Comment by bmathesonFEC** [comment]
The endpoint prototype link and data has been delivered to RAD specialists for to review. The will provide feedback on the following by the end of this week:

- required columns they want to see in the exported H4 data -- remembering not to overexclude data
- suggested columns for the eventual data table once front end work starts in PI 12
- suggested data to display in the flyout on the data table

**Comment by bmathesonFEC** [comment]
Received feedback from RAD on H4 data. Reviewing today, but they asked quite a few of questions about the data. I am planning to answer as many questions as possible and summarize any questions before relaying it to you.

**Comment by patphongs** [comment]
Completed work, closing
