### ISSUE TITLE
Fix connected organization field on about this committee tab

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3435]
### Summary

_After refactoring the committee profile page, we did not update the variable for the connected organization field. As a result, this field is blank._

**How to fix:** update variable name on committee profile page to be: `committee.affiliated_committee_name`. https://github.com/fecgov/fec-cms/blob/3328d825b4376111a4e0edff59c98f51049f402a/fec/data/templates/partials/committee/about-committee.jinja#L80

### How to Reproduce

See any SSF committee page such as: https://www.fec.gov/data/committee/C00062224/?tab=about-committee

### Screenshots

<img width="582" alt="Screen Shot 2020-01-02 at 2 53 49 PM" src="https://user-images.githubusercontent.com/12799132/71689320-c2244c80-2d6f-11ea-8ae0-7a461ae356bd.png">

**Comment by jason-upchurch** [comment]
hotfix merged, closing issue
