### ISSUE TITLE
Preserve dates and deadlines archives offline

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3441]
### Summary

**What we are after:**
Information Division would like to maintain the archived dates and deadlines on transition permanently offline. We plan to archive dates online for 4 to 6 years (Records management and statute of limitations), but we want to keep older ones (pre-2015) accessible for staff. This will also let us take those files off transition.

Ideas:
- infoweb?

### Completion criteria

- [x] Determine how many years will be displayed on site (Decided in 6 years)
- [x] Decide how we will meet record keeping requirements internally

### Future work
Once decisions are made:
- update the site
- setup internal record keeping

**Comment by johnnyporkchops** [comment]
Closing, @dorothyyeager is making a new ticket to move content to InfoWeb
