### ISSUE TITLE
Wagtail wish list: Tweak the Resource and Example Page templates so it doesn't impose a height restriction on images

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3445]
### Summary

**What we are after:**
_As a user, I want the images showing reporting examples to be nice and clear and easy to read._

### Related issues

- #3341 (lobbyist bundling page work)
- #3794 Related page links on resource page wishlist item

### Background
In working on the lobbyist bundling page, which uses the Resource Page template, the images used kept looking fuzzy. They had worked fine on the Record article (but that uses a different template). After looking into it, @rfultz and @jjonesfec figured out that the Resource Page template is imposing a height requirement of 435 pixels on the images. Since reporting images usually use a different height, we'd like to see if that restriction could be lifted.

This issue is also happening to the example page templates. Qhile working on the disclaimer example pages, most notably for the subway billboard ad (https://www.fec.gov/help-candidates-and-committees/making-disbursements-pac/nonconnected-coordinated-communication-example/) the picture elongates on smaller screens and windows.

Test custom page for same problem. 

### Completion criteria
- [ ] use the lobbyist bundling page images as a test for solution
- [ ] images don't stretch vertically

**Comment by jjonesfec** [comment]
Aside from any fuzziness, the fixed height setting was distorting the proportions for images created with the expectation of there being no fixed height.

**Comment by djgarr** [comment]
We're running into the same issue with some images on example page templates (see example below). Would be good to add the example pages to this ticket if possible
![image](https://user-images.githubusercontent.com/40633757/89456332-b8adf900-d731-11ea-8763-8dff1632e256.png)
