### ISSUE TITLE
Fix broken links in Press Release

### ISSUE THREAD

**Issue by AmyKort** [fecgov/fec-cms#3449]
The links in this Press Release are broken: https://www.fec.gov/updates/fec-receives-response-from-senator-mccains-presidential-committee-regarding-primary-matching-funds/

The pdfs we are looking for are on the classic site. Can we move these pdfs over to the new site and link them in the press release?

(Classic links to documents that are missing)
https://classic.fec.gov/press/press2008/20080226letter.PDF
https://classic.fec.gov/press/press2008/FECtoMcCain.PDF
https://classic.fec.gov/press/press2008/mccainletter.pdf
https://classic.fec.gov/press/press2008/20080220c1image.pdf

**Comment by patphongs** [comment]
Closed in favor of this ticket that will fix more issues like this: https://github.com/fecgov/fec-cms/issues/3451
