### ISSUE TITLE
Update full-width pages with legal citations (After 11.2 release goes live January 28)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3450]
### Summary

**What we are after:**
_As a dates and deadlines user, I like to see the legal citations in the usual format._

After the full-width template is updated for the legal citations format, the content team needs to go through the pages that use it (dates and deadlines) and move the legal citations into the new spot.

### Related issues

_List any relevant related issue(s)_
- #3406 (full-width page updates)

### Completion criteria
- [x] identify all pages that need legal citations in the usual spot
- [x] update legal citations on those pages

**Comment by djgarr** [comment]
updated and published pages with citation information on 1/30/2020
