### ISSUE TITLE
[Med] Snyk: Denial of Service (DoS) Due (03/08/2020)

### ISSUE THREAD

**Issue by fec-jli** [fecgov/fec-cms#3454]
[https://app.snyk.io/vuln/SNYK-PYTHON-PILLOW-540746](https://app.snyk.io/vuln/SNYK-PYTHON-PILLOW-540746)
Affecting pillow package, versions [,6.2.2)

Remediation:Upgrade Pillow to version 6.2.2 or higher.

Pillow is a PIL (Python Imaging Library) fork.
Affected versions of this package are vulnerable to Denial of Service (DoS). FpxImagePlugin.py calls the range function on an unvalidated 32-bit integer if the number of bands is large. On Windows running 32-bit Python, this results in an OverflowError or MemoryError due to the 2 GB limit. However, on Linux running 64-bit Python this results in the process being terminated by the OOM killer.
Denial of Service (DoS) describes a family of attacks, all aimed at making a system inaccessible to its intended and legitimate users.

Unlike other vulnerabilities, DoS attacks usually do not aim at breaching security. Rather, they are focused on making websites and services unavailable to genuine users resulting in downtime.

One popular Denial of Service vulnerability is DDoS (a Distributed Denial of Service), an attack that attempts to clog network pipes to the system by generating a large volume of traffic from many machines.

When it comes to open source libraries, DoS vulnerabilities allow attackers to trigger such a crash or crippling of the service by using a flaw either in the application code or from the use of open source libraries.

Two common types of DoS vulnerabilities:

High CPU/Memory Consumption- An attacker sending crafted requests that could cause the system to take a disproportionate amount of time to process. For example, commons-fileupload:commons-fileupload.

Crash - An attacker sending crafted requests that could cause the system to crash. For Example, npm ws package

**Comment by pkfec** [comment]
Pillow is child pkg of wagtail.  CMS app has `wagtail==2.2.1` version. However, the latest wagtail version available is` v2.8`. 
I will try to update wagtail pkg to a stable version that do not break our existing site which should also fix the vulnerable pkg pillow.

**Comment by pkfec** [comment]
With Django and Wagtail upgrade , following Pillow pkg issues will be resolved:
#3454
#3529
#3482
#3478
#3105
#3396
#3422

**Comment by pkfec** [comment]
PR #3563 merged. Closing this issue
