### ISSUE TITLE
Pages getting 500, server-error when trying to edit in Wagtail

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#3459]
### Summary
The following pages in `about/Reports about FEC/Modernizing the E-filing experience and infrastructure` return a 500, server error when trying to open for editing in Wagtail:

https://fec-prod-proxy.app.cloud.gov/admin/pages/6654/edit/

https://fec-prod-proxy.app.cloud.gov/admin/pages/6661/edit/

https://fec-prod-proxy.app.cloud.gov/admin/pages/6663/edit/

https://fec-prod-proxy.app.cloud.gov/admin/pages/6679/edit/

https://fec-prod-proxy.app.cloud.gov/admin/pages/6657/edit/

### Completion criteria

- [ ] Editing capability to these pages can been restored, using techniques here: 
https://github.com/fecgov/fec-cms/wiki/Fixing-invalid-HTML-Wagtail-pages-that-error

**Comment by dorothyyeager** [comment]
See related ticket at #3392

**Comment by pkfec** [comment]
1. These pages have few HTML tags that are not compatible with in the wagtail. For example `<span></span>` and `<\` tag before each closing tag. Have to remove these tags from the `intro`, and `sections` of the resource page.
But this technique only worked when the sections are small and without images etc...

2. Create a new wagtail page in dev by copying intro and each section manually from prod (copy the text from live view). This new page will have a new pageid. Now by activating the python interactive shell( i followed the instructions in wiki) replace the sections of the broken page(s) with the new page that i created earlier. 
3. In one scenario 6654, the images were not in sync with the dev. I had to manually delete the images from the prod wagtail page and upload  the images saved on my computer.

Screenshot of image in dev#
<img width="1242" alt="Screen Shot 2020-02-03 at 11 42 14 AM" src="https://user-images.githubusercontent.com/11650355/73672142-5db02200-467a-11ea-9303-11e2cd1aab30.png">


Screenshot of image in prod#(this is wrong)
<img width="1197" alt="Screen Shot 2020-02-03 at 11 42 38 AM" src="https://user-images.githubusercontent.com/11650355/73672184-6f91c500-467a-11ea-9a13-46cdab0fd89b.png">

**Comment by pkfec** [comment]
I have learned a lot from the shadowing sessions i had with @johnnyporkchops while working on this ticket.Thanks @johnnyporkchops.
