### ISSUE TITLE
Get prototype "basic" logic-free admin fine calculator wizard working 

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3461]
### Summary

**What we're after:**
_For the admin fine calculator wizard, we want to be able to style the wizard and match current FEC pattern library styles to design mock ups._

Invision prototype (in progress): https://invis.io/4GVJIFJE8BS#/400634275_Calculator_Screen_1

### Related issues

_List any relevant related issue(s)_
- #3414 

### Completion criteria

- [ ] calculator should match the site and basic functionality (next, previous, pagination) should work (no expectation that the formulas work).

### Future work

- _Implementing logic for admin fine calculations. This will be a future ticket._
- _Make the content editable in wagtail so the content team can update numbers easily._

**Comment by rfultz** [comment]
Closing this in favor of #3673 . This was the prototype and the next version is part of the build
