### ISSUE TITLE
Draft party disclaimer examples

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#3462]
### 

**What we're after:**
To present the regulated community with disclaimer examples for the real world.

### Completion criteria

List action items that need to be done to complete this task. 
- [ ] Draft examples
- [ ] Draft images 
- [ ] Review by Info Div managers
- [ ] Incorporate manager feedback into examples
- [ ] Circulate to content team 
- [ ] Circulate to OGC 
- [ ] OGC approval

### Future work

- [ ] Draft future ticket for posting examples: 
- [ ] Incorporate OGC comments and edits
- [ ] Publish images

**Comment by dorothyyeager** [comment]
Hi @djgarr Just wanted to flag this ticket for you. https://github.com/fecgov/fec-cms/issues/3342

**Comment by djgarr** [comment]
@dorothyyeager Thanks! I thought a ticket had been created, but couldn't locate it. I'll close this ticket and update #3342
