### ISSUE TITLE
[Snyk: Medium] Allocation of Resources without limits (Due: 3/15/2020)

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-cms#3467]
### Summary

**Remediation:** Pin Pillow@5.4.1 to Pillow@6.2.0 to fix
  ✗ Allocation of Resources Without Limits or Throttling [Medium Severity][https://snyk.io/vuln/SNYK-PYTHON-PILLOW-536096] in Pillow@5.4.1
    introduced by wagtail@2.2.1 > Pillow@5.4.1

**Comment by patphongs** [comment]
This is related to #3396. From earlier discussions, we did not see this as a significant external security vulnerability: https://github.com/fecgov/fec-cms/issues/3396#issuecomment-569716632

**Comment by pkfec** [comment]
The pillow pkg upgrade is handled in this PR https://github.com/fecgov/fec-cms/pull/3563. The change gets deployed to `dev` on 03/03 during the 11.5 release cut.

**Comment by pkfec** [comment]
Pillow pkg is also updated to v6.2.2. PR #3563. This PR #3563 is merged. Closing this issue.
