### ISSUE TITLE
Move archived dates and deadlines pages from transition to InfoWeb

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3473]
### Summary

**What we are after:**
_As a user, I may need to consult dates and deadlines for a previous election cycle._

### Related issues

- In #3441 we decided that the dates and deadlines pages will keep six years worth of archived pages. We'll archive older cycles on InfoWeb (an intranet site for internal use by FEC staff).

### Completion criteria

_List action items that need to be done to complete this task. List in checklist formatting._
- [x] Consult with Information Division and have the front end copy the needed transition files from the following years into InfoWeb: 2019, 2018, 2017, 2016, 2015, 2014, 2013, 2012, 2011, 2010 - back to 2006. The pages do not need to be in Wagtail format; transition format is fine for the archive.
- [x] Add link to new archive on InfoWeb (on http://infoweb.fec.gov/reporting/index.html)

Idea: 
![image](https://user-images.githubusercontent.com/24437369/95226030-77d26f00-07ca-11eb-989e-860f5872b1ad.png)

- [x] Test that it works.

### Future work

- Remove/Delete these pages from transition? (Depends on what's needed to move them to Infoweb.)
- Put in redirects for 2010-2014 main page to Dates and deadlines.

**Comment by patphongs** [comment]
Steps we'll need to take to do the full migration of archived dates and deadlines from transition to infoweb.

1. Migrate these transition site directories over to infoweb based on years `2010-2014`. 

```
/info/report_dates_[YEAR].shtml --> /reporting/report_dates_[YEAR].shtml
/info/charts_primary_dates_[YEAR].shtml --> /reporting/charts_primary_dates_[YEAR].shtml
/info/charts_cc_dates_[YEAR].shtml --> /reporting/charts_cc_dates_[YEAR].shtml
/info/charts_ec_dates_[YEAR].shtml --> /reporting/charts_ec_dates_[YEAR].shtml
/info/charts_ie_dates_[YEAR].shtml --> /reporting/charts_ie_dates_[YEAR].shtml
/info/charts_fea_dates_[YEAR].shtml --> /reporting/charts_fea_dates_[YEAR].shtml
/pages/report_notices/[YEAR] --> /reporting/[YEAR]
/pages/report_notices/[YEAR]/[FREQUENCY].shtml --> /reporting/[YEAR]/[FREQUENCY].shtml
/law/cfr/ej_compilation/[YEAR]/notice_[YEAR]-[FR#].pdf or /law/cfr/ej_compilation/[YEAR]/notice[YEAR]-[FR#].pdf --> /reporting/fr/[YEAR]/notice_[YEAR]-[FR#].pdf or /reporting/fr/[YEAR]/notice[YEAR]-[FR#].pdf
```

2. Re-template the header and footers for these transition pages to be the infoweb headers and footers

3. Re-link dependent URLs that went to transition, now will go to infoweb

3. Infoweb reporting landing page change links to go to infoweb archived page

4. Delete archive year pages from transition

**Comment by patphongs** [comment]
@djgarr will create a landing page in infoweb for archived dates and deadlines that will link to transition for now until we have the time to complete the steps outlined above for the full migration. Please make another ticket.

**Comment by johnnyporkchops** [comment]
@patphongs , @djgarr. Should we wait until Infoweb is in Wagtail to do the full migration?

**Comment by jason-upchurch** [comment]
@djgarr I moved this to innovation sprint in preparation for the next iteration. Please let me know if I need to reprioritize it--thank you!
