### ISSUE TITLE
Design and mock up new Policy and Guidance searchable page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3490]
### Summary

**What we are after:**
_Executive order 13892 requires the FEC to create a searchable page that contains the agency's guidance._

### Related issues

_List any relevant related issue(s)_
- #3220 (Prepping PDFs)
- #3488 (Research ticket for searching PDFs)

### Completion criteria

_List action items that need to be done to complete this task. List in checklist formatting._
- [x] Determine information architecture -where will it live? (Legal resources)
- [x] Determine what it will include? Keywords, Boolean, AND/OR, filters? Does search.gov provide this? (Keyword search
- [x] Conversations with OGC Policy
- [ ] Follow-up tasks such as set up redirect, create new issue
- [ ] etc

### Future work

- Create the new searchable page. Update fec-cms #3491

**Comment by pkfec** [comment]
@JonellaCulmer Need your input on this ticket. Do you think you have all the information that you need to work on ticket. Please feel free to update this ticket if needed.

**Comment by JonellaCulmer** [comment]
@AmyKort Because this is a guidance type page, I'm imagining that this search would live in the H4CC section and we would link to it from relevant pages. Do you have any objections to that?

cc: @dorothyyeager

**Comment by jason-upchurch** [comment]
@JonellaCulmer one place users may test functionality of the prototype is: https://search.usa.gov/search?utf8=%E2%9C%93&affiliate=fec_content_s3

**Comment by JonellaCulmer** [comment]
Mockup so far for policy-guidance feed. Ideally would like the new search to have a skin that resembles the document feed we use for search throughout the site. I'd rather we not introduce yet another type of search. Sticking with this feed should be sufficient for our needs. 

There are some details that might cause concern:
- Dates seem inconsistent across all documents. Will this present a problem for the feed?
- How do we determine the document type? Is this available through search.gov?
- Not sure we can alter the size of the search box to approximately half-width. This would likely shrink should we need to add other filters. 

@AmyKort Do you think this mockup, along with the prototype to be enough to have a conversation with OGC? Through our conversation with them we can get their thoughts on where this could live and any other functionality that they believe fall under the purview of the executive order. 

### Mockup
![Policy_guidance_feed](https://user-images.githubusercontent.com/31663028/75815414-5e170800-5d61-11ea-83bc-a874680965a1.png)

cc: @patphongs @dorothyyeager @jason-upchurch

**Comment by dorothyyeager** [comment]
The document types - they are all PDFs or HTML pages. We have a [list of the documents we need to include](https://docs.google.com/document/d/11Cl-nuGtiTkl7rormQoWYxF3vuhiDi8fCsjV7HrPlvs/edit?usp=sharing), but we do need to ask OGC if supporting documents (like comments on proposed policies) need to be included in this searchable database.

About the date: Not all of these files will have an exact date. For example, forms and Guides will only have a month and a year.

**Comment by jason-upchurch** [comment]
@dorothyyeager thank you for this. Just to clarify the work I did with the prototype, that pertained to searchable pdfs in an s3 bucket. I am not sure how html pages will come into play precisely but I imagine one way might be to provide search.gov a second sitemap (one that deals with pdfs in s3, and another that deals with html pages). This way we can have well-defined steps for either case. For our purposes, we may even want two separate issues.

**Comment by JonellaCulmer** [comment]
@dorothyyeager Perhaps we can leave the document type out? And I'd like to include the date if possible, but if that's not reliable either, we need to find another way to organize the raw list of everything so that it can display without requiring filters. 

> Just to clarify the work I did with the prototype, that pertained to searchable pdfs in an s3 bucket. I am not sure how html pages will come into play precisely but I imagine one way might be to provide search.gov a second sitemap (one that deals with pdfs in s3, and another that deals with html pages). This way we can have well-defined steps for either case. For our purposes, we may even want two separate issues.

@jason-upchurch Do you need to have another conversation with search.gov about the HTML links? To make sure those will all appear in the same search?

cc: @AmyKort @patphongs

**Comment by jason-upchurch** [comment]
> @dorothyyeager Perhaps we can leave the document type out? And I'd like to include the date if possible, but if that's not reliable either, we need to find another way to organize the raw list of everything so that it can display without requiring filters.
> 
> > Just to clarify the work I did with the prototype, that pertained to searchable pdfs in an s3 bucket. I am not sure how html pages will come into play precisely but I imagine one way might be to provide search.gov a second sitemap (one that deals with pdfs in s3, and another that deals with html pages). This way we can have well-defined steps for either case. For our purposes, we may even want two separate issues.
> 
> @jason-upchurch Do you need to have another conversation with search.gov about the HTML links? To make sure those will all appear in the same search?
> 
> cc: @AmyKort @patphongs

@JonellaCulmer @dorothyyeager @AmyKort @PaulClark2 a conversation with search.gov is a minimum (recall I had a whole ticket to converse with them on just the s3 pdf stuff). I'm level setting here. I'll try to "squeeze in" what I can but I would like to be clear that there are more steps between having the conversation and making it work.

**Comment by AmyKort** [comment]
Could we change "Policy and Guidance" to "Guidance Documents"? That's the term used in the EO to describe the information we're compiling.

**Comment by dorothyyeager** [comment]
I'd prefer what Amy suggested just above as well. We are still going to have to do something with the old policy page and just to keep us sane, it would be good if we used different titles.

**Comment by JonellaCulmer** [comment]
@AmyKort I considered that for my mockup, but we don't really use the word "documents" in our other feeds. But we have said "reports." 

Can we specify the type of guidance somehow? Like Legal or compliance guidance

cc: @dorothyyeager

**Comment by dorothyyeager** [comment]
@JonellaCulmer Looking at the EO, they call the things we have to list "Guidance Documents".

Are you thinking in terms of a document feed page where there are categories of documents linked?

If so, the docs on OGC's list fall into these broad categories:

- Policy Statements
- Interpretive Rules
- Campaign Guides
- Press Releases (these are the HTML things)
- Forms and Form Instructions
- Other Documents: Under Other, OGC has listed "Commissioner Compliance Tips", Guidebook on Enforcement Process, Guideline for Presentation in Good Order, Internal Controls for Political Committees.  - We might want to make up a name for this category other than "Other." Maybe "Guidebooks and Tip Sheets" would work.

**Comment by JonellaCulmer** [comment]
@dorothyyeager I guess the question now, is do we maintain the pattern for the website, or name the feed according to the EO?

**Comment by AmyKort** [comment]
Thanks, @dorothyyeager . I agree. Overall, the type of guidance we will have in the feed is "Guidance documents." This is a new term of art defined in the EO that has a really specific definition. I think we need to call it that.

**Comment by dorothyyeager** [comment]
I think the page should be called Guidance documents. I don't know that we need to break them down further other than a list, but if we want to categorize them, I can see how that would be helpful for sorting purposes? Similar to the way docs are sorted on our reports landing pages (for example, see https://www.fec.gov/about/reports-about-fec/strategy-budget-and-performance). I don't think it's necessary for purposes of fulfilling the executive order though.

Was also thinking about the dates. If the forms are what we don't have dates for, it is possible to get month/year for them from Info Div.

**Comment by AmyKort** [comment]
In other cases where we had difficulty identifying the month of publication, we've listed just the year. See, for example, some of our reports under procurement and contracting.

**Comment by JonellaCulmer** [comment]
@dorothyyeager If you think we can at least get a month and year, that would be good. We also need to check the wagtail template to make sure that it can accommodate both at the same time. Stuff with full date, and just month and date.

@dorothyyeager @AmyKort Do we want an intro paragraph for the feed? Doesn't have to be long. For Latest updates we just say: "Search or browse the latest information about the Commission and federal campaign finance law."

Updated mockup below:

![Screen Shot 2020-03-04 at 3 48 07 PM](https://user-images.githubusercontent.com/31663028/75921701-92f19080-5e2f-11ea-8a0f-e3adf895c422.png)

**Comment by AmyKort** [comment]
We're absolutely going to need a paragraph. But we'll have to ask for help with what to say. That's one thing we'll want to discuss when we share this out, so I think what you have is fine for our early conversations. Thanks! 

@JonellaCulmer and @dorothyyeager

**Comment by JonellaCulmer** [comment]
Based on conversations with @AmyKort and @dorothyyeager, please see the latest version of the mockup. It changes the date format to month and year, and removes the PDF reference in the event that will be a difficult implementation. We're focusing on the MVP.

![Guidance_documents_feed](https://user-images.githubusercontent.com/31663028/76001415-0ef0e480-5ed3-11ea-8063-2dcf59b17283.png)

**Comment by AmyKort** [comment]
Looks really good to me @JonellaCulmer

**Comment by JonellaCulmer** [comment]
Blocked until we meet with OGC to discuss the mock up and next steps.

**Comment by JonellaCulmer** [comment]
Updated to reflect new section color and breadcrumbs.

![Document feed + filter_blue](https://user-images.githubusercontent.com/31663028/77195242-af402f00-6ab7-11ea-9b6c-6be4c8c325e1.jpg)

**Comment by JonellaCulmer** [comment]
@patphongs As discussed in slack, I've updated the design to make space for the second and third paragraphs at the bottom of the page. I've also updated the top of the results section to include the number of results, that you included in your screenshot. I like that addition. But can it be moved above the dividing blue line?

![Guidance_document_search](https://user-images.githubusercontent.com/31663028/77932542-b1ef1100-727b-11ea-8e58-81b0f6ac92b1.jpg)

cc: @AmyKort @dorothyyeager @kathycarothers

**Comment by dorothyyeager** [comment]
This works for me @JonellaCulmer - Of course, let's hope it works for OGC! But it achieves the goal of getting the legalese in there that's required.

**Comment by dorothyyeager** [comment]
@JonellaCulmer After testing on feature, we're going to need a tool tip or a sentence that explains the best way to search - boolean or otherwise. We got different results trying things different ways. cc @AmyKort @patphongs I left a similar note in Pat's PR.

**Comment by JonellaCulmer** [comment]
Front-end development happening here (xhttps://github.com/fecgov/fec-cms/pull/3607) so closing.
