### ISSUE TITLE
Implementation ticket: new Policy and Guidance searchable page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3491]
### Summary

**What we are after:**
_Executive order 13892 requires the FEC to create a searchable page that contains the agency's guidance._

### Related issues

_List any relevant related issue(s)_
- #3490 (Design work)
- #3489 (Research indexing for search of PDFs)
- #3488 (Prepping the PDFs)
- #3601 (Research: Add policy and guidance search to CMS)

**Comment by patphongs** [comment]
The issues tied to this ticket have all been closed, so I am closing this ticket...
