### ISSUE TITLE
Add electronic filing search to FEC.gov

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#3493]
**What we are after**
Add electronic filing search to FEC.gov

We need to replicate the search functionality of this form /finance/disclosure/efile_search.shtml

**Completion criteria**
- [x] Ask @JonellaCulmer about placement. Maybe it’s just a link on the filings and reports page that takes you to the form. 
- [x] Make electronic filing form in Wagtail
- [x] Make pick lists for state etc. on form function

**Comment by johnnyporkchops** [comment]
@JonellaCulmer , What section, or what URL would be preferable for this page?

**Comment by JonellaCulmer** [comment]
@johnnyporkchops @PaulClark2 @AmyKort 
Please see the below mockup of how the "All electronic filings" search link can look on the Filings browse data page. Let me know if you have any edits to the language.

<img width="631" alt="Screen Shot 2020-01-30 at 4 13 28 PM" src="https://user-images.githubusercontent.com/31663028/73490962-951d8680-437b-11ea-87ee-162db70e9f55.png">

cc: @patphongs

**Comment by PaulClark2** [comment]
@AmyKort you can also search electronic filings from all filings. Maybe this is fine. I don't want folks to think you can only search for electronic filings from the "all electronic filings" link.  I really don't have a suggestion for a better label or for language we might use to help people understand the "all electronic filings" search is the legacy search.

**Comment by JonellaCulmer** [comment]
@PaulClark2 Should we distinguish some of the search functionality that the legacy search has that the "all filings" does not? But in that case, we may have to add additional clarity under "all filings" as well. 
cc: @AmyKort

**Comment by PaulClark2** [comment]
@JonellaCulmer @AmyKort since this needs to be deployed today. I think it can go out as is. We can try to improve it after folks use it this weekend.

**Comment by johnnyporkchops** [comment]
@PaulClark2 , @JonellaCulmer  I removed the paragraph with links from the top of the form because they are dead links. Let me know if that's an issue.

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Should we open a follow-up ticket for improvements? 

cc: @PaulClark2

**Comment by johnnyporkchops** [comment]
"View or download electronically filed reports from 1997 to the present. The Report Image Search and Disclosure Data Search pages include both paper and electronically filed reports. Subscribe to the FEC Electronic Filing RSS Feed to see and download electronic filings as they are received.
"

> @johnnyporkchops Should we open a follow-up ticket for improvements?
> 
> cc: @PaulClark2
Thats probably a good idea

**Comment by PaulClark2** [comment]
Thank you both @johnnyporkchops @JonellaCulmer

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Okay, thanks, John. I'll add future changes to that ticket. Do you mind opening?

**Comment by johnnyporkchops** [comment]
The form works in modern browsers but returns a 500 error in IE-- this is also the case on classic so we are nor losing any existing functionality. I would be curious to know if Rad people were using it before classic shutdown, and if so, were they using IE?

**Comment by PaulClark2** [comment]
Thanks @johnnyporkchops for looking into this. Most folks in RAD have both IE and Firefox.
