### ISSUE TITLE
Update presidential map help page to reflect how it looks as of 1/31

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3494]
### Summary

**What we are after**
_The presidential map data is now in accordion style and the help page needs to reflect how it works._

### Related issues

_List any relevant related issue(s)_
- #3496 

### Completion criteria

- [x] Draft update to https://www.fec.gov/campaign-finance-data/presidential-map-help/ to reflect how https://www.fec.gov/data/browse-data/?tab=candidates works (the presidential accordion part) 
- [x] Draft reviewed by Paul/Pat/someone who knows what's there and how the accordions work
- [x] Save the old instructions for the return of the map
- [x] Update the page once draft language approved

### Future work

We may need to revisit the description again after other work is completed. See #3496

**Comment by bmathesonFEC** [comment]
Met with Dorothy to discuss the goals of this ticket. Working on draft today.

**Comment by bmathesonFEC** [comment]
Preserved current "Presidential Map Content" in multiple formats: HTML, pdf, word. Also, the page will still be visible in Wagtail's version control. 

Saved in our drive; classic.fec.gov > Presidential Map Help Page

**Comment by dorothyyeager** [comment]
For @patphongs @PaulClark2 Here's the Wagtail draft @bmathesonFEC  needs review of - https://fec-prod-proxy.app.cloud.gov/admin/pages/10252/view_draft/

**Comment by bmathesonFEC** [comment]
@dorothyyeager, thank you for doing leading this ticket through the process!

The draft incorporates as much of the useful language from the previous presidential map help page as possible. Specifically the language related to Contributions By Size.

**Comment by bmathesonFEC** [comment]
Page published with approved language. Sticking with references to _map_.
