### ISSUE TITLE
Update the presidential map help page to reflect new map

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3496]
### Summary

**What we are after:**
_As a user, I need to understand what data is included in the presidential map and how to access it._

### Related issues

_List any relevant related issue(s)_
- #3494 Updating to explain accordions

### Completion criteria

_List action items that need to be done to complete this task. List in checklist formatting._
- [x] Make sure the presidential map help page reflects the product to be released. (Use older instructions as a base for drafting, see #3494)
- [x] Remove references to directional-type words.
- [x] Review by PMs/content team before publishing
- [x]  Consider changing the template to resource template since it's a long page
- [x] Follow-up tasks such as set up redirect, create new issue

### Design
Design work: https://github.com/fecgov/fec-cms/issues/3502
![National view - bubbles](https://user-images.githubusercontent.com/31663028/74055921-f0b8c700-49ae-11ea-9c8d-c4f7bfce159b.jpg)

**Comment by bmathesonFEC** [comment]
Started drafting the new data help page for the map for us to discuss. The language is going to be pulled from the old map's methodology page as closely as possible, changes are being made to conform the language to the current look/flow of the map.

In it's current format the new resources page (hat tip to @dorothyyeager) I propose three sections:
1. Presidential Map Overview
2. Methodology and formulas
3. Downloadable presidential map data (basically the information that is currently [here ](https://www.fec.gov/campaign-finance-data/presidential-map-help/)now.)

Each of these sections will have it's own anchor link that can be linked to from different sections of the presidential map and campaign finance data sections of the site.

**Comment by bmathesonFEC** [comment]
A first draft of the presidential map data help page is ready for review: https://fec-prod-proxy.app.cloud.gov/admin/pages/10806/edit/preview/

(@dorothyyeager, @kathycarothers, @djgarr, @PaulClark2, @AmyKort)

As noted in the previous comment, this resource page has three anchors:
1. Presidential map overview
2. Methodology and formulas
3. Downloadable presidential map data

The page is a new unpublished resource page, not a draft on the existing page. If we choose to move forward with this page we will have to setup a redirect.

**Comment by dorothyyeager** [comment]
I love the switch to the resource page template. Can help with the redirect when we're ready. I'm noticing a few small copy-editor type things so will send you an email with those items.

**Comment by bmathesonFEC** [comment]
Reviewed all of @dorothyyeager's feedback and incorporated it into the current draft. Thanks!

**Comment by dorothyyeager** [comment]
@PaulClark2 @AmyKort Were you good with the draft?

**Comment by PaulClark2** [comment]
@dorothyyeager @bmathesonFEC this looks good to me. Thank you for all your work on this help page.

**Comment by dorothyyeager** [comment]
The page is now live at https://www.fec.gov/campaign-finance-data/presidential-map-data/.

**Comment by dorothyyeager** [comment]
I've updated a redirect for an older page (http://www.fec.gov/press/mapHelp.shtml) and the previous page in custom template (https://www.fec.gov/campaign-finance-data/presidential-map-help/) to now point to the new page at https://www.fec.gov/campaign-finance-data/presidential-map-data/.

Work is complete, so closing this ticket.
