### ISSUE TITLE
Quality assurance for map

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3497]
### Summary

**What we are after:**
_We need to ensure the map complies with content guide, has no typos and works as intended._ 

Please add bugs and issues to this [document](https://docs.google.com/document/d/1CH5-W6QzVF7Zve2P3ttVPK9gdfVNm_x5NBY4gXoV9vQ/edit#heading=h.iwhjpzgyxkrj) 🔒 

We will likely need more than one person working on this. In addition to what is listed below in the related issues, we need to see what other areas we need to include in this quality assurance ticket. 

### Related issues

_List any relevant related issue(s)_
- #3522 
- #3496 
- #3544 

In progress: Presidential map in dev (see link in slack)

### Completion criteria
- [ ] Review by content team for content guide and typos, using the related issues as a place to double check (log any [findings in this document](https://docs.google.com/document/d/1CH5-W6QzVF7Zve2P3ttVPK9gdfVNm_x5NBY4gXoV9vQ/edit#heading=h.iwhjpzgyxkrj)).
- [ ] Test features to ensure they work as intended, using the related issues as a place to double check

### Future work

Open up followup tickets to fix anything found during this review

**Comment by dorothyyeager** [comment]
Calling all content team members: @kathycarothers @djgarr @bmathesonFEC - it's time for us to help test the presidential map. This is just an initial round of testing; there will be more.

Instructions for the first round of testing from @rfultz :  If you see something wrong with the data, content, or the general functionality (except state ‘zoom’), [please log that](https://docs.google.com/document/d/1CH5-W6QzVF7Zve2P3ttVPK9gdfVNm_x5NBY4gXoV9vQ/edit#heading=h.rax4ljvnrtg0). If it’s a layout issue, we’re still working on those.

**Comment by patphongs** [comment]
Also FYI, none of the links to the export files will work as our feature space does not have that mapped. So we'll want to only validate that the candidate ID is updating in the URL and/or that it generally looks like it's linked to the correct state.

**Comment by djgarr** [comment]
What's the link that we should be using to access the map? Can it be sent around?

**Comment by kathycarothers** [comment]
It is in Slack in the content channel @djgarr

**Comment by dorothyyeager** [comment]
First round of testing completed; comments logged. Content team is available to do any other testing needed or answer any questions about our comments.

**Comment by pkfec** [comment]
Testing is done. Closing this ticket.
