### ISSUE TITLE
Expand About this Data page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3498]
### Summary

**What we are after:**
_We need to look at the About this Data page at https://www.fec.gov/campaign-finance-data/about-campaign-finance-data/ and ensure it is explaining things fully to users._

### Related issues

_List any relevant related issue(s)_
- #3363 (Find About this Data a home)

### Completion criteria

_List action items that need to be done to complete this task. List in checklist formatting._
~- [ ] Add a link to the Presidential map "about page"~ Moving this into the ticket for that work.
- [x] Meet with @PaulClark2 and possibly Press/Public Records
- [ ] Expand this page so that it is a general introduction and landing page, and provides 
- [ ] Draft or move any sub-pages as needed (See these pages in Wagtail under Campaign Finance Data. For example, the receipts page, file format pages) etc.
- [ ] Review by @PaulClark2 before publishing
- [ ] Set up any redirects as needed after publishing and put in a testing ticket if needed
- [ ] Add any needed link to this page on a hard-coded page.

### Future work

- Front end work to update the hard-coded page that this page will be linked off -

**Comment by pkfec** [comment]
@PaulClark2 will follow up with @content-team about the methodology.

cc @dorothyyeager @bmathesonFEC

**Comment by dorothyyeager** [comment]
We will hold this for PI15 due to other priorities.

**Comment by dorothyyeager** [comment]
Reviewing all the associated pages now to re-familiarize myself.

**Comment by dorothyyeager** [comment]
After @PaulClark2 and I met, we realized this ticket is way too broadly written. We're going to scrap it and take baby steps, starting with drafting an "About disbursements" page. We also want to add "About this data" to some menus, and draft a page for "about loans and debts"-those will be covered in future tickets.

For now, closing this ticket and we'll start small(er) in https://github.com/fecgov/fec-cms/issues/4774.
