### ISSUE TITLE
Design homepage change to link to presidential map

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3500]
**What we're after:**
We're rebuilding the presidential data map on www.fec.gov and we need to create a pathway from the homepage to that presidential map. 

### Action items
- [x] Mockup design(s) for the homepage to link to the map visualization
- [x] Review with stakeholders
- [x] Make necessary changes and move to an implementation issue

### Completion criteria
- [x] Within this ticket, have a completed mock up design for front end to use to build out presidential map

**Comment by JonellaCulmer** [comment]
@AmyKort @PaulClark2 
Below please find the first draft for the homepage. Feel free to share with stakeholders as you see fit. Happy to explain my thinking further if/when that is necessary. 

This makes the Presidential map a prominent fixture on the homepage and also allows us to showcase other valuable content on the homepage, including the H4CC and legal resources. It should be big and bright enough to generate interest from new visitors as well as those who have been to our site before and know what they're looking for. 

![Homepage_Prezmap_addition](https://user-images.githubusercontent.com/31663028/73573299-070bd380-4441-11ea-9ad2-fd341171f3d3.png)

**Comment by AmyKort** [comment]
Thank you @JonellaCulmer !

**Comment by JonellaCulmer** [comment]
Slight change to the homepage mockup. Switched out the icon for the prez map, from a search icon to an ordered chart icon. 

<img width="1090" alt="Screen Shot 2020-02-01 at 12 25 46 PM" src="https://user-images.githubusercontent.com/31663028/73596171-011ffc00-44ee-11ea-9cfb-f835a89f7bbf.png">

**Comment by JonellaCulmer** [comment]
@dorothyyeager @kathycarothers @bmathesonFEC @djgarr Please let me know if you have any edits to the language used in the above mockup. 

cc: @AmyKort

**Comment by djgarr** [comment]
looks good to me

**Comment by patphongs** [comment]
Thank you @JonellaCulmer, I think this looks good. One question, will the different buckets on the homepage be flexible to linking to other important features on the site as well? What will be the content governance for the decision to change these links @AmyKort?

**Comment by dorothyyeager** [comment]
Thanks @JonellaCulmer! I like the direction you have gone in and as a sidenote, I really appreciate the heightened visibility of H4CC, which a lot of callers to the Information Division seem to not be able to find.

For the data map, isn't it just more than contributions raised? If yes, I'd match the language on https://www.fec.gov/data/browse-data/?tab=candidates and change description to read "Search presidential candidate data including money raised, money spent, cash on hand and debt."

I noticed for H4CC, you used the language from the intro sentence on the landing page, but not for legal resources. So I would recommend doing the same for legal resources and changing that description to "Explore relevant statutes, regulations, Commission actions and court cases" to match the sentence in the heading on https://www.fec.gov/legal-resources/.

**Comment by kathycarothers** [comment]
@JonellaCulmer I would agree with Dorothy's comment about the map being more than contributions raised. I would go with her descriptions.

**Comment by JonellaCulmer** [comment]
@AmyKort @PaulClark2 Any objections to what @dorothyyeager suggested in her comment above?

**Comment by AmyKort** [comment]
I agree with @dorothyyeager .

**Comment by PaulClark2** [comment]
I agree with @AmyKort and @dorothyyeager

**Comment by JonellaCulmer** [comment]
Updated section based on content changes: 

<img width="844" alt="Screen Shot 2020-02-05 at 7 49 31 PM" src="https://user-images.githubusercontent.com/31663028/73896325-a7526580-4850-11ea-9b4f-4e825267f604.png">

**Comment by JonellaCulmer** [comment]
Closing in favor of this implementation issue: https://github.com/fecgov/fec-cms/issues/3544
