### ISSUE TITLE
Define chart components to make for presidential map

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3502]
**What we're after:**
While the front-end team works to build out components for the presidential map, design needs to define what components are necessary and where they will live on a 100% width page. 

Areas to consider:
- Account for bubbles in design
- Navigation between candidates and all candidates on national map and state map
- Navigation between candidates and all candidates on national map and state map
- Navigation to CSV/zip files (MVP, we will link each state by default, without adding additional logic to pare down the list)
- The appearance/on-click changes when a user moves between candidates or all candidates or parties
- Navigation to other sections of the site
- Consider how to show coverage dates for each individual candidate

### Chart components from classic
Below are the components we discussed are MVPs for the presidential map
![Screen Shot 2020-01-31 at 9 59 51 AM](https://user-images.githubusercontent.com/12799132/73552057-8a173480-4415-11ea-8895-e33df746079d.png)

![Screen Shot 2020-01-31 at 10 07 15 AM](https://user-images.githubusercontent.com/12799132/73551670-d44be600-4414-11ea-9d95-9127a1e0145c.png)

![Screen Shot 2020-01-31 at 10 23 21 AM](https://user-images.githubusercontent.com/12799132/73552302-f85bf700-4415-11ea-9cc4-c098800c6a35.png)

### Related issues
- #3500 
- #3501 

### Action items
- [x] Mockup designs for presidential map components and layout
- [x] Review with stakeholders and website team
- [x] Make any necessary changes based on the review and update any implementation tickets with the "final" designs

### Completion criteria

- [ ] Insert presidential map layout and design in this ticket. Inform front-end team

**Comment by JonellaCulmer** [comment]
Wanted to confirm that all the data that's currently available in the accordions is accounted for in the design. 

Based on the components outlined in the original comment for this issue, we have 4 buttons that will need to be included. The buttons will function in the same way, regardless of whether a user is looking at All candidates, Party candidates, or an individual candidate.
- Export Contributor data (Export raising data)
- Export Expenditure data (Export spending data)
- Export [State] Contributor (Export [State] raising data)
- Report summary data (Export report summary data)

Below I've tried to map out how/where all of the information in the accordions will be available in the new presidential map. All but 3 datasets appear to be covered by those 4 buttons. Those 3 datasets are highlighted with pink boxes. 
<img width="1126" alt="Screen Shot 2020-02-05 at 9 46 45 PM" src="https://user-images.githubusercontent.com/31663028/73901731-ab3ab380-4861-11ea-8f89-d1d0a951248e.png">

@PaulClark2 @lbeaufort @patphongs Please let me know if I'm missing anything or if any of this is incorrect. 

@AmyKort We've talked about keeping the accordions up for a time after the map is published and allowing for an overlap. How do you feel about leaving up only those things that the map cannot account for at this time?

**Comment by JonellaCulmer** [comment]
### National view of bubble map, all candidates
![National view - bubbles](https://user-images.githubusercontent.com/31663028/74055921-f0b8c700-49ae-11ea-9c8d-c4f7bfce159b.jpg)

### National view of bubble map, all dems
![National view - bubbles - Dems](https://user-images.githubusercontent.com/31663028/74055920-f0203080-49ae-11ea-9250-3e516e660135.jpg)

### National view of gradient map, with accordion breakouts
![National view - accordions](https://user-images.githubusercontent.com/31663028/74055919-f0203080-49ae-11ea-96b3-def7e16c8fa0.jpg)

### National view with raising export 
![National view - export dropdown](https://user-images.githubusercontent.com/31663028/74055922-f0b8c700-49ae-11ea-99c2-84be9987f60a.jpg)

### State view of florida
![State view](https://user-images.githubusercontent.com/31663028/74055924-f0b8c700-49ae-11ea-9d46-453e1dc9887b.jpg)

**Comment by JonellaCulmer** [comment]
### Mobile view

![Map_mobile](https://user-images.githubusercontent.com/31663028/74172490-5353d200-4bfe-11ea-947c-715b9f039f8d.png)

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issues listed above.

**Comment by PaulClark2** [comment]
@JonellaCulmer @AmyKort question about the map title: "Where presidential candidates raise and spend." All of the location information we display is about raising. You only get location information about disbursements if you download the disbursements file.
