### ISSUE TITLE
Create generic full width page template

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3503]
### Summary

**What we're after:**
_The presidential map will be built on a full width page jinja template within the data section. The template will be similar to Wagtail full width templates, but without the reporting dates javascript and stylings. Also this does not need to be tied to Wagtail._

URL for the map: https://www.fec.gov/data/candidates/president/presidential-map/

### Completion criteria

- [x] Make the data full width template exist for use
- [x] Include `You may also like` section at the bottom of this template

**Comment by johnnyporkchops** [comment]
Paired with @rfultz on this. Trying to resolve issues with making a re-usable/generic  Jinja template for full-width, so for now we are  using either  election-lookup.jinja or raisingbythenumbers.jinja templates as starting point.

**Comment by johnnyporkchops** [comment]
- The template, re-usable for other full-width /data pages can pull in a CSS file  with the `page_specific_css` variable name from a view.
`<link rel="stylesheet" type="text/css" href="{{ asset_for_css(page_specific_css) }}" />`
- You might also like section has been added
