### ISSUE TITLE
Enhancements to e-filing form on fec.gov

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#3505]
### Summary
Make usability and design enhancements to e-filing search page here: 
https://www.fec.gov/fec-electronic-filing-report-retrieval/

- [x] Make sure design is in keeping with fec.gov styles for forms
- [x] make sure it is fully responsive
- [x]  Add language to distinguish this "legacy search" from other e-filing searches both on form and on browse-data/filings-reports tab from where it is linked

Possible Enhancements like:
 - [x]    Date picker for convenience and to control correct date range and format (May be done in first iteration in Wagtail)
 - [ ]  Typeahead/autofill for committee ID (Should be done with a PR and code commits)

**related issue:** https://github.com/fecgov/fec-cms/issues/3493
**related PR :** https://github.com/fecgov/fec-cms/pull/3499

**Comment by JonellaCulmer** [comment]
We are inconsistent with our highlighting of "All", so that adds a bit of uncertainty about how each field works, or should work. Should we default to All for all three fields? Hows does that impact the search?
<img width="723" alt="Screen Shot 2020-02-01 at 12 14 15 PM" src="https://user-images.githubusercontent.com/31663028/73596013-683cb100-44ec-11ea-963c-7041e30bfaa8.png">

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Here are some other thoughts about possible page enhancements:

- Improve the title and sentence case, if appropriate: "FEC Electronic Filing Report Retrieval" Possible changes: Electronic filing reports search with alternate search options. We're already on the FEC website, so I don't think we need to include that.
- Add a description at the top of the page that clarifies what makes this search different from tthe other datatable search. This is mainly the filtering options, right?
- Improve the labeling for some of the filters, mockup below. You can compare to the labeling in my previous comment.
<img width="846" alt="Screen Shot 2020-02-01 at 6 21 01 PM" src="https://user-images.githubusercontent.com/31663028/73600551-abfcde00-451f-11ea-9606-6a35de8cb8f4.png">

- Remove hyperlink from the word "Notice" at the bottom of the form. Can we add a sentence that says: "Learn more about this restriction." and hyperlink that instead?

**Comment by johnnyporkchops** [comment]
@jonella, the highlighting of "all" for the state field was based on the original form which does that but not sure why.

<img width="739" alt="Screen Shot 2020-02-01 at 10 12 11 PM" src="https://user-images.githubusercontent.com/5572856/73602319-f2623500-453f-11ea-8428-0eb4da27cd9a.png">

**Comment by johnnyporkchops** [comment]
@JonellaCulmer These changes have been made, except the title and adding intro language.

**Comment by JonellaCulmer** [comment]
@dorothyyeager @bmathesonFEC @PaulClark2 I think we need a description for the top of the page to explain what all this search does and possibly what makes it different from the other electronic filing searches we have. As well as a better name for the page itself. 

Any thoughts?
cc: @johnnyporkchops

**Comment by dorothyyeager** [comment]
I have never used this tool, so am happy to defer to the others. My suggestion for the page name would be **_Electronic filing report search with additional filters_** .

For the intro text, I'd suggest _"Access and download electronically filed FEC reports from 1997 to the present using a variety of filters to better tailor your search. Sign up for the FEC Electronic Filing RSS Feed to receive notifications of availability of newly filed reports."_

**Comment by PaulClark2** [comment]
@dorothyyeager I like it. One addition to your intro text, `FEC Notify`, _"Access and download electronically filed FEC reports from 1997 to the present using a variety of filters to better tailor your search. Sign up for FEC Notify or the FEC Electronic Filing RSS Feed to receive notifications of availability of newly filed reports."_

I assume we will link to both FEC Notify [https://fecnotify.fec.gov/fecnotify/login/] and RSS [https://efilingapps.fec.gov/rss/display?input}

**Comment by johnnyporkchops** [comment]
These changes have been made:
https://www.fec.gov/fec-electronic-filing-report-retrieval/

**Comment by johnnyporkchops** [comment]
FYI- Multiple select boxes are buggy in IOS, they do not show the options in the box, however, they are selectable from the select popup once you click the box. Looking for a workaround.

**Comment by johnnyporkchops** [comment]
Closing in favor of:
https://github.com/fecgov/fec-cms/issues/3650
