### ISSUE TITLE
Update presidential candidate downloads [Due 2/1/2020]

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#3511]
### Summary

**What we're after:**
We need to update the candidate list to include those candidates that meet our $100,000 threshold. We need to update `CONTRIBUTION TOTALS BY STATE` to `INDIVIDUAL CONTRIBUTIONS BY STATE` in each accordion. 

![image](https://user-images.githubusercontent.com/11817734/73556483-87204200-441d-11ea-8a90-aa2f38ace6ce.png)

![image](https://user-images.githubusercontent.com/11817734/73574656-3ff97780-4444-11ea-873c-297aa52a352d.png)

### Completion criteria
- [ ] Update candidate list
- [x] Update section heading in each accordion: `CONTRIBUTION TOTALS BY STATE` to `INDIVIDUAL CONTRIBUTIONS BY STATE`
- [x] Update OVERALL CANDIDATE SUMMARY links from `2020_overall_summary_now.csv` to `2020_overall_summary.csv` for each election year
- [x] bold `other than the candidate` in each accordion
-  [ ] Deploy HOTFIX

**Comment by patphongs** [comment]
This hotfix has been deployed, closing issue
