### ISSUE TITLE
Filters not working.

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#3512]
@jbucelato commented on [Fri Jan 31 2020](https://github.com/fecgov/FEC/issues/9498)

There is a candidate missing from the list, Tonya Millis, https://www.fec.gov/data/candidates/?party=LIB&name=IN&is_active_candidate=true. Also, I selected a specific state and I getting candidates from other states,
The candidate does appear correctly here, https://www.fec.gov/data/candidates/house/?election_year=2020&election_full=True&party=LIB&name=IN&is_active_candidate=true, however, candidates from other states appear as well.

Thanks for looking into this.

Jason

---

@PaulClark2 commented on [Fri Jan 31 2020](https://github.com/fecgov/FEC/issues/9498#issuecomment-580870110)

The state filter seems to be applying a name filter instead of a state filter: https://www.fec.gov/data/candidates/?name=IN 

![image](https://user-images.githubusercontent.com/11817734/73566708-82b25400-4432-11ea-96b6-454f15844948.png)

The state filter seems to be applying a name filter instead of a state filter:
https://www.fec.gov/data/candidates/house/?election_year=2020&election_full=True&party=LIB&name=IN&is_active_candidate=true

![image](https://user-images.githubusercontent.com/11817734/73567007-6531ba00-4433-11ea-9a6a-7ad5da179ec0.png)

**Comment by patphongs** [comment]
FYI, fix is coming and will be deployed tomorrow 2/1/2020: https://github.com/fecgov/fec-cms/issues/3511

**Comment by patphongs** [comment]
@jbucelato thank you for reporting this issue. This has been patched and the states filter should be functioning as expected again. 

https://www.fec.gov/data/candidates/?party=LIB&state=IN&is_active_candidate=true

https://www.fec.gov/data/candidates/house/?election_year=2020&election_full=True&party=LIB&state=IN&is_active_candidate=true
