### ISSUE TITLE
Presidential map UI component: Display state level UI

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3515]
### Summary

**What we're after:**
_Display all candidates or selected candidate for a specific state._

![Screen Shot 2020-01-31 at 10 07 15 AM](https://user-images.githubusercontent.com/12799132/73551670-d44be600-4414-11ea-9d95-9127a1e0145c.png)

### Designs
https://github.com/fecgov/fec-cms/issues/3502

### Completion criteria
- [ ] State outline exists
- [x] Capability to have selected "all candidates", "party", or specific candidate in the candidate list
- [x] Display export button based on state and "all candidates", "party", or specific candidate in the candidate list

**Comment by johnnyporkchops** [comment]
The data display and export button functionality has been done. @rfultz Is working on the visual,  single-state display in D3. 
Related ticket: Issue #3517
