### ISSUE TITLE
Presidential map UI component: Display export data UI

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3516]
### Summary

**What we're after:**
_Display specific exportable bulk downloads data based on all candidates, party, or selected individual candidate._

![Screen Shot 2020-01-31 at 10 23 21 AM](https://user-images.githubusercontent.com/12799132/73552302-f85bf700-4415-11ea-9cc4-c098800c6a35.png)

### Designs
https://github.com/fecgov/fec-cms/issues/3502

### Completion criteria

- [ ] Based on all candidates, party, or selected individual candidate, show contributor data
- [ ] Based on all candidates, party, or selected individual candidate, show expenditure data
- [ ] Based on all candidates, party, or selected individual candidate, show report summary data (3P)

**Comment by johnnyporkchops** [comment]
The bulk downloads area has been added and works for raising data. Still need to refine some of the other download options based on designs in #3502
