### ISSUE TITLE
Presidential map UI component: Tie individual state clicks to state level display

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3517]
### Summary

**What we're after:**
_The presidential map interface needs to tie to the individual state display when a state is clicked._

### Designs
https://github.com/fecgov/fec-cms/issues/3502

### Completion criteria

- [ ] When a state is clicked, it will show the correct selected state's display

**Comment by rfultz** [comment]
Circles are in and working. Now working on zoom calculations
