### ISSUE TITLE
Need better state list for presidential downloads

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#3519]
### Summary

The list of states for each candidate in the `individual presidential map candidate` accordion is inaccurate.  Currently we use an API endpoint that relies on processed data. The presidential download files do not use processed data.  

### Expected Behavior

Expected to get an accurate list of states for each candidate. For example Deval Patrick has no states listed under his name. 

![image](https://user-images.githubusercontent.com/11817734/73612446-dbf8bf80-45b9-11ea-8c0d-e47d84b308a4.png)

The correct list is: 
AK  AL  AR  AZ  CA  CO  CT  DC  DE  FL  GA  HI  IA  ID  IL  IN  KS  KY  LA  MA  MD  ME  MI  MN  MO  MS  MT  NC  ND  NE  NH  NJ  NM  NV  NY  OH  OK  OR  PA  RI  SC  SD  TN  TX  UT  VA  VT  WA  WI  WV  WY  
 
See: `www.fec.gov/files/bulk-downloads/index.html?prefix=bulk-downloads/Presidential_Map/2020/P00014407/`

### Actual Behavior

No states are listed.
![image](https://user-images.githubusercontent.com/11817734/73612446-dbf8bf80-45b9-11ea-8c0d-e47d84b308a4.png)

### Frequency

- This is an ongoing, predictable issue
- This happens because we are using an API endpoint that only has processed data. 

###Completion criteria
- [ ] Display correct list of states for each candidate
- [ ] Use static list of states for all individual candidates, All candidates, All Republicans and All Democrats
`AL | AK | AZ | AR | CA | CO | CT | DE | DC | FL | GA | HI | ID | IL | IN | IA | KS | KY | LA | ME | MD | MA | MI | MN | MS | MO | MT | NE | NV | NH | NJ | NM | NY | NC | ND | OH | OK | OR | PA | RI | SC | SD | TN | TX | UT | VT | VA | WA | WV | WI | WY | Other`

**Comment by patphongs** [comment]
Fix has been deployed #3520
