### ISSUE TITLE
Design placement of link to presidential map on the browse data/candidates page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3521]
**What we're after:**
We've identified locations to link the new Presidential map page. One of those places is the candidates browse data page, this change requires development work and a redesign to accommodate for the new feature. 

### Related issues
- #3501 Decide where the presidential map will live

### Completion criteria
- [x] Mockup change for candidates browse data page to accommodate the new presidential map
- [x] Update implementation issue with mockup (https://github.com/fecgov/fec-cms/issues/3522)

**Comment by JonellaCulmer** [comment]
@AmyKort @PaulClark2 @patphongs 

First draft for the Candidate browse data page. 
This includes two cards. One directly to the map and another which we can link to the Presidential 2020 election profile page. It doesn't have to stay there permanently, but that makes it something we have to remember to go in and remove at a time we deem appropriate.

I've also included the accordion with everything removed that the map accomplishes, which is most of it. And only one accordion remains. 

![Screen Shot 2020-02-11 at 10 31 41 AM](https://user-images.githubusercontent.com/31663028/74251827-b6a33a00-4cba-11ea-907c-ea9a6e0567fb.png)

**Comment by JonellaCulmer** [comment]
@AmyKort @PaulClark2 Any objections to removing everything in the accordions except for the few things the map can't accommodate? See the above mockup. ^-^

**Comment by AmyKort** [comment]
That sounds great to me. Are you looking for copy edits on the mock-up?

**Comment by JonellaCulmer** [comment]
> Are you looking for copy edits on the mock-up?

@AmyKort Yes, happy to have them. 

Looping in @dorothyyeager @kathycarothers @bmathesonFEC

**Comment by AmyKort** [comment]
Great! I don't have edits myself, but it will be great to have the content team take a look.

**Comment by dorothyyeager** [comment]
No edits from me. Looks good, @JonellaCulmer.

**Comment by JonellaCulmer** [comment]
@PaulClark2 Do we still want to bold, "**...other than the candidate.**"

**Comment by PaulClark2** [comment]
@JonellaCulmer I think so. I think we are trying to highlight that candidate contributions and candidate loans don't count when we are considering the $100,000 threshold.

**Comment by JonellaCulmer** [comment]
@dorothyyeager @AmyKort I've updated the mockup to include the title for the map we discussed in slack. I also changed the language from "All presidential map candidates" in the accordion. 

Let me know if you have any thoughts. We really need to nail down a name for the map. 


<img width="707" alt="Screen Shot 2020-02-18 at 9 26 50 AM" src="https://user-images.githubusercontent.com/31663028/74744870-f6c16a00-5230-11ea-855a-e33d71267a50.png">

cc: @PaulClark2

**Comment by dorothyyeager** [comment]
@JonellaCulmer This seems OK to me. Should we run it by Press Office since I think they refer people to this data more than any other office? @AmyKort @PaulClark2

**Comment by AmyKort** [comment]
I think it looks great. @PaulClark2 Do you think we need to run this past Press? Are you okay with the title?

**Comment by PaulClark2** [comment]
@AmyKort I asked Press about this.

**Comment by PaulClark2** [comment]
@JonellaCulmer @AmyKort this looks good to me. Press thinks it looks good.

**Comment by JonellaCulmer** [comment]
closing in favor of implementation issue: https://github.com/fecgov/fec-cms/issues/3522
