### ISSUE TITLE
Make links to presidential map

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3522]
**What we're after:**
In addition to the homepage, we are linking to the new presidential map page from two places, they are listed below. 

New links: 
Hard-coded change - Candidate Browse data page (https://www.fec.gov/data/browse-data/?tab=candidates)
![Screen Shot 2020-03-05 at 11 19 58 AM](https://user-images.githubusercontent.com/31663028/76001751-92aad100-5ed3-11ea-9d5b-4ffa465b488d.png)

Wagtail edit - Candidates (Public records: https://www.fec.gov/introduction-campaign-finance/how-to-research-public-records/candidates/). Need to confirm exact placement with Public Records office. Suggested placement in one of two places: 
<img width="1040" alt="Screen Shot 2020-02-03 at 3 46 10 PM" src="https://user-images.githubusercontent.com/31663028/73689481-5568de80-469c-11ea-8df9-f20c2bdd5ee2.png">

### Related issues
- #3501 
- #3521 

### Completion criteria
- [x] Share concept/idea with Public records for confirmation
- [ ] Make hard-coded change to add links to presidential map
- [ ] Notify Public records when we're ready to publish the map and provide them with the link to the page for their office to post

**Comment by dorothyyeager** [comment]
After speaking with @JonellaCulmer, I went ahead and reached out to Public Records to let them know where we're thinking of placing the Wagtail link. Will update ticket when I hear back.

**Comment by dorothyyeager** [comment]
Public Records is good with the plan to place a link on that page, in the main column under "Lists..." They'll take care of the Wagtail update, so we'll want to coordinate with them when the map is ready for release.

**Comment by johnnyporkchops** [comment]
Intro @JonellaCulmer , Where does the icon  for "Compare candidates in the 2020 election" link to ?

**Comment by JonellaCulmer** [comment]
@johnnyporkchops It should link to the 2020 presidential election profile page: https://www.fec.gov/data/elections/president/2020/
