### ISSUE TITLE
Suggested search result points to a deleted H4CC page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3523]
### Summary

**What we're after:**
_In #3376, @johnnyporkchops was unable to take deleted pages out of the global search results. However, one of those pages actually shows up as a "Suggested" page for the term "contribution limits."  While we can't take the deleted page out of global search, it would be desirable to change the "Suggested" page to the current page that covers this topic._

### Screenshot

<img width="509" alt="Capture" src="https://user-images.githubusercontent.com/24437369/73780205-084c4180-475c-11ea-98f5-3f8b4f7511e0.PNG">

### Related issues

- #3376 

### Completion criteria

- [ ] Change the "suggested" result for a search for "contribution limits" to point to current page at https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/contribution-limits/

### Future work
- #3524 Figure out how to remove deleted pages from global search results.

**Comment by JonellaCulmer** [comment]
This work is being handled in https://github.com/fecgov/fec-cms/issues/3524.
