### ISSUE TITLE
Gather and prep other documents needed for Policy/Guidance page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3527]
### Summary

**What we are after:**
As a user, I need PDFs that are accessible. As an agency, we need to ensure that PDFs are accessible and searchable and comply with EO 13892.

### Background
Executive order 13892 requires the FEC to create a searchable page that contains the agency's guidance. OGC has given us a [list](https://docs.google.com/document/d/11Cl-nuGtiTkl7rormQoWYxF3vuhiDi8fCsjV7HrPlvs/edit?usp=sharing) of what should be included. This ticket is to make sure we have everything and it's all accessible.

### Related issues

- #3488 

### Completion criteria

- [x] Using OGC's list, note of where everything on it lives now
- [ ] Update any remaining PDFs for accessibility (Forms, Guides, misc. guidance etc.)

### Future Work
- [ ] Decide what to do with supporting documentation (comments and drafts that lived on the policy page; in some cases, these are meeting documents).

**Comment by kathycarothers** [comment]
I have gone through the document and noted two comments for the Policy Statements. 

Jim is working on the Guides to make them accessible. We are testing one way on the Party Guide to see if that would be the most efficient. We are working directly with the pdf. 

In regards to the forms that is a different story. Jim needs to think on this for a bit because of the templates that were used to build the forms. 

I have noted this in the document too.

**Comment by dorothyyeager** [comment]
I updated @kathycarothers comments on the document - in two cases, docs needed to be saved to shared folder so took care of that. In another, it was there but had been labeled in a different way on the website and in the folder. As Kathy noted, we need to make some fixes to the Guides and Forms (both of which live in the CMS) and will need @jjonesfec's help for that.

One more thing for @AmyKort @patphongs to noodle on - Post-2011, we are unable to alter Federal Register notices that came from GPO for accessibility and they don't pass the full check in Adobe Acrobat. Jim has reached out to his contact there to ask why they don't.

**Comment by jjonesfec** [comment]
I've started the process of retrofitting the _Guide_ PDFs for accessibility. The template they use was created specifically for print, so some modification of it will be necessary. The process should be fairly quick and straightforward. I've begun the retrofit and will update as I progress.

Forms, however, are different and will require more research.

**Comment by dorothyyeager** [comment]
Status update: Making the forms and Guides accessible is proving challenging. They were designed as publications for print, not digital. Jim is working hard on it now. The remaining documents have been gathered and are ready for the next steps.

**Comment by dorothyyeager** [comment]
The work to make the forms and Guides accessible will continue into 11.5.

**Comment by dorothyyeager** [comment]
Updating before I leave for the conference. The only thing left in this ticket is making the forms and Guides accessible. @jjonesfec is working on that. Since it is work that takes time, it may be best to close this ticket with the understanding that Info Div will have the forms and guides ready to go when we are ready to go with the new Policy/Guidance page.

**Comment by dorothyyeager** [comment]
Closing this ticket as noted above. We'll have the guides and forms ready to go when needed.
