### ISSUE TITLE
AO results discrepancy between legal search results and link to show results

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3535]
### Summary 

_Global legal search results does not yield the same results when clicking on the AO search when clicking the `All results` button. This is due to the fact that the AO search page automatically applies the "final opinion" filter immediately upon going to the AO search page._

### Example
Search by §30123 keyword

https://www.fec.gov/data/legal/search/?search_type=all&search=%C2%A730123
<img width="1249" alt="Screen Shot 2020-02-10 at 12 32 19 PM" src="https://user-images.githubusercontent.com/12799132/74174336-c01c9b80-4c01-11ea-8064-a1cc868349f2.png">

https://www.fec.gov/data/legal/search/advisory-opinions/?type=advisory_opinions&search=%C2%A730123&search_type=advisory_opinions&q=%C2%A730123&ao_category=F
<img width="1266" alt="Screen Shot 2020-02-10 at 12 33 05 PM" src="https://user-images.githubusercontent.com/12799132/74174335-c01c9b80-4c01-11ea-9513-18a88d9e8382.png">

**Comment by JonellaCulmer** [comment]
The results you see on the datatable should match the results a user receives after using the global legal search. I recommend we remove the "Final opinion" as a default filter and only rely on the filtering (aka keyword) that is applied in the global search. 

"Final opinion" can remain as a default applied filter if coming to the search directly. 
Such as from these places: 
https://www.fec.gov/data/legal/advisory-opinions/ (via "Advanced search" and "Explore all advisory opinions")
https://www.fec.gov/legal-resources/ (Selecting "Advisory opinions" under "Advanced searches"

**Comment by patphongs** [comment]
@JonellaCulmer The final opinion filter may have been a requested default due to the amount of AO results you would get if you don't have final opinion defaulted. @AmyKort Do you recall this being implemented because of this?

**Comment by AmyKort** [comment]
That's what I remember, @patphongs

**Comment by patphongs** [comment]
Clarification for this ticket, we only want to remove the final opinion filter when coming from the global legal search results "All results" page. Final opinion will still remain as a default upon initialization if you go to the AO search datatable page itself.

**Comment by JonellaCulmer** [comment]
Closing in favor of https://github.com/fecgov/fec-cms/issues/4044
