### ISSUE TITLE
Update IE methodology

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#3537]
**What we are after**
Clearer language to explain both the web interaction and the download file. 

Consider changing the website filter option from “current version” to “unique transactions.”  (“Unique” is consistent with a filter option the Receipts page of FEC.gov.) Using “current version” as a website filter is not in fact accurate since that option will display both current version and unknown version transactions.

**Related issues**
- https://github.com/fecgov/fec-cms/issues/3545
- https://github.com/fecgov/fec-cms/issues/3548

**Suggested language**

> **Terminology**:
> The following version indicators and transaction codes are assigned to each 24- and 48-Hour Independent Expenditure Report and to the transactions contained in that report.
> 
> **Current version**: Represents the most recent version of a filer’s independent expenditure report. Transactions contained in the current version of the report are indicated with “t” in Column BS of the export file.
> 
> **Past version**: Represents a previous version of a filer’s independent expenditure report after a subsequent amended report has been filed. Transactions contained in the past version of the report are indicated with “f” in Column BS of the export file.
>
> **Unknown version**: Represents a filing that did not identify whether it was a new or amended version. For example, this may occur when filers attempt to amend their original report but inadvertently submit the amendment as a new filing or submit a new filing as an amendment. Transactions contained in the unknown version of the report are indicated with “null” in Column BS of the export file.
> 
> **Which option should I select**?
> **Unique transactions** 
> With the selection of the "unique transactions" option, the website will display transactions reported on the current and unknown report versions of a 24- or 48-Hour Report of Independent Expenditures. Transactions disclosed in the most recent version of a report will appear. Users must make judgements on any transactions with the version category “unknown” that are presented in the data set.
> 
> **All transactions**
> When the "unique transactions" option is not selected, the website will display transactions reported on the past and unknown report versions of a 24- or 48-Hour Report of Independent Expenditures. Transactions reported on all original and amended filings will be displayed. Users must make judgements on any transactions with the version category “unknown” that are presented in the data set.
>

**Comment by JonellaCulmer** [comment]
@dorothyyeager, @kathycarothers and I are pairing on the language and design for the filter.

**Comment by dorothyyeager** [comment]
We talked about the use of the word "unique" and are not sure that will accurately capture what they're looking for. Unique means "singular or special" and brings that connotation. Also, it seems like the paragraphs above the "What should I select" text adequately describe the options they are choosing between. Plus there's no option to actually choose "All transactions" so this extra description was a bit confusing. 

We'd like to recommend expanding the text on the selection instead to "current and unknown versions" which is both shorter and more accurately presents the users' options. @JonellaCulmer is mocking up our idea.

**Comment by JonellaCulmer** [comment]
@dorothyyeager @kathycarothers @PaulClark2 

Possible design solution for the filter panel. This uses a condensed version of the old tooltip language we had for testing that explains how the filter works. 

![Screen Shot 2020-02-11 at 3 42 50 PM](https://user-images.githubusercontent.com/31663028/74277241-2e865a00-4ce5-11ea-8203-37db140eac83.png)

**Comment by patphongs** [comment]
> Possible design solution for the filter panel. This uses a condensed version of the old tooltip language we had for testing that explains how the filter works.

It's my understanding that you will only get past and unknown versions when this is unchecked. When current version is checked, you will only see current versions.

@PaulClark2 I went over the API logic with @JonellaCulmer @hcaofec @fec-jli @fecjjeng and they helped me document the logic for both processed and raw IE data here: https://github.com/fecgov/openFEC/issues/4202#issuecomment-584846209. This of course may add complexities to explaining the IE version methodology for both processed and raw data.

**Comment by JonellaCulmer** [comment]
> It's my understanding that you will only get past and unknown versions when this is unchecked. When current version is checked, you will only see current versions.

That is not my understanding. If checked, the user will see current and unknown. If unchecked, the user will see current, unknown and past versions. 

cc: @PaulClark2

**Comment by patphongs** [comment]
@JonellaCulmer Ok, looks like we want to pass multiple most_recent values at once according to #3548. I am blocked by the API right now, it won’t allow me to call multiple values or null values. I commented in that ticket my blocker.

**Comment by JonellaCulmer** [comment]
@PaulClark2 @dorothyyeager @patphongs @fecjjeng My attempt at an updated methodology is below:

The following version indicators and transaction codes are assigned to each 24- and 48-Hour Independent Expenditure Report and to the transactions contained in that report.

**Current version:** Represents the most recent version of a filer’s independent expenditure report. Transactions contained in the current version of the report are indicated with “t” in Column BS of the export file.

**Past version:** Represents a previous version of a filer’s independent expenditure report after a subsequent amended report has been filed. Transactions contained in the past version of the report are indicated with “f” in Column BS of the export file.

**Unknown version:** Represents a filing that did not identify whether it was a new or amended version. For example, this may occur when filers attempt to amend their original report but inadvertently submit the amendment as a new filing or submit a new filing as an amendment. Transactions contained in the unknown version of the report are indicated with “unknown” in Column BS of the export file. Flagging this part for @PaulClark2 @fecjjeng Are we changing it from null to unknown?

**Using the Version filter**

**For Processed 24- and 48-hour reports, Raw 24- and 48-hour reports, Raw Regularly scheduled reports:**
When you filter by current version, the website will display "current" and "unknown" versions of independent expenditure transactions. This can include original and amended filings. Users must make judgments on any transactions with the version category “unknown” that are presented in the data set.

When you don’t filter by current version, the website will display all versions, current, past and unknown, of independent expenditure transactions. Transactions reported on all original and all amended filings will be displayed. Users must make judgments on any transactions with the version category “unknown” that are presented in the data set.

**For Processed Regularly scheduled reports:**
This data does not have versioning information associated with it. All transactions are shown as the current version and are indicated with “t” in Column BS of the export file.

**Comment by dorothyyeager** [comment]
This seems OK to me. It explains the users' options clearly as well as the results they can expect when they select an option.

**Comment by patphongs** [comment]
Thanks @JonellaCulmer, I have incorporated this draft copy into this methodology PR: https://github.com/fecgov/fec-cms/pull/3552/files#diff-be752762611de2971d77a6e2aaa9c625R21-R30. It can be updated if there are any changes.

**Comment by PaulClark2** [comment]
This looks good to me. @JonellaCulmer I'm not sure about your question. Let me check.

**Comment by PaulClark2** [comment]
> Unknown version: Represents a filing that did not identify whether it was a new or amended version. For example, this may occur when filers attempt to amend their original report but inadvertently submit the amendment as a new filing or submit a new filing as an amendment. Transactions contained in the unknown version of the report are indicated with “unknown” in Column BS of the export file. Flagging this part for @PaulClark2 @fecjjeng Are we changing it from null to unknown?

should be updated to: 
Unknown version: Represents a filing that did not identify whether it was a new or amended version. For example, this may occur when filers attempt to amend their original report but inadvertently submit the amendment as a new filing or submit a new filing as an amendment. Transactions contained in the unknown version of the report are indicated with a null value in Column BS of the export file.

@JonellaCulmer can you confirm my edit is correct?

**Comment by JonellaCulmer** [comment]
@PaulClark2 Looks good to me. 

And I just check the column name. The column in the export is different for Processed and Raw. Processed it looks like the most_recent column is BS, but Raw is AX.

**Comment by PaulClark2** [comment]
@JonellaCulmer what about this: 

The following version indicators and transaction codes are assigned to each 24- and 48-Hour Independent Expenditure Report and to the transactions contained in that report.

**Current version**: Represents the most recent version of a filer’s independent expenditure report. Transactions contained in the current version of the report are indicated with “t” in Column BS in the processed data export file and Column AX in the raw data export file.
Past version: Represents a previous version of a filer’s independent expenditure report after a subsequent amended report has been filed. Transactions contained in the past version of the report are indicated with “f” in Column BS in the processed data export file and Column AX in the raw data export file.

**Unknown version**: Represents a filing that did not identify whether it was a new or amended version. For example, this may occur when filers attempt to amend their original report but inadvertently submit the amendment as a new filing or submit a new filing as an amendment. Transactions contained in the unknown version of the report are indicated with a null value in Column BS in the processed data export file and Column AX in the raw data export file.

**Using the Version filter**
**For Processed 24- and 48-hour reports, Raw 24- and 48-hour reports, Raw Regularly scheduled reports**:
When you filter by current version, the website will display "current" and "unknown" versions of independent expenditure transactions. This can include original and amended filings. Users must make judgments on any transactions with the version category “unknown” that are presented in the data set.

When you don’t filter by current version, the website will display all versions, current, past and unknown, of independent expenditure transactions. Transactions reported on all original and all amended filings will be displayed. Users must make judgments on any transactions with the version category “unknown” that are presented in the data set.

**For Processed Regularly scheduled reports**:
This data does not have versioning information associated with it. All transactions are shown as the current version and are indicated with “t” in Column BS in the processed data export file and Column AX in the raw data export file.

**Comment by JonellaCulmer** [comment]
@PaulClark2 Looks great!

**Comment by patphongs** [comment]
@PaulClark2 @JonellaCulmer Latest revisions have been made to match the latest updates here: https://github.com/fecgov/fec-cms/issues/3537#issuecomment-586411950

**Comment by PaulClark2** [comment]
@patphongs @JonellaCulmer I noticed two corrections that need to be made to the methodology language. I'll describe the change here and then post the updated language in the next comment. 

`When you filter by current version,` should be something like `When you filter by "current and unknown versions"`. This way the methodology language matches the filter box language. 

The last paragraph references a raw data export file. The processed data doesn't have raw data export file. 

@JonellaCulmer I didn't ask about the language above the checkbox. I can or we can just go live as is and update it next sprint.

**Comment by PaulClark2** [comment]
@patphongs sorry about the last minute update


The following version indicators and transaction codes are assigned to each 24- and 48-Hour Independent Expenditure Report and to the transactions contained in that report.

**Current version**: Represents the most recent version of a filer’s independent expenditure report. Transactions contained in the current version of the report are indicated with “t” in Column BS in the processed data export file and Column AX in the raw data export file.

**Past version**: Represents a previous version of a filer’s independent expenditure report after a subsequent amended report has been filed. Transactions contained in the past version of the report are indicated with “f” in Column BS in the processed data export file and Column AX in the raw data export file.

**Unknown version**: Represents a filing that did not identify whether it was a new or amended version. For example, this may occur when filers attempt to amend their original report but inadvertently submit the amendment as a new filing or submit a new filing as an amendment. Transactions contained in the unknown version of the report are indicated with a null value in Column BS in the processed data export file and Column AX in the raw data export file.

**Using the version filter**
**For processed 24- and 48-hour reports, raw 24- and 48-hour reports, raw regularly scheduled reports**:
When you filter by current and unknown versions, the website will display "current" and "unknown" versions of independent expenditure transactions. This can include original and amended filings. Users must make judgments on any transactions with the version category “unknown” that are presented in the data set.

When you don’t filter by current and unknown versions, the website will display all versions, current, past and unknown, of independent expenditure transactions. Transactions reported on all original and all amended filings will be displayed. Users must make judgments on any transactions with the version category “unknown” that are presented in the data set.

**For processed regularly scheduled reports**:
This data does not have versioning information associated with it. All transactions are shown as the current version and are indicated with “t” in Column BS in the processed data export file.

**Comment by patphongs** [comment]
@PaulClark2 Most recent update from this comment has been made in the PR: https://github.com/fecgov/fec-cms/issues/3537#issuecomment-586729696
