### ISSUE TITLE
Current version filter not functioning properly on IE datatable

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3538]
**What we're after:** We need to ensure that the current version is functioning properly on the IE datatable. 

Test:
- Go to IE datable, default view: Processed and 24- and 48-hour reports and current version applied
- Filter by Trump
- Note the total results (as of this morning, 30,453)
- Remove current version filter
- Note the total results, should still show 30,453. 

Link: https://www.fec.gov/data/independent-expenditures/?data_type=processed&most_recent=true&is_notice=true&candidate_id=P80001571

The final number, if current version was working, should now be larger. 

**Completion criteria:**
- [ ] Fix version filter and ensure that results are displayed accurately

**Comment by patphongs** [comment]
This has been fixed and deployed in this PR: https://github.com/fecgov/fec-cms/pull/3540
