### ISSUE TITLE
Wagtail wish list: Reduce vertical space around table element

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3541]
### Summary

**What we are after:**
_Right now there is a little too much space around the table element. We would like to have less white space._

![table padding](https://user-images.githubusercontent.com/24437369/74270434-33451100-4cd9-11ea-8d76-4ae7e25b6f74.jpg)

(The article this screenshot comes from is at https://www.fec.gov/updates/march-25-webinar-candidate-committees-2020/.)

### Completion criteria
- [ ] The vertical space between tables and other elements on the page should follow visual patterns from elsewhere on the site and the pattern library.
- [ ] The pattern library should specify the updates if needed

**Comment by johnnyporkchops** [comment]
We can add :
```
.body-block.block-paragraph + .body-block.block-table {
    margin-top: -4rem;
}
```
To accommodate for the default margin below `body-block.block-paragraph` when .a table block follows.
We could also add something for a table-block following another table-block but the spacing in the original screenshot seems like the expected separation between content blocks. Thoughts?

![Screen-Shot-2020-02-26-at-8 16 34-PM](https://user-images.githubusercontent.com/5572856/75403474-dd29bd80-58d5-11ea-8218-e790f36b601f.png)
