### ISSUE TITLE
Update homepage with new links to map and other .gov pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3544]
**What we're after:**
As part of the Presidential map work, we need to implement changes to the homepage which creates links to the map. 

### Related issues
- #3500 

Action items: 
- Link the first space to the map. 
- Link the second space to Help for candidates and committee: https://www.fec.gov/help-candidates-and-committees/
- Link the third space to Legal resources: https://www.fec.gov/legal-resources/

Notify @JonellaCulmer if you need any design files

### Completion criteria
- [ ] Homepage is updated to match the mockup and link to the appropriate pages.

### Design
![Screen Shot 2020-02-12 at 1 02 02 PM](https://user-images.githubusercontent.com/31663028/74363106-e2e0b880-4d97-11ea-98df-20628c479be9.png)

**Comment by johnnyporkchops** [comment]
Waiting on images from @JonellaCulmer

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Updated mockup:
<img width="755" alt="Screen Shot 2020-03-04 at 5 48 08 PM" src="https://user-images.githubusercontent.com/31663028/75930314-58dcba80-5e40-11ea-8221-59124ee431f1.png">

**Comment by JonellaCulmer** [comment]
@AmyKort The second icon text, "Information for candidates and committees" is a bit long and throwing off the alignment. Any objections to changing the section to: Candidate and committee guidance.

### Before
<img width="1042" alt="Screen Shot 2020-03-04 at 6 46 42 PM" src="https://user-images.githubusercontent.com/31663028/75933661-87f72a00-5e48-11ea-8a0b-a8cce5bd6c59.png">

### After
<img width="1042" alt="Screen Shot 2020-03-04 at 6 46 29 PM" src="https://user-images.githubusercontent.com/31663028/75933674-90e7fb80-5e48-11ea-80db-e8117563de04.png">

cc: @johnnyporkchops @dorothyyeager

**Comment by dorothyyeager** [comment]
Would prefer "information" over "guidance" - As we know from our other issue, guidance has become a "buzzword" of sorts referring to things covered by the EO.

**Comment by JonellaCulmer** [comment]
More options to consider to keep it to two lines. cc: @dorothyyeager 

"Campaign finance compliance help"
<img width="298" alt="Screen Shot 2020-03-05 at 8 43 58 AM" src="https://user-images.githubusercontent.com/31663028/75987183-7bf97f80-5ebd-11ea-8708-bd761832007f.png">

"Help with campaign finance"
<img width="286" alt="Screen Shot 2020-03-05 at 8 44 55 AM" src="https://user-images.githubusercontent.com/31663028/75987240-9cc1d500-5ebd-11ea-998c-374e4c4c039d.png">

**Comment by dorothyyeager** [comment]
I like this idea the best! @JonellaCulmer

**Comment by dorothyyeager** [comment]
To be clear, either of those two above this message works for me better than my ideas. I lean toward "campaign finance compliance help" because it's more specific, but "Help with campaign finance" is plain language and that's good. I worry it's not clear what we'll be helping them with, so that's why I lean towards the other one.

**Comment by AmyKort** [comment]
Is Help for candidates and committees too redundant? I think we use "campaign finance" to send people to the data, and "compliance" is covered in our legal resources section.

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Following a conversation with @AmyKort and @dorothyyeager, please see the below updated mockup with the language we're going forward with. I also added the image border we talked about so that other folks can see. 

![Screen Shot 2020-03-05 at 11 08 14 AM](https://user-images.githubusercontent.com/31663028/76000476-c127ac80-5ed1-11ea-8078-1cce09928b2d.png)
