### ISSUE TITLE
Fix IE version filter to return current and unknown version when applied

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3548]
**What we're after:**
When the current version filter is applied for raw (all) and processed (24- and 48-hour reports) we should see most_recent=true and most_recent=NULL, or current and unknown versions. At this time we are only seeing most_recent=true. 

When the current version filter is not applied for raw (all) and processed (24- and 48-hour reports) we should see most_recent=true, most_recent=false and most_recent=NULL. 

**Key:**
- most_recent=true is current version
- most_recent=false is past version
- most_recent=NULL is unknown version

### Related issues
- https://github.com/fecgov/fec-cms/issues/3545
- https://github.com/fecgov/fec-cms/issues/3537

### Completion criteria
- [ ] Make sure that the version filter works according to the above description.

**Comment by patphongs** [comment]
@fecjjeng @hcaofec I think I'm blocked here. It appears that `most_recent` only allows for boolean values in the API. So when I set the `most_recent=null`, I get a 422: https://api.open.fec.gov/v1/schedules/schedule_e/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&data_type=processed&is_notice=true&most_recent=null&sort=-expenditure_date&per_page=30.

**Comment by lbeaufort** [comment]
This will be addressed by https://github.com/fecgov/openFEC/issues/4208
