### ISSUE TITLE
IE raw data tab only returns notice, not return regular reports

### ISSUE THREAD

**Issue by fecjjeng** [fecgov/fec-cms#3549]
https://www.fec.gov/data/independent-expenditures/?data_type=efiling
and 
https://www.fec.gov/data/independent-expenditures/?data_type=efiling&is_notice=true
both only return notice data, not regular reports.

The web page for both processed and raw data pass the `is_notice=true` by default
However, unlike the processed tab, the raw tab does not have any way to indicate the selection of regular reports.

<img width="687" alt="Screen Shot 2020-02-12 at 9 37 27 PM" src="https://user-images.githubusercontent.com/24943130/74396454-07f91980-4de0-11ea-9478-1c34e93795ba.png">

select is_notice, count(*) from real_efile_se_f57_vw vw
JOIN real_efile.reps AS reps_1 ON vw.repid = reps_1.repid 
group by is_notice;

<img width="110" alt="Screen Shot 2020-02-12 at 9 53 09 PM" src="https://user-images.githubusercontent.com/24943130/74397195-1ba57f80-4de2-11ea-8458-2f7e32853290.png">

Even manually removed the `is_notice=true` from the url, still returns 3466 rows (as of is_notice=true)

**Comment by patphongs** [comment]
Thanks @fecjjeng, I didn't realize I needed to add report type with the current version checkbox in raw when this was implemented. Now that I've added it in the new PR, this should solve this problem.
