### ISSUE TITLE
Manually update wagtail global search index [March]

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3553]
### Summary

**What we're after:**
_We need to update the global search.gov index for new pages that were published in March._

### Related issues

_List any relevant related issue(s)_
- #3440 

### Completion criteria

- [x] Follow instructions under [Adding CMS pages to the index](https://github.com/fecgov/fec-cms/blob/develop/fec/search/management/instructions.md#adding-cms-pages-to-the-index
)
- [ ] Create ticket for next month April for manual wagtail global search index

**Comment by pkfec** [comment]
Scraped and Indexed 879 pages to i14y API.
