### ISSUE TITLE
Unverified filer data table

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#3564]
### Summary
The FEC asks filers whose registration forms contain questionable information to verify their accuracy. Filers that do not respond to verify the accuracy of their information are listed on fec.gov as **_Unverified Filers_**.

Some users are asking for a better way to find unverified filer committee/candidate _filings_ (including the verification letters that were sent by the FEC) similar to the functionality that was available on classic.fec.gov.

### Current Situation
The list of unverified filers is available under Campaign Finance Data > Filings and Reports > at the bottom of the page (https://www.fec.gov/data/browse-data/?tab=filings). Currently the list is downloadable as a .csv that contains four columns (Committee ID, Committee Name, Committee Type, First Receipt Date).

For a user to find a filing from a candidate or committee on the unverified list they need to add their identification number to the filings url. 

### Proposed
Users are asking for a data table similar to the other data tables available under the Campaign Finance Data section of the site.

- the data table would list all candidates and committees that are on the unverified filer list.
- when the user clicks on a candidate or committee:
  - Preference 1: user is taken to a Filings data table filtered by the entity's id. Something like the filings table we can view now ([committee example](https://www.fec.gov/data/filings/?data_type=processed&committee_id=C00726265) or [candidate example](https://www.fec.gov/data/filings/?data_type=processed&candidate_id=H8NY03185))
  - Preference 2: user is taken to a candidate or committee profile page where the user can navigate to view the entity's filings.

The data table would be filterable by filer ID, name, treasurer (if applicable).

### Use Case
Users need to be able to easily view the filings of an unverified filer in multiple situations:
- a filer calls to ask about their unverified status.
- offices outside of RAD ask why a filer was added to the unverified filer list.
- when a filer is not findable on other parts of the site (because they're flagged as unverified), it would be better to look up the entity in the data table instead of downloading the CSV.

### Related work:
Filings from unverified candidates are not shown on filings page[ #4157](https://github.com/fecgov/openFEC/issues/4157) on openFEC repo.

Other references to unverified filerings:
- #1556 Design front-end unverified candidates and committees (closed in a 2019 ticket cleanup)
- #1555 Overview of committee and candidate search enhancements

**Comment by bmathesonFEC** [comment]
I am meeting with the internal users asking for this feature to get a better understanding of their needs. At that point I'll modify the ticket to specify the proposed outcome.

**Comment by bmathesonFEC** [comment]
Added notes from my meeting with users.  My non-technical first-impression is that a challenge for creating the ideal data table is the commingling of candidates and committees in the same list, something that we don't do elsewhere on the site (that I know of). Looking forward to figuring out how we can figure out a solution!

**Comment by JonellaCulmer** [comment]
Nothing actionable here, just notes from a conversation with @patphongs:
- Do we want to consider improving navigation or findability to the existing feature on .gov as a first step? The unverified filers is not on it's own page. Does this placement make sense? Can't be found through global search. Do we want to index this, or add metatags to improve findability?
- Can we show profile pages for candidates and committees if the individuals/filers who create them want to see those pages. We currently don’t have pages for these. They would 404.

When googling "Unverified filers FEC" I get the following results:
https://www.fec.gov/campaign-finance-data/unverified-filers-file-description/
