### ISSUE TITLE
Add update language above presidential accordions

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#3567]
### Summary
Users need to know and understand what financial data is included in the presidential map download files. 

**What we're after:**
Add language above the accordions

"The 2020 files below contain financial activity through January 31, 2020 for presidential monthly filers and through December 31, 2019 for presidential quarterly filers."

 link
![image](https://user-images.githubusercontent.com/11817734/75044394-91b77f80-548f-11ea-9f5f-50a2d339566d.png)

### Completion criteria
- [ ] add update language 
- [ ] deploy hotfix

**Comment by dorothyyeager** [comment]
One quick editorial comment - We normally avoid using directional words on the website for accessibility and other reasons. So the word "below" should come out of the sentence and it should read 

> "The 2020 files contain financial activity through January 31, 2020 for presidential monthly filers and through December 31, 2019 for presidential quarterly filers."

**Comment by jason-upchurch** [comment]
@dorothyyeager thank you

**Comment by jason-upchurch** [comment]
@dorothyyeager @PaulClark2 @pkfec @fec-jli does the following look correct? I don't see the "space" issue from Dorothy's comment:

<img width="735" alt="Screen Shot 2020-02-21 at 11 23 54 AM" src="https://user-images.githubusercontent.com/49287206/75051897-b36b3380-549c-11ea-9922-e717efa33ff2.png">

**Comment by PaulClark2** [comment]
@jason-upchurch it looks correct to me. I'll let @dorothyyeager speak for herself, but I think she was referencing the trailing space in the HTML, `</a> &#187; </p>` I see you have removed the trailing space. That bit of code looks like this, `</a> &#187;</p>`, now.

**Comment by PaulClark2** [comment]
Change merged #3568
