### ISSUE TITLE
Feedback: "Filing frequency by type of filer" Page

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3571]
@ryanfec commented on [Mon Feb 24 2020](https://github.com/fecgov/FEC/issues/9536)

RAD received a phone call today from a House candidate who received a late notification email for a Pre-Primary Report that was due on February 20th.  After receiving that email, the candidate visited “Filing frequency by type of filer” page (https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/filing-frequency-type-filer/) and didn’t think his committee needed to file a Pre-Primary Report because this page said the filing frequency for House/Senate committees is “quarterly only.”  As a first-time candidate, this caller found this page confusing and suggested it would have been helpful if this page also mentioned pre-election reports. 

### Completion criteria
- [x] Consider wording change to make it more clear that "quarterly" is just a label for filers who aren't monthly filers and those types of filers must file pre-election reports if triggered.
- [x] Consult with @JonellaCulmer regarding formatting changes to improve readability.
- [x] Run suggested changes by Information Division management
- [x] Publish changes to page

**Comment by JonellaCulmer** [comment]
@djgarr Thanks for showing me the draft. Looks good! Thanks!

**Comment by djgarr** [comment]
ran the updates by @JonellaCulmer and info division management. everything looks good. published the updates

**Comment by bmathesonFEC** [comment]
Hey @djgarr, these are a great improvements from RAD's perspective. Thank you for taking the time to do this ticket that started with one  of our callers. It's great that quarterly reporting landing page now references pre/post election reports and 48 hour notices! Thank you. I also noticed that you removed the word "only" from the _Filing Frequency by Filer Type_  page. 

Did you have any thoughts about making the pre/post election and Form 6 filing requirement explicit on the _Filing Frequency by Filer Type_  page? Ultimately the concern within RAD was that a user would get to that page see "Quarterly" and subsequently file only quarterly reports.

Happy to discuss further.
