### ISSUE TITLE
Clean up feature flags for features in production

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3573]
**Summary**
We should clean up feature flags for features that are live. We shouldn't need to set flags locally to see features that are in production. 

**Examples:**
- [ ] `FEC_FEATURE_HOME_MAP`
- [ ] `FEC_FEATURE_HOME_BARCHARTS`
- [ ] `FEC_FEATURE_AGGR_TOTS`

**Completion Criteria:**
- [ ] feature flags default to `True` only for local env 
- [ ] ensure that feature flag functionality does not change for production

**Comment by patphongs** [comment]
We can address this later when there's bandwidth, moving to PI 14
