### ISSUE TITLE
Wagtail wish list - make the anchor links work (or teach content team how to use them)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3575]
### Summary

**What we are after:**
It would be great to have the ability to insert anchor links into a page. Andrew from 18F had set that up in the Wagtail rich text editor, but it hasn't quite worked for us.

### Related issues

_List any relevant related issue(s)_

- #3556 testing recent Wagtail upgrade - see comments and test pages that mention anchor link
- #2251 Andrew's work

### Screenshot of anchor link tool

![image](https://user-images.githubusercontent.com/24437369/80711545-83549800-8abe-11ea-9b6f-f93c0a238909.png)

### Example to reproduce
In the Wagtail page https://fec-prod-proxy.app.cloud.gov/help-candidates-and-committees/keeping-records/records-receipts/ - 
1. Go to the heading "Best efforts to document receipts"
2. Use the # sign in the toolbar to try to create an anchor link to link the phrase "described in the section "File amendments if necessary."" to the heading labeled "File amendments in necessary."

### Completion criteria
- [ ] Content and front-end pairing to identify issue
- [ ] If something in Wagtail needs fixing to make anchor links work, fix it.
- [ ] If it checks out as working in Wagtail, show content team how to use it.

**Comment by patphongs** [comment]
@dorothyyeager I have tested the anchor link functionality and it is working. I was able to create this anchor link in dev: https://fec-dev-proxy.app.cloud.gov/help-candidates-and-committees/keeping-records/records-receipts/#file-amendments-if-necessary

## Steps to create anchor links
1. Find the heading you would like to link to
2. Select that text heading and click on the `#` anchor button. This will create the anchor. The anchor will be the selected text all lower case and separated by dashes. For example, an anchor link for heading `File amendments if necessary` will be `id="file-amendments-if-necessary"`
3. Go to the text you would like to create the link to the anchor. Select that text and click the link button. The link button panel will pop up, select the "Anchor" link. Insert the ID name that was just created in the heading. The # field within the anchor should be `file-amendments-if-necessary`.
4. Preview the page and scroll down to the created anchor link. Click on it and it should link you to the appropriate heading.

**Comment by dorothyyeager** [comment]
Thanks @patphongs ! I got the training invite and am looking forward to the training! I forwarded it to the rest of the content team. Really excited we will have this capability.

**Comment by patphongs** [comment]
Content team has been trained. Anchor links will only be used directly on the page, we will not link to an external page for anchor links. This method was chosen because maintaining external anchor links is not possible in Wagtail and could be an accessibility issue.
