### ISSUE TITLE
Wagtail wish list: Enable ability to have links open in separate browser

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3577]
### Summary

**What we are after:**
Sometimes users want to have links open in a separate window or tab automatically. Right now there is no way to toggle an external or internal link to do this, so the link will open in the same browser window. (Easy workaround if the user knows they can right click and choose open in new tab/new window, but not all users know this.)

### Related issues

- https://github.com/fecgov/FEC/issues/9544

### Completion criteria

- [ ] Determine if there was a reason we set it this way when the redesign was done? (Or if it's a Wagtail setting we can't turn off)
- [ ] If not, enable ability to open links in a separate browser window or tab

**Comment by johnnyporkchops** [comment]
Regarding the first checklist item above:
**"Determine if there was a reason we set it this way when the redesign was done? (Or if it's a Wagtail setting we can't turn off)"**
It is generally considered  best-practice to open links (external and internal) in same tab. There are arguments for this  related to accessibility, SEO, and to a lesser extent, security.  But if it remains the default and we only override it if there is a good reason, then I think it could make sense as long as we consider user-experience and security implications before doing adding  this option.

**Comment by patphongs** [comment]
I agree that opening in a new tab would hinder accessibility and be disorienting for people, especially for users who have difficulty looking at content visually. I am going to close this issue, we can decide to re-open if we find there is a true need.
