### ISSUE TITLE
Add "official site of US government" banner

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3579]
### Summary

**What we're after:**
As a website user, I want to be confident the site I'm looking at is legitimately a US government website. 

We should add a "official site of US government" banner to fec.gov. This is recommended by the US Web Design Standards and also requested by @wluoFEC.

**Background:**
From [US Web Design System website](https://designsystem.digital.gov/components/header/)

>We recommend that all federal government sites include the “official government website” banner and a logo or site name. The banner clearly identifies your site as part of the United States government, while a logo or site name helps visitors understand who you are and what you do

**Code:** https://github.com/uswds/uswds/blob/b8730e8cd17ac451343699e73039c1a7f9a50ebb/src/components/banner/banner.njk

**Example:**
https://www.gsa.gov
<img width="1300" alt="Screen Shot 2020-02-28 at 2 34 09 PM" src="https://user-images.githubusercontent.com/31420082/75582033-b5069f80-5a38-11ea-8e76-eea23ef8a7cc.png">

 **Completion criteria**
- [ ] Add a "official site of US government" banner to fec.gov based on [US Web Design Standards](https://designsystem.digital.gov/components/header/)

**Comment by JonellaCulmer** [comment]
I found a site that uses version 1 of the USWDS. https://www.fedramp.gov/

**Comment by lbeaufort** [comment]
@johnnyporkchops here are my two attempts, in case they're helpful. Thanks for taking this issue!

https://github.com/fecgov/fec-cms/pull/3611
https://github.com/fecgov/fec-cms/pull/3610

**Comment by johnnyporkchops** [comment]
@JonellaCulmer , @lbeaufort Did we write our own language for this, or is this possibly from an older version?  The language in the current [PR](https://github.com/fecgov/fec-cms/pull/3610) is different than USWDS, and FedRamp example. I did not find anything in issues referring to custom language,  but just making sure.
USWDS CODE: https://github.com/uswds/uswds/blob/b8730e8cd17ac451343699e73039c1a7f9a50ebb/src/components/banner/banner.njk

[USWDS](https://designsystem.digital.gov/)

[FedRamp ](https://www.fedramp.gov/)

**Comment by johnnyporkchops** [comment]
Oh, It looks like this language was changed in this USWDS commit:
https://github.com/uswds/uswds/commit/cda27a254870fa50a48d4add90269bae85ed3813#diff-03fb70e2ac5cb87c9bb02ce83f4964c6

So I'll stick with the latest

**Comment by johnnyporkchops** [comment]
Closing issue, PR #3700 has been merged.
