### ISSUE TITLE
Create strategy for policy/guidance documents

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-cms#3580]
### Summary
From #3554 we need to create a strategy for handling policy/guidance documents to make it easier to systematically add/remove pdfs _(Dorothy comment: and html pages)_ for searching. One example strategy could be a naming convention of the document itself such that use of that convention implies that the doc is to be included in search results and not using that naming convention implies that the doc is NOT to be included in the search results, i.e., if and only if.

### Completion criteria
- [x] Decide on naming convention/tagging we need
- [x] strategy adopted
- [ ] test against s3 to verify that convention is necessary and sufficient for inclusion in search results
- [x] Develop strategy for uploading new and replacement documents/pages and updating the page after creation.

**Comment by jason-upchurch** [comment]
@dorothyyeager cc @pkfec I just ran a test script I wrote with dummy files I uploaded to s3 and was able to generate a sitemap based on a convention. In this toy example, the convention happened to be that the characters `zzz` all appeared together in the file name (again, just as a test of the pdf portion of this). This was probably the most obvious solution I could think of. Let me know if you come up with something different and I'll incorporate that.

**Comment by jason-upchurch** [comment]
@dorothyyeager cc @pkfec I'm just commenting here in case it affects you in any way, but I understand that both pdfs and html pages will be searched. I strongly suspect that a strategy for one will not necessarily translate to a strategy for the other. We can talk more on Friday (or one on one) about how we might address the html with respect to this overall strategy. I happened to make a separate issue for my html technical work because it is fundamentally different from the pdf work.

**Comment by dorothyyeager** [comment]
Notes to self on project regarding eventual Guidance page:
- URL for the Guidance doc page must be www.fec.gov/guidance
- For the MVP, we'll focus on PDFs, but eventually HTML search to be incorporated too
- The page itself is going to be hard-coded and search.gov "hosted" but on an fec.gov page. Not a Wagtail editable page. (So after it debuts, when it needs an update or a new document added, the content team/Information Division will need to coordinate with the front end/back end/whoever can update the page.)

Everyone working on the related issues for the Guidance page will meet to talk them through tomorrow.

**Comment by dorothyyeager** [comment]
Next step: I'll make a list of file names (full with https:// for the html pages and just name.pdf for the PDF) in a text file for @jason-upchurch - that will get him what he needs for the MVP. I'll also proceed with uploading the policy statements that need to be uploaded (will add EO13892 into those file names).

**Comment by dorothyyeager** [comment]
I've uploaded the documents that needed uploading as part of work in #3596. I've also sent @jason-upchurch the text file for his sitemap work (see content channel in Slack).  Not sure if we are ready to close this ticket or if it should be re-assigned to you, Jason?

**Comment by jason-upchurch** [comment]
@dorothyyeager I defer to you and PMs on whether to close the ticket or not. One thing we do want to do long term is make sure we have a sustainable "strategy" to deal with modifications to this list. So I'd say we successfully adopted a strategy for the MVP.

**Comment by dorothyyeager** [comment]
This works for me @jason-upchurch. Seems like we can close this ticket as our MVP strategy is adopted and the work will continue in #3581
