### ISSUE TITLE
New icon for disclaimer example

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#3588]
### Summary

The current disclaimer examples on the Advertising and disclaimers page (https://www.fec.gov/help-candidates-and-committees/making-disbursements/advertising/) utilize the current reporting example icon. The goal is to identify a new icon to demonstrate disclaimer examples from reporting examples

![image](https://user-images.githubusercontent.com/40633757/75820505-72abce00-5d6a-11ea-93f0-14076543f38f.png)

### Action items

- [x] Find a new icon for disclaimer examples
- [x] Create implementation issue to add new icon to wagtail for disclaimer example use

### Completion criteria 
- [ ] New icon design for examples

**Comment by JonellaCulmer** [comment]
While I wait for feedback I have already requested regarding my first draft:

<img width="383" alt="Screen Shot 2020-03-09 at 11 06 53 AM" src="https://user-images.githubusercontent.com/31663028/76231518-bf285b00-61fb-11ea-9950-c2cac3d4e22e.png">


Not sure whether to leave out documents entirely as part of the example icon. I'm hoping that whatever is created can be used across all example types. If not, we should just consider different groupings for different types of examples. Examples for reports, examples for printed items, examples for digital media, etc. That route seems more complicated.

**Comment by jjonesfec** [comment]
Not sure if your mock-up would work for all example types. We have completed forms for which this page image would work but we also print and television ads that don't have a page aspect. Having one icon for all examples would be preferable in my opinion and I'd lean towards something totally new but that carried some immediacy. Would an exclamation point be too on-the-nose?

**Comment by djgarr** [comment]
The only thing I can think of that is universal for all the disclaimers is the "Paid for by..." language. Would it be possible to incorporate that into the image?

**Comment by jjonesfec** [comment]
Maybe we should consider separate icons for separate example types.

**Comment by jjonesfec** [comment]
That might be a bit much for an icon but maybe a sidebar.

**Comment by JonellaCulmer** [comment]
@jjonesfec and @djgarr Here's the updated version. I retained the checkmark but this better resembles our example pages regardless of what they're for. 

<img width="725" alt="Screen Shot 2020-03-09 at 1 22 10 PM" src="https://user-images.githubusercontent.com/31663028/76247103-5e0d8100-6215-11ea-9d61-34e93696bbf3.png">

**Comment by djgarr** [comment]
@JonellaCulmer works for me!

**Comment by djgarr** [comment]
@JonellaCulmer Thanks!

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issue https://github.com/fecgov/fec-cms/issues/3602 and pattern library issue: https://github.com/fecgov/fec-pattern-library/issues/151
