### ISSUE TITLE
Research the search capabilities for the latest updates keyword search

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3589]
**What we're after:**
We plan to utilize more keyword type searches for documents as a whole through our feeds. To that end, we need to research and document how the current keyword search functions on the Latest updates feed. 

### Completion criteria
- [ ] Document the functionality and key features for the Latest updates keyword search

**Comment by patphongs** [comment]
This is using Wagtail's built-in search capabilities. http://docs.wagtail.io/en/v2.2/topics/search/searching.html. It appears to only be able to search based on Wagtail page model and field. So it would not be able to search PDF files. We may be able to have it search the contents of a specific page?
