### ISSUE TITLE
Upload EO13892 docs currently on transition into the CMS

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3596]
### Summary

**What we are after:**
_We are preparing the Guidance docs page and need to move some documents over into the CMS._

### Related issues

_List any relevant related issue(s)_

- #3580 
 
### Completion criteria

- [x] All [docs on this list](https://docs.google.com/document/d/11Cl-nuGtiTkl7rormQoWYxF3vuhiDi8fCsjV7HrPlvs/edit?usp=sharing) that currently live in transition uploaded to Wagtail
~- [ ] Revise file names for PDFs to the text file I'm making in #3580 and include EO13891 in file names~
~- [ ] Update links on Policy page (transition) and in Wagtail as needed~
- [x] Add these files to PI12 redirect list

### Future work

Redirects

**Comment by dorothyyeager** [comment]
I've uploaded the documents and added them to a file we are using to do back-end work for the MVP of the Guidance doc page. Now am in process of tagging them in Wagtail and doing the other organizational work needed.

**Comment by dorothyyeager** [comment]
I've updated the relevant links on the old Policy page and requests for legal consideration page, as well as links on the fec.gov pages for misappropriation and enforcement process. I've also updated our redirect spreadsheet, so we can implement redirects for these files. (Holding off on doing them until after we meet with OGC; will open a separate ticket for that work when ready.) Next step is to search some terms on fec.gov to make sure I've got all the fec.gov pages that need a link updated.

**Comment by dorothyyeager** [comment]
I've updated Wagtail pages and transition pages with the updated URLs for these PDF links.  A list of the new URLs for the PDFs is in [this spreadsheet](https://docs.google.com/spreadsheets/d/1e2cYmD0z2lEyHfmmSEEirN62IrsMbsneKoOe0vY36Nw/edit?usp=sharing). Work on this ticket is complete so closing.

**Comment by dorothyyeager** [comment]
We need to reopen this ticket. The wrong EO number was supplied to us; need to adjust the names of the PDF to reflect they are associated with EO **13891**.

**Comment by dorothyyeager** [comment]
Moving to blocked until we have a chance to meet with OGC and get a good handle on what's required.

**Comment by dorothyyeager** [comment]
Clarifying my comments for myself - apparently there are two EOs and we might have the right EO number after all in EO 13892. In any case, we'll know what to do next after meeting with OGC this Friday.

**Comment by jason-upchurch** [comment]
@dorothyyeager, in case it helps any, even if the EO number changes, as it stands, there's no motivation to reupload anything unless you prefer to have it labeled as such. There are a bunch of other documents that we use that don't directly use the EO convention, so everything is hard coded in the sitemap.

**Comment by dorothyyeager** [comment]
Our meeting with OGC confirmed that we had named Wagtail documents correctly (whew!) so no need to do a big re-naming; re-upload. Just some confusion on my end which is now straightened out. I've crossed out the completion criteria we don't need anymore.

**Comment by dorothyyeager** [comment]
The files have been added to our redirect spreadsheet. We'll take care of that in #3637. Closing this ticket.
