### ISSUE TITLE
Guidance doc search MVP

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-cms#3599]
### Summary 
Replaces #3598 for MVP purposes. This issue is to do the MVP backend work to deliver the guidance document search MVP.

Associated backend work to automate and optimize the sitemap remains under #3598 .

Action item: 
- [ ] Using the dates provided by content (after successful test: https://github.com/fecgov/fec-cms/issues/3638) update metadata

### Completion criteria
- [ ] search functionality is in compliance with EO.

**Comment by jason-upchurch** [comment]
added sitemap_pdf.xml and sitemap_html.xml to s3 (prod) and gave to search.gov. They will index the complete listing.

**Comment by dorothyyeager** [comment]
@jason-upchurch Date of issue, date of posting and URLs for testing date part of search (giving two very different pdfs to see what comes up for them).

https://www.fec.gov/resources/cms-content/documents/fedreg_notice_2011-11_EO13892.pdf, date of issue and date posted are the same: 2011-01-08 in YYYY-DD-MM format

https://www.fec.gov/resources/cms-content/documents/colagui.pdf date of issue is 2018-01 (YYYY-MM) and date posted is 2018-18-01

https://www.fec.gov/updates/fec-statement-on-the-supreme-courts-decision-in/, date of issue and date posted are the same: 2010-05-02 in YYYY-DD-MM format

Let me know if any questions. Content team will start working up the list of dates.
