### ISSUE TITLE
Update example icon globally

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3602]
**What we're after:**
We've created a new icon to work for all example pages of varying types. The previous icon worked only for reporting examples. We need to update the icon used for examples, such as cards, globally. 

Icon is here: https://drive.google.com/drive/folders/18kchMACk2e8QWxSi0jW4N04KNxi8CIii

### Related issues
https://github.com/fecgov/fec-cms/issues/3588 New icon for disclaimer example

### Completion criteria
- [ ] Example icon is replaced with the new icon globally

**Comment by rfultz** [comment]
@JonellaCulmer 
- where can we see the current icon in use?
- Is it a global replace or do we need to only replace it in certain places?
- Should it be added to anyplace new (where the current icon isn't being used)?
- Should we update the pattern library, too?

**Comment by JonellaCulmer** [comment]
@rfultz Here's a link to a place where the current icon is in use. See all the cards.  https://www.fec.gov/help-candidates-and-committees/advertising-and-disclaimers/

This will be a global replacement to all current locations, not any place new, and we should definitely add it to the pattern library, if only the place that tracks all of our icons.
