### ISSUE TITLE
Transition pages to take down

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#3609]
### Summary

**What we're after:**
_To remove the outdated pages from transition now that the redirects are in place. These were redirected in #3748, #3546 and in #3637_

### Completion Criteria

- [ ] The following pages are removed from transition and from the search.gov index of transition pages (if they are there).

/em/respondent_guide.pdf

/law/cfr/ej_compilation/2007/notice_2007-13.pdf
/law/cfr/ej_compilation/2007/notice_2007-9.pdf
/law/cfr/ej_compilation/2007/notice_2007-8.pdf

/law/cfr/ej_compilation/2010/notice_2010-13.pdf

/law/cfr/ej_compilation/2011/notice_2011-13.pdf
/law/cfr/ej_compilation/2011/notice_2011-11.pdf
/law/cfr/ej_compilation/2011/notice_2011-02.pdf

/law/cfr/ej_compilation/2013/notice2013-16.pdf
/law/cfr/ej_compilation/2013/notice2013-14.pdf
/law/cfr/ej_compilation/2013/notice2013-09.pdf

/law/cfr/ej_compilation/2016/notice2016-02.pdf

/law/policy/purposeofdisbursement/notice_2006-23.pdf

/law/policy/guidance/internal_controls_polcmtes_07.pdf

/law/policy/notice_2006-11.pdf

/pages/brochures/audit_process.pdf
/pages/brochures/jointfundraising_brochure.pdf
/pages/brochures/notices.shtml
/pages/brochures/pubfund_limits_2016.shtml
/pages/brochures/spec_notice_brochure.pdf

/pdf/1997_Enforcement_Manual.pdf
/pdf/2017-2018_rad_review_referral_procedures.pdf
/pdf/2016title26materialitythresholdsapproved09132016_redacted.pdf
/pdf/2014AuthorizedMaterialityThresholds_Redacted_for_Public_Release.pdf
/pdf/2014UnauthorizedMaterialityThresholds_Redacted_for_Public_Release.pdf
/pdf/2012title2authmaterialitythresholdsapprvd72313_redacted.pdf
/pdf/2012title2unauthmaterialitythresholdsapprvd5713_redacted.pdf
/pdf/2012title26materialitythresholdsapprvd12913_redacted.pdf
/pdf/Additional_Enforcement_Materials.pdf
/pdf/audit_thresholds_auth_2009-10.pdf
/pdf/audit_thresholds_unauth_2009-10.pdf
/pdf/audit_threshold_title26_2008.pdf
/pdf/commissioners_tips.pdf
/pdf/CoverLetter_20130725.pdf
/pdf/RAD_Procedures_2015-16.pdf
/pdf/RAD_Procedures_2013-14.pdf
/pdf/RAD_Procedures.pdf
/pdf/record/1999/index99_1.htm
/pdf/record/1998/index98_1.htm
/pdf/record/1997/index97_1.htm

/press/bkgnd/fund.shtml

/pubrec/pacronyms/pacronyms.shtml

/rad/documents/FECFileGettingStartedManual.pdf

**Comment by rfultz** [comment]
@dorothyyeager @kathycarothers these have been removed, though I couldn't find /pages/brochures/notices.shtml

**Comment by dorothyyeager** [comment]
Thanks @rfultz - very much appreciated!! That much closer to getting off of transition.

**Comment by rfultz** [comment]
Closing this with Dorothy's approval
