### ISSUE TITLE
Clean up all references to classic site

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3620]
`FEC_CLASSIC_URL` is an example

**Comment by rfultz** [comment]
@dorothyyeager @kathycarothers @djgarr it looks like the only place we're using this is in meeting search results messages. Any suggestions for how to change the "No results" message?

![image](https://user-images.githubusercontent.com/26720877/108228702-1d003b00-710d-11eb-8741-dfe858da0195.png)

**Comment by djgarr** [comment]
Could we use the same language on the site search?

![image](https://user-images.githubusercontent.com/40633757/108229917-3a81d480-710e-11eb-8785-39ac272b943e.png)

**Comment by dorothyyeager** [comment]
Agree with @djgarr - let's use the same language for this.
