### ISSUE TITLE
2019 YE missing from calendar

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3625]
https://www.fec.gov/calendar/?calendar_category_id=25&calendar_category_id=26, click back to January 2020, it's missing

See also https://github.com/fecgov/fec-cms/issues/2160

**Comment by djgarr** [comment]
working on it

**Comment by lbeaufort** [comment]
Thanks @djgarr! Year end now shows for monthly and quarterly filers. I also confirmed that the mid-year appears for quarterly filers.
