### ISSUE TITLE
Update presidential candidate bulk data accordions with correct activity dates

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3626]
### Summary

**What we're after:**
_The presidential candidate bulk data accordions need to correctly reflect the activity, which is a day after a filing deadline._

We want to use an API call to get these dates to avoid making hotfixes the day after a filing deadline.

### Technical specs

The on date should be the day after the filing deadline.

"The 2020 files contain financial activity through [X_DATE], 2020 for presidential monthly filers and through [Y_DATE], 2019 for presidential quarterly filers."

Where [X_DATE]
= February 29 on March 21 (day after filing deadline)
= March 31 on April 21
= April 30 on May 21
= May 31 on June 21
= June 30 on July 21
= July 31 on August 21
= August 31 on September 21
= September 30 on October 21
= October 14 on October 23
= November 23 on December 4
= December 31 on February 1, 2021

Where [Y_DATE]
= March 31 on April 16
= June 30 on July 16
= September 30 on October 16
= October 14 on October 23
= November 23 on December 4
= December 31 on February 1, 2021

### Completion criteria

- [ ] Presidential monthly filers date reflects the day after the monthly filing deadline
- [ ] Presidential quarterly filers reflects the day after the quarterly filing deadline

**Comment by PaulClark2** [comment]
@patphongs this might help :lock: https://docs.google.com/spreadsheets/d/1PQ4iTWHpN4Q1eTy-FCKBbSZSEMBcSfHRcfwRPjMtuGQ/edit#gid=0 :lock:

**Comment by lbeaufort** [comment]
If we wanted to use an API call, we could use the /calendar-dates/ endpoint, but it doesn't have coverage end date, only report due date. Here are the calls, but it would require probably a manual change. 

I think instead for now we should use a hard-coded lookup based on @PaulClark2's spreadsheet. I would recommend structuring the data a little differently, we can talk about it.

### Quarterly
- `max_start_date` = today plus one
Example: today
https://api.open.fec.gov/v1/calendar-dates/?api_key=DEMO_KEY&per_page=1&calendar_category_id=25&max_start_date=2020-03-18
Example: 3/21/20
https://api.open.fec.gov/v1/calendar-dates/?api_key=DEMO_KEY&per_page=1&calendar_category_id=25&max_start_date=2020-03-22

### Monthly
- `max_start_date` = today plus one
https://api.open.fec.gov/v1/calendar-dates/?api_key=DEMO_KEY&per_page=1&calendar_category_id=26&max_start_date=2020-03-18
Example: 3/21/20
https://api.open.fec.gov/v1/calendar-dates/?api_key=DEMO_KEY&per_page=1&calendar_category_id=26&max_start_date=2020-03-22

**Comment by lbeaufort** [comment]
Example of a dictionary using ranges: https://github.com/fecgov/fec-cms/issues/3413#issuecomment-569761606

**Comment by lbeaufort** [comment]
PR Merged to release branch
