### ISSUE TITLE
Redirects for guidance docs uploaded to Wagtail

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3637]
### Summary

**What we are after:**
_As a user, I want to find the FEC's guidance docs in their current home._

### Related issues

 - #3596 - We uploaded a bunch of PDFs that were on transition into the CMS. This ticket is to do their transition and www redirects

### Completion criteria

- [x] Do transition redirects for Guidance documents (see tab) on [redirect spreadsheet](https://docs.google.com/spreadsheets/d/1Jn5nC3fFku10RTCP5OAW6RiffjNBE4VwBubITQpCNK8/edit#gid=1954928973)
- [x] Do Wagtail or www redirect for these PDF files (may need to check with @patphongs to see what will work best)
- [x] Test after they are merged
- [x] Fix identified transition [redirect issues](https://github.com/fecgov/fec-cms/issues/3637#issuecomment-610361045)
- [x]  Put in a ticket for front-end to take down the old files off transition.

### Future work

See the Guidance page epic.

**Comment by dorothyyeager** [comment]
Talked with @patphongs about this issue. She is going to work out the coding for the transition redirects. I'll try to put the www ones in Wagtail.

**Comment by patphongs** [comment]
@dorothyyeager I have created the code in this [spreadsheet](https://docs.google.com/spreadsheets/d/1Jn5nC3fFku10RTCP5OAW6RiffjNBE4VwBubITQpCNK8/edit#gid=668027500)🔒. This redirect code covers the transition specific redirects that are needed.

**Comment by dorothyyeager** [comment]
Thanks @patphongs !

**Comment by dorothyyeager** [comment]
PRs submitted for both www and transition addresses. They are ready for @patphongs to review, merge and deploy.

A few www redirects could be done in Wagtail; those are done and spreadsheet updated.

**Comment by dorothyyeager** [comment]
Transition redirects not working for these three
https://transition.fec.gov/pdf/commissioners_tips.pdf
https://transition.fec.gov/em/respondent_guide.pdf
https://transition.fec.gov/law/policy/guidance/internal_controls_polcmtes_07.pdf

**Comment by patphongs** [comment]
@dorothyyeager This link seems to redirect correctly: https://transition.fec.gov/em/respondent_guide.pdf. 

I have submitted a PR to fix the other 2: https://github.com/fecgov/fec-proxy/pull/163. I've added you to review @dorothyyeager

**Comment by dorothyyeager** [comment]
I've approved and merged the PR @patphongs - thanks! They are ready for you to deploy and then I can test.

**Comment by dorothyyeager** [comment]
Many thanks to @patphongs for helping us get these pages redirected! I've added them to our next take down old transition files ticket at #3609 . Closing this ticket.
