### ISSUE TITLE
Test to determine how we can add dates to guidance doc search

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3638]
**What we're after:** The EO 13892 requires us to include dates and we need to find the best way forward. As a first step, content team and back-end will work together for a test to determine whether or not a proposed method of adding dates into the metadata will work. 

Action items:
- [x] Content: Identify the published dates for one single PDF and one HTML page and provide to back-end (Gave two PDFs to test for each type) - Dorothy
- [x] Back-end: Will use the dates provided by content team for test to see if the dates can successfully be added to the guidance “metadata”.
- [x] If it works, content to provide a full list of dates. If not, we need to consider a back-up solution.

### Related issues
- https://github.com/fecgov/fec-cms/issues/3599 Guidance doc search MVP
- https://github.com/fecgov/fec-cms/issues/3635 Draft written content for Guidance document page

### Completion criteria
- [x] Determine path forward to add dates to individual PDFs and HTML pages for guidance search 

### Tech steps or considerations
- [ ] TBD

**Comment by jason-upchurch** [comment]
added metadata. Waiting for indexing.

**Comment by jason-upchurch** [comment]
@dorothyyeager @JonellaCulmer @PaulClark2 , I submitted the metadata to search.gov and will wait for indexing. This ticket was assigned to me as well, so I unassigned myself since I already have an issue open with an edit from Jonella giving me an action item to do exactly this work. I just need that one issue to track the work if anyone else wants to use this for another "meta" issue.

**Comment by kathycarothers** [comment]
I have finished entering all the dates into the document. It looks like all the "Action Items" are now completed. Let me know if I should close this ticket or not. @dorothyyeager @patphongs @JonellaCulmer @jason-upchurch

**Comment by AmyKort** [comment]
Thank you @kathycarothers ! Do we still need to make a plan for going forward?

**Comment by dorothyyeager** [comment]
@patphongs OK to close this ticket? Content side of it is done.

**Comment by patphongs** [comment]
The metadata change to add a custom date did not work. We can attempt to add the custom date by modifying the PDF metadata itself to modify publication_date in the search.gov indexer. cc @jason-upchurch @JonellaCulmer @dorothyyeager. Closing this ticket as the testing is done.
