### ISSUE TITLE
Fix case names and SEO for the press releases that are Guidance documents

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3644]
### Summary

**What we are after:**
We need to fix the press releases that OGC listed as Guidance docs to include the court cases they reference and also do some basic SEO for them (right now there's none) so that Google and Bing and other search engines will pick up on them.

### Action items

For these URLS:

https://www.fec.gov/updates/fec-statement-on-2/
https://www.fec.gov/updates/fec-statement-on-carey-fec/
https://www.fec.gov/updates/fec-statement-on-the-supreme-courts-decision-in/
https://www.fec.gov/updates/fec-statement-on-the-dc-circuit-court-of-appeals-decision-in/
https://www.fec.gov/updates/federal-election-commissions-public-statement-on-the-supreme-courts-decision-in/

1. Locate in Wagtail
2. Add the case name into the title. (Do NOT change the URL) (You may need to read the release to get the case name)
3. Add the title into the "formatted title" field, with the case name in italic tags
4. In the promote tab, fill out the title and search description fields
5. Publish the update

### Completion criteria

- [x] All of those pages have a nice complete title that mentions the court case involved

**Comment by kathycarothers** [comment]
All pages are now complete.
