### ISSUE TITLE
Add reaction box below Presidential candidate map

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3646]
**What we're after:** Now that the map is live and seems to be working just wonderfully, we should add a reaction box to track feedback from users. 

**Completion criteria:**
- [ ] Add reaction box, centered, below the feature under a feature flag

Example of how the reaction box looks. This one is below WCCF.
<img width="884" alt="Screen Shot 2020-03-26 at 12 23 12 PM" src="https://user-images.githubusercontent.com/31663028/77670533-b73b1b80-6f5c-11ea-80eb-04fcb86c8e9f.png">

**Comment by lbeaufort** [comment]
Reference PR: https://github.com/fecgov/fec-cms/pull/3475/files

**Comment by lbeaufort** [comment]
After discussing with @JonellaCulmer @johnnyporkchops @patphongs I'm going to just implement the reaction box without a feature flag. 

We could take the reaction box off by just deleting a few lines of code, I think the ability to turn on/off independent of code changes really only has benefit if we need to be able to do it really quickly. Looking at the startup costs of the env var setup and takedown cost of removing it, it seems like it doesn’t add enough value. If we have any issues with the reaction box getting spammed, we can implement a feature flag and make it a policy to do that going forward.

**Comment by lbeaufort** [comment]
PR was deployed last week
