### ISSUE TITLE
Double check properties for guidance docs (non-forms)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3658]
### Summary

**What we are after:**
_The PDFs we can open and edit for guidance docs may need some work on their properties

### Related issues

- #3657 (form versions)
- #3645 where some returned weird results. (Note- can't really alter 2011 and beyond FR notices)

**Action items**
 
- [x] Download form or form instruction (for each one) and fill out properties tab - Description, Initial view (document name), Advanced (English language). Follow this example for FR notices

![image](https://user-images.githubusercontent.com/24437369/78292168-a0646e00-74f4-11ea-9115-66441f295445.png)

- [x]  Save with same name (save the end product into  Ntrsrv1:\\InfoProj\Policy Page Update\Guidance Docs EO13892)
- [x]  Reupload to Wagtail (you'll need to do it twice)
- [x] For the Guides, make sure to send a copy to Jim Jones so he has it for his version control files.

### Completion criteria
- [x] Guides, FR notices, various items, display actual titles when viewed in Chrome or picked up by a search engine

### Future work
Test in a few weeks

**Comment by kathycarothers** [comment]
I talked with Jim Jones and he does not save pdfs for his version control.

**Comment by kathycarothers** [comment]
I had a conversation with @dorothyyeager and Jim Jones and we decided to create a folder to house the pdfs for the web. Also, I created a document to show the properties that need to be filled out for the pdfs in the folder.
