### ISSUE TITLE
Train Brad and David in use of DAP

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#3665]
### Summary

Brad and David will need to take the "Introduction to Google Analytics for DAP Users" course. The course will be held on April 23 of this year. You both can watch the course after April 23, in small pieces, in order to understand the ins and outs of DAP. The link for the DAP training should be on the following YouTube channel https://www.youtube.com/watch?v=YxNQNL8-kLo&list=PLd9b-GuOJ3nFwlyvLFUtmDpYFKezhot8P&index=28 . 

### Completion criteria:

- [ ] To watch the training video listed above.

**Comment by kathycarothers** [comment]
David has finished the training and Brad will be done by Monday.

**Comment by bmathesonFEC** [comment]
Brad done!
