### ISSUE TITLE
Reach out to OGC on 4/9 to test guidance search on our stage environment. Testing due date is 4/16

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3672]
### Summary

**What we are after:**
_We need to have a guidance search page to comply with EO 13892._

## Action Items

- [x] Send OGC the link to the testing page on April 9 and give them the due date of April 16
- [x] Compile feedback received from OGC

### Completion criteria

- [ ] OGC feedback is received and compiled by April 16

### Future work

#3671 - Ticket for addressing OGC feedback

**Comment by dorothyyeager** [comment]
I've sent the testing link to OGC and asked for their feedback by April 16. Moving to blocked until we hear their feedback.

**Comment by dorothyyeager** [comment]
OGC has returned their feedback. We need to meet to go through it and they'd like to meet with us.

**Comment by dorothyyeager** [comment]
We're putting in two PRs to address some things that OGC noticed about the search results. We're meeting with them Tuesday and will finish compiling feedback then.

**Comment by dorothyyeager** [comment]
PRs merged. Will update this ticket with results of OGC feedback after we meet and close then.

**Comment by JonellaCulmer** [comment]
@dorothyyeager @patphongs Can this ticket be closed in favor of this one? https://github.com/fecgov/fec-cms/issues/3671

**Comment by dorothyyeager** [comment]
Hi @JonellaCulmer Yes, that makes sense. Closing this ticket and we'll pick up from there in #3671
