### ISSUE TITLE
Add Kathy to ITDWeb email list

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3676]
### Summary

**What we are after:**
_With team members transitioning and taking on more responsibilities, it would be good to have @kathycarothers added to the ITDWeb email list to assist with routine posting requests._

### Completion criteria

- [x] Kathy is added to the email distribution list for ITD web
- [ ] Determine who responds when to requests (right now, Dorothy handles during work hours, Pat/John handle outside normal work hours)

**Comment by patphongs** [comment]
Emailed today to get @kathycarothers added to this list

**Comment by dorothyyeager** [comment]
Here's how we'll split work.
During work hours, @dorothyyeager and @kathycarothers 
After hours, @patphongs  and @johnnyporkchops 

Work completed; closing.

**Comment by dorothyyeager** [comment]
Here's how we'll split work.
During work hours, @dorothyyeager and @kathycarothers 
After hours, @patphongs  and @johnnyporkchops 

Work completed; closing.
