### ISSUE TITLE
Add development / staging environment banners

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3678]
### Summary

**What we're after:**
_We need to have a banner on our feature, development, and stage environments so that users know that they are NOT viewing the live production website._

This used to be on our website but has disappeared. See example screenshot below. 

![Screen Shot 2020-04-09 at 10 46 13 AM](https://user-images.githubusercontent.com/12799132/78908246-cf786380-7a4f-11ea-955d-c79c980dd5e2.png)

### Completion criteria

- Ensure that the environment banners are on each of these environments:
   - [ ] Feature
   - [ ] Dev
   - [ ] Stage
- [ ] Ensure that this banner does not appear on the production website

**Comment by johnnyporkchops** [comment]
Closing, completed by PR# 3700
