### ISSUE TITLE
Wagtail wish list: Add HTML validator to Wagtail

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3679]
### Summary

**What we are after:**
_We would like an easy way to detect an error in our html coding, especially since there are important pages like dates and deadlines and E&J tables that incorporate HTML-coding._

### Completion criteria

- [ ] HTML validator added to Wagtail

**Comment by patphongs** [comment]
@dorothyyeager Do you think this is still a need? Since we did identify that external tool that you can use. If this is not needed anymore, please close.

**Comment by dorothyyeager** [comment]
@patphongs I think we can use the other tool.

For those who may look at this ticket, the other tool is https://wordhtml.com/.

Closing as requested.
