### ISSUE TITLE
Deploy Guidance search feature. Release date 4/28/2020

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3684]
**What we're after:** The guidance search is currently under a feature flag. After incorporating any feedback from OGC, we can proceed with deploying the feature officially and removing the feature flag. 

**Completion criteria:**
- [x] Remove feature flag
- [x] Add `SEARCH_GOV_POLICY_GUIDANCE_KEY` to prod

**After deploy:**
- [x] Create Wagtail redirect for `/guidance/` to `/legal-resources/policy-and-other-guidance/guidance-documents/`
- [x] Make links on transition pages as specified below

![Screen Shot 2020-04-20 at 6 59 04 PM](https://user-images.githubusercontent.com/31663028/79807591-650dd000-8339-11ea-8357-ad351249de81.png)
![Screen Shot 2020-04-20 at 6 59 19 PM](https://user-images.githubusercontent.com/31663028/79807592-65a66680-8339-11ea-8bc4-0cf240e44189.png)

**Comment by JonellaCulmer** [comment]
This work will remain blocked until feedback is received from OGC and re-releasing the work back into production.

**Comment by patphongs** [comment]
This feature is no longer blocked. We have received and addressed feedback from OGC and feature flag has been removed as we no longer need it.

**Comment by dorothyyeager** [comment]
@JonellaCulmer @patphongs @AmyKort  Adding one thing from my notes on our meeting with OGC. On the transition policy page under "Other Guidance," they didn't want to delete the press releases, but relabel them "Press Releases" rather than "Guidance Documents." (The guidance page search would be on the top of the page as your image shows.)

Will take care of the "after deploy" tasks tomorrow.

**Comment by dorothyyeager** [comment]
The guidance page is live at https://www.fec.gov/legal-resources/policy-and-other-guidance/guidance-documents/

A redirect for www.fec.gov/guidance is in place.

The policy page at https://transition.fec.gov/law/policy.shtml was updated to add a link to the new guidance search page.

MVP work is done! Great job @patphongs @JonellaCulmer @jason-upchurch @AmyKort @kathycarothers
