### ISSUE TITLE
Add links to guidance search

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3685]
**What we're after:**
Following up on the design work happening [here](https://github.com/fecgov/fec-cms/issues/3670), we need to implement those changes on the front-end

@JonellaCulmer I'll update this ticket with those finalized designs once OGC and the website team have agreed on that work. 

### Related issues
- https://github.com/fecgov/fec-cms/issues/3670 Design options for placement of links to guidance search

### Completion criteria
- [x] New links are added to relevant pages

**Comment by JonellaCulmer** [comment]
Pending OGC review.

**Comment by patphongs** [comment]
OGC completed review and approved the links. Deployed to production on 4/28.
