### ISSUE TITLE
Mock up the new section on the calculating fines page to reflect the new feature

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3687]
**What we're after:** With the creation of the new administrative fine calculator, we need improve the layout of the administrative filings page (https://www.fec.gov/legal-resources/enforcement/administrative-fines/calculating-administrative-fines/). Specifically the section that includes a link to the feature. 

**Completion criteria:**
- [x] Mock up solution to the new administrative fines page
- [x] Share with stakeholdes for comment
- [ ] Update the front-end implementation issue here: https://github.com/fecgov/fec-cms/issues/3732

**Screenshot of existing page/section:**
![Screen Shot 2020-04-15 at 11.42.58 AM.png](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/27f37f62-c8f0-4390-abff-14da23988bda)

**Comment by JonellaCulmer** [comment]
@dorothyyeager @AmyKort @djgarr 
Below is a mock-up of the calculating administrative fines page. I did not build the whole page out, just the section that was pertinent to the update and some content around it for context. 

This is the current page: https://www.fec.gov/legal-resources/enforcement/administrative-fines/calculating-administrative-fines/#calculating-a-fine

I've removed the three links to the existing calculators and replaced them with a button to the new feature. I also adjustecd the text around it a bit. Let me know what you think. Once we're good with it, I'll share with stakeholders for their input.

![Calculating fines mockup](https://user-images.githubusercontent.com/31663028/80535199-6ad56800-896e-11ea-99b2-ec8db4ec2caf.jpg)

**Comment by djgarr** [comment]
Looks good. The only change I'd make is using "nonfiled" instead of "unfiled" in the block text in the 48 hour notice section

**Comment by dorothyyeager** [comment]
Thanks @JonellaCulmer. Looks good to me. You'll want to capitalize "Notice" in the first sentence, along with the change David suggested. (See content guide for that one.)

**Comment by AmyKort** [comment]
This looks great to me. I don't have anything to add to @dorothyyeager and @djgarr 's edits.

**Comment by JonellaCulmer** [comment]
This work is blocked as it's with the stakeholders for their review.

**Comment by JonellaCulmer** [comment]
Barring some minor text changes, this design is complete and we can close in favor of the implementation issue [here](https://github.com/fecgov/fec-cms/issues/3732). Text changes will be tracked there.
