### ISSUE TITLE
Presidential candidate map disbursement download links incorrect

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#3709]
### Summary
_What happened?_
When I click on the export spending data button, I receive a contributions file instead of a disbursements file.  Here's the URL of the downloadable file https://www.fec.gov/files/bulk-downloads/Presidential_Map/2020/P00000001/P00000001-ALL.zip.  It should end with "D-ALL..zip."

_What should have happened?_
I should have recieved a disbursments file. The naming convention for all disbursement files is D-ALL.zip.

For example, 
https://www.fec.gov/files/bulk-downloads/Presidential_Map/2020/P00000001/P00000001D-ALL.zip

### Frequency
_an ongoing issue,_

### How to Reproduce
_List any steps you took for this issue to happen. Be sure to include the URL and what you clicked or entered. More details are better._
URL: https://www.fec.gov/data/candidates/president/presidential-map/

1. …Select any candidate, all candidates, all Dems or all Reps
1. …Expand the spending accordion
1. …Scroll to the bottom of the spending accordion
1. …Click the export button
1. …Examine downloaded file --- it's a contributions file not a disbursements file

![image](https://user-images.githubusercontent.com/11817734/80040861-02e3d500-84c9-11ea-9ba1-1dfeeeb99371.png)

**Completion criteria**
- [ ] Update URL associated with "export spending data" buttons.

**Comment by lbeaufort** [comment]
I believe the code is here: https://github.com/fecgov/fec-cms/blob/b8946ae3de6c2400b40824560d26a9bf00907554/fec/fec/static/js/widgets/pres-finance-map-box.js#L25-L26

**Comment by lbeaufort** [comment]
Hotfix was deployed 4/23
