### ISSUE TITLE
[May] - Manually update wagtail global search index

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-cms#3715]
### Summary

**What we're after:**
_We need to update the global search.gov index for new pages that were published in May._

### Related issues

_List any relevant related issue(s)_
- #3608  

### Completion criteria

- [x] Follow instructions under [Adding CMS pages to the index](https://github.com/fecgov/fec-cms/blob/develop/fec/search/management/instructions.md#adding-cms-pages-to-the-index
)
- [x] Create ticket for next month June for manual wagtail global search index

**Comment by johnnyporkchops** [comment]
**Search.gov indexed for May 2020**

<img width="1270" alt="Screen Shot 2020-05-27 at 3 31 50 PM" src="https://user-images.githubusercontent.com/5572856/83064136-54830080-a02f-11ea-995d-68fe4948d135.png">
