### ISSUE TITLE
Performance testing and fine tune: Slow API response with CMS timeout settings

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3729]
**What we're after:** In order to ensure the best timeout settings in the CMS, we need to perform load testing in the API and check how long it takes for the CMS to respond.

This work can happen simultaneously with: 
- [ ] https://github.com/fecgov/openFEC/issues/4327 After Aurora migration, measure "fallover point" for number/complexity of requests

## Completion criteria:
- [ ] Determine an optimal timeout for CMS api_caller
- [ ] See what the retry settings are - do we need to adjust?

## Technical steps
- [ ] Check slowest query times in pg badger over a period of a few months. Try running those queries with Locust
- [ ] Locust test the stage API. Ensure that connections are dropping after the specified interval of time.
- [ ] Determine if the interval of time is too long, if it is, make it a shorter timeout

**Comment by lbeaufort** [comment]
Issue moved to [fecgov/openFEC #4335](https://github.com/fecgov/openFEC/issues/4335) via [**ZenHub**](https://www.zenhub.com/)
