### ISSUE TITLE
Make OIG-requested revisions to OIG page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3731]
### Summary

**What we are after:**
_The Office of Inspector General has requested extensive revisions to their page. They aren't looking to redesign; these are just content revisions. We've asked them to send a Word document compiling them (right now the requests are in a couple of emails.)_

### Action items
- [x] Make the requested changes to their page, ensuring content guide is followed
- [x] Second pair of eyes on the draft before publishing
- [x] Publish the revisions and let OIG know

### Completion criteria

- [x] OIG page is revised and they're happy

**Comment by kathycarothers** [comment]
@dorothyyeager the draft is ready for you to take look. Things to note: Should we remove "Related Topics" at the bottom? The reference in that section is basically linked throughout the page and is referenced in the first section to the right. I think I caught everything that was asked for that we can do and the items referenced in the emails. 

Once you take a look I will publish it as a pdf to send to them for a look.

**Comment by kathycarothers** [comment]
@dorothyyeager Thank you for your edits to the page.

**Comment by kathycarothers** [comment]
@dorothyyeager @AmyKort I have sent the draft over to the OIG for review.

**Comment by AmyKort** [comment]
Thank you @kathycarothers !

**Comment by kathycarothers** [comment]
I have made the short term changes to the web page. More changes will have to be made around May 29 for the launch of their portal. In addition,  a meeting will need to be scheduled to discuss more detailed changes to the page. I am going to keep this ticket open for a day or two to see if they have any more tweaks to this page.

**Comment by kathycarothers** [comment]
Chris looked over the page and it seems to be in good order, so I will close this ticket now.
