### ISSUE TITLE
Update the Prior Notice Supplements Admin Fine section 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#3746]
### Summary

**What we're after:**
_As a committee filer I  will need to know the latest civil penalties. The Administrative Fine Program section will need to be updated on the Prior Notice Supplements_

### Completion criteria

_The supplements to Prior Notices will need to be updated with the latest penalty amount._

- [x] Supplement for PACs and Party committees 
- [x] Supplement for Congressional committees 
- [x] Supplement for Presidential committees 
- [x] Supplemental notices and prior notices for the remaining special elections

**Comment by djgarr** [comment]
pages were updated with new AF information. closing ticket
