### ISSUE TITLE
Make a plan for getting the pages/brochures/ files off of transition

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3755]
### Summary

**What we are after:**
_Because there is a broader redirect in place for pages/brochures/, every time we update a redirect for one of them, we are not able to do a Wagtail redirect to implement a www one. This has been a problem and pain point for the content team frequently and made us do extra one-on-one redirects in www. In order to get rid of that broader redirect that is troublesome, we need to make sure items in the pages/brochures directory have a new home._

### Related issues

#3748 - 12.3 redirects, where we once again experienced the issue.

### Completion criteria

- [ ] Review all the files in pages/brochures and determine if they already have a home we can redirect to (or are redirecting to). (Pat will provide list.)
- [ ] For files we are already redirecting, need to add them to the take-down list.
- [ ] For those that don't have a home, we will need to work with the Information Division to determine what should be done - should they be retired, turned into a Record article or is there a PDF version we could upload.
- [ ] Make a plan and follow-up tickets.

### Future work

Once we have removed all things we want to keep from pages/brochures and moved them to their new CMS home, we will need to update the redirects by taking out the old generic redirect and putting in Wagtail redirects. We'll also need to delete the www redirects that are one:one in that file.

**Comment by patphongs** [comment]
List of files under /pages/brochures on transition.fec.gov

https://transition.fec.gov/pages/brochures/3656b4ca
https://transition.fec.gov/pages/brochures/adr.shtml
https://transition.fec.gov/pages/brochures/aos.pdf
https://transition.fec.gov/pages/brochures/auditprocess.shtml
https://transition.fec.gov/pages/brochures/bcra_brochure.pdf
https://transition.fec.gov/pages/brochures/BestPracticesforCommitteeManagement.shtml
https://transition.fec.gov/pages/brochures/best_practices.pdf
https://transition.fec.gov/pages/brochures/biennial_limit_brochure.pdf
https://transition.fec.gov/pages/brochures/bkgdseal.gif
https://transition.fec.gov/pages/brochures/calendar.jpg
https://transition.fec.gov/pages/brochures/candidate_registration_brochure.pdf
https://transition.fec.gov/pages/brochures/chart2.gif
https://transition.fec.gov/pages/brochures/chart3.gif
https://transition.fec.gov/pages/brochures/chart.gif
https://transition.fec.gov/pages/brochures/check.gif
https://transition.fec.gov/pages/brochures/checkoff_brochure.pdf
https://transition.fec.gov/pages/brochures/choice.gif
https://transition.fec.gov/pages/brochures/compliance_nonfec.pdf
https://transition.fec.gov/pages/brochures/compliance_nonfec.shtml
https://transition.fec.gov/pages/brochures/Computer.JPG
https://transition.fec.gov/pages/brochures/contrib.gif
https://transition.fec.gov/pages/brochures/contriblimits0304.jpg
https://transition.fec.gov/pages/brochures/contriblimitschart.htm
https://transition.fec.gov/pages/brochures/contriblimits.jpg
https://transition.fec.gov/pages/brochures/ContributionLimits2003-2004.htm
https://transition.fec.gov/pages/brochures/ExamplesofHowtoCalculateFines.shtml
https://transition.fec.gov/pages/brochures/fecfeca1.shtml
https://transition.fec.gov/pages/brochures/fec_feca_brochure_spanish.pdf
https://transition.fec.gov/pages/brochures/fecfeca.shtml
https://transition.fec.gov/pages/brochures/fecseal.gif
https://transition.fec.gov/pages/brochures/fedstat1.gif
https://transition.fec.gov/pages/brochures/fedstat2.gif
https://transition.fec.gov/pages/brochures/fedstate.gif
https://transition.fec.gov/pages/brochures/fed_state_law_brochure.pdf
https://transition.fec.gov/pages/brochures/flowchart.gif
https://transition.fec.gov/pages/brochures/foreign1.shtml
https://transition.fec.gov/pages/brochures/foreign.gif
https://transition.fec.gov/pages/brochures/foreign_nat_brochure.pdf
https://transition.fec.gov/pages/brochures/forvol.gif
https://transition.fec.gov/pages/brochures/hands.jpg
https://transition.fec.gov/pages/brochures/img_0034.jpg
https://transition.fec.gov/pages/brochures/immigran.gif
https://transition.fec.gov/pages/brochures/indexp2.gif
https://transition.fec.gov/pages/brochures/internalcontrols.pdf
https://transition.fec.gov/pages/brochures/jointfundraising_brochure.pdf
https://transition.fec.gov/pages/brochures/limit.gif
https://transition.fec.gov/pages/brochures/local_party_activity_brochure.pdf
https://transition.fec.gov/pages/brochures/men.jpg
https://transition.fec.gov/pages/brochures/office.jpg
https://transition.fec.gov/pages/brochures/orientation0508.pps
https://transition.fec.gov/pages/brochures/pens.gif
https://transition.fec.gov/pages/brochures/prez1.gif
https://transition.fec.gov/pages/brochures/prez2.gif
https://transition.fec.gov/pages/brochures/prez3.gif
https://transition.fec.gov/pages/brochures/prez_checkoff.gif
https://transition.fec.gov/pages/brochures/prez.gif
https://transition.fec.gov/pages/brochures/prohib.gif
https://transition.fec.gov/pages/brochures/pubfund_limits_2004.html
https://transition.fec.gov/pages/brochures/pubfund_limits_2004.shtml
https://transition.fec.gov/pages/brochures/pubfund_limits_2007.shtml
https://transition.fec.gov/pages/brochures/pubfund_limits_2008.shtml
https://transition.fec.gov/pages/brochures/pubfund_limits_2011.shtml
https://transition.fec.gov/pages/brochures/pubfund_limits_2012.shtml
https://transition.fec.gov/pages/brochures/pubfund_limits_2015.shtml
https://transition.fec.gov/pages/brochures/pubfund_limits_2016.shtml
https://transition.fec.gov/pages/brochures/rad_brochure.pdf
https://transition.fec.gov/pages/brochures/ReportsAnalysisDivision.shtml
https://transition.fec.gov/pages/brochures/slcol2.jpg
https://transition.fec.gov/pages/brochures/spec_notice_brochure.pdf
https://transition.fec.gov/pages/brochures/ssfvnonconnected.pdf
https://transition.fec.gov/pages/brochures/statefed.shtml
https://transition.fec.gov/pages/brochures/submission_dates_2016.pdf
https://transition.fec.gov/pages/brochures/table.jpg
https://transition.fec.gov/pages/brochures/treas2.gif
https://transition.fec.gov/pages/brochures/treas3.gif
https://transition.fec.gov/pages/brochures/treas.gif
https://transition.fec.gov/pages/brochures/volact1.shtml
https://transition.fec.gov/pages/brochures/whouse.gif
https://transition.fec.gov/pages/brochures/working.jpg
https://transition.fec.gov/pages/brochures/documents/ChartonContributionLimitsfor2003-04.doc
https://transition.fec.gov/pages/brochures/images/clip_image002_000.gif
https://transition.fec.gov/pages/brochures/images/clip_image002.gif
https://transition.fec.gov/pages/brochures/images/clip_image004_000.gif
https://transition.fec.gov/pages/brochures/images/clip_image004.gif
https://transition.fec.gov/pages/brochures/images/clip_image006_000.gif
https://transition.fec.gov/pages/brochures/images/clip_image006.gif
https://transition.fec.gov/pages/brochures/images/limit.gif

**Comment by dorothyyeager** [comment]
Pages getting hits in pages/ directory:
![image](https://user-images.githubusercontent.com/24437369/105721294-6ab0cb80-5ef2-11eb-841d-3df8176d07f8.png)

**Comment by patphongs** [comment]
This will eventually be addressed in our transition inventory work. Closing this issue.
