### ISSUE TITLE
Upgrade local CMS DB to use Postgres 11

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3757]
### Summary

**What we're after:**
_The CMS postgres databases in our cloud environment is now using postgres version 11. We need to make sure our local environment is running the same version._

### Related issues

- https://github.com/fecgov/openFEC/issues/4332
- https://github.com/fecgov/fec-eregs/issues/499

### Completion criteria

- [x] Local CMS database is running using Postgres V11. Document somewhere for staff to repeat process done already by @fec-jli 
- [x] The read.me is updated. 

### Tech steps or considerations

- [x] Try running both Postgres V11 and Postgres V10.7 locally
- [x] Run local CMS database using Postgres V11

**Comment by jason-upchurch** [comment]
Thank you @johnnyporkchops and @fec-jli for your help with locating a PG11 .dump file. I moved a copy of the latest one to the FEC  CMS DB for devs as part of the PR review.

**Comment by jason-upchurch** [comment]
working on documenting switching between different versions of postgres (openFEC and fec-cms use different versions)
