### ISSUE TITLE
500 errors in production showing test environment banner

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#3760]
500 errors in production showing test environment banner. 

Example: https://www.fec.gov/data/candidate/HOMD02214/
Screenshot: 
<img width="1148" alt="Screen Shot 2020-05-14 at 1 47 46 PM" src="https://user-images.githubusercontent.com/31420082/81977320-d9b1f280-95f7-11ea-8a1f-ece7a4d58d28.png">

**Comment by lbeaufort** [comment]
purposefully won't send context to 500 errors. If you need context, you will need to make your own view. 

Django docs: https://docs.djangoproject.com/en/3.0/ref/views/#the-500-server-error-view
Custom 500 views:https://stackoverflow.com/questions/17662928/django-creating-a-custom-500-404-error-page

**Comment by patphongs** [comment]
PR deployed, closing
