### ISSUE TITLE
Design navigation menus to improve path to landing page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3763]
**What we're after:**
From the [research](https://github.com/fecgov/fec-cms/issues/3675) completed in an effort to improve navigation, one task is to improve the main navigation on the site to improve the pathway to the landing pages, specifically the data landing page. Users tend to get to the data landing, but only in a roundabout way through the breadcrumbs. 

At present, users look at the link to the landing page more as a title than a link. We should make it look like our other links to improve access to this page. 

**Current menu:**
<img width="1232" alt="Screen Shot 2020-05-14 at 10 16 16 PM" src="https://user-images.githubusercontent.com/31663028/82004333-97f16e00-9630-11ea-9171-fe30bb267268.png">

### Related issues
- https://github.com/fecgov/fec-cms/issues/3764 Add links to visualizations in search results
- https://github.com/fecgov/fec-cms/issues/3765 Design a feature discovery tool
- https://github.com/fecgov/fec-cms/issues/3766 Identify places to track navigation to data viz through Tag Manager

### Completion criteria
- [x] Design navigation menu that improves pathway to data landing pages
- [ ] Open implementation issue

**Comment by JonellaCulmer** [comment]
@patphongs @PaulClark2 @AmyKort Below are three mock-ups for the new navigation menu. All three contain minor changes to the existing navigation. The only thing I'm really focused on in these versions is making it easier to get to the data landing page. 

My preference is version 1. Which simply makes the data landing page just another link like all the others. We have seen over and over again, how easily our users are getting to internal links that we list in the navigation - so I do not want to make that any more difficult or change those links too greatly - at least not to simply make improvements for the data viz navigation. I still want all of our menus to be consistent across all four buckets. 

**Version 1:** This version will also allow us to easily change the text for the data landing page. For example, if we change the landing page to better fit the definition of a "data dashboard" we can easily change the language to "Data Dashboard >>"

![Data_menu_1](https://user-images.githubusercontent.com/31663028/82080692-0b3bc400-96b3-11ea-83e6-b219931fe119.png)


**Version 2:**

![Data_menu_2](https://user-images.githubusercontent.com/31663028/82080703-0e36b480-96b3-11ea-8bdf-267728fc6756.png)


**Version 3:** This version allows for a bit more space to link to some data visualizations, but again doesn't change too much in the menu. 

![Data_menu_3](https://user-images.githubusercontent.com/31663028/82080708-11ca3b80-96b3-11ea-8627-38e3e57dde69.png)

**Comment by AmyKort** [comment]
These all look good to me @JonellaCulmer . Thank you. Do you think we could make some time early next week to talk through the benefits of each of these options?

**Comment by patphongs** [comment]
Thanks @JonellaCulmer! I also like version 1 as the "All data" link is just part of the list rather than being seen as a heading. One of the problems we have with the current "Explore all data" link is that users think it's a heading and won't click on it because of that. I can see why we wanted it to be a "heading" though, as "All data" encapsulates everything in the list of data links. But that doesn't necessarily mean we need to show it in a hierarchy form.

**Comment by lbeaufort** [comment]
@JonellaCulmer @patphongs I agree that option number one makes the "All data" page look most like a link. If we go forward with an implementation, we could consider a feature flag to do A/B testing. 

Regarding adding the `>>` next to the links, would that change a pattern on our site? I imagine we'd want to make the change for all menu links.

For implementation, let's remember to add an eregs ticket to keep menus consistent with the CMS.

Thanks for your work on this, @JonellaCulmer!

**Comment by JonellaCulmer** [comment]
@lbeaufort @patphongs Let's move forward with version one then. 

To your point, @lbeaufort I think I can just update the eregs and transition tickets with the latest version so we're only making one change. (cc: @dorothyyeager) 

Here are mockups of the other header navs: 
<img width="627" alt="Screen Shot 2020-06-01 at 10 10 20 AM" src="https://user-images.githubusercontent.com/31663028/83417463-2109f280-a3f0-11ea-9fa8-73a3913a4787.png">

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issues:

- https://github.com/fecgov/fec-cms/issues/3797 Update top-level menus on .gov
- https://github.com/fecgov/fec-cms/issues/3737 Make drop down menu on transition match drop down menu on fec.gov
- https://github.com/fecgov/fec-cms/issues/3754 Make drop down menu on regulation site match drop down menu on fec.gov
