### ISSUE TITLE
Add 10 item limitation to filters on schedule a, b and e datatables

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3779]
**What we're after:** Following a brief outage on 5/21, we need to implement front-end filter limitations on Schedule A, B and E for: **name, ZIP (limit 5), employer, occupation, and city.** 

Datatables where we're making the change: [All receipts](https://www.fec.gov/data/receipts/), [Individual contributions](https://www.fec.gov/data/receipts/individual-contributions/), [Disbursements](https://www.fec.gov/data/disbursements/), [Independent expenditures](https://www.fec.gov/data/independent-expenditures/)

**All receipts and individual contributions datatables:** 
- [x] Limit 10 for:
- Name - `contributor_name`
- Zip - `contributor_zip`
- City - `contributor_city`
- Occupation - `contributor_employer`
- Employer - `contributor_occupation`

**Disbursements datatable:** 
- [x] Limit 10 for:
- Recipient name or ID - `recipient_name` (takes ID or name)
- City  - `recipient_city`

**Independent expenditures datatable:** 
- [x] Limit 10 for:
- Candidate name or ID (`candidate_id`)

**Related ticket:**
- https://github.com/fecgov/openfec/issues/4118
- https://github.com/fecgov/openFEC/issues/3902

**Completion criteria:**
- [x] Implement 10 item limitation for the aforementioned filters on the above datatables. Mimic the 10 committee limitation interaction. Design work here: fecgov/fec-cms#3272

Future work:
- Figure out how to log that the limit is triggered in the server logs

**Comment by patphongs** [comment]
This work has already been merged, closing.
