### ISSUE TITLE
Redirect old calculators to new one and remove old calculators

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3783]
**What we're after:** After the new calculator is deployed we need to implement redirects from the old three calculators, currently on transition. We also need to remove the old calculators. 

Old calculators:
1. https://transition.fec.gov/af/afcalc_20190101.shtml
2. https://transition.fec.gov/af/afcalc_20171228.shtml
3. https://transition.fec.gov/af/afcalc_20170101.shtml

There are also some related links and older calculators on transition that should be redirected too. The content team has captured these on its spreadsheet for redirects.

(Eventual) Link to new calculator:
https://www.fec.gov/legal-resources/enforcement/administrative-fines/calculating-administrative-fines/#calculating-a-fine

**Completion criteria:**
- [x] Add redirects to transition to forward any direct links to the new calculator
~- [ ] Delete the calculators on transition (after backing them up for code preservation purposes) - we'll handle the take down in https://github.com/fecgov/fec-cms/issues/3843.~

**Comment by dorothyyeager** [comment]
There's some additional administrative fine files in transition to redirect and take down beyond the ones noted in this comment. Content team has put them into our spreadsheet and will take care of it. Our usual process for redirects is noted in #3827 which is our ticket for tracking non-admin fine redirects that need doing. We plan to do them all in one bunch.

**Comment by dorothyyeager** [comment]
The redirect PRs are ready for review by @patphongs

**Comment by JonellaCulmer** [comment]
@dorothyyeager Can this ticket be closed in favor of https://github.com/fecgov/fec-cms/issues/3827?

**Comment by dorothyyeager** [comment]
Hi @JonellaCulmer - no. We're experiencing issues with the redirects this issue is tracking. The other issue's redirects worked just fine and I closed it this AM.

**Comment by dorothyyeager** [comment]
Have put in a PR to get these redirects in. Once they are merged and tested, we can close this ticket and move on to the take down ticket.

**Comment by dorothyyeager** [comment]
Redirects merged, deployed, testing and working.

Closing this ticket, and we'll take down the pages in #3843
