### ISSUE TITLE
[JUNE] - Manually update wagtail global search index 

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#3785]
Summary
What we're after:
We need to update the global search.gov index for new pages that were published in June.

Related issues
#3715

Completion criteria
 

- [ ] Follow instructions under [Adding CMS pages to the index](https://github.com/fecgov/fec-cms/blob/develop/fec/search/management/instructions.md#adding-cms-pages-to-the-index)
- [ ]  Create ticket for next month June for manual wagtail global search index

**Comment by patphongs** [comment]
Last indexed page count: 870 (indexed on 05/27/2020)
New indexed page count: 882 (indexed on 06/30/2020)

Created new ticket to scrape and index the pages for July https://github.com/fecgov/fec-cms/issues/3874
