### ISSUE TITLE
Add language to filters with 10 item limits

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3790]
**What we're after:** As work moves forward with the 10 item limitation for schedule A, B, and E datatables, we need to make it clear that a limitation exists so users are not "penalized" and confronted with an error before knowing there was a limit. 

**Completion criteria:**
- [x] Mock up filters with text that explains the 10 item limitation for specific filters. Verify list of filters based on this PR: https://github.com/fecgov/fec-cms/pull/3780
- [x] Flag for front-end to add to aforementioned PR/implementation work

**Comment by JonellaCulmer** [comment]
First draft with 10 item limit language added with @dorothyyeager's help. 

Let me know if you have any concerns/feedback @patphongs and @dorothyyeager. 
I also moved up the larger blurb associated with the time period. 

<img width="211" alt="Screen Shot 2020-06-01 at 10 01 21 AM" src="https://user-images.githubusercontent.com/31663028/83416574-e05da980-a3ee-11ea-920c-4a89d1c775c5.png">

**Comment by patphongs** [comment]
@JonellaCulmer These look good to me, the only thing that we can't do is a line break for the helper text. So for the `Occupation` field, there is already helper text there. We can only add "Limit 10 occupations" to that helper text and can't make it a line break.

**Comment by JonellaCulmer** [comment]
@patphongs Thanks for clarifying that. That's just how the text wrapped for me. No need to include a line break.

**Comment by patphongs** [comment]
These labels have been applied within this PR: https://github.com/fecgov/fec-cms/pull/3780#issuecomment-637733676.

**Comment by patphongs** [comment]
This work has already been merged. Closing.
