### ISSUE TITLE
Change style sheet class name to is_active_committee

### ISSUE THREAD

**Issue by fec-jli** [fecgov/fec-cms#3796]
### Summary

**What we're after:**
_Current style sheet class name is is_active and is_terminated, we should change name to
is_active_committee and is_terminated_committee_

### Related issues

_List any relevant related issue(s)_

- [https://github.com/fecgov/fec-cms/pull/3781](https://github.com/fecgov/fec-cms/pull/3781)

### Completion criteria
- [ ] change style sheet class name to is_active_committee and is_terminated_committee

### Tech steps or considerations (optional)
- [ ] change style sheet class name to is_active_committee and is_terminated_committee in _datatables.scss
- [ ] Modify committees-single.jinja to use new class

**Comment by patphongs** [comment]
This is effecting the MUR left menu, we need to make sure we fix this before release.

<img width="869" alt="Screen Shot 2020-06-02 at 4 24 05 PM" src="https://user-images.githubusercontent.com/12799132/83566736-7a584b80-a4ee-11ea-9e18-8a8f3a719595.png">

**Comment by patphongs** [comment]
Merged into the release
