### ISSUE TITLE
Update top-level menus on .gov

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3797]
**What we're after:**
Improving navigation to our landing page by making a change to their appearance and location on the menus. While this work was motivated to improve navigation throughout the data section, these changes need to be applied to the other menus for consistency and improve landing page visitation to other sections on the site.

**Related issues:**
- https://github.com/fecgov/fec-cms/issues/3763 Design navigation menus to improve path to landing page
- https://github.com/fecgov/fec-cms/issues/3737 Make drop down menu on transition match drop down menu on fec.gov
- https://github.com/fecgov/fec-cms/issues/3754 Make drop down menu on regulation site match drop down menu on fec.gov

**Completion criteria:**
- [ ] Update menus according to designs. Links should not change, just their arrangement on the menu

**Designs:**
<img width="627" alt="Screen Shot 2020-06-01 at 10 10 20 AM" src="https://user-images.githubusercontent.com/31663028/83433830-7b627d80-a407-11ea-81c5-84d6c1059529.png">

**Future work:**

- Update links on transition and regulations site. Tickets are linked in Related issues section.

**Comment by johnnyporkchops** [comment]
@rfultz -  During the last iteration of the meues, I was thinking, if it helps control responsivity better, we could switch to Grid of Flexbox, which were not fully ubiquitous at the time. It uses CSS Columns now, which seems to work fine.  Just a thought that might make this ticket more fun than it is now.  : -)
