### ISSUE TITLE
Revisit metrics for FEC website to plan for PI13

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3800]
### Summary

**What we are after:**
_Awhile ago, we held a meeting to start seriously looking at important website metrics. We need to follow up on that meeting and make a plan for going forward_

### Related issues

_List any relevant related issue(s)_

- #2743 - Baseline metrics part 2
- https://github.com/fecgov/openFEC/issues/3618 - Baseline metrics part 1

### Action items
- [ ] Revisit linked related issues to discover what happened with them.
- [ ] Consider how to break up next steps into easily digestible chunks

### Completion criteria
- [ ] Results and outcomes are documented for team
- [ ] Follow up tickets entered for PI13 as needed

### Tech steps or considerations (optional)

_List any considerations the tech team should know. Additionally, any specific tech steps can be included here._

- [ ] First
- [ ] Next
- [ ] Then

### Future work

_Other future work that may be needed following this issue's completion._

**Comment by JonellaCulmer** [comment]
This ticket was geared towards the performance improvements that are being addressed currently through the performance epic. We'll close this ticket for now in favor of that epics work here: https://github.com/fecgov/fec-epics/issues/160

Front-end performance metrics work will be handled here: https://github.com/fecgov/fec-epics/issues/185
