### ISSUE TITLE
Add 2020 values to admin fine calculator

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#3803]
### Summary

**What we're after:**
The new admin fine calculator should be updated with the values for 2020, after they're approved and published

**Completion criteria:**
- [x] New penalties are added and functioning properly in the AF calculator

**Comment by JonellaCulmer** [comment]
I emailed the teams responsible for the admin fines and it is currently under review. We should hear something early next week.

**Comment by patphongs** [comment]
This was deployed today
