### ISSUE TITLE
Design solution for candidates with missing data from a committee conversion

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3806]
**What we're after:** For those candidates who convert their candidate committees to PACs mid-cycle or mid-two-year-period, their committee information is lost on their candidate profile pages and the connection between candidate and committee is broken. 

For most candidate and committees pages, our system relies on those committees retaining their candidate committee in order for us to link the two together. When a candidate converts mid-cycle our system does not account for it and it appears, on candidate pages, that no money was raised at all and there is no associated committee. 

**As a data user, I need to be able to find financial data for all 2020 candidates.**

**Completion criteria:**
- [x] Mock up solution that allows for users to find relevant financial data

**Comment by JonellaCulmer** [comment]
Affected candidates we know so far:

**Examples of candidates converting mid-cycle**
- Julian Castro's presidential candidate committee (ID C00693044) also already converted to a PAC. 
- Pete Buttigieg's presidential candidate committee (C00697441) converted to a PAC
- Here's some examples of other House candidate committees that converted to a PAC this cycle: C00634212, C00652594, C00691790.  

**Examples of candidates converting post-cycle**
- Rand Paul's presidential committee (C00575449) converted to a PAC in 2017 after he ran in the 2016 cycle. 
- Scott Brown's PCC (C00560003) converted to a PAC in 2015 after he last ran in the 2014 cycle.

**Comment by patphongs** [comment]
@JonellaCulmer This may help with your design ideas. I mocked up in the code what it would look like if we had a separate error message for these kinds of candidates. We can modify the missing financials error to be whatever you should like it to be. The PR is waiting in the wings until you've finalized the design solution: https://github.com/fecgov/fec-cms/pull/3814

<img width="1004" alt="Screen Shot 2020-06-03 at 6 07 00 PM" src="https://user-images.githubusercontent.com/12799132/83694175-8236ef00-a5c5-11ea-8b25-75a7e95c71d9.png">

**Comment by JonellaCulmer** [comment]
@patphongs Thanks for doing that. Will be a helpful visual aid when I meet with RAD today.

**Comment by JonellaCulmer** [comment]
Notes on the steps taken in RAD for when an authorized committee converts mid-cycle. 

Step 1: The committee amends form 1 to change the committee type. Typically, authorized campaign committee's convert to nonconnected PAC (like Pete Buttigieg). Making this amendment is how RAD is informed, although sometimes committees reach out ahead of time to give a heads up. 

Step 2: RAD sees the change and reviews the amended form. 

Step 3: If both the type and name are changed (since PACs cannot have a candidate's name in the name of the PAC) then RAD makes the conversion in their database. They change both the type of committee and whether the committee is authorized/unauthorized. Typically changing from authorized to unauthorized. This change would appear on the website next day.

Step 4: The committee is transferred from one analyst to another because the committee type has changed. A separate process takes place to update the analyst contact information. 

Before RAD can make the conversion, the committee has to have filed all their reports and they need to be reviewed first. Also, any RFAIs resulting from that final filing review need to be sent out, but waiting for response does not prevent the committee from being converted on FEC's end.

**Comment by JonellaCulmer** [comment]
@AmyKort @PaulClark2 @patphongs @hcaofec @lbeaufort 

Below are the first draft mockups for the Pete problem. Right this particular issues impacts about 3-5 "high-level candidates" include presidential and House candidates. Jaime in RAD is going to send me more names next week, if they exist. But we can use the names in the above comment for now. With those candidates in mind, the language is general to just the campaign committee to PAC conversion. 

I've included links on both the candidate and committee pages to re-establish the connection between both places since that was lost once the committee was no longer authorized by the candidate. Jaime confirmed that the language included is accurate. But I'd still like content (@dorothyyeager) to take a look. 

**Candidate profile page:**

<img width="925" alt="Screen Shot 2020-06-04 at 4 07 16 PM" src="https://user-images.githubusercontent.com/31663028/83805522-08af0780-a67e-11ea-85fd-938e29015b58.png">
**Committee profile page:**

<img width="927" alt="Screen Shot 2020-06-04 at 4 07 34 PM" src="https://user-images.githubusercontent.com/31663028/83805534-0ea4e880-a67e-11ea-98b5-85ca4d9b9436.png">

**Comment by dorothyyeager** [comment]
I do have a suggestion for the language, although I like overall approach. I think it's a good idea to specify the type of PAC it became (a nonconnected committee/leadership PAC). I went with leadership PAC but if people are nervous about that, then I'd sub in "nonconnected committee" and that glossary link. How about this:

Candidate version:
Financial data for this candidate now appears under the committee name Win the Era, following the committees conversion to a leadership PAC (add glossary link) from a principal campaign committee (add glossary link). Before its conversion, this committee was authorized by candidate Buttegieg, Pete.

Committee version:
Financial data for this committee contains funds raised and spent under its former name, Pete for America, Inc., which before it was converted, was a principal campaign committee (add the glossary link). Before its conversion to a leadership PAC (add the glossary link), this committee was authorized by candidate Buttegieg, Pete.

**Comment by JonellaCulmer** [comment]
@dorothyyeager Thanks for the suggestion! Some background on why we chose just "PAC", we thought that we'd have to make few adjustments for different candidates who make this change. But I defer to the group on that level of effort.

**Comment by dorothyyeager** [comment]
Yeah, that's definitely why I wouldn't go with "leadership PAC". By definition they wouldn't be a separate segregated fund, so I was thinking "nonconnected" at least points a user to the pages where the rules for them would be found. But it might be too much, so if everyone prefers PAC, that's OK.

**Comment by PaulClark2** [comment]
@JonellaCulmer @dorothyyeager I think for the first iteration of this "pac" is fine. In this specific case, Win the Era is a non-qualified, non-connected PAC (committee type "N," committee designation "U")

**Comment by lbeaufort** [comment]
@JonellaCulmer this language is very helpful and looks great to me. 

Ideally, the logic in the back end would link to the committee ID and dynamically pull the committee name, in case the committee name changes. I'd also want to make sure the messages only show up for the cycle during which the conversion occurred. cc: @patphongs

**Comment by JonellaCulmer** [comment]
@lbeaufort Those were my same thoughts as well, particularly your second point. Thanks for documenting them so clearly.

**Comment by patphongs** [comment]
@JonellaCulmer In our discussions, we decided to show this special message for the "All years" button as well as the effected cycle, in this case, all 2020 two year time periods. Can you mock up what the message would look like for the "All years" view?

**Comment by patphongs** [comment]
@JonellaCulmer I have two issues with the current design solution:

1. There's no way to query the API for the former committee name. Manually creating a look up would be complex to maintain, especially outside of the API.

2. Minor issue: The committee name must be in all caps as that is how the API prints it, but I think that is in line with how we normally display committee names anyways.

**Comment by JonellaCulmer** [comment]
@patphongs Yeah, I figured. I can update my draft of the mockup to include all caps. Can we hard code the name?

**Comment by patphongs** [comment]
Thanks @JonellaCulmer, I did talk to @lbeaufort about this and I think the path will be the hardcode the former committee names as a look up for now. I was worried if the API would be able to catch up, but @lbeaufort knows the data is there in the filings, we just have to build in the capability.

**Comment by JonellaCulmer** [comment]
Closing in favor of PR: https://github.com/fecgov/fec-cms/pull/3814
