### ISSUE TITLE
Revisit language for download errors

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3810]
### Summary

**What we're after:**
_As a data user who is experiencing a slow download of data or who is unable to download data, I want to be able to know definitively whether the FEC is experiencing a data outage that will be resolved soon or whether I have exceeded my downloads._

When there is a failed download due to a 500 error, the message seems to indicate that the user may have exceeded their maximum downloads. This language should be tweaked to indicate that there is a problem with downloads.

<img width="811" alt="Screen Shot 2020-06-03 at 5 01 47 PM" src="https://user-images.githubusercontent.com/12799132/83688831-fec4d000-a5bb-11ea-82da-5a20c1ec57fb.png">

https://github.com/fecgov/fec-cms/blob/54182e4fbcdb7145a108ffb97dfd7962f2260a62/fec/fec/static/js/modules/download.js#L198

### Error states
- 429 error status indicates that the user has exceeded their maximum downloads

- 500 error status indicates more of a problem with downloads

**Comment by dorothyyeager** [comment]
@patphongs @AmyKort @PaulClark2 -paired with @JonellaCulmer and we are thinking of two separate messages depending on the problem. We were looking at the server error language that refers people to Pingdom and considered using it, but we weren't sure how helpful it was to refer people there in this instance. Please let us know your thoughts.

If downloads exceed max:
Sorry, you have exceeded your maximum downloads for the hour. Please try again later.

If there's an outage on our end:
Sorry, this data failed to download due to a server error.  Please try again later.

**Comment by AmyKort** [comment]
Looks good to me! 

What would show up in the Pingdom alerts under these circumstances?

**Comment by dorothyyeager** [comment]
@AmyKort I'm not quite sure. Pingdom just shows all the various end points. So if one is experiencing a disruption or outage, that will show for that day. Here's a screenshot: 

![image](https://user-images.githubusercontent.com/24437369/83795495-8a4a6980-a66d-11ea-9121-3830001be9c0.png)

**Comment by JonellaCulmer** [comment]
@AmyKort @patphongs @PaulClark2 My concern with using Pingdom is that there isn't a specific area for downloads, at least not what I can see. And it doesn't appear that the downloads issue was captured in any of the statuses. So at this point, it doesn't seem like it would be a helpful inclusion in the error message, unless we were able to adjust what's in pingdom to make it clear that downloads are impacted. Is that possible?

**Comment by AmyKort** [comment]
That makes sense to me @JonellaCulmer . How about we don't include the Pingdom link here. We can look for a better solution/dashboard option in a future iteration.

**Comment by dorothyyeager** [comment]
Final version of language @patphongs  

If downloads exceed max:
Sorry, you have exceeded your maximum downloads for the hour. Please try again later.

If there's an outage on our end:
Sorry, this data failed to download due to a server error. Please try again later.

**Comment by dorothyyeager** [comment]
Closing ticket. Implementation ticket opened at https://github.com/fecgov/fec-cms/issues/3819
