### ISSUE TITLE
Design Election Cycle Summary pages

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3816]
### Summary

**What we are after:**
_The election cycle summaries produced by the Press Office are still on transition and because we want to get off transition, they would like to put them into Wagtail, starting with the home page._

Page to bring over: https://transition.fec.gov/press/campaign_finance_statistics.shtml (main page) and https://transition.fec.gov/press/summaries/2020/ElectionCycle/2020DataTitle.shtml (example for a cycle) but that page links to many other transition pages. We may want to have @JonellaCulmer take a look at the best way to bring these summaries over and then plan for that work in PI13 because the next deadline for these pages is August.

### Completion criteria

- [x] Mockup the migrated pages
- [ ] Share preliminary mockups with Press office and make mockup adjustments
- [x] Tickets for future implementation work are created

### Tech steps or considerations (optional)

We want to keep it simple and make sure that the Press Office will be able to use the new pages going forward.

### Future work

_Other future work that may be needed following this issue's completion._

**Comment by JonellaCulmer** [comment]
Breakdown of pages we need to account for in this work: 

**Campaign finance statistics:**
https://transition.fec.gov/press/campaign_finance_statistics.shtml

**Election cycle page:** (Do we still need these? Is it important that we link to press releases still? Perhaps we can find a new home for them? Maybe on the page listed below?)
https://transition.fec.gov/press/summaries/2020/ElectionCycle/2020DataTitle.shtml

X-Month Candidate or committee page: 
https://transition.fec.gov/press/summaries/2020/ElectionCycle/15m_PresCand.shtml
*Expecting 6 segments of data: 6-month, 12-month, 15-month, 18-month, 21-month, and 24-month

@AmyKort @dorothyyeager Please advise if there's anything I'm missing.

**Comment by dorothyyeager** [comment]
I agree with your breakdown @JonellaCulmer - we do need to link these to press releases though (or have a conversation with press about eliminating those). The election cycle page is sort of the table of contents for the election cycle, so it would be the point of entry for someone wanting access to all of the statistics from a cycle.

**Comment by JonellaCulmer** [comment]
Per a discussion on these pages: (cc: @AmyKort @dorothyyeager @patphongs) 
- Mock-up how these pages can coexist in a searchable fashion, or another dynamic way. What's the IA for these pages?
- Which wagtail templates do we want to use, for which pages? For easy editing and future maintenance.

**Comment by JonellaCulmer** [comment]
@AmyKort @dorothyyeager We call these chunks of data different things. I think we need to come to a decision on what to call these moving forward. And hopefully reduce this list down to one.

- Historical statistics
- Campaign finance statistics
- Data summary tables
- Data summaries
- Data summaries of financial activity
- Statistical tables

There's also: Congressional candidates and Campaign summary tables.

When we move these pages over I think we need to try to reduce this list down to one or two names.

**Comment by JonellaCulmer** [comment]
Preliminary mockups are here. I plan to share these with the Press Office when we meet with them later this week. 

<img width="351" alt="Screen Shot 2020-07-22 at 9 53 02 AM" src="https://user-images.githubusercontent.com/31663028/88184999-659c5800-cc01-11ea-8aec-20e06c61cfd9.png">
<img width="351" alt="Screen Shot 2020-07-22 at 9 53 20 AM" src="https://user-images.githubusercontent.com/31663028/88185000-659c5800-cc01-11ea-99f3-b0bc9fa51267.png">
<img width="260" alt="Screen Shot 2020-07-22 at 9 53 55 AM" src="https://user-images.githubusercontent.com/31663028/88185003-6634ee80-cc01-11ea-96c6-5e700470705f.png">

**Comment by AmyKort** [comment]
Thank you @JonellaCulmer !

**Comment by patphongs** [comment]
Thanks @JonellaCulmer, I have one note about these mock ups. I'm wondering what the importance of the "Published date" column is in the filtered table view. We did not give these dates in the HTML view on transition, so I'm wondering if the start and end dates would be more useful for these reports.

**Comment by JonellaCulmer** [comment]
@patphongs Great point. I included them on the preliminary mockup but I'm really hoping to get from the Press Office an idea of what is most important at this stage and hopefully get a list from them of people (or groups of people) whom they think would be appropriate to user test.

**Comment by JonellaCulmer** [comment]
A meeting with the Press Office has been scheduled for Friday. Moving this to blocked while we wait for that discussion and resulting takeaways.

**Comment by JonellaCulmer** [comment]
Other resource to track:  https://www.fec.gov/campaign-finance-data/presidential-campaign-finance-summaries/

Need to consider how we can include this information into the presidential page.

**Comment by patphongs** [comment]
@JonellaCulmer I've set up a prototype for the congressional data summary table on [feature](https://fec-feature-cms.app.cloud.gov/campaign-finance-data/congressional-candidate-data-summary-tables/). I attempted to put all the data in one page, but it was too much HTML to insert into one page as I got an error. So we'll split them up by Summary table type.

**Comment by JonellaCulmer** [comment]
I've sent the below updated mockups to the Press Office for their content additions and any other last feedback. This is blocked while we wait for that information. 

![Historical stats_1](https://user-images.githubusercontent.com/31663028/89063525-53739580-d336-11ea-95d4-9c55d134ed4c.png)
![Historical stats_2](https://user-images.githubusercontent.com/31663028/89063530-540c2c00-d336-11ea-945c-2acaf571f5cf.png)
![Historical stats_3](https://user-images.githubusercontent.com/31663028/89063533-540c2c00-d336-11ea-8a52-fa2cf59d8b2c.png)

**Comment by JonellaCulmer** [comment]
After incorporating feedback from the Press office. Below are the mock-ups with which we are moving forward. Here is the approved content and other details needs for this project:
https://docs.google.com/document/d/1gw1ZrXzXjKP1GavgsLW1HkcCdlGvJDaDyxilODSAkDE/edit#heading=h.3mlmgt6o1ktz

### Main nav
![Campaign stats_1](https://user-images.githubusercontent.com/31663028/89459099-252af700-d736-11ea-838c-ceee4dc92245.png)
### Campaign finance statistics browse data page
![Campaign stats_2](https://user-images.githubusercontent.com/31663028/89459100-25c38d80-d736-11ea-8d01-96ed6b74ab89.png)
### Campaign finance statistics summary page
![Campaign stats_3](https://user-images.githubusercontent.com/31663028/89459103-25c38d80-d736-11ea-8523-300f73fc6c01.png)
### Data table pages
![Campaign stats_4](https://user-images.githubusercontent.com/31663028/89459107-25c38d80-d736-11ea-81b5-a91519b5c0bb.png)
### Archived campaign finance statistics page
![Campaign stats_5](https://user-images.githubusercontent.com/31663028/89459108-25c38d80-d736-11ea-8a8f-42846d18a536.png)

**Comment by JonellaCulmer** [comment]
Closing in favor of:
- Implement filterable campaign finance data summaries https://github.com/fecgov/fec-cms/issues/3943
- Migrate historical stats pages on transition to wagtail https://github.com/fecgov/fec-cms/issues/3958
