### ISSUE TITLE
Update calendar entries with "Event Name"

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#3818]
### Summary

When entering information into the Disclosure database, we add a field for "Event Name". When we transitioned to the new website, that information dropped off the entry. Trying to see if it can be added back.

When we enter data into the Disclosure database, we enter information for:
-Event Name
-Category
-Date
-Location
-URL
-Description

Right now, the information for the category, date, location, url, and description show up:

![image](https://user-images.githubusercontent.com/40633757/83796170-94b93300-a66e-11ea-8fdd-59a6d08dd0ea.png)

![image](https://user-images.githubusercontent.com/40633757/83796194-9c78d780-a66e-11ea-9f33-ed5117d6db1b.png)

### Related issues

- #2315 
- #3817 

### Completion Criteria

- [ ] Add event name to calendar entry

**Comment by lbeaufort** [comment]
In the API, `Event Name` is labelled `summary`. Example: https://api.open.fec.gov/v1/calendar-dates/?api_key=DEMO_KEY&per_page=500&event_id=6045

In the front-end, I think we need to change this:
https://github.com/fecgov/fec-cms/blob/32e66a808ba39918f87371734fcc2ebdc89cc6fa/fec/fec/static/js/modules/calendar.js#L175-L187

**Comment by JonellaCulmer** [comment]
@johnnyporkchops @djgarr @lbeaufort @patphongs 

Below are mockups of what the tooltip will look like on the calendar view. I plan to provide additional mockups for the view on mobile/list view as well. This is what I have so far. [To achieve this look we will need to address the issue in this ticket as well](https://github.com/fecgov/fec-cms/issues/3979). It's possible that both can be achieved with a single PR. 


![calendar_mockup](https://user-images.githubusercontent.com/31663028/94863179-0ed4ab00-0408-11eb-9930-a43f354175ee.jpg)

<img width="787" alt="Screen Shot 2020-10-01 at 5 00 30 PM" src="https://user-images.githubusercontent.com/31663028/94863183-0ed4ab00-0408-11eb-84d4-27b2dce2b49e.png">

**Comment by djgarr** [comment]
These look good to me. Thanks!

**Comment by JonellaCulmer** [comment]
@johnnyporkchops @djgarr @patphongs @lbeaufort @dorothyyeager 
Here's the improved list view that includes the event title (aka summary). One thing of concern as we  move forward is the language we use in the titles (and everywhere). Because, based on the API we're abbreviating presidential as "prez" and congressional as "cong". The GPO style guide appears to use con and cong as abbreviations. 

Some things to note in both of these views is the addition of "Location:" language. Currently states are abbreviated, but that's not in the API, so not sure how that's happening. 

Also, I modified the date area to show the day of the week. Ex. "Wednesday, December 3, 2020"

![Calendar_listview](https://user-images.githubusercontent.com/31663028/95127111-7733cd00-0725-11eb-9173-7d2e4b99180f.jpg)

**Comment by patphongs** [comment]
Thanks @JonellaCulmer, mock ups look good. I think the data in the calendar endpoint is ported directly from the internal calendar tool database without much change. So it's possible the internal tool does not abbreviate states, and hence it gets imported into the calendar endpoint not abbreviated.

**Comment by JonellaCulmer** [comment]
@patphongs Thanks for that info. It appears that sometimes we abbreviate and sometimes we don't. @djgarr Do you think we abbreviate when it's more than one place? Or is there another reason? I think we need to be consistent in all places. 

Examples:
<img width="625" alt="Screen Shot 2020-10-06 at 9 10 35 AM" src="https://user-images.githubusercontent.com/31663028/95205787-dcce9a80-07b3-11eb-9ea0-6fc206718092.png">

**Comment by djgarr** [comment]
@JonellaCulmer You are correct. When it's only one state, I've been spelling it out when entering the information into Disclosure. When it's more, I've been going with the abbreviations

**Comment by JonellaCulmer** [comment]
@djgarr Can the lists be long? The second example I showed with two locations is short, but are there really longs lists too? Like 10-15 locations?

**Comment by djgarr** [comment]
@JonellaCulmer Yes 
![image](https://user-images.githubusercontent.com/40633757/95221660-b0237e80-07c5-11eb-8577-bd791ab63ae9.png)

**Comment by JonellaCulmer** [comment]
@djgarr I think we're good to leave it as is for now then! Thanks! I'm going to open up a followup implementation ticket for this.

**Comment by JonellaCulmer** [comment]
Closing in favor of #4111
