### ISSUE TITLE
Update 2020 meeting dates when new dates are announced

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3822]
### Summary

**What we are after:**
_New meeting dates for 2020 are forthcoming. We need to create those meeting pages after they are announced._

### Completion criteria

- [x] When dates are available for next set of 2020 meetings, meeting pages are created in Updates
Format for slugs: month-day-year-open-meeting (for open meetings) and month-day-year-executive-session (for executive sessions)
- [x] Promote tabs are filled in. Example:
![image](https://user-images.githubusercontent.com/24437369/84421555-b9bb2200-abe9-11ea-98b4-d50bbb995c7a.png)

- [ ] Let calendar editor in Info Div and Commission Secretary know when posted.

**Comment by dorothyyeager** [comment]
Moving this to blocked. The dates have been approved; the Commission Secretary will signal us when the Chair is ready to post them.

**Comment by dorothyyeager** [comment]
And the Chair is ready to post them; moving to assigned.

**Comment by kathycarothers** [comment]
The new dates have been added to the executive session page.
