### ISSUE TITLE
Document workflow for posting to website status

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3839]
### Summary

**What we're after:**
_As a FEC developer, we need to be able to follow a workflow on how to update the website status page so that this is a streamlined process._

### Related issues

- #3838 

### Completion criteria

- [ ] Create a draft workflow on how to update the website status page.
- [ ] Create a future ticket: Incorporate these steps in our incident response documentation: https://github.com/fecgov/fec-accounts/blob/master/troubleshooting.md

**Comment by JonellaCulmer** [comment]
Draft status page service disruption guidance:
https://docs.google.com/document/d/1vE3zgh2Mh5h8h07ob5EXi9capgB-e5Ic0nR_R9Imb8Y/edit#

Draft status page message templates: 
https://docs.google.com/document/d/1DapPOsnSN7Q9P3E6OM2BHqYlHKj5ELHjt49BRpFFG5U/edit

**Comment by JonellaCulmer** [comment]
@patphongs @lbeaufort Do we want to share this with the team for their buy-in before we finalize it with other offices in this 13.4 ticket: https://github.com/fecgov/fec-cms/issues/4003

**Comment by JonellaCulmer** [comment]
Updated language to add homepage banner process. 

Closing now in favor of #4011
