### ISSUE TITLE
[AFTER RELEASE 06/23] Change tv ad examples html in Wagtail

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#3840]
### Summary
Related PR: https://github.com/fecgov/fec-cms/pull/3812
**After 06/23 release deployment:**
Make changes to these two live pages to reflect the simplified structure (below). Remove all css in the html block and replace html. Be sure to put the video embed URL.

To be published after PR is deployed to production as part of 06/23 release (existing pages wont break upon deploying this, we just need to change them after):

- [x] **Edit:** https://fec-prod-proxy.app.cloud.gov/admin/pages/10811/edit/
  **Live page:** https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/party-committee-independent-expenditure-tv-disclaimer-ad/

- [x]  **Edit:** https://fec-prod-proxy.app.cloud.gov/admin/pages/10616//edit/
  **Live page:** https://www.fec.gov/help-candidates-and-committees/making-disbursements/advertising/candidate-television-ad-example/

**New html structure:** 
```
<div class="video-frame">
   <div class="iframe-container">
    <iframe src="https://www.youtube.com/embed/REOm_O2VJcc" rel=0 frameborder="0" allowfullscreen></iframe>
   </div>
</div>
```

**Comment by djgarr** [comment]
Updated the code on the two pages

**Comment by johnnyporkchops** [comment]
@djgarr Changes look good!
