### ISSUE TITLE
[After redirects are tested] Take down transition pages recently redirected (Admin Fines, enforcement, election results)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3843]
### Summary

**What we are after:**
_We are getting things taken off of transition!_

### Related issues

#3827 (12.5 redirects) - This issue is closed
#3789 (Deploy calculator)
#3783 (Redirect old calculators) - This issue is still open; PR is ready for review.

### Completion criteria
AFTER we close the related issues above:
- [ ] The following pages/directories are removed from transition and from the search.gov index of transition pages (if they are there).

/af/af.shtml
/af/afcalc_20190101.shtml - note: calculators should be backed up for code preservation purposes
/af/afcalc_20171228.shtml
/af/afcalc_20170101.shtml
/af/afcalc_20130725.shtml
/af/afcalc_20160701.shtml
/af/afcalc_post-200907.shtml
/af/documents/2016AFPRegulations.pdf
/af/pay.shtml
/af/payment/index.shtml

/elections.html

/general/FederalElections2016.shtml

/law/procedural_materials.shtml

/pubrec/electionresults.shtml

These directories and all files in them:
/pubrec/fe2020/
/pubrec/fe2018/
/pubrec/fe2016/
/pubrec/fe2014/
/pubrec/fe2012/
/pubrec/fe2010/
/pubrec/fe2008/
/pubrec/fe2006/
/pubrec/fe2004/
/pubrec/fe2002/
/pubrec/fe2000/
/pubrec/fe1998/
/pubrec/fe1994/
/pubrec/fe1992/
/pubrec/fe1990/
/pubrec/fe1988/
/pubrec/fe1986/
/pubrec/fe1984/
/pubrec/fe1982/

**Comment by dorothyyeager** [comment]
As of June 16, we still have three redirects on that list that we need to get working, so need to hold off on this ticket for a few days. I'll add a block note.

**Comment by dorothyyeager** [comment]
@rfultz The redirects are all working, so please feel free to take these pages off transition. Thank you!

**Comment by rfultz** [comment]
@dorothyyeager or @kathycarothers this is ready for your review. They should all be gone now

**Comment by kathycarothers** [comment]
@dorothyyeager @rfultz Went through and all the pages are redirecting. I didn't experience any problems going from transition over to the redirected page. Make sense?
