### ISSUE TITLE
Wagtail server error after authentication.

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#3848]
### Summary
After logging into wagtail and authenticating I received an error where I normally see "Home," see screenshots below.

### Screenshots
Error:
![image](https://user-images.githubusercontent.com/33758291/84807563-6f64e700-afd5-11ea-992c-2097b15ea37c.png)

Normal:
![image](https://user-images.githubusercontent.com/33758291/84807892-e69a7b00-afd5-11ea-9082-a7db717c9f5d.png)

### Frequency
This is the first time it's happened. It occurred somewhere between 8:05 and 8:10am on Tuesday, June 16th.

### How to Reproduce
1. log into wagtail via cloud.gov
2. authenticated using google authentication
3. Click "pages"

### Device, browser, etc
Firefox 68.9.0esr (64-bit)

### Misc
This did not prevent me from accessing pages because I could use other links and bread crumbs to navigate to where I needed to go.

 The issue resolved itself after I closed all of my firefox windows and re-opened wagtail.

**Comment by JonellaCulmer** [comment]
No longer experiencing this issues - so closing.
