### ISSUE TITLE
Move the Best Efforts section off of Recording Receipts onto its own page

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#3849]
### Summary
The content team is undertaking work to convert the _Recording Receipts_ pages from Custom templates to a Resource templates because the Resource template is better suited for pages with a large amount of content. One section of _Recording Receipts_, Best Efforts, is particularly large and could benefit from breaking off onto its own page. Being a stand alone page would allow us to link directly to Best Efforts advice on other parts of the site.

There are four recording receipts pages:
- [Candidate committee recording receipts](https://www.fec.gov/help-candidates-and-committees/keeping-records/records-receipts/)
- [Party committee recording receipts](https://www.fec.gov/help-candidates-and-committees/keeping-political-party-records/recording-receipts-party-committee/)
- [Nonconnected recording receipts](https://www.fec.gov/help-candidates-and-committees/keeping-pac-records-nonconnected/recording-receipts/)
- [SSF recording receipts](https://www.fec.gov/help-candidates-and-committees/keeping-ssf-records/recording-receipts-ssf/)

### Related issues
#3767 RAD FAQ: new site content

### Completion criteria
- [x] Create Best Efforts page (using resource template)
- [x] Remove Best Efforts content from the _Recording Receipts_ pages
- [x] Add link to the Keeping Records pages 
- [x] Have content review updated pages one last time

### Future work
Insert links on other pages we want to link to the new best efforts pages.

**Comment by djgarr** [comment]
Reviewed by Content on 10/30 and 11/10

**Comment by djgarr** [comment]
Sent to OGC for review on 11/10/2020

**Comment by djgarr** [comment]
Everything has been reviewed and published
