### ISSUE TITLE
Fix admin fine button in IE

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3855]
**What we're after:**
In internet explorer, the button "Calculate estimated fines" to open the admin fine calculator does not work. We need to fix this bug so users across all browsers are able to access the feature. 

### Completion criteria
- [x] Button to open admin fine calculator in IE functions and opens the calculator

![image001](https://user-images.githubusercontent.com/31663028/85034839-7fed9c80-b150-11ea-9c76-f702b670abbf.jpg)

**Comment by johnnyporkchops** [comment]
@JonellaCulmer : We can change the html to to make it work in IE:
```
<a href="#" class="js-admin-fines-calc-modal button button--cta button--go" aria-controls="modal-gov-fec-calc-af" data-a11y-dialog-show="modal-gov-fec-calc-af">Calculate estimated fines</a>  
```
IE does not like the nested link in button

**Comment by rfultz** [comment]
Yeah, there should only be empty text inside buttons, not other elements

**Comment by JonellaCulmer** [comment]
We tested the code and it works in IE, Chrome and Firefox. Closing this out John!
