### ISSUE TITLE
Make a plan to move pages off pubrec/ in transition

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3861]
### Summary

**What we are after:**
_Public Records has migrated many pages to Wagtail. In other cases like Pacronyms, they've discontinued the publication. Because these older transition pages are still heavily used and directly linked by many outside sources, we need to get them redirected to current content and then remove them from transition. This issue is to plan that work for PI13._

### Related issues

- #3755 - similar issue for Information Division publications

### Completion criteria

- [x] Review all the files in the pubrec/ directory and determine if they already have a home we can redirect to (or are redirecting to). Add to spreadsheet and redirect in #3379 
- [x]  For files we are already redirecting, need to add them to the take-down list.
- [x]  Confirm proposed redirects with Public Records (For example, Public Records wants to redirect Pacronyms to https://www.fec.gov/introduction-campaign-finance/how-to-research-public-records/pacs-parties-and-other-committees/
- [x]  Make any needed follow-up tickets for PI13

### Future work

Redirects put in - #3379
Files to be removed

**Comment by dorothyyeager** [comment]
I've identified potential redirects. We will not need to create any new pages. I've sent the list of proposed redirects to Public Record to approve. Once we hear back, we'll be able to proceed with the redirects.

**Comment by lbeaufort** [comment]
Just noting that Pacronyms are referenced at the bottom of this page: https://www.fec.gov/data/browse-data/?tab=committees

<img width="753" alt="Screen Shot 2020-06-30 at 5 11 05 PM" src="https://user-images.githubusercontent.com/31420082/86177466-b7672c00-baf4-11ea-8a13-3724b533d243.png">

**Comment by dorothyyeager** [comment]
Thanks @lbeaufort - I'll put in a ticket for that to be removed since that's a hard-coded page. In the meantime, assuming Public Records is good with the redirects, the redirects will take users to a page that will tell them how to research PACs.

**Comment by dorothyyeager** [comment]
Public Records has approved most of the redirect list. They are planning to make a few new pages to address 1998 election results and state records office, so we will hold off on taking those pages down and redirecting for now.

**Comment by dorothyyeager** [comment]
We can go ahead and close this ticket and take care of the redirects in #3379. Here are the files to be redirected and their new homes (as approved by Public Records):

![image](https://user-images.githubusercontent.com/24437369/87161280-4d881880-c292-11ea-81f9-54a15952756e.png)




Public Records is working on new content for the CMS to replace these files:
![image](https://user-images.githubusercontent.com/24437369/87161376-6f819b00-c292-11ea-85b1-9237f4c046b0.png)


Will put in a ticket for redirecting those files once Public Records has migrated the content.

With the plan in place, we can close this ticket and move on to the redirects we can do now.
