### ISSUE TITLE
[Do on July 6] Update website to reflect Commissioner departure

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3868]
### Summary

**What we are after:**
_Commissioner Hunter is leaving the FEC effective July 3, 2020. We need to update the website to reflect her departure after that day._

### Completion criteria
In Wagtail page for Commissioner Hunter, following boxes are filled in:

- [x] "Sworn in" is filled in with her swearing-in date (we're getting this soon from her office)
- [x] "Term expiration" is filled in with 2020-07-03
- [x] After page is published, verify that Commissioner Hunter is listed on https://www.fec.gov/about/leadership-and-structure/commissioners/ with term dates shown
- [x] Also verify that current Commissioner listings on home page and https://www.fec.gov/about/leadership-and-structure/ are up to date.

### Tech steps or considerations (optional)

Example from Commissioner Petersen's page:
![image](https://user-images.githubusercontent.com/24437369/85886927-e740c780-b7b4-11ea-82f7-d9b7723738ac.png)

After filling in dates, hit publish. That updates everything.

**Comment by kathycarothers** [comment]
Hunter's page has been updated.
