### ISSUE TITLE
/careers is returning jobs from different agencies and none from FEC

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#3871]
### Summary

/careers is returning jobs from different agencies and none from FEC

- Checked the CF UPS and all env vars for the credentials are correct
- Ran a test query matching our query in Postman and it returns the same incorrect jobs
- Sent email to USAJObs support
- Edited production page in Wagtail to remove our USAJobs templatetag and put a message for users to click through to a search for FEC jobs. Currently there are no jobs. @JonellaCulmer , please let me know of changes to message.

See dev space https://fec-dev-proxy.app.cloud.gov/about/careers/ for broken page.

**Comment by JonellaCulmer** [comment]
@johnnyporkchops This is the style of the message we need to display when we're unable to show FEC jobs. I defer to content team on the language. cc: @dorothyyeager @AmyKort 

<img width="1092" alt="Screen Shot 2020-06-29 at 8 40 39 AM" src="https://user-images.githubusercontent.com/31663028/86006635-420c3600-b9e4-11ea-9f28-4edebcdfd0b9.png">

**Comment by dorothyyeager** [comment]
@JonellaCulmer That language seems OK to me. cc: @AmyKort

**Comment by AmyKort** [comment]
Works for me @JonellaCulmer

**Comment by dorothyyeager** [comment]
To clarify, the language in @JonellaCulmer 's image is the language to go with.

**Comment by johnnyporkchops** [comment]
The  only problem with that language is that USAJobs is not "unavailable". Related to this issue and something I have been meaning to bring up in general is that it seems confusing to say "USAJobs is unavailable, please visit USAJobs." 
We could say "USAJobs API" is unavailable, but that might mean anything for the average user.

**Comment by AmyKort** [comment]
That's a really good point, @johnnyporkchops . How about " This information is currently unavailable. Please visit USAJobs to complete your search" or something like that.

**Comment by johnnyporkchops** [comment]
This has been updated
https://www.fec.gov/about/careers/

**Comment by johnnyporkchops** [comment]
USAJobs API team responded that this has been resolved, and our prod page has been updated to re-enable the templatetag.
https://www.fec.gov/about/careers/

USAJobs team did not provide insight into the cause or solution to the problem in the support email response, except to confirm that it was a problem on their end.
