### ISSUE TITLE
[July/August] - Manually update wagtail global search index

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3874]
###Summary
**What we're after:**
We need to update the global search.gov index for new pages that were published in July.

Related issues
#3785 

**Completion criteria**

- [x] Follow instructions under [Adding CMS pages to the index](https://github.com/fecgov/fec-cms/blob/develop/fec/search/management/instructions.md#adding-cms-pages-to-the-index)
- [x]  Create ticket for next month ~~August~~ september for manual wagtail global search index

**Comment by pkfec** [comment]
Last indexed page count: 882 (indexed on 06/30/2020)
New indexed page count: 893 (indexed on 08/06/2020)

Created new ticket to scrape and index the pages for September #
