### ISSUE TITLE
Remove section on PACronyms publication from hard-coded data page; replace with reference to researching PACs.

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3876]
### Summary

**What we are after:**
_As a user, I want the latest, updated information._

PACronyms has been discontinued by the Public Records Office and a redirect is being put in place in this ticket: #3861 

The last section of https://www.fec.gov/data/browse-data/?tab=committees describes PACronyms and links to it. That section should be removed. This page is hard-coded.

We should replace this section with a button linking to the page where users can learn about how to research PACs and other types of committees.

### Related issues

- #3861 

### Completion criteria

- [x] Section on PACronyms is ~removed~ updated to include content team language on the Committee data page.
- [x] Consider a temporary informational blurb to explain PACronyms disappearance. See comment below for suggested language from content team.
- [x] Button labeled "Learn more about how to research PACs and party committees" is added to the page. Button should link to https://www.fec.gov/introduction-campaign-finance/how-to-research-public-records/pacs-parties-and-other-committees/.

**Comment by dorothyyeager** [comment]
@AmyKort and I came up with this for the replacement language:
`"PACronyms" refers to acronyms, abbreviations, initials and common names of federal political action committees (PACs). The Public Records Office can provide assistance in finding information about a specific PAC, including the PAC's PACronym. (followed by button linking to their page for PACs).`

**Comment by JonellaCulmer** [comment]
After pairing with @dorothyyeager we created the following mockup to address the disappearance of PACronyms. 

@patphongs per your suggestion to add the language to the PACs, parties and other committees page, we will have to incorporate that into future work as that will involve discussions with other offices that we're not prepared to have at this point. 

![PACronyms mockup](https://user-images.githubusercontent.com/31663028/88335543-7b914200-cd01-11ea-9a8d-fd1e7fe2a41f.png)

cc: @AmyKort
