### ISSUE TITLE
Move the Requests for Legal Consideration page into Wagtail

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3878]
### Summary

**What we're after:**
_We are getting the Requests for Legal Consideration page at https://transition.fec.gov/law/legalconsideration.shtml off of transition._

### Completion criteria

- [x]  Do a word document to organize page content and circulate to content team and Policy, Enforcement, Audit and RAD.
- [x] Create the page as child page of legal resources, with a resource page template
- [x] Second pair of eyes before publishing
- [x] Publish the page
- [x] Update the link on the Policy page
- [x]  Add page ~~and any PDFs uploaded~~ to redirect spreadsheet (we created a separate ticket, #4158, for the PDF work)

### Future work

Redirect

**Comment by bmathesonFEC** [comment]
Content team provided input on a draft format for each request that will be posted the page:

![image](https://user-images.githubusercontent.com/33758291/97337829-21030700-1857-11eb-992b-5bc8412d18c7.png)

Currently in the process of building out the rest of sections on the page (Policy Statement, Submit a Request) and I will schedule a meeting with page owners.

**Comment by bmathesonFEC** [comment]
Incorporated feedback into the drafts. Distributed word and PDF views of the pages to the group of stakeholders for review. No specific deadline, but I will follow up if I don't get language consensus by the end of the week.

**Comment by bmathesonFEC** [comment]
Incorporated final changes from the stakeholders and content team. I'm building out the remainder of the "Previous requests" section and the page will be ready for re-distribution to the Content team.

**Comment by bmathesonFEC** [comment]
Built out the remainder of the requests using the existing links to documents. Sent to Content team for final review before publication.

**Comment by bmathesonFEC** [comment]
- Published the page
- Replaced the link on the Policy and other guidance page (published updates)
- Added the Requests for consideration of legal issues page to our 13.7 redirects.
- Emailed stakeholder team to notify them of the live page.
