### ISSUE TITLE
Update link on EFO pages

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#3893]
**What we are after**:
Update link for electronic filing password "read next box." 

**Why we are after it**:
We want to direct users to the most relevant and helpful information. 

**Related issue**:

https://github.com/fecgov/FEC/issues/10083

**Original request**: 

> In the “Read Next” box, the electronic filing password link is outdated (https://transition.fec.gov/elecfil/passwords.html). It should link to the Electronic Filing Password Assignment System: https://webforms.fec.gov/psa/getstarted.htm

**Completion criteria**:
- [x] update link
- [x] notify RAD update has been made
- [x] close https://github.com/fecgov/FEC/issues/10083 once link is updated

**Comment by dorothyyeager** [comment]
I've added this into the redirect PR we have going during the innovation sprint. We should still update the link though. It's better to keep links current rather than rely on redirects.

**Comment by dorothyyeager** [comment]
I've updated the link on www.fec.gov/help-candidates-and-committees/filing-reports/fecfile-software/ and a link to vendor tools on https://www.fec.gov/help-candidates-and-committees/filing-reports/other-filing-software/. We'll also put in a redirect in case the outdated link is in publications like the Campaign Guides or tips for treasurers.
