### ISSUE TITLE
Collect business rules on candidate conversion to PAC

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#3895]
## Summary
When a candidate decides to convert their candidate committee to a political action committee by filing an amended statement of organization their financial totals disappear from the candidate's profile page on the website. Currently, we track those conversions manually, leading to a manual process that updates the candidate profile page with a message directing the user to the PAC's committee profile page.

To automate the process for updating candidate profile pages when a candidate converts their candidate committee to a PAC the team must first have a clear understanding of the steps that lead to financial totals being removed from the candidate's page.

We must know the steps taken by the committee plus the changes that occur in the database as a result (electronic and paper filed form 1s) leading to the change that is reflected on the website.

### Completion Criteria
- [x] Step by step business rules documented (consider a pairing meeting with a few folks to document this, including technical and business logic people)
- [ ] ~~Document the logic as a SQL query, identify needed tables (`DISCLOSURE.dim_cmte_ie_inf`?) and whether they need to get brought into `postgres`. (Thanks to @dzhang-fec the `FECP` table has been copied to "`dev`" aurora PG"
`select count(*) from DISCLOSURE.dim_cmte_ie_in`~~
- [ ] ~~If needed, create a ticket for 13.2 to bring in any additional tables into `postgres` (migration file,  initial load and golden gate transfer work)~~

### Related Issues
- RAD's workflow when a candidate converts to a PAC: https://github.com/fecgov/fec-cms/issues/3806#issuecomment-639064274

### Past Work
- original user submitted issue [#9709](https://github.com/fecgov/FEC/issues/9709) 
- design ticket for candidate profile page language [#3806](https://github.com/fecgov/fec-cms/issues/3806) 
- implementation of manual approach [#4292](https://github.com/fecgov/openFEC/issues/4292)

**Comment by jason-upchurch** [comment]
@djgarr I'm interested in seeing how this works even though I may not be the best person to represent the backend (SQL)  implementation. If you are scheduling  discussions I'd be willing to join and contribute where I can 
cc @PaulClark2

**Comment by djgarr** [comment]
@jason-upchurch sounds good. I'll let you know once I figure things out a bit more

**Comment by lbeaufort** [comment]
Here's a start - it catches known issues, but it's still casting the net too wide. I have this down to around 115 examples - not sure how many are false positives yet.

```
select dim_cmte.cmte_id, min(dim_cmte.cmte_nm), max(dim_cmte.cmte_nm), link.cand_id, max(filed_cmte_tp), min(create_date), min(cand_election_yr)
--select dim_cmte.cmte_id, dim_cmte.cmte_nm, link.cand_id, cand_election_yr, filed_cmte_tp, filed_cmte_dsgn, create_date, filed_cmte_tp_desc, *
-- Any non-candidate committee that's linked to a candidate
from disclosure.dim_cmte_ie_inf dim_cmte
join disclosure.cand_cmte_linkage link using (cmte_id)
where filed_cmte_tp not in ('H', 'S', 'P', 'U', 'Y', 'Q', 'X') 
--and filed_cmte_dsgn not in ('J', 'X', 'P', 'A') 
and filed_cmte_dsgn in ('U','B','D')
and create_date < date(concat('12/31/',cast(cand_election_yr as varchar))) 
and link.linkage_type = 'U' -- what's this?
-- see if they ever had a possible PCC that raised money this cycle 
-- might include JFC's but that seems ok
and cand_id in (
    select link.cand_id
    from disclosure.dim_cmte_ie_inf dim_cmte
    join disclosure.cand_cmte_linkage link using (cmte_id)
    join ofec_totals_combined_vw totals 
    on totals.committee_id = dim_cmte.cmte_id and totals.cycle=cand_election_yr
    where filed_cmte_tp in ('H', 'S', 'P')
    -- exclude J's
    and create_date < date(concat('12/31/',cast(cand_election_yr as varchar)))
    and (totals.receipts > 0 or totals.disbursements > 0)
)
-- look up known examples
-- and (dim_cmte.cmte_id IN ('C00291955','C00693044', 'C00697441', 'C00634212', 'C00691790', 'C00697128', 'C00698894', 'C00727156', 'C00745752', 'C00503094')
-- or link.cand_id='H2PA18143')

GROUP BY dim_cmte.cmte_id, link.cand_id
```

**Comment by bmathesonFEC** [comment]
After Thursday's meeting @djgarr put together some notes documenting the business rules that result in the candidate profile page financial totals being unlinked from the committee's totals. I am currently reviewing that draft to add my notes from the meeting. I also have an email out with RAD's Report's Processing Branch to document the steps that occur for paper filed F1 amendments.

**Comment by djgarr** [comment]
Document was updated with additional business logic courtesy of @bmathesonFEC . Almost done. Just want to look over the document once more

**Comment by bmathesonFEC** [comment]
The original flowchart made the false assumption that the amended Form 1 would update the committee designation **and** the committee type. I have updated the business rules to reflect that the committee designation is updated automatically, but the committee type must be updated manually when a PCC converts to a non-connected PAC (box F on the Form1). As of writing this comment, C00727008 is an example of a committee that has an updated committee designation but it still has the committee type carried over (this may change if someone in RAD updates the committee type).

I added examples to the business rules document.

**Comment by fecjjeng** [comment]
This is a simple test I did with the cand_cmte_linkage table that captures the change of cmte_tp within the same fec_election_yr for a cmte_id.

create trigger tri_bu_cand_cmte_linkage before
update
    on
    disclosure.cand_cmte_linkage for each row execute procedure disclosure.cand_cmte_linkage_upd();

CREATE OR REPLACE FUNCTION disclosure.cand_cmte_linkage_upd()
 RETURNS trigger
 LANGUAGE plpgsql
AS $function$
begin
	if (new.fec_election_yr = old.fec_election_yr) and (new.cmte_tp <> old.cmte_tp) then

	insert into disclosure.cand_cmte_linkage_audit 
	(cmte_id, cand_id_old, cand_id_new, cmte_tp_old, cmte_tp_new, cmte_dsgn_old, cmte_dsgn_new, fec_election_yr)
	values
	(new.cmte_id, old.cand_id, new.cand_id, old.cmte_tp, new.cmte_tp, old.cmte_dsgn, new.cmte_dsgn, old.fec_election_yr);

	end if;
return old;
END;
$function$
;

![image](https://user-images.githubusercontent.com/24943130/90217966-991d6d00-ddd0-11ea-8268-57011b005261.png)

**Comment by fecjjeng** [comment]
After taking a closer look at the dim_cmte_ie_inf table, it may be enough information from this table that the above trigger is not be necessary.  
Following is the query I tried to check the PCC to non-PCC change from this table alone, we will need to check on some known cases to see if it capture all the changes we desired.
WITH DIM_CMTE AS
(
	-- postgresql syntax
	SELECT CMTE_ID, CMTE_NM, FILED_CMTE_TP, FILED_CMTE_DSGN, CREATE_DATE, TO_CHAR(CREATE_DATE, 'YYYY')::numeric +MOD(TO_CHAR(CREATE_DATE, 'YYYY')::numeric , 2) FEC_ELECTION_YR
	FROM DISCLOSURE.DIM_CMTE_IE_INF
	ORDER BY CMTE_ID, CREATE_DATE
)
, LATEST_ROW_IN_CYCLE AS 
(
	SELECT CMTE_ID, MAX(CREATE_DATE) LAST_CHANGE_DATE, FEC_ELECTION_YR 
	FROM DIM_CMTE 
	GROUP BY CMTE_ID, FEC_ELECTION_YR
)
, CHANGE_CAPTURE AS 
(
	SELECT DIM_CMTE.CMTE_ID, DIM_CMTE.CMTE_NM, DIM_CMTE.FILED_CMTE_TP, DIM_CMTE.FILED_CMTE_DSGN, DIM_CMTE.CREATE_DATE 
	, FIRST_VALUE(DIM_CMTE.CMTE_NM) OVER (PARTITION BY DIM_CMTE.CMTE_ID, DIM_CMTE.FEC_ELECTION_YR order by CREATE_DATE) AS FIRST_CMTE_NM
	, LAST_VALUE(DIM_CMTE.CMTE_NM) OVER (PARTITION BY DIM_CMTE.CMTE_ID, DIM_CMTE.FEC_ELECTION_YR order by CREATE_DATE) AS LATEST_CMTE_NM
	, FIRST_VALUE(DIM_CMTE.FILED_CMTE_TP) OVER (PARTITION BY DIM_CMTE.CMTE_ID, DIM_CMTE.FEC_ELECTION_YR order by CREATE_DATE) AS FIRST_CMTE_TP
	, LAST_VALUE(DIM_CMTE.FILED_CMTE_TP) OVER (PARTITION BY DIM_CMTE.CMTE_ID, DIM_CMTE.FEC_ELECTION_YR order by CREATE_DATE) AS LATEST_CMTE_TP
	, FIRST_VALUE(DIM_CMTE.FILED_CMTE_DSGN) OVER (PARTITION BY DIM_CMTE.CMTE_ID, DIM_CMTE.FEC_ELECTION_YR order by CREATE_DATE) AS FIRST_CMTE_DSGN
	, LAST_VALUE(DIM_CMTE.FILED_CMTE_DSGN) OVER (PARTITION BY DIM_CMTE.CMTE_ID, DIM_CMTE.FEC_ELECTION_YR order by CREATE_DATE) AS LATEST_CMTE_DSGN
	, DIM_CMTE.FEC_ELECTION_YR
	FROM DIM_CMTE 
	ORDER BY DIM_CMTE.CMTE_ID, DIM_CMTE.FEC_ELECTION_YR, DIM_CMTE.CREATE_DATE
)
SELECT CHANGE_CAPTURE.CMTE_ID, CHANGE_CAPTURE.FEC_ELECTION_YR, CHANGE_CAPTURE.FIRST_CMTE_NM, CHANGE_CAPTURE.LATEST_CMTE_NM, CHANGE_CAPTURE.FIRST_CMTE_TP, CHANGE_CAPTURE.LATEST_CMTE_TP,CHANGE_CAPTURE. FIRST_CMTE_DSGN, CHANGE_CAPTURE.LATEST_CMTE_DSGN
FROM CHANGE_CAPTURE
JOIN LATEST_ROW_IN_CYCLE 
ON CHANGE_CAPTURE.CMTE_ID = LATEST_ROW_IN_CYCLE.CMTE_ID 
AND CHANGE_CAPTURE.FEC_ELECTION_YR = LATEST_ROW_IN_CYCLE.FEC_ELECTION_YR 
AND CHANGE_CAPTURE.CREATE_DATE = LATEST_ROW_IN_CYCLE.LAST_CHANGE_DATE
WHERE
(
(CHANGE_CAPTURE.FIRST_CMTE_TP IN ('H','P','S') AND CHANGE_CAPTURE.LATEST_CMTE_TP NOT IN ('H','P','S'))
OR (CHANGE_CAPTURE.FIRST_CMTE_DSGN IN ('P','A') AND CHANGE_CAPTURE.LATEST_CMTE_DSGN NOT IN ('P','A'))
)
ORDER BY CHANGE_CAPTURE.FEC_ELECTION_YR, CHANGE_CAPTURE.CMTE_ID;

**Comment by bmathesonFEC** [comment]
I did a strike through on two of the completion criteria because they have been moved to newly created OpenFEC [ticket # 4561](https://github.com/fecgov/openFEC/issues/4561).

@lbeaufort and @fecjjeng comments in this thread are being carried over to that ticket so SQL conversation can continue. Also: WHOA, this is a seriously impressive effort, I can't wait to see where this goes.
