### ISSUE TITLE
Front end implementation: automatic candidate to PAC conversion

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#3896]
## Summary
**What we're after:**
When a candidate converts their candidate committee to a PAC mid-way through a 2 year transaction period, the candidate profile page should automatically display a message directing users to PAC's committee profile page. 

With the API endpoint updated to provide the necessary data, the front-end up must be updated to automatically display the message.

## Implementation  notes

- Generate the list of names for former candidate committees using this endpoint: `/committee/{committee_id}/history/{cycle}/` `committee_id : former_committee_name`
- Include the improved language from #4014 
- Generate the list of candidates who have changed their candidate committees during a recent two year time period using this endpoint: `/candidate​/{candidate_id}​/committees​/history​/{cycle}​/` `{former_candidate_id : committee_id}`

### Action items
- [ ] check endpoint from fecgov/openFEC#4658

### Completion Criteria
- [ ] Converted candidate to PAC committees display message by using the above API endpoints

### Related Issues
- fecgov/fec-cms#3895 Collect business rules for candidate to PAC conversions
- fecgov/openFEC#4457 Identify historic/current cycle conversion, edge cases, and problem situations
- fecgov/openFEC#4419 Database work
- fecgov/openFEC#4458 API work

### Past Work
- original user submitted issue [#9709](https://github.com/fecgov/FEC/issues/9709) 
- RAD's workflow when a candidate converts to a PAC: https://github.com/fecgov/fec-cms/issues/3806#issuecomment-639064274
- design ticket for candidate profile page language [#3806](https://github.com/fecgov/fec-cms/issues/3806) 
- implementation of manual approach [#4292](https://github.com/fecgov/openFEC/issues/4292)

**Comment by patphongs** [comment]
Awaiting backend API logic, moving to PI 14
