### ISSUE TITLE
Add language to PACs (that were formerly PCCs) and candidate pages to indicate committee-type conversion

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#3897]
### Summary

After candidates converted their PCCs to PACs, we need to add language to the candidate and committee pages to indicate the committee changed from an authorized committee to an unauthorized committee at a point during the election cycle for the following candidates/committees: 

- Freedom First PAC (C00503094) (formerly Meadows for Congress) (Candidate ID H2NC11080)

Similar to the work for Julian Castro (https://www.fec.gov/data/candidate/P00009092/) and Pete Buttigieg (https://www.fec.gov/data/candidate/P00010298/).

### Related issues

- fecgov/openFEC#4292 
- fecgov/openFEC#4419 

### Completion criteria

- [x] Add text to C00503094 and H2NC11080
- [x] Publish information on site

**Comment by patphongs** [comment]
Changes have been made for Justin Amash's former committee. 202007010300323379 filing has been moved to C00745752 and C00750216 has been fully expunged. There will be a change to add his committee to the list of candidate to PAC conversions.

**Comment by patphongs** [comment]
Hotfix deployed, closing
