### ISSUE TITLE
Compile examples of current and historic Candidate Committee to PAC conversions

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#3898]
## Summary
Candidates may convert their candidate committees to a political action committee as an alternative to terminating the committee when they are no longer an active candidate ([H4CC Guidance](https://www.fec.gov/help-candidates-and-committees/winding-down-candidate-campaign/conversion-to-multicandidate-committee/), [Reporting Example](https://www.fec.gov/help-candidates-and-committees/filing-reports/converting-multicandidate-committee/))

To help the process of automating the message that is posted on a candidate profile page when the candidate converts their committee to a PAC, we need to identify:

- an exhaustive (as possible) list of current cycle and historic candidate to PAC conversions
- any problem situations and "edge cases" that need to be accounted for in the automation workflow. For example:
   - Deval Patrick's committee converted to a PAC but did not change their committee name.
   - A committee coverts to a PAC then converts back to a candidate committee.
   - Candidate is given two candidate/committee ID #s (Amash)

### Completion Criteria
- [x] Historic examples of candidate conversions added to Converted Committee's tracking document. 
- [x] Known edge cases, problem situations are documented

### Related Issues
- #3915 
- fecgov/fec-cms#3895 Collect business rules for candidate to PAC conversions which has a comment with examples https://github.com/fecgov/fec-cms/issues/3806#issuecomment-637694996
- RAD's workflow when a candidate converts to a PAC: https://github.com/fecgov/fec-cms/issues/3806#issuecomment-639064274

### Past Work
- original user submitted issue [#9709](https://github.com/fecgov/FEC/issues/9709) 
- design ticket for candidate profile page language [#3806](https://github.com/fecgov/fec-cms/issues/3806) 
- implementation of manual approach [#4292](https://github.com/fecgov/openFEC/issues/4292)

**Comment by djgarr** [comment]
Added a note about situations like Amash where the candidate was assigned two ID numbers

**Comment by JonellaCulmer** [comment]
Added another tab to the existing spreadsheet where we're tracking examples. This list came from Jaime, but does not goes back as far as 2008. 
https://docs.google.com/spreadsheets/d/1VypSyRziT-_bgf9PslVNCkVUZ15GovF33AshZ9-f-4s/edit#gid=1234648164

According to the research [here](https://docs.google.com/spreadsheets/d/1Gy8VVC7Yxzqe13dkJC21eGmUI-3O8BNEocWZ_JxuuPs/edit#gid=0), can we find a Senate mid-cycle conversion example?

**Comment by jason-upchurch** [comment]
@bmathesonFEC @djgarr if there is anything I can do to support this effort please let me know, e.g., supporting database queries or being general gopher

**Comment by bmathesonFEC** [comment]
I have collected data from dim_cmte to identify examples of conversions from PCC to PACs. Reviewing the data to document the list and identify any odd cases that may inform the automation process. Will share examples list after notes are added.

**Comment by djgarr** [comment]
@jason-upchurch thanks! we'll let you know

**Comment by bmathesonFEC** [comment]
Added a new document to the PCC>PAC conversion data research folder: https://drive.google.com/drive/u/1/folders/1uBGOnXxp9kqnTzeK-bhlQ-GieQiHE2gP

This document logs additional examples of conversions from Candidate PCCs to PACs. The notes column provides additional context about the particular conversion that may make it "out of the ordinary" and help build out code to capture the conversions we need to capture and write language for the site that reflects a variety of possible conversions.

Still a work in progress as a fill out the remaining notes.

**Comment by bmathesonFEC** [comment]
I documented additional examples of [candidate committee to PAC conversions here](https://drive.google.com/drive/u/1/folders/1uBGOnXxp9kqnTzeK-bhlQ-GieQiHE2gP). In addition, I added some notable examples to our [business rules document](https://docs.google.com/document/d/1eZs9jDOkYLiJsARp0SIcaLJA4TtEGHxWeP5OO3wJ_7U/edit?usp=sharing).
