### ISSUE TITLE
Review FEC landing pages for elements for OIG page 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#3901]
### Summary

**What we're after:**
_To create a web page for the OIG based on common elements from an in-depth look at other inspector general pages. Looking to see what elements we can pull from landing pages to create a landing page for the OIG._

### Related issues

_List any relevant related issue(s)_

- #3787

### Completion criteria

_Will need to review all our landing pages to see what elements would work with the OIG requests and see if those elements could be made Wagtail editable_

### Steps or considerations (optional)

_OIG elements include: branding, red color button, search function, 3 columns, incorporate visuals based on this report https://www.fec.gov/resources/cms-content/documents/SAR_may2020_10-1-2019_to_3-31-2020_final.pdf_

- [ ] Review landing pages - About, Legal resources, H4CC, Contact, etc. 
- [ ] List of elements that could be editable in Wagtail 

### Future work

_Based on this review start to draft a landing page for OIG and to meet with OIG._

**Comment by JonellaCulmer** [comment]
Notes from our discussion in #content about the reusable elements from our existing landing pages we believe will be useful for an OIG landing page:

Elements:
- Horizontal cards (Legal resources H4CC and CFD landing pages
  - Possible technical work: Add a card block
- News feed (Legal resources and H4CC)
  - Possible technical work: use the `document feed templatetag`
- You might also like (Legal resources and H4CC)
  - Possible technical work: editor fields, no HTML required. Or WYSIWYG/text block. Or Read next block (Record pages)
- Images/links (Legal resources and H4CC)
  - Possible technical work: Editor fields, HTML not required. 


Closing this ticket in favor of design work: https://github.com/fecgov/fec-cms/issues/3946
