### ISSUE TITLE
Test to make sure that GTM is successfully going into pages, adding GA accounts to pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3906]
**What we're after:** Follow-up testing on the 3160 to make sure that GTM is successfully going into pages and adding GA accounts to pages.

**Action items:**
- [x] Check each environment's source for home, other html template, Jinja templates, and legal templates to make sure the right option and accounts are being included in the page source. 
- [x] Confirm that GA and DAP tracking are being included for Production so we don't lose data when switching to GTM.
- [x] As far as things to test:
 - Confirm that a data page and a legal page are showing Google Analytics / GSA DAP (may need to set DEBUG = false)
 - Confirm that Home and a Wagtail page are showing GA / GSA DAP (will need to set DEBUG = false)
 - Set the feature flag to true
 - Confirm that Home, a Wagtail page, a data page, and a legal page are showing two Tag Manager elements—a <script> at the end of the <head>, and a <noscript> at the top of the <body>
 - Check the container IDs for the GTM tags—Production should have its own and the others (dev, stage, feature, local) should have a different one
 - To check whether GA and DAP are loaded check the Inspector's network traffic
 - In the console, enter ga to check whether the GA object exists
 - DAP should load into Production but not the other(s)
 - The GA property ID should be different for Production than the others'

**Completion criteria:**
- [x] Confirm that GTM is going to the pages in dev and stage.

**Comment by patphongs** [comment]
@rfultz Could we have a status update on this? We pushed this work to the next sprint since go live of GTM may be delayed for our site

**Comment by rfultz** [comment]
Everything looks goos; closing now
