### ISSUE TITLE
Test the status page tool that we think will work best for us

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3908]
**What we're after:** Based on the list of status page candidates, we need to pick one to test and ensure it meets our needs (see which aspect are customizable) and get team buy-in with a demo. 

Comparison spreadsheet: https://docs.google.com/spreadsheets/d/1ykAuWjL65uZm-sLt7IcOEWmz6h6EAP4lUYCd-5QXW4Q/edit?usp=drive_web&ouid=114351900669501389307

**Completion criteria:**
- [ ] Tool is tested and demo to the team to make sure we're not missing anything.

**Comment by johnnyporkchops** [comment]
- Setup trial-account status pages for status.io and Altassian statuspage. Please let me know if you would like to be invited as a user on these accounts.
- Setup Pingdom alerts for status.io
- Still figuring out how to setup Pingdom for Atlassian.
- My initial impression is that the status.io interface is much more user-friendly than Atlassian. 
Obviously there is more testing to see which one works best for us in terms of functionality and options that we require.

**Comment by johnnyporkchops** [comment]
- Paired with @pkfec and @fec-jli to trigger Pingdom alerts and test response on both trial accounts. 
- Also corresponded with support teams from both tools to verify that trial accounts get all the same alerts a licensed account would (yes)

**Next steps:** It would be helpful to determine a preliminary list of services and apps we want to show on a status page, so we can set up alerts and statuses of those as part of the evaluation and demo process. Related to issue : https://github.com/fecgov/fec-cms/issues/3949

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Is there anything from your testing that would suggest that we are blocked from including certain FEC services? If so, I'm curious what those services might be. How long does our trial of these two status pages last?

**Comment by johnnyporkchops** [comment]
- After testing and demoing status.io and Atlassian Statuspage,  the team has decided to move forward with Atlassian Statuspage. 
- The [spreadshee](https://docs.google.com/spreadsheets/d/1ykAuWjL65uZm-sLt7IcOEWmz6h6EAP4lUYCd-5QXW4Q/edit?usp=drive_web&ouid=114351900669501389307)t has been update with a breaKdown of services we want to provide status on.
- Closing this ticket to and we will move on to https://github.com/fecgov/fec-cms/issues/3909
