### ISSUE TITLE
Finalize status page tool selection

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3909]
**What we're after:** Pick a status page tool. Make sure it includes all our requirements. Look at the tool comparison spreadsheet. 

Action items:
- [x] Check fedramp, or confirm which agencies are using the tool
- [x] Email the security team to make them aware of the chosen tool
- [x] Document why we're using it and share decision with the rest of the team

**Completion criteria:** 
- [x] Tool is selected and requirements are met.
- [x] Security team is made aware of the chosen tool.

**Comment by patphongs** [comment]
First two items are complete

**Comment by JonellaCulmer** [comment]
Here is a selection summary of the statuspage tool and some of the functionality we intend to use: 
https://docs.google.com/document/d/1vfgRgvwK3WLxUpqRxDb94piq9qkgbkIABBouP-Eu5nY/edit#

I intend to go over some of this functionality and the components for the page during 13.2 demo.
