### ISSUE TITLE
Procure status page tool

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3911]
**What we're after:** Procure status page tool. 

Tool comparison spreadsheet with links to tools: https://docs.google.com/spreadsheets/d/1ykAuWjL65uZm-sLt7IcOEWmz6h6EAP4lUYCd-5QXW4Q/edit#gid=0

Tool: statuspage.io by atlassian

**Completion criteria:**
- [x] Procured.

**Comment by lbeaufort** [comment]
Waiting to hear back from contractor about whether this is already covered by our contract. @PaulClark2 will follow up

**Comment by patphongs** [comment]
@PaulClark2 Moving this to blocked since we're still waiting to hear back about this tool.

**Comment by jason-upchurch** [comment]
@PaulClark2 I moved this issue into innovation sprint in prep for the next iteration. Please let me know if I need to reprioritize. Thank you!

**Comment by JonellaCulmer** [comment]
Procured.
