### ISSUE TITLE
Server error when sort by candidate column on electioneering committee spending tab

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-cms#3920]
### Summary

Server error when sort by candidate column on electioneering committee spending tab

https://www.fec.gov/data/committee/C30001101/?tab=spending#electioneering-communication
![EC-giffy](https://user-images.githubusercontent.com/11650355/87800332-44f88a80-c81c-11ea-98f3-815887fddb74.gif)

### Related issues

- #3900

### Completion criteria

- [ ] Fix sort by candidate column on spending section of EC committee page
- [ ] Determine whether there's additional back-end work and open followup ticket.

**Comment by lbeaufort** [comment]
Can be addressed by https://github.com/fecgov/openFEC/pull/4529

**Comment by lbeaufort** [comment]
Can be addressed by https://github.com/fecgov/openFEC/pull/4529

**Comment by patphongs** [comment]
This fix has been merged in
