### ISSUE TITLE
Server error when sort by candidate column on communications cost committee - spending tab

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-cms#3921]
Server error when sort by candidate column on communications cost committee spending tab
https://www.fec.gov/data/committee/C70001318/?tab=spending#communication-costs

![CC](https://user-images.githubusercontent.com/11650355/87802689-88082d00-c81f-11ea-89f5-8870b1675fa5.gif)

### Completion criteria
- [ ] Fix sort by candidate column on spending section of CC committee page

**Comment by lbeaufort** [comment]
Can be addressed by https://github.com/fecgov/openFEC/pull/4529
