### ISSUE TITLE
Confirm all RAD FAQ content has been migrated

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#3924]
### Summary
Now that RAD FAQ content has been migrated to pages on FEC.gov, the transition page needs to be turned off. A final review should be conducted, redirects in place, and the page should be turned off.

### Action items
- [ ] Confirm all content migrated to new site.

### Future tickets
- [ ] After redirect is entered, @patphongs will deploy and merge.
- [ ] After the redirects are deployed, test them and update spreadsheet
- [ ] Put in ticket for front end to take down the pages from transition.

### Related issues

- #3736 - make a plan for 12.4 through 12.innovation
- #3756 - RAD FAQ: New reporting scenarios (stage 1)
- #3767-  RAD FAQ: New new site content (stage 2)
- #3769 - RAD FAQ: New content for existing pages (stage 3)
- #3770 - RAD FAQ: New new site content (stage 4)

**Comment by bmathesonFEC** [comment]
Template creation for the final collection of notes is assigned out to RAD team member. Once done, will coordinate with David and Don to complete the work.

**Comment by bmathesonFEC** [comment]
Received template from RAD, currently reviewing and preparing for distribution to web team members to fill out with content.

**Comment by bmathesonFEC** [comment]
Several sections of the RAD FAQ have notes saved. I'm working on my portion and added several notes for content during this sprint.

**Comment by dorothyyeager** [comment]
@bmathesonFEC Can we close this ticket?
