### ISSUE TITLE
Add new background image for TV ad disclaimer

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#3934]
### Summary

Looking to add a new background to the website for the upcoming TV ad disclaimer 

### Related issues

- #3373 
- #3812 

### Completion criteria

- [x] Build image (@djgarr, @jjonesfec)
- [ ] Add to website (@johnnyporkchops)
     - [ ] upload image(s) to fec/fec/static/img
     - [ ] create new CSS class for new example background to be used in Wagtail html block.
- [ ] Include @JonellaCulmer as a reviewer for Design/UX sign-off

**Comment by djgarr** [comment]
@johnnyporkchops does this ticket look alright to you?

**Comment by djgarr** [comment]
@jjonesfec want to make sure you're in the loop

**Comment by patphongs** [comment]
Moving this to PI 14 as we have a lot of other work to do
