### ISSUE TITLE
Implement upcoming Public Records redirects

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3936]
### Summary

**What we are after:**
_We are getting off of transition and in this ticket, finishing up the pubrec/ files. In #3861 we worked out a plan with Public Records who are making their own pages. Once those pages are made, we can redirect the few remaining files in transition to them._

### Related issues

_List any relevant related issue(s)_

- #3861 - the plan
- #3379 - the first round of redirects completed
- #3916 - the first take-down ticket (13.1)

### Completion criteria

- [x] After Public Records completes work on its new pages, redirect the following pages to the new pages to be created:

/pubrec/cfl/ (directory)
https://transition.fec.gov/pubrec/alpha.htm
https://transition.fec.gov/pubrec/chrono.htm
https://transition.fec.gov/pubrec/staterec.shtml
https://transition.fec.gov/pubrec/stateelection.shtml
https://transition.fec.gov/pubrec/StateRecordsOffices.pdf

- [x] Ticket for future work created after redirects are merged

### Future work
After release, test them (including www redirects)
Put any needed www redirects into Wagtail AFTER the merge.
Put in a takedown ticket
Take down the pages

**Comment by dorothyyeager** [comment]
Public Records has migrated their pages and sent this list for the redirects.

Entire directory for old state law publications at /pubrec/cfl/  redirects to https://www.fec.gov/introduction-campaign-finance/how-to-research-public-records/combined-federalstate-disclosure-and-election-directory/
1998 election dates at https://transition.fec.gov/pubrec/alpha.htm redirects to https://www.fec.gov/resources/cms-content/documents/1998PDates.pdf
1998 election dates by date at  https://transition.fec.gov/pubrec/chrono.htm redirects to https://www.fec.gov/resources/cms-content/documents/1998PDates.pdf
State Records page at https://transition.fec.gov/pubrec/staterec.shtml redirects to https://www.fec.gov/resources/cms-content/documents/StateRecordsOffices.pdf
State records offices PDF at https://transition.fec.gov/pubrec/StateRecordsOffices.pdf redirects to  https://www.fec.gov/resources/cms-content/documents/StateRecordsOffices.pdf
State election offices at https://transition.fec.gov/pubrec/stateelection.shtml redirects to https://www.fec.gov/introduction-campaign-finance/how-to-research-public-records/state-election-offices/

**Comment by dorothyyeager** [comment]
PR is ready for review @patphongs

**Comment by patphongs** [comment]
Putting this issue into 14.1 so that it can be tested after the release goes out.

**Comment by dorothyyeager** [comment]
All things public records are redirecting properly. The pubrec/ directory can be taken down in https://github.com/fecgov/fec-cms/issues/4435.
