### ISSUE TITLE
Implement filterable campaign finance data summaries 

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3943]
### Summary

**What we're after:**
_Implement filterable campaign finance data summary section and committee type tables._

**Sample prototypes on feature space:**
- [Congressional candidate data summary tables](https://fec-feature-cms.app.cloud.gov/campaign-finance-data/congressional-candidate-data-summary-tables/)
- [Presidential candidate data summary tables](https://fec-feature-cms.app.cloud.gov/campaign-finance-data/presidential-candidate-data-summary-tables/)
- [Party committee data summary tables](https://fec-feature-cms.app.cloud.gov/campaign-finance-data/party-committee-data-summary-tables/)
- [Political action committee data summary tables](https://fec-feature-cms.app.cloud.gov/campaign-finance-data/pac-data-summary-tables/)
- [Communication filings data summary tables](https://fec-feature-cms.app.cloud.gov/campaign-finance-data/communication-filings-data-summary-tables/)

### Related issues

- #3816 (design work)
- #4052 (file migration)

### Requirements and technical steps
- Finalize the naming for this data summary section
- Ensure that the [spreadsheet](https://docs.google.com/spreadsheets/d/1fpqKiHy_PAZU5gN6mV0NO0Wow-bpx98W3ct2b2K9T3Q/edit#gid=0) of summary data is accurate
    - Add archived data summaries to spreadsheet
- Create filter capability based on two year period and data summary segment
- Should be able to click on a link to come to a pre-filtered table by two year period and data summary segment
- Migrate all PDF and Excel file resources to the content-s3 bucket **(This has beed moved to https://github.com/fecgov/fec-cms/issues/4052)**
- Delete PDF and Excel files from transition after it's migrated **(This has beed moved to https://github.com/fecgov/fec-cms/issues/4052)**

### Completion criteria
- [ ] New data summary by committee type pages is created
- [ ] Create redirect from the transition data summary pages to the new landing page for data summaries
### Future work

_Other future work that may be needed following this issue's completion._

**Comment by JonellaCulmer** [comment]
Linking to the approved content for these new pages: https://docs.google.com/document/d/1gw1ZrXzXjKP1GavgsLW1HkcCdlGvJDaDyxilODSAkDE/edit#

@patphongs There are other pages that are not going to be filterable that will need to be made as part of the campaign finance statistics pages, I'll open up a separate ticket for that work. 
Specifically, these pages: 
- Main nav
- https://www.fec.gov/data/browse-data/?tab=historical
- https://transition.fec.gov/press/campaign_finance_statistics.shtml
- https://transition.fec.gov/press/summaries/help/statistical_1975_2010.shtml
- https://transition.fec.gov/press/summaries/help/statistical_post2010.shtml

**Comment by JonellaCulmer** [comment]
Here's the design for the five pages: 

![Campaign stats_4](https://user-images.githubusercontent.com/31663028/89459107-25c38d80-d736-11ea-81b5-a91519b5c0bb.png)

**Comment by dorothyyeager** [comment]
Email sent to Press to ask questions on Thursday.
