### ISSUE TITLE
Sort is broken on candidate profile page "other spending" data table IE's

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#3945]
# Summary
In the release [PR](https://github.com/fecgov/fec-cms/pull/3928#issuecomment-665063258) we changed `candidate` to `candidate_name` and `committee` to `committee_name`, but we didn't change them everywhere. Should we?

**Comment by lbeaufort** [comment]
Can be addressed by https://github.com/fecgov/fec-cms/pull/3952 which also includes front-end changes for fecgov/fec-cms#3921 and fecgov/fec-cms#3920
