### ISSUE TITLE
Design landing page and subpages for OIG

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3946]
**What we're after:**
As part of our work to improve the OIG pages and bring them in line with government agencies, we would like to design a landing page where we're able to better showcase top-level information. 

**Need to consider:**
- IA of landing page and subsequent pages

### Related issues
- https://github.com/fecgov/fec-cms/issues/3787 Scan OIG reports for graphical elements and recommendations
- https://github.com/fecgov/fec-cms/issues/3930 Incorporate quick wins to the OIG page
- https://github.com/fecgov/fec-cms/issues/3901 Review FEC landing pages for elements for OIG page

### Completion criteria
- [x] Preliminary design is mocked up and reviewed internally by the website team

**Comment by JonellaCulmer** [comment]
@kathycarothers @AmyKort @patphongs @johnnyporkchops Below is the preliminary mockup of the OIG landing page. It incorporates some of the existing features we have on our landing pages and [uses the list of features discussed](https://github.com/fecgov/fec-cms/issues/3901) earlier in the PI. 

There is a placeholder at the top of the page for a data visualization that we have yet to design. Like the data visualization the rest of the links included on the page would require a discussion with the OIG's office. The links are based largely on the content the [OIG page](https://www.fec.gov/office-inspector-general/) already includes. 

![OIG Landing page](https://user-images.githubusercontent.com/31663028/90673758-2e33c200-e226-11ea-85b6-1eb6f323c9de.png)

**Comment by kathycarothers** [comment]
@JonellaCulmer I really like what you have drafted. I believe it hits the key points they have requested. I would say to change the Political Party committee card out with OIG Reports. I think this is something we could take to them. Plus, it is not overcrowded, so it is pleasing to the eyes. Very straight forward.

**Comment by JonellaCulmer** [comment]
@kathycarothers Oops, I missed that one, thanks for taking a look at the mockup and spotting that. 

I included all the links that would be included in the OIG reports section in the You might also like section. I didn't think they needed their own page that would just take you to another page. Seemed silly. Is there other content you think might be able to go there in place of "Political Party committees"?

**Comment by JonellaCulmer** [comment]
@kathycarothers Thanks for clarifying your earlier point. I've updated my mockup in the original comment to address your concern and link to the OIG reports feed page.

**Comment by kathycarothers** [comment]
@JonellaCulmer looks good. Thank you.

**Comment by patphongs** [comment]
@JonellaCulmer The landing page looks good. Question about the OIG resources horizontal cards and navigation. Are these all intended to be separate pages? If it is, I'd like to make sure there are ways to navigate to these resources while you're on each of these separate pages as well.

**Comment by JonellaCulmer** [comment]
@patphongs Good point. Part of that would be a matter of linking using the Read next section on the top-right or on the bottom, right? @kathycarothers What do you think? That could be an easy first step and wouldn't break any patterns.

I was also thinking about using a kind of Browse data page situation for the new separate pages. But that may be a longer term goal. One that involves making that as a new wagtail-editable template.

**Comment by kathycarothers** [comment]
Yes, I agree. We could utilize the Read next section @patphongs @JonellaCulmer

**Comment by JonellaCulmer** [comment]
@kathycarothers For the other pages, I'm thinking we can use custom page templates. That should give us the flexibility we need if we need to make changes in the future. I am concerned however with the contact bit on the right side of the page, is that required? It doesn't look like it from the quick check I did, but I wanted to confirm with you.

**Comment by JonellaCulmer** [comment]
Discussed my previous comment with @kathycarothers and we're good to go for now. We plan to set up a meeting with OIG to go over what we have for a landing page and the plan for the other content currently on their page.
