### ISSUE TITLE
Add new events into Google Tag Manager

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3948]
**What we're after:** Get the framework into GTM (current functionality into proposed GTM setup)

**Related work:**
- https://github.com/fecgov/fec-cms/issues/3160 Tag Manager implementation
- https://github.com/fecgov/fec-cms/issues/3905 Meeting to discuss tracking goals with Google Tag Manager

**Completion criteria:** 
- [ ] Current and new tracking events are added into GTM

**Comment by JonellaCulmer** [comment]
@rfultz When we get to this step, can we pair on this? I'd like to get my hands dirty and try to add events myself, so that it's not just on you in the future. Permissions? Separate account? Please advise, when the time comes.

**Comment by JonellaCulmer** [comment]
**Preliminary list of tags/events:**
- Contact information clicks (add ID to contact information links)
- Datatable filter usage (specific combinations and individual frequency of use)
- Download attempts for guides, forms and all other PDFs
- Cards (bottom of wagtail pages and reporting examples pages with multiple cards)
- Breadcrumbs
- Side-navigation
- Menu 'all' pages 
- Visualization searches, which excluding any and all PII
- Search box usage (typed searches and clicks)

**Comment by patphongs** [comment]
Looks like this will take some time to figure out how we can best track these events. We are also dependent on GTM going live anyways. Moving this to innovation so we have more time to think about this and work on it.

**Comment by rfultz** [comment]
Reviewing GTM events with @patphongs yesterday, we talked about adding a new event for us for tracking downloads—like the `Export` > `Download` button click data, like which page, which params, etc. Would likely need to parse params from GTM's {{Click URL}}

**Comment by rfultz** [comment]
This work was basically done
