### ISSUE TITLE
Decide on services to showcase on status page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3949]
**What we're after:** Decide on a proposed list of services in which we will have a status. Enhance pingdom data. These can only include things that can be automated. 

**Related work:**
- https://github.com/fecgov/fec-cms/issues/3908 Test the status page tool that we think will work best for us
- https://github.com/fecgov/fec-cms/issues/3909 Finalize status page tool selection
- https://github.com/fecgov/fec-cms/issues/3911 Procure status page tool
- https://github.com/fecgov/fec-cms/issues/3839 Document workflow for posting to website status

**Completion criteria:**
- [ ] List of services is compiled and agreed to for status page

**Comment by JonellaCulmer** [comment]
Compiling list of services here: https://docs.google.com/spreadsheets/d/1ykAuWjL65uZm-sLt7IcOEWmz6h6EAP4lUYCd-5QXW4Q/edit#gid=286623407

**Comment by JonellaCulmer** [comment]
Below is a complete list of the components we plan to include on the status page:

**Group: Legal resources**
- AOs
- Regulations
- Statutes
- MURs
- Enforcement Query System: Legacy MURs
- Enforcement Query System: Alternative Dispute Resolution
- Enforcement Query System: Administrative fines
- Audits

**Group: Campaign finance data**
- Raising
- Spending
- Candidates
- Committees
- Filings and reports
- Loans
- Downloads
- Data refresh

**Group: Help for candidates and committees**
- Reports Analysis Division analyst contact form
- Compliance resources

**Group: openFEC API**
- Candidate
- Committee
- Dates
- Financial
- Search
- Filings
- Receipts
- Disbursements
- Loans
- Debts
- Independent expenditures
- Party coordinated expenditures
- Communication cost
- Electioneering 
- Presidential
- Filer resources
- Efiling
- Audit
- Legal

**USAJobs career postings**

**Group: Efling**
- Filing form images
- Online web forms
- Electronic filing submission system
- Electronic filing vendor tools

**Comment by patphongs** [comment]
@JonellaCulmer I believe on the new website, the MURs are all loaded into Elasticsearch no matter if it's archived or current. So when we post a status message about it, we can reference it as MURs and then we can get more specific in the description as archived MURs if that's what we're having issues with.
