### ISSUE TITLE
Migrate two policy comment pages to Wagtail

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3954]
### Summary
What we are after:
As a person who keeps track of a federal agency's decisions, I need to see the complete record of the Commission's decisions on policy and procedures.

### Background
Like rulemakings, when the Commission works on policy statements, interpretive rules and other types of procedure notices, it will put out a request for comment. Unlike rulemakings, which store the comments received in SERS, we don't have a database for these and have been linking them on the Policy page. In some cases, we had a lot of comments and pages were created on transition to house them. We need to create similar pages in Wagtail (MVP) so that we can retire the transition pages and not clunk up the forthcoming new Policy page with long lists of commenters.

### Related issues
#3220 - Planning for policy page
#3470 - Implementing the new policy page (Note: these pages will link to the new policy page)

### Action Items
- [x] Upload the comments and any related Federal Register notice into CMS (they are stored in the InfoProj network folder for the Policy page, in a subfolder rof Policy Page PDFs - look for the ones related to their topics)
- [x] Create the new pages as child pages of Legal Resources | Policy and other guidance with a good slug (don't use transition versions of the slugs; custom page format should work)
- [x]  Second pair of eyes before publication
- [x]  Publish new pages
- [x]  Update any related links on old or new pages (Policy page, related hearing pages) as needed
- [x]  Add to redirect spreadsheet

### Completion Criteria
- [x] These two pages and related PDF files are migrated to the CMS
https://transition.fec.gov/law/policy/enforcement/2013/2013commentsreceived.shtml
https://transition.fec.gov/law/policy/embezzle/embezzlementpolicycomments.shtml

(For ease in redirect, consider naming PDF files the same name as they are now.)

- [x] All new links to PDFs, comment pages are added to redirect spreadsheet
- [x] Related links on Policy page are updated

Future work
-  Implement redirects for these
- Taking the old files down after redirects are implemented

**Comment by kathycarothers** [comment]
I have uploaded all the documents, but one. There is one document that Wagtail/CMS is not accepting and need to figure out why this is happening.

**Comment by kathycarothers** [comment]
The first page is ready for review. I am going to start on the second page now. Once both pages are ready for review then I will circulate them.

**Comment by kathycarothers** [comment]
The second page has been drafted. I am going to take a break from them and revisit them tomorrow before sending them for review.

**Comment by kathycarothers** [comment]
The pages are ready for review. I will send an email out and note on Slack.
