### ISSUE TITLE
Migrate 2009 internet hearing comments page to Wagtail

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3955]
### Summary
What we are after:
As a person who keeps track of a federal agency's decisions, I need to see the complete record of the Commission's decisions on policy and procedures.

### Background
Like rulemakings, when the Commission works on policy statements, interpretive rules and other types of procedure notices, it will put out a request for comment. Unlike rulemakings, which store the comments received in SERS, we don't have a database for these and have been linking them on the Policy page. In some cases, we had a lot of comments and pages were created on transition to house them. We need to create similar pages in Wagtail (MVP) so that we can retire the transition pages and not clunk up the forthcoming new Policy page with long lists of commenters.

### Related issues
#3220 - Planning for policy page
#3470 - Implementing the new policy page (Note: these pages will link to the new policy page)
#3974 -  Uploading the PDFs

### Action Items
- [ ] ~Upload the comments and any related Federal Register notice into CMS (we will need to make the PDFs first and save them in the InfoProj network folder for the Policy page, in a subfolder of Policy Page PDFs - look for the ones related to their topics)~ This is big enough to have its own ticket at #3974 
- [x] Create the new page as child pages of Legal Resources | Policy and other guidance with a good slug (don't use transition versions of the slug; custom page format should work)
- [x]  Second pair of eyes before publication
- [x]  Publish new pages
- [x]  Update any related links on old or new pages (Policy page, [related hearing page](https://www.fec.gov/updates/7-29-8-25-2009-public-hearings-website-internet-communications-improvement-initiative/) as needed
- [x]  Add to redirect spreadsheet

### Completion Criteria
- [x] This page and related PDF files are migrated to the CMS
https://transition.fec.gov/pages/hearings/internethearingcomments.shtml
- [x] All new links to PDFs, comment pages are added to redirect spreadsheet
- [x] Related links on Policy and hearing pages are updated

### Future work
-  Implement redirects for these
- Taking the old files down after redirects are implemented

**Comment by djgarr** [comment]
work completed and pages created and updated. closing the ticket
