### ISSUE TITLE
Migrate data summary landing page on transition to wagtail

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3958]
**What we're after:**
As part of the migration of the historical statistics work (now exclusively called Campaign finances statistics), we need to migrate a few pages over. These pages include: 
- Campaign finance statistics: https://transition.fec.gov/press/campaign_finance_statistics.shtml
- Formula for 1989-2010: https://transition.fec.gov/press/summaries/help/statistical_1975_2010.shtml
- Formula for after 2010: https://transition.fec.gov/press/summaries/help/statistical_post2010.shtml

For the first page, Campaign finance statistics, we need to follow the mockup below in the #Designs section 

Approved content and linking notes: https://docs.google.com/document/d/1gw1ZrXzXjKP1GavgsLW1HkcCdlGvJDaDyxilODSAkDE/edit#heading=h.3mlmgt6o1ktz

### Related issues
- https://github.com/fecgov/fec-cms/issues/3816 Design Election Cycle Summary pages
- https://github.com/fecgov/fec-cms/issues/3943 Implement filterable campaign finance data summaries

**Action items:**
- [x] Review the mockup, then with group consensus, begin to migrate content

### Completion criteria

- [x] The three aforementioned pages are rebuilt in wagtail
- [x] Handle redirects, or make followup ticket to address this

### Design
![Campaign stats_3](https://user-images.githubusercontent.com/31663028/89459103-25c38d80-d736-11ea-8523-300f73fc6c01.png)

**Comment by JonellaCulmer** [comment]
This issue is blocked until we have the links to the new filterable data table pages. That work is happening here: https://github.com/fecgov/fec-cms/issues/3943

**Comment by kathycarothers** [comment]
I've started drafting the first page in list Campaign finance statistics

**Comment by kathycarothers** [comment]
@JonellaCulmer  what type of template were you thinking for these two pages? 

Formula for 1989-2010
Formula for after 2010

**Comment by JonellaCulmer** [comment]
@kathycarothers I think the custom template would work perfectly.

**Comment by kathycarothers** [comment]
@JonellaCulmer got it. thank you!

**Comment by kathycarothers** [comment]
@JonellaCulmer Should this page a resource template too? https://transition.fec.gov/press/summaries/help/statistical_1975_2010.shtml With the headers being Presidential candidate tables etc.

**Comment by JonellaCulmer** [comment]
@kathycarothers If you think that the resource page would work better for those pages, I'll defer to you. I just know that it would be a lot of tables and we should give those tables a bit more breathing room on a custom page rather than a resource page.

**Comment by kathycarothers** [comment]
@JonellaCulmer  I created two drafts one as a resource template and the other one as a custom. I think the resource template is going to navigate better. Let me know when you have a chance on Monday and I can show you the two drafts. They are in Wagtail if you just want to pop in and look too.

**Comment by kathycarothers** [comment]
The formula for 1989-2010 has been drafted in Wagtail.

**Comment by kathycarothers** [comment]
Pages have been drafted. I am doubling checking them before I send them out for review.

**Comment by kathycarothers** [comment]
The 3 pages are now drafted and will need to be reviewed, and the green light is signaled published. Once published the redirect ticket can be made. A sheet has been added in the redirect excel file named Press Statistical pages. @JonellaCulmer

**Comment by kathycarothers** [comment]
@dorothyyeager @JonellaCulmer I have added the glossary terms to the pages.

**Comment by jason-upchurch** [comment]
@kathycarothers  I moved this to innovation sprint in preparation for the next iteration. Please let me know if I need to reprioritize it--thank you!

**Comment by johnnyporkchops** [comment]
@kathycarothers ,per our conversation,  I have gone in and linked all of the items in this draft : https://fec-prod-proxy.app.cloud.gov/admin/pages/11049/view_draft/

**Comment by kathycarothers** [comment]
This page and its links will be ready to publish on Oct 26

**Comment by kathycarothers** [comment]
I have created the redirect tab for the pages that will be affected by this migration. The pages have been inputted.

**Comment by kathycarothers** [comment]
The archived links have not been added to the redirect spread sheet.

**Comment by kathycarothers** [comment]
Pages have been published.
