### ISSUE TITLE
[Snyk: Med Severity] Cross-site Scripting (XSS) (Due: 10/04/2020)

### ISSUE THREAD

**Issue by fec-jli** [fecgov/fec-cms#3959]
Cross-site Scripting (XSS)
[https://app.snyk.io/vuln/SNYK-PYTHON-WAGTAIL-585980](https://app.snyk.io/vuln/SNYK-PYTHON-WAGTAIL-585980)

Remediation:
Upgrade wagtail to version 2.7.4, 2.9.3 or higher.

**Completion criteria:**
- [x] Verify this is still an issue and make an appropriate change to address vulnerability

**Comment by jason-upchurch** [comment]
This is no longer flagged by snyk. Closing.
