### ISSUE TITLE
All-meetings page keyword search does not seem to work

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#3962]
### Summary

_What happened?_
The search box  on the all-meetings page does not seem to work

Page:
https://www.fec.gov/updates/june-18-2020-open-meeting/

_What should have happened?_

According to the original issue, it is supposed to be a keyword search:
https://github.com/fecgov/fec-cms/issues/1138#issuecomment-316169219

Related Issue: https://github.com/fecgov/fec-cms/issues/1138
Related PR: https://github.com/fecgov/fec-cms/pull/1166
### Frequency

_an ongoing issue,_

### How to Reproduce

_List any steps you took for this issue to happen. Be sure to include the URL and what you clicked or entered. More details are better._
URL: https://www.fec.gov/…

1. https://www.fec.gov/meetings/
2. Search something in the search box next to the dropdown filter 

### Screenshots

<img width="1137" alt="Screen Shot 2020-08-06 at 3 21 34 PM" src="https://user-images.githubusercontent.com/5572856/89573417-93d08900-d7f8-11ea-8b30-29c6f0e0663c.png">

**Comment by patphongs** [comment]
Duplicate, closing in favor of https://github.com/fecgov/fec-cms/issues/4473
