### ISSUE TITLE
[September] - Manually update wagtail global search index

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-cms#3964]
###Summary
**What we're after:**
We need to update the global search.gov index for new pages that were published in August/September.

Related issues
#3874  

**Completion criteria**

- [x] Follow instructions under [Adding CMS pages to the index](https://github.com/fecgov/fec-cms/blob/develop/fec/search/management/instructions.md#adding-cms-pages-to-the-index)
- [x]  Create ticket for next month October for manual wagtail global search index

**Comment by patphongs** [comment]
Last indexed page count: 893 (indexed on 08/07/2020)
New indexed page count: 897 (indexed on 09/17/2020)

Created new ticket to scrape and index the pages for October https://github.com/fecgov/fec-cms/issues/4046
