### ISSUE TITLE
Update FEC.gov content guide for accessibility

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-cms#3965]
### Summary

**What we're after:**
We would like to ensure the content guide conforms to style, e.g., accessibility

### Suggested completion criteria
- [x] review content guide content for conformance to rules specified in content guide
- [ ] have team discussion to consider publishing the content guide in one of our repository wiki's for version control and transparency

**Comment by JonellaCulmer** [comment]
This is done, so closing.

**Comment by jason-upchurch** [comment]
added "have team discussion" to completion criteria.
issue reopened ensure team inputs. No milestone  assigned so that this  issue doesn't get in the way of other work this sprint.

**Comment by dorothyyeager** [comment]
Content team has decided to close this issue in favor of a more general review to follow the work we've done migrating court cases and Audit reports. New issue is at https://github.com/fecgov/fec-cms/issues/4335
