### ISSUE TITLE
Take down elecfil/ and other redirected files off of transition site

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3967]
### Summary

**What we are after:**
_We are getting off of transition_

### Related issues

_List any relevant related issue(s)_

- #3894 

### Completion criteria

- [x] Entire directory of /elecfil/ (and subdirectories and files within) removed from transition and from any search index
- [x] These pages are also removed:

/pages/brochures/partner.shtml
/pdf/firsttenyearsreport.pdf
/pdf/20year.pdf

**Comment by patphongs** [comment]
Additional pages that were deleted. Confirmed by @dorothyyeager to be outdated pages that have been redirected:

/pages/brochures/ao.shtml
/pages/brochures/admin_fines.shtml
/pages/brochures/millionaires_brochure.pdf

**Comment by patphongs** [comment]
The following pages have been deleted from transition:

delete: '/elecfil/PAPER_Format_v3.0.xlsx'
delete: '/elecfil/PaperFormats.zip'
delete: '/elecfil/VenPak.zip'
delete: '/elecfil/VendPak5-2-0-1-20050128.zip'
delete: '/elecfil/authorized_manual/bAuth.pdf'
delete: '/elecfil/authorized_manual/cAuth.pdf'
delete: '/elecfil/authorized_manual/gAuth.pdf'
delete: '/elecfil/eFilingFormats.zip'
delete: '/elecfil/formats/bauthrs.htm'
delete: '/elecfil/formats/bradthrs.htm'
delete: '/elecfil/formats/buchthrs.htm'
delete: '/elecfil/formats/dolethrs.htm'
delete: '/elecfil/formats/gorthrs.htm'
delete: '/elecfil/formats/keythrs.htm'
delete: '/elecfil/formats/laruthrs.htm'
delete: '/elecfil/formats/mccathrs.htm'
delete: '/elecfil/formats/quathrs.htm'
delete: '/elecfil/images/toolkit.jpg'
delete: '/elecfil/mistakes.shtml'
delete: '/elecfil/passwords.shtml'
delete: '/elecfil/sample_letter.htm'
delete: '/elecfil/sample_letter_NC.htm'
delete: '/elecfil/updatelist.html'
delete: '/elecfil/updatelist.shtml'
delete: '/pages/brochures/admin_fines.shtml'
delete: '/pages/brochures/ao.shtml'
delete: '/pages/brochures/millionaires_brochure.pdf'
delete: '/pages/brochures/partner.shtml'
delete: '/pdf/20year.pdf'
delete: '/pdf/firsttenyearsreport.pdf'
