### ISSUE TITLE
Approve Google Tag Manager on production

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3971]
**What we're after:**
Approve Google Tag Manager on production. The GA events on GTM mimic what's on production right now.

**Related tickets:**
- https://github.com/fecgov/fec-cms/issues/3972
- https://github.com/fecgov/fec-cms/issues/3973

**Action item:**
- [ ] Someone else on the team verifies the events are functioning properly

**Completion criteria:**
- [ ] GTM events are on production and function properly

**Comment by rfultz** [comment]
@patphongs @JonellaCulmer @johnnyporkchops the PRODUCTION container in GTM is ready for your review (version RC4)

Comment here with any changes…? There's no code to merge so no PR

**Comment by rfultz** [comment]
Closing because GTM is live on Prod and is working as expected
