### ISSUE TITLE
Duplicate Google Tag Manager to prod

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3972]
**What we're after:**
Duplicate GTM to prod

**Related ticket:**
- https://github.com/fecgov/fec-cms/issues/3971 
- https://github.com/fecgov/fec-cms/issues/3973

**Action items:**
- [ ] Duplicate non-prod (TBD from non-prod ticket here: https://github.com/fecgov/fec-cms/issues/3971)

**Completion criteria:**
- [ ] Duplication to production is completed

**Comment by rfultz** [comment]
Closing because GTM is live on Prod and is working as expected
