### ISSUE TITLE
Deploy Google Tag Manager with env vars 

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3973]
**What we're after:** 
Deploy with env vars (reverse if needed)

**Related tickets:**
- https://github.com/fecgov/fec-cms/issues/3972
- https://github.com/fecgov/fec-cms/issues/3971

**Action items:**
- [x] Flip on the feature flag without removing it from the code

**Completion criteria:**
- [x] Deployed 
- [ ] Remove the old GA

**Future work:**
- [x] Verify that the analytics are coming out okay. If not, take steps to fix with a follow-up ticket
- [ ] When we're comfortable with the analytics, then remove the feature flag from the code for GTM

**Comment by jason-upchurch** [comment]
@rfultz I moved this to innovation sprint in preparation for the next iteration. Please let me know if I need to reprioritize it--thank you!

**Comment by rfultz** [comment]
This one has a checkbox for removing the old GA code but that's listed in #3160 , too, so I'm going to close this ticket
