### ISSUE TITLE
Make 2009 internet hearing PDFS accessible and upload to CMS

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#3974]
### Summary

**What we're after:**
_As a person who keeps track of a federal agency's decisions, I need to see the complete record of the Commission's decisions on policy and procedures._

### Related issues

- #3955 

### Completion criteria

- [x] PDFs linked on this page - https://transition.fec.gov/pages/hearings/internethearingcomments.shtml are made accessible and saved to InfoProj\Policy Page Update\Policy Page PDFs\Internet hearing 2009
(For ease in redirect, consider naming PDF files the same name as they are now.)
- [x] PDFs are uploaded to CMS.

### Future work

Next steps will be in #3955.

**Comment by djgarr** [comment]
created pdfs of the comments on the internet hearing page. need to double check the documents

**Comment by djgarr** [comment]
documents are accessible and have been uploaded to wagtail
