### ISSUE TITLE
Transition pages to take down (Policy pages enforcement and embezzlement) 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#3976]
### Summary

**What we're after:**
_To remove the outdated pages from transition now that the redirects are in place. These were redirected in #3975._

### Completion criteria

_ [ ] The following pages are removed from transition and from the search.gov index of transition pages (if they are there)._

/law/policy/enforcement/2013/mjbauer.pdf
/law/policy/enforcement/2013/danacohn1.pdf
/law/policy/enforcement/2013/danacohn2.pdf
/law/policy/enforcement/2013/centercomppolitics.pdf
/law/policy/enforcement/2013/centercomppoliticscover.pdf
/law/policy/enforcement/2013/perkinscoie.pdf
/law/policy/enforcement/2013/perkinscoiecover.pdf
/law/policy/enforcement/2013/josefiaktorshinskybayes.pdf
/law/policy/enforcement/2013/josefiaktorshinskybayescover.pdf
/law/policy/enforcement/2013/progressivesunited1.pdf
/law/policy/enforcement/2013/progressivesunited2.pdf
/law/policy/enforcement/2013/joeorawczyk.pdf
/law/policy/enforcement/2013/rnccounsel.pdf
/law/policy/enforcement/2013/rnccounselcover.pdf
/law/policy/enforcement/2013/roberterutkowski.pdf
/law/policy/enforcement/2013/crew.pdf
/law/policy/enforcement/2013/crewcover.pdf
/law/policy/enforcement/2013/gregsmith.pdf
/law/policy/enforcement/2013/clcdemocracy21.pdf
/law/policy/enforcement/2013/clcdemocracy21cover.pdf
/law/policy/enforcement/hearing/notice2013-01.pdf

/law/policy/embezzle/anesthesiologists.pdf
/law/policy/embezzle/anesthesiologists_cover.pdf
/law/policy/embezzle/fisher.pdf
/law/policy/embezzle/forrester.pdf
/law/policy/embezzle/indianamedical.pdf
/law/policy/embezzle/indianamedical2.pdf
/law/policy/embezzle/mcconnell.pdf
/law/policy/embezzle/mitchell.pdf
/law/policy/embezzle/namewithheldduetomur.pdf
/law/policy/embezzle/ryan.pdf
/law/policy/embezzle/statemedassn.pdf
/law/policy/embezzle/steveisraelforcongress.pdf

/law/policy/enforcement/2013/2013commentsreceived.shtml
/law/policy/embezzle/embezzlementpolicycomments.shtml

/pages/hearings/internethearingcomments.shtml

/law/policy/internet09/082109websitecomments.pdf
/law/policy/internet09/072909websitecomments.pdf
/law/policy/internet09/072709websitecomments.pdf
/law/policy/internet09/072109websitecomments.pdf
/law/policy/internet09/072009websitecomments.pdf
/law/policy/internet09/071809websitecomments.pdf
/law/policy/internet09/071709websitecomments.pdf
/law/policy/internet09/071609websitecomments.pdf
/law/policy/internet09/071409websitecomments.pdf
/law/policy/internet09/070809websitecomments.pdf
/law/policy/internet09/070609websitecomments.pdf
/law/policy/internet09/070109websitecomments.pdf
/law/policy/internet09/6-29-09websitecomments.pdf
/law/policy/internet09/6-28-09websitecomments.pdf
/law/policy/internet09/6-27-09websitecomments.pdf
/law/policy/internet09/6-26-09websitecomments.pdf

**Comment by dorothyyeager** [comment]
After talking with @patphongs - we'll hold off on taking these pages down for now. It might be easier both redirect-wise and take-down-wise to do all the future policy page redirects/takedowns as one big bunch.

Closing this ticket in favor of a future ticket we'll open when we're ready to do this.
