### ISSUE TITLE
Update circle ci python image to be consistent with runtime version

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-cms#3978]
**What we're after:**
Current runtime environment is 3.7.8 as specified by 3.7.x in runtime.txt. However, current circle ci image is 3.7.4 per .config.yml.

Let's make these consistent so that the tests run are with the same version as the runtime environment for our app.

### Completion criteria
- [ ] circle ci version are updated to match what's in runtime 

### Related issues
- #522
- #3978 
- #https://github.com/fecgov/openFEC/issues/4425

**Comment by pkfec** [comment]
Python docker image **3.7.8-stretch-node-browsers** comes with **node v12.18.3** which is incompatible with our current CMS environment.

**Comment by pkfec** [comment]
Node LTS release versions:
<img width="792" alt="Screen Shot 2020-10-01 at 9 49 41 AM" src="https://user-images.githubusercontent.com/11650355/94817874-7e787500-03cb-11eb-81d6-5cf7b2e4b1d5.png">
