### ISSUE TITLE
Automate commissioner page content to document pages for new feed

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3982]
**What we're after:**
To mitigate some of the tedious and time-consuming work of a manual migration for commissioner pages from links (some external) to Wagtail pages, we want to attempt to automate this process. 

### Related issues
- #3947 

### Completion criteria
- [ ] Attempt to automate document pages or open followup issue for manual input for 13.4

**Comment by johnnyporkchops** [comment]
Here is how we could possibly do this using similar process as the  [InfoWeb Wagtail migration](https://github.com/fecgov/fecnet/issues/209), minus the scraping part.

**Data:**
- Make a copy of the spreadsheet that the commissioners offices created for the documents/items
- Modify this spreadsheet so column names reflect Wagtail blocks,  add any other needed columns,  save to CSV
- Make another spreadsheet for page IDs and Django TreeBeard path, save to CSV
- Write SQL insert statements for CSV

**Migration:** 
- Get the latest db dump from production and restore it to dev
- Put a content freeze on production, so no new pages are created there.
- Use PSQL to write the CSV to the WagtailCorePage and CommissionerItem database tables in dev
- test in dev
- Dump the dev db
- Do a zero downtime restore to production

**Comment by JonellaCulmer** [comment]
Blocked while we wait for conversation with commissioner office tomorrow.

**Comment by rfultz** [comment]
We need to create the pages ( #4006 ), but we need to look into automating it first

**Comment by patphongs** [comment]
This is no longer needed as we are shifting in a different direction. Closing this issue.
