### ISSUE TITLE
Update privacy policy and add URL language to feedback box

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#3985]
**What we're after:**
Following on some recent feedback received in the FEC repo (through the feedback box) we need to update our language to clarify what information we collect when feedback is submitted. 

Privacy policy: https://www.fec.gov/about/privacy-and-security-policy/

Action items: 
- [x] Draft new language for privacy policy
- [x] Draft new language for feedback box
- [x] Make changes in both places 

**Completion criteria:**
- [x] Privacy policy is updated
- [ ] Feedback box is updated

**Comment by JonellaCulmer** [comment]
@AmyKort @PaulClark2 @patphongs @dorothyyeager I've drafted language changes for the privacy policy and feedback box to clarify that we capture the URL of the page the user was viewing when they submit the form. I think the language for the feedback box is a little long, so if you see anyway to shorten that I'm all ears. 

### Draft [privacy policy](https://www.fec.gov/about/privacy-and-security-policy/) language changes: (suggested changes in bold):

**Before:**
When submitting feedback via the feedback tool at the bottom of the page, your messages are sent to a public repository on GitHub and the content of your message (as well as information about the browser you used to submit the form) will be publicly available. In addition to saving the text of the message, we also capture information about your browser in order to help troubleshoot any bugs that may be reported.

**After (with markup):**
When submitting feedback via the feedback tool at the bottom of the page, your messages are sent to a public repository on GitHub **.** ~~and~~ The content of your message **,** ~~(as well as~~ information about the browser you used to submit the form **, and the URL of the page you were viewing when you submitted the form** ~~)~~ will be publicly available. In addition to saving the text of the message, we also capture information about your browser in order to help troubleshoot any bugs that may be reported.

**After without markup:**
When submitting feedback via the feedback tool at the bottom of the page, your messages are sent to a public repository on GitHub and the content of your message, information about the browser you used to submit the form, and the URL of the page you were viewing when you submitted the form will be publicly available. In addition to saving the text of the message, we also capture information about your browser in order to help troubleshoot any bugs that may be reported.


### Draft feedback box language:

**Before:**
Tell us how we can improve the site using the form. This feedback will be posted publicly, so don't include sensitive information like your name, contact information or Social Security number.

**After with markup:**
Tell us how we can improve the site using the form. This feedback will be posted publicly, so don't include sensitive information like your name, contact information or Social Security number. **The content you provide, information about your browser and the URL of the page you were viewing when the form was submitted will be publicly available.**

**Comment by dorothyyeager** [comment]
@JonellaCulmer Looks good to me. You've got an oxford comma after _browser_ in the privacy policy sentence but it's not there in the feedback box sentence. GPO style is no comma, but for this I think having the comma makes it clearer. Either way you go, just should be the same for both.

**Comment by PaulClark2** [comment]
@JonellaCulmer these changes look good to me.  I'm generally opposed to Oxford commas but will defer to folks in the content team.

**Comment by JonellaCulmer** [comment]
Thank you @PaulClark2 @dorothyyeager I will eliminate the oxford comma.

**Comment by patphongs** [comment]
@JonellaCulmer  For the privacy policy, I wonder if we can be a little more concise with our message. We can certainly add more words if we need to make it more clear, but I wanted to get our message across in less words if possible.

> When submitting feedback via the feedback tool at the bottom of the page, your messages are sent to a publicly available repository on GitHub including your message, information about the browser you used to submit the form, and the URL of the page you were viewing when you submitted the form. We capture information about your browser in order to help troubleshoot any bugs that may be reported.

In terms of the feedback box, I'd like to make that text shorter as well? But I just don't know how to do that. Adding text to what's already there seems like a lot to read and elongates the box more. Just something to keep in mind, I'm ok with keeping the feedback box text as you have it though.

**Comment by JonellaCulmer** [comment]
@patphongs I think you're right. We can tweak the last sentence of the privacy policy. As is, it's a bit redundant. 

For the feedback box, I cut out some words: 
**How can we improve FEC.gov?** This feedback will be posted publicly, so don't include sensitive information like your name, contact information or Social Security number. **Your feedback**~~The content you provide~~, **browser** information ~~about your browser~~ **and the URL of the page viewed at the time of submission** will be publicly available.**

**Comment by patphongs** [comment]
Thanks @JonellaCulmer, I like how you've rewritten the feedback box text!

**Comment by JonellaCulmer** [comment]
So...I made another modification to the text. 

### Draft mockup with new text:
![Feedbackbox_update](https://user-images.githubusercontent.com/31663028/91209941-7d706b80-e6da-11ea-98db-6a59b2bf24ee.jpg)

If there are any objections, I can go ahead and update the Privacy policy on .gov and put in a ticket to implement the feedback box changes.
