### ISSUE TITLE
Add new PCC to PAC converted committees

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#3998]
### Summary

After candidates converted their PCCs to PACs, we need to add language to the candidate and committee pages to indicate the committee changed from an authorized committee to an unauthorized committee at a point during the election cycle for the following candidates/committees: 

- Rebellion PAC (C00727008) (formerly Cenk for Congress) (Candidate ID H0CA25170)
- The Blue Initiative (C00712224) (formerly Jeffrey A. Sites for Congress) (Candidate ID H0OH04085)
- Black Conservative Movement (C00706564) (formerly Lerah Lee for Congress) (Candidate ID H0GA07265)
- People Powered Action (C00699090) (formerly Beto for America) (Candidate ID P00010793)

See this hotfix as an example of how this was implemented in the past: https://github.com/fecgov/fec-cms/pull/3953

### Completion criteria

- [x] Add text to C00727008 and H0CA25170
- [x] Add text to C00712224 and H0OH04085
- [x] Add text to C00706564 and H0GA07265
- [x] Add text to C00699090 and P00010793
- [ ] Deploy changes

**Comment by lbeaufort** [comment]
Hotfix has been deployed
