### ISSUE TITLE
Consider language changes needed for Deval for All

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4000]
**What we're after:**
As part of our exploration for committees who have made mid-cycle conversions from PCCs to PAC, we came across Deval Patrick’s committee (Deval for All, P00014407). While this committee converted similarly to others we've identified, the committee never changed their name and shortly after converting, terminated. Because of this difference, we need to now account for it on the front-end and display clear and helpful information for our users that makes locating financial information easy.  

For other committees that convert, we provide the old and new committee name and restore the connection between a (former) candidate and their committee to alleviate the some of the burden of discovery for our users. Unfortunately, that solution does not work for Deval's committee. This ticket is to better understand the problem for this committee and consider solutions that address that problem.

**Current language (template) for candidate profile pages:**
- Example: PCC -> PAC conversion with name change
2019–2020 financial data for **BUTTIGIEG, PETE** now appears under the committee name **WIN THE ERA PAC**, following the committee's conversion to a PAC from a principal campaign committee. Prior to its conversion to a PAC the candidate's principal campaign committee was named **PETE FOR AMERICA, INC.**.

- Example: PCC -> PAC conversion **without** name change
2019–2020 financial data for **PATRICK, DUVAL** now appears under the committee name **DEVAL FOR ALL**, following the committee's conversion to a PAC from a principal campaign committee. Prior to its conversion to a PAC the candidate's principal campaign committee was named **DEVAL FOR ALL**.

**Current language (template for committee profile pages:**
- Example: PCC -> PAC conversion with name change
Financial data for this committee contains funds raised and spent under the former name **PETE FOR AMERICA, INC.** which, before it was converted, was a principal campaign committee. Before its conversion this committee was authorized by candidate **BUTTIGIEG, PETE**.

- Example: PCC -> PAC conversion **without** name change
Financial data for this committee contains funds raised and spent under the former name **DEVAL FOR ALL**. which, before it was converted, was a principal campaign committee. Before its conversion this committee was authorized by candidate **PATRICK, DUVAL**.

**Related issues:**
- https://github.com/fecgov/fec-cms/issues/3897 Add language to PACs (that were formerly PCCs) and candidate pages to indicate committee-type conversion
- https://github.com/fecgov/fec-cms/issues/3806 Design solution for candidates with missing data from a committee conversion
- Slack thread including some discussion of Deval for All, https://fecgov.slack.com/archives/C3W9XBBJL/p1598459943057100

**Completion criteria:**
- [ ] Language and (possible design) is drafted to address Deval problem
- [ ] Implementation issue is opened

**Comment by JonellaCulmer** [comment]
@patphongs @PaulClark2 @lbeaufort Below is the draft language for the Deval for All committee (and others that are affected the same way). Let us (me, @bmathesonFEC, @djgarr) know if you have any comments or concerns. 

**Candidate profile page:**
2019–2020 financial data for PATRICK, DUVAL appears under the committee name DEVAL FOR ALL. This committee converted to a PAC (glossary link) from a principal campaign committee. (glossary link) 

**Committee profile page:**
Financial data for this committee contains funds raised and spent prior to the committee's conversion from a principal campaign committee (glossary link) to a PAC. (glossary link) Before its conversion this committee was authorized by candidate PATRICK, DUVAL.

**Comment by lbeaufort** [comment]
@JonellaCulmer looks good to me!

**Comment by PaulClark2** [comment]
The language looks fine. When we automate this process how will this work? The sql under development does not look at committee names.

**Comment by lbeaufort** [comment]
After further review while answering Paul's question, I have a suggestion:

The SQL in development is going to provide `first_cmte_nm` and `latest_cmte_nm`. I propose the front-end does the following:
Where `first_cmte_nm` **does not** equal `latest_cmte_nm`, message 1: (current behavior)
>2019–2020 financial data for <candidate_name> now appears under the committee name <latest_cmte_nm> following the committee's conversion to a PAC from a principal campaign committee. Prior to its conversion to a PAC the candidate's principal campaign committee was named <first_cmte_nm>.

Where `first_cmte_nm` **does** equal `latest_cmte_nm`, message 2: 
(Option 1 behavior per @JonellaCulmer )
>2019–2020 financial data for <candidate_name> ~now~ appears under the committee name <latest_cmte_nm> ~following the committee's conversion.~ This committee converted to a PAC from a principal campaign committee. ~Prior to its conversion to a PAC the candidate's principal campaign committee was named <first_cmte_nm>.~

(Option 2 behavior per @lbeaufort)
>2019–2020 financial data for <candidate_name> now appears under the committee name <latest_cmte_nm> following the committee's conversion to a PAC from a principal campaign committee. ~Prior to its conversion to a PAC the candidate's principal campaign committee was named <first_cmte_nm>.~

Google doc with difference: https://docs.google.com/document/d/1z_yOqfvndNLqChs0mYCrSSlgDwqwNYZu32VB3o_oCe0/edit

Option 2 just removes the last sentence so it's more consistent with option 1 (commmitee name changed) and allows us to have simpler logic in the code. Thoughts?

**Comment by PaulClark2** [comment]
The front-end logic makes sense to me. I like Option 2. It makes the messages very consistent.

**Comment by JonellaCulmer** [comment]
@lbeaufort @PaulClark2 @bmathesonFEC @djgarr The words "now" and "following" are misleading here. There was no name change before and after the committee converted. I'd appreciate another look at what we proposed. 

@djgarr @bmathesonFEC If you two are fine with option 2 we can move forward. I'll defer to the content team.

**Comment by djgarr** [comment]
I agree with @JonellaCulmer that the words 'now' and 'following' in these contexts seem to indicate there was a difference between the pre- and post- committee's name. My preference would be to stick with the first option

**Comment by lbeaufort** [comment]
@PaulClark2 @JonellaCulmer @djgarr thanks for adding your feedback.
These messages are for the **candidate profile page**: 
>2019–2020 financial data for <candidate_name> now (or not) appears under the committee name <latest_cmte_nm>

I believe the subject of the message is the financial data, not the committee name. I believe the point of the message is to explain where the money went. "The money now shows up in this other place". Maybe we should set up a call to discuss. I'm ok with the "now" or "not the now" but if we're talking about the money moving, I think the message should be the same regardless of the committee name where the money now shows up. 

Happy to discuss on a call!

**Comment by djgarr** [comment]
@PaulClark2 @JonellaCulmer @bmathesonFEC @lbeaufort 

After various conversations, it seems like this might be language that works:

**Candidate profile page without name change**:
[ELECTION CYCLE INFORMATION] financial data for [CANDIDATE NAME] appears under the committee name [COMMITTEE NAME]. The principal campaign committee (glossary link) for this candidate was converted to a PAC (glossary link).

**Candidate profile page with name change**:
[ELECTION CYCLE INFORMATION] financial data for [CANDIDATE NAME] appears under the committee name [COMMITTEE NAME]. The principal campaign committee (glossary link) for this candidate was converted to a PAC (glossary link). The previous name for the principal campaign committee was [NEW COMMITTEE NAME]. 

**Committee profile page:** 
Financial data for this committee contains funds raised and spent prior to the committee's conversion from a principal campaign committee (glossary link) to a PAC. (glossary link). Before its conversion this committee was authorized by candidate [CANDIDATE NAME].

The main goal for the candidate page language was to present language that could be applicable for both situations where a name did or did not change, but to have the ability to add an additional line at the end for the name change in those situation. Hopefully this solves that issue.

**Comment by JonellaCulmer** [comment]
Works for me, @djgarr. Thank you for working on this some more. 

We'll need to put in a separate ticket to change the other candidate profile pages. I can do that if everyone is comfortable with moving forward.

**Comment by JonellaCulmer** [comment]
Since the there are no objections, I've opened a separate ticket to update the language in all instances in a future sprint.

https://github.com/fecgov/fec-cms/issues/4014
