### ISSUE TITLE
Finalize status page message template

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4004]
**What we're after:**
Finalize example status page messaging and template(s)

Draft templates and examples: https://docs.google.com/document/d/1DapPOsnSN7Q9P3E6OM2BHqYlHKj5ELHjt49BRpFFG5U/edit

**Completion criteria:**
- [ ] Clear status page messaging is drafted and ready for use

**Comment by dorothyyeager** [comment]
@JonellaCulmer I've updated the google document with an example for system maintenance (based on the banner we post now). Take a look and let me know your thoughts. Thanks!

**Comment by JonellaCulmer** [comment]
@dorothyyeager I made some slight modifications to the language you drafted. Changes are in red.

@lbeaufort @patphongs Please take a look at the templates when you have a moment. Dorothy and I previously discussed making this an exhaustive list and she made the point and I agree that we can start with this as a baseline for our responses and add to our list of templates as we become more familiar with the process.

**Comment by dorothyyeager** [comment]
@JonellaCulmer Those modifications work for me.

**Comment by dorothyyeager** [comment]
Have pinged @lbeaufort and @patphongs to take a last look at the draft.

**Comment by patphongs** [comment]
Thanks @dorothyyeager @JonellaCulmer for your work on this. I have edited to incorporate an "Update" status message in the doc. The rest of the template looks great!

**Comment by patphongs** [comment]
@JonellaCulmer @dorothyyeager and I have made significant changes to the document to also include statuses for system maintenance, which include statuses like: Scheduled, in-progress, verifying, and completed. Changes now look good to me, I approve!
