### ISSUE TITLE
Customize website status tool for our styles

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4005]
**What we're after:**
Customize tool for our styles. Blocked by procurement.

**Action items:**
- [x] Determine what our options are for the tool
- [x] Provide recommendations based on those options

**Completion criteria:**
- [x] Mock up are agreed upon and page is updated per the design

**Comment by patphongs** [comment]
Waiting for procurement, moved this forward one sprint

**Comment by JonellaCulmer** [comment]
@patphongs @AmyKort @PaulClark2 In addition to the visual styling for the page, we need to make a few decisions on what to call this page and any description for the page we'd like to include. 

**Here are my draft suggestions:** 
<img width="956" alt="Screen Shot 2020-09-29 at 3 31 16 PM" src="https://user-images.githubusercontent.com/31663028/94606696-d9458b80-0268-11eb-980c-27b613cd624d.png">

**Page with seal and name:** (This screenshot does not include the description text above)
<img width="976" alt="Screen Shot 2020-09-29 at 3 11 16 PM" src="https://user-images.githubusercontent.com/31663028/94606776-f37f6980-0268-11eb-855f-1b08481512bc.png">

**Comment by AmyKort** [comment]
Looks good to me. Thanks!

**Comment by patphongs** [comment]
Thanks @JonellaCulmer, context of the "About the page" text looks good. I just have one small missing word, "can", that I think should be added to the third sentence:

> You `can` also see past and upcoming...

**Comment by JonellaCulmer** [comment]
Updates have been made to the test page we have access to, but I will make sure these changes are made after procurement as well. Closing this ticket for now.
