### ISSUE TITLE
Test basic Wagtail functionality in staging before release on 9/8/2020

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#4009]
### Summary

**What we're after:**

After a small security upgrade: https://github.com/fecgov/fec-cms/pull/3990 and a sidebar change to the ResourcePage: https://github.com/fecgov/fec-cms/pull/3995 it would be good to take a little time to test some basic Wagtail functionality in the `staging` environment after the release is cut on 9/1 and before the release goes live on 9/8/2020

### Completion criteria
- [x] Basic Wagtail functionality works 
- [x] Sidebar appears properly on ResourcePage (see #3995 for how to test)
- [x] Enter a high-priority "before-release" ticket if there are any showstoppers or 13.5 tickets for any minor issues.

**Comment by djgarr** [comment]
Tested basic functioning. Everything is working properly. Added sidebar. Seems to be working properly. Not sure what exactly you need for the third testing item @lbeaufort 

![image](https://user-images.githubusercontent.com/40633757/91992049-acea2e00-ed01-11ea-89b8-e9d2a5ce6069.png)

**Comment by lbeaufort** [comment]
@djgarr thanks for testing! The last item is just to make sure to add tickets if there are any bugs, so I think we're good to go if you didn't find anything. Thanks again!

**Comment by djgarr** [comment]
I didn't find anything, so I'm closing the ticket
