### ISSUE TITLE
Unable to share accurate datatable links

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#4010]
**What we're after:**
We expect the links to the datatables to apply filters when the filter is in the URL.

@fec-issues-bot commented on [Thu Aug 27 2020](https://github.com/fecgov/FEC/issues/10195)

## What were you trying to do and how can we improve it?
 When I refresh or go to the page https://www.fec.gov/data/committees/?committee_type=H&committee_type=O&committee_type=P&committee_type=S I get https://www.fec.gov/data/committees/?committee_type=O. What gives? 

Bug: I'm trying to share a link to a datatable https://www.fec.gov/data/disbursements/?cycle=2020&data_type=processed&two_year_transaction_period=2020&line_number=F3X-23 , the URL isn't updating when I add spender committee type = PAC (corporate SSF). I get the correct results but when I hit refresh or try to share the link it goes to the wrong page. I think it happened on receipts too.

**Action items:**
- [ ] Fix known examples of filters not updating URLs
- [ ] ~Is this happening anywhere else—any other tables and/or parameters?~ (moved to #4316)
- [ ] ~Look for other examples~ (moved to #4316)

**Completion criteria:**
- [ ] Datatable filters correctly when URL with filters is shared

**Comment by rfultz** [comment]
Do we know if this ever worked as expected or if something's changed that _now_ it only applies one of them.

Looking at different parts of the code, there are a couple places where we have a list of H, P, and S but O is never included. Coincidental that of the passed vars in the example URL, O is the only one retained while it's not the first or last of the committee_type values and it's not part of the ["H", "P", "S"] lists?

**Comment by PaulClark2** [comment]
Also see, https://github.com/fecgov/FEC/issues/10576

**Comment by cnlucas** [comment]
The research is finished for this ticket. The issue seems to be with the spender/recipient committee type filters for receipts and disbursements. The issue also happens with the committees datatable, but instead of all of the committee type filters not working, it's only Authorized Committees and PAC's. 
https://docs.google.com/spreadsheets/d/1L2aviYhGmiUudYet6gXF4OzV-cy2AUUEWdmqJsVmwrI/edit#gid=0

**Comment by rfultz** [comment]
We dug into it more. Looks like filters with the same name need to be in the same `<filterset>`.

Next task is to group the `committee_type` elements into the same `<filterset>` but keep them as visually separated as they currently are.

Then put all the options to the test.

When we have an approach we like, check if there are other filters that need the same attention.

We should check again that filter counts are unaffected—maybe use that PR as a list of other filters to check
