### ISSUE TITLE
Implement converted committee messages on candidate profile pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4014]
**What we're after:**
Improve the language explaining that a PCC has converted to a PAC and re-establish the link between the candidate and the money previously raised while as a candidate. 

**Related issues:**
- https://github.com/fecgov/fec-cms/issues/4000 Consider language changes needed for Deval for All

**Completion criteria:**
- [ ] Language for all manually added candidates is updated

**Language:**

Candidate profile page, where the committee name did not change: (Only Deval at this point)
[ELECTION CYCLE INFORMATION] financial data for [CANDIDATE NAME] appears under the committee name [COMMITTEE NAME]. The principal campaign committee (glossary link) for this candidate was converted to a PAC (glossary link).

Candidate profile page, where the committee name changed: (addition of third sentence) (All other candidates that were manually added to the list) 
[ELECTION CYCLE INFORMATION] financial data for [CANDIDATE NAME] appears under the committee name [COMMITTEE NAME]. The principal campaign committee (glossary link) for this candidate was converted to a PAC (glossary link). The previous name for the principal campaign committee was [NEW COMMITTEE NAME].

There is no change to the message on committee profile pages.

**Comment by patphongs** [comment]
@JonellaCulmer I'm not sure how we would detect if a committee name did not change. Is that something we're thinking about programming into the API? If not, this may be difficult to maintain. Would we be able to make a generic enough text so that we don't have to worry about 2 different conditions?

**Comment by lbeaufort** [comment]
https://github.com/fecgov/fec-cms/issues/4000#issuecomment-682839659

> The SQL in development is going to provide `first_cmte_nm` and `latest_cmte_nm`. 

Where `first_cmte_nm` == `latest_cmte_nm`, provide the alternate text.

**Comment by patphongs** [comment]
Implemented these changes within this PR: https://github.com/fecgov/fec-cms/issues/4193

**Comment by patphongs** [comment]
PR #4193 has been merged with these language updates. Closing this issue as complete.
