### ISSUE TITLE
[Snyk: High] Directory Traversal (Due 10/02/2020)

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4015]
Directory Traversal
[https://app.snyk.io/vuln/SNYK-PYTHON-FLASKCORS-608972](https://app.snyk.io/vuln/SNYK-PYTHON-FLASKCORS-608972)

Remediation:
Upgrade Flask-Cors to version 3.0.9 or higher.

**Comment by lbeaufort** [comment]
Issue moved to [fecgov/openFEC #4611](https://github.com/fecgov/openFEC/issues/4611) via [**ZenHub**](https://www.zenhub.com/)

**Comment by lbeaufort** [comment]
Moved to https://github.com/fecgov/openFEC/issues/4611
