### ISSUE TITLE
Update campaign finance statistics hard-coded pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4017]
**What we're after:**
There are some hard-code features/pages that need to change to support the migration of the "campaign finance statistics" from transition to wagtail. 

These are the hard-codes changes that are needed:
- Update Campaign finance data menu link from "Historical statistics" to "Campaign finance statistics"
- Update "Historical statistics" browse data page to "Campaign finance statistics"
  - Update header to say "Campaign finance statistics"
  - Update body text to say "Data tables that summarize financial activity by election cycle and coverage period for congressional candidates, political parties, political action committees and communication filings (independent expenditures, electioneering communications and communication costs).
  - Update left-nav to say "Campaign finance statistics"

**Completion criteria:**
- [ ] Page/menu changes are made and show only "Campaign finance statistics"

### Designs

**Main nav:**
![Campaign stats_1](https://user-images.githubusercontent.com/31663028/89459099-252af700-d736-11ea-838c-ceee4dc92245.png)
**Campaign finance statistics browse data page:**
![Campaign stats_2](https://user-images.githubusercontent.com/31663028/89459100-25c38d80-d736-11ea-8d01-96ed6b74ab89.png)

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Does this require a redirect? We should probably change the link from historical to statistics or something similar, yes? Do we need to also change the file names?

**Comment by johnnyporkchops** [comment]
@JonellaCulmer, we should put in a redirect from `?tab=historical` to `?tab=statistics` once we make the change
