### ISSUE TITLE
Implement filterable table for archived campaign finance statistics

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4020]
**What we're after:**
Create an archived campaign finance statistics page with filterable table to search older archived summaries. 

### Related issues
- https://github.com/fecgov/fec-cms/issues/3816 Design Election Cycle Summary pages
- https://github.com/fecgov/fec-cms/issues/3943 Implement filterable campaign finance data summaries
- https://github.com/fecgov/fec-cms/issues/3958 Migrate data summary landing page on transition to wagtail

### Completion criteria
- [ ] Create filterable archived summary page/table. Archived page links to current summary pages (there are 5).

### Design
![Campaign stats_5](https://user-images.githubusercontent.com/31663028/89459108-25c38d80-d736-11ea-8a8f-42846d18a536.png)

**Comment by patphongs** [comment]
Moving this to 13.6 while @johnnyporkchops works on the current campaign finance statistics filterable pages.

**Comment by patphongs** [comment]
I forgot that @johnnyporkchops might finish the current CF statistics filterable tables this sprint, so I've moved it back to 13.5.

**Comment by patphongs** [comment]
The intermediary plan is to leave archive statistical summary pages on transition and link to it there. We will remove the "current" statistical summary information from this page when that feature goes live: https://transition.fec.gov/press/campaign_finance_statistics.shtml. @JonellaCulmer Will make a ticket for this and we'll prioritize that one first before we tackle this one at a later date.

**Comment by kathycarothers** [comment]
@JonellaCulmer @johnnyporkchops The "Archived Campaign Finance Statistics" section is tied to ticket #4020. In the meantime, we talked about using this page https://transition.fec.gov/press/campaign_finance_statistics.shtml as a place holder and removing content that is after 1989 until the page is drafted.
