### ISSUE TITLE
Website banner active and inactive times

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4022]
### Summary

When setting the active date ahead of the inactive date, the banner disappears from the homepage. It was expected that the banner would deactivate on the inactive date and reactivate on the active date.

![Screen Shot 2020-09-08 at 9 59 30 AM](https://user-images.githubusercontent.com/12799132/92486378-03e87b00-f1ba-11ea-84b2-209df469d775.png)

How should we set reactivation of banners when one banner needs to go down and then reactivate again at a later time.

**Comment by johnnyporkchops** [comment]
@patphongs. The active/inactive  dates are meant to be a span of time and are dependent on each other. The active checkbox is a way to turn active on/off during a span. To allow that to happen automatically based on user settings, that might involve more fields/checkboxes as well as logic.

**Comment by patphongs** [comment]
Thank you @johnnyporkchops! It would be nice to reactive a banner automatically so that we wouldn't need to schedule it again. Especially on days like weekends/days off. Not something that happens often, so we have time to think about this a little more.

**Comment by dorothyyeager** [comment]
Closing - see #4300 for workaround.
