### ISSUE TITLE
Migrate Enforcement Process Statistics Profile page off of transition

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4023]
### Summary

**What we're after:**
_We need to migrate pages on transition into fec.gov. That includes the enforcement process statistics page and related files at https://transition.fec.gov/em/enfpro/EnforcementProfile.shtml._

### Action items
- [x] Upload accessible PDFs linked on that page into the CMS.
- [x] Create draft page in Wagtail
- [x] Second pair of eyes
- [x] Publish new page
- [x] Update related links in CMS (e.g., https://www.fec.gov/legal-resources/enforcement/ and hearing page at https://www.fec.gov/updates/january-14-15-2009-public-hearing-agency-procedures/)
- [x] Add files to redirect list

### Completion criteria

- [x] Enforcement process page is migrated to CMS and linked on https://www.fec.gov/legal-resources/enforcement/
- [x] Related PDFs are uploaded to CMS
- [x] Files added to redirect list

### Future work

- Old files redirected
- Once redirected, old files removed from transition

**Comment by dorothyyeager** [comment]
@djgarr and I will pair on Monday to close out this ticket. Press requested one small change. We'll make it, publish the page, update links and put in a redirect ticket.

**Comment by johnnyporkchops** [comment]
@dorothyyeager and @djgarr Are you planning on migrating this page https://transition.fec.gov/press/bkgnd/EnforcementStatistics.shtml as part of this ticket? (It is the first link on https://transition.fec.gov/em/enfpro/EnforcementProfile.shtml )

**Comment by djgarr** [comment]
Page published and redirects submitted. Redirects ticket is https://github.com/fecgov/fec-cms/issues/4073

@johnnyporkchops yes, that is the plan overall. It'll be saved for a future ticket.
