### ISSUE TITLE
Update bad links to the FCC's electioneering communications database

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4025]
### Summary

**What we are after:**
_The link we are providing to the FCC's electioneering communications database is 404'ing. We need to find the new URL and update our pages. @djgarr is reaching out to the FCC since a search of their website found their links 404'ing as well._

Link we have been using is https://apps.fcc.gov/ecd/

### Completion criteria
When we have the new link:
- [ ] Page at https://www.fec.gov/data/browse-data/?tab=external (hard coded page) is updated with the new link
- [ ] Page at https://www.fec.gov/help-candidates-and-committees/other-filers/making-electioneering-communications/ is updated with the new link (see screencap of the button we use)

![image](https://user-images.githubusercontent.com/24437369/92608145-fd720600-f282-11ea-9164-81341c487301.png)

* Note: new link should be sent to Information Division staff so they can update InfoWeb links.

**Comment by djgarr** [comment]
sent an email to the FCC on 9/9/2020. Have not heard back. Will follow up this week

**Comment by djgarr** [comment]
Heard back from the FCC. They were unaware of an issue with the link. It works internally for them, but when they tried to access the page from an external browser, it wasn't working properly. They were getting the same error message we're getting. They will work on it on their end and get back to me once they have more information.

**Comment by djgarr** [comment]
still waiting on the FCC. Checked the links and they are still broken

**Comment by jason-upchurch** [comment]
@djgarr I moved this to innovation sprint in preparation for the next iteration. Please let me know if I need to reprioritize it--thank you!

**Comment by djgarr** [comment]
still waiting on the FCC. Checked the links and they are still broken

**Comment by djgarr** [comment]
Link is still broken. Still waiting to hear back from FCC

**Comment by djgarr** [comment]
Link's still broken

**Comment by djgarr** [comment]
Haven't heard back from FCC. Moved the ticket to the icebox

**Comment by djgarr** [comment]
The link is working again at the same address. Closing ticket
