### ISSUE TITLE
Migration of Policy Page, Step Two: Uploading Accessible PDFs

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4029]
### Summary

**What we are after:**
_The Policy page links a lot of PDFs. We need to upload the ones that are only on transition into the CMS. Right now they are ready to go in a folder shared by InfoDiv and content team._

### Related issues

#3220 - Initial conversation with OGC and decision-making
#3213 (need to find good home for DSP/Admin Term page)
#3954, #3955, #3956 (Migration of related policy comment pages that will be linked on this one)
#4028 - Drafting ticket for policy page.

### Completion criteria

- [x] PDFs are uploaded WITH THE SAME NAME. DO NOT CHANGE THE PDF NAME (helps redirect process) Note 5 documents had to have their names changed. They are noted in the excel file. 
- [x] PDFs are added to the redirect list. We'll hold off on redirects until the end, so that we can make them as broad as possible.

### Future work

Creation of the Wagtail page in #4030

**Comment by kathycarothers** [comment]
@dorothyyeager this is the folder the pdfs are located in, correct:
\\ntsrv1\InfoProj\Policy Page Update\Policy Page PDFs

**Comment by kathycarothers** [comment]
I am now up to Naming of Treasurers in Enforcement Matters.

**Comment by kathycarothers** [comment]
The pdfs have been uploaded into the CMS system. Note for 4 documents their names did have to be changed because of conflicts in CMS. These documents have an asterisk next to their name in the excel document.
