### ISSUE TITLE
Step Three - Migration of Policy Page to Wagtail: Creation and publication of Wagtail page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4030]
### Summary

**What we are after:**
_We are migrating the Policy page to fec.gov_

### Related issues

#3220 - Initial conversation with OGC and decision-making
#3213 (need to find good home for DSP/Admin Term page)
#3954, #3955, #3956 (Migration of related policy comment pages that will be linked on this one)
#4028 - Drafting ticket
#4029 - PDF work

Action Items

- [x]  Create the page as child page of legal resources, with a resource page template
- [x]  Second pair of eyes before publishing
- [x]  Publish the page
- [x]  Remove redirect that was put in place in 10.4 for the breadcrumb link to Policy and Other Guidance.
- [x]  Update the links on enforcement pages (some may be hard coded; we'll handle that in #4115 )
- [x] Add page and any PDFs uploaded to redirect spreadsheet
- [x] Redirect PR created
- [x] After @patphongs merges and deploys redirect, test if working
- [x] Ticket to update menus put in

### Completion criteria

- [x] Policy page is migrated into Wagtail and published
- [x] Redirect put in and working
- [x] Ticket to update menus put in

### Future work

Redirects and taking down transition

**Comment by dorothyyeager** [comment]
Working on creating the page. Realized we may need to draft some intro text that's not on the page currently, just to make the template work and also for SEO reasons.

@AmyKort @kathycarothers - does this work for intro text? Cribbed a little from guidance search page.

> This page includes Commission initiatives that set forth a policy on a statutory, regulatory or technical issue, or interpret a regulation, including Statements of Policy, interpretive rules, certain press releases and other various Commission publications.
> 
> Policy initiatives that are underway and available for public comment are noted.
> 
> Search all guidance documents (linked)
> 
> Sign-up to receive email updates regarding FEC policy developments. (link gov delivery)

**Comment by AmyKort** [comment]
Let's ask for some help with this. Is this for the explainer text under the page title? Looking at other similar text, I think we might want to start with something more like "The Commission adopts policies and issues interpretive rules to . . . "

**Comment by dorothyyeager** [comment]
Sounds good @AmyKort - I'll work up something and ask for input in content channel.

**Comment by dorothyyeager** [comment]
I've laid out the page and consulted with @JonellaCulmer @AmyKort and OGC about the intro language and some simple tweaks to make the new format easier for users. Will get a final draft ready to send to OGC and content team for final review.

**Comment by dorothyyeager** [comment]
The draft final page has been sent to the content team and OGC Policy for a final review and second pair of eyes.

**Comment by dorothyyeager** [comment]
An update from OGC: They were in training last week and expect to return comments this week.

**Comment by dorothyyeager** [comment]
OGC returned comments and had some suggestions. Will work on implementing them.

**Comment by dorothyyeager** [comment]
Having the content team and @JonellaCulmer look the page over one more time before we resend to OGC. We made a few style choices that departed from their comments but will make the page fit better with fec.gov style. They caught some consistency issues and made some suggestions that definitely will improve the page, so those are now in the draft.

**Comment by dorothyyeager** [comment]
Content team and Jonella have signed off. Will resend today to OGC for their approval.

**Comment by dorothyyeager** [comment]
The page is now live at https://www.fec.gov/legal-resources/policy-other-guidance/

The redirect to be removed was referenced in an older ticket at https://github.com/fecgov/fec-cms/issues/3213#issuecomment-545998927 - it was to update the redirect for the breadcrumb on the Debt settlement/Admin term page. I didn't see the redirect in our Wagtail redirects and the breadcrumb on the DS/AT page is going to the new policy page. I think we're good on this item.

On to updating links and redirects.

**Comment by dorothyyeager** [comment]
I've updated the links in various fec.gov pages that weren't hard-coded.

I've put in a redirect for the transition page in this PR: https://github.com/fecgov/fec-proxy/pull/189 - it's ready for review.

**Comment by dorothyyeager** [comment]
The redirect is in place and working. The migration of the Policy page is completed.

New page is at https://www.fec.gov/legal-resources/policy-other-guidance/.
