### ISSUE TITLE
Candidate profile page: 404 when navigating directly to 2-year transaction period if fec_cycles_in_election null

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4040]
### Summary 

_Navigating to the 2-year transaction period directly on a candidate profile page without fec_cycles_in_election will result in a 404._

### How to Reproduce

1. Go to this URL and it will 404: https://www.fec.gov/data/candidate/S6FL00335/?cycle=2014&election_full=false 

_What should have happened?_

The user should not get a 404 when doing this. Consider a redirect to the main All years slice when this happens. Example https://www.fec.gov/data/candidate/S6FL00335/?cycle=2014&election_full=false redirects to https://www.fec.gov/data/candidate/S6FL00335/. By default, the main candidate URL without query params is election_full=true and cycle=[max_cycle]

### Screenshots

![Screen Shot 2020-09-14 at 10 37 33 AM](https://user-images.githubusercontent.com/12799132/93099863-8370c100-f676-11ea-8641-824484529ca9.png)

#### Related PR
https://github.com/fecgov/fec-cms/pull/4034

**Comment by JonellaCulmer** [comment]
De-prioritizing this issue for now. Not easy to get to that broken page. Navigating through normal methods throughout the site gets the user to the right place.
