### ISSUE TITLE
[October] - Manually update wagtail global search index

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4046]
### Summary
**What we're after:**
We need to update the global search.gov index for new pages that were published in October.

Related issues
#3964   

**Completion criteria**

- [x] Follow instructions under [Adding CMS pages to the index](https://github.com/fecgov/fec-cms/blob/develop/fec/search/management/instructions.md#adding-cms-pages-to-the-index)
  - [x] Update your CMS database
  - [x] Scrape the pages: Run fec/manage.py scrape_cms_page
  - [x] Push the indexes to i14y Run fec/manage.py index_pages
  - [x] Once index_pages has run, you can log in to search.gov and see the new pages under "Content" > "i14Y Drawers" > click "show" for the Main drawer.
- [x]  Create ticket for November manual wagtail global search index

**Comment by jason-upchurch** [comment]
Last indexed page count: 897 (indexed on 09/17/2020)
New indexed page count: 906 (indexed on 10/22/2020)

Created new ticket to scrape and index the pages for October #4140
