### ISSUE TITLE
New Reporting Example: Payroll deductions

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#4047]
### Summary
After calling the Reports Analysis Division several times about the same reporting question, a user suggested we add a reporting example for payroll deduction receipts, a very common form of fundraising for SSFs and certain types of non-connected PACs.

Examples/language to use as a staring point for drafting this page are available in the Corporate Guide and in the workshop materials.

### Completion Criteria
- [x] Distribute drafting assignment to an interested RAD analyst
- [x] RAD manager review
- [x] Content team review
- [x] Add links to the Filing SSF Reports page

### Current Situation
Currently we do not have a reporting example for payroll deductions. Payroll deduction guidance is available here:

- SSF guide > Fundraising for an SSF > [Payroll deductions](https://www.fec.gov/help-candidates-and-committees/fundraising-for-ssf/payroll-deduction-ssf/)
- SSF guide >Keeping SSF Records > [Recording Fundraising for an SSF](https://www.fec.gov/help-candidates-and-committees/keeping-ssf-records/recording-fundraising-ssf/)
- Nonconnected guide > Making Disbursements as a PAC > [Fundraising for the PAC](https://www.fec.gov/help-candidates-and-committees/making-disbursements-pac/fundraising-nonconnected-pac/) 
(this page has some reporting example information that we can probably replace with a reporting example card if we write the example with a disclaimer about the types of non-connected PACs that can do payroll deductions.

**Comment by bmathesonFEC** [comment]
Received a draft for the page from RAD analyst, received image from @jjonesfec, created page in wagtail. Distributing to RAD managers and Content team for review.

**Comment by bmathesonFEC** [comment]
Received feedback from Content team and RAD manager. Will publish once edits are incorporated into wagtail.

**Comment by bmathesonFEC** [comment]
RAD manager wanted final approval before publication. Awaiting approval.

**Comment by jason-upchurch** [comment]
@bmathesonFEC I moved this to blocked 13.8 from 13.7. Please let me know if it should be moved elsewhere.

**Comment by bmathesonFEC** [comment]
Unblocked after receiving feedback. Changes made, ready to publish with #3923 (waiting on an image request from Jim to complete that ticket).

**Comment by bmathesonFEC** [comment]
Blocked by #4218. Moving new PAC/Party bitcoin examples.

**Comment by bmathesonFEC** [comment]
New page published: https://www.fec.gov/help-candidates-and-committees/filing-ssf-reports/payroll-deductions/

Added example to the [Filing SSF Reports page](https://www.fec.gov/help-candidates-and-committees/filing-ssf-reports/). Added example link to [All Reporting Examples](https://www.fec.gov/help-candidates-and-committees/reporting-examples/).
