### ISSUE TITLE
Move statistical data summaries from transition S3 to production S3

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#4052]
### Summary
As followup to **Implement filterable campaign finance data summaries** (issue #3943 PR #4088**) we need to move  the  `.PDF` and `.XLS(X)` files to which the new tables link, to the production S3 bucket and maintain the current path after the domain. 

### Action items
- [x] Copy statistical data summary `.PDF` and `.XLS(X)` files from transition S3 bucket to production content S3 bucket as the followup to #4088
- [x] Make relevant changes to the paths currently in tables in the Wagtail pages for Congressional. PAC, Party Committee, and Communication Filings
- [x] export names of paths to maintain SEO and ensure we are not abandoning links
- [x] decide on what paths to use
~[ ]update paths (regex) in `statistical-summary.js` after files are added to content s3 bucket~ Not needed
- [x] Create redirect for old statistical summary files to new bucket

This is the separate issue for deleting files: https://github.com/fecgov/fec-cms/issues/4208
- Make sure everything transferred OK before deleting. 
  - Delete files from transition S3. Confirm this with team.

Since it is priority to take down transition web pages (and not as much, transition bucket), we  left these files on transition give us a sooner delivery date for the new web pages, adding the work in this ticket as a followup.

***Note:** #4088 is only for current summary data tables, there is another issue with #4020 for moving the archived tables, but it makes sense to move all files at once so when archived tables are moved to Wagtail, they will be ready. 

Related issue: https://github.com/fecgov/fec-cms/issues/3943
Related PR: https://github.com/fecgov/fec-cms/pull/4088

### Completion criteria
- [x] data summary files are copied from the transition s3 to the content s3

**Comment by patphongs** [comment]
Redirect PR is in and ready for review by @johnnyporkchops: https://github.com/fecgov/fec-proxy/pull/206

**Comment by patphongs** [comment]
Changes made to URLs for PDF and Excel files:

https://www.fec.gov/campaign-finance-data/congressional-candidate-data-summary-tables/
https://www.fec.gov/campaign-finance-data/presidential-candidate-data-summary-tables/
https://www.fec.gov/campaign-finance-data/political-party-data-summary-tables/
https://www.fec.gov/campaign-finance-data/political-action-committee-data-summary-tables/
https://www.fec.gov/campaign-finance-data/communication-filings-data-summary-tables/

**Comment by patphongs** [comment]
Redirects have been merged and will deployed on 12/8.
