### ISSUE TITLE
Research/create functioning prototype to scrape transition pages and importing into Wagtail

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4063]
### Summary

**What we're after:**
_We need to revisit old code to scrape the transition pages and import them into Wagtail._

### Related code / Tech considerations

This is our scraper that we have for transition pages, in which it will grab the HTML and put it into JSON format: https://github.com/fecgov/fec-cms/blob/develop/fec/search/management/commands/scrape_transition_pages.py. Then there’s an old PR on importing scraped records into Wagtail: https://github.com/fecgov/fec-cms/pull/666.

**Action items:**
- [x] Review old code
- [x] Pair with content team and information division staff to better understand the court cases as an example
- [ ] Compare page templates to understand the best place to migrate content - pair with design and content

### Completion criteria
- [x] Create a functioning prototype for successfully scraping and importing data into Wagtail locally

### Future work

Connect this scraping functionality with content we've prioritized to scrape from transition.

**Comment by johnnyporkchops** [comment]
Here is a google doc showing a working  prototype for scraping and migration of court case using `Node JS` and` \psql`.  We don't necessarily have to use these scripts and processes but there is a lot of required, "esoteric" metadata fields that took a substantial amount of time to figure out. Hopefully documenting these details, by example, will free up more time for the team either refine this solution and/or try other approaches. 
https://docs.google.com/document/d/19_m8P2wuGBklxSfUjLYCKaLdI4sexQqfze-ybWAncI4/edit

**Comment by jason-upchurch** [comment]
@johnnyporkchops I moved this to innovation sprint in preparation for the next iteration. Please let me know if I need to reprioritize it--thank you!

**Comment by patphongs** [comment]
Closing this in favor of: https://github.com/fecgov/fec-cms/issues/4118 and https://github.com/fecgov/fec-cms/issues/4120
