### ISSUE TITLE
Make plans to migrate remaining pages in press/ from transition site to fec.gov / Wagtail

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4067]
### Summary

**What we are after:**
Since Press is getting Windows 10 laptops soon, they won't be able to use Contribute to update their pages on transition. We need to prioritize migrating these pages to fec.gov.

### Related issues

- Statistical page work - see #4052 
- Pages found while working on #4023 

### Completion criteria

- [x] Meeting held with Press Office, front end, Jonella, and content team to determine migration plan for 
Press page files in the press/ directory and subdirectories, including:
ECF Tax Chart out of the transition site: https://transition.fec.gov/press/bkgnd/presidential_fund.shtml - We will replace this page with a pdf from Press and will need to redirect to pdf and update related pages with the new link. The pdfs will need to go through Chris for accessibility.  - Ticket at https://github.com/fecgov/fec-cms/issues/4078 
https://transition.fec.gov/press/bkgnd/AllPublicFunds.xls - Will upload the doc into Wagtail. New URL that will need redirects. 
https://transition.fec.gov/press/bkgnd/history.shtml - Needs a new ticket for the elastic search of case penalities. 
https://transition.fec.gov/press/bkgnd/EnforcementStatistics.shtml - Pdf is there. Will update related pages with the link to the new pdf and put in a redirect for the transition site.  Related pages https://www.fec.gov/legal-resources/enforcement/enforcement-profile/
- [x] Tickets put in for future work

Considerations for Press/website team
- PDF files in the press/ directory and subdirectories are migrated to the CMS (with the same file names) or S3 bucket and links updated in the new pages (or redirects put in) 
-Press can continue to update these pages using Wagtail

### Tech steps or considerations (optional)

Many Press PDF files were moved to S3 bucket already. Not sure if all of them were. There are some PDF files in the press/ folder.

### Future work

Will need to ensure links are working. Use a link checker.

**Comment by kathycarothers** [comment]
Working to coordinate a meeting for either this week or next week.

**Comment by kathycarothers** [comment]
The meeting has been scheduled for this upcoming Wednesday.

**Comment by kathycarothers** [comment]
Meets was successful
