### ISSUE TITLE
Move court case PDFs to the S3 bucket

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4070]
### Summary

**What we're after:**
_We need to get off transition and there are a ton of PDF files associated with court cases. We're going to move them in one fell swoop to the S3 bucket._

### Related issues

- #3938 - Court Case alpha pages (the "letter" pages - cases beginning with A, with B, etc.)
- #3937 - Ongoing and selected case pages (the current cases and the most important cases have their own pages)
- #4118 - Scraping ticket
- #4120 - Scraping ticket

### Completion criteria

- [x] PDF files in the /law/litigation/ and subdirectory are migrated to the S3 bucket (with the same file names) 
- [x] Redirects are put in place and tested (we may want to enlist Information Division help with the testing)

### Future work

- We should update the links to these files in the ongoing and selected litigation pages rather than rely on redirects. Those particular pages are the ones most used.

**Comment by patphongs** [comment]
A copy of the PDF files underneath `/law/litigation` have been added tot he content s3 bucket under `/resources/legal-resources/litigation/`

**Comment by dorothyyeager** [comment]
Thanks @patphongs will we need to update links or put in redirects? cc: @kathycarothers @djgarr (Can't find Zainab's handle)

**Comment by patphongs** [comment]
Redirects have been merged for this and will be deployed tomorrow (11/24). https://github.com/fecgov/fec-proxy/pull/203/
