### ISSUE TITLE
Move the Audit-report related PDFs to the S3 bucket

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4071]
### Summary

**What we're after:**
_We need to get off transition and there are a ton of PDF files associated with audit reports. We're going to move them in one fell swoop to the S3 bucket._

### Related issues

#4064 - Migration of Audit report landing pages and audit report pages

### Completion criteria

- [x] PDF files in the audits/ directory and subdirectories are migrated to the content s3 bucket, preserving the structure and filenames
~[ ] Redirects are put in place and tested (we may want to enlist Audit or Public Records' help with the testing)~ (There's a ticket to do the PDF files in a later sprint once we can get more eyes on the audit updates https://github.com/fecgov/fec-proxy/issues/219)

**Comment by patphongs** [comment]
PDF files from the transition `/audits/` directory have been copied to their new home in the content-s3 bucket under `/resources/legal-resources/enforcement/audits`
