### ISSUE TITLE
Redirects for 13.5 migrations

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4073]
### Summary

**What we are after:**
_We migrated some pages and inventoried some others in 13.5. This ticket is to do the redirects._

### Related issues

#4023 - enforcement statistics
#3884 - inventory

### Completion criteria

- [x] Items on redirect list are redirected in proxy/transition
- [x] After @patphongs merges and deploys, redirects are tested
- [ ] Take down ticket is put in for future sprint

**Comment by djgarr** [comment]
Redirects went in overnight and were tested this morning

**Comment by djgarr** [comment]
Will hold off making ticket to take the page down until more policy pages are ready to be taken down
