### ISSUE TITLE
Individual contributions section on election profile pages not working

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#4096]
Individual contributions section on election profile pages not working

https://www.fec.gov/data/elections/president/2020/#individual-contributions

<img width="645" alt="Screen Shot 2020-10-04 at 9 31 45 PM" src="https://user-images.githubusercontent.com/31420082/95032563-0939c800-0689-11eb-9963-8effcf8969a2.png">

**Technical considerations**
- Looks like no AJAX call is happening
- No obvious recent changes to the code
- Here's a PR that touched this code: https://github.com/fecgov/fec-cms/pull/2545
- Individual contributions by size/state on candidate/committee profile pages seem to work (examples: https://www.fec.gov/data/candidate/P80000722/?cycle=2020&election_full=true&tab=raising and https://www.fec.gov/data/committee/C00703975/?cycle=2020&tab=raising)

**Comment by dzhang-fec** [comment]
@lbeaufort  good morning. @rjayasekera mentioned this ticket to us. It sounds a cms issue.

Just FYI, browser is also an related to the AJAX?
From chrome, "not stable", 2000,2008 1996 works  sometimes  sometimes not.  . it also up to the browser. 
for example, 
works.
![image](https://user-images.githubusercontent.com/62447258/95085365-20120600-06ed-11eb-88d8-5cd044c2ceab.png)
not owrk
![image](https://user-images.githubusercontent.com/62447258/95085470-45067900-06ed-11eb-8e6b-0ad4fc7c9401.png)


**However, For firefox. 2020, 2016 2012... etc  works** 



![image](https://user-images.githubusercontent.com/62447258/95084181-84cc6100-06eb-11eb-9f49-8a7da05c013a.png)
![image](https://user-images.githubusercontent.com/62447258/95084504-fb695e80-06eb-11eb-84e9-5aca963ab150.png)

**Comment by lbeaufort** [comment]
PR #4112 merged to release branch
