### ISSUE TITLE
Investigate why transition PDF redirects for the Record aren't working and fix

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4101]
### Summary

**What we are after:**
_Redirects for transition files in /pdf/record/year/ to /resources/record/year/ aren't working. We need to fix that.

### Completion criteria

- [ ] Old Records on transition redirect to new file in S3 bucket or Wagtail.

**Comment by patphongs** [comment]
@dorothyyeager do you have any specific examples. I'm seeing this still working on at least this type of URL for old records:

https://www.fec.gov/pdf/record/2016/sept2016.pdf --> https://www.fec.gov/resources/record/2016/sept2016.pdf

**Comment by dorothyyeager** [comment]
@patphongs Yes - at the bottom of many of the court case summaries, there are links to older Record articles on the transition site. An example can be found at https://transition.fec.gov/law/litigation_CCA_D.shtml#davis at the bottom of the case in the line labeled "Source". The links to those articles end up on transition site and don't redirect.

**Comment by patphongs** [comment]
Looks like we don't have a generic redirect on transition for the old record article pages. We'll need this redirect rule for the transition redirects:

`rewrite ^/pdf/record/(.*).pdf /resources/record/$1.pdf redirect;`

**Comment by dorothyyeager** [comment]
Thanks @patphongs - We'll add that redirect as part of #4124 in 13.7 and close this ticket; but if you think we should do it right away, let me know and I'll put in a PR (have assigned myself to this ticket if we need to do that; thank you for looking into the issue and giving us the code).

**Comment by patphongs** [comment]
@dorothyyeager 13.7 works since we have the old record articles on both the content-s3 bucket and the transition s3 bucket at the moment. We can clean them from the transition bucket whenever the redirects are in place.

**Comment by dorothyyeager** [comment]
Awesome! Closing this ticket since research is done and we know we need to put in a redirect. We'll do that in #4124.
