### ISSUE TITLE
Take down policy and other recent redirected files off of transition 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#4107]
### Summary

**What we're after:**
We are getting off of transition

### Related issues

_List any relevant related issue(s)_

- #4080 

### Completion criteria

- [ ] These pages are removed:

/em/enfpro/EnforcementProfile.shtml

/hava/law_ext.txt

/law/cfr/ej_compilation/2009/notice_2009-28.pdf
/law/cfr/ej_compilation/2009/notice_2009-24.pdf
/law/cfr/ej_compilation/2009/notice_2009-18.pdf
/law/cfr/ej_compilation/2007/notice_2007-6.pdf
/law/cfr/ej_compilation/2009/notice_2009-12.pdf
/law/cfr/ej_compilation/2009/notice_2009-19.pdf
/law/cfr/ej_compilation/2008/notice_2008-01.pdf
/law/cfr/ej_compilation/2007/notice_2007-21.pdf
/law/cfr/ej_compilation/2007/notice_2007-4.pdf

/law/litigationmajor.shtml
/law/litigationrecent.shtml

/law/policy.shtml 

/law/policy/ao200615/crewcomment_09142016.pdf
/law/policy/ao200615/publiccitizencomment_09142016.pdf
/law/policy/ao200615/comments_centerforcompetitivepolitics_09122016.pdf
/law/policy/ao200615/comment_Torres-Spelliscy_09092016.pdf
/law/policy/ao200615/comments_CommissionerRavel_97-82016.pdf
/law/policy/ao200615/comment_harper_09062016.pdf
/law/policy/ao200615/comments_publiccomment_fecgov_828_8302016.pdf
/law/policy/ao200615/comments_commRavel_fecgov826_8292016.pdf
/law/policy/ao200615/commentsrecd_comm_Ravel_08252016.pdf
/law/policy/ao200615/bradycomment_08152016.pdf

/law/policy/nationwideiereporting/comments/josefiaktorchinskycairncrossbayes-nationwideiecomments.pdf
/law/policy/nationwideiereporting/comments/lenhardlawler-nationwideiecomments.pdf
/law/policy/nationwideiereporting/draftnationwideiereporting.pdf

/law/policy/volunteer/comm01.pdf
/law/policy/volunteer/comm04.pdf
/law/policy/volunteer/comm03.pdf
/law/policy/volunteer/comm02.pdf
/law/policy/volunteer/volunteermaterialscover.pdf
/law/policy/volunteer/volunteermaterialsdrafta.pdf
/law/policy/volunteer/volunteermaterialsdraftb.pdf
/law/policy/volunteer/volunteermaterialsdraftc.pdf
/law/policy/volunteer/volunteermaterialsdraftd.pdf

/law/policy/bestefforts/notice_2006-21.pdf
/law/policy/bestefforts/mhimes.pdf
/law/policy/bestefforts/oleary.pdf

/law/policy/suasponte/notice_2006-20.pdf
/law/policy/suasponte/comm2.pdf
/law/policy/suasponte/comm1.pdf

/law/policy/disbursement_purpose.pdf

/law/policy/purposeofdisbursement/comment_cfi.pdf
/law/policy/purposeofdisbursement/comment_crp.pdf

/law/policy/2004/notice2004-20.pdf

/law/policy/iedisseminationdate/seiucomment.pdf
/law/policy/iedisseminationdate/pomeranzcomment.pdf

/law/policy/enforcement_disclosure/perkins_coie.pdf
/law/policy/enforcement_disclosure/doj.pdf

/law/policy/enforcement/2009/witnesses.pdf

/law/policy/probablecause/notice_2006-19.pdf
/law/policy/probablecause/comm02.pdf
/law/policy/probablecause/comm01.pdf
/law/policy/probablecause/comm03.pdf
/law/policy/probablecause/comm04.pdf

/law/policy/formsrevisions2016/oconnor-formscomment.pdf

/law/ultimatepayee/keithdavis030413.pdf
/law/ultimatepayee/rutkowski030413.pdf
/law/ultimatepayee/rutkowski030413.pdf
/law/ultimatepayee/dem21clc030413.pdf

/press/campaign_finance_statistics.shtml

/press/summaries/help/statistical_1975_2010.shtml
/press/summaries/help/statistical_post2010.shtml

/press/summaries/2020/ElectionCycle/18m_CongCand.shtml
/press/summaries/2020/ElectionCycle/15m_CongCand.shtml
/press/summaries/2020/ElectionCycle/12m_CongCand.shtml
/press/summaries/2020/ElectionCycle/6m_CongCand.shtml

/press/summaries/2020/ElectionCycle/18m_IE_EC.shtml
/press/summaries/2020/ElectionCycle/15m_IE_EC.shtml
/press/summaries/2020/ElectionCycle/12m_IE_EC.shtml
/press/summaries/2020/ElectionCycle/6m_IE_EC.shtml

/press/summaries/2020/ElectionCycle/18m_NatlParty.shtml
/press/summaries/2020/ElectionCycle/15m_NatlParty.shtml
/press/summaries/2020/ElectionCycle/12m_NatlParty.shtml
/press/summaries/2020/ElectionCycle/6m_NatlParty.shtml

/press/summaries/2020/ElectionCycle/18m_PAC.shtml
/press/summaries/2020/ElectionCycle/15m_PAC.shtml
/press/summaries/2020/ElectionCycle/12m_PAC.shtml
/press/summaries/2020/ElectionCycle/6m_PAC.shtml

/press/summaries/2020/ElectionCycle/18m_PresCand.shtml
/press/summaries/2020/ElectionCycle/15m_PresCand.shtml
/press/summaries/2020/ElectionCycle/12m_PresCand.shtml
/press/summaries/2020/ElectionCycle/6m_PresCand.shtml

/press/summaries/2018/ElectionCycle/24m_CongCand.shtml
/press/summaries/2018/ElectionCycle/21m_CongCand.shtml
/press/summaries/2018/ElectionCycle/18m_CongCand.shtml
/press/summaries/2018/ElectionCycle/15m_CongCand.shtml
/press/summaries/2018/ElectionCycle/12m_CongCand.shtml
/press/summaries/2018/ElectionCycle/6m_CongCand.shtml

/press/summaries/2018/ElectionCycle/24m_IE_EC.shtml
/press/summaries/2018/ElectionCycle/21m_IE_EC.shtml
/press/summaries/2018/ElectionCycle/18m_IE_EC.shtml
/press/summaries/2018/ElectionCycle/15m_IE_EC.shtml
/press/summaries/2018/ElectionCycle/12m_IE_EC.shtml
/press/summaries/2018/ElectionCycle/6m_IE_EC.shtml

/press/summaries/2018/ElectionCycle/24m_NatlParty.shtml
/press/summaries/2018/ElectionCycle/21m_NatlParty.shtml
/press/summaries/2018/ElectionCycle/18m_NatlParty.shtml
/press/summaries/2018/ElectionCycle/15m_NatlParty.shtml
/press/summaries/2018/ElectionCycle/12m_NatlParty.shtml
/press/summaries/2018/ElectionCycle/6m_NatlParty.shtml

/press/summaries/2018/ElectionCycle/24m_PAC.shtml
/press/summaries/2018/ElectionCycle/21m_PAC.shtml
/press/summaries/2018/ElectionCycle/18m_PAC.shtml
/press/summaries/2018/ElectionCycle/15m_PAC.shtml
/press/summaries/2018/ElectionCycle/12m_PAC.shtml
/press/summaries/2018/ElectionCycle/6m_PAC.shtml

/press/summaries/2018/ElectionCycle/24m_PresCand.shtml
/press/summaries/2018/ElectionCycle/21m_PresCand.shtml
/press/summaries/2018/ElectionCycle/18m_PresCand.shtml
/press/summaries/2018/ElectionCycle/15m_PresCand.shtml
/press/summaries/2018/ElectionCycle/12m_PresCand.shtml
/press/summaries/2018/ElectionCycle/6m_PresCand.shtml

/press/summaries/2016/ElectionCycle/24m_CongCand.shtml
/press/summaries/2016/ElectionCycle/21m_CongCand.shtml
/press/summaries/2016/ElectionCycle/18m_CongCand.shtml
/press/summaries/2016/ElectionCycle/15m_CongCand.shtml
/press/summaries/2016/ElectionCycle/12m_CongCand.shtml
/press/summaries/2016/ElectionCycle/6m_CongCand.shtml

/press/summaries/2016/ElectionCycle/24m_IE_EC.shtml
/press/summaries/2016/ElectionCycle/21m_IE_EC.shtml
/press/summaries/2016/ElectionCycle/18m_IE_EC.shtml
/press/summaries/2016/ElectionCycle/15m_IE_EC.shtml
/press/summaries/2016/ElectionCycle/12m_IE_EC.shtml
/press/summaries/2016/ElectionCycle/6m_IE_EC.shtml

/press/summaries/2016/ElectionCycle/24m_NatlParty.shtml
/press/summaries/2016/ElectionCycle/21m_NatlParty.shtml
/press/summaries/2016/ElectionCycle/18m_NatlParty.shtml
/press/summaries/2016/ElectionCycle/15m_NatlParty.shtml
/press/summaries/2016/ElectionCycle/12m_NatlParty.shtml
/press/summaries/2016/ElectionCycle/6m_NatlParty.shtml

/press/summaries/2016/ElectionCycle/24m_PAC.shtml
/press/summaries/2016/ElectionCycle/21m_PAC.shtml
/press/summaries/2016/ElectionCycle/18m_PAC.shtml
/press/summaries/2016/ElectionCycle/15m_PAC.shtml
/press/summaries/2016/ElectionCycle/12m_PAC.shtml
/press/summaries/2016/ElectionCycle/6m_PAC.shtml

/press/summaries/2016/ElectionCycle/24m_PresCand.shtml
/press/summaries/2016/ElectionCycle/21m_PresCand.shtml
/press/summaries/2016/ElectionCycle/18m_PresCand.shtml
/press/summaries/2016/ElectionCycle/15m_PresCand.shtml
/press/summaries/2016/ElectionCycle/12m_PresCand.shtml
/press/summaries/2016/ElectionCycle/6m_PresCand.shtml

/press/summaries/2014/ElectionCycle/24m_CongCand.shtml
/press/summaries/2014/ElectionCycle/21m_CongCand.shtml
/press/summaries/2014/ElectionCycle/18m_CongCand.shtml
/press/summaries/2014/ElectionCycle/15m_CongCand.shtml
/press/summaries/2014/ElectionCycle/12m_CongCand.shtml
/press/summaries/2014/ElectionCycle/6m_CongCand.shtml

/press/summaries/2014/ElectionCycle/24m_IE_EC.shtml
/press/summaries/2014/ElectionCycle/21m_IE_EC.shtml
/press/summaries/2014/ElectionCycle/18m_IE_EC.shtml
/press/summaries/2014/ElectionCycle/15m_IE_EC.shtml
/press/summaries/2014/ElectionCycle/12m_IE_EC.shtml
/press/summaries/2014/ElectionCycle/6m_IE_EC.shtml

/press/summaries/2014/ElectionCycle/24m_NatlParty.shtml
/press/summaries/2014/ElectionCycle/21m_NatlParty.shtml
/press/summaries/2014/ElectionCycle/18m_NatlParty.shtml
/press/summaries/2014/ElectionCycle/15m_NatlParty.shtml
/press/summaries/2014/ElectionCycle/12m_NatlParty.shtml
/press/summaries/2014/ElectionCycle/6m_NatlParty.shtml

/press/summaries/2014/ElectionCycle/24m_PAC.shtml
/press/summaries/2014/ElectionCycle/21m_PAC.shtml
/press/summaries/2014/ElectionCycle/18m_PAC.shtml
/press/summaries/2014/ElectionCycle/15m_PAC.shtml
/press/summaries/2014/ElectionCycle/12m_PAC.shtml
/press/summaries/2014/ElectionCycle/6m_PAC.shtml

/press/summaries/2012/ElectionCycle/24m_CongCand.shtml
/press/summaries/2012/ElectionCycle/21m_CongCand.shtml
/press/summaries/2012/ElectionCycle/18m_CongCand.shtml
/press/summaries/2012/ElectionCycle/15m_CongCand.shtml
/press/summaries/2012/ElectionCycle/12m_CongCand.shtml
/press/summaries/2012/ElectionCycle/6m_CongCand.shtml

/press/summaries/2012/ElectionCycle/24m_IE_EC.shtml
/press/summaries/2012/ElectionCycle/21m_IE_EC.shtml
/press/summaries/2012/ElectionCycle/18m_IE_EC.shtml
/press/summaries/2012/ElectionCycle/15m_IE_EC.shtml
/press/summaries/2012/ElectionCycle/12m_IE_EC.shtml
/press/summaries/2012/ElectionCycle/6m_IE_EC.shtml

/press/summaries/2012/ElectionCycle/24m_NatlParty.shtml
/press/summaries/2012/ElectionCycle/21m_NatlParty.shtml
/press/summaries/2012/ElectionCycle/18m_NatlParty.shtml
/press/summaries/2012/ElectionCycle/15m_NatlParty.shtml
/press/summaries/2012/ElectionCycle/12m_NatlParty.shtml
/press/summaries/2012/ElectionCycle/6m_NatlParty.shtml

/press/summaries/2012/ElectionCycle/24m_PAC.shtml
/press/summaries/2012/ElectionCycle/21m_PAC.shtml
/press/summaries/2012/ElectionCycle/18m_PAC.shtml
/press/summaries/2012/ElectionCycle/15m_PAC.shtml
/press/summaries/2012/ElectionCycle/12m_PAC.shtml
/press/summaries/2012/ElectionCycle/6m_PAC.shtml

/press/summaries/2012/ElectionCycle/24m_PresCand.shtml
/press/summaries/2012/ElectionCycle/21m_PresCand.shtml
/press/summaries/2012/ElectionCycle/18m_PresCand.shtml
/press/summaries/2012/ElectionCycle/15m_PresCand.shtml
/press/summaries/2012/ElectionCycle/12m_PresCand.shtml
/press/summaries/2012/ElectionCycle/6m_PresCand.shtml

/press/summaries/2010/ElectionCycle/24m_CongCand.shtml
/press/summaries/2010/ElectionCycle/21m_CongCand.shtml
/press/summaries/2010/ElectionCycle/18m_CongCand.shtml
/press/summaries/2010/ElectionCycle/15m_CongCand.shtml
/press/summaries/2010/ElectionCycle/12m_CongCand.shtml
/press/summaries/2010/ElectionCycle/6m_CongCand.shtml

/press/summaries/2010/ElectionCycle/24m_IE_EC.shtml
/press/summaries/2010/ElectionCycle/21m_IE_EC.shtml
/press/summaries/2010/ElectionCycle/18m_IE_EC.shtml
/press/summaries/2010/ElectionCycle/15m_IE_EC.shtml
/press/summaries/2010/ElectionCycle/12m_IE_EC.shtml
/press/summaries/2010/ElectionCycle/6m_IE_EC.shtml

/press/summaries/2010/ElectionCycle/24m_NatlParty.shtml
/press/summaries/2010/ElectionCycle/21m_NatlParty.shtml
/press/summaries/2010/ElectionCycle/18m_NatlParty.shtml
/press/summaries/2010/ElectionCycle/15m_NatlParty.shtml
/press/summaries/2010/ElectionCycle/12m_NatlParty.shtml
/press/summaries/2010/ElectionCycle/6m_NatlParty.shtml

/press/summaries/2010/ElectionCycle/24m_PAC.shtml
/press/summaries/2010/ElectionCycle/21m_PAC.shtml
/press/summaries/2010/ElectionCycle/18m_PAC.shtml
/press/summaries/2010/ElectionCycle/15m_PAC.shtml
/press/summaries/2010/ElectionCycle/12m_PAC.shtml
/press/summaries/2010/ElectionCycle/6m_PAC.shtml

/press/summaries/2008/ElectionCycle/24m_CongCand.shtml
/press/summaries/2008/ElectionCycle/21m_CongCand.shtml
/press/summaries/2008/ElectionCycle/18m_CongCand.shtml
/press/summaries/2008/ElectionCycle/15m_CongCand.shtml
/press/summaries/2008/ElectionCycle/12m_CongCand.shtml
/press/summaries/2008/ElectionCycle/6m_CongCand.shtml

/press/summaries/2008/ElectionCycle/24m_IE_EC.shtml
/press/summaries/2008/ElectionCycle/21m_IE_EC.shtml
/press/summaries/2008/ElectionCycle/18m_IE_EC.shtml
/press/summaries/2008/ElectionCycle/15m_IE_EC.shtml
/press/summaries/2008/ElectionCycle/12m_IE_EC.shtml
/press/summaries/2008/ElectionCycle/6m_IE_EC.shtml

/press/summaries/2008/ElectionCycle/24m_NatlParty.shtml
/press/summaries/2008/ElectionCycle/21m_NatlParty.shtml
/press/summaries/2008/ElectionCycle/18m_NatlParty.shtml
/press/summaries/2008/ElectionCycle/15m_NatlParty.shtml
/press/summaries/2008/ElectionCycle/12m_NatlParty.shtml
/press/summaries/2008/ElectionCycle/6m_NatlParty.shtml

/press/summaries/2008/ElectionCycle/24m_PAC.shtml
/press/summaries/2008/ElectionCycle/21m_PAC.shtml
/press/summaries/2008/ElectionCycle/18m_PAC.shtml
/press/summaries/2008/ElectionCycle/15m_PAC.shtml
/press/summaries/2008/ElectionCycle/12m_PAC.shtml
/press/summaries/2008/ElectionCycle/6m_PAC.shtml

/press/summaries/2008/ElectionCycle/24m_PresCand.shtml
/press/summaries/2008/ElectionCycle/21m_PresCand.shtml
/press/summaries/2008/ElectionCycle/18m_PresCand.shtml
/press/summaries/2008/ElectionCycle/15m_PresCand.shtml
/press/summaries/2008/ElectionCycle/12m_PresCand.shtml
/press/summaries/2008/ElectionCycle/6m_PresCand.shtml

/press/summaries/2006/ElectionCycle/24m_CongCand.shtml
/press/summaries/2006/ElectionCycle/21m_CongCand.shtml
/press/summaries/2006/ElectionCycle/18m_CongCand.shtml
/press/summaries/2006/ElectionCycle/15m_CongCand.shtml
/press/summaries/2006/ElectionCycle/12m_CongCand.shtml
/press/summaries/2006/ElectionCycle/6m_CongCand.shtml

/press/summaries/2006/ElectionCycle/24m_IE_EC.shtml
/press/summaries/2006/ElectionCycle/21m_IE_EC.shtml
/press/summaries/2006/ElectionCycle/18m_IE_EC.shtml
/press/summaries/2006/ElectionCycle/15m_IE_EC.shtml
/press/summaries/2006/ElectionCycle/12m_IE_EC.shtml
/press/summaries/2006/ElectionCycle/6m_IE_EC.shtml

/press/summaries/2006/ElectionCycle/24m_NatlParty.shtml
/press/summaries/2006/ElectionCycle/21m_NatlParty.shtml
/press/summaries/2006/ElectionCycle/18m_NatlParty.shtml
/press/summaries/2006/ElectionCycle/15m_NatlParty.shtml
/press/summaries/2006/ElectionCycle/12m_NatlParty.shtml
/press/summaries/2006/ElectionCycle/6m_NatlParty.shtml

/press/summaries/2006/ElectionCycle/24m_PAC.shtml
/press/summaries/2006/ElectionCycle/21m_PAC.shtml
/press/summaries/2006/ElectionCycle/18m_PAC.shtml
/press/summaries/2006/ElectionCycle/15m_PAC.shtml
/press/summaries/2006/ElectionCycle/12m_PAC.shtml
/press/summaries/2006/ElectionCycle/6m_PAC.shtml

/press/summaries/2004/ElectionCycle/24m_CongCand.shtml
/press/summaries/2004/ElectionCycle/21m_CongCand.shtml
/press/summaries/2004/ElectionCycle/18m_CongCand.shtml
/press/summaries/2004/ElectionCycle/15m_CongCand.shtml
/press/summaries/2004/ElectionCycle/15m_CongCand.shtml
/press/summaries/2004/ElectionCycle/12m_CongCand.shtml
/press/summaries/2004/ElectionCycle/6m_CongCand.shtml

/press/summaries/2004/ElectionCycle/24m_IE_EC.shtml
/press/summaries/2004/ElectionCycle/21m_IE_EC.shtml
/press/summaries/2004/ElectionCycle/18m_IE_EC.shtml
/press/summaries/2004/ElectionCycle/15m_IE_EC.shtml
/press/summaries/2004/ElectionCycle/12m_IE_EC.shtml
/press/summaries/2004/ElectionCycle/6m_IE_EC.shtml

/press/summaries/2004/ElectionCycle/24m_NatlParty.shtml
/press/summaries/2004/ElectionCycle/21m_NatlParty.shtml
/press/summaries/2004/ElectionCycle/18m_NatlParty.shtml
/press/summaries/2004/ElectionCycle/15m_NatlParty.shtml
/press/summaries/2004/ElectionCycle/12m_NatlParty.shtml
/press/summaries/2004/ElectionCycle/6m_NatlParty.shtml

/press/summaries/2004/ElectionCycle/24m_PAC.shtml
/press/summaries/2004/ElectionCycle/21m_PAC.shtml
/press/summaries/2004/ElectionCycle/18m_PAC.shtml
/press/summaries/2004/ElectionCycle/15m_PAC.shtml
/press/summaries/2004/ElectionCycle/12m_PAC.shtml
/press/summaries/2004/ElectionCycle/6m_PAC.shtml

/press/summaries/2004/ElectionCycle/24m_PresCand.shtml
/press/summaries/2004/ElectionCycle/21m_PresCand.shtml
/press/summaries/2004/ElectionCycle/18m_PresCand.shtml
/press/summaries/2004/ElectionCycle/15m_PresCand.shtml
/press/summaries/2004/ElectionCycle/12m_PresCand.shtml
/press/summaries/2004/ElectionCycle/6m_PresCand.shtml

/press/summaries/2002/ElectionCycle/24m_CongCand.shtml
/press/summaries/2002/ElectionCycle/21m_CongCand.shtml
/press/summaries/2002/ElectionCycle/18m_CongCand.shtml
/press/summaries/2002/ElectionCycle/15m_CongCand.shtml
/press/summaries/2002/ElectionCycle/12m_CongCand.shtml
/press/summaries/2002/ElectionCycle/6m_CongCand.shtml

/press/summaries/2002/ElectionCycle/24m_IE.shtml
/press/summaries/2002/ElectionCycle/21m_IE.shtml
/press/summaries/2002/ElectionCycle/18m_IE.shtml
/press/summaries/2002/ElectionCycle/15m_IE.shtml
/press/summaries/2002/ElectionCycle/12m_IE.shtml
/press/summaries/2002/ElectionCycle/6m_IE.shtml

/press/summaries/2002/ElectionCycle/24m_NatlParty.shtml
/press/summaries/2002/ElectionCycle/21m_NatlParty.shtml
/press/summaries/2002/ElectionCycle/18m_NatlParty.shtml
/press/summaries/2002/ElectionCycle/15m_NatlParty.shtml
/press/summaries/2002/ElectionCycle/12m_NatlParty.shtml
/press/summaries/2002/ElectionCycle/6m_NatlParty.shtml

/press/summaries/2002/ElectionCycle/24m_PAC.shtml
/press/summaries/2002/ElectionCycle/21m_PAC.shtml
/press/summaries/2002/ElectionCycle/18m_PAC.shtml
/press/summaries/2002/ElectionCycle/15m_PAC.shtml
/press/summaries/2002/ElectionCycle/12m_PAC.shtml
/press/summaries/2002/ElectionCycle/6m_PAC.shtml

/press/summaries/2000/ElectionCycle/24m_CongCand.shtml
/press/summaries/2000/ElectionCycle/21m_CongCand.shtml
/press/summaries/2000/ElectionCycle/18m_CongCand.shtml
/press/summaries/2000/ElectionCycle/15m_CongCand.shtml
/press/summaries/2000/ElectionCycle/12m_CongCand.shtml
/press/summaries/2000/ElectionCycle/6m_CongCand.shtml

/press/summaries/2000/ElectionCycle/24m_IE.shtml
/press/summaries/2000/ElectionCycle/21m_IE.shtml
/press/summaries/2000/ElectionCycle/18m_IE.shtml
/press/summaries/2000/ElectionCycle/15m_IE.shtml
/press/summaries/2000/ElectionCycle/12m_IE.shtml
/press/summaries/2000/ElectionCycle/6m_IE.shtml

/press/summaries/2000/ElectionCycle/24m_NatlParty.shtml
/press/summaries/2000/ElectionCycle/21m_NatlParty.shtml
/press/summaries/2000/ElectionCycle/18m_NatlParty.shtml
/press/summaries/2000/ElectionCycle/15m_NatlParty.shtml
/press/summaries/2000/ElectionCycle/12m_NatlParty.shtml
/press/summaries/2000/ElectionCycle/6m_NatlParty.shtml

/press/summaries/2000/ElectionCycle/24m_PAC.shtml
/press/summaries/2000/ElectionCycle/21m_PAC.shtml
/press/summaries/2000/ElectionCycle/18m_PAC.shtml
/press/summaries/2000/ElectionCycle/15m_PAC.shtml
/press/summaries/2000/ElectionCycle/12m_PAC.shtml
/press/summaries/2000/ElectionCycle/6m_PAC.shtml

/press/summaries/2000/ElectionCycle/24m_PresCand.shtml
/press/summaries/2000/ElectionCycle/21m_PresCand.shtml
/press/summaries/2000/ElectionCycle/18m_PresCand.shtml
/press/summaries/2000/ElectionCycle/15m_PresCand.shtml
/press/summaries/2000/ElectionCycle/12m_PresCand.shtml
/press/summaries/2000/ElectionCycle/6m_PresCand.shtml

/press/summaries/1998/ElectionCycle/24m_CongCand.shtml
/press/summaries/1998/ElectionCycle/21m_CongCand.shtml
/press/summaries/1998/ElectionCycle/18m_CongCand.shtml
/press/summaries/1998/ElectionCycle/15m_CongCand.shtml
/press/summaries/1998/ElectionCycle/12m_CongCand.shtml
/press/summaries/1998/ElectionCycle/6m_CongCand.shtml

/press/summaries/1998/ElectionCycle/24m_IE.shtml
/press/summaries/1998/ElectionCycle/21m_IE.shtml
/press/summaries/1998/ElectionCycle/18m_IE.shtml
/press/summaries/1998/ElectionCycle/15m_IE.shtml
/press/summaries/1998/ElectionCycle/12m_IE.shtml
/press/summaries/1998/ElectionCycle/6m_IE.shtml

/press/summaries/1998/ElectionCycle/24m_NatlParty.shtml
/press/summaries/1998/ElectionCycle/21m_NatlParty.shtml
/press/summaries/1998/ElectionCycle/18m_NatlParty.shtml
/press/summaries/1998/ElectionCycle/15m_NatlParty.shtml
/press/summaries/1998/ElectionCycle/12m_NatlParty.shtml
/press/summaries/1998/ElectionCycle/6m_NatlParty.shtml

/press/summaries/1998/ElectionCycle/24m_PAC.shtml
/press/summaries/1998/ElectionCycle/21m_PAC.shtml
/press/summaries/1998/ElectionCycle/18m_PAC.shtml
/press/summaries/1998/ElectionCycle/15m_PAC.shtml
/press/summaries/1998/ElectionCycle/12m_PAC.shtml
/press/summaries/1998/ElectionCycle/6m_PAC.shtml

/press/summaries/1996/ElectionCycle/24m_CongCand.shtml
/press/summaries/1996/ElectionCycle/21m_CongCand.shtml
/press/summaries/1996/ElectionCycle/18m_CongCand.shtml
/press/summaries/1996/ElectionCycle/15m_CongCand.shtml
/press/summaries/1996/ElectionCycle/12m_CongCand.shtml
/press/summaries/1996/ElectionCycle/6m_CongCand.shtml

/press/summaries/1996/ElectionCycle/24m_IE.shtml
/press/summaries/1996/ElectionCycle/21m_IE.shtml
/press/summaries/1996/ElectionCycle/18m_IE.shtml
/press/summaries/1996/ElectionCycle/15m_IE.shtml
/press/summaries/1996/ElectionCycle/12m_IE.shtml
/press/summaries/1996/ElectionCycle/6m_IE.shtml

/press/summaries/1996/ElectionCycle/24m_NatlParty.shtml
/press/summaries/1996/ElectionCycle/21m_NatlParty.shtml
/press/summaries/1996/ElectionCycle/18m_NatlParty.shtml
/press/summaries/1996/ElectionCycle/15m_NatlParty.shtml
/press/summaries/1996/ElectionCycle/12m_NatlParty.shtml
/press/summaries/1996/ElectionCycle/6m_NatlParty.shtml

/press/summaries/1996/ElectionCycle/24m_PAC.shtml
/press/summaries/1996/ElectionCycle/21m_PAC.shtml
/press/summaries/1996/ElectionCycle/18m_PAC.shtml
/press/summaries/1996/ElectionCycle/12m_PAC.shtml
/press/summaries/1996/ElectionCycle/12m_PAC.shtml
/press/summaries/1996/ElectionCycle/6m_PAC.shtml

/press/summaries/1996/ElectionCycle/24m_PresCand.shtml
/press/summaries/1996/ElectionCycle/21m_PresCand.shtml
/press/summaries/1996/ElectionCycle/18m_PresCand.shtml
/press/summaries/1996/ElectionCycle/15m_PresCand.shtml
/press/summaries/1996/ElectionCycle/12m_PresCand.shtml
/press/summaries/1996/ElectionCycle/6m_PresCand.shtml

/press/summaries/1994/ElectionCycle/24m_CongCand.shtml
/press/summaries/1994/ElectionCycle/21m_CongCand.shtml
/press/summaries/1994/ElectionCycle/18m_CongCand.shtml
/press/summaries/1994/ElectionCycle/15m_CongCand.shtml
/press/summaries/1994/ElectionCycle/12m_CongCand.shtml
/press/summaries/1994/ElectionCycle/6m_CongCand.shtml

/press/summaries/1994/ElectionCycle/24m_IE.shtml
/press/summaries/1994/ElectionCycle/21m_IE.shtml
/press/summaries/1994/ElectionCycle/18m_IE.shtml
/press/summaries/1994/ElectionCycle/15m_IE.shtml
/press/summaries/1994/ElectionCycle/12m_IE.shtml
/press/summaries/1994/ElectionCycle/6m_IE.shtml

/press/summaries/1994/ElectionCycle/24m_NatlParty.shtml
/press/summaries/1994/ElectionCycle/21m_NatlParty.shtml
/press/summaries/1994/ElectionCycle/18m_NatlParty.shtml
/press/summaries/1994/ElectionCycle/15m_NatlParty.shtml
/press/summaries/1994/ElectionCycle/12m_NatlParty.shtml
/press/summaries/1994/ElectionCycle/6m_NatlParty.shtml

/press/summaries/1994/ElectionCycle/24m_PAC.shtml
/press/summaries/1994/ElectionCycle/21m_PAC.shtml
/press/summaries/1994/ElectionCycle/18m_PAC.shtml
/press/summaries/1994/ElectionCycle/15m_PAC.shtml
/press/summaries/1994/ElectionCycle/12m_PAC.shtml
/press/summaries/1994/ElectionCycle/6m_PAC.shtml

/press/summaries/1992/ElectionCycle/24m_CongCand.shtml
/press/summaries/1992/ElectionCycle/21m_CongCand.shtml
/press/summaries/1992/ElectionCycle/18m_CongCand.shtml
/press/summaries/1992/ElectionCycle/15m_CongCand.shtml
/press/summaries/1992/ElectionCycle/12m_CongCand.shtml
/press/summaries/1992/ElectionCycle/6m_CongCand.shtml

/press/summaries/1992/ElectionCycle/24m_IE.shtml
/press/summaries/1992/ElectionCycle/21m_IE.shtml
/press/summaries/1992/ElectionCycle/18m_IE.shtml
/press/summaries/1992/ElectionCycle/15m_IE.shtml
/press/summaries/1992/ElectionCycle/12m_IE.shtml
/press/summaries/1992/ElectionCycle/6m_IE.shtml

/press/summaries/1992/ElectionCycle/24m_NatlParty.shtml
/press/summaries/1992/ElectionCycle/21m_NatlParty.shtml
/press/summaries/1992/ElectionCycle/18m_NatlParty.shtml
/press/summaries/1992/ElectionCycle/15m_NatlParty.shtml
/press/summaries/1992/ElectionCycle/12m_NatlParty.shtml
/press/summaries/1992/ElectionCycle/6m_NatlParty.shtml

/press/summaries/1992/ElectionCycle/24m_PAC.shtml
/press/summaries/1992/ElectionCycle/21m_PAC.shtml
/press/summaries/1992/ElectionCycle/18m_PAC.shtml
/press/summaries/1992/ElectionCycle/15m_PAC.shtml
/press/summaries/1992/ElectionCycle/12m_PAC.shtml
/press/summaries/1992/ElectionCycle/6m_PAC.shtml

/press/summaries/1992/ElectionCycle/24m_PresCand.shtml
/press/summaries/1992/ElectionCycle/21m_PresCand.shtml
/press/summaries/1992/ElectionCycle/18m_PresCand.shtml
/press/summaries/1992/ElectionCycle/15m_PresCand.shtml
/press/summaries/1992/ElectionCycle/12m_PresCand.shtml
/press/summaries/1992/ElectionCycle/6m_PresCand.shtml

/press/summaries/1990/ElectionCycle/24m_CongCand.shtml
/press/summaries/1990/ElectionCycle/21m_CongCand.shtml
/press/summaries/1990/ElectionCycle/18m_CongCand.shtml
/press/summaries/1990/ElectionCycle/15m_CongCand.shtml
/press/summaries/1990/ElectionCycle/12m_CongCand.shtml
/press/summaries/1990/ElectionCycle/6m_CongCand.shtml

/press/summaries/1990/ElectionCycle/24m_IE.shtml
/press/summaries/1990/ElectionCycle/21m_IE.shtml
/press/summaries/1990/ElectionCycle/18m_IE.shtml
/press/summaries/1990/ElectionCycle/15m_IE.shtml
/press/summaries/1990/ElectionCycle/12m_IE.shtml
/press/summaries/1990/ElectionCycle/6m_IE.shtml

/press/summaries/1990/ElectionCycle/24m_NatlParty.shtml
/press/summaries/1990/ElectionCycle/21m_NatlParty.shtml
/press/summaries/1990/ElectionCycle/18m_NatlParty.shtml
/press/summaries/1990/ElectionCycle/15m_NatlParty.shtml
/press/summaries/1990/ElectionCycle/12m_NatlParty.shtml
/press/summaries/1990/ElectionCycle/6m_NatlParty.shtml

/press/summaries/1990/ElectionCycle/24m_PAC.shtml
/press/summaries/1990/ElectionCycle/21m_PAC.shtml
/press/summaries/1990/ElectionCycle/18m_PAC.shtml
/press/summaries/1990/ElectionCycle/15m_PAC.shtml
/press/summaries/1990/ElectionCycle/12m_PAC.shtml
/press/summaries/1990/ElectionCycle/6m_PAC.shtml

**Comment by djgarr** [comment]
Added the link for the Enforcement Statistics page (https://transition.fec.gov/em/enfpro/EnforcementProfile.shtml) to the top of the list (if it's in alphabetical order). Thanks!

**Comment by dorothyyeager** [comment]
Groomed the list a little to separate by directory (makes it easier for front end) and added a couple more redirected files to it.

**Comment by patphongs** [comment]
Deleted files as specified from transition on Mon Nov 23 13:53:27 EST 2020
