### ISSUE TITLE
Update links for ongoing and selected litigation pages to the Wagtail court case page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4121]
### Summary

**What we are after:**
_We are moving the court case pages into Wagtail. Since 2012, each case has had its own page created in transition. We need to move those individual case pages into Wagtail._

### Related issues

_List any relevant related issue(s)_

- #4119 Move related document links into case summaries

### Completion criteria

- [x] the transition page for each case linked at https://www.fec.gov/legal-resources/court-cases/#ongoing-litigation is moved into Wagtail using resource page template
- [x] the transition page for each case linked at https://www.fec.gov/legal-resources/court-cases/#selected-court-cases is moved into Wagtail using resource page template

**Comment by patphongs** [comment]
Relinked Ongoing and Selected court cases
