### ISSUE TITLE
Research searching penalties in enforcement cases 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#4122]
(Link to this ticket and close in favor of new front-end ticket)

### Summary

**What we're after:**
We'd like to see if there's a way to search penalties in enforcement cases.

### Related issues

_List any relevant related issue(s)_

- #4067 

### Background

https://transition.fec.gov/press/bkgnd/history.shtml lists the biggest penalties. Short term, we've replaced with a PDF. 

Press Office would like to know if MUR search could be used to generate a list of cases by penalties.

### Completion Criteria

- [ ] Research and document feasibility of adding penalties to MUR search (Press Office would like to sort by penalty size)

**Comment by cnlucas** [comment]
Closing in favor of #5986
