### ISSUE TITLE
Save/archive the content and files on the Campaign finance statistics transition page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4129]
**What we're after:** For safety, we want to retain all the content and files from the [campaign finance statistics transition page](https://transition.fec.gov/press/campaign_finance_statistics.shtml). 

This ticket is to make sure that content is retained in ...@johnnyporkchops will update this year with the location where we want to save this information. 

**Completion criteria:**
- [x] Campaign finance statistic summary files and pages are archived from transition

**Comment by kathycarothers** [comment]
Suggestion from John: For the archive link, if we need to maintain a permanent  redirect for https://transition.fec.gov/press/campaign_finance_statistics.shtml, we could create a copy of this page and remove all but the archive stuff and then just name it something else like https://transition.fec.gov/press/campaign_finance_statistics-archive.shtml and link to that for the archive link.

**Comment by dorothyyeager** [comment]
@patphongs Redirects are in place.

**Comment by dorothyyeager** [comment]
Just moving into 14.2 so we can discuss in grooming if we need this ticket.

**Comment by patphongs** [comment]
@dorothyyeager @johnnyporkchops I have archived the CF statistics summaries file [here](https://drive.google.com/file/d/1OMMXOxgn9bdECg-Lio-LCFJSvAbY_yGP/view?usp=sharing) 🔒
