### ISSUE TITLE
Remove 2020-1989 files from campaign finance statistical summary page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4130]
**What we're after:** Until we're able to build the [new archive summary page](https://github.com/fecgov/fec-cms/issues/4020), we need to [link to this page](https://transition.fec.gov/press/archived-campaign-finance-statistics.shtml) still from the new summary landing page on .gov.

In order to make this work, we want to remove any of the non-archived links and make this exclusively the archived page. To do that we need to make the following changes:
- Change page title to: Archived campaign finance statistics
- Remove anything not within an archived section. 

**Completion criteria:**
- [x] Make sure this page is linked to the [archived campaign finance statistics page](https://transition.fec.gov/press/archived-campaign-finance-statistics.shtml)
- [x] Only archived files are linked on this page. Any dated files outside of the archived sections has been removed.

**Comment by johnnyporkchops** [comment]
This page has been completed:
https://transition.fec.gov/press/archived-campaign-finance-statistics.shtml
@JonellaCulmer I think we need to edit the language in the first patagraph.

**Comment by kathycarothers** [comment]
Jonella has emailed Press to get their input for the first paragraph.

**Comment by jason-upchurch** [comment]
work is done. Closing.
