### ISSUE TITLE
Design court case wagtail page template

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4133]
**What we're after:** 
After the immediate migration of court cases, more or less, how they existed on transition, we need to then convert them to individual pages. Each court case, open or closed would warrant its own page.

This ticket is to design a template for court cases that mirrors the templates for MURs and AOs, but is specific to the content for court cases. This work will likely involve the update of the resource template to accommodate court cases.

**Action items:**
- [x] Template drafted and shared with Info for any modifications
- [x] Template shared with front-end to address any development concerns
- [x] Necessary changes and annotated to the resource template are documented
- [x] Open followup ticket for implementation

**Completion criteria:**
- [x] Design for court case page completed

**Comment by JonellaCulmer** [comment]
First draft based on one court case. Many of the court cases observed use different headings/sections/sub-sections, but all seem to have the same basic information for documents. 
![Court cases](https://user-images.githubusercontent.com/31663028/96506444-a5390700-1225-11eb-9384-c79816e843de.png)

**Comment by JonellaCulmer** [comment]
Updated mockups to show the new display for court case decisions and other related documents. 

There are four different versions we've found depending on the information available for each court case. 
- Court case summary and documents for single court appearance
- Court case summary and documents for multiple court appearances
- Court case summary but no documents
- Court case documents but no summary

The latter two cases can be accommodated within the formatting of the first two, so only those first two versions have been mocked up. They are below. 

I have an open questions for the second mockup (Van Hollen). 

### Court case with single court appearance
![Akins](https://user-images.githubusercontent.com/31663028/97751816-56169000-1ac9-11eb-8644-ce42976a3624.png)
### Court case with multiple court appearances
![Van Hollen](https://user-images.githubusercontent.com/31663028/97751819-56169000-1ac9-11eb-9a15-924628914ad1.png)

**Comment by zsmith-fec** [comment]
These look great! 

My one edit would be to keep the sources as part of the case summary and not as a separate section. (The list of Record articles make up the case summary, so they should be kept together.) I don't think we need an anchor for sources; no one goes directly to them.

In regard to the footnote, this should come at the end of the summary, before the source section. Thankfully, you shouldn't encounter too many footnotes.

**Comment by JonellaCulmer** [comment]
@zsmith-fec We previously discussed moving the FEC record links to the bottom of the page since the information in the Record articles was the same information in separate places. Do you no longer agree with that strategy?

I'm happy to move the footnotes back up and tie those two together. I agree _that_ information doesn't require its own section.

**Comment by zsmith-fec** [comment]
I'm really sorry, I must have misunderstood. The footnotes and Record links should be incorporated into the summary section. They lose their meaning/purpose if placed elsewhere.

**Comment by JonellaCulmer** [comment]
@zsmith-fec I've updated the mockups to move the sources and footnotes up under the summary. 

## Designs

### Court cases with a single appearance
<img width="593" alt="Screen Shot 2020-11-04 at 10 05 24 AM" src="https://user-images.githubusercontent.com/31663028/98128066-6fcb2500-1e85-11eb-81b3-66e8cc250638.png">


### Court cases with multiple court appearances
<img width="425" alt="Screen Shot 2020-11-04 at 10 05 42 AM" src="https://user-images.githubusercontent.com/31663028/98128083-748fd900-1e85-11eb-9f84-aecd4aaff72b.png">

**Comment by JonellaCulmer** [comment]
Discussed the court case designs with @johnnyporkchops and @patphongs and the resource template is in great shape already for the future modifications that will be needed. 

One thing that the page doesn't already provide are the correct tables and their formatting. We will need to modify the resource template to accommodate these tables. Our plan is to create new text fields where wagtail users can enter the appropriate information. Users won't need to create a table but the information they input in text boxes will populate in a table that displays on the site.

Content fields needed:
- (document) Date
- (document) Name
  - Need to hyperlink to uploaded files
- (document # of) Pages

Additional headers may be needed around the tables as well. 
- Headers for all tables that explain whether they are Court decisions or (other) Related documents
- Headers to explain which court appearance the documents apply to. This is for cases only with multiple appearances.
  - Caveat: If we find that there's a technical limitation to only displaying those court appearance headers we can apply them in all cases. But the bare minimum state should be one that explains the court appearance. Even if it _has_ to apply to all cases.

**Comment by JonellaCulmer** [comment]
Closing this ticket in favor of implementation issue https://github.com/fecgov/fec-cms/issues/4191
