### ISSUE TITLE
New Reporting Example: Bank loans taken out by candidate committees

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#4151]
### Summary
Currently the site's candidate guide has a reporting example for [Candidate personal funds loans](https://www.fec.gov/help-candidates-and-committees/filing-reports/candidate-personal-funds-loans/) and [Candidate loans obtained from a bank](https://www.fec.gov/help-candidates-and-committees/filing-reports/bank-loans-obtained-candidate/), but we do not have a reporting example for loans that are obtained from a bank _by the committee itself_.

### Completion Criteria
- [x] Distribute drafting assignment to an interested RAD analyst
- [x] RAD manager review
- [x] Content team review
- [x] Add links to the Filing Candidate Reports page

### Supporting Material

- H4CC > Candidate guide > Handling candidate loans, debts, advances > [Bank Loans](https://www.fec.gov/help-candidates-and-committees/handling-loans-debts-and-advances/bank-loans/)
- Candidate guide: [Reporting Loans, Chapter 13, page 108](https://www.fec.gov/resources/cms-content/documents/candgui.pdf)

**Comment by kathycarothers** [comment]
Images drafted in 22.3

**Comment by bmathesonFEC** [comment]
The first draft of this reporting example is with RAD Managers to review now. I should have feedback before the end fo the week so it can be circulated among the Content team.

**Comment by bmathesonFEC** [comment]
Received feedbck from RAD managers. @ryanfec will distribute to the content team and build wagtail page.

**Comment by bmathesonFEC** [comment]
Page has been published: https://www.fec.gov/help-candidates-and-committees/filing-reports/bank-loan-obtained-candidate-committee/

Reporting example cards have been added to the following pages:
- Bank loans: https://www.fec.gov/help-candidates-and-committees/handling-loans-debts-and-advances/bank-loans/
- Types of contributions: https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/types-contributions/
- Candidate personal funds loans: https://www.fec.gov/help-candidates-and-committees/filing-reports/candidate-personal-funds-loans/
- Bank loans obtained by the candidate: https://www.fec.gov/help-candidates-and-committees/filing-reports/bank-loans-obtained-candidate/

In addition, a link has been added in the relevant portion of the Getting Started with FECFile Manual
