### ISSUE TITLE
Update footer to include link to status page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4154]
**What we're after:**
Once the procurement is finalized, we need to add the status page link to the footer. 

**Action items**
- [ ] Update mockup with agreed upon link title

**Completion criteria:**
- [ ] Link is added to footer

**Design:**
![Screen Shot 2020-10-27 at 11.07.13 AM.png](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/9db83ca9-c284-48b4-a53f-ed08b121f7b7)

**Comment by patphongs** [comment]
@JonellaCulmer We should probably be more specific in our naming of this link. FEC status can indicate multiple things, such as agency operating status, building status, etc. Can you think of something that pertains more to our website status?

**Comment by dorothyyeager** [comment]
@JonellaCulmer @patphongs How about `fec.gov status`?

**Comment by kathycarothers** [comment]
How about fec.gov website status, status website, website operation status, or operation status website, and last one website availability.  @JonellaCulmer

**Comment by JonellaCulmer** [comment]
@patphongs @kathycarothers @dorothyyeager I'm wondering if we need to specify the difference between the .gov and the API and, eventually, the efiling software. I'd rather not say `FEC.gov and openFEC API status` or FEC.gov, efiling and openFEC API status, when fewer words will be much better. 

Alternatively, considering the overall FEC universe of online products and just keep it to FEC.gov like Dorothy has suggested. That's probably the cleanest.
