### ISSUE TITLE
Create documentation for FEC page owner information

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4155]
### Summary

**What we're after:**
_To ensure only approved and public-ready content is posted on the website, we need to identify page owners for our website to allow managers to effectively curate the content that appears on the site._

### Related issues

- #1120 

### Items to include
- Page title
- Link to page
- Office
- Key pageowners for that office

### Completion criteria

- [x] Spreadsheet that documents FEC page owner information

**Comment by dorothyyeager** [comment]
I've started the spreadsheet and have sent the first draft of it to @AmyKort and @patphongs to look over and confirm if I'm on the right track.

**Comment by dorothyyeager** [comment]
Spreadsheet is finalized and has been moved into Content team drawer of Google drive.

Next step: Front-end testing of permissions in #4162
