### ISSUE TITLE
Migrate Request for Legal Consideration PDFs to CMS and make accessible

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4158]
### Summary

**What we're after:**
We're moving off of transition.

### Related issues

_List any relevant related issue(s)_

- #3878 

### Completion criteria

- [x] PDFs linked at https://transition.fec.gov/law/legalconsideration.shtml are made accessible and uploaded to the CMS (we'll want to create a collection)
- [x] Old PDFs are added to the redirect spreadsheet
- [x] PDFs are linked on the new page created in #3878
- [x] add redirects for PDFs hosted in Wagtail to our redirect spreadsheet.

**Comment by kathycarothers** [comment]
I am organizing the documents into folders, so Chris can make them accessible.

**Comment by kathycarothers** [comment]
I have a handful of documents that are giving me some problems, so I am reaching out to Chris Berg for help on accessibility for these documents.

**Comment by kathycarothers** [comment]
I am waiting on 3 documents from Chris. All the other documents have been uploaded in the cms and inputted in the redirect spreadsheet.

**Comment by dorothyyeager** [comment]
@kathycarothers uploaded the remaining documents and Zainab finished up the links and published the page. Doublechecked and it all looks good to go.

Was mulling over the needed redirects. I do think we will need to redirect them after all. It's possible the documents could be linked via MURs or Audit reports. For this ticket, I think it's enough to add them to the redirect spreadsheet and then we can make a redirect ticket for 13.8.

**Comment by dorothyyeager** [comment]
Closing as work is complete and @kathycarothers is good with the above approach.
