### ISSUE TITLE
Document zero-downtime Wagtail DB restore for loading court-cases

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#4164]
### Summary

**What we're after:**
Develop, test,  and document process for migrating scraped court case content into production cms database.

### Related issues

_List any relevant related issue(s)_

- #4120 
- #4118 
- https://github.com/fecgov/fec-cms/issues/4165

### Completion criteria

- [X] Decide what non-production environment we will use to test the Wagtail DB insertions 
  - we used `feature` space for testing
- [ ] create another service inside production to load data (new name)
- [ ] Load the data
- [ ] **verify approach is a zero-downtime deploy**
- [ ] Test and document the process for safely restoring the staged data to production with zero-downtime
- [ ] Document any important steps to take or considerations to make 
- [ ] Decide on a date to do a content halt and deploy the changes
- [ ] Communicate our plans with team

**Comment by patphongs** [comment]
WIP [document](https://docs.google.com/document/d/12PrFIq8EEP7Ws35T24JAmVB6Vntl4Y6PZCuj089X9Dw/edit#) 🔒

**Comment by patphongs** [comment]
This [document](https://docs.google.com/document/d/12PrFIq8EEP7Ws35T24JAmVB6Vntl4Y6PZCuj089X9Dw/edit#) 🔒  has been finalized and we will follow those procedures in this document during prep work on Tuesday 11/17 and final implementation on Wednesday 11/18.
