### ISSUE TITLE
[Due 11/18 after court case DB inserts complete in prod] QA for zero-downtime Wagtail DB restore for court-cases

### ISSUE THREAD

**Issue by jason-upchurch** [fecgov/fec-cms#4165]
### Summary
We need to QA the work from #4164.

For easier documentation of QA findings, please use [this spreadsheet](https://docs.google.com/spreadsheets/d/1bsmTTUDTNr4Ay2AXP7SBSqM72zHpVJbPmhN2L9KRf6g/edit#gid=0) 🔒 . Each QA person has their own spreadsheet tab.

### What pages to QA
- "Court case alphabetical index" page located at this path `https://www.fec.gov/legal-resources/court-cases/court-case-alphabetical-index/`
- Spot check different individual court case pages (We'll split out each section for QA so we don't overlap. Individuals currently helping with QA are: @JonellaCulmer, @kathycarothers, @dorothyyeager and @zsmith-fec) 

### What to look for in QA
- You can use the new Wagtail "Court case alphabetical index" page located at this path `https://www.fec.gov/legal-resources/court-cases/court-case-alphabetical-index/` to get to all the court case pages.
- Strange inserted characters
- No incomplete information on court case pages
- The template for the individual court case pages should be of the "Resource template" type.
- Do not look for content governance type of issues. The scraping tool did not account for this and needs to be fixed by hand.
- Spot check that no links are going to the transition.fec.gov site (court case pages or PDF files). If they are, we may need to account for it with a redirect.
- Check court cases with similar names that needed to be updated for scraping. Here's a [doc to the list of examples](https://docs.google.com/spreadsheets/d/1WEm4hsv8hojC6hylbze3qOkfpEcBMzhAiD0JL-SP7KE/edit#gid=1054893993) 🔒 .

### Action items
- [x] set up kick-off meeting with candidate QAers to go over what is to be done (11am 11/18 in content channel)
- [x] the QA needs to be done at the same time as the related work.

### Completion criteria
- [x] QA is complete with documented [QA findings](https://docs.google.com/spreadsheets/d/1bsmTTUDTNr4Ay2AXP7SBSqM72zHpVJbPmhN2L9KRf6g/edit#gid=0) 🔒

**Comment by patphongs** [comment]
The QA needs to be done after the DB inserts happen on Wednesday 11/18. Content team knows about this implementation and has said they have time to help QA and spot check.

**Comment by patphongs** [comment]
QA has been completed and findings documented
