### ISSUE TITLE
Optimization: Eliminate render-blocking resources

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4172]
### Background
Looking to [optimize the site's performance](https://github.com/fecgov/fec-cms/issues/3711) and that of the homepage specifically, the Lighthouse tool in Chromium browsers has made some suggestions. Some of these will have repercussions throughout the app so we're going to make them their own tickets.

# Recommendation: Eliminate render-blocking resources
Resources are blocking the first paint of your page. Consider delivering critical JS/CSS inline and deferring all non-critical JS/styles. [details](https://web.dev/render-blocking-resources/?utm_source=lighthouse&utm_medium=devtools)

## Overview
We could embed the content of our CSS and JS files into the page rather than linking to them

## Benefit (the 80 of 80/20)
Minimal

## Effort (the 20 of 80/20)
Likely minimal

## Complications
- Possible security complications? Thinking about the sandbox between in-page `<script>` and `<script src="…">`. Check into CORS rules
- Would want to make sure we aren't affecting templates unexpectedly
- Could affect script load timing and race conditions, like with a `<script async defer>` in the head (which would load last) vs putting all that code into the page right then

#### Related tickets
- [Preload key requests](https://github.com/fecgov/fec-cms/issues/4168)
- [Remove unused JavaScript](https://github.com/fecgov/fec-cms/issues/4169)
- [Remove unused CSS](https://github.com/fecgov/fec-cms/issues/4170)
- [Preconnect to required origins](https://github.com/fecgov/fec-cms/issues/4171)
- [Ensure text remains visible during webfont load](https://github.com/fecgov/fec-cms/issues/4173)
- [Reduce the impact of third-party code](https://github.com/fecgov/fec-cms/issues/4175)
- [Does not use passive listeners to improve scrolling performance](https://github.com/fecgov/fec-cms/issues/4176)
- [Image elements do not have explicit width and height](https://github.com/fecgov/fec-cms/issues/4177)
- [Serve static assets with an efficient cache policy](https://github.com/fecgov/fec-cms/issues/4178)
- [Minimize main-thread work](https://github.com/fecgov/fec-cms/issues/4179)
- [Avoid an excessive DOM size](https://github.com/fecgov/fec-cms/issues/4180)
- [Reduce JavaScript execution time](https://github.com/fecgov/fec-cms/issues/4181)
- [Avoid enormous network payloads](https://github.com/fecgov/fec-cms/issues/4182)
- [[aria-hidden="true"] elements contain focusable descendents](https://github.com/fecgov/fec-cms/issues/4183)
- [Elements with an ARIA [role] that require children to contain a specific [role] are missing some or all of those required children](https://github.com/fecgov/fec-cms/issues/4184)
- [[aria-*] attributes do not have valid values](https://github.com/fecgov/fec-cms/issues/4185)
- [ARIA IDs are not unique](https://github.com/fecgov/fec-cms/issues/4186)
- [Lists do not contain only <li> elements and script supporting elements (<script> and <template>)](https://github.com/fecgov/fec-cms/issues/4187)
- [[user-scalable="no"] is used in the <meta name="viewport"> element or the [maximum-scale] attribute is less than 5](https://github.com/fecgov/fec-cms/issues/4188)
- [Links to cross-origin destinations are unsafe](https://github.com/fecgov/fec-cms/issues/4189)
- [Serves images with low resolution](https://github.com/fecgov/fec-cms/issues/4190)

**Comment by JonellaCulmer** [comment]
Closing this ticket while we wrap up the webpack work. https://github.com/fecgov/fec-cms/issues/2708
