### ISSUE TITLE
Optimization: Reduce the impact of third-party code

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4175]
### Background
Looking to [optimize the site's performance](https://github.com/fecgov/fec-cms/issues/3711) and that of the homepage specifically, the Lighthouse tool in Chromium browsers has made some suggestions. Some of these will have repercussions throughout the app so we're going to make them their own tickets.

# Recommendation: Reduce the impact of third-party code
Third-party code can significantly impact load performance. Limit the number of redundant third-party providers and try to load third-party code after your page has primarily finished loading. [details](https://developers.google.com/web/fundamentals/performance/optimizing-content-efficiency/loading-third-party-javascript/?utm_source=lighthouse&utm_medium=devtools)

## Overview
The code we're loading from Google, Fastly, etc are adding nearly a full second to our page load.

## Benefit (the 80 of 80/20)
Significant

## Effort (the 20 of 80/20)
Likely minimal?
Not sure how much we can really do to change it. We could add `async` or `defer` to those `<script>` and we could preconnect.

## Complications
- Want to avoid issues with changed asset load times
- Changing one template could affect other pages that share the same template(s)
- Want to make sure deferring DAP's code doesn't affect their automatic listeners. Should be fine

#### Related tickets
- [Preload key requests](https://github.com/fecgov/fec-cms/issues/4168)
- [Remove unused JavaScript](https://github.com/fecgov/fec-cms/issues/4169)
- [Remove unused CSS](https://github.com/fecgov/fec-cms/issues/4170)
- [Preconnect to required origins](https://github.com/fecgov/fec-cms/issues/4171)
- [Eliminate render-blocking resources](https://github.com/fecgov/fec-cms/issues/4172)
- [Ensure text remains visible during webfont load](https://github.com/fecgov/fec-cms/issues/4173)
- [Does not use passive listeners to improve scrolling performance](https://github.com/fecgov/fec-cms/issues/4176)
- [Image elements do not have explicit width and height](https://github.com/fecgov/fec-cms/issues/4177)
- [Serve static assets with an efficient cache policy](https://github.com/fecgov/fec-cms/issues/4178)
- [Minimize main-thread work](https://github.com/fecgov/fec-cms/issues/4179)
- [Avoid an excessive DOM size](https://github.com/fecgov/fec-cms/issues/4180)
- [Reduce JavaScript execution time](https://github.com/fecgov/fec-cms/issues/4181)
- [Avoid enormous network payloads](https://github.com/fecgov/fec-cms/issues/4182)
- [[aria-hidden="true"] elements contain focusable descendents](https://github.com/fecgov/fec-cms/issues/4183)
- [Elements with an ARIA [role] that require children to contain a specific [role] are missing some or all of those required children](https://github.com/fecgov/fec-cms/issues/4184)
- [[aria-*] attributes do not have valid values](https://github.com/fecgov/fec-cms/issues/4185)
- [ARIA IDs are not unique](https://github.com/fecgov/fec-cms/issues/4186)
- [Lists do not contain only <li> elements and script supporting elements (<script> and <template>)](https://github.com/fecgov/fec-cms/issues/4187)
- [[user-scalable="no"] is used in the <meta name="viewport"> element or the [maximum-scale] attribute is less than 5](https://github.com/fecgov/fec-cms/issues/4188)
- [Links to cross-origin destinations are unsafe](https://github.com/fecgov/fec-cms/issues/4189)
- [Serves images with low resolution](https://github.com/fecgov/fec-cms/issues/4190)

**Completion criteria:**
- [ ] The warning is removed, or warnings that we can address are handled.

**Comment by johnnyporkchops** [comment]
CDNs Used.:
 Reported [here](https://www.webpagetest.org/result/210330_XiHY_e36ae07b12369dd305f601df42e5509e/1/performance_optimization/
)

www.fec.gov : Amazon CloudFront
www.googletagmanager.com :
dap.digitalgov.gov : Amazon CloudFront
www.google.com : Google
www.google-analytics.com : Google
www.gstatic.com : Google
stamen-tiles-d.a.ssl.fastly.net : Fastly
stamen-tiles-c.a.ssl.fastly.net : Fastly
stamen-tiles-a.a.ssl.fastly.net : Fastly
stamen-tiles-b.a.ssl.fastly.net : Fastly
