### ISSUE TITLE
Different size presidential candidate buttons

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#4194]
### Summary
The Presidential candidate buttons are different sizes on [Browse Data > Candidate](https://www.fec.gov/data/browse-data/?tab=candidates)s.

![image.png](https://images.zenhubusercontent.com/5c0e981b4b5806bc2bfc2cb5/4c870a8e-831e-4bf3-9344-b79d2d5bb9c3)

Not sure if this is a known issue or a limitation.

**Comment by JonellaCulmer** [comment]
@bmathesonFEC I think it's the extra line of text "2020 election" that's making the box slightly bigger.

**Comment by bmathesonFEC** [comment]
I see, should I close this on the basis that it's a non-issue?

**Comment by bmathesonFEC** [comment]
Closing issue. Fine as-is.
