### ISSUE TITLE
Migrating BCRA court case PDFs

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4201]
### Summary
We'll want to find a place to move the BCRA and Court case abstract PDFs from transition to the new website.

1. BCRA related PDF files seem to be linked under transition.fec.gov/pages/bcra/. Where should the BCRA PDF files go? Right now I don’t have them in our new bucket under /resources/legal-resources/litigation/ and wonder if they should be? --> This is the new path that court case PDF files are going to.

2. Similar story with this cca.pdf PDF, it’s linked under transition.fec.gov/pdf/ . Should that particular PDF also be moved under /resources/legal-resources/litigation/?

**Comment by dorothyyeager** [comment]
For #2 - It's an old outdated publication and we'll redirect it in #4200

**Comment by dorothyyeager** [comment]
The BCRA PDFs have a redirect in place - see this ticket: https://github.com/fecgov/fec-cms/issues/1161. We had uploaded BCRA litigation PDFS twice - once as part of a BCRA section so those had BCRA in the name, and one that was the material we're migrating now. It was decided to redirect the old BCRA litigation page and related files to the main court case landing page. We may want to put in redirects for those old files with BCRA in their URL and redirect them to the court cases landing page already.

If we want to ensure we have the PDFs already, check PDFs associated with these cases:

- Davis v. FEC
- McConnell v. FEC
- McCutcheon v. FEC
- Shays v. FEC I
- Shays v. FEC III
- Van Hollen v. FEC
- Wisconsin Right to Life v. FEC

**Comment by dorothyyeager** [comment]
After our QA testing, it seems we will need to put a redirect in place as well for these BCRA files. Taking Zainab off, since we'll need to turn this into a redirect ticket.

**Comment by dorothyyeager** [comment]
Actually, I take that back. We will need to migrate the BCRA files. @zsmith-fec @patphongs @johnnyporkchops

**Comment by patphongs** [comment]
@dorothyyeager These are the BCRA files on transition right now. Can you let me know which one of these should be on the content bucket under `/resources/legal-resources/litigation/`

![Screen Shot 2020-12-01 at 4 36 24 PM](https://user-images.githubusercontent.com/12799132/100799816-aa2bd180-33f3-11eb-845f-a482e8f8c262.png)

**Comment by dorothyyeager** [comment]
@patphongs Sorry for the delay in response!

These files are NOT litigation and don't need to migrate; I would think you could delete them and if desired, put in a redirect to the forms page.
form_9_instructions
schedule_e_form_5_instructions
all of the files that start with bcra_webform in the name

I would like to upload the file that's called fr67n230p70175.... into the CMS. It's not related to litigation but it's extremely hard to find in SERS so it's good to know where it lived (and maybe we can put in a redirect for it once uploaded).

**Comment by patphongs** [comment]
@dorothyyeager I have made updates as requested. PR is ready for your review to close out this ticket: https://github.com/fecgov/fec-proxy/pull/216
