### ISSUE TITLE
Redirect old Records after court case page migration

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4202]
### Summary

**What we're after:**
_Following  the court case migration QA, many Record links are broken. We need to figure out what is going on and fix or implement redirects_

### Related issues

- #4165 QA for court case migration
- #4200 Redirects for 13.9 (includes some redirects for court case materials)

### Completion criteria

- [x] Links within court case summary pages to the Record work.

**Comment by patphongs** [comment]
record articles under court cases with the `/record/` in the path should now be redirected correctly. There's another ticket to handle the `/fecrecord/` type articles. https://github.com/fecgov/fec-cms/issues/4207
