### ISSUE TITLE
Content clean-up for Selected and Ongoing Court case pages

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4203]
### Summary

**What we are after:**
_Following migration, we will need to clean up the court case summary pages linked under Selected and Ongoing court cases._

### Related issues

- #4165 QA for court cases
- #4121 Updating links to selected/ongoing on landing page

### Action Items

For each page:
- [x] Court decisions and related documents moved into separate section of page
- [x] Top section relabeled "summary"
- [x] Extra spaces are deleted
- [x] Headings with "Background" and "Opinion" sections are formatted as they are on [this page](https://www.fec.gov/legal-resources/court-cases/mcconnell-v-fec/).
- [x] [Content guide](https://docs.google.com/document/d/1SjRyiqVpdx3j2CkfqHJMS_psWXuTttUDJUsrQ7xN7W0/edit) is applied as needed (Note: We can't italicize the case in the title, but we should italicize cases otherwise)
- [x] Links are fixed as needed
- [x] Issues noted as needed

Example of cleaned-up page: https://www.fec.gov/legal-resources/court-cases/parsons-et-al-v-fec/

### Completion criteria

- [x] Pages have two sections (Summary and Decisions) 
- [x] Pages comply with style guide.
- [x] Links on the pages work.
- [x] Record links go in order from newest to oldest.
- [x] Promote tab filled out (example below)
![image](https://user-images.githubusercontent.com/24437369/99682698-8492e580-2a4d-11eb-9d7b-b5728d6ef065.png)

_Other future work that may be needed following this issue's completion._

We'll need to do similar clean-up on all the other court case pages in #4204 , but these are the priority.

**Comment by zsmith-fec** [comment]
Per @JonellaCulmer, headers should be styled as:
Background (h4)
Courts (Supreme court, District Court (DC), etc.) (h3)
Document headers (court decisions, related documents) (h4)

**Comment by zsmith-fec** [comment]
Notes:
--
Content Style Guide: https://docs.google.com/document/d/1SjRyiqVpdx3j2CkfqHJMS_psWXuTttUDJUsrQ7xN7W0/edit?ts=5f7b608a#heading=h.a5khqwbb649x

Case titles and courts should be in "Title Case." Headers should be in "Sentence case."

Each case has 2 sections. Section 1: Title=Summary (unhide); background=h3; decision=h4; sub-subheaders=bold and inline. Section 2: Title=Documents (unhide); courts=H3; court decisions=h4; related docs=h4

Italicize latin phrases (en banc, certiorari, amici curiae, etc.) and court case names

Re broken links: (per Dorothy) If they end in shtml, you can note them in the spreadsheet in the tab for that. If they end in PDF, the redirects should take care of them when they go live. If they are weird one off things like the Carey press release, just go ahead and link the Wagtail page.

Document names should be left as they are, unless latin phrase or not in title case.

**Comment by zsmith-fec** [comment]
Style updates for [selected and ongoing cases](https://www.fec.gov/legal-resources/court-cases/) completed and double checked.
