### ISSUE TITLE
Post court case migration clean-up 

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4204]
### Summary

**What we are after:**
_We need to follow up on some items following QA of the court case migration. When time permits, we'll take on cleaning up the rest of the court cases. This is work similar to work we are doing off and on with scraped press releases. We've made a separate ticket for priority cases at #4203. _

### Related issues

- #4165 - QA for migration
- #4203 - Clean up for selected / ongoing cases

Example of cleaned-up page: https://www.fec.gov/legal-resources/court-cases/parsons-et-al-v-fec/

### Action Items
For each page:
- [x]  Court decisions and related documents moved into separate section of page
- [x]  Top section relabeled "summary"
- [x]  Extra spaces are deleted
- [x]  Headings with "Background" and "Opinion" sections are formatted as they are on [this page](https://www.fec.gov/legal-resources/court-cases/mcconnell-v-fec/).
- [x] [ Content guide](https://docs.google.com/document/d/1SjRyiqVpdx3j2CkfqHJMS_psWXuTttUDJUsrQ7xN7W0/edit#heading=h.a5khqwbb649x) is applied as needed (Note: We can't italicize the case in the title, but we should italicize cases otherwise)
- [x]  Links are fixed as needed
- [x] Missing Record links are added as needed
- [x] Record links go in order from newest to oldest.
- [x] Footnotes are corrected to new format and anchors are in place 
- [x]  Issues noted as needed
- [x] Fill out promotion tab (example below)
- [x] All pages reviewed and published
![image](https://user-images.githubusercontent.com/24437369/99682399-26fe9900-2a4d-11eb-9965-fff6d8101bee.png)

### Completion criteria

-  Pages have two sections (Summary and Documents)
-  Pages comply with style guide.
-  Links on the pages work.

**Comment by kathycarothers** [comment]
@JonellaCulmer @zsmith @dorothyyeager Question if there are no documents for a court case are we just stating "Summary" and that is is it, or are labeling "Documents" and stating "There are no related documents" ?

**Comment by kathycarothers** [comment]
I have started on the letter O.

**Comment by JonellaCulmer** [comment]
@kathycarothers There shouldn't be a documents section if there are no documents. Thanks for checking!

**Comment by kathycarothers** [comment]
@JonellaCulmer Thank you!

**Comment by kathycarothers** [comment]
I have completed O and P.

**Comment by DMichaelFEC** [comment]
I just completed W

**Comment by kathycarothers** [comment]
I have started on the letter N and have worked up to FEC v. NCPAC (83-2823).

**Comment by DMichaelFEC** [comment]
I completed U and V

**Comment by kathycarothers** [comment]
@DMichaelFEC I went through the letter W cases and for the most they look good. Just tiny things to keep an eye out for the capitalization of the titles in the summary and linking the footnotes. If you are in on Tuesday in the morning I can go over how to anchor the footnotes. 

Also, I noticed some of the cases in the letters V and Us are Live + Draft and a couple of cases in the letter U were missed. There is one in particular the Goland vs United States it has some characters showing up that need to be removed.  When we go over the footnote anchors I can go over that case too.

**Comment by kathycarothers** [comment]
I have stopped at National Media Political Action Committee: FEC v. which is actually National Medical Political Action Committee.

**Comment by zsmith-fec** [comment]
Reviewed footnotes for U, V, W and published.

**Comment by DMichaelFEC** [comment]
I finished T, ready for review / publishing

**Comment by zsmith-fec** [comment]
Reviewed and published T.

**Comment by DMichaelFEC** [comment]
I just finished S, ready for review/ publishing. Some are already published because I was second review.

**Comment by zsmith-fec** [comment]
S is reviewed and published!

**Comment by DMichaelFEC** [comment]
I just finished R, ready for review/publishing.

**Comment by zsmith-fec** [comment]
Remaining work divided up as follows: Zainab: A-E; David: F-I; Don: J-M. Will review and publish each other's work.

**Comment by djgarr** [comment]
Updated cases for F-G

**Comment by DMichaelFEC** [comment]
Reviewed and published F-G

**Comment by DMichaelFEC** [comment]
I just finished J and K. They are ready for review/publishing.

**Comment by zsmith-fec** [comment]
A and B are ready for review and publishing. I will finish C and D tomorrow.

**Comment by zsmith-fec** [comment]
Reviewed and published J.

**Comment by DMichaelFEC** [comment]
Reviewed and published A and B

**Comment by zsmith-fec** [comment]
Reviewed and published O, P and R.

**Comment by DMichaelFEC** [comment]
L is finished and ready to publish.

**Comment by zsmith-fec** [comment]
Stopped with Common Cause v. FEC (85-1130). Will edit  the rest of C on 1/11/21.

**Comment by zsmith-fec** [comment]
Reviewed and published K.

**Comment by zsmith-fec** [comment]
C , D and E are ready for review.

**Comment by DMichaelFEC** [comment]
M is finished and ready for review/publishing.

**Comment by zsmith-fec** [comment]
H, I, and L have been reviewed and published.

**Comment by zsmith-fec** [comment]
M reviewed and published!

**Comment by DMichaelFEC** [comment]
N is finished and ready for review/publishing.

**Comment by zsmith-fec** [comment]
N reviewed and published!

**Comment by zsmith-fec** [comment]
If anyone on @fecgov/content is available to help close this ticket, letters C, D and E need to be reviewed and published. THANKS!

**Comment by djgarr** [comment]
E's been reviewed and published

**Comment by djgarr** [comment]
Finished reviewing D cases. Published. Had trouble fixing link under Davis v. FEC (Brief of Gene DeRossett and J. Edgar Broyhill II as Amici Curiae in Support of Appellant (02/27/2008) (link is at https://www.fec.gov/resources/legal-resources/litigation/davis_sc_amicus_davis_derossett.pdf)).

**Comment by djgarr** [comment]
@patphongs was able to locate the correct link mentioned above. Link's been updated

**Comment by DMichaelFEC** [comment]
C is reviewed and published!

**Comment by zsmith-fec** [comment]
All pages edited according to criteria above and published. Thanks to everyone involved! Closing ticket.
