### ISSUE TITLE
Fill in missing data on migrated court case pages

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4205]
### Summary

**What we are after:**
_Some court case pages are missing summary data. This can be for two reasons:
1. No summary data (like a Record article) was ever drafted, so there's none.
2. The summary data did not scrape properly from transition.

We need to fill in the missing data, either with "No summary is available." or the data that's on transition._

### Related issues

#4165 - QA for migration
#4203 - Clean up for selected / ongoing cases
#4204 - Clean up for the other cases

### Affected Pages

- https://www.fec.gov/legal-resources/court-cases/bialek-v-mukasey-formerly-bialek-v-keisler-bialek-v-gonzales-07-cv-00321-wyd-pal-marcus-v-mukasey-formerly-marcus-v-gonzales-cv07-0398-pct-ehc-beam-v-gonzales-07cv1227/ - Recommend adjusting the slug on this one. Needs to input data from transition.
- https://www.fec.gov/legal-resources/court-cases/schonberg-v-fec/ - needs "No summary is available" added
- https://www.fec.gov/legal-resources/court-cases/iowa-right-to-life-committee-inc-v-williams/ - needs investigation to determine what's available
- https://www.fec.gov/legal-resources/court-cases/olson-v-fec/ - needs investigation to determine what's available

--add missing data page URLs above--

### Action Items
For these pages listed above:
- [ ] Create "summary" section on resource page and fill in "No summary available" or with the data from the transition page that didn't scrape.
- [ ] Doublecheck quality using this checklist: (You may want a second pair of eyes)
-  Court decisions and related documents moved into separate section of page
-  Extra spaces are deleted
-  Headings with "Background" and "Opinion" sections are formatted as they are on [this page](https://www.fec.gov/legal-resources/court-cases/mcconnell-v-fec/).
- "Background" should use H3 styling
-  Content guide is applied as needed (Note: We can't italicize the case in the title, but we should italicize cases otherwise)
-  Links are fixed as needed
-  Issues noted as needed
- Use H3 for subject headings
- Use H4 for topic headings
- Per content guide, use sentence case for headings
- For Latin words in text or in the name of a document, Italicize
- Remove all caps words
- Add "Opinion" documents before "Related documents" if nedded

### Completion criteria

- [x] Affected pages have missing data filled in

**Comment by johnnyporkchops** [comment]
- Bialek has been populated with content. The issue was a missing slash in post scrping cleanup. 
   - https://www.fec.gov/legal-resources/court-cases/bialek-v-mukasey-formerly-bialek-v-keisler-bialek-v-gonzales-07-cv-00321-wyd-pal-marcus-v-mukasey-formerly-marcus-v-gonzales-cv07-0398-pct-ehc-beam-v-gonzales-07cv1227/
- These three  appear as they are on transition (either lacking a summary, or no content at all)
   - https://www.fec.gov/legal-resources/court-cases/schonberg-v-fec/ 
   - https://www.fec.gov/legal-resources/court-cases/iowa-right-to-life-committee-inc-v-williams/ 
   - https://www.fec.gov/legal-resources/court-cases/olson-v-fec/

**Comment by djgarr** [comment]
Updated review elements

**Comment by JonellaCulmer** [comment]
Only page that I found with missing data was the Iowa Right to Life Committee Inc  court case. @johnnyporkchops seems to have already addressed that one. If that page is supposed to be missing all information at this time then it is appearing correctly.

**Comment by kathycarothers** [comment]
Bialek and Schonberg are done

**Comment by kathycarothers** [comment]
For the Iowa Right to Life case there is no info in transition. Should I state "No summary is available" and then list under Related documents the Appeals Court (8th Cir.)
Opinion (8/13/99)  @dorothyyeager @zsmith-fec

**Comment by dorothyyeager** [comment]
Yes. I checked the 1999 Record issues (also doublechecked 1998 and 2000) and no summary was written for this case.

**Comment by dorothyyeager** [comment]
@kathycarothers Yes. It wasn't covered in the Record (checked 1998-2000 indexes).

**Comment by kathycarothers** [comment]
@dorothyyeager Thank you

**Comment by kathycarothers** [comment]
These 4 cases have been updated.
