### ISSUE TITLE
Clean up court case alpha page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4210]
### Summary

**What we are after:**
_Now that court case pages are migrated, we need to clean them up and bring them into current content style._

### Related issues

_List any relevant related issue(s)_

- #4204 (court case summary page clean up)
- #4246

### Completion criteria

- [x] Court case alpha page at https://www.fec.gov/legal-resources/court-cases/court-case-alphabetical-index/ follows current style

###  Action Items
- [x]  Extra spaces are deleted
- [x] Content guide is applied as needed (Note: case names italicized)
- [x] Ensure cases are in alpha order
- [x]  Links are fixed as needed
- [x] Fill out promote tab 
- [x] Remove this sentence: The PDF files on this web site may be viewed or printed using the Adobe® Acrobat® Reader available from Adobe Systems Incorporated.
- [x] Remove "[PDF]"
- [x] Years are done with 4 digits, not 2: 2020 not 20 for example

**Comment by zsmith-fec** [comment]
Created new ticket #4246 to move court decisions from alphabetical list and to delete "opinions" column

**Comment by zsmith-fec** [comment]
Will work on edits from second review. Should be able to close ticket by 12/11/20.

**Comment by zsmith-fec** [comment]
Edits made from second review. Closing out ticket.
