### ISSUE TITLE
Investigate increasing CDN cache length

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#4213]
### Summary

**What we're after:**
The CDN service (cloudfront) that sits in front of www.fec.gov is our main caching layer and a great tool for for performance improvement and resiliency. The CDN service respects the `cache-control:` header which we seem to be universally setting to 600 seconds (10 min). 

```
curl -I "https://www.fec.gov/"
...
cache-control: max-age=600
```

- [ ] Research setting this to be longer
- [ ] Research why we have this output twice

### Related issues

_List any relevant related issue(s)_

- #[issue_number]
- #[issue_number]

### Completion criteria

_What does the end state look like? Include any behavior, appearance, etc required for this ticket to be 'complete.'_

### Tech steps or considerations (optional)

_List any considerations the tech team should know. Additionally, any specific tech steps can be included here._

- [ ] First
- [ ] Next
- [ ] Then

### Future work

_Other future work that may be needed following this issue's completion._

**Comment by patphongs** [comment]
Let's keep the cache length as is since it's working ok for us right now. We can revisit later if needed.
