### ISSUE TITLE
Add missing case pages

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4214]
### Summary

**What we are after:**
_A few cases didn't make it from Record summaries to court case pages, and so we'll need to make a page for them and add them to the alpha index._

### Related issues

#4204 Court case clean up

### List of pages to create (See Record summary linked)
https://www.fec.gov/updates/american-tradition-partnership-inc-v-bullock/
https://www.fec.gov/updates/us-v-danielczyk/

### Completion criteria

- [x] Missing cases have pages created for them
- [x] Second pair of eyes
- [x] Related PDFs are uploaded to CMS
- [x] Alpha index is updated to link new pages/cases

**Comment by djgarr** [comment]
Added pages and added information to chart. Need to double check everything before having a second set of eyes review. Everything was saved as a draft

**Comment by zsmith-fec** [comment]
@dorothyyeager and @djgarr 
Please hold on publishing these pages. Litigation doesn't always want cases to appear on the website (ex. in frivolous cases or when we are not parties). I am confirming these two and will follow up.

**Comment by zsmith-fec** [comment]
Ok, Harry Summers approved postings. Thanks!

**Comment by djgarr** [comment]
Just doing final checks before publishing the pages and closing the ticket
