### ISSUE TITLE
Take down pages redirected in 13.8 off transition

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4216]
### Summary

**What we are after:**
_We are getting off of transition._

Note: this issue does not include any of the court case-related work in case we still need those pages during clean up.

### Related issues

#4124 - redirected pages

### Completion criteria

- [ ] These pages are taken down:
/hava/law_ext.txt
/law/legalconsideration.shtml
/law/policy.shtml
/pages/brochures/sale_and_use_brochure.pdf

**Comment by rfultz** [comment]
@kathycarothers @dorothyyeager @djgarr I think this is ready for your review. The first and third files were already gone, though.

For the third, there's a directory called policy but not a page. (I did _not_ delete that)

**Comment by dorothyyeager** [comment]
Thanks @rfultz! Nothing to review on our end. All are redirecting properly and it's good that you didn't delete the policy directory. At some point, someone on content should go through it and make sure we got it all before deleting it. The policy.shtml page was migrated so we're safe there.

**Comment by dorothyyeager** [comment]
Thanks as always @rfultz I hit send too soon. I'll note that these pages came down in our spreadsheet and we can close this ticket.
