### ISSUE TITLE
Leadership committee profile page 404-ing

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4221]
Getting a 404 on this page: https://www.fec.gov/data/committee/C00481242/

**Comment by pkfec** [comment]
Here are the 5 API endpoints that are being called behind the scenes: 

INFO:data.api_caller: load_first_row_data: http://localhost:5000/v1/committee/C00481242/history?per_page=1&api_key=xxx
INFO:data.api_caller: load_endpoint_results: http://localhost:5000/v1/committee/C00481242/candidates/history/2020?election_full=False&api_key=xxx
INFO:data.api_caller: load_first_row_data: http://localhost:5000/v1/filings?form_category=REPORT&most_recent=True&committee_id=C00481242&cycle=2020&per_page=1&sort_hide_null=True&api_key=xxx
INFO:data.api_caller: load_first_row_data: http://localhost:5000/v1/committee/C00481242/totals?committee_id=C00481242&cycle=2020&per_page=1&sort_hide_null=True&api_key=xxx
INFO:data.api_caller: load_first_row_data: http://localhost:5000/v1/candidate/S2MO00429/history?per_page=1&api_key=xxx
INFO:data.api_caller: load_single_type: http://localhost:5000/v1/candidate/S2MO00429/history/2020?per_page=1&election_full=False&api_key=xxx
Not Found: /data/committee/C00481242/
**WARNING:django.request: Not Found: /data/committee/C00481242/
[01/Dec/2020 10:49:36] "GET /data/committee/C00481242/ HTTP/1.1" 404 1727**

**Comment by pkfec** [comment]
The candidate `S2MO00429` is active thru 2012 and 2018 election_cycles only. There is NO data for this candidate for 2020 election_cycle. Here is the API call, returns ZERO results.
http://localhost:5000/v1/candidate/S2MO00429/history/2020?per_page=1&election_full=False&api_key=xxx

CMS is not handling this scenario gracefully and throwing a 404 error.

**Comment by lbeaufort** [comment]
Also adding a hotfix for this per @PaulClark2, so reopening

**Comment by pkfec** [comment]
Hotfix PR fecgov/fec-cms#4249 deployed to Prod. Closing this issue.
