### ISSUE TITLE
Update the coordinated party expenditure limit page with the 2021 limits

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4225]
### Summary

**What we're after:**
_As a user, I need to know the coordinated party expenditure limits for 2021 as soon as they are available._

This ticket is to update the coordinated party expenditure limits when they adjusted for inflation in 2021.

### Related issues

- #4224 - Contribution limits snippet
- #4229 - Inflation adjustment notice

### Completion criteria

- [x] Coordinated party expenditure page is updated with the new limits
- [x] The html snippet in Wagtail for the archive is updated if needed to add a link to the 2020 limits (use the FR notice cite and PDF link once available).
- [x]  Second pair of eyes from Info Division Note: do not publish until the Federal Register notice is published or when we get the word.

### Tech steps or considerations

-  Snippet is stored in Wagtail with other snippets

**Comment by kathycarothers** [comment]
I need to update the snippet (need the FR notice) and the Record article link.

**Comment by kathycarothers** [comment]
I had Liz from the Info Div look over the page as my second pair of eyes.

**Comment by kathycarothers** [comment]
All has been updated
