### ISSUE TITLE
Candidate profile page S6CA00808 server error

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4234]
### Summary

_We are getting a server error for this candidate profile page: https://www.fec.gov/data/candidate/S6CA00808/_

### Error

```
File "/Users/xxx/dev/fec-cms/fec/data/views.py", line 279, in get_candidate
    current_committee_name = committees[0].get('name')
IndexError: list index out of range
```

**Completion criteria:**
- [x] Candidate profile pages with this type of error

**Comment by PaulClark2** [comment]
Similar symptom, https://github.com/fecgov/FEC/issues/10571. I’m not sure if this feedback issue is related to your current issue.

**Comment by patphongs** [comment]
> Similar symptom, [fecgov/FEC#10571](https://github.com/fecgov/FEC/issues/10571). I’m not sure if this feedback issue is related to your current issue. Candidate is in candidate endpoint, https://api.open.fec.gov/v1/candidate/H2OR01240/?sort_hide_null=false&sort_null_only=false&api_key=DEMO_KEY&sort_nulls_last=false&per_page=20&page=1&sort=name

Thanks @PaulClark2, the issue is related. We needed to handle candidates who do not have any committees linked yet. The [fix](https://github.com/fecgov/fec-cms/pull/4238) has been identified and has been merged into today's release.

**Comment by patphongs** [comment]
The fix has been merged, closing...
