### ISSUE TITLE
Mock-up footnotes appearance for court case pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4236]
**What we're after:** Document how (in the short-term) the court case footnotes should appear.

**Related issues:**
- https://github.com/fecgov/fec-cms/issues/4235 Make a plan for footnotes going forward

### Completion criteria
- [x] Mock-up footnotes appearance for court case pages

**Comment by JonellaCulmer** [comment]
GPO style guide reference: https://www.govinfo.gov/content/pkg/GPO-STYLEMANUAL-2016/pdf/GPO-STYLEMANUAL-2016.pdf#page=321

**Comment by JonellaCulmer** [comment]
Compiled the different ways we format footnotes on .gov: https://app.mural.co/t/fec4461/m/fec4461/1608153477803/ff0aabf845faf94e5e07f3008924a268f1121921

**Comment by JonellaCulmer** [comment]
Because this is an interim application of the footnotes and the strategy for using these in the future might change, I propose we maintain the pattern for footnotes we've used so far. 

There are some exceptions in the styling of footnotes across the site. If another style of footnotes is found prior to our enacting a new footnote strategy, we should update all other pages to this style. 

Footnotes styling for court cases and other pages in the interim:
**_HEADER:_** Bold italic, all caps, regular size font (16)
_Footnote text:_ Italic, regular size font (16). Footnote number in brackets.

<img width="880" alt="Screen Shot 2020-12-21 at 2 44 19 PM" src="https://user-images.githubusercontent.com/31663028/102815980-4154cb00-439b-11eb-847d-de0260a13dfb.png">

**Comment by kathycarothers** [comment]
@JonellaCulmer that looks and sounds fine to me.

**Comment by JonellaCulmer** [comment]
The content style guide has been updated with the proper footnote formatting. Individual case-by-case tickets will be opened for the implementation of this style, such as court case clean-up tickets and reporting page tickets. Closing this ticket in favor of those individual tickets. 

cc: @kathycarothers @djgarr @zsmith-fec
