### ISSUE TITLE
Create design for audit report landing pages

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4240]
### Summary

**What we're after:**
_Create a design for the audit report landing pages that will be based on existing templates for easier migration._

Audit report landing pages for different report types:
- [Authorized committee audit reports](https://transition.fec.gov/audits/audit_reports_auth.shtml)
- [Unauthorized committee audit reports](http://transition.fec.gov/audits/audit_reports_unauth.shtml)
- [Title 26 audit reports](http://transition.fec.gov/audits/audit_reports_pres.shtml)

**Considerations:**
See if we are able to filter the Audit report search to fit the lists for Authorized, Unauthorized, and Title 26 audit reports. If so, we should attempt to link to the pre-filtered list rather than recreate the audit report landing pages. This would help with duplicative content.

### Completion criteria

- [x] Design for audit report landing pages are created and shared
- [x] Get buy-in from public records/press

**Comment by JonellaCulmer** [comment]
The landing pages for the authorized and unauthorized cannot be replaced by links to filter search. The search does not distinguish those authorized committees that received public funds. Those are covered under Title 26 and are distinct. Until we have such a capability in the audit search, we can retain the breakdown pages for authorized, unauthorized and title 26 audits.

**Comment by JonellaCulmer** [comment]
@dorothyyeager @kathycarothers I wanted to get your thoughts on whether you thought we needed to some content updates for these pages. The introductions to these pages seem like definitions to me that can somewhat be covered by a glossary link. I think we can do a better job of explain the audit process as it relates to the authorized, unauthorized. The title 26 page seems to do a good job of this, but could also benefit from a content review. 

This would require engagement with other offices of course, but I wanted to get your initial thoughts.

**Comment by kathycarothers** [comment]
@JonellaCulmer @dorothyyeager I agree Jonella I think something needs to be done with these introductions.

**Comment by JonellaCulmer** [comment]
Thank you for that feedback @kathycarothers. Shall I open a separate content ticket for that work?

Preliminary mock up for the landing pages. The below image is for the authorized committee audit report page. The others will mimic this appearance with the same custom template. 

The other thing I'd like folks to consider is the page title for the title 26 audit reports. It's better that the link to the page and the page title match so that there's no confusion when a user ends up on that page. Would like folks to consider what we should call the page: Title 26 audit reports, Publicly financed and host committee audit reports, or some combination of the two. Either way the title needs to change, the one on transition right now needs reworking.

![authorized_landingpage](https://user-images.githubusercontent.com/31663028/101690760-b808d480-3a3b-11eb-9429-5873558e9a82.png)

**Comment by dorothyyeager** [comment]
@JonellaCulmer @kathycarothers We already have an audit report landing page at https://www.fec.gov/legal-resources/enforcement/audit-reports/ that we could copy/move language from. The three transition pages are linked from it, similar to what is already on the audit report landing page. I would recommend that the candidate and the PAC/party ones start with this paragraph:

_The Commission audits a committee when it appears not to have met the threshold requirements for substantial compliance with the _Federal Election Campaign Act_. The audit determines whether the committee complied with limitations, prohibitions and disclosure requirements._ 

And then the paragraph on the landing page that describes the type of committee could follow.

In addition, the Title 26 audit page should link to our page at https://www.fec.gov/help-candidates-and-committees/understanding-public-funding-presidential-elections/audits-repayment/ (like the main audit landing page does in the first sentence, which I would just crib). That H4CC page might have some language that could be cribbed for the title 26 audit report landing page. It will need to be updated eventually to link the Title 26 H4CC audit page.

As far as a title for the Title 26 page: "Audit reports for publicly funded presidential and host committees" makes sense to me and yes, link title on main landing page should be the same.

I agree with Jonella that we should be using the glossary a lot more on these pages. It might be good to have a page for House/Senate and PAC/Party like the one we have in H4CC for presidential committees to explain to them the audit process. cc @bmathesonFEC who worked on that page.

We should send a word document showing all changes to Audit (Erica/Dayna/Zuzana) for their review and comment.

p.s. I updated the transition links on the main audit report landing page.

**Comment by JonellaCulmer** [comment]
Updated pages based on today's convos. This is what will be presented to the audit team. 

### Authorized and unauthorized audit report landing pages
![authorizedauditlanding](https://user-images.githubusercontent.com/31663028/101828886-2911c000-3b00-11eb-99ec-22839f33776d.png)

### Title 26 audit report landing page
![title26auditlanding](https://user-images.githubusercontent.com/31663028/101828896-2d3ddd80-3b00-11eb-9b72-794378175c24.png)

**Comment by JonellaCulmer** [comment]
Overall design has been approved. Closing.
