### ISSUE TITLE
Create a design for the audit report individual pages

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4241]
### Summary

**What we're after:**
_Create a design for the audit report individual pages that will be based on existing templates for easier migration._

Confirm with Public Records when they started creating individual audit report .shtml pages. We presume it was in 2008, since the years prior are all linked to audit report PDF files.

### Completion criteria

- [x] Design for audit report individual pages are created and shared
- [ ] Get buy-in from public records/press

**Comment by JonellaCulmer** [comment]
Audit page mockup based on resource template

![Individualaudit_authorized](https://user-images.githubusercontent.com/31663028/101697749-5f8b0480-3a46-11eb-8f86-9582ec7f2c2f.jpg)

**Comment by JonellaCulmer** [comment]
Updated pages based on today's convos. This is what will be presented to the audit team.

### Immediate state for individual audit pages
![individualaudit_firststate](https://user-images.githubusercontent.com/31663028/101829145-8efe4780-3b00-11eb-9fb2-f5b212db78c6.jpg)

### Future state for individual audit pages
![indivaudit_futurestate](https://user-images.githubusercontent.com/31663028/101829154-932a6500-3b00-11eb-8175-92fa2cd218db.jpg)

**Comment by JonellaCulmer** [comment]
Overall design has been approved. Some lingering questions about header capitalization, but that can be handled in future tickets.
