### ISSUE TITLE
QA information architecture and navigation to Audit reports

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4242]
### Summary

**What we're after:**
_Make sure audit reports fits into our current information architecture and develop the best way to navigate to the reports. Ensure that all the paths identified in the first comment below still function as good ways to get to the content._

### Related issues

- #4240 

### Completion criteria

- [ ] Document final considerations for IA and Navigation
- [ ] Open a followup ticket to update the links identified to the new wagtail links

**Comment by JonellaCulmer** [comment]
There are presently three main ways to get to the audit report pages. 
- Through the global search
- Through the legal resources top-level navigation, clicking enforcement and scrolling to audit process (to audit report page) or starting an audit search. Is the audit process button noticeable?
- Through the legal resources top-level navigation, clicking all legal resources and scrolling to cards and clicking audits to get to audit reports page

Other audit-related pages that are out there:
- https://www.fec.gov/help-candidates-and-committees/understanding-public-funding-presidential-elections/audits-repayment/
- https://www.fec.gov/legal-resources/enforcement/audit-reports/understanding-presidential-primary-audit-report/
(Are any missing from the list?)

**Comment by JonellaCulmer** [comment]
Blocked while we wait for feedback from audit.

**Comment by JonellaCulmer** [comment]
Closing. We are not making changes now to the IA at this time.
