### ISSUE TITLE
Fix court case filenames with spaces

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4245]
### Summary

**What we're after:**
_S3 buckets are not able to serve up filenames with spaces. We'll need to rename the court case filenames to names without spaces. While we're renaming, it would be good to rename with more semantic naming so that these make more sense._

List of filenames with spaces under the content S3 path `https://www.fec.gov/resources/legal-resources/litigation/`. This is the location of the court case PDF files:

01 -- 02-1674jurisst[1].pdf
02 -- 02-1674&02-1675resptojs[1].pdf
03 -- 02-1674replytojurisst[1].pdf
04 -- 02-1674brief(final)[1].pdf
05 -- 02-1674_fec_brief(final)[1].pdf
06 -- 02-1674rbef(mcconnell)[1].pdf
07 -- 02-1675jurisst[1].pdf
08 -- 02-1674&02-1675resptojs[1].pdf
09 -- 02-1675brief[1].pdf
10 -- 02-1675replybrief[1].pdf
11 -- 02-1676jurisst[1].pdf
12 -- 02-1676_echols_merits(final)[1].pdf
13 -- 02-1676rbrief-echols(final)[1].pdf
14 -- 02-1702jurisst[1].pdf
15 -- merbrredacted-final02-1702[1].pdf
16 -- 02-1727jurisst[1].pdf
17 -- 02-1727&02-1733resptojs[1].pdf
18 -- 02-1727,02-1733,02-1753briefs (final)[1].pdf
19 -- 02-1727reply_brief_merits[1].pdf
20 -- 02-1733jurisst[1].pdf
22 -- 02-1733_brief_(final)[1].pdf
21 -- 02-1727&02-1733resptojs[1].pdf
23 -- 02-1733reply_brief[1].pdf
24 --- 02-1734jurisst[1].pdf
25 -- 02-1734,02-1755&02-1756resptojs[1].pdf
26 -- 02-1734briefmerits[1].pdf
27 -- 02-1734rbriefmerits[1].pdf
28 -- 02-1740jurisst[1].pdf
29 -- 02-1740merits-brief-final[1].pdf
30 -- 02-1740reply-brief[1].pdf
31 -- 02-1747jurisst[1].pdf
32 -- paul_brief_02-1747(final)[1].pdf
33 -- 02-1747reply_brief(final)[1].pdf
34 -- 02-1753jurisst[1].pdf
35 -- 02-1755jurisstl[1].pdf
36 -- 02-1734,02-1755&02-1756resptojs[1].pdf
37 -- 02-1755brief[1].pdf
38 -- 02-1755reply_brief[1].pdf
39 -- 02-1756jurisst[1].pdf
40 -- 02-1734,02-1755&02-1756resptojs[2].pdf
41 -- 02-1756merits-brief[1].pdf
42 -- 02-1756reply-brief[1].pdf
43 -- amcur-cato-inst(02-1674)[1].pdf
45 -- amcur-rodney-a-smith(02-1674)[1].pdf
44 -- amcur-states-of-va-et-al(02-1674)[1].pdf
46 -- amcur-amciv-rights-union(02-1674)[1].pdf
47 -- amcur_j_dennis_hastert(02-1674)[1].pdf
48 --- amicus-moshman[1].pdf
49 -- amcur_ctr_for_govt_studies(02-1674)[1].pdf
50 -- amcur_international_experts(02-1674)[1].pdf
51 -- amcur_interfaith_alliance(02-1674)[1].pdf
52 -- amcur_fred_thompson(02-1674)[1].pdf
53 -- cur_common_cause_and_aarp(02-1674)[1].pdf
54 -- amcur_center_for_responsive_politics(02-1674)[1].pdf
55 -- amcur_league_of_women_voters(02-1674)[1].pdf
56 -- amcur_aclu(02-1674)[1].pdf
57 -- amcur_ca_student_pub_int(02-1674)[1].pdf
58 -- amcur_comm_for_economic_dev(02-1674)[1].pdf
59 -- amcur_bipartisan_frmr_mem_usc(02-1674)[1].pdf
60 -- amcur_iowa(02-1674)[1].pdf
citizens_united_sc_08_ ameindbizalliance.pdf
citizens_united_sc_08_ bsac_publicgood.pdf
epstein_epstein_memo _of_pts_auth_opp_msj.pdf
odonnell_crew_ amicus.pdf

### Action items

- [x] Documented list of name changes for these filenames with spaces
- [x] Documented name changes are made on the content-s3
- [x] Follow up ticket created to redirect filenames with spaces from transition.fec.gov/law/litigation and www.fec.gov/resources/legal-resources/litigation/ to the new content-s3 under path `https://www.fec.gov/resources/legal-resources/litigation/`

### Technical consideration
- [x] defer to dev to rename as appropriate, e.g., semantically, automatically

### Completion criteria
- [x] Court case filenames with spaces are fixed

**Comment by zsmith-fec** [comment]
Hello Pat! I just finished renaming the files. The list is located in the [Court Case QA](https://docs.google.com/spreadsheets/d/1bsmTTUDTNr4Ay2AXP7SBSqM72zHpVJbPmhN2L9KRf6g/edit#gid=1728071194) spreadsheet under the tab "File Renaming Ticket #4245."

Please let me know what else you need me to do to close this ticket. :)

**Comment by patphongs** [comment]
Ticket to redirect filenames with spaces https://github.com/fecgov/fec-proxy/issues/226

**Comment by patphongs** [comment]
Thanks @zsmith-fec for working on this! I have updated the filenames and created a [follow-up ticket for redirects](https://github.com/fecgov/fec-cms/issues/4245#issuecomment-750455829). Here's also a [testing ticket](https://github.com/fecgov/fec-cms/issues/4291) for these names with spaces. We'll do the testing in the next sprint after it's deployed. 

I completion criteria in in this ticket have been satisfied, so I am now closing.
