### ISSUE TITLE
Get approved language & designs for audit report landing pages and individual audit pages

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4248]
### Summary

**What we are after:**
_We need to work with the Audit Division and Public Records to draft the text for the new Audit Report Landing pages mocked up in #4240 ._

### Related issues

See Audit pages sub-epic

### Completion criteria

- [x] Text for audit report landing pages is drafted ([look at this comment](https://github.com/fecgov/fec-cms/issues/4240#issuecomment-742519123))
- [ ] Approval by Public Records and Audit
- [x] open ticket for future training for audit and public records (needs to be conducted before we go live)https://github.com/fecgov/fec-cms/issues/4262

### Technical considerations
- [ ] agree on naming convention for individual audit page title, e.g., Marsha Blackburn for Congress (2016)
- [ ] agree on naming convention for audit landing page titles
- [ ] agree on introductory text for all audit landing pages titles
- [x] we should use 0-padded dates to produce MM/DD/YYYY formatting

**Comment by JonellaCulmer** [comment]
Update language is drafted (in Word for easy sharing) and will be shared with audit in the new year.

**Comment by dorothyyeager** [comment]
Closing. We reached agreement.
