### ISSUE TITLE
Draft audit page documentation 

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4255]
**What we're after:** As part of the migration of audit report pages to wagtail, we need to detail the necessary steps to make it easier for audit to create pages in the future. 

Considerations:
- [x] What kind of details are important for audit to know?
- [x] Should we include instructions/details on formatting and page templating?

**Completion criteria:**
- [x] Documentation is compiled in easily shareable/savable format for audit team

**Comment by patphongs** [comment]
Here's the [draft Wagtail documentation](https://docs.google.com/document/d/1XU8XpFa5vm7tVq6go88E-25KLc68ZIOaVvsHjbfTwSY/edit#heading=h.4qe21wf3uyhl) 🔒

**Comment by patphongs** [comment]
Draft documentation is complete. We still need to finalize the documentation by having a meeting with the Audit team. New ticket here: https://github.com/fecgov/fec-cms/issues/4273
