### ISSUE TITLE
Wagtail training with audit team

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4262]
**What we're after:**
We have written documentation that explains the process of building an audit report page and we need to know conduct a training session and go through that documentation with the audit team. 

**Draft audit page documentation:**
- https://github.com/fecgov/fec-cms/issues/4255 Draft audit page documentation

**Action items:**
- [x] Identify everyone who needs to attend
- [x] Schedule training

**Completion criteria:**
- [x] Training is conducted with all necessary audit staff

**Comment by patphongs** [comment]
Training with the Audit team is now complete.
