### ISSUE TITLE
Update the regulations page, the admin fines page and the E&J to add the 2021 fine inflation adjustments

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4279]
### Summary

What we are after:
Once the Commission approves the new fine inflation adjustments, there will be a FR notice updating the regulations for admin fines. We need to do the routine work of updating the regulations page and the E&J pages. We will use this notice to train Info Division and content team staff in how to update regulations and E&J pages.

### Completion criteria
 
- [x] FR notice (using SERS link) is added to https://www.fec.gov/legal-resources/regulations/ under "Changes to be included in 2022 edition"
- [x] FR notice (using SERS link) is added to the chronological index and to the citation indexes for the regulations mentioned in the notice.
- [x] Because this FR notice contains admin fines, need to add to legal citations box (using SERS link) of https://www.fec.gov/legal-resources/enforcement/administrative-fines/
- [ ] Text on this page is updated as Admin Fines specifies: https://www.fec.gov/legal-resources/enforcement/administrative-fines/calculating-administrative-fines/
- [ ] Work is demo'ed for Info and content team. (Done in demo)

**Comment by dorothyyeager** [comment]
Blocked until the FR notice comes out.

**Comment by dorothyyeager** [comment]
Chronological page updated at https://www.fec.gov/legal-resources/regulations/explanations-and-justifications/chronological-index-2020-2029-ejs/

Citation page updated at https://www.fec.gov/legal-resources/regulations/explanations-and-justifications/citation-index-part-111/ (Luckily, part 111 is the only part affected by this regulations change. I updated the page for each row that had an affected regulations).

Citation added to the Admin fines landing page.

Citation added to the Regulations landing page under "Changes in the 2022 printed edition." Confirming that with OGC, so this part is saved in draft.

**Comment by dorothyyeager** [comment]
Because of the timing of these docs, one of the two FR notices won't make it into the 2021 or 2022 printed edition, so we varied up the wording on the regulations page. OGC is OK with the way I worded it.

![image](https://user-images.githubusercontent.com/24437369/104238709-6337ef80-5427-11eb-8685-d5a1ae2d3852.png)

The notice is all linked now and we'll demo this as part of the 13.12 demo, so closing the ticket.

**Comment by dorothyyeager** [comment]
We also need to update the https://www.fec.gov/legal-resources/enforcement/administrative-fines/calculating-administrative-fines/ page with the FR notice and the new amounts. Thanks @djgarr

**Comment by djgarr** [comment]
I updated the 48 hour notice total and examples, but will need to update the other examples when Rhiannon sends the information

**Comment by djgarr** [comment]
Rhiannon sent me updates for the other 3 reporting examples. They got updated and published this morning.

**Comment by dorothyyeager** [comment]
We're reopening and assigning to @djgarr because there may be more edits coming.

**Comment by djgarr** [comment]
Additional information was updated on 1/14/21
