### ISSUE TITLE
(After 4/15/21) Implement default year change to 2022

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4280]
### Summary

**What we're after:**
_For the new year, we will want to change the default year across the CMS to 2022._

### Related issues

- #4159 

### Completion criteria

- Update default year to 2022

**Comment by lbeaufort** [comment]
In 2019, we [didn't change the default year to 2020](https://github.com/fecgov/fec-cms/issues/2640) until May 2019, since there won't be any data until the April quarterly reports.

**Comment by rfultz** [comment]
Should we increment things like `DEFAULT_TIME_PERIOD` values?

**Comment by patphongs** [comment]
Will probably need to hotfix this because the April quarterly filings will be coming in on 4/15, which means we need to have the 2022 cycle in place by that time.

**Comment by rfultz** [comment]
Not sure why this didn't close when its PRs did

**Comment by patphongs** [comment]
> Not sure why this didn't close when its PRs did

I think it's because we merged this into the release instead of develop branch.
