### ISSUE TITLE
Wagtail login issue

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4282]
### Summary

**What we're after:**
_Receive server error when trying to login to Wagtail_

<img width="1058" alt="Screen Shot 2020-12-22 at 1 15 29 PM" src="https://user-images.githubusercontent.com/31420082/102920141-22683e80-4458-11eb-8631-ca8e62163027.png">

It looks like there’s a breaking change in version 2.0.0 with the `PyJWT` package. 

> Drop deprecation warnings ([#515](https://github.com/jpadilla/pyjwt/pull/515))
> https://github.com/jpadilla/pyjwt/blob/master/CHANGELOG.md#v200
> https://pypi.org/project/PyJWT/2.0.0/#history. 

cloud.gov’s `cg-django-uaa` imports pyJWT here: https://github.com/cloud-gov/cg-django-uaa/blob/5347d5ab7e565d4c4cab91af1eda73f9d82861c4/setup.py#L102. 

New builds starting today (12/22) installed 2.0.0 instead of 1.7.1

**Completion criteria**
- [x] Fix it on our end by pinning `PyJWT` to 1.7.1
- [ ] Put in an issue for cloud.gov’s `cg-django-uaa` to https://github.com/cloud-gov/cg-django-uaa/blob/5347d5ab7e565d4c4cab91af1eda73f9d82861c4/setup.py#L102

**Comment by lbeaufort** [comment]
Hotfix deployed to production
