### ISSUE TITLE
Take down pages redirected in 13.9

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4286]
### Summary

**What we are after:**
_We are really getting things off of Transition._

### Related issues

_List any relevant related issue(s)_

- #4265 - testing ticket for 13.9 redirects

### Completion criteria

These files are removed from transition (or their previous removal is verified):

/eeo/AfricanHistoryMonth.shtml
/eeo/EEOCounselors.shtml
/eeo/eeocounselors.htm
/eeo/HispanicHeritageMonth.shtml
/eeo/LegalAuth.shtml
/eeo/MD-715Report.shtml
/eeo/NoFear.shtml

/pdf/cca.pdf

/press/bkgnd/EnforcementStatistics.shtml
/press/bkgnd/AllPublicFunds.xls

**Comment by rfultz** [comment]
Moving this to ready for others to verify that the files have been removed.

**Comment by djgarr** [comment]
It looks like these have all been removed. These links all redirect to either main pages on www or specific www pages
