### ISSUE TITLE
Put in Wagtail redirects for court case files that were renamed to take out spaces

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4287]
### Summary

**What we are after:**
_To finish fixing the file names with spaces issues, we'll need a good redirect for each of those files. @patphongs and I figured out we can do this via Wagtail (which means that a Wagtail admin (David, Kathy, Dorothy, Pat, John) will need to take this ticket)._

### Related issues

_List any relevant related issue(s)_

- #4245 (fix court case file names with spaces)

### Completion criteria

- [ ] Court case names with spaces (contact @patphongs for spreadsheet) are redirected in Wagtail.
- [ ] Wagtail redirects are tested and found working.

**Comment by patphongs** [comment]
Closing in favor of: https://github.com/fecgov/fec-proxy/issues/226
