### ISSUE TITLE
GA special runoff is showing up in the 2022 election search

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#4289]
The special runoff is showing up in both the 2020 and 2022 cycles. It should only show up for 2020. There is, however, a GA senate general election in 2022 so it's possible the label just and date need to be changed.

https://www.fec.gov/data/elections/?cycle=2020&state=GA
https://www.fec.gov/data/elections/?cycle=2022&state=GA

<img width="950" alt="Screen Shot 2020-12-23 at 12 45 19 PM" src="https://user-images.githubusercontent.com/31420082/103024028-0d091800-451d-11eb-8fd8-55de8587e232.png">

**Completion criteria**
- [x] Label for GA 2022 election should say "General election: November 8th, 2022" like other 2022 elections.

**Comment by johnnyporkchops** [comment]
@lbeaufort , I think this has been corrected:
https://www.fec.gov/data/elections/?cycle=2022&state=GA

<img width="1376" alt="Screen Shot 2021-01-13 at 9 59 37 PM" src="https://user-images.githubusercontent.com/5572856/104538930-c0c86980-55ea-11eb-97b0-63e6d1500e82.png">

**Comment by johnnyporkchops** [comment]
This problem is not persisting, so closing.
