### ISSUE TITLE
Research updates to election profile pages for reapportionment 

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#4290]
**What we are after**:
2022 searches of the election profile page return 2022 congressional districts.

**Why we are after it:**
To provide up-to-date ZIP code-to-congressional district searches for our users.

**Considerations**:
- Do we want to keep the congressional districts based on the 2010/2012 reapportionment/congressional districts
- Are there other places on the site that use congressional district maps?
    - survey site
    - If yes, these need to be updated to reflect 2022 changes

**Technical considerations**:
- We will need maps/boundary files for the new congressional districts

**Related to**:
https://github.com/fecgov/openFEC/issues/4727

Possibly helpful information from previous related task:
https://github.com/fecgov/fec-cms/issues/1942

**Completion criteria**:
- [ ] Document findings in this ticket  for questions above under "considerations"
- [ ] Cross reference any findings in related openFEC ticket that may be helpful to that ticket https://github.com/fecgov/openFEC/issues/4727
- [ ] Create implementation ticket with completion criterion : "2022 searches return 2022 congressional districts"

**Comment by patphongs** [comment]
Bumping due to resource constraints and data unavailability

**Comment by patphongs** [comment]
Closing in favor of this ticket: fecgov/fec-cms#4290
