### ISSUE TITLE
[Do on January 26] Banner work for January

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4298]
### Summary

**What we are after:**
Need to set up first few banners for the year the week of January 25.

### Completion criteria
- [x] Open meeting banner for January 28 
- [x] Year-End banner for January 31

**Comment by djgarr** [comment]
Updated the banner for the open meeting on 1/28/21. Waiting for Tips for Treasurers for YE Report

**Comment by djgarr** [comment]
Tips for Treasurers article was posted this morning. @kathycarothers added the information to the YE banner. Ticket should be good to go
