### ISSUE TITLE
Wagtail - Banners: Make Data inactive (expiration) date field optional

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4300]
### Summary

**What we are after:**
_For long-term banners, it's easy to forget when they expire. It would be better if we didn't have to fill out that field at all so we don't have a situation where a banner expires during a time when people are out (for example, the December holiday season)._

### Completion criteria

- [ ] Date inactive field is made optional (see screenshot)

![image](https://user-images.githubusercontent.com/24437369/103573863-f5c31680-4e9c-11eb-81e5-2f100ea6a310.png)

**Comment by johnnyporkchops** [comment]
@dorothyyeager If you want a banner to never expire, you can always just give it a date far in the future like 2035. My only concern with also having the option to leave it blank  is the more we keep updating the way the feature works, the more confusing it can get for both editors and developers.                               

For example, when we added the "Active" checkbox,  one could already make a  banner active/inactive by just publishing/unpublishing  it and that checkbox has occasionally led to some confusion. 

If we add more logic to make a banner  persist indefinitely if the `date inactive` field were left  blank, we would also want  to add more help-text to let editors know that is an option.   Like the "Active" checkbox we  would be adding another option for something that already exists. In addition to it possibly becoming more confusing for editors, the underlying logic seems unnecessarily complicated :

```
alert_banners = AlertForEmergencyUseOnly.objects.live().filter((Q(
        alert_active=True, alert_date_active__lte=datetime_now,
        alert_date_inactive__gt=datetime_now) | (Q(alert_active=True,alert_date_inactive__isnull=True)))).order_by('-alert_date_active')[:2]
```

**Comment by dorothyyeager** [comment]
Talked with @johnnyporkchops and content team just now. Because he's raised valid concerns about making the logic confusing, we'll go with the proposed workaround if @AmyKort @patphongs are OK with it (give us a thumbs up here).

Workaround for things like government shutdowns and COVID banners where we don't know end date: We'll set the "date inactive" field to **ten years** in the future. I'll document this in the "how to do banners" spreadsheet and instructions.

Reassigning ticket to me to get sign off and update the instructions. Thanks @johnnyporkchops for looking into this!

**Comment by johnnyporkchops** [comment]
Thanks @dorothyyeager. Maybe in an innovation sprint,  I would not mind working with content team to evaluate the  home page banner interface so that we can rename the fields in a way that makes more sense to editors and also add the options that work better for the way you actually use the feature. This might also include extending Wagtail to have more prominent and readable help-text.

**Comment by johnnyporkchops** [comment]
There is also this ticket regarding active/inactive dates that makes me think we should evaluate the functionality from scratch and see how we can accommodate the way content team schedules home banners
https://github.com/fecgov/fec-cms/issues/4022

**Comment by dorothyyeager** [comment]
I'll make sure these tickets are in our Content epic planning doc-might be a good sub-epic for the Content team and you to pair on in future.

**Comment by johnnyporkchops** [comment]
That sounds great @dorothyyeager , thanks!

**Comment by dorothyyeager** [comment]
Closed. We'll do our workaround and that's been added to the spreadsheet and instructions for banners.
