### ISSUE TITLE
Add Reporting Example link to H4CC All Compliance Resources Page

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#4301]
### Summary

In 13.11 we created and published a landing page for all Reporting Examples. As part of that ticket the Content Team discussed a possible location where we would like to add a link to new Reporting Example page on the site.

#4218 - Create landing page for all reporting examples.

### Placement of Link to New Page
The proposed home of the link to the full list of reporting examples is the Help For Candidate and Committees [All Compliance Resources Page](https://www.fec.gov/help-candidates-and-committees/)   >   You might also like   >   Get help from an FEC analyst:

![image](https://user-images.githubusercontent.com/33758291/103575307-83a00100-4e9f-11eb-92e7-31f53099509b.png)

### Completion criteria

- [ ] Reporting examples link added to H4CC All Resources Page

**Comment by bmathesonFEC** [comment]
Reporting examples page is live: https://www.fec.gov/help-candidates-and-committees/reporting-examples/

**Comment by dorothyyeager** [comment]
This is one that content team can do and ask @patphongs to review.  Let me know if you want to pair @bmathesonFEC. Would be great to get it done this sprint and put in the 13.11 release.
