### ISSUE TITLE
Update Audit Reports datatable title to title casing

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4302]
**What we're after:** It's been determined that "Audit Reports" is a term of art and therefore requires the title on relevant datatable to be updated to title casing. 

Datatable link: https://www.fec.gov/legal-resources/enforcement/audit-search/
https://www.fec.gov/legal-resources/enforcement/audit-reports/

**Completion criteria:**
- [ ] Title case Audit Reports datatable page title

**Comment by rfultz** [comment]
A list of places I've found "audit report" in the repo:
- The formal name for the first of the OIG report types (constants.py, 146:1)
- Description of Open Meetings in the calendar where it's lower case in a sentence. (calendar-helpers.js 77:138)
- Title of the Audits datatable (datatable-audit.js 31:25)
- Transition pages json. Not sure how it's used but all six occurrences are Title Case (transition_pages.json)
- Multiple migration files
  - 0083_auto_20170506_0059.py is the most recent to define the documentpage and resourcepage models
  - 0034_auto_20161221_1920.py is the most recent to define the pressreleasepage/PressReleasePage model
