### ISSUE TITLE
Candidate profile page: Do not show committees if there are none

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4303]
### Summary

**What we're after:**
_We should remove committee information from the about this candidate section of the candidate profile page if there are no linked committees._

#### Current state
![Screen Shot 2021-01-04 at 3 33 44 PM](https://user-images.githubusercontent.com/12799132/103584675-c538a800-4eaf-11eb-9ae7-35d381bbfd00.png)

#### Desired state
![Screen Shot 2021-01-04 at 5 10 19 PM](https://user-images.githubusercontent.com/12799132/103584695-cec21000-4eaf-11eb-8d60-08dc48615f22.png)

### Technical considerations
Add a condition like this: 
`{% if committee_groups['P'] or committee_groups['A'] or committee_groups['J'] | length > 0 %}`

### Completion criteria

- [ ] Committee information is removed from the candidate profile page if there are no linked committees

**Comment by pkfec** [comment]
In about this candidate section --> under committees : The current logic checks if the committee designation is either one  of  P, A or J type then the committee information is displayed. There is no check on the  heading `committees` and the heading displays by default.
