### ISSUE TITLE
Take down pages redirected in 13.10

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#4309]
### Summary

**What we're after:**
We are really getting things off of Transition.

### Related issues

- #4291 Test redirects deployed in 13.10

### Completion criteria

These files are removed from transition (or their previous removal is verified):

/law/litigation_CCA_Alpha.shtml
/law/litigation_CCA_A.shtml
/law/litigation_CCA_B.shtml
/law/litigation_CCA_C.shtml
/law/litigation_CCA_D.shtml
/law/litigation_CCA_E.shtml
/law/litigation_CCA_FEC_A.shtml
/law/litigation_CCA_FEC_D.shtml
/law/litigation_CCA_FEC_K.shtml
/law/litigation_CCA_FEC_N.shtml
/law/litigation_CCA_FEC_P.shtml
/law/litigation_CCA_FEC_Q.shtml
/law/litigation_CCA_FEC_T.shtml
/law/litigation_CCA_F.shtml
/law/litigation_CCA_G.shtml
/law/litigation_CCA_H.shtml
/law/litigation_CCA_I.shtml
/law/litigation_CCA_J.shtml
/law/litigation_CCA_K.shtml
/law/litigation_CCA_L.shtml
/law/litigation_CCA_M.shtml
/law/litigation_CCA_N.shtml
/law/litigation_CCA_O.shtml
/law/litigation_CCA_P.shtml
/law/litigation_CCA_R.shtml
/law/litigation_CCA_S.shtml
/law/litigation_CCA_T.shtml
/law/litigation_CCA_U.shtml
/law/litigation_CCA_V.shtml
/law/litigation_CCA_W.shtml
/law/litigation_CCA_X.shtml

**Comment by rfultz** [comment]
Moving this to ready for others to verify that the files have been removed.

**Comment by djgarr** [comment]
It looks like these files have been removed. All these links redirect to the alphabetical court case page
