### ISSUE TITLE
Make "Audit Report" title case in titles in Wagtail-editable pages

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4310]
### Summary

**What we are after:**
We've decided along with the Audit Division that "Audit Report" is a term of art that should be title cased.

### Related issues

- #4302 - Similar front-end issue for hard-coded pages

### Action items
- [ ] Use global search to identify pages in H4CC, legal resources, etc. that use the word "Audit report" 
- [ ] On those pages, change "Audit report" or "audit report" to "Audit Report"

### Completion criteria

- [ ] "Audit Report" uses title case in all Wagtail-editable pages on fec.gov
- [ ] Add it to content guide (Publicly Financed Committee Audit Report)

**Comment by patphongs** [comment]
Closing since we are not doing this for previously created pages.
