### ISSUE TITLE
Remove recently migrated transition pages from global search

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4324]
We'll have some recently migrated pages on transition that are being removed and we don't want them to come up on the site search. Right now the index is using this to find which pages to index for transition: https://github.com/fecgov/fec-cms/blob/develop/fec/search/management/data/transition_pages.json.

### Completion criteria

- [x]  Take a look at transition site and make a list of pages we want to add to the global site search as well as pages that could be deleted. [LIST IS HERE](https://docs.google.com/document/d/1vIC_QGpDDqZL7E0qI-tlRLqhHWROLoRkNGVlnr1sREc/edit) Content has looked at this list, and all transition pages on it. can be deleted.
- [x]  Add/Delete items from transition_pages.json, and scrape. (Front-end)
- [x]  We need to run a manual delete of items we want removed from the index using this documentation: http://gsa.github.io/slate/#delete-a-document (Front-end)

### Completion criteria

The only thing being indexed from the transition site is the Audit Reports. (Everything else has been migrated)

**Comment by patphongs** [comment]
This is now complete

**Comment by patphongs** [comment]
Forgot that the PR needs to be merged before closing this issue.
