### ISSUE TITLE
Events and deadlines are missing on homepage

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4332]
### Summary

_Items under events and deadlines are missing from the homepage._

A 403 is presented on the homepage for those calendar events.

![Screen Shot 2021-01-19 at 5 00 32 PM](https://user-images.githubusercontent.com/12799132/105098417-04eabc80-5a78-11eb-93dc-80b8453841fa.png)

**Comment by lbeaufort** [comment]
PR deployed to production on 1/19/21
