### ISSUE TITLE
Banner work for 14.1

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4341]
### Summary

**What we are after:**
_Content team is going to have routine sprint ticket for banner work each sprint to make sure we're on top of it._

### Related 

[Banner spreadsheet](https://docs.google.com/spreadsheets/d/1MPGmgOFg-pjlkYZHUl28thVd1IPCQEmsseg7idH5ThU/edit?usp=sharing)
[Banner How to](https://docs.google.com/document/d/1Ehq3sxa6WXzLWf1UdwnbLIsKNTcCnSHIECcPYfWWhC4/edit?usp=sharing)

### Completion criteria

Banners set up for:
- [x] Open meeting of [February 25](https://www.fec.gov/updates/february-25-2021-open-meeting/) and administrative review hearing- will use "today's events" banner; set up by February 24
- [x] If needed: any change in status doc that may happen

**Comment by djgarr** [comment]
Banner set up for 2/25. Need to follow up with Commission Sec's Office for a question about times listed
