### ISSUE TITLE
Banner work for 14.6 (May 4 - 17)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4346]
### Summary

**What we are after:**
_Content team is going to have routine sprint ticket for banner work each sprint to make sure we're on top of it._

### Related 

[Banner spreadsheet](https://docs.google.com/spreadsheets/d/1MPGmgOFg-pjlkYZHUl28thVd1IPCQEmsseg7idH5ThU/edit?usp=sharing)
[Banner How to](https://docs.google.com/document/d/1Ehq3sxa6WXzLWf1UdwnbLIsKNTcCnSHIECcPYfWWhC4/edit?usp=sharing)

### Completion criteria

Banners set up for:
- [x] Open meeting of [May 6](https://www.fec.gov/updates/may-06-2021-open-meeting/) - set up by May 5
- [x]  Notice of availability to be published in FR. Waiting on OGC to give us add comment link for pending rulemaking page. We'll need to keep this banner in rotation through July 2nd at midnight. For now, we'll need to make it expire at 7:29am May 6, and reappear at May 6 at 5:31 pm to expire 7:29 am May 20 (date of the next open meeting)
- [x] If needed: any change in status doc that may happen  (including updating the admin fines spreadsheet)

**Comment by djgarr** [comment]
Updated banners for open meeting on 5/6 and the NOA

**Comment by djgarr** [comment]
Banner updated to amend text and add safety workplace document
