### ISSUE TITLE
Banner Work for PI14 innovation (May 18 - June 7)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4347]
### Summary

**What we are after:**
_Content team is going to have routine sprint ticket for banner work each sprint to make sure we're on top of it._

### Related 

[Banner spreadsheet](https://docs.google.com/spreadsheets/d/1MPGmgOFg-pjlkYZHUl28thVd1IPCQEmsseg7idH5ThU/edit?usp=sharing)
[Banner How to](https://docs.google.com/document/d/1Ehq3sxa6WXzLWf1UdwnbLIsKNTcCnSHIECcPYfWWhC4/edit?usp=sharing)

### Completion criteria

Banners set up for:
- [x] Open meeting of [May 20](https://www.fec.gov/updates/may-20-2021-open-meeting/) - set up by May 19 - meeting canceled on 5/18
- [x] Update NOA banner to go off 7:30 am May 20 and return May 21 at 5:31 pm. 
- [ ] If needed: any change in status doc that may happen

**Comment by djgarr** [comment]
Set the NOA banner to come down in favor of the Open Meeting banner

**Comment by djgarr** [comment]
Meeting canceled. Unpublished meeting banner

**Comment by djgarr** [comment]
NOA banner set to come down on 6/10 (date of next commission open meeting) at 7:29am.

**Comment by djgarr** [comment]
No more banner updates during innovation
