### ISSUE TITLE
Research adding tracking/tags to the RAD analyst form (and others) to identify errors

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4352]
**What we're after:** We need to explore adding trackers to the RAD form to better understand the errors that occur repeatedly in order to make future enhancements.

**Action items:**
- Decide what we are tracking

**Completion criteria:**
- [ ] Look into how the current RAD(+) forms work, what would be involved in tracking different error states (GTM may be a challenge. Can we use custom events; look into RAD validation? Do we need to adjust form validation functionality, etc.?)
- [ ] Create any follow-up do-the-work tickets to add Trackers/tags to RAD(+) form fields to identify reoccurring error states

**Comment by patphongs** [comment]
Bumping to 16.1 due to resource constraints
