### ISSUE TITLE
Add validation and improve error messages for RAD analyst form

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4354]
**What we're after:** Following design work, we need to now implement several improvements to the RAD analyst form. These improvements are included in the action items. With these improvements we can make it easier for the regulated community to complete the form and correct any errors before submitting. In the event user still encounter errors, we will improve those as well to account for the potential mistakes that can still occur. 

Further still, we will attempt to track the kinds of errors we're seeing in order to make future improvements. That work will happen here: https://github.com/fecgov/fec-cms/issues/4352 

**Action items:**
- [x] Add inline validation for each required field. We should be careful not to trigger validation when the user has not yet reached that field, or are prompted with the validation before they've had a chance to finish.
  - **Text fields (First name, Last name and Question):** The validation should be triggered when an attempt is made to complete the form but nothing is entered. If the user attempts to submit the form with the field blank, prompt that page to scroll to the first error that needs completion or correction. Similar to the behavior of the current tooltip messages.
  - **Email field:** A proper email without a valid email that includes a username, @ and domain, will trigger immediately after an attempt is made. Clicking or tabbing outside the field, or attempting to submit the form will trigger the validation
  - **Committee name or ID:** A valid committee has not been selected from the list of committees. The validation will trigger if the field is left blank or an invalid name is included. 
  - **Subject field:** A selection of nothing other than Choose a subject will trigger the validation, only after an attempt has been made or the user attempts to submit the form without having made a choice.
  - **"I agree" field:** Should be triggered if the user attempts to submit the form without checking the box. 
- [x] Update error messages to add explainer text. Image below with updated text. 
- [x] Update error message to provide next steps like the success message. Image below with buttons.
- [x] Update success message to include additional language about confirmation email. Image below with updated text.
- [x] Make display of error states consistent. Technical solution: create single error message for both possible errors. Or maintain separate error messages that display in the exact same way. Right now we have two error messages that display in two different places. 
- [x] Address page refresh issue after receiving error. Hitting refresh on the page, results in the following message appearing at the top of the browser. Hitting continue does not refresh the page and the error is still present. I have to leave the page entirely and come back to it to start the form over again.

<img width="540" alt="Screen Shot 2021-01-22 at 3 11 51 PM" src="https://user-images.githubusercontent.com/31663028/105540595-761eaf80-5cc4-11eb-80c1-c640bb7da098.png">

- [x] Update Submit button language to "Submit your question"

- [x] Add padding between fields to allow for the new validation messages to fit without running into other components of the form
- [x] Remove tooltip error states

### RAD form
![Updated-RAD-contact-form-with-validation.png](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/805fb93b-e568-43ea-a5be-b0ad7a05860d)

### Success message
<img width="553" alt="Screen Shot 2021-01-22 at 6 29 23 PM" src="https://user-images.githubusercontent.com/31663028/105560185-24385280-5ce1-11eb-8264-9a7f02fb77f1.png">

### Error message. 
Can be as a single message or separate messages, pending any technical limitations with either solution.  

<img width="796" alt="Screen Shot 2021-01-22 at 6 40 16 PM" src="https://user-images.githubusercontent.com/31663028/105560261-4fbb3d00-5ce1-11eb-8c57-7f18bc3c266a.png">

**Comment by bmathesonFEC** [comment]
@johnnyporkchops and I had a quick chat about the RAD Contact Form after I asked if I could delete a test entry that he submitted through the form. In that conversation I referenced the fact that we're currently running a Customer Service Satisfaction Survey for RAD and in that survey I ask questions about the RAD Contact Portal. These are the questions we're asking, I'll let you know if there's any useful feedback for you when the survey period closes at the end of next week.

1. Are you aware that you can submit questions in writing to your Campaign Finance Analyst through FEC.gov's contact form?
- Yes (jumps to question 3 then 4)
- No (proceeds to question 2, then skips 3 and 4)

2. FEC.gov now offers a feature allowing filers registered with the FEC to submit written questions to your assigned Campaign Finance Analyst. www.fec.gov/help-candidates-and-committees/question-rad/ After completing and submitting the form, you will get an email response from your committee's Campaign Finance Analyst at the email address you provide within 3 business days. For immediate assistance, this page also provides a feature to look-up the name and direct phone number to your assigned Campaign Finance Analyst using your Committee ID Number. Is this a feature you would consider using in the future?

3. Have you used FEC.gov's contact form to submit a question to your Campaign Finance Analyst?
- Yes
- No

4. After receiving the email response from your Campaign Finance Analyst, do you feel your needs were met?
- Yes
- No
- NA
- This question has a comment box and it may be the place where I'd get feedback about the form.
