### ISSUE TITLE
Add links from committee profile pages to candidate profile pages.

### ISSUE THREAD

**Issue by fec-jli** [fecgov/fec-cms#4361]
### Summary
Currently, we only show Leadership PAC sponsor name on about-committee section in committee profile page and don't have the link to candidate profile page.
ex: http://www.fec.gov/data/committee/C00764878/?cycle=2020&tab=about-committee
So this ticket will add the link to candidate profile page.

### Related issues
[https://github.com/fecgov/fec-cms/issues/4270](https://github.com/fecgov/fec-cms/issues/4270)
[https://github.com/fecgov/fec-cms/pull/4358](https://github.com/fecgov/fec-cms/pull/4358)

### Action items
- [ ] Add link on Leadership PAC sponsor name to corresponding candidate profile page.

<img width="705" alt="Screen Shot 2021-02-02 at 2 56 00 PM" src="https://user-images.githubusercontent.com/24395751/106655844-e43a6080-6567-11eb-9717-9db96abb7985.png">

**Comment by JonellaCulmer** [comment]
@fec-jli @patphongs @PaulClark2 Any objections to mimicking the box style for sponsoring candidates they way we have for authorizing candidates? 

Example: https://www.fec.gov/data/committee/C00431445/?cycle=2012&tab=about-committee
<img width="600" alt="Screen Shot 2021-02-02 at 3 21 06 PM" src="https://user-images.githubusercontent.com/31663028/106657989-b73b7d00-656a-11eb-86f5-376910118f8b.png">

**Comment by PaulClark2** [comment]
@JonellaCulmer I don't have any objections.

**Comment by JonellaCulmer** [comment]
@fec-jli Please see the below mockup. @dorothyyeager Let me know if you have any objections/suggestions to replace "Committee sponsor:"
<img width="803" alt="Screen Shot 2021-02-02 at 4 42 40 PM" src="https://user-images.githubusercontent.com/31663028/106666583-caa01580-6575-11eb-841f-2097ddea8e26.png">

**Comment by dorothyyeager** [comment]
@JonellaCulmer That wording works for me. Thanks!
