### ISSUE TITLE
Redirect old reporting example pages and investigate why newer ones aren't in global search

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4364]
### Summary

**What we're after:**
Three reporting examples that were moved around in Wagtail are 404'ing in the global search.

![image](https://user-images.githubusercontent.com/24437369/106920601-41095880-66d9-11eb-96df-68d09ce4a39d.png)

### Related issues

- #4223 - next manual global search index

### Completion criteria

- [x] The URLs in the photo don't 404
- [ ] After #4223 is done, test to see what comes up for "bitcoin" makes sense, is the latest URL, and doesn't 404.

**Comment by dorothyyeager** [comment]
@djgarr put in Wagtail redirects to fix the 404 error. The bigger question is why the indexing from December didn't pick up these pages:
https://www.fec.gov/help-candidates-and-committees/reporting-examples/bitcoin-contributions/
https://www.fec.gov/help-candidates-and-committees/reporting-examples/bitcoins-investment/
https://www.fec.gov/help-candidates-and-committees/reporting-examples/liquidating-bitcoins/

Hopefully whoever takes on #4223 can look out and ensure these three pages get indexed. @bmathesonFEC we couldn't find the three pages in the photo above in Wagtail, did they just get moved to reporting-examples?

**Comment by djgarr** [comment]
The redirects are working properly. Two sets of results for the same bitcoin page (one the correct page and one the redirected page), but everything is redirecting properly
