### ISSUE TITLE
Retire the library

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4371]
### Summary

**What we are after:**
_We are getting off of transition and need to retire the library (https://transition.fec.gov/general/library.shtml) since the contents of the library have all been migrated._

### Completion criteria
- [x] Info Division and Public Records are given a heads up (by @AmyKort)
- [x] Library is retired and redirected to https://www.fec.gov/introduction-campaign-finance/how-to-research-public-records/.
- [x] Links to the library are removed from any pages on fec.gov

**Comment by kathycarothers** [comment]
Email sent to Public Records for them to remove the link on https://www.fec.gov/introduction-campaign-finance/how-to-research-public-records/individual-contributions/

**Comment by kathycarothers** [comment]
Jason removed the link from the Public Record pages. We are good for bullet point number three.
