### ISSUE TITLE
Improve customer experience and address security issues by building an agency-wide contact form

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4377]
**What we're after:** Explore a contact form for the remainder of the agency. One that builds on the analyst form, or creates a new one for the rest of the agency to use. We currently receive communications via email. But with continued phishing attempts through email it's getting harder and harder to tell the difference between legitimate and fake email requests. 

We should consider a contact form that addresses this security concern and at the same time helps to better facilitate requests and ensure they go to the right office the first time. 

**Action items:**
- [x] Look into the LOE of either building on top of or building new contact form for the rest of the agency
- [x] Think through some of the user flow to determine what the form could/should include/do

**Completion criteria:**
- [ ] Compile research findings, make recommendations and open any followup tickets as necessary

**Comment by JonellaCulmer** [comment]
@bmathesonFEC @patphongs @AmyKort My intention with this work is to provide a simple form to answer questions from the people who need our help. Using reCaptcha to weed out bots and spam. By proxy, I'm hoping we can also reduce the number of phishing emails received each day. 

Using ServiceNow as a starting point, I wanted to pick your brains about the feasibility of incorporating other offices, with email addresses on the [contact page](https://www.fec.gov/contact/), into this form.

**Comment by JonellaCulmer** [comment]
While I wait to have more conversations on this topic, we've discussed starting the form with just those divisions that are already in ServiceNow and building from there.

**Comment by JonellaCulmer** [comment]
6/7 email addresses mentioned on the contact page have received multiple phishing/spam emails.

**Comment by JonellaCulmer** [comment]
Based on conversations with those familiar with ServiceNow, we seem to be in great shape for creating a new form and have correspondence go through that service. It's just a matter of making space for that work. We're not on a specific timeline for completion but this work will be picked back up when time allows.

**Comment by JonellaCulmer** [comment]
Next steps for this:
- Offices that currently use ServiceNow for email/correspondence 
  - RAD, Info, Public Records, Congressional Affairs(?), Press(?) who else? 
  - Other email addresses to add webmanager and APIinfo
- Map out what the form would do
- Get preliminary access to ServiceNow to better understand the system

@bmathesonFEC Can you help @dorothyyeager and I with the first and third items on this list?

**Comment by JonellaCulmer** [comment]
@patphongs @PaulClark2 @AmyKort 
Here's a link to the prototype I demo'ed today. It is not pixel perfect and there are definitely things I can improve. But, generally, as a concept, is this something you want to proceed with?

https://invis.io/3812YD5HUQMK#/469046235_Main

**Comment by patphongs** [comment]
> is this something you want to proceed with?

Thank you @JonellaCulmer for your great work on this and the interactive mock-up. This is a great start and I would like to proceed with it. As @rfultz mentioned, we should also take a look at accessibility related questions if we move to this model. Just to make sure all users can get to what they need with this form.

**Comment by JonellaCulmer** [comment]
Closing in favor of accessibility ticket: https://github.com/fecgov/fec-cms/issues/5367
