### ISSUE TITLE
Select 2021-2022 from data table filters

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#4378]
What we are after
Users should be able to select 2021-2022. 

Why we are after it
Users should be able to filter by 2021-2022

I only checked https://www.fec.gov/data/filings/ and https://www.fec.gov/data/reports/pac-party/

![image](https://user-images.githubusercontent.com/11817734/107644376-5b958180-6c45-11eb-83b7-149a7af7ff3d.png)
![image](https://user-images.githubusercontent.com/11817734/107644482-7b2caa00-6c45-11eb-93a6-87bb93ddb164.png)

**Comment by lbeaufort** [comment]
Hotfix deployed to production 2/18/21
