### ISSUE TITLE
Take down migrated transition directories and follow up others

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4380]
### Summary

**What we are after:**
_Getting off of transition._

The content and front end teams went through the transition directory (we got about halfway so we'll need to pick this up again) and identified some items that need migration and some other directories, that are no longer needed, redirect properly. This ticket is to take down the directories we no longer need off of transition.

### Completion criteria
- [x] List of contents of /em/enfpro folder provided for content team to verify if redirects are in place (if they are, we'll add to list below)
- [x] Old web disclaimer internet examples sent to content team and @jjonesfec for archiving if ever needed again. (After this is done, add related folders to list below)
- [x] Directory /images/ sent to content team and @jjonesfec for archiving. (We'll not take this one down yet to avoid breaking image links we aren't aware of.)
- [x] This folder sent in a zip file to Information Division (@djgarr and Liz) /info/ElectionDate 
- [x] These directories are removed from transition:
- /ans/
- /audio/
- /common/
- /documents/
- /fecig/
- /general/documents/
- /info/conference_materials
- /info/conferences
- /info/ElectionDate/

### Future work

We have some related follow-up tickets for migration of other content we found. We also will have another meeting to pick up with the info/ directory on.

**Comment by patphongs** [comment]
@dorothyyeager @kathycarothers Here's the list of documents still left in `/em/enfpro`:

- https://transition.fec.gov/em/enfpro/Enforcement_Matters_(Updated_2_20_2018).pdf
- https://transition.fec.gov/em/enfpro/enforcestatsfy06-08.pdf
- https://transition.fec.gov/em/enfpro/enforcestatsfy09-10.pdf
- https://transition.fec.gov/em/enfpro/Enforcement_Matters_Updated_2_20_2018.pdf
- https://transition.fec.gov/em/enfpro/enforcestatsfy03-08.pdf
- https://transition.fec.gov/em/enfpro/enfpro2005.pdf
- https://transition.fec.gov/em/enfpro/complistatsfy05-08.pdf
- https://transition.fec.gov/em/enfpro/enforcestatsfy1975-2018.pdf
- https://transition.fec.gov/em/enfpro/enforcestatsfy1975-2019.pdf

**Comment by kathycarothers** [comment]
@patphongs @dorothyyeager We do not have redirects in place for all these documents: 

•	https://transition.fec.gov/em/enfpro/Enforcement_Matters_(Updated_2_20_2018).pdf no redirect in place 
•	https://transition.fec.gov/em/enfpro/enforcestatsfy06-08.pdf no redirect in place 
•	https://transition.fec.gov/em/enfpro/enforcestatsfy09-10.pdf redirect 
•	https://transition.fec.gov/em/enfpro/Enforcement_Matters_Updated_2_20_2018.pdf no redirect in place 
•	https://transition.fec.gov/em/enfpro/enforcestatsfy03-08.pdf redirect 
•	https://transition.fec.gov/em/enfpro/enfpro2005.pdf redirect 
•	https://transition.fec.gov/em/enfpro/complistatsfy05-08.pdf redirect 
•	https://transition.fec.gov/em/enfpro/enforcestatsfy1975-2018.pdf no redirect in place 
•	https://transition.fec.gov/em/enfpro/enforcestatsfy1975-2019.pdf no redirect in place

**Comment by kathycarothers** [comment]
@pat Dorothy and I are going to research the links that are not redirecting. Sorry, I thought I had posted this earlier.

**Comment by dorothyyeager** [comment]
We will need to redirect the ones with no redirect to this page: https://www.fec.gov/legal-resources/enforcement/enforcement-profile/. We'll make a redirect ticket for 14.1 and add them to it. cc: @kathycarothers @patphongs (Sorry other Pat.)

**Comment by kathycarothers** [comment]
I have created a new ticket #4423 for the redirects. I am closing this ticket out.
