### ISSUE TITLE
Hold meeting to go through the rest of the transition inventory in 14.1

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4381]
### Summary

**What we are after:**
In #4380 we held a meeting and made a plan for a lot of transition folders. There's still a lot more to go through! So we need another meeting.

[Redirect spreadsheet](https://docs.google.com/spreadsheets/d/1vzN-wZlS8K8ZyfExSV3hwXDenDEN9KyyAUJFTI6OjKU/edit?usp=sharing) - see tab marked "Transition Inventory"

### Related issues

- #4380 Take down transition directories
- #3755 Get pages/brochures off transition - make a plan

### Completion criteria

- [x] Meeting is held with content and front end
- [x]  Implementation tickets made

**Comment by kathycarothers** [comment]
A meeting is scheduled for 2/25 @ 11 am

**Comment by kathycarothers** [comment]
Need to hold another meeting. It will take place on March 10.

**Comment by kathycarothers** [comment]
I have created a new ticket since this is an ongoing project. We stopped at execsum.htm in the inventory list.
