### ISSUE TITLE
Review technical review conducted for IT modernization

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4402]
**What we're after:**
As part of our work to eventually shut down EQS and SAOs, we need to review the current features. Starting with a review of the technical review conducted as part of the ongoing IT modernization effort. This review included conversations and artifacts from product owners and stakeholders and should contain valuable information. 

**Resources:** Artifacts in FEC IT Modernization Confluence. 
[Application assessments](https://fecgov.atlassian.net/wiki/spaces/FIMFDR/pages/549158927/Searchable+Legal+Systems+Assessments)
[Application analysis](https://fecgov.atlassian.net/wiki/spaces/FIMFDR/pages/482836694/Searchable+Legal+Systems)

**Completion criteria:**
- [x] Review and compile takeaways from the technical review

**Comment by JonellaCulmer** [comment]
There's not much information in the IT documentation that will help with the shutdown of legacy systems EQS and SAOS. 

EQS:
- Very few comments about the UI for EQS

SAOS: Questions for PMs (@PaulClark2 @AmyKort @patphongs) Are the below comments within the scope of this epic?
- When we shutdown SAOS in favor of an improved .gov AO search, is it our intention to pull straight from the database and bypass any internal SAOS system. Since that seems to just be the front-end display for the public accessing AOs? 
- A delay in documents appearing on .gov has been experienced by internal staff. Will the migration address this, or later, if/when we get documents and data straight from internal systems, as mentioned in my previous comment, speed things along? I believe this will be crucial in our shutdown of SAOS - documents appearing without any observable delay.

**Comment by PaulClark2** [comment]
@JonellaCulmer we would only be shutting down the public facing part of the system. There's a user interface FEC staff use to enter data and publish. 

>When we shutdown SAOS in favor of an improved .gov AO search, is it our intention to pull straight from the database and bypass any internal SAOS system, since it seems to just be the front-end display for the public accessing AOs?

Someone that knows this system better than I do should probably answer this. My understanding is that FEC.gov currently pulls data from the same database (perhaps it's transferred to PG first) as the legacy front-end. I don't think shutting down the legacy front-end changes that. 

>A delay in documents appearing on .gov has been experienced by internal staff. Will the migration address this, or later, if/when we get documents and data straight from internal systems, as mentioned in my previous comment, speed things along? I believe this will be crucial in our shutdown of SAOS - documents appearing without any observable delay.

At first there will be no difference. The current move to a cloud environment will be a lift and shift. The architecture of SAOS including its database will continue to function as it does now.

**Comment by JonellaCulmer** [comment]
Closing this ticket in favor of a future research ticket to look into possible AO lag: https://github.com/fecgov/openFEC/issues/4798
