### ISSUE TITLE
Review previous comments and update ADR/AF mockups

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4403]
**What we're after:**
We need to review previous comments submitted to the website team from ADR/AF team as well as previous research. After the review we should make updates to the design mockups as necessary and annotate with explanations and comments. Code is currently available under a CMS feature flag. 

@JonellaCulmer will look through her emails from 2018 to find comments from the ADR/AF team.

This is a great pairing opportunity with a developer(s) to ensure that the (new) proposed features are technically possible. 

**Completion criteria:**
- [ ] Research and ADR/AF comments are reviewed and mockups are updated, including annotations (with technical considerations accounted for)

**Comment by patphongs** [comment]
Noting this to correct in the code when we update the ADR CMS canonical page template.

I discovered that `subjects` is displayed based on a condition of if `respondents > 1`. We actually want to display subjects if `subjects > 0`. Otherwise, `Subject = no subject`. Should fix this in the code here:

https://github.com/fecgov/fec-cms/blob/c088aa83ca003a1548027c1ae65dd597f9972f31/fec/legal/templates/legal-adr.jinja#L41

**Comment by JonellaCulmer** [comment]
@AmyKort @patphongs @lbeaufort 

Requested changes from ADR and status of making that change:
- Remove subject from the summary:
  - It was requested that subject be removed until updates to Law Manager had been made. Those updates have since occurred, so we should be able to include them. Subject is already in the API. Need to discuss with content what the page should say in the event that there is still no subject. No subject? It needs to explain the absence of the information without sounding like something broke along the way. cc: @dorothyyeager @djgarr @kathycarothers 
- Change complainant to Referral office:
  - Easy change on the front-end, but it requires a better understanding of the originating data. The data containing the referral office currently comes to the API as a disposition along with multiple other items. At this point, it would be very difficult to distinguish one disposition from another to move it to referral office instead. Scheduled following conversation to go through Law Manager to get more information.
- Remove citations from disposition:
  - This was also requested to be removed until updates to Law Manager had been made. Those updates have since occurred, so we should be able to include them. Need to confirm that it's in the originating data and possibly make changes to the API.
- Add non-monetary term to the disposition:
  - Need to get a better understanding of the originating data. Currently, the data comes through with duplicate dispositions but with different respondents. That makes it difficult to make it clean on the front-end and display only the relevant information in one view. 

Confusion from research
- What's the difference between the two dispositions:
  - Merge the two dispositions into one section

**Updated ADR page mockups:**
![ADR Canonical_update1](https://user-images.githubusercontent.com/31663028/109972166-050be800-7cc5-11eb-8c95-8afe570e26ea.jpg)



**Updated AF page mockups:**
(Not shown to AF office prior to today, so no feedback from them. Still endeavored to make improvements after conversations with Jennie, who has a better understanding of the data)
![AF Canonical_update1](https://user-images.githubusercontent.com/31663028/109972525-67fd7f00-7cc5-11eb-82db-5f25dd4e68a6.png)

**Comment by JonellaCulmer** [comment]
Based on followup conversation with Jennie, @patphongs and @lbeaufort, here are some updates to my previous comment.
- Remove subject from the summary:
  - Subject is in the API and would require a simple front-end change. We can mention this to the ADR team and see whether this is still something they'd rather we leave out. 
- Change complainant to referral office:
  - This would require modifications on the contractor-side that we don't believe is readily feasible. Opening a research ticket to verify whether or not it's an APIU change or a contractor change.
- Remove citations from disposition:
  - For now, we are going to remove from this from the page. This would require modifications on the contractor-side that we don't believe is readily feasible. Opening a research ticket to verify whether or not it's an APIU change or a contractor change.
- Add non-monetary term to the disposition:
  - This would require modifications on the contractor-side that we don't believe is readily feasible. Opening a research ticket to verify whether or not it's an APIU change or a contractor change.

**Comment by JonellaCulmer** [comment]
@patphongs I'm still concerned about the display for the disposition. Particularly for the duplicate dispositions for each respondent. What do you think about that issue?

Here's an updated mockup:
![ADR Canonical_update2](https://user-images.githubusercontent.com/31663028/110038893-66a47480-7d0e-11eb-8d6b-c55c82d5daf9.jpg)

**Comment by dorothyyeager** [comment]
@JonellaCulmer Regarding what to say to "no subject" - that's kind of weird that there would be no subject (without a subject, there wouldn't be a case). You might be able to go with a generic "Administrative review" for an ADR case or "Filing deadline" for an AF case. All AF cases will be about filing deadlines (and not meeting them on time). ADR cases will vary by topic though.

**Comment by JonellaCulmer** [comment]
@dorothyyeager They are some ADRs in EQS currently that don't have subjects. But that's an option too, but not as specific as some of the other subjects that are available like "allocation."

**Comment by dorothyyeager** [comment]
@JonellaCulmer I'm not strongly wedded to having a generic subject or no subject. ADR cases are usually pretty minor stuff. If we want a precise subject for each case, for those with no subject, we'll need to read the case, see what it was about, and arrange to plop in a subject into EQS.

**Comment by JonellaCulmer** [comment]
@dorothyyeager Thanks. That's helpful. That can be a point of conversation with the ADR team as well. I don't want to leave it blank. Either we fix those areas where it was left out, or explain why one doesn't exist.

**Comment by JonellaCulmer** [comment]
Based on a conversation with @patphongs, (in response to [this comment](https://github.com/fecgov/fec-cms/issues/4403#issuecomment-790987452)) we're going to need to better understand the way that the data is consolidated into the front-end. Right now, though, what I identified as a possible problem is not a problem.

**Comment by JonellaCulmer** [comment]
Closing this ticket in favor of #4446 and #4438.
