### ISSUE TITLE
Compile list of all security and incident response documentation

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4404]
**What we're after:** 
Find out what the universe of documentation will be and pair with content team for help in scoping. Prioritize what needs to be documented and add completion criteria to review and update those smaller tickets. 

**Action items:**
- [x] Look across all locations/sources for documentation: wikis, github readme, google docs, etc

**Completion criteria:**
- [x] Universe of documentation is compiled and documented

**Comment by patphongs** [comment]
List of documentation is being compiled [here](https://docs.google.com/document/d/1lRn_lfsphAxi5_MN8kDS8c04grb2jjFrg943Cf0XUMw/edit#heading=h.6v1i0hukuor) 🔒

**Comment by patphongs** [comment]
Compiled list of documentation has been distributed to the team for review and this is now complete.
