### ISSUE TITLE
[March] - Manually update wagtail global search index

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4417]
## Summary
**What we're after:**
We need to update the global search.gov index for new pages that were published in March

Related issues
#4223 

Completion criteria

- [ ] Follow instructions under [Adding CMS pages to the index](https://github.com/fecgov/fec-cms/blob/develop/fec/search/management/instructions.md#adding-cms-pages-to-the-index)
- [ ] Create ticket for April manual Wagtail global search index

**Comment by rfultz** [comment]
Unable to see document totals. Waiting for a response from search.gov

~Last indexed page count: 1553 (indexed on 2/23/2021).
New indexed page count: XXXXXX (indexed on 3/25/2021)~

Created new ticket to scrape and index the pages for April https://github.com/fecgov/fec-cms/issues/4514

**Comment by patphongs** [comment]
Search.gov has acknowledged the bug and will be working on a fix in the future. Closing this issue as the indexing is complete.
