### ISSUE TITLE
Modify top raising/spending candidates chart on homepage and by the numbers pages to default to Senate candidates

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4418]
**What we're after:**
Top raising/spending candidates on homepage is currently showing presidential candidates. Senate candidate data is more relevant at this time so we should switch to those candidates instead. 

**Completion criteria:**
- [ ] By default, the top spending/candidate data should be Senate data on homepage and by the numbers pages

**Comment by rfultz** [comment]
This was solved with gitflow merges yesterday
