### ISSUE TITLE
Transition clean up: /info/notices

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4430]
### Summary

**What we're after:**
_As we continual move to migrate from the transition.fec.gov website, we are removing content that is no longer needed and redirected to its new home on www.fec.gov._

**Action items:**
- [x] Upload https://transition.fec.gov/info/notices/2005/notice_2005-05.pdf to Wagtail. Also add link in the E&J tables.
- [x] Redirect https://transition.fec.gov/info/notices/2005/notice_2005-05.pdf to Wagtail uploaded copy.
- [x] Redirect https://transition.fec.gov/info/notices/2005/notice_2005-07.pdf to Wagtail uploaded copy here: https://www.fec.gov/resources/cms-content/documents/fedreg_notice_2005-07.pdf
~- [ ] Once redirects are in place, delete /info/notices/2005 folder from transition.~
- [x] Find the equivalent for this: https://transition.fec.gov/info/notices/2006/alprim.shtml on www.fec.gov. Then make a redirect for it. If it is no longer needed, we should delete.
~- [ ] Once redirects are in place, delete /info/notices/2006 folder from transition.~
- [x] Testing ticket is created for 14.4

### Completion criteria

- [x] `/info/notices/2005/` has been redirected (deleting is a follow-up ticket)
- [x] `/info/notices/2006/` has been redirected (deleting is a follow-up ticket)
- [x] follow-up ticket for deletion has been created

**Comment by dorothyyeager** [comment]
Merged, so closing. We'll test these in #4520.
