### ISSUE TITLE
Take down transition and older s3 bucket files redirected in 14.1 release

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4435]
### Summary

**What we are after:**
_These files can be taken down off of transition as redirects were put in place during 14.1._

### Related issues

- #3936 - Public Records pubrec/ redirects
- #4382 - Innovation sprint redirects

### Completion criteria

- [x] These files are removed from transition
/law/legalconsideration.shtml
/law/litigation.shtml
/law/policy.shtml
/pubrec/, including:
/pubrec/alpha.htm
/pubrec/chrono.htm
/pubrec/staterec.shtml
/pubrec/stateelection.shtml
/pubrec/cfl/ (all files)

- [x] These files are removed from the S3 bucket (accessible replacements uploaded into CMS)
/resources/foia/brgoals.pdf
/resources/foia/chieffoiareport2014.pdf
/resources/foia/chieffoiareport2013.pdf
/resources/foia/chieffoiareport12.pdf
/resources/foia/chieffoiareport11.pdf
/resources/foia/chieffoiareport09.pdf
/resources/foia/foiareport2012.pdf
/resources/foia/foiareport2011.pdf
/resources/foia/foiareport2010.pdf
/resources/foia/foiareport2009.pdf
/resources/foia/foiareport2008.pdf
/resources/foia/foiareport2007.pdf
/resources/foia/foiareport2006.pdf

**Comment by patphongs** [comment]
Files have been deleted
