### ISSUE TITLE
Draft security documentation

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4439]
**What we're after:**
Start drafting the security documentation in google docs with github markup. Add edits to the documentation as needed. TTS, 18F, and cloud.gov documentation have been good examples for us. We may want to continue using their documentation as a template for our own. 

Often asked for this information by security personnel, having a live link would be valuable for them. 

**Related issues:**
- [x] https://github.com/fecgov/fec-cms/issues/4404 Compile list of all security and incident response documentation

**Action items:**
- [x] Based on list of security documentation, identify gaps in security documentation and necessary improvements.
- [x] Utilize TTS, 18F and cloud.gov documentation as a guide
- [x] Include security practices (ATO documentation), security incident response and workflow
- [ ] 

**Completion criteria:**
- [x] Update security documentation is drafted and circulated for review from @lbeaufort, content team and devs
- [x] Followup ticket(s) are opened, as needed, to refine the documentation based on review

**Comment by patphongs** [comment]
First draft has been made, follow-up ticket to continue to refine and have team give comments. [Draft 1](https://docs.google.com/document/d/1Ggb7u7JfK2r4Of8sG5oTytoE82CYcYL81_1CiBBJ0fE/edit) 🔒
