### ISSUE TITLE
Fix broken agenda pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4447]
**What we're after:**
These agenda pages are broken. We're not sure where they are in space right now, but this ticket is to fix these broken links. 
https://transition.fec.gov/agenda/2016/agenda20160128.shtml
https://transition.fec.gov/agenda/2012/agenda20120712.shtml
https://transition.fec.gov/agenda/2010/agenda20100615.shtml

**Action items:**
- [x] Links to these meetings were previously corrected. ~Need to determine whether these pages are in wagtail, or if they need to be recreated. ~ They are in Wagtail but dates were changed for various reasons. Fixing with redirects.
~- [ ] Grab the classic compressed file and see if we can find those three agenda files~

**Completion criteria:**
- [x] Links to these three pages are no longer broken or 404
- [ ] Redirects merged and added to testing ticket for 14.2 redirects.

**Comment by patphongs** [comment]
The https://transition.fec.gov/agenda/2010/agenda20100615.shtml should link to this agenda: https://www.fec.gov/updates/june-16-2010-open-meeting/

**Comment by dorothyyeager** [comment]
Noting that the 2012 meeting is now at https://www.fec.gov/updates/july-12-2012-canceled-open-meeting/. We'll probably need to put in a redirect.

Still hunting for the 2016 one.

**Comment by dorothyyeager** [comment]
And I just found it!
The meeting at https://transition.fec.gov/agenda/2016/agenda20160128.shtml should be redirected to https://www.fec.gov/updates/february-11-2016-open-meeting/

I'll add the three redirects to our 14.2 redirect spreadsheet and put in a PR to redirect them.

**Comment by dorothyyeager** [comment]
PR was merged; closing.
