### ISSUE TITLE
Modify committee profile page to display active, terminated and administratively terminated

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#4465]
**What we are after**
We need to make a distinction between terminated and administratively terminated committees. On the committee profile page we need to be able committees: 'terminated,' 'administratively terminated' or 'active.'

**Example**
This committee was administratively terminated. We would like to make a distinction between terminated and administratively terminated committees. 
![image](https://user-images.githubusercontent.com/11817734/110531108-2b78bb80-80e9-11eb-969b-5357fbe77e27.png)

**Back-end work** (potentially)
https://github.com/fecgov/openFEC/issues/4800

**Pairing**
David G. is interested in paring on this work.

**Tech steps**
- [x] Check whether `is_active == False && filing_frequency == 'A' ? Administratively terminated : Terminated` solves the need
- [x] Verify that the typeahead icons in global search and data landing page's candidate/committee search are unaffected (green only for Active) (and make sure the search for Calendar and Legal are using the same code/functionality)

**Completion criteria**
- [x] Ask Content and/or RAD if we should use `Administrative termination` or `Administratively terminated` or something else. 
- [x] Display agreed upon `Administratively terminated`, `Terminated`, or `Active` as appropriate
- [x] "Administratively terminated" will use the grey icon

**Comment by patphongs** [comment]
Backend modifications are no longer necessary: https://github.com/fecgov/openFEC/issues/4800, https://github.com/fecgov/openfec/issues/4809
