### ISSUE TITLE
Rename `FEC_DIGITALGOV_KEY` env var

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#4467]
digitalgov is now search.gov.

- [x] Rename `FEC_DIGITALGOV_KEY` env var to ~`SEARCHGOV_SITEWIDE_KEY`~ SEARCHGOV_API_KEY
- [x] Update comment here: https://github.com/fecgov/fec-cms/blob/66ea4d806f1379b98c379eb0ae2c337adb447de2/fec/home/templatetags/filters.py#L71 per https://github.com/fecgov/fec-cms/pull/4452#pullrequestreview-606799413
- [x] Look for other references
- [x] Add instructions for setting env vars for running the sitewide and policy guidance search locally to ~README.md~ instructions.md (Currently need `FEC_DIGITALGOV_KEY` and `SEARCH_GOV_POLICY_GUIDANCE_KEY`

**Completion criteria:**
- [x] `FEC_DIGITALGOV_KEY` is now named ~`SEARCHGOV_SITEWIDE_KEY`~ SEARCHGOV_API_KEY
- [x] `SEARCH_GOV_POLICY_GUIDANCE_KEY` is updated in the ~README.md~ instructions.md 
- [x]  Test update wagtail global search index script (https://github.com/fecgov/fec-cms/issues/5294)
- [ ]  Update the cloud.space with the new environment variables before these changes gets merged/deployed

**Comment by pkfec** [comment]
`digitalgov` will be replaced with `searchgov` in the following files:

1. [fec/search/utils/search_indexing.py](https://github.com/fecgov/fec-cms/blob/6ebd8317056c960fc61761e7f53ac0387f595112/fec/search/utils/search_indexing.py)
2. [fec/search/tests/test_indexing.py](https://github.com/fecgov/fec-cms/blob/6ebd8317056c960fc61761e7f53ac0387f595112/fec/search/tests/test_indexing.py)
3. [fec/fec/settings/base.py](https://github.com/fecgov/fec-cms/blob/b69f24b426928fbd2c4c0c6f616d18f0400423cf/fec/fec/settings/base.py)
4. [fec/search/management/instructions.md](https://github.com/fecgov/fec-cms/blob/b10fe9da5d223488025bb0a3baa59e2c1e865bec/fec/search/management/instructions.md)
5. [fec/search/management/commands/index_pages.py](https://github.com/fecgov/fec-cms/blob/6ebd8317056c960fc61761e7f53ac0387f595112/fec/search/management/commands/index_pages.py)
6. [fec/search/views.py](https://github.com/fecgov/fec-cms/blob/6ebd8317056c960fc61761e7f53ac0387f595112/fec/search/views.py)
7. [fec/search/management/commands/scrape_transition_pages.py](https://github.com/fecgov/fec-cms/blob/6ebd8317056c960fc61761e7f53ac0387f595112/fec/search/management/commands/scrape_transition_pages.py)
8. [fec/search/management/commands/scrape_web_app_pages.py](https://github.com/fecgov/fec-cms/blob/6ebd8317056c960fc61761e7f53ac0387f595112/fec/search/management/commands/scrape_web_app_pages.py)
9. [fec/search/management/commands/scrape_cms_pages.py](https://github.com/fecgov/fec-cms/blob/6ebd8317056c960fc61761e7f53ac0387f595112/fec/search/management/commands/scrape_cms_pages.py)
10. [fec/home/templatetags/filters.py](https://github.com/fecgov/fec-cms/blob/b9583f911dde62141279301525f6be203a0a3dc8/fec/home/templatetags/filters.py)
11. [fec/fec/static/js/modules/typeahead.js](https://github.com/fecgov/fec-cms/blob/6ebd8317056c960fc61761e7f53ac0387f595112/fec/fec/static/js/modules/typeahead.js)

**Comment by pkfec** [comment]
The following environment variables needs to be updated in cloud.gov environments:

| Digitalgov  | Searchgov|
| ------------- | ------------- |
|DIGITALGOV_DRAWER_HANDLE| SEARCHGOV_DRAWER_HANDLE |
|DIGITALGOV_DRAWER_KEY|SEARCHGOV_DRAWER_KEY |
|FEC_DIGITALGOV_KEY| SEARCHGOV_KEY |
|SEARCH_GOV_POLICY_GUIDANCE_KEY | SEARCHGOV_POLICY_GUIDANCE_KEY |
