### ISSUE TITLE
After March 30 (14.2 release): Test redirects implemented in 14.2 release

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#4475]
### Summary

**What we are after:**
_We need to test the redirects merged into the 14.2 release._

### Related issues

_List any relevant related issue(s)_

- #4471 (library and items from the inventory list) 
- #4371 (Library) 
- #4447 3 broken agenda pages
- 2018 Enforcement Matters broader redirects 

### Completion criteria - see https://github.com/fecgov/fec-cms/issues/4475#issuecomment-810453297 below

- [x] Redirects work 
- [x] Wagtail or www redirects put in if needed
- [ ] Pages/files put into a take-down ticket.

**Comment by dorothyyeager** [comment]
I've added the pages we can take down to #4490 since that ticket was still open.

We need to fix two of the transition redirects and put in www redirects for the three agenda pages. I will put in PRs for that.

**Comment by dorothyyeager** [comment]
For @patphongs - I looked at the transition redirects and I can't figure out why these two redirects aren't working. The coding for them looks correct. I have added Wagtail redirects for them but that didn't work. Could you take a look?

https://transition.fec.gov/info/contrib.htm
https://transition.fec.gov/info/elecmas.htm

Also, I put in a PR to www redirect the three agenda files and tagged you to review. Wagtail redirect for them did not work. I suspect there's a broader transition redirect for agenda documents.

**Comment by dorothyyeager** [comment]
Closing since above redirects merged. We'll need to test and also if working, delete some Wagtail redirects. I've added to the 14.3 redirect testing ticket at #4520 .
