### ISSUE TITLE
Add Reporting Examples to Party H4CC Pages

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#4479]
### Summary

In an effort to provide additional and helpful information to page visitors, these pages were identified as pages under the Party H4CC umbrella that could possible use reporting examples added to them. 

### Related issues

- #4385 

### Completion criteria

- [x] Add reporting examples to the following pages:

-  https://www.fec.gov/help-candidates-and-committees/registering-political-party/national-party-accounts-certain-expenses/
-  https://www.fec.gov/help-candidates-and-committees/handling-political-party-loans-debts-and-advances/advances-personal-funds/

**Comment by bmathesonFEC** [comment]
Working with RAD's Party Non-Party Branch to draft examples with images.

**Comment by bmathesonFEC** [comment]
Kicking this to 15.4 after speaking with the RAD analyst who is helping me with this task.

**Comment by bmathesonFEC** [comment]
Received drafts for the national party accounts pages. After brainstorming with the analyst who completed the work we decided to break this out into two separate reporting examples, one for the the reciepts side and another for the expenditure side.

A draft for advances should be coming today and I will start work:
- getting images to Jim Jones
- creating the wagtail pages
- distributing for Content team review

**Comment by bmathesonFEC** [comment]
To elaborate on the decision made above: the reporting advice is very similar across the different accounts, but more different receipts vs. disbursements. As a result, we decided to create one receipts example that covers all of the accounts and a separate disbursements example to cover all of the accounts. Once published these examples will be linked by referencing each other with Reporting Examples cards.

Created two wagtail pages:
- National party receipts for presidential nomination convention, headquarters, and recount accounts
- National party disbursements for presidential nomination convention, headquarters, and recount accounts

Images drafts are with @jjonesfec.

Once images are updated these examples will be distributed to reviewers.

**Comment by bmathesonFEC** [comment]
Received images, created wagtail pages for National Party Accounts, sent back to the original author for review and sent an image edit back to Jim.

Re: Advance of Personal Funds. Decided to create these as Form 3X examples that will work for PACs and Parties. Like the F3X Bitcoin examples these examples will be under the All Reporting Example parent (as opposed to the Filing PAC or Party Reports page). Submitted images to be created for the Advance examples.

**Comment by bmathesonFEC** [comment]
Moved to blocked while I wait for images, image edits, then for Content Team/RAD review.

**Comment by bmathesonFEC** [comment]
Just received images from Jim. I will build these pages this afternoon and distribute to reviewers. As a result, I'm moving this out of "blocked" back to in progress in 15.5.

**Comment by bmathesonFEC** [comment]
These page drafts are complete, they drafts are with the RAD Party Non-Party Branch for their second round of review. Once I hear back I'll distribute to the Content Team so we can publish the examples.

Moving to "blocked" while I wait for a response from RAD.

**Comment by bmathesonFEC** [comment]
Incorporated feedback into the example drafts, distributed them to the Content team for review this morning. If there's any chance the Content Team puts eyes on these today, I will publish the examples and update the guidance pages with Reporting Example Cards.
