### ISSUE TITLE
Hold a meeting: Convert Custom Page Template Party Pages on H4CC to Resource Page Templates

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#4480]
### Summary

After inventorying the party pages in H4CC, we noticed that a number of the pages were long and, in their current custom page template, required a lot of scrolling a searching to get to certain pieces of information. In an effort to make some of our information easier to locate on the page, we determined that a number of pages that could utilize the resource template. 

### Related issues

- #4385 
- #4479 

### Completion criteria

Convert the following pages into resource template pages:

- [ ] Types of contributions to party committees: https://www.fec.gov/help-candidates-and-committees/taking-receipts-political-party/contributions-party-committees/ (create a resource template page using page's content first, then compare it to similar page in candidate section (https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/types-contributions/) to see if information should be blended together with candidate page)
- [ ] Who can and can't contribute to a party committee: https://www.fec.gov/help-candidates-and-committees/taking-receipts-political-party/who-can-and-cant-contribute-party-committee/ (create a resource template page using page's content first, then compare it to similar page in candidate section (https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/who-can-and-cant-contribute/) to see if information should be blended together with candidate page)
- [ ] Donations of Levin funds to state and local party committees: https://www.fec.gov/help-candidates-and-committees/taking-receipts-political-party/levin-funds-political-party-committees/
- [ ] Volunteer activity for party committees: https://www.fec.gov/help-candidates-and-committees/taking-receipts-political-party/volunteer-activity-party/
- [ ] Permissible use of corporate/labor resources and facilities by party committees: https://www.fec.gov/help-candidates-and-committees/taking-receipts-political-party/permissible-use-corporatelabor-resources-and-facilities-party-committees/ (determine if we should separate communications and facilities into separate pages. cross check with candidate versions. coordination could use a button to those pages)
- [ ] Exempt party activities: https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/exempt-party-activities/
- [ ] Coordinated party expenditures: https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/coordinated-party-expenditures/ (decide how much of the coordination section to keep vs. adding a button/link to the coordination page)
- [ ] Making independent expenditures as a political party committee: https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/making-independent-expenditures-political-party-committee/ (decide how much of the coordination section to keep vs. adding a button/link to the coordination page)
- [ ] Definition of Federal Election Activity (FEA) | https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/definition-federal-election-activity-fea/

**Comment by dorothyyeager** [comment]
Leaving open until these are broken into separate tickets.

**Comment by kathycarothers** [comment]
We will need to schedule a meeting to break this ticket down into smaller tickets.

**Comment by kathycarothers** [comment]
Closing to break into 3 separate tickets.

**Comment by dorothyyeager** [comment]
Reopening to link the tickets it has split off to:
https://github.com/fecgov/fec-cms/issues/4771 - The simple ones that are just converting to resource template, 15.4
