### ISSUE TITLE
Update Joint Fundraising Page for Party Committees 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#4485]
### Summary

While going through and completing an inventory of the party H4CC pages, we determined that a few pages needed to have some content added or amended. The pages noted below need updates. The updated information or discussed updates are noted in parentheses.

### Related issues

- #4481 
- #4385 

### Completion criteria

- [x] Change link on https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/ for Joint fundraising by political party committees (https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/joint-fundraising-political-party-committees/) to point instead to https://www.fec.gov/help-candidates-and-committees/making-disbursements/joint-fundraising-candidates-political-committees/ (**_should this be moved out of the candidate section/breadcrumb??_YES**) and add Levin Fund information noting that it pertains to party committees only.
- [x] Add https://www.fec.gov/help-candidates-and-committees/making-disbursements/joint-fundraising-candidates-political-committees/ link to the Nonconnected "Making disbursements" section.
- [x] Main joint fundraising page is moved to main level of H4CC
- [x] Party joint fundraising page is unpublished and redirected to main joint fundraising page
- [x] Redirects in Wagtail are put in place for old URL to new URL
- [x] Redirects in www and proxy are updated with new URL

**Comment by dorothyyeager** [comment]
I've added the joint fundraising link to the fundraising links at https://www.fec.gov/help-candidates-and-committees/making-disbursements-pac/#day-to-day-operations-for-a-nonconnected-pac

![image](https://user-images.githubusercontent.com/24437369/117027537-cb5a5c00-acca-11eb-9700-ca99a1df3bee.png)

**Comment by dorothyyeager** [comment]
After checking with @patphongs, it would be good to move the joint fundraising page up a level since the content affects all committees, not just candidates. I'll update the steps/completion criteria accordingly.

Content team is looking at the draft Levin fund paragraph now.

**Comment by dorothyyeager** [comment]
I've moved the joint fundraising page to https://www.fec.gov/help-candidates-and-committees/joint-fundraising-candidates-political-committees/. Redirects are in place in Wagtail. PRs submitted to update joint fundraising redirects to point to the newly moved page.

Testing ticket for the redirects is #4600 

This ticket can be closed once the related PRs are merged.

**Comment by dorothyyeager** [comment]
PRs merged, so closing. We'll test redirects in #4600 after May 25.
