### ISSUE TITLE
Continue to draft security and incident response guide

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4487]
## Summary
Continue to draft the documentation for security and incident response guide to make sure it is clear, thorough and complete. 

## Completion criteria
- [x] [Draft 2](https://docs.google.com/document/d/1KLJnvH68gB7K5fcY-TrkJYmdeBJ9mZCGrKiJPv15x4E/edit#) 🔒  is completed

**Comment by patphongs** [comment]
Draft 2 is now complete. Moving on to have team review in 14.6: #4516
