### ISSUE TITLE
14.3 Transition pages to take down (Pages redirected in 14.1 and 14.2)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4490]
### Summary

**What we are after:**
_We are getting off transition. The files listed in this ticket have been successfully redirected to new homes and can be taken down safely._

### Related issues

_List any relevant related issue(s)_

- #4423 Redirects from 14.1
- #4433 Testing redirects from 14.1
- #4475 14.2 redirects/testing

### Completion criteria

- [x] Pages in this list are removed from transition

/em/enfpro/Enforcement_Matters_Updated_2_20_2018.pdf
/em/enfpro/EnforcementProfile.shtml
/em/enfpro/enforcestatsfy06-08.pdf
/em/enfpro/enforcestatsfy1975-2018.pdf
/em/enfpro/enforcestatsfy1975-2019.pdf

/foia/quarterly/ (entire directory and contents)

/general/library.shtml

/info/contriblimits0708.pdf
/info/contriblimits0910.pdf
/info/contriblimits1112.pdf
/info/contriblimitschart1314.pdf
/info/contriblimitschart1516.pdf 
/info/contriblimitschart1718.pdf
/info/efnprm.htm

- [x] This page is removed from S3 bucket: /resources/legal-resources/enforcement/audits/2016/Friends_of_Erik_Paulsen/5OGC-DFAR1357376.pdf

**Comment by rfultz** [comment]
@dorothyyeager @kathycarothers @djgarr these should all be gone now—ready for your confirmation!
