### ISSUE TITLE
Update Bitcoin reporting examples: line numbers

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#4492]
### Summary
OGC identified an issue with the reporting advice on the advice presented in Bitcoin liquidation reporting examples. The current advice presented on the site in the reporting example matches the reporting advice provided in [AO2014-02](https://www.fec.gov/updates/ao-2014-02-campaign-may-accept-bitcoins-as-contributions/); however, concerns have been raised about how the reporting advice may lead to confusing disclosure of Bitcoin Exchanges as direct contributors to committees.

Form 3X reporting examples: https://www.fec.gov/help-candidates-and-committees/reporting-examples/liquidating-bitcoins/
Form 3 reporting example: https://www.fec.gov/help-candidates-and-committees/filing-reports/liquidating-bitcoins/

### Completion criteria

- [x] get updated images from @jjonesfec 
- [x] create draft with updated line numbers, distribute draft to review group for approval (OGC, RAD, content team)
- [x] Publish updated version of the examples

**Comment by dorothyyeager** [comment]
@bmathesonFEC - see my message on Slack

**Comment by bmathesonFEC** [comment]
Received updated image from Jim. Working on draft language this afternoon.

**Comment by bmathesonFEC** [comment]
Distributed drafts to OGC, RAD, and the website content team for review.

The key decision here was how to incorporate the _Miscellaneous Receipts_ approach to disclosing liquidated bitcoin to an unknown purchaser when AO2014-02 outlines reporting instructions for itemizing the liquidation on line 11ai. We settled on a _Recommended_ + _Alternative_ headings to preserve the advice laid out in the AO but also provide advice that will prevent bitcoin exchanges from appearing as contributions on website searches.

**Comment by bmathesonFEC** [comment]
Marked as blocked pending external review. Not all parties were onboard with the _Recommended_ + _Alternative_ approach that was presented in the draft. As a result we are consulting the Information Division about how to present an alternative approach to reporting that is not specifically outlined in AO2014-02.

**Comment by bmathesonFEC** [comment]
After receiving approval from OGC the updated pages have been published:

Liquidating Bitcoins:
Form 3X filers: https://www.fec.gov/help-candidates-and-committees/reporting-examples/liquidating-bitcoins/
Form 3 filers:  https://www.fec.gov/help-candidates-and-committees/filing-reports/liquidating-bitcoins/
