### ISSUE TITLE
Update regulations page when 11 CFR 2021 comes out

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#4510]
### Summary

**What we are after:**
_As a user, I like to have the most recent edition of the 11 CFR so I have the current rules available._

### Completion criteria

- [x] Regulations page at https://www.fec.gov/legal-resources/regulations/ is updated with links to the 2021 CFR in all the different formats to be provided once available at https://www.govinfo.gov/app/collection/cfr/2021/ or https://www.govinfo.gov/bulkdata/CFR
- [x] Information on the 2021 printed edition is deleted. (We'll need to add 2022 version if any final rules are published in the Federal Register in 2021, so we might want to have a placeholder sentence there like "Changes to the 2021 printed edition will be posted here.")
- #4331 (Technical corrections)

**Comment by patphongs** [comment]
Waiting for new regulations for 2021, moving forward for now

**Comment by dorothyyeager** [comment]
Still waiting. We filed a ticket with GPO and were told it's coming. https://github.com/usgpo/bulk-data/issues/82

**Comment by dorothyyeager** [comment]
Still waiting as of June 14.

**Comment by dorothyyeager** [comment]
This is still not available as of 8/3.

**Comment by dorothyyeager** [comment]
The data was made available 8/11.

**Comment by dorothyyeager** [comment]
I've updated the regulations page. There are some wrinkles with what's leftover that I want to check in with OGC, @patphongs  and @bmathesonFEC on before closing the ticket.

**Comment by dorothyyeager** [comment]
We need to hear back from OGC on the one question about the page before we can close this out.

**Comment by dorothyyeager** [comment]
OGC confirmed that the technical correction we note on the regs page did not make it into the 11 CFR 2021 version. So we will leave that note up until otherwise notified by them to take down.

@pkfec  This means you can parse e-regs without worrying about further changes other than the ones we noted in your ticket.

And it means I can close this ticket; we are all updated now for 2021 on the cms side.
