### ISSUE TITLE
Hold meeting to go through the transition inventory 14.6

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#4512]
### Summary

In #4380 , #4381, #4469, we held meetings and made a plan for a lot of transition folders. There's still a lot more to go through! So we need another meeting.

Redirect spreadsheet - see tab marked "Transition Inventory"

### Related issues

#4469 Hold a meeting to go through the transition inventory 14.3 
#4381 Hold a meeting to go through the transition inventory 14.1 
#4380 Take down transition directories
#3755 Get pages/brochures off transition - make a plan

### Completion criteria

- [x] Meeting is held with content and front end to go over the inventory list picking up after interior_template 
- [x] Spreadsheet updated to reflect meeting
- [x] Redirect ticket created.
- [x] Take down ticket created

### Future work

Schedule a new meeting, fill out redirect excel sheet and create a  redirect ticket.

**Comment by patphongs** [comment]
Moving to 14.6 since content team will be fairly busy in 14.5.

**Comment by djgarr** [comment]
Had a Content conversation. We figured it could happen in 14.5 afterall. We want to keep prioritizing getting content off transition.

**Comment by kathycarothers** [comment]
The meeting is scheduled for next Tuesday 5/11.
