### ISSUE TITLE
[April] - Manually update wagtail global search index

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4514]
## Summary
**What we're after:**
We need to update the global search.gov index for new pages that were published in April

Related issues
#4417  

Completion criteria

- [x] Follow instructions under [Adding CMS pages to the index](https://github.com/fecgov/fec-cms/blob/develop/fec/search/management/instructions.md#adding-cms-pages-to-the-index)
- [x] Create ticket for April manual Wagtail global search index

**Comment by johnnyporkchops** [comment]
- Pages scraped and indexed for April. Still missing ability to see indexed totals based on this known-issue referenced in March/2021 issue. Screenshot below verifies April/2021 update. 
- https://github.com/fecgov/fec-cms/issues/4417#issuecomment-807316267
- Ticket for May 2021 created. #4567 
<img width="1070" alt="Screen Shot 2021-04-25 at 10 57 31 PM" src="https://user-images.githubusercontent.com/5572856/116023448-19f85e00-a61a-11eb-9d40-86f1a95c5edf.png">
