### ISSUE TITLE
After April 13: Test all redirects implemented in 14.3 release

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4520]
### Summary

**What we're after:**
_We are getting off of transition._

### Related issues

_List any relevant related issue(s)_

- #4430 - Redirects for info/notices
- #4451 - 14.3 redirects 

### Completion criteria

- [x] Redirects work
- [x] Non-working redirects Pat [flagged in this comment](https://github.com/fecgov/fec-proxy/pull/256#pullrequestreview-628008890) are deleted.
- [x] [Spreadsheet](https://docs.google.com/spreadsheets/d/1vzN-wZlS8K8ZyfExSV3hwXDenDEN9KyyAUJFTI6OjKU/edit#gid=0) updated
- [x] Redirected pages added to a take-down ticket (#4546)
- [x] www redirects / Wagtail redirects have been added as needed

**Comment by djgarr** [comment]
Redirects working properly. Created take down ticket (noted above).
