### ISSUE TITLE
Draft terminology for "contributor" in all receipts section

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4527]
### Summary

**What we're after:**
Not all receipts are from contributors. We need a different term to more generically describe money coming in. We do **not** need to make this change to the individual contributions search page/data table. 

![image](https://user-images.githubusercontent.com/11817734/112511522-dd122080-8d68-11eb-94b5-7ec120bc9ce9.png)

![image](https://user-images.githubusercontent.com/11817734/112511636-fca94900-8d68-11eb-99c2-8f6f34697ee2.png)

![image](https://user-images.githubusercontent.com/11817734/112511765-1cd90800-8d69-11eb-9e8a-838e68d27e3b.png)

### Action items
- [x] Come up with new term/ new language for "contributor"
- [x] Submit to OGC for feedback

### Completion criteria
- [ ] New terminology is decided with appropriate approvals

**Comment by bmathesonFEC** [comment]
While preparing a response to OGCs email to the Commission regarding the Liquidating Bitcoin issue, we are proposing  "Source name" as a possible alternative to "Contributor name" as the column header. (@dorothyyeager, @JonellaCulmer )

**Comment by dorothyyeager** [comment]
@JonellaCulmer Like @bmathesonFEC above, and looking at a thesaurus, I think that "source" is the way to go. I considered "payor" but that seems less like "plain language" and also could have a legal connotation we don't necessarily mean. Source is a little more plain and simple.

For the gray column:
"Source of receipt details" or "Source details" 
For the table column head: "Name of source"

Seems like we need to update [the wording on this page](https://www.fec.gov/data/browse-data/?tab=raising) too: 
![image](https://user-images.githubusercontent.com/24437369/124629251-41a44780-de4f-11eb-87b9-3bec48f79d4c.png)

**Comment by dorothyyeager** [comment]
We've sent the images and the proposal to sub "source" for "contributor" to OGC.

**Comment by dorothyyeager** [comment]
OGC thinks "source" works perfectly, so we're ready to close this ticket and move on to implementation in https://github.com/fecgov/fec-cms/issues/4513
