### ISSUE TITLE
Trouble viewing archived MUR case

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4538]
@fec-issues-bot commented on [Tue Apr 06 2021](https://github.com/fecgov/FEC/issues/10831)

## What were you trying to do and how can we improve it?
 Access Enforcement MUR 950 

## General feedback?
 Cannot access this MUR 950 on the enforcement archive.  It fails to load.  

## Tell us about yourself
 I'm a FEC employee interested in research. 

## Details
* URL: https://www.fec.gov/data/legal/matter-under-review/950/ 
* User Agent: Amazon CloudFront

---

@JonellaCulmer commented on [Tue Apr 06 2021](https://github.com/fecgov/FEC/issues/10831#issuecomment-814467553)

I'm not able to replicate this issue. I can see MUR 950 at the link above. 

Here is the link to the MUR in the search results: https://www.fec.gov/data/legal/search/murs/?search_type=murs&search=&case_no=950&case_respondents=&case_min_open_date=&case_max_open_date=&case_min_close_date=&case_max_close_date=

**Comment by JonellaCulmer** [comment]
We are, in fact, able to replicate the issue. The document cannot be opened. The page loads just fine.

**Comment by fec-jli** [comment]
the mur_950.pdf is on S3 bucket, the file cannot be download.
https://www.fec.gov/files/legal/murs/950.pdf

**Comment by patphongs** [comment]
Large MUR case files greater than 280MB seem to not be loading from the normal path www.fec.gov/files/legal/murs. However, you can load the file if you go to our public bucket directly: http://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/legal/murs/950.pdf. That's a temporary solution for now until we can figure out how to fix the load issue on our www.fec.gov path.
