### ISSUE TITLE
[Snyk: High] Denial of Service (DoS) due - 05/4/2021

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-cms#4540]
**Update**
Adding other Snyk tickets to this as they have the same remediation paths. Here are all four:
https://app.snyk.io/vuln/SNYK-PYTHON-PILLOW-1090584
https://app.snyk.io/vuln/SNYK-PYTHON-PILLOW-1090586
https://app.snyk.io/vuln/SNYK-PYTHON-PILLOW-1090587
https://app.snyk.io/vuln/SNYK-PYTHON-PILLOW-1090588

**Overview**
Pillow is a PIL (Python Imaging Library) fork.

Affected versions of this package are vulnerable to Denial of Service (DoS). The readline in EPS use an accidentally quadratic method of accumulating lines while looking for a line ending. A malicious EPS file can use this to perform a DoS in the open phase, before an image is accepted for opening.

**Details**
Denial of Service (DoS) describes a family of attacks, all aimed at making a system inaccessible to its intended and legitimate users.

Unlike other vulnerabilities, DoS attacks usually do not aim at breaching security. Rather, they are focused on making websites and services unavailable to genuine users resulting in downtime.

One popular Denial of Service vulnerability is DDoS (a Distributed Denial of Service), an attack that attempts to clog network pipes to the system by generating a large volume of traffic from many machines.

When it comes to open source libraries, DoS vulnerabilities allow attackers to trigger such a crash or crippling of the service by using a flaw either in the application code or from the use of open source libraries.

Two common types of DoS vulnerabilities:

High CPU/Memory Consumption- An attacker sending crafted requests that could cause the system to take a disproportionate amount of time to process. For example, commons-fileupload:commons-fileupload.

Crash - An attacker sending crafted requests that could cause the system to crash. For Example, npm ws package

**Remediation**
Upgrade Pillow to version 8.2.0 or higher.
https://app.snyk.io/vuln/SNYK-PYTHON-PILLOW-1090588

**Comment by patphongs** [comment]
These pillow vulnerabilities should be remediated after deploy of the [Wagtail upgrade](https://github.com/fecgov/fec-cms/pull/4518)

**Comment by rfultz** [comment]
Assigning this to myself to come back to it after Wagtail upgrade launch
