### ISSUE TITLE
Draft new language for matching fund submission pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4541]
**What we're after:**
We need to re-work the language for the matching fund submission pages to both modernize and remove repetitive language. The new pages will include "Read next" links to previously published pages on .gov where the language can be found instead. 

Pages needing new language:
Matching fund submission landing page: 
- https://transition.fec.gov/finance/disclosure/presidential_matching_fund_submissions_2004_present.shtml
Individual election year pages:
- https://transition.fec.gov/finance/disclosure/2016MatchingFundSubmissions.shtml
- https://transition.fec.gov/finance/2012matching/2012matching.shtml
- https://transition.fec.gov/finance/2008matching/2008matching.shtml
- https://transition.fec.gov/finance/disclosure/2004MatchingFundSubmissions.shtml

### Completion criteria
- [x] Draft New language is drafted and circulated with relevant offices, any changes are incorporated, Adhere to one place for content rule
- [x] Follow-up implementation ticket is created (Ask @JonellaCulmer for final mockup to include in issue)
- [x] Submit final language to Jonella

**Comment by dorothyyeager** [comment]
A draft has been sent to @JonellaCulmer @djgarr @kathycarothers @bmathesonFEC for review before sending on to the various offices that handle public funding.

**Comment by dorothyyeager** [comment]
Moving to blocked. Content team is good with the draft so we have sent it on to Public Records, Press, OGC Policy and Audit for their input. Audit and Public Records co-own these pages. They've been asked to return comments by April 30.

**Comment by dorothyyeager** [comment]
We've received comments back from Audit (they want to Title Case the page titles, but no other comments). I've reminded the other offices that we are waiting on their feedback.

**Comment by dorothyyeager** [comment]
We've received one comment from Press. Awaiting the other two offices' feedback. I'll want to send the combined comments around, so will move this to 14.6.

**Comment by dorothyyeager** [comment]
I sent a combined draft around again to the business offices. We never got comments from Policy, but Audit and Public Records/Press are the main offices for these pages anyway. We'll give them a few days to respond.

**Comment by dorothyyeager** [comment]
Public Records has some questions and opinions about where this should be linked. Will move this into innovation sprint and try to wrap up their questions.

**Comment by dorothyyeager** [comment]
We're ready to go with this. Public Records made a good case for why these should be created as child pages in Campaign Finance Data so we'll go with that. Links will be added to point to the new landing page in the public funding pages as well as https://www.fec.gov/data/browse-data/?tab=candidates (where the presidential portion lives) and in the Public Records pages.

I'll email the final draft to @JonellaCulmer 

Follow up tickets: 
https://github.com/fecgov/fec-cms/issues/4593 (Uploading the files/redirecting)
https://github.com/fecgov/fec-cms/issues/4594 (Publishing)
