### ISSUE TITLE
Add document list block to custom page template

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4542]
**What we're after:**
As part of our work to move the matching fund submission pages off of transition, we need to make adjustments to the custom page template to accommodate the information and display it the best way we can. To do this we need to add the document list block to the page template.

**Depending on the desired presentation and styling We could possible use one of the following:**
 - The existing FeedDocumentBlock:
 https://github.com/fecgov/fec-cms/blob/6ebd8317056c960fc61761e7f53ac0387f595112/fec/home/blocks.py#L96

 - A Wagtail DocumentChooserBlock with structure and styling set by the template and CSS.

**Completion criteria:**
- [ ] Document list block added to the CustomPage template

**Mockup:**
![mockup_documentlist_custompage](https://user-images.githubusercontent.com/31663028/114922792-1aaf1a00-9dfa-11eb-93c2-929906a4b7f1.png)

**Comment by dorothyyeager** [comment]
@johnnyporkchops I just found something else to fix with the document block that will affect the matching funds work. ZIP files show up as PDFs
![image](https://user-images.githubusercontent.com/24437369/115780568-519ba780-a387-11eb-876e-e053d4e7749c.png)
See https://fec-feature-cms.app.cloud.gov/introduction-campaign-finance/understanding-ways-support-federal-candidates/presidential-elections/public-funding-presidential-elections/test-of-document-block-for-zip-files/ for the test of this.
Do you want me to open a new ticket for this or do you just want to add it to your PR?
