### ISSUE TITLE
14.5 Transition pages to take down

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#4546]
### Summary

**What we are after:**
_We are getting off transition. The files listed in this ticket have been successfully redirected to new homes and can be taken down safely._

### Related issues

- #4520 After April 13: Test all redirects implemented in 14.3 release

### Completion criteria

- [ ] Pages in this list are removed from transition

/agenda/2010/agenda20100615.shtml
/agenda/2012/agenda20120712.shtml
/agenda/2016/agenda20160128.shtml

/info/contrib.htm
/info/elecmas.htm
/info/fecmaill.shtml
/info/individuals.shtml
/info/notices/2005/notice_2005-05.pdf
/info/notices/2005/notice_2005-07.pdf
/info/notices/2006/alprim.shtml

**Comment by rfultz** [comment]
@djgarr any concerns that I'm not seeing any of /agenda files at all?

**Comment by djgarr** [comment]
Possibly. @patphongs @dorothyyeager @kathycarothers do you happen to know if these files had been removed previously?

**Comment by patphongs** [comment]
> /agenda/2010/agenda20100615.shtml
> /agenda/2012/agenda20120712.shtml
> /agenda/2016/agenda20160128.shtml

@djgarr @rfultz @dorothyyeager @kathycarothers  These agenda files probably never existed as they were special agendas that content team had to find in Wagtail when doing redirects. So no need to worry about finding and deleting them, as all the old agendas on transition have already been deleted.

**Comment by rfultz** [comment]
Thanks everybody! The other files have been removed, so I'm closing this one
