### ISSUE TITLE
[May] - Manually update wagtail global search index 

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#4567]
## Summary
**What we're after:**
We need to update the global search.gov index for new pages that were published in May 2021

Related issues
#4514 

Completion criteria

- [ ] Follow instructions under [Adding CMS pages to the index](https://github.com/fecgov/fec-cms/blob/develop/fec/search/management/instructions.md#adding-cms-pages-to-the-index)
- [ ] Create ticket for June manual Wagtail global search index

**Comment by patphongs** [comment]
- Pages scraped and indexed for May. Still missing ability to see indexed totals based on this known-issue referenced in [March/2021 issue](https://github.com/fecgov/fec-cms/issues/4417#issuecomment-807316267). Screenshot below verifies May/2021 update. 
![Screen Shot 2021-05-24 at 11 40 48 AM](https://user-images.githubusercontent.com/12799132/119372200-0b3ab080-bc85-11eb-934e-e9b10867adee.png)


- Ticket for June 2021 created. https://github.com/fecgov/fec-cms/issues/4645
- Created follow-up ticket to perform clean up on the transition page json, as those are now redirected: https://github.com/fecgov/fec-cms/issues/4646
