### ISSUE TITLE
[Bug] Take users to the correct datatable from the legal resources search results page and ensure accurate result totals

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4568]
**What we're after:**
Encountered a bug using the global legal resources search on the legal resources landing page. Regardless of whether or not you filter by a specific legal type, the results still take you to the MUR search. The below gif shows filtering by Regulations, but the same was seen filtering by AOs and without filtering.

**Completion criteria:**
- [ ] Results page displays correct number of results and 
- [ ] Results total takes users to the correct datatable

![legal-resources-bug.gif](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/113e7127-230c-42cd-87eb-b6da1fd88127)

### Technical considerations

The results link bug is located here in the code: https://github.com/fecgov/fec-cms/blob/92edd9a7e594c8d3530ccdc6eabf92f5bd69f4e9/fec/legal/templates/legal-search-results.jinja#L56 

It doesn’t distinguish the link based on type, like we do for the "All results" button. This is an issue for all of the paginated links.

**Comment by johnnyporkchops** [comment]
We need to add the {{ category }} variable to the results link:
```
<span class="results-info__details">1&ndash;{{ results[category + "_returned"] }} of <a href="/data/legal/search/{{ category }}/?search={{ query }}&search_type={{ category}}"><strong>{{ results["total_" + category] }}</strong> results</a></span>
```
