### ISSUE TITLE
Post message about updated district maps on election search page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4570]
**What we're after:**
We should consider posting a message notifying customers that we will update the new district maps on the election search as soon as we have them from the states. 

Election search page: https://www.fec.gov/data/elections/?state=&cycle=2022&election_full=true 

**Completion criteria:**
- [x] Design is mocked up (pairing opportunity with design)
- [ ] Language for message is finalized (pairing opportunity with content team)
- [ ] Message is posted on election search page

**Comment by JonellaCulmer** [comment]
Here are some mock-ups for the redistricting message: 

### On load, no filters applied
![Screen Shot 2021-07-15 at 3 23 29 PM](https://user-images.githubusercontent.com/31663028/125845670-7d5f2ab6-e2dc-4e6b-a0e1-0dfa4831581b.png)

### Display with results
![Screen Shot 2021-07-15 at 3 22 19 PM](https://user-images.githubusercontent.com/31663028/125845669-1fa34175-8d30-476e-a65e-0e281bd0594b.png)

**Comment by johnnyporkchops** [comment]
@JonellaCulmer Heads We have a special message for Penn 2018 that goes inside the Results area. I know this one is a different context, but just wanted to make sure you were aware of that existing pattern:

<img width="1092" alt="Screen Shot 2021-07-20 at 8 56 31 PM" src="https://user-images.githubusercontent.com/5572856/126413860-11faee80-1c5e-4887-a19d-4501c19d507b.png">

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Yes, I'm aware. The difference between the Pennsylvania message and the 2020 census is that the census changes will apply to multiple states and regardless of what filters people choose, I want them to be able to see that message. At least for now. When we have more specific information about how states will change I'd rather have it available on default. 

I also figured if we put it in the results wouldn't that require additional logic? If I'm wrong about that please let me know.

**Comment by kathycarothers** [comment]
@johnnyporkchops @JonellaCulmer    David @djgarr and I played around with language and wanted to emphasize that this is on the states to get us the information and a bit more direct. Here is what we came up with:

Following the 2020 Census, some states may redraw their districts. The FEC will update its map to reflect the new Congressional districts and boundaries once information has been made available from the states. Note: should a district change, a candidate may need to amend their registration forms (Forms 1 and 2). 

*We were not sure if we need this sentence “Candidates are listed using information from their registration forms and may be running in different districts than in the past.”  We saw that it was included in the PA district change summary.

**Comment by JonellaCulmer** [comment]
@kathycarothers @djgarr I think it's important to include that a candidate may switch from one district to another and that it may be different from previous cycles. That's a key thing when trying to track a specific candidate or candidates. It's also data we're responsible for managing. 

Also, I don't think we need to say "Note:" It's a short message. Can we tweak to say something like: "Candidates may need to amend their registration forms if the district their running in is changed or removed."

Lastly, for the second sentence can we say "...available from each state." 

cc: @PaulClark2 @AmyKort @patphongs

**Comment by kathycarothers** [comment]
@JonellaCulmer  I have incorporated your changes:

Following the 2020 Census, some states may redraw their districts. The FEC will update its map to reflect the new Congressional districts and boundaries once information has been made available from each state. Candidates may need to amend their registration forms if the district their running in is changed or removed.  Candidates are listed using information from their registration forms and may be running in different districts than in the past. 

I am good with those changes, though should keep the parenthesis (Form 1 and 2) so folks are clear which forms we are referring to when we say "registration forms" the first time? If I am being too cautious, please disregard. I am fine either way. 

cc @PaulClark2 @AmyKort @patphongs @johnnyporkchops

**Comment by AmyKort** [comment]
Can we stick a little closer to the 2018 message: "Following the 2020 Census, some states may redraw their districts. Some candidates may subsequently amend their registration forms to reflect new district numbers. Candidates are listed using information from their registration forms and may run in different districts than in the past. The FEC will update its map to reflect the new Congressional districts and boundaries once information has been made available from each state."

**Comment by PaulClark2** [comment]
I agree with @AmyKort
