### ISSUE TITLE
Add RAD FAQ pdfs to the policy guidance search

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#4588]
### Summary
Before terminating the RAD FAQ pages OGC has requested that the pages be preserved in PDF format for future reference in enforcement documentation. Currently the [RAD FAQ for PACs](https://www.fec.gov/resources/cms-content/documents/RAD_FAQs-PACs_last_visited_september_21_2020.pdf) is searchable in the [policy guidance document search](https://www.fec.gov/legal-resources/policy-and-other-guidance/guidance-documents/?query=RAD+FAQ) page.

Steps:
- [x] PDF the current RAD FAQ pages, upload into Wagtail
- [x] Add the documents to the Guidance Search XML site map.

### Completion criteria

- [ ] RAD FAQs are findable on in the guidance search.

### Tech steps or considerations

Here's our guidance for how to do this: https://docs.google.com/document/d/1hfvlYhGVNF0Km5vrAYtJak2cdAYLYQPbiPUfLxbRN1E/edit#heading=h.83p10qypinz4

### Future work

Redirects in place for the RAD FAQ page ( #3350)

**Comment by dorothyyeager** [comment]
@bmathesonFEC Here's the last time we updated guidance search so you can look at the "how to" and the PR. It's got some layers to it, happy to pair. https://github.com/fecgov/fec-cms/issues/4472

**Comment by bmathesonFEC** [comment]
Pulled PDFs for each page that needs to be added the guidance search. Saved them in RAD network as well as the content team google drive under RAD FAQ.

**Comment by bmathesonFEC** [comment]
Prepared the PDFs and uploaded them into Wagtail. Checking with Content Team to find out if there are any other additions to the Guidance Search xml site map before doing the PR.

**Comment by bmathesonFEC** [comment]
All RAD FAQ documents are preserved in the guidance document search: https://www.fec.gov/legal-resources/policy-and-other-guidance/guidance-documents/?query=rad+faq
