### ISSUE TITLE
Upload matching fund submission files to CMS and put in redirects

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4593]
### Summary

**What we are after:**
We are migrating the matching fund submission files currently found on these pages:
https://transition.fec.gov/finance/disclosure/presidential_matching_fund_submissions_2004_present.shtml
Individual election year pages:
https://transition.fec.gov/finance/disclosure/2016MatchingFundSubmissions.shtml
https://transition.fec.gov/finance/2012matching/2012matching.shtml
https://transition.fec.gov/finance/2008matching/2008matching.shtml
https://transition.fec.gov/finance/disclosure/2004MatchingFundSubmissions.shtml

### Related issues

_List any relevant related issue(s)_

- #4541 - Language for new pages

### Completion criteria

- [x] Collection created and files uploaded to it 
- [ ] Redirects put into proxy, added to spreadsheet, and follow up redirect testing ticket entered.

### Future work

- Making the pages once language approved and files uploaded.

**Comment by dorothyyeager** [comment]
Reassigning to @kathycarothers - feel free to reassign back to me on Friday. :)

The main thing is to download all those .xls, .zip, etc files linked on those individual election year pages, create a collection in Wagtail and then upload to the collection. 

After that, we'll need to make a tab in redirect spreadsheet and do the redirects.

**Comment by kathycarothers** [comment]
I have created a new folder in the Documents section of Wagtail for these documents called "Matching funds submissions"

**Comment by kathycarothers** [comment]
For the Zip files on the 2008 page, they are located in the S3 bucket and just need to be linked in the new page.
