### ISSUE TITLE
Banner Work for 15.1 (June 8 - June 21)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4596]
### Summary
What we are after:
_Content team is going to have routine sprint ticket for banner work each sprint to make sure we're on top of it._

### Related
[Banner spreadsheet](https://docs.google.com/spreadsheets/d/1MPGmgOFg-pjlkYZHUl28thVd1IPCQEmsseg7idH5ThU/edit?usp=sharing)
[Banner How to](https://docs.google.com/document/d/1Ehq3sxa6WXzLWf1UdwnbLIsKNTcCnSHIECcPYfWWhC4/edit?usp=sharing)

### Completion criteria
Banners set up for:

- [x]  Open meeting of June 10 - set up by June 9
- [x]  On Thursday June 10, update NOA banner to return June 10 at 5:31 pm and go off at 7:29 am June 24
- [x]  If needed: any change in status doc that may happen

**Comment by kathycarothers** [comment]
Open meeting was canceled for this week.
