### ISSUE TITLE
Content beyond "Read more" appearing on Latest updates

### ISSUE THREAD

**Issue by prstoetzer** [fecgov/fec-cms#4610]
### Summary

_What happened?_

Content beyond "Read more" is "spilling" out for some Record articles on https://www.fec.gov/updates/

_What should have happened?_

No content beyond the "Read more" cutoff should appear

### Frequency

_Is this the first time it's happened,_
_an ongoing issue,_
_seems to happen randomly, or_
_some other frequency?_

First noticed this morning

### How to Reproduce

_List any steps you took for this issue to happen. Be sure to include the URL and what you clicked or entered. More details are better._
URL: https://www.fec.gov/…

https://www.fec.gov/updates/
The first article exhibiting this problem is https://www.fec.gov/updates/ao-2021-04/

### Device, browser, etc

_Tell us everything you can about:_

- _your device (e.g. laptop, tablet, phone),_

Laptop

- _its operating system (e.g. Windows, iOS, Android),_

Windows 10

- _your browser (e.g. Chrome, Internet Explorer, Safari, "Internet"),_

Chrome and Firefox tested

- _your screen or browser window size (for mobile, is it portrait or landscape?),_

1920x1080

- _your Internet connection (e.g. home, mobile, VPN),_

Home - on and off VPN

### Screenshots

![image](https://user-images.githubusercontent.com/31514408/117456964-c689e800-af16-11eb-8568-93d7e760b2c4.png)

**Comment by johnnyporkchops** [comment]
The leading paragraphs are less than 30 characters and the Django built-in `truncatewords_html` filter does not count HTML tags as words and closes any tags that were left open as a result of the truncation. So it closes the `Read more` link into the first paragraph. 
I  think this one is tricky to solve for all cases, I had the same issue with FECet and finally gave up after trying several conditional statements to NOT close the html iff the lead-in was less than 30 words.
