### ISSUE TITLE
"Ending cash on hand" glossary link not working

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4617]
### Summary

The "Ending cash on hand" glossary link is not working on the committee profile page or the candidate profile page. ~The term also does not seem to exist in the glossary.~ The term is `Ending cash-on-hand`, see comment below. The easiest way to fix this is for content team to take the hyphens out of the glossary term (they shouldn't be there anyway per GPO rules).

### How to Reproduce

Example committee profile page: https://www.fec.gov/data/committee/C00401224/#cash-summary
Example candidate profile page: https://www.fec.gov/data/candidate/P80000722/#cash-summary

### Screenshots

![Screen Shot 2021-05-11 at 3 17 36 PM](https://user-images.githubusercontent.com/12799132/117872731-07626380-b26d-11eb-86cf-01b9dd331875.png)

### Completion criteria
- [x] Put in PRs for e-regs and CMS to take the hyphens out of cash on hand wherever it appears in the glossary [[How to guide](https://docs.google.com/document/d/1u1ksIbb44JgbquwcYXpJz9he8lz5fyhYAmwpA129f34/edit?usp=sharing)]
- [x] Update the content guide to put cash on hand in it (without hyphens)
- [x] Process of updating glossary demo'ed for team

**Comment by lbeaufort** [comment]
Looks like I can't share a link to the glossary, but the `data-term` should be `ending cash-on-hand`, not `ending cash on hand`
<img width="303" alt="Screen Shot 2021-05-11 at 3 48 36 PM" src="https://user-images.githubusercontent.com/31420082/117875746-87d69380-b270-11eb-9320-f6fa2e42250c.png">

**Comment by patphongs** [comment]
The glossary term "cash-on-hand" is hyphenated in the glossary, I'm wondering if we should also hyphenate on the profile pages as well to remain consistent.

**Comment by dorothyyeager** [comment]
We should hyphenate. 

Just a reminder for this ticket, two PRs will be needed - one for CMS and one for e-regs. There's a how-to in the content section of the team folders in Google drive.

**Comment by dorothyyeager** [comment]
I take it back! GPO Style says we should not hyphenate, which makes this an easier fix. I've updated the ticket to note how the glossary should be changed and our style guide updated.

**Comment by dorothyyeager** [comment]
PRs have been submitted for review. We've also included taking out the hyphen in the presidential map and also in the term net outstanding campaign obligations. 
![image](https://user-images.githubusercontent.com/24437369/119398511-a8a5dc80-bca5-11eb-91f2-90d6a2d8089c.png)

This ticket can be closed after the PRs are merged.

**Comment by dorothyyeager** [comment]
Closing. Related PRs have been merged.
