### ISSUE TITLE
Redirects identified in transition inventory meeting 14.6

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4619]
### Summary

**What we're after:**
We need to redirect the pages we found need redirecting in #4512 

### Related issues

_List any relevant related issue(s)_

- #4512 14.6 transition inventory meeting

### Completion criteria

- [x] Redirects are merged into the release (See spreadsheet for redirects)
- [x]  2021 spreadsheet is updated
- [x] Testing ticket is created to be done in the next sprint after deploy of releases to test redirects and implement any needed www ones.
- [x] Take down ticket is created to take down the redirected items.

**Comment by bmathesonFEC** [comment]
@kathycarothers @djgarr  I tagged Dorothy, but she certainly doesn't need to be the reviewer on this redirect PR.

**Comment by bmathesonFEC** [comment]
PR merged, 6/8/21.  Testing ticket #4677
