### ISSUE TITLE
Take down pages identified in transition meeting 14.6

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4620]
### Summary

**What we are after:**
_We're getting off of transition._

### Related issues

https://github.com/fecgov/fec-cms/issues/4512 - transition meeting

### Completion criteria

These files (identified as already redirected or no longer needed) are removed from transition:
/info/interior_template.shtml
/info/keyissues.shtml
/info/l-sc.jpg
/info/mission.shtml
/info/phone.gif
/info/present.gif
/info/primtop.jpg
/info/record.gif
/info/report_dates.shtml
/info/TipsforTreasurers.shtml
/info/tools.jpg
/info/treas.gif
/info/treas2.gif
/info/treas3.gif
/info/webinarpic.jpg

**Comment by patphongs** [comment]
The above files have been deleted from the transition bucket as requested.

```
Mon May 24 12:05:17 EDT 2021
delete: 's3://bucket_name/info/TipsforTreasurers.shtml'
delete: 's3://bucket_name/info/interior_template.shtml'
delete: 's3://bucket_name/info/keyissues.shtml'
delete: 's3://bucket_name/info/l-sc.jpg'
delete: 's3://bucket_name/info/mission.shtml'
delete: 's3://bucket_name/info/phone.gif'
delete: 's3://bucket_name/info/present.gif'
delete: 's3://bucket_name/info/primtop.jpg'
delete: 's3://bucket_name/info/record.gif'
delete: 's3://bucket_name/info/report_dates.shtml'
delete: 's3://bucket_name/info/tools.jpg'
delete: 's3://bucket_name/info/treas.gif'
delete: 's3://bucket_name/info/treas2.gif'
delete: 's3://bucket_name/info/treas3.gif'
delete: 's3://bucket_name/info/webinarpic.jpg'
Finished syncing and  deleting files
```
