### ISSUE TITLE
H4CC Quality Control - Take out hyphens in cash on hand

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4624]
### Summary

**What we are after:**
In looking into what's causing a bug, we discovered we've been hyphenating cash-on-hand but shouldn't have been. We're updating the glossary to address the bug, but we'll want to make sure H4CC (global search) pages and reporting examples take out the hyphens too.

### Related issues

- #4617 - Glossary update 

### Completion criteria

- [x] No more hyphens in cash on hand (to find them, we may need to do a global search to id pages with that wording)

**Comment by kathycarothers** [comment]
I did a global search and came up with the following pages:
Assigning debts to another committee
Winding down publicly funded presidential candidate
Raising contributions to retire debts
Registering the SSF 

H4CC pages doing a general scan:
Misappropriated funds
Terminating a committee 

All the above pages showed cash on hand with hyphens and now have been removed.

**Comment by kathycarothers** [comment]
@bmathesonFEC  I wanted to double-check with the reporting examples. I didn't see cash on hand in the examples. Is this correct?

**Comment by kathycarothers** [comment]
I have now done a global search with "cash-on-hand" in quotes and came up with more results:
Types of contributions to the SSF 
Personal loans from the candidate 
Settling debts for less than the amount owed
Fundraising for the PAC
Types of contributions to party committees
Transfers between a candidate's committee
Recording receipts
Cunninghan v FEC
Investment income
Paying for the IE first and disseminating in a later reporting period
Bitcoin contributions
Investment income of nonconnected committees
Filing amendments 
Debts owed by publicly funded presidential committees 
Winding down publicly funded presidential candidate committee 
Bitcoin contributions
