### ISSUE TITLE
Election Profile Page - data tables warning message

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#4625]
### Summary
When navigating to any election profile page the following warning message pops up:

![image.png](https://images.zenhubusercontent.com/5c0e981b4b5806bc2bfc2cb5/791bc067-b02f-4340-a56f-0a613502b3b1)

When I click OK the warning goes away and I am able to navigate the page as expected.

### Frequency
first time I noticed this was today, May 14th, 2021 but I don't frequent the election profile pages. Happens ever time I visit the pages now

### How to Reproduce

Navigate to any election profile page, for example: 
https://www.fec.gov/data/elections/president/2020/
https://www.fec.gov/data/elections/house/CT/02/2022/
https://www.fec.gov/data/elections/senate/CO/2022/

or:
home > compare candidate in an election > choose state, office, district (if applicable)

### Device, browser, etc
Firefox, Opera, Edge, Chrome
(screen shot above is taken from Firefox)

**Comment by patphongs** [comment]
Fixed with this hotfix: https://github.com/fecgov/fec-cms/pull/4633
