### ISSUE TITLE
User feedback on https://www.fec.gov/data/elections/house/FL/19/2020/

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#4632]
@fec-issues-bot commented on [Mon May 17 2021](https://github.com/fecgov/FEC/issues/10917)

## What were you trying to do and how can we improve it?
 I got this error when searching for information about the 2020 election in Florida's 19th House District: DataTables warning: table id=DataTables_Table_5 - Requested unknown parameter '1' for row 0, column 1. For more information about this error, please see http://datatables.net/tn/4 

## Tell us about yourself
 I'm an FEC employee in OGC. 

## Details
* URL: https://www.fec.gov/data/elections/house/FL/19/2020/ 
* User Agent: Amazon CloudFront

**Comment by PaulClark2** [comment]
Closing in favor of #4625
