### ISSUE TITLE
Banner Work for 15.3 (July 6  - July 19) 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#4639]
### Summary
What we are after:
_Content team is going to have routine sprint ticket for banner work each sprint to make sure we're on top of it._

### Related
[Banner spreadsheet](https://docs.google.com/spreadsheets/d/1MPGmgOFg-pjlkYZHUl28thVd1IPCQEmsseg7idH5ThU/edit?usp=sharing)
[Banner How to](https://docs.google.com/document/d/1Ehq3sxa6WXzLWf1UdwnbLIsKNTcCnSHIECcPYfWWhC4/edit?usp=sharing)

### Completion criteria
Banners set up for:

- [x]  Open meeting of July 15 - set up by July 14 
- [x]  If needed: any change in status doc that may happen - NOTE: will need to reset status doc on July 15 - see comment.
- [x] July Quarterly late hours - set up by July 14. (Verified with RAD/EFO that it's happening)
- [ ] Double-check for any other banners that might be needed

**Comment by dorothyyeager** [comment]
We will need to juggle the banners on July 15 since we'll need three banners and only have two slots on that day.

Our plan is to run the late hours banner as we normally would the whole day. The status doc will take a break in the AM in favor of the open meeting banner, and then return at Noon.

**Comment by dorothyyeager** [comment]
July 15th meeting banner is set up.
Waiting on the related tip to set up the July Quarterly banner.
Status doc banner set to take a break on the morning of July 15.

**Comment by dorothyyeager** [comment]
July 15 banners rotated. Status doc is taking a break until noon.

**Comment by dorothyyeager** [comment]
Status doc banner has returned as promised. Its expiration date is now December 31 although that may change when the FEC changes its mandatory telework order.

Closing ticket since no more banner work is expected this sprint.
