### ISSUE TITLE
Banner Work for 15.5 (August 3 - August 16) 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#4641]
### Summary
What we are after:
_Content team is going to have routine sprint ticket for banner work each sprint to make sure we're on top of it._

### Related
[Banner spreadsheet](https://docs.google.com/spreadsheets/d/1MPGmgOFg-pjlkYZHUl28thVd1IPCQEmsseg7idH5ThU/edit?usp=sharing)
[Banner How to](https://docs.google.com/document/d/1Ehq3sxa6WXzLWf1UdwnbLIsKNTcCnSHIECcPYfWWhC4/edit?usp=sharing)

### Completion criteria
Banners set up for:

- [x]  Open meeting of August 11  - set up by August 10 (the day before the open meeting)
- [ ] If needed: any change in status doc that may happen
- [x] Make a rulemaking banner for new Federal Register notice petition for rulemaking once the FR is published - note- this banner will come down on August 11 for the meeting banner. Will need to be reset to go live on August 11 at 5:30 pm and expire at 7:29 am September 2 (next Commission meeting).
- [ ] Double-check for any other banners that might be needed

**Comment by dorothyyeager** [comment]
The rulemaking banner for the NOA that was approved last week is going up today at 10 am. The pending rulemaking page has been updated. The banner will stay up through October 4.

**Comment by dorothyyeager** [comment]
The NOA banner has been reset to reappear at 5:30 pm today.

**Comment by dorothyyeager** [comment]
No banner posting needs planned for today. Closing out for the sprint.
