### ISSUE TITLE
Add additional Administrative fine parameters

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4650]
### Summary

**What we're after:**
_The last 3 parameters that are needed for the administrative fine work are: `af_dispositions.disposition_description`, `af_dispositions.amount`, `af_dispositions.disposition_date`, `civil_penalty_due_date`, `civil_penalty_payment_status`._

### Related issues

_List any relevant related issue(s)_

- WIP PR: https://github.com/fecgov/fec-cms/pull/4598
- [x] https://github.com/fecgov/openFEC/issues/4832
- [x] https://github.com/fecgov/fec-cms/issues/4552

### Completion criteria

These 3 parameters are added to the Administrative fines canonical page:
- [x] af_dispositions.disposition_description
- [x] af_dispositions.amount
- [x] af_dispositions.disposition_date
- [x] civil_penalty_due_date
- [x] civil_penalty_payment_status

**Comment by pkfec** [comment]
API pr#https://github.com/fecgov/openFEC/pull/4899 merged.

**Comment by patphongs** [comment]
These changes have been implemented, but there are some data anomalies that the AF team should look at:

1. Sometimes there is no civil penalty due date or civil penalty status, but there is a payment amount. 
2. Sometimes there is no data available for the dispositions table.

![Screen Shot 2021-07-12 at 10 37 51 AM](https://user-images.githubusercontent.com/12799132/125306503-48263980-e2fd-11eb-8243-78d8680af402.png)

**Comment by patphongs** [comment]
Moved this to blocked until we can get AF to review the data anomalies commented on [above](https://github.com/fecgov/fec-cms/issues/4650#issuecomment-878335650).

**Comment by patphongs** [comment]
This is now with the Administrative Fine team for review

**Comment by patphongs** [comment]
PR merged, this work is now complete
