### ISSUE TITLE
Election profile page: Medium width content cut off

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4656]
### Summary

The election profile pages do not display well on medium width screens. The display should stack according to screen size and you should also be able to scroll horizontally for the datatables when there's smaller screens.

### Frequency

_an ongoing issue_

### How to Reproduce

Go to any election profile page on a medium width screen (such as an ipad or phone on landscape view), you'll notice that things start getting cut off. Ex: https://www.fec.gov/data/elections/house/CA/01/2022/

### Device, browser, etc

Smaller devices that utilize medium width screens such as ipads or phones on landscape view.

### Screenshots

![Screen Shot 2021-05-25 at 4 13 28 PM](https://user-images.githubusercontent.com/12799132/119562979-fb9a9500-bd74-11eb-92fd-d318310fbf60.png)

**Comment by PaulClark2** [comment]
Might be related to https://github.com/fecgov/fec-cms/issues/4668
