### ISSUE TITLE
Update/add leadership PAC sponsor fields to Committees data table

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4660]
### Summary

**What we're after:**
To make our leadership PAC sponsor information more consistent, we need to update the committees datatable to include the leadership PAC sponsor information in the details panel. We also need to update the committee profile page about this committee tab to change the label from "Committee sponsor" to "Leadership PAC sponsor".

There is a [WIP PR](https://github.com/fecgov/fec-cms/pull/4669) that can be used for this. Decided to wait for the "[Add leadership PAC sponsor names to API /committees/ endpoint](https://github.com/fecgov/openfec/issues/4870)" ticket first before working on this. That ticket should be done in 15.1. Once the API work is completed, we can remove the datatable call to the /names/ endpoint and reference the name field from the API.

![Screen Shot 2021-05-27 at 9 34 06 AM](https://user-images.githubusercontent.com/12799132/119836216-8db6b080-becf-11eb-85ea-6cde6d01a2d8.png)

![Screen Shot 2021-05-27 at 9 37 02 AM](https://user-images.githubusercontent.com/12799132/119836230-914a3780-becf-11eb-9412-05f957bcf49e.png)

### Completion criteria

- [x] Leadership PAC sponsor is added to the committees datatable details panel
- [x] Committee profile page about this committee tab updated with "Leadership PAC sponsor" label

**Comment by pkfec** [comment]
API changes are merged in  pr# https://github.com/fecgov/openfec/issues/4870
