### ISSUE TITLE
Consider how to improve committee profile page committee type labels

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4661]
**What we're after:**
We should consider how to improve the labeling of different committee types on committee profile pages. 

Examples:
- Say Leadership PAC, instead of just PAC
- Change Corporation PAC to Corporate PAC

**Considerations:**
- [ ] How might the data limit our options for improvement?

**Completion criteria:**
- [ ] List of committee type name changes compiled
- [ ] Follow-up back-end tickets opened

**Comment by patphongs** [comment]
Closing in favor of https://github.com/fecgov/fec-cms/issues/5349
