### ISSUE TITLE
Consider adding corporation name to "Committee organization" section on committee profile pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4662]
**What we're after:**
For corporate PACs, we don't have a specific place where we list the committee's corporate sponsor name. We should consider adding this to the About this committee tab under the header "Connected organization" or create another place. 

**Considerations:**
- Consider all SSFs with connected organizations
- Line 6 on form 1

**Completion criteria:**
- [x] Research possible pain points from user feedback
- [x] Design for the inclusion of corporate sponsor name (pair with content for language)

**Comment by JonellaCulmer** [comment]
@patphongs @dorothyyeager @kathycarothers Here is the mockup for adding SSF connected organizations. Let me know if you see any necessary updates or changes. 

![SSF committee - about this committee](https://user-images.githubusercontent.com/31663028/189402762-25af55e0-2456-4a29-86a4-79faef9a0a48.png)

**Comment by dorothyyeager** [comment]
I think this looks perfect! Thank you @JonellaCulmer

**Comment by JonellaCulmer** [comment]
@pkfec @fec-jli @cnlucas Can you tell me whether this work requires an API change to implement on the about this committee page for SSF-type committees?

**Comment by pkfec** [comment]
@JonellaCulmer `committee/<committe_id>/history/` endpoint yields `affliated_committee_name` which can be used to display `corporation name` for SSF profile pages. Here is the API call and screenshot attached for your reference. 

https://api.open.fec.gov/v1/committee/C00822353/history/?sort_hide_null=false&election_full=true&sort_nulls_last=false&sort=-cycle&per_page=20&sort_null_only=false&page=1&api_key=DEMO_KEY

<img width="1370" alt="Screen Shot 2022-10-03 at 12 25 28 PM" src="https://user-images.githubusercontent.com/11650355/193629492-d8825557-1438-4f52-8e7b-0aed9654d3de.png">
