### ISSUE TITLE
Design for replacement of the map on the homepage

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4664]
**What we're after:**
We need to consider what we'll be replacing the presidential map with on the homepage. The map is not the most relevant content we can be highlighting at this time, so exploring replacements will add value to the people we serve and get them to the content that's more relevant. 

**Completion criteria:**
- [ ] Mockups are complete and PMs have reviewed

**Comment by JonellaCulmer** [comment]
Potential replacements on the homepage and reasons why they should be considered:
1. Raising by the numbers: High-level overview of money raised and from where contributions are originating. Good for exploring our data
2. Campaign finance landing page: Access to quick searches of candidates, committees and individual contributions. Would also be on the same level as the other two icons on the homepage which go to the H4CC and legal resources landing pages. Good to provide a pathway to multiple places.
3. Election search: Allows users to drill into a specific election and compare candidates. Good for candidates who know who they're looking for.

**Comment by JonellaCulmer** [comment]
Analytics for the last three months

Top page views Mar 26 - May 26:
<img width="854" alt="Screen Shot 2021-05-27 at 2 49 24 PM" src="https://user-images.githubusercontent.com/31663028/119880978-ca4bd180-befa-11eb-8ed6-c70153c61643.png">

Top paths through content drilldown Mar 26 - May 26:
<img width="700" alt="Screen Shot 2021-05-27 at 2 53 22 PM" src="https://user-images.githubusercontent.com/31663028/119881475-53fb9f00-befb-11eb-9b0d-bc0425fa7743.png">

**Comment by JonellaCulmer** [comment]
As discussed this morning, we're going to explore A/B testing these pages to determine the best option for us. That work will happen here: https://github.com/fecgov/fec-cms/issues/4667

In order to test all three pages, we need to design for all three pages, including language and image. We also discussed testing the linking of images - something we don't currently do on the site.

**Comment by JonellaCulmer** [comment]
@rfultz @patphongs Here are the graphics for the A/B/C? test. @rfultz Please let me know what sizes/file types you need from me. 
- Election search: relies on a map image similar to the presidential map. The difference being, we are highlighting some of the states as if someone we're hovering over or looking into states. Gives the feeling of moving around the map and taking a closer look at what's happening there. 
- Campaign finance landing page: Uses an image seen in other places on that site that suggest a drill down and exploration of the data. 
- Raising by the numbers: Uses the same image as the data landing page because it's a similar drill down and exploration of the data, just presented as charts here as opposed to a collection of searches. The image works well in both places.
<img width="935" alt="Screen Shot 2021-06-07 at 9 46 12 AM" src="https://user-images.githubusercontent.com/31663028/121028669-00e4e000-c776-11eb-9432-cab653df8d59.png">

**Comment by JonellaCulmer** [comment]
Closing in favor of https://github.com/fecgov/fec-cms/issues/4676

**Comment by rfultz** [comment]
@JonellaCulmer, are these the three different options for that first link or are we replacing all three?

**Comment by JonellaCulmer** [comment]
@rfultz Those are all the different options for the first link. We won't touch the other two links to Help for candidates and committees and legal resources.
