### ISSUE TITLE
Explore updating/upgrading to new Google analytics

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4666]
**What we're after:**
Google analytics is making the following advertisement on their site:
![Screen Shot 2021-05-28 at 9.14.50 AM.png](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/55654a5f-1f25-41ee-8b6a-99e9e1b7176f)

We should explore making this change and determine any pros/cons with doing so. 

Here's a brief slack conversation about this: https://fecgov.slack.com/archives/C3X3K6EVA/p1622207721082500

**UPDATE**
[Google says](https://support.google.com/analytics/answer/11583528) we have until 2023-07-01 to make the switch

**Tech considerations**
- Since we're using Tag Manager, all of the work (for our FEC account) should be handled inside GTM.
- Are there others sites than www that we need to update? (prod, dev, stage, feature, localhost are all included under www)
- What do we need to update for the DAP GA? Do they have guidance yet? 
- Google says [CSP rules need to be updated](https://developers.google.com/tag-platform/tag-manager/web/csp):
   - `script-src: *.google-analytics.com`
   - `img-src: *.google-analytics.com *.analytics.google.com`
   - `connect-src: *.google-analytics.com *.analytics.google.com`

**Completion criteria:**
- [x] www is migrated from using Google's Universal Analytics inside GTM
- [ ] additional subdomains (outside www, dev, prod, stage, feature, localhost) have been updated, too
- [ ] CSP have been updated as necessary
- [ ] API?
- [x] DAP has been updated as per their (as-yet-unpublished?) directions

**Comment by rfultz** [comment]
I've created a saved a GTM version called `Version 36 - GA4 - step 0 - DO NOT PUBLISH`.

In this version
- I renamed everything to have a `UA - ` prefix to make it more clear what still needed attention
- I created GA4 variables for our environments' (streams') Measurement IDs
- I paused implementation when I got to events; GA4 events don't come with UA's eventCategory, eventAction, eventLabel. I figured we should wait until DAP's implementation and follow their structure so our reports are similar

**Comment by rfultz** [comment]
This has been done for a while
