### ISSUE TITLE
Explore using GTM for A/B testing

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4667]
**What we're after:**
We want to explore the possibility of using GTM for A/B testing to determine the presidential map replacement on the homepage.

Three pages we want to include in the A/B testing:
CFD landing page: https://www.fec.gov/data/
Election search: https://www.fec.gov/data/elections/?state=&cycle=2022&election_full=true
Raising by the numbers: https://www.fec.gov/data/raising-bythenumbers/

**Completion criteria:**
- [x] Research is complete and recommendations have been made on ideal next steps

**Comment by JonellaCulmer** [comment]
@rfultz Here's a link to the icons: https://drive.google.com/drive/folders/18kchMACk2e8QWxSi0jW4N04KNxi8CIii 
Below is how each will look. Let me know if you have any questions. 

@dorothyyeager @kathycarothers @djgarr Can you take a look at the draft language and let me know if you have any edits?
<img width="985" alt="Screen Shot 2021-06-08 at 12 49 57 PM" src="https://user-images.githubusercontent.com/31663028/121226274-5c879a00-c858-11eb-9e36-699018101b07.png">

**Comment by dorothyyeager** [comment]
One suggested edit - "across the spectrum" isn't really needed; would recommend just taking it out.

**Comment by kathycarothers** [comment]
Looks good and I agree with Dorothy's comment.

**Comment by JonellaCulmer** [comment]
@rfultz Updated based on Dorothy and Kathy's comments. 

<img width="941" alt="Screen Shot 2021-06-08 at 2 34 11 PM" src="https://user-images.githubusercontent.com/31663028/121238927-a37c8c00-c866-11eb-8537-0cfe773fc10a.png">

**Comment by JonellaCulmer** [comment]
Closing in favor of #4676
