### ISSUE TITLE
Determine/document line numbers/math needed for percentages

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4670]
**What we're after:**
Before we can move forward with some of the front-end work, we need to make sure that we have the correct line numbers and math are documented. This will also help us make sure that any API work that needs to happen or has happened will serve our needs for this feature.

### Completion criteria
- [ ] Document line numbers and the math for percentages
- [ ] Plan for edge cases in formula (denominators of 0, etc)
- [ ] Any followup tickets are opened

**Comment by PaulClark2** [comment]
I've received feedback from the Press Office, and I'm waiting for feedback from RAD. The feedback from the Press Office is incorporated in the text and formulas below. 

Receipts side
**Percentage contributions from individuals** (will not include Line 12 transfers)

- Total individual contributions divided by total receipts (Form 3X Line 11(a)(iii)  divided by Line 19)

**Percentage contributions from other political committees** (will not include Line 12 transfers)
(Should this be contributions from just PACs or PACs and party committees?)

- Contributions from other committees divided by total receipts (Form 3X Line 11(c) divided by Line 19)
- OR 
- Contributions from party committees plus contributions from other committees divided by total receipts (Form 3X Line 11(b) + Line 11(c) divided by Line 19)
    - If we included PACs and party committees, perhaps the language under the doughnut could be something like, “percent raised from contributions from PACs and party committees.”

Disbursement side
**Percentage IEs, candidate contributions & party coordinated expenditures**

- Contributions to candidates plus independent expenditures plus party coordinate expenditures divided by total disbursements (Form 3X Line 23 + 24 + 25 divided by Line 31)

**Percentage operating expenditures**
(Should this be just other federal operating expenditures, all federal operating expenditures or all operating expenditures?)

- Other federal operating expenditures divided by total disbursements (Form 3X Line 21(b) divided by Line 31)
- OR
- Allocated federal operating expenditures plus other federal operating expenditures divided by total disbursements (Form 3X Line 21(a)(i) + Line 21(b) +  divided by Line 31)
- OR
- Total operating expenditures divided by total disbursements (Form 3X Line 21(c)  divided by Line 31)

**Comment by PaulClark2** [comment]
@lbeaufort 

Receipts
Percentage contributions from individuals 
- Total individual contributions divided by total receipts (Form 3X Line 11(a)(iii)  divided by Line 19)

Contributions from party committees plus contributions from other committees divided by total receipts (Form 3X Line 11(b) + Line 11(c) divided by Line 19)
- The language under the doughnut could be something like, “percent raised from contributions from PACs and party committees.”  

Disbursement 

Percentage IEs, candidate contributions & party coordinated expenditures
- Contributions to candidates plus independent expenditures plus party coordinate expenditures divided by total disbursements (Form 3X Line 23 + 24 + 25 divided by Line 31) 

Percentage operating expenditures
- Total operating expenditures divided by total disbursements (Form 3X Line 21(c)  divided by Line 31)

**Comment by lbeaufort** [comment]
Looks great, matches the email, thanks @PaulClark2!
