### ISSUE TITLE
Update designs for new data feature on committee profile pages

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4671]
**What we're after:**
Make updates to the committee snapshot mockup to include coverage dates, error states, methodology and design for what the mobile state will look like. 

### Completion criteria
- [x] Aforementioned updates have been made and approved by PMs
- [ ] Any followup tickets have been opened

**Comment by patphongs** [comment]
@JonellaCulmer The mobile view stacks nicely, but I have some questions around the totals bar chart. 

1. Will the total receipts bar always display as 100% width and everything else comparatively (the disbursements and cash on hand bars) will be a percentage of what total receipts is?
2. At any given time, a committee can have negative receipts, disbursements, or cash on hand. So I'm not sure how the bar chart will display in the negative scenario.

**Comment by JonellaCulmer** [comment]
@patphongs 
> Will the total receipts bar always display as 100% width and everything else comparatively (the disbursements and cash on hand bars) will be a percentage of what total receipts is?

The largest figure will always be 100%. I don't think we can reliably predict that the total receipts will always be the largest figure of the three. 

> At any given time, a committee can have negative receipts, disbursements, or cash on hand. So I'm not sure how the bar chart will display in the negative scenario.

That's a great point. The bar charts are a bit of a stretch goal for mobile, but if we can/want to go down that route, I can update it to allow for negatives as well. It's probably less accurate to use a display of $0 for -$, but that's one possible route for a first iteration.

**Comment by JonellaCulmer** [comment]
## Language
Feature title, disclaimer, percentage descriptions: 

## Desktop and mobile views
![Screen Shot 2021-07-07 at 11 41 45 AM](https://user-images.githubusercontent.com/31663028/124789497-57ca0a80-df18-11eb-8906-ab44b6579685.png)

## All states, including error
![Screen Shot 2021-07-07 at 11 33 01 AM](https://user-images.githubusercontent.com/31663028/124789296-2c472000-df18-11eb-9d3b-9ad76b990cf1.png)
