### ISSUE TITLE
Finalize content for committee profile page data feature 

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4672]
**What we're after:**
We need to finalize the content for the committee snapshot feature and the glossary terms we plan to include. 

Content included:
- [ ] Feature title
- [x] Raising and spending blurbs per committee type (no longer doing this)
- [ ] Glossary terms we plan to link
- [ ] Disclaimer language (at the bottom of the feature)

Send to OGC after language is drafted.

**Completion criteria:**
- [ ] Language is finalized from a content team perspective
- [ ] Language is finalized by OGC and shared with front-end for development

**Comment by JonellaCulmer** [comment]
Link to the draft content here: https://docs.google.com/document/d/1WqBnjD80G7_dBx4yy1LyEUgm6KixPe_B3LWDDxQmwZA/edit#

**Comment by JonellaCulmer** [comment]
@dorothyyeager @kathycarothers @djgarr 
We've cut the raising and spending blurbs for now and are relying on glossary links for information at this time. Want to make sure the rest of the language we plan on using is good from your perspective. Let me know what you think. I don't think any of this needs to go to OGC, do you?

**Feature title:** 
Committee snapshot

**Percentage descriptions and glossary terms we plan to link:** 
* Percent raised in individual contributions (glossary link).

* Percent raised in contributions (glossary link) from other federal political committees (glossary link)

* Percent spent on contributions to other federal committees (glossary link), independent expenditures (glossary link), and coordinated party expenditures (glossary link). 

* Percent spent on operating expenditures (glossary link).
* Error state for negative percentages, dividing by zero or null values: Could not calculate a percent based on available data

**Disclaimer language:** 
The percentages shown do not represent 100% of this committee’s activity. Refer to the tables that follow for a complete breakdown of raising and spending.

**Comment by djgarr** [comment]
The new information looks good to me

**Comment by dorothyyeager** [comment]
Me too. I don't think you need to go to OGC, as they are always OK with glossary links.
