### ISSUE TITLE
Design adjustments for PAC & Party datatable

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4674]
### What we're after
- Move coverage end date in details panel to financial section
- Consider adjusting committee type filters to match committees datatable?
- Add checkbox for IE filers?
- Make sure we include JFCs because some file on F3X

### Completion criteria
- Updates have been made, shared with PMs
- Any followup tickets have been opened

### Related PRs
#4653 

### Future work

_Other future work that may be needed following this issue's completion._

**Comment by JonellaCulmer** [comment]
@patphongs @AmyKort @PaulClark2 
Below are updated mockups of the PAC and party datatable. Let me know if you have any other suggested edits.
![Updated-DetailsPanel](https://user-images.githubusercontent.com/31663028/121536490-1b66c580-c9d1-11eb-8f11-479163eba8f4.jpg)
![Updated-PACParty-datatable](https://user-images.githubusercontent.com/31663028/121536492-1bff5c00-c9d1-11eb-8349-c5f54ee3b83f.jpg)

**Comment by patphongs** [comment]
@JonellaCulmer For the row details panel, I'd like to confirm a few things

1. Has the info icon been removed from filing frequency?
2. Has coverage date been removed?

If the answer to all those are yes, then that's ok with me. Once these are finalized, can you please update the [mock ups in the epic](https://github.com/fecgov/fec-epics/issues/204)?

**Comment by patphongs** [comment]
One more thing I noticed with the datatable sort @JonellaCulmer, I believe we decided to default sort on the "Receipts" column, like we have for other datatables. So it would be good to update that in the mock up too if you concur.

**Comment by JonellaCulmer** [comment]
@patphongs 

> Has the info icon been removed from filing frequency?

I'll add it back in and update the mockup.

> Has coverage date been removed?

It's at the top of the financials section in the details panel.

> I believe we decided to default sort on the "Receipts" column descending order, like we have for other datatables.

Fine by me, thanks! If you need that in the mock-up, I can update that as well. 

> Should we rename the "Cash on hand" filter to "Ending cash on hand" to be consistent with what's in the details panel?

@dorothyyeager @kathycarothers @PaulClark2 @AmyKort Thoughts on this?

**Comment by dorothyyeager** [comment]
It does seem like you should use "ending cash on hand" for consistency, but not sure if there is room since that's longer.

**Comment by kathycarothers** [comment]
I agree it does seem like we should use "ending cash on hand for consistency and makes more sense.

**Comment by JonellaCulmer** [comment]
@dorothyyeager @kathycarothers @patphongs I completely agree with consistency. So it should be the same in all places. The question, I suppose, is should it say "Ending cash on hand", or "Cash on hand" in all places?

**Comment by dorothyyeager** [comment]
@JonellaCulmer It's almost more a design choice. Adding "ending" might make the spacing weird. I don't think you need "ending" unless you have two types of cash on hand on the page - beginning and ending. Maybe we could say cash on hand in all places and if it's possible note somehow with an asterisk that we mean "Ending".

**Comment by patphongs** [comment]
@JonellaCulmer I've updated the code for the details panel to reflect these comments. Screenshot below. PR is in ready for review: https://github.com/fecgov/fec-cms/pull/4709.

![Screen Shot 2021-06-15 at 10 41 58 AM](https://user-images.githubusercontent.com/12799132/122074938-a841c280-cdc7-11eb-9304-c8598d45d615.png)

**Comment by JonellaCulmer** [comment]
Updated datatable version with ending cash on hand: 
![PACs datatable_endingcashonhand](https://user-images.githubusercontent.com/31663028/122291644-0a332280-cec3-11eb-86a2-631b69a34810.jpg)
