### ISSUE TITLE
Front-end: consume changes from API into datatable

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4675]
### Summary

**What we're after:**
_Briefly describe the goal or user story for this issue. Be sure to include any dependencies._

WIP PR for PAC/Party datatable: https://github.com/fecgov/fec-cms/pull/4653

### Completion criteria

_What does the end state look like? Include any behavior, appearance, etc required for this ticket to be 'complete.'_

### Tech steps or considerations
CMS is waiting to consume:
- easier
   - Committee type filter (NOT existing field -that’s more like category)
   - Min/Max receipts/disbursements/COH/debt filters
   - First file date output field
- Harder
   - Leadership pac sponsor output and filter (for the two year period)
   - Most recent treasurer output and filter (for the 2-year period)
   - State output and filter(for the two year period)
   - Filing frequency output and filter “” (openapi #4871)

_List any considerations the tech team should know. Additionally, any specific tech steps can be included here._

- [ ] First
- [ ] Next
- [ ] Then

**Comment by lbeaufort** [comment]
All the CMS work has been broken into individual tickets. This is now a duplicate.
