### ISSUE TITLE
Replace presidential map link

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4676]
### Summary

**What we're after:**
We're going to experiment with options to replace the card/cta for the presidential map link on the homepage

### Completion criteria

- The card to the presidential data has been replaced by results of experiments and design decisions

### Designs for first link
<img width="941" alt="Screen Shot 2021-06-08 at 2 34 11 PM" src="https://user-images.githubusercontent.com/31663028/121238927-a37c8c00-c866-11eb-8537-0cfe773fc10a.png">

**Comment by rfultz** [comment]
@JonellaCulmer, the experiments are live on Feature if you'd like to take a look. I'd like to finesse a bit.
TODO: actually tracking the clicks

**Comment by JonellaCulmer** [comment]
@rfultz Looks great so far. A few comments:
- For option #1, can we change the text to say: Compare candidates **in** federal elections
- For option #2, can we change the text to say: Search **all** campaign finance data
- The images and text don't seem to be matched up properly.

**Comment by rfultz** [comment]
The experiment is live!
