### ISSUE TITLE
Test redirects deployed in 14 innovation after that release is deployed

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4677]
### Summary

**What we're after:**
_We need to verify that redirects we implemented in 14 innovation are working._

### Related issues

_List any relevant related issue(s)_

- #4628 RAD Redirects 
- #4619 Transition Inventory from 14.6
- #4593 Matching funds
- #4691 AO Procedure doc (in the 15.1 tab of redirects but slipped into this release)

### Completion criteria

- [ ] Redirects implemented in the 14.inn release work.
- [x] Spreadsheet updated
- [ ] PR to fix any issues with transition redirects entered
- [ ] www redirect ticket put in as needed
- [ ] Take-down ticket put in as needed - This can be pushed back to 15.4 (DG)

**Comment by bmathesonFEC** [comment]
The 14.6 redirects and RAD FAQ redirects have been entered:

14.6 PR: https://github.com/fecgov/fec-proxy/pull/268
RAD FAQ PR: https://github.com/fecgov/fec-proxy/pull/267

I updated the issues to reflect that these are complete.

**Comment by kathycarothers** [comment]
It appears the matching funds submission redirects are not working.
