### ISSUE TITLE
Banner meeting

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4678]
### Summary

**What we're after:**
_Briefly describe the goal or user story for this issue. Be sure to include any dependencies._

### Related issues

_List any relevant related issue(s)_

- #[issue_number]
- #[issue_number]

### Completion criteria

_What does the end state look like? Include any behavior, appearance, etc required for this ticket to be 'complete.'_

### Tech steps or considerations (optional)

_List any considerations the tech team should know. Additionally, any specific tech steps can be included here._

- [ ] First
- [ ] Next
- [ ] Then

### Future work

_Other future work that may be needed following this issue's completion._

**Comment by dorothyyeager** [comment]
@rfultz our banner ticket for 15.1 is at https://github.com/fecgov/fec-cms/issues/4596 (it follows our usual format) so this ticket may be a duplicate. We don't really have banner meetings anymore unless someone wants to watch.

**Comment by dorothyyeager** [comment]
Closing in favor of #4596
