### ISSUE TITLE
Transition pages to take down (RAD FAQ and other 14.6 redirects) 

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#4683]
### Summary

What we're after:
To remove the outdated pages from transition now that the redirects are in place.

These were redirected in #4628 (RAD FAQ) and #4619 (14.6 transition inventory)

Completion criteria

- [ ] The following pages are removed from transition and from the search.gov index of transition pages _(if they are there)_.

/rad/index.html
/rad/candidates/FEC-ReportsAnalysisDivision-CandidateCommittees.shtml
/rad/parties/FederalElectionCommission-RAD-Parties.shtml
/rad/pacs/FederalElectionCommission-RAD-PACs.shtml
/rad/rad_process/FEC-ReportsAnalysisDivision-RADProcesses.shtml
/rad/other_filers/FederalElectionCommission-RAD-OtherFilers.shtml
/rad/JointFundraisingCommittees.shtml
/rad/internal_controls/InternalControlsQA.shtml
/rad/FederalElectionCommission-RAD-RespondingtoRFAIs.shtml
/rad/FEC-ReportsAnalysisDivision-Penalties.shtml
/rad/FederalElectionCommission-RAD-ElectronicFilingPasswords.shtml
/rad/documents/best_practices_to_avoid_pitfalls_2018.pdf
/pages/brochures/rad_brochure.pdf
/rad/BitcoinFAQ.shtml
/rad/documents/RADProcessDocument3-16-16.pdf
/finance/disclosure/adv-search.shtml

/info/limits_and_thresholds.shtml
/info/mis-sc.htm
/info/nprmintr.htm
/info/pacs.shtml
/info/parties.shtml
/info/plainwriting.shtml
/info/plainwriting041312.shtml
/info/plainwriting041313.shtml
/info/plainwriting071311.shtml
/info/plainwritingreport.shtml
/info/prim98.htm
/info/primref.htm
/info/recent_conference_materials.shtml
/info/report_dates_midterm6.shtml
/info/report_dates_midterm.shtml
/info/report_dates_non.shtml
/info/report_dates_non7.shtml
/info/sbrefa.htm
/info/sd-w.htm
/info/subj98.htm
/info/tips4treasurers.xml
/info/treas.htm
/info/tresur.htm

### Related issues

- #4677 Redirect test ticket

**Comment by rfultz** [comment]
All done! `/finance/disclosure/adv-search.shtml` was already gone
