### ISSUE TITLE
Update bad link to the Office of Government Ethics (OGE) presidential candidate financial disclosure reports

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#4711]
### Summary

The link to the Office of Government Ethics (OGE) presidential candidate financial disclosure reports is not working. The link is found on https://www.fec.gov/data/browse-data/?tab=external

### Completion criteria

- [x] Page at https://www.fec.gov/data/browse-data/?tab=external (hard coded page) is updated with the new link. The new link is https://www.oge.gov/web/oge.nsf/Officials%20Individual%20Disclosures%20Search%20Collection?OpenForm

![image](https://user-images.githubusercontent.com/40633757/121920349-f2626f80-cd05-11eb-89cd-990417533b6a.png)

- Note: new link should be sent to Information Division staff so they can update InfoWeb links.

**Comment by djgarr** [comment]
@prstoetzer Can you update InfoWeb with the link as well (https://www.oge.gov/web/oge.nsf/Officials%20Individual%20Disclosures%20Search%20Collection?OpenForm)?

**Comment by prstoetzer** [comment]
InfoWeb has been updated.
