### ISSUE TITLE
[July] - Manually update wagtail global search index

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4714]
## Summary
**What we're after:**
We need to update the global search.gov index for new pages that were published in July 2021

Related issues
#4645   

Completion criteria

- [x] Follow instructions under [Adding CMS pages to the index](https://github.com/fecgov/fec-cms/blob/develop/fec/search/management/instructions.md#adding-cms-pages-to-the-index)
- [x] Create ticket for June manual Wagtail global search index

**Comment by pkfec** [comment]
CMS pages scraped and indexed for July. 
<img width="1080" alt="Screen Shot 2021-07-19 at 1 30 29 PM" src="https://user-images.githubusercontent.com/11650355/126201936-f5d54ddf-3db7-4ec9-9497-f0b662e731b1.png">

**Comment by pkfec** [comment]
Still missing ability to see indexed totals based on this known-issue referenced in March/2021 issue.
