### ISSUE TITLE
Snapshot usability testing

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4716]
**What we're after:** We need to test the first iteration of the snapshot with users. Will attempt to find users who are less versed in campaign finance language, starting with those individuals who have signed up via the feedback form. 

**What we need to test:**
- Overall impressions
- Ease of use

**Action items:**
- Create testing slots on Ethn.io
- Draft and send emails
- Create interview guide
- Create invision prototype
- Update interview spreadsheet with new questions
- Solicit for notetakers
- Synthesize the research

**Completion criteria:**
- [x] Testing is complete
- [x] Research is synthesized
- [x] Followup design tickets are created as necessary

**Comment by JonellaCulmer** [comment]
Synthesis here: https://app.mural.co/t/fec4461/m/fec4461/1624914396151/439b2a8190f8576962eec2712b497f986fa58919?sender=jculmer4627
<img width="1080" alt="Screen Shot 2021-07-06 at 4 13 48 PM" src="https://user-images.githubusercontent.com/31663028/124661265-424fd480-de75-11eb-825f-044f6a935cb5.png">

**Comment by JonellaCulmer** [comment]
Followup tickets:
- Draft updated methodology
- Consider links on donuts to take users to the total receipts and total disbursements sections
