### ISSUE TITLE
Snapshot: donuts

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4717]
### Summary

From Mural: "Creation of animated donut feature"

### Related issues

_List any relevant related issue(s)_

- #[issue_number]
- #[issue_number]

### Completion criteria

_What does the end state look like? Include any behavior, appearance, etc required for this ticket to be 'complete.'_

### Tech steps or considerations (optional)

_List any considerations the tech team should know. Additionally, any specific tech steps can be included here._

- [ ] First
- [ ] Next
- [ ] Then

### Future work

_Other future work that may be needed following this issue's completion._

**Comment by lbeaufort** [comment]
Closing in favor of #4718
