### ISSUE TITLE
Redirect old disclosure page to CFD landing page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4720]
**What we're after:** A user reported on [Sun Jun 20 2021](https://github.com/fecgov/FEC/issues/10984) that the old data landing page (IT/public records) was 404ing. We need to create a redirect that link and send traffic to the new data landing page. 

Old link: https://www.fec.gov/disclosure.shtml 
Redirect link: https://www.fec.gov/data/

**Completion criteria:**
- [x] Page is successfully redirected to the data landing page on .gov

From the user:

## What were you trying to do and how can we improve it?
 trying to access the page 

## General feedback?
 Received a Page Noy Found message 

## Tell us about yourself
 I'm a voter interested in finance research 

## Details
* URL: https://www.fec.gov/disclosure.shtml 
* User Agent: Amazon CloudFront

**Comment by kathycarothers** [comment]
@patphongs @johnnyporkchops Is this a Wagtail redirect?

**Comment by johnnyporkchops** [comment]
@kathycarothers Yes, this can be done as a Wagtail redirect . Just redirect the relative path `/disclosure.shtml` to the full URL `https://www.fec.gov/data`

**Comment by johnnyporkchops** [comment]
Page is redirected:
![disclosure_redirect](https://user-images.githubusercontent.com/5572856/123847403-8f1b3480-d8e4-11eb-8a1d-33d1df4b314a.gif)
