### ISSUE TITLE
Candidate's Committee Information Not Showing Properly

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#4728]
### Summary

A candidate running in a 2021 special election is having a previously terminated and a current committee showing up on the candidate's page as current committees. Additionally, the candidate's 2008 information is not showing on the drop down menu along with the candidate's 2010 and 2022 information.

![image](https://user-images.githubusercontent.com/40633757/123655406-f1006f00-d7fc-11eb-8be5-4f9e30b5e90f.png)

### Completion Criteria
- [ ] Determine what might be causing the issue
- [ ] Fix issue

**Comment by PaulClark2** [comment]
Removed 1051120210264891330. 
![image](https://user-images.githubusercontent.com/11817734/123661829-ddf09d80-d802-11eb-96cb-6ecb033191a7.png)

We should see the updated information on the website tomorrow morning.
