### ISSUE TITLE
Design adjustments following data-design studio

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4735]
**What we're after:**
Following the [data-design studio](https://github.com/fecgov/fec-cms/issues/4734) feedback we need to make design adjustments to the mockups. 

**Action items:**
- [x] Consider reaching out to Press/Public Records for feedback on desired data points for horse race chart
- [x] Update designs for bar charts
- [x] Consider data points for cards and more details on navigating between cards

**Completion criteria:**
- [x] Designs are updated and shared with team

**Comment by patphongs** [comment]
We'll want to move this to 16.4 after we make the new milestones

**Comment by JonellaCulmer** [comment]
@patphongs @PaulClark2 @AmyKort 

Please see the below updated designs for House pages following data-design studio and Press/Public Records feedback. Would love to discuss this further, there are some areas with details that still need to be determined/clarified, such as: 
- Data points for special election cards
- Can we calculate the "average contribution size" per candidate
- Need to determine what kind year limit we may want to set for the contributions across time bar charts
- Data points for election data cards
- Do we want to show dollar amounts or a total percentage for expenditure type
- Can we get a list of expenditures by type such as marketing, advertising, staff salaries, swag, graphic/web design, etc

![House_elections_page](https://user-images.githubusercontent.com/31663028/143169484-b532e68e-4374-418c-bd9a-41b02ca754ae.jpg)

**Comment by PaulClark2** [comment]
We can calculate the average. I don't know what overhead this calculation will create. I did this in FECP using the `is_individual` transaction types. For our information, I also included median and mode. 

ID	|	Name	|	Two-year period	|	Average(mean) contribution amount	|	Median contribution amount	|	Contribution amount mode
----	|	----	|	----	|	----	|	----	|	----
C00630426	|	JON OSSOFF FOR CONGRESS	|	2018	|	72.61	|	25	|	50
C00631945	|	GREG FOR MONTANA	|	2018	|	784.71	|	300	|	250
C00330894	|	RYAN FOR CONGRESS, INC.	|	2018	|	603.93	|	100	|	100

```
select cm.cmte_id, cm.cmte_nm, cm.fec_election_yr,
round(avg(fi.transaction_amt),2) as average_contribution, 
median(fi.transaction_amt) as median_contribution, 
STATS_MODE(fi.transaction_amt) as mode_contribution 
---round(STDDEV(fi.transaction_amt),2) as standard_deviation
from DISCLOSURE.F_ITEM_RECEIPT_OR_EXP fi, DISCLOSURE.CMTE_VALID_FEC_YR cm 
where fi.cmte_id = cm.cmte_id
and cm.fec_election_yr = 2018
and cm.cmte_id in ('C00630426', 'C00330894', 'C00631945')
and cm.cmte_tp = 'H'
and cm.cmte_dsgn = 'P'
and fi.rpt_yr in (2017, 2018)
and fi.transaction_tp in ('10', '10J', '11', '11J', '15', '15E', '15J', '30', '30J', '30T', '31', '31J', '31T', '32', '32J', '32T')
group by cm.cmte_id, cm.cmte_nm, cm.fec_election_yr;
```

**Comment by patphongs** [comment]
@JonellaCulmer Thanks for showing me these designs the other day, I also really like them! 

Looks like you incorporated linking the candidate contributions dollar figures feedback I had yesterday. The only other thing that I think we should think about is what the max for the "How candidates are spending" radio rings will look like. I think having a full circle ring that is the total of all candidate spending may be an interesting comparison with the other expenditure types. For example, I could compare that of the [$294,177,110](https://www.fec.gov/data/spending-bythenumbers/) total spending by all House candidates running in 2022, $x,xxx,xxx of that was operating expenditures for all House candidates running in 2022.

**Comment by JonellaCulmer** [comment]
Updated designs. These are not finished yet. We will need to devote more time to them when we get to thinking through packages and breaking out tickets. Additional conversations need to happen around feasibility and final desired states, but this is much closer to where we want to go. 

![Desktop Copy 12](https://user-images.githubusercontent.com/31663028/144620540-e052d447-27b4-46f8-925d-d6ba036b7338.jpg)
