### ISSUE TITLE
Remove tooltips from PAC/Party data table

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#4737]
### Summary

**What we're after:**
There are `i` tooltips on the filter panel and flyout panel several terms listed below. We should finalize the language and update it.

- Filing frequency
- Independent expenditure committees
- PACs
- Party committees
- Individual contributions
- Ending cash on hand

### Completion criteria

- [ ] Determine language to use for tooltips starting with the glossary definition - may need to be more succinct than glossary definition. Use "Inspect" to preview how it will look.
- [ ] If modifying glossary language, circulate with OGC
- [ ] Consider removing the tooltip if we're not going to be able to make progress and split it into future ticket
- [ ] Put in a ticket to make the changes

**Comment by patphongs** [comment]
@JonellaCulmer I'm assuming that since we're removing the tooltips from the filter panel, we also want to remove it from the details panel?

![Screen Shot 2021-07-19 at 10 44 42 AM](https://user-images.githubusercontent.com/12799132/126178993-0b2e840f-14d6-40a0-9043-45b759487328.png)
