### ISSUE TITLE
[Delete after 7/27 deploy] Transition pages to take down (15.3 redirects and matching funds pages)

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#4739]
### Summary

What we're after:
To remove the outdated pages from transition now that the redirects are in place.

These were redirected in #4628 (RAD FAQ) and #4619 (14.6 transition inventory)

Completion criteria

- [x] The following pages are removed from transition and from the search.gov index of transition pages _(if they are there)_.

**15.3 Redirects missed from previous rounds of redirects **
/rad/internal_controls/InternalControlsQA.shtml
/about/offices/org_chart.shtml
/af/index.shtml

**15.3 Redirects, identified in 7/13 transition inventory meeting**
/law/cfr/cfr_2009.pdf
/law/cfr/cfr_2008.pdf
/law/cfr/2014cfr.pdf
/law/cfr/11cfr2015.pdf
/law/cfr/11_cfr.pdf
All files of this name pattern /law/cfr/ej_citation_*.shtml

**Matching Funds**
- Delete files noted in this [spreadsheet](https://docs.google.com/spreadsheets/d/1vzN-wZlS8K8ZyfExSV3hwXDenDEN9KyyAUJFTI6OjKU/edit#gid=743177583) 🔒  EXCEPT for matching fund zip files

### Related issues

- #4677 Redirect test ticket

**Comment by patphongs** [comment]
Thu Jul 29 15:01:49 EDT 2021
delete: '/about/offices/org_chart.shtml'
delete: '/af/index.shtml'
delete: '/finance/2004matching/clark_docs_001.pdf'
delete: '/finance/2004matching/clark_sub_001.xls'
delete: '/finance/2004matching/dean_docs_001.pdf'
delete: '/finance/2004matching/dean_sub_001.pdf'
delete: '/finance/2004matching/dean_sub_001.xls'
delete: '/finance/2004matching/edwards_docs_001.pdf'
delete: '/finance/2004matching/edwards_sub_001.xls'
delete: '/finance/2004matching/gephardt_docs_001.pdf'
delete: '/finance/2004matching/gephardt_sub_001.xls'
delete: '/finance/2004matching/kucinich_docs_001.pdf'
delete: '/finance/2004matching/kucinich_sub_001.xls'
delete: '/finance/2004matching/larouche_docs_001.pdf'
delete: '/finance/2004matching/larouches_sub_001.xls'
delete: '/finance/2004matching/lieberman_docs_001.pdf'
delete: '/finance/2004matching/lieberman_sub_001.xls'
delete: '/finance/2004matching/matching.html'
delete: '/finance/2004matching/matching.shtml'
delete: '/finance/2004matching/nader_docs_001.pdf'
delete: '/finance/2004matching/nader_sub_001.xls'
delete: '/finance/2004matching/sharpton_docs_001.pdf'
delete: '/finance/2004matching/sharpton_sub_001.xls'
delete: '/finance/2008matching/2008matching.shtml'
delete: '/finance/2008matching/biden_docs_001.pdf'
delete: '/finance/2008matching/biden_threshold.xls'
delete: '/finance/2008matching/dodd_docs_001.pdf'
delete: '/finance/2008matching/dodd_threshold.xls'
delete: '/finance/2008matching/edwards_docs_001.pdf'
delete: '/finance/2008matching/edwards_threshold.xls'
delete: '/finance/2008matching/gravel_docs_001.pdf'
delete: '/finance/2008matching/gravel_threshold.xls'
delete: '/finance/2008matching/hunter_docs_001.pdf'
delete: '/finance/2008matching/hunter_threshold.xls'
delete: '/finance/2008matching/kucinich_docs_001.pdf'
delete: '/finance/2008matching/kucinich_threshold.xls'
delete: '/finance/2008matching/mccain_docs_001.pdf'
delete: '/finance/2008matching/mccain_threshold.xls'
delete: '/finance/2008matching/nader_docs_001.pdf'
delete: '/finance/2008matching/nader_threshold.xls'
delete: '/finance/2008matching/tancredo_docs_001.pdf'
delete: '/finance/2008matching/tancredo_threshold.xls'
delete: '/finance/2012matching/2012matching.shtml'
delete: '/finance/2012matching/JohnsonSubmission1.xlsx'
delete: '/finance/2012matching/JohnsonSubmission2.xlsx'
delete: '/finance/2012matching/JohnsonSubmission3-4.xlsx'
delete: '/finance/2012matching/JohnsonSubmission5-6.xlsx'
delete: '/finance/2012matching/JohnsonSubmission7.xlsx'
delete: '/finance/2012matching/RoemerSubmission1.xlsx'
delete: '/finance/2012matching/RoemerSubmission2.xlsx'
delete: '/finance/2012matching/SteinSubmission1.xlsx'
delete: '/finance/2012matching/SteinSubmission2.xlsx'
delete: '/finance/2012matching/SteinSubmission3.xlsx'
delete: '/finance/2012matching/johnson_docs_001.pdf'
delete: '/finance/2012matching/johnson_threshold.xls'
delete: '/finance/2012matching/roemer_docs_001.pdf'
delete: '/finance/2012matching/roemer_threshold.xls'
delete: '/finance/2012matching/stein_docs_001.pdf'
delete: '/finance/2012matching/stein_threshold.xls'
delete: '/finance/2016matching/OMalleySubmission1.xls'
delete: '/finance/2016matching/OMalleySubmission2.xlsx'
delete: '/finance/2016matching/OMalleySubmission3.xls'
delete: '/finance/2016matching/SteinSubmission1.xlsx'
delete: '/finance/2016matching/SteinSubmission2.xlsx'
delete: '/finance/2016matching/SteinSubmission3.xlsx'
delete: '/finance/2016matching/SteinSubmission4.xlsx'
delete: '/finance/2016matching/omalley_docs_001.pdf'
delete: '/finance/2016matching/omalley_threshold.xls'
delete: '/finance/2016matching/stein_docs_001.pdf'
delete: '/finance/2016matching/stein_threshold.xlsx'
delete: '/finance/disclosure/2004MatchingFundSubmissions.shtml'
delete: '/finance/disclosure/2016MatchingFundSubmissions.shtml'
delete: '/finance/disclosure/2020presidentialmatchingfundsubmissions.shtml'
delete: '/finance/disclosure/presidential_matching_fund_submissions_2004_present.shtml'
delete: '/law/cfr/11_cfr.pdf'
delete: '/law/cfr/11cfr2015.pdf'
delete: '/law/cfr/2014cfr.pdf'
delete: '/law/cfr/cfr_2008.pdf'
delete: '/law/cfr/cfr_2009.pdf'
delete: '/law/cfr/ej_citation_part100_subpartA.shtml'
delete: '/law/cfr/ej_citation_part100_subpartA_2.shtml'
delete: '/law/cfr/ej_citation_part100_subpartsBC.shtml'
delete: '/law/cfr/ej_citation_part100_subpartsDE.shtml'
delete: '/law/cfr/ej_citation_part101.shtml'
delete: '/law/cfr/ej_citation_part102.shtml'
delete: '/law/cfr/ej_citation_part103.shtml'
delete: '/law/cfr/ej_citation_part104.shtml'
delete: '/law/cfr/ej_citation_part105.shtml'
delete: '/law/cfr/ej_citation_part106.shtml'
delete: '/law/cfr/ej_citation_part108.shtml'
delete: '/law/cfr/ej_citation_part109.shtml'
delete: '/law/cfr/ej_citation_part110a.shtml'
delete: '/law/cfr/ej_citation_part110b.shtml'
delete: '/law/cfr/ej_citation_part111.shtml'
delete: '/law/cfr/ej_citation_part112.shtml'
delete: '/law/cfr/ej_citation_part113.shtml'
delete: '/law/cfr/ej_citation_part114.shtml'
delete: '/law/cfr/ej_citation_part115.shtml'
delete: '/law/cfr/ej_citation_part116.shtml'
delete: '/law/cfr/ej_citation_part300.shtml'
delete: '/law/cfr/ej_citation_part300_subpartsAB.shtml'
delete: '/law/cfr/ej_citation_part300_subpartsCDE.shtml'
delete: '/law/cfr/ej_citation_part400_subpartsAB.shtml'
delete: '/law/cfr/ej_citation_part400_subpartsCDE.shtml'
delete: '/law/cfr/ej_citation_part9003.shtml'
delete: '/law/cfr/ej_citation_part9004.shtml'
delete: '/law/cfr/ej_citation_part9008.shtml'
delete: '/law/cfr/ej_citation_part9034.shtml'
delete: '/law/cfr/ej_citation_parts1-8.shtml'
delete: '/law/cfr/ej_citation_parts107_120-129.shtml'
delete: '/law/cfr/ej_citation_parts130-134.shtml'
delete: '/law/cfr/ej_citation_parts140_146.shtml'
delete: '/law/cfr/ej_citation_parts200-201.shtml'
delete: '/law/cfr/ej_citation_parts9001_9002.shtml'
delete: '/law/cfr/ej_citation_parts9005_9012.shtml'
delete: '/law/cfr/ej_citation_parts9031-9033.shtml'
delete: '/law/cfr/ej_citation_parts9035-9037.shtml'
delete: '/law/cfr/ej_citation_parts9038-9039.shtml'
delete: '/rad/internal_controls/InternalControlsChecklist.shtml'
