### ISSUE TITLE
Homepage A/B experiment follow-up (meet 7/22)

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4740]
**What we're after:** We need to follow up on https://github.com/fecgov/fec-cms/issues/4676 where we tested new images and links to improve access to high-level H/S data. 

**Action items:**
- Schedule meeting for Thursday, 7/22 to:
  - check findings
  - look at page flow
  - make changes
  - adjust and/or remove experiment(s)

**Completion criteria:**
- [x] Based on findings, document and take appropriate next steps to determine what changes should be made the home page

**Comment by JonellaCulmer** [comment]
Followup docs:
**Preliminary results**
https://docs.google.com/document/d/1rQFSMrlaS_Pi1FuSz_NmU2yugTA9_FxsW30a88nZ8Lw/edit

**"Final" results"**
https://docs.google.com/spreadsheets/d/1IPOx-CA07UnDGhMWur7Wfu45TL0I2ktv1HkyOjdpBzQ/edit#gid=0
