### ISSUE TITLE
Draft new glossary terms for snapshot

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4759]
**What we're after:**
Each of the committees below don't currently exist in the glossary. These committees are, however, included in the snapshot we are building. This ticket is to create glossary terms so that we can link to the glossary from the snapshot. 

**New terms needed:**
- Cooperatives
- Corporations without capital stock
- Single candidate independent expenditure filer

**Completion criteria:**
- [x] Glossary terms are drafted 
- [x] Glossary terms are circulated to OGC for approval
- [x] Make a follow up ticket to update glossary with new terms (#4793)

**Comment by djgarr** [comment]
Glossary terms sent to OGC for review. Follow up ticket #4793 created for next step
