### ISSUE TITLE
After 15.3 release: Test all redirects implemented in 15.3 release (and hard coded page) 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#4760]
### Summary

**What we're after:**
We are getting off of transition.

### Related issues

- #4594
- #4738 
- #4762 

### Completion criteria

- [x] Redirects work
- [x] Non-working redirects Pat flagged in this comment are deleted.
- [x] [Spreadsheet](https://docs.google.com/spreadsheets/d/1vzN-wZlS8K8ZyfExSV3hwXDenDEN9KyyAUJFTI6OjKU/edit#gid=0) updated (Matching funds submission 2) - this had already been done.
- [x] 15.3 redirects / previously missed redirects ([spreadsheet](https://docs.google.com/spreadsheets/d/1vzN-wZlS8K8ZyfExSV3hwXDenDEN9KyyAUJFTI6OjKU/edit#gid=1565874220))
- [x] Redirected pages added to a take-down ticket (include earlier matching funds submissions to be removed now with this tickets) 
- [x] www redirects / Wagtail redirects have been added as needed to a PR and a testing ticket
- [x] Test Link on hard-coded data page is put into place and tested (https://www.fec.gov/data/browse-data/?tab=candidates)
- [x] Take down ticket

**Comment by dorothyyeager** [comment]
www PR submitted at https://github.com/fecgov/fec-proxy/pull/279 and linked to this issue. We can close this ticket after that PR is merged.
Testing ticket at #4799

**Comment by dorothyyeager** [comment]
Merged, so closing.
