### ISSUE TITLE
Transition pages to take down in 15.4

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#4761]
### Summary

To remove the outdated pages from transition now that the redirects are in place. 
### Related issues

- #4618 

### Completion criteria

- [ ] The following pages are removed from transition:

/jpg/backgrounders.jpg
/jpg/backgrounders2.jpg
/jpg/backgrounders3.jpg
/jpg/bdot.jpg
/jpg/bkg.jpg
/jpg/bluepapr.jpg
/jpg/blueston.jpg
/jpg/btopfec.jpg
/jpg/cand.jpg
/jpg/cart.jpg
/jpg/fec_small.jpg
/jpg/fec.jpg
/jpg/fec1.jpg
/jpg/fec2.jpg
/jpg/fec3.jpg
/jpg/fec6.jpg
/jpg/fec300.jpg
/jpg/fecicon.jpg
/jpg/fecltr.jpg
/jpg/flagus.gif
/jpg/forms.jpg
/jpg/hava_banner.jpg
/jpg/hlp.jpg
/jpg/new.jpg
/jpg/pac.jpg
/jpg/party.jpg
/jpg/question.jpg
/jpg/smfec1.jpg
/jpg/Thumbs.db
/jpg/topfec.jpg
/jpg/usflg.jpg
/jpg/ytopfec.jpg

/law/cfr/ej_0305.pdf
/law/cfr/cfr.shtml

/law/cfr/ej_compilation.pdf
/law/cfr/ej_toc.shtml

**Comment by patphongs** [comment]
These files have been deleted:

Tue Aug 3 11:38:39 EDT 2021
delete: '/jpg/Thumbs.db'
delete: '/jpg/backgrounders.jpg'
delete: '/jpg/backgrounders2.jpg'
delete: '/jpg/backgrounders3.jpg'
delete: '/jpg/bdot.jpg'
delete: '/jpg/bkg.jpg'
delete: '/jpg/bluepapr.jpg'
delete: '/jpg/blueston.jpg'
delete: '/jpg/btopfec.jpg'
delete: '/jpg/cand.jpg'
delete: '/jpg/cart.jpg'
delete: '/jpg/fec.jpg'
delete: '/jpg/fec1.jpg'
delete: '/jpg/fec2.jpg'
delete: '/jpg/fec3.jpg'
delete: '/jpg/fec300.jpg'
delete: '/jpg/fec6.jpg'
delete: '/jpg/fec_small.jpg'
delete: '/jpg/fecicon.jpg'
delete: '/jpg/fecltr.jpg'
delete: '/jpg/flagus.gif'
delete: '/jpg/forms.jpg'
delete: '/jpg/hava_banner.jpg'
delete: '/jpg/hlp.jpg'
delete: '/jpg/new.jpg'
delete: '/jpg/pac.jpg'
delete: '/jpg/party.jpg'
delete: '/jpg/question.jpg'
delete: '/jpg/smfec1.jpg'
delete: '/jpg/topfec.jpg'
delete: '/jpg/usflg.jpg'
delete: '/jpg/ytopfec.jpg'
delete: '/law/cfr/cfr.shtml'
delete: '/law/cfr/ej_0305.pdf'
delete: '/law/cfr/ej_compilation.pdf'
delete: '/law/cfr/ej_toc.shtml'
