### ISSUE TITLE
Address the E&J appendix by redirecting or retiring

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#4762]
### Summary

We are getting off transition.

### Related issues

- #4618 
- #4761 

### Completion criteria

~- [ ] Items identified in our 15.4 transition meeting are redirected.~ No meeting in 15.4
- [x] Contact OGC about the E&J appendix
- [ x] Put in redirects and dump the appendix or retain the transition site and make a decision on migration, as they wish
~- [ ] Spreadsheet updated~

**Comment by bmathesonFEC** [comment]
Committed redirects that were identified in the meeting:
2008, 2009, 2010, 2014, 2015 CFR pdfs.
Broader redirect for /law/cfr/ej_citation_*.shtml

I'm not closing this ticket because there are some other redirect candidates that are dependent on asking other offices.

**Comment by dorothyyeager** [comment]
Nudged OGC on August 9 and offered to do a call.

**Comment by dorothyyeager** [comment]
OGC does not want to retire the appendix. So there won't be redirecting to do as of now, but we'll need to decide whether it should live on transition forever or whether we should make a migration ticket. For now I'll close this ticket and put in a research ticket regarding what would be involved for migration.
