### ISSUE TITLE
Create regulation CFR archive page

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#4764]
### Summary
FEC.gov > [Regulations](https://www.fec.gov/legal-resources/regulations/) links directly to the current version of the regulations in several formats eCFR, PDF, XML, and text; however, we do not have an archive that links to past versions of the CFR.

**Decisions:** 
- Create a regs landing page or add an archive at the bottom of the [Regs landing page](https://www.fec.gov/legal-resources/regulations/)?
- link to this govinfo page that lists all of the CFRs docs (organized by year) or we have multiple links on our site that link directly to the CFR pdf for a given year. Or both?!

### Completion Criteria
- [x] Decide on how to proceed with an archive
- [x] Download CFR documents from GPO upload into Wagtail (if necessary) - We will just link to GPO.
- [x] Create wagtail page for the CFR archive or add it to the regs landing page - We will add to regs page.

**Comment by dorothyyeager** [comment]
I've set up a page in feature and will show it to OGC when their schedule permits. Have shown it to content team and Jonella and all are OK with it.

**Comment by dorothyyeager** [comment]
I've sent OGC a screencap of the new table. If they don't raise any objections, will plan to publish on Monday.

**Comment by dorothyyeager** [comment]
OGC likes it and we can go ahead and publish it. I should have it done by end of this sprint.

**Comment by dorothyyeager** [comment]
Thank you to @prstoetzer for being my second pair of eyes. The new 11 CFR archive chart has been published at https://www.fec.gov/admin/pages/6682/edit/preview/#go-to-11-cfr.
