### ISSUE TITLE
QA for PAC/Party datatable

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#4765]
**What we're after:**
Before launching the new PAC and party datatable, we need to perform quality assurance testing to ensure everything is working. 

**Completion criteria:**
- [x]  All datatable filters are functioning correctly
- [x]  All accordions are functioning correctly
- [x] Draft and get language approved by content for the committees browse data page datatable: https://dev.fec.gov/data/browse-data/?tab=committees **(Language in following comment)**
- [x]  Committee row details panel appears as expected
   - [x] Leadership PAC sponsor appears in the committee details panel as expected (backend work was completed for this: https://github.com/fecgov/openFEC/issues/4879)

**Comment by JonellaCulmer** [comment]
Language for [committees browse data page](https://dev.fec.gov/data/browse-data/?tab=committees):

**Political action and party committees**
Search for political action and party committees by type, state or territory, treasurer, sponsor and filing frequency.

**Comment by patphongs** [comment]
Checked all the filters and they appear to work:

✅  COMMITTEE NAME OR ID
✅  TIME PERIOD
✅  INDEPENDENT EXPENDITURE COMMITTEES
✅  PACS
✅  LEADERSHIP PAC SPONSOR
✅  PARTIES
✅  OTHER COMMITTEES
✅  TOTAL DISBURSEMENTS
✅  ENDING CASH ON HAND
✅  DEBTS OWED BY COMMITTEE

@JonellaCulmer If you have time to test as well, please feel free. I have a [PR](https://github.com/fecgov/fec-cms/pull/4783) in to modify the content for the committees browse data PAC and party datatable language link.

**Comment by JonellaCulmer** [comment]
@patphongs Went through the checklist and everything works and appears as expected.
