### ISSUE TITLE
Update "Other committees" label on specified datatables

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4766]
**What we're after:**
To make it more accurate, we need to update the committee type filter, Other committees, say "Other committees and filers" since not all in the list are committees. 

Update label on these tables: https://github.com/fecgov/fec-cms/issues/4766#issuecomment-892103033

Filter that needs fixing: 
![Screen Shot 2021-07-14 at 2.13.15 PM.png](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/f215b096-5921-415c-805a-f6761729eadd)

**Completion criteria:**
- [ ] Filter label now says `Other committees and filers` on committees datatable
- [ ] Filter label now says `Other committees and filers` on PAC/Party datatable

**Comment by patphongs** [comment]
@JonellaCulmer We actually have the "OTHER COMMITTEES" filter label in several place datatables across the site. Can you please let me know which ones you would like this new label applied to?

- https://www.fec.gov/legal-resources/enforcement/audit-search/
- https://www.fec.gov/data/committees/
- https://dev.fec.gov/data/committees/pac-party/
- https://www.fec.gov/data/disbursements/
- https://www.fec.gov/data/receipts/
- https://www.fec.gov/data/receipts/individual-contributions/

**Comment by JonellaCulmer** [comment]
@patphongs We should update the label on the following tables. I don't think we need to add it to the PAC/party table anymore because we've removed the other filter options that were not committees. 
- https://www.fec.gov/data/committees/
- https://www.fec.gov/data/disbursements/
- https://www.fec.gov/data/receipts/
- https://www.fec.gov/data/receipts/individual-contributions/
