### ISSUE TITLE
Convert certain party H4CC pages into the resource template

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4771]
### Summary

**What we are after:**
After inventorying the party pages in H4CC, we noticed that a number of the pages were long and, in their current custom page template, required a lot of scrolling a searching to get to certain pieces of information. In an effort to make some of our information easier to locate on the page, we determined that a number of pages that could utilize the resource template.

### Related issues

_List any relevant related issue(s)_

- #4772 - party pages to resource and compare to candidate version
- #4773  - party pages to resource with coordination info we can consolidate into a button/link

### Completion criteria

- [x] Create the resource pages for the following:
Donations of Levin funds to state and local party committees: https://www.fec.gov/help-candidates-and-committees/taking-receipts-political-party/levin-funds-political-party-committees/
Volunteer activity for party committees: https://www.fec.gov/help-candidates-and-committees/taking-receipts-political-party/volunteer-activity-party/
Exempt party activities: https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/exempt-party-activities/
Definition of Federal Election Activity (FEA) | https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/definition-federal-election-activity-fea/
- [x] Second pair of eyes 
- [x] Ping front end team to update the page templates for these pages to resource pages and insert the content copied from the newly created resource pages
~- [ ] Wagtail redirects are put in for the old page to the new pages.~
- [x]  Delete dummy resources pages in Wagtail once front end team has converted the pages

| Custom page (currently live) | New resource page content |
| ---------------------------- | ---------------------------- |
| https://www.fec.gov/help-candidates-and-committees/taking-receipts-political-party/levin-funds-political-party-committees/ (ID 9167) |  https://www.fec.gov/admin/pages/12014/view_draft/ |
| https://www.fec.gov/help-candidates-and-committees/taking-receipts-political-party/volunteer-activity-party/ (ID 8674) | https://www.fec.gov/admin/pages/12023/view_draft/ |
| https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/exempt-party-activities/ (ID 8168) | https://www.fec.gov/admin/pages/12018/view_draft/ |
| https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/definition-federal-election-activity-fea/ (ID 8177) | https://www.fec.gov/admin/pages/12024/view_draft/ |

We would take a similar approach to these template changes as we did for the [OIG landing page](https://github.com/fecgov/fec-cms/issues/4318).

**Comment by kathycarothers** [comment]
I have sent this around to the content team for review. Step two-second pair of eyes.

**Comment by kathycarothers** [comment]
@patphongs @johnnyporkchops @rfultz We are ready for the final step of this ticket to publish the pages and front end to work their magic. I was going to work with John on publishing the pages. John is out for this week, so I plan to push this ticket to 15.5, so we can collaborate on it together.

**Comment by johnnyporkchops** [comment]
@kathycarothers The pages have been moved to ResourcePages. Please take a look at the pages and confirm they are correct.

**Comment by kathycarothers** [comment]
Pages converted, so I am closing this ticket.
