### ISSUE TITLE
Convert certain party H4CC pages to resource template and incorporate material from candidate pages

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4772]
### Summary

**What we are after:**
After inventorying the party pages in H4CC, we noticed that a number of the pages were long and, in their current custom page template, required a lot of scrolling a searching to get to certain pieces of information. In an effort to make some of our information easier to locate on the page, we determined that a number of pages that could utilize the resource template. 

We also noticed that the candidate and party versions of some pages differ and the candidate versions may be more useful. This ticket will identify things from the candidate pages that might improve the party pages.

### Related issues

#4385 - Inventory party pages
#4771 - The simple ones that are just converting to resource template, 15.4

### Action Items
- [ ] Types of contributions to party committees: https://www.fec.gov/help-candidates-and-committees/taking-receipts-political-party/contributions-party-committees/ (create a resource template page using page's content first, then compare it to similar page in candidate section (https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/types-contributions/) to see if information should be blended together with candidate page)
- [ ] Who can and can't contribute to a party committee: https://www.fec.gov/help-candidates-and-committees/taking-receipts-political-party/who-can-and-cant-contribute-party-committee/ (create a resource template page using page's content first, then compare it to similar page in candidate section (https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/who-can-and-cant-contribute/) to see if information should be blended together with candidate page)
- [ ] Consider suggestion from @zsmith-fec :
_Also, the Act and Commission regulations have specific language regarding which national party committees share the extra contribution limit to senate campaigns. I noticed that this language is removed on the general contributions page and the party contribution page. I’d like to recommend that the language be edited to fall closer what the Act allows. 

FYI, OGC approved the following for the party guide: “The Democratic and Republican national committees share this limit with their parties’ national Senate campaign committees. 110.2(e).”_

- [ ] Draft any new content and send around to content team.
- [ ] If OGC approval is needed, send to OGC.
- [ ] Once approved, add new content to pages

### Completion Criteria
- [ ] Pages listed above are converted to resource template
- [ ] New content is approved by content 
- [ ] New content is approved by OGC (if needed)
- [ ] Wagtail redirects are put in for new pages

**Comment by kathycarothers** [comment]
Closing ticket in lieu of party guide updates that will be taking place.
