### ISSUE TITLE
Wagtail wish list: Add example paragraph feature to the resource template 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#4777]
### Summary

**What we're after:**
_Would like the ability to add examples to the resource template - example paragraph feature. 

For example, this feature is available on the custom template:
![image](https://user-images.githubusercontent.com/32739251/126223479-01020853-b824-4e4a-8da0-27a5ac37e022.png)

![image](https://user-images.githubusercontent.com/32739251/126223549-4daf1c86-a791-4b0a-98a9-98d294232149.png)

### Completion criteria

- [ ] We would like the same for the resource template

![image](https://user-images.githubusercontent.com/32739251/126223879-a93167f4-dd3c-4b24-9c4e-cb6fe5f2627d.png)

**Comment by patphongs** [comment]
Moving to 15.6 due to bandwidth constraints
