### ISSUE TITLE
Update candidates browse data page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4778]
**What we're after:**
As part of our efforts to improve access to high-level House and Senate data, we need to make changes to the Candidates browse data page. Specifically, we need to add cards to the Raising: by the numbers pages to pre-filtered links for House and Senate candidate information. 

**Completion criteria:**
- [x] Add raising by the numbers cards to the Senate and House sections. (Link to https://www.fec.gov/data/raising-bythenumbers/?office=S for Senate and https://www.fec.gov/data/raising-bythenumbers/?office=H for House)
- [x] Update the "Compare candidates in the 2020 election" card to 2024 (hard-coded)
- [x] Move "Learn how this information is compiled" link to the inside-bottom the presidential data exports accordion. 

### Designs
![Candidates_browsedata](https://user-images.githubusercontent.com/31663028/126162125-f3fd081d-9a43-4af8-b7d4-3ccba0a1c41d.png)
![Screen Shot 2021-07-19 at 8 36 15 AM](https://user-images.githubusercontent.com/31663028/126160667-a8dc4554-79ad-4bbd-9b0e-169e48dab866.png)

**Comment by patphongs** [comment]
@JonellaCulmer Could you please provide an SVG of the graph primary contrast icon you have in your comp in order to incorporate it within the raising by the numbers cards.

![Screen Shot 2021-08-04 at 3 25 53 PM](https://user-images.githubusercontent.com/12799132/128242663-675bef02-f4e6-4139-8a59-0ce73f7692b3.png)

**Comment by JonellaCulmer** [comment]
@patphongs The icon is on the data landing page here: https://www.fec.gov/data/ on the raising and spending cards Do you still need me to provide it in the turquoise color?

**Comment by patphongs** [comment]
> Do you still need me to provide it in the turquoise color?

Yes I'll still need the turquoise SVG for the image icon. The alternate background cards I'm using aren't dynamic like the regular horizontal cards. It'll need to be exported from Sketch I think, similar to how [this was done](https://www.fec.gov/static/img/i-elections--primary-contrast.svg).
