### ISSUE TITLE
Handle null political party result in committees datatable details panel display

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4779]
### Summary

**What we're after:**
_Sometimes there is no political party attached to a committee. We should determine what should be displayed if this is the case._

![Screen Shot 2021-07-20 at 11 22 44 AM](https://user-images.githubusercontent.com/12799132/126351647-242f5d2f-336f-4e4d-aed8-6ea48b4d13fc.png)

Action item: 
- Consider whether we need to meet about this

### Completion criteria

- [x] Explore the options and decide what to do, other than null, for displaying political party when there is none. 
- [x] Followup implementation ticket is created

**Comment by JonellaCulmer** [comment]
Considerations: There are cases of committees that register as a party but are not recognized yet by the FEC as a political party. This may not be a clean solution so we need to consider all the possibilities and edge cases.

**Comment by dorothyyeager** [comment]
H4CC page for people who want to start a new political party. A lot goes into actually being a party. https://www.fec.gov/help-candidates-and-committees/registering-political-party/qualifying-as-a-political-party-committee/

**Comment by JonellaCulmer** [comment]
Rather than find language to explain the missing information, we're going to remove the line whenever the data is null. 

In the future, we should consider better ways to explain other codes like Unknown and Other to help add more clarity to this field. A separate ticket will be opened for that work.

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation ticket https://github.com/fecgov/fec-cms/issues/4850
