### ISSUE TITLE
Research gender neutral language for H4CC pages 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#4784]
### Summary

**What we're after:**
To better serve our community we need to update our gender language to be more gender-neutral on the H4CC pages. The trend is to move towards gender-neutral messaging.  

### Completion criteria

_We will need to complete the following steps_

- [x] Research gender-neutral language on other government websites. The more favored word is "you" rather than "they" were appropriate. Come to a decision on the word. 
- [x] Identify H4CC where this would apply and segment out the pages in chunks
- [x] Schedule a meeting with the content team to work through some ideas with Amy 
- [x] Schedule a meeting with Info and Press

**Comment by prstoetzer** [comment]
GPO does not yet address gender neutral language in their style guide.

18F supports the singular they:
https://content-guide.18f.gov/our-style/inclusive-language/#gender-and-sexuality

NARA's style guide also includes the singular they:
https://www.archives.gov/files/open/plain-writing/style-guide.pdf#page=20

**Comment by JonellaCulmer** [comment]
@kathycarothers @prstoetzer If we're going to go through this exercise the language changes shouldn't be limited to one section of the site.

**Comment by kathycarothers** [comment]
More sources from an earlier conversation we had 3 months ago: 
 
A resource on designing/writing for inclusivity of gender that recommends using “they.”
https://careerfoundry.com/en/blog/ux-design/design-for-every-gender/

Digital.gov's style guide:
https://digital.gov/style-guide/#conscious-inclusivity

Bluebook uses the word "individual" (Jonella email Bluebook not sure if they have responded 3 months ago) 

Plain Language community:
https://digital.gov/communities/plain-language/

Check with the DEI group

**Comment by kathycarothers** [comment]
@JonellaCulmer I have created an excel sheet for our research. I will email the sheet. Also, when we meet we need to break this ticket out a little differently.

**Comment by kathycarothers** [comment]
I sent Amy an email detailing research on this topic on 9/8

**Comment by kathycarothers** [comment]
Amy is reaching out to Judy and Kate and then we will set up a meeting with Press and Content
