### ISSUE TITLE
Design changes to move "compare candidates" up on the data landing page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4790]
**What we're after:**
Following on the [A/B experiment](https://github.com/fecgov/fec-cms/issues/4740) we ran to improve access to high-level House and Senate data, we want to make adjustments to the data landing page. Specifically, we want to move the compare candidates section higher up on the landing page. In a future ticket we will compare with another A/B test to see how the modifications improve access to that section of the site. 

**Considerations:**
- How might we move the compare candidates up on the landing page without harming access to the other valued areas on the landing page

### Completion criteria
- [x] Design is reviewed and approved by PMs
- [x] Create follow-up task for front-end implementation 
- [x] Create follow-up task for A/B test implementation in Google Tag Manager

**Comment by PaulClark2** [comment]
Thanks, @JonellaCulmer. No objections here.

**Comment by patphongs** [comment]
Looks good to me @JonellaCulmer

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issue https://github.com/fecgov/fec-cms/issues/4840
