### ISSUE TITLE
Publish glossary term updates

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#4793]
### Summary

Following OGC's review and approval, we will need to add a glossary term and definition to the website for "cooperative" 

### Related issues

- #4759 

### Action items

- [x] Update spreadsheet of glossary code to prepare for conversion to JSON (in Content team folder)
- [x] Submit two separate PRs to edit the terms.json file in both EREGS and CMS repos to update the glossary. (Instructions are in shared content team folder in Google Drive.)
- [x] Update master list of terms in content team folder to add the new ones
- [ ] Test in stage after PR is merged and release is cut
- [ ] Create ticket to add the links to the new terms after 15.5 release is deployed.

### Completion criteria

- [x] Glossary terms (in shared content folder) updated to add the new terms.
- [ ] Tested in stage after 15.5 release is cut
- [ ] Ticket created to add the links in H4CC pages to the new terms.

**Comment by djgarr** [comment]
OGC reviewed the glossary terms and were ok with the following:

- Cooperatives
  A cooperative is a voluntary economic association organized to provide economic services, without gain, to itself, and to the members who own and control it. A federated cooperative as defined in the Agricultural Marketing Act of 1929, 12 U.S.C. 1141j, or a rural cooperative eligible for assistance under chapter 31 or title 7 of the United States Code, may solicit the members of the cooperative's regional, state or local affiliates, provided that all of the political committees established, financed, maintained or controlled by the cooperative and its regional, State or local affiliates are considered one political committee for the purposes of the limitations in 11 CFR 110.1 and 110.2.
- Single candidate independent expenditure filer
  A committee that supports or opposes only one candidate and is not an authorized committee.

**Comment by djgarr** [comment]
Updated the glossary term for "Single candidate independent expenditure filer" based on OGC's additional request

**Comment by djgarr** [comment]
@rfultz if it's easiest to add the glossary items at the same time, I can add it to the ticket. Would need help, but I don't mind doing it

**Comment by djgarr** [comment]
Updated informational documents (document and spreadsheet) and submitted PRs

**Comment by djgarr** [comment]
OGC requested that we not include "Single candidate independent expenditure filer" in the updated glossary additions. The item was removed from the PRs

**Comment by JonellaCulmer** [comment]
Work is merged. So closing.
