### ISSUE TITLE
Transition pages and other files to take down in 15.5

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#4798]
### Summary

**What we're after:**
To remove the outdated pages from transition now that the redirects are in place. 

### Related issues

_List any relevant related issue(s)_

- #4794

### Completion criteria

- [x] The following pages are removed from transition:
/about/offices/org_chart.shtml
/af/ and all subdirectories and files within

- [x] The following files are removed from S3 bucket
 /resources/cms-content/documents/FEC_FY_2018_Congressional_Budget_Justificiation.pdf

DONE ALREADY:

/finance/disclosure/presidential_matching_fund_submissions_2004_present.shtml
/finance/disclosure/2016MatchingFundSubmissions.shtml
/finance/2012matching/2012matching.shtml
/finance/2008matching/2008matching.shtml
/finance/disclosure/2004MatchingFundSubmissions.shtml

**Zip files that have been moved to the cms:
2008**

http://www.fec.gov/files/bulk-downloads/presidential_matching_funds/2008/biden2008.zip
https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/bulk-downloads/presidential_matching_funds/2008/dodd2008.zip
https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/bulk-downloads/presidential_matching_funds/2008/edwards2008.zip
https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/bulk-downloads/presidential_matching_funds/2008/edwards2008.zip
https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/bulk-downloads/presidential_matching_funds/2008/gravel2008.zip
https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/bulk-downloads/presidential_matching_funds/2008/hunter2008.zip
https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/bulk-downloads/presidential_matching_funds/2008/kucinich2008.zip
https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/bulk-downloads/presidential_matching_funds/2008/nader2008.zip
https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/bulk-downloads/presidential_matching_funds/2008/tancredo2008.zip

**2004** 

https://www.fec.gov/files/bulk-downloads/presidential_matching_funds/2004/clark.zip
ftp://ftp.fec.gov/FEC/presidential_matching_funds/2004/edwards.zip
ftp://ftp.fec.gov/FEC/presidential_matching_funds/2004/gephardt.zip
ftp://ftp.fec.gov/FEC/presidential_matching_funds/2004/kucinich.zip
ftp://ftp.fec.gov/FEC/presidential_matching_funds/2004/larouche.zip
ftp://ftp.fec.gov/FEC/presidential_matching_funds/2004/ieberman.zip
ftp://ftp.fec.gov/FEC/presidential_matching_funds/2004/nader.zip
ftp://ftp.fec.gov/FEC/presidential_matching_funds/2004/sharpton.zip

15.3 transition redirects that are working:

/law/cfr/cfr_2009.pdf
/law/cfr/cfr_2008.pdf
/law/cfr/2014cfr.pdf
/law/cfr/11cfr2015.pdf
/law/cfr/11_cfr.pdf
/law/cfr/ej_citation_*.shtml (broader redirect is working)

**Comment by johnnyporkchops** [comment]
It looks like these files were already removed based on this comment:
https://github.com/fecgov/fec-cms/issues/4739#issuecomment-889388170
