### ISSUE TITLE
Usability testing for PAC/Party datatable

### ISSUE THREAD

**Issue by lbeaufort** [fecgov/fec-cms#4805]
**What we're after:**
We need to conduct usability testing for the PAC/Party datatable. 

**What we need to test:**
- Overall impressions
- Ease of use

**Action items:**
- Create testing slots on Ethn.io
- Draft and send emails
- Create interview guide
- Create invision prototype
- Update interview spreadsheet with new questions
- Solicit for notetakers
- Synthesize the research

**Completion criteria:**
- [x] Testing is complete
- [x] Research is synthesized
- [x] Followup design tickets are created as necessary

**Comment by JonellaCulmer** [comment]
**Usability testing script:** https://docs.google.com/document/d/1xNUD1uabQWvCWbAoCRUIuriiipXGjLmL6wohUZmLnQ0/edit
**MURAL board with research findings:** https://app.mural.co/t/fec4461/m/fec4461/1630615605837/3531bcda866261d2a63a77f6c68f74a83b4972fb?sender=jculmer4627

Followup tickets: 
- https://github.com/fecgov/fec-cms/issues/4868
- https://github.com/fecgov/openFEC/issues/4946
- https://github.com/fecgov/openFEC/issues/4947
- https://github.com/fecgov/fec-cms/issues/4873
- https://github.com/fecgov/fec-cms/issues/4874
- https://github.com/fecgov/fec-cms/issues/4876
- https://github.com/fecgov/fec-cms/issues/4877
- https://github.com/fecgov/fec-cms/issues/4878
