### ISSUE TITLE
Upgrade Wagtail to 2.15.4 LTS

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4807]
### Summary

Upgrade Wagtail from 2.11.8 to 2.15.4 LTS. [See documentation](https://github.com/wagtail/wagtail/wiki/Release-schedule) for latest LTS for Wagtail. We also need to ensure that our Django is upgraded to avoid becoming too out of date.
[Wagtail releases](https://github.com/wagtail/wagtail/releases)

### Related issues
- https://github.com/fecgov/fec-cms/issues/4258#issuecomment-998420749 This is a possible solution for updating column widths in Wagtail
- Wagtail upgrade to > 15.2 will resolve https://github.com/fecgov/fec-cms/issues/5043

**Completion criteria:**
- [ ] Upgrade to Wagtail 2.15.4 LTS is completed
- [ ] Create follow-up issue to upgrade Django to version 3.2.11
- [ ] Close https://github.com/fecgov/fec-cms/issues/5043

**Comment by cnlucas** [comment]
The Django 3.2.12 upgrade needs to be completed by 5/22/2022 for ticket #5126
