### ISSUE TITLE
Ensuring glossary terms are consistent grammar-wise

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4818]
**What we're after:**
Ensuring glossary terms are consistent grammar-wise. There are a few terms that are plural when most of our terms are singular. 

**Related ticket:**
- https://github.com/fecgov/fec-cms/issues/4969

Should we make these singular: 
- communication costs
- communication filers
- federal funds (think it might sound weird in the singular)
- levin funds (levin fund sounds weird to me)
- operating expenditures
- reports, designations and statements

### Completion criteria
- [x] Review glossary terms for grammar improvements
- [ ] Based on necessary improvements, create two PRs to make changes (do in the same PRs as [4969](https://github.com/fecgov/fec-cms/issues/4969) followup ticket

**Comment by djgarr** [comment]
After looking through the terms, it looks like the plural terms listed correspond to terminology in the CFR, guides, or pages on the site and the preference is to keep them plural. It does look like the term "Cooperatives" can be made into a singular term in the glossary. Once OGC returns feedback on the additional glossary items in #4969 , I'll make a ticket to combine the new glossary items with the update for "Cooperatives"
