### ISSUE TITLE
Track clicks in GTM on tooltips, glossary terms and methodology links

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4828]
**What we're after:**
We want to get a better understanding of how users are interacting with tooltips, glossary terms and methodology links. For methodology links, we display them differently in some places. This tracking will help point us toward a more perfect display solution for this information. 

**Action items:**
- Add GTM tracking for tooltips, glossary terms and methodology links 
- Consider what other interactions we should track

**Completion criteria:**
- [x] Add tracking for these interactions in GTM
- [ ] Set a schedule for reviewing these at a later date

**Comment by rfultz** [comment]
All done! We've set up the event listeners, verified they were working for non-prod, and published to production. Next: check performance in __ days

Thanks @JonellaCulmer

**Comment by JonellaCulmer** [comment]
We'll review the findings in this ticket: https://github.com/fecgov/fec-cms/issues/4841
