### ISSUE TITLE
Transition inventory meeting (innovation)

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#4832]
### Summary

Looks like the last meeting we held was in 15.3

### Related issues
#4618 

### Completion criteria

- [x] Meeting is held with content and front end to go over the inventory list picking up with /law/crew_152038.shtml
- [x] Spreadsheet updated to reflect meeting
- [x] Redirect ticket created
- [x] Take down ticket created
- [x] Testing ticket

### Future work

Will need to test redirects and put them in take down ticket too.

**Comment by kathycarothers** [comment]
meeting has been scheduled

**Comment by kathycarothers** [comment]
I have included these redirects in the Innovation redirect ticket located in the backlog. The take down-ticket will happen once the redirects have been tested.
