### ISSUE TITLE
Implement design changes for data landing page A/B test

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4840]
**What we're after:**
We'd like to learn more about whether the placement of the election search on the data landing page affects user engagement. For an A/B test we're going to move the "Compare candidates" and "Raising" and "Spending" cards to the top of the data landing page. 

We will conduct this test over 2 weeks.

**Completion criteria:**
- [ ] Make necessary design changes in [these designs](https://github.com/fecgov/fec-cms/issues/4790).
- [ ] Add necessary GTM tracking for A/B test (Pair with Robert on this)

**Comment by patphongs** [comment]
Closing in favor of #5009
