### ISSUE TITLE
Hyperlinked text in italicized paragraphs not spacing correctly

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#4846]
### Summary

When we have text that is hyperlinked that's contained within an italicized sentence/paragraph, the space between the unlinked and linked text appears removed in production, despite there being a space in wagtail.

![image](https://user-images.githubusercontent.com/40633757/130501381-fae2129c-8b07-43d4-8ee0-064100423856.png)

### Frequency

This is commonly showing up on reporting pages (such as the 2021 Monthly Report prior notices).

### Work around
There is a current work around to use the Wagtail HTML block to ensure correct spacing, but we want to avoid that and use the Wagtail WYSIWYG editor.

**Completion criteria:**
- [ ] Make sure spacing is present when there is italicized links in Wagtail

### Similar Issues 

- [ ] #4727

**Comment by djgarr** [comment]
@patphongs made an update to the 2021 February Monthly Report to correct the space issue and see if the change retains on the page (https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/2021-reporting-dates/february-monthly-report-notice-monthly-filing-pacs-and-parties-2021/)

**Comment by johnnyporkchops** [comment]
https://github.com/wagtail/wagtail/issues/6710
