### ISSUE TITLE
[Do after 11/2/2021 deploy] Add administrative fine search to enforcement page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4848]
**What we're after:**
Embed administrative fine search onto the enforcement page

### Related issues
- https://github.com/fecgov/fec-cms/issues/4823
- https://github.com/fecgov/fec-cms/issues/4848
### Related PR
https://github.com/fecgov/fec-cms/pull/4925

**Action items:**
- Search is embedded on [enforcement page](https://www.fec.gov/legal-resources/enforcement/)
- "Search closed cases" button is changed to "Calculate a fine" and the link is replaced with https://www.fec.gov/legal-resources/enforcement/administrative-fines/calculating-administrative-fines/#calculating-a-fine

### Completion criteria
- [x] Embedded search is added to the enforcement page (Use Wagtail block created in this PR https://github.com/fecgov/fec-cms/pull/4925)
- [x] Search closed cases button is updated

### Design
<img width="984" alt="Screen Shot 2021-08-24 at 9 40 44 AM" src="https://user-images.githubusercontent.com/31663028/130627601-72f440bf-fa63-466c-9124-fe1931831cb8.png">

**Comment by dorothyyeager** [comment]
Done. The page at https://www.fec.gov/legal-resources/enforcement/ has been updated with the search block and the change in the button to the text and link.
