### ISSUE TITLE
15 innovation redirects

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#4852]
### Summary

**What we're after:**
We need to make sure that we don't have dead links.

[Redirects spreadsheet - tabs 15 innovation and transition inventory](https://docs.google.com/spreadsheets/d/1vzN-wZlS8K8ZyfExSV3hwXDenDEN9KyyAUJFTI6OjKU/edit#gid=1568097790) 

### Completion criteria

- [x] Documents uploaded for accessibility have been redirected via www
- [x] www redirects for E&Js identified in #4808 are implemented
- [x] transition ~and www~ redirects identified in transition inventory meeting (innovation) are implemented - www redirects done in the testing ticket
- [x] Testing ticket created for 16.1
~- [ ] Take down ticket ~ - handled in the testing ticket

**Comment by dorothyyeager** [comment]
Transition redirects are ready for review in https://github.com/fecgov/fec-proxy/pull/286 cc @patphongs @kathycarothers 

Will do www redirects after that PR is merged.

**Comment by dorothyyeager** [comment]
PR for www is ready: https://github.com/fecgov/fec-proxy/issues/287

This ticket can be closed once it's merged.

Testing ticket will reveal if more www redirects are needed and is where we put the takedown ticket in.
