### ISSUE TITLE
Wagtail Bug - paragraph width formatting

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#4857]
### Summary
In a reporting example that was drafted recently, there are sections of text that are wider than the rest of the text on the page. I'm not sure if it's a trend or not, but it appears that this happens to the last line of text in a **Paragraph** block before an **Example Image** block.

https://www.fec.gov/help-candidates-and-committees/reporting-examples/reimbursement-personal-funds-for-travel-expenses/

### Screenshots

![image.png](https://images.zenhubusercontent.com/5c0e981b4b5806bc2bfc2cb5/034915a2-f4a1-42d8-bd3c-17caef48267d)

### Considerations
- Is this intentional and only looks weird when there is one paragraph that exhales into the space under the right column? i.e. is this just a strange-looking wrap/flow issue that wouldn't stick out if there were more text on the page?

### Completion criteria

- [ ] Lists in body copy should be the same width as paragraphs

**Comment by rfultz** [comment]
@bmathesonFEC is this still an issue? I don't suppose you could point us to an example…?

**Comment by bmathesonFEC** [comment]
This is still an issue (although it's not a serious one). The example in the ticket is still an example that demonstrates the inconsistent width: https://www.fec.gov/help-candidates-and-committees/reporting-examples/reimbursement-personal-funds-for-travel-expenses/ (image at the bottom of this comment)

After inspecting the page it looks like <p> elements have a max-width assigned in rem units, but ul and ol elements don't have a set max-width. I don't actually know whether that's what's causing the difference in width but I think that bullet and numbered lists should have the same margins as the paragraph blocks above and below them.

Here's another reporting example that demonstrates the difference between p and ul widths: https://www.fec.gov/help-candidates-and-committees/filing-pac-reports/disseminating-ie-first-and-paying-later-reporting-period/

So far this is just my opinion, @dorothyyeager, @kathycarothers, @djgarr, @JonellaCulmer, agree it should be consistent?



![image](https://user-images.githubusercontent.com/33758291/173095521-46fa5f20-0f85-43cd-8880-07bf557b0126.png)

**Comment by JonellaCulmer** [comment]
@bmathesonFEC Yes, the shorter line lengths have better readability. Agree it should be consistent.

**Comment by bmathesonFEC** [comment]
@johnnyporkchops  I asked a question about `ul` tags in the PR, otherwise I have nothing else before I approve it.
