### ISSUE TITLE
Separate "Strategic plan" for IT and OIG

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4860]
### Summary

Documents from the IT "Strategic plan" category are appearing in the feed for OIG because they also have a "Strategic plan" category

### How to Reproduce

Assign any Document to the 'Strategic plan' category and it will appear on any list that looks for that category, regardless of whether it's IT or OIG

### Possible solutions

1. Rename at least one of the 'Strategic plan' categories (e.g. 'IT Strategic plan', 'Strategic plan - OIG')
1. Tighten feed filters (`DocumentPage.objects.filter(category__in=constants.report_category_groups['oig'].EXCLUDE(…))`

### Considerations

- Should we make this change anywhere else?
- Should we comment this part of the code so the next addition won't have the same issue?
 
### Completion criteria

Documents for IT's Strategic plan category and OIG's Strategic plan category do not appear in the other's feeds

### Misc

There's a [conversation](https://fecgov.slack.com/archives/C3Z3QP0JD/p1630516796029000) with more details

**Comment by patphongs** [comment]
Done, closing issue
