### ISSUE TITLE
Update message on transition.fec.gov for 404's resulting from bad redirect

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4872]
### Summary

**What we're after:**
We updated our messages but must have missed the one generated by transition.fec.gov that shows up when a redirect doesn't work and 404's:

![image (6)](https://user-images.githubusercontent.com/24437369/133085253-1cf4936e-8d48-4129-9bc5-0ba983fed3fb.png)

From Pat: The custom error messages on transition need to be updated separately from the main website.

### Related issues

- #https://github.com/fecgov/fec-cms/issues/2693 - previous 404 message update

### Completion criteria

- [ ] If a redirect fails, the 404 message is updated.

**Comment by patphongs** [comment]
@dorothyyeager @JonellaCulmer Unfortunately the feedback box on transition has never worked and I haven't been able to remove it. Can we refer them to the feedback box on the homepage instead? I know it's an extra click and takes them away from the problem page, but that's the best I can do for now I think.

> **Page not found**
> Sorry, we couldn't find the page you're looking for.
> 
> We work hard to keep our URLs up to date, but please let us know if you think something is missing or broken. Use the feedback box on the bottom of ~any page~ the [FEC homepage](https://www.fec.gov/) or [contact the FEC](https://www.fec.gov/contact/).

**Comment by patphongs** [comment]
The updated error message has been implemented. You can see it in action by triggering an error page like this: https://transition.fec.gov/testerror

<img width="653" alt="Screen Shot 2021-10-05 at 9 51 29 AM" src="https://user-images.githubusercontent.com/12799132/136036538-0849f97d-d5ef-481e-b57b-dc845a92b3ac.png">
