### ISSUE TITLE
Design adding affiliated committees to joint fundraising committees in side details panel

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4874]
**What we're after:**
Add in the affiliated committees to the joint fundraising committees in the side panel of the PAC and party datatable. This work requires design work and should also consider PAC profile pages that do not include affiliated committees. 

Example: Take Back the House 2022 with 79 "affiliated" committees
- Committees datatable: https://www.fec.gov/data/committees/?q=C00766782&designation=J
- About this committee: https://www.fec.gov/data/committee/C00766782/?tab=about-committee
- Form 1 (amended): https://docquery.fec.gov/cgi-bin/forms/C00766782/1488769/

**Completion criteria:**
- [x] Design mock-ups for adding Affiliated committees  to the pages for joint fundraising committees
- [ ] Create the implementation ticket

**Comment by JonellaCulmer** [comment]
@patphongs @PaulClark2 @AmyKort Instead of trying to list out what could be dozens of committees on datatable details panels, I mocked up a link to committee profile pages and added JFC participants to the About this committee page. 

Would love to hear your thoughts on this approach. 

###About this committee - Committee profile page
![Committee - About Copy 3](https://user-images.githubusercontent.com/31663028/143309816-60d26e76-f87e-4708-b763-26b66eb0803e.png)

### Details panel - All committees datatable
![Committees datatable details panel](https://user-images.githubusercontent.com/31663028/143309936-818af2fa-9d0f-4ffb-8f57-353cec1685c7.jpg)


### Details panel - PAC and party datatable
![PAC and party datatable details panel](https://user-images.githubusercontent.com/31663028/143309841-f91d2809-9d66-438f-816a-0be156854a07.jpg)

cc: @rfultz @lbeaufort

**Comment by PaulClark2** [comment]
@JonellaCulmer I like this. I know this is a question the public facing offices get pretty often. 

I know this is a mockup but the authorizing candidate card threw me. We aren't adding that card to the "about this committee" page, are we? If we did, we'd need one for each candidate committee that is a JF participant, right? 

Other than my confusion about the candidate card, I like this and I think it's a helpful way to provide JF participant information to our customers.

**Comment by JonellaCulmer** [comment]
@PaulClark2 Oops, no. I used another page to create this new mockup and left that card on there. I've removed the authorizing candidate card and updated the mockup. 

I think we're good for now with just the JFC about this committee page change. Anything on top of that can come from feedback we receive.

**Comment by PaulClark2** [comment]
@JonellaCulmer thanks for the clarification. I agree. It looks like we are good for now.

**Comment by JonellaCulmer** [comment]
@dorothyyeager @kathycarothers @djgarr What do you think about the language I used on the details panels? Should it instead say "Full list of participants" or something similar?

**Comment by dorothyyeager** [comment]
@JonellaCulmer I'm good with it as you have it. It reinforces that this is a JFC the person is looking at.

**Comment by kathycarothers** [comment]
@JonellaCulmer I concur with Dorothy. Looks good.

**Comment by JonellaCulmer** [comment]
Thanks @dorothyyeager and @kathycarothers Here is the updated details panel. The panels on both tables will have this formatting. 

<img width="524" alt="Screen Shot 2021-12-02 at 11 30 53 AM" src="https://user-images.githubusercontent.com/31663028/144463322-9c73fd74-e1ff-4d9b-b125-ad6aeff58638.png">

**Comment by JonellaCulmer** [comment]
@pkfec @fec-jli @hcaofec Do any of you think that providing the list of  JFC participants on the About this committee tab would require any back-end work first?

**Comment by JonellaCulmer** [comment]
According to @pkfec this work requires a back-end change. Here are the two followup tickets for this work:

- https://github.com/fecgov/openFEC/issues/4997
- https://github.com/fecgov/fec-cms/issues/4980
