### ISSUE TITLE
Clarify which contributions are included with individual contributions on PAC and party datatable side panel

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4876]
**What we're after:**
We'd like to add a tooltip to the PAC and party datatable side panel that clarifies which types of contributions are included in the "individual contributions" dollar figure. 

Website URL: https://www.fec.gov/data/committees/pac-party/?cycle=2022

**Considerations**
- Is it itemized contributions, unitemized contributions or both?
- Should we clarify whether it includes transfers from other committees? Like JFCs?
- Are there other considerations not listed?
- Work with backend team to identify the Line number for displaying the individual contributions
- Consider changing the label name to reflect the line number

**Screenshot of PAC/Party detail panel:**
<img width="1428" alt="Screen Shot 2022-10-13 at 11 02 25 AM" src="https://user-images.githubusercontent.com/11650355/195633818-c047867d-1117-4034-a0a1-4cda10851834.png">

**Completion criteria**
- [ ] Tooltip that clarifies the data is added next to the "Individual contributions" label in the side panel

**Comment by pkfec** [comment]
@Jonella @kcarothers
 The line number for individual contributions on PAC and party datatable side panel is Line a(iii). Individual contributions field is summary of both itemized and unitemized contributions. 

Thanks @hcao for helping me identify the right line number.

**Comment by kathycarothers** [comment]
Maybe something like -  Individual contributions include itemized and unitemized contributions from the Form 3X Detailed Summary page line 11(a)(iii).
