### ISSUE TITLE
Discuss the future of Webpack

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4889]
Do we want to stay wit Webpack now that there are other 'bundler' options?

### Completion criteria:
- [x] Hold a meeting to determine pros and cons, and any other possible issues with changing to another tool
- [x] Determine if the LOE is worth the reconfiguring needed to move to a new tool

See related issue for history of upgrade issues: https://github.com/fecgov/fec-cms/issues/2708

**Comment by rfultz** [comment]
Closing this as we have a way forward. See #2708
