### ISSUE TITLE
Bug: Wagtail redirects - sometimes not working for "choose page"

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4915]
### Summary

Inputting redirects from pages in transition to pages in Wagtail, sometimes the "Choose page" redirect works and sometimes it doesn't. When it doesn't, it works to paste the FEC.gov URL into the "Choose URL" field. So that's a good workaround, except if the page ID should change, than the redirect will no longer work.

### Frequency

Seems to happen randomly

### How to Reproduce

1. Go to https://www.fec.gov/admin/redirects/ 
2. Add a redirect from /law/litigationalpha.shtml (https://www.fec.gov/admin/redirects/290/) to https://www.fec.gov/legal-resources/court-cases/court-case-alphabetical-index/ by entering choose a page and selecting the Court Case alphabetical page
![image](https://user-images.githubusercontent.com/24437369/136415258-536cc95f-7273-41b8-8a61-0e93a2784f8a.png)

(Note: Redirect currently exists but with the workaround of the URL pasted in.)

### Device, browser, etc

I was using Chrome

### Screenshots

**Redirect using "choose page" that works** (this is what we want for all the pages that exist)
![image](https://user-images.githubusercontent.com/24437369/136415759-d8283ebf-8f21-45ed-b4ef-ca4895d67f8e.png)

**Redirect with workaround in place**
![image](https://user-images.githubusercontent.com/24437369/136415470-a3f38d50-e24e-4f05-abc0-b4cbc3261e19.png)

**Comment by johnnyporkchops** [comment]
Closing  based on  the conversation above.
