### ISSUE TITLE
Psycopg2 errors

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#4916]
### What we’re after

No psycopg2 errors with `pip install -r requirements.txt`

Looks like there's been an update and I get errors when trying to `pip install -r requirements.txt` file unless `psycopg2-binary` has been installed, too.

### Action item(s)
- Research the cause of the error (e.g. is another package causing an error here?)
- If another package is causing this error
   - Fix it?
- If we want to switch to psycopg2-binary
   1. Add psycopg2-binary to requirements.txt, using the same version # as psycopg2
   1. `pip install -r requirements.txt`
   1. Check that localhost works as expected
   1. Remove psycopg2 from requirements.txt
   1. `pip install -r requirements.txt`
   1. Check that localhost works as expected
   1. Upgrade psycopg2-binary?

### Completion criteria

- requirements.txt file represents exactly what's needed, as far as psycopg2* goes
- no `pip install` errors from requirements.txt (because of psycopg2*)
- CMS works as expected:
   - localhost
   - CircleCI

**Comment by patphongs** [comment]
Closing this as this is only a localized problem now.
