### ISSUE TITLE
Remove "celebrity" from list of examples

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#4932]
### Summary

**What we're after:**
Remove the word "celebrity" from our list of examples for the individual contribution search feature. 

![image](https://user-images.githubusercontent.com/11817734/138320533-23023ebe-3834-482b-b9b8-2c59bc42bae4.png)

**Comment by JonellaCulmer** [comment]
@cnlucas @PaulClark2 Actually, where it says "someone running for office" isn't correct or at least a little misleading. The search on the data landing page is to search the name of contributors. Putting in the name "Sanders" and searching goes to the contributor name or ID - not the recipient. And the results you get aren't very helpful when searching for the name Sanders. 

To fix this and give another example, what are your thoughts on providing a generic name like "John Smith" in quotes to show the two names can be searched in quotations?

**Comment by cnlucas** [comment]
@JonellaCulmer @PaulClark2 I agree. Jonella, is this what you're thinking below? 

Example: your name or "John Smith"

**Comment by JonellaCulmer** [comment]
@PaulClark2 @dorothyyeager @djgarr Any thoughts on the language below the individual contributor search on the data landing page? ^^

**Comment by djgarr** [comment]
I could be overthinking it, but I'm not sure we need 'your name' in there. I think something like "Example: 'John Smith' or 'Mary Jones'" would work

**Comment by PaulClark2** [comment]
I don't have strong feelings about this. I would be fine with either:  

"Examples: 'John Smith' or 'Mary Jones'" 
OR
"Examples: yourself, 'John Smith' or 'Mary Jones'" 

Probably too long: 
"Examples: yourself, members of your family or other individuals like, John Smith' or 'Mary Jones'"

**Comment by JonellaCulmer** [comment]
@djgarr @PaulClark2 I like where you're going with it. I'd like to show how the search works with the quotations. 

Examples: you or a family member's name such as Mary, Jones or "Mary Jones"

cc: @cnlucas

**Comment by djgarr** [comment]
My inclination would be to stay away from suggesting people can search for their family members. I think "Example: Jones, Mary or 'Mary Jones'" could work. But again, I could be overthinking this

**Comment by dorothyyeager** [comment]
I agree with @djgarr since it's a contributor search. The most helpful thing will be to show how to format the search term.

**Comment by PaulClark2** [comment]
@dorothyyeager @cnlucas @JonellaCulmer I asked Public Records and Press about this. Their suggestion lines up with @djgarr's suggestion. They also suggested using Jane and John Doe instead of Mary Jones. 

> It might be more helpful to address  formatting (last name, first name or first name last name) since both approaches work with searches.  I think that would be the user’s big question with this search – how do I format the name?   Here is a slight modification to [the previous] suggestion:  Examples: your name or someone you want to look up; Jane Doe; Doe, John.

We might still want to work in a quoted example.

**Comment by JonellaCulmer** [comment]
@PaulClark2 Thanks for doing that extra leg work. I appreciate it. 

Slight modification: 

Example: the name of someone you want look up; Jane Doe or "Doe, John"

Or

Example: Jane Doe or "Doe, John"

cc: @dorothyyeager @djgarr @cnlucas

**Comment by PaulClark2** [comment]
You're welcome, @JonellaCulmer . I like the first one, `Example: the name of someone you want look up; Jane Doe or "Doe, John"`

**Comment by cnlucas** [comment]
Great, thanks everyone. I appreciate all the leg work and attention to detail.
