### ISSUE TITLE
Update the report_type_full constant

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#4943]
### Summary

**What we're after:**
_To make it easier to understand the report_type field, the full name of the report type (report_type_full) should be added to the CMS constants._

### Related issues

_List any relevant related issue(s)_

- #4912 
- #4936

### Completion criteria
- [x] Apply report type name changes as indicated in this [document](https://docs.google.com/document/d/1QntwhFYqFYa6MG3q_hmJxm991ocAz2QNd5WbCvo0Vd8/edit).
- [x] Update the report_type_full constant

**Comment by cnlucas** [comment]
I updated @johnnyporkchops PR to match Content's document as he had already worked on adding the constant. Closing  as this is addressed in #4912.
