### ISSUE TITLE
Front End: Take down pages redirected in 16.2

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4947]
### Summary

**What we're after:**
We need to remove files and pages that have recently been redirected.

### Related issues

#4929 

### Completion criteria

- [x] Take these pages down from transition:
/law/2012TDbyEntity.shtml
/law/proposed_rule_comment.shtml
/law/brief/2012TDbyEntity.shtml
/law/brief/2011_2012_election_cycle_total_disbursements_by_entity_type.xlsx
/law/documents/rtao_stay_of_mandate.pdf
/law/feca/us_code.shtml
/law/media/lagop_dc_opinion.pdf
/law/media/lagop_dc_order.pdf
/law/media/Mullin_Winter_Tulsa_60.mp3
/law/media/Socialists-Stream.mov
/law/policy/2004/notice2004-03.pdf

- [x] Take these files down from S3
/resources/about-fec/reports/budget/fy2015/FY2015_AFR.pdf
/resources/about-fec/reports/budget/fy2016/fy_2016_Congressional_budget.pdf
/resources/about-fec/reports/budget/fy2014/FY2014-SummaryOfPerformanceAndFinancialInformation.pdf

**Comment by rfultz** [comment]
Got the transition files down but looking for direction for those in S3

**Comment by rfultz** [comment]
@dorothyyeager I'm not seeing any of the S3 files on transition or production. Should I be?

**Comment by dorothyyeager** [comment]
@rfultz It's possible that Pat may have taken them down already. In any case, it's good if they aren't there (they are in our CMS now and redirects are working).
