### ISSUE TITLE
Research alternatives for showing money raised by Inaugural committees on profile pages

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4949]
### Summary

**What we're after:**
_For inaugural committees, donations filed on schedule 13-A of the Form 13 won't show up in the individual contributions datatable. Since this was causing a blank "Individual contributions" datatable to show up for Inaugural Committees on their committee page,  we currently hide the  table. Therefore, we need to find alternative ways to show how this type of committee has raised money._

https://www.fec.gov/data/filings/?data_type=processed&form_type=F13

### Related issues

_List any relevant related issue(s)_

- #3390 

### Completion criteria

- [x] Research how these committees are funded
- [x] Propose the next step
- [x] Document data needed for inaugural committees
- [ ] Create follow up tickets

### Action items

- [x] Talk with Jason in Public Records
- [ ] Review these pages

https://www.fec.gov/help-candidates-and-committees/presidential-transition-and-inauguration/funding-inaugural-committee-activities/
https://www.fec.gov/help-candidates-and-committees/filing-reports/inaugural-committee-reports/

- [ ] Talk with back end and content to resolve any questions.

### Future work

_Other future work that may be needed following this issue's completion._

**Comment by dorothyyeager** [comment]
This section of H4CC may or may not be helpful: https://www.fec.gov/help-candidates-and-committees/other-filers/#inaugural-committees

**Comment by kathycarothers** [comment]
Ping @PaulClark2

**Comment by JonellaCulmer** [comment]
So the reason why nothing was appearing in the original datatable on inaugural committees profile pages is that none of the money recieved was considered an individual contribution. Everything received is considered a donation. 

These transactions can be found on the receipts datatable.  

- Inaugural committees file on form 13: https://www.fec.gov/resources/cms-content/documents/fecfrm13.pdf

- Here's an example of a receipts datatable search and the kind of information that's already in the API: https://www.fec.gov/data/receipts/?data_type=processed&committee_id=C00540005&two_year_transaction_period=2014

**Comment by JonellaCulmer** [comment]
After looking at what how inaugural committees are required to report, the information currently available in the API and the way our profile page tables are structured, I made some mockups of how this can look. 

Other areas that this work does not cover includes the use of IE tables on the spending tab for these committees. I don't believe they make any IEs as there is no place to report them on form 13. Should this table also be removed (and not replaced with anything) from the spending tab?

### Designs for review
@patphongs @AmyKort @fec-jli @johnnyporkchops Let me know what you think.
![Screen Shot 2022-07-25 at 11 55 12 AM](https://user-images.githubusercontent.com/31663028/180821897-2a81a985-e2e5-48c1-98f8-8fbb31099dd4.png)

**Comment by kathycarothers** [comment]
The regulation is 104.21 in case you need a reference for understanding donation. These committees will report their donations.

**Comment by JonellaCulmer** [comment]
Updated comments following comments from Jason. One question for back-end (@JonellaCulmer @pkfec @cnlucas). Do we need to make any API changes to accommodate totals by donor on schedule A endpoint?
![Screen Shot 2022-07-27 at 10 11 24 AM](https://user-images.githubusercontent.com/31663028/181268962-f97bf3a3-7dd1-4fe2-bac0-469a8a97c15b.png)


Mockups in full:
![Screen Shot 2022-07-27 at 10 09 15 AM](https://user-images.githubusercontent.com/31663028/181269017-ae56e4ee-7df5-4a10-b67f-9949cf5e0b32.png)

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issues:
- https://github.com/fecgov/fec-cms/issues/5353
- https://github.com/fecgov/openFEC/issues/5208
