### ISSUE TITLE
Correct intro language for the audit hearing pages 

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4950]
### Summary

**What we're after:**
The Commission Secretary noticed some inaccurate language on the audit hearing intro page that we need to fix. We put in a short term fix for an upcoming hearing, but we need to update the template to avoid that in the future.

### Completion criteria

- [x] Intro language on audit hearing page (meeting page) [template](https://github.com/fecgov/fec-cms/blob/develop/fec/home/templates/home/meeting_page.html) is changed to say:

The Commission considers new regulations and other public matters at public hearings. Members of the public can attend public hearings in person. Public hearings are also streamed live online. To attend in person, please bring a photo ID and be prepared to go through a security check. After security, attendees are escorted to the Commission's hearing room.
- [ ] **After this is deployed:** Remove temporary code (`<style>` and `<p>` blocks) from additional_information block on https://www.fec.gov/updates/november-10-2021-audit-hearing/ and https://www.fec.gov/updates/december-2-2021-audit-hearing/ so they just has `<h3>Because of the COVID-19 pandemic, we will conduct the audit hearing virtually.</h3>`
*THIS HAS BEEN MOVED INTO A FUTURE TICKET - https://github.com/fecgov/fec-cms/issues/5062

### Tech steps or considerations (optional)

Example of audit hearing page and what it should say at https://www.fec.gov/updates/november-10-2021-audit-hearing/

**Comment by dorothyyeager** [comment]
PR submitted to make the language change. The rest of the ticket will be done after the release is deployed.

**Comment by patphongs** [comment]
@dorothyyeager I've merged in the PR for this. However, do we want to hold on removing the temporary code for now as it has a statement about COVID-19 embedded in there?

**Comment by dorothyyeager** [comment]
@patphongs I agree, let's hold off for now. If Laura requests it be removed, we can do that when she asks. I'll move that into its own ticket and put in PI18 for now so we don't lose track.

**Comment by dorothyyeager** [comment]
Closing. Left style code intact. There is no duplicate language on those two hearing pages.
