### ISSUE TITLE
Add reporting examples page button to reporting pages

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#4954]
### Summary

Add "Read next links" to pertinent reporting examples to these H4CC pages on recordkeeping

### Completion criteria

Add "Read next" links to:
- [x] Recording candidate receipts: https://www.fec.gov/help-candidates-and-committees/keeping-records/recording-receipts/~  
- [x] Recording candidate disbursements: https://www.fec.gov/help-candidates-and-committees/keeping-records/records-disbursements/ 
- [x] Recording candidate loans/debts: https://www.fec.gov/help-candidates-and-committees/keeping-records/recording-debts-and-loans/ 
- [x] Party receipts: https://www.fec.gov/help-candidates-and-committees/keeping-political-party-records/recording-receipts/
- [x] Party disbursements: https://www.fec.gov/help-candidates-and-committees/keeping-political-party-records/recording-disbursements-party-committee/
- [x] Party loans/debts: https://www.fec.gov/help-candidates-and-committees/keeping-political-party-records/recording-debts-and-loans-party-committee/
- [x] SSF receipts: https://www.fec.gov/help-candidates-and-committees/keeping-ssf-records/recording-receipts/
- [x] SSF disbursements: https://www.fec.gov/help-candidates-and-committees/keeping-ssf-records/recording-disbursements-ssf/
- [x] Nonconnected receipts: https://www.fec.gov/help-candidates-and-committees/keeping-pac-records-nonconnected/recording-receipts/ 
- [x] Nonconnected disbursements: https://www.fec.gov/help-candidates-and-committees/keeping-pac-records-nonconnected/recording-nonconnected-pac-disbursements/
- [x] Nonconnected loans/debts: https://www.fec.gov/help-candidates-and-committees/keeping-pac-records-nonconnected/recording-nonconnected-pac-debts-and-loans/

**Comment by dorothyyeager** [comment]
Reviewing all recordkeeping pages now. In some cases, buttons or read next links make more sense than reporting example links. In any case, added these types of links to the pages linked in the ticket.

In addition to pages listed above, a button was added to  https://www.fec.gov/help-candidates-and-committees/best-efforts-document-receipts/.
