### ISSUE TITLE
Add new report category for the IG feed: "Management challenges"

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4959]
### Summary

**What we are after:**
OIG has an annual report that they'd like to take out of the Inspection and special report category and give its own category called Management challenges

### Related issues

#4813 #4860 #4865  - issues related to previous category work for OIG.  

### Completion criteria
- [x] Name for new category is run by OIG - Content
- [x] New category is added to OIG [document feed page](https://www.fec.gov/about/reports-about-fec/oig-reports/) only (no other report feed) for "Management challenges reports" (Front end work)
- [x] Categories with "-OIG" in the names are renamed _Other OIG reports and plans_ and _OIG strategic plans_ (Front end work)
- [x] Non-OIG reports do not show up in the OIG landing page feed (Front end work)

Future work after 16.5 is deployed - moved to https://github.com/fecgov/fec-cms/issues/4977
-Update "Management challenges" link at the bottom of the OIG landing page to point to the new category and other links at the bottom to point to any revised links.
-Reports called "Management and Performance Challenges" are moved from https://www.fec.gov/about/reports-about-fec/oig-reports/?category=inspection+or+special+review+report to the new category (Content can do this part by editing the document pages to update the category after it's added.)

**Comment by JonellaCulmer** [comment]
The category "management challenges" would break the existing pattern of report types. Management challenges to me is more of a subject, not a report type.

**Comment by dorothyyeager** [comment]
I'll ping @patphongs when front end is needed.

**Comment by dorothyyeager** [comment]
We've sent this email to OIG to ask about category names for them:

> We are starting the work on adding that new category for the management challenges. We wanted to run one tweak by you for it. Would it be OK if we called It “Management challenges reports” – Adding “reports” makes it more consistent with the labeling of other report categories on the website.

> Also, as you know, we added an “-OIG” to two of your category names to separate out what should go in your feed from what should go in other agency feeds. Would your office be amenable to changing those categories to read “Other OIG reports and plans” and “OIG strategic plans”? It reads a little less clunky but will still do the job of separating them out.

**Comment by dorothyyeager** [comment]
That was very quickly approved by OIG! They are fine with our proposed rewording.
New category: Management challenges reports
Rename "Other reports and plans - OIG" to "Other OIG reports and plans"
Rename "Strategic plans - OIG" to " OIG strategic plans"

**Comment by dorothyyeager** [comment]
I've moved the remaining content work to 16.6. It will require the new category to be live so makes sense to do it then.

Once the PR at https://github.com/fecgov/fec-cms/pull/4976 is merged, this ticket can be closed.
