### ISSUE TITLE
Add percentage of total disbursements to disbursements table

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4962]
**What we're after:**
Add the percentage of total disbursements to the disbursements table on the spending tab for PAC profile pages. This will require adding a calculated percentage by vendor compared to total disbursements to the database and API and displaying on the front-end. 

Example: https://www.fec.gov/data/committee/C00727834/?tab=spending&cycle=2020#disbursement-transactions

**Action items:**
- New column for "Percent of total disbursements"
- Update disclaimer language at bottom of table

**Completion criteria:**
- [ ] Calculated percentage has been added to the disbursements table, recipients tab on the spending page for PAC profiles (sorry)

Design: 
![Screen Shot 2021-11-16 at 8.56.10 AM.png](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/96cd2d02-de7e-4df3-80db-187fe755b82a)

**Comment by pkfec** [comment]
API pr ready here # https://github.com/fecgov/openFEC/pull/4992

**Comment by JonellaCulmer** [comment]
Work has been merged, so closing.
