### ISSUE TITLE
Tooltips added to committee type filters on committees datatable

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4963]
**What we're after:**
Tooltips are added to the filter labels for authorized committees, IE committees and PACsCommittee type accordion on committee data table. Default path will be to use glossary definitions. Once Content team able to get shorter approved tool tip language in #4964 , we'll update.

**Completion criteria:**
- [ ] Tooltips are added to aforementioned filter labels

**Designs:**
![Screen Shot 2021-11-16 at 9 26 28 AM](https://user-images.githubusercontent.com/31663028/142003435-f5043129-0c9b-4bf9-8619-f2abd6f48549.png)

**Comment by dorothyyeager** [comment]
We are aiming to finish this in this sprint. Workaround plan will be to paste in glossary definition into tooltip  if content can't get the simpler tool tip approved.
