### ISSUE TITLE
Tooltip language approved

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4964]
**What we're after:**
Tooltips language is approved for the committees datatable for committee type filters

Draft language:

**Authorized committees:** A political committee that has been authorized by a candidate to accept contributions or make expenditures on their behalf. 

**Independent expenditure committees:** A political committee that makes only independent expenditures that may solicit and accept unlimited contributions from individuals, corporations, labor organizations and other political committees.

**PACS:** Popular term for a political committee that is neither a party committee nor an authorized committee of a candidate.

**Completion criteria:**
- [x] Tooltip language is reviewed and approved (maybe a meeting with Policy) - Take the approach as a demo meeting at first to explain to Policy why we need shorter language for the tooltips. And then have them review the language. 

**Designs:**
![Screen Shot 2021-11-16 at 9 26 28 AM](https://user-images.githubusercontent.com/31663028/142003435-f5043129-0c9b-4bf9-8619-f2abd6f48549.png)

**Comment by dorothyyeager** [comment]
Brad has reached out to Policy to set up meeting for week of 11/29.

**Comment by bmathesonFEC** [comment]
Content team met with OGC Policy this afternoon. Conducted some live group editing and we arrived at this tooltip language in the meeting. Emailed them the current version and now we wait for their official agreement:

---

### Authorized committees:
A political committee authorized by a candidate to accept contributions or make expenditures on behalf of that candidate. Also known as a campaign committee.

### Independent expenditure committees:
A political committee that makes only independent expenditures. and may solicit and accept unlimited contributions from individuals, corporations, labor organizations and other political committees. This committee may not make contributions to federal candidates, party committees or generally other political committees.

### PAC:
Popular term for a political committee that is neither a candidate’s authorized committee nor a party committee.

**Comment by dorothyyeager** [comment]
This is just waiting for OGC to officially confirm what Brad has above.
