### ISSUE TITLE
[Snyk: High] json-schema-Prototype Pollution  (due 12/17/21)

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#4967]
**Detailed paths**

- Introduced through: fec-cms@1.0.0 › [request@2.88.0](https://app.snyk.io/test/npm/request@2.88.0) › http-signature@1.2.0 › jsprim@1.4.1 › json-schema@0.2.3
- Fix: No remediation path available.

**Overview**
Affected versions of this package are vulnerable to Prototype Pollution via the `validate` function, which when given a special payload will pollute `Object` with undesired attributes.

**Comment by rfultz** [comment]
Looks like it's been addressed with json-schema 0.4.0. https://security.snyk.io/vuln/SNYK-JS-JSONSCHEMA-1920922
