### ISSUE TITLE
Draft and add glossary terms related to foreign nationals 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#4969]
### Summary

**What we're after:**
_To add glossary terms for U.S. national and green card holders to further clarification on the terms for the regulated community ._

### Related issues

- #4945
- https://github.com/fecgov/fec-cms/issues/4818

### Completion criteria

- [x] Draft glossary terms for U.S. national and green card holder 
- [x] Get OGC approval for any definitions that don't have approved language.
- [x] Open follow-up ticket to do PRs to implement new glossary terms and update "Cooperatives" (as per #4818)
- - New ticket opened at #5042  

### Future work

When OGC returns comments, move to Publish updates to the glossary and update the glossary for both cms and eregs.  Up date the foreign national page with these terms.

**Comment by kathycarothers** [comment]
Foreign national means - (i) A foreign principal, as defined in 22 U.S.C. 611(b); or. (ii) An individual who is not a citizen of the United States and who is not lawfully admitted for permanent residence, as defined in 8 U.S.C.

**Comment by kathycarothers** [comment]
Green card holder  
A Green Card holder (permanent resident) is someone who has been granted authorization to live and work in the United States on a permanent basis. As proof of that status, U.S. Citizenship and Immigration Services (USCIS) grants a person a permanent resident card, commonly called a "Green Card."
Source https://www.dhs.gov/get-green-card

U.S. National 
31 CFR § 800.253 U.S. national.
The term U.S. national means an individual who is a U.S. citizen or an individual who, although not a U.S. citizen, owes permanent allegiance to the United States.

**Comment by djgarr** [comment]
Drafted terms sent to OGC for review on 1/19/22

**Comment by djgarr** [comment]
OGC sent feedback/updates

**Comment by djgarr** [comment]
New ticket for PRs opened at #5042
