### ISSUE TITLE
Add JFC participants to JFC profile pages and committees and PAC and party datatable details panels

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#4980]
**What we're after:**
To address a usability finding, we need to update the front-end to display: 
- A list of joint fundraising participants on JFC committee profile pages only (About this committee tab). 
- A link to JFC profile pages (About this committee tab) is added to details panels on both the Committees and PAC and party committee datatables. 

These changes will remove a burden on users which currently requires them to sift through a committee's Form 1s to locate a list of participating joint fundraising committees. 

Designs for both are included at the end of this ticket. 

### Related issues
- https://github.com/fecgov/fec-cms/issues/4874

### Completion criteria
- [ ] Front-end changes to the JFC committee profile pages
- [ ] Front-end changes are made to JFC committee details panels on Committees and PAC and party datatables

### About this committee - Committee profile page
![Committee - About](https://user-images.githubusercontent.com/31663028/143883820-66a0e92d-6c05-4df6-857f-ffd95351cfb3.png)

### Details panel - All committees datatable

![Committees datatable details panel](https://user-images.githubusercontent.com/31663028/144473057-a6890f9c-b561-48f0-8100-c366f2852e9f.jpg)

### Details panel - PAC and party datatable
![PAC and party datatable details panel](https://user-images.githubusercontent.com/31663028/144473088-465df1e6-7a04-4698-9a0f-ef80c4cc67d1.jpg)

**Comment by lbeaufort** [comment]
@JonellaCulmer FYI there's some additional information in this ticket: https://github.com/fecgov/openFEC/issues/4861. These could probably be combined.

**Comment by patphongs** [comment]
@JonellaCulmer During our discussion today about JFCs, we find it will be confusing and not possible to list a history of JFCs on the About committee section. There can be multiple amendments to form 1's which make it impossible to be able to show history.  Therefore the election cycle dropdown would be irrelevant in this case. We propose that the label in the About committee section would be descriptive enough to tell the user that they are seeing the most recent or current list regardless of year.  For example: "Joint fundraising participants from most recent form 1"

**Comment by JonellaCulmer** [comment]
@patphongs Thank you. Then we should also change the labels on the datatables from "full" list to "Current" list. 

@dorothyyeager @kathycarothers @djgarr Any suggestions/recommendations/comments on the language we use?
