### ISSUE TITLE
Update the regulations page and the E&J pages when the 2022 Civil Penalty FR notice is published

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#4999]
**User story** As a filer (or a stakeholder or a consultant), I need to know that there are automatic penalties for late/non-filed reports, and that the law for those penalties has been extended.

**Background** 
 Revised rules will be published very soon in the Federal Register the penalties for certain FECA violations. We need to update admin fine pages accordingly.

Related front end ticket: https://github.com/fecgov/fec-cms/issues/5000

**Completion Criteria**
- [x] Using SERS link, regulations page (https://www.fec.gov/legal-resources/regulations/)   are updated with link to the FR notice under "Changes not included in 2022 edition"
- [x] The main admin fine page (https://www.fec.gov/legal-resources/enforcement/administrative-fines/) is updated with link to the  FR notice (using SERS link)
- [x] The FR notice is added to the E&J chronological index and to the citation indexes for the regulations mentioned in the notice.
- [x] Text on this page is updated as Admin Fines specifies:
 https://www.fec.gov/legal-resources/enforcement/administrative-fines/calculating-administrative-fines/.
- - [x] Check with Rhiannon on calculation

**Comment by djgarr** [comment]
Citations added to all pages

**Comment by dorothyyeager** [comment]
Rhiannon will send us the text for the one page later this week.

**Comment by dorothyyeager** [comment]
E&J pages updated. Moving to blocked until we hear back from Rhiannon.

**Comment by dorothyyeager** [comment]
Rhiannon has sent her edits; reassigning to David who will put them in.

**Comment by djgarr** [comment]
Edits added. Page published
