### ISSUE TITLE
Update admin fine calculators for 2022 with new fine amounts

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5000]
### Summary

What we are after:
Once the Commission approves the new fine inflation adjustments, there will be a FR notice updating the regulations for admin fines. We'll need to update the calculator (https://www.fec.gov/legal-resources/enforcement/administrative-fines/calculating-administrative-fines/#calculating-a-fine)

From Rhiannon: Please hold on development until the Commission approves the adjustments. She'd like for the calculator to go live with new amounts within a few days after the effective date in the FR notice (TBD).

Related content team work: https://github.com/fecgov/fec-cms/issues/4999

### Completion criteria

- [x] Once approved, calculator is updated with the new amounts but does not go live
- [x] Once ready, AF staff test the first or second week of January
- [x] Once AF gives the go live signal: Go live with the calculator with new amounts.

**Comment by rfultz** [comment]
@dorothyyeager this work is ready to be committed for internal testing when you're ready for it to be

**Comment by patphongs** [comment]
This is done
