### ISSUE TITLE
Work planning/research ticket: Scope work of updating pages

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5013]
### Summary

**What we are after:**
We need to update a lot of Candidate pages. This ticket is to have a planning meeting, scope out that work into bite-sized, sprint-sized chunks, and create the follow up tickets.

### Related issues and info

Example of a work plan we can follow: https://docs.google.com/document/d/18gBKozzlXq1JNIYktjhWUB8amm2eNl-5OpiJmu2HJP4/edit

- https://github.com/fecgov/fec-cms/issues/4886 (inventory)

### Work to scope
Use of campaign funds pages (some receipts, all disbursements and winding down) Need to create tickets - every page behind these section links is affected. https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/#other-sources-of-income-and-support
https://www.fec.gov/help-candidates-and-committees/making-disbursements/#campaign-related-expenses
https://www.fec.gov/help-candidates-and-committees/making-disbursements/#noncampaign-expenses
https://www.fec.gov/help-candidates-and-committees/winding-down-candidate-campaign/

Communications by corporations etc Need to create tickets for pages in this section: https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/support-corporations-labor-organizations/
Making remaining changes going chapter by chapter using Kathy’s spreadsheet - Need to create tickets

### Completion criteria

- [x] Planning meeting held with content team to confirm next steps, future tasks, possible blockers, timing, and other considerations.
- [x] Work plan made
- [x] Tickets created

**Comment by kathycarothers** [comment]
I drafted a work plan document at https://docs.google.com/document/d/1SCwENOlpp0rgqb40iUh7xD4MMX2di4Rec7Zn97OxOJY/edit

**Comment by kathycarothers** [comment]
In our meeting, we confirmed our plan with the working document and will create tickets as we go.
