### ISSUE TITLE
Homepage Optimization - CLS

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#5015]
### Summary

**What we're after:**
Fix:
![image](https://user-images.githubusercontent.com/26720877/149143148-42a4b7bd-1261-4c2a-9f6b-6b2c67c2def4.png)

### Related issues

_List any relevant related issue(s)_

- #[issue_number]
- #[issue_number]

### Completion criteria

_What does the end state look like? Include any behavior, appearance, etc required for this ticket to be 'complete.'_

### Tech steps or considerations (optional)

_List any considerations the tech team should know. Additionally, any specific tech steps can be included here._

- [ ] First
- [ ] Next
- [ ] Then

### Future work

_Other future work that may be needed following this issue's completion._

**Comment by JonellaCulmer** [comment]
Closing. Will pick this back up after webpage upgrade: https://github.com/fecgov/fec-cms/issues/2708
