### ISSUE TITLE
Mobile Usability - Text Too Small To Read

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#5016]
### Summary
Find out what text is considered too small for mobile usability. Use lighthouse to generate a report and see when modifications are made to the font, if this will fix the mobile usability. If it does, we should document this and consider whether or not we need to fix the text sizing.

Google is dinging us for having text that's too small for mobile devices. Not sure if this is something we can fix, care to fix, or just remember while creating other pages or updating these. Maybe it's just a css tweak! There are a lot of docquery pages on the list, but here are some of the other example URLs:

- https://www.fec.gov/help-candidates-and-committees/handling-loans-debts-and-advances/settling-debts-candidate/
- https://www.fec.gov/help-candidates-and-committees/registering-pac/registering-nonconnected-committee/
- https://www.fec.gov/help-candidates-and-committees/filing-reports/-kind-contributions-candidate/
- https://www.fec.gov/help-candidates-and-committees/filing-reports/in-kind-contributions/
- https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/investment-income/
- https://www.fec.gov/help-candidates-and-committees/making-disbursements-pac/contributions-made-party-committees-and-pacs-nonconnected/
- https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/food-beverage-discount/
- https://www.fec.gov/help-candidates-and-committees/registering-ssf/ssf-registration/

Domains outside of www.fec.gov domain:
- https://docquery.fec.gov
- https://eqs.fec.gov/
- https://webforms.fec.gov/webforms/form1/login.htm

### Completion criteria

- [x] Document what text sizes are considered too small for mobile usability (**update**: 12px)
- [ ] Determine any changes that are needed (**update**: I can't seem to find any)
- [ ] Create follow-up tickets to fix

**Comment by cnlucas** [comment]
Closing this ticket, explanation by @rfultz above
