### ISSUE TITLE
All House and Senate totals (by the numbers) Consider designs for showing all House and all Senate spending and raising totals

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5018]
**What we're after:**
All House and Senate totals (by the numbers) Consider designs for showing all House and all Senate spending and raising totals (design)

**Related tickets:**

**Completion criteria:**
- [ ] Mockup solution to show all raising and spending totals on House and Senate data pages - this will function similarly to the top feature on the by the numbers pages

**Comment by JonellaCulmer** [comment]
@patphongs @PaulClark2 @AmyKort @rfultz @lbeaufort Would love your thoughts on this preliminary mockup for all raising, spending as well as IEs. We've removed IE from the total table at the bottom of the page, so I wanted to attempt to include it at the top.

<img width="1089" alt="Screen Shot 2022-01-20 at 3 36 11 PM" src="https://user-images.githubusercontent.com/31663028/150418273-483232ef-ded9-44dd-a1e6-1fe6e3863ff5.png">

**Comment by lbeaufort** [comment]
> @patphongs @PaulClark2 @AmyKort @rfultz @lbeaufort Would love your thoughts on this preliminary mockup for all raising, spending as well as IEs. We've removed IE from the total table at the bottom of the page, so I wanted to attempt to include it at the top.
> 
At first glance, this looks great to me. I don't think we currently do top-level independent expenditure calculations anywhere on the site - if that's the case, I'd need to dig deeper to see what additional API work would need to happen.

**Comment by JonellaCulmer** [comment]
@lbeaufort Thanks. I'll open a ticket to do API research/work on the IE piece. 

For the purposes of this mockup I went to the IE datatable, filtered by support, House and regularly scheduled reports and then again for opposition. Exported each and just added them up. Didn't include 24- and 48-hour reports, so the "real" number may be different.

**Comment by AmyKort** [comment]
Thank you, Jonella! This looks good to me. I did have one question: Looking at this, I wonder if it is confusing to have a "totals for all Houses races" and a "totals for all House elections" option.  I'm not sure I would know what the difference was going to be.

**Comment by JonellaCulmer** [comment]
@AmyKort Thanks, you're right. The names are too similar and might be confusing. What about something like "House election summary"?

**Comment by JonellaCulmer** [comment]
Updated mockup:
![Screen Shot 2022-01-27 at 2 08 00 PM](https://user-images.githubusercontent.com/31663028/151427113-48f65fbb-c186-4564-9743-0ac6fa4e9f4f.png)

**Comment by JonellaCulmer** [comment]
Closing this ticket in favor of followup API work:
https://github.com/fecgov/openFEC/issues/5029
