### ISSUE TITLE
Contributions across time: Update designs

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5021]
**What we're after:**
Based on the conversation and takeaways from[ #5017](https://github.com/fecgov/fec-cms/issues/5017) we need to update the designs for the contributions across time feature as necessary. 

**Completion criteria:**
- [ ] Designs are updated and reviewed by team
- [ ] Updated designs are added to implementation issue

**Comment by patphongs** [comment]
@JonellaCulmer 
- Ticket needs to be opened for methodology content.
- Ticket needs to be opened for coverage dates. Maybe it can be moved to methodology so that we don't need it to take up the feature area.

The rest of the design looks good to me!

**Comment by JonellaCulmer** [comment]
Updated designs. 

### House/Senate election summary
<img width="700" alt="Screen Shot 2022-02-28 at 5 00 55 PM" src="https://user-images.githubusercontent.com/31663028/156067838-8cda971d-0380-4335-836b-6a10bbb44737.png">

### Contributions over time
<img width="709" alt="Screen Shot 2022-02-28 at 5 00 34 PM" src="https://user-images.githubusercontent.com/31663028/156067890-1ca3bba5-3235-431c-af5e-f1a649c43433.png">

New tickets: 
- https://github.com/fecgov/fec-cms/issues/5089
- https://github.com/fecgov/fec-cms/issues/5090
- https://github.com/fecgov/fec-cms/issues/5091
- https://github.com/fecgov/openFEC/issues/5069
