### ISSUE TITLE
Contributions across time: Build out chart

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5034]
**What we're after:**
Build out the contributions across time chart. Pair with @JonellaCulmer as much as necessary or to answer any questions. 

**Completion criteria:**
- [x] UX and frontend team meet to establish user interaction for two-year selects and resulting data presentation.
- [ ] Chart is built out and ready for QA testing by front and back-end teams (17.5)

**Design:**
<img width="709" alt="Screen Shot 2022-02-28 at 5 00 34 PM" src="https://user-images.githubusercontent.com/31663028/156187190-733acdce-28c9-4ce3-8208-5ce4da43948e.png">

**Comment by johnnyporkchops** [comment]
While working on the basic logic to populate the three sections, questions about the user interaction  have come up again. We need to have a pairing with UX and frontend team to establish how we want it to work :
  - Should we consider one  select dropdown instead of two, where the user chooses a two-year period and sees previous three(or more) two-year period totals
  - What other options might there be with either one ore two select dropdowns
  - What other options might there be for how the bars are shown (how manny years back or forward do we show?)
  - What else do we need to consider in terms of usability

**Comment by JonellaCulmer** [comment]
To add to your comment, @johnnyporkchops, we need to make it possible for data users to select up to 6 two-year time periods. Based on usability testing, most users will likely not go back more than 6 periods because the comparisons are no longer apples to apples. To me, that also means the periods need to be consecutive. 

What kind of filtering will allow the easiest path to the maximum amount of data and one that allows for the flexibility to see whatever set of data they are interested in? Does that mean one single date selector that automatically shows the 3-6 previous periods, or a range filter that grays out options unavailable? Or, even still, some kind of dropdown that allows the user to select whichever 6 periods they like? Knowing that users may not be as interested in 1976 data, we can probably exclude that last option. 

Or, should the data be fixed and we allow the user to select how far back in time the data should go with a 3 periods vs 6 periods toggle?

Just some options to jumpstart the conversation. I'll be available to meet Wednesday and Thursday this week.

**Comment by JonellaCulmer** [comment]
### Updated mock-up based on a conversation with content. 

Looking for feedback/edits from @PaulClark2 @AmyKort on the language at the bottom of the feature:
Coverage dates for each two-year period cover January 1 of the first year through December 31 of the second year. Coverage dates as of last report filed are only available at the individual committee level. 

Do you think ^^ language can be tucked into the methodology, instead? At this point, I have no other recommendations for helpful language there, other than our somewhat standard "Newly filed summary data may not appear for up to 48 hours."

### Tooltips language (pulled from reporting example pages):

**Individual contributions:**
Itemized contributions received from individuals that exceed or aggregate over $200 when added to other contributions from the same source during that same election cycle.

**PACs and other committee contributions:**
All itemized contributions from PACs and other political committees except party committees and Super PACs.

**Transfers from other authorized committees:**
All funds transferred between authorized committees of the same candidate during that same election cycle.

### Methodology 
Work happening here: https://github.com/fecgov/fec-cms/issues/5090 

### Design
![Screen Shot 2022-04-01 at 8 40 42 AM](https://user-images.githubusercontent.com/31663028/161265512-faa89a6c-c7c2-442b-8be8-9df364245ff9.png)


cc: @patphongs @johnnyporkchops

**Comment by AmyKort** [comment]
Thanks for sharing this! I think the "Coverage dates or each two-year period cover January 1 of the first year through December 31 of the second year" language makes a lot of sense to me. And I think we should add our disclaimer about summary data not being immediately available.

For me, though, the sentence "Coverage dates as of the last report filed are only available at the individual committee level" language is a little confusing in the context of this chart. I noticed we don't say this on our Cumulative amount spent by committees chart, which also aggregates data of committees who may have different coverage dates at different points in time. Can we leave that sentence out?

**Comment by PaulClark2** [comment]
@JonellaCulmer thanks. I agree with Amy's comments.

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Here's the updated mockup and language.

### Tooltip language:
**Individual contributions:**
Itemized contributions received from individuals that exceed or aggregate over $200 when added to other contributions from the same source during that same election cycle.

**PACs and other committee contributions:**
All itemized contributions from PACs and other political committees except party committees and Super PACs.

**Transfers from other authorized committees:**
All funds transferred between authorized committees of the same candidate during that same election cycle.

### Disclaimer language
**Below chart:**
Coverage dates for each two-year period cover January 1 of the first year through December 31 of the second year. Newly filed summary data may not appear for up to 48 hours.

### Design
![Screen Shot 2022-04-01 at 1 28 37 PM](https://user-images.githubusercontent.com/31663028/161312927-bfd92984-f190-4999-b2ed-716f75629c67.png)
