### ISSUE TITLE
Input best bets in the search.gov for election cycle to date 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#5037]
**What we're after:**
We need to make the searches related to election cycle year to date work better, we will add "best bets" to search.gov for this keyword.

### Related issues
- #5036

### Completion criteria
- [x] Document in this ticket which best bets will be added
- [x] Create the best bets in search.gov

**Comment by bmathesonFEC** [comment]
Input the following best bets keywords to suggest this page:
- election cycle
- election cycles
- election cycle dates
- election cycle running in
- election cycle to date

There are other terms that will yield this best bet, for example, I didn't specify "cycle" alone as a keyword but it will yield this best bet suggestion
