### ISSUE TITLE
Add new glossary terms related to foreign nationals and update "Cooperatives" term

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#5042]
### Summary

OGC has approved new glossary definitions for "lawfully admitted for permanent residence" and "U.S. National." These terms, in addition to making the term "Cooperatives" singular, need to be included for an update to the glossary.

### Related issues

- #4969 
- #4818 

### Completion criteria

- [x] Add PRs to the appropriate branches
- [x] Test in staging after release is cut
- [x] Link glossary items to "Foreign National page" once everything is on production

**Comment by dorothyyeager** [comment]
Just a note that when we paired on the PR, cooperative was already singular, so no changes needed for that term.

**Comment by djgarr** [comment]
Updates are in production. Everything is working properly. Added glossary links to the "Foreign nationals" page. Closed issue
