### ISSUE TITLE
Inventory of Wagtail pages that need annual updates

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#5051]
**User story**
As a user, I need to know the latest limits and get the latest versions of things.

**Background**
We have updated the site for 2022 coordinated expenditure limits and lobbyist bundling limits. There are a number of pages though that we should check to see if RECORD articles or videos need to be updated. The inventory list for checking can be found at https://docs.google.com/spreadsheets/d/164phGPvSHgvneNJUIV2WogMYl7MnDX5n0d2dIFNn9y8/edit#gid=0  and https://docs.google.com/document/d/1A_qyq7sSYpafxaVKDzqYknBxqjE2CFSl7BBIX7qXaW0/edit

Completion criteria:
- [x] Make updates as needed
- [x] Check the list for articles or videos that need to be updated. 
- [x] Check learning videos to see if any have been updated. 

Future work:
Will revisit in 2023

**Comment by djgarr** [comment]
The following videos would be helpful to update: 

- FECfile videos at https://www.fec.gov/help-candidates-and-committees/filing-reports/fecfile-software/ have not been updated since 2014 and 2016

**Comment by djgarr** [comment]
Will update the list for videos that could be updated as I come across any more
