### ISSUE TITLE
Catchup on redirects from transition 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#5063]
**What we're after:**
We are looking to remove transition pages off our serves. We have around 200 links that need to be tested and then redirects put in place. 

### Related issues
- #4995

### Completion criteria
- [x] Review Pat's testing link tab in our redirects excel sheet
- [x] If a link is broken figure out where it should redirect 
- [x] Put in a ticket(s) to put in the redirects 
- [x] Put in a take-down ticket to take down files that can just be deleted.

### Future work

- Testing tickets
- Take down tickets

**Comment by dorothyyeager** [comment]
This ticket was too broad. I'll continue to work through researching the list, but will split off the redirect work into its own tickets (there will be more than one), following our usual way of doing them.

**Comment by dorothyyeager** [comment]
Take down tickets, migration tickets and redirect tickets created. Closing and we'll move on to #5112, #5122, and #5123. Most of the redirects will happen in #5111
