### ISSUE TITLE
Take down recently redirected pages (17.4)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5080]
### Summary

**What we're after:**
Getting off transition 

### Related issues

- #5060 17.2 redirects
- #5063 

### Completion criteria

- [x] These files are removed from transition since redirects are working:

/law/policy/embezzle/embezzlementpolicycomments.shtml

/law/policy/enforcement/2013/2013commentsreceived.shtml

/law/policy/enforcement/2009/comments/comments.shtml

/MMWIP/3827d75c43e7e896/f818ed6ca0fc8a1a.shtml

/open/documents/PECF_monthly_report_2019.pdf 
/open/index.shtml

/pages/bcra/aos_bcra.shtml
/pages/bcra/bcra_update.shtml
/pages/bcra/rulemakings/rulemakings_bcra.shtml

/pages/brochures/foreign1.shtml
/pages/brochures/chart.gif
/pages/brochures/chart2.gif
/pages/brochures/chart3.gif
/pages/brochures/check.gif
/pages/brochures/choice.gif
/pages/hearings/internethearingcomments.shtml

**Comment by rfultz** [comment]
Should I also remove
- /MMWIP/3827d75c43e7e896/_notes
- pages/bcra/aos_bcra.htm

**Comment by dorothyyeager** [comment]
Yes please

**Comment by rfultz** [comment]
All done!
