### ISSUE TITLE
17.4 Banners (3/1 through 3/15/22)

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#5082]
### Summary

What we are after:
Content team is going to have routine sprint ticket for banner work each sprint to make sure we're on top of it.

### Related issues

[Banner spreadsheet](https://docs.google.com/spreadsheets/d/1MPGmgOFg-pjlkYZHUl28thVd1IPCQEmsseg7idH5ThU/edit?usp=sharing)
[Banner How to](https://docs.google.com/document/d/1Ehq3sxa6WXzLWf1UdwnbLIsKNTcCnSHIECcPYfWWhC4/edit?usp=sharing)

### Completion criteria

Banners set up for:
- [x] if needed: any Commission meeting or hearing that is scheduled during the sprint 
- - Open meeting scheduled for 3/10 (https://www.fec.gov/updates/march-10-2022-open-meeting/)
- [x] If needed: any change in status doc that may happen
- [x] Post any other banners that might be needed:
- EFO maintenance banner, running from 3/4 through 3/5

Additional banner work:
- [x] Create banner ticket for 17.5 and add it to PI planning doc for Content PI17

**Comment by dorothyyeager** [comment]
March 10 meeting banner is set up.

**Comment by dorothyyeager** [comment]
EFO banner set up for this weekend.

**Comment by dorothyyeager** [comment]
Status banner updated to remove link to safety plan - that now goes in with other routine reports at https://www.fec.gov/about/reports-about-fec/agency-operations/.
