### ISSUE TITLE
Add new "Rule of Agency Procedure" to the Policy and other guidance page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5085]
### Summary

**What we're after:**
The Commission approved a new "rule of agency procedure" - these go on our Policy page. We'll need to add this new one when it is published in the Federal Register.

### Completion criteria
- [x] Anything we need to coordinate with OGC is coordinated (Jessica Selinkoff is the person)
- [x] The Federal Register notice is uploaded once published (it won't be in SERS)
- [x] The section at https://www.fec.gov/legal-resources/policy-other-guidance/#rules-of-agency-organization-procedure-or-practice is updated to add the new FR notice, the Record article to be written and the related drafts (https://www.fec.gov/resources/cms-content/documents/mtgdoc-22-02-B.pdf and https://www.fec.gov/resources/cms-content/documents/mtgdoc-22-02-A.pdf), following the format of the other items in that section.
- [x] Second pair of eyes before publishing.

**Comment by djgarr** [comment]
page published. ticket closed
