### ISSUE TITLE
Draft methodology for overall House totals and overall Senate totals features

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5089]
**What we're after:**
We need to draft a methodology for the all House and all Senate totals features. 
Based on usability testing, users are interested in the following information in this methodology:
- Explanation of where the money came from
- How the data was compiled, formulas
- Include definitions of some of the terms
- What kinds of committees are included in each bucket (raising v spending)
- Plain language

Previous usability testing also suggested that users would be interested in dynamically generated figures that show the exact figure and how it was calculated, but that was at an individual committee. How might that work at an aggregate level?

**Completion criteria:**
- [ ] Methodology is drafted 
- [ ] Methodology is reviewed and approved by content and dev teams

**Designs:**
![Screen Shot 2022-02-28 at 5.06.42 PM.png](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/627df0de-64e0-4f14-9252-dc57fd59cff4)

**Comment by patphongs** [comment]
[Initial draft](https://docs.google.com/document/d/15ej48jO1kE7bOgqnhD2e85DI-OVrcXz79psbskU-57g/edit#) of the House and Senate election totals summary.

**Comment by patphongs** [comment]
Final draft now complete:

> ## Methodology
> 
> The totals raised, spent, and cash on hand presented in this chart include the sums from the two-year period data up to and including the most recently filed reports on [Form 3](https://www.fec.gov/resources/cms-content/documents/fecfrm3.pdf) (Report of Receipts and Disbursements) by authorized candidate committees. For the current two-year period, total raised, spent and cash on hand are the sums disclosed on each committee’s most recent report. It displays overall totals for the U.S. `[office_sought]` office and is further broken down by party.
> 
> Each total is calculated as follows:
> 
> - Total raised by all authorized candidate committees is the sum of total receipts of each reporting period disclosed by each authorized candidate committee (Form 3, Line 16, Column A)
> - Total spent by all authorized candidate committees is the sum of total disbursements of each reporting period disclosed by each authorized candidate committee (Form 3, Line 22, Column A)
> - Total cash on hand of all authorized candidate committees is the sum of all cash on hand that remains at the end of the selected two-year period (Form 3, Line 8). 
>
