### ISSUE TITLE
Draft methodology for contributions across time feature for all House and all Senate

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5090]
**What we're after:**
We need to draft a methodology for the all House and all Senate contributions across time feature. 
Based on usability testing, users are interested in the following information in this methodology:
- Explanation of where the money came from
- How the data was compiled, formulas
- Include definitions of some of the terms
- What kinds of committees are included
- Plain language
- Coverage dates

**Completion criteria:**
- [x] Methodology is drafted 
- [ ] Methodology is reviewed and approved by content and dev teams

**Designs:**
<img width="709" alt="Screen Shot 2022-02-28 at 5 00 34 PM" src="https://user-images.githubusercontent.com/31663028/156065893-e658566c-78d6-4be8-82e9-810937cc0345.png">

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Here's the information to include in the methodology from our discussion with content. Do you mind updating your draft? Then we should tag some folks to look at it. 

**Individual contributions:**
Include Form 3, Line 11(a)(i)

**PACs and other committee contributions:**
Include Form 3, Line 11(c). All itemized contributions from PACs and other political committees, including state PACs and other federal candidate committees. Party committee and Super PAC contributions are not included.

**Transfers:**
Include Form 3, Line 12

**General methodology language additions:**
Include link to archived contribution limits page.

**Comment by johnnyporkchops** [comment]
@JonellaCulmer I  incorporated  this language into the draft in the [comment above ](https://github.com/fecgov/fec-cms/issues/5090#issuecomment-1071011390)

**Comment by dorothyyeager** [comment]
Just my thought on this line; I don't feel strongly about this if others disagree:

```
PACs and other committee contributions:
Include Form 3, Line 11(c). All itemized contributions from PACs and other political committees, including state PACs and other federal candidate committees. Party committee and Super PAC contributions are not included.
```

Suggest changing to:
Other committee contributions
Include Form 3, Line 11(c). All itemized contributions from other political committees, including federally registered PACs, committees registered at a state or local level and other federal candidate committees. Party committee and Super PAC contributions are not included.

Also for this line: This data is generated from [FEC Form 3- REPORT OF RECEIPTS AND DISBURSEMENTS](https://www.fec.gov/resources/cms-content/documents/fecfrm3.pdf) 
Take out "FEC" (content guide thing).

**Comment by PaulClark2** [comment]
> PACs and other committee contributions:
> Include Form 3, Line 11(c). All itemized contributions from PACs and other political committees, including state PACs and other federal candidate committees. Party committee and Super PAC contributions are not included.

I have other edits, but I wanted to start with this. I'm not sure I understand why we include this phrase "including state PACs and other federal candidate committees." Also, I think "state PACs" is confusing. I don't know that that term means. Are these federally registered state PACs like the Alabama Republican Party or the Alaska Democratic Party? Are they actually state PACs not registered with the FEC? Dorothy's edit might help with my confusion here.

**Comment by PaulClark2** [comment]
> This data is generated from [FEC Form 3- REPORT OF RECEIPTS AND DISBURSEMENTS](https://www.fec.gov/resources/cms-content/documents/fecfrm3.pdf)

We should drop "FEC" and the name of the form should be initial case like, https://www.fec.gov/help-candidates-and-committees/forms/.  

> General methodology language additions:
> Include link to archived contribution limits page.
> [Archived contribution limits](https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/archived-contribution-limits/)

I'm just curious about this. Will the link to the archived contribution limits be incorporated into the introductory sentences? Will it remain in a separate section like it is above?

**Comment by johnnyporkchops** [comment]
Methodology moved to google doc, with above comments added
https://docs.google.com/document/d/1-6gGhRtNiMrcPr48CMgriFMfBP-S57TXvy5VFF-KE4s/edit

**Comment by PaulClark2** [comment]
🔒 [draft](https://docs.google.com/document/d/1-6gGhRtNiMrcPr48CMgriFMfBP-S57TXvy5VFF-KE4s/edit) 🔒

**Comment by PaulClark2** [comment]
Thanks, @djgarr . @johnnyporkchops , @JonellaCulmer @patphongs here's are working draft. 

## Methodology

The totals presented in the chart are calculated using data submitted by principal campaign and authorized committees on [Form 3](https://www.fec.gov/resources/cms-content/documents/fecfrm3.pdf) (Report of Receipts and Disbursements) for the selected office by two-year periods. Financial summary data for this chart are available from 2005 to present.

These totals do not include data from Form 6 (48-Hour Notice of Contributions/Loans Received) or Form 3L (Report of Contributions Bundled by Lobbyists/Registrants and Lobbyist/Registrant PACs).

For contributions across time, data are calculated as follows: 

- Individual contributions: the sum of Form 3, Line 11(a)(i) by two-year period 
- PAC and other committee contributions: the sum of Form 3, Line 11(c) by two-year period. Party committee and Super PAC contributions are not included in this total.  
- Transfers from other authorized committees: the sum of Form 3, Line 12 by two-year period.

### Contribution limits
[Contribution limits](https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/contribution-limits/) have changed over time. Historical contribution limits are available on our Archive of contribution limits [page](https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/archived-contribution-limits/).

**Comment by djgarr** [comment]
Works for me
