### ISSUE TITLE
Draft methodology for the all totals for House and Senate

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5091]
**What we're after:**
We need to draft a methodology for the all House and all Senate totals table feature. 

Based on usability testing, users are interested in the following information in this methodology:
- Explanation of where the money came from
- How the data was compiled, formulas
- Include definitions of some of the terms
- What kinds of committees are included in each bucket (raising v spending)
- Plain language

Draft the methodology in a google doc. Someone with data knowledge should start the methodology first, then share with PMs and content for review. Consider templatizing the methodology for future feature methodology language. 

**Completion criteria:**
- [ ] Methodology is drafted 
- [ ] Methodology is reviewed and approved by content and dev teams

**Designs:**
![Screen Shot 2022-02-28 at 5.00.25 PM.png](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/ccb64afe-fd79-486c-ab41-fb2372bd32f9)

**Comment by patphongs** [comment]
[Draft methodology](https://docs.google.com/document/d/1hm-ymr-I-pEpCpGJkogzqVu2ha5NyY85aFhygVY3Rng/edit#) for review 🔒

**Comment by JonellaCulmer** [comment]
@PaulClark2 @hcaofec @djgarr  Looks good to me. My thought though would be to split up the first paragraph a bit. 

The totals presented in the table are calculated using a two-step process: in step one, financial data reported within a two-year period is aggregated by candidate campaign committees creating totals by candidate by two-year `period. In step two,` candidates are grouped by state and two-year period creating totals by state and two-year period. Financial summary data are available from 1979 to present.

cc: @patphongs @johnnyporkchops

**Comment by PaulClark2** [comment]
@JonellaCulmer I'm fine with that if @djgarr and @hcaofec are.

**Comment by djgarr** [comment]
@PaulClark2 @JonellaCulmer @hcaofec I'm ok breaking the first part up a bit, with an additional change to remove the colon. I also missed a "data are plural" example earlier and corrected it. Here's my minor update:

The totals presented in the table are calculated using a two-step process. In step one, financial data reported within a two-year period are aggregated by candidate campaign committees creating totals by candidate by two-year period. In step two, candidates are grouped by state and two-year period creating totals by state and two-year period. Financial summary data are available from 1979 to present.

**Comment by patphongs** [comment]
Looks good to me!
