### ISSUE TITLE
Add COVID-19 guidance to website

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5095]
**What we're after:**
We need to add messaging to the website that briefly outlines our COVID-19 guidance for visits to FEC building. We're going to think through the use of a code snippet to update multiple locations on the website simultaneously. It must also be easily editable for on-the-fly changes. 

**Draft language:**
Washington, D.C.’s COVID-19 Community Level is currently **LOW**. 
Individuals visiting FEC offices are not required to wear masks, regardless of vaccination status. Masks are required in certain shared spaces, including the building lobby, elevators and stairwells.

Some suggested locations:
- Meeting pages
- Contact page
- ~Footer~

**Completion criteria:**
- [ ] New language posted to the website in easily editable format 
- [ ] Create a follow-up ticket to add the new informational snippet to the FEC contact page with approved language after these changes are deployed to production on 3/08.

**Comment by JonellaCulmer** [comment]
@patphongs Here's my first draft. Mimics what's on the OIG page. Didn't think it needed the huge text we use in other types of messages. Let me know if you have any questions or concerns. 

![Screen Shot 2022-03-03 at 11 43 32 AM](https://user-images.githubusercontent.com/31663028/156610747-753f32f3-b77d-4870-89a3-037687f845d1.png)

**Comment by lbeaufort** [comment]
@patphongs @JonellaCulmer Should this page automatically pull transmission status from CDC so it doesn't have to be updated manually every time the community level changes?

**Comment by patphongs** [comment]
> Should this page automatically pull transmission status from CDC so it doesn't have to be updated manually every time the community level changes?

I thought about doing this, however, I decided to go the manual route because guidance always needs time to change as transmission levels change. If we become more fluent in these changes, I think doing it in an automated way is a good idea for a future ticket.

**Comment by pkfec** [comment]
PR  https://github.com/fecgov/fec-cms/pull/5096  merged to [cms-release-branch] (https://github.com/fecgov/fec-cms/pull/5093). Closing this issue.
