### ISSUE TITLE
Migrate or archive older files from old /open transition directory

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5112]
### Summary

**What we're after:**
There were some older files in the open/ directory on transition. We need to archive some of them, upload some of them, and put in redirects.

### Related issues

#5063 - Catchup on transition redirects

### Completion criteria

- [x] Archive these transition files offline somewhere (check with Pat) and redirect all of them to https://www.fec.gov/about/open/ (lines 253-255 of transition inventory)
/open/documents/2016-MD-715%20-OGOV.pdf
/open/documents/FY-2016-Privacy-ManagementReport-to-OMB.pdf
/open/documents/Non-Federal-Source-Travel-Report-April1-Sept30-2016.pdf

- [x] Upload these files to the CMS and put in redirects from transition to their new URLS (lines 257-259 of the redirect spreadsheet)
/open/documents/PECF_monthly_report_2016.pdf
/open/documents/PECF_monthly_report_2017.pdf
/open/documents/PECF_monthly_report_2018.pdf
/open/documents/PECF_monthly_report_2019.pdf

- [x] Add these redirects to the testing ticket created in #5125

**Comment by kathycarothers** [comment]
@dorothyyeager I am not sure where this one is /open/documents/Non-Federal-Source-Travel-Report-April1-Sept30-2016.pdf
It is not within 253-255 in the excel sheet. Rather this one is listed for 255 [https://transition.fec.gov/open/documents/gifts-to-foreigners-fy2016-letter.pdf].

**Comment by dorothyyeager** [comment]
@kathycarothers Sorry about that! I forgot to copy it from Pat's page. It's there now. That makes the lines to be redirected for this ticket lines 253-256

**Comment by kathycarothers** [comment]
Sounds good I will go back in and add it. @dorothyyeager

**Comment by dorothyyeager** [comment]
Testing ticket created ^

**Comment by kathycarothers** [comment]
@patphongs The above-mentioned files are ready for you to archive offline. I have uploaded them into the CMS. Also, the pr is ready for your review and merge.

**Comment by dorothyyeager** [comment]
@patphongs We're not going to migrate those files but Amy wanted to preserve them offline somewhere (similar to what you did with some Information Division files). Instead we're going to redirect them to the open government page.

**Comment by patphongs** [comment]
@AmyKort I noticed the [FY 2016 management report is in Wagtail](https://www.fec.gov/resources/cms-content/documents/FY-2016-Privacy-ManagementReport-to-OMB.pdf) and it is also on [transition](https://transition.fec.gov/open/documents/FY-2016-Privacy-ManagementReport-to-OMB.pdf). Did you want me to remove it from both locations and just put it in the offline archive?

@kathycarothers Those files that were in the `/open/` folder in transition are now in our [offline archive here](https://drive.google.com/drive/folders/1-xGbDQl4nMtlu56JNZHfHe8EdMaF4fXw) 🔒

**Comment by AmyKort** [comment]
That sounds great, thanks!

**Comment by kathycarothers** [comment]
Thank you all!
