### ISSUE TITLE
H4CC: Updating "Making disbursements" with changes from the new Candidate

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#5120]
### Summary

**What we're after:**
_We need to ensure that the updates for the Candidate Guide are reflected on our website_

### Related issues

- #5101 
- #5013 
- #5120 
- #5160 

### Completion criteria
_Compare the web page "Making disbursements" against the excel document to see the pages under it that need to be updated. Excel sheet can be found at https://docs.google.com/spreadsheets/d/1jT2XGwgFYNsiOwaQJV0n_XwxmK7afItcntNXyZ0KcEI/edit#gid=93471181

 Pages for updating under the tab -

- Day-to-day operations - DONE
- Transfers between a candidate's committees - DONE
- Fundraising notices for campaigns - DONE
- Joint fundraising with other candidates and political committees - DONE
- Travel - Done
- Advertising and disclaimers - Done
- Noncampaign expenses for travel, transfers, and donations - DONE
- Making contributions to other candidates - Done
- Fundraising for other candidates, committees, and organizations - DONE
- Personal use - Done

- [x]  Compare with the new Guide
- [x]  Incorporate new examples if needed
- [x]  Draft the page as a word document so reviewers can see the changes. Save in \ntsrv1\InfoProj\H4CC Candidate Guide Updates
- [x]  Second pair of eyes for review (Include George) before updating and publishing in Wagtail
- [x]  Update in Wagtail and publish

### Future work

- [x] Create the next ticket for the tab entitled "Taking Receipts" (#5160)

**Comment by kathycarothers** [comment]
I have finished my assigned parts

**Comment by dorothyyeager** [comment]
I've finished my parts.

**Comment by djgarr** [comment]
Updated pages. Added redirect. Done
