### ISSUE TITLE
Update hybrid PAC description on committee profile pages 

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#5121]
### Summary

**What we're after:**
So that we are consistent, we should consider updating the description of hybrid PACs on committee profile pages to be consistent with the newly approved Form 1. 

Current hybrid PAC description on committee profile pages

- PAC with Non-Contribution Account - Nonqualified
- PAC with Non-Contribution Account - Qualified

Updated hybrid PAC description

- Hybrid PAC (with Non-Contribution Account) - Nonqualified
- Hybrid PAC (with Non-Contribution Account) - Qualified

### Related issues

The content team has work related to the Form 1 update to complete. 
Do we need to update any reference tables in the database?
Do we need to update any description fields of existing hybrid PACs? 

### Completion criteria

- [ ] A verifiable list has been created where all these terms are located
- [ ] Hybrid PAC committee profile pages display the new hybrid PAC description
- [ ] Applicable datatable filters display the new hybrid PAC description
- [ ] Applicable datatable rows and flyout panels display the new hybrid PAC description
- [x] Update data description page (https://www.fec.gov/campaign-finance-data/committee-type-code-descriptions/)

**Comment by JonellaCulmer** [comment]
Does this include datatable filters?
<img width="287" alt="Screen Shot 2022-04-14 at 5 07 09 PM" src="https://user-images.githubusercontent.com/31663028/163475232-0712dfcd-6263-4659-902b-a226721d33e6.png">

- https://www.fec.gov/data/committees/
- https://www.fec.gov/data/committees/pac-party/?cycle=2022
- https://www.fec.gov/data/receipts/?data_type=processed&two_year_transaction_period=2022&min_date=01%2F01%2F2021&max_date=12%2F31%2F2022
- https://www.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2022&min_date=01%2F01%2F2021&max_date=12%2F31%2F2022
- https://www.fec.gov/data/disbursements/?data_type=processed&two_year_transaction_period=2022&min_date=01%2F01%2F2021&max_date=12%2F31%2F2022

^ Not a complete list

**Comment by johnnyporkchops** [comment]
Also appears on datatable rows  and flyout panels:

<img width="989" alt="Screen Shot 2022-05-08 at 12 24 08 AM" src="https://user-images.githubusercontent.com/5572856/167281673-bd11d51e-764a-42f8-a52d-5a22c306d977.png">

**Comment by PaulClark2** [comment]
I think it should include both the data table filers, data table rows and the flyouts panels. I will update the underlying data in the database.

**Comment by hcaofec** [comment]
database function public.expand_committee_type need to be updated to display hybrid PAC description on committee profile pages. 

Here is the ticket: [#5313](https://github.com/fecgov/openFEC/issues/5133)

**Comment by PaulClark2** [comment]
I have updated the descriptions of committee types V and W in staging.ref_filed_cmte_tp and disclosure.cmte_valid_fec_yr on FECP, FECPTST, and FECPDEV

Follow-on work in ticket https://github.com/fecgov/openFEC/issues/5133
