### ISSUE TITLE
Take down old files that can be deleted (17.5 - 17.6)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5122]
### Summary

**What we're after:**
We are cleaning out transition

### Related issues

_List any relevant related issue(s)_

- #5063 

### Completion criteria

- [ ] These files removed from transition and content team notified so they can update spreadsheet. Some may already have been removed and that's fine.
- [ ] Remove directly from  transition prod via FTP
- [ ]  Or from transition stage `fecas065`  via FTP and then SSH in and run `./prod-sync-and-delete.sh`(because the half-hourly auto sync does not remove deleted files)

/law/policy/enforcement/2013/2013commentsreceived.shtml
/law/policy/enforcement/2013/crewcover.pdf
/law/policy/enforcement/2013/crew.pdf
/law/policy/enforcement/2013/danacohn1.pdf
/law/policy/enforcement/2013/danacohn2.pdf
/law/policy/enforcement/2013/gregsmith.pdf
/law/policy/enforcement/2013/joeorawczyk.pdf
/law/policy/enforcement/2013/josefiaktorshinskybayescover.pdf
/law/policy/enforcement/2013/josefiaktorshinskybayes.pdf
/law/policy/enforcement/2013/mjbauer.pdf
/law/policy/enforcement/2013/perkinscoiecover.pdf
/law/policy/enforcement/2013/perkinscoie.pdf
/law/policy/enforcement/2013/progressivesunited1.pdf
/law/policy/enforcement/2013/progressivesunited2.pdf
/law/policy/enforcement/2013/rnccounselcover.pdf
/law/policy/enforcement/2013/rnccounsel.pdf
/law/policy/enforcement/2013/roberterutkowski.pdf

/law/policy/internet09/070109websitecomments.pdf
/law/policy/internet09/070609websitecomments.pdf
/law/policy/internet09/6-26-09websitecomments.pdf
/law/policy/internet09/6-27-09websitecomments.pdf
/law/policy/internet09/6-28-09websitecomments.pdf
/law/policy/internet09/6-29-09websitecomments.pdf
/law/policy/internet09/actbluecomment072109.pdf
/law/policy/internet09/agencyhearingextract.pdf
/law/policy/internet09/cathdemhearingcomment.pdf
/law/policy/internet09/comments070809.pdf
/law/policy/internet09/comments071409.pdf
/law/policy/internet09/comments071409.pdf.pdf 
/law/policy/internet09/comments071609.pdf
/law/policy/internet09/comments071709.pdf
/law/policy/internet09/comments071809.pdf
/law/policy/internet09/comments072009.pdf
/law/policy/internet09/comments072109.pdf
/law/policy/internet09/houghtalingcomment072709.pdf
/law/policy/internet09/houghtaling.pdf
/law/policy/internet09/notice_2009-10.pdf
/law/policy/internet09/notice_2009-14.pdf
/law/policy/internet09/sunlighthearingcomment.pdf
/law/policy/internet09/webmanageremails.pdf
/law/policy/internet09/westcomments072909.pdf

/law/ultimatepayee/marcelias030413.pdf

/open/documents/FY-2016-Privacy-ManagementReport-to-OMB.pdf
/open/documents/gifts-to-foreigners-fy2016-letter.pdf
/open/documents/Non-Federal-Source-Travel-Report-April1-Sept30-2016.pdf
/open/documents/PECF_monthly_report_2016.pdf
/open/documents/PECF_monthly_report_2017.pdf
/open/documents/PECF_monthly_report_2018.pdf
/open/documents/PECF_monthly_report_2019.pdf

/pages/bcra - could probably delete entire file
/pages/bcra/02-1674.pdf
/pages/bcra/aos_bcra.htm
/pages/bcra/bcra-stay-mem.pdf
/pages/bcra/bcra-stay-temp-mem.pdf
/pages/bcra/bcra_update.shtml
/pages/bcra/bcra_webform_ec.pdf
/pages/bcra/litigation.shtml
/pages/bcra/major_resources_bcra.shtml
/pages/bcra/wrtl_complaint_amended.pdf
/pages/bcra/wrtl_complaint.pdf
/pages/bcra/wrtl_dccirc.pdf
/pages/bcra/wrtl_dc_remand_fec_opp_plaintiff_motion_tro_pi.pdf
/pages/bcra/wrtl_dc_remand_fec_summ_judg_mot.pdf
/pages/bcra/wrtl_dc_remand_fec_summ_judg_mot_reply_exh.pdf
/pages/bcra/wrtl_dc_remand_fec_summ_judg_mot_reply.pdf
/pages/bcra/wrtl_dc_remand_opinion_granting_wrtl_sj.pdf
/pages/bcra/wrtl_fec_motion_summary_judgment.pdf
/pages/bcra/wrtl_FEC_opposition_to_pls_motion_for_prelim_injunction.pdf
/pages/bcra/wrtl_fec_opp_pls_motion_pl_dccir.pdf
/pages/bcra/wrtl_memo_opinion_district_court.pdf
/pages/bcra/wrtl_motion_dismiss_appeal_dccir.pdf
/pages/bcra/wrtl_opinion.pdf
/pages/bcra/wrtl_opp_fec_application_inj_pending_appeal_filed_by_sg.pdf
/pages/bcra/wrtl_order_district_court.pdf
/pages/bcra/wrtl_sc_appellee_brief.pdf

/pages/brochures/adr.shtml
/pages/brochures/bkgdseal.gif
/pages/brochures/calendar.jpg/
/pages/brochures/fedstat2.gif
/pages/brochures/fedstate.gif
/pages/brochures/fed_state/pages/brochures
/pages/foreign.gif_law_brochure.pdf
/pages/brochures/forvol.gif
/pages/brochures/hands.jpg
/pages/brochures/img_0034.jpg
/pages/brochures/immigran.gif
/pages/brochures/indexp2.gif
/pages/brochures/internalcontrols.pdf
/pages/brochures/limit.gif
/pages/brochures/men.jpg
/pages/brochures/office.jpg
/pages/brochures/pens.gif
/pages/brochures/prez1.gif
/pages/brochures/prez2.gif
/pages/brochures/prez3.gif
/pages/brochures/prez_checkoff.gif
/pages/brochures/prez.gif
/pages/brochures/prohib.gif
/pages/brochures/slcol2.jpg
/pages/brochures/statefed.shtml
/pages/brochures/table.jpg
/pages/brochures/treas2.gif
/pages/brochures/treas3.gif
/pages/brochures/treas.gif
/pages/brochures/whouse.gif
/pages/brochures/working.jpg

/pages/brochures/images/clip_image002_000.gif
/pages/brochures/images/clip_image002.gif
/pages/brochures/images/clip_image004_000.gif
/pages/brochures/images/clip_image004.gif
/pages/brochures/images/clip_image006_000.gif
/pages/brochures/images/clip_image006.gif
/pages/brochures/images/limit.gif

/pages/hearings/hearing_transcript20090825.pdf
/pages/hearings/internethearingcomments.shtml
/pages/hearings/statusofwebsiteinitiative-bluedraftrev.pdf

**Comment by patphongs** [comment]
Files have been deleted:

```
Fri Apr 8 11:09:50 EDT 2022
delete: '/law/policy/enforcement/2013/crew.pdf'
delete: '/law/policy/enforcement/2013/crewcover.pdf'
delete: '/law/policy/enforcement/2013/danacohn1.pdf'
delete: '/law/policy/enforcement/2013/danacohn2.pdf'
delete: '/law/policy/enforcement/2013/gregsmith.pdf'
delete: '/law/policy/enforcement/2013/joeorawczyk.pdf'
delete: '/law/policy/enforcement/2013/josefiaktorshinskybayes.pdf'
delete: '/law/policy/enforcement/2013/josefiaktorshinskybayescover.pdf'
delete: '/law/policy/enforcement/2013/mjbauer.pdf'
delete: '/law/policy/enforcement/2013/perkinscoie.pdf'
delete: '/law/policy/enforcement/2013/perkinscoiecover.pdf'
delete: '/law/policy/enforcement/2013/progressivesunited1.pdf'
delete: '/law/policy/enforcement/2013/progressivesunited2.pdf'
delete: '/law/policy/enforcement/2013/rnccounsel.pdf'
delete: '/law/policy/enforcement/2013/rnccounselcover.pdf'
delete: '/law/policy/enforcement/2013/roberterutkowski.pdf'
delete: '/law/policy/internet09/070109websitecomments.pdf'
delete: '/law/policy/internet09/070609websitecomments.pdf'
delete: '/law/policy/internet09/6-26-09websitecomments.pdf'
delete: '/law/policy/internet09/6-27-09websitecomments.pdf'
delete: '/law/policy/internet09/6-28-09websitecomments.pdf'
delete: '/law/policy/internet09/6-29-09websitecomments.pdf'
delete: '/law/policy/internet09/actbluecomment072109.pdf'
delete: '/law/policy/internet09/agencyhearingextract.pdf'
delete: '/law/policy/internet09/cathdemhearingcomment.pdf'
delete: '/law/policy/internet09/comments070809.pdf'
delete: '/law/policy/internet09/comments071409.pdf'
delete: '/law/policy/internet09/comments071409.pdf.pdf'
delete: '/law/policy/internet09/comments071609.pdf'
delete: '/law/policy/internet09/comments071709.pdf'
delete: '/law/policy/internet09/comments071809.pdf'
delete: '/law/policy/internet09/comments072009.pdf'
delete: '/law/policy/internet09/comments072109.pdf'
delete: '/law/policy/internet09/houghtaling.pdf'
delete: '/law/policy/internet09/houghtalingcomment072709.pdf'
delete: '/law/policy/internet09/notice_2009-10.pdf'
delete: '/law/policy/internet09/notice_2009-14.pdf'
delete: '/law/policy/internet09/sunlightcomments072109.pdf'
delete: '/law/policy/internet09/sunlighthearingcomment.pdf'
delete: '/law/policy/internet09/webmanageremails.pdf'
delete: '/law/policy/internet09/westcomments072909.pdf'
delete: '/law/ultimatepayee/marcelias030413.pdf'
delete: '/open/documents/FY-2016-Privacy-ManagementReport-to-OMB.pdf'
delete: '/open/documents/Non-Federal-Source-Travel-Report-April1-Sept30-2016.pdf'
delete: '/open/documents/PECF_monthly_report_2016.pdf'
delete: '/open/documents/PECF_monthly_report_2017.pdf'
delete: '/open/documents/PECF_monthly_report_2018.pdf'
delete: '/open/documents/gifts-to-foreigners-fy2016-letter.pdf'
delete: '/pages/bcra/02-1674.pdf'
delete: '/pages/bcra/bcra-stay-mem.pdf'
delete: '/pages/bcra/bcra-stay-temp-mem.pdf'
delete: '/pages/bcra/bcra_webform_ec.pdf'
delete: '/pages/bcra/litigation.shtml'
delete: '/pages/bcra/major_resources_bcra.shtml'
delete: '/pages/bcra/wrtl_FEC_opposition_to_pls_motion_for_prelim_injunction.pdf'
delete: '/pages/bcra/wrtl_complaint.pdf'
delete: '/pages/bcra/wrtl_complaint_amended.pdf'
delete: '/pages/bcra/wrtl_dc_remand_fec_opp_plaintiff_motion_tro_pi.pdf'
delete: '/pages/bcra/wrtl_dc_remand_fec_summ_judg_mot.pdf'
delete: '/pages/bcra/wrtl_dc_remand_fec_summ_judg_mot_reply.pdf'
delete: '/pages/bcra/wrtl_dc_remand_fec_summ_judg_mot_reply_exh.pdf'
delete: '/pages/bcra/wrtl_dc_remand_opinion_granting_wrtl_sj.pdf'
delete: '/pages/bcra/wrtl_dccirc.pdf'
delete: '/pages/bcra/wrtl_fec_motion_summary_judgment.pdf'
delete: '/pages/bcra/wrtl_fec_opp_pls_motion_pl_dccir.pdf'
delete: '/pages/bcra/wrtl_memo_opinion_district_court.pdf'
delete: '/pages/bcra/wrtl_motion_dismiss_appeal_dccir.pdf'
delete: '/pages/bcra/wrtl_opinion.pdf'
delete: '/pages/bcra/wrtl_opp_fec_application_inj_pending_appeal_filed_by_sg.pdf'
delete: '/pages/bcra/wrtl_order_district_court.pdf'
delete: '/pages/bcra/wrtl_sc_appellee_brief.pdf'
delete: '/pages/brochures/adr.shtml'
delete: '/pages/brochures/calendar.jpg'
delete: '/pages/brochures/fedstat2.gif'
delete: '/pages/brochures/fedstate.gif'
delete: '/pages/brochures/foreign.gif'
delete: '/pages/brochures/forvol.gif'
delete: '/pages/brochures/hands.jpg'
delete: '/pages/brochures/images/clip_image002.gif'
delete: '/pages/brochures/images/clip_image002_000.gif'
delete: '/pages/brochures/images/clip_image004.gif'
delete: '/pages/brochures/images/clip_image004_000.gif'
delete: '/pages/brochures/images/clip_image006.gif'
delete: '/pages/brochures/images/clip_image006_000.gif'
delete: '/pages/brochures/images/limit.gif'
delete: '/pages/brochures/img_0034.jpg'
delete: '/pages/brochures/immigran.gif'
delete: '/pages/brochures/indexp2.gif'
delete: '/pages/brochures/internalcontrols.pdf'
delete: '/pages/brochures/limit.gif'
delete: '/pages/brochures/men.jpg'
delete: '/pages/brochures/office.jpg'
delete: '/pages/brochures/pens.gif'
delete: '/pages/brochures/prez.gif'
delete: '/pages/brochures/prez1.gif'
delete: '/pages/brochures/prez2.gif'
delete: '/pages/brochures/prez3.gif'
delete: '/pages/brochures/prez_checkoff.gif'
delete: '/pages/brochures/prohib.gif'
delete: '/pages/brochures/slcol2.jpg'
delete: '/pages/brochures/statefed.shtml'
delete: '/pages/brochures/table.jpg'
delete: '/pages/brochures/treas.gif'
delete: '/pages/brochures/treas2.gif'
delete: '/pages/brochures/treas3.gif'
delete: '/pages/brochures/whouse.gif'
delete: '/pages/brochures/working.jpg'
delete: '/pages/hearings/hearing_transcript20090825.pdf'
delete: '/pages/hearings/statusofwebsiteinitiative-bluedraftrev.pdf'
```
