### ISSUE TITLE
Feedback button errors on Congressional Pre-Election Dates Page

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#5124]
### Summary
The feedback button errors on this page: https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/2022-reporting-dates/congressional-pre-election-reporting-dates-2022/

It still works on other pages.

This issue was reported by a registered committee in a call to RAD. RAD staff reproduced and reported to me.

### Frequency
Every time I try to submit feedback. 

### How to Reproduce

1. Open https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/2022-reporting-dates/congressional-pre-election-reporting-dates-2022/
2. Click Feedback
3. Click "Post"

### Technical considerations:
- Investigate why the page is getting a `Content Security Policy (CSP)`  error, see screenshot below
- Investigate why the page is trying to submit to `https://issue `

### Completion criteria:

- [ ] User can submit feedback from  [Congressional pre-election dates page](https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/2022-reporting-dates/congressional-pre-election-reporting-dates-2022/)

### Screenshots
<img width="1197" alt="Screen Shot 2022-03-23 at 9 41 35 PM" src="https://user-images.githubusercontent.com/5572856/159825067-c6076366-6666-4391-a99c-1bb26b21bddc.png">

**Comment by rfultz** [comment]
The CSP is because we haven't approved https://issue/.

There are several references in our code to `/data/issue/` and `/data/issue/reaction/` but those 404—they're not real pages or even redirects

**Comment by johnnyporkchops** [comment]
@rfultz Would you expect this to happen on every page, if we have not  approved https://issue/ in the CSP?
Can we add https://issue/ to CSP ?
