### ISSUE TITLE
Reporting examples: Draft  new images for the updated Form 1 for reporting pages 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#5133]
### Summary

**What we're after:**
We need to update/draft images of the reporting examples that display Form 1 to be consistent with the newly approved Form 1.

### Related issues

_List any relevant related issue(s)_

- #5134
- #5135 
- #5172 

### Completion criteria

The following reporting examples need their images updated for the newly revised Form 1:

- Candidate committees: https://www.fec.gov/help-candidates-and-committees/filing-reports/registering-committee/
- Converting a multicandidate committee: https://www.fec.gov/help-candidates-and-committees/filing-reports/converting-multicandidate-committee/ No updates needed 
- SSFs: https://www.fec.gov/help-candidates-and-committees/filing-ssf-reports/registering-ssf/
- Registering as a nonconnected committee: https://www.fec.gov/help-candidates-and-committees/filing-pac-reports/registering-nonconnected-committee/ image and text 

- [x] Reach out to Jim Jones for new images

**Comment by kathycarothers** [comment]
I have reached out to Jim regarding the images 4/14.

**Comment by jjonesfec** [comment]
Began work retrofitting the new Form 1 onto the  appropriate examples.

**Comment by jjonesfec** [comment]
Images completed. The image of page 2 on _Converting to a multicandidate_ was not affected by the recent changes and does not need updating.

**Comment by dorothyyeager** [comment]
Reopening for some things caught in review process.

**Comment by jjonesfec** [comment]
Completed and transmitted all Form 1 images requested to-date.
