### ISSUE TITLE
Reporting examples: Updating/Draft Form 1 with new images and language 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#5134]
### Summary

**What we're after:**
We need to update the reporting examples that display the Form 1 to be consistent with the newly approved Form 1.

### Related issues

- #5133 

### Completion criteria

The following reporting examples need their images and language updated for the newly revised Form 1:

- Super PACs: https://www.fec.gov/help-candidates-and-committees/filing-pac-reports/registering-super-pac/  (Brad)
- Hybrid PACs: https://www.fec.gov/help-candidates-and-committees/filing-pac-reports/registering-hybrid-pac/ (Brad)
- Nonconnected PACs: https://www.fec.gov/help-candidates-and-committees/filing-pac-reports/registering-nonconnected-committee/ (Kathy)
- Joint Fundraising: https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/registering-joint-fundraising-representative/  (Kathy)
- How to register an SSF https://www.fec.gov/help-candidates-and-committees/filing-ssf-reports/registering-ssf/ (Kathy)
- Nonconnected remove text and make sure reporting examples are connected
https://www.fec.gov/help-candidates-and-committees/registering-pac/registering-nonconnected-committee/ (Dorothy)

- [x] Reach out to Jim Jones for images
- [x] Draft revisions for review by RAD management
- [x] Be sure to remove FECFiles videos for Form 1 (they need to be updated)
- [x] Update Wagtail page
- [x] Second pair of eyes
- [x] Brad final green light
- [x] Publish on May 17

**Comment by bmathesonFEC** [comment]
Super PAC and Hybrid PAC drafts are ready for review. Will circulate among team after our 10am meeting. These two pages were not among the first round of image creation submissions to Jim. Will submit the draft I have prepared for him after the meeting.
