### ISSUE TITLE
May 17: Upload revised Form 1 (PDF and screenfillable) and update H4CC pages [Do after revised form becomes effective]

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5135]
### Summary

**What we are after:**
The FEC has approved revisions to Form 1 and they are pending before Congress now. At 4 pm on May 17, we will need to upload the newly revised form. We'll also handle uploading related PDFs and updating related pages in this ticket (FEC File page, Forms page)

[Spreadsheet for Form 1 update sub-epic work](https://docs.google.com/spreadsheets/d/1LiaUjoqK5RGd5q_M6AUVcI4C1JDVDvoye7SfgxWNtTo/edit#gid=0)

### Related tickets

- #5133 
- #5172 
- #5212 
- #5213 

### Completion criteria

- [x] 508 compliant version of the revised Form 1 is uploaded (work with @jjonesfec)
- [x] 508 compliant version of the screenfillable Form 1 is uploaded (work with @jjonesfec)
- [x] 508 compliant version of the instructions is uploaded (work with jjonesfec)
- [x] Upload revised FECFile manuals for candidates and PAC/party (work with @bmathesonFEC)

- [x] Forms page is updated to remove references to letters.
- [x] FECFile page is updated to update the release notes for FECFile.

**Comment by dorothyyeager** [comment]
We uploaded the instructions file that was sent, but it will need 508 remediation. We also need to receive the FECFile manuals.

**Comment by jjonesfec** [comment]
An accessible PDF was sent to @kathycarothers this morning.

**Comment by jjonesfec** [comment]
*Instructions PDF

**Comment by dorothyyeager** [comment]
Updated 508-compliant instructions and the FECFile manual for candidates was uploaded today.

**Comment by dorothyyeager** [comment]
Going to close out this ticket. The FECFile manual for PAC/parties might take some time to update. We can handle that upload as a routine content team task.  All other items have been uploaded or updated as needed.
