### ISSUE TITLE
End GTM Experiment for Data Landing Page

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#5137]
### Summary

**What we're after:**

End the /data/ GTM experiment after #5087 goes live

### Related issues

Not really blocked by #5087, but we want to wait until 5087 goes to Production rather than having musical sections for those who are already seeing the new version (Don't want Compare candidates to be the first section until this ticket is done, then be the second section until the 5087 is live)

### Completion criteria

The GTM experiment for the /data/ landing page is no longer running, no longer swapping the top two sections of the data landing page

**Comment by rfultz** [comment]
@JonellaCulmer @patphongs or @johnnyporkchops Could you confirm that https://www.fec.gov/data/ always has the 'Compare candidates' section at the top? And then close this?

Shouldn't matter, but if you'd like to check the 'cookie,' in Inspector, under Application, look under Storage, Local Storage, https://www.fec.gov, and delete the Key that's like `gtmExp:2021_data_landing`. Or change it to either 0 or 1—either value should no longer do anything

**Comment by JonellaCulmer** [comment]
@rfultz I'm only seeing the compare candidates section at the top.
