### ISSUE TITLE
17 Innovation Banners

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#5149]
### Summary

What we are after:
Content team is going to have routine sprint ticket for banner work each sprint to make sure we're on top of it.

### Related issues

[Banner spreadsheet](https://docs.google.com/spreadsheets/d/1MPGmgOFg-pjlkYZHUl28thVd1IPCQEmsseg7idH5ThU/edit?usp=sharing)
[Banner How to](https://docs.google.com/document/d/1Ehq3sxa6WXzLWf1UdwnbLIsKNTcCnSHIECcPYfWWhC4/edit?usp=sharing)

### Completion criteria

Banners set up for:
- [X] Extended office hours for the Q1
- [x] Open meeting scheduled for 4/28 (https://www.fec.gov/updates/april-28-2022-open-meeting/)
- [x] Post any other banners that might be needed (reporting deadlines, rulemaking deadlines, eFiling maintenance, etc.)
 - EFO banner 4/29

Additional banner work:
- [x] Create banner ticket for 18.1 and add it to PI planning doc for Content PI18

**Comment by dorothyyeager** [comment]
@djgarr set up the April Quarterly banner. I'll look for a good time to set up the April 28 open meeting banner and do a demo in Content Slack since it's innovation sprint.

**Comment by dorothyyeager** [comment]
April 28 banner is set up. I forgot to demo so I will do that at innovation demo.

**Comment by dorothyyeager** [comment]
April 29 EFO banner (just requested) is set up as well.

**Comment by dorothyyeager** [comment]
Closing, no more banners needed this sprint. Next banner ticket: https://github.com/fecgov/fec-cms/issues/5167
