### ISSUE TITLE
H4CC: Updating "Taking receipts" section "Contributions" with changes from the new Candidate

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#5160]
### Summary

**What we're after:**
We need to ensure that the updates for the Candidate Guide are reflected on our website_

### Related issues

- #5101 
- #5013 
- #5120 

### Completion criteria
Compare the web page "Making disbursements" against the excel document to see the pages under it that need to be updated. Excel sheet can be found at https://docs.google.com/spreadsheets/d/1jT2XGwgFYNsiOwaQJV0n_XwxmK7afItcntNXyZ0KcEI/edit#gid=93471181

 Pages for updating under the tab -
- Types of contributions - updated 
- Joint fundraising with other candidates and political committees - updated
- Who can and can't contribute to a candidate - updated 
- Using the personal funds of the candidate - This page will be dealt with in ticket #5223 
- Handling a questionable contribution - updated 
- Partnership and LLC contributions - updated
- Contribution limits - updated
- Remedying an excessive contribution - updated
- Recounts and contested elections - no changes 
- Affiliation and contribution limits - updated

- [ ]  Compare with the new Guide
- [ ]  Incorporate new examples if needed
- [ ]  Draft the page as a word document so reviewers can see the changes. Save in \ntsrv1\InfoProj\H4CC Candidate Guide Updates
- [ ]  Second pair of eyes for review (Include George) before updating and publishing in Wagtail
- [ ]  Update in Wagtail and publish

**Comment by kathycarothers** [comment]
We have a meeting to divide up the work and will make two new tickets.
