### ISSUE TITLE
18.1 Banners (May 3 - May 16, 2022)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5167]
### Summary

What we are after:
Routine sprint ticket for banner work each sprint.

### Related issues

[Banner spreadsheet](https://docs.google.com/spreadsheets/d/1MPGmgOFg-pjlkYZHUl28thVd1IPCQEmsseg7idH5ThU/edit?usp=sharing)
[Banner How to](https://docs.google.com/document/d/1Ehq3sxa6WXzLWf1UdwnbLIsKNTcCnSHIECcPYfWWhC4/edit?usp=sharing)

### Completion criteria

Banners set up for:
- [x] Open meeting scheduled for 5/12 (https://www.fec.gov/updates/may-12-2022-open-meeting/)
- [ ] Any other banners that might be needed (reporting deadlines, rulemaking deadlines, eFiling maintenance, etc.)

Additional banner work:
- [x] Create banner ticket for 18.2 and add it to PI planning doc for Content PI18 (#5195)

**Comment by djgarr** [comment]
Banner is set for next Thursday's meeting

**Comment by djgarr** [comment]
Banner ticket for 18.2 has been created
