### ISSUE TITLE
H4CC: Updating "Taking receipts" section "Other Sources of income and support"  with changes from the new Candidate

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#5169]
### Summary

**What we're after:**
_We need to ensure that the updates for the Candidate Guide are reflected on our website_

### Related issues

- #5101 
- #5013 
- #5120 
- #5160

### Completion criteria
_Compare the web page "Taking Receipts" against the excel document to see the pages under it that need to be updated. Excel sheet can be found at https://docs.google.com/spreadsheets/d/1jT2XGwgFYNsiOwaQJV0n_XwxmK7afItcntNXyZ0KcEI/edit#gid=93471181

 Pages for updating under the tab -
- Food and beverage discounts - DONE
- Legal and accounting services - NO CHANGES 
- Volunteer activity - DONE 
- Support from other campaigns - DONE
- Transfer between a candidate's committees - DONE 

- [x]  Compare with the new Guide
- [x]  Incorporate new examples if needed
- [x]  Draft the page as a word document so reviewers can see the changes. Save in \ntsrv1\InfoProj\H4CC Candidate Guide Updates
- [x]  Second pair of eyes for review (Include George) before updating and publishing in Wagtail
- [x]  Update in Wagtail and publish

**Comment by djgarr** [comment]
Drafted remaining pages. Reviewed by Web Team and Info management. Got the ok to publish.
