### ISSUE TITLE
H4CC: Updating "Taking receipts" section "Outside spending" with changes from the new Candidate Guide

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#5170]
### Summary

**What we're after:**
_We need to ensure that the updates for the Candidate Guide are reflected on our website_

### Related issues

- #5101 
- #5013 
- #5120 
- #5169

### Completion criteria
_Compare the web page "Taking Receipts" against the excel document to see the pages under it that need to be updated. Excel sheet can be found at https://docs.google.com/spreadsheets/d/1jT2XGwgFYNsiOwaQJV0n_XwxmK7afItcntNXyZ0KcEI/edit#gid=93471181

 Pages for updating under the tab -
[Understanding independent expenditures](https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/understanding-independent-expenditures/) - Changes made. Page approved and published

[Electioneering communications](https://www.fec.gov/help-candidates-and-committees/other-filers/making-electioneering-communications/) - NO CHANGES NECESSARY

[Coordinated communications](https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/coordinated-communications/) - DONE

[Support from political parties](https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/support-political-parties/) - DONE 

[Communications and other support by corporations and labor organizations](https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/support-corporations-labor-organizations/) Covered by https://github.com/fecgov/fec-cms/issues/5201 - DONE

[Raising and spending funds for delegate activity](https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/delegate-activity/) - NO CHANGES NECESSARY

[Raising and spending funds for the national party's nominating convention](https://www.fec.gov/help-candidates-and-committees/taking-receipts-political-party/national-nominating-convention/) - NO CHANGES NECESSARY

- [x]  Compare with the new Guide
- [x]  Incorporate new examples if needed
- [x]  Draft the page as a word document so reviewers can see the changes. Save in \ntsrv1\InfoProj\H4CC Candidate Guide Updates
- [x]  Second pair of eyes for review (Include George) before updating and publishing in Wagtail
- [x]  Update in Wagtail and publish

**Comment by djgarr** [comment]
Ticket is done
