### ISSUE TITLE
Reporting examples: Publish Form 1 with new images and language

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#5173]
### Summary

**What we're after:**
We need to update the reporting examples that display the Form 1 to be consistent with the newly approved Form 1.

### Related issues

_List any relevant related issue(s)_

- #5133 
- #5134 
- #5172

### Completion criteria

The following reporting examples need their images and language updated for the newly revised Form 1:

- Super PACs: https://www.fec.gov/help-candidates-and-committees/filing-pac-reports/registering-super-pac/ 
- Hybrid PACs: https://www.fec.gov/help-candidates-and-committees/filing-pac-reports/registering-hybrid-pac/
- Nonconnected PACs: https://www.fec.gov/help-candidates-and-committees/filing-pac-reports/registering-nonconnected-committee/
- Joint Fundraising: https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/registering-joint-fundraising-representative/ and https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/joint-fundraising-representative/

- [ ] Publish on May 17

**Comment by dorothyyeager** [comment]
Closing; duplicate for #5134
