### ISSUE TITLE
Take down recently redirected files (18.1)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5174]
### Summary

**What we're after:**
We are cleaning out transition

### Related issues

_List any relevant related issue(s)_

- #5111 - 17.6 redirects implemented
- #5144 - 17.6 redirects tested 

### Completion criteria

- [x] These files removed from transition and content team notified so they can update spreadsheet as needed. Some may already have been removed and that's fine.

/law/policy/guidance/2008_guideline_approved_aug092007.doc

/law/policy/internet09/englecomments072109.pdf
/law/policy/internet09/svobodacomments072109.pdf
/law/policy/internet09/tonercomments072109.pdf
/law/policy/internet09/witnesslist.pdf

/law/policy/nationwideiereporting/draftinterpretiverule-reportingnationwideies-presprimaries.pdf

/law/policy/nyspecial/nyspecialprimaryirdraft.pdf

/law/policy/purposeofdisbursement/inadequate_purpose_list_3507.pdf

/law/policy/technicalcorrections/drafttechcorrections2014.pdf

/open/documents/Yearly-Long-Term-Budget-Estimates-for-PECF-FY2017_2027.pdf

/pages/bcra/rulemakings/charts_fea_dates_2010.shtml
/pages/bcra/rulemakings/charts_fea_dates_2011.shtml
/pages/bcra/rulemakings/charts_fea_dates_2013.shtml
/pages/bcra/rulemakings/charts_fea_dates_midterm.shtml
/pages/bcra/rulemakings/charts_fea_dates_prez.shtml
/pages/bcra/rulemakings/charts_fea_dates.shtml
/pages/bcra/rulemakings/charts_fea_dates_special.shtml
/pages/bcra/rulemakings/consolidated_reporting.shtml
/pages/bcra/rulemakings/ECs_WRTL_Exemption_Examples.shtml
/pages/bcra/rulemakings/presidential_rules.htm
/pages/bcra/rulemakings/rulemakings_bcra.shtml
/pages/bcra/bcra_faq.htm
/pages/bcra/bcra_fea.dcf
/pages/bcra/bcra_form_2.fec
/pages/bcra/bcra_interim_cand.dcf
/pages/bcra/draft_form_3x_instructions.doc
/pages/bcra/educational_outreach_bcra.htm
/pages/bcra/electioneering_communications.htm
/pages/bcra/electronic_filing_examples_bcra.htm
/pages/bcra/fea_3x.fec
/pages/bcra/fea_h5.fec
/pages/bcra/fea_h6.fec
/pages/bcra/fea_nonallocable_disb.fec
/pages/bcra/fec_form_1_draft_instructions.doc
/pages/bcra/fec_form_2_draft_instructions.doc
/pages/bcra/interim_reporting_policy.htm
/pages/bcra/major_resources_bcra.htm
/pages/bcra/proposed_formats.html

/pages/brochures/documents/ChartonContributionLimitsfor2003-04.doc
/pages/brochures/aos.pdf
/pages/brochures/auditprocess.shtml
/pages/brochures/bcra_brochure.pdf
/pages/brochures/BestPracticesforCommitteeManagement.shtml
/pages/brochures/best_practices.pdf
/pages/brochures/biennial_limit_brochure.pdf
/pages/brochures/candidate_registration_brochure.pdf
/pages/brochures/checkoff_brochure.pdf
/pages/brochures/compliance_nonfec.shtml
/pages/brochures/contrib.gif
/pages/brochures/contriblimits0304.jpg
/pages/brochures/contriblimitschart.htm
/pages/brochures/contriblimits.jpg
/pages/brochures/ContributionLimits2003-2004.htm
/pages/brochures/ExamplesofHowtoCalculateFines.shtml
/pages/brochures/fecfeca1.shtml
/pages/brochures/fec_feca_brochure_spanish.pdf
/pages/brochures/fecfeca.shtml
/pages/brochures/flowchart.gif
/pages/brochures/foreign1.shtml
/pages/brochures/foreign_nat_brochure.pdf
/pages/brochures/internalcontrols.pdf
/pages/brochures/local_party_activity_brochure.pdf
/pages/brochures/orientation0508.pps
/pages/brochures/pubfund_limits_2004.shtml
/pages/brochures/pubfund_limits_2007.shtml
/pages/brochures/pubfund_limits_2008.shtml
/pages/brochures/pubfund_limits_2011.shtml
/pages/brochures/pubfund_limits_2012.shtml
/pages/brochures/pubfund_limits_2015.shtml
/pages/brochures/pubfund_limits_2016.shtml
/pages/brochures/ReportsAnalysisDivision.shtml
/pages/brochures/spec_notice_brochure.pdf
/pages/brochures/ssfvnonconnected.pdf
/pages/brochures/submission_dates_2016.pdf
/pages/brochures/volact1.shtml

/pages/hearings/internethearingcomments.shtml
/pages/hearings/McCutcheonRulemakingPublicHearing.shtml

/pages/procure/publicreports/fair_act_fy12.pdf - please save a copy of this file in our archive somewhere before deleting and send to @AmyKort 
/pages/procure/publicreports/fair_act_fy14.pdf
/pages/procure/publicreports/fair_act_fy15.pdf
/pages/procure/publicreports/fair_act_fy16.pdf
/pages/procure/publicreports/fair_act_fy17.pdf
/pages/procure/publicreports/FEC_FY11_Services_Contract_Inventory_Report.pdf
/pages/procure/publicreports/FEC_FY12_Service_Contract_Inventory_Report.pdf
/pages/procure/publicreports/FEC_FY15_Service_Contract_Inventory_Report.pdf
/pages/procure/publicreports/FEC_Service_Orders_Over_25k_FY2010_rev02.pdf

**Comment by dorothyyeager** [comment]
Most redirects are working. There's one we apparently missed implementing and one that I need to investigate to see why it's not working.

**Comment by patphongs** [comment]
These files have been deleted:

```
Thu Apr 28 15:38:53 EDT 2022
delete: 'law/policy/guidance/2008_guideline_approved_aug092007.doc'
delete: 'law/policy/internet09/englecomments072109.pdf'
delete: 'law/policy/internet09/tonercomments072109.pdf'
delete: 'law/policy/internet09/witnesslist.pdf'
delete: 'law/policy/nationwideiereporting/draftinterpretiverule-reportingnationwideies-presprimaries.pdf'
delete: 'law/policy/nyspecial/nyspecialprimaryirdraft.pdf'
delete: 'law/policy/purposeofdisbursement/inadequate_purpose_list_3507.pdf'
delete: 'law/policy/technicalcorrections/drafttechcorrections2014.pdf'
delete: 'open/documents/Yearly-Long-Term-Budget-Estimates-for-PECF-FY2017_2027.pdf'
delete: 'pages/bcra/bcra_faq.htm'
delete: 'pages/bcra/bcra_fea.dcf'
delete: 'pages/bcra/bcra_form_2.fec'
delete: 'pages/bcra/bcra_interim_cand.dcf'
delete: 'pages/bcra/draft_form_3x_instructions.doc'
delete: 'pages/bcra/educational_outreach_bcra.htm'
delete: 'pages/bcra/electioneering_communications.htm'
delete: 'pages/bcra/electronic_filing_examples_bcra.htm'
delete: 'pages/bcra/fea_3x.fec'
delete: 'pages/bcra/fea_h5.fec'
delete: 'pages/bcra/fea_h6.fec'
delete: 'pages/bcra/fea_nonallocable_disb.fec'
delete: 'pages/bcra/fec_form_1_draft_instructions.doc'
delete: 'pages/bcra/fec_form_2_draft_instructions.doc'
delete: 'pages/bcra/interim_reporting_policy.htm'
delete: 'pages/bcra/major_resources_bcra.htm'
delete: 'pages/bcra/proposed_formats.html'
delete: 'pages/bcra/rulemakings/ECs_WRTL_Exemption_Examples.shtml'
delete: 'pages/bcra/rulemakings/charts_fea_dates.shtml'
delete: 'pages/bcra/rulemakings/charts_fea_dates_2010.shtml'
delete: 'pages/bcra/rulemakings/charts_fea_dates_2011.shtml'
delete: 'pages/bcra/rulemakings/charts_fea_dates_2013.shtml'
delete: 'pages/bcra/rulemakings/charts_fea_dates_midterm.shtml'
delete: 'pages/bcra/rulemakings/charts_fea_dates_prez.shtml'
delete: 'pages/bcra/rulemakings/charts_fea_dates_special.shtml'
delete: 'pages/bcra/rulemakings/consolidated_reporting.shtml'
delete: 'pages/bcra/rulemakings/presidential_rules.htm'
delete: 'pages/brochures/BestPracticesforCommitteeManagement.shtml'
delete: 'pages/brochures/ContributionLimits2003-2004.htm'
delete: 'pages/brochures/ExamplesofHowtoCalculateFines.shtml'
delete: 'pages/brochures/ReportsAnalysisDivision.shtml'
delete: 'pages/brochures/aos.pdf'
delete: 'pages/brochures/auditprocess.shtml'
delete: 'pages/brochures/bcra_brochure.pdf'
delete: 'pages/brochures/best_practices.pdf'
delete: 'pages/brochures/biennial_limit_brochure.pdf'
delete: 'pages/brochures/candidate_registration_brochure.pdf'
delete: 'pages/brochures/checkoff_brochure.pdf'
delete: 'pages/brochures/compliance_nonfec.shtml'
delete: 'pages/brochures/contrib.gif'
delete: 'pages/brochures/contriblimits.jpg'
delete: 'pages/brochures/contriblimits0304.jpg'
delete: 'pages/brochures/contriblimitschart.htm'
delete: 'pages/brochures/documents/ChartonContributionLimitsfor2003-04.doc'
delete: 'pages/brochures/fec_feca_brochure_spanish.pdf'
delete: 'pages/brochures/fecfeca.shtml'
delete: 'pages/brochures/fecfeca1.shtml'
delete: 'pages/brochures/flowchart.gif'
delete: 'pages/brochures/foreign_nat_brochure.pdf'
delete: 'pages/brochures/local_party_activity_brochure.pdf'
delete: 'pages/brochures/orientation0508.pps'
delete: 'pages/brochures/pubfund_limits_2004.shtml'
delete: 'pages/brochures/pubfund_limits_2007.shtml'
delete: 'pages/brochures/pubfund_limits_2008.shtml'
delete: 'pages/brochures/pubfund_limits_2011.shtml'
delete: 'pages/brochures/pubfund_limits_2012.shtml'
delete: 'pages/brochures/pubfund_limits_2015.shtml'
delete: 'pages/brochures/pubfund_limits_2016.shtml'
delete: 'pages/brochures/spec_notice_brochure.pdf'
delete: 'pages/brochures/ssfvnonconnected.pdf'
delete: 'pages/brochures/submission_dates_2016.pdf'
delete: 'pages/brochures/volact1.shtml'
delete: 'pages/hearings/McCutcheonRulemakingPublicHearing.shtml'
delete: 'pages/procure/publicreports/FEC_FY11_Services_Contract_Inventory_Report.pdf'
delete: 'pages/procure/publicreports/FEC_FY12_Service_Contract_Inventory_Report.pdf'
delete: 'pages/procure/publicreports/FEC_FY15_Service_Contract_Inventory_Report.pdf'
delete: 'pages/procure/publicreports/FEC_Service_Orders_Over_25k_FY2010_rev02.pdf'
delete: 'pages/procure/publicreports/fair_act_fy12.pdf'
delete: 'pages/procure/publicreports/fair_act_fy14.pdf'
delete: 'pages/procure/publicreports/fair_act_fy15.pdf'
delete: 'pages/procure/publicreports/fair_act_fy16.pdf'
delete: 'pages/procure/publicreports/fair_act_fy17.pdf'
```

The following fair act files have been placed in the [archive](https://drive.google.com/drive/folders/18mQcmSYyHiRCGsDoBOcvdgQf2Xy3uCOt) 🔒  and sent to @AmyKort for her records:
```
pages/procure/publicreports/fair_act_fy12.pdf'
pages/procure/publicreports/fair_act_fy14.pdf'
pages/procure/publicreports/fair_act_fy15.pdf'
pages/procure/publicreports/fair_act_fy16.pdf'
pages/procure/publicreports/fair_act_fy17.pdf'
```

The following files had been previously deleted:

```
pages/bcra/rulemakings/rulemakings_bcra.shtml
pages/brochures/foreign1.shtml
pages/brochures/internalcontrols.pdf
pages/hearings/internethearingcomments.shtml
pages/bcra/rulemakings/rulemakings_bcra.shtml
```
