### ISSUE TITLE
Form 1 Reporting Examples: New examples for registering a Super and Hybrid PAC 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#5177]
### Summary

**What we're after:**
_We need to draft two new reporting examples to better serve committees registering their Forms for Super PACs and Hybrid PACs. We the updates to the new form 1 and the removal of the letter these examples need to be drafted._

### Related issues

- #5134

### Completion criteria

The following 2 reporting examples will need images and language created for the newly revised Form 1:

- Super PACs: https://www.fec.gov/help-candidates-and-committees/filing-pac-reports/registering-super-pac/ 
- Hybrid PACs: https://www.fec.gov/help-candidates-and-committees/filing-pac-reports/registering-hybrid-pac/

- [ ] Pull the text from the reporting example for registering a nonconnected committee https://www.fec.gov/help-candidates-and-committees/filing-pac-reports/registering-nonconnected-committee/ and make adjustments for Super PACs and Hybrid PACs
- [ ] Update images to fit Super  and Hybrid PAC reporting examples - Reach out to Jimn 
- [ ] Second pair of eyes 
- [ ] Publish on May 17

**Comment by jjonesfec** [comment]
Awaiting image content info.

**Comment by dorothyyeager** [comment]
This issue is a duplicate for work covered in #5133 and #5134 so closing.
