### ISSUE TITLE
[1st draft] Design new MUR search results view

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#5183]
**What we're after:**
Design a new MUR search results view to accommodate multiple items such as: document type, document URL, document title, highlighted document text, election cycle. There may also be other meta data that we want to add as well and that should be considered.

- MUR API call: https://api.open.fec.gov/v1/legal/search/?api_key=DEMO_KEY&type=murs 
- EQS prioritization spreadsheet: https://docs.google.com/spreadsheets/d/111lB-G0pjLPNDFuIsARv-4teC8lnyttqXypJwNstU1k/edit#gid=0
- MUR search MoSCoW doc: https://docs.google.com/document/d/1Uvp9MtFKnYK2vZBGH33EOIxQa2RBjQop_El6qZ9-Qj8/edit#

### Completion criteria
- [x] Demoable first draft of the search results view of the MUR search. Use any feedback for 2nd draft in next sprint

**Comment by JonellaCulmer** [comment]
MUR search options for review. Please leave comments if you have a moment to review. @patphongs @PaulClark2 @AmyKort @rfultz @johnnyporkchops @dorothyyeager @kathycarothers 

### Option 1: 
Excludes document type in results.
![MUR-updated1](https://user-images.githubusercontent.com/31663028/169060390-2d017f34-af23-43f4-a625-b10755b98dc6.png)


### Option 2: 
Stacked version, excludes document type in results.
![MUR-updated2](https://user-images.githubusercontent.com/31663028/169060410-9dbe1ecb-dca4-48ac-9ab3-789c56d1d579.png)


### Option 3:
Stacked version, includes document type in "tags"
![MUR-updated3](https://user-images.githubusercontent.com/31663028/169060447-61da4e9d-9bcc-4d23-bc5c-239418ef5dd5.png)


### Option 4:
Stacked version, includes document type in separate column
![MUR-updated4](https://user-images.githubusercontent.com/31663028/169060467-144e3798-fa2c-4420-aca0-8070bfd35d32.png)

**Comment by AmyKort** [comment]
Thank you, @JonellaCulmer . These all look really good to me, but in different ways. Seeing these options all together is very helpful. Do you think it would make sense for our team to set up a meeting to go over these together and talk about the benefits of each?

**Comment by JonellaCulmer** [comment]
After discussing with @AmyKort and @patphongs we're going to move forward with version #3 where the appearance is less cluttered and where we can see the document type in the results view. 
![MUR-updated3](https://user-images.githubusercontent.com/31663028/169589694-2205bf3d-dcb0-4763-a35c-3aa9cb310bdd.png)
