### ISSUE TITLE
Change feature space CMS db from `shared-psql` to `micro-psql`

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#5189]
### Summary

**What we're after:**
_Shared-psql will be deprecated on cloud.gov by August 2022. We need to convert the feature space db to use the micro-psql plan._

We also need to update the retention policy to 35 days.

`cf create-service aws-rds micro-psql ${NEW_SERVICE_NAME} -c '{"backup_retention_period": 35}'`

Try upgrading using the [service command](https://cloud.gov/docs/services/relational-database/#update-an-instance):
```
cf update-service ${SERVICE_NAME} -p ${NEW_SERVICE_PLAN_NAME}
```

### Related issues

_List any relevant related issue(s)_

- #5231 

### Completion criteria

- [x] feature space DB has been upgraded to micro-psql plan
- [x] retention period has been set to 35 days

**Comment by cnlucas** [comment]
Attempted to update using the above command and it failed. We may need to create a new instance which would require a code change. Doing more research.

**Comment by cnlucas** [comment]
For Future Reference:

1. `cf create-service aws-rds micro-psql fec-feature-cms-micro -c '{"version": "11","backup_retention_period": 35}'`
2. waited for creation to finish (check with `cf services`)
3. `cf unbind-service cms fec-feature-cms`
4. `cf bind-service cms fec-feature-cms-micro`
5. In new terminal SSH into tunnel (several steps) (https://github.com/fecgov/fec-cms/wiki/Backup-or-Restore-Wagtail-PostgreSQL-database-in-dev,-staging,-or-production)
6. `pg_restore --dbname postgres://$creds@localhost:5432/$dbname --no-acl --no-owner <path of the dump file>.dump`
7. `cf restage cms`
8. restart last feature deploy in circleci

Going to wait for @patphongs to confirm I can delete shared-psql service.

**Comment by cnlucas** [comment]
Shared space was deleted.
