### ISSUE TITLE
Modify title of redistricting accordion on election search page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5191]
**What we're after:**
Modify title of redestricting accordion for accuracy and clarity. The accordion is on the [election search page](https://www.fec.gov/data/elections/?state=&cycle=2022&election_full=true). 

New language:
Information about redistricting and the 2020 Decennial Census

### Completion criteria
- [x] Accordion title has been updated with aforementioned language

### Mockup
<img width="617" alt="Screen Shot 2022-05-02 at 8 17 54 AM" src="https://user-images.githubusercontent.com/31663028/166232688-2dbedc70-d9ad-4f6c-8a55-a05f9d90a12a.png">

**Comment by dorothyyeager** [comment]
Related PR is ready for review. Once that is approved and merged, this ticket can be closed.
