### ISSUE TITLE
Move informational snippet on meeting pages

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#5197]
### Summary

**What we're after:**
_Move the informational snippet on meeting pages below the first two introduction paragraphs so that we can show the most important information at the top._

<img width="974" alt="Screen Shot 2022-05-05 at 12 38 55 PM" src="https://user-images.githubusercontent.com/12799132/166983023-1022cb5b-1f8a-498b-b69e-17c46202c128.png">

### Completion criteria

- [ ] Information snippet is moved on the meeting page

**Comment by AmyKort** [comment]
Just to clarify, there's also a new sentence at the end of the second paragraph:

The Commission considers new regulations, advisory opinions and other public matters at open meetings, which are typically held at FEC headquarters on Thursdays at 10:00am.
Members of the public can attend any open meeting or hearing in person. Open meetings are also streamed live online. To attend in person, please bring a photo ID and be prepared to go through a security check. After security, attendees are escorted to the Commission's hearing room. **Visitors must also follow current COVID-19 safety protocols, which are updated each Monday.**

**Comment by AmyKort** [comment]
Also, if we want to have two snippets, we can leave the top one there--but empty--in case there are more changes.

**Comment by patphongs** [comment]
@AmyKort As we discussed in our meeting, the `"Visitors must also follow current COVID-19 safety protocols, which are updated each Monday."` will be placed within the additional information box in the CMS so that it's more flexible in case it needs to change in the future. This text will only appear if we choose to put it in the meeting page.

**Comment by AmyKort** [comment]
Thank you!

**Comment by patphongs** [comment]
Changes have been made and deployed
