### ISSUE TITLE
Update district dropdown to reflect changes

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#5204]
### Summary

**What we're after:**
_13 states have district changes. Those changes must be reflected in the district dropdown list._

State | 2022 district count | Change
| -- | -- | -- |
California | 52 | -1
Colorado | 8 | +1
Florida | 28 | +1
Illinois | 17 | -1
Michigan | 13 | -1
Montana | 2 | +1
New York | 26 | -1
North Carolina | 14 | +1
Ohio | 15 | -1
Oregon | 6 | +1
Pennsylvania | 17 | -1
Texas | 38 | +2
West Virginia | 2 | -1

### Completion criteria

- [ ] District dropdown is updated to reflect the changes

**Comment by PaulClark2** [comment]
We have district data over time in a PG table. 

select election_yr, state, state_desc, district, office, office_desc
 from disclosure.dim_race_inf  where office = 'H' and election_type_id = 'G' and election_yr between 1980 and 2030
 order by election_yr, state_desc, district;

**Comment by patphongs** [comment]
> we have district data over time in a PG table.

Thanks @PaulClark2, I have created a [new ticket](https://github.com/fecgov/fec-cms/issues/5207) so we can make the district drop down historical. The API was already updated so that the correct number of districts appear per state across each election year.
