### ISSUE TITLE
Bug: Issue when searching MURs by citation 30123 in keyword search

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5208]
**What we're after:**
Correcting issue with front-end display after searching by 30123 in MUR keyword search. 

Search query: https://www.fec.gov/data/legal/search/murs/?search_type=murs&search=30123&case_no=&case_respondents=&case_min_open_date=&case_max_open_date=&case_min_close_date=&case_max_close_date= 

In this similar issue, the offending characters were in the OCR'd content:
Similar issue: https://github.com/fecgov/fec-cms/issues/1861

**What the page looks like:**

**Before:**
![Screen Shot 2022-05-09 at 10.35.32 AM.png](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/1bcd9109-80e1-42ad-9fbb-12ca139e0c50)

**After:**
![Screen Shot 2022-05-09 at 10.35.51 AM.png](https://images.zenhubusercontent.com/59b1a5f3b0222d5de476d238/02ff1181-f9d9-49f8-a0c7-13a62471b178)

**Completion criteria:**
- [ ] Identify cause and fix if front-end problem, reference  https://github.com/fecgov/fec-cms/issues/1861
- [ ] Followup ticket to fix on API if back-end problem

**Comment by patphongs** [comment]
There seems to be an issue with the data for these particular MUR documents. They are identical documents with the exception of the MUR document header number at the top of every PDF page. The special characters within this is causing the HTML to form badly on the results.

https://www.fec.gov/files/legal/murs/6917/6917_33.pdf
https://www.fec.gov/files/legal/murs/6929/6929_28.pdf

It returns something that is incoherent when searching for the keyword "30123" in particular. The return is:

```
5*<em>30123</em>!20<*,!6@/<!1360#3/*6! #-02=*0<*,N!9**'!*N=N'!GHIL(((L(((((7!`*5#1-!5*66#=*!?,25!GHI!
```

Sample API calls:
- https://api.open.fec.gov/v1/legal/search?case_no=6929&hits_returned=20&type=murs&from_hit=0&q=30123&api_key=DEMO_KEY

- https://api.open.fec.gov/v1/legal/search?case_no=6917&hits_returned=20&type=murs&from_hit=0&q=30123&api_key=DEMO_KEY

**Comment by patphongs** [comment]
Reached out to internal team to ask about the scan on these two PDF files. Will update once I receive a response.

**Comment by patphongs** [comment]
These two MUR documents have been rescanned correctly. It no longer shows in the [search results](https://www.fec.gov/data/legal/search/murs/?search_type=murs&search=30123&case_no=&case_respondents=&case_min_open_date=&case_max_open_date=&case_min_close_date=&case_max_close_date=) for `30123`.

https://www.fec.gov/files/legal/murs/6917/6917_33.pdf
https://www.fec.gov/files/legal/murs/6929/6929_28.pdf

This issue is now resolved.
