### ISSUE TITLE
Take down items redirected in innovation sprint

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5214]
### Summary

**What we're after:**
_As a user, I don't want to find stuff that is outdated and that has been redirected._

### Related issues

_List any relevant related issue(s)_

- #5190 

### Completion criteria

- [ ] These files are taken down off transition (and content team notified). No worries if they are already gone.

/pages/hearings/coordinationshays3hearing.shtml
/pages/hearings/corplabor_indexp_ec.shtml
/pages/hearings/shaysfea09hearing.shtml

/law/policy/guidance/gb2006-1.pdf (for this file, please send a copy to the content team or archive somewhere offline)

/law/policy/internet09/houghtaling.pdf
/law/policy/internet09/ngpcomments072109.pdf
/law/policy/internet09/sunlightcomments072109.pdf

/pages/brochures/pubfund_limits_2004.html

**Comment by patphongs** [comment]
/law/policy/guidance/gb2006-1.pdf file has been [archived](https://drive.google.com/drive/folders/18mQcmSYyHiRCGsDoBOcvdgQf2Xy3uCOt) 🔒 . Also emailed to web posting email for our records.

Mon May 16 13:51:23 EDT 2022
delete: 'law/policy/guidance/gb2006-1.pdf'
delete: 'law/policy/internet09/ngpcomments072109.pdf'
delete: 'pages/brochures/pubfund_limits_2004.html'
delete: 'pages/hearings/coordinationshays3hearing.shtml'
delete: 'pages/hearings/corplabor_indexp_ec.shtml'
delete: 'pages/hearings/shaysfea09hearing.shtml'

Already deleted previously:
/law/policy/internet09/houghtaling.pdf
/law/policy/internet09/sunlightcomments072109.pdf
