### ISSUE TITLE
Update transition inventory spreadsheet 

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5219]
### Summary

**What we're after:**
_We are getting off transition. This work will help content team make decisions in #5143 ._

### Related issues

- #5143

### Completion criteria

- [x] @patphongs updates the [transition link testing tab in redirect spreadsheet](https://docs.google.com/spreadsheets/d/1vzN-wZlS8K8ZyfExSV3hwXDenDEN9KyyAUJFTI6OjKU/edit#gid=1998561118) with the file names (we left off at line 273, press/)

**Comment by patphongs** [comment]
Scanned entire /pdf/ directory and documented
