### ISSUE TITLE
Update candidate loan pages to reflect recent Supreme Court decision and Commission rulemaking

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5223]
### Summary

**What we are after:**
As a candidate, I need to know how the Supreme Court ruling in _Cruz v. FEC_ will affect FEC rules on candidate loan repayments.

(Note: Info will handle update to any litigation page. Reporting examples did not mention the requirement that's affected and don't need to be updated.)

FEC Rules implementing this ruling: https://sers.fec.gov/fosers/showpdf.htm?docid=420045 
These rules take effect on November 30.

### Completion criteria

- [x] Updates to pages below are drafted in Word showing revisions using approved language (maybe from the Federal Register notice).
    - [x] https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/using-personal-funds-candidate/
    - [x] https://www.fec.gov/help-candidates-and-committees/handling-loans-debts-and-advances/personal-loans-candidate/
    - [x] https://www.fec.gov/help-candidates-and-committees/handling-loans-debts-and-advances/retiring-debts-candidate/
- [x] Draft circulated to Info/content team/OGC 
- [x] Second pair of eyes before publishing
- [x] Updated pages are published

### Press release
https://www.fec.gov/updates/supreme-court-issues-opinion-on-appeal-in-fec-v-ted-cruz-for-senate-et-al/

**Comment by bmathesonFEC** [comment]
Campaign guide update changes to [Raising Contributions to Retire Debt](https://www.fec.gov/help-candidates-and-committees/handling-loans-debts-and-advances/retiring-debts-candidate/) were deferred until this ticket ready. The campaign guide updates included language about the candidate loan repayment limit. Ticket assignee should reach out to me for an updated version of the page content before updating that page to remove references to the loans repayment limitations.
