### ISSUE TITLE
Fix JS `trim` error on committee typeahead filter

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5227]
**What we're after:**
We need to address a "trim" JS error when using the committee typeahead filter. 

Type-ahead and free text filter: https://fec-pattern-library.app.cloud.gov/components/detail/type-ahead-and-free-text.html

**Datatables with processed and autosuggest/type-ahead filters:**
- [Receipts](https://www.fec.gov/data/receipts/?data_type=processed) 
- [Disbursements](https://www.fec.gov/data/disbursements/?data_type=processed)
- [Independent expenditures](https://www.fec.gov/data/independent-expenditures/?data_type=processed&is_notice=true&most_recent=true)
- [Filings ](https://www.fec.gov/data/filings/?data_type=efiling)
- [Presidential committee reports](https://www.fec.gov/data/reports/presidential/?is_amended=false&data_type=processed)
- [House and Senate committee reports](https://www.fec.gov/data/reports/house-senate/?data_type=processed)
- [PAC and party committee reports ](https://www.fec.gov/data/reports/pac-party/?two_year_transaction_period=2022&data_type=processed&min_receipt_date=01%2F01%2F2021&max_receipt_date=05%2F17%2F2022)

**Related tickets:**
- https://github.com/fecgov/fec-cms/issues/5146 (closed)
- https://github.com/fecgov/fec-cms/issues/5193 (closed)

**Completion criteria:**
- [ ] "trim" JS error when using the committee typeahead filter

**Comment by patphongs** [comment]
This may be fixed when the typeahead filter is replaced, closing for now
