### ISSUE TITLE
Add committee designation description to committee profile page

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#5238]
As a customer interested in committee details, I would like to see committee designation information at the top of the committee profile page. 

Current situation
It is difficult to determine a committee's designation from it's committee profile page. 

![image](https://user-images.githubusercontent.com/11817734/169389067-b4f1d4ef-1c7f-49ed-8837-abb2b5213688.png)
![image](https://user-images.githubusercontent.com/11817734/169389158-f5188987-784c-4413-91d0-1412f90f5792.png)

![image](https://user-images.githubusercontent.com/11817734/169389499-7498eec4-4117-4102-8185-2327de884c86.png)

![image](https://user-images.githubusercontent.com/11817734/169389282-617cd136-deb6-4c5a-bb27-acb3bc84c486.png)

Completion criteria
- [x] Determine feasibility of adding committee designation information
- [ ] <s> Design the addition of this information </s> (already there, just not rendering)
- [x] Add committee designation to top of committee profile page

**Comment by johnnyporkchops** [comment]
@PaulClark2 It looks like we already have this  in the template, but with incorrect syntax, so it fails to render the designation. If we change `if designation` to` if committee.designation` in two places here, it works
        
https://github.com/fecgov/fec-cms/blob/07bf18fca92057bb1b78f4d1db2d1f03f73862b8/fec/data/templates/committees-single.jinja#L40-L50

<img width="988" alt="Screen Shot 2022-05-19 at 5 36 22 PM" src="https://user-images.githubusercontent.com/5572856/169408729-64635974-f431-4324-b53f-5d5b17d39b92.png">

**Comment by PaulClark2** [comment]
Thanks, @johnnyporkchops
