### ISSUE TITLE
18.3 Banners (May 31 - June 13, 2022)

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#5242]
### Summary

What we are after:
Routine sprint ticket for banner work each sprint.

### Related issues

[Banner spreadsheet](https://docs.google.com/spreadsheets/d/1MPGmgOFg-pjlkYZHUl28thVd1IPCQEmsseg7idH5ThU/edit?usp=sharing)
[Banner How to](https://docs.google.com/document/d/1Ehq3sxa6WXzLWf1UdwnbLIsKNTcCnSHIECcPYfWWhC4/edit?usp=sharing)

### Completion criteria

Banners set up for:
- [x] Open meeting scheduled for 6/8 (https://www.fec.gov/updates/june-08-2022-open-meeting/)
- [ ] Any other banners that might be needed (reporting deadlines, rulemaking deadlines, eFiling maintenance, etc.)

Additional banner work:
- [x] Create banner ticket for 18.4 and add it to PI planning doc for Content PI18

**Comment by dorothyyeager** [comment]
6/8 banner created
18.5 ticket created
Will put this ticket back into assigned tickets in case any other banner needs arise and close on June 13.

**Comment by dorothyyeager** [comment]
Closing; no further banner work expected this sprint.
