### ISSUE TITLE
[Snyk:Medium] pyjwt- Use of a Broken or Risky Cryptographic Algorithm (due by 07/24/2022)

### ISSUE THREAD

**Issue by cnlucas** [fecgov/fec-cms#5247]
### Summary
Introduced through
    cg-django-uaa@2.1.3
    Fixed in
    pyjwt@2.4.0

Detailed paths and remediation

    Introduced through: project@0.0.0 › cg-django-uaa@2.1.3 › pyjwt@1.7.1
    [Fix: Pin pyjwt to version 2.4.0]

Overview

[PyJWT](https://pypi.org/project/PyJWT/) is a Python implementation of RFC 7519.

Affected versions of this package are vulnerable to Use of a [Broken or Risky Cryptographic Algorithm]((https://app.snyk.io/org/fecgov/project/ff0dca01-794e-4c1c-bf1f-0c0f8932fadd/#issue-SNYK-PYTHON-PYJWT-2840625)) via non-blacklisted public key formats leading to key confusion.

### Completion criteria
- [ ] Verify that this is indeed a vulnerability for us and either complete the remediation or document, close the ticket and snooze the Snyk alert.

**Comment by JonellaCulmer** [comment]
@cnlucas @rfultz Can this be closed?

**Comment by cnlucas** [comment]
@JonellaCulmer They just released the new version of cg-django-uaa, but there's still been an issue with our builds. Moving forward
