### ISSUE TITLE
Update results display for MUR search 

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5255]
**What are we after:**
Update MUR search results display with election cycle, disposition, subject, document name, document URL, document type, removed ellipses, force all-caps for committee name

**MUR search epic:**
 https://github.com/fecgov/fec-epics/issues/221 

**Completion criteria:**

- [ ] Update results display from design 

##Related pull-requests
#5175

**Prototype for matching keyword interaction:**
https://invis.io/YN12TP3Q2XQJ#/468022210_Mur_Main

**Updated mockups with keyword matching included:**
![MUR-Document with lines](https://user-images.githubusercontent.com/31663028/176271235-30738800-3928-4619-811d-e03a759028c4.png)

**Comment by patphongs** [comment]
@JonellaCulmer A disposition can have multiple respondents. See example for [MUR 7927](https://www.fec.gov/data/legal/matter-under-review/7927/#disposition). 

<img width="730" alt="Screen Shot 2022-06-23 at 8 17 03 PM" src="https://user-images.githubusercontent.com/12799132/175435911-0c9d9656-d256-4f44-a8cd-bbedb99bed88.png">

In the [design](https://user-images.githubusercontent.com/31663028/170500009-2155dce9-5036-4139-a8df-2fc8df8c4fb0.png), it appears dispositions are listed uniquely and don't necessarily repeat. Do you want the dispositions to be listed just once or do you want it to repeat?

```
Disposition(s): Conciliation-PPC; Conciliation-PPC; 
```

**Comment by JonellaCulmer** [comment]
@patphongs Dispositions should only be listed once. Are we able to include the number of respondents for each disposition? Ex. Conciliation-PPC _(2 respondents)_

**Comment by patphongs** [comment]
> Dispositions should only be listed once

Thanks @JonellaCulmer, I forgot that we've had this [conversation](https://github.com/fecgov/fec-epics/issues/221#issuecomment-1142410318) already. I should be able to do that.
