### ISSUE TITLE
18.4 Banners (6/14 - 6/27/22)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5273]
### Summary

What we are after:
Routine sprint ticket for banner work each sprint.

### Related issues

[Banner spreadsheet](https://docs.google.com/spreadsheets/d/1MPGmgOFg-pjlkYZHUl28thVd1IPCQEmsseg7idH5ThU/edit?usp=sharing)
[Banner How to](https://docs.google.com/document/d/1Ehq3sxa6WXzLWf1UdwnbLIsKNTcCnSHIECcPYfWWhC4/edit?usp=sharing)

### Completion criteria

Banners set up for:
- [x] Open meeting scheduled for 6/23 (https://www.fec.gov/updates/june-23-2022-open-meeting/)
- [x] EFO Maintenance for June 25 banner needs to go up Friday, June 24 (See email from Ken)
- [x] Any other banners that might be needed (reporting deadlines, rulemaking deadlines, eFiling maintenance, etc.)

Additional banner work:
- [x] Create banner ticket for 18.5 and add it to PI planning doc for Content PI18

**Comment by kathycarothers** [comment]
I created the banner for the open meeting on June 23 and created the ticket for 18.5. I will be out of the office starting June 18, so @djgarr will pick up this ticket if any updates need to be made to the banner.

**Comment by kathycarothers** [comment]
I have set up the maintenance banner for the EFO office and @djgarr will double-check the two banners.
