### ISSUE TITLE
Take down files redirected in 18.2 release or id'ed in 18.4 transition meeting

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5291]
### Summary

**What we're after:**
_As a user, I don't want to find stuff that is outdated and that has been redirected._

### Related issues

_List any relevant related issue(s)_

- #5276 

### Completion criteria

- [x] These files are taken down off transition (and content team notified). No worries if they are already gone.
/pages/brochures/partner.shtml
/pages/brochures/partnership.shtml
/pages/brochures/partnership_brochure.shtml
/pages/brochures/partnership_brochure.pdf

/pdf/amend1.pdf
/pdf/amend2.pdf
/pdf/amend.pdf

/pdf/ei-25612.pdf
/pdf/FE0AR0002.pdf
/pdf/fe9-ar-5.pdf
/pdf/fe9ar8.pdf
/pdf/fec_shutdown_plan.pdf
/pdf/gaspec.pdf
/pdf/guidesup03.pdf
/pdf/legrec1992.pdf
/pdf/marinv.pdf
/pdf/recruit.pdf
/pdf/v_survey.pdf

/pdf/forms/printform.mp4 - please save this one offline (and send to Dorothy so we can figure out owner of it).

These entire subdirectories:
/pdf/conf/ 
/pdf/record/[YEAR]/[NAME].pdf
/pdf/nrpm/*

- [x] Send to Info Division to archive offline (Check with Pat to ensure it's ok to delete them from Wagtail now that they redirect.)
/resources/cms-content/documents/ie_only_letter.pdf
/resources/cms-content/documents/noncontribution_letter.pdf

**Comment by patphongs** [comment]
> /resources/cms-content/documents/ie_only_letter.pdf
> /resources/cms-content/documents/noncontribution_letter.pdf

@dorothyyeager @rfultz I have put those two PDF files into our [archive transition folder](https://drive.google.com/drive/folders/18mQcmSYyHiRCGsDoBOcvdgQf2Xy3uCOt) 🔒. I'll follow-up with @djgarr about who I should email them to for other archive purposes.

**Comment by dorothyyeager** [comment]
Reassigning to me to close out the last item. @patphongs advises we can test this out to ensure the redirect works.
