### ISSUE TITLE
psycopg2 install error on Monterey OS version 12.4

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#5293]
### Summary

An error occurred within the CMS repo when trying to pip install `psycopg2==2.8.6` on Monterey version 12.4. Upgrading to `psycopg2==2.9.3` fixed the error.

**Error:**

```
ld: library not found for -lssl
      clang: error: linker command failed with exit code 1 (use -v to see invocation)
      error: command '/usr/bin/clang' failed with exit code 1
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> psycopg2
```

### Related issue
- https://github.com/fecgov/fec-cms/issues/4916
- https://github.com/fecgov/fec-eregs/issues/690

### Completion criteria

- [ ] Research and document path forward for the 'psycopg2' package
- [ ] Document bugs when upgrading to `psycopg2==2.9.3`

### Tech steps or considerations

Test `psycopg2==2.9.3` on older OS versions:
- [ ] Monterey versions less than 12.4
- [ ] Big Sur
- [ ] Catalina
- [ ] Mojave
- [ ] Test deploy to dev

**Comment by patphongs** [comment]
Looks like there's an issue during CMS database migrations on psycopg2 v2.9.3: `cd fec && ./manage.py migrate`. 

```
raise ImproperlyConfigured("Error loading psycopg2 module: %s" % e)
django.core.exceptions.ImproperlyConfigured: Error loading psycopg2 module: dlopen(/.pyenv/versions/cms-dev/lib/python3.8/site-packages/psycopg2/_psycopg.cpython-38-darwin.so, 0x0002): Library not loaded: /usr/local/opt/postgresql/lib/libpq.5.dylib
  Referenced from: /.pyenv/versions/3.8.12/envs/cms-dev/lib/python3.8/site-packages/psycopg2/_psycopg.cpython-38-darwin.so
  Reason: tried: '/usr/local/opt/postgresql/lib/libpq.5.dylib' (no such file), '/usr/local/lib/libpq.5.dylib' (no such file), '/usr/lib/libpq.5.dylib' (no such file)
```

When trying to use `psycopg2==2.9.3` it can't seem to find the configured psycopg2 module. But if you switch to just using `psycopg2-binary==2.9.3`, it all runs fine.

**Comment by pkfec** [comment]
On my MAC, I recently upgraded macOS Monterey to v12.4 and xcode to v13.4.1. I was able to setup/build and run cms app without running any psycopg2 errors on my local workspace.

**Here are the steps i followed:**
1. update macOS Monterey to v12.4
2. update xcode to v13.4.1
3. run brew update and brew upgrade (Upgrade postgresql@13 13.6_1 -> 13.7)
4. create and activate python 3.8.13 virtualenv
5. install cms requirements.txt
6. dropdb cfdm_cms_test
7. createdb cfdm_cms_test
8. npm i
9. npm run build
10. cd fec/
11. ./manage.py migrate
12. ./manage.py runserver

**Comment by patphongs** [comment]
This seems to be just an issue for me right now, I am closing
