### ISSUE TITLE
18.5 Banners (6/28 - 7/11/22)

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#5299]
### Summary

What we are after:
Routine sprint ticket for banner work each sprint.

### Related issues

[Banner spreadsheet](https://docs.google.com/spreadsheets/d/1MPGmgOFg-pjlkYZHUl28thVd1IPCQEmsseg7idH5ThU/edit?usp=sharing)
[Banner How to](https://docs.google.com/document/d/1Ehq3sxa6WXzLWf1UdwnbLIsKNTcCnSHIECcPYfWWhC4/edit?usp=sharing)

### Completion criteria

Banners set up for:
- [x] No open meeting scheduled during this sprint 
- [x] Any other banners that might be needed (reporting deadlines, rulemaking deadlines, eFiling maintenance, etc.)

Additional banner work:
- [ ] Create banner ticket for 18.6 and add it to PI planning doc for Content PI18 (July 14 meeting July Q reports) 
  - [x] #5322

**Comment by djgarr** [comment]
Ticket for 18.6 created (#5322). Will keep an eye out for other banners needed
