### ISSUE TITLE
Migration of 1996 Presidential Primary Campaign Finance Summaries from the Press Office 

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5305]
### Summary

**What we are after:**
_As a researcher, I am interested in the 1996 Primary Campaign Finance Summaries drafted by the Press Office._

We are getting off transition, but found 1996 presidential primary campaign finance summaries  in the PDF directory during the 18.4 transition inventory meeting. We will need to create a page to migrate that information to, and then link it on our home page for this.

### Related issues

_List any relevant related issue(s)_

- #4594 - Previous matching fund page creation work 

### Transition pages to migrate:

Follow these  pages for style
https://www.fec.gov/campaign-finance-data/presidential-matching-fund-submissions/
https://www.fec.gov/campaign-finance-data/presidential-matching-fund-submissions/2004-presidential-matching-fund-submissions/

1996:
https://transition.fec.gov/pdf/presind.htm (main page)
https://transition.fec.gov/pdf/alexind.htm
https://transition.fec.gov/pdf/buchind.htm
https://transition.fec.gov/pdf/clinind.htm
https://transition.fec.gov/pdf/doleind.htm
https://transition.fec.gov/pdf/dornind.htm
https://transition.fec.gov/pdf/forbesin.htm
https://transition.fec.gov/pdf/grammind.htm
https://transition.fec.gov/pdf/keyesind.htm
https://transition.fec.gov/pdf/larind.htm
https://transition.fec.gov/pdf/lugarind.htm
https://transition.fec.gov/pdf/specind.htm
https://transition.fec.gov/pdf/taylind.htm
https://transition.fec.gov/pdf/totind.htm
https://transition.fec.gov/pdf/wilsind.htm

### Action items
- [x] Have a meeting with Press to decide what to do with these pages
- [x] Below is work that was done when it was thought they were matching funds submissions
- [x] Create draft pages in the Campaign finance data section to replace these pages using Custom page template, approved language (Dorothy can supply), and https://github.com/fecgov/fec-cms/issues/3386#issuecomment-815849646
- [x] Second pair of eyes by content team member and Jonella before publishing
- [x] PDF and ZIP files are placed in CMS or in S3 bucket (check with @patphongs)

###  Completion criteria
- [x] New pages are published to replace these pages
- [x] Audit/Public Records/Press are informed that the pages are live
- [x] Ticket for redirecting old pages is created.

**Comment by kathycarothers** [comment]
I have sent the pages for review to @dorothyyeager @djgarr and @JonellaCulmer

**Comment by kathycarothers** [comment]
I talked with Judy and these pages will be archived with the Press Office. I have sent them the pdfs.

**Comment by kathycarothers** [comment]
I have also deleted the work I did in Wagtail too. So it has all been cleaned up.
