### ISSUE TITLE
Migrate Legislative History volumes

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5310]
### Summary

**What we're after:**
_There are four large transition files that need to be migrated. They are too large to upload to the CMS. We need to upload them to S3 and add them to redirect list._

https://transition.fec.gov/pdf/legislative_hist/legislative_history_1971.pdf
https://transition.fec.gov/pdf/legislative_hist/legislative_history_1974.pdf
https://transition.fec.gov/pdf/legislative_hist/legislative_history_1976.pdf
https://transition.fec.gov/pdf/legislative_hist/legislative_history_1979.pdf

### Related issues

_List any relevant related issue(s)_

- #5292 

### Completion criteria

- [x] Files (Dorothy has them) - sent to Chris Berg for remediation - Can not remediate these pdfs 
- [x] Pat to upload to S3 bucket  -or-  ~consider reducing file size to <100MB  in Acrobat for upload via Wagtail~
- [x] links on [legislation page](https://www.fec.gov/legal-resources/legislation/#selected-amendments-to-feca) updated with new links
- [x] New/Old URLs added to redirect spreadsheet 
- [x] Redirects have been merged
- [x] Ticket created for testing
- [x] Ticket created for takedown (after testing)

**Comment by kathycarothers** [comment]
Emailed Chris to see his availability for making the documents accessible on 10/13.

**Comment by kathycarothers** [comment]
@patphongs @dorothyyeager @AmyKort 
I had Chris look into these files to how hard it would be to make them 508. He tested one file and this was his report:

There are several problem areas with this file that would take some time to fix before it could be remediated. Any page with strikethrough text would need to be edited, and most of the italicized text is causing OCR errors. The document could be done, but it would take considerable time.

In addition, it took a number of hours to auto-tag the pdf. 

This will be a number of stuff hours to complete and could result in edits to the text. I am proposing we do not touch the 508. Your feedback?

**Comment by kathycarothers** [comment]
Review and merge request submitted.
