### ISSUE TITLE
Take down files redirected in 18.4, 18.5 release and 18.6 meeting 

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5328]
### Summary

**What we're after:**
_As a user, I don't want to find stuff that is outdated and that has been redirected._

### Related issues

_List any relevant related issue(s)_

- #5313
- https://github.com/fecgov/fec-cms/issues/5331

### Completion criteria

- [ ] These files are taken down off transition (and content team notified). No worries if they are already gone.

**PDFs:**

/pdf/00adminfines.pdf
/pdf/2006reports.pdf
/pdf/2007reports.pdf
/pdf/2008reports.pdf
/pdf/2010reports.pdf
/pdf/2011reports.pdf
/pdf/441a(d)2006.pdf
/pdf/67fr05445.pdf
/pdf/ar1995.pdf
/pdf/Audit_Procedures.pdf
/pdf/budget2001.PDF
/pdf/cand_guide_supp.pdf
/pdf/cfr11.pdf
/pdf/corp_guide.pdf
/pdf/eldi9601.pdf
/pdf/expresad.pdf
/pdf/FCCMSupplement.pdf
/pdf/fecapp.pdf
/pdf/fecrpt.pdf
/pdf/fecfile3.pdf
/pdf/guidesup03.pdf
/pdf/hear399.pdf
/pdf/legrecsup.PDF
/pdf/llc.pdf
/pdf/members.pdf
/pdf/noa.pdf
/pdf/nongui_supp.pdf
/pdf/recrep.pdf
/pdf/recrept.pdf
/pdf/sofnprm.pdf
/pdf/soft_money_final_rules.pdf
/pdf/!the1996.pdf

/pdf/2017/jan2017.pdf

/pdf/aos/Sample_ao.pdf

/pdf/forms/fecfrm1.pdf
/pdf/forms/fecfrm1auth.pdf
/pdf/forms/fecfrm2cand.pdf
/pdf/forms/fecfrm3x_05.pdf
/pdf/forms/fecfrm3x_06.pdf
/pdf/forms/fecfrm5sf.pdf
/pdf/forms/fecfrm10.pdf
/pdf/forms/fecfrm10i.pdf
/pdf/forms/fecfrm11.pdf
/pdf/forms/fecfrm11i.pdf
/pdf/forms/fecfrm12.pdf
/pdf/forms/fecfrm12i.pdf

**Images:**

/rad/images/PictureforMainPage.jpg
/rad/images/PictureforMainPageNew.jpg
/rad/images/RFAIImageforRADFAQs_001.jpg
/support/images/clip_image002_000.jpg
/support/images/clip_image002.jpg
/support/images/clip_image004_000.jpg
/support/images/clip_image004.jpg
/support/images/clip_image006_000.jpg
/support/images/clip_image006.jpg
/support/images/clip_image008.gif
/support/images/clip_image008.jpg
/support/images/clip_image010_000.jpg
/support/images/clip_image010.jpg
/support/images/clip_image012_000.jpg
/support/images/clip_image012.jpg
/support/images/clip_image014_000.jpg
/support/images/clip_image014.jpg
/images/clip_image016_000.jpg
/support/images/clip_image016.jpg
/support/images/clip_image018_000.jpg
/images/clip_image018.jpg
/support/images/clip_image020_000.jpg
/support/images/clip_image020.jpg
/support/images/clip_image022_000.jpg
/support/images/clip_image022_001.jpg
/support/images/clip_image022.jpg
/support/images/clip_image024_000.jpg
/support/images/clip_image024.jpg
/support/images/clip_image026_000.jpg
/support/images/clip_image026.jpg
/support/images/clip_image027.jpg
/support/images/clip_image028.jpg
/support/images/clip_image029.jpg
/support/images/clip_image030.jpg
/support/images/clip_image031.jpg
/support/images/rbld01.gif
/support/images/rbld02.gif
/support/images/rbld03.gif
/support/images/rbld04.gif
/support/images/rbld05.gif
/support/images/rbld06.gif
/support/images/rbld07.gif
/support/images/rbld08.gif
/support/images/rbld09.gif
/support/images/rbld10.gif
/support/images/rbld11.gif
/support/images/rbld12.gif
/support/images/rbld13.gif

**shtml:**

/press/archived-campaign-finance-statistics.shtml
/press/bkgnd/presidential_fund.shtml
/rad/analyst_search.shtml
/rad/FEC-ReportsAnalysisDivision-CandidateCommittees.shtml
/rad/CandidateCommitteesToPrint.shtml
/rad/parties/FEC-ReportsAnalysisDivision-PartiesandPACs.shtml
/support/faq_filing.shtml
/support/faq_parser.shtml
/support/faq_soft.shtml
/support/faq_valid.shtml

**Directories:**

/press/summaries/1976/
/press/summaries/1978/
/press/summaries/1980/
/press/summaries/1982/
/press/summaries/1984/
/press/summaries/1986/
/press/summaries/1988/

**Comment by rfultz** [comment]
All done!
