### ISSUE TITLE
After 8/2 release deployed: Test redirects merged into 18.6

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5343]
### Summary

**What we are after:**
_As a user, I don't want outdated content and want to be correctly redirected._

### Related issues

#5331 

### Completion criteria

- [x] Redirects merged into 18.6 release work (both the transition and the www - see PRs linked above)
- [x] Wagtail redirects and www PRs submitted as needed
- [x] Testing ticket created (#5360)
- [x] Transition inventory is updated
- [x] Redirected files are added to take-down ticket.

**Comment by djgarr** [comment]
One link needed to be updated. Updated made and PR created (https://github.com/fecgov/fec-proxy/pull/324)

**Comment by djgarr** [comment]
Links tested. One link was not working and has been fixed and added to the PR mentioned above. The PR has been added to the next testing ticket for review after the next release (#5360) 

Ticket closed
