### ISSUE TITLE
Design where the new committee label should be implemented 

### ISSUE THREAD

**Issue by cnlucas** [fecgov/fec-cms#5349]
### Summary

Now that we have the new `committee_label` built out in the back-end ([thanks Helen](https://github.com/fecgov/openFEC/pull/5196)!) we need to decide where and how it should be used in the front-end.  Also, need to determine what the proper arrangement of the new committee labels we be alongside other labeling so that the committees are appropriately and clearly labeled across all committee types. 

**Considerations:** 
- How might these new labels be arranged in the subheader on committee profile pages?
- Should it be used other places than the committee profile pages? 
- Are there considerations with mobile view with the longer names?

**Resources:**
- Committee profile page example: https://www.fec.gov/data/committee/C00000729/
- API call: https://api.open.fec.gov/v1/committee/C00000729/history/?page=1&election_full=true&sort=-cycle&sort_hide_null=false&sort_nulls_last=false&api_key=DEMO_KEY&sort_null_only=false&per_page=20
- Web page logic: 
    - If it's an SSF, the committee header will show: `organization_type_full` `committee_type_full` `designation_full`. SSFs are `organization_type` "W", "C", "L", "V", "M", or "T".
    - Otherwise, the committee header will show: `committee_type_full` `designation_full`
    - Note that designation does not always exist, and if it doesn't, then we won't show it.
    - There's a dash between `committee_type_full` and `designation_full`, dash only appears if there is a `designation_full`

### Related Issue
https://github.com/fecgov/openFEC/issues/4915

### Action Items
- [ ] Designs for new committee labels are mocked up and shared with PMs and content for review
- [ ] Create front-end ticket for implementation

**Comment by JonellaCulmer** [comment]
Committee type labels spreadsheet: https://docs.google.com/spreadsheets/d/1IJOnb0o7MbfVuUklBrHx-4qic7_CpbEt4wmG1mti74Q/edit#gid=798440796

**Comment by johnnyporkchops** [comment]
We separate  the labels with hyphens while there are also hyphens within the labels on the comm profile page subheader which can make it hard to visually separate  where on label starts and ends.
**Example :** `"Corporation"`  and  `"Party - Nonqualified"` are concatenated  without a hyphen, then  `"Unauthorized"` is concatenated to the end with a hyphen. This could be  read  as `Corporation Party`, `Nonqualified`, `Unauhtorized`
<img width="948" alt="Screen Shot 2022-08-29 at 3 33 40 PM" src="https://user-images.githubusercontent.com/5572856/187285361-1c1677fb-df4d-412c-ba10-37731e782dcf.png">

**Comment by JonellaCulmer** [comment]
@patphongs @dorothyyeager @kathycarothers I have some concerns that I didn't notice before in the dev ticket and how data currently exists in the API. 
We use Qualified and qualified. Nonqualified and nonqualified. Membership PAC and Membership Organization. 

Before moving forward on this, should we address these inconsistencies? For a more complete look, here's the table in the dev ticket and the spreadsheet with all committee types.
Dev ticket table: 
Committee type spreadsheet: https://docs.google.com/spreadsheets/d/1IJOnb0o7MbfVuUklBrHx-4qic7_CpbEt4wmG1mti74Q/edit#gid=798440796

**Comment by dorothyyeager** [comment]
Hi Jonella. Agree that we should be consistent with Qualified and Nonqualified. I don't have a strong preference but capitalized makes a little more sense for this.

Membership PAC and Membership Organization are two different things. A Membership PAC is the SSF formed by a Membership Organization.

**Comment by JonellaCulmer** [comment]
@dorothyyeager You wouldn't call it a Membership Organization PAC? You'd prefer Membership PAC?

**Comment by dorothyyeager** [comment]
I would prefer Membership Organization PAC. (But I'm not the one who gets to make that call.) I notice in the statistical summaries put out by Press, they are called "membership" no organization.

**Comment by kathycarothers** [comment]
Maybe we should match Press?

**Comment by JonellaCulmer** [comment]
@dorothyyeager @kathycarothers @djgarr Based on the conversation above, I started to update some of these labels. I don't believe all of them require changes but if you see any others that do, feel free to comment here in this ticket or make the changes straight into the spreadsheet. And I'm foregoing any changes that require capitalization because we will force all caps on profile pages. My changes are in red. Feel free to use a different color. 

🔒 https://docs.google.com/spreadsheets/d/1IJOnb0o7MbfVuUklBrHx-4qic7_CpbEt4wmG1mti74Q/edit#gid=76142581 🔒

**Comment by kathycarothers** [comment]
I guess I am confused. Are we going to follow Press or not? I think they look fine, but I am confused as to who should make the final decision. I think Membership PAC or Membership Organization PAC was the big one to decide on.

**Comment by JonellaCulmer** [comment]
@kathycarothers The membership issue was just one example that I found while looking at the list, but I'd imagine that trade associations and labor organizations would be handled similarly. I'll reach out to whoever you think needs to weigh in on this. I can't believe I can't find a single reference anywhere (other than the one Dorothy found in the statistics). 

Although, I wouldn't say that section is consistent with the rest of the site for other terminology, such as their reference to "Corporations without Stock" (and not Capital Stock).

cc: @dorothyyeager @dorothyyeager @AmyKort

**Comment by JonellaCulmer** [comment]
We're going to icebox this work for now. We've made previous progress to improve profile pages in the past [here](https://github.com/fecgov/fec-cms/issues/5238), and without making significant changes to the existing committee label work, it isn't enough to satisfy current need.
