### ISSUE TITLE
Improve access to AO comment information 

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5355]
**What we're after:**
Improve access to AOR comment information. Several comments (list to follow) from customers interested in providing comments on pending AOs are having trouble locating information to make comments. Some have even submitted their comments via the feedback box, which is not a valid method - and so these voices are potentially going unheard. 

### Related issues
- https://github.com/fecgov/FEC/issues/11958
- https://github.com/fecgov/FEC/issues/11934
- https://github.com/fecgov/FEC/issues/11949
- https://github.com/fecgov/FEC/issues/11947
- https://github.com/fecgov/FEC/issues/11919
- https://github.com/fecgov/FEC/issues/11918
- https://github.com/fecgov/FEC/issues/11326

**Considerations:**
- Page about AOs, including how to comment on pending AOs: https://www.fec.gov/legal-resources/advisory-opinions-process/#commenting
- Another page that explains in greater details how to submit rulemaking comments: https://www.fec.gov/legal-resources/regulations/how-to-comment-on-proposed-rules-and-other-rulemaking-documents/
- Google search's top two results are the AO search and how to comment on rulemakings. 

### Completion criteria
- [x] Recommendations to improve access to AO comment information are made
- [x] Recommendations are approved
- [ ] Implement changes, if possible, open up followup tickets for any front-end or back-end work

**Comment by JonellaCulmer** [comment]
@AmyKort @PaulClark2 @patphongs Below are some thoughts compiled by me and Kathy on how to improve access to the AO comment information, both short and long term. Please let us know if you have any questions/concerns/suggestions or would you like to meet to discuss further. 

### Short-term recommendations for improvements:
**Page improvements:**
- Add AOR comment submission information including email address, fax number and physical address to the AOR comment section on [AO process page.](https://www.fec.gov/legal-resources/advisory-opinions-process/#commenting)
- Fix [anchor link on the AO page to the AO process page ](https://www.fec.gov/legal-resources/advisory-opinions-process/#commenting)to get to that section easier.
- Button/link to comment sections on AO page (would like to discuss further).

**Need to confirm with OGC:**
- Need to confirm with OGC about the use of fax and hand delivery for AOR and draft AO comments, is that still accurate? If so, that information should be conveyed in the AOR comment section. 
- Need to confirm with OGC, do we need to update the language to say "ten **business** days" for AOR comments?

**Need to confirm with devs:**
- Need to speak with devs about automating the AOR comment due date and/or making changes to the system where dates are entered by Jason to add AOR comment due date, and future AO draft comment due dates. 

### Long-term recommendations:
- [ ] Build a form for customers to submit comments directly through the website. Need to determine what are limitations are with this scenario. I.e. privacy
- [ ] Include links to the new form on individual AO pages.

**Comment by PaulClark2** [comment]
If we were to implement a form, I think we'd need to include an option for commenters to upload a document. See for example the two comments submitted on 07/12/2022 and the comment submitted on 08/04/2022 related to AO 2022-14. 

Would we be adding end of comment period and how to comment to the "pending AO" page? https://www.fec.gov/data/legal/advisory-opinions/. The current button "learn how to comment" is essentially  useless. 
![image](https://user-images.githubusercontent.com/11817734/183071162-8430fcf4-3eac-4a94-98f3-7d32290258cd.png)

**Comment by JonellaCulmer** [comment]
@PaulClark2 Yes, I agree. That button is currently useless until we can get an anchor link working to that specific section. 

I really like the idea of adding the AOR comment due date and potentially a draft document due date on the pending AO section. 

I'll eventually open a separate ticket for an AO comment form.

**Comment by JonellaCulmer** [comment]
@johnnyporkchops @patphongs @rfultz  A couple questions for you all: 

- Any issues with fixing an anchor link [on the AO page to the AO process page](https://www.fec.gov/legal-resources/advisory-opinions-process/#commenting)? Right now it takes you to the top of the page instead of the specific section. 
Refer to this comment for more information: https://github.com/fecgov/fec-cms/issues/5355#issuecomment-1205753287
- Are we able to automate AOR comment and draft AO comment due dates appearing [under pending AOs on the AO page](https://www.fec.gov/data/legal/advisory-opinions/) and on individual canonical pages?
- If we're not able to automate the due dates on individual canonical pages, can we automate a link to the comment section? For example: on all pending AO canonical pages, show a link to the comment section, once it is no longer pending, remove that link to the comment section. 

If you have any questions, please let me and @kathycarothers know. We can set up a call. 

Once we have these details ironed out, we can reach out to the policy division for their thoughts.

**Comment by johnnyporkchops** [comment]
> * Any issues with fixing an anchor link [on the AO page to the AO process page](https://www.fec.gov/legal-resources/advisory-opinions-process/#commenting)? Right now it takes you to the top of the page instead of the specific section.
@JonellaCulmer The anchor link would actually be https://www.fec.gov/legal-resources/advisory-opinions-process/#commenting-on-advisory-opinion-requests
....not much a a "vanity" URL, but it works. The only way I can think if to fix that is to stick an html field above each one with the proper anchor link: `<a id="commenting"></a>`. I think I have seen content team use html blocks like this before. Not ideal, but also not the end of the world.

**Comment by dorothyyeager** [comment]
Correct, we can’t redirect to anchors

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by johnnyporkchops** [comment]
> * Are we able to automate AOR comment and draft AO comment due dates appearing [under pending AOs on the AO page](https://www.fec.gov/data/legal/advisory-opinions/) and on individual canonical pages?

Based on pairing with @patphongs and @JonellaCulmer , we determined we can display the "Comments due...." text from the `document_description`  field for each pending AO.
 
Questions to clarify:
 - What do we do when there are two separate documents indicating comment due date.
EXAMPLE: AO number `2022-12` has two documents indicating same due date: `Agenda Document No. 22-36-A` and `Agenda Document No. 22-36-B`. Do show both?  ([data for 2022-12](https://api.open.fec.gov/v1/legal/docs/advisory_opinions/2022-12?api_key=DEMO_KEY))
- Are we linking to the due-date docs or just listing the due date?

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Yes, we need to show both/all instances of documents with due dates. What do you mean by due-date docs? The document that the public can comment on, or the wagtail pages with instructions on how to comment?

**Comment by JonellaCulmer** [comment]
Closing in favor of followup design and implementation work:
- https://github.com/fecgov/fec-cms/issues/5398
- https://github.com/fecgov/fec-cms/issues/5400
