### ISSUE TITLE
Research how to fix Arch-MUR dispositions display

### ISSUE THREAD

**Issue by fec-jli** [fecgov/fec-cms#5357]
### Summary
Currently, the dispositions show empty in Arch-MUR search result page. We need to research how to fix it to display the correct dispositions for Arch_MUR. This ticket involves research and design if displaying dispositions is possible.

Ref PRs: 
[https://github.com/fecgov/fec-cms/pull/5319](https://github.com/fecgov/fec-cms/pull/5319)
[https://github.com/fecgov/fec-cms/pull/5356](https://github.com/fecgov/fec-cms/pull/5356)

### How to Reproduce
https://www.fec.gov/data/legal/search/murs/?search_type=murs&search=&case_no=4000&case_respondents=&case_min_open_date=&case_max_open_date=&case_min_close_date=&case_max_close_date=

API call for MUR 4000 canonical page: https://fec-dev-api.app.cloud.gov/v1/legal/search?case_no=4000&hits_returned=20&type=murs&from_hit=0&api_key=DEMO_KEY
MUR search for 400 archived MUR: https://www.fec.gov/data/legal/search/murs/?search_type=murs&search=&case_no=4000&case_respondents=&case_min_open_date=&case_max_open_date=&case_min_close_date=&case_max_close_date=

### Completion criteria
- [x] Decide next steps for archived MURs dispositions following research and design

**Action items:**
- [x] Identify whether it's possible to pull out dispositions in a clean/reliable way from archived MURs. 
- [x] Check in the database to see if dispositions are there and can be pulled into the API.
- [ ] If data is available, design appearance in the MUR search. If data is not available, design appearance with dispositions removed. 
- [ ] If data is not available, document blockers and remove dispositions from search.

### Screenshots
<img width="400" alt="arch-mur_disposions" src="https://user-images.githubusercontent.com/24395751/182676835-3eb9e2e4-6cdf-4d0f-84f6-7405dba6c2bd.png">

**Comment by JonellaCulmer** [comment]
Blocked while we wait to hear from Jenny.

**Comment by JonellaCulmer** [comment]
We've heard from Jennie who recommends we speak to the contractors about getting more detailed information. This ticket remains blocked until we hear from them.

**Comment by JonellaCulmer** [comment]
@patphongs With help, we've learned that there is no archived MUR disposition data available in the database. So we'll be moving forward without incorporating that data. For archived MURs, I recommend the following solution:

![Screen Shot 2022-09-28 at 4 57 14 PM](https://user-images.githubusercontent.com/31663028/192887985-8bb7b6c4-2a3b-403a-98aa-1a8a77b0ece0.png)

**Comment by JonellaCulmer** [comment]
We're going to move forward with the aforementioned design. So closing this ticket in favor of implementation here: https://github.com/fecgov/fec-cms/issues/5423
