### ISSUE TITLE
After 8/23 release deployed: Test redirects merged into 18 Innovation

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#5360]
### Summary

**What we are after:**
_As a user, I don't want outdated content and want to be correctly redirected._

### Related issues

#https://github.com/fecgov/fec-proxy/pull/324
/pdf/forms/fecfrm9i_06.pdf 

### Completion criteria

- [x] Redirects merged into 18 Innovation release work (both the transition and the www - see PRs linked above)
- [x] Wagtail redirects and www PRs submitted as needed
- [x] Testing ticket created.
- [x] Transition inventory is updated
- [x] Redirected files are added to take-down ticket.

**Comment by kathycarothers** [comment]
Need to add a redirect to www

**Comment by dorothyyeager** [comment]
Have merged the PR to add the www redirect.

**Comment by JonellaCulmer** [comment]
@kathycarothers Can this be closed?

**Comment by kathycarothers** [comment]
All redirects are working now.
