### ISSUE TITLE
Take down transition files identified in 18.6 and 19.1 are ready to delete

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#5361]
### Summary

**What we're after:**
_We are getting off transition._

In our meeting, we found some files that can be taken down.

### Completion criteria

- [ ] These files are taken down and Content team alerted when done:

Files:

**pdf**

/pdf/forms/fecfrm3xi_05.pdf
/pdf/forms/fecfrm3xi_06.pdf
/pdf/forms/fecfrm9i_06.pdf

**html**
/support/style-val.css
/support/tools_formats.shtml
/support/tools_lookup_db.shtml
/tools_rebuilding.shtml
/press/archive/[YEAR]/* /press/archive/([0-9]{4})/(.*)
/press/bkgnd/history.shtml
/press/bkgnd/documents/enforcementstats1975to2019_000.pdf
/press/bkgnd/documents/enforcementstats1975to2019_001.pdf
/press/bkgnd/documents/enforcementstats1975to2019.pdf
/press/summaries/party_soft_money/(*)
/rad/analyst_search.shtml
/rad/best_practices_to_avoid_pitfalls_2018.pdf
/rad/candidates/documents/1991-39.pdf
/rad/candidates/documents/1992-01.pdf
/rad/candidates/documents/1995-19.pdf
/rad/candidates/documents/2003-18.pdf
/rad/candidates/documents/2003-30.pdf
/rad/candidates/documents/2006-24.pdf
/rad/candidates/documents/CanGuide100-101.pdf
/rad/candidates/documents/CanGuide100.pdf
/rad/candidates/documents/CanGuide101-103.pdf
/rad/candidates/documents/CanGuide20-21.pdf
/rad/candidates/documents/CanGuide23-24.pdf
/rad/candidates/documents/CanGuide24-27.pdf
/rad/candidates/documents/CanGuide25.pdf
/rad/candidates/documents/CanGuide27-28.pdf
/rad/candidates/documents/CanGuide29-30_000.pdf
/rad/candidates/documents/CanGuide29-30.pdf
/rad/candidates/documents/CanGuide34.pdf
https://transition.fec.gov/rad/candidates/documents/CanGuide76-77.pdf
/rad/candidates/documents/CanGuide80-81_000.pdf
/rad/candidates/documents/CanGuide80-83.pdf
/rad/candidates/documents/CanGuide81.pdf
/rad/candidates/documents/CanGuide83-86.pdf
/rad/candidates/documents/CanGuide91013-104.pdf
/rad/candidates/documents/CanGuide92-93.pdf
/rad/candidates/documents/CanGuide95-99.pdf
/rad/candidates/documents/CanGuide99-100.pdf
/rad/candidates/documents/CanGuide99-100.pdf
/rad/candidates/documents/JointFundraising_000.pdf
/rad/candidates/documents/LobbyistBundledContributions.pdf
/rad/candidates/documents/PartnershipContributions_000.pdf
/rad/candidates/documents/StartingtheCampaign_001.pdf
/rad/candidates/documents/WindingDown.pdf
/rad/documents/ExamplesofAdequatePurposes.pdf
/rad/documents/GettingStartedManual_U.pdf
/rad/documents/PartyGuideBestEfforts.pdf
/rad/documents/RADProcessDocument1-6-12_002.pdf
/rad/documents/RADProcessDocument1-6-12.pdf
/rad/documents/RADProcessDocument7-13-12.pdf
/rad/other_filers/RAD-Form5Filers.shtml
/rad/other_filers/RAD-Form7Filers.shtml
/rad/pacs/documents/AO2003-04PACIEsection.pdf
/rad/pacs/documents/ExamplesofAdequatePurposes.pdf
/rad/pacs/documents/GettingStartedManual_U.pdf
/rad/pacs/documents/GettingStartedManual_U.pdf
/rad/pacs/documents/SSFguidepg13adminexpenses.pdf
/rad/parties/documents/AllocatedRefund-rebate.pdf
/rad/parties/documents/CreditCardonH4.pdf
/rad/parties/documents/Expressadvocacy.pdf
/rad/parties/documents/Expressadvocacy.pdf
/rad/parties/documents/PartyCampaignGuidep109-110ScheduleL.pdf
/rad/parties/documents/PartyCampaignGuidep112-113ScheduleH6.pdf
/rad/parties/documents/PartyCampaignGuideP75In-kindContributionscropped.pdf
/rad/parties/documents/PartyCampaignGuideP75In-kindContributionscropped.pdf
/rad/parties/documents/PartyCampaignGuidePage79OffsetsCropped.pdf
/rad/parties/documents/PatyCampaignGuidep53-56Coordination.pdf
/rad/parties/documents/ScheduleFwithdesignation.pdf
/rad/rad_process/FederalElectionCommission-RAD-TrainingandConferences.shtml

**xml**
/press/PressOffice.xml

**Comment by kathycarothers** [comment]
Yes, for the ones listed twice. The ones listed in the right-hand column need to be deleted. Sorry for the confusion. @rfultz

**Comment by rfultz** [comment]
All done!
