### ISSUE TITLE
19.1 Banners (8/16 - 8/29)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5365]
### Summary

What we are after:
Routine sprint ticket for banner work each sprint.

### Related issues

[Banner spreadsheet](https://docs.google.com/spreadsheets/d/1MPGmgOFg-pjlkYZHUl28thVd1IPCQEmsseg7idH5ThU/edit?usp=sharing)
[Banner How to](https://docs.google.com/document/d/1Ehq3sxa6WXzLWf1UdwnbLIsKNTcCnSHIECcPYfWWhC4/edit?usp=sharing)

### Completion criteria

Banners set up for:
- [x] No open meetings (there is one on 8/31 that can be done in 19.2 ticket).
- [x] Any other banners that might be needed (reporting deadlines, rulemaking deadlines, eFiling maintenance, etc.)

Additional banner work:
- [x] Create banner ticket for 19.2 and add it to PI planning doc for Content PI19 (#5385)

**Comment by JonellaCulmer** [comment]
@djgarr Can this be closed?

**Comment by djgarr** [comment]
@JonellaCulmer Most likely yes, but I planned to keep it open until tomorrow just in case someone needed a banner today
