### ISSUE TITLE
[SNYK: Medium] io.netty:netty-handler Improper Certificate Validation (Due 2022-10-17)

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#5377]
### What we’re after

SNYK flagged a vulnerability, [io.netty:netty-handler Improper Certificate Validation](https://app.snyk.io/org/fecgov/project/e6c155e9-f0ac-4a49-98fa-83c24f5b74b3#issue-SNYK-JAVA-IONETTY-1042268)

Introduced through `org.flywaydb:flyway-commandline@9.0.2`

**Detailed paths**
Introduced through: unknown:unknown@0.0.0 › org.flywaydb:flyway-commandline@9.0.2 › software.amazon.awssdk:s3@2.17.189 › software.amazon.awssdk:netty-nio-client@2.17.189 › io.netty:netty-handler@4.1.77.Final
Introduced through: unknown:unknown@0.0.0 › org.flywaydb:flyway-commandline@9.0.2 › software.amazon.awssdk:s3@2.17.189 › software.amazon.awssdk:netty-nio-client@2.17.189 › io.netty:netty-codec-http@4.1.77.Final › io.netty:netty-handler@4.1.77.Final
Introduced through: unknown:unknown@0.0.0 › org.flywaydb:flyway-commandline@9.0.2 › software.amazon.awssdk:s3@2.17.189 › software.amazon.awssdk:netty-nio-client@2.17.189 › io.netty:netty-codec-http2@4.1.77.Final › io.netty:netty-handler@4.1.77.Final
…and 1 more

**Overview**
io.netty:netty-handler is a library that provides an asynchronous event-driven network application framework and tools for rapid development of maintainable high performance and high scalability protocol servers and clients. In other words, Netty is a NIO client server framework which enables quick and easy development of network applications such as protocol servers and clients. It greatly simplifies and streamlines network programming such as TCP and UDP socket server.

Affected versions of this package are vulnerable to Improper Certificate Validation. Certificate hostname validation is disabled by default in Netty 4.1.x which makes it potentially susceptible to Man-in-the-Middle attacks.

### Action item(s)

(These are the smaller tasks that should happen in order to complete this work)
- [ ] 

### Completion criteria

- [ ] SNYK no longer flags this as a vulnerability, or
- [ ] We've determined that this isn't an issue and we've documented that

### References/resources/technical considerations

-

**Comment by JonellaCulmer** [comment]
Closing in favor of https://github.com/fecgov/openFEC/issues/5182
