### ISSUE TITLE
H4CC: Updating other pages with changes from the new Candidate - Registering as a Candidate section 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#5380]
### Summary

**What we're after:**
We need to ensure that the updates for the Candidate Guide are reflected on our website

### Related issues

- #5379
- #5160

### Completion criteria

Compare the web page for the pages listed in this ticket against the excel document and the Guide to see what updates need to be made. This section might require a meeting with Info. Excel sheet can be found at https://docs.google.com/spreadsheets/d/1jT2XGwgFYNsiOwaQJV0n_XwxmK7afItcntNXyZ0KcEI/edit#gid=93471181

The pages that will be worked on for this ticket are:

**House, Senate and presidential candidate registration**
- https://www.fec.gov/help-candidates-and-committees/registering-candidate/house-senate-president-candidate-registration/

- [x] 1st paragraph – The Guide removes the following 
“Money raised and spent to test the waters does not count toward this dollar threshold until the individual decides to run for federal office or conducts activities that indicate he or she is actively campaigning rather than testing the waters.” Turn this into a “Testing the Water button”
The Guide goes into the $5,000 registration threshold:
The $5,000 threshold is reached when:
•	The individual and/or persons he or she has authorized to conduct campaign activity receive over $5,000 in contributions or make over $5,000 in expenditures; or
•	The individual fails to disavow unauthorized campaign activity by writing a letter to the FEC within 30 days after being notified by the agency that another person or group has received contributions or made expenditures of more than $5,000 on the individual’s behalf. 100.3(a)(1)-(3) and 102.13(a)(2).

- [x] Add example to this section:
Updating an existing registration
For example, if Mr. Jones, who was a candidate for the U.S. House of Representatives in 2020, wishes to run again in 2022, he must amend his FEC Form 2 within 15 days after crossing the $5,000 registration threshold for the 2022 election cycle. 
In addition, a separate Form 2 must be filed for any special election in which the candidate is running. For example, if Mr. Jones is also participating in the 2021 special election in his district, he must file a Form 2 for the 2021 election year. (Footnote #5) 

- [x] Updating the principal campaign committee
Should we add footnote # 6 to the second bullet point 

6 Redesignated committees are reminded that, if outstanding debts remain from the previous election, the committee must continue to report the debts as well as the contributions that have been designated by contributors to retire them. 104.11, 110.1(b)(3) and (4) and 110.2(b)(3) and (4).

- https://www.fec.gov/help-candidates-and-committees/registering-candidate/testing-the-waters-possible-candidacy/

- [x] Add AOs and regs 

AO 2015-09
102.10, 102.15, 103.2 and 103.3(a)

**Testing the waters for possible candidacy**
https://www.fec.gov/help-candidates-and-committees/registering-candidate/testing-the-waters-possible-candidacy/

- [x] Testing the waters vs. campaigning
Change the example year to 2024 

Add bullet to the bullet sections 
• Inform the media (either directly or through an advisor) that they will announce their candidacy on a certain date;

- [x] Add the following example to the end of the page:
Mr. Jones is interested in running for a seat in the U.S. House of Representatives but is unsure whether he has enough support within his district to make a successful bid. He therefore accepts up to 
$2,700900 from each of several relatives and friends and raises $30,000. He uses the money to pay for an opinion poll. He sees that good records are kept on the money raised and spent in his testing the waters effort. The poll results indicate good name recognition in the community, and Jones decides to run.
By making this decision, Jones has crossed the line from testing the waters to campaigning. The funds he raised earlier now automatically become contributions, and the funds he spent, including the polling costs, are now expenditures. These contributions and expenditures count toward the threshold that triggers candidate status. Since his contributions or expenditures exceed $5,000, he becomes a candidate and must register with the FEC. The money raised and spent for testing the waters must be disclosed on the first report his principal campaign committee files.
Had Jones decided not to run for federal office, there would have been no obligation to report the monies received and spent for testing the waters activity, and the donations made to help pay for the poll would not have counted as contributions.

**House, Senate and presidential candidate committee registration**
- https://www.fec.gov/help-candidates-and-committees/registering-candidate/house-senate-presidential-candidate-committee-registration/

- [x] Did we want to add this paragraph to this page 
If the candidate designates a new principal campaign committee, the committee must file a new Statement of Organization (FEC Form 1) within 10 days after being designated. 102.1(a). The newly designated committee will receive a new FEC identification number.

- [x] Compare with Guide online
- [x] Talk to Info if needed 
- [x] Draft changes in Word to circulate 
- [x]  Draft in Wagtail 
- [x]  Second pair of eyes 
- [x]  Publish

**Comment by djgarr** [comment]
Edits made and word versions of the pages circulated to Content and Info
