### ISSUE TITLE
Add table data to spreadsheet for E&J table data 

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5383]
### Summary

**What we are after:**
_We are working on a plan to make E&J pages/tables easier to update using Wagtail's table tool and also eventually migrate the many tables in the E&J appendix off of transition._

### Related issues

- #5316 
- #5373 
- #5407 
- #4834 

### Completion criteria

-  [x] Table data is added into the [spreadsheet](https://docs.google.com/spreadsheets/d/1BeKTLFc-eV5-USEdY_xmXzXPQXR41L-EOU_aD0P9C5E/edit?usp=sharing), one page per tab

### Tech steps or considerations (optional)
- Copy each table into the spreadsheet
- Spreadsheet will contain the code for each table.
- One page per tab in the spreadsheet
- Pat to add the html for the links

### Future tickets
- Will copy/paste from the spreadsheet into the table block(s) for each page (start with this page: https://www.fec.gov/legal-resources/regulations/explanations-and-justifications/chronological-index-2020-2029-ejs/)
- Will delete the old html block that contained the manually coded tables.
- Will migrate the E&J appendix in the same way

**Comment by dorothyyeager** [comment]
We'll start with pages that will be affected by upcoming rulemakings just approved by the Commission
https://www.fec.gov/legal-resources/regulations/explanations-and-justifications/chronological-index-2020-2029-ejs/

Citation index:
https://github.com/fecgov/fec-cms/issues/5223#issuecomment-1238632721 (Those are the cites that will need indexing updates, so we'll do those pages first.)

**Comment by dorothyyeager** [comment]
We tested today in the candidate loan ticket and it went very smoothly. On chronological pages, we will need to manually add <br> in the 2nd column. The rest worked fantastic. On Citation pages, it will be just simple copy/paste.

**Comment by dorothyyeager** [comment]
Almost done with this. One more page to go! Then will re-assign to Pat to finish putting in the hyperlinks.

**Comment by dorothyyeager** [comment]
All of the tables have been pasted into the spreadsheet; reassigning to @patphongs to add the hyperlinks. For Pat, no hyperlinks needed for the tabs that start with App:

**Comment by patphongs** [comment]
Thanks @dorothyyeager, I was able to update the spreadsheet with the necessary HTML. I was also able to preserve the line breaks (`<br>`) tags and put them in as code for the "Title, FR Notice Citation and Effective Date" column as well. That way you don't need to add those manually.
