### ISSUE TITLE
Design changes for relevant AO comment pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5398]
**What we're after:**
Mockup AO pages based on recommendations and discussion in [improve access to AO comment information](https://github.com/fecgov/fec-cms/issues/5355) ticket. 

**Affected pages:**
- https://www.fec.gov/data/legal/advisory-opinions/
- https://www.fec.gov/legal-resources/advisory-opinions-process/#commenting

**Action items:**
- [x] Mock up pages and share with PMs and content for review
- [x] Designs are shared with stakeholders via demo meeting
- [x] Any required changes are made and used in implementation tickets

**Completion criteria:**
- [x] Designs are mocked up and approved by stakeholders and PMs
- [x] Implementation tickets are created/updated

**Comment by JonellaCulmer** [comment]
@AmyKort @patphongs 

Here is a mock-up of the draft AOR comment section on the advisory opinion process page. The only changes to this section compared to what's currently available on .gov are the blurbs that say "During this time..." and the email address, hand delivery address and fax numbers. If you see any wrong information, please let me know. 

Have the contact information repeat does seem slightly redundant, but with contact information available for the other steps in the process and not this one, it appears to some that there is no shipping/delivery information available. Unless we want to rewrite the page to make it clear that that same shipping/delivery information is used for all steps. 

<img width="847" alt="Screen Shot 2022-08-23 at 5 18 58 PM" src="https://user-images.githubusercontent.com/31663028/192384846-bf026419-9778-4446-9c68-00de492323bb.png">

**Comment by AmyKort** [comment]
Thanks, Jonella. I think this is a good solution.

**Comment by JonellaCulmer** [comment]
@patphongs @AmyKort 
Thanks for your feedback on the AO process page. What follows is the mockup for the AO page. Specifically the section for the pending AO requests. The only change is the addition of the deadline for AO requests. When speaking with OGC to present them with both pages, I'd like to talk through the addition of the draft AO deadlines as well, but because there's no way to automate that, it will need to be a longer term change involving our contractors to add fields in our system where AO documents are added. 

For now, I think we can automate the AO request comment deadlines.
 
![Screen Shot 2022-09-27 at 10 01 55 AM](https://user-images.githubusercontent.com/31663028/192548624-05760c47-fe57-4cf8-a25d-e3b78c6838a0.png)

**Comment by AmyKort** [comment]
Looks good to me!

**Comment by kathycarothers** [comment]
Looks good

**Comment by JonellaCulmer** [comment]
Blocked while we wait to meet with OGC.

**Comment by JonellaCulmer** [comment]
Takeaways from meeting with OGC:
- Good to go on adding AOR comment deadlines on the [AO page](https://www.fec.gov/data/legal/advisory-opinions/) and updating delivery information on the [AO process page](https://www.fec.gov/legal-resources/advisory-opinions-process/)
- Deadlines will remain on the website until 11:59pm the day of the deadline and will then be removed
- Neven is going to confirm the delivery language for where comments should be sent and whether we still need the language, “During this time, the Commission is not accepting hand deliveries or faxes. Please submit comments on AO drafts by email.”
- Once we have that information and make the other changes, Jonella will keep everyone informed on when the changes have been implemented on the website.

**Comment by JonellaCulmer** [comment]
Blocked while we wait for final delivery language from OGC. Moving to 19.5
