### ISSUE TITLE
Take down transition files identified in 19.2 are ready to delete 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#5417]
### Summary

**What we're after:**
We are getting off transition 

### Completion criteria

- [ ] These files are taken down and Content team alerted when done:

Files:

HTML

/rad/documents/FECFileGettingStartedManual_000.pdf
/rad/documents/GettingStartedManual-UpdatedDecember2011.pdf
/rad/documents/GettingStartedManual-UpdatedDecember2011RL.pdf
/support/DataConversionTools.shtml

**Comment by johnnyporkchops** [comment]
All files deleted from transition stage and I ran the delete sync script to:
```
[websync@fecas065 ~]$ ./prod-sync-and-delete.sh
Wed Oct 26 15:36:17 EDT 2022
delete: 's3://cg-9b32b324-4671-48ca-b13b-a37b742f7443/rad/documents/FECFileGettingStartedManual_000.pdf'
delete: 's3://cg-9b32b324-4671-48ca-b13b-a37b742f7443/rad/documents/GettingStartedManual-UpdatedDecember2011.pdf'
delete: 's3://cg-9b32b324-4671-48ca-b13b-a37b742f7443/rad/documents/GettingStartedManual-UpdatedDecember2011RL.pdf'
delete: 's3://cg-9b32b324-4671-48ca-b13b-a37b742f7443/support/DataConversionTools.shtml'
Finished syncing and  deleting files

```
