### ISSUE TITLE
Electronic Filing Page - user feedback confusing language

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#5424]
### Summary
Feedback from RAD Analyst:

"I’ve had a couple of newer committees lately that are getting confused by this page on the website and I wanted to bring it to your attention: https://www.fec.gov/help-candidates-and-committees/filing-reports/electronic-filing/. They are reading it and thinking that they don’t have to file at all until they make or disburse $50,000. Maybe a banner at the top stating that every registered committee must file a report, until they file a termination report would be helpful since they just read voluntary and are moving on."

Discuss with content team to decide how to improve the language on this page. (Include @JonellaCulmer.)

### Completion criteria

- [x] Update language. Send around to Content and Jonella for comments
- [x] Send around to OGC
- [x] Second pair of eyes
- [x] Publish update

**Comment by djgarr** [comment]
Updates published
