### ISSUE TITLE
Research and Migrate the 2000 matching fund submissions

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#5441]
### Summary

**What we're after:**
As a researcher, I am interested in matching fund submissions of the 2000 presidential candidates.

We need to locate the 2000 presidential candidate submission pages in transition, then create a page for those as well and link on the home page for this.

### Related issues

_List any relevant related issue(s)_

- #5305 

### Completion criteria

**Follow these pages for style**
https://www.fec.gov/campaign-finance-data/presidential-matching-fund-submissions/
https://www.fec.gov/campaign-finance-data/presidential-matching-fund-submissions/2004-presidential-matching-fund-submissions/

### Action items
- [ ] Create draft pages in the Campaign finance data section to replace these pages using Custom page template, approved language (Dorothy can supply), and https://github.com/fecgov/fec-cms/issues/3386#issuecomment-815849646
- [ ] Second pair of eyes by content team member and Jonella before publishing
- [ ] PDF and ZIP files are placed in CMS or in S3 bucket (check with @patphongs)

###  Completion criteria
- [ ] Need to locate the 2000 files in folders for the classic website. Please see the following press release for the candidate https://www.fec.gov/updates/fec-approves-matching-funds-for-2000-presidential-candidates-8/
- [ ] New pages are published to replace these pages
- [ ] Audit/Public Records/Press are informed that the pages are live
- [ ] Ticket for redirecting old pages is created.

**Comment by dorothyyeager** [comment]
We learned via work on the 1996 matching funds that didn't turn out to be matching funds, that there are no 2000 files to migrate. Closing ticket, no work needed.
