### ISSUE TITLE
Document  how to update the Debt Settlement/Administrative Termination page

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5464]
### Summary

**What we're after:**
_As a website team member, I need to know how to update https://www.fec.gov/legal-resources/policy-other-guidance/administrative-terminations-and-debt-settlement-plans/ when there is a debt settlement or administrative termination to post._

### Completion criteria

- [ ] Process for updating https://www.fec.gov/legal-resources/policy-other-guidance/administrative-terminations-and-debt-settlement-plans/ is documented and shared with team.

**Comment by bmathesonFEC** [comment]
Draft is saved here: https://docs.google.com/document/d/1z4WJL4K61HSeu-0R0rBuyKmr-erMNyU7ZNP3-4i-_OA/edit?usp=sharing

Emailed to the Content Team for review

**Comment by dorothyyeager** [comment]
Looked good to me! Thanks @bmathesonFEC !

**Comment by bmathesonFEC** [comment]
Updates following @dorothyyeager feedback:

1. Linked to the Wagtail page in the instructions documents
2. Updated the [ITD Web Posting Guidance](https://docs.google.com/document/d/1NK1lSTXUNiHlg4-CjV5FZzbq3hnmqJJj9dA2d_fWB8s/edit?usp=sharing) with a link to the AT/DSP instructions
3. Linked to the Instructions in Wagtail using a comment. Looks like this when you're viewing the page:

![image](https://user-images.githubusercontent.com/33758291/210379756-f3e2172a-d617-448a-ae85-920148067b99.png)
