### ISSUE TITLE
Research sitemap generation

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#5499]
Investigate if there are sitemap generation [changes for Wagtail V3 or V4](https://docs.wagtail.org/en/stable/reference/contrib/sitemaps.html).

**Completion criteria**
- Checked into sitemap changes from v3 to v4
- Any changes (additional functionality) has been implemented
- New version of sitemap has been/will be generated

**Comment by johnnyporkchops** [comment]
-  Using [Wagtail ](https://docs.wagtail.org/en/stable/reference/contrib/sitemaps.html)and [Django](https://docs.djangoproject.com/en/4.1/ref/contrib/sitemaps/#django.contrib.sitemaps.Sitemap.protocol) sitemap docs, we can create a sitemap of all pages in Wagtail  cms which will be automatically updated and available at `fec.gov/sitemap.xml`
- We  can create another sitemap for `/data` and `/legal` pages either manually or using an online sitemap generator.
    - The online generator referenced on search.gov limits the number of pages based on current server load,  starting at 3500 pages and  going to up to 5500 (i think) . When running  our  site, I got up to `4650 ` which is less than our 10,000+ pages.  However, I  think it did capture all `/data` ,   and most if not all `data/legal`; and `/regulations` pages. So it  might work to use i the free online generator to create the static non-wagtail sitemap.  Also we could considet  paying to generate a one-time sitemap that we can use.
- We can  create a sitemap index using the Django/Wagtail[ sitemap-index utility ](https://docs.djangoproject.com/en/4.1/ref/contrib/sitemaps/#creating-a-sitemap-index) to point search.gov and search engines to both of our sitemaps

I have a WIP branch with cms-sitemap setup and the partial  online-generated one mentioned above saved if you would like to see that.

**Comment by johnnyporkchops** [comment]
Options have been documented above and the  process tested in WIP branch.
Waiting to hear back from search.gov support for next issue:  [#5501-Document search.gov xml sitemap requirements](https://github.com/fecgov/fec-cms/issues/5501)
