### ISSUE TITLE
QA Wagtail V3 and log any issues

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#5519]
### Summary

**What we're after:**
We need to do quality assurance testing and log any issues for the new version of Wagtail V3. It has been deployed to [feature space](https://fec-feature-cms.app.cloud.gov/admin/) for testing.

### Related issues

_List any relevant related issue(s)_

- #5500 

### Tech steps or considerations

Take a look at the ["What's new"](https://docs.wagtail.org/en/v4.0.1/releases/3.0.html#what-s-new) section of the Wagtail documentation. Here's a summary of some things to test:

- [x] Rich text block splitting (will existing complicated content still display, allow and save updates and then display again?)
- ~Page descriptions~ (This is an added feature that we have not implemented, we'd need to add `page_description` to the model if we want to utilize it.)
- [x] Image duplicate detection
- [x] Check all rich text editor functionality to make sure it still works
- CMS Templates
    - [x] About landing page
    - [x] Alert for emergency use only
    - [x] Collection page
    - [x] Commissioner page
    - [x] Contact page
    - [x] Custom page
    - [x] Digest page
    - [x] Document feed page
    - [x] Document page
    - [x] Example page
    - [x] Full width page
    - [x] Home page
    - [x] Home page banner announcement
    - [x] Legal resources landing page
    - [x] Meeting page
    - [x] Oig landing page
    - [x] Press landing page
    - [x] Press release page
    - [x] Record page
    - [x] Reports landing page
    - [x] Resource page
    - [x] Services landing page
    - [x] Tips for treasurers page
    - [x] Snippets

### Completion criteria

- Wagtail v3 has been tested and we have a list of fixes/issues

### Future work

Will roll out v3 to Production, then move to v3>v4

**Comment by patphongs** [comment]
Wagtail search is not working

<img width="885" alt="Screen Shot 2022-12-14 at 11 03 33 AM" src="https://user-images.githubusercontent.com/12799132/207646332-a6039291-8202-4a8e-9d96-4df1497c5d9f.png">

**Comment by johnnyporkchops** [comment]
@patphongs, for the admin search, could this be the issue: . (we ignored it in the bump to 2.15 because we dont have it in installed apps and I think it comes into play in V3)
https://docs.wagtail.org/en/stable/releases/2.15.html#database-search-backends-replaced

**Comment by kathycarothers** [comment]
I am moving this ticket into the next sprint

**Comment by patphongs** [comment]
> for the admin search, could this be the issue: . (we ignored it in the bump to 2.15 because we dont have it in installed apps and I think it comes into play in V3)

Thanks for this tip @johnnyporkchops! Once I made this modification, the wagtail search worked again

**Comment by patphongs** [comment]
@kathycarothers A good video to watch for changes to the Wagtail 3 version is here: https://www.youtube.com/watch?v=owsdUze9m0Q. It'll show you the improvements made for this version, so you can kind of know what to look out for.

**Comment by patphongs** [comment]
I found that on the services landing page template, it requires something in the intro block to be published. But this is not related to the Wagtail 3 upgrade as this is also a requirement in production. I tested inserting text into the intro block and because we don't have it being inserted anywhere on the page, you don't see it. I think we can just move past this for now, if it needs fixing at a later date, we can remove the intro block from there.

**Comment by patphongs** [comment]
Image duplication detection works great

<img width="911" alt="Screen Shot 2023-01-11 at 2 43 03 PM" src="https://user-images.githubusercontent.com/12799132/211902588-31a48c44-6398-4995-b7d3-48477bb221f7.png">

**Comment by patphongs** [comment]
Wagtail v3 has been fully tested, all aspects seem to be functioning well. Will review the [PR](https://github.com/fecgov/fec-cms/pull/5517) with @rfultz and @johnnyporkchops tomorrow to make sure things are looking good.

**Comment by djgarr** [comment]
@patphongs asked me to test the page title updates. They are functioning as they do in V2: to change the internal page title, the page needs to be published first

**Comment by pkfec** [comment]
PR https://github.com/fecgov/fec-cms/pull/5517 got merged. Closing this issue.
