### ISSUE TITLE
Banners 20.2 (12/20 through 1/2)

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#5524]
### Summary

What we are after:
Routine sprint ticket for banner work each sprint.

### Related issues

[Banner spreadsheet](https://docs.google.com/spreadsheets/d/1MPGmgOFg-pjlkYZHUl28thVd1IPCQEmsseg7idH5ThU/edit?usp=sharing)
[Banner How to](https://docs.google.com/document/d/1Ehq3sxa6WXzLWf1UdwnbLIsKNTcCnSHIECcPYfWWhC4/edit?usp=sharing)

### Completion criteria

Banners set up for:
- [x] No Open meeting during sprint (next meeting is 1/12/)
- [x] Any other banners that might come up during the sprint (rulemaking deadlines, eFiling maintenance, etc.)

Additional banner work:
- [x] Rotate the rulemaking banner that was posted 10/28 as needed (if there are two other banners to be posted) - not anticipated during this sprint.
- [x] Add new rulemakings to the pending rulemaking page that goes in tandem with the banner as needed (One will need to be added on 12/22)
- [x] Update pending rulemaking page on 12/28 to take the rulemaking expiring on 12/27 off
- [x] Create the ticket for the next sprint.

**Comment by pkfec** [comment]
EFO maintenance banner set for 12/24 (Ken's request)

**Comment by pkfec** [comment]
Dorothy and I deleted the _REG 2022-05 Conduit Reporting Threshold_ rule making from the website’s pending rule making page on 12/28

**Comment by rfultz** [comment]
Not anticipating anything new, so closing
