### ISSUE TITLE
Banners and pending rulemaking page updates 20.3

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5529]
### Summary

What we are after:
Routine sprint ticket for banner work each sprint.

### Related issues

[Banner spreadsheet](https://docs.google.com/spreadsheets/d/1MPGmgOFg-pjlkYZHUl28thVd1IPCQEmsseg7idH5ThU/edit?usp=sharing)
[Banner How to](https://docs.google.com/document/d/1Ehq3sxa6WXzLWf1UdwnbLIsKNTcCnSHIECcPYfWWhC4/edit?usp=sharing)

### Completion criteria

Banners set up for:
- [x] Open meetings during sprint (next meeting is 1/12/23)
- [ ] Any other banners that might come up during the sprint (eFiling maintenance, etc.)

Additional banner work:
- [x] Rotate the rulemaking banner out (if there are two other banners to be posted) - not anticipated during this sprint.
- [x] Add new rulemakings to the pending rulemaking page that goes in tandem with the banner as needed  
- [x] First thing on January 10: Update pending rulemaking page to take the rulemaking that expired 1/9 off the page.
- [x] Create the ticket for the next sprint.

**Comment by pkfec** [comment]
Everything is updated for next week.
