### ISSUE TITLE
Update glossary for new terms (adapted disclaimer, indicator, and mechanism)

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#5559]
### Summary

With the updated guidance for internet public communication disclaimers, three new terms are defined that are important to the understanding of what is needed for an internet disclaimer

### Completion Criteria

- [ ] Add terms and definitions for adapted disclaimer, indicator, and mechanism to the glossary for when the new rules take effect on March 1, 2023

### Definitions

The new 11 CFR 110.11(g) defines an adapted disclaimer as:

“A clear statement that the internet public communication is paid for, and that identifies the person or persons who paid for the internet public communication using their full name or a commonly understood abbreviation or acronym by which the person or persons are known, which is accompanied by: (1) an indicator and (2) a mechanism”

An indicator is defined as:

“Any visible or audible element associated with an internet public communication that is presented in a clear and conspicuous manner and gives notice to persons reading, observing, or listening to the internet public communication that they may read, observe, or listen to a disclaimer satisfying the requirements of paragraphs (b) and (c)(1) of this section through a mechanism. An indicator may take any form including, but not limited to, words, images, sounds, symbols, and icons.”

A mechanism is defined as:

“Any use of technology that enables the person reading, observing, or listening to an internet publication communication to read, observe, or listen to a disclaimer satisfying the requirements of paragraphs (b) and (c)(1) of this section after no more than one action by the recipient of the internet public communication. A mechanism may take any form including, but not limited to, hover-over text, pop-up screens, scrolling text, rotating panels, and hyperlinks to a landing page.”

**Comment by kathycarothers** [comment]
Sent to OGC for review

**Comment by kathycarothers** [comment]
OGC approved the terms

**Comment by kathycarothers** [comment]
This ticket has been incorporated into ticket #5565
