### ISSUE TITLE
Research issues found during Wagtail 4 QA and testing

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#5583]
### Summary

**What we're after:**
_Wagtail 4.1.1 has so far been a successful upgrade. However, there have been a lot of changes since Wagtail v3, which we are currently using in production. We need to carefully document these changes for our content owners so that they will be informed and trained before we officially upgrade to the new version._

Content owners:
- Audit
- Press
- Public Records
- Info
- RAD

Another consideration is that [Wagtail 4.2](https://docs.wagtail.org/en/stable/releases/4.2.html) has recently been released. We may want to try it out for the upgrade.

### Related issues
- #5545 
- https://github.com/fecgov/fec-cms/pull/5576

### Completion criteria
- [ ] Create a document of changes in version 4.2 for content owners
- [ ] Attempt 4.2 upgrade
- [ ] Test 4.2 upgrade considerations

**Comment by dorothyyeager** [comment]
Referencing this issue as this bug is happening in our current version of Wagtail: https://github.com/fecgov/fec-cms/issues/5532

**Comment by dorothyyeager** [comment]
Documenting some unwanted spacing found when linking documents on a meeting page
![image](https://user-images.githubusercontent.com/24437369/218200236-2dd5802a-559d-4c06-a641-b32a1b7ca0c7.png)

**Comment by patphongs** [comment]
I've been so busy this sprint that I could not do this ticket. I have moved it to PI 20 innovation.

**Comment by cnlucas** [comment]
https://docs.google.com/document/d/15QsPaXpQ21LB1MYnbOgMowgb2t4tiDQto4HmzVXOys8/edit?usp=sharing
