### ISSUE TITLE
On committee profile page, show raw filings for new cycle

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#5588]
### Summary

**What we're after:**
_On the committee profile page, we want to show raw filings for the new cycle, even when there is no other processed filings present._

When a 2022 year end filing, which is an F3, F3x, or F3p, should be under the 2022 cycle. However, in cases like this, the year end filings are showing up in the 2024 cycle.

Example 1:
For example, as of today 1/31/2023, this committee has no processed filings for the 2024 two year period. However, they do have raw electronic filings, we want to show the 2024 two year period in the drop down and be able to see the electronic filings for the current period. Example API call: https://api.open.fec.gov/v1/efile/filings/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&data_type=efiling&sort=-receipt_date&per_page=100&cycle=2024&committee_id=C00766162&min_receipt_date=2023-01-28

Example 2: 
https://www.fec.gov/data/committee/C00099259/?tab=filings&cycle=2022 this committee has the 2022 YE raw filing showing up in the 2024 cycle only for the CMS. The 2022 cycle does not have the 2022 YE raw filing, but it should. API call for raw efiling is: https://api.open.fec.gov/v1/efile/filings/?api_key=DEMO_KEY&sort_hide_null=false&sort_nulls_last=true&sort=-receipt_date&per_page=100&page=1&cycle=2024&committee_id=C00099259&min_receipt_date=01%2F28%2F2023&election_full=false 

### Completion criteria

- [ ] TBD

**Comment by fec-jli** [comment]
http://127.0.0.1:8000/data/committee/C00099259/?tab=filings&cycle=2024
(7 server side api call)
127.0.0.1 - - [31/Jan/2023 12:02:43] "GET /v1/committee/C00099259/history/2024?per_page=1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jan/2023 12:02:43] "GET /v1/committee/C00099259/history/2024?per_page=1 HTTP/1.1" 200 -
127.0.0.1 - - [31/Jan/2023 12:02:44] "GET /v1/committee/C00099259/candidates/history/2024?election_full=False HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jan/2023 12:02:44] "GET /v1/committee/C00099259/candidates/history/2024?election_full=False HTTP/1.1" 200 -
127.0.0.1 - - [31/Jan/2023 12:02:45] "GET /v1/filings?form_category=REPORT&most_recent=True&committee_id=C00099259&cycle=2024&per_page=1&sort_hide_null=True HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jan/2023 12:02:45] "GET /v1/filings?form_category=REPORT&most_recent=True&committee_id=C00099259&cycle=2024&per_page=1&sort_hide_null=True HTTP/1.1" 200 -
127.0.0.1 - - [31/Jan/2023 12:02:48] "GET /v1/committee/C00099259/totals?committee_id=C00099259&cycle=2024&per_page=1&sort_hide_null=True HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jan/2023 12:02:48] "GET /v1/committee/C00099259/totals?committee_id=C00099259&cycle=2024&per_page=1&sort_hide_null=True HTTP/1.1" 200 -
127.0.0.1 - - [31/Jan/2023 12:02:50] "GET /v1/efile/filings?cycle=2024&committee_id=C00099259&min_receipt_date=01%2F28%2F2023 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jan/2023 12:02:50] "GET /v1/efile/filings?cycle=2024&committee_id=C00099259&min_receipt_date=01%2F28%2F2023 HTTP/1.1" 200 -
127.0.0.1 - - [31/Jan/2023 12:02:51] "GET /v1/filings?committee_id=C00099259&form_type=F1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jan/2023 12:02:51] "GET /v1/filings?committee_id=C00099259&form_type=F1 HTTP/1.1" 200 -
127.0.0.1 - - [31/Jan/2023 12:03:05] "GET /v1/efile/filings/?api_key=&sort_hide_null=false&sort_nulls_last=true&sort=-receipt_date&per_page=100&page=1&cycle=2024&committee_id=C00099259&min_receipt_date=01%2F28%2F2023&election_full=false HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jan/2023 12:03:05] "GET /v1/efile/filings/?api_key=&sort_hide_null=false&sort_nulls_last=true&sort=-receipt_date&per_page=100&page=1&cycle=2024&committee_id=C00099259&min_receipt_date=01%2F28%2F2023&election_full=false HTTP/1.1" 200 -


(5 client api call)
http://localhost:5000/v1/efile/filings/?api_key=&sort_hide_null=false&sort_nulls_last=true&sort=-receipt_date&per_page=100&page=1&cycle=2024&committee_id=C00099259&min_receipt_date=01%2F28%2F2023&election_full=false
http://localhost:5000/v1/filings/?api_key=&sort_hide_null=false&sort_nulls_last=true&sort=-coverage_end_date&sort=report_type_full_original&sort=-beginning_image_number&per_page=100&page=1&cycle=2024&committee_id=C00099259&form_type=F3&form_type=F3X&form_type=F3P&form_type=F3L&form_type=F4&form_type=F5&form_type=F7&form_type=F13&form_type=RFAI&report_type=-24&report_type=-48&request_type=-1&request_type=-5&request_type=-6&request_type=-9&election_full=false
http://localhost:5000/v1/filings/?api_key=&sort_hide_null=false&sort_nulls_last=true&sort=-receipt_date&per_page=100&page=1&cycle=2024&committee_id=C00099259&form_type=F5&form_type=F24&form_type=F6&form_type=F9&form_type=F10&form_type=F11&form_type=RFAI&report_type=-Q1&report_type=-Q2&report_type=-Q3&report_type=-YE&request_type=-1&request_type=-3&request_type=-5&request_type=-6&request_type=-7&request_type=-8&request_type=-9&election_full=false
http://localhost:5000/v1/filings/?api_key=&sort_hide_null=false&sort_nulls_last=true&sort=-receipt_date&per_page=100&page=1&cycle=2024&committee_id=C00099259&form_type=F1&form_type=RFAI&request_type=-2&request_type=-3&request_type=-4&request_type=-5&request_type=-7&request_type=-8&request_type=-9&election_full=false
http://localhost:5000/v1/filings/?api_key=&sort_hide_null=false&sort_nulls_last=true&sort=-receipt_date&per_page=100&page=1&cycle=2024&committee_id=C00099259&form_type=F1M&form_type=F8&form_type=F99&form_type=F12&form_type=RFAI&request_type=-1&request_type=-2&request_type=-3&request_type=-4&request_type=-5&request_type=-6&request_type=-7&request_type=-8&election_full=false

--------------------

http://127.0.0.1:8000/data/committee/C00099259/?tab=filings&cycle=2022
(5 server side api calls)
127.0.0.1 - - [31/Jan/2023 12:19:06] "GET /v1/committee/C00099259/history/2022?per_page=1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jan/2023 12:19:06] "GET /v1/committee/C00099259/history/2022?per_page=1 HTTP/1.1" 200 -
127.0.0.1 - - [31/Jan/2023 12:19:07] "GET /v1/committee/C00099259/candidates/history/2022?election_full=False HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jan/2023 12:19:07] "GET /v1/committee/C00099259/candidates/history/2022?election_full=False HTTP/1.1" 200 -
127.0.0.1 - - [31/Jan/2023 12:19:08] "GET /v1/filings?form_category=REPORT&most_recent=True&committee_id=C00099259&cycle=2022&per_page=1&sort_hide_null=True HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jan/2023 12:19:08] "GET /v1/filings?form_category=REPORT&most_recent=True&committee_id=C00099259&cycle=2022&per_page=1&sort_hide_null=True HTTP/1.1" 200 -
127.0.0.1 - - [31/Jan/2023 12:19:09] "GET /v1/committee/C00099259/totals?committee_id=C00099259&cycle=2022&per_page=1&sort_hide_null=True HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jan/2023 12:19:09] "GET /v1/committee/C00099259/totals?committee_id=C00099259&cycle=2022&per_page=1&sort_hide_null=True HTTP/1.1" 200 -
127.0.0.1 - - [31/Jan/2023 12:19:10] "GET /v1/filings?committee_id=C00099259&form_type=F1 HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [31/Jan/2023 12:19:10] "GET /v1/filings?committee_id=C00099259&form_type=F1 HTTP/1.1" 200 -

(4 client api calls)
http://localhost:5000/v1/filings/?api_key=&sort_hide_null=false&sort_nulls_last=true&sort=-coverage_end_date&sort=report_type_full_original&sort=-beginning_image_number&per_page=100&page=1&cycle=2022&committee_id=C00099259&form_type=F3&form_type=F3X&form_type=F3P&form_type=F3L&form_type=F4&form_type=F5&form_type=F7&form_type=F13&form_type=RFAI&report_type=-24&report_type=-48&request_type=-1&request_type=-5&request_type=-6&request_type=-9&election_full=false
http://localhost:5000/v1/filings/?api_key=&sort_hide_null=false&sort_nulls_last=true&sort=-receipt_date&per_page=100&page=1&cycle=2022&committee_id=C00099259&form_type=F5&form_type=F24&form_type=F6&form_type=F9&form_type=F10&form_type=F11&form_type=RFAI&report_type=-Q1&report_type=-Q2&report_type=-Q3&report_type=-YE&request_type=-1&request_type=-3&request_type=-5&request_type=-6&request_type=-7&request_type=-8&request_type=-9&election_full=false
http://localhost:5000/v1/filings/?api_key=&sort_hide_null=false&sort_nulls_last=true&sort=-receipt_date&per_page=100&page=1&cycle=2022&committee_id=C00099259&form_type=F1&form_type=RFAI&request_type=-2&request_type=-3&request_type=-4&request_type=-5&request_type=-7&request_type=-8&request_type=-9&election_full=false
http://localhost:5000/v1/filings/?api_key=&sort_hide_null=false&sort_nulls_last=true&sort=-receipt_date&per_page=100&page=1&cycle=2022&committee_id=C00099259&form_type=F1M&form_type=F8&form_type=F99&form_type=F12&form_type=RFAI&request_type=-1&request_type=-2&request_type=-3&request_type=-4&request_type=-5&request_type=-6&request_type=-7&request_type=-8&election_full=false

**Comment by hcaofec** [comment]
For C00766162
As seen in [fec/data/views.py](https://github.com/fecgov/fec-cms/blob/develop/fec/data/views.py#L597), the cycle on the drop-down list must equal to current cycle in order to have raw filings shown on committee profile page.  After the committee has processed filings for 2023, the drop-down list of cycle will have 2023-2024, then the "Raw electronic filings" section will shown on committee profile page.

For C00099259
This committee has processed 2023 filings, so the cycles_has_activity includes 2023-2024 in drop-down list. Because there is no cycle filter in efiling endpoint, the endpoint returns all raw filing that is within min_receipt_date regardless of cycle.  

```
# If in the current cycle, check for raw filings in the last three days
    if cycle == utils.current_cycle():
        # (4)call efile/filings under tag: efiling
        path = "/efile/filings/"
        filters = {
            "cycle": cycle,
            "committee_id": committee["committee_id"],
            "min_receipt_date": template_variables["min_receipt_date"]
        }
        raw_filings = api_caller.load_endpoint_results(path, **filters)

        template_variables["has_raw_filings"] = True if raw_filings else False
    else:
        template_variables["has_raw_filings"] = False
```

**Comment by patphongs** [comment]
Hotfix to resolve this issue has been deployed.
