### ISSUE TITLE
Methodology buttons do not work on House and Senate overview pages

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#5607]
### Summary

Methodology buttons do not work on House and Senate overview pages:
https://www.fec.gov/data/elections/senate/

Since the  nav tag is wrapping  the link to the `{{ other_office }}` page,  it thinks it's part of the tabbed panel. It looks like moving `js-toc` class from the `nav` to the `ul`  fixes it without any responsive issues. i.e : `<ul class="sidebar__content js-toc">`

https://github.com/fecgov/fec-cms/blob/1a67e0fc9a2562d824e63731e0b4c2eed1e94d01/fec/data/templates/house-senate-overview.jinja#L26-L27

_What should have happened?_
Methodology buttons should open dialogue
### Frequency
Always

### How to Reproduce
Try Methodology buttons on https://www.fec.gov/data/elections/senate/

### Device, browser, etc

_Tell us everything you can about:_

- _your device (e.g. laptop, tablet, phone),_
- _its operating system (e.g. Windows, iOS, Android),_
- _your browser (e.g. Chrome, Internet Explorer, Safari, "Internet"),_
- _your screen or browser window size (for mobile, is it portrait or landscape?),_
- _your Internet connection (e.g. home, mobile, VPN),_

### Screenshots

_Screenshots would help us correctly identify the issue._

### Misc

_If you'd like to include anything else that may be of interest, do that here._

### Completion Criteria
- [ ] Methodology buttons should open dialogue

**Comment by JonellaCulmer** [comment]
Work has been merged, so closing.
