### ISSUE TITLE
Wagtail wish list: Ability to put snippets in order so the most used are on page 1.

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5608]
### Summary

**What we're after:**
As a Wagtail user who needs a snippet, it would be good to not have to go to the last page for the one I need.

Right now the snippets are in the order they were created. That means some of the most used ones (contribution limits for 2023-2024) and COVID snippet) are on the last page.

Background information: https://stackoverflow.com/questions/63472227/wagtail-how-to-order-snippets

### Completion criteria

- [x] Snippets for 2023-2024 contribution limits, the COVID snippet and the coordinated party expenditures archive appear on page 1 of the snippet list.

**Comment by johnnyporkchops** [comment]
We could add this to the `EmbedSnippet` model and it will order the snippets in the Wagtail admin from newest to oldest, putting most recently created on page one.

    class Meta:
        ordering = ['-id']
        
Don't forget to run `makemigrations` and add the new migration file to the PR.

<hr>

**Note:**  Wagtail 4 will have a ton of new ways to handle Snippets, including adding sortability in the admin panel, although the [ implementation ](https://docs.wagtail.org/en/stable/topics/snippets.html#customising-snippets-admin-views)looks a bit complex at first glance of the docs.
