### ISSUE TITLE
Presidential Map 2024

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#5641]
**What are we after:**
We're going to continue to add presidential election cycles to the presidential map. In anticipation of that work, we need to modify the toggle year selector to a dropdown select. 

**Related work:**
Previous epic work: https://github.com/fecgov/fec-epics/issues/174

**Action items:**
- [x] Bubbles are removed 
- [x] "Candidates running in" filter is now a dropdown selector
- [x] 2024 is added

**Completion criteria:**
- [x] Presidential map is updated for 2024 election

**Comment by JonellaCulmer** [comment]
@PaulClark2 @patphongs @rfultz @AmyKort 

Updated mock-up:
![Screen Shot 2023-03-29 at 1 23 45 PM](https://user-images.githubusercontent.com/31663028/228619269-df0a5cc7-957e-40d0-a861-baec7cb3b88e.png)

Draft text for intro paragraph: 
Presidential candidates are included in this presentation if they have reported receipts of more than $100,000 from sources outside the candidate's own funds. The candidate list displays each candidate's overall receipts, including contributions from the candidate, individuals and other political committees as well as transfers from the candidate’s prior federal campaigns.

**Comment by PaulClark2** [comment]
Thanks @JonellaCulmer .  This looks good to me.

**Comment by patphongs** [comment]
This hotfix has been deployed
