### ISSUE TITLE
Verify old transition files are taken down

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5650]
### Summary

**What we're after:**
We recently updated the www redirects and want to verify that some transition files were removed.

### Completion criteria

- [ ] These files are confirmed to be removed from transition:

/audits/audit_reports.shtml
/audits/audit_reports_auth.shtml
/audits/audit_reports_unauth.shtml
/audits/audit_reports_pres.shtml

/finance/2012matching/2012matching.shtml
/finance/2008matching/2008matching.shtml
/finance/disclosure/2016MatchingFundSubmissions.shtml
/finance/disclosure/2004MatchingFundSubmissions.shtml

/general/library.shtml

/images/audio.png
/images/play_icon.png
/images/transcript_icon.png

**Comment by patphongs** [comment]
The following have been removed from transition:
- /audits/audit_reports.shtml
- /audits/audit_reports_auth.shtml
- /audits/audit_reports_unauth.shtml
- /audits/audit_reports_pres.shtml
- /images/audio.png
- /images/play_icon.png
- /images/transcript_icon.png

These files had already been removed previously:
- /finance/2012matching/2012matching.shtml
- /finance/2008matching/2008matching.shtml
- /finance/disclosure/2016MatchingFundSubmissions.shtml
- /finance/disclosure/2004MatchingFundSubmissions.shtml
- /general/library.shtml
