### ISSUE TITLE
Front-end: H4 feature updates based on UAT feedback

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5653]
**What we're after:**
This ticket serves as a placeholder for potential future improvements to H4 feature work. 

UAT happening here: https://github.com/fecgov/fec-cms/issues/5652

**Completion criteria:**
- [ ] Updates to the H4 feature work has been completed based on UAT feedback

**Comment by pkfec** [comment]
Closing this issue in favor of https://github.com/fecgov/fec-cms/issues/5652
