### ISSUE TITLE
Incorporate shape files into code

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5656]
**What we're after:**
Begin to incorporate congressional district map shape files into election search code. Consult with cloud.gov using supplemental support hours. 

### Related issues
https://github.com/fecgov/fec-cms/issues/5655

### Completion criteria
- [ ] Completed consultation with cloud.gov and followup tickets have been opened to incorporate shape files into code base.

**Comment by rfultz** [comment]
Closing this ticket as the work was completed in the research ticket #5663 and PR #5672
