### ISSUE TITLE
Redesign debts table columns

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5658]
**What we're after:**
Need to consider improvements to the table layout (columns) that improve clarity. Coverage start and end dates with coverage end date being more important. 

**Action items:**
- [x] Consider coverage date placement
- [x] Sorting by coverage end date
- [ ] Does data need to be moved to the details panel
- [x] Is there additional data that should be included on the datatable

**Completion criteria:**
- [x] Designs are created and added to followup tickets

**Comment by JonellaCulmer** [comment]
@PaulClark2 @johnnyporkchops @AmyKort @tmpayton @prstoetzer 
Here are the updated mockups for the debts datatable and details panel. Please let me know if you have any edits/feedback on what's being presented. 
![Screen Shot 2023-05-15 at 10 55 20 AM](https://github.com/fecgov/fec-cms/assets/31663028/9a9b4f1b-0163-46de-a606-475f7c77a362)
![Screen Shot 2023-05-15 at 10 55 32 AM](https://github.com/fecgov/fec-cms/assets/31663028/d6364abe-1411-4dff-bf84-5b43a9ea144c)

**Comment by PaulClark2** [comment]
Thanks, @JonellaCulmer. Please use `committee_name`.
