### ISSUE TITLE
Banner updates for 21.2 (4/4 - 4/17)

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#5678]
### Summary

What we are after:
Routine sprint ticket for banner work each sprint.

### Related issues

[Banner spreadsheet](https://docs.google.com/spreadsheets/d/1MPGmgOFg-pjlkYZHUl28thVd1IPCQEmsseg7idH5ThU/edit?usp=sharing)
[Banner How to](https://docs.google.com/document/d/1Ehq3sxa6WXzLWf1UdwnbLIsKNTcCnSHIECcPYfWWhC4/edit?usp=sharing)

### Completion criteria

Banners set up for:
- [x] No scheduled open meeting during the sprint (next open meeting scheduled for 4/19 during 21.3)
- [x] Extended phone hours for the April Quarterly filing deadline on 4/14
- [x] Any other banners that might come up during the sprint (rulemaking deadlines, eFiling maintenance, etc.)

Additional banner work:
- [x] Create the ticket for the next sprint

**Comment by dorothyyeager** [comment]
Closing, no banner work anticipated today.
