### ISSUE TITLE
(After 4/15/23) Check for 2024 bugs and switch default years to 2024

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#5682]
## Summary
Check and document bugs for change of default year to 2024. Fix any bugs that arise and switch to 2024. We'll need to update the following default year constants to 2024:

```
DEFAULT_TIME_PERIOD
DEFAULT_ELECTION_YEAR
DEFAULT_PRESIDENTIAL_YEAR
```

### Action items
- [ ] Use this [compare candidate totals script](https://github.com/lbeaufort/scripts/blob/master/compare_candidate_totals.py) to check totals across different endpoints to ensure changes look good.
- [x] Once default years are updated to 2024, check the behavior of items below

**Items to check**
- [x] Homepage
- [x] Current totals
- [x] Future election cycles
- [x] Candidate profile page
- [x] Election profile page
- [x] Raising by the numbers, candidate totals data table
   - [x] Aggregate totals
   - [x] Where do contributions come from?
- [x] Presidential map

**Completion criteria:**
- [x] `DEFAULT_TIME_PERIOD`, `DEFAULT_ELECTION_YEAR`, and `DEFAULT_PRESIDENTIAL_YEAR` is updated to 2024

**Comment by rfultz** [comment]
Looks good!
