### ISSUE TITLE
Feature flag "Who is raising and spending the most" feature on homepage

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#5683]
### Summary

**What we're after:**
_As we wait for additional filings to come in, we'll want to add a feature flag for the "Who is raising and spending the most" visualization on the homepage._

### Completion criteria

- [x] Feature flag is added and turned on

**Comment by johnnyporkchops** [comment]
Home page raising/spending has an existing feature flag: `FEC_FEATURE_HOME_BARCHARTS`

We can turn off/on as needed with either:
-  `cf update-user-provided-service`[(FEC-WIKI)](https://github.com/fecgov/FEC/wiki/5.-Development#enablingdisabling-features-on-cloud-foundry) 
- Or in the Cloud.gov dashboard : https://dashboard.fr.cloud.gov/

![Screen Shot 2023-03-31 at 1 37 27 AM](https://user-images.githubusercontent.com/5572856/229032896-9863a0f3-cb3b-49c6-b1db-8061cac3ebed.png)
