### ISSUE TITLE
Add 2024 for presidential candidate map exports

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#5701]
### Summary

**What we're after:**
_We need to update the presidential candidate map export links to include 2024._

In addition, we'd like to avoid additional hotfixes for the monthly and quarterly coverage dates by making the following sentence more generic:

> The 2020 files contain financial activity through the most recent filing. The historical files contain financial activity through December 31 of the corresponding election year.

 We will update the sentence to and include a variable for the default presidential year:

>The {{ default_presidential_year }} files contain financial activity through the most recent filing. The historical files contain financial activity through December 31 of the corresponding election year.

**Overall candidate summary**
[2024](https://www.fec.gov/files/bulk-downloads/Presidential_Map/2024/2024_overall_summary.csv)

**Contribution totals by size**
[2024](https://www.fec.gov/files/bulk-downloads/Presidential_Map/2024/Contributions_by_Size.csv)

**Contribution totals by state and three-digit zip code**
[2024](https://www.fec.gov/files/bulk-downloads/Presidential_Map/2024/Contributions_by_3Zip.csv)

<img width="693" alt="Screen Shot 2023-04-18 at 12 24 20 PM" src="https://user-images.githubusercontent.com/12799132/232842233-b467f36d-48b6-40a6-9ada-2685f1a90f2e.png">

### Related issues

_List any relevant related issue(s)_

- #5641 

### Completion criteria

- [ ] 2024 links for presidential candidate map exports is added
- [ ] Update the coverage date sentence

**Comment by PaulClark2** [comment]
@patphongs the 2024 links look good.

**Comment by rfultz** [comment]
Both PRs have been merged
