### ISSUE TITLE
Debts browse data page language

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5766]
**What we're after:**
Write language for the introduction to the debts datatable:

Draft language: Search debts owed by committees. Search by committee, creditor/debtor's name, coverage date and balance.

### Completion criteria
- [x] Language is approved by content and added to [development ticket](https://github.com/fecgov/fec-cms/issues/4413).

**Comment by JonellaCulmer** [comment]
@dorothyyeager Please take a look at the draft language in the original comment for the debts datatable. You can see what the table in-progress looks like in @rfultz's PR: https://github.com/fecgov/fec-cms/pull/5765

**Comment by dorothyyeager** [comment]
@JonellaCulmer One small tweak - can we say:
Search debts owed by committees. Search by committee, creditor/debtor's name, coverage date, beginning balance and ending balance.

**Comment by JonellaCulmer** [comment]
Thanks @dorothyyeager I'm good with your changes. I'll add this to the dev ticket that Robert is working on. Thanks so much!
