### ISSUE TITLE
Debts data table fixes from QA, if any

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#5779]
### Summary

**What we're after:**
Address any issues identified with QA of Debts datatable. https://github.com/fecgov/fec-cms/issues/5778

### Related issues

_List any relevant related issue(s)_

QA Debts datatable: https://github.com/fecgov/fec-cms/issues/5778
Prep debts datatable to launch: https://github.com/fecgov/fec-cms/issues/5660

### Completion criteria

- [ ] Any issues identified in QA are resolved in PR. https://github.com/fecgov/fec-cms/pull/5765

### Future work

_Other future work that may be needed following this issue's completion._

**Comment by JonellaCulmer** [comment]
Closing in favor of https://github.com/fecgov/fec-cms/issues/5778
