### ISSUE TITLE
Add historic presidential election years to Presidential map

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-cms#5780]
### Summary

Blocking this work is DBA Team work link TBA

**What we're after:**
_Include the historic presidential election years  2008 and 2012 to the Presidential map election years dropdown menu ._

### Completion criteria

Presidential map is live on the website, showing 2008 and 2012 Presidential summary data.

**Comment by rfultz** [comment]
The data work should be done on Sunday (Slack #data channel, 2023-07-11 11:38 EDT)
