### ISSUE TITLE
Inventory items in guidance search

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5782]
### Summary

**What we are after:**
_As a legal researcher, I need to access items in the guidance search such as Federal Register notices, RAD FAQs and Campaign Guides._

**Background**
Content team will need to put in redirects for the many PDF files in the guidance search after the site map is launched. This ticket is to prepare for that by making a complete inventory of the PDF files in a separate tab of our redirect spreadsheet. That way, we'll be ready to go when it's redirect time. We also should inventory the HTML files (although we may not need to redirect them).

### Related issues

#5770 

### Completion criteria

- [x] Spreadsheet for the guidance search files is created in the [redirect spreadsheet](https://docs.google.com/spreadsheets/d/1vzN-wZlS8K8ZyfExSV3hwXDenDEN9KyyAUJFTI6OjKU/edit) and populated with their current and new URLs.
- [x] Create ticket(s) for the redirects that will be needed
- [x] Create a chart that Agency Divisions can use to update URLs in internal documents

### Tech steps or considerations (optional)

Redirects for PDFs will be via www since the current PDFs are in the CMS.
Current URLs for the PDFs can be found in [this code](https://github.com/fecgov/fec-cms/blob/f9f0593025e9b2148363e2a1ed253aba14c4f065/fec/search/management/data/sitemap_pdf.xml) and [this code](https://github.com/fecgov/fec-cms/blob/f9f0593025e9b2148363e2a1ed253aba14c4f065/fec/search/management/data/sitemap_html.xml) 
Need columns for both the current URL and the future URL (work with @johnnyporkchops)

The new url patters are:
 HTML files: `https://www.fec.gov/updates/guidance-search/[FILE NAME]`
 PDF files: `https://www.fec.gov/resources/cms-content/documents/policy-guidance/[FILE NAME]`

### Future work

Redirect tickets
Testing tickets
Updating H4CC, Policy and other pages that contain the original URLs

**Comment by johnnyporkchops** [comment]
@dorothyyeager @kathycarothers 
The new path for PDFS will be:
 PDF files: `https://www.fec.gov/resources/cms-content/documents/policy-guidance/[FILE NAME]`
 
 We do not need to redirect HTML files because they will be aliased from their original location in `https://www.fec.gov//updates/[FILE NAME]` to: `https://www.fec.gov/updates/guidance-search/[FILE NAME]`. Edits to aliased pages are reflected in both locations.
 The webform one that is not in Wagtail will keep the same location too, ` https://webforms.fec.gov/wfja/form99`

**Comment by dorothyyeager** [comment]
@johnnyporkchops Thanks - you meant that this is the new path for PDFs in guidance search only, right?

Are other PDFs we've uploaded that aren't in guidance search affected in any way?

**Comment by dorothyyeager** [comment]
Updating to note that @johnnyporkchops confirmed that this is the new path for guidance search documents only.

**Comment by dorothyyeager** [comment]
Ticket created for www redirects at https://github.com/fecgov/fec-proxy/issues/365

We may need transition redirects too. We'll see.

**Comment by dorothyyeager** [comment]
I've created the chart and reached out to content team to doublecheck my inventory.

**Comment by dorothyyeager** [comment]
The follow up tickets were created and put in [22.5](https://github.com/fecgov/fec-cms/issues/5828) and [22.6](https://github.com/fecgov/fec-cms/issues/5829).

Kathy doublechecked the inventory and we are all set for [redirects in 22.4](https://github.com/fecgov/fec-proxy/issues/365) after site map is launched.

We will need to add two missing items to the guidance search (Form 7 and a FR notice from 2006) in [22.3](https://github.com/fecgov/fec-cms/issues/5818).

The chart I made of the old and new URLs is uploaded to our shared drive’s folder for guidance search and is linked in the two new tickets as well.. I did include the two missing items since we will fix that in the next sprint. This chart 

Inventory is done; thanks @kathycarothers for your help in checking it over!
