### ISSUE TITLE
Help language for H4 datatable and/or related pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5793]
**What we're after:**
Draft language that adds clarity to the H4 datatable. 

**Considerations:**
- [x] Brief language to add to the search page
- [x] Link to the allocation pages
- [x] Identify all affected changes

**Action items:**
- [x] Ask Jonella for email thread with discussion for additional information. 

**Completion criteria:**
- [x] Draft language approved by press
- [x] language updated on browse data page

**Comment by djgarr** [comment]
Spoke with Myles for clarification. Here's my understanding of what he is looking for with regards to the information and descriptions on https://www.fec.gov/data/browse-data/?tab=spending

Does information showing up in the H4 search
![image](https://github.com/fecgov/fec-cms/assets/40633757/430e90c1-23d6-40c7-b354-538b83a97e5d)

Also show up in general disbursement search
![image](https://github.com/fecgov/fec-cms/assets/40633757/edbf7c4c-33fd-4d52-aa0b-ff791734a66d)

An initial search doesn't appear to show that it does. @JonellaCulmer do you know if there is an overlap in the search results?

If it is the case that there isn't an overlap and the two searches pull different results, should we amend the language under the disbursement search to include a direction to the H4 search for allocated disbursements?

**Comment by JonellaCulmer** [comment]
@djgarr I'm not sure what other disbursements are not available through the disbursements search and what other datatables would be needed to account for that data, so my initial reaction is to not call out only allocated disbursements are not available there. It does already say "select" disbursements. Do you think we need something more substantial than that?

**Comment by djgarr** [comment]
After discussions, we'll update the language under the disbursements search to read "Excludes outside spending to support or oppose candidates and allocated federal/nonfederal disbursements.”
