### ISSUE TITLE
Content publishing for new procedure for litigation brought pursuant to 52 U.S.C. 30109 (a)(8) (2023)

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#5803]
### Summary

**What we're after:**
_Briefly describe the goal or user story for this issue. Be sure to include any dependencies._

The Commission passed new litigation procedures on 7/13/2023 (but are not implemented until 30 days) and there are some documents that we will need to publish to the website and link in the right places: Federal Register notice  and Record article.

Policy page how to posting guide: https://docs.google.com/document/d/1laNUjXQHAnXhjyo2OF04zUrV18IDQBgGwjHr7vNI13M/edit?usp=sharing

### Related issues

- Post approved items to Policy and other guidance page #5709
- Document updating the Policy and other guidance page #5639

### Completion criteria

- [x] Federal Register notices uploaded, following naming convention. Download them from https://www.federalregister.gov/agencies/federal-election-commission on August XX and upload into the Policy statements collection in Wagtail CMS.
- [x] FR notice linked 
- [x] Update calender for comment deadline October 16
- [x] Double-check the Guidance search 24 hours after the site map has been updated 
- [x] Record articled linked 
- [x] OGC and OCS notified about FR notices with cc to Press Office and Paul Stoetzer
- [x] Update Guidance Search OGC does require

### Screencap of what it will look like once all four items are uploaded and linked:
![image](https://github.com/fecgov/fec-cms/assets/24437369/9b7edb14-e7fa-4bc6-940a-70d040eda3dd)

**Comment by dorothyyeager** [comment]
Re-opened. The PR is merged, but there's some non-PR tasks left.
