### ISSUE TITLE
Add Presidential map to homepage, replacing Campaign finance data section/circle/link

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5805]
**What we're after:**
We need to reinstate the Presidential map circle on the homepage, replacing the Campaign finance data circle. 

### Related issues
- https://github.com/fecgov/fec-cms/issues/3544
- https://github.com/fecgov/fec-cms/issues/4791

### Completion criteria
- [x] Campaign finance data circle/links now shows the Presidential map and links directly to the Presidential map

**Comment by rfultz** [comment]
Should I do a full PR for what will be a Wagtail change? Here's the replacement first `<li>`:
```html
  <li class="grid__item grid__item--with-icon icon--large grid__icon--white text-centered gtm-exp gtm-exp-2021_hp_pres_link">
    <img src="/static/img/map-chart-icon.svg" alt="icon representing Presidential candidate map">
    <h2 class="u-margin--top"><a href="/data/candidates/president/presidential-map/">Presidential candidate map</a></h2>
    <p>Search presidential data such as money raised, money spent, cash on hand and debt.</p>
  </li>
```

Just for future reference, here's [a previous issue](https://github.com/fecgov/fec-cms/issues/4821).

This is what will be replaced:
```html
  <li class="grid__item grid__item--with-icon icon--large grid__icon--white text-centered">
    <a href="/data/" class="no-decoration"><img src="/static/img/i-complex--data--gray-lightest.svg" alt="icon representing search all campaign data"></a>
    <h2 class="u-margin--top"><a href="/data/">Search all campaign finance data</a></h2>
    <p>Research federal election data and its relevance across the country.</p>
  </li>
```

**Comment by JonellaCulmer** [comment]
@rfultz Everything looks good on the homepage! Thanks for handling this so quickly!
