### ISSUE TITLE
Add Romy Adame-Wilson to Wagtail author list

### ISSUE THREAD

**Issue by prstoetzer** [fecgov/fec-cms#5812]
Add Romy Adame-Wilson to Wagtail author list

### What we're after

Add Romy Adame-Wilson with title of Communications Specialist to the author list for Record articles in Wagtail.

### Completion criteria

Romy Adame-Wilson listed in the author list for Record articles.

**Comment by PaulClark2** [comment]
@dorothyyeager approved.
