### ISSUE TITLE
Take down transition files redirected in 22.2

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5827]
### Summary

**What we're after:**
We are getting the last random things off transition

### Completion criteria

- [x] These files are removed 

/law/policy/enforcement/2009/comments/comm32.pdf
/law/policy/enforcement/2009/comments/comm3.pdf
/law/policy/enforcement/2009/comments/comm4.pdf
/law/policy/enforcement/2009/comments/comm5.pdf

/law/us_code/us_code.shtml

/pages/hearings/candidatenonfederalfundraiser.shtml

/pdf/FR66n132p35978.pdf

/rad/candidates/CandidateCommitteesToPrint.shtml

**Comment by rfultz** [comment]
All gone!
