### ISSUE TITLE
Update pages with address to add delivery zip code of 20002

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5830]
### Summary

**What we're after:**
We want to ensure people who send things via delivery services send them to 20002 and not 20463. The paper filing page and contact page clearly explain this but other pages are missing the info.

### Completion criteria
- [x] Visitors section added to left side of contact page below Mailing address with the address, no ZIP
- [x] Visitor page icon needs to be replaced with the new one. Page has been drafted. 

- [x] [Paper filing page](https://www.fec.gov/help-candidates-and-committees/filing-reports/paper-filing/) is updated to match contact page for the wording regarding delivery services but keep examples - DRAFTED

![image](https://github.com/fecgov/fec-cms/assets/24437369/279f8dc5-0d0b-4436-b24d-98ce4731438a)

- [x] Remove zip code from this page - https://www.fec.gov/introduction-campaign-finance/how-to-research-public-records/
- [x] How to research Public records page has been drafted, but the icon needs to be replaced with the new icon. 
- [x] The following pages are updated, using the same wording as the contact page. DRAFTED
https://www.fec.gov/legal-resources/enforcement/complaints-process/how-to-file-complaint-with-fec/
https://www.fec.gov/legal-resources/policy-other-guidance/requests-legal-consideration/
https://www.fec.gov/freedom-information-act/
https://www.fec.gov/about/privacy-and-security-policy/
https://www.fec.gov/legal-resources/advisory-opinions-process/

- [x] OIG is contacted regarding what they'd like to do with addresses on their pages.
https://www.fec.gov/office-inspector-general/how-submit-a-complaint-with-the-fec-oig/
 
- [x] Zip code working group is notified that changes have been made.

**Comment by JonellaCulmer** [comment]
@kathycarothers I looked at all your current drafts and they look great. We should be good to publish these after the PR is merged. I'm about to review that now. 

Have we reached out to OIG about their page?

**Comment by kathycarothers** [comment]
@dorothyyeager, @JonellaCulmer  I believe Dorothy was going to reach out to the OIG office

**Comment by kathycarothers** [comment]
Dorothy has emailed the OIG office

**Comment by kathycarothers** [comment]
OIG has no changes to their pages at this time

**Comment by kathycarothers** [comment]
All pages and icons have been updated.
