### ISSUE TITLE
Update footer, meeting page language templates (open meeting and hearings) and add map-pin icon to wagtail templates

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5838]
**What we're after:**
Following a ZIP code working group decision, we need to make adjustments to some wagtail templates to include the [map-pin icon](https://fec-pattern-library.app.cloud.gov/docs/icons.html) for a new address display. Right now we don't have a great way to distinguish between "mailing address" versus "visitors address". 

We also need to modify our footer by removing the U.S postal service address in all environments, sites where our footer is present.

Lastly, we need to update the language in the meeting page template. There changes for open meetings and hearings will be different. Both use the meeting page template.

**Open meeting page change:** Amend the first paragraph to say,
“The Commission considers new regulations, advisory opinions and other public matters at open meetings, which are typically held on Thursdays at 10:30 a.m. at FEC headquarters, 1050 First Street NE, Washington, DC.” 

**Public hearing page change:** Amend the first sentence to say, 
“The Commission periodically holds public hearings at FEC headquarters, 1050 First Street NE, Washington, DC.”

**Templates needing the icon for contact item/item icon:**
- [ ] contact page
- [ ] resource page
- [ ] custom page

Related tickets: 
- https://github.com/fecgov/fec-cms/issues/5830

### Completion criteria
- [ ] Relevant wagtail templates now showing map-pin as icon choice for contact item/item icon
- [ ] Footer, in all locations, no longer includes address
- [ ] The meeting page template has updated language for both hearings and open meetings.

### Map icon location in Wagtail:
![Screen Shot 2023-08-02 at 9 11 45 AM](https://github.com/fecgov/fec-cms/assets/31663028/cab324bd-e127-456c-9277-4322055e953f)

### Mockup of modified footer:
![UpdatedFooterImage](https://github.com/fecgov/fec-cms/assets/31663028/6729b4f5-1374-4df4-a906-62dade1766f8)

**Comment by rfultz** [comment]
Closed with a hotfix
