### ISSUE TITLE
Research/Design improved placement of state filter on schedule a datatables (or all receipts)

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5857]
**What we're after:**
Need to update the appearance and organization of our all receipts datatable, and others, where we have state grouped in a separate category. Data customers have reported difficulty finding the filter. 

All the user issues below cited [https://www.fec.gov/data/receipts/individual-contributions/](https://www.fec.gov/data/receipts/individual-contributions/). 
There are two complaints among these issues, this issue will focus on the placement/design with future followup work to address the usability/accessibility issues:
 1) The state or territory dropdown is "hidden or buried" under "More contributor details"
 2) The scrolling on thst state dropdown in problematic

FEC repo comments:

- https://github.com/fecgov/FEC/issues/12699 
- https://github.com/fecgov/FEC/issues/12585
- https://github.com/fecgov/FEC/issues/12472
- https://github.com/fecgov/FEC/issues/11914
- https://github.com/fecgov/FEC/issues/11791

**Action items:**
-  [x] Research and propose solutions for updated filter organization
-  [x] Design for proposals
-  [x] Review with team
-  [x] Add to followup implementation ticket

**Completion criteria:**
- [x] Designs have been created and added to implementation issue(s)

**Future work:**
Research possible changes to usability/accessibiity  of drop downs based on other comments in these user-submitted issues

**Comment by JonellaCulmer** [comment]
@patphongs Because of the way we've organized the filters on the schedule a datatables, we're a little stuck in how/where we move the state filter. All other filters in the source details section are either limited to 10 selections or prevent data users from selecting an additional year. Currently there is no such limitation on state, but it's proving to be confusing to data users to be separated from the other similar filters. 

Do you have any objections with moving the state filter to the source details section? Perhaps we can discuss whether it needs to also be a blocker, only for consistency sake, with the other filters. I hesitate to do that though.

**Comment by patphongs** [comment]
> Do you have any objections with moving the state filter to the source details section?

@JonellaCulmer Moving the state filter to source details would require some changes in the error text right? It currently says "You're trying to search across multiple time periods. Filter by recipient name or ID, source details, or image number for results." The state filter is not included in the ability to select multiple time periods and moving it to source details would make the error statement inaccurate. Otherwise, I would have no problem in moving it to the source details section as you suggest. Especially since data users are having issues finding it.

**Comment by JonellaCulmer** [comment]
@patphongs Not necessarily. We really only need to if we want to limit it or make it requirement to adding additional time periods. It's good that we specify which filters need to be added, we would just leave state off the way it is now.

**Comment by JonellaCulmer** [comment]
@patphongs Please see the following updated filter panels for the receipts and individual contributions datatables. Let me know if you have any questions or feedback. 

### Receipts

Removes the "State and territory" filter from the "More source details" section. "Restrict contributions is the only remaining filter in that section. I've organized the state filter between city and ZIP.
![Receipts - moved state filter](https://github.com/fecgov/fec-cms/assets/31663028/74f3227e-8914-46f1-87dc-bf9221b73efd)


### Individual contributions

Remove the "More contributor details" section entirely, since the "State and territory" filter was the only thing in that section. We need to update the arrangement to "City", "State and territory", then "ZIP" to match the receipts datatable. 
![Individual contributions - moved state filter](https://github.com/fecgov/fec-cms/assets/31663028/7e982ebf-fd0a-4019-b3c2-0e412bfea89b)

**Comment by JonellaCulmer** [comment]
@patphongs @cnlucas Modified mockup for state or territory filter. Let me know your comments or concerns with this change. I also added similar language for the other filters with restrictions, those mockups follow the state or territory filter mockup. 
![Screenshot 2024-03-26 at 4 46 54 PM](https://github.com/fecgov/fec-cms/assets/31663028/33381b45-efa6-4090-a653-3c6a573729f2)

![Screenshot 2024-03-26 at 4 48 53 PM](https://github.com/fecgov/fec-cms/assets/31663028/129ae9fe-9262-488c-8017-b0507668d7d1)

![Screenshot 2024-03-26 at 4 49 54 PM](https://github.com/fecgov/fec-cms/assets/31663028/b7bbf848-1141-4e9b-9fc5-1c71db4ed476)

**Comment by patphongs** [comment]
> Modified mockup for state or territory filter.

Thanks @JonellaCulmer, this change looks good to me and should be easily implemented

**Comment by JonellaCulmer** [comment]
Closing in favor of https://github.com/fecgov/fec-cms/issues/6196
