### ISSUE TITLE
Update transition office page and organization chart for new Acting Deputy Staff Director

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5898]
### Summary

**What we're after:**
_We want to keep office pages updated._

### Completion criteria

- [x] **Content team:** On September 11, update https://www.fec.gov/about/leadership-and-structure/fec-offices/ to remove Kate Higginbothom as Deputy Staff Director and replace with Dayna Brown as "Acting Deputy Staff Director, ..."

![image](https://github.com/fecgov/fec-cms/assets/24437369/6cd7ac0b-58b9-480e-b807-7c2db5047dde)

- [x] **Frontend team:** Update https://transition.fec.gov/about/offices/DSDMA/DSDMA.shtml with Dayna's photo and bio. Do this on http://transition-stage.fec.gov/about/offices/DSDMA/DSDMA.shtml and it will sync to prod on next half-hourly sync. Please confirm that the sync took place (hard refresh/new icognito window)
    - Dayna's photo is at https://transition.fec.gov/about/offices/audit/Brown_Dayna.jpg 
    - Dayna's  bio can be copied from https://transition.fec.gov/about/offices/audit/audit.shtml.
    

### Future work

We'll need to update that Audit page if they name someone to act in Dayna's current position.

**Comment by johnnyporkchops** [comment]
This has been completed:
https://www.fec.gov/about/leadership-and-structure/fec-offices/
https://transition.fec.gov/about/offices/DSDMA/DSDMA.shtml
