### ISSUE TITLE
Update statistical summary PAC pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5902]
**What we're after:**
In order to prep for when the statistical summaries are ready to be posted, we may need to make hard-coded changes to the [PAC tables page](https://www.fec.gov/campaign-finance-data/political-action-committee-data-summary-tables/) in order to accommodate some additional tables. 

**Action items:**
**After PR is merged and deployed:**
- [x] Upload the 2023-6-month files to the S3:  `campaign-finance-statistics/2024/tables/pac/`
- [x] Add the new table with `id=type_3` to a new Wagtail html-block (see PR for table html that still needs the descriptions column for 12a-14d added)
- [x] Add a selected-option to the `year select` in Wagtail for 2024 (remove selected from 2022):
     ```
     <option selected value="2024">2023-2024</option>
    
    ```
 - [x] Make the 6-month option selected in the `segment select` and remove selected from the 24-month option)
    ```
    <option selected value="6">6 Month</option>
    ````

### Completion criteria
- [x] Statistical summary pages are prepped and ready for 2023-2024, 6-month segment
- [x] Statistical summary pages are updated

**Comment by johnnyporkchops** [comment]
complete
