### ISSUE TITLE
Update Audit Division page on Transition site for new Acting Assistant Staff Director

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5915]
### Summary

**What we're after:**
_We want to keep office pages updated._

### Completion criteria

- [x] **Content** - Get photo and bio from Zuzana Pacious (Requested)

Bio to insert: 
Ms. Pacious joined the FEC as an Auditor in 2000.  Since 2012, she has served as an Audit Supervisor and the Presidential Election Campaign Fund Manager.  She is a Certified Fraud Examiner and received her Bachelor of Science from the University of Louisville College of Business and Public Administration.

- [ ] **Front end team:** Update https://transition.fec.gov/about/offices/audit/audit.shtml to replace Dayna's photo and bio with Zuzana Pacious's photo and bio and change the title to "Acting Assistant Staff Director." Do this on http://transition-stage.fec.gov/about/offices/audit/audit.shtml and it will sync to prod on next half-hourly sync. Please confirm that the sync took place (hard refresh/new incognito window)

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Image is in ITDweb.

**Comment by johnnyporkchops** [comment]
https://transition.fec.gov/about/offices/audit/audit.shtml
