### ISSUE TITLE
Wagtail Bug: Document Page template pages are showing up in search results

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#5918]
### Summary

When searching for a PDF document, the page used to feed that PDF into a document feed is showing up in search results. That's not good because those pages contain no content and will confuse users. 

Example: Enter "shutdown" into global search

This page and others like it appear: https://www.fec.gov/about/reports-about-fec/agency-operations/fec-plan-for-agency-operations-in-the-absence-of-the-fiscal-year-2024-appropriation/

![image](https://github.com/fecgov/fec-cms/assets/24437369/07838390-8883-46b2-ba7e-03d868e62728)
 
_What should have happened?_

It would be better if the document feed page associated with that document appeared: https://www.fec.gov/about/reports-about-fec/agency-operations/

Alternatively, it would work OK if the PDF associated with the page was included on the document page: https://www.fec.gov/resources/cms-content/documents/FY2024-Shutdown-Plan-07-27-2023.pdf

### Frequency

Since site search improved

### How to Reproduce

Enter a term like "shutdown" into global search and click results that aren't PDFs.

### Device, browser, etc

Happened on Chrome 

### Screenshots

Above

### Misc

@dorothyyeager is available to pair or answer questions about what needs to show up.

**Comment by johnnyporkchops** [comment]
### @dorothyyeager  @JonellaCulmer. Three options below:

### 1) Can we just link the title like this?:

![doc_page_linked](https://github.com/fecgov/fec-cms/assets/5572856/36a3b7cc-dd03-4960-b894-c058d38b68bd)

### 2) Or do you want to add the extension and size and link the extension, like this?:

![file_extension_linked](https://github.com/fecgov/fec-cms/assets/5572856/79b9d617-64d4-4909-a877-e0d7910ec146)

### 3)  Or both, or something else?

**Comment by dorothyyeager** [comment]
@johnnyporkchops I'll defer to @JonellaCulmer but I am good with either of those options. It seems like just the link is less work and gets the job done, so that's my vote.

**Comment by johnnyporkchops** [comment]
@JonellaCulmer , the only way to force a search result link to a webpage to go to a link to a document (or any other address) is to redirect it.

For the pages with the document link, we can also link from the Category button above to a filtered parent:
Example: /about/reports-about-fec/oig-reports/?category=inspection+or+special+review+report&year=2023
![link_category_btn](https://github.com/fecgov/fec-cms/assets/5572856/95288521-d6fc-4f98-8745-b7d5740b5ecb)

**Comment by JonellaCulmer** [comment]
@johnnyporkchops What's the level of effort on the redirects? I think it would be cleaner for customers to click on the link in the search and go directly to the PDF. As you said, these pages were not intended to be seen.

**Comment by johnnyporkchops** [comment]
@JonellaCulmer,  We might want to ask @dorothyyeager because redirects are her expertise, but it would mean creating @420 redirects and then having to create a new redirect every time a new document is created. There is no way to do a global redirect pattern for these pages because the document name is different than the title of the page.

While it does represent an extra click to get to the document from a search result, the interim step is not totally useless  because it orients the user to where they are in the ecosystem of `Reports about the FEC` and shows the same into you would get there before viewing a document (date, file size, category, file-type). It also gives the user a path to search other related documents.

Although the pages were not  originally not meant to be seen, the `DocumentPage` template was created with some foresight (building some fields into the template) We just need to add the others.

**Comment by JonellaCulmer** [comment]
@johnnyporkchops Here's the mockup for the intermediary step while we work on the longer term fix. 

![Screen Shot 2023-09-27 at 5 29 22 PM](https://github.com/fecgov/fec-cms/assets/31663028/935eed8e-b267-4131-9e44-65912a3204b7)

@dorothyyeager @AmyKort 
The current plan for the longer term fix would be to explore the removal of document pages from the global search results or redirect them and @johnnyporkchops will spend some time during innovation exploring the options. The end goal would be to bypass these document pages and go directly to PDFs. So even if we implement this intermediary step, we'll later remove the extra click and customers won't lose any time.

**Comment by JonellaCulmer** [comment]
Closing for now, work has been merged to fix links to documents. Longer term issues to link directly to documents from search and bypass these pages entirely.
