### ISSUE TITLE
Non-election year IE reporting on Form 5, content updates

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#5941]
### Summary
Update the Form 5 IE reporting guidance on the site to clarify reporting requirements during the non-election year. Feedback from RAD is here:

I would recommend the following:

1. On the “Reporting Independent Expenditures on Form 5” page (https://www.fec.gov/help-candidates-and-committees/making-independent-expenditures/reporting-independent-expenditures-form-5/), under “Filing Reports”/”48-Hour Reports,” revise the first sentence with the text in bold: “At any time during a calendar year **, including non-election years,** through the 20th day before an election, filers must report each time they make independent expenditures with an aggregate value of $10,000 or more with respect to a given election.”
2. Also add the language below to this portion of the page:

> 24-hour and 48-hour reports
> In some circumstances, filers may need to file specific and separate reports of independent expenditures. These are called 24- and 48-hour reports.
> •	**For each election in which a person who is not a political committee makes independent expenditures, the person shall aggregate its independent expenditures made in each calendar year to determine its reporting obligation.**  
> •	[Electronic filers](https://www.fec.gov/help-candidates-and-committees/filing-reports/electronic-filing/) file these reports electronically.
> •	[Paper filers](https://www.fec.gov/help-candidates-and-committees/filing-reports/paper-filing/) file by fax or email.

3. In the 48-Hour reporting example for Form 5 filers (https://www.fec.gov/help-candidates-and-committees/making-independent-expenditures/48-hour-reports-independent-expenditure-filers/), revise the second sentence with the text in bold: ” The 48-hour reporting period is for independent expenditures that are made in any calendar year **, including non-election years,** up to an**d** including the 20th day before an election.”  Please note that the letter “d” at the end of “and” is currently missing and should be added, see the screen shot below.

4. Also add this language as the first sentence of the page referenced below:

> **For each election in which a person who is not a political committee makes independent expenditures, the person shall aggregate its independent expenditures made in each calendar year to determine its reporting obligation.**  

![image](https://github.com/fecgov/fec-cms/assets/33758291/ae9c2c63-624c-408a-b927-4b7314460cb9)

5. **This has been split into another ticket at https://github.com/fecgov/fec-cms/issues/5955**
 On the “Dates and Deadlines” page (https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/), under “2023 Reporting Dates,” there is a bullet for “Independent Expenditures,” which leads directly to the page on “24- and 48-Hour Reports of Independent Expenditures periods: special elections (2023).”  The filer complained that this makes it sound like there is no other IE reporting requirement besides that relating to special elections, so I was wondering if we could tweak this.  We could make the special election reporting a subsection on this page, and include a new section stating that for IEs relating to the upcoming 2024 elections, there is a 48-Hour reporting requirement.  My suggestion would be to change the title of this page to “**2023 24- and 48-Hour Reports of Independent Expenditures**,” for consistency with the title of the quarterly reporting page for committees (“2023 Quarterly Reports”), and revise the first paragraph with the text in bold: “Political committees and other persons who make independent expenditures (IEs) may have to disclose this activity within 24- or 48-hours based upon the date and amount of the expenditure. **Aside from the reporting requirements below relating to 2023 special elections, filers may need to disclose IEs _made in 2023_ relating to 2024 elections on 48-Hour Reports.  During non-election years, filers must report each time they make independent expenditures with an aggregate value of $10,000 or more with respect to any given election, up to and including the 20th day before an election, on a 48-Hour Report.**”  Then, we can move the title below for 2023 special election reporting below the button “Learn more about making independent expenditures” (please see the screen shot below), so that it is a subsection.

![image](https://github.com/fecgov/fec-cms/assets/33758291/d5e4743d-91bf-432e-be15-a38210c62dd3)

### Completion criteria

- [ ] Pages updated with new wording/titles
- [ ] Content team second-set-of-eyes review

**Comment by bmathesonFEC** [comment]
Useful regulatory language:

> 
For each election in which a person who is not a political committee makes independent expenditures, the person shall aggregate its independent expenditures made in each calendar year to determine its reporting obligation.

**Comment by dorothyyeager** [comment]
During refinement, the content team realized #5 is a much bigger undertaking and decided to spin it off into its own ticket so we could do the MVP work in #1 - #4 in 23.1.

#5 will need input from Info Division. New ticket is at https://github.com/fecgov/fec-cms/issues/5955.

**Comment by bmathesonFEC** [comment]
Reviewed and approved @ryanfec edits. Ready for changes in Wagtail.
