### ISSUE TITLE
Fix broken links and formatting on Commissioner bio pages

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#5956]
**What we're after:**
A customer posted a comment in our FEC repo regarding broken links on Commissioner Scott Thomas' bio page. We need to audit the page to identify all broken links requiring redirects/remediation. 

### Related issues
https://github.com/fecgov/fec-proxy/pull/46 - beta redirect

### Slack conversations:
Legal resources: https://fecgov.slack.com/archives/C3X34QQNQ/p1696944220138779 
Content: https://fecgov.slack.com/archives/C3Z3QP0JD/p1697213986900199 

**Action items:**
- [ ] Review page and compile list of broken links
- [x] Fix formatting problems with the page (compare with other Commissioner pages to ensure formatting is correct)
- [ ] Cursory review of other Commissioner pages to identify similar issues
- [ ] Create redirects as applicable
- [ ] Identify other methods of remediation as needed
- [ ] Consider whether we need to let the original reporter know that the work's been complete? Or, before then, that we've got it queued?

**Completion criteria:**
- [ ] Broken links on Commissioner page(s) have been repaired
- [x] Formatting has be corrected in bio pages

**Comment by johnnyporkchops** [comment]
Redirects for [Scott E.Thomas's page](https://www.fec.gov/about/leadership-and-structure/scott-e-thomas/) and other past commissioners pages with these patterns

FYI: NGINX does not require forward slashes be escaped in the rewrite rules.

**Example link:** /members/former_members/thomas/thomasstatement17.htm (htm, html, doc, pdf)
**Regex101:** https://regex101.com/r/ArApLi/1
**Rewrite rule:** `rewrite ^\/members\/former_members\/(.*)\.(htm|html|pdf|doc) /resources/about-fec/commissioners/$1.$2 redirect`

Can we do full URL rewrites ,like below, in proxy [redirects-www.conf](https://github.com/fecgov/fec-proxy/blob/develop/redirects-www.conf) or do we need to put a return rule in NGINX conf?

**Example link:** https://cg-069252d5-5311-406c-9d08-a09e59f6b9c8.s3.amazonaws.com/legal/murs/current/35833.pdf
**Regex101:** https://regex101.com/r/WKGZxx/1
**Rewrite rule:** `rewrite https:\/\/cg-069252d5-5311-406c-9d08-a09e59f6b9c8\.s3\.amazonaws\.com\/(.*) https://cg-519a459a-0ea3-42c2-b7bc-fa1143481f74.s3-us-gov-west-1.amazonaws.com/$1 redirect`

**Comment by kathycarothers** [comment]
Fixed the formatting issues on Commissioner Thomas' page
