### ISSUE TITLE
Design changes to receipts and disbursements datatable - line number filter

### ISSUE THREAD

**Issue by cnlucas** [fecgov/fec-cms#5994]
Line_number currently doesn't work with more than one selection. Our current design makes it seem as if we should be able to support list inputs. We should redesign these section to support only one input. 

### Summary

Line-number selections on receipts and disbursement datatables should only support one selection. We need a design that will show the users to select one single line_number. 

### Current Situation

![Screen Shot 2023-11-09 at 9 58 54 AM](https://github.com/fecgov/fec-cms/assets/66386084/c1fbe010-8a2a-4384-84da-d4f9ac01b0b1)

![Screen Shot 2023-11-09 at 10 03 52 AM](https://github.com/fecgov/fec-cms/assets/66386084/2d663a98-f4ae-4d96-9b7e-c5975f24e2c8)

### Completion Criteria
- [ ] Designs for A and B tables have been created that support a single line_number
- [ ] Front-end Implementation tickets are created

**Comment by JonellaCulmer** [comment]
@patphongs @cnlucas @rfultz 
Since we are limited to one selection for line number on our larger schedule datatables, I've modified the receipt type filter to deactivate other options after one option is selected. 

![Screen Shot 2023-11-22 at 3 36 47 PM](https://github.com/fecgov/fec-cms/assets/31663028/91dc473f-9ead-46e7-85f1-81494a42cdb1)

**Comment by patphongs** [comment]
> deactivate other options

@JonellaCulmer I see multiple possible issues with this.

1. **Deactivating other options issue:** A typical single select drop down shows the selected option in the select box itself. If a user wants to go in and change their selection, they would simply click into the select box to make another selection.

<img width="558" alt="Screenshot 2023-12-11 at 1 49 12 PM" src="https://github.com/fecgov/fec-cms/assets/12799132/04d806fc-4a49-44b6-a162-a0ad64da875c">
<img width="535" alt="Screenshot 2023-12-11 at 1 48 54 PM" src="https://github.com/fecgov/fec-cms/assets/12799132/5fae4a49-5950-498e-ac77-5d379ff20634">

<img width="553" alt="Screenshot 2023-12-11 at 1 49 30 PM" src="https://github.com/fecgov/fec-cms/assets/12799132/6d68882d-54a5-454c-a2f7-02f5aa50ec98">
<img width="533" alt="Screenshot 2023-12-11 at 1 49 22 PM" src="https://github.com/fecgov/fec-cms/assets/12799132/da5854e9-bd13-4666-9d85-f5230e507a05">

With the deactivated options, the user would have to deselect the the option from the checkbox option first to reactivate the options then go into the dropdown to select another option. I don't think users are going to understand this. 

2. Multiple select boxes issue: Here we are deactivating multiple select boxes and options at once when a single option is selected. But if I want to select another option, I'd have to find the one original check box that is checked, uncheck it to reactivate the list, and then click back into a select box to select another option. And that checkbox could be in multiple locations, on the top of the first, second, or last select box. 

<img width="279" alt="Screenshot 2023-12-11 at 2 04 08 PM" src="https://github.com/fecgov/fec-cms/assets/12799132/fe7afba9-cd7c-4af5-9347-971e65726f3c">

Can we simplify it to where all the line numbers are in one select box with headings. We do this for [PACs SSF filters](https://www.fec.gov/data/receipts/individual-contributions/?two_year_transaction_period=2024&min_date=01%2F01%2F2023&max_date=12%2F31%2F2024).

<img width="418" alt="Screenshot 2023-12-11 at 2 07 46 PM" src="https://github.com/fecgov/fec-cms/assets/12799132/b3044fe6-d556-4a9f-b436-2ffc4a8d4018">

**Comment by JonellaCulmer** [comment]
@patphongs @rfultz Thanks for your feedback. So to summarize, make it a deselect and not deactivate, and combine all the filters into one dropdown with headers? I am a little concerned with combining all the line numbers together into one dropdown as it will now include 30 options, which is more than double what's in the PAC dropdown. It would be a relatively easy way to address both your concerns.

**Comment by JonellaCulmer** [comment]
@patphongs @rfultz @cnlucas Updated design for single dropdown for all line numbers:

### Dropdown appearance
![Screen Shot 2023-12-14 at 5 19 54 PM](https://github.com/fecgov/fec-cms/assets/31663028/d694d44a-9b71-4702-ba50-bd075ff998a3)

### Full dropdown options for [all receipts datatable ](https://www.fec.gov/data/receipts/)
Please note the correct location for the checkmark on the longest option. 
![Screen Shot 2023-12-14 at 4 16 52 PM](https://github.com/fecgov/fec-cms/assets/31663028/49cfe91f-5238-4801-a82c-9972f59ca5a6)

### Full dropdown options for the [disbursements datatable](https://www.fec.gov/data/disbursements/)
Please note the correct location for the checkmark on the longest option. 
![Screen Shot 2023-12-14 at 4 36 11 PM](https://github.com/fecgov/fec-cms/assets/31663028/b94f5574-2275-4cb1-b6f9-b8d5321d79c1)

**Comment by patphongs** [comment]
@JonellaCulmer Thanks for the updated designs. I tried it out in code form and can confirm that the dropdown text should extend out like in your comp. I just have a question regarding the new filter. When a line number is selected, where will the selected option appear when the dropdown is collapsed? Since I don't think we want to use the normal checkbox at the top of the dropdown for this new filter, we'll need a way for the user to know what filter was selected. Here's a crude mock up of what I mean. It doesn't necessarily need to appear inside the select box, but that's how a normal select box operates.

<img width="280" alt="Screenshot 2023-12-19 at 11 40 38 AM" src="https://github.com/fecgov/fec-cms/assets/12799132/8ad45e69-4c0d-425b-8457-e9e803e9c5e1">

**Comment by JonellaCulmer** [comment]
@patphongs Based on how I understand it to work right now, it would cut off the text after a certain length, right?

![Screen Shot 2023-12-19 at 3 48 14 PM](https://github.com/fecgov/fec-cms/assets/31663028/6e03fef0-4684-4581-8533-0f3c2400c0b1)

**Comment by patphongs** [comment]
> it would cut off the text after a certain length, right?

@JonellaCulmer I believe we could probably make it wrap, but this may make the select box grow taller or shorter depending on what's selected. @rfultz Do you have any suggestions about this?

**Comment by JonellaCulmer** [comment]
@patphongs Here are the updated mockups for the filter tags and dropdowns. The filter tags already include the section header such as "PACs and party committees". So we'd need to decide how we want the text to appear with the line number moved to the front of the line. 

**Filter tag before:**
<img width="237" alt="Screen Shot 2023-12-27 at 2 54 33 PM" src="https://github.com/fecgov/fec-cms/assets/31663028/e05fe6a1-1fa9-4622-802a-e3cd73d40138">


**Filter tag after:**
![Screen Shot 2023-12-27 at 3 18 01 PM](https://github.com/fecgov/fec-cms/assets/31663028/15e51d0b-b14b-449e-ad35-a4d09234a703)



**Dropdown without and with selection:**
![Screen Shot 2023-12-27 at 3 17 20 PM](https://github.com/fecgov/fec-cms/assets/31663028/2597791b-590f-4001-a3ab-460332dbbc14)


**Dropdown (open):**
![Screen Shot 2023-12-27 at 3 07 49 PM](https://github.com/fecgov/fec-cms/assets/31663028/b1748d5d-92f5-4c40-9c1b-45caa6aaddb3)


**Full dropdown text for receipts (moved line number and Form # added to section rows):**
![Screen Shot 2023-12-27 at 3 15 07 PM](https://github.com/fecgov/fec-cms/assets/31663028/3775c4cf-106f-4d64-ba68-88eae5978347)


**Full dropdown text for disbursements (moved line number and Form # added to section rows):**
![Screen Shot 2023-12-27 at 3 16 15 PM](https://github.com/fecgov/fec-cms/assets/31663028/25254709-5095-430f-84de-00a449e90c0c)

**Comment by patphongs** [comment]
> Here are the updated mockups for the filter tags and dropdowns. The filter tags already include the section header such as "PACs and party committees". So we'd need to decide how we want the text to appear with the line number moved to the front of the line.

Thanks @JonellaCulmer, I think the designs look good. But one thing to note is the consecutive use of colons within the filter tag. In your example "PACs or party committees: Line 28a: Refunds of contributions made to individuals/persons other than political committees". The first use of the colon is to signify a heading, but the second is to just signify a subheading? Something about the use of two colons in one tag doesn't make sense to me. But at the same time, I'm not sure how it should be. Perhaps this is something content could help with?

**Comment by JonellaCulmer** [comment]
@dorothyyeager @AmyKort @kathycarothers @djgarr, does at least one of you have a moment to look at the filter tag mock-ups in my last comment and provide feedback? We will adjust the filter tags to match, based on how we plan to change the dropdown. Do you have issues with the double colon?

**Comment by kathycarothers** [comment]
When I first reviewed it, it made sense. If you didn't want all the colons you could do a - for the sub heading, But I don't have an issue. Not sure if you want the -

**Comment by JonellaCulmer** [comment]
Following a discussion in Slack, we're updating the filter tag to look like this:
![Screen Shot 2024-01-05 at 10 07 11 AM](https://github.com/fecgov/fec-cms/assets/31663028/d82cc638-93d0-40fb-a9d9-ed3af74f90d9)


@patphongs @rfultz @johnnyporkchops Please let me know if there are any downstream issues resulting from reformatting these filter tags. I can make additional mockups if needed.

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation ticket: https://github.com/fecgov/fec-cms/issues/6073
