### ISSUE TITLE
Set up meeting pages for 2024 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#5997]
### Summary

**What we're after:**
As a user who follows Commission news, I need to know when the Commission is meeting in 2024. 

### Related Issues
#5998 - update meeting time to 10 am.

### Action items

- [x] Create pages in Updates using eh format for slugs: month-day-year-open-meeting (for open meetings) and month-day-year-executive-session (for executive sessions)
- [x] Content team spot-check pages
- [x] Let calendar editor in Info Div and Commission Secretary know when posted.

### Completion criteria

- [x]  Pages created 
- [x]  Info and Commission Secretary notified
- [x] Publish after December 14th meeting when the 23.4 release is deployed (12/18)
- [x]  Make sure the meeting start time has been changed to 10 am (hard coded) - related PR is ready to be merged.

### Helpful resources

#4885 (Create Meeting Pages for 2022 once Requested by OCS)
#5267 (Create Meeting Pages for second half of 2022 once Requested by OCS)
https://docs.google.com/document/d/13TJV9YD7V7GKOfp42nL_sT6qql1KUHgGEZ3W0Hwy6To/edit (How to page)

**Comment by dorothyyeager** [comment]
The meeting pages for 2024 are now live (both open meetings and executive sessions). Thank you @patphongs for getting them ready and @kathycarothers for being that second pair of eyes.
