### ISSUE TITLE
Update meeting page template to change default open meeting time 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#5998]
RELEASE DEPLOYED 12/18. Safe to do in 23.4 sprint. :)

### Summary

**What we're after:**
OCS has indicated that meeting times will go back to start meetings at 10:00. We need to update the default time in the meeting page template so that users interested in Commission meetings have accurate information.

### Completion criteria

- [x]  After December 14th the default time is changed on the meeting page template to 10 am
- [x]  Alert Content team once the time is changed to publish the meeting pages

**Comment by dorothyyeager** [comment]
This ticket can be closed once the PR is merged. For @kathycarothers @djgarr @patphongs: 2024 meeting pages can be published after the 23.4 release is deployed on December 18.
