### ISSUE TITLE
Fix closing double angle quotes (») on navigation links on Safari

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#6002]
**What we're after:**
Need to address issue on main site navigation where double closing angle quotesare appearing strangely on Safari. Additional research is needed across browsers to ensure this issue is only occurring on Safari. 

**Completion criteria:**
- [ ] Double closing angle quotes appearing correctly on navigation links on Safari

**Screenshot:**
<img width="960" alt="Screen Shot 2023-11-15 at 9 33 48 AM" src="https://github.com/fecgov/fec-cms/assets/31663028/dfe639e0-2d11-4009-b101-5b565a03d095">

**Comment by rfultz** [comment]
Other findings, all in desktop Safari:
- looks and behaves as expected in the smallest widths
- starts to break when we get a second column of menu items 
- adding a `position: relative` to the <a> seems to fix them and shouldn't break other things
