### ISSUE TITLE
QA Wagtail V5 and log any issues: Due 2/2

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-cms#6026]
**New features in wagtail 5.0**

- [x] When deleting an object(page, image, document or snippet), the confirmation screen now provides a summary of where the object is used, allowing users to see the effect that deletion will have elsewhere on the site.
[More on deleting objects](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-0/#object-usage-information-on-deleting-objects) 
Pat:

 - [x] Support for SVG image upload is available by adding the [settings](https://wagtail.org/blog/how-we-added-svg-support-to-wagtail-50/)
 [More on SVG image support](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-0/#svg-image-support)
Corinne: Not necessary, might be nice to test **I think we need to add  WAGTAILIMAGES_EXTENSIONS = ["gif", "jpg", "jpeg", "png", "webp", "svg"] to base.py**
- [x] Highlight item in pages with accessibility issues to more easily identify elements with errors
[Accessibility checker improvements](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-0/#accessibility-checker-improvements) Priya:
- [x] Page editor minimap always stays on
[More on Page editor minimap](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-0/#always-on-minimap)
Priya:
-  [x] Dark mode introduced! 
[More on Dark mode](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-0/#dark-mode)
Robert:
_____________________________________________________________________________________________

**New features in wagtail 5.1**
[Read-only panels](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-1/#read-only-panels)
[AVIF image support](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-1/#avif-image-support)
[Accessibility improvements](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-1/#accessibility-improvements)
[Dark mode improvements](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-1/#dark-mode-improvements)
[General UI improvements](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-1/#general-ui-improvements)
 - [x] Auto-select the StreamField block when only one block type is declared 
Corinne: Only true when block is req
 - [x] Comment notifications toggle is moved to the comments side panel
Corinne: In top right corner ok
**New features in wagtail 5.2**
[Redesigned page listing view](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-2/#redesigned-page-listing-view)
[User interface refinements](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-2/#user-interface-refinements)
[External links in promoted search results](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-2/#external-links-in-promoted-search-results)
[Subject and body for email links](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-2/#subject-and-body-for-email-links)
[Site-specific improvements](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-2/#site-specific-improvements)
[Wagtail user interface extensions with Stimulus](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-2/#wagtail-user-interface-extensions-with-stimulus)
[Content management features beyond pages](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-2/#content-management-features-beyond-pages)

**Fixed bugs**
- [x] Adding a new page in the left panel News and updates sub menu no longer timeout. Corinne

**CMS Templates**
Corinne:
- [x] About landing page
- [x] Alert for emergency use only
- [x] Collection page
- [x] Commissioner page
- [x] Contact page
John:
- [x] Custom page
- [x] Digest page
- [x] Document feed page
- [x] Document page 
- [x] Example page
- [x]  Reporting date table
Tricia:
- [x] Full width page
- [x] Home page
- [x] Home page banner announcement
- [x] Legal resources landing page
- [x] Meeting page
Pat:
- [x] Oig landing page
- [x] Press landing page
- [x] Press release page
- [x] Record page
- [x] Reports landing page
Priya:
- [x] Resource page 
- [x] Services landing page 
- [x] Tips for treasurers page 
- [x] Snippets 

### Action items
John:
 - Loop  Paul S (ask to test meeting template), Ryan, Myles (ask to test press release template & weekly digest) along with Kathy, Dorothy and David to test Wagtail5 upgrade in feature. 
     - Specifically, we would like Myles to test creating a new T4T from the News and Updates left menu because this upgrade fixes a [bug he reported here](https://github.com/fecgov/fec-cms/issues/5756).

- [x] When deployed to stage, loop in @djgarr @kathycarothers @ryanfec @dorothyyeager to spot check some of Wagail 5. It has already been fully tested by devs.  
- [x] Share out "What's new in Wagtail 5" link to wagtail users: https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-2/

### Related issues

- https://github.com/fecgov/fec-cms/issues/5580

### Completion criteria

- [x] Wagtail v5 has been tested and we have a list of fixes/issues
- [x] Warnings/errors in #5580 have been addressed

**Comment by pkfec** [comment]
>   Priya:
> * [x]  Resource page
> * [ ]  Services landing page
> * [x]  Tips for treasurers page
> * [x]  Snippets
In wagail 5.2 the following pages show Snippets menu:
Authors, Digest pages, Embed snippets, Press release pages, Record pages, Tips for treasurers pages

**Comment by cnlucas** [comment]
I tested on local and feature. Everything is working well for me. We do have to add 

WAGTAILIMAGES_EXTENSIONS = ["gif", "jpg", "jpeg", "png", "webp", "svg"] 

to base.py to use the svg uploader. I tested this as well and it seems to work fine. 
![Screenshot 2024-01-26 at 11 06 11 AM](https://github.com/fecgov/fec-cms/assets/66386084/c1307d57-c3cc-42be-8ba1-344c42227793)


Thanks for the awesome work @pkfec!

**Comment by tmpayton** [comment]
@pkfec great job on this ticket!

When I tried to create a home page and Legal resources landing page I got this server error

![image](https://github.com/fecgov/fec-cms/assets/121631201/2071cbb0-2afb-4a20-bbc5-b40a42cb758a)

**Comment by patphongs** [comment]
> When deleting an object(page, image, document or snippet), the confirmation screen now provides a summary of where the object is used, allowing users to see the effect that deletion will have elsewhere on the site.
> [More on deleting objects](https://guide.wagtail.org/en-latest/releases/new-in-wagtail-5-0/#object-usage-information-on-deleting-objects) 

This worked well, I was able to delete multiple pages and it gave me a summary of deletion.

### Multi-select deletion of pages
<img width="1256" alt="Screenshot 2024-01-26 at 12 45 29 PM" src="https://github.com/fecgov/fec-cms/assets/12799132/b583bba5-f8e2-4feb-a4eb-6396cb9affb7">

### Summary of deletion
<img width="576" alt="Screenshot 2024-01-26 at 12 45 43 PM" src="https://github.com/fecgov/fec-cms/assets/12799132/877785c2-26c6-4809-a21d-8a1e787ec0cc">

### Confirmation of deletion
<img width="263" alt="Screenshot 2024-01-26 at 12 45 54 PM" src="https://github.com/fecgov/fec-cms/assets/12799132/ffb37449-1951-458b-9c08-87d1c395a1ce">

**Comment by patphongs** [comment]
Oig landing page - Able to create a new OIG landing page and edit the existing one.
Press landing page - Able to create a new Press landing page and edit the existing one.
Press release page - Able to edit existing press releases. I could also navigate to the "News and updates" --> "Press releases" section in the Wagtail admin. Then when I clicked "Add press release page  ( as child of /updates )", it pulled up the press release template to create a new press release.
Record page - Able to edit existing record articles. I could also navigate to the "News and updates" --> "Press releases" section in the Wagtail admin. Then when I clicked "Add record page  ( as child of /updates )", it pulled up the record page template to create a new record page article.
Reports landing page - I am able to edit the existing reports landing page. But I am not able to create a new reports landing page. This also occurs using the older version of Wagtail too. I think we designed it to only be able to create one on the site, so we don't allow multiple. Server error produces the following error:

```
13:03:53.121: [APP/PROC/WEB.0] raise ValidationError('Only one {0} allowed'.format(self.__name__))
13:03:53.121: [APP/PROC/WEB.0] AttributeError: 'ReportsLandingPage' object has no attribute '__name__'
```

**Comment by patphongs** [comment]
> When I tried to create a home page and Legal resources landing page I got this server error

Thanks @tmpayton, this is expected. I think we made it so that there can only ever be one of these types of home and legal resources landing pages. Server error produces the following:

```
13:21:37.534: [APP/PROC/WEB.0]     raise ValidationError('Only one {0} allowed'.format(self.__name__))
13:21:37.534: [APP/PROC/WEB.0] AttributeError: 'LegalResourcesLandingPage' object has no attribute '__name__'
```

```
13:23:33.866: [APP/PROC/WEB.0]     raise ValidationError('Only one {0} allowed'.format(self.__name__))
13:23:33.866: [APP/PROC/WEB.0] AttributeError: 'HomePage' object has no attribute '__name__'
```

**Comment by rfultz** [comment]
Dark mode looks good! I wish it would apply the theme as soon as I change the pull-down but that's not the case yet.
No problems changing between Light theme, Dark theme, and System default. Editing a random selection of pages was fine

**Comment by johnnyporkchops** [comment]
Page models that that extend the `UniqueModel` abstract class can only have one page created:
HomePage
ReportsLandingPage
LegalResourcesLandingPage
ServicesLandingPage

**Comment by johnnyporkchops** [comment]
> I tested on local and feature. Everything is working well for me. We do have to add
> 
> WAGTAILIMAGES_EXTENSIONS = ["gif", "jpg", "jpeg", "png", "webp", "svg"]

...the team agreed we would add this setting as needed later.

Everything else above has been tested and confirmed. Closing,
