### ISSUE TITLE
Remove "Acting" references from Dayna Brown's title

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#6038]
**What we're after:**
Remove "Acting" from Dayna's position on wagtail and transition pages. 

Pages requiring updates:
- https://www.fec.gov/about/privacy-and-security-policy/ (Done by @JonellaCulmer) 
- https://www.fec.gov/about/leadership-and-structure/fec-offices/ (Done by @JonellaCulmer) 
- https://transition.fec.gov/about/offices/DSDMA/DSDMA.shtml

Refer to this ticket for guidance on transition pages: https://github.com/fecgov/fec-cms/issues/5898 

### Related issues
- https://github.com/fecgov/fec-cms/issues/5898 

### Completion criteria
- [ ] "Acting" no longer appears

**Comment by johnnyporkchops** [comment]
The transition page has been edited:
https://transition.fec.gov/about/offices/DSDMA/DSDMA.shtml
