### ISSUE TITLE
Front end remove old public funding report files from transition 

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#6041]
### Summary

**What we're after:**
_We got another thing off of transition!_

### Related issues

- #6032 
 

### Completion criteria

- [x] These files are removed from transition and content team notified:

/info/pfund.htm
/info/appfive.htm
/info/appfour.htm
/info/apthree.htm
/info/chfive.htm
/info/chfour.htm
/info/chone.htm
/info/chthree.htm
/info/chtwo.htm
/info/content.htm

**Comment by patphongs** [comment]
These files have been deleted as requested: 

```Thu Dec 21 13:02:35 EST 2023
delete: '/info/appfive.htm'
delete: '/info/appfour.htm'
delete: '/info/apthree.htm'
delete: '/info/chfive.htm'
delete: '/info/chfour.htm'
delete: '/info/chone.htm'
delete: '/info/chthree.htm'
delete: '/info/chtwo.htm'
delete: '/info/content.htm'
delete: '/info/pfund.htm'
Finished syncing and  deleting files
```
