### ISSUE TITLE
Update admin fine calculators for 2024 with new amounts

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#6043]
### Summary

What we are after:
Once the Commission approves the new fine inflation adjustments, there will be a FR notice updating the regulations for admin fines. We'll need to update the calculator (https://www.fec.gov/legal-resources/enforcement/administrative-fines/calculating-administrative-fines/#calculating-a-fine)

Please refer to email from Rhiannon sent on 12/20/2023 to ITD Web

### Related Issues
https://github.com/fecgov/fec-cms/issues/6042
https://github.com/fecgov/fec-proxy/issues/391
https://github.com/fecgov/fec-cms/issues/2638

### Completion criteria

- [ ] Once approved, calculator is updated with the new amounts but does not go live
- [ ] Once ready, AF staff test  
- [ ] Once AF gives the go live signal: Go live with the calculator with new amounts.

**Comment by rfultz** [comment]
Closing this since its PRs have been merged
