### ISSUE TITLE
Implement new dropdown filter on receipts and disbursements datatables

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#6073]
**What we're after:**
Change out the filter been using for the line number filter on the receipts and disbursements datatables. 

**Datatable links:**
All receipts: https://www.fec.gov/data/receipts/
Disbursements: https://www.fec.gov/data/disbursements/ 

**Single-select pattern in pattern library:** 
https://fec-pattern-library.app.cloud.gov/components/detail/single-select.html

**Completion criteria:**
- [ ] Line filter now functions as a single-select option

**Designs:**
**Filter tag before:**
<img width="237" alt="Screen Shot 2023-12-27 at 2 54 33 PM" src="https://github.com/fecgov/fec-cms/assets/31663028/e05fe6a1-1fa9-4622-802a-e3cd73d40138">

**Filter tag after:**
![Screen Shot 2024-01-05 at 10 07 11 AM](https://github.com/fecgov/fec-cms/assets/31663028/d82cc638-93d0-40fb-a9d9-ed3af74f90d9)

**Dropdown without and with selection:**
![Screen Shot 2023-12-27 at 3 17 20 PM](https://github.com/fecgov/fec-cms/assets/31663028/2597791b-590f-4001-a3ab-460332dbbc14)

**Dropdown (open):**
![Screen Shot 2023-12-27 at 3 07 49 PM](https://github.com/fecgov/fec-cms/assets/31663028/b1748d5d-92f5-4c40-9c1b-45caa6aaddb3)

**Full dropdown text for receipts (moved line number and Form # added to section rows):**
![Screen Shot 2023-12-27 at 3 15 07 PM](https://github.com/fecgov/fec-cms/assets/31663028/3775c4cf-106f-4d64-ba68-88eae5978347)

**Full dropdown text for disbursements (moved line number and Form # added to section rows):**
![Screen Shot 2023-12-27 at 3 16 15 PM](https://github.com/fecgov/fec-cms/assets/31663028/25254709-5095-430f-84de-00a449e90c0c)

**Comment by johnnyporkchops** [comment]
Thanks

From: Jonella ***@***.***>
Date: Wednesday, April 3, 2024 at 8:07 AM
To: fecgov/fec-cms ***@***.***>
Cc: John Carroll ***@***.***>, Mention ***@***.***>
Subject: Re: [fecgov/fec-cms] Implement new dropdown filter on receipts and disbursements datatables (Issue #6073)

@johnnyporkchops<https://github.com/johnnyporkchops> Here's the text you requested:

Receipts line number dropdown:
Received by House or Senate committees (Form 3)
Line 11 ai: Contributions from individuals
Line 11b: Contributions from political party committees
Line 11c: Contributions from other political committees
Line 11d: Contributions from the candidate
Line 12: Transfers from authorized committees
Line 13a: Loans received from the candidate
Line 13b: All other loans
Line 14: Offsets to operating expenditures
Line 15: Other receipts
Received by Presidential committees (Form 3P)
Line 16: Federal funds
Line 17ai: Contributions from individuals
Line 17b: Contributions from political party committees
Line 17c: Contributions from other political committees
Line 17d: Contributions from the candidate
Line 18: Transfers from other authorized committees
Line 19a: Loans received from candidate
Line 19b: Other loans
Line 20a: Offsets to operating expenditures - operating
Line 20b: Offsets to operating expenditures - fundraising
Line 20c: Offsets to operating expenditures - legal and accounting
Line 21: Other receipts
Received by PACs or Party committees (Form 3X)
Line 11ai: Contributions from individuals
Line 11b: Contributions from political party committees
Line 11c: Contributions from other political committees
Line 12: Transfers from affiliated committees
Line 13: Loans received
Line 14: Loan repayments received
Line 15: Offsets to operating expenditures
Line 16: Refunds of contributions made to federal candidates and other political committees
Line 17: Other federal receipts

Disbursements line number dropdown:
Made by House or Senate committees (Form 3)
Line 17: Operating expenditures
Line 18: Transfers to other authorized committees
Line 19: Loan repayments
Line 19a: Loan repayments of loans made or guaranteed by the candidate
Line 19b: Loan repayments of all other loans
Line 20a: Refunds of contributions to individuals
Line 20b: Refunds of contributions to political party committees
Line 20c: Refunds of contributions to other political comittees
Line 21: Other disbursements
Made by Presidential committees (Form 3P)
Line 23: Operating expenditures
Line 24: Transfers to other authorized committees
LIne 25: Fundraising disbursements
Line 26: Exempt legal and accounting disbursements
Line 27a: Repayments of loans made or guaranteed by candidate
Line 27b: Other loan repayments
Line 28a: Refunds of contributions to individuals
Line 28b: Refunds of contributions to political party committees
Line 28c: Refunds of contributions to other political committees
Line 29: Other disbursements
Made by PACs or Party committees (Form 3X)
Line 21b: Other federal operating expenditures
Line 22: Transfers to affiliated/other party committees
Line 23: Contributions to federal candidates/committees and other political committes
LIne 26: Loan repayments made
Line 27: Loans made
Line 28a: Refunds of contributions made to individuals/persons other than political committees
Line 28b: Refunds of contributions to political party committees
Line 28c: Refunds of contirbutions to other political committees
Line 28d: Total contributions refunds
Line 29: Other disbursements
Line 30b: Party - Types 3 & 4 Federal Election Activity (FEA)

**Comment by johnnyporkchops** [comment]
@jonella, It is not possible to style the section headers in the select box with CSS or JS. Browsers provide very few options for changing form elements for accessibility reasons. In Chrome and Edge,`<optgroup> labels`  are greyed out by default and there is virtually no way to change this.  Firefox happens to make them bold (like the design mockup). 
https://fec-feature-cms.app.cloud.gov/data/receipts/

[PR](url)
