### ISSUE TITLE
Contributions group by Contributor state does not work

### ISSUE THREAD

**Issue by fec-jli** [fecgov/fec-cms#6079]
### Summary
On election pages, the individual contributions to candidates, by state is not working. 

Example:https://www.fec.gov/data/elections/president/2024/#individual-contributions
under section: Individual contributions to candidates
group by state return blank.

The reason is per_page=610 (default should be per_page=10)
ex api url:
https://api.open.fec.gov/v1/schedules/schedule_a/by_state/by_candidate/?api_key=DEMO_KEY&cycle=2020&candidate_id=P00014530&candidate_id=P80000722&candidate_id=P80001571&candidate_id=P00012716&candidate_id=P60007168&candidate_id=P00009621&candidate_id=P80006117&candidate_id=P00009696&candidate_id=P00009423&candidate_id=P00006486&per_page=610&election_full=true

same issue for api schedules/schedule_a/by_size/by_candidate/

### How to Reproduce
https://www.fec.gov/data/elections/president/2024/#individual-contributions

<img width="500" alt="by_state" src="https://github.com/fecgov/fec-cms/assets/24395751/4cf73007-3717-4254-a238-5daec84f9f10">

### Action items
- [ ] Fix api call /schedules/schedule_a/by_state/by_candidate/,  per_page is wrong value
- [ ] Verify api call /schedules/schedule_a/by_size/by_candidate/

### Completion criteria
- [ ] Contributions by state table is appearing correctly

**Comment by patphongs** [comment]
A per page cap was introduced for the schedule A by size, by state, and by state totals views in the API. This is causing a per page error. A new [ticket](https://github.com/fecgov/openFEC/issues/5734) has been logged to fix in the API.

**Comment by patphongs** [comment]
Closing in favor of [backend ticket to fix](https://github.com/fecgov/fec-cms/issues/6079#issuecomment-1957672699)
