### ISSUE TITLE
Office page and org chart updates

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#6086]
### Summary

**What we're after:**
We need to update this page: https://transition.fec.gov/about/offices/budget/budget.shtml

**Action items:**
- [x] Get bio and picture from the new budget director James Gerber (Content) - he will send to Jonella.
- [x] Update office pages in progress it wagtail
- [x] Update the page with the bio and picture. Use this image for an example (Front-end) (John did this, no photo yet)
- [x] Update org chart to remove Kevin Deeley (Dorothy did this.)
- [x] Remove Kevin from office page on transition (Front-end)  (John did this)

![image](https://github.com/fecgov/fec-cms/assets/24437369/7a737789-30a4-4aff-9896-99fe3e783567)

**Comment by JonellaCulmer** [comment]
**James Gerber bio:** 
James Gerber serves as the FEC's Budget Director. In this position, he oversees the development of the FEC budget and ensures all requirements and obligations are funded. Prior to joining the FEC, James served as the Budget Officer for the Selective Service System. In this role, he also directed the development and execution of the agency’s budget, and had additional duties overseeing contracting and logistics. He previously served as a budget analyst with the Department of the Interior and with Navy’s Judge Advocate General. James holds a Bachelor’s degree in Asian Studies from Washington State University and a Master’s degree in Management from the Naval Postgraduate School.


There is no photo at this time. Once I get it I will add to the new pages but we don't need to add it to transition.

**Comment by JonellaCulmer** [comment]
This is done.
