### ISSUE TITLE
Handle "Reserved" regulations

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#6089]
### Summary

**What we're after:**
_Figure out how to pull a list of all “reserved” regulations to create redirects. Also determine how to maintain this list._

**Related tickets**
https://github.com/fecgov/fec-cms/issues/6095

**Action items:**
- [x] Find a way to query the eRegs dataset for any regulation numbers that are "Reserved"
- [x] Make a [list](https://docs.google.com/spreadsheets/d/175Xk3SzzIQ4yBST_JbBelwYAv-XVLgLT8RnbH6y3Wys/edit#gid=0) of redirects for "Reserved" regulation numbers
- [x] Determine how to maintain a list of the "Reserved" items, 
- [x] Ask OGC in case they maintain a list of reserved
- [x] Create draft PR of redirects (https://github.com/fecgov/fec-proxy/pull/400)

### Completion criteria
- [x] Redirects for reserved regulations are implemented

**Comment by johnnyporkchops** [comment]
Here is a utility you can use to list reserved regulations and compare across dates (Unzip and open the file in a browser)
[title_11_reserved_all_redirects_compare.html.zip](https://github.com/fecgov/fec-cms/files/14412488/title_11_reserved_all_redirects_compare.html.zip)

 It is still unclear from the issue description and further discussions exactly how we want to use this list to redirect regulations and where we want to redirect to.

**Comment by patphongs** [comment]
To test the reserved regulations, I created a draft [PR](https://github.com/fecgov/fec-proxy/pull/400/files) for broader redirects and redirects for reserved regulations. It's currently deployed to stage for testing.

### Examples
- [MUR](https://stage.fec.gov/data/legal/matter-under-review/4214/) with reserved regulations linked

**Comment by patphongs** [comment]
An inventory of every reserved link has been documented in this [spreadsheet](https://docs.google.com/spreadsheets/d/175Xk3SzzIQ4yBST_JbBelwYAv-XVLgLT8RnbH6y3Wys/edit#gid=0) 🔒.

**Comment by patphongs** [comment]
@dorothyyeager We also have the option to redirecting to eCFR's reserved regulations page rather than our own. The advantage of that would be that it would retain any titles pertain to it if there were any. Take a look at the eCFR equivalent reserved link in this [spreadsheet](https://docs.google.com/spreadsheets/d/175Xk3SzzIQ4yBST_JbBelwYAv-XVLgLT8RnbH6y3Wys/edit#gid=0) 🔒.
