### ISSUE TITLE
Deploy Wagtail V5

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#6094]
### What we’re after
In order to deploy wagtail v5, we need to do the following in action items. 

### Related ticket(s)
- [x] https://github.com/fecgov/fec-cms/issues/6026

### Action item(s)
- [x] Remove update index, slack convo for reference: https://fecgov.slack.com/archives/C3W9XBBJL/p1706041554440749
- [x] Ensure QA has passed
- [x] Any needed fixes are completed
- [ ] Doublecheck stage env once release has been cut
- [ ] Make backup of production CMS database before deploy
- [ ] Confirm vulnerabilities have been handled with this upgrade, including [#5930](https://github.com/fecgov/fec-cms/issues/5930) and [#5972](https://github.com/fecgov/fec-cms/issues/5972)

### Completion criteria
- [ ] Wagtail v5 is prepped for launch

**Comment by patphongs** [comment]
update_index command has been removed in this [commit](https://github.com/fecgov/fec-cms/pull/6020/commits/1c0b488550aa0bccde69ce9f7cadd8bd519040ca).

**Comment by pkfec** [comment]
Wagtail 5.2 was deployed to production on Feb 6th, 2024 (PI 23 innovation release). Closing this issue
