### ISSUE TITLE
Draft a new reserved CMS page for eCFR migration purposes

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#6095]
### Summary

**What we're after:**
_We are making sure that the regulations on our website are the current ones._

### Related issues

- #6089 
 
### Completion criteria

- [ ] Google doc drafted that will be used for content on a future Wagtail page for redirects for reserved regulations that explains what "Reserved" means and possibly offers more info and/or links.

### Action items

- [ ] Draft a definition for "Reserved".  [here](https://www.archives.gov/federal-register/cfr/about.html#:~:text=An%20agency%20uses%20%22%5BReserved%5D,a%20printing%20or%20computer%20error) On [our stage](https://stage.fec.gov/legal-resources/regulations/reserved-regulation/)
- [ ] Tell users where to go and maybe link to E&J landing (Not linking to specific section in E&J)
- [ ] Research other useful resources to provide on the page
- [ ] Draft-language review by OGC
- [ ] Alert frontend team that the language has been drafted

### Future work

_Other future work that may be needed following this issue's completion._

**Comment by patphongs** [comment]
@dorothyyeager I'm debating whether or not to create our own reserved page now. Before, I thought that eCFR did not have a reserved page for each reserved regulation, but then I found out that they did. See my comment here for more info and the [spreadsheet](https://github.com/fecgov/fec-cms/issues/6089) 🔒. So this ticket may not be necessary? We can unpack more during refinement.

**Comment by patphongs** [comment]
In content sync refinement today, we decided to link to the eCFR's reserved regulation page instead so that it's a better flow for the user and to retain the associated titles and headings for those reserved regulations. cc @dorothyyeager @JonellaCulmer @AmyKort
