### ISSUE TITLE
Upgrade prod db engine

### ISSUE THREAD

**Issue by cnlucas** [fecgov/fec-cms#6101]
**What we're after:**
Cloud.gov needs us to upgrade our CMS db instance from PG 11 to PG 12, as they are retiring PG 11. 

Refer to Cloud.gov email for more information.

**Completion criteria:**
- [ ] We are upgraded to PG ~12~ 15

### Tech steps or considerations (optional)
- [ ] Confirm with cloud.gov our maintenance window by Feb 14th 
- [ ] Upgrade the db instance by Feb 29th

**Comment by pkfec** [comment]
PostgreSQL database service in our lower environments is currently on version PG 15.x. 
<img width="476" alt="Screen Shot 2024-02-14 at 5 15 48 PM" src="https://github.com/fecgov/fec-cms/assets/11650355/56418ba8-88f1-4833-9f29-4ff2d42c676a">

**Comment by pkfec** [comment]
Steps i followed to upgrade CMS postgres DB from PG 11 to PG 15

1. SSH into existing `fec-cms-prod`  rds service
2. take pg_dump from `fec-cms-prod` service
3. create new service `fec-cms-prod-new`
4. SSH and restore cms pg dump on to the new `fec-cms-prod-new` service
5. unbind cms app from existing `fec-cms-prod` service
6. rename existing service from `fec-cms-prod` to `fec-cms-prod-old-20240214`
7. bind cms app to the new service `fec-cms-prod-new`
8. rename new service from `fec-cms-prod-new` to `fec-cms-prod` (rename new service to match with the name given in manifest.yml file)
9. on circleci rerun the latest master build

**Comment by pkfec** [comment]
he CMS database was updated to PostgreSQL 15 yesterday evening, and the website appears to be functioning properly

**Comment by pkfec** [comment]
CMS database in Prod environment was updated to PostgreSQL 15 yesterday evening, and the website appears to be functioning properly
