### ISSUE TITLE
Ensure tables for presidential spending and coordinated party expenditure limits comply with accessibility rules

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#6107]
### Summary

**What we're after:**
To make our tables on these pages in compliance with accessibility rules. 

These tables and data included in the tables are currently in an html block on the wagtail page. This ticket is about migrating the information included in these tables to a table block in wagtail for these pages. 

### Related issues

- #6055
- #6056

## Action Items 
- [x] Copy table from browser into wagtail tables 
- [x] Make sure the table data undergoes QA testing to ensure data is still accurate
- [ ] Use comparison or diff tool to compare data 

### Completion criteria

To change out the HTML code for the Wagtail tables 

- [x] https://www.fec.gov/help-candidates-and-committees/understanding-public-funding-presidential-elections/presidential-spending-limits/
- [x] https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/coordinated-party-expenditures/coordinated-party-expenditure-limits/
- [x] Reach out to front end for help

**Comment by djgarr** [comment]
Updated the ticket information for clarity
