### ISSUE TITLE
Create accessibility statement page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#6113]
**What we're after:**
Create new custom wagtail page for accessibility statement.

**Related tickets:**
- https://github.com/fecgov/fec-cms/issues/6091
- #6114 
- #6115 

**Completion criteria:**
- [x] Accessibility statement is published on fec.gov

**Comment by tmpayton** [comment]
Meeting to discuss accessibility statement has not happened yet

**Comment by JonellaCulmer** [comment]
https://www.fec.gov/accessibility-statement/
