### ISSUE TITLE
MUR cannot be found through Latest updates search

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#6118]
**What we're after:**
A keyword search for "MUR 6535" yields no results through the Latest updates search. Other keywords return results as expected. A result for a weekly digest should come up: **Weekly Digest for the week of December 14-18, 2015**

Link: https://www.fec.gov/updates/?update_type=weekly-digest&search=MUR+6535

**Completion criteria:**
- [ ] Fix has been identified and implemented, MUR 6535 is successfully found through Latest updates keyword search

**Comment by patphongs** [comment]
After researching the issue, it appears that the items the news and meeting items that were just imported HTML into Wagtail are not being searched. These include imported HTML pages for record articles, press releases, weekly digests, and commission meetings. We need to figure out a way to have the Wagtail search feature also search those HTML content types. These are older news and meeting items from the classic site.

**Comment by johnnyporkchops** [comment]
According to this older post, `index.SearchField('body')` will not search the body in a queryset for a subclassed page, only in a queryset for the parent class. `DigestPage` is a subclass of `ContentPage`. Our queryset for /Updates  is  `digests = DigestPage.objects.live()`.  I could not find any update or change to this in more recent version docs.
https://stackoverflow.com/a/63917472/5616606

**Comment by johnnyporkchops** [comment]
This ticket is for the /Updates search, but for followup work we can resolve this for meetings too. Unlike the updates, we could probably target the alternate search by meeting-date. The last open MeetingPage that has `imported_html` is April 27, 2017.
