### ISSUE TITLE
Design new Regulations search

### ISSUE THREAD

**Issue by cnlucas** [fecgov/fec-cms#6127]
### Summary

_Now that the eCFR research has completed, the design work for this new section of the site needs to be completed_

**Related tickets:**
- https://github.com/fecgov/fec-eregs/issues/826
- https://github.com/fecgov/fec-cms/issues/6095
- https://github.com/fecgov/fec-cms/issues/5978

**Action items:**
- [x] Designs are mocked up
- [x] Designs are shared out for review with PMs and team
- [x] Followup tickets are created

### Completion Criteria
- [x] Design work is completed for new regulations section of our website

**Comment by AmyKort** [comment]
Thank you for sharing these designs @JonellaCulmer . This looks really good to me, and I don't have additional comments at this point. When we get closer to completing this we might think about making sure the description of the timeline's limitations describes the two ways to review the E&Js in the same order that the buttons are presented.

**Comment by JonellaCulmer** [comment]
Closing in favor of usability testing ticket: https://github.com/fecgov/fec-cms/issues/6161
