### ISSUE TITLE
[Snyk:Medium] es5-ext Regular Expression Denial of Service (ReDoS) (due on 05/23/2024)

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-cms#6132]
Affected versions of this package are vulnerable to Regular Expression Denial of Service (ReDoS) when processing a malicious function name with the copy() function.### Overview

https://app.snyk.io/org/fecgov/project/2a97cddb-4b62-4d54-b18f-3b85d55a5e10#issue-SNYK-JS-ES5EXT-6095076

### Introduced through: 
Introduced through: fec-cms@1.0.0 › es6-weak-map@2.0.1 › es5-ext@0.10.52
Introduced through: fec-cms@1.0.0 › es6-weak-map@2.0.1 › d@0.1.1 › es5-ext@0.10.52
Introduced through: fec-cms@1.0.0 › es6-weak-map@2.0.1 › es6-iterator@2.0.3 › es5-ext@0.10.52

### Remediation:
Your dependencies are out of date, otherwise you would be using a newer es5-ext than es5-ext@0.10.52. Try relocking your lockfile or deleting node_modules. If the problem persists, one of your dependencies may be bundling outdated modules.

### Considerations
- [ ] Your dependencies are out of date, otherwise you would be using a newer es5-ext than es5-ext@0.10.52. Try relocking your lockfile or deleting node_modules. If the problem persists, one of your dependencies may be bundling outdated modules.

### Completion criteria:**
- [ ] Determine best next steps - issue will go away soon

**Comment by rfultz** [comment]
This should become a non-issue when the ES6/ESM/Webpack work is merged because `es6-weak-map` will go away
