### ISSUE TITLE
Modify OIG landing page to include new image and Oversight.gov PDF link

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#6137]
**What we're after:**
We need to modify the OIG landing page to include a link to Oversight.gov open recommendations PDF. We also need to modify the layout to accommodate both a link and an image to provide context.

Link: https://www.oversight.gov/recommendations/pdf-version?field_publication_date%5Bdate%5D=&field_publication_date_1%5Bdate%5D=&field_submitting_oig%5Bdate%5D=376&field_submitt_oig_report_number=&search_api_views_fulltext=&field_rec_number=&field_significant_rec=All&in_priority_queue=All&

**Action items:**
- [x] Mockup updated layout to include image and link to Oversight.gov
- [x] OIG approves updated layout
- [x] Implementation tickets are opened as necessary

### Completion criteria
- [x] Updated layout design is approved

**Comment by JonellaCulmer** [comment]
@AmyKort @patphongs Initial mockup that allows for link to the list of open recommendations on oversight.gov. Let me know if you have any initial thoughts. If you are okay with this mockup I will pass along to OIG for their review. 

![Image](https://github.com/fecgov/fec-cms/assets/31663028/a2d884d4-8869-4828-b767-5253c5b55efe)

**Comment by AmyKort** [comment]
Looks great to me. Thank you @JonellaCulmer !

**Comment by patphongs** [comment]
All good @JonellaCulmer, please go ahead and send it along to OIG for review
