### ISSUE TITLE
Update robots.txt

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#6145]
### Summary

**What we're after:**
_We'll want to update our robots.txt to disallow legal search results pages._

How Google handles robots.txt files: https://developers.google.com/search/docs/crawling-indexing/robots/robots_txt

Add the following for all search engines:

```
/data/legal/search/advisory-opinions/?*
/data/legal/search/murs/?*
```

### Completion criteria

- [ ] additional robots.txt disallow parameters are added

**Comment by rfultz** [comment]
@patphongs our robots.txt already includes `Disallow: /data/legal/search/?*`

Could we just add `Disallow: /data/legal/search/*`?

Would `Disallow: /data/legal/search/*` also cover `/data/legal/search/?*`?

**Comment by lbeaufort** [comment]
@patphongs what about `/data/receipts/?` and `/data/disbursements/?`?

**Comment by cnlucas** [comment]
Hotfix was merged Friday
