### ISSUE TITLE
Quality Control: Remove "menu option 0" from Wagtail pages

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#6148]
### Summary

**What we're after:**
In updating the office pages, we learned that the phone system at the FEC no longer does a menu option 0 then enter the extension. We need to remove menu option 0

### Related issues

- #6086 

### Completion criteria

- [x] Search ran to identify any pages with "menu option 0" or "option 0" or "menu option" to identify where an edit may be needed
- - [x] https://www.fec.gov/office-inspector-general/how-submit-a-complaint-with-the-fec-oig/
- - [x] https://www.fec.gov/help-candidates-and-committees/understanding-public-funding-presidential-elections/receiving-public-funding-grant-for-general-election/ "(extension 1200)"
- - [x] https://www.fec.gov/about/leadership-and-structure/fec-offices/communication-offices/ "(extension)"
- - [x] https://www.fec.gov/about/leadership-and-structure/fec-offices/compliance-offices/ "(extension)"
- [x] Needed edits made.

**Comment by djgarr** [comment]
Offices reached. Edits made. Ticket closed
