### ISSUE TITLE
Pull analytics for ERegs and Regulations search

### ISSUE THREAD

**Issue by johnnyporkchops** [fecgov/fec-cms#6152]
### Summary
What we're after:
Pull analytics for ERegs and Regulations search, compare month over month internal versus external traffic to the feature to the greatest extent possible.

Main URLs:
https://www.fec.gov/regulations
https://www.fec.gov/data/legal/search/regulations/?search=&search_type=regulations

### Completion criteria
- Analytics research compiled and documented in this ticket ([The slack post with the report link](https://fecgov.slack.com/archives/C02K8UBC0MR/p1712854004840369))

### Future work
 Schedule followup discussion with website team members to review data and discuss next steps

**Comment by rfultz** [comment]
Closing this because the report has been made, and now linked from a Slack post
