### ISSUE TITLE
Quality Control: Update references to superseded AOs or policy statement

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#6162]
### Summary

**What we're after:**
_As a user doing legal research, I want to make sure I am not using outdated citations._

The technological modernization rules superseded several AOs and one interpretive rule. We've already dealt with the interpretive rule in the guidance search and on the policy page. We need to go through H4CC and make sure the AOs are removed as references in the citations portion of a page. If that policy statement is cited anywhere, we need to make sure we add the caveat language OGC gave us.

Superseded AOs: 

AO 1995-34
 - 0 H4CC pages reference this AO

AO 1999-22 
 - [x] https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/types-contributions/
 - [x] https://www.fec.gov/help-candidates-and-committees/taking-receipts-ssf/types-contributions-to-ssf/
 
AO 2012-07
 - 0 H4CC pages reference this AO

AO 2012-17
 - [x] https://www.fec.gov/help-candidates-and-committees/keeping-political-party-records/recording-receipts/
 - [x] https://www.fec.gov/help-candidates-and-committees/keeping-ssf-records/recording-receipts/

Superseded 2011 Interpretive rule on electronic contributor redesignations
 - [x] Record article linked on https://www.fec.gov/help-candidates-and-committees/making-disbursements-pac/how-handle-excessive-contributions-made-nonconnected-pac/
 - [x] Record article linked on https://www.fec.gov/help-candidates-and-committees/making-disbursements-ssf-or-connected-organization/handling-excessive-contributions-made-by-ssf/ and listed in citations
 - [x] Record article linked on https://www.fec.gov/help-candidates-and-committees/making-disbursements-pac/designation-contributions-made-nonconnected-pac/
 - [x] FR notice linked in citations https://www.fec.gov/help-candidates-and-committees/candidate-taking-receipts/remedying-excessive-contribution/

### Related issues

- #6128 

### Completion criteria

- [x] Search is done via global search to identify any pages that contain references to these items:
- [x] Pages are updated to take out the AOs
- [x] Any reference to the older interpretive rule is updated by adding "To the extent that this interpretive rule’s
approach to a ‘‘signature’’ could be construed to conflict with the updated definition of ‘‘signature,’’ it is superseded."

### Tech steps or considerations (optional)

- How do the AOs get updated in the legal search to be flagged as superseded?

**Comment by djgarr** [comment]
Information removed from the pages noted above. Updates published. Ticket closed
