### ISSUE TITLE
Handle global legal search for regulations

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#6167]
### What we're after:
_eRegulations will be redirecting to the eCFR. Therefore, we will need to update the global legal search to pull results from the eCFR instead of from our own API._

We may want to consider using the eCFR API to return the results for the regulations in our global legal search. Refer to the [eCFR API text search](https://github.com/fecgov/fec-eregs/issues/826#issuecomment-1939134277) research for more information.

<img width="1045" alt="Screenshot 2024-03-20 at 8 04 13 PM" src="https://github.com/fecgov/fec-cms/assets/12799132/38a2bb88-9d58-43a9-82ea-5fa7bddf04b2">

### Related issues
- https://github.com/fecgov/fec-eregs/issues/826#issuecomment-1939134277
- https://github.com/fecgov/fec-cms/issues/6161

### Completion criteria
- [x] API call is updated to the new eCFR search 
- [x] Results structure is updated to match eCFR capabilities 

### Tech steps or considerations
- [x] Pull results from eCFR API instead of from out own API 
- [x] Understand the mapping of the results fields between our openFEC API and the new eCFR API - need to display results in a way that makes sense. 
- [x] Handle boolean search operators for regulations. Operators are different for "and" and "or" conditions using the eCFR API.
- [x] Figure out pagination. Pagination is not required in eCFR API.
- [x] There are two different pages that contain results: global legal search (advisory opinions, MURs, statutes, and regulations) and individual regulations search result page (must handle pagination and display of all results).  

### Future work
- [ ] Make improvements to the eRegs search results display based on user feedback and research.
- [ ] Make a design ticket to fix example text, keyword search tooltip, and boolean search pop-up box

**Comment by patphongs** [comment]
@JonellaCulmer I'm trying to resolve what to do when handling the boolean search modal for regulations. Operators are different for `and` and `or` operators in the eCFR API. Also, when it concatenates the boolean search terms together, it's slightly different when enclosing parentheses too.

### eCFR API operators 
| Symbol | Meaning | Usage |
| ------- | ------- | ------- |
| `\|` | or | If you wish to search for either one word or another, use a `\|` character between terms. |
| `Space` | and |  If you enter more than one search term, your results will include only results that match both terms. |
| `“ ”` | exact phrase | If you are searching for the exact phrase, enclose it in quotes. |
| `-` | but not | If you wish to exclude sections that match a certain term, use a “-” for negation. |

Usage was found in the eCFR [docs](https://www.ecfr.gov/reader-aids/using-ecfr/navigating-to-content-of-interest#understanding_search_results).

### Design problem
I was able to account for the operator usage change specifically in the regulations search results page. Although there may be a better way to explain how to use the and operator?

<img width="794" alt="Screenshot 2024-04-09 at 8 58 47 PM" src="https://github.com/fecgov/fec-cms/assets/12799132/a4e1573f-1710-4d0a-92e2-0c81b3bc68bc">

Since boolean operator usage differs between our API and the eCFR's API, we also have to explain the difference when using the boolean global search. I'm not sure how the interaction should work, since you have to pass different operators depending on if you're searching regulations or everything else. Should we just note that if you want to search regulations boolean search, direct them to the regulations search page?

<img width="461" alt="Screenshot 2024-04-09 at 8 57 25 PM" src="https://github.com/fecgov/fec-cms/assets/12799132/26e8bdca-e15b-4bb1-9a7b-5a9478b50c34">

**Comment by JonellaCulmer** [comment]
@patphongs Do we want to open a separate ticket for the "search across all legal resources" boolean search. I have a couple ideas that I can continue to think through. 
- Only show boolean options that apply to all legal resources
- Remove boolean options and rely only on keyword

Not sure at this point which might be better and I'm sure there are other options I haven't thought of yet.

**Comment by patphongs** [comment]
> Re: eCFR boolean operators problem

The eCFR boolean operators problem is no longer an issue. I figured out a way to handle the operators on the backend query, so that it gets transformed there, but will remain visually the same on the front end. So you'll be able to do the search seamlessly on the global legal search and on the individual regulations search.
