### ISSUE TITLE
QA redirects for eRegs related links to eCFR

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#6169]
### Summary

**What we're after:**
_eRegulations will be redirecting to the eCFR and we need to check various pages on our website to make sure the redirects are working as expected._

[Spreadsheet](https://docs.google.com/spreadsheets/d/175Xk3SzzIQ4yBST_JbBelwYAv-XVLgLT8RnbH6y3Wys/edit#gid=0) of all eRegs redirects and also reserved regulations redirects

### QA list
- [x] MUR pages(Jonella)
- [x] AO pages (Jonella)
- [x] Help for candidates and committees pages (Jonella)
- [x] Legal resources (Jonella)
- [x] Introduction to campaign finance and elections  (Dorothy)

### Related issues

_List any relevant related issue(s)_

- https://github.com/fecgov/fec-proxy/issues/393

### Completion criteria

- [ ] Each item in the QA list is spot checked 
- [ ] Document any issues in this ticket

**Comment by JonellaCulmer** [comment]
@patphongs I spot-checked MURs and AOs. I didn't come across anything in MURs that redirected to eCFR. In AOs, there were some that did and others that didn't redirect. For example in AO 2024-02, 100.26 redirected to eCFR but nothing else did.

**Comment by JonellaCulmer** [comment]
@patphongs I spotted checked MURs and AOs after you redeployed this morning, as well as links in the spreadsheet and everything redirected as expected. 

I've checked off MURs and AOs and will reassign to another tester.

**Comment by dorothyyeager** [comment]
@patphongs For the Introduction to campaign finance section, the only page with legal citations is https://stage.fec.gov/introduction-campaign-finance/understanding-ways-support-federal-candidates/presidential-elections/public-funding-presidential-elections/#legal-citations. Those citations are not redirecting to eCFR. 

On the spreadsheet, I spot checked a few links. I noticed redirects to the table of contents for an entire part are not working.

For example, the redirect of https://www.fec.gov/regulations/9012 to https://www.ecfr.gov/current/title-11/chapter-I/subchapter-E/part-9012?toc=1 redirects to Part 9012 in eregs but doesn't show any of the regs in part 9012. This seemed to be true for all the redirects ending in ?toc=1 that I tested.

**Comment by patphongs** [comment]
> Those citations are not redirecting to eCFR.

Thanks @dorothyyeager, it's because the links on the page were absolute URLs to our production site and the redirects are only working with stage URLs currently. So I went ahead into the page in our stage environment and modified the legal citation links to be relative to stage. Now the redirects should work. 

> I noticed redirects to the table of contents for an entire part are not working.

I don't think I'm following here. When I look at the table of contents in eCFR, I can see all of the regs in part 9012 listed. Am I missing something?

<img width="814" alt="Screenshot 2024-04-04 at 9 47 57 AM" src="https://github.com/fecgov/fec-cms/assets/12799132/a56beb14-b0bc-4e5a-92a4-890409540097">

**Comment by patphongs** [comment]
@dorothyyeager I also noticed that on the public funding of presidential elections page, the legal citations sometimes reference part ranges and then just link to the homepage of the regulations site. That doesn't make sense to me. Shouldn't each part be a separate link. Meaning, shouldn't each part in the range be in the list? I.e. 11 CFR 9001, 11 CFR 9002, 11 CFR 9003, 11 CFR 9004, 11 CFR 9005, 11 CFR 9006, 11 CFR 9007 

<img width="383" alt="Screenshot 2024-04-04 at 9 49 55 AM" src="https://github.com/fecgov/fec-cms/assets/12799132/9305a72a-f757-4273-93fd-25d5f5f294e2">

**Comment by dorothyyeager** [comment]
Talked with @patphongs and she demo'ed how the redirect is now working that I flagged in my comment above.

As for the page in the comment right above, the easiest solution will be just to directly link eCFR so I'll take care of that today.

**Comment by JonellaCulmer** [comment]
@patphongs The regs on this page did not appear to be working. https://stage.fec.gov/help-candidates-and-committees/candidate-taking-receipts/recounts-and-contested-elections/

AOs under Legal Reources seem to be redirecting correctly.

**Comment by patphongs** [comment]
> The regs on this page did not appear to be working. https://stage.fec.gov/help-candidates-and-committees/candidate-taking-receipts/recounts-and-contested-elections/

Thanks @JonellaCulmer, the URLs for legal citations on this page were not redirecting because it was hardcoded to using production links. If you copy the link URL and change `www` to `stage`, you'll see that it redirects. Ex: https://www.fec.gov/regulations/100-91/CURRENT#100-91 --> https://stage.fec.gov/regulations/100-91/CURRENT#100-91

**Comment by JonellaCulmer** [comment]
PR has been merged, so closing.
