### ISSUE TITLE
Add "Alert/informational" panel to the Resource template in Wagtail (to the top part)

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#6176]
### Summary

**What we're after:**
In preparation for changes to the page on Requests for Legal Consideration, we need the ability to have an "alert/informational" panel in the heading on the resource page template.

### Related issues

_List any relevant related issue(s)_

- #6163 

### Completion criteria

- [ ] Resource page template modified to add "alert/informational message panel" (screenshot under Tech steps)

### Tech steps or considerations (optional)

Screenshot of the kind of panel we want
![Screenshot 2024-04-02 at 3 29 45 PM](https://github.com/fecgov/fec-cms/assets/24437369/d04b9a99-c4eb-4aac-8eeb-70dc833e2887)

**Comment by johnnyporkchops** [comment]
This should just add the option for the page editor to include an html block above the intro so it can be used for any kind of alert or message.
