### ISSUE TITLE
Update OIG landing page

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#6178]
**What we're after:**
Modify OIG landing page to accommodate image and link to external page. 

Link: https://www.oversight.gov/recommendations/pdf-version?field_publication_date%5Bdate%5D=&field_publication_date_1%5Bdate%5D=&field_submitting_oig%5Bdate%5D=376&field_submitt_oig_report_number=&search_api_views_fulltext=&field_rec_number=&field_significant_rec=All&in_priority_queue=All&

@JonellaCulmer can send image to front-end team member who picks up the ticket (Posted in #design-research channel)

**Related issues:**
- https://github.com/fecgov/fec-cms/issues/6137

**Completion criteria:**
- [ ] OIG landing page now matches design mockup

**Design:**

![Image](https://github.com/fecgov/fec-cms/assets/31663028/0403d7a6-707e-4a48-803f-bd4ffc5582bf)

**Comment by rfultz** [comment]
@JonellaCulmer I have a draft saved for this. Unfortunately, we can't remove the background color without a code/repo change, too—it's in the stylesheets and template and not just a change in the content editor.

Draft:
![Image](https://github.com/fecgov/fec-cms/assets/26720877/44eda1a4-d352-4796-ae32-7c712043093d)
