### ISSUE TITLE
Build national party account receipts datatable

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#6179]
### What we're after
Build out the National party account receipts datatable and update the raising browse data page to include the new datatable.

### Related issues
- #6112 
- https://github.com/fecgov/fec-cms/issues/6180
- https://github.com/fecgov/fec-cms/issues/6181
https://github.com/fecgov/fec-cms/issues/6182

### Completion criteria
- [ ] National party account receipts datatable is available and accessible from the raising browse data page

### Designs
![Screenshot 2024-04-24 at 2 08 14 PM](https://github.com/fecgov/fec-cms/assets/31663028/83e6ce79-dc34-4e95-8927-6ae086e23796)

![Screenshot 2024-04-02 at 3 38 30 PM](https://github.com/fecgov/fec-cms/assets/31663028/3cd1527f-7b2e-40f1-931c-e0833df5898b)

**Comment by rfultz** [comment]
@JonellaCulmer have we listed somewhere what the page URLs should be—an abbreviation or something unwieldy like `/data/national-party-accounts-receipts/`?

**Comment by JonellaCulmer** [comment]
@rfultz No, thanks for asking. I don't have a huge preference for the name. 
`/data/national-party-account-receipts` (without an s on account) should be good. And a similar name for disbursements, I can put that in the ticket once we confirm here. 

@patphongs @PaulClark2 @bmathesonFEC Let us know if you have any preferences other than that.
