### ISSUE TITLE
Design FE changes to display a max of 10

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#6186]
Adding 10 candidate cap will change the front-end [here](https://www.fec.gov/data/elections/president/2024/)

We should deactivate the more section on both by contribution state and by contribution size once ten candidates are selected
and add language that explains we won't support more than 10 candidates 

Language: 
**CANDIDATES TO COMPARE (LISTED BY AMOUNT RAISED):**
_Limit 10 candidates_

![Image](https://github.com/fecgov/fec-cms/assets/66386084/c58bb043-bd18-4017-bfa9-dbe5e0a7f2b7)

Consider changing the results per page

Completion Criteria
- [ ] FE ticket is created, design is finished

**Comment by JonellaCulmer** [comment]
@patphongs Here's my updated mockup of the filtering portion of the individual contributions - contributor state feature. 
It shows any additional candidates, beyond ten as deactivated, the dropdown filter is also deactivated. Once a candidate, currently selected, is unchecked, the dropdown is activated as well as any candidates in the list. 

Currently, any candidates from the original set of 10 cannot be removed. I don't mind maintaining that functionality, as well as the functionality if all candidates are deselected. Any candidates in addition to the original 10 are removable and we can  keep that functionality as well. Let me know if you have any questions or would like to discuss further. 

<img width="802" alt="Screenshot 2024-04-10 at 10 18 10 AM" src="https://github.com/fecgov/fec-cms/assets/31663028/79fb9ba0-b961-49a6-9ea9-6bdbb7a07a48">

**Comment by patphongs** [comment]
Thanks @JonellaCulmer, I can't really think of any problems we may come across with the design right now. That may change during development. But conceptually, the direction is good.
