### ISSUE TITLE
Take down office pages from the transition site

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#6187]
### Summary

**What we're after:**
_We are finally getting the last few pages off of transition! The pages in this ticket have been migrated to FEC.gov and their transition versions have been redirected. They can be deleted._

### Related issues

[_List any relevant related issue(s)_

- https://github.com/fecgov/fec-proxy/issues/398

### Completion criteria

- [x] These pages are deleted from transition

 /about/offices/adm/admin.shtml
/about/offices/adr/adr.shtml
/about/offices/audit/audit.shtml
/about/offices/budget/budget.shtml
/about/offices/CCO/CCO.shtml
/about/offices/CDEAO/CDEAO.shtml
/about/offices/CFO/CFO.shtml
/about/offices/CIO/CIO.shtml
/about/offices/cong_affairs/cong_affairs.shtml
/about/offices/DSDMA/DSDMA.shtml
/about/offices/finance/finance.shtml
/about/offices/finance/procurement.shtml
/about/offices/hr/hr.shtml
/about/offices/info/info.shtml
/about/offices/oar/oar.shtml
/about/offices/OGC/OGC.shtml
/about/offices/OGC/DepGC.shtml
/about/offices/OGC/DepGCLaw.shtml
/about/offices/OGC/AGC_enforcement.shtml
/about/offices/OGC/AGC_litigation.shtml
/about/offices/OGC/AGC_policy.shtml
/about/offices/OSD/OSD.shtml
/about/offices/press/press.shtml
/about/offices/rad/rad.shtml
/about/offices/secretary/secretary.shtml

**Comment by dorothyyeager** [comment]
> ### Summary
> **What we're after:** _We are finally getting the last few pages off of transition! The pages in this ticket have been migrated to FEC.gov and their transition versions have been redirected. They can be deleted._
> 
> ### Related issues
> [_List any relevant related issue(s)_
> 
> * #[issue_number]
> * #[issue_number](https://github.com/fecgov/fec-proxy/issues/398)
> 
> ### Completion criteria
> * [ ]  These pages are deleted from transition
> 
> /about/offices/adm/admin.shtml /about/offices/adr/adr.shtml /about/offices/audit/audit.shtml /about/offices/budget/budget.shtml /about/offices/CCO/CCO.shtml /about/offices/CDEAO/CDEAO.shtml /about/offices/CFO/CFO.shtml /about/offices/CIO/CIO.shtml /about/offices/cong_affairs/cong_affairs.shtml /about/offices/DSDMA/DSDMA.shtml /about/offices/finance/finance.shtml /about/offices/finance/procurement.shtml /about/offices/hr/hr.shtml /about/offices/info/info.shtml /about/offices/oar/oar.shtml /about/offices/OGC/OGC.shtml /about/offices/OGC/DepGC.shtml /about/offices/OGC/DepGCLaw.shtml /about/offices/OGC/AGC_enforcement.shtml /about/offices/OGC/AGC_litigation.shtml /about/offices/OGC/AGC_policy.shtml /about/offices/OSD/OSD.shtml /about/offices/press/press.shtml /about/offices/rad/rad.shtml /about/offices/secretary/secretary.shtml

**Comment by dorothyyeager** [comment]
Mouse slipped; this is a new issue.

**Comment by patphongs** [comment]
Deleted pages:

Tue Apr 9 10:53:11 EDT 2024
delete: '/about/offices/CCO/CCO.shtml'
delete: '/about/offices/CDEAO/CDEAO.shtml'
delete: '/about/offices/CFO/CFO.shtml'
delete: '/about/offices/CIO/CIO.shtml'
delete: '/about/offices/DSDMA/DSDMA.shtml'
delete: '/about/offices/OGC/AGC_enforcement.shtml'
delete: '/about/offices/OGC/AGC_litigation.shtml'
delete: '/about/offices/OGC/AGC_policy.shtml'
delete: '/about/offices/OGC/DepGC.shtml'
delete: '/about/offices/OGC/DepGCLaw.shtml'
delete: '/about/offices/OGC/OGC.shtml'
delete: '/about/offices/OSD/OSD.shtml'
delete: '/about/offices/adm/admin.shtml'
delete: '/about/offices/adr/adr.shtml'
delete: '/about/offices/audit/audit.shtml'
delete: '/about/offices/budget/budget.shtml'
delete: '/about/offices/cong_affairs/cong_affairs.shtml'
delete: '/about/offices/finance/finance.shtml'
delete: '/about/offices/finance/procurement.shtml'
delete: '/about/offices/hr/hr.shtml'
delete: '/about/offices/info/info.shtml'
delete: '/about/offices/oar/oar.shtml'
delete: '/about/offices/press/press.shtml'
delete: '/about/offices/rad/rad.shtml'
delete: '/about/offices/secretary/secretary.shtml'
