### ISSUE TITLE
Rethinking the bulk data page

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#6188]
### Question
Should we add links to all downloadable files to the bulk data page. 

**Files currently on bulk data page**

- All candidates (weball)
- Candidate master (cn)
- Candidate-committee linkages (ccl)
- House/Senate current campaigns (webl)
- Committee master (cm)
- PAC summary (webK)
- Contributions by individuals (indiv)
- Contributions from committees to candidates & IEs (pas2)
- Any transaction from one committee to another (oth)
- Operating expenditures (oppex)
- Electronically filed reports (.fec)
- Paper filed reports (.fec)

**Leave these where they are but add links to them on the bulk data page**

- Lobbyist bundled contributions
- Candidate summary
- Presidential candidate map exports
- New statements of candidacy
- Committee summary
- Leadership PACs and sponsors
- Lobbyist/registrant committees
- Senate unofficial electronic filings
- False and fictitious filings

**New fec.gov links**

- Indiv "delta" files
- PGdump files

**Comment by JonellaCulmer** [comment]
@PaulClark2 To avoid breaking the one-place-rule for the bulk data files, I've mocked up what the pages could look like with links to the updated bulk data page. Instead of the accordions in both places, I've kept the headers (since that's where some folks have learned to look for them and update the accordions to buttons. Let me know if you have any comments or concerns. 

Need to tell me what you think about the placement of the new accordions/sections on the bulk data page. They weren't in alphabetical order to start and instead seemed to be grouped by category. 

![Screenshot 2024-04-11 at 4 25 35 PM](https://github.com/fecgov/fec-cms/assets/31663028/e291b5d1-978d-42dd-9fdc-a32e5a16cc50)
![Screenshot 2024-04-11 at 4 26 06 PM](https://github.com/fecgov/fec-cms/assets/31663028/d7806281-7ed2-471b-b793-9a4af33165c5)

**Comment by PaulClark2** [comment]
@JonellaCulmer 

The buttons look good to me. Here's my first attempt to organize the files for the bulk data page. I'm not sure we need "candidates," "committees," "transactions" and "other." They just helped me organize the files. 

I move this to a 🔒 [sheet ](https://docs.google.com/spreadsheets/d/1a1lMYl9FWHhZozXIu8UXXRnpPl7_j9cpZ70H9Sa9wi0/edit#gid=0)🔒 

[Lobbyist bundled contributions](https://www.fec.gov/files/bulk-downloads/data.fec.gov/lobbyist_bundle.csv) seems to be a list of F3L filings, not contributions. We should consider renaming the file.

**Comment by JonellaCulmer** [comment]
@PaulClark2 Thanks, Paul. I can rearrange the mockup to match the order in the spreadsheet. I also have 3 comments in there for you. If you have a chance to take a look at those and confirm/correct my assumptions, then I can make the updated mockups.

**Comment by JonellaCulmer** [comment]
@PaulClark2 @fecjjeng @hcaofec @pkfec Here are some updated mockups for the bulk data page. This still needs a lot of work. 
Need to update/confirm the following information:
- Organization of the page into new groupings
- Explanation of what's available in each file
- Do data description pages need to be created for new files?
- Are all files with header file listed correctly?
- Should the dump files remain grouped?

![Advanced-data_bulk-updated](https://github.com/fecgov/fec-cms/assets/31663028/a0300e70-c764-40db-a0e4-c72de0959082)
![Screenshot 2024-05-02 at 8 28 27 AM](https://github.com/fecgov/fec-cms/assets/31663028/d577f45b-7cf8-48f3-a0ff-8a9accc090c5)
![Contributions by individual](https://github.com/fecgov/fec-cms/assets/31663028/d57cab2e-7168-49c7-8fb6-3da0cedd20b8)
![Postgres dump files](https://github.com/fecgov/fec-cms/assets/31663028/c4066fab-dc1e-4ea7-9fb0-9fcf51b640fe)

**Comment by fecjjeng** [comment]
Following is the description for the dump files for your reference @PaulClark2 @JonellaCulmer 

The database dump file contain information of database table structure as well as data in the table.
This set of weekly generated dump files include the data for the following tables that are frequently searched:
schedule_a
schedule_b
schedule_e
ofec_committee_history
Users can download these dump files and restore into their own postgresql database and use the data tailored to their specific needs.
The readme.txt file contains brief instruction on the content and how to restore these dump files.
NOTE:  These files are big and could take several hours to download and restore.

**Comment by PaulClark2** [comment]
@JonellaCulmer. I have these comments to add to @fecjjeng's comments. 

- File organization looks good. 
- Presidential candidate map exports looks good.
- Contributions by individuals 
    - The header file for INDIV, delete and insert is the same. So, maybe we only need one link to the file. Also, the header file link is in the accordion and not on the data dictionary page. 
    - Maybe move the text about the header file closer to the header file link? 
    - Maybe replace, "A comma delimited header file is available on this file's data dictionary page." with "The header file is comma delimited and may be used with INDIV, delete and insert. [or whatever we are officially calling these files]" 
- Postgress database dump files
    - The postgres database dump files contain data from 1975 to present from schedule a, schedule b, schedule e and committee history. In addition, you will find a readme file with basic information about how to restore the PG .dump files. Note: these files can be very large.

**Comment by JonellaCulmer** [comment]
Thank you @PaulClark2 and @fecjjeng Here are the updated mockups. If no final changes, I will move this to a front-end dev ticket. 

![Contributions by individual](https://github.com/fecgov/fec-cms/assets/31663028/27a1accf-8053-44a7-b5d5-5244c5e71f89)
![Postgres dump files](https://github.com/fecgov/fec-cms/assets/31663028/1289dfe6-2e39-4ac8-9fd5-86da5b5a2276)

**Comment by PaulClark2** [comment]
@JonellaCulmer looks good to me. I don't have any additional edits.

**Comment by JonellaCulmer** [comment]
@PaulClark2 Looks like we were missing a few things in the list of bulk data files to move over. I also noticed that the "Contributions from committees to candidates and independent expenditures" looks different from the bulk data under "Independent expenditures" accordion currently on the spending tab. Should IEs be added to the existing accordion on the bulk data page, or should we give IEs their own separate accordion and combine both IE datasets?

From the current list it appears we're missing:
- Independent expenditures (as explained above)
- Communication costs
- Electioneering communications
- New committee registrants (rename to New statements of organization to match New statements of candidacy)

![Image](https://github.com/fecgov/fec-cms/assets/31663028/3faeb1a0-f7fb-41cd-9d43-18393bc307be)


![Image](https://github.com/fecgov/fec-cms/assets/31663028/8806bc93-57d8-4a7d-8dcd-36af664f78a3)


![Image](https://github.com/fecgov/fec-cms/assets/31663028/2cb86b63-90b2-46e7-9add-5799557ef6b9)

**Comment by PaulClark2** [comment]
@JonellaCulmer "Independent expenditures" accordion currently on the spending tab should be it's own accordion. The data in this file is 24- and 48-hour reports data while the "Contributions from committees to candidates and independent expenditures" IE data is from regular monthly and quarterly reports. 

You're suggested placement of the files below makes sense to me, and I agree with you about renaming the F1 file to be consistent the current name of the F2 file. 

- Communication costs
- Electioneering communications
- New committee registrants (rename to New statements of organization to match New statements of candidacy)

**Comment by JonellaCulmer** [comment]
@PaulClark2 Updated mockups. 
If I understood you correctly, there are now two sections that reference independent expenditures. If you would like these grouped together I can rearrange the order. If you see anything else amiss, please let me know. Otherwise I will move this to a dev ticket and aim for 24.4.
![Image](https://github.com/fecgov/fec-cms/assets/31663028/7efb48ee-bbe9-4e73-9a3a-37b65d611eed)

**Comment by PaulClark2** [comment]
@JonellaCulmer For the "Independent expenditures" accordion "label/title" can we somehow indicate that its 24/48-hour report data?

**Comment by JonellaCulmer** [comment]
@PaulClark2 Yes, of course. Here's my recommendation:
- Independent expenditures (24- and 48-Hour Reports) - how it's formatted on the [dates and deadlines page](https://www.fec.gov/help-candidates-and-committees/dates-and-deadlines/)

Should we also update the label for the "Contributions from committees to candidates and independent expenditures"?
For example: 
- Contributions from committees to candidates and independent expenditures (Form 3X)

**Comment by JonellaCulmer** [comment]
@PaulClark2 For the contributions by individual and postgres files, it looks like we will need new data description pages. Are you able to assist with these?


![Image](https://github.com/fecgov/fec-cms/assets/31663028/97e90bfc-5a44-4014-b086-f4d4b6ca11ed)
![Image](https://github.com/fecgov/fec-cms/assets/31663028/a5c1cc1d-4990-4986-968c-1336197314f0)

**Comment by PaulClark2** [comment]
@JonellaCulmer 

Yes to "Independent expenditures (24- and 48-Hour Reports)"

No to "Contributions from committees to candidates and independent expenditures (Form 3X)." The IE data in this file includes processed quarterly F5 data. 

This should be the data description page for Contributions by individuals: https://www.fec.gov/campaign-finance-data/contributions-individuals-file-description/

For the dump files, we should link to the readme for the description. It explains the data and how to restore the dump file.

**Comment by JonellaCulmer** [comment]
@PaulClark2 Updated mockups to show one data description page for the "Contributions by individual" accordion and updated the Data description link to a Readme for the "postgres" accordion.



![Image](https://github.com/fecgov/fec-cms/assets/31663028/6df0cec4-8a4f-4ba9-a373-1772b0a87602)
![Image](https://github.com/fecgov/fec-cms/assets/31663028/6adaa0d2-10a7-4085-ba12-155b737e06c8)

**Comment by PaulClark2** [comment]
Thanks, @JonellaCulmer . These changes look great.

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issue: https://github.com/fecgov/fec-cms/issues/6338
