### ISSUE TITLE
Update Regulations and E&J pages for new interim final rules on FOIA

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#6217]
### Summary

What we are after:
In the coming days, the FEC will issue a FR notice of interim final rules on implementation of the FOIA improvement act.  We need to do the routine work of updating the regulations page and the E&J pages. 

The part of this where there is a comment period will be handled in the banner ticket. This ticket is for the regulations and E&J page work

[How-to guide](https://docs.google.com/document/d/1MnzKRglu6M-JBYDQKWZfKOy9Zh58qtbz/edit#heading=h.gjdgxs)

### Completion criteria
- [x] FR notice (using SERS link) is added to https://www.fec.gov/legal-resources/regulations/ under "Changes not included in 2024 printed edition"
- [x] [E&J tables in Google Drive](https://docs.google.com/spreadsheets/d/1BeKTLFc-eV5-USEdY_xmXzXPQXR41L-EOU_aD0P9C5E/edit#gid=0) are updated
- [x] FR notice (using SERS link) is added to the [2020s chronological index](https://www.fec.gov/legal-resources/regulations/explanations-and-justifications/chronological-index-2020-2029-ejs/) and to the citation indexes for the regulations mentioned in the notice.
https://www.fec.gov/legal-resources/regulations/explanations-and-justifications/citation-index-parts-1-8/ - this rulemaking affects a number of rules in Part 4. No changes to the appendix are indicated.

**Comment by pkfec** [comment]
Assign this to Issac Baker after he is added to github

**Comment by isaacjamesbaker** [comment]
From the FR Notice... My notes on edits to make 5/2/24:
(i). Revisions to 11 CFR 4.4— Availability of Records 
The Commission is amending 11 CFR 4.4(a) and (c) and adding new paragraph (h) 

(ii). Revisions to 11 CFR 4.5—Categories of Exemptions 
11 CFR 4.5(a)(5)

(iii). Revisions to 11 CFR 4.7—Requests for Records
The Commission is amending 11 CFR 4.7(c) and (h) and adding paragraph (j)

(iv). Revisions to 11 CFR 4.8—Mediation Services and Appeal of Denial The Commission is amending 11 CFR 4.8 by adding paragraph (h)

(v). Revisions to 11 CFR 4.9—Fees
The Commission is adding paragraph (a)(5) 
	New 11 CFR 4.9(a)(5)(i)
	New 11 CFR 4.9(a)(5)(ii)
	New 11 CFR 4.9(a)(5)(iii)
	Finally, new 11 CFR 4.9(a)(5)(iv)
