### ISSUE TITLE
Banners - PI 24 Innovation (4/23 through 5/13)

### ISSUE THREAD

**Issue by djgarr** [fecgov/fec-cms#6221]
### Summary

**What we're after:**
Routine sprint ticket for banner work each sprint.

[Banner language spreadsheet](https://docs.google.com/spreadsheets/d/1MPGmgOFg-pjlkYZHUl28thVd1IPCQEmsseg7idH5ThU/edit?usp=sharing)
[Banner How to](https://docs.google.com/document/d/1Ehq3sxa6WXzLWf1UdwnbLIsKNTcCnSHIECcPYfWWhC4/edit?usp=sharing)

### Completion criteria

Banners set up for:
- [x] Next Open meeting on 5/1 (goes up 5/1 at 7:30 and down at 5 pm)
- [x] eFiling Maintenance on 4/27 (goes up 4/26 at 5 pm and goes down 4/27 at 5 pm - a little longer due to AWS migration than normal)
- [x] Interim rules on FOIA (update pending rulemaking page on 5/2) - this will need the multiple rulemaking banner when published to stay up through 11:59 pm on 6/1.
- [x] Anything else that comes up (eFiling maintenance, rulemaking or policy comment period, government closure, etc.)
- [x] Banner ticket created for 25.1

**Comment by dorothyyeager** [comment]
Multiple rulemaking banner went up on 5/2 and will go through 6/3 when the FOIA comment period ends. The single rulemaking banner is set to come back on 6/4.

**Comment by dorothyyeager** [comment]
No more banner work expected this sprint.
