### ISSUE TITLE
Design updated footer to include taxpayer statement

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#6222]
### What we're after
We need to add the following statement to our footer. 
 "This information is produced and disseminated at U.S. taxpayer expense."

### Related issues
- https://github.com/fecgov/fec-cms/issues/6098

### Completion criteria
- [x] Designed and approved by @AmyKort

**Comment by JonellaCulmer** [comment]
Here are a couple options for the footer. Let me know if you like either of these or if you have any other suggestions. 
![Screenshot 2024-04-23 at 2 28 44 PM](https://github.com/fecgov/fec-cms/assets/31663028/19f05c59-a8c0-4c9d-818d-d5eb9f80ccf9)

**Comment by AmyKort** [comment]
Thank you @JonellaCulmer ! I think we should go with the second option, where we place the disclaimer on the left side under the seal.
