### ISSUE TITLE
Update FEC system diagram with new eCFR changes

### ISSUE THREAD

**Issue by cnlucas** [fecgov/fec-cms#6234]
### What we're after
We should update our system diagram [here](https://github.com/fecgov/FEC/wiki/2.-FEC-system-diagram) to reflect the recent eCFR changes. Need to be updated after the deploy of the innovation release on May 21. 

Source diagram: @patphongs to add later.

### Related tickets:
- #6167 

### Action items:
- [x] Add as an external service for the CMS

### Completion criteria
- [x] Diagram now includes new eCFR details

**Comment by patphongs** [comment]
This has been completed, wiki updated: https://github.com/fecgov/FEC/wiki/2.-FEC-system-diagram
