### ISSUE TITLE
Design: Improving search results display for enforcement search filters

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#6262]
COMPLETION OF THIS TICKET IS BLOCKED BY TICKET TO RESEARCH HIGHLIGHTS.

### What we're after:
Bring parity between the different legal search systems. Consider the following:

- Filter options
- Column formatting
- Details panel possibilities
- UI fixes
- Tooltip explanatory language

### Completion criteria
- [x] Update designs for related search systems are shared and review with team/PMs

**Comment by JonellaCulmer** [comment]
Followup designs may be needed following usability testing here: https://github.com/fecgov/fec-cms/issues/6361#issuecomment-2313607327
