### ISSUE TITLE
Retiring GA3, Downloads

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#6266]
### Summary

**What we're after:**
What kind of analytics data do we want to export? We have data from two separate accounts (GA4 and DAP) from about July 2023 

### Related issues

_List any relevant related issue(s)_

- #6267 

### Completion criteria

- [x] Create a shared meeting with PMs to discuss IE support and this data
- [x] Decision: which data we want to download from FEC GA3
- [x] Decision: which data we want to download from DAP GA3
- [x] Downloads are complete?
- [ ] Team approvals
   - [ ] Amy
   - [ ] Jonella
   - [x] Pat
   - [ ] Paul
  - [x] Robert

**Comment by rfultz** [comment]
@patphongs @PaulClark2 @JonellaCulmer I'll let one of you decide when the files mentioned in #analytics are complete and that this ticket can be considered complete and closed.

**Comment by patphongs** [comment]
@rfultz The [GA analytics](https://drive.google.com/drive/folders/13RXrRUrqfngKMIa8nM0y4Kkpj2twhF4K):lock: look good to me. I approve, thanks for working on this!

**Comment by PaulClark2** [comment]
I'm sorry I'm a little late to this. The GA analytics look good to me, too. I approve., thanks for working on this.
