### ISSUE TITLE
[Snyk:Medium] django Regular Expression Denial of Service (Due 08/12/2024 )

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-cms#6268]
Regular Expression Denial of Service [ReDoS](https://security.snyk.io/vuln/SNYK-PYTHON-DJANGO-6370660) in django@4.2.10

### Introduced through: 
django@4.2.10

### Remediation:
  Upgrade django@4.2.10 to django@4.2.11

### Completion criteria:
- [ ] Upgrade django to version 4.2.11 and verify snyk cli no longer flags django as vulnerable package

**Comment by fec-jli** [comment]
check logs sprint 25.1 week 1, no this vulnerability any more, so close this one.
