### ISSUE TITLE
[Snyk:Medium] setuptools Regular Expression Denial of Service (Due 08/12/2024 )

### ISSUE THREAD

**Issue by pkfec** [fecgov/fec-cms#6269]
Regular Expression Denial of Service [ReDoS](https://security.snyk.io/vuln/SNYK-PYTHON-SETUPTOOLS-3180412) in setuptools@65.5.0

### Introduced through: 
introduced by gevent@23.9.1 > zope.event@5.0 > setuptools@65.5.0

### Remediation:
  Pin setuptools@65.5.0 to setuptools@65.5.1

### Completion criteria:
- [ ] Pin setuptools to version setuptools@65.5.1 and verify snyk cli no longer flags setuptools as vulnerable package

**Comment by fec-jli** [comment]
Check log Spirnt 25.1 week 1, this vulnerability not exist, so close this.
