### ISSUE TITLE
Inaccurate regulations results count in search across legal resources

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#6282]
### Summary
Small bug with the counts for regulations on the search across legal resources search results.
https://www.fec.gov/data/legal/search/?search_type=regulations&search=105

### Related Tickets
- [ ] #6270 
 
### Screenshots
<img width="1205" alt="Screenshot 2024-06-02 at 10 53 09 PM" src="https://github.com/fecgov/fec-cms/assets/5572856/6ac39fa5-0347-4339-8ce4-d4ba0c4ffbee">

### Completion criteria
- [ ] An accurate count is displayed in search results

**Comment by johnnyporkchops** [comment]
The `api_caller` is still searching the api for regulations and that is where is gets its `results["regulations_returned"]` count that is currently used in the template for this tag.

Our api returns 3 results:  https://api.open.fec.gov/v1/legal/search/?q=105&type=regulations&api_key=DEMO_KEY

The new regulations search using eCFR returns 2: https://www.ecfr.gov/api/search/v1/results?query=105&agency_slugs%5B%5D=federal-election-commission&date=current&per_page=3&page=1&order=relevance&paginate_by=results

--or--
https://www.fec.gov/data/legal/search/regulations/?search=105&search_type=regulations
