### ISSUE TITLE
Improve access to additional legal datasets

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#6289]
### What we're after:
Consider how to elevate access to legal datasets that are not currently keyword searchable, including court cases, policy and other guidance, and audits. 

### Related issues
- #6270 

### Completion criteria
- [x] Designs are mocked up, reviewed and ready for implementation tickets

**Comment by JonellaCulmer** [comment]
@patphongs @AmyKort Here is a mockup of the search results page when searching "across legal resources". I've added section for the other legal datasets that are not keyword searchable. Let me know if there is any legal data missing or if you have any other comments for this work. 

![Image](https://github.com/fecgov/fec-cms/assets/31663028/6aa37228-feb7-4435-bb9c-aeedc326c59d)

**Comment by patphongs** [comment]
@JonellaCulmer I like having the additional box to link to other legal data sets. I approve.

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation issue: https://github.com/fecgov/fec-cms/issues/6384
