### ISSUE TITLE
Update detail panel labels to accommodate ZIP code

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#6293]
### What we're after
For datatable detail panels displaying "City and state" we need up the label to say "City, state and ZIP code"

### Related issues
- [x] #6179 
- [x] #6180 

### Completion criteria
- [ ] Details panel label now correctly shows "City, state and ZIP code"

**Comment by johnnyporkchops** [comment]
The last time we discussed implementing this new pattern, we opted not to.  I don't remember why(maybe to wait for webpack PR?). In case we end up in the same holding pattern again and need to fix the existing details panel in the meantime, this older issue has a conversation on why its happening and possible approaches to fixing it:
https://github.com/fecgov/fec-cms/issues/4913
