### ISSUE TITLE
Update the wording on the national party account data table filter for transaction type

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#6305]
RELATED TICKET: https://github.com/fecgov/fec-cms/issues/6301

### What we're after:
Organize the transaction type filter options on the National Party Account data tables to be more user friendly. Currently, the filters list transaction types that we used to populate the data in the table, those transaction type descriptions aren't consistently worded which makes the list difficult to read.

Instead, format the filter menu to appear like the Receipt Type menu on the[ receipts table](https://www.fec.gov/data/receipts/?data_type=processed&two_year_transaction_period=2024&min_date=01%2F01%2F2023&max_date=12%2F31%2F2024), making use of the headings within the menu: 

![image](https://github.com/fecgov/fec-cms/assets/33758291/1acedaa0-d707-4d6b-85ad-21748a41f4dd)

For the National Party Account menu the headings would be the account names, something like this:

> More
> **Headquarters account**
>    &nbsp;&nbsp;&nbsp;Individual, partnership, limited liability company
>    &nbsp;&nbsp;&nbsp;Earmarked receipt
>    &nbsp;&nbsp;&nbsp;Joint fundraising receipt from individual 
>    &nbsp;&nbsp;&nbsp;Joint fundraising receipt from registered filer
>    &nbsp;&nbsp;&nbsp;Transfer
>    &nbsp;&nbsp;&nbsp;Registered filer
>    &nbsp;&nbsp;&nbsp;Native American tribe
> 
> **Recount account**
>    &nbsp;&nbsp;&nbsp;Individual, partnership, limited liability company
>    &nbsp;&nbsp;&nbsp;Earmarked receipt
>    &nbsp;&nbsp;&nbsp;Joint fundraising receipt from individual 
>    &nbsp;&nbsp;&nbsp;Joint fundraising receipt from registered filer
>    &nbsp;&nbsp;&nbsp;Transfer
>    &nbsp;&nbsp;&nbsp;Registered filer
>    &nbsp;&nbsp;&nbsp;Native American tribe
>
> **Convention account**
>    &nbsp;&nbsp;&nbsp;Individual, partnership, limited liability company
>    &nbsp;&nbsp;&nbsp;Earmarked receipt
>    &nbsp;&nbsp;&nbsp;Joint fundraising receipt from individual 
>    &nbsp;&nbsp;&nbsp;Joint fundraising receipt from registered filer
>    &nbsp;&nbsp;&nbsp;Transfer
>    &nbsp;&nbsp;&nbsp;Registered filer
>    &nbsp;&nbsp;&nbsp;Native American tribe

### Related issues

- #6179
- #6180

**Comment by bmathesonFEC** [comment]
For the disbursements filter:

> More
> **Headquarters account**
>    &nbsp;&nbsp;&nbsp;Disbursement
>    &nbsp;&nbsp;&nbsp;Refund to an individual, partnership or limited liability company
>    &nbsp;&nbsp;&nbsp;Refund to Native American tribe
>    &nbsp;&nbsp;&nbsp;Refund to registered filer
> 
> **Recount account**
>    &nbsp;&nbsp;&nbsp;Disbursement
>    &nbsp;&nbsp;&nbsp;Refund to an individual, partnership or limited liability company
>    &nbsp;&nbsp;&nbsp;Refund to Native American tribe
>    &nbsp;&nbsp;&nbsp;Refund to registered filer
>
> **Convention account**
>    &nbsp;&nbsp;&nbsp;Disbursement
>    &nbsp;&nbsp;&nbsp;Refund to an individual, partnership or limited liability company
>    &nbsp;&nbsp;&nbsp;Refund to Native American tribe
>    &nbsp;&nbsp;&nbsp;Refund to registered filer

**Comment by rfultz** [comment]
This has all been merged
