### ISSUE TITLE
Updates for National Party Account disbursements and receipts datatable

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#6315]
### Summary

Remove transaction code from "National party disbursement type" and "National party account receipt type" dropdown field because it's not data the users need to know.

### Related issues

_List any relevant related issue(s)_

- #6179 

### Completion criteria

- [x] Transaction codes are removed from National party disbursement type dropdown

**Comment by rfultz** [comment]
This is live

![Image](https://github.com/user-attachments/assets/a13bb1e1-abbc-489e-a9b2-9cd68f0f1676)
