### ISSUE TITLE
[Snyk: Med] Improper Handling of Insufficient Permissions or Privileges (Due 08/05/24)

### ISSUE THREAD

**Issue by tmpayton** [fecgov/fec-cms#6320]
Affecting [wagtail](https://security.snyk.io/package/pip/wagtail) package, versions [,6.0.5) [6.1rc1,6.1.2)

How to fix?
Upgrade wagtail to version 6.0.5, 6.1.2 or higher.

Overview
[wagtail](https://wagtail.io/) is an open source content management system built on Django.

Affected versions of this package are vulnerable to Improper Handling of Insufficient Permissions or Privileges in the wagtail.contrib.settings module. An attacker with access to the admin and knowledge of the URL of the edit view for a settings model can modify settings without proper permissions.

Workaround
This vulnerability can be mitigated in ModelViewSet by registering the model as a snippet instead. No workaround is available for wagtail.contrib.settings.

References
[GitHub Commit](https://github.com/wagtail/wagtail/commit/284f75a6f91f7ab18cc304d7d34f33b559ae37b1)

### Completion Criteria 
- [ ] upgrade wagtail to v6.0.5 or higher

**Comment by cnlucas** [comment]
https://github.com/advisories/GHSA-xxfm-vmcf-g33f

Wagtail versions below 6.0 are not affected
