### ISSUE TITLE
Document highlights not displaying for MURs and ADRs in global legal search

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#6334]
### Summary

**What we're after:**
_When using the global legal keyword search, MURs and ADRs are not showing document highlights. This needs to be fixed._

This bug is related to the logic change in the MUR and ADR templates to only show documents when a keyword and/or document type is selected. The global legal keyword search needs to always display document highlights when present.

### Related issues

_List any relevant related issue(s)_

- https://github.com/fecgov/fec-cms/pull/6288

### Completion criteria

- [ ] MURs and ADRs show document highlights in global legal keyword search

**Comment by johnnyporkchops** [comment]
@pat, Is there some way to set the condition to  make the documents show in `legal-search-results.jinja`? This did not work for me, but maybe something along these lines?
```
                        {% with murs = results[category], filters_keyword=query %}
                        {% include 'partials/legal-search-results-mur.jinja' %}
```
