### ISSUE TITLE
[Research] Global legal keyword results display when selecting only a single legal dataset

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#6335]
### Summary

**What we're after:**
_Decide the best path forward for global legal keyword results display when selecting only a single legal dataset to search by._

### Current results displays for one and all:

![Image](https://github.com/fecgov/fec-cms/assets/5572856/abc06487-a28c-485d-8605-2165a245cfa4)

<hr>

![Image](https://github.com/fecgov/fec-cms/assets/5572856/a224edf7-7c84-437f-a85b-5cd9990fb435)

### Related issues

_List any relevant related issue(s)_

- #6270 
- https://github.com/fecgov/fec-cms/pull/6333

### Completion criteria

- [ ] Research is logged in this ticket
- [ ] Decision on best path forward is made and implementation ticket created

**Comment by johnnyporkchops** [comment]
Logging some code here that did not make it into the last PR for this so it does not get lost --

If we decide  to only show the item chosen in the left side nav, we can conditionally show  with:
```
              {% if result_type == category or result_type == 'all' %}
                <li class="side-nav__item">
                    <a class="side-nav__link" href="#results-{{ category|replace('_', '-') }}">
                        {{ category_title }} ({{ results["total_" + category]|default(0) }})
                </a>
                </li>
                {% endif %}

```
And it is probably a good idea in that case, not to render the blank result sections to the page as they are now, so we can move the  existing conditional statement there:
```
 {% if result_type == category or result_type == 'all' %}
          <div id="results-{{ category|replace('_', '-') }}" class="content__section">
          ...
  Move the  {% endif %} all the way down, above the final {% endfor %}
```

**Comment by JonellaCulmer** [comment]
5/6 individuals tested agreed that the menu changing to show a single option met their expectations. 

1/6 believed the menu should remain the same and provide access to the other datasets, if needed. 

Next steps: Consider pathways to allow legal data users to have access at will to each section.
