### ISSUE TITLE
Usability testing for legal query updates

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#6361]
**Blocked by https://github.com/fecgov/fec-cms/issues/6360

### Summary

**What we're after:**
We are making several changes to the way Elasticsearch will handle queries. This will hopefully help with several issues:
- Removal of reserve/stop words from search results
- Removal of stemming from search results
- Exact string matching

So far, in the development environment, we have re-indexed to use the `standard` analyzer. **Important note:** This has only been done for current MURs, since re-indexing archived MURs is very resource intensive. We hope to get cursory feedback about current MURs first before we apply the re-index for archived MURs.

In addition, we would like to switch to using the `simple_query_string` which provides a simpler query syntax, lenient on invalid syntax, and simplifies the query syntax.

### Related issues
- https://github.com/fecgov/fec-cms/issues/6335
- https://github.com/fecgov/openFEC/issues/5830
    - https://github.com/fecgov/openFEC/pull/5886
- https://github.com/fecgov/openFEC/issues/5832
- https://github.com/fecgov/openFEC/issues/5872
    - https://github.com/fecgov/openFEC/pull/5887
    - https://github.com/fecgov/openFEC/issues/5832

### Usability testing steps

- [x] Interview guide is created
- [x] Contact participants
- [x] Conduct and synthesize research
- [x] Document high-level takeaways

### Tech steps or considerations

- [ ] Ensure simple_query_syntax changes are deployed to dev
- [ ] Ensure standard analyzer is applied for current MURs in dev
- [ ] Ensure CMS app is updated with [new bool operators](https://github.com/fecgov/fec-cms/issues/6360) in dev (blocker)
- [ ] [Developer testing notes 🔒](https://docs.google.com/spreadsheets/d/1MCj4r21mMnLr7DGEPw3gaeLMCnAckSLNGREMGJIj_MU/edit?gid=0#gid=0)

### Completion criteria
- [ ] Testing is complete and actionable next steps are documented and discussed

**Comment by JonellaCulmer** [comment]
Takeaways are documented here: 
https://docs.google.com/presentation/d/1yiWLlgnHe1xNGrLUVApRY0EwjYocwXTV6bTHVoVsbOE/edit#slide=id.g2f41793e554_0_25
