### ISSUE TITLE
Global search prepending text

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#6378]
### Summary

The global search seems to have a bug. When you type quoted text into the search box, it prepends "quote" to the search term if you select "search individual contributions," "search other pages" or "search legal resources." 

### Technical considerations:
- See [this comment below](https://github.com/fecgov/fec-cms/issues/6378#issuecomment-2236820082) for cause and possible solution

### How to Reproduce
Type any double quoted text into the global search box.

### Screenshots
![image](https://github.com/user-attachments/assets/8a8858b0-e46c-48c1-80aa-1483eff73024)
![image](https://github.com/user-attachments/assets/4e0e2a68-9c20-42c8-bab2-86a4d8031357)
![image](https://github.com/user-attachments/assets/19757414-f19c-4b58-8144-228b71abc3aa)
![image](https://github.com/user-attachments/assets/5ee9cff0-010f-4276-94e6-d796c9762898)

**Comment by johnnyporkchops** [comment]
It is replacing the ‘&’ and ‘;’ in the entity after doing the quote replacement . It seems to works as expected if  we switch the order of the replacements in  [DOMPurify.sanitize()](https://github.com/fecgov/fec-cms/blob/699fa40c6622667a7dffaa1d91e6781bf19a4858/fec/fec/static/js/modules/helpers.js#L574) like this:
   ```
value = DOMPurify.sanitize(value)
      .replace(validCharactersRegEx, '')
      .replace('"', `&quot;`);
```

**Comment by rfultz** [comment]
This was closed with hotfixes
