### ISSUE TITLE
Add space for downloadable files to Commissioner bio page templates

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#6381]
### What we're after
Modify the Commissioner bio page template to include a link to downloadable files, specifically headshots. 

### Completion criteria
- [x] Design updates completed and moved to an implementation ticket

**Comment by JonellaCulmer** [comment]
@AmyKort @patphongs Here's my initial mock up for the download button for headshots. Let me know what you think. 
![Screenshot 2024-08-28 at 1 19 07 PM](https://github.com/user-attachments/assets/65238e3c-ef4f-4aa6-92d8-3e53028fc92a)

**Comment by AmyKort** [comment]
This looks great to me. Thanks, @JonellaCulmer !

**Comment by patphongs** [comment]
Looks good to me too @JonellaCulmer!

**Comment by JonellaCulmer** [comment]
Closed in favor of implementation ticket: https://github.com/fecgov/fec-cms/issues/6467
