### ISSUE TITLE
Remove Slacker

### ISSUE THREAD

**Issue by tmpayton** [fecgov/fec-cms#6400]
### Summary

We need to replace [slacker](https://github.com/os/slacker) since it has been archived. We should move to the slacker [sdk](https://github.com/slackapi/python-slack-sdk). 

After researching further, it appears that Slacker package was never used in cms repo to send slack notifications. With GitHub Slack integration, slack is sending real time messages to bots# channel. We no longer need Slacker package in cms repo. 

### Actions Items 
- [ ] ~replace slacker with slacker-sdk~
- [x] delete slacker packge
- [ ] ~unpin setuptools~ 
- [x] test with setuptools > 72.1.0
- [x] delete unused slack environment variables for all 3 spaces
        1. FEC_SLACK_CHANNEL: "#fec-dev",
        2. FEC_SLACK_TOKEN": ends with "kISKm"

### Completion Criteria 

- [x] Remove slacker, Git actions performed on cms remo are recevied in slack channel (bots#)
- [x] bump setuptools to 72.1.0 or later

**Comment by pkfec** [comment]
The [invoke task](https://github.com/fecgov/fec-cms/blob/develop/tasks.py#L179-L195) was never used in cms repo. Git and slack integration are sending real-time notifications to slack bots# whenever a pull request is opened/closed or deployed to cloud.gov space.
