### ISSUE TITLE
HotFix - NPA

### ISSUE THREAD

**Issue by rfultz** [fecgov/fec-cms#6429]
### Summary

Remove the "See the financial summary for a breakdown of each type of account" text from national party accounts single pages

### Completion criteria

- [x] That text is gone
- [x] Nothing else on the page has changed

**Comment by pkfec** [comment]
CMS hotfix  [#6430](https://github.com/fecgov/fec-cms/pull/6430) deployed to Production on Aug 14th. Confirmed that the financial summary language no longer shows on the website.
