### ISSUE TITLE
National Party Account disclaimer

### ISSUE THREAD

**Issue by PaulClark2** [fecgov/fec-cms#6433]
### What we're after:
Add disclaimer language to NPA features on raising and spending tabs. 

### Completion criteria
Disclaimer language added to raising and spending tabs. 

### Possible disclaimer language

"Total raised was not a summary total disclosed by the committee. It may include contributions that did not meet the itemization threshold."  [Explanation for this language: To ensure that the user understands the figure is derived by the FEC, not the committee.  Further, the transactions shouldn't be coded if the YTD amount was $200 or less, but there could be exceptions to that rule.]

![image](https://github.com/user-attachments/assets/49de7142-2bb6-4da8-99a8-9165997a381d)
![image](https://github.com/user-attachments/assets/a8b287f7-ee94-4ba5-989f-330775da7e14)

**Comment by JonellaCulmer** [comment]
@PaulClark2 Here are some mockups to add that disclaimer text to the total raised and total spent information. I've added the language in two places to show the differences. Let me know if you have a preference on the location. Also, the language for the total spent may need some tweaking. 



![Image](https://github.com/user-attachments/assets/c1cd5363-28f8-4d41-83cd-06aaee236499)



![Image](https://github.com/user-attachments/assets/02e2b299-e585-44cd-bfb7-23e33bfde61d)

**Comment by PaulClark2** [comment]
@JonellaCulmer this looks good. Let's go with the disclaimer at the bottom. That seems to better follow patterns we use elsewhere on the site.

**Comment by PaulClark2** [comment]
@JonellaCulmer should the spending disclaimer just be, "Total spent is not a summary total disclosed by the committee?"

**Comment by JonellaCulmer** [comment]
@PaulClark2 Thank you. I'll make that text update for total spent and go with the pattern with the text on the bottom.

**Comment by JonellaCulmer** [comment]
Closing in favor of this implementation ticket: https://github.com/fecgov/fec-cms/issues/6540
