### ISSUE TITLE
Update legal search designs based on user research

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#6439]
### What we're after
We conducted user research during the innovation sprint and need to update based on the takeaways. 

### Completion criteria
- [ ] Designs are updated and shared with the team for review

**Comment by JonellaCulmer** [comment]
### MURs

#### Document type filter applied view
![Image](https://github.com/user-attachments/assets/04af28f4-41e2-42d7-a7ba-45a6b6af18a9)

#### Document type and keyword filter applied view
![Image](https://github.com/user-attachments/assets/2c5c86c8-fa9e-4b67-bda6-b9fee3e181fd)

**Comment by JonellaCulmer** [comment]
### ADRs

#### Initial results view, no filters applied
![Image](https://github.com/user-attachments/assets/b934d38f-54d1-4242-a0db-3d6b30468dc3)

#### Document type filter applied view
![Image](https://github.com/user-attachments/assets/ab85a511-9bba-4050-89d2-d2009a967746)

#### Document type and keyword filter view
![Image](https://github.com/user-attachments/assets/aa0bfb60-9a1f-4287-847a-c1074a576af4)

**Comment by JonellaCulmer** [comment]
### Administrative fines

#### Initial result view
![Image](https://github.com/user-attachments/assets/2122aa44-4980-4224-882f-67d08bd91f5b)

#### Keyword search result view
![Image](https://github.com/user-attachments/assets/2b640d06-4b5b-4c7e-bb07-8d23520d6002)

**Comment by JonellaCulmer** [comment]
AOs will be updated in a separate ticket, pending updates following SAOS survey with OGC staff.
