### ISSUE TITLE
AOs with missing date showing incorrect date

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#6448]
### What we're after
AO showing the wrong date. If documents have no date, we need a replacement statement in place of date. 

Example AO with incorrect date: https://www.fec.gov/data/legal/advisory-opinions/1975-110/

### Action items
- [ ] Speak to OGC about dates missing from AOs and if they have a preference for docs without dates
- [ ] Change incorrect dates to `Not dated`
- [ ] Add date function next to the Final opinion button (ao_document_date)
- [ ] Slack convo: https://fecgov.slack.com/archives/C6GFZQX96/p1725546553145049?thread_ts=1725545723.196499&cid=C6GFZQX96

### Completion criteria
- [ ] Date no longer displaying incorrect information and instead showing `Not dated`

**Comment by pkfec** [comment]
I contacted Jennie Boyt and Jason B regarding the document date. Jason updated it to 01/26/1976 using the NextGen AO application, which corrected the date in Postgres and on the website. However, the date still shows 1900 in Oracle.I've reached out to Jennie to update the date in Lawmanager to prevent any data discrepancies.

### Before:
<img width="721" alt="Screenshot 2024-09-11 at 10 32 29 AM" src="https://github.com/user-attachments/assets/e75d959c-e8fc-47c4-a1f6-2b302f0be49e">



### After:

<img width="727" alt="Screenshot 2024-09-11 at 11 51 14 AM" src="https://github.com/user-attachments/assets/4b01c760-cbb8-4c25-ba36-8365d93e38b6">

**Comment by pkfec** [comment]
**64 Final opinions with incorrect date:**


| AO number |
| ------------- | 
| AO 2003-13
AO 1995-35
AO 1995-25
AO 1995-19
AO 1976-17
AO 1975-99
AO 1975-98
AO 1975-95
AO 1975-94
AO 1975-91
AO 1975-85
AO 1975-84
AO 1975-82
AO 1975-70
AO 1975-69
AO 1975-68
AO 1975-66
AO 1975-65
AO 1975-64
AO 1975-63
AO 1975-62
AO 1975-61
AO 1975-57
AO 1975-55
AO 1975-54
AO 1975-53
AO 1975-52
AO 1975-51
AO 1975-50
AO 1975-49
AO 1975-48
AO 1975-47
AO 1975-46
AO 1975-45
AO 1975-44
AO 1975-41
AO 1975-40
AO 1975-39
AO 1975-36
AO 1975-33
AO 1975-32
AO 1975-31
AO 1975-30
AO 1975-29
AO 1975-28
AO 1975-27
AO 1975-26
AO 1975-21
AO 1975-15
AO 1975-14
AO 1975-124
AO 1975-12
AO 1975-11
AO 1975-108
AO 1975-106
AO 1975-105
AO 1975-104
AO 1975-102
AO 1975-100
AO 1975-10
AO 1975-09
AO 1975-08
AO 1975-07
AO 1975-02 |

**Comment by pkfec** [comment]
In the legal project timeline meeting, the team and project managers prioritized updating the dates on AOs with final opinions. However, updating them all at once or individually could overload backend resources and lead to delays when searching for legal documents on the website. I’ll reach out to Shawn to explore a solution for bulk updates after hours, rather than updating individual records.

cc @AmyKort @patphongs

**Comment by pkfec** [comment]
Website team met with Jenny and Jason this morning, and we agreed to use the Issue date for final opinion AOs that were previously marked as not dated on the website. The progress of updating the issue date is tracked in  https://github.com/fecgov/fec-cms/issues/6487.  Other document types without dates will continue to be labeled as not dated (this policy remains unchanged).
