### ISSUE TITLE
Template change - H4CC Draft Coordinated Party Expenditures 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#6452]
### Summary

**What we're after:**
To better serve the regulated community we want to make it easier to navigate information on our web pages. 

### Related issues

_List any relevant related issue(s)_

- #6237 

### Completion criteria

We want to keep the URL for this page, so we need front-end to change the template code from a custom template to a resource template.  Will need to remove the word "Draft" from the title. 

The page URL is https://www.fec.gov/help-candidates-and-committees/making-disbursements-political-party/coordinated-party-expenditures/

The draft is posted in Slack in the Content channel for the resource page for reference if needed. 

Once completed Content will delete the custom page.

**Comment by JonellaCulmer** [comment]
The work is done, so closing.
