### ISSUE TITLE
Design: Provide explanation to limited keyword matches being returned

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#6454]
### What we're after
When conducting a document keyword search, searches are returned with a maximum number of 6 keyword matches. We need to consider how we might explain the limit to users and make it clearer about how results are being returned. 

### Completion criteria
- [x] Designs are created and reviewed by stakeholders, followup tickets are opened

### Future work
- Add relevancy to sort the more relevant results first, since not all keyword matches will be returned.

**Comment by JonellaCulmer** [comment]
@patphongs @AmyKort Proposal for explaining the maximum number of results being returned. Let me know if you have any comments or edits. If we're sure we want to make this change we can combine with Pat's [ticket in progress](https://github.com/fecgov/fec-cms/issues/6466). 


![Image](https://github.com/user-attachments/assets/18e46a07-29d4-4867-90c6-a13398f1d24d)

**Comment by AmyKort** [comment]
That looks good to me. Thank you @JonellaCulmer !

**Comment by patphongs** [comment]
Looks good to me as well @JonellaCulmer, I will add it to my [PR](https://github.com/fecgov/fec-cms/pull/6485#event-14399361466).

**Comment by patphongs** [comment]
@JonellaCulmer A suggestion for the future: When there's more than 5-6 matches, there is a possibility that more matches are found in a document. Do you want the results display to also tell the user that more results may be there in the document when we have 5 or greater hits for a document? It's not guaranteed that there's more, but it's probably a good indication if they've broached the max hits per document.

I was thinking some kind of notification near the MUR highlights or within the accordion of more matches that says "Showing top 5 results. There may be additional matches within the document." Thoughts?

**Comment by JonellaCulmer** [comment]
@patphongs I like the idea of displaying top results, when we have them prioritized by relevancy. I think that could be really helpful.
