### ISSUE TITLE
Legal resources "more keyword options" modal and related tooltip for keyword search is updated

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#6455]
### What we're after:**
Update the layout of the "More keyword options" modal to better clarity with search options. Tooltip language, which is related to the function of the keyword search box, can also be edited along with this work. 

### Completion criteria
- [ ] Modal layout is updated
- [ ] Tooltip language is written and approved

**Comment by JonellaCulmer** [comment]
@patphongs Draft language for tooltip:
`Refine a keyword search by using + (and), | (or), " " (exact phrase), - (but not), to expand or limit results.`

Here are two layout options for the "More keyword options" modal. 
I'm leaning towards option 1 because on smaller widths it's going to stack anyway. But I'm concerned about the spacing for a future state with validation. 

<img width="292" alt="Screenshot 2024-08-27 at 5 18 13 PM" src="https://github.com/user-attachments/assets/223fd9e8-69ec-4917-bca8-312c4fee6ddc">
<img width="445" alt="Screenshot 2024-08-27 at 5 19 03 PM" src="https://github.com/user-attachments/assets/b419568a-d2f2-4864-9ee1-56f6c3b30fd9">

With validation:
<img width="584" alt="Screenshot 2024-08-27 at 5 20 53 PM" src="https://github.com/user-attachments/assets/9523045f-6be1-41e0-90df-871e255c3532">

**Comment by patphongs** [comment]
Thanks @JonellaCulmer, I like option where the input boxes stack as well. What do you think about retaining the width when stacked?

<img width="905" alt="Screenshot 2024-08-29 at 10 47 06 AM" src="https://github.com/user-attachments/assets/0bff06d8-302b-44c0-8abe-5ee7e526316b">

**Comment by JonellaCulmer** [comment]
@patphongs No objections to keep that width. The field's width should suggest what the boxes will accept. So if there is a character limit the boxes should match that. For example, a telephone number text field would be much smaller since it doesn't require that many characters. 

If you don't think that's an issue here, I don't object. Since we don't have a firm plan for other boolean operators this may have to change again, but that's less of a concern.

**Comment by patphongs** [comment]
> No objections to keep that width. The field's width should suggest what the boxes will accept. So if there is a character limit the boxes should match that.

Ok thanks @JonellaCulmer, let's go with something like that then. Yes no char limit on the boxes, so they can type as much as they want. If we start to make refinements to allow exact string with `and` and `or` boolean options, these input boxes may grow.

**Comment by JonellaCulmer** [comment]
Closing this ticket in favor of: 

- Remove symbols from "more keyword options" box on legal searches
