### ISSUE TITLE
Remove symbols from "more keyword options" box and update keyword search tooltip on legal searches

### ISSUE THREAD

**Issue by JonellaCulmer** [fecgov/fec-cms#6466]
### What we're after
To reduce confusion with the use of symbols in the additional boolean search boxes, we're going to remove the symbols entirely and rely on their placement in the keyword search tooltip. We also need to update the tooltip language everywhere symbols are used. 

Updated tooltip language:
`Refine a keyword search by using + (and), | (or), " " (exact phrase), - (but not), to expand or limit results.`

Places to remove:
- Search across legal resources
- Advisory opinions
- MURs
- ADRs
- AFs

### Completion criteria
- [ ] Symbols no longer appear in legal search system "more keyword options"
- [ ] Tooltips are updated with new text

### Mockup
<img width="905" alt="Screenshot 2024-08-29 at 10 47 06 AM" src="https://github.com/user-attachments/assets/0bff06d8-302b-44c0-8abe-5ee7e526316b">

**Comment by patphongs** [comment]
@JonellaCulmer The text in the box says "Use these search boxes to refine your search. Only letters, numbers, and spaces are accepted". But we also accept hyphenated words like "in-kind" and "multi-candidate" as well. Should the phrase be "Only words with letters, numbers, spaces, and hyphens are accepted"?

**Comment by JonellaCulmer** [comment]
@patphongs Yes, generally I'd say so. And it looks like we need a comma in there after letters. Should we provide an example in parens, ex. `(such as in-kind)`?
