### ISSUE TITLE
Decide how to handle case subjects for archived MURs

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#6478]
### Summary

**What we're after:**
_It has been [decided](https://github.com/fecgov/openFEC/issues/5965#issuecomment-2359368685) that we will not include filtering for case subjects in Archived MURs._

As part of this decision, we should:
1) Determine if we should exclude subjects entirely from archived MURs since the data will not be filterable and it can be messy.
- We've decided to keep subjects because arch MURs do not have easily readable documents, therefore keeping the subjects will aid in understanding the substance of the arch MUR. 
2) Help users understand that MUR case subjects are only filterable for current MURs only 
mur_dispositions filter is just current cases as well
- Need to determine how to relate this to the user (tooltip?) 

### Completion criteria

- [x] We've determined how to let users know that case subjects are only filterable for current MURs
- [x] Mockup designs have been created

**Comment by JonellaCulmer** [comment]
@patphongs @AmyKort Please see the attached mockups for notifying legal users that final disposition and subject cannot be searched for archived cases. 

### Before:
![Image](https://github.com/user-attachments/assets/46a4fa6e-b24a-4a20-a6f7-7e290ba3cd8a)

### After: 
![Image](https://github.com/user-attachments/assets/da7693cc-f17f-403d-a46e-0a3eb8428912)

### New tooltips for final disposition and subject
![Image](https://github.com/user-attachments/assets/e970754f-1609-413e-ab11-97623bae25bb)

**Comment by AmyKort** [comment]
Looks good @JonellaCulmer! Do you think we should try to define Archived cases? Something like, "which generally include cases closed prior to 2000"?

**Comment by JonellaCulmer** [comment]
@AmyKort Thanks for your review. Here are my text suggestions. I'm trying to bring as much brevity as possible. We've never seemed to explain what archived means until now. 

- Case details preview not available for archived cases (generally closed before 2000)
- Final disposition does not search archived cases (generally closed before 2000)
- Case subject does not search archived cases (generally closed before 2000)

**Comment by AmyKort** [comment]
Thanks @JonellaCulmer I think this looks good. But, you make a really good point about the length of this notice, which is something I wasn't thinking enough about. Do you think we'd be better off going with your first proposal and adding a definition/explanation of "archived MUR" to the "guide to legal searches" we plan to make? That might give us more opportunity to explain what we mean by "archived" MURs.

**Comment by JonellaCulmer** [comment]
@AmyKort That works for me. I'll move forward with my original proposal. Thanks, Amy.

But as a follow-up, and after thinking through what it means to be archived, there should still be a pathway to that page from these datatables. I can create a separate design ticket to consider how/where we might add that language.

**Comment by JonellaCulmer** [comment]
May as well add "and documents to the "...preview not available.." language. 

Updated language and mockup: 
"Case details and documents preview not available for archived cases"
![Screenshot 2024-09-26 at 10 41 12 AM](https://github.com/user-attachments/assets/86b9c437-d1da-4e9e-8e72-d097c0a4e378)

**Comment by patphongs** [comment]
@JonellaCulmer @AmyKort We discussed and confirmed that the document type and document date filers are only available for current MURs. Therefore we will add a similar tooltip for document type and document date as well. As for MUR respondents, we have determined that there are respondents for archived cases and we can add that capability, a new ticket has been created to do this https://github.com/fecgov/openFEC/issues/6019.

**Comment by JonellaCulmer** [comment]
Closing in favor of implementation tickets: 
[Add case subject tooltip and new result language for archived MURs #6503](https://github.com/fecgov/fec-cms/issues/6503)
[Add tooltip to final disposition filter for mur search #6504](https://github.com/fecgov/fec-cms/issues/6504)
