### ISSUE TITLE
Add filter by final disposition for MUR search only

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#6499]
### Summary

**What we're after:**
A multi-select checkbox dropdown list of MUR dispositions is integrated into the MUR search feature. The list of dispositions is hardcoded in the CMS based on this [disposition category list mapping](https://github.com/user-attachments/files/17103760/mur_disposition_category_list.csv).

The filter applies the condition `mur_disposition_category_id` to refine search results.

### Related issues

_List any relevant related issue(s)_

- https://github.com/fecgov/openFEC/issues/5966
- https://github.com/fecgov/openFEC/pull/5988

### Completion criteria

_What does the end state look like? Include any behavior, appearance, etc required for this ticket to be 'complete.'_

### Design

![Image](https://github.com/user-attachments/assets/52161e95-c392-43fc-aa33-030e1f7111df)

**Comment by johnnyporkchops** [comment]
@JonellaCulmer Do I need to spelll out the acronyms in this list like you have done for the suggested checkboxes in the mockup above
[disposition category list mapping](https://github.com/user-attachments/files/17103760/mur_disposition_category_list.csv).
