### ISSUE TITLE
Draft updates to H4CC pages for new candidate and officeholder use of campaign funds for security (effective Jan 1, 2025)

### ISSUE THREAD

**Issue by kathycarothers** [fecgov/fec-cms#6521]
### Summary

**What we're after:**
As a candidate or officeholder who wants to use campaign funds for security, I need to know about the new rules taking effect on 1/1/2025.

Content team will need to update appropriate H4CC pages with any changes/updates coming out of new candidate and officeholder security rules published on 9/25/24 and effective 1/1/2025.

### Related issues

_List any relevant related issue(s)_

- #6077 

### Completion criteria

- [x] Pages that will need to be updated:
https://www.fec.gov/help-candidates-and-committees/making-disbursements/
https://www.fec.gov/help-candidates-and-committees/making-disbursements/personal-use/
- [x] Create a new child page off https://www.fec.gov/help-candidates-and-committees/making-disbursements/personal-use/ and include an internal button to this new page
- [x] Drafts of wording to be done in Word document 
- [x] Submit the draft(s) to OGC Policy for review (Bob, Luis, Joseph, and Neven) 
- [x] Update Wagtail pages and submit for second pair of eyes to content team 
- [x] Ready to publish on or after 1/1/2025

### Future work

Publish changes after 1/1/25 (#6602)

**Comment by prstoetzer** [comment]
Drafting of the pages complete, awaiting review from OGC and final publication after the regs are effective on 1/1.
