### ISSUE TITLE
The number 4 looks weird in banners

### ISSUE THREAD

**Issue by dorothyyeager** [fecgov/fec-cms#6551]
### Summary

**What we're after:**
_As a user, I need to see the number 4 in a banner if it's in a date or time._

### Completion criteria

The number 4 looks like it's the same size as the other numbers in a banner.

### Tech steps or considerations (optional)

Right now, the number 4 looks smaller than the other numbers. I had to blow up the view to make sure it was right.

![Image](https://github.com/user-attachments/assets/f40ccf3d-33f3-416b-9251-a3c4cae2d9ac)

**Comment by dorothyyeager** [comment]
Thanks @rfultz for looking into this! I was using Chrome on Windows computer at 90% zoom.

**Comment by rfultz** [comment]
> Thanks [@rfultz](https://github.com/rfultz) for looking into this! I was using Chrome on Windows computer at 90% zoom.

@dorothyyeager is this still an issue at 100%?

**Comment by dorothyyeager** [comment]
I think so... this is the screenshot at 100% zoom on Chrome. The 4 is still a little shorter. It gets a little better as you increase the zoom and looks fine when you go up to 150%. It's not the highest priority thing though.

![Image](https://github.com/user-attachments/assets/e989ae15-7e6f-4464-96b0-28c95ed52059)

**Comment by rfultz** [comment]
Seems to be fine on Windows at 0 zoom / 100%. If this comes up again, we may need to swap fonts, change font size… something
