### ISSUE TITLE
AO keyword search is not finding results

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#6558]
### Summary
I am attempting to search Advisory Opinions by keyword and I'm getting no results. When I search by keyword from the Advisory Opinion landing page (https://www.fec.gov/data/legal/advisory-opinions/) or the Advisory Opinions search page (https://www.fec.gov/data/legal/search/advisory-opinions/) I get no results.

### Frequency
Just noticed right before reporting this issue. Not sure when it started.

### Device, browser, etc
Firefox browser

### Screenshots
![Image](https://github.com/user-attachments/assets/919c0837-1db7-4fb5-930b-c837c774817a)

### Work around:

Worth noting that searching: _spending_ gets no results and _(spending)_ gets no results. However, I am able to get results if I click "More Keyword Options" and make my search from that page:

![Image](https://github.com/user-attachments/assets/7905abeb-1906-4cb3-ad97-afe493fbc0ef)

**Comment by rfultz** [comment]
Closing because its PR has been merged
