### ISSUE TITLE
AO search links to related AOs have a broken URL

### ISSUE THREAD

**Issue by bmathesonFEC** [fecgov/fec-cms#6559]
### Summary
Links to related AOs are broken on the AO search page. When viewing a list of AOs on the AOs search there is a column named "This opinion is cited by these later opinions" that links to other Advisory Opinions. When I click on those AO links I get a 404 Page Not Found error.

Example URL I get when I click the link: https://www.fec.gov/data/legal/search/advisory-opinions/1975-144/ however, when I remove "/search" from that URL I'm delivered the page I was trying to get to:  https://www.fec.gov/data/legal/advisory-opinions/1975-144/

### Frequency
Just noticed right before reporting this issue. Not sure when it started.

### Device, browser, etc
Firefox browser

### Screenshots
![Image](https://github.com/user-attachments/assets/1acea70d-eb1b-44f8-8bac-e3d2845d0229)

![Image](https://github.com/user-attachments/assets/a8dd7c34-6d68-4765-84e8-7f45547a22c9)

### Work around: 
Remove "/search" from the url:
![Image](https://github.com/user-attachments/assets/bf4d9795-9138-48eb-9312-1c09d65a37e6)

**Comment by rfultz** [comment]
Closing because its PR has been merged
