### ISSUE TITLE
[BUG] CMS AO search module search not working

### ISSUE THREAD

**Issue by patphongs** [fecgov/fec-cms#6599]
### Summary

The AO search module is not working on the [Advisory opinions landing page](https://www.fec.gov/data/legal/advisory-opinions/).

- Search by keyword text field returns no results WITH or WITHOUT query parameters passed
- AO number returns no results WITHOUT query parameters passed. If you insert an AO number, it works ok.

### Frequency

This is an ongoing bug that was just discovered

### How to Reproduce

1. Go to the [Advisory opinions landing page](https://www.fec.gov/data/legal/advisory-opinions/)
1. Submit a query in the Search advisory opinions search box without passing any parameters by clicking on the magnifying glass. No results show up in the search.
2. Submit a query using search parameters into the Search by keyword text field. No results show up in the search. The AO number text field works with query parameters as expected.

### Device, browser, etc

All devices

### Screenshots

<img width="999" alt="Image" src="https://github.com/user-attachments/assets/8b3c379b-db04-4dd2-90b0-b45133d9957c" />

<img width="1208" alt="Image" src="https://github.com/user-attachments/assets/5f70e1f6-944f-448f-8719-a97f19dbdb42" />

**Comment by rfultz** [comment]
After debugging this, @tmpayton is looking into it for an API fix

**Comment by patphongs** [comment]
This has been fixed by a PR in the API: https://github.com/fecgov/openFEC/pull/6082, thanks @tmpayton !
